### ISSUE TITLE
[5G-SA-Regression] TC2 and TC9 failing in daily regression on TVM setup.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#10002]
Below testcases are failing in daily regression which runs on 141 server.
  TC2 - SA_TC2_UE_Initiated_PDU_Session_Establishment_with_traffic_test
  TC9 - SA_TC9_AMF_Initiated_Paging

But these testcases are passing on 140 server when we execute manually.
While debugging we observed that flag "periodic_stats_reporting" is not configured properly in default configuration file /etc/magma/pipelined.yml. This flag is mentioned as individual parameter, but it should be nested flag under "enforcement" as shown in the attached image.

Could you please set the "periodic_stats_reporting" flag as mentioned in attached image. Also it should be updated in overridden configuration file "/var/opt/magma/configs/pipelined.yml".![periodic_stats_reporting.png](https://images.zenhubusercontent.com/60ff6822051e9582447f32aa/d5ef4b11-542b-449a-8c16-039a014e93fa)

**Comment by arun-magma** [comment]
TC-2 and TC-9 issues are bit different.
TC9 – Control plane paging flows are good; TC fails as Downlink packets received during UE idle state are all dropped by AGW.

**Comment by arun-magma** [comment]
TC-9 Pcaps Enclosed: After UE context release ~between Frame 341 to 438 has UDP DL pkts , there is no corresponding GTP pkts towards UE.
[https://app.zenhub.com/files/170803235/4a7f3a9d-d2e8-420e-8929-e6fccf301fd9/download](https://app.zenhub.com/files/170803235/4a7f3a9d-d2e8-420e-8929-e6fccf301fd9/download)

**Comment by arun-magma** [comment]
@NeelimaKalpana : Another issue in TC-9 related to GTP DL not going during idle mode

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Regarding TC2 it is passing in our local setup. We are not having any extra configurations for making that testcase pass.
just we have to have APN/DNN match between UE and AMF-Subscriberdb.

TC9 - I will analyze and get back to you.

**Comment by arun-magma** [comment]
TVM side issue in TC-2 is packets are being lost in uplink. 
[TVM traffic verification b/w UE sent and AS received, there are close to 75k bytes are lost for the 100k sent ]
_verification fail:  ((as_received_raw_bytes=25000) 			>= (ue_sent_total_bytes=100000)-((ue_sent_total_bytes=100000)*0.01))  => False_
Does your local setup do check the counts of pkts sent by UE and pkts received beyond N6 ?

For TC-2 the last run had this config set as indicated in above,
![Screen Shot 2021-11-16 at 1.07.26 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/25249db2-43c4-404e-a523-c25eef183896)

**Comment by NeelimaKalpana** [comment]
Hi Arun,

W.r.t TC9 - When UE is in Idle mode that is expected that DL-Traffic drop will happen until UE is moving to Active mode when paging is happening for a session. Kindly try sending traffic after UE moving to Active mode with Paging request.

**Comment by NeelimaKalpana** [comment]
Hi Arun, 

Can we have a sync-up call so we can debug together and check for the Issue for both TC2 and TC9.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Regarding the TC2 test case , I was analyzing the ovs-table 0 to check the received and transmitted data. I can see we are receiving 99 packets and forwarding   all packets received. there is no drop from AGW side.
Please find the screenshot for the same.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/ee112553-064b-4fff-ac64-eefeeb9ae1b3)


TeraVM Screenshot for the same statistics.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/eef52b84-398f-4291-828a-b98022df1cca)

**Comment by arun-magma** [comment]
Hi Neelima, Both TC-2 and TC-9 looks good with no pkt losses in today's run, we may close this ticket.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Great.
I just want to understand about how it is passing now, is there any config mismatch or anything got changed in the TC steps.

Please let me know either I will close it your going close the ticket.

**Comment by arun-magma** [comment]
This config addition must be fixing the issues, No changes are done in scripts as you can check by compare the pcaps.

![Screen Shot 2021-11-16 at 1.07.26 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/b22b8b3f-b0a5-4fe1-9db1-8916ef76ec1b)

**Comment by NeelimaKalpana** [comment]
Hi Arun,
Okay. Thank you.
We can see the consistence for 3 days and we can close this issue right.

**Comment by arun-magma** [comment]
Sure, Thanks!

**Comment by arun-magma** [comment]
Hi Neelima and Wlabs Team:  We see no Response for PDU establishment in some instances , 
sys logs are showing dup request, are we planning to handle this message with a valid error response in this case, kindly look into it.
If needed lets open a separate ticket for this issue.

![Screen Shot 2021-11-22 at 11.35.16 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/8e6f856c-7a70-486f-96c0-cf7bc09a2c7b)

[https://app.zenhub.com/files/170803235/a65eff77-b980-46af-8ee3-f26489993e2f/download](https://app.zenhub.com/files/170803235/a65eff77-b980-46af-8ee3-f26489993e2f/download)

![Screen Shot 2021-11-22 at 11.30.12 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/5da075d6-2125-42f7-a884-62bb4e3e8f9d)

**Comment by NeelimaKalpana** [comment]
Hi Arun, 
 I raised a bug for this and team is working to fix this issue.

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10455

**Comment by arun-magma** [comment]
As #10455 is tracking the no PDU Response issues we May close this issue.
