### ISSUE TITLE
TC43b: Verify Authentication Reject with "Cause #21 – Synch failure"

### ISSUE THREAD

**Issue by Kaleem-Wavelabs** [magma/magma#10005]
@arun-magma As discussed last time, can you check the re-sync scenario TC and update TC43b accordingly and let us know the result.

**Comment by arun-magma** [comment]
Kindly clarify once again, this Cause-21 is expected in first Auth Request & response or during Auth Response for Resync, if possible please add the full flow in few steps.

**Comment by Kaleem-Wavelabs** [comment]
@arun-magma 
1) Please trigger re-sync scenario with first authentication response as failure from UE with cause as "21"
2) In this case, AGW will start the authentication procedure again
3) Ensure re-sync authentication scenario also gets failed with cause as "21" again
4) Now AGW triggers Authentication Reject message to UE

**Comment by arun-magma** [comment]
@Kaleem-Wavelabs : This Script goes bit tricky as it needs Cause-21 in both the Auth Req, Working on below flow & will get ready by sometime next week. New test case TC18g added to cover this scenario.

[Flow to be Scripted]
Authentication Request
Authentication Failure (cause -21: Sync Failure)
[Resync trigger] Authentication Request
Authentication Failure (cause -21: Sync Failure)
Authentication Reject (?)

**Comment by arun-magma** [comment]
TC 18g scripts are ready to validate
Enclosing Sample Traces tested with TVM SA Core.
[https://app.zenhub.com/files/170803235/9588f4cd-73c0-4abd-b820-7a818c2e428c/download](https://app.zenhub.com/files/170803235/9588f4cd-73c0-4abd-b820-7a818c2e428c/download)

**Comment by Kaleem-Wavelabs** [comment]
Thanks Arun, now the test case is pass through with additional changes to script.
Let's pass through this in regression for TC43b, and we can close this issue.

**Comment by arun-magma** [comment]
TC18g would cover TC43b hence proposed to remove TC43b from regression
