### ISSUE TITLE
[1.6.1][MME] debug log shows incorrect number of connected eNBs

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#10019]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6.1
- **Affected Component:** AGW
- **Affected Subcomponent:** MME
- **Deployment Environment:** AWS (orc8r), Bare metal AGW

### Describe the Issue

In the private campus network,  when we looked at the debug MME logs, we noticed that the # of active eNBs was showing up as a uint32 max value (or something really close to it). 

The only thing notable in this network is that we setup one eNB to constantly fail s1setup in order to trigger an alert in the NMS. 

```
root@fre-agw7:~# tail -f /var/log/mme.log

010643 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0044                   |   Current Status|
010644 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0045    Attached UEs   |          4      |
010645 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0048    Connected UEs  |          4      |
010646 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0051    Connected eNBs | 4294967016      |
010647 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0054    Default Bearers|          4      |
010648 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0057    S1-U Bearers   |          3      |

010649 Tue Nov 02 03:57:11 2021 7FD9220F4700 DEBUG SERVIC tasks/service303/service303_mme_:0061    ======================================= STATISTICS ============================================
```

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ulaskozat** [comment]
@ardzoht can you add this to the BE tracker?
