### ISSUE TITLE
mongo-driver update needed

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#10017]
There is an issue with go.mongodb.org/mongo-driver used. The issue severity is moderate. It affects four components. The overall ROI on this work is high.

The proposed fix is to upgrade to v1.5.1 or later. For example:
`require go.mongodb.org/mongo-driver v1.5.1`

More information: https://github.com/magma/magma/security/dependabot/wifi/cloud/go/go.sum/go.mongodb.org%2Fmongo-driver/open

**Comment by nikolakn** [comment]
After updating   go-swagger from 0.21.0 to  go-swagger 0.26.0
getting errors in test 
✖  tools/swaggergen/generate (50ms)
✖  services/state/indexer (268ms)
✖  services/state/indexer/reindex (6.136s)
