### ISSUE TITLE
[CI] Can't update orc8r with the latest version using CI-artifact channel reference

### ISSUE THREAD

**Issue by uri200** [magma/magma#10012]
After merging my PR #9992 which modifies orc8r, we are unable to see the artifact message on `ci-artifacts` channel. That prevents us to follow update path for staging or even for future teravm automated deployments. 

Shouldn't the PR and [this](https://magmacore.slack.com/archives/C01RGBRKGRJ/p1635789907038800) trigger an Orc8r artifact generation.  Note that for NMS we do see a message indicating us the Artifact name [here](https://magmacore.slack.com/archives/C01RGBRKGRJ/p1635792113039500)

![image](https://user-images.githubusercontent.com/16157139/139749531-a27a91eb-8454-430e-a605-e97a3be08979.png)

Note when running the script we get this below. So not sure if the image is missing or the script is worng

```
╰─ fab staging deploy:404804
Promoting controller...

Fatal error: Error promoting docker image on Jfrog: Received response status code: 404

Aborting.

Fatal error: Image promotion failed

Aborting.
```

**Comment by uri200** [comment]
This is how it shows up for NMS (note we can see the hash that has been published so oncall knows what version to apply)

![image](https://user-images.githubusercontent.com/16157139/139750523-c1aed167-c5bc-4aa4-9de0-0a7c1857cc19.png)

**Comment by tmdzk** [comment]
If I recall correctly the fab script is pointing to the old non public registry. (facebookconnectivity.jfrog.io)
Someone need to change the oncall scripts to point to the new open source one

**Comment by uri200** [comment]
Hey @tmdzk , the fab moves an artifact from ci into production/staging folder on the repo. But those folders do not exist on coremagma  artfactory.  Is it possible to create a similar structure?

```
    'staging': DeployConfig(
        from_reg='orc8r-ci-docker',
        to_reg='orc8r-staging-docker',
    ),
    'production': DeployConfig(
        from_reg='orc8r-staging-docker',
        to_reg='orc8r-prod-docker',
    ),
```
As you showed me ^^^ this is where we actually move images from -> to 



Also note the script uses a JFROG key to be able to move objects from one place to another. That key is in lastpass. Do you know if we  have  access to magmacore JFROG key?

**Comment by uri200** [comment]
Btw, i removed the promotion step from the script but still did not work

```
elm_release.orc8r: Still modifying... [id=orc8r, 5m10s elapsed]
helm_release.feg-orc8r[0]: Still modifying... [id=feg, 5m20s elapsed]
helm_release.fbinternal-orc8r[0]: Still modifying... [id=fbinternal, 5m10s elapsed]
helm_release.lte-orc8r[0]: Still modifying... [id=lte, 5m20s elapsed]
helm_release.cwf-orc8r[0]: Still modifying... [id=cwf, 5m21s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 5m20s elapsed]
helm_release.feg-orc8r[0]: Still modifying... [id=feg, 5m30s elapsed]
helm_release.fbinternal-orc8r[0]: Still modifying... [id=fbinternal, 5m20s elapsed]
helm_release.lte-orc8r[0]: Still modifying... [id=lte, 5m30s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 5m30s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 5m40s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 5m50s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 6m0s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 6m10s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 6m20s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 6m30s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 6m40s elapsed]
helm_release.orc8r: Still modifying... [id=orc8r, 6m50s elapsed]
╷
│ Error: timed out waiting for the condition
│
│   with helm_release.orc8r,
│   on orc8r.tf line 10, in resource "helm_release" "orc8r":
│   10: resource "helm_release" "orc8r" {
│
╵
╷
│ Error: timed out waiting for the condition
│
│   with helm_release.cwf-orc8r[0],
│   on orc8r.tf line 37, in resource "helm_release" "cwf-orc8r":
│   37: resource "helm_release" "cwf-orc8r" {
│
╵
╷


....


Releasing state lock. This may take a few moments...

Fatal error: local() encountered an error (return code 1) while executing 'terraform apply -var orc8r_tag=404804'

Aborting.
[localhost] local: rm -f tf/deploy_staging.kube

```

**Comment by uri200** [comment]
@hcgatewood  I think you mentioned there is an alternative to manually push an specific image to the old . This would unlock temporarily the update of staging using the current fab script

Can you share the steps?  For feg i normally build feg and use `orc8r/tools/docker/publish.sh` script to publish my image  to the old repo. 

```
publish.sh  -r facebookconnectivity-feg-docker.jfrog.io -i gateway_python -u magmaci-bot -p ~/.magma/secrets/jfrog_apikey -v 5d6fa06 &&
```

Can we use the same script for orc8r? Can you please share the command you use to do so?

**Comment by hcgatewood** [comment]
@uri200 check in the `fb/cloud/helm/tf` for which artifactories are being targeted, as a sanity check

If it is indeed targeting the old jfrog repo -- @quentinDERORY would probably know how to use that `publish.sh` script. The old way of doing it was creating the charts locally then doing a "jfrog upload" via the jfrog cli

**Comment by uri200** [comment]
@tmdzk  can we keep publishing the images on the old repo at https://facebookconnectivity.jfrog.io/  until new staging is up and running?

That will allow us to keep using the same scripts without us wasting time on a process that is going away in few weeks

**Comment by uri200** [comment]
Ok it seems the problem is simpler than it seems:   the tag published on ci-artifact channel is wrong for some components since it is just 6 digits (it should be 8)

So the solution is to publish the 8 digits of the hash on the slack ci-artifact channel


[Good Hash](https://magmacore.slack.com/archives/C01RGBRKGRJ/p1635969965066900)
![image](https://user-images.githubusercontent.com/16157139/140186401-83477a2e-fd8f-4f46-85c4-2f41ff511f55.png)


[Bad hash](https://magmacore.slack.com/archives/C01RGBRKGRJ/p1635970373067000) 
![image](https://user-images.githubusercontent.com/16157139/140186377-32721506-a1ca-4d3e-b70c-a9a314b39414.png)
