### ISSUE TITLE
TeraVM scripts to validate PDUSessionEstablishment Rejecting Scenarios

### ISSUE THREAD

**Issue by ganeshg87** [magma/magma#10021]
Regression should have support below TeraVM scripts to validate PDUSessionEstablishment Failures

Handled below Failure Cases:
---------------------------
Cause #27 – Missing or unknown DNN
This 5GSM cause is used by the network to indicate that the requested service was rejected by the external DN
because the DNN was not included although required or if the DNN could not be resolved.

Cause #28 – Unknown PDU session type
This 5GSM cause is used by the network to indicate that the requested service was rejected by the external DN
because the requested PDU session type could not be recognized or is not allowed.

Cause #43 –Invalid PDU session identity
Usecase: If AMF receives a new PDU Session Establishment Request and 
         AMF has already another active PDU Session in progress with the Same PDU Session IDentity,
		 AMF will not process PDUSession Establishment requests for 5 times, after that AMF rejects with reason #43.

**Comment by arun-magma** [comment]
Scripting in progress.
QQ:  In Cause 43 we see a PDU Est Request for 5 Times, Should we need to wait for PDU Reject on 5th attempt ? , don't we get this rejecttion(Perm error) in first attempt itself ? , Anyways scripts would go for retries of 1+4 times if there is a no response on pdu_est_requests.

**Comment by NeelimaKalpana** [comment]
Hi Arun&Ankur,

As part of Rejections, just added 2 more cases which are required. Kindly please do the needful.

Scenario1:  Missing or unknown DNN and try to correct the DNN name while PDU-Session retry is happenning.
Step1: Try to send the the PDU-Request with no DNN-Name in the IE.
Step2: Add a subscriber with different apn name in
Step3:Try to Trigger the PDU-Session
Step4: PDU session should not come up successfully,PDU-Reject(Cause:27) should be sent.
Step5:Try to send proper apn/dnn when session retry is happening.
Step6: PDU-Session should come up successfully.

Scenario2:   Unknown PDU session type(PDU-Session Types :IPv4, IPv6 ,IPv4v6 , unstructured, EThernet.)
Step1: Try to send the the PDU-Request with PDU-Session type as unstructured/Ethernet
Step2: Try to Trigger the PDU-Session
Step3: PDU session should not come up successfully,PDU-Reject(Cause:28) should be sent.
Step4: Try to send the the PDU-Request with PDU-Session type as IPv4, before maximum retries will expire.
Step5: PDU session should come up sucessfully.

**Comment by arun-magma** [comment]
Here are the 3 test cases covers these 3 scenarios.
TC1h (Cause-#27) - Scripts added in regression & passing.
TC20 (Cause-#28) - WIP , ETA 9/11
TC20a (Cause-#43)- Scripts available for testing, Currently no response while 2nd PDU Est request goes for same PDU identifiy. Here is the pcap enclosed.
[https://app.zenhub.com/files/170803235/de658035-7e1e-46e6-b096-9856088b7186/download](https://app.zenhub.com/files/170803235/de658035-7e1e-46e6-b096-9856088b7186/download)

**Comment by arun-magma** [comment]
TC1h, TC20 and TC20a are available to test, Kindly add your observations & change if any needed
Note: on TC20 with PDU establish:  Session type: Unknown, Let us know if this need to be "unstructured/Ethernet" only or "unknown" is fine.


[https://app.zenhub.com/files/170803235/61964ba7-f871-4585-8227-592a49a1be44/download](https://app.zenhub.com/files/170803235/61964ba7-f871-4585-8227-592a49a1be44/download)
[https://app.zenhub.com/files/170803235/d9ec9b03-420b-44eb-b5ce-c748c5c5bfed/download](https://app.zenhub.com/files/170803235/d9ec9b03-420b-44eb-b5ce-c748c5c5bfed/download)
[https://app.zenhub.com/files/170803235/d849a55c-d314-4fcc-b450-c2936e3596dd/download](https://app.zenhub.com/files/170803235/d849a55c-d314-4fcc-b450-c2936e3596dd/download)

**Comment by NeelimaKalpana** [comment]
Hi Arun,

 "unstructured/Ethernet"  is also required . I will execute the testcases and give respective feedback on the same.

**Comment by arun-magma** [comment]
Hi Neelima, We are adding PDU type as a explicit configurable parameter in the scripts, with this we can send any type by configuring the value of it, please check with me by early next week.

**Comment by arun-magma** [comment]
Hi @NeelimaKalpana @ganeshg87:
We made PDU Session type as configurable in run config, this would allow to set required type from 1 ~ 5
by default 4 is set for unstructured ...
![Screen Shot 2021-11-17 at 10.50.01 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/498effc5-6aa6-4e02-b528-e94aa48870d4)

Ref table for PDU type as per spec

![Screen Shot 2021-11-17 at 10.51.56 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/9530f8c8-4055-44ae-a5cc-41b0c7d699c7)

**Comment by NeelimaKalpana** [comment]
Hi Arun,

TC1h is for "5GMM cause: DNN not supported or not subscribed in the slice (91)" .

pcap screenshot:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/b37e4028-aae9-46e2-a016-984e325bec66)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/50bb64ce-f524-4017-bdce-358a1cb69ccf)

But we need to add one more TC for the cause 27(Missing or unknown DNN) . Please find bellow description for the same.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/171add44-90b3-4f28-b326-c22936ed1244)

**Comment by NeelimaKalpana** [comment]
This is a request for TC20a.

Current behavior PCAP screenshot.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/44e3c732-7405-4362-a343-a98332ef1efc)

After PDU-Reject for a invalid-Session identity can you please add a step to send some traffic before de-registration.
So that we can make sure existing successful session is up .

**Comment by arun-magma** [comment]
TC20a have traffic flow added, Kindly validate and if any more change needed plz let us know

**Comment by NeelimaKalpana** [comment]
Sure Arun, I will validate and get back.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please refer the PCAPS for expected behavior and change the script expectations accordingly.

And I am asking to send the traffic after PDU-Reject is triggered.
But from latest pcap i couldn't fins any traffic after PDU_Rejection is triggered.[https://app.zenhub.com/files/170803235/f50d5eb7-baba-47ca-a0e5-664dfe45dd38/download](https://app.zenhub.com/files/170803235/f50d5eb7-baba-47ca-a0e5-664dfe45dd38/download)

**Comment by arun-magma** [comment]
When PDU Reject is Triggered GTP Tunnel don't get created, how UE can send the traffic ?  , Kindly review the expectation again.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

In this case , we can see there is a PDU-Session is up and UE is trying to send a request with same session-id(which is an unexpected behavior) so amf is rejecting the new request from UE without disturbing  existing session. So Traffic can be sent on the Active PDU-Session. before the clean-up.

**Comment by arun-magma** [comment]
Got it, Traffic flow on previously formed PDU session, let me check this

**Comment by NeelimaKalpana** [comment]
Arun, Please see the pcap, we should have 6-PDU requests , 1-Accept and 1-Reject.
I think we need to update the verdict also.

**Comment by arun-magma** [comment]
Hi @NeelimaKalpana: I see 6 PDU Request is already there. 1 Accept and 5 during DUP request.
Note:  Traffic flow added to flow continuously untill Dereg, so after the PDU reject you would see 10 Pkts and then Dereg gets triggered. We couldn't verify this as PDU Reject is not being triggered currently by AGW, kindly validate the flow after issue resolution.

![Screen Shot 2021-12-02 at 11.12.22 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/6183530a-8156-4f38-8750-fa24401556a1)

**Comment by NeelimaKalpana** [comment]
Hi Arun, I am sending the sample pcaps , subscriber config for TC1j- Missing DNN case

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/33394327-18d3-4b70-aefe-8f06952adb37)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/7bcbe919-9d2b-4950-884b-352406f47c23)

[https://app.zenhub.com/files/170803235/cfecb047-aeae-4544-8b52-41faf44d70ae/download](https://app.zenhub.com/files/170803235/cfecb047-aeae-4544-8b52-41faf44d70ae/download)

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

For TC20a Please update the verdict check 

verification fail:  ((nas5g_sent_Sess__Establ__Req_=6)    	== (nas5g_received_Sess__Establ__Acc_=1)+(nas5g_received_Sess__Establ__Rej_=1))  => False

In the current behavior we are receiving 
nas5g_sent_Sess__Establ__Req =6
nas5g_sent_Sess__Establ__Req =1
nas5g_sent_Sess__Establ__Req =1

This is also expected behavior.
Please change the verdict expectation according.

**Comment by arun-magma** [comment]
@NeelimaKalpana 
Why is AGW code waiting for 4 repeated attempts to say Reg_reject, especially in Dup PDU ID request we expect rejection immediately on 1st such PDU Request itself, Please check.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please find the PR details for further clarity on the implemetation of Cause 43 error code.
https://github.com/magma/magma/pull/9813

Please do the needful by editing the verdict as per current behavior.

**Comment by NeelimaKalpana** [comment]
Hi Arun, 
Please do the needful by modifying the Verdict.
Otherwise, Please let me know if there is any conflict w.r.t to your Understanding.
