### ISSUE TITLE
Requesting Testcases for multiple PDU-Sessions Per UE

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10026]
Hi Arun & Ankur,

Can you please provide the test cases for multi-sessions per UE .

Here is the PR details:

https://github.com/magma/magma/issues/9422

**Comment by arun-magma** [comment]
@GANESH-WAVELABS 
How Many PDUs would be supported by the code ?
Would we have orc8r updates to include the DNN profiles or its gonna be hardcoded ? if hardcoded we like to know the DNN names for all supported no of PDUs.

**Comment by GANESH-WAVELABS** [comment]
@arun-magma 
Maximum number PDU sessions supported is 16.
using NMS dashboard we can configure APN values, these are not hard coded. 
CC : @panyogesh , @ ankursh@fb.com

**Comment by NeelimaKalpana** [comment]
Please find the Scenarios that are required to automate.

Scenario1:  With SUCI as registration type.
Step1: Configure 2 apn's on the UE .
Step2: Attach 2 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3:Two PDU sessions should come UP successfully.
 
Scenario2:  With GUTI as registration type.
Step1: Configure 2 apn's on the UE .
Step2: Attach 2 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3:Two PDU sessions should come UP successfully.

Scenario3: Try to establish maximum supported Sessions per UE.  
Step1: Configure 16 apn's on the UE .
Step2: Attach 16 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3:16 PDU sessions should come UP successfully.

Scenario4: UE IDEL-ACTIVE(MO-Signalling),then Paging ,then periodic_Registration_Connected_Mode when multiple sessions are established.  
Step1: Configure 4 apn's on the UE .
Step2: Attach 4 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3: 4 PDU sessions should come UP successfully.

Scenario5: UE IDEL-ACTIVE(MO-data Signalling) ,then Paging ,then Periodic_Regestration_IDLEMode  when multiple sessions are established.  
Step1: Configure 4 apn's on the UE .
Step2: Attach 4 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3:4 PDU sessions should come UP successfully.
Step4: Make UE to Idle mode and trigger Mo-Signal at any single-Session.
Step5:UE should move to Active-Mode.

Scenario6: Multi_Session Valid and Invalid APN's
Step1: Configure 8 apn's on the UE .
Step2: Attach 4 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3:4 PDU sessions should come UP successfully and 4 should get rejected with cause-91.

Scenario6: Multi_Session Valid and Invalid APN's. Try to update invalid APN's in subscriber before timer will get expired.
Step1: Configure 8 apn's on the UE .
Step2: Attach 4 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3: 4 PDU sessions should come UP successfully and 4 should get rejected with cause-91.
Step4: Try to update the subscriberdb with rest proper APN's and check all four sessions are coming up.

Scenario7: Try to trigger more than maximum PDU sessions.
Step1: Configure 17 apn's on the UE .
Step2: Attach 17 apn names that are similar to apn's configured on UE. Attach them to respective subscriber IMSI.
Step3: 16 PDU-Sessions should come up successfully. And last PDU should get rejected with proper reason.

**Comment by arun-magma** [comment]
Scripts are ready to use upto 8 DNNs "SA_TC2a_Verify_Max_no_of_PDU_session", we have scripted to choose no of DNNs need for the run a selectable parameter, Please make use of it to run diff variants of test listed above. 16 DNNs on single UE use case in 5G seems not valid as std UEs support max 8 DNNs, kindly review and let us know if you have any special devices and use cases.

[DNN nos can be selected from below config window]
![Screen Shot 2021-11-08 at 5.41.34 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/d86fdcfc-8c37-40d8-bcb8-b3ea8206beac)

**Comment by arun-magma** [comment]
DNN names as listed below, the scripts auto select from this list in ascending order , just you need to select the no of DNNs.

internet1
internet2
internet3
internet4
internet5
internet6
internet7
internet8

**Comment by NeelimaKalpana** [comment]
Thank you Arun for the inputs. I will  execute the scenarios and check for multi session support functionality.

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

For multi Session testing ,I tried executing "SA_TC2a_Verify_Max_no_of_PDU_session" TC.

I tried up to 4 sessions and all 4 sessions are coming up successfully.
In subscriber configurations I added 4 apn's that are matching with DNN request that UE will be sending.

Please find the subscriber info from bellow:
magma@TVM3-SA:~$ subscriber_cli.py get IMSI222456000000101
sid {
  id: "222456000000101"
}
lte {
  state: ACTIVE
  auth_key: "\213\257G?/\217\320\224\207\314\313\327\t|hb"
}
network_id {
  id: "tvm3_sa_agw_network_140"
}
state {
  lte_auth_next_seq: 106970
}
sub_profile: "default"
non_3gpp {
  apn_config {
    service_selection: "internet1"
    qos_profile {
      class_id: 9
      priority_level: 1
    }
    ambr {
      max_bandwidth_ul: 3000
      max_bandwidth_dl: 4000
    }
  }
  apn_config {
    service_selection: "internet2"
    qos_profile {
      class_id: 9
      priority_level: 1
    }
    ambr {
      max_bandwidth_ul: 3000
      max_bandwidth_dl: 4000
    }
  }
  apn_config {
    service_selection: "internet3"
    qos_profile {
      class_id: 9
      priority_level: 1
    }
    ambr {
      max_bandwidth_ul: 3000
      max_bandwidth_dl: 4000
    }
  }
  apn_config {
    service_selection: "internet4"
    qos_profile {
      class_id: 9
      priority_level: 1
    }
    ambr {
      max_bandwidth_ul: 3000
      max_bandwidth_dl: 4000
    }
  }
}

Ideally the subscriber info should be added from NMS-dash board ,since we are not having access for dash board added manually using cli.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/89ba6535-267a-4940-b1a6-44cf60deaa9d)[https://app.zenhub.com/files/170803235/3487031d-28ad-4fd7-9453-36d47d624fee/download](https://app.zenhub.com/files/170803235/3487031d-28ad-4fd7-9453-36d47d624fee/download)

Please find the logs and pcaps attached for the same.

**Comment by NeelimaKalpana** [comment]
As per current SOW only 4 sessions are to be tested so I Will aline my testing for 4 Sessions.

I need some clarity on "SA_TC2b_verify_Multiple_QFI_in_single_PDU_session" test cases. This is failing as requested DNN:apn_1 is not added on subscriberdb. We are having "internet" as APN/DNN name . In the topology also DNN is set to "internet" , just I want to understand from where DNN:apn_1 is been requested in PDU-Establishment-Request.

Please find the attached pcaps screenshot for the same:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a7b1cabf-083d-4b6b-8e6b-93210bb3c8e5)

AMF-Rejecting PDU-Session:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/b0f1dd33-7161-4a03-a7c4-cb4ae7b2db48)

**Comment by arun-magma** [comment]
TC2b is for multiple QFI in single PDU Session, this is different from multi PDU session test cases.
DNN change can be made to internet for TC2b, will let u know on this.

**Comment by arun-magma** [comment]
Great to see Multi PDN for 4 DNNs work well, Thanks for this validation
Can you please add here the config procedure for Multi DNN to apply & maintain in Regression ?
Did we add this through orc8r or through swagger ?

**Comment by NeelimaKalpana** [comment]
Hi Arun,
We need to add those configuration from NMS-Dash board.

Please follow the following steps to add the same.:

Step1: In NMS-Dash board : under Traffic config add muntiple APN's 
Step2 :Go to  add subscriber where we can attache the configured APN's.

Note Either we can add APN's while adding a subscriber or we can edit the existing subscriber and add the APN's.

Please find bellow sceenshots for the same:
![image](https://user-images.githubusercontent.com/90390982/141732963-ba0a7b32-259c-4ba5-bb01-2ae18c498620.png)

Please let me know for any inputs.

**Comment by NeelimaKalpana** [comment]
> Great to see Multi PDN for 4 DNNs work well, Thanks for this validation Can you please add here the config procedure for Multi DNN to apply & maintain in Regression ? Did we add this through orc8r or through swagger ?

Thank you Arun for the Inputs.

**Comment by NeelimaKalpana** [comment]
Hi Arun,
Kindly add TC for following scenario:
1. UE-Idle mode to Active-Mode scenario 
2. Paging scenario.
3. Valid and Invalid Session scenario.

**Comment by arun-magma** [comment]
Please try add Testplan for this requests as per below Ref Template, Is these scenario needed for Multi-PDN ? , is yes 4 PDNs are good to script with these scenarios ? What is valid and invalid session differentiator ? (PDU ID repeat and Make it invalid okay ?) , provide bit more clarities. 

Ref template
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10369

**Comment by NeelimaKalpana** [comment]
Hi Arun,

I will make an excel with keeping all pointers in the template.
4 PDN's is fine w.r.t. current SOW.
All above scenarios are w.r.t multi session testing.

For Valid and Invalid Sessions, we can use any PDU-Reject case for one of the session, as of now I tested with DNN mismatch for 1 session , I am expecting only that session to be rejected and other sessions to exist.

I am really sorry for not giving proper clarity beforehand.

**Comment by arun-magma** [comment]
Change DNN names from group-2 and group-9 only for this TC, And never change DNN group-0 that would impact regression runs as change applies globally all TCs. Please inform to ll teravm users from Wlabs side.

**Comment by NeelimaKalpana** [comment]
Hi Arun, 

Thank you for giving us a note on different groups available , we will use the groups accordingly without disturbing group-0.

**Comment by arun-magma** [comment]
Hi Neelima, Based on your above request we are adding below TCs, I would request kindly open a new ZH task for this. On Invalid Session i need input what bad values need to be injected to make it invalid.

TC2C	Verify Idle and Active Mode transition with Multi PDU session 
TC2d	Verify Paging with Multi PDU session

**Comment by NeelimaKalpana** [comment]
Thank you Arun.
I created new ticket where I attached the detailed scenario in the requested format. Please check ticket #10451 once .
I shared the document over the mail-id given in the ticket. Please let me know if your facing problem to access it.

**Comment by NeelimaKalpana** [comment]
TC2c and TC2d I will verify and get back arun.

**Comment by arun-magma** [comment]
Lets close this ticket as base Multi PDU session is verified with this ticket & other enhancement scenarios are being in below ticket https://github.com/magma/magma/issues/10451
