### ISSUE TITLE
task: validate L3 transport with inbound roaming.

### ISSUE THREAD

**Issue by pshelar** [magma/magma#10037]
Steps:
1. Setup inbound roaming
2. Follow doc to setup L3 transport: https://github.com/magma/magma/blob/master/docs/readmes/howtos/l3_transport.md
3. Validate L3 transport is up and running.
4. Validate inbound roaming datapath works on L3 transport.

@jpad-freedomfi please assign this to appropriate engineer.

**Comment by jaredmullane** [comment]
@jpad-freedomfi Do you have any test cases or logs from your side for this?

**Comment by uri200** [comment]
Hey @jpad-freedomfi will the L3 transport be tested on your setup anytime soon?

**Comment by pshelar** [comment]
this is doc to configure L3 transport: https://docs.magmacore.org/docs/next/howtos/l3_transport

**Comment by uri200** [comment]
Hey @jpad-freedomfi were you able to test this feature? 

If so could you share some pcaps or logs to see how it works?
