### ISSUE TITLE
[AMF]: Verification of the Stateless feature

### ISSUE THREAD

**Issue by Lkishor123** [magma/magma#10035]
To develop test script for stateless feature for testing in TeraVM.

1. 
Bring up GNB and UE

2. Configure some of the UEs and ensure that they are in either IDLE mode or connected

3. 
Restart the MME

4. 
Once the MME is up check of the UEs are in expected state.

**Comment by arun-magma** [comment]
@Lkishor123  Please help to add quick AGW commands to check UE's MM state.

**Comment by arun-magma** [comment]
We may use existing scripts, Need a bit of efforts to automate it.
cc: @vaishaliCI

**Comment by arun-magma** [comment]
Stateless Enabled in TVM Regression and all daily & sanity runs are now Stateless Mode of AGW.
