### ISSUE TITLE
[Proposal] CI Integration with Test Infra

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#10038]
# CI Integration with Test Infra

## Problem

Integrating CI with 3rd party test infra has always been difficult due to the amount of custom work needed to support different kinds of access requirements and APIs. Often times, we resort to deploying jump hosts to prevent access to sensitive security credentials.
In this proposal we attempt to standardize the way all 3rd party test infra integrate with CI.

## Solution

We adopt a poll model in which different test infra “workers” read a dedicated jobs queue from a shared database. These job queues are hydrated by the CI pipeline or, later, through manual intervention from a management website.

The database will also host all CI related metrics and test reports. Upon completing a testing job, test nodes submit a json-formatted report to the database that can then be presented on a central dashboard or consumed by CI to make workflow decisions.

We will use Firebase Real Time Database [1] to implement the above solution. Advantages of this solution are
- Easy to deploy and manage. 
- Wide set of SDKs + REST API
- Easy to manage security rules
- Simple NoSQL json-based data model

We will build a template test infra agent that allows for quick integration of 3rd party test systems. The templates will stub infra-specific integration points and implement key components of the system including the scheduler and Database API calls, 

For more details and alternatives considered, please see the document at https://docs.google.com/document/d/1Zi7-H3olnlRdxA4ZNjfi6WrIViPflwvmGMspTy9rAZI/edit#

References:
[1] https://firebase.google.com/docs/database

## Non-goals
N/A

**Comment by hcgatewood** [comment]
Accepted! Excited for this 😄
