### ISSUE TITLE
Make markdown-lint a required CI check

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#10058]
# Make markdown-lint a required CI check

The check has been active for 1+ months, and has support parity with the other required checks.

The win here is automatically enforcing a minimal set of Markdown standards -- only catches actual issues, is not meant to be intrusive 🙂 

Job ref: https://github.com/magma/magma/blob/136ad859fe4c42786a00230f881a1f4c8d9bfe51/.github/workflows/docs-workflow.yml#L32-L48

**Comment by hcgatewood** [comment]
cc @themarwhal

**Comment by themarwhal** [comment]
I made this required some time ago :)
