### ISSUE TITLE
Regarding functionality of testcases that are proposed for Qos testing.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10066]
Hi Arun & Ankur,

This is regarding the exact flow of test steps in the test cases proposed for Qos testing.

Below are the 2 test cases:
SA_TC51_Scale_mbps_udp
SA_TC52_Scale_mbps_tcp

Tried executing the test case but couldn't find any ngap messages in the pcap.

Please find attached pcap for the same.

Please let me know exact flow of testcases.
[https://app.zenhub.com/files/170803235/dfc3df97-1a5f-4b37-bd6c-9f00c8052feb/download](https://app.zenhub.com/files/170803235/dfc3df97-1a5f-4b37-bd6c-9f00c8052feb/download)

**Comment by NeelimaKalpana** [comment]
Hi Ankur & Arun,

These are few TC need to be automated for Qos-Support.

Scenario 1: Configure Qos-Profile1(QFI:9,Priority:15 UL/DL ambrs:as default,) and Add one 
                      apn_1(ClassID:9, PremsionPriority:False and Premsion Vulnerability:False) 
Step1:Add a subscriber with attaching Qos-Profile1 and APN_1 on Subscriber.
Step2:Trigger the PDU-Session procedures.
Ste4: Check that PDU-Session is comingup with configured values.
Ste5: Trigger the traffic according to ambr values configured.


Scenario 2: Configure Qos-Profile1(QFI:9,Priority:15 ,UL/DL ambrs:as default,) , Flow(IP-Packets as deny.)
                      apn_1(ClassID:9, PremsionPriority:True and Premsion Vulnerability:True) 
Step1:Add a subscriber with attaching Qos-Profile1 and APN_1 on Subscriber.
Step2:Trigger the PDU-Session procedures.
Ste4: Check that PDU-Session is comingup with configured values.
Ste5: Trigger the traffic according to ambr values configured.
Step6: Trigger the all tarffic types(IP,TCP and UDP). IP-Packets should get droped.

Scenario 3: Configure Qos-Profile1(QFI:9,Priority:15 UL/DL ambrs:as default,) , Flow(TCP-Packets as deny.)
                      apn_1(ClassID:9, PremsionPriority:False and Premsion Vulnerability:False) 
Step1:Add a subscriber with attaching Qos-Profile1 and APN_1 on Subscriber.
Step2:Trigger the PDU-Session procedures.
Ste4: Check that PDU-Session is comingup with configured values.
Ste5: Trigger the traffic according to ambr values configured.
Step6: Trigger the all tarffic types(IP,TCP and UDP). TCP-Packets should get droped.


Scenario 4: Configure Qos-Profile1(QFI:9,Priority:15 UL/DL ambrs:as default,) , Flow(UDP-Packets as deny.)
                      apn_1(ClassID:9, PremsionPriority:True and Premsion Vulnerability:True) 
Step1:Add a subscriber with attaching Qos-Profile1 and APN_1 on Subscriber.
Step2:Trigger the PDU-Session procedures.
Ste4: Check that PDU-Session is comingup with configured values.
Ste5: Trigger the traffic according to ambr values configured.
Step6: Trigger the all tarffic types(IP,TCP and UDP). UDP-Packets should get droped.

Scenario 5: Configure Qos-Profile1(QFI:9,Priority:15 UL/DL ambrs:as default,) , Flow(all Packet types as deny.)
                      apn_1(ClassID:9, PremsionPriority:True and Premsion Vulnerability:True) 
Step1:Add a subscriber with attaching Qos-Profile1 and APN_1 on Subscriber.
Step2:Trigger the PDU-Session procedures.
Ste4: Check that PDU-Session is comingup with configured values.
Ste5: Trigger the traffic according to ambr values configured.
Step6: Trigger the all tarffic types(IP,TCP and UDP). all-Packets should get droped.
Step7:Modify the filters with seeting All packet types as allow.
Step8: Pump the traffic of all packet type, Packet flow should happen.



Scenario 6: Configure Qos-Profile1 , APN_1(with UL and DL AMBR) and APN_2(Specific UL and DL AMBR). In UE configur multiple session parameters.
Step1:Add a subscriber with attaching Qos-Profile1,APN_1 and APN2 on Subscriber.
Step2:Trigger the PDU-Session procedures.
Ste4: Check that 2 PDU-Session is comingup with configured values accordingly.
Ste5: Trigger the traffic according to ambr values configured at each session level.
Step6: creat connjetion and check that traffic forwarded on session coming up with high priority is served first.

**Comment by arun-magma** [comment]
@NeelimaKalpana : The pcaps for performance tests (Esp throughput) are disabled intentionally as its gonna be jumbo size and would load the teravm machine and could blocks the running services, if needed we need to collect tcpdump from magma agw side for our analysis. In teravm there are nice statical view we can view the vive throughputs and also after test completes we can DL the stats and evaluate the throughput.

**Comment by arun-magma** [comment]
TC-51 and TC52 throughput scripts with UDP and TCP traffic are good to test most of the above listed QOS scenarios, the configs for these 6 scenarios need to be aligned from magma AGW side and can use the same script, As we have static policies config in policydb these Polices can be controlled internally to get diff QOS profile, incase these policies are planned from PCF or diff traffic pattern (Ports etc need to be changed) let us know the specific requirements & flow, we can align scripts for it.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

I Will work on the scripts and update the same.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

I don't feel that  we can use TC51 and TC52 for all scenarios.
if I want o align the Qos-Profiles according to above scenarios , I should have access to NMS-Dash board.
And to have a complete automation of above scenarios we will need to configure the profile and bind them to subscriber from script itself, this is right approach to do.

**Comment by arun-magma** [comment]
We can set QOS profiles & filters in NMS and map to particular subscriber for our test, In automation we can pick subscriber based on test scenario need, That should be manageable i believe as we have other ways to feed the inputs during Automated run.
I see in the list we need test all filtering combination, let me arrange a Mix Traffic (UDP + TCP) scripts with configurable UL/DL throughput, which would help to complete most of the scenarios.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

That fine to configure profile from NMS-Dash board.
Kindly give the url for NMS-Dash board and share me the credentials to access the same.

@"I see in the list we need test all filtering combination, let me arrange a Mix Traffic (UDP + TCP) scripts with configurable UL/DL throughput, which would help to complete most of the scenarios."
==>This is really required. 
Thank you Arun.

**Comment by arun-magma** [comment]
Lets use Wavelabs hosted orc8r for this dev testing env, Access to magma staging is restricted to internal domain users atm.

**Comment by arun-magma** [comment]
As Discussed below scripts are available to validate QOS cases 
TC-51 - UDP Traffic
TC-52 - TCP Traffic
TC52a - UDP + TCP Traffic

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

Sure I will execute the TC's and give the update and necessary configurations for the same.

**Comment by NeelimaKalpana** [comment]
TC51	Verify UDP throughput for Single Subscriber & with Scale

Observations:
1. UPTO 99Mbps until 60 sec. we are able to see all traffic is getting forwarded .
2. Traffic is failing when we are sending 100Mbps and above for 60 sec.
With IMSI-Prefix bug fix we need to retest the functionality of TC51.

TC52	Verify TCP throughput for Single Subscriber & with Scale
Observation:
Update the QFI=5 still seeing no traffic flow.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/c62909b5-6e17-4c1a-bedc-2729b16c7464).

TC52a	Verify UDP & TCP throughput for Single Subscriber & with Scale
Observation: Seeing both UDP and TCP traffic failing
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6327a769-b259-4eea-a19f-511c74c8903a)
Need to further debug with help of developers.

@parbinak , Please help us to debug TC52 and TC52a

**Comment by NeelimaKalpana** [comment]
Hi Arun for TC52 and TC52a please give the QFI/QCI value as 5 .

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma, Today we tested TC52 and TC51 with a fix given by Developers for the UDP and TCP traffic flow. we are able to see successful traffic flow(Both UL/DL) but In TVM GUI statistics are not updating properly and Testcase is also failing. Please check the below PCAP's for your reference.
[https://app.zenhub.com/files/170803235/6d15832c-a05a-4510-9c26-04a3d70f4eeb/download](https://app.zenhub.com/files/170803235/6d15832c-a05a-4510-9c26-04a3d70f4eeb/download)

**Comment by NeelimaKalpana** [comment]
Hi Arun,

In regression I am seeing the verdict is getting share for TC51 and TC52.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/8f7be4da-e83c-448b-99eb-22c6aefc23d8)

But in the regression Logs I am seeing the logs for TC51cc and TC52cc , with scaling up to 200 scenario.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/3c2905e3-8490-4c94-93ca-9b5e95e05b64)

Please let me know why we are porting in this way.

**Comment by NeelimaKalpana** [comment]
TC are working fine . I am closing this issue.
