### ISSUE TITLE
[docker][agw] Redis fails to load due to missing template config

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#10079]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** redis
- **Deployment Environment:** docker AGW

### Describe the Issue

- redis docker container fails to load after bringing docker containers:
```
redis             | Traceback (most recent call last):
redis             |   File "/usr/local/bin/generate_service_config.py", line 138, in <module>
redis             |     main()
redis             |   File "/usr/local/bin/generate_service_config.py", line 134, in main
redis             |     generate_template_config(opts.service, opts.template, opts.output_path, {})
redis             |   File "/usr/local/bin/generate_service_config.py", line 113, in generate_template_config
redis             |     template_str = open(template_filename, 'r').read()
redis             | FileNotFoundError: [Errno 2] No such file or directory: '/etc/magma/templates/redis.conf.template'
redis             | WARNING:root:Service (redis) missing in mconfig
redis             | Traceback (most recent call last):
redis             |   File "/usr/local/bin/generate_service_config.py", line 138, in <module>
redis             |     main()
redis             |   File "/usr/local/bin/generate_service_config.py", line 134, in main
redis             |     generate_template_config(opts.service, opts.template, opts.output_path, {})
redis             |   File "/usr/local/bin/generate_service_config.py", line 113, in generate_template_config
redis             |     template_str = open(template_filename, 'r').read()
redis             | FileNotFoundError: [Errno 2] No such file or directory: '/etc/magma/templates/redis.conf.template'
```
- looking at the gateway configs mounted on the volume, it is copying from `../lte/configs..`, however, redis configuration template file is under `../orc8r/gateway/configs`, which in this case is missing on the container.

**Comment by ymasmoudi** [comment]
@ardzoht Hi Alex, How did you install your agwc ?
as you can see here, we do copy the redis template during ansible installation
https://github.com/magma/magma/blob/a96c02e49ba59db7711bd0b68f2c4ca242701f72/lte/gateway/deploy/roles/agw_docker/tasks/main.yml#L116

**Comment by ymasmoudi** [comment]
Also, the installation should leave your .env file with this and not ../lte/configs

ROOTCA_PATH=/var/opt/magma/certs/rootCA.pem
CONTROL_PROXY_PATH=/etc/magma/control_proxy.yml
CONFIGS_TEMPLATES_PATH=/etc/magma/templates

CERTS_VOLUME=/var/opt/magma/certs
CONFIGS_OVERRIDE_VOLUME=/var/opt/magma/configs
CONFIGS_DEFAULT_VOLUME=/etc/magma
SECRETS_VOLUME=/var/opt/magma/secrets
