### ISSUE TITLE
Connectiond socket read error 

### ISSUE THREAD

**Issue by koolzz** [magma/magma#10081]
Observing this on lab agw. Check if this is something we can handle or if its an internal mnl library bug that we'll just have to deal with.

Remediation is keeping connectiond in services_to_restart list in magmad.

```
Nov  3 20:52:08 u-160-161-nat connectiond[3043169]: mnl_socket_recvfrom: No buffer space available
Nov  3 20:52:08 u-160-161-nat systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by koolzz** [comment]
From my digging the error is internal to libmnl as it gets overwhelmed by msgs. The current approach lgtm, if this error happens(which should be rare) then the service will crash/restart leading to the libmnl socket reconfiguration and minimal downtime of lost requests.

**Comment by wallyrb** [comment]
hey @koolzz Thanks for checking this. can we re-open this issue? However, these errors are very frequent in a production environment. As you see below , there are restarts every 2 minutes. Is there anything we can do to avoid this? 


Nov 29 12:07:44 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:09:45 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:11:46 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:13:47 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:15:48 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:17:48 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:19:49 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:21:50 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:23:51 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:25:52 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:27:53 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:29:53 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:31:54 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:33:55 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:35:56 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:37:57 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:39:58 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 12:41:58 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE

**Comment by koolzz** [comment]
@wallyrb same error as above I presume?

**Comment by koolzz** [comment]
@wallyrb Could you share connectiond logs and the connectiond.yml from the prod env

**Comment by wallyrb** [comment]
Hey @koolzz correct, all restarts have the same error `mnl_socket_recvfrom: No buffer space available`

I just shared full logs in the internal task T103956264. Let me know if need more info. Thanks for the quick response

**Comment by koolzz** [comment]
@wallyrb I've seen this happen rarely on our testbed but it recovers from it.  Whats the kernel version for the agw? Whats the magma version?
Lets check some stuff to better triage.
How it the memory usage looking can you check htop?
Also whats the output of the following commands:
`sysctl fs.file-nr`, ` cat /proc/sys/net/ipv4/tcp_mem`

**Comment by wallyrb** [comment]
Hey @koolzz thanks for following up. Output of magma, kernel and top can be find in the logs file commands_output.log
https://drive.google.com/drive/u/2/folders/1yP16wpHrG6LdoEuBjpbwA73Av7QrfRLm

Also pasting below.

I will collect these two sysctl fs.file-nr, cat /proc/sys/net/ipv4/tcp_mem

```
Command: uname -a
Linux agwbrisa04 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```


```
Command: top -b -n 1
top - 19:43:27 up  7:36,  1 user,  load average: 2.60, 1.45, 0.84
Tasks: 153 total,   1 running, 152 sleeping,   0 stopped,   0 zombie
%Cpu(s): 10.7 us,  7.1 sy,  0.0 ni, 46.4 id, 32.1 wa,  0.0 hi,  3.6 si,  0.0 st
MiB Mem :   3936.1 total,    123.2 free,   1295.1 used,   2517.7 buff/cache
MiB Swap:   4096.0 total,   3562.2 free,    533.8 used.   2375.6 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   8068 root      20   0   20.0t 517860  13152 S  43.8  12.8  27:59.93 mme
   2224 root      20   0   74636   9060   5824 S   6.2   0.2   3:14.82 td-agen+
   7405 root      10 -10  313868  46268   9908 S   6.2   1.1  11:12.95 ovs-vsw+
  85760 root      20   0  133236  47712   9776 S   6.2   1.2   0:15.73 ansible+
  93574 root      20   0    9264   3524   3072 R   6.2   0.1   0:00.01 top
      1 root      20   0  105744   8072   6048 S   0.0   0.2   0:13.15 systemd
```

```
Command: apt show magma
Package: magma
Version: 1.5.3-1631131046-89c90f6d
```


Note, this issue can be also reproduced in 1.6.1.

**Comment by Radula76** [comment]
Hi, some more information from agwbrissa04 1.5.3 AGW as well, I have a show-tech 1.2Gbps file available:
syslog:
Jan  4 13:32:52 agwbrisa04 connectiond[1872254]: mnl_socket_recvfrom: No buffer space available
Jan  4 13:32:52 agwbrisa04 systemd[1]: magma@connectiond.service: Main process exited, code=exited, status=1/FAILURE
Jan  4 13:32:53 agwbrisa04 systemd[1]: magma@connectiond.service: Failed with result 'exit-code'.
...
Jan  4 13:32:58 agwbrisa04 systemd[1]: magma@connectiond.service: Scheduled restart job, restart counter is at 5344.
Jan  4 13:32:58 agwbrisa04 systemd[1]: Stopped Magma connection tracking service.
Jan  4 13:32:58 agwbrisa04 systemd[1]: Started Magma connection tracking service.
Jan  4 13:32:58 agwbrisa04 connectiond[1872585]: [/home/vagrant/magma/orc8r/gateway/c/common/config/MConfigLoader.cpp:62] Couldn't find connectiond config
Jan  4 13:32:58 agwbrisa04 connectiond[1872585]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:35] Override file not found for service connectiond
Jan  4 13:32:58 agwbrisa04 connectiond[1872585]: I0104 13:32:58.262471 1872585 magma_logging.h:33] Setting verbosity to 3
Jan  4 13:32:58 agwbrisa04 connectiond[1872585]: I0104 13:32:58.262591 1872585 main.cpp:77] Starting Connection Tracker
Jan  4 13:32:58 agwbrisa04 connectiond[1872585]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:35] Override file not found for service service_registry
Jan  4 13:32:58 agwbrisa04 connectiond[1872585]: I0104 13:32:58.281441 1872585 PacketGenerator.cpp:37] Using interface ipfix0 for pkt generation

connectiond.yml:
---
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

log_level: INFO

# Interface for internal packet sending
interface_name: ipfix0

# Used for generated internal packets
pkt_dst_mac: "33:aa:99:33:aa:00"
pkt_src_mac: "55:11:44:ee:00:00"
zone: 897

Attached are some statistics, I was investigating the crash/halt of services at around 13:45pm which I think is an MME crash, not related to this issue.
![Physical_virtual_mem](https://user-images.githubusercontent.com/80013777/149429024-e92c4fa5-cf40-479d-b297-949b517c8
![CPU_Utilization](https://user-images.githubusercontent.com/80013777/149429033-9796c25b-e332-4f9f-b63b-9b430c87947c.jpeg)
75a.png)

Regards,
  Mark Harris
