### ISSUE TITLE
Orc8r RDS upgrades

### ISSUE THREAD

**Issue by arunuke** [magma/magma#10112]

**Comment by sudhikan** [comment]
I went through a terraform based orc8r RDS upgrade and put my findings [here](https://docs.google.com/document/d/1mCppAa-5vZWGF2JiSMmGAHfIui9oW_CgjdHGmTH_UDs/edit?usp=sharing).

Essentially, we can’t do PostGres 13.4 as AWS doesn’t allow us to jump to that version with the instance type m4.large The largest we could go for PostGres was 12.8. And that’s what I tested.

I didn’t test with 9.6 -> 12.8 as that was more “production-y”. I wanted to test something more along the lines of “it’s okay if this breaks”. So thanks to cloudstrapper, I deployed an orc8r instance in eu-west-2 and did a 10.18 -> 12.8 upgrade.

Finally, the downtime is around 20 minutes (rounding up a bit) and post install, the validation can be a little scary as it takes a few minutes for the various DB connections to come alive.

I think 12.8 is our RDS version. I am going to test with 9.6 -> (ens orc8r is on this version) and then publish the instructions for dogfooding and feedback.

**Comment by sudhikan** [comment]
Thus far, these are the steps I followed for the upgrade: 

1. In `.terraform/modules/orc8r/orc8r/cloud/deploy/terraform/orc8r-aws/db.tf` add `apply_immediately = var.orc8r_db_apply_immediately` 
2. In `.terraform/modules/orc8r/orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf` make the following addition.
```
variable "orc8r_db_apply_immediately"{
  description = "Apply DB changes immediately or after during maintenance window"
  type = bool
  default = false
}
```

NOTE: Steps [1] and [2] should be done as a PR to the repo. This was purely to document the process.

3. In `main.tf` set the following variables:
```
  orc8r_db_engine_version = "12.8"
  orc8r_db_apply_immediately = "true"
```
NOTE: `orc8r_db_engine_version` might already be set to a specific value, if it is, change it to `12.8`. Further, these changes should be made in `module "orc8r" {...}` stanza. 

4. Run [terraform plan](https://gist.github.com/sudhikan/f05c52eab4ec66e00ef928dc3edf6669). Inspect the output to ensure that RDS is being upgraded in place and not replaced. 
5. Run [terraform apply](https://gist.github.com/sudhikan/f18f7388abbf098ed2cf1b67f8c30bfd). This will take about 20 minutes or so of downtime. Check the AWS console for RDS to see that it is "Upgrading" the current DB. 
![image](https://user-images.githubusercontent.com/38921899/142980288-b436b1d1-e39c-4742-93ca-8a23823fbf3b.png)

6. Go back to `main.tf` and modify `orc8r_db_apply_immediately = "false"` and run `terraform apply` again. This should not take long. 
7. Go back to the NMS and ensure that you are able to load the DB, subscribers are visible, polices are visible, and ultimately that gateways are able to checkin and get config streamed (the last part is just for completeness). 

Showing the snippet on aws_db_instance from `terraform show` command with all the above changes incorporated.

```
# module.orc8r.aws_db_instance.default:
resource "aws_db_instance" "default" {
    address                               = "orc8rdb.czay9gi9jk5o.eu-west-2.rds.amazonaws.com"
    allocated_storage                     = 64
    allow_major_version_upgrade           = true <<<<<<<<<<------------------------
    apply_immediately                     = false <<<<<<<<<<------------------------
    arn                                   = "arn:aws:rds:eu-west-2:007606123670:db:orc8rdb"
    auto_minor_version_upgrade            = true
    availability_zone                     = "eu-west-2a"
    backup_retention_period               = 7
    backup_window                         = "01:00-01:30"
    ca_cert_identifier                    = "rds-ca-2019"
    copy_tags_to_snapshot                 = false
    customer_owned_ip_enabled             = false
    db_subnet_group_name                  = "orc8r"
    delete_automated_backups              = true
    deletion_protection                   = false
    enabled_cloudwatch_logs_exports       = []
    endpoint                              = "orc8rdb.czay9gi9jk5o.eu-west-2.rds.amazonaws.com:5432"
    engine                                = "postgres"
    engine_version                        = "12.8" <<<<<<<<<<------------------------
    engine_version_actual                 = "12.8" <<<<<<<<<<------------------------
```
