### ISSUE TITLE
sentry: Add HOSTNAME env variable as a tag for Sentry events

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#10147]
In C/C++ configuration, we've added an entry to include the value of HOSTNAME environment variable. This is useful in easily identifying the problematic AGW when seeing issues.

https://github.com/magma/magma/blob/master/orc8r/gateway/c/common/sentry/SentryWrapper.cpp#L124

We should do the same for Python errors as well.

**Comment by jheidbrink** [comment]
The Sentry Python SDK already does that per default, but it's called `server_name` instead of `hostname`. And given that in the events view of an issue the columns are ordered alphabetically, I have to set my browser's zoom level below 100% to actually see it ;)
