### ISSUE TITLE
TAU with no response

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#10151]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:1.7
- **Affected Component:AGW
- **Affected Subcomponent:MME
- **Deployment Environment:bare-metal (AGW)

### Describe the Issue

some background: our subscriber has two SIMs from two providers, provider 1 for calls and SMS, and provider 2 for data, we've notice that when a subscriber receive a SMS from provider 1, the ENB send to MME a TAU type 1 (combined TA/LA), but  MME does not respond, ENB sends the TAU again, but not response, then the ENB sends a conext release request with cause 21, and the UE start again the attach procedure

**To Reproduce**
1. A phone with two providers, one for calls and SMS and other for data with Magma.
2. Start capturing SCTP packets.
3. Send a SMS to the testing phone.

**Expected behavior**
MME should respond to TAU.

**Screenshots**

![imagen](https://user-images.githubusercontent.com/90400693/140554979-2ab9cb2a-a523-416c-82b9-9dd41a7d32df.png)

![imagen](https://user-images.githubusercontent.com/90400693/140554912-b611f336-814b-4f05-b527-a92b91b9d0f7.png)

**Comment by javieraubert** [comment]
[agw2-1_sctp05112021_1016_DISC.zip](https://github.com/magma/magma/files/7487983/agw2-1_sctp05112021_1016_DISC.zip)

Here's the pcap capture

**Comment by javieraubert** [comment]
Update: we 've made more test so far this issue semms to happend when using a Xiaomi Redmi Note 9, we make test with Samsung A50 (SM-A505G), Samsung A11 (SM-A115F/DS) and Xiaomi Redmi Note10 and none of those 3 phones send the TAU request when receiving SMS.

**Comment by wallyrb** [comment]
Hey @javieraubert could you try testing on master? TAU Combined is supported on master as of now.

**Comment by edaspb** [comment]
Hi @wallyrb, these messages we observe on version 1.7.0-1632844785-0073ffd9 which already supports combined TAU. Earlier versions send reject, here we see just no respond at all. And this behavior typical only for specific models.

**Comment by joary** [comment]
@edaspb, @javieraubert , can we repeat the test with the MME log in debug mode [see instructions](https://docs.magmacore.org/docs/next/faq/faq_magma#how-to-switch-between-infodebug-mode-in-mme-logs)?

Feel free to share the whole /var/log/MME.INFO of the test and point out when the EMMAS_ESTABLISH_REQ fails.

**Comment by javieraubert** [comment]
Hi @joary we repeat the test, here are the files, logs and pcap. At 16:31:51 we send the SMS on the testing phone, then the ENB sended the TAU, but MME did not respond, then a second TAU and it gets a reject. After that the UE sended an attach request at 16:32:15. The logs were configured on debug level.

[10112021.zip](https://github.com/magma/magma/files/7514450/10112021.zip)

**Comment by ulaskozat** [comment]
@pruthvihebbani
