### ISSUE TITLE
Request for updating TC7d -"Verify_Service_Reject_for_SReq_MO_Data" on TVM setup.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#10169]
[https://app.zenhub.com/files/170803235/97b2b851-8192-43c6-a9f3-c76049eb6c61/download](https://app.zenhub.com/files/170803235/97b2b851-8192-43c6-a9f3-c76049eb6c61/download)Currently TC7d is failing with "cause 9 :  UE id can not be derived by the network"

But TC7d functionality (Service Reject) is already covered in TC7e and TC7f. If TC7d needs to pass, the script should be changed with TMSI in NGAP and NAS messages. 
please find the pcaps and logs below.[https://app.zenhub.com/files/170803235/da3b791f-1517-434f-84e8-bdf46093523a/download](https://app.zenhub.com/files/170803235/da3b791f-1517-434f-84e8-bdf46093523a/download)
[https://app.zenhub.com/files/170803235/1be0dea9-98bd-451b-a38f-37970992933c/download](https://app.zenhub.com/files/170803235/1be0dea9-98bd-451b-a38f-37970992933c/download)
[https://app.zenhub.com/files/170803235/f8687c82-8981-49d3-9a79-1f32fca10944/download](https://app.zenhub.com/files/170803235/f8687c82-8981-49d3-9a79-1f32fca10944/download)

**Comment by panyogesh** [comment]
@Vinay

**Comment by arun-magma** [comment]
@VinayKumar1591 @shanjanaWL 
We see on TC7d TeraVM scripts are sending correct TMSI in service request, using the TMSI allocated in Context setup ( Reg Accept), enclosing the pcap and snap, kindly recheck.
There is another issue in this TC7D that very frequently we see PDU Session Establish Req has no response, after Max Retry test ends, Please check this also.

[https://app.zenhub.com/files/170803235/3876e36e-f6f3-427b-8f5b-e06b21ab49e6/download](https://app.zenhub.com/files/170803235/3876e36e-f6f3-427b-8f5b-e06b21ab49e6/download)

![Screen Shot 2021-11-17 at 11.32.44 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/7aad67ea-1ef8-4d78-93d7-432b5ab8916d)

**Comment by VinayKumar1591** [comment]
@arun-magma as per testcase service reject is expected from AGW, But TMSI in service request is same as sent in registration accept. So to pass the testcase TMSI needs to be modified or exclude 5G Uplink status in service request to expect service reject we can use below causes
1. wrong TMSI - ue id can not be derived 
2. without uplink status IE : conditional IE missing

**Comment by arun-magma** [comment]
Wrong/bad TMSI is injected in SReq, lets validate. @NeelimaKalpana

**Comment by NeelimaKalpana** [comment]
Hi Arun,

I Executed the TC7d and it is passing now.
[https://app.zenhub.com/files/170803235/55fdd82c-72c1-4c41-9f9d-6ea119e71625/download](https://app.zenhub.com/files/170803235/55fdd82c-72c1-4c41-9f9d-6ea119e71625/download)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/86dc83c8-f623-4b5d-ac7d-0d3e158264a8)

**Comment by arun-magma** [comment]
let's close this Ticket as Expected behavior is achieved.
