### ISSUE TITLE
GCC warning annotations seen on unrelated PR

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#10166]
https://github.com/magma/magma/pull/10149/files <- seeing some unrelated GCC warning annotations. Might be good to address these.

In case the annotation goes away, I'll take screenshots of the warnings. 

<img width="1229" alt="Screen Shot 2021-11-08 at 10 50 08 AM" src="https://user-images.githubusercontent.com/37634144/140773634-4bd532c3-7927-4e4e-bc85-d0f07cdf9aec.png">

**Comment by themarwhal** [comment]
Wasn't sure who to assign as an owner, so I'll just ping all the names I get from git for each line above.

* lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L36, lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L37 @panyogesh 
* lte/gateway/c/core/oai/tasks/nas/emm/Attach.c#L1076 @pruthvihebbani 
* lte/gateway/c/core/oai/tasks/mme_app/mme_app_statistics.c#L26 @ulaskozat 
* lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c#L798 @ulaskozat (this looks like a cherrypick from something else though)
* lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c#L1229 @ganeshg87 
* lte/gateway/c/core/oai/tasks/amf/amf_config.c#L394 @ganeshg87

**Comment by ulaskozat** [comment]
@sureshgorijavolu can you follow up on the 5G functions?

**Comment by ulaskozat** [comment]
PR raised for lte/gateway/c/core/oai/tasks/mme_app/mme_app_statistics.c#L26 (cc @themarwhal)

**Comment by themarwhal** [comment]
I'm also seeing GCC warnings on the OAI Jenkins job. https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/8981/artifact/build_results_magma_oai_mme.html
<img width="1248" alt="Screen Shot 2021-11-16 at 6 00 09 PM" src="https://user-images.githubusercontent.com/37634144/142079947-8dbe1a35-7fc1-49d1-b9d2-94cc036431ce.png">
Can we take care of these as well? @sureshgorijavolu

**Comment by panyogesh** [comment]
> I'm also seeing GCC warnings on the OAI Jenkins job. https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/8981/artifact/build_results_magma_oai_mme.html <img alt="Screen Shot 2021-11-16 at 6 00 09 PM" width="1248" src="https://user-images.githubusercontent.com/37634144/142079947-8dbe1a35-7fc1-49d1-b9d2-94cc036431ce.png"> Can we take care of these as well? @sureshgorijavolu

Sure Marie. I have created a ZenHub task and assigned it (10367). Will address them shortly.

**Comment by themarwhal** [comment]
Looks like these are the remaining ones:
see https://github.com/magma/magma/runs/5225556056?check_suite_focus=true
```
Warning: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:36:19: warning: initialization of 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  Imsi_t,  struct ip_flow_dl *, uint32_t,  char *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct <anonymous>,  struct ip_flow_dl *, unsigned int,  char *)'} from incompatible pointer type 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  uint32_t,  uint32_t,  Imsi_t,  struct ip_flow_dl *, uint32_t,  char *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  unsigned int,  unsigned int,  struct <anonymous>,  struct ip_flow_dl *, unsigned int,  char *)'} [-Wincompatible-pointer-types]
[162](https://github.com/magma/magma/runs/5225556056?check_suite_focus=true#step:7:162)
Warning: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:37:19: warning: initialization of 'int (*)(struct in_addr,  struct in6_addr *, struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  struct ip_flow_dl *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct ip_flow_dl *)'} from incompatible pointer type 'int (*)(struct in_addr,  struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  struct ip_flow_dl *)' {aka 'int (*)(struct in_addr,  struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct ip_flow_dl *)'} [-Wincompatible-pointer-types]
[163](https://github.com/magma/magma/runs/5225556056?check_suite_focus=true#step:7:163)
Warning: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:40:24: warning: initialization of 'int (*)(Imsi_t,  struct in_addr,  struct in6_addr *)' {aka 'int (*)(struct <anonymous>,  struct in_addr,  struct in6_addr *)'} from incompatible pointer type 'int (*)(struct in_addr)' [-Wincompatible-pointer-types]
[164](https://github.com/magma/magma/runs/5225556056?check_suite_focus=true#step:7:164)
Warning: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:41:27: warning: initialization of 'int (*)(struct in_addr,  struct in6_addr *)' from incompatible pointer type 'int (*)(struct in_addr)' [-Wincompatible-pointer-types]
```

**Comment by ardzoht** [comment]
Latest compilation warnings from Jenkins OAI: https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/lastSuccessfulBuild/artifact/build_results_magma_oai_mme.html
