### ISSUE TITLE
Shared Sentry mconfigs

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#10170]

**Comment by Neudrino** [comment]
Is this issue still valid? Are there any open points here?

As far as one can see from https://github.com/magma/magma/issues/9508, this would be the last subtask for that bigger issue, right?

@christinewang5 @hcgatewood @themarwhal

**Comment by themarwhal** [comment]
@Neudrino I think this can be closed now! Maybe a good follow up task is to migrate some of our lab setups to use the orc8r streamed config now.
