### ISSUE TITLE
Adding testcases for the issue 10185

### ISSUE THREAD

**Issue by VinayKumar1591** [magma/magma#10196]
steps to add test case

Testcase 1:

1. Initiate NG Setup procedure
2. Do not add NGAP IE UeContextRequest in Initial UE Message and initiate registration procedure
3. Complete Registration Procedure 
     i. Verify Initial Context Setup Request is not received at GNB and Registration accept sent in DL_NAS_Transport
4. Initiate UeContext Release procedure for the user inactivity and wait for complete of UE Context Release Procedure
5. Do not add NGAP IE UeContextRequest in Initial UE Message and initiate service request procedure for the signaling
6. Wait for Service request procedure completion 
   i. Verify Initial Context Setup Request is not received at GNB and service accept sent in DL_NAS_Transport

7. Initiate and complete  DeRegistration procedure

Testcase 2:
1. Initiate NG Setup procedure
2. 2. Do not add NGAP IE UeContextRequest in Initial UE Message and initiate registration procedure
3. Complete Registration Procedure 
     i. Verify Initial Context Setup Request is not received at GNB and Registration accept sent in DL_NAS_Transport
4. Initiate Pdu Session establishment request 
5. Wait for pdu session establishment accept and Initial context setup request which includes pduSessionResourceSetupListCtxReq IE and UEAggregatedMaxBitRate
6. Complete ICS Procedure
7. Initiate and complete pdusessionRelease Procedure
8. Initiate and complete DeRegistration Procedure

Attached PCAP for reference 
[Uploading... Without-ICS-Flag.pcap]

**Comment by arun-magma** [comment]
TC66 and TC67 are added, scripts are available to validate

**Comment by arun-magma** [comment]
Closing this ticket inacase any changes needed we can reopen.
