### ISSUE TITLE
Gx/Gy ReAuthRequest fails if FUI is sent on session Init

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#10214]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:** Orchestrator, Access Gateway, & FeG
- **Affected Subcomponent:** Session_proxy
- **Deployment Environment:** AWS (orc8r & FeG), bare-metal (AGW)

### Describe the Issue

When UE joins with Gy/Gx relay enabled, and subscriber has zero balance and receives FUI in CCA-I, if the PCRF or OCS triggers a ReAuthRequest this results in 5012 and 3002 in response from Magma (Gy and Gx respectively) when FeG is unable to resolve AGW HW ID for IMSI. 

However, session is established and after validity time expiry, Magma sends CCR-U, gets quota in CCA-U and subscriber can then pass data, but due to Gx failure, using the wrong policy. 

**To Reproduce**
1. Configure network with external PCRF and OCS with Gx Gy relay enabled
2. Configure two policy rules for high speed at and low speed data (any speeds, just rules for Gx to trigger)
3. Configure subscriber with zero balance (and configure zero balance user to get low speed rule)
4. Attach the UE to the network
5. observer that FUI is sent on Gy and magma creates session, but with redirect
6. observe that low speed rule is sent on Gx and magma installs
7. perform top up to add balance to the subscriber
8. observe the ReAuth Request on Gy and Gx (where Gx signals to install high speed rule)
9. observe magma reply with 5012 and 3002 respectively
10. observe magma sends CCR-U due to validity time after timer expiry (we use short validity timer 100s)
11. observe UE can now suffer data after reauth, but low speed rule still in place cause step 8 failed/was rejected when lookup failed. 

**Expected behavior**
When session is initiated with FUI, magma needs to record AGW HW ID for this session so FeG and perform lookup. It seems this only happens for session initiate with balance. 

**Additional context**
Logs. 
```

I1109 23:58:50.886196       1 logcodec.go:46] Sending: *protos.ChargingReAuthRequest: {
	"session_id": "IMSIxxxxx0000000015-860826",
	"charging_key": 0,
	"sid": "IMSIxxxxx0000000015",
	"type": "ENTIRE_SESSION",
	"service_identifier": null
}
E1109 23:58:50.907039       1 handlers.go:51] Error relaying reauth request to gateway: rpc error: code = Unknown desc = unable to get HwID from IMSI IMSIxxxxx0000000015. err: could not find gateway location for IMSI: IMSIxxxxx0000000015

```

I can share magmad, sessiond, session_proxy, and pcaps privately as they contain customer data.

**Comment by joary** [comment]
Issue workarounded by configuring `/var/opt/magma/configs/state.yml` with

```
sync_interval: 2
```

**Comment by crbertoldo** [comment]
Our current setup with no failure, per this issue, has:
`sync_interval: 2`
and 
`/usr/local/lib/python3.5/dist-packages/magma/magmad/main.py line 128, default = 60, new setting = 4`
@jpad-freedomfi @joary @uri200

**Comment by uri200** [comment]
Thanks @crbertoldo  and @jpad-freedomfi 

We are thinking on better solutions to avoid having to set synch to 2 seconds.

For now let's use this workaround

**Comment by joary** [comment]
Closing this one, @uri200 , If you intend to create another to track the "final solution", please tag it here to be documented to others.
