### ISSUE TITLE
Request for TC43d and TC43e (Verify Authentication Reject with Cause #24 and Cause #23) script change.  

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#10221]
Currently in daily regression TC43d and TC43e are failing as magma code is not supporting Authentication reject.

Could you please change those scripts to validate Security reject instead of Authentication reject.

Please find the pcaps and logs below:
[https://app.zenhub.com/files/170803235/0b779aaa-4f37-4df1-a3ef-5b390e6578b5/download](https://app.zenhub.com/files/170803235/0b779aaa-4f37-4df1-a3ef-5b390e6578b5/download)[https://app.zenhub.com/files/170803235/ca01ea84-0ab5-4f2e-9ddf-49fd36f338a9/download](https://app.zenhub.com/files/170803235/ca01ea84-0ab5-4f2e-9ddf-49fd36f338a9/download)

**Comment by arun-magma** [comment]
Evaluating the Move to "Security Reject" procedure

**Comment by arun-magma** [comment]
Done, included Cause 24 & cause 23 in Security Reject, Separate TC43g & Tc43h are added and scripts are ready to evaluate, Kindly validate. 

Let us know if TC43d and TC43e are still in plan to develop, accordingly would change the priority.

**Comment by panyogesh** [comment]
The changes for are already merged. Will try to execute on 140 and update.

**Comment by panyogesh** [comment]
Just to clarify 
1. Cause #23 (TC43e) : Implemented as per 
 ETSI TS 124 501 V15.6.0 (2020-01) [Section : 5.5.1.2.8 Abnormal cases on the network side i) UE security capabilities invalid or unacceptable ]  

Expected Behavior : If AMF does not agrees on UE Security Capability Registration Request will be sent (Cause is left to network and in AMF its chosen to be #23). 

2. Cause #24 (TC43d) : This as per the understanding will be generated by UE (Security Mode Reject). So I guess this is not applicable for AMF. If there is any section which tells about the support in AMF (or network) kindly let us know.

**Comment by panyogesh** [comment]
Can we look onto TC43g and TC43h from the above updates and let know the inputs.

**Comment by arun-magma** [comment]
Working on this & will update very soon

**Comment by arun-magma** [comment]
Hi @panyogesh: More Ref and example traces (TVM SA Core tested) enclosed, Please let us know if this hold good to implement in AGW.

TC43d :
UE returns Auth Failure with cause-24 (Security Mode Rejected)
AGW may respond with Auth Reject

[Sample other SA core traces]
![Screen Shot 2021-12-02 at 11.22.53 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/9bd5b47b-5636-4aeb-bdf6-25f2612ca4f7)

[https://app.zenhub.com/files/170803235/7aab8c4e-1d18-4bff-878b-17b3577ff6f6/download](https://app.zenhub.com/files/170803235/7aab8c4e-1d18-4bff-878b-17b3577ff6f6/download)

TC43e:
UE returns Auth Failure with cause-23 (UE security Cap Mismatch)
AGW may respond with Auth Reject

[Sample other SA core traces]
![Screen Shot 2021-12-02 at 11.23.09 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/c34049be-93e6-4e55-8882-08380b35f29a)

[https://app.zenhub.com/files/170803235/9c42f5dd-7281-4bee-99be-0748dc840ea0/download](https://app.zenhub.com/files/170803235/9c42f5dd-7281-4bee-99be-0748dc840ea0/download)

**Comment by rupa455wavelabs** [comment]
Closing this issue, as the issue got resolved.
