### ISSUE TITLE
[Qos]: Encoding is not proper in the downlink-PDUEstablishmentAccept message.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10220]
### Your Environment

Version: magma/focal-ci, now 1.7.0-1636428543-ef82f726
Affected Component : Access Gateway
Affected Subcomponent : AGW service
Deployment Environment : Vagrant (AGW)

### Describe the Issue

To Reproduce
1. Configure an APN with ambr values other than default values.
2. Try to configure a Qos-Profile with ambr values.
3. Bind the Qos-profile and APN on the subscriber.
4. Trigger the PDU session from UE with AON name configure.
5. Check that PDU-Session is coming up with configured ambr's by validating the packets.
6. Noticed that configured ambr's values are not getting decoded properly.

**Expected behavior**
PDU-Session should come up with configured values.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/2da71842-9cb0-44b8-a60a-3be8c9a25a51)[https://app.zenhub.com/files/170803235/3f0fb030-b4cf-45ca-b6eb-942209f48d89/download](https://app.zenhub.com/files/170803235/3f0fb030-b4cf-45ca-b6eb-942209f48d89/download)

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by NeelimaKalpana** [comment]
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/8df32266-913a-4ffb-b1cb-4dd08c938fbb)

These are the configured values which I am expecting to be displayed in the Accept-Message

**Comment by Lkishor123** [comment]
TeraVM test in progress.

**Comment by Lkishor123** [comment]
PR raised: https://github.com/magma/magma/pull/10474.
