### ISSUE TITLE
Add integration testcase for CoreNetworkType restrictions of Subscriber.

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#10246]
Introduced "Forbidden Network Type" attribute per Subscriber. to restrict the access to the network. If not configured, Subscriber will have access to all Network Types by default.

Refer PR [#9161](https://github.com/magma/magma/pull/9161) (Orc8r changes)
PR #[9165](https://github.com/magma/magma/pull/9165)(NMS changes)
PR [#9775](https://github.com/magma/magma/pull/9775) (AGW changes).

**Comment by arun-magma** [comment]
Hi Anusha, I'm handling TeraVM compliance test, Like to inform you that I'm not handling Integ test, Please route this ticket to right person. @panyogesh should be able to guide you, Thanks!
