### ISSUE TITLE
Requesting for Usage report and charging report testcase list automated in TeraVM for 5G.

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#10247]
Requesting for Usage report and charging report testcase list automated in Teravm setup for 5G traffic flows.

**Comment by arun-magma** [comment]
Please Detail the Test cases with Pre & Post conditions, Thanks!

**Comment by arun-magma** [comment]
As discussed with Yogesh currently there is no plans for Quota Management to external reporting entities such as PCF or CF, current reporting is planned for only Metrics Monitoring in Orc8r, please add details about the flow of this usage & charging report to automate it.

**Comment by prabinakpattnaik** [comment]
Usage report (TX, RX bytes), credit/charging functionality support for 5G as similar to 4G towards Orc8r.

**Comment by prabinakpattnaik** [comment]
[PCF_SMF_AMF_Design_Proposal_Changes.docx](https://github.com/magma/magma/files/7560776/PCF_SMF_AMF_Design_Proposal_Changes.docx)

Attached proposal document, please go thro the section "configuration of session proxy service" and services for sessionreporter for existing (4g) and New changes for 5g

**Comment by arun-magma** [comment]
We are evaluating the efforts to introduce orc8r monitoring in Auto Framework
