### ISSUE TITLE
[AMF]:  Mapping imsi_amf_ue_id_htbl and tun11_ue_context_htbl to existing protos in oai for stateless feature

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#10266]
1. 
Check if the existing OAI protos will serve the purpose for storing/restoring the imsi_amf_ue_id_htbl and tun11_ue_context_htbl

2.
Put the design if new proto message is required or an existing proto needs to be changed.

**Comment by shashidhar-patil** [comment]
Analyzed the existing OAI protos. The existing protos for global tables will serve the purpose. No changes are needed.
![structAndprotos.png](https://images.zenhubusercontent.com/613855e61bcb9d0f761befab/177fe079-d61e-410c-b875-b4994b5d170b)

**Comment by shashidhar-patil** [comment]
### **Mapping and analysis of exisiting Protos with amf_ue_context_t.**

**Existing implementation:** mme_app_desc_t was converted to MmeNasState proto, 
                                       internally hashtable structure(mme_ue_context_t) was converted to protbuf::map( MmeUeContext).
									   
**Changes :** 
1) Completed: Converted hashtable(amf_ue_context_t) to Map as part of PR #10072
2) To Do: Have to convert amf_app_desc_t to MmeNasState proto, internally convert map structure (amf_ue_context_t) to protbuf::map(MmeUeContext).

**Conclusion:** Existing proto MmeUeContext is sufficient for the global maps (amf_ue_context_t).

**Detailed Comparison:**
![structToProtoComparison.png](https://images.zenhubusercontent.com/613855e61bcb9d0f761befab/2eae4da8-e961-4884-8ec3-80ad48c550d5)

**Next step:** 
1) Implement AmfNasStateConverter and AmfNasStateManager base code.
2) Implement state_to_proto and proto_to_state in AmfNasStateConverter.
3) Implement the helper functions like guti_to_string and string_to_guti.
