### ISSUE TITLE
[Multi-Session] AMF is send Release command when there is a unsuccessful session for the requested sessions from UE.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10304]
### Your Environment

- Version: 1.7.0-1636755075-921ff014
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue

Try to send multiple PDU-Sessions(4-Sessions) from UE , and make sure that AMF can server only few session(say 2-Sessions) and check that successful sessions should be maintained for the given IMSI.

To Reproduce
1. From NMS-Dash board configure subscriber with 2-APN's attached(say : internet1 and internet2). 
2. From UE request 4 sessions with DNN/APN's as internet1,internet2,internet3 and internet4.
3.Check that UE is sending 4-PDU-Session Requests.
4. AMF is serving first 2 sessions and once 3 reuqest is received amf -s sending PDU-reject with error code and releasing the context of UE which is deleting all sessions.

**Expected behavior**
AMF- should maintain all the sessions which are successful.

Please fine the logs and pcaps from the attachment.[https://app.zenhub.com/files/170803235/c9fd0264-76e1-4bb7-b133-4f8a3ab2e7d7/download](https://app.zenhub.com/files/170803235/c9fd0264-76e1-4bb7-b133-4f8a3ab2e7d7/download)

**Comment by ganeshg87** [comment]
PR is under review
https://github.com/magma/magma/pull/10453

**Comment by ganeshg87** [comment]
Hi @NeelimaKalpana ,
 updated binary, please validate P0 & P1 cases
https://drive.google.com/file/d/10PJ6zpFkx1mfao1wcjNOLNj3HcQ9yNis/view?usp=sharing

**Comment by ganeshg87** [comment]
PR merged to master, https://github.com/magma/magma/pull/10453
