### ISSUE TITLE
[subscriberdb]: Suci decryption changes for Profile-A and Profile-B

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#10303]
Suci decryption changes for Profile-A and Profile-B

1. 
CLI change to configure profileA and profileB 

2. 
Have the decryption libraries as part of subscriberdb

3.
Unit testcases for the features.

**Comment by rupa455wavelabs** [comment]
https://github.com/magma/magma/pull/10469/ PR raised by Kaleem and got merged into master.

closing the issue as PR got merged into master
