### ISSUE TITLE
[Multi-Session]: PDU-Session retry is happening , after correction of APN info in the subscriber according to UE  requested sessions.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10306]
Your Environment
-Version: 1.7.0-1636671684-31d6df13
-Affected Component:Access Gateway
-Affected Subcomponent:AGW service
-Deployment Environment:Vagrant (AGW)

### Describe the Issue
**To Reproduce**
1. Configure the subscriber with 1 APN's attached.
2. Try to trigger the PDU-session from UE with 2 APN's where one APN will match with subscriber configuration
3. Check that PDU-Session is coming up successfully for the matching DNN/APN name.
4. Trigger deregistration from UE.
4. Now edit the subscriber with adding one more APN on subscriber which is matching with the UE-Requested APN.
5. Trigger the PDU-Session from UE again.
6. PDU-Session retry is happening for the first request which is successful at the first time and after deregistering the session and triggering it again both sessions are successful.

**Expected behavior**
Both sessions should be successfully up after correcting the APN/DNN info.

[https://app.zenhub.com/files/170803235/32ec9b58-d2b2-4d3d-a258-b967a6a64971/download](https://app.zenhub.com/files/170803235/32ec9b58-d2b2-4d3d-a258-b967a6a64971/download)Please find the logs and pcaps from attachement.

**Comment by ganeshg87** [comment]
PR merged on magma 
https://github.com/magma/magma/pull/10635
