### ISSUE TITLE
feat(agw): enable M1 macs by working around VirtualBox

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#10300]
### Your Environment (If applicable)

- **Version:** MacBook Air (M1, 2020)m
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** Vagrant (AGW)

### Describe the problem

**Description**
The development process relies on VirtualBox, which doesn't run on a mac with an M1 chip. This is not an issue of waiting for VirtualBox to be ported to M1 - the VB team has specifically said they will not. 

**Additional context**

The [quick start](https://docs.magmacore.org/docs/basics/quick_start_guide) directs developers to provision the AGW VM using Vagrant:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/111581/141830593-09a647b9-9931-4f90-9be1-4910de749c7c.png">

However, Virtualbox does not run on current-generation Macs with an M1 chip:

![image](https://user-images.githubusercontent.com/111581/141830282-ed8f3560-8980-4806-9b3c-3aed016a048f.png)

The text of the error is:

<pre>There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp</pre>

To see discussion of the same underlying issue in a different project, not Magma, see  https://github.com/hashicorp/vagrant/issues/12105 . 

[Discussion of this issue within the Virtualbox community](https://forums.virtualbox.org/viewtopic.php?t=98742): says <q>there will be no port, for the same reason that VirtualBox isn't available on an iPhone. VirtualBox is not a CPU emulator, it requires x86 CPU.</q>

### Describe your idea (optional)

**Description**

There are two paths to a solution:

1. Remove Intel dependency
2. Rearchitect to use a proper emulator (e.g. Rosetta) and a different VM

**Desired timelines**

As M1 chips grow as a proportion of all developer laptops, there will be more and more pressure to find a solution.

**See also**

https://github.com/magma/magma/issues/10297

**Comment by hcgatewood** [comment]
cc @ulaskozat @ardzoht @electronjoe

**Comment by electronjoe** [comment]
I recognize that it appears a VM is necessary for certain testing of our datapath (at least so long as we rely on Open VSwitch - pending migration to EBPF at some future time). So finding another VM provider is likely - pending that datapath breakthrough - a blocker (and I guess it could be required for EBPF datapath tests also, I don't know).

But I want to also toss out that the vast majority of tests do not require these VMs and it would be very nice to see them migrated to lower overhead / simpler test environments (e.g. containers - if required).  This makes the majority of our test coverage executable in environments friendly to e.g. cloud development (such as GH Codespaces). And further any VM required tests could be offloaded to CI orchestration for many PRs (though perhaps not all development) - enabling ~full workflows for many without requiring nearly such intense local compute resources.  I think it further promotes best practicers - like avoiding state between test runs (our present VM workflows often mislead - with state accumulating over time - unless you are cautious to regularly destroy them / reprovision).
