### ISSUE TITLE
Correct gRPC message set (AMF-SMF and SMF-AMF) for UE IP address.

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#10305]
We have found that UE IP address in gRPC message (AMF-SMF and SMF-AMF) is setting wrong message. So that it is difficult to extend for IPv6 and IPv4IPv6 support.

It should be set below message:
message CommonSessionContext {
  SubscriberID sid = 1;
  string ue_ipv4 = 3;
  string apn = 4;
  bytes msisdn = 5;
  RATType rat_type = 6;
  // PDU session state to mirror with AMF or MME
  SMSessionFSMState sm_session_state = 7;
  uint32 sm_session_version = 9;
  string ue_ipv6 = 10;
  // TEIDs corresponding to the default bearer
  Teids teids = 11;
}

**Comment by mehul-jindal** [comment]
[15-Nov-2021 : Mehul]Following PR has been raised https://github.com/magma/magma/pull/10318

**Comment by prabinakpattnaik** [comment]
The PR has been merged into master branch. Hence this task will mark as a close
