### ISSUE TITLE
[Qos] configured Qos-profile info with flow control is not getting updated in PDU-Session

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10316]
-Version: 1.7.0-1636671684-31d6df13
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue

Configured Qos-Flow info is not updating while PDU-Session is served by AMF.

To Reproduce
1. Configure proper Qos-Profiles with proper flow configurations
2. Bind the profile on Subscriber.
3. Trigger the PDU-Session 
4. Check that PDU-Session is coming-up with configured flow-controls.

**Expected behavior**
Configured flow values should get updated in the PDU-Session.

Note : Observation AMF is not sending PDU-Accept message.

Please check the attachment for logs and pcap.[https://app.zenhub.com/files/170803235/b8decc56-2d97-4fef-89b3-575add6dc12a/download](https://app.zenhub.com/files/170803235/b8decc56-2d97-4fef-89b3-575add6dc12a/download)

**Comment by moinuddin1980** [comment]
Looks to be duplicate as that #10434.
Hence, this can be closed

**Comment by rupa455wavelabs** [comment]
Verified with latest master code and observed that info with flow control is updating in PDU Session, Please find the attached logs and pcaps for the reference.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/16fde4cb-c98d-4106-bb7b-c449f9abd83c)
[https://app.zenhub.com/files/170803235/b3a0c20f-69e3-40f0-be55-cf8054a2b315/download](https://app.zenhub.com/files/170803235/b3a0c20f-69e3-40f0-be55-cf8054a2b315/download)
