### ISSUE TITLE
bug(agw): invalid IP address in Vagrantfile

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#10328]
### Your Environment

- **OS Version:** MacOS Monterey 12.0.1
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Vagrant
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

Provisioning the AGW VM per the Quick Start leads to error "IP address configured for the host-only network is not within the allowed ranges"

**To Reproduce**

1. Run through Quick Start to "Terminal Tab 1: Provision the AGW VM" section
2. `cd lte/gateway`
3. `vagrant up magma`

<pre>The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.

  Address: 192.168.129.1
  Ranges: 192.168.56.0/21</pre>

**Expected behavior**
VirtualBox should boot

**Screenshots**

![image](https://user-images.githubusercontent.com/111581/141847673-cd44773d-2cad-4434-aac4-9b12edba76d3.png)

**Additional context**

The IP is set in `magma/lte/gateway/Vagrantfile`

**Comment by Neudrino** [comment]
This issue was probably
- introduced in https://github.com/magma/magma/pull/11926
- fixed and discussed in https://github.com/magma/magma/pull/12897
- re-introduced in https://github.com/magma/magma/pull/13010

**Comment by ssanadhya** [comment]
@lucasgonze , @Neudrino , this is not really a bug, but a misconfiguration on the Vagrant Box setup. See https://github.com/magma/magma/pull/13010#issuecomment-1168561341 . Resolution in #13100

**Comment by Neudrino** [comment]
Fixes for this bug are in:
- https://github.com/magma/magma/pull/13126 for CI
- https://github.com/magma/magma/pull/13100 for local setup
