### ISSUE TITLE
is it possible to disable Gx only ?

### ISSUE THREAD

**Issue by DishNet** [magma/magma#10330]
# TITLE OF YOUR PROPOSAL

## Problem

The raw idea, a use case, or something that motivates acting on this proposal

## Solution

The core elements of the solution, presented concisely, targeting an audience with high-breadth but low-depth understanding of Magma

## Non-goals

Anything specifically excluded from the concept

**Comment by uri200** [comment]
You can try this 
https://docs.magmacore.org/docs/feg/configure_federation#disable-gx--gy

I think it only works for OMNIrules. Meaning, you will not have PCRF so you need to define some kind of rule. If you want to use OCS you will need to define a rule with a charging key.  That rule will apply for all the subscribers.

I don't think this works for regular rules you define on orc8r per subscriber. Only omni rules
