### ISSUE TITLE
[TeraVm Regress] QFI values mismatch in PDU session & GTP extension header

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#10339]
Title: QFI values mismatch in PDU session & GTP extension header

Tested build: 1.7.0-1636994247-c191f41e

Issue:

QFI: 9 in PDU session Establish Accept
QFI: 5 in GTP Extension header

TC:  SA_TC9_AMF_Initiated_Paging

Expectation:  QFI value match in PDU session and GTP Ext header 

Here are the pcaps and snaps.

[https://app.zenhub.com/files/170803235/ab9788ed-33fb-4c3f-ac0d-89dc313d7780/download](https://app.zenhub.com/files/170803235/ab9788ed-33fb-4c3f-ac0d-89dc313d7780/download)

Snaps which has QFI values captured in PDU session Est Accept and GTP Header

![Screen Shot 2021-11-15 at 10.58.33 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/0b613b38-f6b2-49a9-9a48-9ef6dae8e29c)

![Screen Shot 2021-11-15 at 10.58.12 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/0acc5b38-0805-4dc7-accd-1fbaa2accae7)

**Comment by prabinakpattnaik** [comment]
@arun-magma , QFI functionality not yet supported in OVS. For downlink traffic, QFI value is set to 5 (Hardcoded)

**Comment by arun-magma** [comment]
@panyogesh: As discussed we need to find a Matching QFI value in PDU Session Est Accept and QFI on GTP ext header, Can we hardcode either one of the side to match it ?

This will help to resolve the DL GTP traffic mapping issues @ gNodeB which would keep connection oriented Traffic Cases (TCP cases) in good shape.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

For making TCP traffic flow we need to configure QFI as 5.

**Comment by arun-magma** [comment]
Hi @NeelimaKalpana , These values seems hardcoded from AGW, need support to match it in code to have QFI=5 in PDU Accept, once implemented we can try run this TCP test as GTP-Ext header already populated QFI=5.

**Comment by arun-magma** [comment]
@NeelimaKalpana @prabinakpattnaik @panyogesh 
1. PDU Accept:  QFI = 9
2. UL GTP Ext Header: QFI=9 (Teravm Adopts from PDU Accept)
3. DL GTP Ext Header: QFI=5

As requested earlier need a support to change in AGW code to match above #1 & #3 to same QFI value, either 5 or 9 is okay, This is blcoking TCP test in teravm & root cause of TC-52 failure.

AGW pcap: 
[https://app.zenhub.com/files/170803235/064e917d-ccfe-4423-b579-47e16d34fa26/download](https://app.zenhub.com/files/170803235/064e917d-ccfe-4423-b579-47e16d34fa26/download)

Snap of pcaps

[PDU Accept:  QFI=9]
![Screen Shot 2022-01-12 at 7.58.53 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/f253ee2a-502b-46af-b7c3-2aa43e109828)

[UL GTP Ext Header: QFI=9]
![Screen Shot 2022-01-12 at 7.59.50 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/21702b38-8c04-4b60-9402-58988268e8fa)

[DL GTP Ext Header: QFI=5]
![Screen Shot 2022-01-12 at 8.00.04 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/3915d632-84d6-4273-ac27-7993f2e3fbeb)

**Comment by arun-magma** [comment]
++ Relevant Dev ticket for Ref 
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/9452
