### ISSUE TITLE
[AMF]: Fixing compilation warning as reported in 10116 & 10289

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#10367]
This is regarding the compilation warning fixes in AMF/NGAP code reported as part of https://github.com/magma/magma/pull/10289

Detail Report : 
1.
https://github.com/magma/magma/issues/10166

2.
https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/8981/artifact/build_results_magma_oai_mme.html

**Comment by RahulKalsangra** [comment]
merged as pr  #10401
