### ISSUE TITLE
Gx ReAuth Failure with: Queue does not exists for gwID

### ISSUE THREAD

**Issue by joary** [magma/magma#10379]
### Your Environment

- **Version:1.5**
- **Affected Component:** FeGW
- **Affected Subcomponent:** session_proxy

### Describe the Issue

In the scenario of connectivity lost between Orc8r and AGW, if a FeG call is made during AGW offline time, session_proxy fails to find the queue for the target AGW. 

session_proxy fails to find the queue for the target 

```
Error relaying Gx reauth request to gateway: rpc error: code = Internal desc = err sending request gwId:"XXXXXXXXXXXXXX" authority:"sessiond" path:"/magma.lte.SessionProxyResponder/PolicyReAuth" headers:<key:"Content-Type" value:"application/grpc" > headers:<key:"Te" value:"trailers" > headers:<key:"User-Agent" value:"grpc-go/1.31.0" > payload:"\000\000\000\000P\n\032IMSIXXXXXXXXXXXX-489529\022\023IMSI3XXXXXXXXXXX\032\016InternetMedium2\r\n\013InternetLow"  to gateway: Queue does not exist for gwId XXXXXXXXXXXXXXXXXX
```

**Expected behavior**

Assuming the AGW connectivity lost is very short, FeG should retry to deliver the failed message. Otherwise FeG should answer the federated core with the expected error condition.

**Comment by uri200** [comment]
Maybe this is not the issuem but sometimes ReAuth comes too early and orc8r is doesn;t have the routing information yet. Just to discard this, can you create the   ` /var/opt/magma/configs/state.yml`

And  add this 
```
# sync_interval is set in mconfig. it can be overridden here
sync_interval: 4
```

This will reduce the time it takes AGEs to sync with or8cr. The faster, the earlier the routing information will be to feg relay

If that is not enough we may need to create a new feature to have a temporal cache.

**Comment by uri200** [comment]
by the way error `Queue does not exist for gwId` is triggered by syn rpc. 
So maybe this is not a problem of information not available on orc8r, but orc8r dropping the connection

Note there were some issues opened for this problem, like 

https://github.com/magma/magma/issues/4833

**Comment by crbertoldo** [comment]
Our current setup with no failure, per this issue, has:
`sync_interval: 2`
and
`/usr/local/lib/python3.5/dist-packages/magma/magmad/main.py line 128, default = 60, new setting = 4`
@jpad-freedomfi @joary @uri200
