### ISSUE TITLE
5G SA MultiSession TCs Regression Failing root cause Tracker

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10451]
Hi Arun,

Please arrange the automation TC for Multi session to cover required positive and negative scenarios.

I created TC in the requested format.
Please find the attached document for your perusal and let me know for any additional inputs.

https://wavelabstechnologies.sharepoint.com/:x:/r/sites/Wavelabs-Connectivity/_layouts/15/Doc.aspx?sourcedoc=%7B119DE675-716C-4565-8216-8DEBB2489931%7D&file=Feature_TestCase_Desing_Document.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-ELECTRON.teams.files&wdExp=TEAMS-CONTROL&wdhostclicktime=1637324150718

Thanks and Regards,
Neelima.

**Comment by arun-magma** [comment]
I couldn't access this doc which needs MS account, Kindly add my email id arunkumar@delartech.com or send the offline copy of it / Gdoc link

**Comment by NeelimaKalpana** [comment]
Okay Arun. I will do that.

**Comment by arun-magma** [comment]
TC2c and TC2d scripts are available to validate, Please map it in shared online excel sheet so that will focus on remaining missing scripts scenario.

**Comment by NeelimaKalpana** [comment]
Hi Arun,
For these TC2c and TC2d I should have IMSI subscribed with proper dnn's in  subscriberdb .
So ,  please add respective subscriber with all required apn's , even I am doing this from cli, it is taking configs from orc8 so my apn-configs are getting flushed.
Please do the needful so I can proceed on further validation.

**Comment by arun-magma** [comment]
I Hope you are validating on Dev AGW setup headed with Wlabs orc8r, As discussed in base Multi PDU session tickets use DNN name "internet1 ~ internet8" (8 DNNs in sequence) for this Test case, before run this test case kindly add DNN profile for these list of DNNs and map it in sub db on Sub profile.

**Comment by arun-magma** [comment]
@NeelimaKalpana : In the shared sheet added "Script Prep Queries" (Column E) with scripts related queries and concerns , Kindly check & address inline in the same cell plz.

**Comment by arun-magma** [comment]
Multi PDU session:  8 new TC Scripting (TC2e ~ TC2l) in progress, Current ETA 12/10.

**Comment by arun-magma** [comment]
Hi @NeelimaKalpana @parthiban337 : Scripts are ready for all New Multi PDU session cases, Kindly validate it & let me know, flows are as per given plan in spread sheet, For one of the case i corrected the flow and updated in Column "E" of "Script Prep Notes"
https://docs.google.com/spreadsheets/d/1YH3dDfkehd7aFfEHIbK7_563pMIkMP8B/edit#gid=282628356

[TCs - Multi PDU]
TC2e	MultiSession_UE(IDLE-to-Active)_With_ServiceReq_Mo_Signaling
TC2g	MultiSession_UE_PeriodicRegistration_ConnectedMode
TC2h	MultiSession_UE_PeriodicRegistration_IDLEMode
TC2i	MultiSession_1Invalid_Sessions_With_DNNMissing value
TC2j	MultiSession_1Invalid_Sessions_With_DNNMissing IE
TC2k	MultiSession_1Invalid_Sessions_With_Invlide_Session_Type
TC2L	MultiSession_1Invalid_Sessions_With_Invalid_PDU_SessionID

**Comment by arun-magma** [comment]
Once the validation goes good let me know we would soon add it in Daily Regression.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

I will execute the TC's and update the feedback.
I was on leave so couldn't respond back.

**Comment by arun-magma** [comment]
@NeelimaKalpana : Added one more for "unsupported DNN", kindly validate.
TC2M	Multisession_Cause #27 – Missing or unknown DNN

**Comment by rupa455wavelabs** [comment]
sure @arun-magma , Thank you. we will update after validating the TC.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

This is regarding TC2j and TC2i
TC2j MultiSession_1Invalid_Sessions_With_DNNMissing IE
TC2i MultiSession_1Invalid_Sessions_With_DNNMissing value


TC verdict is failing hear:
In this particular scenario we should not expect PDU_Reject with  Missing dnn error code , as amf will pick the exisiting apn/dnn to serve the request.

In case of Multi-Session we will have a set of subscribed-apn's so we should expect pdu is coming up with first apn in the subscribed list.

Please find the pcaps and verdict logs for your reference.Please change the verdict accordingly.

And also a small observation is we are triggering 4 sessions and we are noticing 5-sessions triggering from TC flow. Please provide clarity on the same.

I am sorry from my end as I missed updating the expectation in the Scenario document for this TC.
[https://app.zenhub.com/files/170803235/7087adab-2629-4446-82a6-c91dcfae1708/download]
(https://app.zenhub.com/files/170803235/7087adab-2629-4446-82a6-c91dcfae1708/download)

[https://app.zenhub.com/files/170803235/00abd97a-2109-4328-99ae-759f2e842da5/download](https://app.zenhub.com/files/170803235/00abd97a-2109-4328-99ae-759f2e842da5/download)

**Comment by NeelimaKalpana** [comment]
TC2e MultiSession_UE(IDLE-to-Active)_With_ServiceReq_Mo_Signaling
TC2g MultiSession_UE_PeriodicRegistration_ConnectedMode
TC2h MultiSession_UE_PeriodicRegistration_IDLEMode
TC2L MultiSession_1Invalid_Sessions_With_Invalid_PDU_SessionID
TC2M Multisession_Cause #27 – Missing or unknown DNN

Control plane verdict is passing and as expected in all above cases. But traffic is failing so TC is failing. Once the issue got fixed we will update.

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

In following scenarios we are observing Number of sessions getting triggered is one more than the requested number of session.


And In this case I can see de-regestration is not getting triggered for all the sessions.


We are requesting 3 session and can see 4 PDU-Establishment requests getting triggered and only 3 sessions are getting release.
TC2i , TC2j ,TC2l ,TC2k ,TC2m
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/b0bac0c2-e577-4bea-a14c-62d8b9353110)

Please check the below pcap [https://app.zenhub.com/files/170803235/83cf3b56-e675-433d-9659-a56320fc68f0/download](https://app.zenhub.com/files/170803235/83cf3b56-e675-433d-9659-a56320fc68f0/download) reference.

**Comment by arun-magma** [comment]
This Request seems fit only for TC2I, TC2J and TC2M, Work in progress to include the PDU release, will update on this, Kindly review for TC2L and TC2K.

**Comment by arun-magma** [comment]
PDU Release flow added in TC2I and TC2J for the PDUs established due to DNN errors.

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

I checked TC2l and TC2k pcaps --> They are looking good , initially got bit confused with the flow.
TC2i an Tc2j --->Release command got triggered for all sessions established.
Thanks for the modification provided.

**Comment by rupa455wavelabs** [comment]
Executed Multiple PDU Sessions scenario's with latest magma build(1.7.0-1642806525-9fe73914) 
TC2a - Verify_Max_no_of_PDU_session - Verdict is failing due to UL/DL data loss
TC2c - Verify_Idle_and_Active_Mode_transition_with_Multi_PDU_session - Verdict is failing due to service accept issue & UL/DL traffic data loss.
TC2d - Verify_Paging_with_Multi_PDU_session - Verdict is failing due to service accept issue & UL/DL traffic issue.
TC2e - MultiSession_UEIDLE-to-Active_With_ServiceReq_Mo_Signaling - Verdict is failing due to UL/DL data loss
TC2g - MultiSession_UE_PeriodicRegistration_ConnectedMode - Verdict is failing due to UL/DL data loss
TC2h - MultiSession_UE_PeriodicRegistration_IDLEMode -  Verdict is failing due to UL/DL data loss
TC2i - MultiSession_1Invalid_Sessions_With_DNNMissing_value - Verdict is failing due to UL/DL data loss
TC2j - MultiSession_1Invalid_Sessions_With_DNNMissing_IE - Verdict is failing due to UL/DL data loss
TC2k - MultiSession_1Invalid_Sessions_With_Invalid_Session_Type - Verdict is failing due to UL/DL data loss
TC2L - MultiSession_1Invalid_Sessions_With_Invalid_PDU_SessionID - Verdict is failing due to UL/DL data loss and Number of PDU Establishment Request verdict has to be changed.
verification fail:  ((nas5g_sent_Sess__Establ__Req_=9)    	== (nas5g_received_Sess__Establ__Acc_=4)+(nas5g_received_Sess__Establ__Rej_=1))  => False

TC2m - MultiSession_1Invalid_Sessions_With_Missing_or_unknown_DNN - Verdict is failing due to UL/DL data loss

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/d85c0f89-0a50-4e38-a97e-5c2d1f046dc3)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/2607d166-c21a-4f14-94f4-a6cb56bbe1c6)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/1b39941b-5b66-4d43-80f6-7c3440f4f51b)
Please check the required logs and pcaps
[https://app.zenhub.com/files/170803235/ec0abf52-8fea-4a40-87b6-5fa1037a59a8/download](https://app.zenhub.com/files/170803235/ec0abf52-8fea-4a40-87b6-5fa1037a59a8/download)

**Comment by rupa455wavelabs** [comment]
magma@TVM3-SA:~$ subscriber_cli.py get IMSI222456000000208
sid {
  id: "222456000000208"
}
lte {
  state: ACTIVE
  auth_key: "\213\257G?/\217\320\224\207\314\313\327\t|hb"
  auth_opc: "\216\'\266\257\016i.u\0172fz;\024`]"
}
network_id {
  id: "magmatvmdev"
}
state {
  lte_auth_next_seq: 248
}
sub_profile: "default"
non_3gpp {
  ambr {
    max_bandwidth_ul: 100000000
    max_bandwidth_dl: 200000000
  }
  apn_config {
    service_selection: "internet"
    qos_profile {
      class_id: 5
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 1000000
      max_bandwidth_dl: 1000000
    }
  }
  apn_config {
    service_selection: "internet1"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 6000000
    }
  }
  apn_config {
    service_selection: "internet2"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 2000000
      max_bandwidth_dl: 3000000
    }
  }
  apn_config {
    service_selection: "internet3"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 5000000
    }
  }
  apn_config {
    service_selection: "internet4"
    qos_profile {
      class_id: 5
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 5000000
    }
  }
}

magma@TVM3-SA:~$

**Comment by arun-magma** [comment]
@rupa455wavelabs @NeelimaKalpana : Configs are cross verified and we would use the same for Regression Runs, this Multi session failures need to be tracked separately as all cases are failing, Will add all these cases in "Code Merged" TCs summary.

**Comment by rupa455wavelabs** [comment]
Sure @arun-magma , Thank you.

**Comment by arun-magma** [comment]
@NeelimaKalpana @rupa455wavelabs :
Added 11 Multi session cases in Daily Regression, being monitored in "Code Merged" state.

**Comment by rupa455wavelabs** [comment]
Thanks @arun-magma

**Comment by NeelimaKalpana** [comment]
Hi Arun, 

All multisession cases are failing because of verdict check done for UL/DL traffic.

I am sharing the Verdict logs , and TVM runtime screenshot for your understanding.

Verdict check:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/74111e2d-3f80-4889-b696-f79514277270)

In the above check UE received total bytes over each session is always 0 , even there is traffic flow. Ideally we observed latency of 2 packets per session. Please recheck the verdict validation and correct it .

[https://app.zenhub.com/files/170803235/4d78397d-885b-446f-a7f1-327a8b16a982/download](https://app.zenhub.com/files/170803235/4d78397d-885b-446f-a7f1-327a8b16a982/download)

Arun , I am giving this observation for TC2g , I observed the same thing is happening with all other multisession related cases.

Please revisit the verdict check and do the needful.
Thank you

**Comment by arun-magma** [comment]
@NeelimaKalpana : As discussed DL GTP traffic is not accounted by TVM as There is QFI Mismatch issue.

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

All Multisession TC Control plane is working fine.
Please find the TC Status after OVS-Update :
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/db34f6d8-47bf-4484-be7c-8645b295e379)

But the following cases are failing due to traffic issue.
TC2c ,TC2d ,TC2h 

And TC2l is failing because of below verdict check.
Verdict for TC2l :
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1c8d8490-5d11-4175-99b6-2c283ac801e1)
Please change the verdict check as in this case Expected stats for following messages are as shown below and same thing is observed in controle-plane stats.
nas5g_sent_Sess__Establ__Req_=9
nas5g_received_Sess__Establ__Acc_=4
nas5g_received_Sess__Establ__Rej_=1

But in verdict file your checking for 

nas5g_sent_Sess__Establ__Req_ = nas5g_received_Sess__Establ__Acc_ + nas5g_received_Sess__Establ__Rej_

which is not proper check.
Please correct this verdict also.


Please find attached logs and pcaps for your reference.[https://app.zenhub.com/files/170803235/e82afefc-944e-47e2-80ba-d3b3887ff6e3/download](https://app.zenhub.com/files/170803235/e82afefc-944e-47e2-80ba-d3b3887ff6e3/download)

**Comment by arun-magma** [comment]
Traffic flow in one of the UDP Port "***43" is failing which induce failire of many Multisession TCs, config review in progress at Magma side.

![Screen Shot 2022-03-14 at 11.40.53 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/576b931d-5d42-4ef2-a743-1aa4d025c4c1)
![Screen Shot 2022-03-14 at 11.37.12 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/3da56043-4988-4d99-9e22-596c789ffd0d)

**Comment by arun-magma** [comment]
@panyogesh @NeelimaKalpana : 
[Key issue]
By Looking Closely into the verdict calculation we find on Multi PDU session scenarions Downlink GTP Traffic nos are Zero, It means traffic is not being routed into Mult PDN Tunnels in DL Direction by AGW, Need to debug in OVS to check the flows when this TC is running.

![Screen Shot 2022-03-16 at 10.39.14 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/62ff3a4d-ac09-42a9-86c2-2829b9a65ed5)

@NeelimaKalpana : TC2L verdicts are matched with TC20a, TCs should pass now in CP flows, Plz validate & let me know.

**Comment by arun-magma** [comment]
@panyogesh @NeelimaKalpana @parthiban337 
And we see QFI values are not consistent across Multiple PDNs. Here is the snap & pcap of one the test run, this should be the reason for DL traffic flow issue & TCs failure.

[https://app.zenhub.com/files/170803235/5cad19df-f269-4aa7-8549-3120d502c568/download](https://app.zenhub.com/files/170803235/5cad19df-f269-4aa7-8549-3120d502c568/download)
![Screen Shot 2022-03-22 at 8.45.48 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/01a55c49-5531-4a36-9714-8029e0b828fb)

**Comment by NeelimaKalpana** [comment]
TCs are failing due to traffic failure in regression setup. Control-Plane is working fine.
TC requirements are served , closing for now.
