### ISSUE TITLE
[AMF] AMF is sending PDU-Reject with cause 27 for PDU-Release command from UE.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10479]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- Version: 1.7.0-1637360209-fcdd682f
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue
[AMF] AMF is sending PDU-Reject with cause 27 for PDU-Release command from UE.

**To Reproduce**
1. Add subscriber without attaching APN.
2. Send PDU session request from UE with DNN-Name as empty.
3. Check that PDU-Session is getting rejected are notified.
4. PDU-Session is getting accepted. For PDU-Release from UE AMF is sending PDU-Reject with cause 27.

**Expected behavior**
PDU-Reject should not be sent for PDU-Release command.

**Screenshots**

Subscriber Configuration:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/5b72fd33-dc1a-40fb-8e4b-ac9793cfc4d5)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6614b89c-40f4-46ab-a1b5-e323f8f4cc78)

**Comment by sreedharkumartn** [comment]
Fixed as part of #10500

**Comment by rupa455wavelabs** [comment]
Test case is passed in TVM setup.
Expected behaviour: PDU-Reject should not be sent for PDU-Release command.
Actual behaviour: PDU-Session is not getting accepted due to cause 27 (missing or unknown DNN).
Magma version: 1.7.0-1638935298-04806477

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/90eeb5e4-d8db-4e07-9460-cc31856754fa)

**Comment by rupa455wavelabs** [comment]
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/e5a58e28-b5f1-46a5-816a-7980fc257bbf)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/06e3a61b-5819-4a1d-b7b6-6af1794926c8)
