### ISSUE TITLE
Unified Images for Magma Based On Operating Environments

### ISSUE THREAD

**Issue by arunuke** [magma/magma#10498]
**Proposal : Unified Images for Magma Based on Operating Environments**

**Problem**

Magma Orchestrator (Orc8r) services are built and deployed as containerized images. With Access Gateways (AGWs) being containerized, services at the distributed edge are also deployed as containerized images. Although Magma is polyglot with components written in multiple programming languages, it is a finite set with C/C++, Python and Golang being the languages of choice. 

As an example for the current scenario where multiple images provide similar operating environments, the [artifactory for Magma images]((https://artifactory.magmacore.org/artifactory/docker/) ) contains many versions of Python images and Go images supporting different components that run in the Cloud and at the Edge. The gateway_go and gateway_python images are part of the Federation Gateway services while cwag_go (for CWAG) and other Orc8r images have go based operating environments. In the containerized AGW model, services that are python based are also deployed from a single base container that contains all the python libraries needed which adds one more python based image to go with the other python images in the artifactory. Having two (or more) images from the same programming language causes proliferation of base images and requires as many images be built, maintained, patched and secured increasing maintenance overhead exponentially.

**Solution**

This proposal intends to build common, standardized base images that contain all the necessary dependencies to run services based on that operating environment. As an example, all Go related services, whether they run as containers in Orc8r or the AGW, will be built using the same base image. Based on the service in question, additional layers may be added as part of the CI process. However, they would all pull the same base image from the Magma artifactory.

This allows the CI process to harden a single base image from a source and install the necessary packages which can be continuously maintained and upgraded as versions change. As an added benefit, this also acts as a forcing function for applications within the Magma landscape to have common dependencies instead of completely divergent paths (ex: applications requiring two versions of python with the highest variance, such as python2 and python3).

As the Magma build process gets re-designed with the introduction of Bazel, it might provide an opening for creating common, unified images for Magma services. 

**Non-goals**

This proposal does not intend to choose one enterprise version of the host OS over another. Developers and distro vendors could choose to port the services onto other base images than the one the community version of Magma is built on, but that is outside of the scope of this proposal.

**Comment by uri200** [comment]
Hey @arunuke, Note `gateway_go` and `gateway_python` used by feg are already big. Does it mean images will become bigger?
