### ISSUE TITLE
Request to add TC into TVM test suit.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10503]
Hi Arun,

Please add the following TC into TVM suite.

1.TC40	Hybrid Test - 4G IMSI Attach & Traffic + 5G SUCI Reg , PDU & Traffic
2.TC41	Hybrid Test - 4G GUTI Attach & Traffic + 5G GUTI Reg , PDU &Traffic
3.TC43g	Verify Security Reject with "Cause #24 – Security mode rejected, unspecified"
4.TC43h	Verify Security Reject with "Cause #23 – UE security capabilities mismatch"

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please add the following TC in TVM-GUI.

TC40 Hybrid Test - 4G IMSI Attach & Traffic + 5G SUCI Reg , PDU & Traffic
TC41 Hybrid Test - 4G GUTI Attach & Traffic + 5G GUTI Reg , PDU & Traffic
TC42 Scale Hybrid Mode 4G eNB+ UE & 5G gNB + UE

Its is required for debugging.

**Comment by arun-magma** [comment]
Hi @NeelimaKalpana @parthiban337 :

Its part of another 4G Emulator, Here is the UI info, Please access these hybrid TCs as indicated in below snap. if needed i can explain to Neelima about this by tomorrow morning.  Its a Regression setup plz let us know when you use it over slack usage channel.

http://10.22.162.4:8080/ng40gui/

![Screen Shot 2022-01-19 at 11.43.07 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/f68849c0-a42f-436a-a3fd-8846d42e859e)

**Comment by NeelimaKalpana** [comment]
Hi Arun ,
The link is not accessible.
Please give permissions to access.
