### ISSUE TITLE
[PDU-Rejections] Request to add additional test case for DNN-Missing(cause 27).

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10501]
Hi Arun,

Cause #27 – Missing or unknown DNN
This 5GSM cause is used by the network to indicate that the requested service was rejected by the external DN
because the DNN was not included although required or if the DNN could not be resolved.

TC1h is for Unsupported DNN/Unsubscribed DNN (cause 91).
So we will require one more Test case for Missing-DNN.

**Comment by arun-magma** [comment]
TC1i added for missing DNN, Plz look/expect for a scripts in coming days

**Comment by arun-magma** [comment]
TC1i ready to validate & available in GUI, Kindly check
@NeelimaKalpana @parthiban337

**Comment by NeelimaKalpana** [comment]
Hi Arun,

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/e26d4650-ac3c-4fee-9e07-777555f2052b)


For TC1i , we are having subsciberdb with internet as subscribed-apn . so in this cases if UE-requested the session with dnn as null the PDU should come-up with 'internet' as dnn-name.
Please modify the script accordingly.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Due to some bug Expected behavior is not getting hit.
I will check it once the bug got fixed.

[PDU-Rejection] AMF is crashing when a PDU-Establishment Request came with missing DNN info in the IE.#10581

**Comment by arun-magma** [comment]
Thanks let me know when Bug gets fixed, This TC will be part of the Daily regression in coming week.

**Comment by NeelimaKalpana** [comment]
Arun, to add this TC into the regression , We should trigger this TC with a different  IMSI ,as IMSI should not have any subscribed apn's.

**Comment by arun-magma** [comment]
Which IMSI being used ?

**Comment by NeelimaKalpana** [comment]
Hi Arun,

PDU_Reject_01_Cause_27 (For Missing DNN error code) :

For this scenario we should have a IMSI not subscribed with any apn as shown bellow.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/02e8ed50-252d-4d09-ad70-b2d44080319f) .
Please add a TC for the same to achieve the Scenario.

PDU_Est_Even_RequesthavingDNNEmpty_04 :TC1i 
please modify the TC expectations as requested int he Test Scenario sheet.

Please do the needful at the earlist.

Please align these 2 TC's according to the TS sheet .

**Comment by arun-magma** [comment]
@NeelimaKalpana 
Adding Two new test cases for these requirement, ETA 12/15< Please check if this suffice for your above needs.

1, **TC1j - Verify missing DNN I.E in PDU Est Req**
- Complete DNN IE would be removed in PDU Est Request from UE

- TC1i is having DNN Length =0 , cannot change that so adding a new TC. Let us know if TC1i need to continue or not.

2, **TC2M Multisession_Cause #27 – Missing or unknown DNN**

- TC1h with Multi session. Use DNN (unsupporteddnn) which is not subscribed in Magma.

**Comment by NeelimaKalpana** [comment]
Hi Arun,
Thank you for giving these details.
TC1i is required , in this TC with current configuration please change the verdict of TC - We need to check the verdict expecting the PDU-Establishment in this case.

**Comment by arun-magma** [comment]
Sure Neelima, Completely understood, on TC1i will get the Verdict changed to expect PDU Est Accept and pass it.

**Comment by NeelimaKalpana** [comment]
Thank you Arun.
And for TC1j for hitting the scenario, we should have the IMSI without any APN subscription.

**Comment by arun-magma** [comment]
You mean SubscriberDB should be configured with IMSI and Auth info but no APN should be mapped on it , Is that correct ?

**Comment by NeelimaKalpana** [comment]
Yes Arun, correct.

**Comment by arun-magma** [comment]
Sure will find a separate IMSI for this, which is not in the current range and plan this

**Comment by NeelimaKalpana** [comment]
Okay. Thank you.

**Comment by arun-magma** [comment]
TC1j updated, Kindly validate & let me know.

**Comment by rupa455wavelabs** [comment]
sure @arun-magma , we will test it and update you

Thank you

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma , kindly let us know the IMSI you are configuring for the TC1j scenario ?

A Gentle Reminder for TC1i Test script expectation modification.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please add TC1j also in the regression. 
I think for TC1j we should not have any APN subscribed for that your planning for an different IMSI. But it is picking the same IMSI that is ending with 101. So , please look into this and also add the case into Regression Suit.

Please find the pcaps for the same.
[Uploading... SA_TC1j_Verify_missing_DNN_Omit_IE_220214_024441-1.zip]

**Comment by NeelimaKalpana** [comment]
This TC is already added and met the expectation.
