### ISSUE TITLE
Please add the below mentioned TC in the TVM Suit.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10504]
Hi Arun,
Please add bellow TC in the TVM suit

1.TC40	Hybrid Test - 4G IMSI Attach & Traffic + 5G SUCI Reg , PDU & Traffic
2.TC41	Hybrid Test - 4G GUTI Attach & Traffic + 5G GUTI Reg , PDU & Traffic
3.TC43g	Verify Security Reject with "Cause #24 – Security mode rejected, unspecified"
4.TC43h	Verify Security Reject with "Cause #23 – UE security capabilities mismatch"

**Comment by arun-magma** [comment]
- TC40 and TC41 are already added in regression and running for more than two weeks, inconclusive part would be debugged in coming days.
- TC43... series would be aded in coming days, Thanks for the follow up on this.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

But we are not finding them in TVM-GUI. Are we using different TC-ID for these cases in TVM.
for TC43 series => please refer the ticket(#10221) and take a step on those TC's.

**Comment by arun-magma** [comment]
Hybrid scripts are bit complex & using Multiple emulators, we need to watch on for automated Regression results.

**Comment by arun-magma** [comment]
Will work on #10221
