### ISSUE TITLE
Regarding TC6c failing in Regression

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10525]
Hi Arun ,

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/0f51ba32-c202-4304-8a27-8634a9d4d751)

In this TC, trying to trigger Session with 2 UE's. 1 valid and other is invalid.
But  while executing it is sending more than intended number of registration requests.
Please look into the SreenShot for your understanding.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/fb8b690d-3e53-484b-bbdd-176bc0be5f60)

I can see the registration-request are getting triggered for same IMSI which is invalid.  
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/2e15dce0-ef76-42c8-b5ba-4faa45883457)

Please give me the access to the Test Script for better understanding of TC flow automated.

**Comment by NeelimaKalpana** [comment]
Please find the PCAP for the test case.
[https://app.zenhub.com/files/170803235/4e3338c6-621d-4bde-91cc-73ae8052985b/download](https://app.zenhub.com/files/170803235/4e3338c6-621d-4bde-91cc-73ae8052985b/download)

**Comment by arun-magma** [comment]
We are restricting the invalid UE related Registartion to only one attempt and verdict the outcode, this would stop the endless loop of Reg, will let you know when the change applied.

**Comment by NeelimaKalpana** [comment]
This is fine , Thank you Arun.

**Comment by arun-magma** [comment]
TC6C is passing for last 5 Runs after restricting to one attempt, Kindly review and close it. @NeelimaKalpana

**Comment by NeelimaKalpana** [comment]
Hi Arun,

TC6c I will observer for this week and close it.

**Comment by arun-magma** [comment]
Passing Consistently Since Nov 26th, lets close it
