### ISSUE TITLE
GTP error indication 

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#10534]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:1.7**
- **Affected Component: AGW
- **Affected Subcomponent:AGW service
- **Deployment Environment:bare-metal (AGW)

### Describe the Issue

Context: a few weeks ago we notice we were having an issue with GTP Echo, details are in [here](https://github.com/magma/magma/issues/9049), it was solved and we were using the OVS 2_15_2-1. 

A few days ago we notice other issue, some of our CPE were experiencing a low performance, just the same as in [here](https://github.com/magma/magma/discussions/8953), we upgrade the OVS from 2_15_2-1 first to 2_15_2-5 and the speed increased, but we started having disconection issues, on the sctp trace we started seeing again the "transport resource unavailable" message and in GTP we started seeing many GTP MESSAGE 0X1A (error indication). We made a downgrade to OVS 2_15_2-1 and the GTP error stop appearing, we try: new installation 1.6.0, with OVS 2_15_2-5, new installation of rel. 1.6.1 with OVS2_15_2-6 and it was the same, so far the GTP error does not appear when using OVS 2_15_2-1 an therefore the transport resource unavailable does not appear anymore.

**To Reproduce**
1. Use OVS 2_15_2-5 or 2_15_2-6
2. Capture some GTP and SCTP traffic
3. See error

**Expected behavior**
No GTP error, and a stable performance on speed.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/90400693/143254529-883bf1f6-b451-4d42-8dff-9ed8dbe9f134.png)

**Additional context**
Attached are the pcaps files, MME Logs and Syslogs for both when using OVS2_15_2-1 and 2_15_2-6

[24112021_AGW2_3.zip](https://github.com/magma/magma/files/7596323/24112021_AGW2_3.zip)

**Comment by joary** [comment]
@pshelar Has the OVS GTP-U Echo changed between 2.15.2-1 and 2.15.2-5 that could cause a different behavior?
