### ISSUE TITLE
Regarding intent of TC37 and TC38.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10532]
Hi Arun,

This is a follow-up for comment on #ZH10455 . Just for clear tracking raised a separate ticket.
 
Note By Yogesh:
Script expectation is not clear. As of now UPF does not support integrity protection checks in fast path. 

If there is no special intent in the TC , can we remove it from the regression.

**Comment by arun-magma** [comment]
Will review and remove it, This TC was given by Suresh as part of Error injection not feasible in DStest tool.

**Comment by NeelimaKalpana** [comment]
Okay Arun. Thank you

**Comment by NeelimaKalpana** [comment]
Closing this issue as already got info on this .
