### ISSUE TITLE
Regarding regression failure TC6a.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10548]
Hi Arun,

This is regarding TC6a which is failing in todays regression. 

This TC is failing only in the suit run . I tried executing individually and this is passing.

One more observation :

Test Case Verdict which is failing:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/394bd2da-69f9-4de8-bc36-c6e944b29c8b)

But in pcap I can see for UE-IMSI222456000000103 , One retry is happening. This can be expected , because here we are trying to pick 2 different UE's with  IMSI222456000000103 and IMSI222456000000104 , and it may take little time to setup topology with new UE's. This is my analysis as per pcaps and verdict logs.

Can you also please look into this so we can take a step to clear this from fail list.
Please fid logs and pcap's from bellow.
[https://app.zenhub.com/files/170803235/4b5f03d4-a691-4fd2-a9cb-95bdf228c732/download](https://app.zenhub.com/files/170803235/4b5f03d4-a691-4fd2-a9cb-95bdf228c732/download)

**Comment by arun-magma** [comment]
TC6a is passing for last 5 runs, Kindly review and close this issue.
if In 2nd Reg_Req Retry we see Reg Accept then the verdict should show pass, let's check this in further runs.

**Comment by arun-magma** [comment]
passing Consistently since 26th Nov, Lets close it.
