### ISSUE TITLE
Requesting access to TS that need to be investigated.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10549]
Hi Arun,

Please give access to the TS that need to be investigated.
For some cases we already raised Tickets and gave the details 
Please find below screen shot for the TC list and Ticket details.
TC9b , I will execute share the details.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/930f5ac4-5413-47a8-ae12-f4cd248b40c7)

For some cases we already raised Tickets and gave the details 
Please do the needful at the earliest.

**Comment by arun-magma** [comment]
Lets go over one by one separately, the 3gpp message flow in pcap should be able to give the scripted sequence, lets verify case by case.

**Comment by arun-magma** [comment]
"TC43d & TC43e" 
addressed with sample behavior traces in below ticket

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10221

"TC37 & TC38"
 Below ZH covers it, would be reviewed and removed from regression as it looks not supported at the moment.

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10532

TC7d
Added required traffic flow to validate healthy status of 1st successful PDU session, make sure PDU reject for DUP request not affect 1st PDU session, below relevant ZH Ticket updated.

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10021

TC43b
A new scenario 18g added to cover the required Cause-21 flow in both Auth res and Resync Auth Res, below relevant ticket updated, ETA: Next week (It needs a Error injection and changes in default flows)

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10005

TC9b
Validated in 140 (Dev AGW) and it passing, Idea in this scenario is to get Service Request on last paging attempt.
here is the successful pcap.
[https://app.zenhub.com/files/170803235/59513786-7875-43a1-8d3b-f49a785292af/download](https://app.zenhub.com/files/170803235/59513786-7875-43a1-8d3b-f49a785292af/download)

Hope covered all the listed TCs behavior related queries, let me know if i missed any & feel free to add queries in res tickets. Thanks!

**Comment by rupa455wavelabs** [comment]
closing this issue, as we got the inputs.
