### ISSUE TITLE
Mikrotik routers not attaching

### ISSUE THREAD

**Issue by obensouda** [magma/magma#10554]
### Your Environment

- Version: 1.5.2-1624485681-ae972900
- **Affected Component:**Access Gateway
- **Affected Subcomponent: AGW service
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

We having been testing getting UE to attach and are working on Mikrotik LtAP mini LTE kit with a built in model. We see that device is able to go through the authentication process with mme but fails to maintain a session. Currently devices is running latest firmware available for mikrotik which is 6.48.5. 

**To Reproduce** 
We have attached the the logs for the account IMSI as part of the steps.
329663 Sat Nov 27 14:09:16 2021 7F590E3F3700 WARNI MME-AP tasks/mme_app/mme_app_context.c :0335   [607070000000009]  No IMSI hashtable for this IMSI
329664 Sat Nov 27 14:09:16 2021 7F590E3F3700 NOTIC NAS-EM tasks/nas/emm/Attach.c          :0591    EMM-PROC  - Create EMM context ue_id = 0x0001BBD2
329665 Sat Nov 27 14:09:16 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1117    Hit 3GPP TS 24_301R10_5_5_1_2_3__1 : EMM common procedure initiation during attach procedure
329666 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :1459    Sending Authentication Information Request message to S6A for ue_id =0x0001BBD2
329667 Sat Nov 27 14:09:16 2021 7F5909BEA700 INFO  S6A    common/common_utility_funs.cpp  :0054   [607070000000009] PLMN is not configured. Selecting default mode: SPGW_SUBSCRIBER 
329668 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/nas_proc.c            :0363    Received Authentication Information Answer from S6A for ue_id =0x0001BBD2
329669 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_cn.c      :1136    EMMCN-SAP - Received primitive EMM_CN_AUTHENTICATION_PARAM_RES (401)
329670 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0238    EMM-FSM   - Received event COMMON_PROC_ABORT (4) in state EMM-DEREGISTERED
329671 Sat Nov 27 14:09:16 2021 7F590E3F3700 ERROR NAS-EM tasks/nas/emm/sap/EmmDeregistere:0119    EMM-FSM state EMM_DEREGISTERED - Primitive _EMMREG_COMMON_PROC_ABORT is not valid
329672 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :0163    ue_id=0x0001BBD2 EMM-PROC  - Initiate Authentication KSI = 0
329673 Sat Nov 27 14:09:16 2021 7F590E3F3700 WARNI NAS-EM tasks/nas/emm/LowerLayer.c      :0472    NO Valid Security Context Available
329674 Sat Nov 27 14:09:16 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Authentication.c  :1232    Hit 3GPP TS 24_301R10_5_4_2_2 : Authentication initiation by the network
329675 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_SECURITY_REQ (201)
329676 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :1639    EMMAS-SAP - Send AS security request
329677 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :1344    EMMAS-SAP - Send Authentication Request message for ue_id = (113618)
329678 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_context.c :1413   [607070000000009] UE STATE - CONNECTED.
329679 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0238    EMM-FSM   - Received event COMMON_PROC_REQ (1) in state EMM-DEREGISTERED
329680 Sat Nov 27 14:09:16 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0152    UE 0x0001BBD2 EMM-FSM   - Status changed: EMM-DEREGISTERED ===> EMM-COMMON-PROCEDURE-INITIATED
329681 Sat Nov 27 14:09:16 2021 7F590A3EB700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0595   [607070000000009] Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x0001BBD2 MME_UE_S1AP_ID = 0x0001BBD2 eNB_UE_S1AP_ID = 0x000D7A
329682 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0314    Received S1AP UPLINK_NAS_TRANSPORT message MME_UE_S1AP_ID 0x0001BBD2
329683 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0077   [607070000000009] Sending NAS Uplink indication to NAS_MME_APP, mme_ue_s1ap_id = (113618) 
329684 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS    tasks/nas/nas_proc.c            :0307    Received NAS UPLINK DATA IND from S1AP for ue_id = (113618)
329685 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_DATA_IND (214)
329686 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0617    EMMAS-SAP - Received AS data transfer indication (ue_id=0x0001BBD2, delivered=true, length=11)
329687 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0396    Hit 3GPP TS 24_301R10_4_4_4_3__1 : Integrity checking of NAS signalling messages exception in the MME
329688 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0399    Hit 3GPP TS 24_301R10_4_4_4_3__2 : Process NAS signalling message in the MME, even if it fails the integrity check or MAC cannot be verified
329689 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :0955    EMMAS-SAP - Received Authentication Response message
329690 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :0864    EMM-PROC  - Authentication complete (ue_id=0x0001BBD2)
329691 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :0881    EMM-PROC  - Authentication complete (ue_id=0x0001BBD2)
329692 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Authentication.c  :0891    Hit 3GPP TS 24_301R10_5_4_2_4__1 : AUTHENTICATION RESPONSE received, stop T3460, check RES
329693 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Authentication.c  :0894    Hit 3GPP TS 24_301R10_5_4_2_4__2 : authentication procedure is success, new eKSI for new authentication procedure
329694 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0238    EMM-FSM   - Received event COMMON_PROC_CNF (2) in state EMM-COMMON-PROCEDURE-INITIATED
329695 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0152    UE 0x0001BBD2 EMM-FSM   - Status changed: EMM-COMMON-PROCEDURE-INITIATED ===> EMM-DEREGISTERED
329696 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Attach.c          :1220    ATTACH - Authentication procedure success!
329697 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1225    Hit 3GPP TS 24_301R10_5_5_1_2_3__1 : EMM common procedure initiation during attach procedure
329698 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1262    Hit 3GPP TS 24_301R10_5_5_1_2_3__1 : EMM common procedure initiation during attach procedure
329699 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/SecurityModeContro:0178    EMM-PROC  - Initiate security mode control procedure, KSI = 0
329700 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/SecurityModeContro:0225    Hit 3GPP TS 24_301R10_5_4_3_2__2 : SMC initiation, reset DL NAS count, use SC
329701 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/SecurityModeContro:0782    Hit 3GPP TS 24_301R10_5_4_3_2__14 : SMC initiation, include replayed security capabilities, eKSI, algos
329702 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_SECURITY_REQ (201)
329703 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :1639    EMMAS-SAP - Send AS security request
329704 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :1458    EMMAS-SAP - Send Security Mode Command message for ue_id = (113618)
329705 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/SecurityModeContro:0826    Hit 3GPP TS 24_301R10_5_4_3_2__1 : SMC initiation, start T3460
329706 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0238    EMM-FSM   - Received event COMMON_PROC_REQ (1) in state EMM-DEREGISTERED
329707 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0152    UE 0x0001BBD2 EMM-FSM   - Status changed: EMM-DEREGISTERED ===> EMM-COMMON-PROCEDURE-INITIATED
329708 Sat Nov 27 14:09:17 2021 7F590A3EB700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0595   [607070000000009] Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x0001BBD2 MME_UE_S1AP_ID = 0x0001BBD2 eNB_UE_S1AP_ID = 0x000D7A
329709 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0314    Received S1AP UPLINK_NAS_TRANSPORT message MME_UE_S1AP_ID 0x0001BBD2
329710 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0077   [607070000000009] Sending NAS Uplink indication to NAS_MME_APP, mme_ue_s1ap_id = (113618) 
329711 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS    tasks/nas/nas_proc.c            :0307    Received NAS UPLINK DATA IND from S1AP for ue_id = (113618)
329712 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_DATA_IND (214)
329713 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0617    EMMAS-SAP - Received AS data transfer indication (ue_id=0x0001BBD2, delivered=true, length=19)
329714 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/msg/emm_msg.c     :0182    EMM-MSG   - IMEISV: 3556540940495723
329715 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0418    Hit 3GPP TS 24_301R10_4_4_4_3__1 : Integrity checking of NAS signalling messages exception in the MME
329716 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :1068    EMMAS-SAP - Received Security Mode Complete message
329717 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/SecurityModeContro:0456    EMM-PROC  - Security mode complete (ue_id=0x0001BBD2)
329718 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/SecurityModeContro:0484    Hit 3GPP TS 24_301R10_5_4_3_4__1 : SMC completion, stop T3460, 
329719 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/SecurityModeContro:0546    Hit 3GPP TS 24_301R10_5_4_3_4__2 : SMC completion, integ. cipher. all messages
329720 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0238    EMM-FSM   - Received event COMMON_PROC_CNF (2) in state EMM-COMMON-PROCEDURE-INITIATED
329721 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0152    UE 0x0001BBD2 EMM-FSM   - Status changed: EMM-COMMON-PROCEDURE-INITIATED ===> EMM-DEREGISTERED
329722 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Attach.c          :1305    ATTACH - Security procedure success!
329723 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Attach.c          :1521    ue_id=0x0001BBD2 EMM-PROC  - Attach UE 
329724 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/sap/esm_sap.c     :0140    ESM-SAP   - Received primitive ESM_UNITDATA_IND (20)
329725 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/sap/esm_recv.c    :0150    ESM-SAP   - Received PDN Connectivity Request message (ue_id= 0x0001BBD2, pti=1, ebi=0)
329726 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  SCTP   tasks/mme_app/mme_app_location.c:0067    Sending S6A UPDATE LOCATION REQ to S6A, ue_id =0x0001BBD2 
329727 Sat Nov 27 14:09:17 2021 7F5909BEA700 INFO  S6A    common/common_utility_funs.cpp  :0054   [607070000000009] PLMN is not configured. Selecting default mode: SPGW_SUBSCRIBER 
329728 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_main.c    :0210    Received S6A Update Location Answer from S6A
329729 Sat Nov 27 14:09:17 2021 7F590E3F3700 ERROR MME-AP tasks/mme_app/mme_app_location.c:0297    No MSISDN received for mme_app_handle_s6a_update_location_ans 607070000000009
329730 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/nas_proc.c            :0462    Received S6a-Update Location Answer Success for ue_id = 0x0001BBD2
329731 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_cn.c      :1136    EMMCN-SAP - Received primitive EMM_CN_ULA_SUCCESS (403)
329732 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_apn_select:0138    Selected APN <inet>, PDN Type <0> for UE 607070000000009
329733 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/PdnConnectivity.c :0132    ESM-PROC  - PDN connectivity requested by the UE (ue_id=0x0001BBD2)
329734 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/DefaultEpsBearerCo:0105    ESM-PROC  - Default EPS bearer context activation (ue_id=0x0001BBD2)
329735 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/esm_ebr_context.c :0092    ESM-PROC  - Create new default EPS bearer context (ebi=5) for PDN connection (pid=0) for ue_id (113618)
329736 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP common/common_utility_funs.cpp  :0054   [607070000000009] PLMN is not configured. Selecting default mode: SPGW_SUBSCRIBER 
329737 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_itti_messa:0390   [607070000000009] Sending s11 create session req message to SPGW task for ue_id 0x0001BBD2
329738 Sat Nov 27 14:09:17 2021 7F590B3ED700 INFO  SPGW-A tasks/sgw/sgw_handlers.c        :0110   [607070000000009] Received S11 CREATE SESSION REQUEST from MME_APP
329739 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :1012    Received S11_CREATE_SESSION_RESPONSE from S+P-GW
329740 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/nas_proc.c            :0480    Handle Create Session Response Success at NAS for ue_id = 0x0001BBD2
329741 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_cn.c      :1136    EMMCN-SAP - Received primitive EMM_CN_CS_RESPONSE_SUCCESS (404)
329742 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/sap/esm_send.c    :0227    ESM-SAP   - Send Activate Default EPS Bearer Context Request message
329743 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/sap/esm_send.c    :0327    ESM-SAP   - Send Activate Default EPS Bearer Context Request message (pti=1, ebi=5)
329744 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/DefaultEpsBearerCo:0204    ESM-PROC  - Initiate non standalone default EPS bearer context activation (ue_id=0x0001BBD2, ebi=5)
329745 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/esm_ebr.c         :0515    ESM-FSM   - Status of EPS bearer context 5 changed: BEARER CONTEXT INACTIVE ===> BEARER CONTEXT ACTIVE PENDING
329746 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1713    #NOT IMPLEMENTED 3GPP TS 24_301R10_5_5_1_2_4__3 : Attach accepted by the network, delete the stored UE radio capability information.
329747 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1716    Hit 3GPP TS 24_301R10_5_5_1_2_4__4 : Attach accepted by the network, store UE network capability IE or the MS network capability IE or both.
329748 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1723    Hit 3GPP TS 24_301R10_5_5_1_2_4__5 : Attach accepted by the network, use DRX parameter for the downlink transfer of signalling and user data
329749 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1728    Hit 3GPP TS 24_301R10_5_5_1_2_4__9 : 
329750 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS    tasks/nas/api/mme/mme_api.c     :0545    UE 0x0001BBD2  Got GUTI 607.07 |0001|01|4441337e. The number of TAI partial lists: 1
329751 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1748    Hit 3GPP TS 24_301R10_5_5_1_2_4__6 : 
329752 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1749    Hit 3GPP TS 24_301R10_5_5_1_2_4__10 : 
329753 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1800    Hit 3GPP TS 24_301R10_5_5_1_2_4__14 : 
329754 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/Attach.c          :1852    Hit 3GPP TS 24_301R10_5_5_1_2_4__2 : 
329755 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_ESTABLISH_CNF (206)
329756 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :2017    EMMAS-SAP - Send AS connection establish confirmation for (ue_id = 113618)
329757 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :0221    EMMAS-SAP - Send Attach Accept message, ue_id = (113618)
329758 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0535   [607070000000009] MME APP : Sent Initial context Setup Request and Started guard timer for UE id  113618 timer_id :50b0 
329759 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0873    Received Connection Establishment Confirm from MME_APP for ue_id = 113618
329760 Sat Nov 27 14:09:17 2021 7F590A3EB700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:1123   [607070000000009] Send S1AP_INITIAL_CONTEXT_SETUP_REQUEST message MME_UE_S1AP_ID = 0x0001BBD2 eNB_UE_S1AP_ID = 0x000D7A
329761 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :1544    Received MME_APP_INITIAL_CONTEXT_SETUP_RSP from S1AP for ue_id = (113618)
329762 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :1472   [607070000000009] Sending S11 MODIFY BEARER REQ to SPGW for ue_id = (113618), teid = (1632)
329763 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :4427   [607070000000009] Sending S11 modify bearer req message to SPGW task for ue_id 0x0001BBD2
329764 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0314    Received S1AP UPLINK_NAS_TRANSPORT message MME_UE_S1AP_ID 0x0001BBD2
329765 Sat Nov 27 14:09:17 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0077   [607070000000009] Sending NAS Uplink indication to NAS_MME_APP, mme_ue_s1ap_id = (113618) 
329766 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS    tasks/nas/nas_proc.c            :0307    Received NAS UPLINK DATA IND from S1AP for ue_id = (113618)
329767 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_DATA_IND (214)
329768 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0617    EMMAS-SAP - Received AS data transfer indication (ue_id=0x0001BBD2, delivered=true, length=9)
329769 Sat Nov 27 14:09:17 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0357    Hit 3GPP TS 24_301R10_4_4_4_3__1 : Integrity checking of NAS signalling messages exception in the MME
329770 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :0096    EMMAS-SAP - Received EMM Status message (cause=0)
329771 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/EmmStatusHdl.c    :0069    EMM-PROC  - EMM status procedure requested (cause=0)
329772 Sat Nov 27 14:09:17 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_main.c    :0120    Received S11 MODIFY BEARER RESPONSE from SPGW
329773 Sat Nov 27 14:09:18 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0314    Received S1AP UPLINK_NAS_TRANSPORT message MME_UE_S1AP_ID 0x0001BBD2
329774 Sat Nov 27 14:09:18 2021 7F590A3EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0077   [607070000000009] Sending NAS Uplink indication to NAS_MME_APP, mme_ue_s1ap_id = (113618) 
329775 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS    tasks/nas/nas_proc.c            :0307    Received NAS UPLINK DATA IND from S1AP for ue_id = (113618)
329776 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0174    EMMAS-SAP - Received primitive EMMAS_DATA_IND (214)
329777 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0617    EMMAS-SAP - Received AS data transfer indication (ue_id=0x0001BBD2, delivered=true, length=18)
329778 Sat Nov 27 14:09:18 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0511    Hit 3GPP TS 24_301R10_4_4_4_3__1 : Integrity checking of NAS signalling messages exception in the MME
329779 Sat Nov 27 14:09:18 2021 7F590E3F3700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0512    Hit 3GPP TS 24_301R10_4_4_4_3__2 : Process NAS signalling message in the MME, even if it fails the integrity check or MAC cannot be verified
329780 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :0480    EMMAS-SAP - Received Detach Request message
329781 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Detach.c          :0265    EMM-PROC  - SGS Detach type = COMBINED (2) requested (ue_id=0x0001BBD2) 
329782 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/Detach.c          :0332    EMM-PROC  - Detach type = EPS/IMSI (2) requested (ue_id=0x0001BBD2)
329783 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0238    EMM-FSM   - Received event DETACH_REQ (9) in state EMM-DEREGISTERED
329784 Sat Nov 27 14:09:18 2021 7F590E3F3700 ERROR NAS-EM tasks/nas/emm/sap/EmmDeregistere:0193    EMM-FSM state EMM_DEREGISTERED - Primitive _EMMREG_DETACH_REQ is not valid
329785 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_detach.c  :0152    Handle Detach Req at MME app for ue-id: 0x0001BBD2 with mme_s11_teid 0x1BBD2
329786 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_detach.c  :0067   [607070000000009] Handle Delete session request for mme_s11_teid :113618
329787 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_detach.c  :0131   [607070000000009] Send delete session Req for teid to spgw task 0x1BBD2
329788 Sat Nov 27 14:09:18 2021 7F590B3ED700 INFO  SPGW-A tasks/sgw/sgw_handlers.c        :1065   [607070000000009] Handle delete session request for sgw_s11_teid 0x660
329789 Sat Nov 27 14:09:18 2021 7F590CBF0700 INFO  GTPv1- lib/openflow/controller/PagingAp:0148    Deleted paging flow rule for UE IP 172.16.0.71
329790 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0844    Received S11_DELETE_SESSION_RESPONSE from S+P-GW with teid 0x1BBD2
 
329791 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_itti_messa:0086   [607070000000009] Sending UE Context Release Cmd to S1ap for (ue_id = 113618)
UE Context Release Cause = (2)
329792 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_context.c :1803    Received UE context release complete message for ue_id: 0x0001BBD2
329793 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_purge_ue.c:0077    Sent PUR to S6a TASK for IMSI 607070000000009
329794 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  MME-AP tasks/mme_app/mme_app_context.c :0121   [607070000000009] Deleted UE location from directoryd
329795 Sat Nov 27 14:09:18 2021 7F590E3F3700 INFO  NAS-ES tasks/nas/esm/sap/esm_sap.c     :0140    ESM-SAP   - Received primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ (10)
329796 Sat Nov 27 14:09:18 2021 7F590E3F3700 ERROR NAS-ES tasks/nas/esm/PdnConnectivity.c :0525    ESM-PROC  - PDN connection identifier is not valid
329797 Sat Nov 27 14:09:18 2021 7F590E3F3700 ERROR NAS-ES tasks/nas/esm/sap/esm_sap.c     :0293    ESM-SAP   - Failed to process primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ (10)
329798 Sat Nov 27 14:09:18 2021 7F590E3F3700 WARNI MME-AP tasks/mme_app/mme_app_context.c :0335   [607070000000009]  No IMSI hashtable for this IMSI

**Expected behavior**
We expect the UE to attach however so far no mikrotik devices tested is able to attach successfully.

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by pshelar** [comment]
Its worth trying out 1.6.2 release.

cc: @ardzoht @ulaskozat

**Comment by ulaskozat** [comment]
Not sure why upgrading to 1.6.2 would resolve this issue as the logs are not sufficient to understand the root cause. Looks like UE is sending a detach request before registration procedure completes.

**Comment by ardzoht** [comment]
Agree with @ulaskozat. @obensouda Is it possible to attach full `mme.log` file and also if possible run through the steps on https://magma.github.io/magma/docs/lte/debug_show_tech to have full output of AGW state and services.

**Comment by obensouda** [comment]
I have attached the full mme.log file. I am trying to get the show-tech data. it is proving a bit elusive the command to download with ansible does not seam to get me the file.
[mme.zip](https://github.com/magma/magma/files/7633227/mme.zip)

**Comment by obensouda** [comment]
@ardzoht am having difficult running show-tech. Any suggestions. Additionally was the mme.log useful?
