### ISSUE TITLE
[TeraVM 5G] Additional AGW 

### ISSUE THREAD

**Issue by parthiban337** [magma/magma#10568]
Request to add 2 TWO additional AGW to the Manual Testing TeraVM(140) setup.

This is to help Magma 5G SA development team to test private binaries before code merge.

In total 3 - THREE AGW connected to 140 TeraVM setup.
- one set up for code merge/post PR Feature testing --> Already existing
- two setups for the Development team to do private binaries testing and run 
   all P0/P1 test scripts from TeraVM after each bug fix. --> to be newly provisioned. 
 
Please share the AGW hardware certs/keys/IP Addresses so that they can be added into Wavelabs Orchestrator for configuration & testing.

**Comment by arun-magma** [comment]
As 140 was keep troubling we recreated it to clear the block, lets validate it @NeelimaKalpana .
Will let you know when new GWs get ready

**Comment by NeelimaKalpana** [comment]
Hi Arun,

This is a gentle reminder for new agw requirement . Please do the need full .

**Comment by arun-magma** [comment]
@NeelimaKalpana : We are working on it to bring up two more AGWs, atleast one should be available by today.
cc: @vaishaliCI

**Comment by arun-magma** [comment]
Two More AGWs are added in the Dev test line up, here are the list, All can be accessible through default credentials, Its headless now, Wlabs team may connect to Wlabs Orc8r.
cc: @vaishaliCI 

Dev-1:  10.22.162.140 (old)
Dev-2: 10.22.162.143 (New)
Dev-3: 10.22.162.144 (New)

And currently loaded below AGW build
_magma-sctpd/focal-ci,now 1.7.0-1638510273-2b4f71ea amd64 [installed,automatic]
magma/focal-ci,now 1.7.0-1638510273-2b4f71ea amd64 [installed]_

**Comment by arun-magma** [comment]
Closing this ticket as AGWs are ready to use, Thanks!

**Comment by NeelimaKalpana** [comment]
Please enable the security settings to login from any terminal.
Once the settings are done , I will close the ticket.

Parallelly , we will try connecting to wavelabs-orc8.
