### ISSUE TITLE
[PDU-Rejection] AMF is crashing when a PDU-Establishment Request came with missing DNN info in the IE.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10581]
Your Environment

- Version: 1.7.0-1638231879-2b0c8bf7
- Affected Component : Access Gateway
- Affected Subcomponent : AGW service
- Deployment Environment : Vagrant (AGW)

Describe the Issue

To Reproduce
1. Add subscriber with 1 apn-configed.
2. In UE, don't configure any apn.
3. Trigger the 5G call flow with apn/dnn name missing in the IE.
4. AMF is crashing.

**Expected behavior**
Check that AMF is establishing the session with subscribed-dnn in subscriberdb.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/228b7da0-e23e-4c1d-a895-39b24207bcc0)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/95ecc4a3-928c-4df1-8856-0e8abbbef644)

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ff142470859 in __GI_abort () at abort.c:79
#2  0x00007ff1426f6911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ff14270238c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ff1427023f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ff1427026a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ff1426f9326 in std::__throw_length_error(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ff14279c388 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x000056456720b419 in magma5g::amf_smf_process_pdu_session_packet (ue_id=1, msg=0x7ff135dd16a8, amf_cause=0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:460
#9  0x00005645671ff110 in magma5g::amf_as_establish_req (msg=0x7ff135de1878, amf_cause=0x7ff135de173c)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:221
#10 0x00005645671fead5 in magma5g::amf_as_send (msg=0x7ff135de17f8)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:87
#11 0x000056456720212b in magma5g::amf_sap_send (msg=0x7ff135de17c0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_sap.cpp:58
#12 0x00005645671f1509 in magma5g::amf_app_handle_uplink_nas_message (amf_app_desc_p=0x613000000380, msg=0x0, ue_id=1,
    originating_tai=...) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:542
#13 0x00005645671ed5cc in magma5g::handle_message (loop=0x607000016ff0, reader=0x60400001a080, arg=0x0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp:75
#14 0x00007ff142beb5c7 in zloop_start () from /lib/x86_64-linux-gnu/libczmq.so.4
#15 0x00005645671ed80f in magma5g::amf_app_thread (args=0x0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp:171
#16 0x00007ff143782609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007ff14256d293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

(gdb) p msg->dnn
$1 = {iei = 37 '%', len = 0 '\000', dnn = '\000' <repeats 101 times>}
(gdb) p msg->dnn.len - 1
$2 = -1

**Comment by NeelimaKalpana** [comment]
Please execute TC1i for the scenario

Please find logs and pcaps for the issue:
[https://app.zenhub.com/files/170803235/c9a50040-d70a-4452-a7a7-481639317906/download](https://app.zenhub.com/files/170803235/c9a50040-d70a-4452-a7a7-481639317906/download).

**Comment by sreedharkumartn** [comment]
Tracked as part of #10584
