### ISSUE TITLE
[Sessiond] Credits gets suspended and immediately un-suspended on CCA-U with FUA

### ISSUE THREAD

**Issue by joary** [magma/magma#10609]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:** AGW
- **Affected Subcomponent:** Sessiond
- **Deployment Environment:** Federeted FWA with Gx/Gy federation

### Describe the Issue

When the subscriber quota ends the Gy will answer any CCR-U coming from magma with a CCA-U containing FUI and action configured to TERMINATE.

The behaviour seen is:

1. On the first CCA-U the rules are dropped as expected.
2. The next CCA-U the rules are dropped but are immediately reactivated
3. The subsequent CCA-U the rule is dropped again as expected.
4. The next CCA-U behavior on 2 reproduces

Follows the sessiond log for the suspention and imediatelly unsuspension seen in #2 and #4. (All IMSI values are the same)

![image](https://user-images.githubusercontent.com/1166157/144244227-13e6f4d0-fbe9-4a46-9281-ec1992ad9825.png)

**Expected behavior**

Magma should always drop the rules that are linked to the RG contained in the CCA-U with FUA TERMINATE

**Comment by joary** [comment]
The probable root cause is the fact that magma suspends a given session (drop the rule) when the FUI is received and later un-suspends if a CCR-U is received and there's a suspended session.

The first  CCA-U + 4012 FUA-TERMINATE magma gets will suspend the session: [as seen here](https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/LocalEnforcer.cpp#L1435)

The second CCA-U + 4012 FUA-TERMINATE will also suspend the session but it will later un-suspend it since there's a suspended session already, [as seen here](https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/LocalEnforcer.cpp#L1483)

The proposed workaround is to avoid the credit suspension [here](https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/LocalEnforcer.cpp#L1483) by changing the conditional to not be executed on FUA, for example:

```
if (valid_credit && !credit_update_resp.credit().is_final() && session->is_credit_suspended(credit_key)) {
```


cc @uri200, @themarwhal

**Comment by themarwhal** [comment]
Does the second CCA-U include any credit? I wonder why we pass the `valid_credi` check if the second one has the 4012 code.

**Comment by joary** [comment]
> Does the second CCA-U include any credit? 

It does, my rationale:

valid_credit will only [be false](https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/SessionState.cpp#L1735) if the CCR-U has [result PERMANENT_FAILURE]().  Though the CCR's that contains a FUI will also have a result code as TRANSIENT_FAILURE (4012) by Diameter definition.

**Comment by crbertoldo** [comment]
As per @joary's suggestion, adding `&& !credit_update_resp.credit().is_final()` to [this](https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/LocalEnforcer.cpp#L1483) conditional, solves the issue:

Before:
` if (valid_credit && session->is_credit_suspended(credit_key))`

After:
`if (valid_credit && !credit_update_resp.credit().is_final() && session->is_credit_suspended(credit_key))`

**Comment by uri200** [comment]
that workaround will only work if the credit were final. If the credit was suspended for any other reason and it was not final the credit will never be unsuspended

**Comment by uri200** [comment]
The problem seems to be in fact this [line](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=lte%2Fgateway%2Fc%2Fsession_manager%2FLocalEnforcer.cpp&editor=JetBrains&version=v1.2.2&start_row=1476&start_col=41&end_row=1476&end_col=41) 

Being suspended and with no quota, `should_activate` should be `fasle`

**Comment by uri200** [comment]
this pr may fix this issue 
https://github.com/magma/magma/pull/10671
