### ISSUE TITLE
[DNN]AMF is sending wrong error code when PDU-request came with dnn-name:oai.ipv4 and requested apn is not subscribed in the subscriberdb.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10603]
Your Environment

- Version: 1.7.0-1638329740-91d1304b
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue
Decoding is failing when dnn name is a string of mixed characters and it is not subscribed. AMF is sending a wrong cause value , protocol error : cause 111.

**To Reproduce**
1. Give dnn-name as oai.ipv4
2. Make sure subscriber is not subscribed with requested dnn.
3. Trigger the 5G call flow.
4. Getting PDU-Reject with protocol-erro(cause:111)

**Expected behavior**
AMF should send  PDU-Reject with error code : 91.                                     

Screenshots**

mme.logs showing decode failure:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/d92470b4-8be0-4b7c-96c5-3de4400e397b)

PCAP Screenshots:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/ef35d80e-5e3e-4e8a-ac08-0e629fdd1f60)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/15440378-206f-44d3-80ae-72321fd0a249)

[https://app.zenhub.com/files/170803235/7e256774-a41a-437a-b059-bdeb91d56ef0/download](https://app.zenhub.com/files/170803235/7e256774-a41a-437a-b059-bdeb91d56ef0/download)

**Comment by sreedharkumartn** [comment]
Subscriber db:
![subscriber_db.JPG](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/1baaf437-cf0a-40cb-b668-888a75bb710e)
UE:
![UE_info.JPG](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/3ad3f051-5469-4187-ac3a-efeafc5d981a)

In PCAP and mme log, it is showing PDU - reject with error code :91.
PCAP snap:
![Pcap.JPG](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/8d4fa2cd-b646-43dc-a4a8-0c9cb61a8a2f)
mme log snap:
![mme.JPG](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/1666b8f6-a1ca-4756-81f4-d5c9a0d5288e)

Please find attached PCAP and mme log.
[https://app.zenhub.com/files/170803235/b0376189-33a4-43c6-a935-3d029e22f734/download](https://app.zenhub.com/files/170803235/b0376189-33a4-43c6-a935-3d029e22f734/download)

**Comment by NeelimaKalpana** [comment]
Reopening the Issue as initial problem is existing in the master-build: 

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a9d9f6f5-faa1-4921-ae63-f54d9a344809)

Decoding of DNN-Name is failing as it is having '.' character in the dnn-sting.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/eed3ee55-91db-4cd8-9c7f-68da88baa20e)

Reference Document talking about DNN String syntax:
https://www.etsi.org/deliver/etsi_ts/123000_123099/123003/10.05.00_60/ts_123003v100500p.pdf
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/bf6776dd-85be-491a-95ba-e0a324e27985)

**Comment by moinuddin1980** [comment]
"Refer 9.1.2 Format of APN Operator Identifier"  in "https://www.etsi.org/deliver/etsi_ts/123000_123099/123003/10.05.00_60/ts_123003v100500p.pdf"
It has clear examples of how an APN entry should look like
EXAMPLE 1: province1.mnc012.mcc345.gprs 
EXAMPLE 2: ggsn-cluster-A.provinceB.mnc012.mcc345.gprs 
Hence, AGW also should support this format label1.label2.label3.

Also, as told by tester, in the +ve scenario, when the subscriberdb is configured with exact APN(. separated) requested by UE, the the PDU session gets established. (@Sathya @Neelima please re-confirm this)
But, if the subscriberdb is not configured with the APN name , then the PDU session is getting rejected with protocol error as the decoding is failing at nas5G IE decoding/encoding. (This need to be investigated.)

**Comment by rupa455wavelabs** [comment]
Issue got resolved, closing the issue.
