### ISSUE TITLE
[sessiond] Undesired CCR-T after CCA-I with FUI, since the non-terminated/free-of-charge rule should be kept

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#10612]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:** AGW and/or FeG
- **Affected Subcomponent:** sessiond and/or session_proxy
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

When the OCS sends an FUI (with FUA TERMINATE or REDIRECT, and result-code 2001 or 4012) in CCA-I, what is expected, Magma sends a TERMINATION_REQUEST about 10 seconds later. The session may be kept, with the another rule / rating group (RG 10) applied, for the free of charge IP addresses per se. There is an open question now if Magma supports FUI in CCA-I and, if so, how does it work when there are multiple rules / RGs attached to the sessions itself, and when only the exhausted rule should be stopped. 

**Expected behavior**

We need to keep the session open, because later a Diameter RAR might be sent, and the subsequent CCR-U/CCA-I will authorize the RG30, the to-be-charged rating group.

**Screenshots**

About 10 seconds between INITIAL_REQUEST and TERMINATION_REQUEST:

![Screen Shot 2021-12-01 at 13 11 23](https://user-images.githubusercontent.com/6054708/144270574-fa6e91e5-2a28-4cfe-8355-e7a9120894a6.png)

I can share magmad, sessiond, session_proxy, and pcaps privately as they contain customer data.

**Comment by crbertoldo** [comment]
@jpad-freedomfi @joary

**Comment by joary** [comment]
Adding more color, here we can see sessiond receiving a session response with FUI active and result code 4012 (for charging_key: 30)

![image](https://user-images.githubusercontent.com/1166157/144292367-3a40153a-89ee-4e20-ac3c-ac7d6dc8cb91.png)

Session will be installed as expected without internet access.
After some seconds observe the service being deactivated during a charging-credit update:

![image](https://user-images.githubusercontent.com/1166157/144292896-10fdd9cc-4840-462e-8ad9-b9ecb241cabc.png)

Expected:

The CCA-I with FUI+ResultCode(4012) should keep the customer session active, but without any rule installed.
The termination of the session after a CCA-I with FUI+ResultCode(4012) prevents the subscriber to be granted quota in a upcoming RAR or CCR-U.
