### ISSUE TITLE
helm (orc8r) - support configmaps from secrets helm chart to cert-managed helm chart

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#10614]
Our current secrets helm chart also create configmaps that are stored as secrets, we will have to move these to configmaps some other place for fully deprecating secrets helm charts.
```
orc8r-secrets-certs
orc8r-secrets-configs-cwf
orc8r-secrets-configs-orc8r
orc8r-secrets-envdir
orc8r-secrets-registry
```

**Comment by ShubhamTatvamasi** [comment]
@hcgatewood should I move the above config files to the [Orc8r](https://github.com/magma/magma/tree/master/orc8r/cloud/helm/orc8r) helm chart?

**Comment by hcgatewood** [comment]
I don't know that we have to deprecate/remove the secrets chart -- can "secrets" and "certs" sub-charts coexist effectively?

**Comment by ShubhamTatvamasi** [comment]
Yes, they can coexist. In that case, we can update the secrets chart to avoid adding certificates secret if cert-managed charts are being deployed.

**Comment by ShubhamTatvamasi** [comment]
I have figured out the way for supporting both `secrets` and `certs` helm charts in a single deployment. Configs part will be taken care of by `secrets` helm chart and certificates part will be taken care of by `certs` helm chart.
