### ISSUE TITLE
SubscriberID set as a "IMSI +number" for AMF-SMF gRPC communication.

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#10632]
As we know, we are doing the refactor of sessiond data structure of 5G and already done for SessionStore. It means SessionStore is storing for 4G and 5G sessions and primary key is IMSI.
For Pipelined, same grpc method is used for usage report, monitoring etc for 4g and 5g for sending towards sessiond.

For 4G, all requests are coming from MME or Pipelined as a “IMSI + number” to sessiond. 
For 5G,  requests are coming from AMF as a “number” without IMSI keyword and from UPF, coming as a “IMSI + number”. So here, searching the session info from SessionStore getting failed.

We need to do all requests as a same pattern for IMSI value and in line with 4G as well.

Dec  2 08:32:34 magma-dev-focal sessiond[25901]:   magma.lte.SetSMSessionContext {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:       common_context {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         sid {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           id: "901700000000001"
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         }
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         ue_ipv4: "0.77.33.142"
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         apn: "internet"
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         rat_type: TGPP_NR
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:       }
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:       rat_specific_context {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         m5gsm_session_context {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           pdu_session_id: 1
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           gnode_endpoint {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:             end_ipv4_addr: "178.127.0.0"
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           }
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           procedure_trans_identity: "\001-\r\333"
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           default_ambr {
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:             max_bandwidth_ul: 100000000
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:             max_bandwidth_dl: 200000000
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:           }
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:         }
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:       }
Dec  2 08:32:34 magma-dev-focal sessiond[25901]:   }

**Comment by prabinakpattnaik** [comment]
We have planned for fix this issue on sessiond.

**Comment by mehul-jindal** [comment]
[13-Dec-2021: Mehul] Raised the following PR #10825

**Comment by panyogesh** [comment]
#10825 will be closed without any change and #10972 (changes in AMF) will address the issue.

**Comment by GANESH-WAVELABS** [comment]
[06-01-2022 : Ganesh . I] AMF PR #10972 has been merged into master so closing this task.
