### ISSUE TITLE
[TerraVM]: TC34 Expected behavior for Timer 3560 expiry for Security mode Procedure

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#10645]
This is regarding the expected behavior for expiry of timer 3560 on security mode timer expiry after completion of re-transmission TC34 : _Attempt UE Registration when security mode completion was not sent to AMF in the previous registration attempt_

As per the specification 24.501 "Section 5.4.2.7 Abnormal cases on the network side" It says :
------
b) Expiry of timer T3560.
The network shall, on the first expiry of the timer T3560, retransmit the SECURITY MODE COMMAND message and shall reset and start timer T3560. This retransmission is repeated four times, i.e. on the fifth expiry
of timer T3560, the procedure shall be aborted.
------

It does not  specifies which  packet to be sent out.  As per the current behavior in Magma after the expiration of timer for security mode the procedures is aborted, a context release message is sent out. 

For Registration Reject there is no specific cause for security mode reject.
Kindly let us know for any observations/comments  (w.r.t to any spec reference). If not will like to align the existing testcases accordingly (as per current magma behavior).

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please look into the above explanation , and cross check from the specification document and revisit the testcases expectations.

Let me know if you need any more clarification.

**Comment by arun-magma** [comment]
@NeelimaKalpana 
Ref traces and behavior enclosed, Kindly check

[https://app.zenhub.com/files/170803235/0dafd846-c04a-4e28-9001-458649911565/download](https://app.zenhub.com/files/170803235/0dafd846-c04a-4e28-9001-458649911565/download)

**Comment by NeelimaKalpana** [comment]
Hi Yogesh and Moin ,

Please find the pcaps for TC34 . I can see that WL-Local server flow is matching with TVM-Core pcaps.
https://app.zenhub.com/files/170803235/48732536-0879-4d32-a047-00073bb508eb/download

But here also as part of TC verdict they are expecting a Reg-Rej.

@Arun ,
As we are not getting any Reg-Rej in TVM-Core can we change the Verdict expectation in both TC33 and TC34 .

Please find verdict logs for reference.
https://app.zenhub.com/files/170803235/2747df9d-fa0d-4bd4-9f89-372a72d5d3c4/download

**Comment by Kaleem-Wavelabs** [comment]
@arun-magma 

As part of the specs, it only indicates the abort the procedure, do not indicate any reject message with specific cause value.  Suggest to change the verdict expectation in the script to align with the specs.
Please let us know if you come across anything differently for this scenario.

_b) Expiry of timer T3560.
The network shall, on the first expiry of the timer T3560, retransmit the SECURITY MODE COMMAND
message and shall reset and start timer T3560. This retransmission is repeated four times, i.e. on the fifth expiry
of timer T3560, the procedure shall be aborted._
CC @NeelimaKalpana

**Comment by arun-magma** [comment]
Script is Under investigation with above expectation

**Comment by NeelimaKalpana** [comment]
Hi Arun, 

Please let me know for any  inputs required from our end.

**Comment by arun-magma** [comment]
Security Mode Command Retry has been added into verdict removing Reg_Reject message. TC passing and changed the TC to Merged state as it results are as expected.

![Screen Shot 2021-12-21 at 8.51.31 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/b6505870-b172-424f-8d49-459a0a02e1b1)

**Comment by NeelimaKalpana** [comment]
Thank you Arun for providing script modification. TC34 TC is passing in todays regression.

**Comment by rupa455wavelabs** [comment]
Issue got resolved, closing the issue.
