### ISSUE TITLE
Avoid triggering build-all in forked repo

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#10647]

**Comment by themarwhal** [comment]
@quentinDERORY  Do we want to do this for the lte integ test as well? I was thinking that since we'll have to pull down build cache from S3 for those jobs, it might be good to limit it to upstream unless explicitly specified otherwise.

**Comment by quentinDERORY** [comment]
yes we can do that, I will restrict integ test only for on fork push and let it open for workflow_dispatch(on demand).
