### ISSUE TITLE
[TerraVM]: TC33 Expected behavior for Attempt UE Registration when initial context response was not sent to AMF on the previous registration request

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#10646]
This is regarding the testcase TC33.

If the ICS response is missing an imiplicit de-registration timer has to be started and the Context needs to be cleaned up.

But on the Pcaps the new UE registration will be established as its a new connection.  So the current behavior of TC33 seems to be fine.
There is no rejection packet which will be put on the wire.

Any reference to the spec which is not inline with the current behavior kindly let us know. If not then can we tune the testcases with the existing behavior,

**Comment by NeelimaKalpana** [comment]
Hi Arun,

This is also need to be cross checked . We are at to find any reference in 3gpp-spec , please share if you have found it. 
I suggest let's align TC to the magma's current implementation.
Let me know if you need any more clarification.

**Comment by arun-magma** [comment]
@NeelimaKalpana 
Ref Traces and behavior enclosed, kindly check.

[https://app.zenhub.com/files/170803235/46c1662a-65ce-4020-aa06-32727f7b1ec9/download](https://app.zenhub.com/files/170803235/46c1662a-65ce-4020-aa06-32727f7b1ec9/download)

**Comment by NeelimaKalpana** [comment]
Hi Moin and Yogesh,

Please find the latest pcaps for TC33 .
Please find the pcap screen shots for quick reference, showing difference between pcaps shared by Arun.

Pcap from TVM-Core:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/89bac4b5-c924-4ab1-8a6a-f75c9e577482)

PCAP_Local_Execution_143-Server:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/31d702ee-7ac3-4d32-9110-c6b4c9955ade)

@Yogesh: In this scenario in the testcase verdict they are expecting a Registration-Reject message.
Please give the clarity on , either we are going to release the context with out sending a Reg-Rej of we need to send a Reg-Rej and release the context.
Note: In TVM-Core also we didnt received any Reg-Rej.
[https://app.zenhub.com/files/170803235/451b2c8f-259c-4b64-be1a-053159ae5972/download](https://app.zenhub.com/files/170803235/451b2c8f-259c-4b64-be1a-053159ae5972/download)

**Comment by NeelimaKalpana** [comment]
Hi Yogesh and Moin ,

Please find the pcaps for TC34 . I can see that WL-Local server flow is matching with TVM-Core pcaps. 
[https://app.zenhub.com/files/170803235/48732536-0879-4d32-a047-00073bb508eb/download](https://app.zenhub.com/files/170803235/48732536-0879-4d32-a047-00073bb508eb/download)

But here also as part of TC verdict they are expecting a Reg-Rej.

@Arun ,
As we are not getting any Reg-Rej in TVM-Core can we change the Verdict expectation in both TC33 and TC34 .

Please find verdict logs for reference.
[https://app.zenhub.com/files/170803235/2747df9d-fa0d-4bd4-9f89-372a72d5d3c4/download](https://app.zenhub.com/files/170803235/2747df9d-fa0d-4bd4-9f89-372a72d5d3c4/download)

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

In TC33 , AMF is not going to send any reg-rej as registration was successful for that UE. As IntialContextResponce is related to gnodeb .

Please modify TC expectation accordingly.
Please check above attached TC-Verdict logs and PCAPS for your reference.

**Comment by arun-magma** [comment]
Registration Reject part of verdict Fixed and TC Passed

**Comment by NeelimaKalpana** [comment]
Thanks Arun for the update.
