### ISSUE TITLE
[Magma] [Bug] GTP Echo indication errors

### ISSUE THREAD

**Issue by fb-mose** [magma/magma#10658]
### Environment
**Version:** 1.6.1
**Affected Component(s):** AGW
**Affected Sub-Component(s):** ovs
**Deployment Environment:** bare-metal
### Problem Description
**Description**
eNB is sending UE release request with `transport resource unavailable` and also `GTP error indications` due to AGW sending GTP echo response with different length.

It was notice that on OVS version  2_15_2-5 and  2_15_2-6, the length of GTP Echo response sent by AGW is 4. This is different from the version  2_15_2-1 which is length 6 and it was working(no GTP errors sent by eNB).
**Workaround**
NA
**Impact**
UE disconnection
**Triaging Steps**
NA
**Reproduction Steps**
Install magma 1.6.1 with ovs version 2_15_2-6
**Expected Behavior**
AGW should response with correct GTP response length

**Internal Task:** T107223794

![image](https://user-images.githubusercontent.com/37117037/144528783-919400f1-e169-4a79-b2b3-4968c649e7f5.png)
![image](https://user-images.githubusercontent.com/37117037/144528800-065c8bd2-9bf6-4113-b424-b549ada09ace.png)

**Comment by pshelar** [comment]
@wallyrb GTP echo response packet has 4 bytes of data( seq number 2 bytes + recovery (type bytes: 1, value bytes: 1): 2 bytes. so the length should be four. Do you have GTP echo response packet capture from other AGW that shows length as six?

**Comment by wallyrb** [comment]
Hey @pshelar yes full logs are in the internal task T107223794, both pcap traces are attached there.
