### ISSUE TITLE
[Regression]TC7d failing because of PDU-Retry .

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10662]
Your Environment

- Version: 
- Affected Component: Access Gateway    
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

Describe the Issue
TC7d failing because of PDU-Retry .

**To Reproduce**
Execute the Test cases in the flow shown in the Sreenshot

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1d265d1b-e85d-439b-8942-6cd70c0c684b)

Expected behavior
Proper clean-up should happen and PDU-session should come up successfully.

**Screenshots**
Test case passing after service restart.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/c5f93368-c599-48d0-8723-65217efa9544)

[https://app.zenhub.com/files/170803235/3a327064-994d-4ea8-bbc2-ba81b4f5591b/download](https://app.zenhub.com/files/170803235/3a327064-994d-4ea8-bbc2-ba81b4f5591b/download)[https://app.zenhub.com/files/170803235/291f71bf-57a4-442c-b271-187db8b44180/download](https://app.zenhub.com/files/170803235/291f71bf-57a4-442c-b271-187db8b44180/download)

**Comment by moinuddin1980** [comment]
As per TC execution procedure, the TC 7d gets executed in suite.
The sctp connection need to be reset properly.
Hence, it need to be checked, if sctpd reset was done after each TC execution or not?

**Comment by NeelimaKalpana** [comment]
Hi Moin,

As per my understanding we need not do sctpd reset after every script. PDU-Release and De-Registration is done in all the TC's for clean-up. Please let me know for any more inputs on this.

**Comment by moinuddin1980** [comment]
![image.png](https://images.zenhubusercontent.com/6184f6ae82047233ede1227b/d9259005-5508-4328-ae0a-9efd9fc5d90a)
With the private build (with fixes in AMF "during t3592 expiry, now the concerned PDU sessions are intimated to SMF for release) now the original issue of PDU retry as depicted above is resolved.

As the TC7d execution proceeds further, it establishes a new PDU session, as depicted below.
![image.png](https://images.zenhubusercontent.com/6184f6ae82047233ede1227b/ee76d7a7-999e-44ca-af26-8e45486323f6)

But there is no de-registration triggered from the UE side. This results in a stale PDU session, after the TC execution is over. Also, the SMF cannot trigger the clearing of this stale PDU session all by itself.

And this is the reason any other TC(considering same imsi and PDU session id) executed after this, will fail in establishing the new PDU session.

Request you to please check why there is no deregistration procedure triggered in the TC7d.

**Comment by RahulKalsangra** [comment]
The T3592 timer is aborted after maximum "PDU session release command" retry.
And there is no way for the SMF to know what need to be done with the PDU session under consideration.
As the PDU session is already out of the AMF context, it will become a stale one from the SMF perspective as well.
Hence, it need to be intimated to the SMF for removal from it's context.
pr Raised :[ #10933](https://github.com/magma/magma/pull/10933)

**Comment by NeelimaKalpana** [comment]
Closing this issue as problem in this case is fixed.

Validated and closing with proper logs and pcaps 
 [https://app.zenhub.com/files/170803235/5d901841-01c2-4728-90cd-7f273941f883/download](https://app.zenhub.com/files/170803235/5d901841-01c2-4728-90cd-7f273941f883/download)
