### ISSUE TITLE
[AMF]: Authentication reject on getting authentication failure from UE with different causes

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#10663]
This is reference to testcase TC43d and TC43e. As part of Authentication Procedure UE is sending Authentication failure with Error as UE Security Capability Mismatch and Security Mode failures.

Although this is related to security mode but as its Authentication Failure so AMF has to respond with Authentication Reject (with the logs saying its not un-related error).

Reference : 3GPP TS 24.501 version 15.6.0 Release 15
5.4.1.2 EAP based primary authentication and key agreement procedure

General section : It states : 

If the authentication of the UE completes unsuccessfully, the EAP-failure message is transported from the network to
the UE using the AUTHENTICATION RESULT message or the AUTHENTICATION REJECT message of the EAP
result message transport procedure or in a response of the initial 5GMM procedure as part of which the EAP based
primary authentication and key agreement procedure is performed

**Comment by panyogesh** [comment]
[https://app.zenhub.com/files/170803235/d1894910-26b6-47c8-84be-886ef69fb2e1/download] 
   (https://app.zenhub.com/files/170803235/d1894910-26b6-47c8-84be-886ef69fb2e1/download)[https://app.zenhub.com/files/170803235/a6aaa004-da93-47c4-850a-8f2fb4b41205/download](https://app.zenhub.com/files/170803235/a6aaa004-da93-47c4-850a-8f2fb4b41205/download)

**Comment by Sathyaj27** [comment]
Have made the required code changes for authentication reject at amf_proc_authentication_failure .
Yet to test.
