### ISSUE TITLE
[Usage Reporting] There is no traffic flow when enable_pull_stats flag is set to true.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10692]
Your Environment

- Version: 1.7.0-1638583943-b4fbd713
- Affected Component: Access Gateway 
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue
There is no traffic flow when enable_pull_stats flag is set to true. 

**To Reproduce**
1. set the enable_pull_stats : true in  /etc/magma/sessiond.yml .Please find the sceenshot for he same.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/3426a6d5-0504-415d-9b23-3da0b8fedda2)

2. Trigger the basic traffic Test case to monitor the metrics and usage reporting graph . Execute SA_01_02_03_04_Hyper_Suci 
3.Please check for the traffic flow.

**Expected behavior**
Traffic flow should be fine.

Note: Tested with and without /var/opt/magma/pipelined.yml changes. in both cases if enable_pull_stats is set to true I can see there is no traffic flow.
 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/beb79f54-2d64-49ee-b9cc-50effbc42ad3)

With pipelined changes and enable_pull_stats :true [https://app.zenhub.com/files/170803235/65903650-45d6-4a75-a957-60e5eb6d4d4e/download](https://app.zenhub.com/files/170803235/65903650-45d6-4a75-a957-60e5eb6d4d4e/download) ---> traffic loss
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/8b873ac0-d8d1-4418-9756-e94a3b519ad1)

**Comment by panyogesh** [comment]
@rupa455wavelabs : Can we please confirm if the issue is fixed.

**Comment by NeelimaKalpana** [comment]
With Pull stats enabled traffic flow is going fine.
And stats are getting updated in the Usage reporting.
