### ISSUE TITLE
Idle and Active Mode transition with Multi PDU Session is failing

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#10738]
Your Environment
Version: magma/focal-ci, now 1.7.0-1638987121-f05b82db amd64
Affected Component : Access Gateway
Affected Subcomponent : AGW service

**Describe the Issue**

**Actual Behavior:** 

UE should not able to transit from Idle Mode to Active state when we test with Multi PDU sessions(Only one PDU session is able to transition from IdleMode to Active Mode). 

**Expected Behavior:**

UE should go to Idle Mode to Active Transition with Multi Pdu session.

**Comment by moinuddin1980** [comment]
Please attach the relevant mme. syslogs and pcaps.
What is the TC status when run individually?

**Comment by rupa455wavelabs** [comment]
Hi @moinuddin1980 , Please find the pcap and logs below.

 TC status when individually:
  4th Pdu session Attempt is getting rejected due to Cause #91(DNN not 
  supported or not subscriberd in the slice)

 
![image.png]

(https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/8e6949e7-c8d6-47eb-9a84-9d56d066bce0)
[https://app.zenhub.com/files/170803235/20f4c168-b574-4430-94e5-e9a3649fe525/download](https://app.zenhub.com/files/170803235/20f4c168-b574-4430-94e5-e9a3649fe525/download)

**Comment by rupa455wavelabs** [comment]
Please find the attached pcap and logs below
[https://app.zenhub.com/files/170803235/a877f893-0628-4974-8c46-46420f5fa675/download](https://app.zenhub.com/files/170803235/a877f893-0628-4974-8c46-46420f5fa675/download)

**Comment by rupa455wavelabs** [comment]
It's a duplicate of #10739 issue.
