### ISSUE TITLE
Inconsistent commit hash on the CI dashboard

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#10743]
Noticing that the commit hash in the table doesn't always seem to match the commit hash in the actual job.

https://magma-ci.web.app
<img width="1776" alt="Screen Shot 2021-12-08 at 4 07 59 PM" src="https://user-images.githubusercontent.com/37634144/145284565-b5f8c532-e737-433e-8ecf-9c0b6965774f.png">

If I click on the CWF Integ test red circle in the same row as `1e3e3d09` I get to this job.

https://github.com/magma/magma/actions/runs/1551727157

Which looks like
<img width="1024" alt="Screen Shot 2021-12-08 at 4 09 11 PM" src="https://user-images.githubusercontent.com/37634144/145284721-eaadadc8-0bba-4dd8-84ac-e8e3d359cd99.png">

1. The job is still ongoing and it has not failed
2. The commit hash and the author are different

**Comment by talkhasib** [comment]
There is no problem with Dashboard
Issue is, the CWF test fails to generate any test result (XML file).
In this case, we publish the run ID to firebase as reference point

**Comment by themarwhal** [comment]
> There is no problem with Dashboard
> 
> Issue is, the CWF test fails to generate any test result (XML file).
> 
> In this case, we publish the run ID to firebase as reference point

@talkhasib where is the run ID published?

**Comment by talkhasib** [comment]
> @talkhasib where is the run ID published?

If there is no HTML report available, clicking on the failed report will lead you to the github actions run
