### ISSUE TITLE
how to configure URL redirection when QUOTA_EXHAUSTED !!

### ISSUE THREAD

**Issue by blueCARDSS** [magma/magma#10741]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** AGW : 1.6.0-1625592603-1f26ba81
- **Affected Component:** FEG 
- **Affected Subcomponent:** AGW 
- **Deployment Environment:** e.g. AWS (orc8r), , bare-metal (AGW),

### Describe the Issue

how to configure URL redirection when QUOTA_EXHAUSTED !!

<img width="1298" alt="Screenshot 2021-12-08 at 9 13 56 PM" src="https://user-images.githubusercontent.com/92744847/145269708-3dadfebd-86fb-4179-b9f3-8819b487f87a.png">
<img width="1002" alt="Screenshot 2021-12-08 at 9 13 48 PM" src="https://user-images.githubusercontent.com/92744847/145269724-6053ac06-dbee-4fbd-b17d-5f8e273cc32f.png">
<img width="958" alt="Screenshot 2021-12-08 at 9 13 40 PM" src="https://user-images.githubusercontent.com/92744847/145269726-f2a02595-409a-4815-b380-315b40473e2a.png">
<img width="964" alt="Screenshot 2021-12-08 at 9 13 33 PM" src="https://user-images.githubusercontent.com/92744847/145269729-9be573d5-a628-4438-a13b-5db9153ece7e.png">
<img width="947" alt="Screenshot 2021-12-08 at 9 13 26 PM" src="https://user-images.githubusercontent.com/92744847/145269731-13fa0a39-335b-45b7-81ed-9ec27adf516b.png">
<img width="938" alt="Screenshot 2021-12-08 at 9 13 17 PM" src="https://user-images.githubusercontent.com/92744847/145269746-0b9d41d3-f239-4ec6-9e9d-95fc8d19e3b3.png">
<img width="941" alt="Screenshot 2021-12-08 at 9 13 11 PM" src="https://user-images.githubusercontent.com/92744847/145269751-f687687e-3eab-46d1-aa91-e4c25bbf434d.png">
<img width="976" alt="Screenshot 2021-12-08 at 9 13 02 PM" src="https://user-images.githubusercontent.com/92744847/145269761-a74f9429-4781-4a93-a9d0-081ef88fdca9.png">
<img width="1305" alt="Screenshot 2021-12-08 at 9 12 50 PM" src="https://user-images.githubusercontent.com/92744847/145269765-54879ae3-bb46-49bc-b03c-24439e836839.png">

**Expected behavior**
we want user to remain in network when QUOTA_EXHAUSTED . and it redirect to portal " https://bluecardss.com/"

**Comment by koolzz** [comment]
@sudhikan do you recall how we setup redirect in lab by any chance?
@andreilee I think you had a captive portal setup before right?

**Comment by blueCARDSS** [comment]
@sudhikan @andreilee your input is highly appreciated .

**Comment by blueCARDSS** [comment]
@uri200 how to configure URL redirection when QUOTA_EXHAUSTED !! Need help

**Comment by uri200** [comment]
Hey @blueCARDSS  did you try to add the ip or url here?

![image](https://user-images.githubusercontent.com/16157139/146598618-9615ae74-be9e-4367-b31a-eae908c36cef.png)

**Comment by sudhikan** [comment]
> @sudhikan do you recall how we setup redirect in lab by any chance? @andreilee I think you had a captive portal setup before right?

hey, sorry for the delay here. But AFAIK we had tested this with Carrier WiFi and the redirect URL came from the PCRF.

**Comment by blueCARDSS** [comment]
@uri200 we tried with url but it didn’t worked . So we got an advise from OCs provider that if we can setup two different rating group one for “ finite “ and Other one for portal with infinite rating . But some how that one also didn’t worked

**Comment by koolzz** [comment]
> @uri200 we tried with url but it didn’t worked . So we got an advise from OCs provider that if we can setup two different rating group one for “ finite “ and Other one for portal with infinite rating . But some how that one also didn’t worked

When testing redirect use a non https website like neverssl.com
