### ISSUE TITLE
No event triggered for Attach Failure in case on unknown User

### ISSUE THREAD

**Issue by amanThakral002** [magma/magma#10756]
### Your Environment

- **Version:** v1.6.1
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** eventd
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue
We are trying out a simply attach failure scenario and checking for event trigger/generated for the same. During attach failure due to 5001 DIAMETER_ERROR_USER_UNKNOWN, no event by eventd generated for same.
**Scenario:** Trying for initial attach with UE Identity (IMSI) which is not configured in AGW through NMS UI subscriber DB.
 **Result:** Attach Failed
 **Expected:** An event to be triggered from eventd, so remote user can understand that attach got failed.

Logs:
**MME log:** [invalid_imsi_mme.log](https://github.com/magma/magma/files/7684773/invalid_imsi_mme.log)
**syslog:** [wrong_imsi.log](https://github.com/magma/magma/files/7684777/wrong_imsi.log)

**Call Trace**: 
[wrong_imsi.zip](https://github.com/magma/magma/files/7684801/wrong_imsi.zip)

**Comment by amanThakral002** [comment]
Any updates on this ?

**Comment by uri200** [comment]
HEy @amanThakral002 , right now it looks like we are reporting the success event. 

We will see if we can add rejects too.

**Comment by ssanadhya** [comment]
Closed with #11461
