### ISSUE TITLE
Local orc8r build fails with docker-compose version 2.1.1

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#10761]
### Your Environment

- **Version:** 1.7 (current master)
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator
- **Deployment Environment:** local docker-compose (orc8r)

### Describe the Issue

**To Reproduce**
1. Install docker-compose version 2.1.1
2. Go to `orc8r/cloud/docker`
2. Execute `./build.py --all`
3. The result is:
```
3 errors occurred:
* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/magma_orc8r_build/home: no such file or directory
* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/magma_orc8r_build/home: no such file or directory
* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/magma_orc8r_build/home: no such file or directory 
```

**Expected behavior**
The orc8r containers should be built successfully.

**Work-around**
Downgrading docker-compose to version 2.0.1.

**Comment by Neudrino** [comment]
This change (or regression) is likely to have happened in the following commit: https://github.com/docker/compose/commit/94379769e300002daa1a4c654baa436c57289b17.

While I am not into the docker-compose, the following line looks as if Dockerfile locations outside of the Docker context are now prohibited: https://github.com/docker/compose/commit/94379769e300002daa1a4c654baa436c57289b17#diff-892466cfaee03eb856c2aa2b468059a44cc6f2df1649136f724b387f1e9ab1c2R275 .

It remains to be clarified if the changes from version docker compose version 2.2.2 mitigate the issue. https://github.com/docker/compose/blob/e2f33af831ae9edcfa8efd53dfe24a36337a8250/pkg/compose/build.go#L290-L295

**Comment by ShubhamTatvamasi** [comment]
I am running Orchestrator builds every six hours, It seems to be working just fine. Have you tried building on Github Action?
Are you making some changes to the Orchestrator or you are trying to build from the upstream master?
https://github.com/ShubhamTatvamasi/magma-build/actions

**Comment by sebathomas** [comment]
It works perfectly for me too in version 2.0.1, it's only in 2.1.1 that it fails. Not sure which version is running in the Github Action.

**Comment by ShubhamTatvamasi** [comment]
You can always check `docker-compose --version`.

**Comment by sebathomas** [comment]
Sure but I'm building it locally, not inside a Github Action. :)

**Comment by ShubhamTatvamasi** [comment]
So I just check for `ubuntu-latest` image it's using:
```
docker-compose version 1.29.2, build 5becea4c
```

**Comment by ShubhamTatvamasi** [comment]
Are you building on macOS or Linux?

**Comment by sebathomas** [comment]
Ah, so the GA version won't be affected then.

I'm on Linux.

**Comment by ShubhamTatvamasi** [comment]
We have not tested the latest docker-compose version on Linux. Are you on Ubuntu or some other distro?

**Comment by sebathomas** [comment]
On Manjaro, they already have a more recent version of docker-compose.

**Comment by Neudrino** [comment]
Possibly related issues in the [docker-compose](https://github.com/docker/compose) project:

* https://github.com/docker/compose/issues/8046
* https://github.com/docker/compose/issues/8170
* https://github.com/docker/compose/issues/8461
* https://github.com/docker/compose/issues/8981

**Comment by Neudrino** [comment]
I.e. Ubuntu should / will also be affected some-when, I believe.

**Comment by sebathomas** [comment]
Update: The build is successful in the more recent docker-compose version 2.2.2. It looks like the build failure is a bug in docker-compose 2.1.1.

I'll close this issue.
