### ISSUE TITLE
TC1d is failing in regression suit

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#10774]
**Description**

Expected behavior:
First invalid UE Registration fails with no response and on retry we get expected error Cause-3 and second valid UE Registration should pass without any issue.

Actual behavior:
TC1d is passing when we run it individually, it's failing in the suit due to pdu session retry.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/5e301b07-6b95-4adc-a7e8-eb81bb7e864c)

**Comment by moinuddin1980** [comment]
The UE imsi under testing with MCC 222, MNC 456 and MSIN 000000102  has no DNN configured in the NMS and as a result it is not available at subscriber db. Thus, the AGW is rejecting this PDU session establishment request with   DNN not supported.
"the DNN internet is not supported and a reject is being sent"

**Comment by rupa455wavelabs** [comment]
Closing the issue, as TC1d is passing in daily regression suit.
