### ISSUE TITLE
bazel: Add repository dependencies for nettle

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#10797]
Libnettle is currently installed here in the devcontainer: https://github.com/magma/magma/blob/master/.devcontainer/Dockerfile#L132

For an example of an existing custom build of a dependency, see [bazel/external/libtins.BUILD](https://github.com/magma/magma/blob/master/bazel/external/libtins.BUILD)
For an example of an existing wrapper library for a system dependency, see [bazel/external/system_libraries.BUILD](https://github.com/magma/magma/blob/master/bazel/external/system_libraries.BUILD)

## Exit Criteria
1. Have the library built manually (like libfluid) or create a wrapper around the dependency (like folly)
2. For custom BUILD files, it is recommended to build and run a small test to make sure everything is linking properly

**Comment by LKreutzer** [comment]
Currently not needed
