### ISSUE TITLE
Refactoring amf UEContext maps

### ISSUE THREAD

**Issue by ganeshg87** [magma/magma#10810]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:**
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
amf has below global data structures to holding ue context data.
	
  (1)std::unordered_map<amf_ue_ngap_id_t, ue_m5gmm_context_s*> ue_context_map
   amf_app_desc_t      
        | 
        |-(2)imsi_amf_ue_id_map
        |-(3)tun11_ue_context_map
        |-(4)gnb_ue_ngap_id_ue_context_map
        |-(5)guti_ue_context_map		

	
	
	a)amf is using five maps ((1),(2),(3),(4),(5)) context lookup based on IMSI, 
	  TunnelID, gnb_ue_ngap_id, GUTI Key types.
	  it is multi level lookup to fetch Ue Context except from ue_context_map
	  GUTI, gnb_ue_ngap_id keys lookup are sequential in existing implementation.
	       
	b) all maps in amf_app_desc_t require to serialize/deserilze for stateless feature.
	

**To Refactor**:
 
     IMSI, TunnelID, gnb_ue_ngap_id, GUTI are part of Ue Context, 
	  a) amf can avoid maps to write/read from Radis DB for the stateless feature.
	  
	  b) amf can have direct logical maps to point shared ue context directly.
	      amfid_ue_context_map
		  gnbid_ue_context_map
		  guti_ue_context_map
		  supi_ue_context_map
            amf can serialize/deserilze only ue context, above maps can reconstruct by conext object.
     	      
	Please have a look below draft PR  for low level implementation sketech
	     1. 1st commit - change ue_m5gmm_context_s* to std::shared_ptr<ue_m5gmm_context_s>
	        https://github.com/magma/magma/pull/10681/commits/f87e8d18beb047040875f0706a3a4ac20daf52f1
		 2. 2nd commit - designed AmfUeContextStorage class to hold context data.
		 https://github.com/magma/magma/pull/10681/commits/8e99a3e05bab53561a66a86a709454f6fa24dd5c

		 3. remove all maps in amf_app_desc_t and use aps from AmfUeContextStorage - TODO
	I would need your feedback on Implementation Sketch . 	  

          PR is in the draft: https://github.com/magma/magma/pull/10681.
         
    https://docs.google.com/presentation/d/10v-0YtlkGOBHzwMyTvSYKekJtXTOeQaj/edit#slide=id.p1

**Expected behavior**
It was an improvement task, all the existing flows should not break.

**Screenshots**
![1](https://user-images.githubusercontent.com/83060027/145659015-6b39eac1-4c77-4d44-a38b-6f4f9e64567f.jpg)

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ganeshg87** [comment]
there was another map defined in amf_idenity.cpp, can replace with supi_ue_context_map
``` // Global map of supi to guti along with amf_ue_ngap_id
std::unordered_map<imsi64_t, guti_and_amf_id_t> amf_supi_guti_map;
```

**Comment by ardzoht** [comment]
@ganeshg87 As part of the stateless enhancement plan, can we include an action item to replace `std::unordered_map` with `google::protobuf::Map` (on `lte/gateway/c/core/oai/include/map.h`), and update the current usages of these hashtables accordingly? The overall idea would be to use directly the protobuf generated Map structures instead, this way we can avoid the steps of converting the local hashtables members to the protobuf structure members, and just have one source to hold these values instead. We can setup a call if it's not clear yet, but hopefully this makes sense.

**Comment by ganeshg87** [comment]
Hi @ulaskozat, @ardzoht, @ssanadhya,

    I would need your approval/feedback on the **implementation sketch** (not code review) to finish the PR(#10681). 
    I will raise complete PR for code review approval separately.

      1. changed ue context to shared ptr(std::shared_ptr<ue_m5gmm_context_t>) (validated with UERANSIM)
      2. designed AmfUeContextStorage class to manage ue context objects.
      
      **below task is pending** for your feedback 
      3. remove all maps defined for amf task and replace them with AmfUeContextStorage APIs

**Comment by ardzoht** [comment]
Left some comments and feedback on #10681
