### ISSUE TITLE
TVM Scale Test: Scale test is failing due to traffic issue

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#10829]
Expected Behavior: 5G call flow and UL, DL traffic should work for 100 UE's

Actual Behavior: 5G call flow successful due to UL & DL traffic issue, TC is failing 

Please check the below attached screenshots
![SUCI_100UE.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/85a82adb-0cce-4f12-8c72-51069fd0d500)

![suci_dereg.PNG]
(https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/c9eb42a0-f6df-44da-a446-b252e23bda9e)

![suci_pdu.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/03f65ecf-c4f2-486b-9409-71e5ffc4cb14)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/024a04cb-ac26-4bab-bda9-c1c9f6ff8c2b)

**Comment by rupa455wavelabs** [comment]
Please check the attached Pcap and logs 
[https://app.zenhub.com/files/170803235/4885206e-a52c-4dbb-8b9c-324c4f9cf365/download](https://app.zenhub.com/files/170803235/4885206e-a52c-4dbb-8b9c-324c4f9cf365/download)

**Comment by panyogesh** [comment]
Closing the issue as UDP started working. If needed we can open a new one.

**Comment by panyogesh** [comment]
Closing the issue as UDP started working. If needed we can open a new one.
