### ISSUE TITLE
UE is implicity deregistered with active traffic

### ISSUE THREAD

**Issue by ymasmoudi** [magma/magma#10862]
### Your Environment

- **Version:** v1.6
- **Affected Component:** AGW
- **Affected Subcomponent:** MME
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

Call flow is explained below:
- UE attached more than 10+ hours, sending data traffic.
- UE initiates UE Context release with cause -- radio-connection-with-ue-lost  (enb restart)
- This is followed by Attach request from UE which is successful
- After the attach is successful, GTP flows through
- Around 2 hours, the UE is implicitly deregistered because of reachability timer expiry

All through, the gtp uplink traffic from UE is being sent (ping traffic), yet the T3412 timer expires. 

The AGW  triggers a local context cleanup upon timer cleanup and stops forwarding traffic without sending UE Context release command to enb.
UE looses data access. 

**Expected behaviour**
The old context should be deleted upon the new attach request and timer stopped. 

**Additional context**
Logs are attached.
[mme_log.tar.gz](https://github.com/magma/magma/files/7714005/mme_log.tar.gz)
[magma_logs.txt.gz](https://github.com/magma/magma/files/7
[s1ap_gtp.pcap.pcapng.zip](https://github.com/magma/magma/files/7714016/s1ap_gtp.pcap.pcapng.zip)
714013/magma_logs.txt.gz)

**Comment by ulaskozat** [comment]
@ymasmoudi is this for 1.6.1 or 1.6.0? one fix we had post 1.6.1 was this: https://github.com/magma/magma/pull/10538. Can they try backporting and testing it?

**Comment by ulaskozat** [comment]
@ymasmoudi I think the issue is that we do not stop the running mobile reachability and implicit detach timers during implicit detach procedure when we receive an attach request for a registered UE (cc @rsarwad, @ssanadhya, @ardzoht).

**Comment by ulaskozat** [comment]
> @ymasmoudi I think the issue is that we do not stop the running mobile reachability and implicit detach timers during implicit detach procedure when we receive an attach request for a registered UE (cc @rsarwad, @ssanadhya, @ardzoht).

strike this comment. I actually see that it gets deleted.

**Comment by rsarwad** [comment]
Hi @ulaskozat , I checked the code of branch v1.6. As part of processing new attach request, MME is stopping the mobile reachability timer and implicit detach timer. 
https://github.com/magma/magma/blob/v1.6.0/lte/gateway/c/core/oai/tasks/nas/emm/Attach.c#L2622
https://github.com/magma/magma/blob/v1.6.1/lte/gateway/c/core/oai/tasks/nas/emm/Attach.c#L2598

**Comment by ulaskozat** [comment]
@rsarwad yes indeed. see my previous comment.

**Comment by ymasmoudi** [comment]
Another partner reports that the issue is fixed in v1.6.1.
We can close this
