### ISSUE TITLE
Unified builder docker image for all builds involving Bazel

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#10860]
# Unified builder docker image for all builds involving Bazel

## Preface

This proposal is _not_ to be confused with https://github.com/magma/magma/issues/10498 regarding unified run time docker images!

## Problem

There are currently efforts ongoing to migrate to Bazel as build system. (https://github.com/magma/magma/issues/8338, https://github.com/magma/magma/issues/9714, https://github.com/magma/magma/issues/9878, among others)

One perceived overall goal with Bazel as build system is the ability to build the complete product with one command (e.g. `bazel build //...`) and to execute all (unit) tests in a similar easy fashion. More advantages of Bazel are detailed in [the original proposal](https://github.com/magma/magma/issues/8338).

With this goal in mind there are some restrictions toward the **Bazel setup**, which derive from Bazel internal workings, which lead to **implication** for the Magma build setup.

* One Bazel build for everything requires to have one workspace only, i.e. one `WORKSPACE.bazel` on top level.
* External dependencies must be, and can only be defined in the `WORKSPACE.bazel`. I.e. the external dependencies for all languages need to be defined there globally.
* Before Bazel starts a build, the workspace is "resolved". To my understanding that means roughly, that all defined external dependencies must be accessible / acquirable / available.

On the other hand in the current state we have the current setup of **separate builder images per service (or language)** and I find the following points noteworthy here.

* Builder images contain only dependencies for that specific language. I.e. external dependencies for other languages are not available (and potentially not desired).
* Builder images can deviate for different services.
(_Personal comment:_ This has pros and cons, such that it is hard to tell if it is advantageous.)
* Examples for one image per service can be found for AGW part of [Python](https://github.com/magma/magma/blob/master/lte/gateway/docker/services/python/Dockerfile) and [C](https://github.com/magma/magma/blob/master/lte/gateway/docker/services/c/Dockerfile).

So the **problem is**, that the **bazelfication** and having **separate builder images** (environments) for the languages appear ~~mutually exclusive~~ **contradicting**, because Bazel aims to have external dependencies required collected centrally for everything, while the idea of separate builder images aims toward a separation.

This is especially important, when it comes to the **CI design**. Language specific builder images would work fine for separate bazel setups for every language, however combining multiple languages in one bazel build are opposing the idea of separate build images.

As an example for the [effort to build Python with bazel](https://github.com/magma/magma/pull/10341) we get:
* :heavy_check_mark: Bazel build works on VM (no CI coverage)
* :heavy_check_mark: Bazel build works in devcontainer ([CI covered](https://github.com/magma/magma/runs/4525781522?check_suite_focus=true))
* :x: Bazel build does not work for C specific build environment ([CI covered](https://github.com/magma/magma/runs/4525778144?check_suite_focus=true))

This contradictory discrepancy makes bazelfication for additional languages (e.g. Python) hard and cumbersome.
It is undesirable to be forced to do major infrastructure changes for every new service, which is added within the path of bazelfication of the project.

### Further considerations

* Currently builder images are not overly clearly separated from docker artifacts created for the services as build result. While there are certainly some advantages to this approach, this entanglement adds additional complexity to the docker image management.
* Version congruence (same versions for tools) is more difficult for multiple builder images. There are different aspects pro and con the desirability of version congruence.
* The maintenance effort for multiple images is higher compare to one image.
* While this proposal is motivated by bazelfication of Python currently, even without bazel the unification of builder images can hold advantages and be discussed.

### Goal

As a developer introducing bazel to a new part of the project (service, etc.) for a supported programming language, I want to have a known platform, where no (or only minor) changes are necessary, in order to focus on the bazel setup. 
A sensible CI check would contribute to a clear definition of done and supports a safe migration.

#### One (docker image) to build it all

The obvious solution by the mechanics Bazel implies, would be the "one stop shop" image for bazel builds. I.e. we would have one builder docker image, which has all necessary dependencies for all languages. Whatever you want to build with bazel, this image would be enabled to do it.

I see the following advantages:
* It is clearer in/against which environment any component is build (in the CI).
* Developers can easily use the same build environment (locally or in the cloud) as the CI does for its checks. (No questions like: Builds on my setup A but not in CI. Why?)
* A reduced resource usage is expected because unnecessary rebuilds are avoided. Docker builder image can be prebuild and used from GHCR. A further reduce is likely caused by sensible docker layer caching.
* Reduction of code duplication of multiple similar docker builder images. With that a reduced maintenance effort.

It depends on the viewpoint and arguments, whether the following points are perceived as advantages (at least I do):
* The build environment would have homogeneous dependency versions across multiple components.
* Dependency upgrades can be done for multiple components with minimal effort.
* Reduction of complexity regarding the build infrastructure setup.

Possible existing docker image candidates to be extended in this _one_ builder image are:
* the [bazel-base image](https://github.com/magma/magma/blob/master/experimental/bazel-base/Dockerfile) or
* the [devcontainer image](https://github.com/magma/magma/blob/master/.devcontainer/Dockerfile).

### Multiple-builder images

If choosing an approach of multiple builder images, the assumption and goal of a combined build for all languages needs to be questioned. Having multiple build environments, they will be different and naturally diverge more and more as time passes, if no energy against this entropy increase is mustered.

There are arguments to support this strategy.
* In case of different build tools for different languages a separation of concerns is easier.
* Teams responsible for different languages can have their own build environment and maintain it independently, i.e. with less interference with others.
* The usage of dependencies in different versions for different components is easier. (If different versions of the same dependency is desired, is another question.)

### No build inside docker at all

One could also abandon the concept of building inside docker images altogether.
* For the CI that would mean that we need a specially prepared worker node (=Github actions runner) capable of building everything.
  * Currently Github provided runners are used. In that case a elaborate setup of the runner before the build is necessary each time.
  * One could use customized, self-hosted runners, however, they imply setup, maintenance and infrastructure costs.
* It remains unclear to me what the strategy for local build would look like in this scenario.
  * There are some projects striving to provide [Github actions locally](https://github.com/nektos/act), however the appear early stage.

## Non-goals

* Runtime environments as discussed in https://github.com/magma/magma/issues/10498.
* Changes to artifact packaging.

**Comment by Neudrino** [comment]
Reserved. :wink:

**Comment by Neudrino** [comment]
Reserved. :wink: :stuck_out_tongue:

**Comment by nstng** [comment]
Closed as out-of-scope for now.
