### ISSUE TITLE
Unable to delete the multiple subscribers in NMS Dashboard

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#10873]
Delete & Update subscribers button  in NMS dashboard is not working as expected.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/3555c83f-d854-481d-aa1b-79d97e7a79f9)

**Comment by rupa455wavelabs** [comment]
In the Add subscribers page also we are unable to add multiple rows for adding multiple subscribers, Please check the screenshots for the same
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/6f1bbd44-a8be-4824-b02f-3a8dc323fca8)

If I am trying to add new row, it is hiding the existing row
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/56c8be09-ebb2-49c0-8c36-dbcb400ca092)

**Comment by anusha-konda** [comment]
@rupa455wavelabs , as discussed when clicked on "Add New Row", after filling the details of subscriber, please click on Actions (tick or wrong). This will save the row and will not be hidden when clicked on "Add New Row" next time.
