### ISSUE TITLE
Modify sgw and sgw_s8 to work with centralized user plane TEID on inbound roaming

### ISSUE THREAD

**Issue by rsarwad** [magma/magma#10876]
### Your Environment

- **Version:**
- **Affected Component:**  Access Gateway, 
- **Affected Subcomponent:** sgw,sgw_s8  and 5G smf/ session manager
- **Deployment Environment:**  Vagrant (AGW)

### Describe the Issue
User plane teid is used at OVS to route the data packets on specific bearer/tunnel. The user plane needs to be unique across 4G normal user, 4G inbound user and 5G user. 
Currently user-pane teid for 4G users is allocated between 0 to 7FFFFFFF and for inbound 4G users and 5G users, it's allocated from 80000000 to FFFFFFFF. 
Issue here is user plane teid is same for both inbound 4G users and 5G users;

Now we will work on centralized teid allocation. We need to explore how we need to allocate unique user plane teid for all these users.

**Expected behavior**
Assign unique UP teid for all these users

**Comment by ssanadhya** [comment]
@rsarwad , could you please confirm if #10985 resolves this issue? If not, what is pending?

**Comment by rsarwad** [comment]
> @rsarwad , could you please confirm if #10985 resolves this issue? If not, what is pending?

The user plane needs to be unique across 4G normal user, 4G inbound user and 5G user.
Currently user-pane teid for 4G users is allocated between 0 to 7FFFFFFF and 5G users  it's allocated from 80000000 to FFFFFFFF.
For inbound 4G user, teid is allocated by Orc8r. So there are chances to have collision with teid allocated by AGW for 4G normal user and 5G user. So we need have unique teid pool for all these 3 users
