### ISSUE TITLE
Magma GTP Gateway

### ISSUE THREAD

**Issue by Arsenii-Oganov** [magma/magma#10882]
**Objectives**

The objective is to add a GTP aggregation gateway to the Magma system. This Gateway will aid in scale deployments where S8 inbound roaming is supported by reducing the number of integration points for roaming partners.

**Background**

In traditional telecom deployments using a centralized (or non-distributed) core, roaming interfaces are limited in number. These interfaces often connect to an IPX/GRX network provider to aggregate roaming traffic into a small set of interfaces, regardless of the number of roaming partners an operator may have. 

In the case of S8 roaming interconnections, the connection supports GTP-C and GTP-U traffic between the SGW in the visited network and the PGW in the home network. The SGW IP for the GTP-U endpoint must be routable from the home network. When using an IPX/GRX provider, this means having a globally routable IP address dedicated to the IPX/GRX network interface of an SGW.

Magma has a distributed core architecture. Each cell site, where the Access Gateway (AGW) element usually resides, has an SGW. The requirement that each site have a globally routable IP dedicated to the IPX/GRX connection (i.e. not a general traffic WAN port ISP provided address) is a challenge for operators using Magma core for roaming. Furthermore, IPX/GRX vendors are reluctant to support large numbers of VPN terminations coming from each AGW.

Pull request with proposed solution - https://github.com/magma/magma/pull/10901

**Comment by uri200** [comment]
Hey @Arsenii-Oganov, note we are still working on getting unique TEIDs per network. Meaning every subscriber will get a unique TEID. So two subscribers in different AGW of the same agw network will never have the same TEID.

**Comment by uri200** [comment]
After reading the proposal I see this will be a whole separate gateway. We will have to define where those configurations are store. 

Per what I can see this is only for Federated case and Inbound roaming case so maybe we need to create a whole set of different end points: we have LTE Federated Gateway, whe may need an GTP Federated Gateway with all its new endpoints defined. I don't think this entity can be created inside AGW or FEG gateway.



I am still not understanding how GTPG will work but per what I can see this will be transparent to the AGW. The AGW Will have to be configured with a specific IP, which will happen to be the GTPG. Then GTPG will read and learn from every single packet and will route it accordingly.   When a packet is received from the internet, it will do the reverse action. 

In that case I think we won't have to define anything  new on AGW configuration. The AGW will point to a specific IP which will be that GTPG. Is that correct?

**Comment by pshelar** [comment]
Can you expand on "3.2.5 HA Active Active".
For active Active HA, we need to sync the IP -> TEID state across AGWs. how is that done?

**Comment by pshelar** [comment]
can you also explain the scaling solution mentioned in the doc, I am not sure how skb-mark would be used? which networking component would be involved.

```
Alternate solutions may use @mark attribute of the sk_buff struct or other native linux networking stack functions/attributes for flow mapping. Such solutions will be explored for scale performance and evaluated against the OVS solution.
```

**Comment by jpad-freedomfi** [comment]
> Hey @Arsenii-Oganov, note we are still working on getting unique TEIDs per network. Meaning every subscriber will get a unique TEID. So two subscribers in different AGW of the same agw network will never have the same TEID.

We have 500 AGWs per network and multiple networks. We found API and NMS don't like having more than 500 AGWs per network. 

As such, sounds like we will have some non-zero probability of TEID collision across networks. We'll need to ensure we have some retry mechanism to help resole these cases.

**Comment by jpad-freedomfi** [comment]
> After reading the proposal I see this will be a whole separate gateway. We will have to define where those configurations are store.
> 
> Per what I can see this is only for Federated case and Inbound roaming case so maybe we need to create a whole set of different end points: we have LTE Federated Gateway, whe may need an GTP Federated Gateway with all its new endpoints defined. I don't think this entity can be created inside AGW or FEG gateway.
> 

Agreed, we were thinking this would be first class gateway, standalone, like FeG or AGW, but not embedded inside of either. 

> I am still not understanding how GTPG will work but per what I can see this will be transparent to the AGW. The AGW Will have to be configured with a specific IP, which will happen to be the GTPG. Then GTPG will read and learn from every single packet and will route it accordingly. When a packet is received from the internet, it will do the reverse action.
> 

That is correct. What is you concern with GTP? If OVS does flow learning based on TEID/UE IP then all NAT functions can be transparent to GTP endpoints. @amarpad has more details here. 

> In that case I think we won't have to define anything new on AGW configuration. The AGW will point to a specific IP which will be that GTPG. Is that correct?

On AGW side we use the wiregaurd/L3 tunnel Pravin has added.

**Comment by amarpad** [comment]
Yeah we are just going to learn the ue_ip->tunnel_ip (effectively AGW) on the packets.

**Comment by lucasgonze** [comment]
Stale
