### ISSUE TITLE
bazel: Blockers for migrating all C/C++ services to be built with Bazel for production/CI/development

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#10890]
Work for MME is tracked here separately: https://github.com/magma/magma/issues/9714

## Is a blocker and seeking an owner
- [x]  https://github.com/magma/magma/issues/11835
- [x] #12059
- [x] #12210

## Not a blocker but needs action soon
- [x] https://github.com/magma/magma/issues/12058

## Cleanup work
- [x] #12063

## In Progress
- [x]  https://github.com/magma/magma/issues/11870 @ajahl 
- [x] #12064 @themarwhal 

## Completed
- [x] https://github.com/magma/magma/issues/10893
- [x] https://github.com/magma/magma/issues/10910
- [x]  https://github.com/magma/magma/issues/10919
- [x] #12060

## PRs that need to be merged together
- https://github.com/magma/magma/pull/10590
- https://github.com/magma/magma/pull/10544
- https://github.com/magma/magma/pull/10592

**Comment by nstng** [comment]
all sub-tasks done
