### ISSUE TITLE
[Regression]Paging is not getting triggered as there is no UDP-Traffic after UE-Idle mode.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10949]
Hi Arun ,

In latest regression run (21-12-2021) , seeing that paging is not getting triggered properly as we are not receiving UDP traffic.

Failure PCAPS: 
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/fc3ebc11-40fc-4d71-b609-3f3d77d3ebca)

Working Scenario pcap capture :
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/af7b37d5-1ae4-472e-b89f-8faf44a2c1e0)

Please let us know if there is any changes in the traffic triggering in the script or some thing got broken because of lab maintenance .

Form development side there are no code changes w.r.t tp paging scenarios.[https://app.zenhub.com/files/170803235/b2524e35-594a-4631-b75f-14efdd92aa67/download](https://app.zenhub.com/files/170803235/b2524e35-594a-4631-b75f-14efdd92aa67/download)

Please find the attached working and failure pcaps for your reference.

**Comment by arun-magma** [comment]
Probably a Momentary issue, tested this morning on Regression AGW (141) and found a DL UDP pkt which triggers the paging. This TC passes as before.

[SA_TC9_AMF_Initiated_Paging_211221_115948-1.pcapng.zip](https://github.com/magma/magma/files/7760141/SA_TC9_AMF_Initiated_Paging_211221_115948-1.pcapng.zip)


<img width="1758" alt="Screen Shot 2021-12-21 at 9 04 31 PM" src="https://user-images.githubusercontent.com/70725754/147038673-acb747a5-7600-4efb-a220-4b97c2b0dc5a.png">

**Comment by NeelimaKalpana** [comment]
Hi Arun ,
We are observing above specified behavior when number of gnodebs  set as '1' .

After changing the number of gnodebs set to  '12' testcases are behaving as per testcase flow.
Please let me know if there is any dependence on number of gnodeb s in TC9 series testcases.

**Comment by rupa455wavelabs** [comment]
As UDP traffic issue got resolved paging is triggering, please check the below pcap for more info:

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/d1454a1b-2ff8-4c0d-8d47-569a8210238c)
