### ISSUE TITLE
[Regression]TC9b is failing as proper PDU-Session clean-up is not happening  because of delayed pdu-release procedure in previous testcase. 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10968]
Your Environment

- Version: 
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue
TC9b is failing as proper PDU-Session clean-up is not happening  because of delayed pdu-release procedure in previous testcase. 
In this case pdu-relese from amf to smf is getting delayed and by that time a new pdu-request with same id is coming to smf so smf is considering that as a duplicate request.

**To Reproduce**
Execute TC9a and then TC9b , TC9b is failing as PDU-Retry is happening.

**Expected behavior**
Proper clean-up should happen .[https://app.zenhub.com/files/170803235/13e0cf56-d36d-40d5-a04a-3518264efde1/download](https://app.zenhub.com/files/170803235/13e0cf56-d36d-40d5-a04a-3518264efde1/download)

**Comment by NeelimaKalpana** [comment]
Please find requested mme and syslogs from the attachment.
[https://app.zenhub.com/files/170803235/c769e141-88ac-4bb8-b789-4a091dc8eca7/download](https://app.zenhub.com/files/170803235/c769e141-88ac-4bb8-b789-4a091dc8eca7/download)

**Comment by moinuddin1980** [comment]
Today's analysis from attached TC9a_TC9b_mme log:
- After receiving the UE CONTEXT RELEASE REQUEST the UE state changed to REGISTERED_IDLE
000773 Thu Dec 23 01:17:47 2021 7F68B74EF700 INFO  NAS-AM tasks/amf/amf_fsm.cpp           :0173    [STATE_EVENT_CONTEXT_RELEASE] Event triggered, UE switches from [REGISTERED_CONNECTED] to [REGISTERED_IDLE] and PDU session :[SESSION_NULL]
- After the paging requests, the service request received is having service type as signaling.
![service_req_frame_1839.png](https://images.zenhubusercontent.com/6184f6ae82047233ede1227b/4327cc8a-e571-4f41-8588-f2a0e38ee3da)
- As the service type received is of type signaling, the service accepted but, still remained in REGISTERED_IDLE state.
Thus, when the PDU session release request procedure is triggered, AMF eventually received the PDU_SESSION_RELEASE_COMPLETE from UE.
The AMF tries to trigger releasing of active PDU towards SMF and cleans the PDU context in AMF.
But, as the UE is still in REGISTERED_IDLE state, and there is no handling of sending clear PDU session for UE in REGISTERED_IDLE state.
Thus, there will be no clear PDU session gRPC from AMF towards SMF and AMF's perspective PDU session info is removed.   

000932 Thu Dec 23 01:18:12 2021 7F68B74EF700 INFO  AMF-AP tasks/amf/amf_smf_send.cpp      :0538    T3592: after stop PDU_SESSION_RELEASE_REQUEST timer T3592 with id = 5
000933 Thu Dec 23 01:18:12 2021 7F68B74EF700 INFO  AMF-AP tasks/amf/amf_smf_send.cpp      :0246    notifying SMF about PDU session release n_active_pdus=1
000934 Thu Dec 23 01:18:12 2021 7F68B74EF700 DEBUG AMF-AP tasks/amf/amf_smf_send.cpp      :0256    clear saved context associated with the PDU session
000935 Thu Dec 23 01:18:12 2021 7F68B74EF700 DEBUG AMF-AP tasks/amf/amf_smf_send.cpp      :0193    clearing saved context associated with the pdu session

**Comment by moinuddin1980** [comment]
Analysis from TC9a_TC9b_syslog.log
- With TC9b execution UE context and PDU session is created at AMF.
- After this PDU session retry hapened 5 times because everytime sessiond(SMF) identified the PDU session as duplicate, as the PDU session establishd from TC9a was never cleared and has become stale session.
Line 1931: Dec 23 01:18:47 TVM3-SA-regression sessiond[489739]: I1223 01:18:47.182830 489739 SetMessageManagerHandler.cpp:289] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do
	Line 2066: Dec 23 01:19:03 TVM3-SA-regression sessiond[489739]: I1223 01:19:03.162014 489739 SetMessageManagerHandler.cpp:289] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do
	Line 2335: Dec 23 01:19:19 TVM3-SA-regression sessiond[489739]: I1223 01:19:19.161418 489739 SetMessageManagerHandler.cpp:289] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do
	Line 2602: Dec 23 01:19:35 TVM3-SA-regression sessiond[489739]: I1223 01:19:35.172199 489739 SetMessageManagerHandler.cpp:289] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do
	Line 2726: Dec 23 01:19:51 TVM3-SA-regression sessiond[489739]: I1223 01:19:51.168443 489739 SetMessageManagerHandler.cpp:289] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do

- The stale PDU session id in sessiond from TC9a execution has same identifier as that of PDU session info present in AMF as part of TC9b execution.
- After 5 retries AMF receives deregistration request from UE.
- Thus, AMF removes the UE context and sends the PDU session release gRPC towards SMF.
Line 2917: Dec 23 01:20:10 TVM3-SA-regression sessiond[489739]: I1223 01:20:10.272361 489739 SetMessageManagerHandler.cpp:142] Release request for session from IMSI: 222456000000101 pdu_id 5

**Comment by NeelimaKalpana** [comment]
Hi Moin ,
Please find the requested logs attached.[https://app.zenhub.com/files/170803235/b97c0583-8bda-4c3d-86ac-d1a34ec3dfdb/download](https://app.zenhub.com/files/170803235/b97c0583-8bda-4c3d-86ac-d1a34ec3dfdb/download)

**Comment by rupa455wavelabs** [comment]
Issue resolved, Please find the logs and pcaps for more information
[https://app.zenhub.com/files/170803235/d56577f9-d777-4d99-8d22-2f2b1d316df0/download](https://app.zenhub.com/files/170803235/d56577f9-d777-4d99-8d22-2f2b1d316df0/download)
