### ISSUE TITLE
[sessiond]: Refactor sessiond code that manages session state enum SessionFsmState

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#10999]
Refactor sessiond code that manages session state enum SessionFsmState
1) Currently 4G and 5G are using two different sessions state values for active and release case.
2) use common enum value for 4G and 5G  in case of session state active and release by removing ACTIVE, RELEASE enum values from SessionFsmState enum.
3) This change may impact AMF side code changes also need to check if there are any proto files changes needed for N11 interface.

**Comment by khansiddiquekc** [comment]
[06:01:2022] we have created below PR for this task. #11073
