### ISSUE TITLE
[TeraVM] Ipv6 PDU Reject - 4G FWA Federated Mode

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#10994]
_Issue:_ 
Tested Ipv6 and Ipv4v6 Dual Stack PDU Types and finding PDU Reject 

_Tested Magma Code:_
magma/focal-ci,now 1.7.0-1640135233-43b3fbec

_Test Scenario:_ 

- UE attach and PDU Connectivity Request (APN: inet6 & PDN type: Ipv6)
- AIR/AIA of S6a via Fed GW
- ULR/ULA ( APN Config: apn: inet6 & PDN Type: Ipv6, apn:  inet46 & Pdn type: ipv4v6)
- AGW sends Attach & PDN Connectivity reject (cause:  38)

_Enclosed:_
- pcaps with S1 & S6a flows
- mmelog
- syslog
[Ipv6 pdu reject- mme-syslogs-pcaps.zip](https://github.com/magma/magma/files/7772654/Ipv6.pdu.reject-.mme-syslogs-pcaps.zip)

_TeraVM Scenarios:_

Test suit: testplan_gxgy_plus.conf
Test Script:
- gx_gy_combined_109 (PDN Type: Ipv6 only)
- gx_gy_combined_110 (PDN Type: Ipv4v6)

_Magma AGW ipv6 related config:_

[AGW @NMS JSON]
"epc":{7 items
"dns_primary":"8.8.8.8"
"dns_secondary":"8.8.4.4"
"ip_block":"192.168.128.0/24"
"ipv6_block":"xxxx:yyyy:zzzz::96::/48" (Actual IP differs in agw)
"ipv6_dns_addr":"2001:4860:4860:0:0:0:0:8888"
"ipv6_prefix_allocation_mode":"RANDOM"
"nat_enabled":true

[SGi Network Int] Actual IP differs in agw
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb state UP group default qlen 1000
    link/ether 00:0c:29:dc:fb:9e brd ff:ff:ff:ff:ff:ff
    inet 192.168.62.104/24 brd 192.168.62.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 xxxx:yyyy:zzzz:96:20c:29ff:fedc:fb9e/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591739sec preferred_lft 604539sec
    inet6 fe80::20c:29ff:fedc:fb9e/64 scope link 
       valid_lft forever preferred_lft forever

_**mmelog**_ (key error) - complete file enclosed in above zip file

001416 Thu Dec 23 20:33:58 2021 7FF83D5FC700 ERROR UTIL   lib/mobility_client/MobilityClie:0199     Error in allocating ipv6 address for IMSI <999991234632730> apn <inet6>
001417 Thu Dec 23 20:33:58 2021 7FF83D5FC700 ERROR UTIL   lib/mobility_client/MobilityClie:0258    Failed to allocate IPv6 PAA for PDN type IPv6 for imsi <999991234632730> and apn <inet6>

----

_Pcap snap:_

<img width="1746" alt="Screen Shot 2021-12-23 at 8 43 08 PM" src="https://user-images.githubusercontent.com/70725754/147317269-411e415d-7d42-44a2-8899-14bc01e73d30.png">

**Comment by arun-magma** [comment]
@uri200 Here is the debug & grpc logs from directoryd and subdb
[Ipv6_debug logs.zip](https://github.com/magma/magma/files/7786926/Ipv6_debug.logs.zip)

[Error]
Dec 28 17:09:27 ipv6AGW mme[22965]: Directoryd RPC failed with code 5, msg: Record for ID IMSI999991234632730 was not found.

**Comment by uri200** [comment]
Hey @arun-magma  @vaishaliCI , those two test do not exist on setup 1

Can you configure those so we can run it independently from CI?

**Comment by arun-magma** [comment]
these ipv6 related ntl files are added in setup-1, existing AGW iface need to enable dualstack (to add Ipv6 also) or need to plan a separate IPv6 AGW in setup-1 to try out all Ipv6 related configs.

/home/ng40/magma/automation
-rw-rw-r-- 1 ng40 ng40   3937 Jan 27 10:35 gxgy109.ntl
-rw-rw-r-- 1 ng40 ng40   3937 Jan 27 10:35 gxgy110.ntl
