### ISSUE TITLE
Regarding TC9b Testcase expectations.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10996]
Hi Vinay,

This is regarding TC9b scenario expectation.

As per the testcase verdict in the script we are expecting a nas5g_received_Service_Acc_ and nas5g_sent_Service_Req__mt
Please find the bellow screenshot for the same.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6c1b3284-cee7-48b0-90f8-79ed9d7577eb)
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/248901af-b12a-4677-8a83-d26db85ae72a)

But in the pcaps we are not seeing any nas5g_sent_Service_Req__mt message. Please find the pcap sreenshot for quick reference.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/bb7f9229-d7d8-4b85-843f-023f05efa8d1)

Because of this conflict TC is failing. Please investigate the same and let me know what should be the expected behavior in this scenario.

Note: I can see the time gap between last paging retry message and service request is almost 17Sec
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/3d8a9b74-8950-4d27-a0c9-f76909fc72ae)

Please find the TC logs and pcaps from the attachment.

[https://app.zenhub.com/files/170803235/8de60d51-d6d3-4862-b84b-536342c3397a/download](https://app.zenhub.com/files/170803235/8de60d51-d6d3-4862-b84b-536342c3397a/download)

**Comment by VinayKumar1591** [comment]
@NeelimaKalpana as per testcase emulator shall send service request for the last paging request with service type mobile_terminated_services , however through traces I could see service request with service type signaling. Please change  script accordingly

**Comment by NeelimaKalpana** [comment]
Hi Arun,

As discussed please do the needful by aligning the TS to the required scenario expectations.
In the TC verdict we are expecting Service-Type as ServiceRequestMT by from scripting we are seeing UE is sending the Service-Type as Signaling so AMF is responding accordingly.

**Comment by arun-magma** [comment]
@NeelimaKalpana 
In the enclosed traces we could see only two paging request is triggered by AGW towards a gNB, 3rd and 4th (last) attempt of paging is missing to send the Service Request = MT, Please don't consider Service Request = MO_SIG as its in diff time leg and it is to reinstantiate the session to connected mode. Please let us know how many paging attempts are configured currently in AGW ?

<img width="1761" alt="Screen Shot 2022-01-04 at 6 27 14 PM" src="https://user-images.githubusercontent.com/70725754/148151310-13ce30e7-78fc-44d0-9563-42037dd0fe04.png">

**Comment by NeelimaKalpana** [comment]
I am closing the ticket as we are tracking this as part of a bug.

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/11064
