### ISSUE TITLE
TVM Scale Test: Periodic Registration update scale test

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11024]
magma build version: 1.7.0-1640745493-d0ca0d93

Executed scale test scenario's for periodic registration updating:

1. SA_TC8_UE_initiated_Periodic_Registration - 100UE, 12 GNB, 5 UE/s,1 loop, Periodic Registration in Active Mode, T3512 set by script (default=15s) - Test case is passing.

![n2_100ue_12gnb_periodic.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/2014329f-7c90-4498-99ff-f6e10994c7f3)

![periodic_registration_100ue_12gnb.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/05ce69d7-50d3-4ce7-a5a3-707028976b57)

2. SA_TC8_UE_initiated_Periodic_Registration - 200UE, 12 GNB, 5 UE/s, 1 loop, Periodic Registration in Active Mode, T3512 set by script (default=15s) - Test case verdict is failing.

3. 1. SA_TC8_UE_initiated_Periodic_Registration - 200UE, 12 GNB, 5 UE/s, 10 loops, Periodic Registration in Active Mode, T3512 set by script (default=15s) - Test case verdict is failing due to 200 de-registration requests and de-registration accepts.
verification fail:  ((nas5g_sent_Dereg__Req_=200)           	>= 200*10)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=200)       	>= 200*10)  => False 
![n2_200ue_10l_periodic.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/55763765-d093-4681-a90a-19190c110066)
![200ue_10l_periodicreg.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/8484b62d-add7-4769-90e8-9ea49da87ad6)

4. SA_TC8_UE_initiated_Periodic_Registration - 100UE, 12 GNB, 5 UE/s, 50 loops, Periodic Registration in Active Mode, T3512 set by script (default=15s) - Test case verdict is failing due to 200 de-registration requests and de-registration accepts.
verification fail:  ((nas5g_sent_Dereg__Req_=200)           	>= 200*10)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=200)       	>= 200*10)  => False 

![200ue_50l_periodic.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/5a863f15-eabd-4caf-85f9-2b2da4706f51)
![n2_periodic_200ue_50l.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/12b6a343-fcd4-4700-9117-1e8f2012cd3a)

Please refer the logs and pcaps for more info:
https://drive.google.com/drive/folders/1ScqgUbEuIucfSe3I54S1jiMeW3-bJXeP

**Comment by Kaleem-Wavelabs** [comment]
@rupa455wavelabs 

From the description, for 100/200 UE /12 gNb / 5UE attach/ 1 loop, TC is passing but with more loops it is failing.
With more loops i can see only 200 reg requests are triggered from script, can we sync up on this to know is it valid TC scenario and result.

@parthiban337

**Comment by rupa455wavelabs** [comment]
sure @Kaleem-Wavelabs
