### ISSUE TITLE
Spirent_Scale_Test: UE Registration with GUTI - UE1 -Valid & UE2-Invalid

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#11020]
Magma build version -1.7.0-1640745493-d0ca0d93

Tested for GUTI based 200 UE with 100 valid UE and 100 invalid UE,1 GnB, 4 PDU sessions, 5 UE/sec attach rate in 60 loops, traffic test is passing. PDU session establishment is happening. 100 UE registration accept and PDU session establishment is seen. Illegal UE registration is seen in case of 100 invalid UE.  Callflow is in correct format. No errors found.
![GUTI_REC.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/ca4f48bd-6d89-4571-9928-3be1e9b89048)

![GUTI_Measurement_REC.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/b70826c2-efed-4743-8317-435e2fbc75f4)

Attached Pcap, mme log and syslog in the google drive. Please find the link below for 29-12-2021 

https://drive.google.com/drive/folders/1s6ZB59_7q5h3R3niUCZRmhDZ4y1I4_jy

**Comment by Kaleem-Wavelabs** [comment]
@apekshapk 

If the issue is not observed in the latest build, please process to close the ticket
