### ISSUE TITLE
TVM Scale Test: GUTI based Registration with Valid and Invalid UE's

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11023]
Executed Scale Test Scenario's:

[20-12-2021]
1. SA_TC50b_Scale_Test_Guci Scaling, Registration, PDU_Session_Establishment/Release, UDP Traffic UL DL, Guci(100 Valid & 100 Invalid UE, 1Gnb) - Test is failing due to UL/DL traffic issue.
![50b_guti_100_i_v_n3.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/2ec5aa87-df11-421f-9733-d4135373a3ef)
![50b_guti_100_i_v_ue.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/fbf51abc-26a8-487f-888d-1b98f2809367)

2. scale Test Guci - 200 Valid UE, 200 Invalid UE(Registration, Pdu Session Establishment/Release, DeRegistration, UL/DL traffic(200UE,12Gnb,5UE/s) - Test case is failing due to UL/DL traffic issue.

Please refer the logs and pcaps for more info:
https://drive.google.com/drive/folders/1Kziq5t9sKTW_QEh7cMvvHNOHOCc2Okol

**Comment by Kaleem-Wavelabs** [comment]
Close this as the root cause is same as #11021 and #11022

**Comment by rupa455wavelabs** [comment]
Executed the TC with latest magma code and observed an issue with Registration Retry and Identity request retry,Please check the attached logs and screenshots for reference.

![n3_guti_reg.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/5195a840-a010-4813-b489-074a871c9c38)
![50b_guti_200ue.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/ab68f9e3-3703-480f-9c74-970620d6159b)
![guti_50b.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/3dac4bc4-c106-4a24-a5b5-90e737969b32)

[https://app.zenhub.com/files/170803235/81941d24-7aac-4638-b3ca-37710002acca/download](https://app.zenhub.com/files/170803235/81941d24-7aac-4638-b3ca-37710002acca/download)

**Comment by rupa455wavelabs** [comment]
Need to re-verify it in spirent setup and update the results.
