### ISSUE TITLE
TVM Scale Test: Hyper SUCI Registration 

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11021]
magma build version: 1.7.0-1640745493-d0ca0d93 amd64
Executed scale test scenario's for SUCI based Registration

1. SA_TC1_2_3_4_Hyper_Suci(Registration,PDU session Establishment/Release, DeRegistration,UL/DL traffic) - (100ue,12GNB,5 UE/s) in 30 loops - Test case verdict failed due to UL/DL traffic issue

![n1_n2_suci_100ue_30l.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/19f1dc31-7fd0-454f-8868-02693dac052b)

2. SA_TC1_2_3_4_Hyper_Suci(Registration,PDU session Establishment/Release, DeRegistration,UL/DL traffic) - (100ue,12GNB,5 UE/s) in 50 loops - Test verdict failed due to UL/DL traffic issue
![100ue_suci_50loops.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/771376f4-8a4f-4ecf-85d1-11b26bac1c79)

3. SA_TC1_2_3_4_Hyper_Suci(Registration,PDU session Establishment/Release, DeRegistration,UL/DL traffic) - (100ue,4GNB,5 UE/s) in 60 loops - Test case was exited due to mme service restart

![100ue_60l_suci.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/e049b3e3-8aa5-48e2-b6ac-a2a0ed82cf38)

4.SA_TC1_2_3_4_Hyper_Suci(Registration,PDU session Establishment/Release, DeRegistration,UL/DL traffic) - (100ue,12GNB,5 UE/s) in 100 loops - all magma services are stable and Test verdict failed due to Registration request retry and UL/DL traffic issue.

Please find the required logs and pcaps from the below link: 
https://drive.google.com/drive/folders/1j7epZ3FwZcZBp17bwvWVDmLdY7jiYBk2

**Comment by rupa455wavelabs** [comment]
SA_TC1_2_3_4_Hyper_Suci(Registration,PDU session Establishment/Release, DeRegistration,UL/DL traffic) - (200ue,12GNB,5 UE/s) in 50 loops - Test verdict failed due to UL/DL traffic issue
![200ue_12Gnb_50loops.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/70b4de28-d612-4c5a-b693-afd5248f5856)

Please find the pcaps and logs from below link for more info
https://drive.google.com/drive/folders/1pdoAMr2Q7r5Vd4oTWHPBrp0yGwi0WJFR

**Comment by rupa455wavelabs** [comment]
SA_TC1_2_3_4_Hyper_Suci(Registration,PDU session Establishment/Release, DeRegistration,UL/DL traffic) - (200ue,12GNB,5 UE/s) in 60 loops - Test verdict failed due to UL/DL traffic issue and Test case stopped automatically. 
![n1_n2_suci_60l.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/3aa625b4-2dbc-45b6-a720-638f056eab38)
![suci_60l.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/09aa19ae-69b8-4bb0-b13c-fd4353672cc5)

**Comment by Kaleem-Wavelabs** [comment]
Hi @rupa455wavelabs,

Out of 4 TCs mentioned, the root cause for 3 issues is due to traffic loss in UL/DL which got fixed by #10972 and it got manually verified the fix as well.

For 60 loop test, what we have observed is that mme got restarted due to sctpd restart not due to mme failure. When we checked why sctpd is restarted from the log it was observed that it is done due to manual intervention.

You can verify these in the latest build and assign the issue back to us if you still observe the same.

**Comment by rupa455wavelabs** [comment]
Hi @Kaleem-Wavelabs, 
After traffic issue fix I have executed the same scenario's and we have observed that if we are executing the TC with 5 loops and more than 5 loops, services are keep on restarting for multiple times. we are trying to reproduce the issue in spirent as well, In spirent we are observing UL/DL traffic issue for TCP/UDP, once that issue is resolved we will update you.

**Comment by panyogesh** [comment]
@rupa455wavelabs, @Kaleem-Wavelabs : Can you please conclude

**Comment by rupa455wavelabs** [comment]
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment]
re-tested with latest magma build and observing a drop in ul/dl traffic, all the Registrations, PDU session Establishment, DeRegistration Procedures are triggered without any issues. Please check the below logs.

Verdict Log:
verification fail:  ((as_received_raw_bytes=37017000) 			>= (ue_sent_total_bytes=40002000)-((ue_sent_total_bytes=40002000)*0.01))  => False
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/377fa5fc-b2ad-4870-8cac-f91839616bc2)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/282ae6e9-5084-46b4-9e7a-a639bed740eb)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/8fb40f36-d0df-46e8-b8d3-ec1ea423401b)
[https://app.zenhub.com/files/170803235/f2747a75-592a-4617-af1b-776bf06995a7/download](https://app.zenhub.com/files/170803235/f2747a75-592a-4617-af1b-776bf06995a7/download)

**Comment by panyogesh** [comment]
Closing as the testing is working fine
