### ISSUE TITLE
TVM Scale Test: IdleMode to Active Transition with Multipe Pdu Sessions is failing

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11031]
magma build version: 1.7.0-1640745493-d0ca0d93

Executed scale test scenario's for IdleMode to Active Transition TC:

1. SA_TC2c_Verify_Idle_and_Active_Mode_transition_with_Multi_PDU_session -
100 UE, 12 GNB, SUCI Registration, 2 PDU Sessions Idle/Active MO & traffic - All the 100 UE's are transitioning between IdleMode and Active Mode - Testcase is failing due to PDU session Establishment is failing for 200 PDU sessions and UL/DL traffic issue.

![idle_100ue_2pdu.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/1c85b4e3-07ed-491d-93c2-6754408528e2)
![idle_n1_n2_100ue_2pdu.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/8eb5f818-ea4c-4bc1-a92a-a5ce5d106c71)
![n2_n3_idle_2pdu_100ue.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/4063093e-d97b-495b-b373-183ff6fae759)

2. SA_TC2c_Verify_Idle_and_Active_Mode_transition_with_Multi_PDU_session -
200 UE, 12 GNB, SUCI Registration, 2 PDU Sessions Idle/Active MO & traffic - All the 200 UE's are transitioning between IdleMode and Active Mode - Testcase is failing due to PDU session Establishment is failing for 200 PDU sessions and UL/DL packet drop issue.

Please check the logs and pcaps for more information:
https://drive.google.com/drive/folders/1ScqgUbEuIucfSe3I54S1jiMeW3-bJXeP

**Comment by Kaleem-Wavelabs** [comment]
@rupa455wavelabs Please regress this with the latest master and close

**Comment by rupa455wavelabs** [comment]
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment]
SA_TC2c_Verify_Idle_and_Active_Mode_transition_with_Multi_PDU_session -
200 UE, 12 GNB, SUCI Registration, 2 PDU Sessions Idle/Active MO & traffic - All the 200 UE's are transitioning between IdleMode and Active Mode - Re-executed Test scenario with latest magma, and I am observing an issue with PDU Session Retry with 4 PDU Sessions, UL/DL Traffic issue Please check the below logs and pcaps.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/e2d77fe7-66bd-450c-b153-f481a22c5df7)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/93a3c0b5-384b-4877-bc4c-df55c3a31e6f)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/d8589e0b-e0c1-4aa5-aa7f-9bcd13336acb)

[https://app.zenhub.com/files/170803235/0faa4982-b9f6-4e89-8ff6-1bc23a8b21fa/download](https://app.zenhub.com/files/170803235/0faa4982-b9f6-4e89-8ff6-1bc23a8b21fa/download)

[https://app.zenhub.com/files/170803235/210fcfb6-2666-4580-a833-ee359486cbf9/download](https://app.zenhub.com/files/170803235/210fcfb6-2666-4580-a833-ee359486cbf9/download)

**Comment by rupa455wavelabs** [comment]
verification fail:  ((nas5g_received_Sess__Establ__Acc_=338)	>= 200*1*4)  => False
verification fail:  ((nas5g_sent_Sess__Establ__Req_=1112)    	== (nas5g_received_Sess__Establ__Acc_=338))  => False
verification fail:  ((nas5g_sent_Service_Req_=78)			>= 200*1)  => False
verification fail:  ((as_received_raw_bytes=54538000) 			>= (ue_sent_total_bytes=62424000)-((ue_sent_total_bytes=62424000)*0.01))  => False
verification fail:  ((as_received_raw_bytes_40=14130000)			>= (ue_sent_bytes_40=15606000)-((ue_sent_bytes_40=15606000)*0.01))  => False
verification fail:  ((as_received_raw_bytes_41=13843000)			>= (ue_sent_bytes_41=15606000)-((ue_sent_bytes_41=15606000)*0.01))  => False
verification fail:  ((as_received_raw_bytes_42=13508000)			>= (ue_sent_bytes_42=15606000)-((ue_sent_bytes_42=15606000)*0.01))  => False
verification fail:  ((as_received_raw_bytes_43=13057000)			>= (ue_sent_bytes_43=15606000)-((ue_sent_bytes_43=15606000)*0.01))  => False
verification fail:  ((ue_received_bytes_40=7763000)			>= (as_sent_bytes_40=14082336)-((as_sent_bytes_40=14082336)*0.01))  => False
verification fail:  ((ue_received_bytes_41=7489000)			>= (as_sent_bytes_41=13785876)-((as_sent_bytes_41=13785876)*0.01))  => False
verification fail:  ((ue_received_bytes_42=7135000)			>= (as_sent_bytes_42=13432068)-((as_sent_bytes_42=13432068)*0.01))  => False
verification fail:  ((ue_received_bytes_43=6672000)			>= (as_sent_bytes_43=12957732)-((as_sent_bytes_43=12957732)*0.01))  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=312)       	>= 200*1*4)  => False
verification fail:  ((nas5g_received_Sess__Rel__Cmd_=312)   	>= 200*1*4)  => False
verification fail:  ((nas5g_sent_Dereg__Req_=78)           	>= 200*1)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=78)       	>= 200*1)  => False

**Comment by rupa455wavelabs** [comment]
[https://app.zenhub.com/files/170803235/b1885b1b-e4bc-4c08-9b99-5a522f63e844/download](https://app.zenhub.com/files/170803235/b1885b1b-e4bc-4c08-9b99-5a522f63e844/download)

**Comment by panyogesh** [comment]
Kindly test on latest abot tool and confirm. As this old closing it.
