### ISSUE TITLE
[Proposal] Mini Magma Orchestrator

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#11045]
# Mini Magma Orchestrator
## Problem

A lot of community members struggle when it comes to deploying Magma Orchestrator on Virtual Machines or Bare Metal and AWS is too costly for them to start with.

## Solution

We can build an automated process that will deploy Magma Orchestrator with a single bash script, the way we do today with Magma Access Gateway.

We will have to limit our resources to the following.

4 CPU/vCPU
8GB RAM
100GB Storage
1 Public/Private IP

If we deploy this solution on AWS it should not cost more than $100/month.
https://calculator.aws/#/createCalculator/EC2

Once after testing Mini Magma Orchestrator they can deploy terraform managed Orc8r on AWS.

## Non-goals

As everything will be running inside a single node the solution won't be fault-tolerant.

**Comment by ShubhamTatvamasi** [comment]
Here is the first draft.
https://github.com/ShubhamTatvamasi/magma-galaxy

**Comment by ShubhamTatvamasi** [comment]
The code has been updated to use 1 Public/Private IP via HAProxy.

**Comment by qoderwork** [comment]
greate job, I also need

**Comment by ShubhamTatvamasi** [comment]
As per the discussion in the TSC meeting today, there should be a CI job that should check the integration of the Mini Magma Orchestrator with Access Gateway. I have created an issue for that. https://github.com/magma/magma/issues/12214
