### ISSUE TITLE
Docker as Standard Build Environments for Bazel

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#11040]
# Docker (OCI images) as Standard Build Environments for Bazel

## Problem

Currently there are several build environments around, e.g. docker, VMs, local setups.
Supporting multiple build environments comes with a significant maintenance overhead and tech depth.
Especially when exploring Bazel as build system and migrating to Bazel, supporting multiple very different build systems comes at high costs.

## Solution

It is proposed to use Open Container Initiative (OCI) conform images as (the only) build environment for Bazel builds.
Amongst others, Docker is a technology providing OCI confrom images. For the ease of reading we always name Docker below, while other OCI conform images are not excluded by that.
Using Docker images has several advantages:

- Docker is available in CI as well as on all major operating systems (Linux, Windows, Mac) locally.
  - The build environment can be the same for CI and local build.
  - Changes to the build system only need to be made once and used everywhere.
  - Developers with certain operating systems are no longer excluded from the project. (Also see https://github.com/magma/magma/issues/10116.)
- Tech depth reduction:
  - Docker is a well known and popular technology. It is expected to be easy to use and maintain.
  - Contributors local build process preparation can be simplified to a docker agent installation.
  - Only minimal setup required for CI (Github actions). It would be easy to switch to other build systems (as long as they support docker).
- High flexibility:
  - Deciding for Docker as the build environment still leaves room for several builder (image) strategies.

## Non-goals

- Changes to non Bazel builds
- Changes to runtime environments
- Changes to integration test environments
- Particular docker strategy for Bazel build environments (in scope of follow up https://github.com/magma/magma/issues/10860)
- Changes to build artifact packaging or build artifact format

## Further considerations

- Docker is currently the de-facto standard for the Bazel builds, as it is build in the devcontainer in the CI.
- Github action runners (native VMs) were considered as alternative. Main drawbacks are:
  - No re-usage of setup for local builds, i.e. local build setup needs to be separately designed and maintained.
  - A machine setup is still required. However, there are several drawbacks of the Github runner setup.
    - Using Github provided runners, setup needs to be made on every execution. In contrast for docker, the image has only to be build once and can be reused from GitHub Container Registry (GHCR).
    - Using self-hosted runners comes at extensive setup and maintenance overhead. Possibly bigger infrastructure changes are necessary.
  - Using a elaborate Github runners setup implies a higher vendor lock-in.

**Comment by Neudrino** [comment]
## Development process integration

### IDEs

The integration into IDE is expected to be at least similar as for the VMs.

#### VS Code

With devcontainer there is a native integration of containers into the IDE for VS Code. DevContainer can be build on top of any functional builder image.

#### IntelliJ (Community Edition)

For IntelliJ (Community Edition) you need to install the docker plugin and configure the docker deamon inside IntelliJ.

![2022-01-03 Docker deamon connection](https://user-images.githubusercontent.com/13189449/147953148-b5efdccd-db6f-483e-b52b-72bb25d9f2ec.png)

After that you are able to manage docker images as well as containers.
Attaching a local folder to the container is easily possible via GUI. A terminal inside the container is available.

![2022-01-03 IntelliJ with docker container attached-b](https://user-images.githubusercontent.com/13189449/147952942-a871235c-1f63-4125-86ed-31bbd5371350.png)

Another interesting approach might be the [IntelliJ Projector](https://blog.jetbrains.com/blog/2021/03/11/projector-is-out/).
Another interesting approach might be the [IntelliJ Gateway](https://youtrack.jetbrains.com/issue/IDEA-226455#focus=Comments-27-5290105.0-0).

**Comment by Neudrino** [comment]
Reserved. :wink: :wink:

**Comment by ssanadhya** [comment]
@Neudrino , can you present this in the TSC meeting on [March 28](https://wiki.magmacore.org/pages/resumedraft.action?draftId=2366682&draftShareId=6e21b3b0-dcac-4944-80cd-f077eb7e9a09&)? If yes, I can add it to the agenda.

**Comment by nstng** [comment]
@ssanadhya We are currently discussing the actions implied by this proposal internally. Is it OK if we come back to you when we reached a conclusion? So it will not be ready for the next TSC meeting.

**Comment by ssanadhya** [comment]
> @ssanadhya We are currently discussing the actions implied by this proposal internally. Is it OK if we come back to you when we reached a conclusion? So it will not be ready for the next TSC meeting.

Sure, that makes sense. I will mark it "on hold" for now

**Comment by nstng** [comment]
Closed as out-of-scope for now.
