### ISSUE TITLE
Requesting  to provide the regression suit scheduling option in the TVM-GUI.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11065]
Hi Arun ,

Please provide an option to trigger the suit in a single click from TVM-GUI.

So, this will help us to trigger the Regression-TCs/ a set of required TC's from GUI.

**Comment by arun-magma** [comment]
@NeelimaKalpana :
Under "Scenarios -> Scheduler (Top Right) " added to run list of test cases in batch, we can list regression cases and run to check the sequential impacts. Also it helps in many ways to group and some tests for a specific feature, Please start use this UI feature.
![Screen Shot 2022-01-06 at 9.26.24 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/c9f6b361-7e41-40dc-8561-37ff493eb7d9)

**Comment by NeelimaKalpana** [comment]
Hi Arun ,
Thank you for giving this scheduling option.

But here in setting the parameters I am trying to set number of loops and number of users but it is not taking the values set.
I just want to notify this , as of now I can proceed with the available options.
Please look into this.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/7796f565-b303-4b71-a4ca-72f7b1d1c25a)

**Comment by arun-magma** [comment]
lets jump onto a common debug when ever its possible, in batch run one script need to be included once in the list and run config gets affected if TC is included multiple times, Kindly check this point once.
And recently we tested with TCs with certain run config parameter variation like diff Num_users and loops , it went through well, You may retry once and share the latest status.
Please list out if anymore issues in batch run window, as its a newly added feature we may need to fine tune a bit.

**Comment by NeelimaKalpana** [comment]
Hi Arun ,

I was selecting a TC  multiple times .
So , we cannot set the config-parameters if we select a script multiple times , if I understand in a right way.
Yes , Arun we will post our observation if noticed any issues.

**Comment by rupa455wavelabs** [comment]
Requirement satisfied, closing the issue.
