### ISSUE TITLE
[AUSF] Registration is getting rejected as decryption is not happening properly for different MSIN values passed

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11076]
Your Environment

- Version: 1.7.0-1641405746-597f0eb1
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: bare-metal (AGW)/Private_Cloud_VM_Based

### Describe the Issue
Registration is getting rejected as decryption is not happening properly for different MSIN values passed. Because of bit reversal problem the decryption of MSIN is not happening properly.
Eg. IMSI_Requested : 222451234567891 
      IMSI_Decrypted : 222451325476981 
**To Reproduce**
1. Generate proper Public-Keys by passing  home_net_public_key_id and protection_scheme as 0.
2. Decrypt the private-Key for every IMSI for which registration has to be triggered.
3. Make necessary changes in TVM-GUI 
    a. Select SUPI_Profile : profile a
    b. Give the Profile a Public_Key.
    c. Give the decrypted Private_Key
4. Try to trigger the TC (TC1x_SUPI_ProfileA).
5. TC is failing as Registration is getting rejected as IMSI is not getting decrypted properly.

**Expected behavior**
Proper decryption of IMSI should happen.

Note : Tried for IMSI222450000000001 , IMSI222456000000001 also here the Registration is getting successful.

[https://app.zenhub.com/files/170803235/a31c862c-4041-43d1-807c-a293c962da4e/download](https://app.zenhub.com/files/170803235/a31c862c-4041-43d1-807c-a293c962da4e/download)

**Comment by Kaleem-Wavelabs** [comment]
@NeelimaKalpana 

From the logs observed that the private key received at subscriberdb:
"uePubkey": "2JyltpOPUTAWocmRKl1oQJYJJd6UGrzsLSQ9NnT7PDk=" for imsi: 222456 1234567891 is not matching with the private key generated using the script test_supi_decrypt_imsi_cli.py

>>> some_bytes = b"2JyltpOPUTAWocmRKl1oQJYJJd6UGrzsLSQ9NnT7PDk="
>>> hexadecimal_string = some_bytes.hex()
>>> print(hexadecimal_string)
**324a796c74704f50555441576f636d524b6c316f514a594a4a64365547727a734c5351394e6e543750446b3d**
This key in hex is not matching with the private keys generated in DifferentIMSI_Public_Keys.txt.

Let us sync up on Monday to know how these private keys are feeded to TeraVM scripts, how they are manipulated in the process. The same key feeded to ueransim is working fine means decryption is successful and thereby registration also accepted.

CC @panyogesh

**Comment by Kaleem-Wavelabs** [comment]
@rupa455wavelabs is the TC script has been modified to pass on the expected key values.

**Comment by Kaleem-Wavelabs** [comment]
This is tracked using #11174, can close this.

**Comment by NeelimaKalpana** [comment]
Reopening this ticket as SUPI registration is tested from Spirent setup and observed same failure of registration reject due to MSIN bit reversal issue.

Version : 1.8.0-1650349643-2c297fdd

ScreenShots:

Spirent_Config:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/ada25529-c807-4ac1-88f4-8373768b6064)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/738bdc8e-f061-4b16-af8a-eead6233abc9)


![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9a3b3b3b-c78e-411e-b452-89a2d5ba1d00)

Please find the attached Logs and pcaps
[https://app.zenhub.com/files/170803235/3d9d0066-9346-448c-abb7-f3e42e5b2730/download](https://app.zenhub.com/files/170803235/3d9d0066-9346-448c-abb7-f3e42e5b2730/download)

**Comment by Kaleem-Wavelabs** [comment]
@NeelimaKalpana 

[](https://user-images.githubusercontent.com/83354949/154668940-c2029b24-dbe2-452a-830c-829d064613bb.png)[](https://user-images.githubusercontent.com/83354949/154669161-d66406ed-399b-46cc-86b7-1465b8f04eb1.png)In SUCI based Registration Request, we are to receive ecc_public_key (Recipient's public key, not part of supi profiles stored in subscriberdb) and public key identifier(pki), which identifies public/private key pair stored in subscriberdb as part of suci profiles.
Subscriberdb uses pki, recipient's key (ue specific) and ciphertext to decrypt the concealed MAC(10 digits).

Please refer https://github.com/magma/magma/issues/11174#issuecomment-1044344169 for more details.

**Comment by NeelimaKalpana** [comment]
Hi Kaleem ,

I raised a quire to the Spirent team , about how the ECC key is getting generated.
Meanwhile I was trying to check for the Public-Key in the subscriber-db logs but seeing some tracebacks.
Please check the below tracesbacks observed.

Apr 21 10:11:16 localhost smsd[1281254]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 21 10:11:16 localhost subscriberdb[1281156]: ERROR:grpc._server:Exception calling application: 'NoneType' object is not subscriptable
Apr 21 10:11:16 localhost subscriberdb[1281156]: Traceback (most recent call last):
Apr 21 10:11:16 localhost subscriberdb[1281156]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
Apr 21 10:11:16 localhost subscriberdb[1281156]:     response_or_iterator = behavior(argument, context)
Apr 21 10:11:16 localhost subscriberdb[1281156]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/m5g_auth_servicer.py", line 184, in M5GDecryptImsiSUCIRegistration
Apr 21 10:11:16 localhost subscriberdb[1281156]:     aia.ue_msin_recv = msin_recv[:10]
Apr 21 10:11:16 localhost subscriberdb[1281156]: TypeError: 'NoneType' object is not subscriptable
Apr 21 10:11:16 localhost sctpd[1281483]: I0421 10:11:16.993060 1282092 sctp_connection.cpp:195] Unhandled notification type 32777
Apr 21 10:11:21 localhost smsd[1281254]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 21 10:11:31 localhost smsd[1281254]: message repeated 2 times: [ INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.]
Apr 21 10:11:34 localhost magmad[1280998]: INFO:root:Setting logging level to INFO
Apr 21 10:11:36 localhost subscriberdb[1281156]: INFO:root:get digest stored in gateway: zA+nUsJ48MxIASn9f4rKew==1B2M2Y8AsgTpgAmY7PhCfg==
Apr 21 10:11:36 localhost control_proxy[1281348]: 2022-04-21T10:11:36.424Z [127.0.0.1 -> subscriberdb-controller.magma.wavelabs.int,8443] "POST /magma.lte.SubscriberDBCloud/CheckInSync HTTP/2" 200 7bytes 0.028s
Apr 21 10:11:36 localhost smsd[1281254]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 21 10:11:41 localhost smsd[1281254]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 21 10:11:42 localhost subscriberdb[1281156]: ERROR:grpc._server:Exception calling application: An X25519 public key is 32 bytes long
Apr 21 10:11:42 localhost subscriberdb[1281156]: Traceback (most recent call last):
Apr 21 10:11:42 localhost subscriberdb[1281156]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
Apr 21 10:11:42 localhost subscriberdb[1281156]:     response_or_iterator = behavior(argument, context)
Apr 21 10:11:42 localhost subscriberdb[1281156]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/m5g_auth_servicer.py", line 179, in M5GDecryptImsiSUCIRegistration
Apr 21 10:11:42 localhost subscriberdb[1281156]:     msin_recv = home_network_info.unprotect(
Apr 21 10:11:42 localhost subscriberdb[1281156]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/crypto/ECIES.py", line 162, in unprotect
Apr 21 10:11:42 localhost subscriberdb[1281156]:     shared_key = KDF(ue_pubkey, self.EC.generate_sharedkey(ue_pubkey))
Apr 21 10:11:42 localhost subscriberdb[1281156]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/crypto/EC.py", line 107, in generate_sharedkey
Apr 21 10:11:42 localhost subscriberdb[1281156]:     extpubkey = X25519PublicKey.from_public_bytes(ext_pubkey)
Apr 21 10:11:42 localhost subscriberdb[1281156]:   File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 25, in from_public_bytes
Apr 21 10:11:42 localhost subscriberdb[1281156]:     return backend.x25519_load_public_bytes(data)
Apr 21 10:11:42 localhost subscriberdb[1281156]:   File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 2168, in x25519_load_public_bytes
Apr 21 10:11:42 localhost subscriberdb[1281156]:     raise ValueError("An X25519 public key is 32 bytes long")
Apr 21 10:11:42 localhost subscriberdb[1281156]: ValueError: An X25519 public key is 32 bytes long
Apr 21 10:11:42 localhost sctpd[1281483]: I0421 10:11:42.989902 1282092 sctp_connection.cpp:195] Unhandled notification type 32777
Apr 21 10:11:46 localhost smsd[1281254]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 21 10:11:51 localhost smsd[1281254]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.025s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.018s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.012s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.020s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.014s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.047s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.013s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> metricsd-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.042s
Apr 21 10:11:53 localhost control_proxy[1281348]: 2022-04-21T10:11:53.162Z [127.0.0.1 -> state-controller.magma.wavelabs.int,8443] "POST /magma.orc8r.StateService/ReportStates HTTP/2" 200 5bytes 0.027s
Apr 21 10:11:53 localhost magmad[1280998]: INFO:root:Checkin Successful! Successfully sent states to the cloud!
Apr 21 10:11:54 localhost magmad[1280998]: INFO:root:Checking for upgrade...

Please find the latest logs captured.

[https://app.zenhub.com/files/170803235/7cf3eedf-ee0a-433e-874c-e924f5bf42e8/download](https://app.zenhub.com/files/170803235/7cf3eedf-ee0a-433e-874c-e924f5bf42e8/download)

**Comment by moinuddin1980** [comment]
Hi Neelima,

The traceback above are printed in order to just understand the call flow where the exception occurred from.
As the exception in question over here is handled properly in AMF, hence is a non issue from overall exception handling perspective.

Below are the reference logs for the same.
**012947 Thu Apr 21 06:39:09 2022 7F49439D7700 ERROR AMF-AP lib/n11/M5GSUCIRegistrationServi:0062    get_decrypt_imsi_info fails with code 2, Message : Exception calling application: An X25519 public key is 32 bytes long
012948 Thu Apr 21 06:39:09 2022 7F49439D7700 ERROR AMF-AP lib/n11/M5GSUCIRegistrationServi:0065    Deconcealing IMSI Failed, sending Registration Reject**
012949 Thu Apr 21 06:39:09 2022 7F49439D7700 DEBUG NAS-AM tasks/amf/amf_app_ue_context.cpp:0262    Stored UE id 9
012950 Thu Apr 21 06:39:09 2022 7F49439D7700 WARNI AMF-AP tasks/amf/Registration.cpp      :0304    AMF-PROC  - AMF Registration procedure not accepted
012951 Thu Apr 21 06:39:09 2022 7F49439D7700 DEBUG NAS-AM tasks/amf/Registration.cpp      :0332    Processing REGISTRATION_REJECT message
012952 Thu Apr 21 06:39:09 2022 7F49439D7700 DEBUG NAS-AM tasks/amf/amf_as.cpp            :1473    Send AS connection establish Reject for UE ID: 9
012953 Thu Apr 21 06:39:09 2022 7F49439D7700 DEBUG NAS-AM tasks/amf/amf_app_ue_context.cpp:0262    Stored UE id 9
012954 Thu Apr 21 06:39:09 2022 7F49439D7700 INFO  NAS-AM tasks/amf/amf_as.cpp            :1431    AMFAS-SAP - Send Registration Reject message (cause=3)

**Comment by moinuddin1980** [comment]
The imsi deconcealing in subscriberdb is dependent upon the ue_pubkey, ue_ciphertext and ue_encrypted_mac received from UE in the registration request.
The length of ue_ciphertext  as per standards is 5 bytes.
But, the Spirent tool is sending the ciphertext as 10 bytes.
Hence, while copying the ciphertext only 5 bytes from the buffer are copied in AGW.
Also, the remaining 5 bytes of ciphertext gets copied to ue_encrypted_mac making it invalid value.

AGW uses the crypto.ECIES algorithm to decrypt the imsi where the ciphertext is considered only for 5 bytes

**Comment by NeelimaKalpana** [comment]
This issue is still open

**Comment by NeelimaKalpana** [comment]
Will validate and close after the below fix is in master.

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/13419
