### ISSUE TITLE
Stateless feature integration for AMF

### ISSUE THREAD

**Issue by sreedharkumartn** [magma/magma#11072]

**Comment by shashidhar-patil** [comment]
**Environment setup:**
This test was performed by including both AMF stateless feature changes and NGAP stateless feature changes.
The following PRs were taken as a base to perform this integration test using ueransim.
AMF PRs: #10605 #10805 #10903 #10853 #10885 #10906 #10908 #10958 #11034 
NGAP PRs: #11014 #11005 #11032 #11070

**Test Plan:**
1. Bring up mme. Add subscriber. Connect GNB(ueransim). Connect UE(ueransim).                  
    UE registration and PDU session is up.
2. Do a make restart. This mimics a mme crash and the state data is lost.**(1)**
3. Trigger a ps-release from the ueransim's ue-cli.
     **Expected behavior:** The PDU session release should take place successfully. This verifies that mme has fetched 
       the data from Redis DB and is successfully able to continue with the ps-release flow.
     **Observed**: Successfully continuation.
4. Do a make restart. This mimics a mme crash and the state data is lost.**(2)**
5. Trigger deregister normal from the ueransim's ue-cli.
    **Expected behavior:**  The deregister normal should take place successfully. We receive a Guti-based registration Request.
     **Observed**: Successfully continuation and Guti-based registration is successful and PDU session is established.
6. Do a make restart. This mimics a mme crash and the state data is lost.**(3)**
7. Trigger deregister switch-off from the ueransim's ue-cli.
    **Expected behavior:** The deregister switch-off should take place successfully
     **Observed**: De-register switch-off is successful.

The following is a snapshot of the Redis DB entries after Registration and PDU session establishment.
This verifies the state data being written to Redis DB.
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/89975652/148546923-f8e32d23-7faa-422d-bdb8-394d952d3e9b.png)

**MME LOGS:**
- After PDU session establisment :  [pdusession.log](https://github.com/magma/magma/files/7828906/pdusession.log)
- After ps-release: [ps-release.log](https://github.com/magma/magma/files/7828925/ps-release.log)
- After deregister normal: [dereg_normal.log](https://github.com/magma/magma/files/7828931/dereg_normal.log)
- After deregister switch-off: [dereg_switchoff.log](https://github.com/magma/magma/files/7828932/dereg_switchoff.log)

**PCAP SNAP:**
![integration_amf_ngap](https://user-images.githubusercontent.com/89975652/148547739-70831b60-159b-4231-95d1-2105477a9222.png)

**Attached are complete PCAP and logs:**
[pcap_and_logs.zip](https://github.com/magma/magma/files/7828959/pcap_and_logs.zip)
