### ISSUE TITLE
[TVM] Observing a statistics counter issue while executing GUTI Registration scale Test with more than 1 loop

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11096]
Hi @arun-magma ,

**Expected behavior:**
200 UE, 12 GNB, 5 UE/s, 5 loop -  Script should be able to send 2000 Registration requests and Accept the 2000 Registration Request and PDU session Establishment/Release, De-Registration.

**Actual behavior:**
200 UE, 12 GNB, 5 UE/s, 5 loop - For single loop it is creating 400 Registration Requests and Accepting 400 Registrations, but when we are executing GUTI Registration TC with 5 loops we are observing only 1200 sessions, it should create 2000 Registration requests but after 1200 sessions Testcase is stopping automatically, can you please do the needful to resolve the issue.

**Comment by arun-magma** [comment]
200 SUCI based Attach, Rest 1000 attaches are set 5 times GUTI loop, Total to 1200
GUTI is derived with onetime SUCI attach and no need for GUTI base Reattaches, during Loop all  5 GUTI reattach uses the same GUTI derived from first SUCI attach, this is very much inline to production scenario.

**Comment by arun-magma** [comment]
TC1a loop is good now with Maxing out RUN TIME, will reduce this to 10 loops in Regression if we agree.
@rupa455wavelabs @NeelimaKalpana 

[https://app.zenhub.com/files/170803235/42115fdc-5ec0-4f4f-a98a-c1d83290f79d/download](https://app.zenhub.com/files/170803235/42115fdc-5ec0-4f4f-a98a-c1d83290f79d/download)

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma ,
I  will discuss with the team and get back to you

Thanks
