### ISSUE TITLE
Add ability for Magma admin define custom routing rules for traffic subsets.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#1109]
### Your Environment
Version: 1.0.0
Affected Component: Orchestrator, AGW
Deployment Environment: AWS, bare-metal

### Describe the Issue
At the moment Magma admin has no ability configure Access Gateway to make it able to distinguish specific traffic subset and mark it with specific VLAN tag or "route" it in other direction then default uplink port. For the modern LTE networks with lots of IoT devices and other latency sensitive clients it's important to provide ability to route their traffic to Edge Cloud so it can be processed with low latency.

### Suggested Implementation
As result of magma code base review look like we can provide required functionality in following way:
 - Add optional Ryu App in PipelineD which can match specific traffic and mark it with VLAN or define custom out port
 - Add configuration params for new app in to mconfig protobuf definition for PiplineD
 - Ensure we can update mconfig for PipelineD through the Orchestrator API and magmaD 

@xjtian, @amarpad, @lionelgo would be cool to get your feedback on this feature request as well as for suggested implementation.

**Comment by amarpad** [comment]
Thanks for the outline.
The optional RYU service is making a forwarding decision that is based on the PDN which is tied to the APN. Ideally have an APN associated with the subscriber and then having some forwarding rules associated with the APN which is managed by this new controller.
Setting a VLAN is in the underlay and potentially we should do the tagging of the VLAN as part of the output decision made in the in/out controller and then the APN -> Forwarding decision is just a TAG, like send to network1 or network2 etc. and then we have a physical rule that says network1, network2 etc. maps to a vlan or a specific out port.
Please let me know if this makes sense

**Comment by ulaskozat** [comment]
The feature makes sense to me. As Amar pointed out, the next hop PDN decision should be based on the APN for which the PDN session is established.

**Comment by 119Vik** [comment]
@amarpad  @ulaskozat  thanks for the answer and for suggested approach, it totally makes sense. Let me dig in to the codebase and prepare draft implementation.

**Comment by 119Vik** [comment]
@amarpad, @ulaskozat  can you please correct me if I'm wrong ?
 

1.  to allow UE to be connection to PDN we need to define APN as allowed (or even default) for UE's IMSI in HSS?
1. 1 UE can have only 1 APN connection ? so we can't have 2 Bearers for same UE which are connecting UE to 2 different PDNs (at least for today and some nearest future)?
1. If previous statement is correct we will have all traffic for UE routed trough Edge Cloud even to the internet ?
1. APN is used by EPC services during UE auth process and "Create Bearer" , "Update Bearer" steps so when Bearer is established and traffic flowing though the OVS we can't distinguish PDN1 traffic from PDN2 ?

**Comment by ulaskozat** [comment]
My answers for the four questions:

1.  For each APN that UE has access, there should be an APN configuration in HSS.

2. A UE can connect to more than one APN. In the current code, we limit one PDN session per APN for a given UE. E.g., if UE has two APNs configured, then it can have 2 PDN connections.

3. There is no assumption on how traffic is routed beyond the next PDN that AGW is connected to. We allow an AGW be connected to multiple PDNs (virtual or physical) and each PDN has at least one APN. 

4. PDN1 and PDN2 have separate mutually exclusive set of default and dedicated (optional) bearers. UE is assigned a distinct IP address for each PDN session/connection and all the bearers in the same PDN session use the same UE IP address. Thus, packet filter rules based on UE (local) IP addresses are used to distinguish between PDNs. Default and dedicated bearers in the same PDN session/connection are distinguished based on the packet filter rules (flow match) and the packet filter rules are prioritized based on the policy precedence of a given dedicated bearer.

**Comment by 119Vik** [comment]
@ulaskozat just created PR with placeholders and comments which you can review to confirm that I understood your idea correctly and integration points were identified correctly.

**Comment by ekowtaylor** [comment]
Stale
