### ISSUE TITLE
Show a more relevant message when there is no subscriber being added in NMS

### ISSUE THREAD

**Issue by ankitMeta1** [magma/magma#11126]
### Your Environment (If applicable)

- **Affected Component:** NMS
- **Deployment Environment:**  local docker-compose

### Describe the problem

**Description**
When a user tries to add subscribers on NMS, a pop up comes up and says "Subscriber(s) saved successfully", which is fine for the case when there are subscribers added, but even when there is no subscriber to add (i.e user didnt add a row or forgot to got to the actions tab to confirm the details on the row) we still get the same message, which is not wrong but isnt really applicable.

### Describe your idea (optional)

**Description**
A clear message like "No Subscriber(s)/Nothing to add" might be more meaningful and applicable, it also helps when user inadvertently doesnt follow the correct flow for adding the Subscriber(for example:- user has to add a row with subscriber information, and then confirm this information by clicking the tick button in the Action tab, and if they don't do it, nothing will be added by hitting the Save and Add Subscribers button)

**Comment by andreilee** [comment]
Currently backlogged.
