### ISSUE TITLE
[Proposal] CG-NAT support on magma to scale up concurrent sessions

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#11136]
## Overview
CG-NAT feature on magma will enable FWA service providers offer IPv4 and IPv6 connectivity supporting concurrent sessions on the core network.

CGNAT must be deployed to enable key capabilities such as:
1.  Enablement of IP address expansion by relying on the CGNAT to overcome the IPv4 address exhaustion, with the support of NAT64/DNS64 and NAT46 seamless IPv4/v6 connectivity
2.  Enhanced threat prevention by hiding subscribers’ and infrastructures’ IP addresses from the Internet.
3.  High scalability to support the rapid growth in the number of subscribers and devices to substantially increase revenue.
4.  Carrier Grade NAT as a Lifecycle Strategy: Service providers need to implement a network address translation strategy that includes both a short-term plan to address the preservation of their existing IPv4 address allocation and a long-term plan to seamlessly migrate to an IPv6 infrastructure. This requires a solution that provides a robust set of Carrier Grade Network Address Translation capabilities and addresses the entire lifecycle of the transition from IPv4 to IPv6.

## Solution
This Proposal intends to implement python based CGNAT and integrate with pipelined. It generates CGNAT rules using netmap and handled by pipelined on UPF.

**Comment by pshelar** [comment]
@prabinakpattnaik Thanks for this proposal, This would very useful addition to AGW.
Do you have any particular CG-NAT in mind for AGW?

**Comment by prabinakpattnaik** [comment]
@pshelar, Yes, Python based library "py-cgnat" for generating firewall rules to deploy Carrier-Grade NAT, besides translating a given IP and port to its private address and vice versa.

Please review the Proposal document #11137 (I have mentioned the details about design),

**Comment by pshelar** [comment]
does it support NAT46 or NAT64?

**Comment by pshelar** [comment]
Lets compare OVS based NAT and py-cgnat based NAT approach to make decision on implementation direction.

**Comment by lucasgonze** [comment]
This issue is closely related to https://github.com/magma/magma/pull/11137, which has rightly been closed as stale.
