### ISSUE TITLE
[Proposal] Deep packet Inspection service to enforce policy rules on 5G SA Deployments.

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#11134]
## Overview
DPI (Deep Packet Inspection) is a traffic recognition method that classifies IP traffic in real time. DPI identifies protocols, applications and application attributes. In addition to IP traffic classification, DPI engines extract protocol and application-based metadata,
providing insight into user behavior and application usage.

TIP OCN Functional requirement REQ-OCN-18 for FWA deployment asks for application detection as a minimum DPI requirement. 

## Proposal
Will provide the proposal document for gap (design) analysis to provide DPI support on magma  OVS and Pipelined.

**Comment by lucasgonze** [comment]
Project was approved but implementation was abandoned.

**Comment by lucasgonze** [comment]
Closing by TSC consensus 6/17/2024
