### ISSUE TITLE
[Regression]TC17 is failing as PDU is getting rejected with Cause=91 even UE is requesting the session with subscribed DNN.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11149]
[https://app.zenhub.com/files/170803235/c36744c0-4329-4dfe-be1d-24ffdc8f3e45/download](https://app.zenhub.com/files/170803235/c36744c0-4329-4dfe-be1d-24ffdc8f3e45/download)- Version: 
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: bare-metal (AGW)-VM Based

## Describe the Issue
TC17 is failing as PDU is getting rejected with Cause=91 even UE is requesting the session with subscribed DNN. IN Syslogs noticed the subscriber lock during the timestamp TC17 got triggered. 

**To Reproduce**
1. Trigger the regression SUIT.

**Expected behavior**
AGW should respond with the proper response.

**Screenshots**
mme.log 
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/38729d2c-cf87-49fe-9693-8d5894de8675)

Syslogs : Where subscriberdb locked at that time stamp (16:56:38).
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a8d981d0-1dee-4298-a78a-610cfcc6eff6)

DNN Got decoded:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/846cc5f4-1026-4b80-87cb-548fb1c81cac)

Note: Subscribed DNN and UE requested DNN are same. 
**Additional context**
Note : This is a random failure noticed in regression SUIT.

**Comment by NeelimaKalpana** [comment]
[14-1-2022]
Observed the Subscriber lock in TC20a , and TC is failing as AMF is sending the reject with cause:91 , here the UE requested dnn is same as Subscribed dnn.

ScreenShots:
mme.log:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/3aeb70e8-1d90-4be9-b68e-5b6e5f076f75)

syslogs:[https://app.zenhub.com/files/170803235/9a29cfb5-bc88-48a9-a8af-a8fd1bf072eb/download](https://app.zenhub.com/files/170803235/9a29cfb5-bc88-48a9-a8af-a8fd1bf072eb/download)
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/41ae456d-8d4e-41cb-8f7c-e7e55702fd11)

[https://app.zenhub.com/files/170803235/846a6634-52f1-4555-8e4c-420d433f37fa/download](https://app.zenhub.com/files/170803235/846a6634-52f1-4555-8e4c-420d433f37fa/download)

**Comment by arun-magma** [comment]
@NeelimaKalpana : For Sub_Lock issues lets collect sys_log or sub_db journal log for longer duration and check its persistence time, its highly random in sense probably we can combine it with some loop test.

**Comment by NeelimaKalpana** [comment]
Yes Arun , we tried in loop run as well.But it is not happening in our setups might be because of our setup environment.

In out server we are having only 200 IMSI subscribed , so I will try to add 600 IMSI and try for loop run.
load .
Yogesh and team are trying to provide some logs , where this subscribe-db will get locked , so it will be easy to analyze.

**Comment by NeelimaKalpana** [comment]
Issue is still observed so re-opening it.
Logs screen shot for quick reference:
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:   }
Mar 21 12:12:19 TVM3-SA-regression sctpd[3602]: I0321 12:12:19.302579  4557 sctp_connection.cpp:195] Unhandled notification type 32777
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: INFO:root:(b' 2306334', b'                     USER        PID ACCESS COMMAND\n/var/opt/magma/subscriber1.db:\n                     root      F.... (root)python3\n')
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: ERROR:grpc._server:Exception calling application: IMSI222456000000101
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: Traceback (most recent call last):
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/store/sqlite.py", line 265, in get_subscriber_data
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:     res = conn.execute(
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: sqlite3.OperationalError: database table is locked: subscriberdb
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: During handling of the above exception, another exception occurred:
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: Traceback (most recent call last):
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:     response_or_iterator = behavior(argument, context)
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/s6a_proxy_servicer.py", line 102, in UpdateLocation
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:     profile = self.lte_processor.get_sub_profile(imsi)
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/processor.py", line 152, in get_sub_profile
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:     subs = self._store.get_subscriber_data(sid)
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/store/sqlite.py", line 282, in get_subscriber_data
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]:     raise SubscriberServerTooBusy(subscriber_id)
Mar 21 12:12:19 TVM3-SA-regression subscriberdb[2306334]: magma.subscriberdb.store.base.SubscriberServerTooBusy: IMSI222456000000101
Mar 21 12:12:19 TVM3-SA-regression mme[2306468]: [ERROR] 2: Exception calling application: IMSI222456000000101
Mar 21 12:12:19 TVM3-SA-regression mme[2306468]: [ERROR]  Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 222456000000101; Status: Exception calling application: IMSI222456000000101; ErrorCode: 0
Mar 21 12:12:19 TVM3-SA-regression mme[2306468]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 222456000000101
Mar 21 12:12:19 TVM3-SA-regression sctpd[3602]: I0321 12:12:19.879161  4557 sctp_connection.cpp:195] Unhandled notification type 32777


Please find the latest logs for the failures

[https://app.zenhub.com/files/170803235/387e98da-908b-40ce-a476-b2a76771bab6/download](https://app.zenhub.com/files/170803235/387e98da-908b-40ce-a476-b2a76771bab6/download)

**Comment by NeelimaKalpana** [comment]
Closing this issue as problem is not observed in latest Runs.
