### ISSUE TITLE
[Sigscale OCS integration] After succesful attach prepaid UE can't download or access internet

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#11157]
### Your Environment

- **Version:** master (commit b852ac45f)
- **Affected Component:** LTE Gateway, Sigscale OCS release 3.2.12
- **Affected Subcomponent:** NA
- **Deployment Environment:** local docker-compose (orc8r, NMS and FeG), Vagrant VM (AGW), Vagrant VM (OCS and OAI HSS)

### Describe the Issue

I am tryiyng to make an integration with Sigscale OCS software release 3.2.12, my setup as follows:

- USRP B210 that connect via USB to server running OAI eNodeB.
- Docker compose running on same server for orc8r, NMS and FEG.
- One Vagrant VM running Magma services on baremetal
- One Vagrant VM running OAI HSS and Sigscale OCS.

I made this integration scenario on multiple steps:
1- Using Magma standalone with internal subscriber DB [Succesful, user can attach to internet]
2- Using Magma as EPC and OAI HSS to manage authentication functions [Succesful, user can attach to internet]
3- Introduced Sigscale OCS and configured (user, policy and offer) [User can attach and get 4G signal and IP from Magma EPC, however there is no internet connectivity].
Note: Same setup and same network connections works normally as postpaid by setting the parameter (gx_gy_relay_enabled to false of the LTE network).

**To Reproduce**
1. Set gx_gy_relay_enabled to true to make sure the LTE network should use Gx and Gy interfaces.
2. Configure policy, charging groups and profiles on the Magma (configuration as below).
3. Configure OCS by setting user, offer and policy (which matches the Magma ones).
4. Try to attach physical phone, attach was succesful and accepted, authentication passed but user can't access internet.

**Expected behavior**
Magma should provide internet connectivity and send usage info to OCS.

**Screenshots**
![Screen Shot 2022-01-13 at 6 14 15 PM](https://user-images.githubusercontent.com/34710611/149367168-c9a0538c-437b-411a-a5a1-e3503c785a62.png)
![Screen Shot 2022-01-13 at 6 15 33 PM](https://user-images.githubusercontent.com/34710611/149367385-9c43ab84-8202-4743-a824-d5b64755760f.png)
![Screen Shot 2022-01-13 at 6 15 44 PM](https://user-images.githubusercontent.com/34710611/149367389-5062408e-7d55-4aeb-9c19-c0fbee7be6f7.png)
![Screen Shot 2022-01-13 at 6 16 09 PM](https://user-images.githubusercontent.com/34710611/149367395-1690315f-e5fb-4947-922c-ac3f17fec9c6.png)

**Additional context**
Below logs are relevant to this case:
1- Magma configuration (LTE network, FEG network and gateways, Policy, qos profile and charging group).
[Info.txt](https://github.com/magma/magma/files/7864122/Info.txt)

2- pcap file of the Diameter interaction between FEG and OCS (full pcap with S1AP messages available but for 180 Mbyte, I can share it if needed)
[billing-diameter-attach-test-prepaid 1.pcap.zip](https://github.com/magma/magma/files/7864132/billing-diameter-attach-test-prepaid.1.pcap.zip)

3- tail -f /var/log/mme.log (relavent to this attach request only).
[trace.txt](https://github.com/magma/magma/files/7864138/trace.txt)

Let me know if more info are needed or some configuration are missing

**Comment by MAAHamid** [comment]
hey @uri200 appreciat your support in this issue, can't mention Vance unfortunately

**Comment by blueCARDSS** [comment]
@MAAHamid hi if you can post sessionD log it will be more clear .

**Comment by uri200** [comment]
Hey @MAAHamid per the pcap, the response includes a static `policy_0`. Is that policy defined on orc8r?. Why don't you define the rules on the OCS?


![image](https://user-images.githubusercontent.com/16157139/149414725-0a64d805-e82e-43b5-913f-1865cf46b28e.png)

Note the session terminate immediately, that makes me think there is an error on the rules. You can try to see the log of sessiond doing
```
sudo journalctl -fu magma@sessiond
```

You can also increase the level of verbosity changing it at `/etc/magma/sessiond/yml`
```
log_level: DEBUG
print_grpc_payload: true
```

Here you have an exampe of Create Session Response received by sessiond from PCRF/OCS. As you can see here we use dynamic rules so the definitoon of the rule comes from the PCRF/OCS

```
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]: I0113 13:55:37.315424 2943019 GrpcMagmaUtils.cpp:58]
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:   magma.lte.CreateSessionResponse {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       credits {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         success: true
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         sid: "IMSI999991234567810"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         charging_key: 9
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         credit {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           validity_time: 86400
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           granted_units {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             total {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               is_valid: true
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               volume: 2000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             tx {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               is_valid: true
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               volume: 1000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             rx {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               is_valid: true
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               volume: 1000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         result_code: 2001
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         service_identifier {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           value: 59
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         tgpp_ctx {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           gy_dest_host: "tvm-vocs.magma.com"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       dynamic_rules {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         policy_rule {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           id: "DEFAULT1-QCI9"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           priority: 1
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           rating_group: 9
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           flow_list {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             match {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               udp_dst: 19000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               ip_proto: IPPROTO_UDP
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               ip_src {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:                 address: "192.168.128.14"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               ip_dst {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:                 address: "172.16.20.111/32"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           flow_list {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             match {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               udp_dst: 17000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               ip_proto: IPPROTO_UDP
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               direction: DOWNLINK
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               ip_src {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:                 address: "172.16.20.111/32"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               ip_dst {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:                 address: "192.168.128.14"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:               }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           qos {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             max_req_bw_ul: 100000000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             max_req_bw_dl: 100000000
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             qci: QCI_9
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           redirect {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           service_identifier {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:             value: 59
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:           }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       session_id: "IMSI999991234567810-125334"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       tgpp_ctx {
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         gx_dest_host: "tvm-vpcrf.magma.com"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:         gy_dest_host: "tvm-vocs.magma.com"
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       event_triggers: UNSUPPORTED
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:       online: true
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]:   }
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]: I0113 13:55:37.316057 2943019 LocalSessionManagerHandler.cpp:372] Processing CreateSessionResponse for IMSI999991234567810-125334
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]: I0113 13:55:37.316377 2943019 SessionState.cpp:1590] Session: IMSI999991234567810-125334 Teid: 0 FSM state change from SESSION_CREATING to SESSION_ACTIVE of imsi: IMSI999991234567810
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]: I0113 13:55:37.316977 2943019 LocalSessionManagerHandler.cpp:405] Successfully initialized IMSI999991234567810-125334 in SessionD after talking to PolicyDB/SessionProxy
Jan 13 13:55:37 tvm1-agw2 sessiond[2943019]: I0113 13:55:37.316990 2943019 LocalSessionManagerHandler.cpp:530] Sending a request to DirectoryD to register sessiond ID: IMSI999991234567810-125334 msisdn: 1234567810
```

Here we have pcaps with create session, maybe you can compare to see if you have something wrong on your user profile

[docs.magmacore.org/docs/next/resources/ref_pcap#pcap-collection](https://docs.magmacore.org/docs/next/resources/ref_pcap#pcap-collection)

**Comment by vances** [comment]
> Hey @MAAHamid per the pcap, the response includes a static `policy_0`. Is that policy defined on orc8r?. Why don't you define the rules on the OCS?

You can certainly define the rules with SigScale OCS (PCRF) however it has been my understanding that Magma didn't support dynamic rules (`Charging-Rule-Definition`) but only static predefined rules (`Charging-Rule-Name`). So I instructed @MAAHamid to set the _Predefined_ flag in the _Policy Rule_ as seen in the screen shot above.

> Here you have an exampe of Create Session Response received by sessiond from PCRF/OCS. As you can see here we use dynamic rules so the definitoon of the rule comes from the PCRF/OCS

Well that is GREAT news!  All @MAAHamid needs to do is uncheck _**Predefined**_ in the _Policy Rule_ of SigScale OCS and he can do all the _Policy_ management from there.

**Comment by blueCARDSS** [comment]
@vances @uri200  hi sorry to jump in this issue but i am facing similar challenges .When predefined rule was on i am able to connect but not able to access internet . After disabling predefined rule on ocs i am not able connect with network . 

![Capture11](https://user-images.githubusercontent.com/92744847/149472584-8000d6a3-ced3-42d5-95cc-731c0a0e0d29.PNG)
![Capture12](https://user-images.githubusercontent.com/92744847/149472592-56ed9380-7a36-450d-a027-cb1c816b717e.PNG)
[dishnet not working env.zip](https://github.com/magma/magma/files/7868883/dishnet.not.working.env.zip)
![Capture13](https://user-images.githubusercontent.com/92744847/149473534-a904c1df-32aa-400d-9617-e4665e8f3d31.PNG)

**Comment by uri200** [comment]
Hey @blueCARDSS not sure if that issue is caused by OCS configuration, but the way to see it  is on OCS logs.  Magma sends create request to PCRF/OCS but the reply it gets is unable to comply. So it is better to start checking OCS logs to figure out the reason why OCS is returning that and then see if that is caused by anything else.

Make sure your subscriber on ocs matches with the subscriber you are requesting for

![image](https://user-images.githubusercontent.com/16157139/149529931-d7c769fb-0f5c-4aa5-9c3c-4a755541d1f4.png)


Here we have pcaps with create session, maybe you can compare to see if you have something wrong on your user profile

https://docs.magmacore.org/docs/next/resources/ref_pcap#pcap-collection

**Comment by vances** [comment]
> Magma sends create request to PCRF/OCS but the reply it gets is unable to comply.

Yes, we're looking into that now. At this point it seems to be a problem in OCS.

**Comment by MAAHamid** [comment]
> The response includes a static `policy_0`. Is that policy defined on orc8r? Why don't you define the rules on the OCS?

Yes the policy was defined on the orc8r according to below configs, I followed the instructions from Vance and set the flag to "Pre-defined", that is why OCS sent only the name instead of the dynamice one:

curl -X GET "https://10.237.71.196:9443/magma/v1/networks/feg_lte_test/policies/rules" -H  "accept: application/json"

[
  "policy_0"
]

curl -X GET "https://10.237.71.196:9443/magma/v1/networks/feg_lte_test/policies/rules/policy_0" -H  "accept: application/json"

{
  "flow_list": [
    {
      "action": "PERMIT",
      "match": {
        "direction": "UPLINK",
        "ip_proto": "IPPROTO_IP"
      }
    },
    {
      "action": "PERMIT",
      "match": {
        "direction": "DOWNLINK",
        "ip_proto": "IPPROTO_IP"
      }
    }
  ],
  "header_enrichment_targets": null,
  "id": "policy_0",
  "priority": 1,
  "qos_profile": "0",
  "rating_group": 1,
  "tracking_type": "ONLY_OCS"
}


> Note the session terminate immediately, that makes me think there is an error on the rules. You can try to see the log of sessiond doing

HYG sessiond logs and mme logs, 
[sessiond.log](https://github.com/magma/magma/files/7877305/sessiond.log)
[mme.log](https://github.com/magma/magma/files/7877312/mme.log)

Is this related to QoS ID 9 wasn't set properly. Magma only allowed the default bearer but didn't allow internet access with QCI=9?

**Comment by MAAHamid** [comment]
> > Magma sends create request to PCRF/OCS but the reply it gets is unable to comply.
> 
> Yes, we're looking into that now. At this point it seems to be a problem in OCS.

@vances I had to re-install OCS for some testing, I am facing same issue with OCS v3.2.15, 
[billing-diameter-attach-test-prepaid-ocs.pcap.zip](https://github.com/magma/magma/files/7877319/billing-diameter-attach-test-prepaid-ocs.pcap.zip)
![Screen Shot 2022-01-16 at 6 03 12 PM](https://user-images.githubusercontent.com/34710611/149667732-77b0d780-5a30-4975-b22d-1ac6a1548969.png)

I am now unable to retest attach and internet access with predefined flag set to "false" due to diameter uncomply issue, kindly let me updated once solved or a having a workaround.

**Comment by MAAHamid** [comment]
@vances any update about the last issue?

**Comment by vances** [comment]
> @vances any update about the last issue?

Yes, version 3.2.16 of SigScale OCS is available now.which includes commit [0fa22099a6](https://github.com/sigscale/ocs/commit/0fa22099a6bb2480abc8c2741d2bd5389bdc8db6) addressing a typo in the 3GPP DIAMETER dictionary.  I think this shall resolve this issue.

**Comment by MAAHamid** [comment]
> > @vances any update about the last issue?
> 
> Yes, version 3.2.16 of SigScale OCS is available now.which includes commit [0fa22099a6](https://github.com/sigscale/ocs/commit/0fa22099a6bb2480abc8c2741d2bd5389bdc8db6) addressing a typo in the 3GPP DIAMETER dictionary. I think this shall resolve this issue.

@vances I have noticed the new version earlier today and tested it, however I faced another issue which I reported over mail:
![image](https://user-images.githubusercontent.com/34710611/150687705-c1f1faae-3837-426d-b8cd-b8ba894447e2.png)

No changes introducted on magma side, so the CCR wasn't changed, the only change was in OCS version upgrade, pcap and all details are on the mail sent to you and support team.

**Comment by vances** [comment]
> @vances I have noticed the new version earlier today and tested it, however I faced another issue 

It seems recent commit [e014a012900d](https://github.com/sigscale/ocs/commit/e014a012900df8bf2b41bbd20ecf0f4257403cd2) introduced a few type errors. These should be corrected in commit [d427c7bec101](https://github.com/sigscale/ocs/commit/d427c7bec10120b7e3dd0ec12139daf1694cfb62) and will be included in v3.2.17.

**Comment by MAAHamid** [comment]
@vances I have noticed the new release of OCS, Version: 3.2.18-1+ubuntu18.04, thanks, the old issue was solved and attach is completed now.

@uri200 After OCS reported proper CCA and dynamic policy was sent to Magma, user was attached succesfully, however there wasn't any internet connectivity, can you help with checking attached logs and provide advice?

magma.lte.CreateSessionResponse {
    credits {
      success: true
      sid: "IMSI208930000000009"
      charging_key: 9
      credit {
        granted_units {
          total {
            is_valid: true
            volume: 200000
          }
          tx {
          }
          rx {
          }
        }
      }
      result_code: 2001
      tgpp_ctx {
        gy_dest_host: "ocs.realm.test"
      }
    }
    static_rules {
      rule_id: "rule_1"
    }
    dynamic_rules {
      policy_rule {
        id: "policy9"
        rating_group: 9
        qos {
          max_req_bw_ul: 100000000
          max_req_bw_dl: 100000000
          qci: QCI_9
        }
        redirect {
        }
      }
    }
    session_id: "IMSI208930000000009-115898"
    tgpp_ctx {
      gx_dest_host: "ocs.realm.test"
      gy_dest_host: "ocs.realm.test"
    }
    online: true
}

git branch -v
* master b852ac45f [behind 423] chore: Set default build type of magma-build.sh to be RelWithDebInfo (#8632)

[mme log.log](https://github.com/magma/magma/files/8056212/mme.log.log)
[sessiond log.log](https://github.com/magma/magma/files/8056213/sessiond.log.log)
[info.txt](https://github.com/magma/magma/files/8056215/info.txt)
[billing-diameter-attach-test-prepaid-ocs.pcap.zip](https://github.com/magma/magma/files/8056217/billing-diameter-attach-test-prepaid-ocs.pcap.zip)

- The full trace including S1AP messages is available, let me know if it is needed so I can send it.

Kindly note:
- rule_1 was removed, test repeated but same symptom occur.
- QoS profile QCI_9 was added to orc8r, test was repeated but same symptom.
- policy9 was removed from Magma at all, test repeated but same symptom.

**Comment by uri200** [comment]
Hey @MAAHamid , you may need to turn on groc print on sessiond to see the messages sent back and forth.

You can do the same with in pipelined.yml (log_level to debug and print grpc). 

Both sessiond and pipelind will show on the report GRPC messages if bytes are being recorded or dropped.

Also it would be good to check with tcpdump on your AGW if you are receiving any packet on the GTP tunnel interface. If you are not getting any GTP packet when trying to surf the internet then the issue may be at eNB.

Since UE was attached I don't think MME log is needed anymore.

**Comment by MAAHamid** [comment]
@uri200 Strangely mmed, sessiond, pipelined crashed and failed to start after updating the yml files of sessiond and pipelined with below two lines:

sessiond.yml:
log_level: DEBUG
print_grpc_payload: true

pipelined.yml:
log_level: DEBUG
magma_print_grpc_payload: true

Nothing changed on the mme.yml file nor the gateway.mconfig, below logs of the service:

> ● magma@mme.service - Magma OAI MME service
     Loaded: loaded (/etc/systemd/system/magma@mme.service; disabled; vendor preset: enabled)
     Active: failed (Result: signal) since Tue 2022-02-15 17:40:52 UTC; 1s ago
    Process: 338266 ExecStartPre=/usr/bin/env python3 /usr/local/bin/generate_oai_config.py (code=exited, status=0/SUCCESS)
    Process: 338279 ExecStartPre=/usr/bin/env python3 /usr/local/bin/config_stateless_agw.py reset_sctpd_for_stateful (code=killed, signal=TERM)
    Process: 338337 ExecStopPost=/usr/bin/env python3 /usr/local/bin/service_util.py mme (code=exited, status=0/SUCCESS)
Feb 15 17:40:50 magma-dev-focal systemd[1]: Starting Magma OAI MME service...
Feb 15 17:40:50 magma-dev-focal mme[338266]: ERROR:root:Error retrieving config for spgw, key not found: ovs_internal_sampling_fwd_tbl
Feb 15 17:40:50 magma-dev-focal mme[338266]: WARNING:root:Service (spgw) missing in mconfig
Feb 15 17:40:52 magma-dev-focal systemd[1]: magma@mme.service: Control process exited, code=killed, status=15/TERM
Feb 15 17:40:52 magma-dev-focal systemd[1]: magma@mme.service: Failed with result 'signal'.
Feb 15 17:40:52 magma-dev-focal systemd[1]: Stopped Magma OAI MME service.

Any advice?
I have rebuilt the whole AGW VM, problem persisted.

**Comment by uri200** [comment]
Hey @MAAHamid note the change in the logs can not create an issue on MME.

Per the error some config files in MME are missing some values such neans that files were not updated properly.

Is this a baremetal AGW? Or are you using your dev VM? If you are using dev machine with vagrant then you probably have to either reprovision the VM or just destroy it and build it again.

**Comment by MAAHamid** [comment]
> 

Hello @uri200 , yes agree, the changes of the yml files shouldn't create an issue with MME. I have added one of the missing parameters on the mm.yml file (natEnable) it worked, however one of them (ovs_internal_sampling_fwd_tbl) isn't on spgw.yml file by default and even I don't know what value I should put for it.

I have destroyed the vagrant machine and created a new one but problem persisted.

**Comment by uri200** [comment]
Hey @MAAHamid  the reason for you to have older yml files on your Vagrant machine is provisioning. 

If you pull from master new code but do not do `vagrant porvision magma`, your code will be new, but your config files installed on vagrant vm will be old. That is how you end up with parameters not found. 

Note sometimes provisioning is not enough and you will have to destroy the VM.

Also make sure that provisioning completes successfully.  If it fails you will still be able to use the vm and you may not realize ansible didn't porivision completely the vm

**Comment by uri200** [comment]
You may also need to remove orc8r database in case you want to start from scratch there too
```
cd magma/orc8r/cloud/docker
./run.py --clear-db
```

**Comment by MAAHamid** [comment]
@uri200 @vances Hello again, it has been a long time hope both of you are doing well.

I have restarted working on this integration, still I am facing same issue, user got attached succesfully without traffic.

Currently I am using:
Magma: master 331551e22 fix(mme): Null terminates string to stop bufer overflow (#11925)
OCS: 3.2.18-1+ubuntu18.04

According to the logs and comparing to the reference PCAP, we can confirm following:
- OCS replied with the needed charging rules:
![image](https://user-images.githubusercontent.com/34710611/162219130-1c0632e9-96f3-4c14-815d-523fc1e2ecf7.png)

- OCS replied with the granted total units to be used:
![image](https://user-images.githubusercontent.com/34710611/162219355-229d3d5a-5486-4f64-b837-d6503031bcc2.png)

- Magma received the allowed units from OCS:
![image](https://user-images.githubusercontent.com/34710611/162219802-bd8c2c88-295c-4a6c-85a0-1b68fab4d4f0.png)

Below are the necessary logs:
[sessiond.txt](https://github.com/magma/magma/files/8443708/sessiond.txt)
[pipelined.txt](https://github.com/magma/magma/files/8443714/pipelined.txt)
[ocs.pcap.zip](https://github.com/magma/magma/files/8443719/ocs.pcap.zip)
[magma.pcap.zip](https://github.com/magma/magma/files/8443721/magma.pcap.zip)

Reaching this point, it is so confusing why Magma dropped user packets without errors or clear reason, is it confiugraiton issue? @uri200 can you help?

**Comment by uri200** [comment]
Hey @MAAHamid , there is no traffic being reported by ovs. See how the `rule_id: "QCI_9"` record doesn't show any tx or rx bytes being reported. There is not even dropped traffic. That means UE is not reaching AGW, so OVS has nothing to report (neither passed traffic or dropped traffic)

```
Apr 07 11:48:37 magma-dev-focal pipelined[824105]: records {
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   sid: "IMSI208930000000009"
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   rule_id: "QCI_9"
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   ue_ipv4: "192.168.128.14"
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   rule_version: 1
Apr 07 11:48:37 magma-dev-focal pipelined[824105]: }
Apr 07 11:48:37 magma-dev-focal pipelined[824105]: records {
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   sid: "IMSI208930000000009"
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   rule_id: "internal_default_drop_flow_rule"
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   ue_ipv4: "192.168.128.14"
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   dropped_tx: 6534
Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   dropped_rx: 252
Apr 07 11:48:37 magma-dev-focal pipelined[824105]: }
Apr 07 11:48:37 magma-dev-focal pipelined[824105]: epoch: 1649331810
Apr 07 11:48:37 magma-dev-focal pipelined[824105]: }
```

You may need to check if your eNB is really sending packets to the AGW. You can try to see if any packet gets there running tcpdump on your gtp interfaces at your AGW.
```
sudo tcpdump -i gtp_sys_2152 
sudo tcpdump -i gtp_bro
```

You may need to inspect ovs flows using any of those commands. But I think flows must be fine. They are just not receiving any data from enb
```
sudo ovs-ofctl dump-flows gtp_br0
sudo pipelined_cli.py debug display_flows
```

**Comment by MAAHamid** [comment]
> Hey @MAAHamid , there is no traffic being reported by ovs. See how the `rule_id: "QCI_9"` record doesn't show any tx or rx bytes being reported. There is not even dropped traffic. That means UE is not reaching AGW, so OVS has nothing to report (neither passed traffic or dropped traffic)
> 
> ```
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]: records {
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   sid: "IMSI208930000000009"
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   rule_id: "QCI_9"
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   ue_ipv4: "192.168.128.14"
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   rule_version: 1
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]: }
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]: records {
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   sid: "IMSI208930000000009"
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   rule_id: "internal_default_drop_flow_rule"
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   ue_ipv4: "192.168.128.14"
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   dropped_tx: 6534
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]:   dropped_rx: 252
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]: }
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]: epoch: 1649331810
> Apr 07 11:48:37 magma-dev-focal pipelined[824105]: }
> ```
> 
> You may need to check if your eNB is really sending packets to the AGW. You can try to see if any packet gets there running tcpdump on your gtp interfaces at your AGW.
> 
> ```
> sudo tcpdump -i gtp_sys_2152 
> sudo tcpdump -i gtp_bro
> ```
> 
> You may need to inspect ovs flows using any of those commands. But I think flows must be fine. They are just not receiving any data from enb
> 
> ```
> sudo ovs-ofctl dump-flows gtp_br0
> sudo pipelined_cli.py debug display_flows
> ```

ُThanks for the advice, problem is same eNB, AGW with same connection and configuration works on standalone mode without OCS. That is to say when I modify the LTE network not to federate Gx/Gy traffic and remove relative configuration from FEG, everything works fine and UE has active internet access.
Is there anything we can confirm from this ?

**Comment by vances** [comment]
On Sun, Apr 10, 2022 at 7:14 PM Mahmoud Abdelhamid ***@***.***>
wrote:

> problem is same eNB, AGW with same connection and configuration works on
> standalone mode without OCS.


How does eNB know that OCS is in use?  There must be something different in
the messaging.

-- 
Vance Shipley, CEO
SigScale Global Inc.
+639208370397

**Comment by uri200** [comment]
Hey @MAAHamid , eNodeb doesn't have the concept of OCS. The eNb just sets a tunnel to sessiond (sgw). 

The difference is at sessiond. What you could do is compare the rules installed on the federated vs non federated. You can use the same logs on sessiond you used before (with log info to debug and enable groc printing).

Comparing that you will be able to see the differences. Maybe there is a problem with the rule you installed there. But that seems weird, because pipelined was not reporting any usage at all.

You should also take a pcap of S1ap in both modes to see where the GTP U traffic is sent at all from eNb to AGW
