### ISSUE TITLE
[tvm-inbound] S8 gtp-u traffic flow breaks

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#11162]
Issue Title: S8 gtp-u traffic flow breaks

Description:
roaming plmn 001/02
testing basic Inbound roaming flows and find s8- gtp-u flow is not moving.
//checks done
s1-u uplink flow  is good.
gtp-u echo transaction is good between s8 source and destination IPs.

//Traces enclosed
3gpp pcaps
ovs-debug-logs
[inbound_roaming_01_220113_160839-1.pcapng.zip](https://github.com/magma/magma/files/7867044/inbound_roaming_01_220113_160839-1.pcapng.zip)

[ovs-debug-logs.zip](https://github.com/magma/magma/files/7867046/ovs-debug-logs.zip)
<img width="1792" alt="Screen Shot 2022-01-13 at 4 32 26 PM" src="https://user-images.githubusercontent.com/70725754/149450282-3e4e0409-39ce-4c19-a97c-13ff9b959dfb.png">

// Key IPs of this Setup:

// S1-u tunnel

src: 172.16.3.101
dst: 172.16.3.11

// S8-u tunnel

src: 192.168.62.3
dst: 192.168.62.110

UE flow

src:  192.168.126.6/24 (IPs allocated by external PGW)
dst: 192.168.62.3

Tested AGW build: 1.7.0-1642099598-b6b86e36

**Comment by uri200** [comment]
Hey @pshelar  , we have done changes on MME to centralize allocation of TEID on orc8r 

This should have not changed anything on datapath but maybe it has impacted it. Setup 1 has a custom mme version taken from the PR Below

If you want to take a look, the agw is at 
```
ssh magma@192.168.60.19
```
and the test can be easily run from 
```
mosh ng40@192.168.60.75


cd ~/magma/4g/automation/inbound_roamin$
ng40test inbound_roaming_01.ntl
```

https://github.com/magma/magma/pull/10985

**Comment by pshelar** [comment]
```
2022-01-14T00:08:45.524Z|01234|odp_util(revalidator3)|DBG|pending encap Unexpected state while processing packet_type=(1,0x800),reg1=0x10,reg6=0x1,reg8=0x5,reg9=0x80000005,tun_id=0x90000000,tun_src=172.16.3.101,tun_dst=192.168.62.110,tun_ipv6_src=::,tun_ipv6_dst=::,tun_gbp_id=0,tun_gbp_flags=0,tun_tos=0,tun_ttl=64,tun_erspan_ver=0,gtpu_flags=0,gtpu_msgtype=0,tun_flags=csum|key,metadata=0x76be5e6c205,in_port=3,nw_src=192.168.126.6,nw_dst=192.168.62.3,nw_proto=17,nw_tos=0,nw_ecn=0,nw_ttl=64,tp_src=17160,tp_dst=19160
```
is debug msg, and can be ignored safely.

**Comment by arun-magma** [comment]
@pshelar : Please provide some insights with debug steps to be followed during this s8 gtp-u issue ? , this will help to collect & attach more appropriate logs to quickly resolve issues.

**Comment by pshelar** [comment]
I just ran the test and it passed, so there was no need to do any debugging.

**Comment by arun-magma** [comment]
@pshelar @uri200 
I see again this s8 gtp-u traffic flow not moving both in dev AGW setup (tvm1) and in regression setup (tvm2), Please check, Setup details are listed below

[Setups info]
//TVM1
Emulator UI (to run test): 
mosh ng40@192.168.60.75
cd ~/magma/4g/automation/inbound_roamin$
ng40test inbound_roaming_01.ntl

AGW: 192.168.60.19
[Current build]
magma-sctpd/focal-ci,now 1.7.0-1637354267-93e7ad77 amd64 [installed,upgradable to: 1.7.0-1642099598-b6b86e36]
magma/focal-ci,now 1.7.0-1642023020-5d4cab23 amd64 [installed,upgradable to: 1.7.0-1642099598-b6b86e36]

//TVM2
Emulator UI (to run test): 
mosh ng40@192.168.60.81
ng40@facebook-2-vhopran:~/magma/4g/automation/TC_inbound_invidual$ 
ng40test inbound_roaming_01.ntl

AGW: 192.168.61.20
[Current build]
magma-sctpd/focal-ci,now 1.7.0-1642197942-be1cfad0 amd64 [installed]
magma/focal-ci,now 1.7.0-1642197942-be1cfad0 amd64 [installed]

**Comment by pshelar** [comment]
@arun-magma can you check flows in table 0, if those are present when you run the test.

**Comment by pshelar** [comment]
@arun-magma can you also follow doc to debug datapath issues: https://docs.magmacore.org/docs/next/howtos/troubleshooting/datapath_connectivity

This doc is not for S8 connectivity issues, but the basic packet tracing should be the same.

**Comment by arun-magma** [comment]
Hi @pshelar : 
Thanks! for the link, it helps & explains to get debug steps for home subs, In that i'm not sure which step is more relevant for S8-gtp-u path issues where two tunnels are involved (S1-u & S8-u), Please give little more insight for s8 gtp-u which specific check would help.

This issue is currently found only in Regression Environment which runs latest AGW build 
[Build IDs]
magma-sctpd/focal-ci,now 1.7.0-1642541607-e3f27a1d amd64 [installed]
magma/focal-ci,now 1.7.0-1642541607-e3f27a1d amd64 [installed]

And Here is the OVS Table flow output during the testrun & s8 gtp-u ul traffic failure, UE IP flows(192.168.126.4) are hitting table-0, Please take a look.

```
magma@regressionAGW:~$ 
magma@regressionAGW:~$ sudo ovs-ofctl dump-flows gtp_br0
 cookie=0x0, duration=8222.843s, table=0, n_packets=2, n_bytes=140, priority=10,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=19.973s, table=0, n_packets=10, n_bytes=10000, priority=10,tun_id=0x80000008,in_port="g_650310ac" actions=load:0x3f000000->NXM_NX_TUN_ID[],load:0xc0a83e6e->NXM_NX_TUN_IPV4_DST[],load:0x5->NXM_NX_REG8[],load:0x80000008->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1->NXM_NX_REG6[],load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=19.973s, table=0, n_packets=0, n_bytes=0, priority=10,tun_id=0x9,in_port="g_6e3ea8c0" actions=load:0x89090000->NXM_NX_TUN_ID[],load:0xac100365->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x9->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1->NXM_NX_REG6[],load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=19.973s, table=0, n_packets=0, n_bytes=0, priority=10,ip,in_port=mtr0,nw_dst=192.168.126.4 actions=load:0x89090000->NXM_NX_TUN_ID[],load:0xac100365->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x9->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1->NXM_NX_REG6[],load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=19.973s, table=0, n_packets=0, n_bytes=0, priority=10,arp,in_port=mtr0,arp_tpa=192.168.126.4 actions=load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=8222.843s, table=0, n_packets=1467, n_bytes=150776, priority=0 actions=resubmit(,1)
 cookie=0x0, duration=8253.387s, table=1, n_packets=12, n_bytes=9308, priority=10,in_port=LOCAL actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.386s, table=1, n_packets=1841, n_bytes=137354, priority=10,in_port=mtr0 actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.386s, table=1, n_packets=10, n_bytes=700, priority=10,in_port="proxy_port" actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.386s, table=1, n_packets=133, n_bytes=131140, priority=0,reg6=0 actions=set_field:0x1->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.386s, table=1, n_packets=171, n_bytes=171000, priority=0,reg6=0x1 actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.284s, table=2, n_packets=0, n_bytes=0, priority=12,arp,reg1=0x10,arp_tpa=10.1.0.1,arp_op=2 actions=set_field:0x1->reg6,resubmit(,3),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.283s, table=2, n_packets=0, n_bytes=0, priority=12,arp,reg1=0x10,arp_tpa=10.1.0.1,arp_op=1 actions=move:NXM_OF_ETH_SRC[]->NXM_OF_ETH_DST[],mod_dl_src:72:99:d9:1d:04:10,load:0x2->NXM_OF_ARP_OP[],move:NXM_NX_ARP_SHA[]->NXM_NX_ARP_THA[],load:0x7299d91d0410->NXM_NX_ARP_SHA[],move:NXM_OF_ARP_TPA[]->NXM_NX_REG0[],move:NXM_OF_ARP_SPA[]->NXM_OF_ARP_TPA[],move:NXM_NX_REG0[]->NXM_OF_ARP_SPA[],IN_PORT
 cookie=0x0, duration=8257.283s, table=2, n_packets=437, n_bytes=18354, priority=11,arp,metadata=0 actions=drop
 cookie=0x0, duration=8257.283s, table=2, n_packets=0, n_bytes=0, priority=10,arp,reg1=0x10,arp_op=2 actions=set_field:0x1->reg6,resubmit(,3),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.283s, table=2, n_packets=332, n_bytes=13944, priority=10,arp,reg1=0x10,arp_op=1 actions=move:NXM_OF_ETH_SRC[]->NXM_OF_ETH_DST[],mod_dl_src:3e:70:05:29:40:49,load:0x2->NXM_OF_ARP_OP[],move:NXM_NX_ARP_SHA[]->NXM_NX_ARP_THA[],load:0x3e7005294049->NXM_NX_ARP_SHA[],move:NXM_OF_ARP_TPA[]->NXM_NX_REG0[],move:NXM_OF_ARP_SPA[]->NXM_OF_ARP_TPA[],move:NXM_NX_REG0[]->NXM_OF_ARP_SPA[],IN_PORT
 cookie=0x0, duration=8257.282s, table=2, n_packets=1399, n_bytes=417274, priority=0 actions=resubmit(,3),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.282s, table=3, n_packets=2, n_bytes=140, priority=10,icmp6,reg1=0x1,ipv6_src=fe80::/10,icmp_type=133 actions=CONTROLLER:65535
 cookie=0x0, duration=8257.282s, table=3, n_packets=0, n_bytes=0, priority=10,icmp6,reg1=0x1,ipv6_src=fe80::/10,icmp_type=135 actions=CONTROLLER:65535
 cookie=0x0, duration=8257.281s, table=3, n_packets=0, n_bytes=0, priority=10,icmp6,reg1=0x10,ipv6_dst=ff02::1:ff00:0/104,icmp_type=135 actions=CONTROLLER:65535
 cookie=0x0, duration=8257.282s, table=3, n_packets=1397, n_bytes=417134, priority=0 actions=resubmit(,4),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.268s, table=4, n_packets=0, n_bytes=0, priority=100,icmp,reg1=0x1,nw_dst=10.1.0.1 actions=resubmit(,5),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.269s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=127.0.0.0/8 actions=drop
 cookie=0x0, duration=8257.269s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=192.168.62.103 actions=drop
 cookie=0x0, duration=8257.268s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=172.16.3.11 actions=drop
 cookie=0x0, duration=8257.268s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=192.168.61.20 actions=drop
 cookie=0x0, duration=8257.268s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=192.168.128.1 actions=drop
 cookie=0x0, duration=8257.268s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=10.1.0.1 actions=drop
 cookie=0x0, duration=8257.267s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=10.5.0.2 actions=drop
 cookie=0x0, duration=8257.280s, table=4, n_packets=1266, n_bytes=286134, priority=0,reg1=0x10 actions=resubmit(,5),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.280s, table=4, n_packets=131, n_bytes=131000, priority=0,reg1=0x1 actions=resubmit(,21),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8257.269s, table=5, n_packets=3794, n_bytes=292076, priority=1,in_port="proxy_port" actions=drop
 cookie=0x0, duration=8257.269s, table=5, n_packets=175835, n_bytes=182207215, priority=0 actions=resubmit(,10),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.383s, table=10, n_packets=171, n_bytes=171000, priority=15,reg6=0x1 actions=resubmit(,20),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.382s, table=10, n_packets=0, n_bytes=0, priority=12,ip,reg1=0x1,vlan_tci=0x0000/0x1000,nw_dst=10.1.0.1 actions=set_field:72:99:d9:1d:04:10->eth_dst,output:mtr0
 cookie=0x0, duration=8253.382s, table=10, n_packets=0, n_bytes=0, priority=12,ip,reg1=0x1,vlan_tci=0x1000/0x1000,nw_dst=10.1.0.1 actions=strip_vlan,set_field:72:99:d9:1d:04:10->eth_dst,output:mtr0
 cookie=0x0, duration=8253.383s, table=10, n_packets=1215, n_bytes=245364, priority=10 actions=resubmit(,11),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=8253.402s, table=11, n_packets=162334, n_bytes=169489780, priority=0 actions=resubmit(,12),set_field:0->reg0,set_field:0->reg3
 cookie=0xfffffffffffffffe, duration=8253.406s, table=12, n_packets=1196, n_bytes=226238, priority=0 actions=resubmit(,13),set_field:0->reg0,set_field:0->reg3
 cookie=0xfffffffffffffffe, duration=8253.397s, table=13, n_packets=198, n_bytes=128434, priority=0 actions=drop
 cookie=0x0, duration=8253.378s, table=20, n_packets=0, n_bytes=0, priority=12,reg10=0x1 actions=set_field:e6:8f:a2:80:80:80->eth_dst,output:"proxy_port"
 cookie=0x0, duration=8253.378s, table=20, n_packets=10, n_bytes=10000, priority=10,reg1=0x1 actions=set_field:3e:70:05:29:40:49->eth_dst,LOCAL
 cookie=0x0, duration=8253.379s, table=20, n_packets=180, n_bytes=180126, priority=0,ip,reg1=0x10,vlan_tci=0x0000/0x1000 actions=output:NXM_NX_REG8[]
 cookie=0x0, duration=8253.379s, table=20, n_packets=0, n_bytes=0, priority=0,ip,reg1=0x10,vlan_tci=0x1000/0x1000 actions=strip_vlan,output:NXM_NX_REG8[]
 cookie=0x0, duration=8253.378s, table=20, n_packets=0, n_bytes=0, priority=0,ipv6,reg1=0x10,vlan_tci=0x0000/0x1000 actions=output:NXM_NX_REG8[]
 cookie=0x0, duration=8253.378s, table=20, n_packets=0, n_bytes=0, priority=0,ipv6,reg1=0x10,vlan_tci=0x1000/0x1000 actions=strip_vlan,output:NXM_NX_REG8[]
 cookie=0x0, duration=8257.270s, table=21, n_packets=131, n_bytes=131000, priority=0 actions=resubmit(,5),set_field:0->reg0,set_field:0->reg3
magma@regressionAGW:~$ 
```

**Comment by arun-magma** [comment]
This issues is not found in another Dev AGW Environment which runs below build
@uri200 

[AGW Build]
magma-sctpd/focal-ci,now 1.7.0-1637354267-93e7ad77 amd64 [installed,upgradable to: 1.7.0-1642197942-be1cfad0]
magma/focal-ci,now 1.7.0-1642023020-5d4cab23 amd64 [installed,upgradable to: 1.7.0-1642197942-be1cfad0]
magma@tvm1-agw2:~$ 


[OVS Table logs during Traffic run]
`magma@tvm1-agw2:~$ sudo ovs-ofctl dump-flows gtp_br0
 cookie=0x0, duration=49606.265s, table=0, n_packets=96, n_bytes=6720, priority=10,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=49606.133s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,202)
 cookie=0x0, duration=49606.133s, table=0, n_packets=95, n_bytes=6650, priority=0,in_port="li_port" actions=resubmit(,202)
 cookie=0x0, duration=12.971s, table=0, n_packets=10, n_bytes=10000, priority=10,tun_id=0x80000004,in_port="g_40a10ac" actions=load:0x5000000->NXM_NX_TUN_ID[],load:0xac101496->NXM_NX_TUN_IPV4_DST[],load:0x4->NXM_NX_REG8[],load:0x80000004->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1->NXM_NX_REG6[],load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=12.971s, table=0, n_packets=2, n_bytes=2000, priority=10,tun_id=0x9fad09df,in_port="g_961410ac" actions=load:0x4000000->NXM_NX_TUN_ID[],load:0xac100a04->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x9fad09df->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1->NXM_NX_REG6[],load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=12.971s, table=0, n_packets=0, n_bytes=0, priority=10,ip,in_port=mtr0,nw_dst=192.168.126.1 actions=load:0x4000000->NXM_NX_TUN_ID[],load:0xac100a04->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x9fad09df->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1->NXM_NX_REG6[],load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=12.971s, table=0, n_packets=0, n_bytes=0, priority=10,arp,in_port=mtr0,arp_tpa=192.168.126.1 actions=load:0x76be5e6c205->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=49606.134s, table=0, n_packets=21917, n_bytes=110426, priority=0 actions=resubmit(,1)
 cookie=0x0, duration=324364.206s, table=1, n_packets=96, n_bytes=6720, priority=10,in_port=mtr0 actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=324309.585s, table=1, n_packets=138, n_bytes=9948, priority=10,in_port="proxy_port" actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49601.775s, table=1, n_packets=95, n_bytes=6650, priority=10,in_port=LOCAL actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=324364.206s, table=1, n_packets=3346, n_bytes=24100, priority=0,reg6=0 actions=set_field:0x1->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=324364.206s, table=1, n_packets=234, n_bytes=234000, priority=0,reg6=0x1 actions=set_field:0x10->reg1,resubmit(,2),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.132s, table=2, n_packets=0, n_bytes=0, priority=12,arp,reg1=0x10,arp_tpa=10.1.0.1,arp_op=2 actions=set_field:0x1->reg6,resubmit(,3),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.132s, table=2, n_packets=0, n_bytes=0, priority=12,arp,reg1=0x10,arp_tpa=10.1.0.1,arp_op=1 actions=move:NXM_OF_ETH_SRC[]->NXM_OF_ETH_DST[],mod_dl_src:ba:15:67:c9:11:f2,load:0x2->NXM_OF_ARP_OP[],move:NXM_NX_ARP_SHA[]->NXM_NX_ARP_THA[],load:0xba1567c911f2->NXM_NX_ARP_SHA[],move:NXM_OF_ARP_TPA[]->NXM_NX_REG0[],move:NXM_OF_ARP_SPA[]->NXM_OF_ARP_TPA[],move:NXM_NX_REG0[]->NXM_OF_ARP_SPA[],IN_PORT
 cookie=0x0, duration=49606.132s, table=2, n_packets=0, n_bytes=0, priority=11,arp,metadata=0 actions=drop
 cookie=0x0, duration=49606.132s, table=2, n_packets=0, n_bytes=0, priority=10,arp,reg1=0x10,arp_op=2 actions=set_field:0x1->reg6,resubmit(,3),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.131s, table=2, n_packets=0, n_bytes=0, priority=10,arp,reg1=0x10,arp_op=1 actions=move:NXM_OF_ETH_SRC[]->NXM_OF_ETH_DST[],mod_dl_src:ca:06:cd:a1:7c:47,load:0x2->NXM_OF_ARP_OP[],move:NXM_NX_ARP_SHA[]->NXM_NX_ARP_THA[],load:0xca06cda17c47->NXM_NX_ARP_SHA[],move:NXM_OF_ARP_TPA[]->NXM_NX_REG0[],move:NXM_OF_ARP_SPA[]->NXM_OF_ARP_TPA[],move:NXM_NX_REG0[]->NXM_OF_ARP_SPA[],IN_PORT
 cookie=0x0, duration=49606.131s, table=2, n_packets=170, n_bytes=125360, priority=0 actions=resubmit(,3),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.131s, table=3, n_packets=0, n_bytes=0, priority=10,icmp6,reg1=0x1,ipv6_src=fe80::/10,icmp_type=133 actions=CONTROLLER:65535
 cookie=0x0, duration=49606.131s, table=3, n_packets=0, n_bytes=0, priority=10,icmp6,reg1=0x1,ipv6_src=fe80::/10,icmp_type=135 actions=CONTROLLER:65535
 cookie=0x0, duration=49606.131s, table=3, n_packets=0, n_bytes=0, priority=10,icmp6,reg1=0x10,ipv6_dst=ff02::1:ff00:0/104,icmp_type=135 actions=CONTROLLER:65535
 cookie=0x0, duration=49606.131s, table=3, n_packets=170, n_bytes=125360, priority=0 actions=resubmit(,4),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.115s, table=4, n_packets=0, n_bytes=0, priority=100,icmp,reg1=0x1,nw_dst=10.1.0.1 actions=resubmit(,5),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.120s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=127.0.0.0/8 actions=drop
 cookie=0x0, duration=49606.118s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=172.16.20.4 actions=drop
 cookie=0x0, duration=49606.118s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=172.16.10.101 actions=drop
 cookie=0x0, duration=49606.115s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=192.168.60.19 actions=drop
 cookie=0x0, duration=49606.115s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=192.168.128.1 actions=drop
 cookie=0x0, duration=49606.115s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=10.1.0.1 actions=drop
 cookie=0x0, duration=49606.114s, table=4, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,nw_dst=10.5.0.2 actions=drop
 cookie=0x0, duration=49606.121s, table=4, n_packets=170, n_bytes=125360, priority=0,reg1=0x10 actions=resubmit(,5),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.120s, table=4, n_packets=0, n_bytes=0, priority=0,reg1=0x1 actions=resubmit(,21),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.122s, table=5, n_packets=140, n_bytes=10136, priority=1,in_port="proxy_port" actions=drop
 cookie=0x0, duration=49606.121s, table=5, n_packets=3761, n_bytes=270674, priority=0 actions=resubmit(,10),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=324364.204s, table=10, n_packets=234, n_bytes=234000, priority=15,reg6=0x1 actions=resubmit(,20),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=324364.204s, table=10, n_packets=0, n_bytes=0, priority=12,ip,reg1=0x1,vlan_tci=0x0000/0x1000,nw_dst=10.1.0.1 actions=set_field:ba:15:67:c9:11:f2->eth_dst,output:mtr0
 cookie=0x0, duration=324364.204s, table=10, n_packets=0, n_bytes=0, priority=12,ip,reg1=0x1,vlan_tci=0x1000/0x1000,nw_dst=10.1.0.1 actions=strip_vlan,set_field:ba:15:67:c9:11:f2->eth_dst,output:mtr0
 cookie=0x0, duration=324364.204s, table=10, n_packets=3527, n_bytes=36674, priority=10 actions=resubmit(,11),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.120s, table=11, n_packets=27, n_bytes=1890, priority=0 actions=resubmit(,22),resubmit(,12),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=324364.198s, table=12, n_packets=3527, n_bytes=36674, priority=0 actions=resubmit(,13),set_field:0->reg0,set_field:0->reg3
 cookie=0xfffffffffffffffe, duration=324364.200s, table=13, n_packets=3527, n_bytes=36674, priority=0 actions=resubmit(,14),set_field:0->reg0,set_field:0->reg3
 cookie=0xfffffffffffffffe, duration=324364.196s, table=14, n_packets=3517, n_bytes=26674, priority=0 actions=drop
 cookie=0x0, duration=160642.278s, table=20, n_packets=0, n_bytes=0, priority=12,reg10=0x1 actions=set_field:e6:8f:a2:80:80:80->eth_dst,output:"proxy_port"
 cookie=0x0, duration=324364.201s, table=20, n_packets=0, n_bytes=0, priority=10,reg1=0x1 actions=set_field:ca:06:cd:a1:7c:47->eth_dst,LOCAL
 cookie=0x0, duration=324364.202s, table=20, n_packets=234, n_bytes=234000, priority=0,ip,reg1=0x10,vlan_tci=0x0000/0x1000 actions=output:NXM_NX_REG8[]
 cookie=0x0, duration=324364.202s, table=20, n_packets=0, n_bytes=0, priority=0,ip,reg1=0x10,vlan_tci=0x1000/0x1000 actions=strip_vlan,output:NXM_NX_REG8[]
 cookie=0x0, duration=324364.202s, table=20, n_packets=0, n_bytes=0, priority=0,ipv6,reg1=0x10,vlan_tci=0x0000/0x1000 actions=output:NXM_NX_REG8[]
 cookie=0x0, duration=324364.202s, table=20, n_packets=0, n_bytes=0, priority=0,ipv6,reg1=0x10,vlan_tci=0x1000/0x1000 actions=strip_vlan,output:NXM_NX_REG8[]
 cookie=0x0, duration=49606.120s, table=21, n_packets=0, n_bytes=0, priority=0 actions=resubmit(,5),set_field:0->reg0,set_field:0->reg3
 cookie=0x0, duration=49606.119s, table=22, n_packets=41, n_bytes=2870, priority=0 actions=set_field:0xffffffff->reg10,set_field:0->reg0,set_field:0->reg3
 cookie=0xb, duration=49606.120s, table=201, n_packets=14, n_bytes=980, priority=0 actions=resubmit(,22),resubmit(,202),set_field:0->reg0,set_field:0->reg3
magma@tvm1-agw2:~$ `

**Comment by uri200** [comment]
Hey @arun-magma can you check this is not happening anymore with latest master (f3af5167)

**Comment by arun-magma** [comment]
@uri200 @pshelar : On a Regression environment Verified S8-gtp-u flow is good now with the latest AGW build "1.7.0-1642712894-a6f604dd"
Thanks!

[inbound_roaming_01_220120_142155-1.pcapng.zip](https://github.com/magma/magma/files/7908889/inbound_roaming_01_220120_142155-1.pcapng.zip)


<img width="1688" alt="Screen Shot 2022-01-20 at 2 24 16 PM" src="https://user-images.githubusercontent.com/70725754/150431990-4e5f3a7c-b0ac-4a0a-8ad5-52e82a7d2ad8.png">

**Comment by uri200** [comment]
Thanks @arun-magma for testing it!
