### ISSUE TITLE
Configurations required for executing the TC1x and TC1y , SUPI registration TC in regression SUIT.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11174]
Hi Arun ,

For Executing the SUPI profile support TC in regression below are required steps.

Step 1 : Generate the Public-Key and Private key using the python CLI provided.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/f41ddb2f-6f93-4a02-ac49-3a76637abd00)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/51d5b3c6-a584-4787-aaf9-029388de38c8)

Step 2 : Feed the public-key and private-key from swagger_API

Step3 : In TVM-GUI , need to select the 
            a. SUCI encryption Scheme as Profile-A/Profile-B
            b. Give the respective hn-Public-Key and key-identifiers
            ![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/441a5006-07f1-4553-a6c0-2e1f7256a3d1)
            ![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/f5eab2bc-2c93-4c15-8fe8-facfc819bfde)
             c. Give the respective private-key
              ![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/48fbe8da-4c0a-422f-acf9-ee0ae5db1cc3)

So , here we will require the IMSI and Private-Key also as configurable parameters .

Please do the needful to support these TC to get executed in the Regression.

**Comment by arun-magma** [comment]
Really Thanks for all this Execution summary.
Will check the feasibilities to add below parameters as part of run config and update you soon.
Private key
IMSI

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma ,

With your suggestions I executed TC1x script again and I am seeing the same Registration Reject Issue(configured private key doesn't matching with the private key sending by TVM), can you please look into the issue and resolve it.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/019281c1-532e-4eff-8b5c-dbf382f65f02)

Please find the required logs and pcaps from below
[https://app.zenhub.com/files/170803235/5c6958e0-a058-47cd-b3cd-042c6cd43727/download](https://app.zenhub.com/files/170803235/5c6958e0-a058-47cd-b3cd-042c6cd43727/download)

Please find more details from this zenhub issue(https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/11400)

**Comment by arun-magma** [comment]
@rupa455wavelabs: To help T-shoot this issue we can use a Module Logs In Test run results which shows the Teravm side internal Key computation, Not sure why private key should be used for SUCI Encryption as Public key and Identifier encrypts the MSIN on SUCI, Please review the logic, I will try bring the ref computation flow in this ticket or you may request the designer to add the computation flow diagram for SUCI Prof-A and B. this helps to debug faster.

Please DL Module logs from right most blue icon and you can find the SUCI computation keys as snapped below.

![Screen Shot 2022-02-10 at 11.23.58 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/4b8eba7e-2abd-458d-9dd9-7b844174c151)

![Screen Shot 2022-02-10 at 11.24.30 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/cd8c38b1-0d24-4ab7-a05d-08100da5cbfd)

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma,

As suggested I checked the module logs for the TC1x Testcase and observed that, configured keys are not matching with the keys in module logs, can you please check this issue and unblock us.
![1x_1y.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/2c89fd49-88ec-4aa2-b76c-94b203845df8)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/38d6b895-ab11-4c9b-b49a-59e0c3fe4b98)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/bda5cf5a-fbc4-427d-ad94-9269bfc6e5a1)

**Comment by arun-magma** [comment]
@rupa455wavelabs @Kaleem-Wavelabs : Does Private key used for SUCI(MSIN) concealment ? our understanding is only Public Key should be used & Private key should be preserved for local ref, Like to get the 3gpp SUCI computation formula. Kindly review & explore from your side.

**Comment by Kaleem-Wavelabs** [comment]
@arun-magma 

In SUCI based Registration Request, we are to receive ecc_public_key (Recipient's public key, not part of supi profiles stored in subscriberdb) and public key identifier(pki), which identifies public/private key pair stored in subscriberdb as part of suci profiles.
Subscriberdb uses pki, recipient's key (ue specific) and ciphertext to decrypt the concealed MAC(10 digits).

This we are able to test end-end using test scripts written in python, we can have one call to demo this and also can check why the input recipient key stored in TVM script is not received at AMF.

![image](https://user-images.githubusercontent.com/83354949/154668940-c2029b24-dbe2-452a-830c-829d064613bb.png)

![image](https://user-images.githubusercontent.com/83354949/154669161-d66406ed-399b-46cc-86b7-1465b8f04eb1.png)

cc @rupa455wavelabs

**Comment by arun-magma** [comment]
@Kaleem-Wavelabs : Thanks! , let's sync up next week (Tue Eve PST)
