### ISSUE TITLE
[TVM] Scale Test: observering cause #91 issue with correct APN configuration also while executing scale test with 50 UE and 5 attach rate

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11179]
### Your Environment

- **Version:** - 1.7.0-1642197942-be1cfad0
- **Affected Component:** - Access Gateway
- **Affected Subcomponent:** - AGW service
- **Deployment Environment:** - bare-metal (AGW)

### Describe the Issue
Go to TVM GUI and execute the  "SA_TC51_Scale_mbps_udp" Test scenario with 50 UE and 5 attach rate

**Expected behavior**
5G call flow for 50 UE should be successful and UL/DL traffic should pass without any issues.

**Actaul behavior**
out of 50 Pdu session establishment requests only 22 got Accepted by AMF and for other PDU Sessions observered DNN not supported or DNN not subscriberd issue(cause #91) with correct APN configuration also. 

**Screenshots**
![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/2f49ca5e-658b-4cf1-858a-e98d4cb8a9e1)

**Additional context**
Please check the attached logs and pcaps 
[https://app.zenhub.com/files/170803235/f9e58da7-7dd6-448f-871a-c35d6aaea48e/download](https://app.zenhub.com/files/170803235/f9e58da7-7dd6-448f-871a-c35d6aaea48e/download)

**Comment by Kaleem-Wavelabs** [comment]
As this is tracked using #11174, closing this.
