### ISSUE TITLE
Spirent scale test: UDP/TCP DL traffic is not getting populated in spirent 

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#11183]
Hi  @all,

As per Spirent user guide we have configured TCP, HTTP, UDP traffic, but we are getting only uplink traffic we are not seeing downlink traffic in pcap. I have attached the snapshot of the configurations. Could you please help me to resolve th![ICMP_pcap.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/a010f9d6-c694-4bec-b29c-93dcb689d71d)![TCP_pcap.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/da1f961e-aff4-40f7-ae07-eb16a2466265)![Traffic_1.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/1d83b7b1-0475-41cc-88ef-f629893ae406)![Traffic_2.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/a169965b-9ba5-4618-a6c4-1768a56484b2)e issues.

**Comment by apekshapk** [comment]
Today, tried with setting PDU release time (ms) parameter in spirent tool for UDP/TCP. Not able to see the downlink traffic. PDU release timer is not triggering for specified timer.  
![PDU_release_time.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/8894df46-8347-4544-bd86-819e74c19481)

Tried with SSC mode 3 timer parameter, observing the same issue with downlink traffic![SSC.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/fe9c66a2-3a8d-458f-9a75-b8a4e68ad3a2)

**Comment by rupa455wavelabs** [comment]
Hi @apekshapk , Please close this issue if the issue got resolved.

**Comment by apekshapk** [comment]
Hi @all,

The issue is resolved, we are now able to pump uplink and downlink traffic through Spirent . Attached snapshot for the same.

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/21ff6cc1-8bb6-4c57-8a3d-ed194d7c07c3)
