### ISSUE TITLE
Request to provide direct access to AGW that are allocated for Wavelabs Team.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11209]
Hi Arun,

Please provide direct access to the following AGW machines 

10.22.162.143
10.22.162.144
10.22.162.141- Regression(We will not access this server for our testing activities.)

Please help us by raising a internal ticket to fb-lab .

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please find the User details 

User Details:

User-id 1 : yogesh
User-id 2 : nkalpana
User-id 3 : rupa.seshaveni
User-id 4 : cnaresh
User-id 5 : shanjana.medisetti​

**Comment by rupa455wavelabs** [comment]
Closing the issue, as we got the direct access to AGW nodes that are allocated for wavelabs Team.

**Comment by arun-magma** [comment]
yes @rupa455wavelabs : Direct Access provided as below, Shanjana's Account have some issues , rest all done. Forgot to update earlier.

**Comment by arun-magma** [comment]
IP addresses list which need access:
10.22.162.88 ([http://10.22.162.88/](http://l.facebook.com/l.php?u=http%3A%2F%2F10.22.162.88%2F&h=AT3_U1j1jHd9BcvkYMdbrBy4Jn2Pa1_ux5zPzj3FlIfxI5-J5P1BdCM8f9xnj_rQCUkEFSLG_IlPFQBa7PVMSQki8ny7l7_-hKTCbEBv3gDZd5RRUHhndgHCPAj7VxKfaHXUUgqvwxJ5V6PVCg))
10.22.162.140 ([http://10.22.162.140/](http://l.facebook.com/l.php?u=http%3A%2F%2F10.22.162.140%2F&h=AT146Ml0SEXCVqD9ouufDvpAlVynjPNBavBNj1UR2IOja9OnMVPaJpPLpbCRp3XUHYEN1Rh-5ZaBE_7MRID4Nc0GmMUsqcAmsoEmOppQpJd316vO3hUjJSgKIl2WuuXqV0Dd310u6kx7qzs43Q)) 
10.22.162.143 ([http://10.22.162.143/](http://l.facebook.com/l.php?u=http%3A%2F%2F10.22.162.143%2F&h=AT3dr8QEdXDy1IcKSl7TCaoyrTag16PokORKXpbhgVzTD9RSNwZxN26PvKlz-k9L2sT7N3_M5spOLA0exNNt4PK06vw39o0ByEzbVfgpxfLbxfmMctdq35bBIwO-LXKsq0pgaPwJgiL2-R41sg))
10.22.162.144 ([http://10.22.162.144/](http://l.facebook.com/l.php?u=http%3A%2F%2F10.22.162.144%2F&h=AT1A2W7OAM0uHiv7LL3M5jF7Y6QUpwCft-DRRCNdBShbcS3XNWhgqF0B8LeVehYMs1_dX4nlgjahXyY2lbPmBIG1t1V4dOz9JBtvGlf2hVV1uM4dR3WtBX5xHHVQAJkfaxEVPtuE0HMezCOMiQ))
10.22.162.141 ([http://10.22.162.141/](http://l.facebook.com/l.php?u=http%3A%2F%2F10.22.162.141%2F&h=AT2fb2oO6gXy9rt154Pu2hxtjdR0GOV_dzOfwgjIP2meVdQzXaV6tWeEvtKbtA5wGkLBdtonwcRt6ujKJlO8TyWM0I8QQJG_RjqlgyyxZv6_PSQzYQQSCb7o62Eb0b9hh6cduepx4CPNMxQM-g))

VPN accounts ([vpn.thetiplabs.com](http://l.facebook.com/l.php?u=http%3A%2F%2Fvpn.thetiplabs.com%2F&h=AT2-Sauw-6YGegMnUiqh7BEFEY1velCRZ-Re1JkhF4KQOr_BeN2mC1mbrMX1n7XirpV_kMvi84diAkcvRJMLBgQBvAP3rrKk2NeIbxF4yGnQNe1LanVtihVIcX4l8yepV8WLn7qkwxU1D1dj5g)) of the Wavelabs team members who needs to access to the above mentioned IPs:
User-id 1 : yogesh 
User-id 2 : nkalpana 
User-id 3 : rupa.seshaveni 
User-id 4 : cnaresh 
User-id 5 : shanjana.medisetti​

**Comment by rupa455wavelabs** [comment]
Thanks @arun-magma.
