### ISSUE TITLE
Spurious CI errors on commit in fork

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#11200]
Commit https://github.com/lucasgonze/magma/commit/3fbb60392242e91371eb02e97f3da77ccdaec6bd on my lucasgonze/magma fork of magma/magma has three failures reported by the CI. They may not be relevant to my changes. There should exist documentation. I am filing this ticket to initiate discussion on each of the failures, so that contributors can use this ticket to learn about how to interpret them.

Note that the errors under discussion are all happening on a fork. To see them in context: 
https://github.com/magma/magma/runs/4821395549?check_suite_focus=true

I will post each individual error as a comment, so we can use a thread for each one.

### Your Environment

CI run in GitHub. Running against a personal fork of magma/magma

- **Version:** Jan 18, 2021
- **Affected Component:** all
- **Affected Subcomponent:** all
- **Deployment Environment:** CI

### Describe the Issue

**Expected behavior**
No error in CI

**Screenshots**
See comments

**Comment by lucasgonze** [comment]
path_filter

```
Get current git ref
/usr/bin/git branch --show-current
 fatal: not a git repository (or any of the parent directories): .git
```

![image](https://user-images.githubusercontent.com/111581/150006923-f6237e57-07eb-4f7d-b9b7-f61ba28ba72d.png)

**Comment by lucasgonze** [comment]
nms-build job - run Docker compose
```

 [1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install --mutex network --frozen-lockfile && yarn cache clean' returned a non-zero code: 1
Service 'magmalte' failed to build : Build failed
```

![image](https://user-images.githubusercontent.com/111581/150017571-09ea1e5c-bb88-4bba-a3e7-2a421de511f2.png)

**Comment by lucasgonze** [comment]
nms-workflow / nms-flow-test job (pull_request) 

There are tens of errors on the hardware_id property:

`Cannot get gwCtx.state[gatewayId].device.hardware_id because property hardware_id is missing in undefined [1].`

![image](https://user-images.githubusercontent.com/111581/150018446-7b1fc023-7ac7-4991-9c5e-23aa78c78d38.png)

**Comment by lucasgonze** [comment]
nms-eslint job 

```
Run cd ${MAGMA_ROOT}/nms
yarn install v1.22.17
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

![image](https://user-images.githubusercontent.com/111581/150018789-edf13512-ed33-4e40-93e4-00a109e65b3b.png)

**Comment by lucasgonze** [comment]
> error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

This failure is the one most likely to reflect a genuine error in the commit.

**Comment by quentinDERORY** [comment]
> y changes. There should exist documentation. I am filing this ticket to initiate discussion on each of the failures, so that contributors can use this ticket to learn about how to interpret them.

we should add the checkout module when this is a push to prevent this issue like here https://github.com/magma/magma/blob/eb86cc41f0aa1a97c1102828d75ce86c29939844/.github/workflows/agw-workflow.yml#L31

**Comment by lucasgonze** [comment]
Broke this ticket up into two:

1. https://github.com/magma/magma/issues/11220
2. https://github.com/magma/magma/issues/11221
