### ISSUE TITLE
Request to add TC64 and TC65 in the TVM-GUI. 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11207]
Hi Arun,

Please add TC64 and TC65 in the TeraVM-GUI for Networkinitiated session modification and PCF testing.

Please let me know for any inputs/quires .

**Comment by arun-magma** [comment]
@NeelimaKalpana 
TC64: needs PCF N7 Integration to be completed first with Magma Fed GW.
TC65: If dynamic policy need to be managed with magma there is no need a separate scripts, a basic SUCI or GUTI Registration script is sufficient to validate it.
Need to commands and files used for Policy stub being planned for Dynamic Policy management, this will help to Automate using existing script with mid session Modification through Stub.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please add these two cases in TVM-GUI.

**Comment by NeelimaKalpana** [comment]
Closing this issue will re-open as per requirement
