### ISSUE TITLE
Regrading the subscriber-db lock issue.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11208]
Hi Arun,

We are seeing subscriber-db lock issue very frequently in regression .
We were trying to reproduce the same in our local-setup but it is not happening in all combination we tried.

We are seeing the issue in TC1a , TC6 , TC14 , TC17 , TC43f , TC60 and TC67 randomly.
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/11088

In one of the case we saw this issue in  PDU-Establishment case also.
Where PDU-Session got rejected, Please find the ticket for the same for your reference.
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/11149

Please help us to reproduce the same and identify exact TC/Scenario /Timing to hit the subscriberdb-lock .

Please help us by sharing the csv file for adding 600 subscribers in the NMS-Dash board.

**Comment by arun-magma** [comment]
CC: @vaishaliCI : 600 UE batch addition CSV file parameters need to be validated/ cross verified with Wlabs dev test team.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please enable the grpc prints for subscriber-db also, 
print_grpc_payload: true.

This gives more logs for debugging.

**Comment by arun-magma** [comment]
@NeelimaKalpana : yes On demand, Better we enable GRPC for couple of automated runs and Manual Executions, later we may disable it to keep the log size less.

cc: @vaishaliCI

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Thanks for the Update.
Please give the CVS file for adding 600 UE's

**Comment by arun-magma** [comment]
@NeelimaKalpana : Shared over slack
https://magmacore.slack.com/files/U01E2HGNY93/F02UHJECTSS/sa.csv

**Comment by NeelimaKalpana** [comment]
Thanks Arun.

I missed checking the slack.
Vaishali pointed out about this in todays morning call.
Sorry for the inconvenience.

**Comment by jheidbrink** [comment]
This looks related to #10782 and #11260.

**Comment by moinuddin1980** [comment]
The below PR is under review for the suscriberdb lock issue
https://github.com/magma/magma/pull/11454

**Comment by NeelimaKalpana** [comment]
This issue is tracked under below ticket.
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/11088

Closing this issue as problem is not observed.
