### ISSUE TITLE
Reduce the amount of filters for Sentry

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#11211]
Currently, Sentry needs a lot of server-side filters to avoid spamming the server with too many errors. These filters will soon also be handled on the client side by default (#10276).

The goal of this task is to reduce the amount of filters by finding other ways to handle the corresponding error logs.

**Comment by Neudrino** [comment]
The filter list is available in the [gateway.mcnofig](https://github.com/magma/magma/blob/master/lte/gateway/configs/gateway.mconfig#L142-L154).

**Comment by sebathomas** [comment]
The same default list in [swagger.v1.yml](https://github.com/magma/magma/blob/master/orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml) should be kept in sync.

**Comment by Neudrino** [comment]
The patterns can also be found in [other `swagger.yml` files](https://github.com/magma/magma/blob/master/orc8r/cloud/go/obsidian/swagger/v1/swagger.yml#L9971) and go code. However those files are automatically created by `./build.py --generate` from the `orc8r/cloud/docker` directory.

The file to be changed manually is [swagger.v1.yml](https://github.com/magma/magma/blob/master/orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml). More details are described in [first comment of #10276](https://github.com/magma/magma/pull/10276#discussion_r748615949).
