### ISSUE TITLE
IPv6 lab validation

### ISSUE THREAD

**Issue by pshelar** [magma/magma#11229]
Tracker for IPv6 validation work on Spirent, TVM and Real Devices.

**Comment by sudhikan** [comment]
Looks like the eNB we were using did not like IPv6 GTP tunnels... had to revert to IPv4 transport with IPv4/v6 UE address allocation. 

Need to debug if there is any other configuration missing on the eNB side to get end to end IPv6. 

Spirent emulation testing on the other hand validated:
* IPv4/v4
* IPv6/v4
* IPv4/v6
* IPv6/v6

**Comment by arun-magma** [comment]
Tried in TeraVM side AGW Getting "PDN Connectivity Reject (Network Failure)" for Ipv6 PDN request for apn: "inet6" (configured in NMS with pdn_type-2 & mapped to subs)

[mmelog, syslog and 3gpp pcaps enclosed]
[Ipv6_4G_test.zip](https://github.com/magma/magma/files/7963293/Ipv6_4G_test.zip)


https://docs.google.com/document/d/1ZgowXtn24mHcJp-8QBiLtXahRlra6ADdobgTthGCOPM/edit?usp=sharing
Configs are done almost as per ref config in above doc except S1 (eth1) is on IPv4 only, And all the running AGW configs are pasted below & in this doc @ page-2 & 3 for your verification, Can someone help to check what config is missing or needed in this AGW to avoid PDN Reject?  

<img width="628" alt="Screen Shot 2022-01-29 at 12 13 24 AM" src="https://user-images.githubusercontent.com/70725754/151654123-44aaef71-d3de-4f9f-b3f6-3a61bbb74f4d.png">

<img width="423" alt="Screen Shot 2022-01-29 at 12 16 55 AM" src="https://user-images.githubusercontent.com/70725754/151654358-28c39983-94d5-45ee-b50e-1a25e29ba8e7.png">


In MME logs finding IPv6 allocation is failing
```
000766 Sat Jan 29 00:09:41 2022 7F2AFE4EC700 DEBUG SPGW-A tasks/sgw/sgw_handlers.c        :0272   [999991234632730] Updated eps_bearer_entry_p eps_b_id 5 with SGW S1U teid294225218
000767 Sat Jan 29 00:09:41 2022 7F2AFE4EC700 DEBUG SPGW-A tasks/sgw/pgw_handlers.c        :0102   [999991234632730] Handle s5_create_session_request, for context sgw s11 teid, 294225218EPS bearer id 5
000768 Sat Jan 29 00:09:41 2022 7F2AF8CE1700 ERROR UTIL   lib/mobility_client/MobilityClie:0201     Error in allocating ipv6 address for IMSI <999991234632730> apn <inet6>
000769 Sat Jan 29 00:09:41 2022 7F2AF8CE1700 ERROR UTIL   lib/mobility_client/MobilityClie:0260    Failed to allocate IPv6 PAA for PDN type IPv6 for imsi <999991234632730> and apn <inet6>
000770 Sat Jan 29 00:09:41 2022 7F2AF8CE1700 DEBUG UTIL   lib/mobility_client/MobilityClie:0271   [999991234632730] Sending IP allocation response message with cause: 84
000771 Sat Jan 29 00:09:41 2022 7F2AFE4EC700 DEBUG SPGW-A tasks/sgw/sgw_handlers.c        :1864   [999991234632730] Received ip_allocation_rsp from gRPC task handler
000772 Sat Jan 29 00:09:41 2022 7F2AFE4EC700 DEBUG SPGW-A tasks/sgw/sgw_handlers.c        :1310   [999991234632730] Handle s5_create_session_response, for Context SGW S11 teid, 294225218EPS bearer id 5
```
[3gpp pcap snapshot]
<img width="1417" alt="Screen Shot 2022-01-29 at 12 45 11 AM" src="https://user-images.githubusercontent.com/70725754/151654412-b97f1cbc-13c2-48dd-9afa-618651585c3e.png">
