### ISSUE TITLE
S1AP: Add integ tests for IPv6 datapath with IPv6 UE address

### ISSUE THREAD

**Issue by pshelar** [magma/magma#11227]
This involves Adding S1AP integ tests for UE with IPv6 address.
we need to validate datapath. IPv6 support Non-NAT  datapath only. There is Non-NAT test for IPv4, we could add similar test for IPv6 UE: https://github.com/magma/magma/blob/master/lte/gateway/python/integ_tests/s1aptests/test_attach_detach_non_nat_dp_ul_tcp.py

**Comment by ssanadhya** [comment]
Test scenarios 1:
UE: Ipv6
S1: Ipv4

Test scenarios 2:
UE: Ipv4
S1: Ipv6

Option 1:
Assign Ipv6 addresses in same subnet to `eth2` on Magma dev VM and `eth0` on Magma trfserver VM

Option 2:
Need to add a new Ipv6 interface in Magma dev VM from Vagrantfile, which will be `eth3`
Update the SGI interface from `eth2` to `eth3` in pipelined.yml
-- uplink_eth_port_name
-- nat_iface

**Comment by ssanadhya** [comment]
@pruthvihebbani , can you post an update here so that stale bot knows that there is ongoing activity on this issue?

**Comment by pruthvihebbani** [comment]
1. ipv6 data tests are working with ipv6 only vms. If vms are brought up with ipv4 address and if ipv6 address is manually added on eth2 interface, only ipv4 test data cases work and vice versa. 
2. Brain storming on the changes needed to bring up ipv6 address on a new interface in all the vms: dev, test and trfserver
