### ISSUE TITLE
Concurrent session hold time config for Scale test

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#11231]
@NeelimaKalpana @Kaleem-Wavelabs @rupa455wavelabs 

Hi Kaleem: As per your request we have added hold timer for concurrent session Scale testing, Please make use of it.Config this Timer higher the Ramp time of all configured subscriber. For ex: If 200 UEs scale test with 3sec rate then Ramp up time would be around 66sec, keep the Hold time as 100 sec so that all 200 UEs would stay concurrent for 34 sec. This is ex, you Please keep hold time in sec, Min or Hrs.

![Screen Shot 2022-01-19 at 10.55.01 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/d4620c5c-6509-4203-b527-e6b98616f17f)

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma, we also need PDU session Establishment/Release, UL/DL traffic with timer for the concurrent sessions, can you please do the needful to modify the script. you can check the required details in this zenhub issue #11230, Please let me know if you need more information.

Thanks

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma ,

I have executed the TC's you provided for the hold time, "SA_TC_1_4_Hyper_SUCI_NO_PDU" is working as expected. butI observed an issue "SA_TC_1_4_Hyper_GUTI_NO_PDU" , DeRegistration is triggering immediately, request you to check the issue and resolve it.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/e4c7f4b6-1a34-4b46-a155-969df3f0d6d7)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/08ed051b-14ed-4fdd-a9ba-a93c3c36f2f4)

**Comment by arun-magma** [comment]
Let me check, Fyi Dereg should be triggering after the Hold timer expiry, By default Hold Timer is 30 sec, even if you config <30s scripts take 30s as default.
