### ISSUE TITLE
TVM Scale Test: SUCI/GUTI Concurrent Registration TC Script with longer run

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11230]
Hi @arun-magma,

As we discussed earlier, we need a script for SUCI/GUTI concurrent Registration, PDU Session Establishment/Release, UL/DL traffic,DeRegistration with longer run and we need an option for running traffic for longer run also, can you please create the script for this TC's, It will be very useful to run scaleTests in TVM. please let me know if yo need any information.

**Comment by arun-magma** [comment]
TC51 can be used by scaling the subscriber and also Traffic run for longer period as well, it might help the objective SUCI Reg, PDU Est, Run traffic and DeReg, if not let me know which are the additional parameters in this script would help to achieve desired test flows. 

![Screen Shot 2022-01-24 at 10.36.45 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/007c73ec-5de8-4c9c-95c3-b8f5ae7754c4)

**Comment by arun-magma** [comment]
@rupa455 @rupa455wavelabs : 

On TC51 we need to make sure while going for subs in scale the throughput should be configured less (1mbps)
In addition "Traffic Duration" parameter is being planned to add in RUN CONFIG to allow Reg+PDU+Traffic test for subscribers in scale, here less UL/DL traffic 100bps would run to check traffic continuity, will let you know once its completed.

**Comment by arun-magma** [comment]
Traffic Duration added to run the test longer & with Concurrent sessions, Plz test and reopen if there is a any issues or needs. Thanks!
![Screen Shot 2022-01-27 at 11.01.25 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/7e683f39-7aa7-47ce-af01-a87a13bdf065)
