### ISSUE TITLE
TVM Scale Test: MultiSession_UE_PeriodicRegistration_ConnectedMode is failing 

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11235]
### Your Environment

- **Version:** 1.7.0-1642646508-681d6599
- **Deployment Environment:**  bare-metal (AGW)

### Describe the Issue
**Expected behavior:**
UE_PeriodicRegistration with ConnectedMode should be successful for Multiple PDU Sessions without any issue.

**Actaul Behavior:**
200UE, 12GNB, 4 PDU Sessions, 5 attach rate
UE_PeriodicRegistration with ConnectedMode is failing for Multiple PDU Sessions due to mme service failure.

Please find the required logs and pcaps from the below link:
[https://app.zenhub.com/files/170803235/084b5c32-5b53-4e5e-8857-13b42474d356/download](https://app.zenhub.com/files/170803235/084b5c32-5b53-4e5e-8857-13b42474d356/download)

**Comment by Kaleem-Wavelabs** [comment]
@rupa455wavelabs Please regress this with the latest build

**Comment by rupa455wavelabs** [comment]
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment]
200UE, 12GNB, 4 PDU Sessions, 5 attach rate
UE_PeriodicRegistration with ConnectedMode - Re-Executed the TC with latest magma, I am observing an issue PDU Session Retry and UL/DL Traffic drop, Please check the below logs and pcaps.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/5c30090c-6a83-4a75-bb7d-af22dfe9f705)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/39e2cc56-65ad-4025-aae7-01d57ca812a3)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/41943e18-06a2-4a6b-8b45-cbf925907005)

[https://app.zenhub.com/files/170803235/db049fbd-3356-4311-bd02-dc92daf59cb1/download](https://app.zenhub.com/files/170803235/db049fbd-3356-4311-bd02-dc92daf59cb1/download)

**Comment by panyogesh** [comment]
TVM specific. Kindly check on abot and confirm. Closing this ticket as its setup is not there.
