### ISSUE TITLE
[Regression] Magma services got restarted due to some kernel crash in the regression run

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11248]
Your Environment

- Version: 1.7.0-1642712894-a6f604dd
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: bare-metal (AGW)-VM Based

### Describe the Issue
In regression Run all MME services got restarted because of which TC33 and TC34 got failed 
TC33 Attempt UE Registration when initial context response was not sent to AMF on the previous registration request
TC34 Attempt UE Registration when security mode completion was not sent to AMF in the previous registration attempt
 
**To Reproduce**
Happening in SUIT.
Tring to reproduce in the local setup.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/70d9a48f-5c3f-4f0e-ba36-b939c6af30f3)[https://app.zenhub.com/files/170803235/4cc70902-fdd6-4fe2-9ada-2ed3b1099f13/download](https://app.zenhub.com/files/170803235/4cc70902-fdd6-4fe2-9ada-2ed3b1099f13/download)

**Comment by rupa455wavelabs** [comment]
Hi all, 

Currently I don't have details for this issue. Neelima will share the details as she tried to reproduce this issue.

**Comment by rupa455wavelabs** [comment]
closing the issue for now.
If This issue can be reproduced we can raise a new issue.
