### ISSUE TITLE
Regarding test requirements for Network Initiated Session Modification .  

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11267]
Hi Ganesh and Prabinak,

Please give me inputs to test Network Initiated session modification feature.

What are infrastructure requirements for testing?
What are the triggers/Instances that will trigger session Modification ?

Please share respective Proposal/PR details for reference.

Hi Arun,

Please add the TC64 that is for Network Initiated session modification in TVM-GUI

**Comment by arun-magma** [comment]
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/9957

**Comment by arun-magma** [comment]
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/9952

https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/11207

**Comment by arun-magma** [comment]
TC64 is being designed for PCF and Can be added after the PCF N7 interface  integration? 
Are we planning to use PCF triggered Network Initiated session Modification or Local Magma side Triggered Network Initiated session Modification ? ,

**Comment by arun-magma** [comment]
++ 3 Earlier ZH tasks linked to this requirment

**Comment by VinayKumar1591** [comment]
We are going to initiate pdu session modification though magma stub CLI. so for now we planned to test without N7 interface. please prepare the testcase accordingly

**Comment by NeelimaKalpana** [comment]
Hi Ganesh , 
Please share the current implementation call flow for network initiated session modification.

**Comment by NeelimaKalpana** [comment]
Hi Ganesh,

Please add the current call flow for network initiated session modification for creating Automation cases accordingly. So We will be ready with cases by the time feature is ready.

**Comment by NeelimaKalpana** [comment]
Closing this as received inputs from Dev-Team in 
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/12486
