### ISSUE TITLE
AVP Subscription-Id-Type MSISDN (E164) never sent over Gx Diameter CCR-I

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#11271]
### Your Environment

- **Version:** 1.5 (Ubuntu)
- **Affected Component:** Access Gateway or FeG
- **Affected Subcomponent:** Gx interface
- **Deployment Environment:** e.g. On-prem (orc8r), bare-metal (AGW)

### Describe the Issue

In order to proceed with Protei's OCS and PCRF integration, their platforms need to get the MSISDN (E164) value from the Gx CCR-I message, alongside the IMSI itself. But the MSISDN is not being sent despite the code's suggestion that it should be. No doc, issue, or configuration related to it was found.

**To Reproduce**
1. Enable Gx/Gy relay in a federated network, configuring PCRF/OCS
2. Add an MSISDN to a given subscriber through Magma API
3. Start a session while sniffing Gx interface
4. See no AVP: Subscription-Id containing Subscription-Id-Type = MSIDN in Gx Diameter CCR-I (screenshot below)

**Expected behavior**

Subscription-Id-Type = E164 should be sent when AGW/FeG requests session creation, if the MSISDN exists, towards PCRF. 

**Screenshots**

Only END_USER_IMSI:

![Screen Shot 2022-01-25 at 10 00 47](https://user-images.githubusercontent.com/6054708/150984592-4df9b83a-ec9a-4714-90fe-2facdb8fb41f.png)

MSISDN exists for the subscriber under test:

![Screen Shot 2022-01-25 at 10 07 39](https://user-images.githubusercontent.com/6054708/150984611-16f44f89-6b8c-49ef-95a2-cf99a4ea6af8.png)

**Additional context**
SubscriptionIDType 0 (E164) exists:

https://github.com/magma/magma/blob/d2854460dd226051563665e0255a76ae5336506d/feg/gateway/services/session_proxy/credit_control/definitions.go#L57

The conditional for adding it seems correct:

https://github.com/magma/magma/blob/d2854460dd226051563665e0255a76ae5336506d/feg/gateway/services/session_proxy/credit_control/gx/gx_client.go#L227

But it has never been sent.

**Comment by uri200** [comment]
Hey @crbertoldo  this is a orc8r/subscriberdb issue 

The picture below shows an example of a pcap taken from a setup using a real HSS. In that case Magma AGW will receive MSISDN and it will be used on subsequent messages the core. 

![image](https://user-images.githubusercontent.com/16157139/161865961-883372a4-9b12-485d-87cf-4b7a2c9767df.png)

But when using subscriberDB instead of HSS, MSDIN is not being sent from the Orc8r to the agw.  So AGW never knows that field and sends it empty. So FEG does not send any AVP.

I configured MSDIN on subscriberdb in one of our labs. The code below shows how to print out the content of a subscriber on the AGW. As you can see MSDIN is not a parameter there even it is configured on Orc8r. So orc8r is not sending that information. 

```
magma@tvm1-agw2:/var/core$ subscriber_cli.py
usage: subscriber_cli.py [-h] {add,delete,update,get,list} ...
magma@tvm1-agw2:/var/core$ subscriber_cli.py list
IMSI888881234632894
magma@tvm1-agw2:/var/core$ subscriber_cli.py get IMSI888881234632894
sid {
  id: "888881234632894"
}
lte {
  state: ACTIVE
  auth_key: "\213\257G?/\217\320\224\207\314\313\327\t|hb"
}
network_id {
  id: "terravm1_agw_network"
}
state {
  lte_auth_next_seq: 5
}
sub_profile: "default"
non_3gpp {
  ambr {
    max_bandwidth_ul: 2000000000
    max_bandwidth_dl: 4000000000
  }
  apn_config {
    service_selection: "internet"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
    }
    ambr {
      max_bandwidth_ul: 10000000
      max_bandwidth_dl: 20000000
    }
  }
}
sub_network {
}
```

**Comment by crbertoldo** [comment]
Hi @uri200, thanks a lot. Our plan was to set up a SigScale HSS tomorrow to see it, but you just confirmed. Really appreciated your help here.

**Comment by vances** [comment]
> Our plan was to set up a SigScale HSS tomorrow

SigScale OCS supports S6a interface mainly because Magma previously did not support Gy without also providing Gx and S6a. It is not intended to be a full HSS, there is no "SigScale HSS" product at this time. The ULA does **not** (currently) include MSISDN in `Subscription-Data`.

**Comment by crbertoldo** [comment]
Thanks, @vances. So I'd say the "tiny HSS feature" by the SigScale OCS.
