### ISSUE TITLE
The Orchestrator can be hosted on a private cloud or local machine

### ISSUE THREAD

**Issue by jingc1413** [magma/magma#11278]
eg: https://docs.magmacore.org/docs/basics/introduction
Hi, thanks
   The documentation here only has the operation steps to deploy Orchestrator on aws cloud, I want to deploy Orchestrator locally, how do I do it？

**Comment by jheidbrink** [comment]
Do you have a development setup or a production-ready setup in mind?

For local development, you can run the Orchestrator locally using docker-compose. The [Quick Start Guide](https://docs.magmacore.org/docs/basics/quick_start_guide) describes how to run the access gateway and orchestrator locally and configure them to talk to each other. Does this work for you?

**Comment by jheidbrink** [comment]
Hi @jingc1413, I assigned the ticket to you to express that it's waiting for your input and not otherwise actionable. Feel free to change the assignees again after responding :)

**Comment by qoderwork** [comment]
![QQ图片20220211102123](https://user-images.githubusercontent.com/13563637/153528408-64be03b5-e9c1-47f1-a455-425ba1fa9a35.png)

  thanks your reply
      The [Quick Start Guide](https://docs.magmacore.org/docs/basics/quick_start_guide), NMS setup, but i got this error

**Comment by sebathomas** [comment]
I can confirm I get the same error on branch v1.6. Looking into it.

**Comment by sebathomas** [comment]
I think it might be a problem with the DB dependency versions (similar to #11435 for the current master branch). As a workaround, you can hardcode the exact version of some dependencies in package.json like in this draft:
https://github.com/magma/magma/pull/11525/files

Then you can retry the build:
```
HOST [magma]$ cd nms/packages/magmalte
HOST [magma/nms/packages/magmalte] $ docker-compose down -v
HOST [magma/nms/packages/magmalte] $ docker-compose build magmalte
HOST [magma/nms/packages/magmalte] $ docker-compose up -d
HOST [magma/nms/packages/magmalte] $ ./scripts/dev_setup.sh
```

**Comment by qoderwork** [comment]
> I think it might be a problem with the DB dependency versions (similar to #11435 for the current master branch). As a workaround, you can hardcode the exact version of some dependencies in package.json like in this draft: https://github.com/magma/magma/pull/11525/files
> 
> Then you can retry the build:
> 
> ```
> HOST [magma]$ cd nms/packages/magmalte
> HOST [magma/nms/packages/magmalte] $ docker-compose down -v
> HOST [magma/nms/packages/magmalte] $ docker-compose build magmalte
> HOST [magma/nms/packages/magmalte] $ docker-compose up -d
> HOST [magma/nms/packages/magmalte] $ ./scripts/dev_setup.sh
> ```

thanks, it's work

**Comment by qoderwork** [comment]
![11112](https://user-images.githubusercontent.com/13563637/153565706-28e3fa36-d682-461f-9184-eae2b2bc986f.jpg)
everything's ready， 
  I use this link https://172.16.248.145/ to log nms, 172.16.248.145 is my vm ip.
But the login failed， usename: admin@magma.test    password: password1234
![11114](https://user-images.githubusercontent.com/13563637/153566157-b8edb217-7cc7-460f-bb18-68d6dfad6922.jpg)

magmalte logs output:
![11113](https://user-images.githubusercontent.com/13563637/153565718-7619a526-f9c8-48cd-b9de-43af4a29e94e.jpg)
