### ISSUE TITLE
SA_TC52_Scale_mbps_tcp TC is failing in daily Regression

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11343]
Hi @arun-magma,

TC52 Testcase is failing due to QCI value, can you please change the QCI value to 5 for the IMSI222456000000101 in Regression Suit and test it.

magma@TVM3-SA-regression:~$ subscriber_cli.py get IMSI222456000000101
sid {
  id: "222456000000101"
}
lte {
  state: ACTIVE
  auth_key: "\213\257G?/\217\320\224\207\314\313\327\t|hb"
}
network_id {
  id: "tvm3_sa_agw_network_141"
}
state {
  lte_auth_next_seq: 8216495189712
}
sub_profile: "default"
non_3gpp {
  ambr {
    max_bandwidth_ul: 100000000
    max_bandwidth_dl: 200000000
  }
  apn_config {
    service_selection: "internet"
    qos_profile {
      class_id: 9
      priority_level: 15
    }
    ambr {
      max_bandwidth_ul: 100000000
      max_bandwidth_dl: 200000000
    }
  }
  apn_config {
    service_selection: "internet1"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 6000000
    }
  }
  apn_config {
    service_selection: "internet2"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 2000000
      max_bandwidth_dl: 3000000
    }
  }
  apn_config {
    service_selection: "internet3"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 5000000
    }
  }
  apn_config {
    service_selection: "internet4"
    qos_profile {
      class_id: 5
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 5000000
    }
  }
}

magma@TVM3-SA-regression:~$

**Comment by arun-magma** [comment]
@rupa455 : Q: Whats the need for two QCI-5 PDNs, understood one is needed for IMS signaling, Is there a use case need for Multiple QCI-5 PDNs ? , lets plan & test this QCI based on field use case or if there another reason please provide the info here, Thanks!

And while above Qs is still open we just change as per your above DNN & QCI list for regression.

**Comment by rupa455wavelabs** [comment]
Hi @arun-magma, 
we are trying to execute scaleTest with Multiple PDU Sessions for that we need Multiple QCI-5 PDNs, but for now in the regression AGW VM I am seeing APN configuration of internet class ID as 9 for the IMSI222456000000101.
 apn_config {
service_selection: "internet"
qos_profile {
class_id: 9
priority_level: 15
}

Please change the class ID value to 5.

Thanks

**Comment by rupa455wavelabs** [comment]
I am discussing with developers I will get back to you.

**Comment by arun-magma** [comment]
@rupa455wavelabs: It took a while to update in AGW sub_db. It updated for all subscribers as below to QCI-5 for internet and internet-4
magma@TVM3-SA-regression:~$ subscriber_cli.py get IMSI222456000000101
sid {
  id: "222456000000101"
}
lte {
  state: ACTIVE
  auth_key: "\213\257G?/\217\320\224\207\314\313\327\t|hb"
}
network_id {
  id: "tvm3_sa_agw_network_141"
}
state {
  lte_auth_next_seq: 8216495189734
}
sub_profile: "default"
non_3gpp {
  ambr {
    max_bandwidth_ul: 100000000
    max_bandwidth_dl: 200000000
  }
  apn_config {
    service_selection: "internet"
    qos_profile {
      class_id: 5
      priority_level: 15
    }
    ambr {
      max_bandwidth_ul: 100000000
      max_bandwidth_dl: 200000000
    }
  }
  apn_config {
    service_selection: "internet1"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 6000000
    }
  }
  apn_config {
    service_selection: "internet2"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 2000000
      max_bandwidth_dl: 3000000
    }
  }
  apn_config {
    service_selection: "internet3"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 5000000
    }
  }
  apn_config {
    service_selection: "internet4"
    qos_profile {
      class_id: 5
      priority_level: 15
      preemption_capability: true
      preemption_vulnerability: true
    }
    ambr {
      max_bandwidth_ul: 4000000
      max_bandwidth_dl: 5000000
    }
  }
}

magma@TVM3-SA-regression:~$

**Comment by rupa455wavelabs** [comment]
sorry @arun-magma, Thank you.

**Comment by rupa455wavelabs** [comment]
Hi @all, There is an issue with session modification, even if we change the QCI Value as 5 for the configured IMSI, AMF was not able to update the value, This issue will be fixed by these 2 #PRs #11261 and #11261.

Thanks

**Comment by panyogesh** [comment]
@rupa455wavelabs , @NeelimaKalpana : #11261 Got merged. Can you please re-check the same.

**Comment by NeelimaKalpana** [comment]
TCP Traffic is flowing by updating OVS , where QFI=9 is hardcoded in the switch.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9f6792b7-c1da-405e-8e72-84e90c2b6216)

But observing flow of 50Mbps of TCP-Traffic flowing , because of Hardware support.
Need to retest maximum throughput once Supported virtual hardware 
configurations are upgraded to required configuration.
For now Closing this issue as basic traffic is flowing. 

[https://app.zenhub.com/files/170803235/a55dfbcc-5a7b-4de8-af13-64d7389573d0/download](https://app.zenhub.com/files/170803235/a55dfbcc-5a7b-4de8-af13-64d7389573d0/download)
