### ISSUE TITLE
ARM - Third party packages build issues on aarch64

### ISSUE THREAD

**Issue by m-govind** [magma/magma#11345]
Environment: ARM/Ubuntu/5.4.0-91-generic

- **Version:** -- Master
- **Affected Component: Access Gateway

### Describe the Issue
While building the third party packages using the script in "~/magma/third_party/build/bin", some of them failed.
Please find the script name and corresponding error logs attached.

**Expected behavior**
Generation of debian packages
[third_party_pkg_build_errors.txt](https://github.com/magma/magma/files/7976216/third_party_pkg_build_errors.txt)

**Comment by m-govind** [comment]
Following packages are built successfully:
-----------------------------------------------

2u-thunderx2:~/magma_ci/magma/third_party/build/bin$ ls *.deb

liblfds710_7.1.0-0_aarch64.deb

magma-cpp-redis_4.3.1.1-2_aarch64.deb

magma-libfluid_0.1.0.7-1_aarch64.deb

magma-libtacopie_3.2.0.1-1_aarch64.deb

oai-asn1c_0~20190423+c0~rf12568d6-0_aarch64.deb

oai-nettle_2.5-1_aarch64.deb
prometheus-cpp-dev_1.0.2-d8326b2_aarch64.deb
python3-aioeventlet_0.5.1-2_aarch64.deb
python3-aioh2_0.2.3-1_all.deb
sentry-native_0.4.12-1_aarch64.deb

**Comment by tmdzk** [comment]
Those build scripts are meant to run on amd64, so I'm not surprised a few of them don't work @m-govind. I guess the way forward is to rewrite the missing one for arm. Do you have a list of all the packages that failed? I can have a look

**Comment by m-govind** [comment]
@tmdzk Please see the "[third_party_pkg_build_errors.txt](https://github.com/magma/magma/files/7976216/third_party_pkg_build_errors.txt)" file attached.

**Comment by m-govind** [comment]
This is not a blocker issue as of now.
