### ISSUE TITLE
Real Time Metrics of Data Usage in NMS Dashboard showing wrong values

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11348]
Hi @prabinakpattnaik  and @anusha-konda,

we are observing an issue with Data Usage metrics in NMS Dashboard, Please check the below screenshots and syslog for more info. 

In the real time graph we are observing the data in multiples of 100.(here we send 64 MB data but in this graph it is showing it in 6090.1 MB)
![dishnet.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b0ca2d9f-ec9b-43d1-8716-609aaa975bfd) 

In the Grafana Metrics we are able to see the correct data values.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b7cb5f71-8b45-4ae0-b7c0-89e5bc40df07)

[https://app.zenhub.com/files/170803235/953d573c-2164-40a5-b142-6a3176c5f24a/download](https://app.zenhub.com/files/170803235/953d573c-2164-40a5-b142-6a3176c5f24a/download)

Please let me know if you need more Info.

**Comment by sabithaatla** [comment]
Hi Rupa,

'UE data Usage In ' Grafana and Data Usage graph in subscriber page represents two different units. We should not compare these two values.
Data Usage of subscriber is Throughput calculated for 5min interval of time .You can compare the Throughput In Grafana dashboard and Data usage in subscriber page with 1hr time frame. (i.e; for every 5min ).

And also DataUsage unit is MBs and Throughput in Grafana unit is Bs. Need to calculate accordingly.
Please find the attached SS for the same.

.![GrafanaDashboard.png](https://images.zenhubusercontent.com/61ba0d2dc74757ed74c79377/91298645-74df-4676-a16f-0bd557c808bb)![DataUsage.png](https://images.zenhubusercontent.com/61ba0d2dc74757ed74c79377/a05278f5-86c4-4d00-a0a7-5c9b95303aa0)

**Comment by sabithaatla** [comment]
@rupa455wavelabs  

Please post if you need further clarification on this. If not you can proceed with closure.

**Comment by sabithaatla** [comment]
@rupa455wavelabs 

For Data Usage and Grafana graphs ,average rate of ue_reported_usage is calculated in the latest version where Y-axis represents MBs of data for Data Usage but we could see there are some code diffrences in the earlier versions where different formulae is used for calculation of Data Usage (i;e sum of ue_reported_usage) and "ThroughputIn" in Grafana with average rate in KBs .

Could you please share the versions of Orc8r ,NMS used for your testing to verify these data .

**Comment by anusha-konda** [comment]
@rupa455wavelabs , @NeelimaKalpana , please confirm the orc8r version used for testing. We don't see issue in latest master according to analysis shared by @sabithaatla .

**Comment by mehul-jindal-wavelabs** [comment]
@NeelimaKalpana , as of latest build, the metrics are being updated correctly. Please find the corresponding logs, for 100MB of data sent via UDP. I request you to revalidate and close this issue.

Before Test
![graphana-before-test](https://user-images.githubusercontent.com/88073743/176423807-de6d3818-f908-46b7-8cc2-21d175b68a8e.png)
![subscriber-info-before-test](https://user-images.githubusercontent.com/88073743/176423832-390bce31-32fc-4882-982e-93495e1fb091.png)

After Test
![graphana-after-100mb-udp](https://user-images.githubusercontent.com/88073743/176423793-5f5a5a3c-9500-48ec-af2a-00a26b45bd36.png)
![subscriber-info-after-test](https://user-images.githubusercontent.com/88073743/176425013-fa099725-ff21-4f22-9431-54bce7f41e4c.png)

command used for the test: [iperf.log](https://github.com/magma/magma/files/9009927/iperf.log)
