### ISSUE TITLE
Python Interpreter for Bazel

### ISSUE THREAD

**Issue by nstng** [magma/magma#11346]
This documentation has become obsolete with https://github.com/magma/magma/pull/12325. A pre-build interpreter is used now, i.e., we are more hermetic (no system interpreter) and do not have the disadvantage of a long build time (not fetched and build as dependency).

### Python Interpreter for Bazel

The Python interpreter that is used in Bazel builds can be pre-installed on an environment and configured in Bazel (i.e., as a requirement) or as a Bazel dependency that is downloaded and built. Both approaches have their upsides and downsides.

**Dependency**
* :heavy_check_mark: No system interpreter needed
* :heavy_check_mark: No incompatibility with existing interpreters
* :heavy_check_mark: Installed pip dependencies of the system interpreter do not interfere with Bazel dependencies
* :heavy_check_mark: Reproducible builds
* :x: Long build time for initial builds (~10 minutes on up-to-date laptop; this also holds for non-python targets)
* :x: A little more configuration effort in Bazel

**Requirement**
* :heavy_check_mark: Faster initial builds
* :heavy_check_mark: Quite a bit of knowledge goes into the distributors' package builds (feature flags, optimization flags), so using a downloaded compiled interpreter will likely be faster and have less surprises like missing standard library modules.
* :x: Configuration effort: all dev environments should have the same interpreter
  * Might reduce to 1 though: #11040
* :x: Incompatibility problems (see above)

## Current status (01/2022)

We decided to use the requirement approach for now. The main reason is that the Bazel-migration is an ongoing effort. A lot of initial builds are needed and build times are important.

## How to set up the dependency approach

Python3 binaries usually ship with sqlite3 support for Linux environments. If Python is build by Bazel then libsqlite3-dev needs to be present so that Python is compiled with sqlite3 support.

The following files in the repository need to be added (A) or modified (M).
```
$MAGMA_ROOT
├── bazel
│   ├── external
│   │   └── python_interpreter.BUILD (A)
│   ├── python_dependencies.bzl (M)
│   ├── python_repositories.bzl (A)
│   └── python_toolchain.bzl (M)
└── WORKSPACE.bazel (M)
```

**python_interpreter.BUILD** - Build file for external python interpreter.
```
exports_files(["python_bin"])

filegroup(
    name = "files",
    srcs = glob(["bazel_install/**"], exclude = ["**/* *"]),
    visibility = ["//visibility:public"],
)
```

**python_repositories.bzl** - Python interpreter resource URL and build definition. In this file the python version can be changed.
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

PY_VERSION = "3.8.5"
PY_HASH = "e3003ed57db17e617acb382b0cade29a248c6026b1bd8aad1f976e9af66a83b0"
BUILD_DIR = "/tmp/bazel/external/python_{0}".format(PY_VERSION)

def _patch_cmds():
    return [
        "mkdir -p {0}".format(BUILD_DIR),
        "cp -r * {0}".format(BUILD_DIR),
        "cd {0} && ./configure --prefix={0}/bazel_install".format(BUILD_DIR),
        "cd {0} && make install".format(BUILD_DIR),
        "rm -rf * && mv {0}/* .".format(BUILD_DIR),
        "ln -s bazel_install/bin/python3 python_bin",
    ]
    
def python_repositories():

    http_archive(
        name = "python_interpreter",
        urls = ["https://www.python.org/ftp/python/{0}/Python-{0}.tar.xz".format(PY_VERSION)],
        sha256 = PY_HASH,
        strip_prefix = "Python-{0}".format(PY_VERSION),
        patch_cmds = _patch_cmds(),
        build_file = "//bazel/external:python_interpreter.BUILD",
    )
```

**python_dependencies.bzl** - Use dependency python interpreter for pip installs.
```
# python_interpreter = "python3",
python_interpreter_target = "@python_interpreter//:python_bin",
```

**python_toolchain.bzl** - Set dependency python interpreter as default bazel interpreter. 
```
# interpreter_path = "/usr/bin/python3.8",
files = ["@python_interpreter//:files"],
interpreter = "@python_interpreter//:python_bin",
```

**WORKSPACE.bazel** - Download and set up python interpreter for bazel targets.
```
load("//bazel:python_repositories.bzl", "python_repositories")
python_repositories()
```

**Comment by Neudrino** [comment]
Some more points which should be considered are the following.

#### Dependency

- :x: Even with a Python interpreter as dependency we will likely never get hermetic, as long as we have system dependencies, e.g. BRF from bbc.

#### Requirement

- :heavy_check_mark: Reuse the effort and know-how distribution spend to ship an optimized Python interpreter.
- :heavy_check_mark: System dependencies are easier to integrate.
- :heavy_check_mark: Less maintenance effort of the interpreter.

**Comment by electronjoe** [comment]
Thank you for the detailed GH Issue @nstng! You write excellent GH Issues =D

**Comment by nstng** [comment]
> Thank you for the detailed GH Issue @nstng! You write excellent GH Issues =D

Thank you, it was a team effort :)
