### ISSUE TITLE
Relative python imports and bazel

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#11357]
## Problem
If a python dependency contains a relative module import and is (naively) bazilified the following error occurs:
```ImportError: attempted relative import with no known parent package```

## Solution
Magma wants to adhere to the PEP8 [1] style guide. In this case: prefer absolute imports over relative imports. The change to absolute imports will occur during the bazilification (if necessary).

[1] https://github.com/magma/magma/wiki/Contributing-Code-Conventions#python

**Comment by nstng** [comment]
relative imports were changed during migration
