### ISSUE TITLE
Docusaurus no longer automatically updated from master branch

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#11350]
## Describe the Issue

The [DocuSaurus `next` version](https://docs.magmacore.org/docs/next/basics/introduction.html) used to automatically update from master branch.

Currently there is no update of the DocuSaurus any more!

## Expected behavior

The DocuSaurus `next` version should update upon each merge to master of the Magma repository automatically.

## Additional information

- You might want to look into https://github.com/magma/magma/commit/83d68a2cdfb182eb0804d7fa1d43f158d5b2f5f5. It seems to me, that from this change on the automatic update is broken.
- Related: I suspect, because https://github.com/magma/magma/pull/11198 never got active, https://docs.magmacore.org/docs/next/lte/configure_sentry is leading to a 404 currently.

FYI @jbryce @jaredmullane @themarwhal @electronjoe @hcgatewood

**Comment by electronjoe** [comment]
Thanks for reporting @Neudrino!

**Comment by Neudrino** [comment]
Afaiks the Docusaurus was updated to master branch. If the automatic update works again has to be seen upon the next merge of a `docs` PR. Or maybe @jbryce can comment?

Once confirmation is there of the automatic update working again, we can close this issue.

**Comment by Neudrino** [comment]
Closing this issue, as I can see changes from #11471 in [DocuSaurus](https://docs.magmacore.org/docs/next/howtos/inbound_roaming#inbound-roaming).

**Comment by JpMaxMan** [comment]
In reviewing this a bit more there were some improvements to be made with the base directory and the build command as doc updates could be made and it would not trigger a deploy as it was outside of the base directory.  With these changes it should appropriately trigger a deploy and run a build command to sweep in any new changes as they are made.  If someone on the docs team could monitor this upon future updates - or make an update to verify - that would be greatly appreciated.
