### ISSUE TITLE
[AGW] Incorrect data usage reported in NMS 

### ISSUE THREAD

**Issue by blueCARDSS** [magma/magma#11351]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** : 1.6.1-1636529012-5d886707 
- **Affected Component:** Orchestrator 
- **Affected Subcomponent:** AGW service / APi
- **Deployment Environment:** e.g. local docker-compose (orc8r), bare-metal (AGW),
- 
### Describe the Issue

We are working on building platform for Management of users via orc8r/api . and trying to build as per below guide, 

https://docs.magmacore.org/docs/1.3.x/howtos/ue_metering

during testing we have realise that NMS show incorrect data in graphs . 

<img width="1439" alt="Screenshot 2022-02-01 at 1 04 51 PM" src="https://user-images.githubusercontent.com/92744847/151957477-a5f94780-ecbb-4d28-ac23-7222526aef25.png">

Even if we stop using internet system still produce data in graphs . 

while if we check current usage then its shows correct data . 

<img width="1438" alt="Screenshot 2022-02-01 at 1 08 28 PM" src="https://user-images.githubusercontent.com/92744847/151957966-a5aeaaa9-7641-4419-8753-7afa87085913.png">

**Expected behavior**
System supposed to display correct data consumption in graphs .

**Comment by rupa455wavelabs** [comment]
Hi @blueCARDSS,
In the above shared screenshots I saw the IMSI values are different.
Now I checked it in the NMS dashboard and found that at 3:52 PM IST No data usage was there. I can see the same timings in Data Usage dashboard and Grafana Metrics also, Please find the below screenshots for the same.

It is taking some time to reflect the data values in NMS dashboard
![3842_SUB](https://user-images.githubusercontent.com/84853370/151966340-b4bfd3e7-c934-428b-9679-68c597e0201b.PNG)

![image](https://user-images.githubusercontent.com/84853370/151966665-e469d3fd-a381-4324-b011-0344a2fdf627.png)

**Comment by blueCARDSS** [comment]
what is the usage reporting interval configured?

And how to reduce it to 30 seconds !

**Comment by rupa455wavelabs** [comment]
By default it is 60 seconds, you can change it to 30 seconds using below configurations under /etc/magma/magmad.yml
How long to sleep between statistic collections
sampling_period: 60

metricsd:
log_level: INFO
collect_interval: 60 # How frequently to collect metrics samples in seconds
sync_interval: 60 # How frequently to sync to cloud in seconds
grpc_timeout: 30 # Timeout in seconds
max_grpc_msg_size_mb: 4 # Max message size for gRPC channel in MBs

**Comment by rupa455wavelabs** [comment]
Provided temporary fix to check the correct usage data using prometheus query.
