### ISSUE TITLE
[5G-SA]: Generalizing the behavior for enable5g_features flags in yaml files

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#11363]
enable5g_features: false in yml files to be commented out in all modules.
By default orc8r should drive the behavior.

The behavior can be over-ridden by configurations in local yaml files.

So as part of this task :
1. Comment enable5g_features flag from all yaml files.
2. Ensure orc8r is dictating the behavior.
3. To override local yaml can be used.

**Comment by khansiddiquekc** [comment]
PR #11797 has been raised for this task.
