### ISSUE TITLE
[5G AGW] [Spirent] [Scale test] -DNN not supported issue is triggering while executing scale Test with 250K UDP downlink traffic per UE

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#11429]
-Version:1.7.0-1643771447-32938190**

While performing scale test in Spirent, with 250K UDP Downlink traffic per UE for some IMSI observing DNN not supported, even after the DNN configured same as in NMS board. For this reason we are observing PDU Establishment request failures. Please check the logs attached below.  

(https://app.zenhub.com/files/170803235/d4f5d4b0-af11-4167-83e1-00ac5d9218bc/download)[https://app.zenhub.com/files/170803235/c469421b-85ef-405c-aee8-84d5c40838bc/download]

(https://app.zenhub.com/files/170803235/c469421b-85ef-405c-aee8-84d5c40838bc/download)[https://app.zenhub.com/files/170803235/7ff544e8-bc4f-4a5f-8938-40a0f911a4d6/download]

(https://app.zenhub.com/files/170803235/7ff544e8-bc4f-4a5f-8938-40a0f911a4d6/download)rcontent.com/61bb050c5a4b60928b83af15/3ec93e1b-8593-4bf3-9cd5-ddc57eb43322)

![03-02-22_PDU_Failure.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/dfbc1f98-f880-434f-a525-a647cf5aa8c0)

**Comment by Kaleem-Wavelabs** [comment]
Analysis on the issue as below:
1) When Registration is accepted, AMF sends S6A update location request via GRPC to Subscriberdb 
2) Subscriberdb fetches update location response which includes static APN profile subscribed via S6A and returns this info to AMF
3) During this transaction, if AMF receives PDU session establishment request, it is unable to serve the request as the APN profile is not yet received so marking the PDU session as reject with "5GMM cause: DNN not supported or not subscribed in the slice (91)" . 
4) This is observed randomly while doing scale test with large number of PDU sessions when there is any network delay of milliseconds in receiving location update response from subscriberdb.

Proposal to fix the issue:
1) Would like to introduce one new intermediate PDU state to mark the PDU session request as waiting for APN profile to be received from subscriberdb
2) On receiving APN profile info within the default timer (3sec) expiry, AMF will proceed with accepting the PDU session
3) This procedure will be performed only once for imsi, means AMF will store APN info in smcontext for reference to any new PDU session request
4) On timer(3sec) expiry, we will retry this procedure one more time
5) In failure scenario:
	i) if response is null, reject the PDU session
	ii) if retry also fails, reject the PDU session
	iii) in subscriberdb lock issue, retry the procedure one more time

Please let us know if any comments on this approach.

Thanks
Kaleem

**Comment by rupa455wavelabs** [comment]
Hi @all, With kaleem's latest binary we retested the TC and observed that DNN not supported issue is not triggering. Please check the logs and pcaps for the same.
[https://app.zenhub.com/files/170803235/52502eb4-1443-43f5-8ed4-c8a33712bde9/download](https://app.zenhub.com/files/170803235/52502eb4-1443-43f5-8ed4-c8a33712bde9/download)
