### ISSUE TITLE
Make Bazel build and test a required PR check

### ISSUE THREAD

**Issue by nstng** [magma/magma#11439]
# Make Bazel build and test a required PR check

## Problem

Current efforts of building Magma with Bazel are ongoing and first parts are merged. Changes on bazelfied code can now lead to Bazel build failures if respective build scripts are not changed as well. Main cause might be added classes or dependencies that are not modeled in Bazel.

## Solution

Proposal to set the job "bazel_build_and_test" GitHub Action workflow "Bazel Build & Test" (bazel.yml) as required. A lot of cases where changes in Bazel scripts are missing can be found by the "bazel_build_and_test" job.

Setting the job as required should also support developers in being aware about needed tasks in case Magama uses Bazel as an exclusive build system.

**Comment by ssanadhya** [comment]
@nstng , @themarwhal , as this check is already running in CI, could you please comment on the stability of this workflow? Is there any flakiness in the runs?

**Comment by nstng** [comment]
> @nstng , @themarwhal , as this check is already running in CI, could you please comment on the stability of this workflow? Is there any flakiness in the runs?

Hi, @ssanadhya - @themarwhal is working hard on reviewing the cache handling in this (and related) jobs. We will come back to you when there are news.

**Comment by themarwhal** [comment]
@ssanadhya and @nstng, sorry I missed this last week. The Bazel Build & Test job runs are actually quite stable. https://github.com/magma/magma/actions/workflows/bazel.yml?query=branch%3Amaster . 

The check with stability issues right now is the C/C++ unit test job in the agw-workflow which is already required. (We've since then made it not required due to the cache issue)

**Comment by ssanadhya** [comment]
@themarwhal @nstng , please note that TSC will vote on this proposal today. Could you post the latest status here?

**Comment by nstng** [comment]
@ssanadhya I checked the last couple days - the job looks very stable.

**Comment by Neudrino** [comment]
:heavy_check_mark: Vote happened in [TSC meeting on 2022-03-21](https://wiki.magmacore.org/display/HOME/March+21%2C+2022+Meeting). Proposal was accepted.

**Comment by maxhbr** [comment]
The Workflow is now required
