### ISSUE TITLE
[Flaky_Sanity] Pipelined gets stuck in restart loop randomly after sctpd restart

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#11433]
### Your Environment

- **Version:** Local Development Setup
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Magma MME/SPGW service
- **Deployment Environment:** Vagrant (AGW)

### Setup Details
The S1APTester ([https://github.com/facebookexperimental/S1APTester](https://github.com/facebookexperimental/S1APTester)) was used along with Magma EPC in Vagrant based setup to reproduce the issue.

### Describe the Issue
One issue has been frequently observed in past few weeks when running integ test on master codebase is that the test scripts which trigger sctpd service restart (like s1aptests/test_sctp_shutdown_after_multi_ue_attach.py and s1aptests/test_attach_detach_enb_rlf_initial_ue_msg.py) leads to failure of sanity run. The reason is that after the test case triggers sctpd restart, pipelined gets stuck in restart loop and because of that MME keeps on restarting. So the next test case execution fails in connecting to MME and sanity stops with failure. The issue is more visible with sanity execution which randomly and definitely occurs in few iterations of sanity  but does not happen so easily with individual test case execution or just manual service restart.

The syslog snippet of pipelined error from one of such failures with test case s1aptests/test_sctp_shutdown_after_multi_ue_attach.py on running sanity is as follows:
```
Feb  2 12:51:36 magma-dev-focal pipelined[319296]: Traceback (most recent call last):
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:     return _run_code(code, main_globals, None,
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:     exec(code, run_globals)
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/main.py", line 236, in <module>
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:     main()
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/main.py", line 155, in main
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:     mtr_ip = get_ip_from_if(mtr_interface)
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/common/misc_utils.py", line 156, in get_ip_from_if
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:     return get_if_ip_with_netmask(iface_name, preference)[0]
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/common/misc_utils.py", line 39, in get_if_ip_with_netmask
Feb  2 12:51:36 magma-dev-focal pipelined[319296]:     ip_addresses = netifaces.ifaddresses(interface)
Feb  2 12:51:36 magma-dev-focal pipelined[319296]: ValueError: You must specify a valid interface name.
Feb  2 12:51:37 magma-dev-focal systemd[1]: magma@pipelined.service: Main process exited, code=exited, status=1/FAILURE
```

**To Reproduce**
1) Run the sanity  "make integ_test" multiple times

**Comment by pshelar** [comment]
@VinashakAnkitAman can you post syslog from the test failure.

**Comment by VinashakAnkitAman** [comment]
> @VinashakAnkitAman can you post syslog from the test failure.

@pshelar The logs posted above was for the test case  s1aptests/test_sctp_shutdown_after_multi_ue_attach.py creating issue during sanity run. I am posting here logs for running sanity on today's master codebase with commit id: 61b9c008d4e1464c5b312150a9133ad7b42e2e88. This time same issue was seen after execution of test case "s1aptests/test_attach_detach_enb_rlf_initial_ue_msg.py" during sanity run. The logs below include syslog, pipelined and some other services log as well as s1aptester terminal log for observing failure of sanity:
[sanity_failure.zip](https://github.com/magma/magma/files/8010105/sanity_failure.zip)

Moreover, on today's master I see that individual run of the above test case also results in same issue. However, running the command "sudo service sctpd restart" to manually restart the sctpd service after that is working fine.

**Comment by VinashakAnkitAman** [comment]
Closing the issue after no more instances of the issue observed for more than 10 days after merging pr #11453
