### ISSUE TITLE
5G-Regression: No response from AGW for Service request (TC-7e) 

### ISSUE THREAD

**Issue by Yatheesha-Gubbi** [magma/magma#11473]
Observed in 5G Regression that, AGW is not sending any response to the Service Request. Test case 7e (verify Service Reject cause-#9 after max retry of Registration accept) is failed due to this issue.

Magma build: 1.7.0-1644261919-e40a420b

Expected behaviour:
AGW has to respond Service Reject with the cause 9 "UE identity cannot be derived by the network (9)"

[https://app.zenhub.com/files/170803235/667bc5c8-98ef-4e2f-b763-5017a5e6e1a9/download](https://app.zenhub.com/files/170803235/667bc5c8-98ef-4e2f-b763-5017a5e6e1a9/download)[https://app.zenhub.com/files/170803235/056f130e-71bd-4651-bf21-bd08a519b850/download](https://app.zenhub.com/files/170803235/056f130e-71bd-4651-bf21-bd08a519b850/download)

**Comment by moinuddin1980** [comment]
Following is the analysis:
1. The UE registration procedure was never completed, hence the UE context got removed from AMF after maximum registration accept send attempt.
2. The UE context removal was acknowledged by UE as part of UEContextReleaseCommand and UEContextReleaseComplete.
3. After this there is a InitialUEMessage with a ServiceRequest.
    a. The AMF found there was no UE context and hence created one. But, there was no authentication, security procedure, done with the UE. So the security context was not set under the newly created UE context.
    b. As part of processing the Service Request the AMF found the absence of security context in UE context and aborts the Service Accept.

Below are the queries w.r.t it.
1. Is the script right in sending a InitialUEMessage with a ServiceRequest, when it knows already that the UE context was removed in the earlier step? I mean the UE has to send a InitialUEMessage with Registration Request. 
2. Can the AMF send a Service Reject for a Service Request received, when the security context is not set in AMF for the UE?

**Comment by Yatheesha-Gubbi** [comment]
Verified the test case and it’s working. Issue got resolved, closing the ticket…
