### ISSUE TITLE
New Codeowners for bazel migration

### ISSUE THREAD

**Issue by nstng** [magma/magma#11480]
# New Codeowners group for bazel migration

There are efforts to use Bazel as new build system for Magma (#11283).

## Problem

Changing the build system is a cross cutting concern requiring changes to (nearly) all components of Magma. However, there are no functional changes to the component, but only to the orthogonal subject of component builds. This separation is also clearly represented file-wise.

Being a cross cutting topic, there are often reviews requested, from _a lot_ of teams, which are sometimes (understandably) only reluctantly provided, as this is a new build system and the expertise is with the people involved in the migration in the beginning. This is a serious slow down for the migration.

## Solution

**We propose to temporarily create a new approvers group in order to speed up and increase efficiency of the Bazel migration process.**

In detail:
- The approvers group should be named `approvers-bazel`, i.e. the fully qualified name becoming `@magma/approvers-bazel`.
- We propose the following members to start with:
  - @electronjoe 
  - @themarwhal 
  - @nstng 
  - @LKreutzer 
- This new group should (mainly) gain control over all bazel relevant files, which are detailed in #11479. Roughly that are:
  - Basically all `*.bazel`, `*.bzl` files, which will affect files across multiple directories. 
  - Respective Bazel (only) directories, e.g. `/bazel/`, respective caches.
  - Bazel focused CI, e.g. Bazel build images, Bazel Github Action.

Once the Bazelification effort has stabilized, we plan to move back the ownership of the BUILD files to the wider team. Either giving it back to the subdirectory owner (the current approach) or giving it to `repo-magma-maintain` (all codeowners).

## Non-goals

- Changes to feature providing code or their codeowners.

**Comment by electronjoe** [comment]
Vote occurred on slack at https://magmacore.slack.com/archives/C01Q1T14YJ2/p1644490878655279
