### ISSUE TITLE
make run/restart not effecting(stop/start/restart) SCTPD while stateless is enabled.

### ISSUE THREAD

**Issue by Chandhu-Wavelabs** [magma/magma#11481]
When stateless feature is enable SCTPD is not restarting when we do make restart, while doing make run also SCTP is not stopping/starting.

Is this expected behavior when stateless enabled ?  

When stateless enabled, I have experienced one issue, i.e. REG_ACCEPT was not going as  INITIAL CONTEXT SETUP REQUEST message from NGAP, NGAP was sending to TASK_SCTP but it was not going to SCTP, only it was going as downlink message.

After disabling stateless, i did not see this issue even after stateless enabled again.

**Comment by panyogesh** [comment]
@Chandhu-Wavelabs : If the issue is not consistently reproducible then we can close it. Once its reproduced we can open a new one.
