### ISSUE TITLE
[NMS] Merging Administration Tools into NMS

### ISSUE THREAD

**Issue by iirisgao** [magma/magma#11543]
### Problem
When the user wants to manage users, networks, or view audit logs, they have to switch to the Administration Tools from the NMS. The switch between two portals has a few usability problems:
- Users may not be aware of the Portal Switcher. The Administration Tools is hard to discover.
- Users may be confused about which portal they are at, especially for non-power users.
- Switching back and forth between the two portals is inefficient.

### Design proposal
In this new proposal, we are merging the Administration Tools into the NMS. The users, audit logs, and networks pages will be tabs under a parent page called Administration. It can be accessed through Account --> Administration in the navigation menu.

Here's a link to the mockup: [Figma link](https://www.figma.com/file/Ec5jkliFb4i4OYGdI9AkYk/?node-id=3%3A11)

<img width="1440" alt="Account" src="https://user-images.githubusercontent.com/88680700/156828556-559cf0c1-7305-49b9-bace-587d5c4c7670.png">
<p align = "center"><em>Access point to Administration</em></p>

<img width="1440" alt="Administration" src="https://user-images.githubusercontent.com/88680700/156828609-125c806b-3840-4797-bfff-e839f02ac0ca.png">
<p align = "center"><em>Administration page</em></p>

**Comment by sebathomas** [comment]
@iirisgao Can I get access to the Figma mockup or is there a way to make it public?

**Comment by iirisgao** [comment]
> @iirisgao Can I get access to the Figma mockup or is there a way to make it public?

Hi @sebathomas! The Figma link is shareable only with email addresses. Can you please leave your email here so that I can share it with you? Thanks

**Comment by sebathomas** [comment]
@iirisgao We already got pretty far based on the screenshots (see #12402) but it might be useful to get Figma access in the future. Can you share the mockups with
- sebastian.thomas@tngtech.com
- thomas.schmitt@tngtech.com

Thank you!

**Comment by iirisgao** [comment]
@sebathomas Just sent the invite to your email. Please feel free to let me know if we could provide anything else. Thank you!
