### ISSUE TITLE
grpcpp sync crash with 1.7 and ipv6 enabled

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#11540]
### Your Environment

- **Version:** 1.7.0-1644523313-a451d376
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue
observed on phy-u6
with ipv6 feature enabled from orc8r config. we tried run few automated test cases from spirent side.

UE ipv6 address allocation with GTP transport using ipv6.
just when this test starts we see grpcpp_sync crash is observed on magma system and all magma process gets restarted.

we have attached core included with syslog, mme logs.
[mme.log](https://github.com/magma/magma/files/8052043/mme.log)
[core-1644617057-grpcpp_sync_ser-357646.gz](https://github.com/magma/magma/files/8052044/core-1644617057-grpcpp_sync_ser-357646.gz)
[syslog.zip](https://github.com/magma/magma/files/8052047/syslog.zip)

**Comment by ulaskozat** [comment]
@milapjoshi which version of sctpd is running on the machine?

**Comment by ulaskozat** [comment]
is this a one-off thing or can it be reproduced easily?

**Comment by ulaskozat** [comment]
Looks like assertion is coming from grpc library: https://github.com/grpc/grpc/blob/8de825ba8010cf510733477b615ec69a48f23b2c/src/core/lib/gpr/sync.cc#L105

**Comment by milapjoshi** [comment]
as discussed on slack lets debug this with joint session.
