### ISSUE TITLE
Observing Registration Request Retry while executing scaleTest with stateless feature

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11584]

**Comment by rupa455wavelabs** [comment]
magma build: 1.7.0-1644644622-1975dfbc

SA_TC1_2_3_4_Hyper_Suci - Executed 100 UE, with 5 attach rate(Registration,PDU Session Establishment,UL/DL for 5sec, DeRegistration) - Observed a Retry issue with Registration Request and Registration Accept, mme was restarted in the middle.
Please find the logs and pcaps for more information:
[https://app.zenhub.com/files/170803235/671d1e34-0b6e-4aca-b747-141b381df313/download](https://app.zenhub.com/files/170803235/671d1e34-0b6e-4aca-b747-141b381df313/download)

verdict logs
verification fail:  ((nas5g_received_Registration_Acc_=178)		== (nas5g_sent_Registration_Req_=295))  => False
verification fail:  ((nas5g_received_Sess__Establ__Acc_=39)	>= 100*1*1)  => False
verification fail:  ((nas5g_sent_Sess__Establ__Req_=159)    	== (nas5g_received_Sess__Establ__Acc_=39))  => False
verification fail:  ((as_received_raw_bytes=1710000) 			>= (ue_sent_total_bytes=3900000)-((ue_sent_total_bytes=3900000)*0.01))  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=80)       	>= 100*1*1)  => False
verification fail:  ((nas5g_received_Sess__Rel__Cmd_=30)   	>= 100*1*1)  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=80)       	== (nas5g_received_Sess__Rel__Cmd_=30))  => False
verification fail:  ((nas5g_sent_Dereg__Req_=56)           	>= 100*1)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=25)       	>= 100*1)  => False
verification fail:  ((nas5g_sent_Dereg__Req_=56)           	== (nas5g_received_Dereg__Acc_=25))  => False

**Comment by rupa455wavelabs** [comment]
magma build: 1.7.0-1644644622-1975dfbc

SA_TC1_2_3_4_Hyper_Suci - Executed 100 UE, with 1 attach rate(Registration,PDU Session Establishment,UL/DL for 5sec, DeRegistration) - Observed an issue with PDU Session Retry, due to PDU Session retry issue some of the sessions was not released and deregistered.

Please check the logs and pcaps for more information:
[https://app.zenhub.com/files/170803235/82953867-e6e9-42e2-8f60-833c1458cfa3/download](https://app.zenhub.com/files/170803235/82953867-e6e9-42e2-8f60-833c1458cfa3/download)

Verdict logs:
verification fail:  ((nas5g_received_Registration_Acc_=99)		== (nas5g_sent_Registration_Req_=100))  => False
verification fail:  ((nas5g_received_Registration_Rej_=1) 	== 0)  => False
verification fail:  ((nas5g_received_Sess__Establ__Acc_=86)	>= 100*1*1)  => False
verification fail:  ((nas5g_sent_Sess__Establ__Req_=151)    	== (nas5g_received_Sess__Establ__Acc_=86))  => False
verification fail:  ((as_received_raw_bytes=7688000) 			>= (ue_sent_total_bytes=8601000)-((ue_sent_total_bytes=8601000)*0.01))  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=86)       	>= 100*1*1)  => False
verification fail:  ((nas5g_received_Sess__Rel__Cmd_=86)   	>= 100*1*1)  => False
verification fail:  ((nas5g_sent_Dereg__Req_=86)           	>= 100*1)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=86)       	>= 100*1)  => False

**Comment by Kaleem-Wavelabs** [comment]
@Chandhu-Wavelabs can you please have a look at it and do initial level of analysis.

**Comment by rupa455wavelabs** [comment]
Hi @all, I have re-executed the scale test after flushing redis data and observed that there is no issue with mme crash but I am observing PDU Session Request Retry issue, Please find the attached logs and pcaps for the same.

[https://app.zenhub.com/files/170803235/eb866c93-c2b8-45a2-ade6-2a1949cd4d07/download](https://app.zenhub.com/files/170803235/eb866c93-c2b8-45a2-ade6-2a1949cd4d07/download)

**Comment by Chandhu-Wavelabs** [comment]
Hi @ganeshg87, for 100 UEs only 9UE's PDU sessions are established, for remaining 91 UE's PDU sessions are accepting from AMF/SMF, but the accept message in not going to UE from NGAP, because encoding of PDU session resource request is failing at NGAP. Please check the below logs. 

007182 Thu Feb 17 06:28:51 2022 7F0E008E8700 INFO  NGAP   tasks/ngap/ngap_amf.c           :0084    Received msg from :[TASK_AMF_APP] id:[94] name:[NGAP_PDUSESSION_RESOURCE_SETUP_REQ]
007183 Thu Feb 17 06:28:51 2022 7F0E008E8700 DEBUG NGAP   tasks/ngap/ngap_amf.c           :0094    NGAP ZMQ latency: 70367.
007184 Thu Feb 17 06:28:51 2022 7F0E008E8700 ERROR NGAP   tasks/ngap/ngap_amf_nas_procedur:1239    PDU Session Resource Request IE encode error 
007185 Thu Feb 17 06:28:51 2022 7F0E008E8700 ERROR NGAP   tasks/ngap/ngap_amf_nas_procedur:1322    PDU Session resource setup request stream failed toencode

**Comment by rupa455wavelabs** [comment]
Please find the updated logs and pcaps from below

[https://app.zenhub.com/files/170803235/2dabbb06-dda1-496c-b596-877a9e205ea6/download](https://app.zenhub.com/files/170803235/2dabbb06-dda1-496c-b596-877a9e205ea6/download)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b39df795-b7a2-4d15-9fb0-ec331e7ba99f)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/cb98d2e4-43e1-46e7-8bd9-b480e0b89562)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/840c78ae-0b73-496f-8a64-11a8b9e57937)

**Comment by Chandhu-Wavelabs** [comment]
Hi @all, PDU session establishment request retransmitting due to NGAP encoding failure for "PDU Session Resource Request". This encode fails when qos values are ZERO, Tested using UT code by making all QOS values as ZERO.

PR #11261 will address this issue.
