### ISSUE TITLE
Verify MME lack of support for LOG_WITH_GLOG in .bazelrc

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11586]
Marie and I discussed possible strategy of disabling blanket flag setting in .bazelrc and migrating to per-target Bazel label enablement.

**Comment by themarwhal** [comment]
Update: The problem seems to be that MME uses MLOG even though glog support is not yet verified. The linked PR should hopefully solve our issue.

**Comment by themarwhal** [comment]
@electronjoe I cherry-picked the linked PR onto your big branch to test. This issue can be resolved on the latest master, pretty sure.

**Comment by electronjoe** [comment]
Closed, thanks @themarwhal!
