### ISSUE TITLE
Color of gateway state button on NMS is misleading

### ISSUE THREAD

**Issue by xjtian** [magma/magma#1158]
### Your Environment

- **Version:** 1.0.0
- **Affected Component:** NMS
- **Affected Subcomponent:** Gateways tag on NMS
- **Deployment Environment:** Any

### Describe the Issue

The status button on the gateways page can show up as green even in cases when a gateway isn't healthy. For example, if a gateway's enodeb is connected but doesn't report a connection to the MME, the status will show up as green.

**Expected behavior**

Regardless of RF transmit state, we should show green only if the enodeB is connected *and* MME is connected. We should show red in ay other scenario when RF is enabled.

When RF transmit is disabled, we should show yellow if the enodeB is disconnected or if the MME is disconnected - this indicates a fault with the radio configuration which will not impact the site (since transmit is disabled). If the gateway hasn't checked in in 15+ minutes, we can show a grey status icon.

**Screenshots**

<img width="638" alt="Screen Shot 2019-10-03 at 12 02 59 PM" src="https://user-images.githubusercontent.com/3249794/73779022-f01af900-4740-11ea-8785-e983e344e05d.png">

**Comment by 119Vik** [comment]
Hi @xjtian we observe same issue with MME connection status as well as similar issue with GPS sync statuses.
In the Baicells UI, we could see GPS sync’d with 12-14 satellites visible, but Magma status showed red next to “GPS Synchronization”
<img width="672" alt="Magma" src="https://user-images.githubusercontent.com/372029/74730316-8cb7bd80-524e-11ea-937c-47147bbbb959.png">

**Comment by vladiskuz** [comment]
Is it still valid issue? As I can see there is no page in the master branch as shown above. There is only one status circle.
![image](https://user-images.githubusercontent.com/8994720/76633813-c1bde400-655e-11ea-8928-ed963571dbc3.png)

**Comment by vladiskuz** [comment]
I added fix for this issue in this pull request -- https://github.com/facebookincubator/magma/pull/1398

**Comment by ekowtaylor** [comment]
PR closed
