### ISSUE TITLE
Find method for replacement of compile-time {PACKAGE_BUGREPORT, PACKAGE_NAME, PACKAGE_VERSION}

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11591]
Some of our logging macros in the MME leverage the above compiler defines as part of log line outputs.  This is problematic because in our Bazel build, having one large MME core target of `lte/gateway/c/core:core` (due to cyclic dependencies) - necessitates ~one definition at compile time for these defines (unless one does the awful and uses headers to over-write the defines - which ends up fragile and depends upon header ordering).

We will likely need a new way of expressing this logging output behavior - either splitting these MACROs into per-domain macros with static log line outputs... Or modifying our logging framework (a goal but maybe now is not the time).

I suppose an initial question is whether these log line outputs are even necessary or used functionally today (before we spend effort ensuring their maintenance).  We appear to have ~3 domains differentiated in logging - by differing CMakeLists.txt defines / header file over-writes today in MME.

**Comment by electronjoe** [comment]
Discussion with Alex, Shruti, Ulas and Marie - we may just replace these with constant strings to mark the important fields.

**Comment by electronjoe** [comment]
Regarding `PACKAGE_VERSION` I'm wondering if this is used in some way to bind a build release version into our outputs. I see something over in `.github/workflows/amis-workflow.yml`? [Sourcegraph](https://sourcegraph.com/github.com/magma/magma/-/blob/.github/workflows/amis-workflow.yml?L88:56&subtree=true).

**Comment by nstng** [comment]
Our understanding:
* These values are only set via `CMakeList.txt` s. There are only three cases. `PACKAGE_VERSION` and `PACKAGE_BUGREPORT` seem to be only dummy values, i.e., piratically unused.
* Could be solved by creating packages - should this be tried or do you see the circular dependencies as happening here?

**Comment by themarwhal** [comment]
> Our understanding:
> 
> * These values are only set via `CMakeList.txt` s. There are only three cases. `PACKAGE_VERSION` and `PACKAGE_BUGREPORT` seem to be only dummy values, i.e., piratically unused.
> * Could be solved by creating packages - should this be tried or do you see the circular dependencies as happening here?

Yes I think we were worried about circular dependencies here. (But maybe it might not be a problem, I am not sure)

**Comment by themarwhal** [comment]
I will investigate using per_file_copt for this!
