### ISSUE TITLE
Measuring the running time for individual tests for OAI tests 

### ISSUE THREAD

**Issue by thhung** [magma/magma#11628]
# Measuring the running time for each individual tests

## Problem

Currently, the running time of the unit test from googletest is reported at the module level. Therefore, it is hard to determine which individual test takes a long time to finish. The idea here is that we would like to have a report about the running time of each test-cases.
 
## Solution

Since `googletest` provides the report of the running time of each test case in the XML format. The idea here is to add a script as the post process of `test_oai` target in the Makefile that transforms the information inside the XML report to the desired format.  

Example for the information inside the report:

```
testsuites
@tests:7
@failures:0
@disabled:0
@errors:0
@time:21.164
@timestamp:2022-02-09T14:47:58
@name:AllTests
testsuite
        @name:SPGWAppInjectedStateProcedureTest
        @tests:7
        @failures:0
        @disabled:0
        @errors:0
        @time:21.164
        @timestamp:2022-02-09T14:47:58
        testcase
                  @name:TestDeleteSessionSuccess
                  @status:run
                  @result:completed
                  @time:3.091
                  @timestamp:2022-02-09T14:47:58
                  @classname:SPGWAppInjectedStateProcedureTest`
```

To receive this XML report, we could simply set the GTEST_OUTPUT environment variable or the --gtest_output flag to the string `"xml:path_to_output_file" `or `"xml:output/directory/"`. 

Ref: [Google Test Advanced topics - XML report](https://github.com/google/googletest/blob/main/docs/advanced.md#generating-an-xml-report)

## Non-goals
Nothing.

**Comment by ardzoht** [comment]
Thanks @thhung for providing the examples on how this would look. I think it makes sense to add these as part of an extended part of `make test_oai`, we can add a separate make target (e.g. `make test_oai_runtime` or something similar) cc @ssanadhya thoughts?
