### ISSUE TITLE
Magma cdr availability proposal

### ISSUE THREAD

**Issue by Arsenii-Oganov** [magma/magma#11636]
Currently Magma doesn’t support any kind of CDR files for any scenarios. By implementing this proposal Magma will have full support for standard 3GPP CDRs for inbound roaming scenario and core CDR functionality for outbound roaming scenario. 

The objective is to extend Magma to support Call Data Records (CDR). The charging information is passed through a chain of logical charging functions. At the end of this process, CDR files are generated by the network, which are then transferred to the CDR client/network operator's Billing Domain for the purpose of subscriber billing and/or inter-operator accounting.

Design proposal - https://github.com/magma/magma/pull/11637

**Comment by electronjoe** [comment]
Thank you for authoring the design doc! Below are some of my thoughts.

I'm placing notes on the design proposal here as our process calls for discussion on this GH issue for the merged design proposals / iterations.

> SFTP - Persistent CDR storage

I immediately assumed that this was secure FTP - but then in further reading saw no such evidence.  I was surprised we would be using secure FTP. If we are, an explanation is warranted (and somewhere in the document the term "secure ftp" should exist). If this is not secure FTP, maybe we can chose another name for this block and explain what it is doing.

> covered inside different proposal (Settlement service)

Could we provide a link to the settlement service proposal, if we are going to depend upon its contents for context.

1. The `pull_stats` and `put_CDR` gRPC calls shows a double ended arrow, is this intended to be a bi-directional streaming gRPC? If so I advise against it. If not, can we change the arrow to indicate who is calling into who? Generally I think you are putting the end of the arrow into the server side of the gRPC interface.
2. What are nominal messaging rates for push stats? That is how many connection status changes per second could we be talking about? This may be more related to the other proposal I suppose.  Do these status changes need to be batched based upon those expected rates?
3. For `CDR file structure` are we adhering 100% to some existing standard and not having to invent anything? If so I would simply say "We will store the files per standard XX.YY and no deviation is necessary - relevant details in this context include the separation of CDR by ... .etc" This then requires less review burden on us - if we are not inventing something here.
4. Call Data Records are by nature very sensitive. Do we need elevated privacy / security handling of these in some way (e.g. some sort of encrypted vault?) @hcgatewood any thoughts?
5. With respect to the privacy / security aspect (which is sensitive for this proposal) - where do `SFTP` and `CDR Client` live? How are they authenticated for these gRPC sessions to ensure the sensitive user data is not handed off to the wrong party?
6. How is storage duration of the CDR data managed? Is there regulatory requirement to forget / wipe these records on demand? How would that be accomplished.
7. Given the trend of questions above, this proposal merits a privacy and security section to discuss these aspects of the design.
8. How large are these CDR uploads?
9. Are there any possible bottlenecks of memory, disk use, cpu or network in this chain? If not can that be quickly discussed. If so what future mitigation strategies might we apply?

**Comment by Arsenii-Oganov** [comment]
@electronjoe 

As for SFTP - agreed, changed, new commit pushed.
Reference to issue with settlement proposed added, new commit pushed.

1. Agreed, it was different meaning, diagram updated, new commit pushed.
2. let's discuss this inside original proposal. this topic discussed with Oriol and Amar
3. Absolutely, The content and format of these CDRs are specified per domain/subsystem/service in the related charging specification [3GPP TS 32.251](http://www.3gpp.org/ftp/specs/html-info/32251.htm) for PS domain.
CDR abstract syntax specification and Charging Data Record (CDR) parameters described in the (3GPP TS 32.298)
6. no such requirements. this is design level question and will be decided later and reviewed with codeowner (Oriol).
7. will be done during design phase with Oriol
8. up to 5MB, usually not more than 1 MB
9. So far, we do not see such cases

**Comment by hcgatewood** [comment]
> Call Data Records are by nature very sensitive. Do we need elevated privacy / security handling of these in some way (e.g. some sort of encrypted vault?) @hcgatewood any thoughts?

@electronjoe to answer this specific part -- currently we do not provide any defense-in-depth security measures for data at rest. Probably preferable to kick that consideration to a separate, top-down treatment rather than including it in the scope for this proposal
