### ISSUE TITLE
[mme] Use a macro for OVS table num controlled by MME, instead of 0

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#11643]
We have not done it anywhere in GTP application, have a look at call create_default_flow_mod(). '0' is passed from all GTP apps. I can post other incremental PR for this improvement.

_Originally posted by @pshelar in https://github.com/magma/magma/pull/11639#r808313987_

**Comment by vikramgreddy** [comment]
Fix is available in the PR https://github.com/magma/magma/pull/12204
