### ISSUE TITLE
mme: Convert unit tests to use Google Test framework

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11660]
## Problem
All other C++ unit tests (MME and others) are written using Google Test. The goal is to unify the test framework for all C++ unit tests so that they can be run in the same way.

## Exit Criteria
Migrate the test to be run with gtest OR figure out a strategy on running this test easily with `bazel test //...` command

## Tests that need refactoring
- [x] lte/gateway/c/core/oai/test/mobility_client/test_mobility_client.cpp
- [x] lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_ue_context.c

**Comment by themarwhal** [comment]
Collapsing with https://github.com/magma/magma/issues/11739
