### ISSUE TITLE
Possible Technical Debt found During Bazelification 

### ISSUE THREAD

**Issue by nstng** [magma/magma#11730]
Here we collect possible technical debt that was found during the Bazelification. Issues should be checked with the dev community and either be marked as false-positive or be tracked as a separate issue.

## TODO

* usage of netifaces - this is archived and has currently no maintainer. Some functionality regarding ipv6 **might** be buggy. 
* divergent test folder structure in Python services
  * e.g., `subscriberdb/tests/submodule/aTest.py` vs `magmad/submodule/tests/aTest.py`
* `enodedb` has a lot of back-and-forth dependencies among the main module and submodules
  * Cleaned up dot file based on: `bazel query 'filter("(^[^@])", filter("^(?!.*\.py)", filter("^(?!.*external)", deps(//lte/gateway/python/magma/enodebd:enodebd))))' --output graph`
![enodebd](https://user-images.githubusercontent.com/99820677/155743978-e2a47c5e-d540-4a79-95c2-1e179906e885.svg)
* `lte/gateway/python/magma/enodebd/state_machines/enb_acs_pointer.py` is not used anywhere

## Done

* `lte/gateway/python/magma/enodebd/main.py` uses `unittest.mock` - using mock in production code seems wrong, is this a valid pattern in Python? 
  * https://github.com/magma/magma/pull/11752
* `lte/gateway/python/magma/subscriberdb/store/cached_store.py` is currently only used in tests. Is this dead production code or should the file be moved in a tests folder?
  * https://github.com/magma/magma/pull/11753
* Verify if `lte/gateway/python/magma/pkt_tester` is dead code. See in [slack](https://magmacore.slack.com/archives/C018J8UMGMR/p1652264738399409).

**Comment by themarwhal** [comment]
Thanks for summarizing these findings @nstng !

For `subscriberdb` questions: @ardzoht / @ulaskozat / @mstre123 
For `enodebd`, I agree it seems wrong that mock would be used in production. Do you have any insight into how it might be used? From a quick glance, I did not understand whether the `get_context` function was used.

**Comment by ulaskozat** [comment]
for subscriberdb, indeed cached store is not used. It should be safe to clean up...

**Comment by nstng** [comment]
> Do you have any insight into how it might be used? From a quick glance, I did not understand whether the `get_context` function was used.

@themarwhal I also do not see any usage - and it looks like `lte/gateway/python/magma/enodebd/tests/test_utils/spyne_builder.py` (introduced a couple of days later) provides the same functionality. But it looks to me like `get_context` was not used when it was introduced - i.e., either an artifact or magically used by a framework (that I do not see). We are currently migrating enodedb and can have a more detailed look when we arrive at the tests.

**Comment by themarwhal** [comment]
> > Do you have any insight into how it might be used? From a quick glance, I did not understand whether the `get_context` function was used.
> 
> @themarwhal I also do not see any usage - and it looks like `lte/gateway/python/magma/enodebd/tests/test_utils/spyne_builder.py` (introduced a couple of days later) provides the same functionality. But it looks to me like `get_context` was not used when it was introduced - i.e., either an artifact or magically used by a framework (that I do not see). We are currently migrating enodedb and can have a more detailed look when we arrive at the tests.

Looks good to delete then :D @nstng

**Comment by nstng** [comment]
out dated
