### ISSUE TITLE
Bazel technical debt

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#11743]
### Bazel technical debt

This issue collects technical debts from the ongoing bazelification effort originating from new insights. Changes will be applied according to the scout rule or as dedicated refactoring if appropriate.

## Prioritized backlog

- Refactor WORKSPACE.bazel (has grown really big).
- State of `requirements.in` should be validated vs `setup.py`s.
- Revise visibility of targets. Global visibility vs local visibility. (see https://github.com/magma/magma/issues/12531)
- Use external swagger rule if one is released.
- Use external pytest rule if one is released (also needs to support `bazel coverage`).
- Centralize all bazel (rules, etc) dependencies into one file - having one point where upgrades can be organized or pinned versions can be documented.
- Update Lupa and fakeredis version when python restrictions are resolved.
- Use python rules>=0.8.0 when python3.8 for arm is supported.

## Done

- test_only = 1 -> test_only = True #12473 
- Use `testonly = 1` in test only libraries. #11802
- Fix typo everywhere `legacy_creat_init` #11803
- Inline all lists in BUILD.bazel files (so the buildifier can format them). #11789
- Use pattern for imports: #11778
```
MAGMA_ROOT = "../../../../../"
ORC8R_ROOT = "{}orc8r/gateway/python".format(MAGMA_ROOT)
LTE_ROOT = "{}lte/gateway/python".format(MAGMA_ROOT)
```
- Split py_library from py_binary for each service. I.e. move the .py files (other than main.py) into a separate py_library. (@LKreutzer) https://github.com/magma/magma/pull/12154
- Add [`size`](https://docs.bazel.build/versions/main/be/common-definitions.html#test.size) attribute to python test targets (default is 'medium', with 5 minute timeout). https://github.com/magma/magma/pull/12196
- Figure out why magmad tests do not need imports (swagger generated files needs to be checked). (@LKreutzer) https://github.com/magma/magma/pull/12225

**Comment by nstng** [comment]
outdated - already covered by other issues
