### ISSUE TITLE
[feg] Federation gateway failed to register to orc8r after clean installation due to SSL error

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#11745]
### Your Environment

- **Version:** master (commit # 633fe905d)
- **Affected Component:** Federation gateway
- **Affected Subcomponent:** Magmad service
- **Deployment Environment:** local docker-compose (orc8r, NMS and FeG), Vagrant VM (AGW)

### Describe the Issue

Upon clean installation of Magma services (orc8r, NMS, Feg), Registeration of Feg services to or8r failed due to SSL certificate error (client SSL certificate verify error)

**To Reproduce**
1. Clean everything on docker 
$ docker system prune -af
$ docker images ls
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ docker container ls -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

2. Clone magma source code and checkout to master branch:
$ git clone https://github.com/magma/magma
Cloning into 'magma'...
remote: Enumerating objects: 237251, done.
remote: Total 237251 (delta 0), reused 0 (delta 0), pack-reused 237251
Receiving objects: 100% (237251/237251), 215.39 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (164442/164442), done.
$ cd magma/
~/magma$ git branch -v
* master 633fe905d docs: Add documentation for Domain Proxy (#11673)

3. Build orc8r images and run services:
~/magma/orc8r/cloud/docker$ ./run.py --clear-db
Removing network orc8r_default
WARNING: Network orc8r_default not found.
orc8r_pgdata
~/magma/orc8r/cloud/docker$ ./build.py 
~/magma/orc8r/cloud/docker$ ./run.py 
~/magma/orc8r/cloud/docker$ docker-compose ps
        Name                       Command               State                                                                   Ports                                                                
elasticsearch           /usr/local/bin/docker-entr ...   Up       0.0.0.0:9200->9200/tcp,:::9200->9200/tcp, 0.0.0.0:9300->9300/tcp,:::9300->9300/tcp                                                  
fluentd                 tini -- /bin/entrypoint.sh ...   Exit 1                                                                                                                                       
orc8r_controller_1      /bin/sh -c /usr/local/bin/ ...   Up                                                                                                                                           
orc8r_kibana_1          /usr/local/bin/dumb-init - ...   Up       0.0.0.0:5601->5601/tcp,:::5601->5601/tcp                                                                                            
orc8r_maria_1           docker-entrypoint.sh mysql ...   Up       3306/tcp                                                                                                                            
orc8r_nginx_1           /bin/sh -c /usr/local/bin/ ...   Up       80/tcp, 0.0.0.0:7443->8443/tcp,:::7443->8443/tcp, 0.0.0.0:7444->8444/tcp,:::7444->8444/tcp, 0.0.0.0:9443->9443/tcp,:::9443->9443/tcp
orc8r_postgres_1        docker-entrypoint.sh postg ...   Up       0.0.0.0:5432->5432/tcp,:::5432->5432/tcp                                                                                            
orc8r_postgres_test_1   docker-entrypoint.sh postg ...   Up       0.0.0.0:5433->5432/tcp,:::5433->5432/tcp                                                                                            
orc8r_test_1            /bin/bash -lc echo Hello W ...   Exit 0  

4. Build NMS images and run service:
~/magma/nms/packages/magmalte$ docker-compose build magmalte
~/magma/nms/packages/magmalte$ docker-compose up -d
~/magma/nms/packages/magmalte$ docker-compose ps
         Name                       Command                  State                          Ports                    
magmalte_magmalte_1      docker-entrypoint.sh /usr/ ...   Up (healthy)   0.0.0.0:8081->8081/tcp,:::8081->8081/tcp    
magmalte_nginx-proxy_1   /docker-entrypoint.sh ngin ...   Up             0.0.0.0:443->443/tcp,:::443->443/tcp, 80/tcp
magmalte_postgres_1      docker-entrypoint.sh postgres    Up             5432/tcp

5. Build feg docker images and run services:
~/magma/feg/gateway/docker$ sudo docker-compose build --parallel
~/magma/feg/gateway/docker$ docker-compose up -d
~/magma/feg/gateway/docker$ docker-compose ps
    Name                   Command                  State       Ports
aaa_server      envdir /var/opt/magma/envd ...   Up                  
control_proxy   /bin/bash -c /usr/local/bi ...   Up                  
csfb            envdir /var/opt/magma/envd ...   Up                  
eap_aka         envdir /var/opt/magma/envd ...   Up                  
eap_sim         envdir /var/opt/magma/envd ...   Up                  
eventd          python3.8 -m magma.eventd.main   Up                  
feg_hello       envdir /var/opt/magma/envd ...   Up                  
health          envdir /var/opt/magma/envd ...   Up                  
hss             envdir /var/opt/magma/envd ...   Up                  
magmad          python3.8 -m magma.magmad.main   Up                  
radiusd         envdir /var/opt/magma/envd ...   Up                  
redis           /bin/bash -c /usr/local/bi ...   Up                  
s6a_proxy       envdir /var/opt/magma/envd ...   Up                  
s8_proxy        envdir /var/opt/magma/envd ...   Up                  
session_proxy   envdir /var/opt/magma/envd ...   Up                  
swx_proxy       envdir /var/opt/magma/envd ...   Up                  
td-agent-bit    /bin/bash -c /usr/local/bi ...   Up (healthy)        
test            /bin/bash -c mkdir -p ../. ...   Up 

6. Get gateway hardware ID and add the gateway into orc8r:
~/magma/feg/gateway/docker$ docker exec -it magmad /bin/bash
root@5G-WS1:/#  cd /usr/local/bin/
root@5G-WS1:/usr/local/bin# ./show_gateway_info.py 

Hardware ID
017bc549-e21f-41e2-8da8-4b740b4d78f2

Challenge key
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEY1jhzX34LjaRCSwHV4smqDe61c/AqsNNx4JwuyYesd8wnj4lvvsZWkus48WsvervCUf97ACluPaC8u0FwLezvuW45dQYY4isKJnonGMcwc+Y7+R0Un+vVRWGTO5VPEVX

root@5G-WS1:# ls -l /var/opt/magma/certs/
total 16
-rw-r--r-- 1 root root  908 Feb 20 21:24 gateway.crt
-rw-r--r-- 1 root root  227 Feb 20 21:24 gateway.key
-rw-r--r-- 1 root root  288 Nov  9 19:14 gw_challenge.key
-rw-r--r-- 1 root root 1172 Feb 22 20:06 rootCA.pem

7. Add network and GW using swagger API:
[API-config.txt](https://github.com/magma/magma/files/8118241/API-config.txt)

8. Check gateway magmad services for checkin errors:
root@5G-WS1:/usr/local/bin# ./checkin_cli.py 
1. -- Testing TCP connection to controller.magma.test:7443 -- 
2. -- Testing Certificate -- 
3. -- Testing SSL -- 
4. -- Creating direct cloud checkin -- 
E0222 20:49:45.068158209     372 hpack_parser.cc:1240]       Error parsing metadata: error=invalid value key=content-type value=text/html

> Error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received http2 header with status: 400"
	debug_error_string = "{"created":"@1645562985.068184661","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":123,"grpc_message":"Received http2 header with status: 400","grpc_status":13,"value":"400"}"
>

Suggestions
- Ensure gateway has been registered in the cloud, with correct
  hardware ID and key
    1. Run show_gateway_info.py.
    2. Go to cloud swagger
        - E.g. https://127.0.0.1:9443/swagger/v1/ui/
        - Query the list gateways endpoint
- Ensure cloud's state service is healthy
    - Connect to cloud cluster
    - View cloud pods (kubectl get pods --selector app.kubernetes.io/component=state)
    - Tail cloud logs (stern orc8r-state --since 2m)
    - Pods should indicate minimal restarts, tailed logs should
      be free of crashes or fatal logs
- Check gateway's logs for more information (sudo tail -f /var/log/syslog)

root@5G-WS1:/usr/local/bin# ./health_cli.py 
Health Summary

Gateway <-> Controller connectivity
E0222 20:49:48.320314815     391 hpack_parser.cc:1240]       Error parsing metadata: error=invalid value key=content-type value=text/html
* Testing TCP connection to controller.magma.test:7443 -- 
* Testing Certificate -- 
* Testing SSL -- 
* Creating direct cloud checkin -- 
Error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received http2 header with status: 400"
	debug_error_string = "{"created":"@1645562988.320350152","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":123,"grpc_message":"Received http2 header with status: 400","grpc_status":13,"value":"400"}"

Suggestions
- Ensure gateway has been registered in the cloud, with correct
  hardware ID and key
    1. Run show_gateway_info.py.
    2. Go to cloud swagger
        - E.g. https://127.0.0.1:9443/swagger/v1/ui/
        - Query the list gateways endpoint
- Ensure cloud's state service is healthy
    - Connect to cloud cluster
    - View cloud pods (kubectl get pods --selector app.kubernetes.io/component=state)
    - Tail cloud logs (stern orc8r-state --since 2m)
    - Pods should indicate minimal restarts, tailed logs should
      be free of crashes or fatal logs
- Check gateway's logs for more information (sudo tail -f /var/log/syslog)

E0222 20:49:55.364805669     383 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies

Running on feg_gateway_python:latest, last updated: -
Version: Linux 5G-WS1 5.4.0-99-generic #112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
:
  Service              Status     SubState        Running for  Log level Errors since last restart
- magmalte_nginx-proxy_1 running    running         0:13:26             -          0
- magmalte_magmalte_1  running    running         0:13:26             -          0
- magmalte_postgres_1  running    running         0:13:26             -          0
- aaa_server           running    running         0:00:36             -          0
- eventd               running    running         0:00:36             -          0
- health               running    running         0:00:36             -          0
- eap_sim              running    running         0:00:36             -          0
- redis                running    running         0:00:26             -          0
- csfb                 running    running         0:00:36             -          0
- s8_proxy             running    running         0:00:36             -          0
- s6a_proxy            running    running         0:00:36             -          0
- magmad               running    running         0:00:36             -          0
- swx_proxy            running    running         0:00:36             -          0
- session_proxy        running    running         0:00:36             -          0
- eap_aka              running    running         0:00:36             -          0
- feg_hello            running    running         0:00:36             -          0
- control_proxy        running    running         0:00:26             -          0
- radiusd              running    running         0:00:36             -          0
- test                 running    running         0:00:26             -          0
- hss                  running    running         0:00:36             -          0
- td-agent-bit         running    running         0:00:31             -          0
- orc8r_nginx_1        running    running         0:43:17             -          0
- orc8r_controller_1   running    running         0:43:18             -          0
- orc8r_kibana_1       running    running         0:43:18             -          0
- orc8r_postgres_1     running    running         0:43:19             -          0
- orc8r_postgres_test_1 running    running         0:43:19             -          0
- elasticsearch        running    running         0:43:19             -          0
- orc8r_maria_1        running    running         0:43:18             -          0

Internet health: Up
DNS health: Up

Restart summary:
No restarts since the gateway started

9. Check orc8r and feg logs found below error:
[orc8r-nginx-logs.txt](https://github.com/magma/magma/files/8118345/orc8r-nginx-logs.txt)
[orc8r-controller-logs.txt](https://github.com/magma/magma/files/8118346/orc8r-controller-logs.txt)
[feg-control-proxy-logs.txt](https://github.com/magma/magma/files/8118349/feg-control-proxy-logs.txt)
[feg-magmad-logs.txt](https://github.com/magma/magma/files/8118347/feg-magmad-logs.txt)

nginx_1          | 2022/02/22 20:50:32 [info] 17#17: *201 client SSL certificate verify error: (21:unable to verify the first certificate) while reading client request headers, client: 172.26.0.1, server: ~^(?<srv>.+)-controller.magma.test$, request: "POST /magma.orc8r.SyncRPCService/EstablishSyncRPCStream HTTP/2.0", host: "dispatcher-controller.magma.test"

* Note: Various restart of Feg/orc8r services, rebuild, re-install occured but all trials failed to resolve this issue. *

**Expected behavior**
It is expected that the FEG register using the SSL certificate normally.

**Screenshots**
NA

**Additional context**
I have tried to build bare metal FEG machine however it failed to provsion due to below error:

TASK [apt_cache : Create a local directory for apt cache if not exist] *********
Tuesday 22 February 2022  23:06:18 +0200 (0:00:00.136)       0:00:00.695 ****** 
fatal: [feg_bare]: FAILED! => {"changed": false, "msg": "There was an issue creating /home/vagrant/magma/.cache/apt as requested: [Errno 71] Protocol error: '/home/vagrant/magma/.cache/apt'", "path": "/home/vagrant/magma/.cache/apt/xenial"}

PLAY RECAP *********************************************************************
feg_bare                   : ok=2    changed=1    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   

Tuesday 22 February 2022  23:06:18 +0200 (0:00:00.076)       0:00:00.771 ******  
Gathering Facts --------------------------------------------------------- 0.44s
apt_cache : Delete /var/cache/apt/archives if exists -------------------- 0.14s
apt_cache : Create a local directory for apt cache if not exist --------- 0.08s
distro_snapshot : Check existence of  ----------------------------------- 0.01s
distro_snapshot : Exit if missing or invalid configured archive --------- 0.01s
distro_snapshot : Edit /etc/apt/sources.list to only use snapshot ------- 0.01s
distro_snapshot : Upload and unpack archive ----------------------------- 0.01s
distro_snapshot : Add archive gpg key ----------------------------------- 0.01s
distro_snapshot : Create destination to unpack archive ------------------ 0.01s
apt_cache : Check if role variables are defined ------------------------- 0.01s
gateway_dev : Check if role variables are defined ----------------------- 0.01s
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by MAAHamid** [comment]
Hey @uri200 would you kindly help to check or dispatch this issue?

**Comment by uri200** [comment]
Hey @MAAHamid , per what I see you are running all components of magma in your own laptop. We have some fab scripts that configure orc8r to register the gateways. Check it out here please

https://docs.magmacore.org/docs/next/feg/s1ap_federated_tests#s1ap-federated-integration-tests

Note that to run FEG locally you need to go to the integ_test docker  folder described on that document.

**Comment by uri200** [comment]
Note we are changing this on master. Now FEG will be run inside Magma Vagrant VM.

Reason is docker on MAC doesn't support host network and that limit us some testing capabilities.  Moving Feg to the VM fixes that
