### ISSUE TITLE
Request to trigger 2 different regressions runs.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11784]
Hi Arun,

This is a request to arrange two different regression runs.

1. Basic MVP-Features with stateless feature disable.
2. Current regression with all Merged cases . We need to have stateless feature enabled in this regression.

Please find below link with list of all MVP-TCs.
[https://app.zenhub.com/files/170803235/7448416f-8dd5-475a-8478-f07c146a0d53/download](https://app.zenhub.com/files/170803235/7448416f-8dd5-475a-8478-f07c146a0d53/download)

Please let me know for any inputs if required.

Thanks and Regards,
Neelima.

**Comment by parthiban337** [comment]
Hi Arun,
Request your help in setting up these two sets of daily regression runs... 
1) Basic MVP-Features with the stateless feature disabled. ==> you can name this run as Rel 1.7 daily regression as well. we want to see all green for the basic MVP test cases to do a cut-off for release. this is for the 5G SA alpha release as part of the main 1.7 release.

**Comment by arun-magma** [comment]
Hi @parthiban337: 

We are planning to enable stateless in separate new AGW and run all Regression cases, will Likely open a new Tab in the same 5G Regression sheet & have Stateless Results recorded over there on daily basis. working on this in Top Priority.
CC: @vaishaliCI

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Thanks for the information .
