### ISSUE TITLE
Request to add configurable throughput support for Multiple PDU-Session cases.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11787]
Hi Arun,

As discussed over a call, please provide a TC with configurable throughput support for Multiple PDU-Session cases.

For supporting this we should have each APN-AMBR with UL/DL upto 450 Mbps support.

And while sending throughput we should able to send traffic up to 400 Mbps per session or sum of 4 sessions throughput should be  up to 400 Mbps . 

Here are few example .
In all the cases APN-AMBR will be configured according to my throughput requirement. Here I may maintain it as 400Mbps per APN UL/DL

Case 1 : Session1 : 100 Mbps UL/DL
             Session2 : 100 Mbps UL/DL
             Session3 : 100 Mbps UL/DL
             Session4 : 100 Mbps UL/DL

Case 2 : Session1 : 200 Mbps UL/DL
             Session2 : 100 Mbps UL/DL
             Session3 : 50 Mbps UL/DL
             Session4 : 50 Mbps UL/DL

Case 3 : Session1 : 400 Mbps UL/DL
             Session2 : 1 Kbps UL/DL
             Session3 : 1 Kbps UL/DL
             Session4 : 1 Kbps UL/DL

Case 4 : For Multiple session and Multi UEs
     
            UE1 till UE 100 : 3 Mbps per UE
            UE101 till UE200 : 1 Mbps per UE 

Above are few example , and please arrange the TC for Multiple users also.

Please let me know for any clarity if required.

**Comment by arun-magma** [comment]
@NeelimaKalpana : Added scripts for Multi PDN Throughput with configurable Tput values, Kindly start your validations.
SA_TC2act_Verify_Max_no_of_PDU_session_tcp_tput
SA_TC2acu_Verify_Max_no_of_PDU_session_udp_tput

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Thank you for arranging the scripts . I will validate and update the results.

**Comment by NeelimaKalpana** [comment]
Hi Arun,

During some debugging of scaling scenarios with multisession notice that all AGW-VMs are running with single core CPUs.

But to have better throughput and scaling support we should have 4 Core CPUs.

Please find below output for your reference:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/d92e95a7-fdd1-4987-aa15-48a0a60201fe)


I just wanted to share these observations with you.
If possible can we plan for configuring 4-Core CPU in any one AGW VM.

**Comment by arun-magma** [comment]
@NeelimaKalpana
AGWs of Regression (141) and Dev (144, 143) upgraded to below config, Please continue Scale & Capacity test & let us know how is the performance after this upgrade.
cc: @vaishaliCI

[Current HW Config]
CPU: 4 vCPUs
Memory: 12 GB
Hard disk: 60 GB

**Comment by arun-magma** [comment]
@NeelimaKalpana 
on TC2acu, TC2act, TC51 & 52  added Configurable UL and DL Throughput values for variable rate testing in Multi PDN, Kindly make use of these parameters for diff Tput test scenarios.

**Comment by NeelimaKalpana** [comment]
Support is given so closing the issue
