### ISSUE TITLE
Explore failing //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11785]
Aside from not using Google Test (conversion is GH Issue #11660), this unit test appears to be failing in Bazel test with output:

```
1 exec ${PAGER:-/usr/bin/less} "$0" || exit 1                                      
   2 Executing tests from //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test
   3 -----------------------------------------------------------------------------    
   4 Allocating IP address...                                                         
   5 GetIPv4AddressForSubscriber fails with code 14, msg: failed to connect to all addresses
   6 get_ipv4_address_for_subscriber error 14 for sid 0002                            
   7 [libprotobuf FATAL external/protobuf/src/google/protobuf/repeated_field.h:1733] CHECK failed: (index) < (current_size_):·
   8 terminate called after throwing an instance of 'google::protobuf::FatalException'
   9   what():  CHECK failed: (index) < (current_size_):·    
```

It is not clear to me that this unit test is executing in our present `make test_oai` regime?

## Reproduction

- If you have access to GitHub Codespaces
- Go over to my [Bazel prototype branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase) (~4 PRs on master today)
- Click on the Green colored `Code` drop down button
- Select the `Codespaces` toggle
- Select `New Codespace` and when asked select 16 core (why not!)
- This will spin up a GitHub codespace that contains my branch
- Once the codespace is up (vs code in browswer) in the terminal window type `bazel test //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test --test_output=errors` and hit enter. This triggers a bazel build of all necessary components to run the mobility_client:mobility_client_test, then runs the test

**Comment by themarwhal** [comment]
@electronjoe, @ardzoht 

From what I can see, this test is not being executed. It's missing the `add_test` command in the cmake config
https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt#L10-L19

This diff gives the same error for `make test_oai` 
```bash
diff --git a/lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt b/lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt
index b1b5ca977..819b1bb26 100644
--- a/lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt
+++ b/lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt
@@ -15,5 +15,4 @@ target_link_libraries(mobility_client_test
     LIB_MOBILITY_CLIENT protobuf grpc++ dl stdc++ m
     )
 
-# TODO add support for integration tests
-# add_test(test_rpc_client_integration rpc_client_test)
+add_test(test_mobility_client mobility_client_test)
```

make test_oai output
```
-- Build files have been written to: /workspaces/magma/build/c/core/oai
[6/8] Performing build step for 'MagmaCore'
[1/2] Building CXX object test/mobility_client/CMakeFiles/mobility_client_test.dir/test_mobility_client.cpp.o
[2/2] Linking CXX executable test/mobility_client/mobility_client_test
[8/8] Completed 'MagmaCore'
cd  /workspaces/magma/build/c/core/oai && ctest --output-on-failure -R  ".*"
Test project /workspaces/magma/build/c/core/oai
      Start  1: test_mobility_client
 1/15 Test  #1: test_mobility_client .............Child aborted***Exception:   0.42 sec
[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1728] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
```

**Comment by themarwhal** [comment]
Closed by removing the unit test: https://github.com/magma/magma/pull/11837
