### ISSUE TITLE
[Dev Tools] Moving S1APTester repository under Magma organization

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#11794]
# Moving S1APTester repository under Magma organization

## Problem

S1APTester is used as the UE and eNB emulator for LTE integration tests of Magma Access Gateway (AGW). Currently, it resides in a separate repository https://github.com/facebookexperimental/S1APTester, under `facebookexperimental` organization. Since the development of this tool happens primarily in the context of Magma AGW, we can unify the community by moving it under the `magma` organization.

## Solution

The goal of this proposal is to migrate S1APTester project repository from `facebookexperimental` GitHub organization to `magma` GitHub organization. To this end, we need to do the following:

- Code freeze on original repository: Announce to the code-owners
- Duplicate code to new repository under https://github.com/magma 
- Change the scripts under https://github.com/magma/magma/tree/master/lte/gateway/deploy/roles/magma_test/files to point to the new repository URL
- Deprecate the old repository under https://github.com/facebookexperimental/S1APTester

**Comment by talkhasib** [comment]
Would be great to have this done before 1.7 is released. Yes, the move does not affect production deployments. But, having it in 1.7 might help us accelerate depreciation of the old repo.

**Comment by sudhikan** [comment]
This work will enable a larger testing effort to facilitate Magma testing via open source tools. As part of this initiative, the community will be in a position to write additional tests and maintain existing test code. Additionally, other open source tools like srsRAN and ueRANSIM can also be developed with to make Magma testing robust.

**Comment by ssanadhya** [comment]
Based on the discussion in today's TSC meeting, this proposal has been accepted. I will work with the administrators of https://github.com/facebookexperimental/S1APTester to initiate the migration. cc: @talkhasib @sudhikan

**Comment by VinashakAnkitAman** [comment]
Hi @ssanadhya I think this activity will be very helpful going forward, in maintaing the S1APTester codebase in a better way. Moreover it will remove some unwanted issues of missing updated S1APTester codebase during provision. I have a small query on this activity. I see some open PRs are still there in the S1APTester repo under facebookexperimental. How are we planning to migrate those PRs to the integrated magma repo?

**Comment by ssanadhya** [comment]
> Hi @ssanadhya I think this activity will be very helpful going forward, in maintaing the S1APTester codebase in a better way. Moreover it will remove some unwanted issues of missing updated S1APTester codebase during provision. I have a small query on this activity. I see some open PRs are still there in the S1APTester repo under facebookexperimental. How are we planning to migrate those PRs to the integrated magma repo?

@VinashakAnkitAman , good point! When repository ownership is transferred from one organization to another, all open issues, PRs and commit history are preserved, as described [here](https://docs.github.com/en/enterprise-server@3.3/repositories/creating-and-managing-repositories/transferring-a-repository).

**Comment by ssanadhya** [comment]
Closed with https://github.com/magma/magma/pull/12091
