### ISSUE TITLE
[AMF]: Throughput Characterization on 5G Sa

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#11793]
Attaching the sheet for throughput characterization on Magma 5G SA[https://app.zenhub.com/files/170803235/c523cacc-598d-4ec5-af62-c617a9df9e69/download](https://app.zenhub.com/files/170803235/c523cacc-598d-4ec5-af62-c617a9df9e69/download)

**Comment by NeelimaKalpana** [comment]
Hi Yogesh 

Please find the attachment with update data of throughput observations.

So far I tested the following cases and captured every observations.

1. UDP traffic up to  200 UE by increasing the UE's step by step.
2. UDP traffic with 1 UE multisession(4 and 2 sessions) by pumping different data rates.
3. TCP sing UE Single Session up to 240 Mbps , by increasing throughput step by step.

This doc is also having Observation with Spirent setup.

I need to test below cases w.r.t TCP traffic characterization 

1. TCP traffic with multi UEs
2. TCP traffic with Multisession.
https://wavelabstechnologies-my.sharepoint.com/:x:/g/personal/neelima_kalpana_wavelabs_ai/Ee6sUlT7jyxBnR1L3jMJzhABtuR2vYHXW8e8uBd4ZfC1Dg?e=S8aqXg

Yogesh and Prabinak please let me know if I need to test more cases to benchmark throughput .

**Comment by NeelimaKalpana** [comment]
Closing the issue as Throughput is characterized for 1.7 release.
