### ISSUE TITLE
Benchmark build time impact of build-all agw job with Bazel changes

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#11835]
My current thinking is that with https://github.com/magma/magma/pull/10590 and https://github.com/magma/magma/pull/10544 , the agw build job and lte-integ-test job run times should not be impacted that greatly. 

This issue tracks the work of verifying this change.

**Comment by themarwhal** [comment]
@LKreutzer I think you're doing some of this already with the cache benchmarking, feel free to close this issue out or take ownership of this. :)

**Comment by LKreutzer** [comment]
> @LKreutzer I think you're doing some of this already with the cache benchmarking, feel free to close this issue out or take ownership of this. :)

Current work for https://github.com/magma/magma/issues/12458 is CI focused - primary focus are the "bazel build & test" and "LTE integ test" workflows - thus there is certainly overlap with this. Will keep this open for now.

**Comment by LKreutzer** [comment]
"Analysis of bazel vs. Make runtimes" #13246 in CI and locally
