### ISSUE TITLE
Circle CI always failing

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#11840]
### Describe the Issue

There is a Circle CI job in the Github actions which always fails on every PR. It also always fails on master.

![grafik](https://user-images.githubusercontent.com/13189449/156012678-3f224e31-1f8e-4642-a4f8-533827e151fd.png)

https://app.circleci.com/pipelines/github/magma/magma?branch=master&filter=all

The job is failing due to a missing Circle CI configuration.
![grafik](https://user-images.githubusercontent.com/13189449/156013049-40031748-ed87-470e-b882-2511074da7bf.png)

### Suggested Solution

An always failing check is contra-productive in the CI. Thus I would suggest to remove the always failing Circle CI jobs as checks from Github.
Ideally one would not only silence the back channel, but also remove the (webhook) trigger for the respective jobs.

If this job is required later, I still would remove it now and re-add it, when it is fixed.

### Additional Context

The suggested actions required admin-permission on Github.

@magma/approvers-ci

**Comment by voisey** [comment]
@Neudrino I believe this has now been removed and so this issue can be closed?

**Comment by Neudrino** [comment]
One might want to clean this up for older releases, but the CI for those is unmaintained anyway.
