### ISSUE TITLE
[v1.7] Ansible provisioning of gateway VM fails when using branch v1.7 

### ISSUE THREAD

**Issue by Milind-Blaze** [magma/magma#11854]
- **Version:** v1.7
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Ansible
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

__Host environment__: Ubuntu 20.04

Provisioning of magma and magma_test VMs fail (with errors shown in the Issue Screenshots section below). This is an issue only with the v1.7 branch. It is possible to provision both VMs using the master (commit b3128d7d4c8227f74c7584acdb4aadec40fa48c5) and v1.6 branches. The VMs are still accessible using

```
HOST [magma/lte/gateway]$ vagrant ssh magma
```
```
HOST [magma/lte/gateway]$ vagrant ssh magma_test
```
The issue is explained further below with screenshots.

### Issue screenshots

- This is the output that ```vagrant up magma``` terminates with 

![magma_vm_failure](https://user-images.githubusercontent.com/25522467/156101566-3fa89b55-fa58-4932-b1dc-489ec8462dd7.png)

- SSHing into the magma VM and running ```sudo apt update``` produces

![magma_sudo_apt_update](https://user-images.githubusercontent.com/25522467/156102316-7af620cc-6c9e-4e07-84dc-df34827d0e8e.png)

- This is the output that ```vagrant up magma_test``` terminates with

![second_term_failure](https://user-images.githubusercontent.com/25522467/156102067-ab0131f9-3e07-4a2e-a64c-c42f4e5a0054.png)

This termination is after a roughly 10 minute pause.

- SSHing into the magma_test VM and running ```sudo apt update``` produces 

![test_sudo_apt_update](https://user-images.githubusercontent.com/25522467/156102567-3e96994c-d6fc-4f17-a7af-1f31f67171ea.png)

**To Reproduce**
1. Follow the [Prerequisites page](https://docs.magmacore.org/docs/basics/prerequisites) to set up your environment
2. Checkout the v1.7 branch using ```git checkout v1.7```
3. Navigate to __magma/lte/gateway__ 
4. Run ```vagrant up magma```
5. Open another terminal at the same path and run ```vagrant up magma_test```
6. Observe errors

**Expected behavior**
Expected behavior is the success of creation and provisioning of both VMs terminating in 

- below output, shown for the same steps carried out in the __master__ branch for __magma VM__:  
![master_magma_success_provision](https://user-images.githubusercontent.com/25522467/156103746-7f2c6f59-a46a-44f1-8daf-1f62e13ba3e1.png)

- below output, shown for the same steps carried out in the __master__ branch for __magma_test VM__:  
![test_master_provisioning](https://user-images.githubusercontent.com/25522467/156103860-ab235222-6184-4ba1-91bf-abd60fc7bd8e.png)

__Note__: Above two screenshots are for the __master__ branch to indicate that this is the expected output.

**Similar Issues**

- Issue [#7910](https://github.com/magma/magma/issues/7910)
- Issue [#8139](https://github.com/magma/magma/issues/8139)

**A workaround**

Based on the discussion [here](https://github.com/fluent/fluent-bit/issues/4180), I tried (for the __v1.7 branch__)

```
HOST [magma/lte/gateway]$ vagrant ssh magma
vagrant@magma-dev-focal:~$ sudo apt-get install ca-certificates
vagrant@magma-dev-focal:~$ sudo apt update
```
which produces
![installing_ca_certs](https://user-images.githubusercontent.com/25522467/156104952-21d223c0-76f0-4d1c-b831-2c12b6f41706.png)

Then, exiting the VM using ```exit``` and running ```vagrant provision magma``` finishes successfully with the below output

![ansible_provisioning_gateway_v1 7_after_ca_cert](https://user-images.githubusercontent.com/25522467/156105171-c0b1a63e-2386-4069-876b-8bfe8488ac2c.png)

However, I am not sure how to translate this into a fix.

**Additional context**

Before switching to the v1.7 branch

- Had a running orc8r (localhost) and AGW (Vagrant) setup with the master branch
- Shutdown orc8r using ```docker-compose down``` and ```docker-compose down --remove-orphans```
- Shutdown AGW setup by 1) running ```vagrant halt magma``` and ```vagrant destroy magma``` and 2) removing the machines from VirtualBox
- It was after this that I switched to the v1.7 branch

**Comment by Neudrino** [comment]
Might be related to https://github.com/magma/magma/issues/4958.

**Comment by uri200** [comment]
As of today 1.7 has been merged with master, but is yet not official.

**Comment by Milind-Blaze** [comment]
Hi, after [this commit](https://github.com/magma/magma/commit/2199f6f6971db5d1622ba7474197b644a5a1a0fd), I was able to checkout v1.7 and run

- ```HOST [magma/lte/gateway]$ vagrant up magma``` successful with the following output

![v1 7_gateway_ansible_success](https://user-images.githubusercontent.com/25522467/156906524-4270791a-cb3d-41c1-8d51-dc2b6aa60819.png)

- ```HOST [magma/lte/gateway]$ vagrant up magma_test``` successfully ends with 
![v1 7_magma_test_success](https://user-images.githubusercontent.com/25522467/156906588-3b983f85-9b19-4934-bd23-02f2c5a5a88d.png)

This is the expected output. Therefore closing the issue. @uri200, @tmdzk, @Neudrino hope this is the right thing to do.
