### ISSUE TITLE
Configured Policy AMBR values are not reflecting in PDUSessionResourceSetupRequest and PDU session establishment accept messages from AMF 

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11866]
magma version: 1.7.0-1645582388-d3289720

Executed Test case with attaching Policy for the UE and observed that AMF is updating the PDUSessionResourceSetupRequest and PDU session establishment accept messages with APN AMBR values instead of Policy AMBR values. Please check the attached logs and pcaps for the same.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/1d11a52a-07fb-4612-b75c-bd77f240dd77)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b55f2583-9a49-45ae-b463-1266f10c7a40)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/21c9f10d-c560-48b2-b3d6-c355768878ff)

[https://app.zenhub.com/files/170803235/488dd098-653c-45a7-8e57-242c395578ca/download](https://app.zenhub.com/files/170803235/488dd098-653c-45a7-8e57-242c395578ca/download)

**Comment by NeelimaKalpana** [comment]
Traces of GDB:

(gdb) p *response.rat_specific_context_.m5g_session_context_rsp_.qos_
$5 = {<google::protobuf::Message> = {<No data fields>}, static kIndexInFileMessages = 6,
  static QCI_0 = magma::lte::FlowQos_Qci_QCI_0, static QCI_1 = magma::lte::FlowQos_Qci_QCI_1,
  static QCI_2 = magma::lte::FlowQos_Qci_QCI_2, static QCI_3 = magma::lte::FlowQos_Qci_QCI_3,
  static QCI_4 = magma::lte::FlowQos_Qci_QCI_4, static QCI_5 = magma::lte::FlowQos_Qci_QCI_5,
  static QCI_6 = magma::lte::FlowQos_Qci_QCI_6, static QCI_7 = magma::lte::FlowQos_Qci_QCI_7,
  static QCI_8 = magma::lte::FlowQos_Qci_QCI_8, static QCI_9 = magma::lte::FlowQos_Qci_QCI_9,
  static QCI_65 = magma::lte::FlowQos_Qci_QCI_65, static QCI_66 = magma::lte::FlowQos_Qci_QCI_66,
  static QCI_67 = magma::lte::FlowQos_Qci_QCI_67, static QCI_70 = magma::lte::FlowQos_Qci_QCI_70,
  static QCI_75 = magma::lte::FlowQos_Qci_QCI_75, static QCI_79 = magma::lte::FlowQos_Qci_QCI_79,
  static Qci_MIN = magma::lte::FlowQos_Qci_QCI_0, static Qci_MAX = magma::lte::FlowQos_Qci_QCI_79,
  static Qci_ARRAYSIZE = 80, static kArpFieldNumber = 6, static kMaxReqBwUlFieldNumber = 1,
  static kMaxReqBwDlFieldNumber = 2, static kGbrUlFieldNumber = 3, static kGbrDlFieldNumber = 4,
  static kQciFieldNumber = 5,
  _internal_metadata_ = {<google::protobuf::internal::InternalMetadataWithArenaBase<google::protobuf::UnknownFieldSet, google::protobuf::internal::InternalMetadataWithArena>> = {ptr_ = 0x0, static kPtrTagMask = 1,
      static kPtrValueMask = -2}, <No data fields>}, arp_ = 0x0, max_req_bw_ul_ = 5000000,
  max_req_bw_dl_ = 4000000, gbr_ul_ = 0, gbr_dl_ = 0, qci_ = 9, _cached_size_ = {
    size_ = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = 0}, <No data fields>}}}
(gdb)

**Comment by NeelimaKalpana** [comment]
Hi Sathya,

A small observation w.r.t QFI that can be addressed along with above fix.
Along with AMBRs , QFI is also not getting.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6ce54d0d-b27e-4051-93e6-9c826135af47)

QCI in Policy:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1513826d-5992-48da-80ee-440290a22792)



Please find the attach logs and pcaps.

[https://app.zenhub.com/files/170803235/f2ea972f-debe-4c53-92fd-e9b6d774200e/download](https://app.zenhub.com/files/170803235/f2ea972f-debe-4c53-92fd-e9b6d774200e/download)

**Comment by NeelimaKalpana** [comment]
Verified and closing 

[https://app.zenhub.com/files/170803235/f5444068-e8bc-4d03-ad67-563d79ba0df3/download](https://app.zenhub.com/files/170803235/f5444068-e8bc-4d03-ad67-563d79ba0df3/download)
