### ISSUE TITLE
Strategy for handling DMME_UNIT_TEST in OAI code-base & Bazel

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11861]
Presently, there are some ~sixty uses of `MME_UNIT_TEST` precompiler define to do ~dependency injection of the MME code base for purposes of unit test.

A strategy is necessary for this problem - specifically for Bazel use.  Precompiler defines are a painful way to toggle dependencies as they require wholesale recompilation AND require increased (to be determined) complexity of the Bazel build rules to accomplish. However in C lang there appears to be ~only one alternative and that's to pass around function pointers all over the place or allocate static global pointers to these functions but then require initialization sequencing (both 'solutions' in C appears fairly non-ideal). Ultimately C makes this hard.

- Option A: Refactor out the precompiler defines.  So long as this codebase is in C I'm not sure there is a great path here - but welcome deeper thought / investigation by others.
- Option B: Make this work in Bazel. How I do not yet know.  Do we have to go so far as to have two cc_library labels? One with precompiler defines for MME_UNIT_TEST and `testonly = "true"`, a second without? That sounds awful.  Or can we use a switch statement on precompiler defines in which bazel detects if this is being consumed by a cc_test?

**Comment by nstng** [comment]
We did some testing ...

Option B: in `.bazelrc` add a line `test --copt=-DMME_UNIT_TEST`

It seems that Bazel is intelligent enough to have this information in the cache digests, i.e., first run of build and test takes a long time. Afterwards this will be faster.

Might be a good intermediate solution, what do you think @electronjoe, @themarwhal ?

**Comment by themarwhal** [comment]
> We did some testing ...
> 
> Option B: in `.bazelrc` add a line `test --copt=-DMME_UNIT_TEST=1` (`=1` might be redundant ... but testing this locally takes so much time - test TBD)
> 
> It seems that Bazel is intelligent enough to have this information in the cache digests, i.e., first run of build and test takes a long time. Afterwards this will be faster.
> 
> Might be a good intermediate solution, what do you think @electronjoe, @themarwhal ?

Oh I hadn't thought of this! Yes this does seem like a good temproarily workaround.

**Comment by electronjoe** [comment]
> Might be a good intermediate solution, what do you think @electronjoe, @themarwhal ?

I think this looks good for now!

I also think that my compilation time concerns are a little bit a red herring in retrospect, because any test builds will differ greatly in compiler flags relative to production build - so there won't be much bazel cache re-use between regardless of our precompiler define deltas.
