### ISSUE TITLE
[NMS] Clean up directory organization

### ISSUE THREAD

**Issue by andreilee** [magma/magma#11890]
# Clean up directory organization of `/nms/packages/magmalte`

## Summary
This is a task to migrate everything from `magma/nms/packages/magmalte` to `magma/nms`. Some of the basic testing and building workflows present some difficulty here because of the doubled `package.json` files in those two directories.

Some other dependencies on the current structure that need to be cleaned up:
- docker-compose files
- .circleci files
- .md documentation files
- .yaml deployment files

**Comment by thmsschmitt** [comment]
I'm starting to work on this now
