### ISSUE TITLE
bazel-base: magmad test failures 

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#11915]
Seeing that some magmad unit tests are failing inside bazel-base
<img width="851" alt="Screen Shot 2022-03-02 at 8 18 50 PM" src="https://user-images.githubusercontent.com/37634144/156477677-d0741aa8-67e6-4c38-87bb-90eed915c4c8.png">

All the errors seem to be related:
```
orc8r/gateway/python/magma/magmad/metrics.py:22: in <module>
    from magma.common.service import MagmaService
orc8r/gateway/python/magma/common/service.py:25: in <module>
    import pkg_resources
E   ModuleNotFoundError: No module named 'pkg_resources'
```

## Repro steps
1. checkout latest master
2. cd magma/experimental/bazel-base; docker-compose build; docker-compose run magma-builder bash
3. bazel test //...

**Comment by themarwhal** [comment]
cc @LKreutzer

**Comment by LKreutzer** [comment]
@themarwhal  Created https://github.com/magma/magma/pull/11918 to fix it right now. The `setuptools` dependency was removed by mistake in https://github.com/magma/magma/pull/11838 and would be reintroduced in https://github.com/magma/magma/pull/11857 - but that will likely not be merged today, thus the PR https://github.com/magma/magma/pull/11918.
