### ISSUE TITLE
pipelined takes long time to start

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#11914]
### Your Environment

- **Version:1.6.1 and 1.7.0-1640913705-e6e795fd**
- **Affected Component:** AGW
- **Affected Subcomponent:** pipelined/ovs
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

service pipelined takes long time to start up.  From the example in syslogs the AGW was booted at Feb  9 16:41:23 and pipelined started to run without errors around  Feb  9 16:47:16. So it took several minutes to load.
ovs version 2.15.2-7

From the logs I observe some errors

Feb  9 16:42:01 gw2-3 pipelined[3770]: WARNING:GYController:Datapath not initilized, setup failed
Feb  9 16:42:01 gw2-3 pipelined[3770]: WARNING:InOutController:Datapath not initilized, setup failed

**Expected behavior**
After service restart or  AGW boot, pipelined should start within a minute instead of several minutes. 

**Screenshots**

**Additional context**
Internal Task T112052395
syslog https://fburl.com/oxpfjbyr

**Comment by crbertoldo** [comment]
Hi, @wallyrb did you happen to get this issue solved?

**Comment by edaspb** [comment]
Hi @crbertoldo, we investigated this issue with @wallyrb on our deployment. 1.7.0 stable release solved it.
