### ISSUE TITLE
NMS Gateways page is incorrect for networks without gateways 

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#1192]
### Your Environment

- **Version:** 1.0.1
- **Affected Component:** NMS
- **Affected Subcomponent:** NMS
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

At the moment when Orc8r deployed to AWS according to https://facebookincubator.github.io/magma/docs/orc8r/deploy_intro 

**To Reproduce**
1. Go to NMS web portal
2. Login
3. Create first Network (without Gateway setup)
4. Open Network details page /nms/<network name>/gateways
5. See infinit spinner 

**Expected behavior**
Empty Gateways list with "No Gateways found" placeholder is expected.

**Screenshots**
<img width="1510" alt="Magma" src="https://user-images.githubusercontent.com/372029/74247134-444c4d00-4cee-11ea-94de-f45542b055d9.png">

**Comment by vladiskuz** [comment]
Everything is working now. This was probably fixed in some patch. This issue may be closed.
![image](https://user-images.githubusercontent.com/8994720/77545366-bbffc100-6ec3-11ea-81ae-4d6adc691bc1.png)
