### ISSUE TITLE
Subscriber count is not correct in NMS UI

### ISSUE THREAD

**Issue by Siddharthlende** [magma/magma#11929]
### Your Environment
- **Version:** v1.6.1
- **Affected Component:** NMS
- **Affected Subcomponent:** N/A
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue
 i have provisioned 29 subscribers. When i  see in network it is showing 25 subscribers (may be based on default page size) when i go to next page it is showing 4 subscribers on network. If any one explored or having knowledge on NMS code please let me know the exact behavior or exact fix for the same if it seems as a bug. Sharing screenshots of same for your reference.

**To Reproduce**
1. Go to NMS UI
2. Click on Subscriber and add subscriber (in my case i have uploaded subscribers via .csv file)
3. Scroll up to Network there check subscriber count (it may be displaying based on the default page size)
4. Go to subscriber and go to next row 
5. Come back to Network and check it will show number subscribers from second page/row

**Expected behavior**
It has to show total number of subscribers provisioned irrespective of page/row we are changing.
![image](https://user-images.githubusercontent.com/50014969/156588950-24a16c1b-0c1c-43bf-8e48-ad2426d0f8f0.png)
![image (1)](https://user-images.githubusercontent.com/50014969/156588947-555cdd3a-3191-4858-b8b9-1a92fb5fbc7f.png)
![image (2)](https://user-images.githubusercontent.com/50014969/156588945-5d16d48c-cb51-4f4e-9466-d5ed9c1ef110.png)
![image (3)](https://user-images.githubusercontent.com/50014969/156588937-b4170e21-338a-40b3-b244-2f0eba2f3c07.png)
![image (4)](https://user-images.githubusercontent.com/50014969/156588932-88e466ad-38df-40d1-bb28-4590dce90c5d.png)

**Comment by pshelar** [comment]
@andreilee can you have a look and assign it to right person.

**Comment by Siddharthlende** [comment]
Hi @pshelar and @andreilee,
Any update / inputs on this..?

Regards,
Siddharth.
