### ISSUE TITLE
[aws debug] nameserver issue to use deploy script to bring up docker services of AGW

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#11942]

**Comment by ShubhamTatvamasi** [comment]
When we deploy AGW on bare-metal we change nameservers.

https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install_ubuntu.sh#L74

```
ubuntu@ubuntu:~$ cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 8.8.8.8
nameserver 208.67.222.222
```

**Comment by tmdzk** [comment]
In newer Ubuntu, resolv.conf is managed by a systemd-resolved, so the file is automatically regenerated according to the different files in `/etc/systemd/network/*.network`

Check out what we did for baremetal installation: https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install_ubuntu.sh#L72 that will help you out. 

cc @ShubhamTatvamasi

**Comment by ShubhamTatvamasi** [comment]
Thanks @tmdzk, let me try using the following method. If it works on EC2 instance, I will add an Ansible task for this and create a PR for same.

**Comment by ShubhamTatvamasi** [comment]
Your code did the trick @tmdzk, I have created a PR for same #12045
