### ISSUE TITLE
Request to add "Regression test result 5G-Alpha - Release 1.7 Candidate"

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11958]
Hi Arun,

Please provide regression results for 5G-Alpha -Release 1.7 Candidate .

Please work on it at high priority , and it will be good if we are able to port them from yours tomorrow Morning. Initially we can get the results from master branch and once the Candidate is ready , we can run the same on Candidate build.

All the Test cases listed for 5G-Alpha release should run with stateless-mode.

Title for the Run : Regression test result 5G-Alpha - Release 1.7 Candidate
Excel sheet tab name --> 5G Alpha Rel

Please find the List of all TC marked for 5G-Alpha release from the attachment.
[https://app.zenhub.com/files/170803235/2913b847-707a-4597-adfc-ba0ffd9a361b/download](https://app.zenhub.com/files/170803235/2913b847-707a-4597-adfc-ba0ffd9a361b/download)

**Comment by arun-magma** [comment]
Received 56 MVP Test cases list, Planning & Execution in progress, will provide More updates by early next week.
cc: @vaishaliCI

**Comment by NeelimaKalpana** [comment]
Closing this issue as we got it resolved.
