### ISSUE TITLE
Competitive Analysis on NMS Documentation

### ISSUE THREAD

**Issue by iirisgao** [magma/magma#11957]
# Competitive Analysis on NMS Documentation

Related issue: #9848 

One of our goals of the open source Network Management System (NMS) is to enable all users to find the information they need from the documentation. Improving the quality of documentation is one of the priorities towards the graduation of Magma. To find out the gaps and opportunities, we did a competitive analysis on the product documentation of 4 open source NMS products: [Zabbix](https://www.zabbix.com/manuals), [Ubiquiti (UISP)](https://l.workplace.com/l.php?u=https%3A%2F%2Fhelp.ui.com%2Fhc%2Fen-us%2Fcategories%2F360003421733&h=AT1ONg9jB84bcmTl4enS5e00SY7B4RAw-616-BqiZ6JJdIWpjfgDRlMFyTYZUXqVZ8KqfsF9Pl2b_Agmt5jah4LSJDe741e96nXZMPzuybMx87FIWpowR5k4oX_OKbJ6tCQkNaNmpRxTr8AptzHInQ), [OpenNMS](https://l.workplace.com/l.php?u=https%3A%2F%2Fdocs.opennms.com%2Fstart-page%2F1.0.0%2Findex.html&h=AT1ONg9jB84bcmTl4enS5e00SY7B4RAw-616-BqiZ6JJdIWpjfgDRlMFyTYZUXqVZ8KqfsF9Pl2b_Agmt5jah4LSJDe741e96nXZMPzuybMx87FIWpowR5k4oX_OKbJ6tCQkNaNmpRxTr8AptzHInQ), and [LibreNMS](https://l.workplace.com/l.php?u=https%3A%2F%2Fdocs.librenms.org%2F&h=AT1ONg9jB84bcmTl4enS5e00SY7B4RAw-616-BqiZ6JJdIWpjfgDRlMFyTYZUXqVZ8KqfsF9Pl2b_Agmt5jah4LSJDe741e96nXZMPzuybMx87FIWpowR5k4oX_OKbJ6tCQkNaNmpRxTr8AptzHInQ). Here’s a summary of the high level findings.

## Developers Contributing to the Documentation
Some NMS allow the community developers to create and publish documentation to describe the features they added. They also provide guidance and instructions on how to write the docs. 

![image](https://user-images.githubusercontent.com/88680700/156680636-6bc95a05-eb8d-4415-86b5-ccd7868d216b.png)
<p align = "center"> LibreNMS guidelines for creating documentation </p>

![image](https://user-images.githubusercontent.com/88680700/156680705-9b30150b-f531-43ad-9a3e-f386959f76e3.png)
<p align = "center"> OpenNMS rules for developing documentation </p>

## Change Log, Release Notes, and Version History
All four NMS publish release notes to inform the user of the new features, changes, and product updates of new releases. They keep a record of past versions since the user may not always be on the latest version.  

![image](https://user-images.githubusercontent.com/88680700/156681055-7487f82f-6398-4442-9d0b-52162152e2de.png)
<p align = "center"> Zabbix keeps the documentation for difference versions </p>

![image](https://user-images.githubusercontent.com/88680700/156681065-c8a0d58d-66af-4667-a86b-9f7328f99f70.png)
<p align = "center"> The What's new section on Zabbix documentation </p>

## Discussion Forum and Topics
Each NMS we looked into has a discussion forum for the user to ask and answer questions to the community. The discussions are grouped by topic/tag for the user to filter or search for the information they need. Magma's Slack channel enables the users to communicate with each other, but it is not the best way to find topics or answers to questions in a structured way.

![image](https://user-images.githubusercontent.com/88680700/156681103-78136d6b-29b6-4704-baa5-c20a1581290b.png)
<p align = "center"> Ubiquity discussion forum and tags </p>

![image](https://user-images.githubusercontent.com/88680700/156681118-76a92fe2-ea3b-40f0-ab42-4c313d094587.png)
<p align = "center"> OpenNMS discussion forum </p>

![image](https://user-images.githubusercontent.com/88680700/156681135-95069a47-78da-4a32-8c28-b70afcbc2eab.png)
<p align = "center"> Users can subscribe to the questions they want to follow </p>

## Suggesting New Features
Another cool thing the user can do on the discussion forum is suggesting new features. If they like a feature someone else has suggested, they can show their support by 'Liking' it. This creates opportunities for the community to benefit and support each other. Developers from the community can gain inspirations on what features to create, and other community members could possibly get the feature they need.

![image](https://user-images.githubusercontent.com/88680700/156681170-93f169bc-c1db-4a82-8302-fb4ed016ec44.png)
<p align = "center"> Feature requests on LibreNMS discussion forum </p>

## Documentation Structure
The structure of the documentation can be generally categorized into the following sections

- Introduction (overview, definition)
- Deployment (installation, getting started, setup)
- Operation (configuration, use of the platform such as monitoring, alerting, API)
- Development (setup environment, code guidelines, creating documentation)
- Appendix (FAQ, reference material)

![image](https://user-images.githubusercontent.com/88680700/156681230-0bd5c677-1beb-477d-a092-84486d18d2c0.png)
<p align = "center"> Side-by-side navigation structure of LibreNMS, OpenNMS, and Zabbix </p>

## Recommendations for Magma's Documentation

- Audit the current documentation. This will help us list out the content that we need to add or improve.
- Enable the community to contribute to the documentation. Community members can either help us improve the quality of the documentation, or create new content when they develop new features.
- Streamline the publishing process. Align the publishing timeline with the product releases and make documentation an integral part of the product development process. 
- Define templates. Define the structure and guidelines to ensure the consistency of the language and content.
- Use a forum for discussion. Group the conversations into different topics so that it's easy to find answers to questions.

**Comment by Neudrino** [comment]
I think https://github.com/magma/magma/issues/9848 should be mentioned for reference here.
I wonder if this supersedes or conflicts with #9848?

**Comment by Neudrino** [comment]
Was the Magma documentation also analysed to see, which of the recommendations is already met or which of the components and features are already available?

**Comment by Neudrino** [comment]
One point not covered so far is the **Documentation distribution**.

For Magma documentation seems to be rather distributed to several places, including
- DocuSaurus: https://docs.magmacore.org/docs/basics/introduction.html
- Github Wiki: https://github.com/magma/magma/wiki
- Confluence :question: (There was a confluence announced some-when, however, I am not sure if it was decided yet.)
- Documentation of "parallel organisation", e.g. https://docs.magmaindia.org/index.html

**Comment by iirisgao** [comment]
> I think #9848 should be mentioned for reference here. I wonder if this supersedes or conflicts with #9848?

Thanks for mentioning this issue, just added it to the proposal. 
This should be additions to #9848 hopefully, not conflicts with it.

**Comment by iirisgao** [comment]
> One point not covered so far is the **Documentation distribution**.
> 
> For Magma documentation seems to be rather distributed to several places, including
> 
> * DocuSaurus: https://docs.magmacore.org/docs/basics/introduction.html
> * Github Wiki: https://github.com/magma/magma/wiki
> * Confluence ❓ (There was a confluence announced some-when, however, I am not sure if it was decided yet.)
> * Documentation of "parallel organisation", e.g. https://docs.magmaindia.org/index.html

Great point on the distribution. Looks like the the user guide in on DocuSaurus and the contributor guide is on GitHub. I don't have enough context about why we keep them separate. But one single place for documentation would be ideal, if that's possible.

**Comment by andreilee** [comment]
Great point of comparison between the more traditional discussion forums and our use of Slack, as well as the downsides we face with Slack. I think if that's something we can add without much overhead, we should go for it.

**Comment by lucasgonze** [comment]
This improvement does not have the urgency to dedicate extremely limited hours to it. However, it could be reopened if a contributor wants to take it over the finish line.
