### ISSUE TITLE
Bare Metal AGW Upgrade from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by edaspb** [magma/magma#1196]
### Your Environment

- Version: 1.0.1
- Affected Component: Access Gateway
- Deployment Environment: bare-metal (AGW)

Looks like the instruction (in the github's releases page) for upgrade bare metal AGW from ver 1.0.0 to 1.0.1 is incorrect.

After

`sudo apt-get install -o Dpkg::Options::="--force-confnew" --assume-yes --force-yes magma=1.0.1-1580860031-33a94e98`

I receive 

`The following packages will be DOWNGRADED:
  magma`

Checking other agw with ver 1.0.0:

`apt-cache show magma
Package: magma
....
Version: 1.0.2-1580873311-7a4747db`

**Comment by mpgermano** [comment]
This is expected. You can proceed with the command and you'll be on version 1.0.1.
