### ISSUE TITLE
Request to upgrade the HW configurations in the TVM-AGW .

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11967]
Hi Arun,

This is a request to increase few HW configurations in TVM-AGWs.

Kindly , please start with once server .
By doing this we may mitigate Traffic-Failures and also failures due to subscriber-db issue.

Below are some of the configurations need to be updated.
Current Configurations:
CPU(s): 1
L3 cache: 24.8 MiB

Required configurations.
CPU-Core : 4
L3 cache: 24.8 MiB

Please try to do this Arun, before 1.7 release . 
Please let me know the ETA for this

**Comment by arun-magma** [comment]
@NeelimaKalpana 
AGWs of Regression (141) and Dev (144, 143) upgraded to below config, Please continue Scale & Capacity test & let us know how is the performance after this upgrade.
cc: @vaishaliCI 

[Current HW Config]
CPU: 	 4 vCPUs
Memory:	 12 GB
Hard disk: 60 GB

**Comment by NeelimaKalpana** [comment]
Closing this issue as support is given.
