### ISSUE TITLE
[5G] Add Test Results & Logs

### ISSUE THREAD

**Issue by jaredmullane** [magma/magma#11974]
Hey @parthiban337 ,

Can you add the 5G test logs you shared here for the broader community? Relevant information would include the setup configuration along with the accompanying result. Please also share you PCAP logs to the documentation [here](https://docs.magmacore.org/docs/next/resources/ref_pcap#pcap-collection) so the community knows what to look for in their own setups.

**Comment by parthiban337** [comment]
Hi All,

5G Alpha Release as part of 1.7 release SIT updates: 5G call working with real equipment in SIT.

The latest Magma Mater branch builds 1.7.0-1646352009-440622cf tested in the Baicells lab with real equipment.

Baicells gNB + Huawei Mate 30 are used in this testing.

Basic 5G call is working consistently and we are in the process of testing traffic, service requests, etc. I will continue to update the progress. 

With this update, we are confident the 5G alpha release can be bundled with the 1.7 Release as planned.

Additionally, all the 1.7/alpha release subset of test cases are passing in the TVM & also in the CICD run. 

I am working with the team to report these 1.7 candidate regression tests run separately to see consistently green.

PFA the logs, pcaps & screenshot of the pcaps.  

Thanks & Regards,
Parthiban. N
![PLMN details](http
![config files](https://user-images.githubusercontent.com/70892901/156879658-c2965a1a-f7fa-4cb0-adb6-f3270e59f8bd.png)
s://user-images.githubusercontent.com/70892901/156879651-92897942-3b9c-47cc-8b8f-8f71b50e8c88.png)

![pcap pic](https://user-images.githubusercontent.com/70892901/156879632-d7152615-6b9e-4e61-8f25-f8eb5ed6e3df.png)
![Subscriber details](https://user-images.githubusercontent.com/70892901/156879647-1537e46b-4d2f-451f-b782-24e92fa1ce99.png)
[AGW MMESYS-LOGPCAP.zip](https://github.com/magma/magma/files/8190469/AGW.MMESYS-LOGPCAP.zip)

@jaredmullane

**Comment by NeelimaKalpana** [comment]
Hi All,

Please find the attached "5G SA TVM_Feature_Reg_Test_Logs" folder  which contains both Logs and Packet captures for your perusal .

[5G SA TVM_Feature_Reg_Test_Logs.zip](https://github.com/magma/magma/files/8333459/5G.SA.TVM_Feature_Reg_Test_Logs.zip)


Thanks and Regards,
Neelima

**Comment by NeelimaKalpana** [comment]
Hi All,

Please find the attached "5G SA -CICD_ Abot_Test_Logs" folder which contains both Logs and Packet captures for your perusal .

[5G SA -CICD_ Abot_Test_Logs.zip](https://github.com/magma/magma/files/8333788/5G.SA.-CICD_.Abot_Test_Logs.zip)


Thanks and Regards,
Neelima

**Comment by NeelimaKalpana** [comment]
Hi All,

Please find the attached SIT/Real Equipment test  logs folder  which contains both Logs and Packet captures for your perusal .
[5A Baicells Logs - Baicell Lab.zip](https://github.com/magma/magma/files/8333808/5A.Baicells.Logs.-.Baicell.Lab.zip)

[5G Baicells Logs - CpqD Lab.zip](https://github.com/magma/magma/files/8333814/5G.Baicells.Logs.-.CpqD.Lab.zip)


Thanks and Regards,
Neelima

**Comment by NeelimaKalpana** [comment]
Hi All,

Please find the attached "5G SA - Sprient- Perf_Scale_Test_Logs" folder which contains both Logs and Packet captures for your perusal .

[5G SA - Sprient- Perf_Scale_Test_Logs.zip](https://github.com/magma/magma/files/8333835/5G.SA.-.Sprient-.Perf_Scale_Test_Logs.zip)


Thanks and Regards,
Neelima
