### ISSUE TITLE
Explore failing //lte/gateway/c/core/oai/test/spgw_task:spgw_procedures_test

### ISSUE THREAD

**Issue by nstng** [magma/magma#11984]
# Problem
* https://github.com/magma/magma/blob/331551e2289d30fdbd6c811e8d2a46d95fd5c6b2/lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp#L623 fails with Bazel with [1].
  * with make this test is successful
* The matcher https://github.com/magma/magma/blob/331551e2289d30fdbd6c811e8d2a46d95fd5c6b2/lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp#L72 is triggered, but the `memcmp` of the arrays failes. With Bazel the passed array (not the array from `arg`) seems to start with five non-deterministic values (from this point of view).
* Creating a copy of the matcher array before defining the `EXPECT_CALL` works for Bazel (also with asan and lsan) and make, i.e., in between something happens with the array when running with Bazel.
  * My understanding of the google test matchers: expected values are passed, i.e., variables should be constants that are not changed by test and/or tested logic. The solution above seems reasonable. Understanding the root cause is still open.
* Unclear if related: during testing was observed that removing https://github.com/magma/magma/blob/331551e2289d30fdbd6c811e8d2a46d95fd5c6b2/lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp#L361 and lines until the end of the function results in a still green test (with make) - obviously, because additional testing and asserts are removed. But, removing now https://github.com/magma/magma/blob/331551e2289d30fdbd6c811e8d2a46d95fd5c6b2/lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp#L359 results in similar behavior as with Bazel (the "random" pattern of the array is slightly different).

[1]
```
lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp:365: EXPECT_CALL(*mme_app_handler, mme_app_handle_nw_init_bearer_deactv_req( check_params_in_deactv_bearer_req( sample_gx_nw_init_ded_bearer_deactv_req.no_of_bearers, sample_gx_nw_init_ded_bearer_deactv_req.ebi )))...
  Expected arg #0: check params in deactv bearer req (1, 0x7ffe36289f89)
           Actual: 20-byte object <01-06 00-00 00-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00>
         Expected: to be called once
           Actual: never called - unsatisfied and active
```

**Comment by themarwhal** [comment]
@nstng If you want to compare against testing with CMake, you will need this patch: https://github.com/magma/magma/pull/11883
