### ISSUE TITLE
Explore failing //lte/gateway/c/core/oai/test/mme_app_task:sgw_config_test

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#11994]
- Running `bazel test //lte/gateway/c/core/oai/test/mme_app_task:sgw_config_test` results in:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //lte/gateway/c/core/oai/test/mme_app_task:sgw_config_test
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SGWConfigTest
[ RUN      ] SGWConfigTest.TestParseHealthyConfig
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in the test body.
[  FAILED  ] SGWConfigTest.TestParseHealthyConfig (1 ms)
[ RUN      ] SGWConfigTest.TestParseHealthyConfigDisplay
[       OK ] SGWConfigTest.TestParseHealthyConfigDisplay (0 ms)
[----------] 2 tests from SGWConfigTest (2 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SGWConfigTest.TestParseHealthyConfig

 1 FAILED TEST

```

**Comment by LKreutzer** [comment]
@electronjoe : If `copts = ["-DEMBEDDED_SGW"]` is added to the bazel target `sgw_config_test`, then the test passes, also with the `--config=lsan` and `--config=asan` options.

The same is true for the `pgw_pco_test` https://github.com/magma/magma/issues/11678 (also with the `--config=lsan` and `--config=asan` options)!

According to the [bazel documentation on copts](https://bazel.build/reference/be/c-cpp#cc_library.copts): _"The flags take effect only for compiling this target, not its dependencies, so be careful about header files included elsewhere"_. Since the test is not using the `EMBEDDED_SGW` variable anywhere it should not be needed in the test targets. The flag is set for the `core` target which includes the files that use the variable. **We currently do not understand why it doesn't work if it isn't set in the test targets.**

PS: Should we create a PR on your fork for things like this or just write the code in the issues?

**Comment by electronjoe** [comment]
Excellent finding @LKreutzer! I think you just earned a flower delivery from me. I've been SO CONFUSED by these failures. I've been in gdb for a number of hours now.  What I am still unclear on is - I eyed `EMBEDDED_SGW` and other precompiler defines as failure points, but swear that in `gdb` evaluation these code segments were executing.  What I now worry is that perhaps my target binary was not ~equal to the `bazel test` binary for some reason (a failure in my workflow with gdb mislead me?). I don't yet know. [Edit: Aah, I see now. Only Header files included transitively in our `cc_test` were carving out / omitting `EMBEDDED_SGW` - so the last uncertainty is why the [removal of the `log_config` element](https://github.com/electronjoe/magma/commit/bdda0320fa1ed377feba957dc9f0efb5b1ea2c82) was causing such strange misbehavior (and why it compiled at all)].

Time to dig into the bazel documentation you point at.  What I figure might be happening here is that when we compile the `cc_test` target, some headers are getting sucked into our test target that include optional `EMBEDDED_SGW` flags and Bazel only (maybe) applies the cc flags to the compilation of the `:core` c/cpp files? And therefore we are missing these flags in the `cc_test` header hoovering?

Generally this is an awfulness to the use of precompiler flags IMO. I had not thought of this but they break scope - leak out into compilation of libraries depending upon. Yuck.

**Comment by electronjoe** [comment]
> PS: Should we create a PR on your fork for things like this or just write the code in the issues?

You are welcome to fork my "outstanding tests that don't work" [branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase), fix a ~subset, and then post a PR to enlarge our unit test coverage with the newly fixed tests. You may run into some mild conflict on rebase with merge of #11927 (which appears to be hitting a disk storage issue in GH Actions... sad panda).

**Comment by electronjoe** [comment]
So I think they have mis-worded this IMO.  From what we are seeing, and from the structure of their sentence, I think the following:

> The flags take effect only for compiling this target, not its dependencies, so be careful about header files included elsewhere.

Should in fact read

> The flags take effect only for compiling this target, **not dependencies upon this target**, so be careful about header files included elsewhere.

If true then we have a problem in that ~all defines may be exposed to dependent-upon-core compilation targets. Which is really ugly...

I'm going to post a question to Bazel GH Repo for clarity on above wording.

**Comment by electronjoe** [comment]
It appears that ONLY this one instance of `EMBEDDED_SGW` is in violation of the "don't use precompiler defines in headers" that we have discovered.  See [source search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+file:.h%24+EMBEDDED_SGW&patternType=literal).

I would be in favor of refactoring and removing. If possible (taking a look now).

Edit: straight removal of conditional definition of `log_config` appears to result in successful tests! As @LKreutzer noted.  It is not at all clear to my why this instantiation (or omission) of a member variable is causing such difference in behavior (or for that matter if the `log_config` variable is necessary why this compiles without it).

**Comment by nstng** [comment]
We had another look into this. We also see that the core is compiled with `EMBEDDED_SGW` and for example `pgw_pco_test` is not. Both targets depend on `sgw_config.h` where the pre compiler flag is used. Seems to be the root cause of strange behavior.

If we remove the pre compiler `#if` only from `sgw_config.h` then we only solved one instance of this problem.

In general we want to have tests (or other targets) that use different values for pre compiler flags for all transitive dependencies. It seems this is not supported by Bazel - flags can be set via `cops` for one target (without dependencies) or via `defines` for a target and targets above. But propagating `cops` down the chain is not supported.

Approaches
* getting rid of Magma pre compiler statements (approach from @electronjoe) -> if possible, good
* `defines` (https://docs.bazel.build/versions/main/be/c-cpp.html#cc_library.defines) can be used to propagate `cops` up the dependency chain -> locks in certain defaults (i.e., can not be changed without changing the code)
* duplication of targets -> ugly (but seems to be the most straight forward/native approach, but (again) makes a mess if the core is split up)
* same approach as for `lsan`/`asan` -> needs to be added to command line, tests need to be manual (or else they will fail if configuration is not set)
* maybe https://docs.bazel.build/versions/4.2.2/skylark/config.html can help -> needs investigation but seems to add complexity

Recommendation
* try to remove the one pre compiler usage - if the problem occurs again, try to remove the pre compiler statement as well. If further removes are not possible, then look at alternatives.

**Comment by electronjoe** [comment]
> * try to remove the one pre compiler usage - if the problem occurs again, try to remove the pre compiler statement as well. If further removes are not possible, then look at alternatives.

Thanks for the thorough exploration of alternatives! I agree with everything you laid out above.

Edit: This was ~said by your comment but ultimately header files are not a reasonable place for precompiler flags to hide or expose interface details (which is the purpose of a header file). So this is absolutely technical debt - just a question of if we can remove it ~now and easily (across all flags that may modulate behavior in headers).

**Comment by ssanadhya** [comment]
@electronjoe , @LKreutzer , looking at this particular case, the code guarded by these pre-compiler flags in `sgw_config.h` and `sgw_config.c` is dead and should be cleaned up. Let me create a separate PR to do that. cc: @ardzoht 

I do agree with the general principal that we should avoid these pre-compiler flags in header files altogether.

**Comment by ssanadhya** [comment]
Cleaned up `sgw_config.h/c` in https://github.com/magma/magma/pull/12018
