### ISSUE TITLE
AGW status is fluctuating under Dashboard (Connected/Disconnected) and Equipment (Good/Bad) in NMS UI

### ISSUE THREAD

**Issue by p00jaY** [magma/magma#12004]
**Your Environment**

     Version : v1.6.1
     Affected Component : NMS
     Affected Subcomponent : N/A
     Deployment Environment : Vagrant [(AGW)]

**Describe the Issue**
Added Gateway in NMS. The status of added gateway is not accurate(fluctuating) sometime it shows Good/Bad in NMS. In Dashboard, same behavior is observed. Gateway's connected status under Events is not accurate (fluctuating) sometime it shows Connected/Disconnected.  If any one explored or having knowledge on NMS code please let me know the exact behavior or exact fix for the same if it seems as a bug. Screenshots are attached below for same:

**To Reproduce**

    Go to NMS UI
    Click on Add Gateway button and add details such as Hardware ID and Challenge Key from AGW Host.
    After Adding Gateway, you can check the gateway status as Good/Bad.
    Then go to Dashboard and monitor the gateway connected status under Events as Connected/Disconnected.

**Expected behavior**

It has to show Good as a gateway status.
![Gateway_health_is_bad](https://user-images.githubusercontent.com/101162794/157183290-060e4583-0eef-4ebb-9fa2-bfb50a0216a9.PNG)
![Gateway_health_is_good](https://user-images.githubusercontent.com/101162794/157183299-5302d5aa-c0dd-43ce-a93f-2ad01b8d2fd4.PNG)
![Gateway_status_as_disconnected](https://user-images.githubusercontent.com/101162794/157183306-10ec3eca-3d0a-4531-9324-2f81fe1ad56c.PNG)
![Gatway_status_as_connected_under_Dashboard](https://user-images.githubusercontent.com/101162794/157183312-d86561fb-4c73-4a3e-8673-fd40b083a185.PNG)

**Comment by Bharat0908** [comment]
@andreilee, requesting you to please suggest your inputs here.

**Comment by p00jaY** [comment]
@andreilee @HannaFar  , is there any update on this issue??

**Comment by p00jaY** [comment]
Hi @andreilee,

Found this similar issue, we request you to please provide your inputs here. 
https://github.com/magma/magma/issues/7645

Best Regards,
Pooja Yadav

**Comment by p00jaY** [comment]
Hi Team,

We noticed the below observation in which we have seen the bad states.
-- When the NMS Equipment page is unable to fetch the information and get http error code 502 bad gateway. We see the following type of logs in nms-nginx-proxy

2022/04/20 12:17:53 [error] 35#35: *1115 connect() failed (111: Connection refused) while connecting to upstream, client: 10.42.0.53, server: , request: "GET /nms/apicontroller/magma/v1/lte/net1/gateways HTTP/1.1", upstream: "http://10.43.6.174:8081/nms/apicontroller/magma/v1/lte/net1/gateways", host: "magma-test.nms.galaxy.svpb.com", referrer: "https://magma-test.nms.galaxy.svpb.com/nms/net1/equipment/overview/gateway"

-- When we go to some page say for instance From NMS Equipment Page to Network/Subscriber Page, we stay there for duration greater than checkin interval(default 5 mins) and go back to  NMS Equipment Page, it shows "BAD" for sometime.

Requesting you to please provide your inputs.
cc @andreilee @hcgatewood @pshelar @sudhikan 

Best Regards,
Pooja Yadav

**Comment by sebathomas** [comment]
The status is based on the periodic check-in of the gateway. Can you see if there are check-in errors in the AGW logs at the time when the status goes "bad"?

**Comment by p00jaY** [comment]
There are no errors at AGW side. We faced the errors that we discussed over the slack.
If we will see any errors, we will report.

Regards,
Pooja

**Comment by thmsschmitt** [comment]
@p00jaY have you change the checkin_interval? 
![Screenshot 2022-04-28 at 18 38 39](https://user-images.githubusercontent.com/102796295/165802322-6cff300c-a837-401a-bd62-ca55544e7efa.png)

Can you check frequently you see this log message 
`INFO:root:Checkin Successful! Successfully sent states to the cloud!`
on the AGW?

**Comment by sebathomas** [comment]
Fixed by #12699 and #12735.
