### ISSUE TITLE
Security Program Management

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#12016]
# Proposal

## Problem

Magma security work is generally done in private by particular people, in the style of a commercial project. As an open-source project Magma should involve the community as a whole. Working in a group allows Meta to transition ownership from its payroll to the community.

Expanding the scope of the security team would improve the product. Security is a more acute need for Magma than many projects because the project is targetted at vendors rather than consumers. For vendors, security is a benefit rather than a cost.

## Solution

The TSC should regularly review and influence security work. See "Charter" below for the scope.

## Non-goals

Inviting the general public to do security work on Magma. To limit disclosures, participation would be limited to trusted members of the community. 

Create a standalone working group.

**Comment by lucasgonze** [comment]
Prior art for a working group charter:

* W3C: https://www.w3.org/Guide/process/charter.html
* ICANN: https://gnso.icann.org/sites/default/files/filefield_37345/charter-template-19mar13-en.pdf
* http://publichealth.lacounty.gov/plan/docs/Workgroup%20Charter%20Template.pdf

**Comment by lucasgonze** [comment]
The proposed charter is linked here and inline below: https://github.com/magma/security/blob/main/WG-charter.md

# Security Discussions in TSC - Charter

This charter is derived from the [W3C Charter Template](https://w3c.github.io/charter-drafts/charter-template.html).

## Responsibilities

- implement best practices
  - OSSF Scorecard
  - OSSP Best Practices Badge 
- manage upstream exposure
  - track and repair advisories with Dependabot
  - catalog upstream packages with SBOM
  - coordinate with package providers (e.g. Storybook)
- triage disclosures
  - workflows for intake
  - program management for executing fixes
  - publishing advisories and working with reporters
- confidential workflows
  - admin access-controlled issues and Slack

## Out of Scope for this WG:

Penetration testing

## Deliverables 

Demonstrated progress towards goals

Vendor buy-in on security methodology

Organization-wide security policy

Well-maintained issues and project board

## Coordination

Assignments for team who implement decisions

Communication with codeowners

## Participation

To be successful, this discussion must be a regular part of TSC meetings. 

The group encourages questions, comments and issues on the #security channel in the Magma Slack server.

## Membership

TSC members
TPM to coordinate with implementors

## Decision Policy

Security decision-making will be in accord with ordinary TSC processes.

**Comment by lucasgonze** [comment]
Advanced notice for charter, based on the W3C's [Advance Notice for Charter template](https://www.w3.org/new-doc-from-template?location=%2FTeam%2F&template=%2Fafs%2Fw3.org%2Fpub%2FWWW%2FTeam%2FTemplates%2Fadv-charter.html&submit=Continue...):

- Working group name: Security
- Chair 1 name: Lucas Gonze
- Chair 1 email: lucas@gonze.com
- Chair 2 name: Eli Sutton
- Chair 1 email: elisutton@fb.com
- Charter URI:

**Comment by lucasgonze** [comment]
Responsibilities of the WG:

1. Determine [security managers Magma](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)

**Comment by lucasgonze** [comment]
Out of Scope for this WG:

1. TBD
2. TBD

**Comment by lucasgonze** [comment]
Following the procedure for proposals laid out in the wiki page [Adding and Tracking Proposals](https://github.com/magma/magma/wiki/Adding-and-Tracking-Proposals), the next step for this issue is discussion in a TSC venue, including the [#governance-tsc](https://magmacore.slack.com/archives/C01Q1T14YJ2) slack or the [magma-tsc-voting@lists.magmacore.org](mailto:magma-tsc-voting@lists.magmacore.org) list.

I have started a conversation in the Slack channel.

**Comment by lucasgonze** [comment]
I would like to call out these points for discussion:

1. Who are the chairs in the long term, given that Meta's role is changing and the initial chairs may need to cycle out? 
2. How does the WG interface with the TSC? Should there be a TSC member present to have a quorum? If not, how does coordination happen? 
3. Is there truly a quorum with only two people - the chairs - present?
4. Should there be a real-time discussion in [the next TSC meeting](https://wiki.magmacore.org/display/HOME/March+21%2C+2022+Meeting)?

**Comment by ssanadhya** [comment]
@lucasgonze , based on our Slack discussion, could you please revise the proposal to incorporate this activity with the existing TSC? cc: @mstre123

**Comment by lucasgonze** [comment]
@ssanadhya @mstre123 I have updated this proposal. I welcome your feedback in advance of the Monday meeting. 

I anticipate engaged discussion on the scope of the charter, given the limited amount of time available in TSC meetings.

**Comment by lucasgonze** [comment]
Resolved: regular updates in Eng biweekly and TSC weekly. An assigned subtopic.

Communicate this to Slack channels. Close this ticket.
