### ISSUE TITLE
[Regression]TC9 is failing because of traffic loss.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12040]
Your Environment

Version: 1.7.0-1646694943-6937a1c1
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: Bare-Metal(VM Based)

### Describe the Issue
Observing traffic loss in paging scenario.

**To Reproduce**
1. Execute TC9 - AMF initiated paging. 
2. Observing traffic loss of 11.2% 

**Expected behavior**
There should not be any traffic loss. Loss up to 1% is acceptable.

Please find attached logs or reference.[https://app.zenhub.com/files/170803235/16d443c1-908a-46ed-ae5b-06926b75485c/download](https://app.zenhub.com/files/170803235/16d443c1-908a-46ed-ae5b-06926b75485c/download)

**Comment by arun-magma** [comment]
Regression on Build “1.7.0-1646792286-35f8c481”
During paging & Service Req Retry downlink Pkts are being dropped.
[https://app.zenhub.com/files/170803235/f47239e7-9548-496b-809f-b535552606e4/download](https://app.zenhub.com/files/170803235/f47239e7-9548-496b-809f-b535552606e4/download)

![Screen Shot 2022-03-15 at 12.09.28 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/08f64ddc-09da-46bc-a601-e2682af1901e)

**Comment by panyogesh** [comment]
Kindly test on top of latest and confirm. Closing it for now.  This testcase is also related to TVM.
