### ISSUE TITLE
Deleting and adding subscriber usage was showing the Usage data before deleteting. 

### ISSUE THREAD

**Issue by p00jaY** [magma/magma#12043]
### Your Environment

- **Version:** v1.6.1
- **Affected Component:** NMS
- **Affected Subcomponent:** NA
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

We freshly added an subscriber, did s1 setup, attach and run the data for the UE. Now deleted the subscriber from NMS UI, but we didn't see any signaling from MME side towards UE. After that we again added the same subscriber and it is fetching the old data before deletion. Hence on checking code, we see that sessiond is pushing the UE data to prometheus at Orc8r, but somehow it is not getting cleared. We suspect persistence of deleted subscribers usage in UI.

**To Reproduce**
1. Go to Subscriber tab
2. Click on add subscribers
3. Delete one of the added subscriber and add the same subscriber again. 
4. We can see the persistence of deleted subscriber in UI

**Expected behavior**
Ideally it should show zero usage for a newly added subscriber. Whenever subscriber is deleted all it's relevant data should also get deleted. There should not be any stale entries when a subscriber is deleted.

**Screenshots**
Please find below the screenshots for same from NMS UI
![image](https://user-images.githubusercontent.com/101162794/157621976-92cc3a82-af93-4878-9d6a-a54b80287fb6.png)
![image](https://user-images.githubusercontent.com/101162794/157622078-e02e7860-aa92-4fa2-9137-91f8c3671630.png)
![image](https://user-images.githubusercontent.com/101162794/157622580-37cb5fc5-7881-4e5d-8e11-735cd528e2fb.png)
![image](https://user-images.githubusercontent.com/101162794/157622842-1fee3063-2b7a-430a-bf78-1dacc7ebd2ff.png)

**Comment by Bharat0908** [comment]
@andreilee please suggest your inputs here.
