### ISSUE TITLE
Enodeb status rows showing the connection between MME and enodeB as disconnected

### ISSUE THREAD

**Issue by p00jaY** [magma/magma#12042]
**Your Environment**

- **Version:** v1.6.1
- **Affected Component:** NMS
- **Affected Subcomponent:** NA
- **Deployment Environment:** Vagrant (AGW)

**Describe the Issue**

I am trying to add the eNodeB's functionality at Orc8r and simulating enodeB using S1 Simulator and srsRan. We want to analyse some functionality. At enodeB page, SCTP connection is there but mme connection with eNodeB is showing as "Disconnected" on NMS UI. Can someone suggest what eNodeB configuration can help to achieve this functionality. 

Please explain the behaviors for externally managed eNodeB's.

Also on what basis exactly orc8r or enodebd decides to mark mme_connected ? Like what is difference in terms of managed or un-managed enoded? And if it has to be a real enodeb to show mme_connected to connected, then what is the difference between a simulated or real enodeb? I guess, s1ap is enough for that purpose isn't it? which would be done by both simulated and real enodeb .

**To Reproduce**
1. Go to Equipment tab and then go to eNodeB tab
2. Click on add eNodeB
3. Register your eNodeB with AGW
4. Under eNodeB status tab we can see MME connected as Disconnected.

**Expected behavior**
The eNodeB tab should show MME connected status as Connected.

**Screenshots**
Please find below the screenshots for same:

![image](https://user-images.githubusercontent.com/101162794/157616289-52c3b339-5e2f-45af-b4ab-93b562647460.png)
![image](https://user-images.githubusercontent.com/101162794/157616596-5e6ae3b6-d74e-40c1-a8d9-767750f86d3f.png)
![image](https://user-images.githubusercontent.com/101162794/157617382-22320bb5-d5ec-42b9-8802-7df9c6eb021b.png)

**Comment by Bharat0908** [comment]
@andreilee please suggest your inputs.
