### ISSUE TITLE
eNodeB - connected NMS GUI - Connected GWY tab shows as disconnected. ENodeB is atttached and up and running

### ISSUE THREAD

**Issue by p00jaY** [magma/magma#12044]
### Your Environment

- **Version:** v1.6.1
- **Affected Component:** NMS
- **Affected Subcomponent:** NA
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

We have connected the externally managed eNodeB (srsran simulator) to the MME but still it shows as Disconnected inside Gateway tab.

**To Reproduce**
1. Go to gateway tab, add eNodeb and register it to the gateway
2. Click on gateway page 
3. Check the eNodeb connected state it shows as Disconnected

**Expected behavior**
On establishing s1ap connection, ideally we should see the status as connected.

**Screenshots**
Please find below the screenshots attached for reference:
![image(1)](https://user-images.githubusercontent.com/101162794/157640420-36c28f37-ca50-4506-a3c0-a688f91fc726.png)
![image](https://user-images.githubusercontent.com/101162794/157640427-ca5bd9e6-9aef-49c7-87d0-a7cc3b79f651.png)

**Comment by Bharat0908** [comment]
@andreilee  please suggest your inputs.
