### ISSUE TITLE
Stateless Access Gateway

### ISSUE THREAD

**Issue by xjtian** [magma/magma#1205]
Summary
---

This is a long-term tracking task for making all services on the AGW stateless - i.e. AGW services should store all internal state into Redis. This will enable later features like HA AGW deployments and user mobility.

**Comment by xjtian** [comment]
Punting out of the 1.1.0 release - we'll target 1.2.0 for this as it's a blocker for a lot of NMS enhancements we're making.

**Comment by ssanadhya** [comment]
Stateless Access Gateway mode is turned on by default in [v1.4](https://github.com/magma/magma/tree/v1.4).
