### ISSUE TITLE
Migrate OAI-Jenkins job to use Bazel-ified SCTPD/MME

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#12059]
This is blocked on https://github.com/magma/magma/issues/12057

- [x] https://github.com/magma/magma/issues/10891
- [x] https://github.com/magma/magma/issues/10892

Whoever owning this can feel free to take ownership of work started here:
https://github.com/magma/magma/pull/10886

**Comment by nstng** [comment]
all subtasks done
