### ISSUE TITLE
[CI] Add install/upgrade check for Magma .deb package

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#12075]
### Problem

Several failures in testing and production/partner environments come up due to unexpected changes on third-party dependencies. For example, fixes such as https://github.com/magma/magma/pull/11698 are frequently required when AGW services start failing on fresh install or package upgrade.

It is really hard to continuously monitor all the changes on third-party packages. The best approach is to check each AGW build in CI so that the issue can be caught before it trickles to testing or production .

### Solution

- Add `fresh-deploy-check` GH action
-- Wait for AGW debian package to be built from https://github.com/magma/magma/actions/workflows/agw-build.yml
-- Provision a vanilla Ubuntu host (VM or bare-metal)
-- Install the latest Magma AGW package version <VVVV>  with `sudo apt update` and `sudo apt install magma=<VVVV>`
-- Check and report status of all Magma services (including Sctpd)

- Add `upgrade-deploy-check` GH action
-- Wait for AGW debian package to be built from https://github.com/magma/magma/actions/workflows/agw-build.yml
-- Provision a vanilla Ubuntu host (VM or bare-metal)
-- Install the last "green" build from `fresh-deploy-check` 
-- Check the status of all Magma services (including Sctpd)
-- Install the latest Magma AGW package version <VVVV>  with `sudo apt update` and `sudo apt install magma=<VVVV>`
-- Check and report status of all Magma services (including Sctpd)

**Comment by jheidbrink** [comment]
We might also run the integ tests on that machine.

**Comment by Neudrino** [comment]
Might be done within https://github.com/magma/magma/issues/13685.
