### ISSUE TITLE
datapath: Refactor ARP handling from inout app

### ISSUE THREAD

**Issue by pshelar** [magma/magma#12071]
Create separate module to handle ARP handling
verification: 
Run unit test and integ test after rector is done.

**Comment by sebathomas** [comment]
@pshelar Can you give a few more details about this task? Which ARP handling should be extracted to a separate module?

Is it about the ArpController or ARP handling in one of the other parts of pipelined? It might also be related to #12495, I see there are some reference to ARP in the new EgressController.

**Comment by pshelar** [comment]
I am referring to ARP probes : _get_gw_mac_address_v4(), _get_gw_mac_address_v6(), etc: https://github.com/magma/magma/blob/de09125790a2494b91eba4bbc4cbe1ef08d942ab/lte/gateway/python/magma/pipelined/app/inout.py#L510
