### ISSUE TITLE
Add option to deploy AGW log aggregation

### ISSUE THREAD

**Issue by xjtian** [magma/magma#1207]
Summary
---

Currently on head master, it is possible to aggregate all deployed AGW logging to an Elasticsearch datasink. This is implemented with fluent-bit on the AGW forwarding systemd, MME, and enodebd logs to fluentd running inside Orchestrator, which in turn outputs everything received to Elasticsearch.

For 1.1.0 we should make this deployable via a Terraform variable.

Task List
--

- [ ] Document log aggregation pipeline
- [ ] Document how to turn log aggregation on for a deployed gateway
- [x] Add AWS Elasticsearch domain to example Terraform scripts, guarded by a flag
- [ ] Document how to access VPC Elasticsearch domain

**Comment by ekowtaylor** [comment]
Stale
