### ISSUE TITLE
[Spirent 5G ScaleTest] : Observing Registration and PDU establishment Accept retries with Stateless - Enable 

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#12097]
- Version: 1.7.0-1647047113-6937a1c1
- Affected Subcomponent: AGW service

While performing Spirent Scale test with 200UEs, 4 PDU session, 5 UE/sec attach rate, 12 gNBs, HTTP traffic - 2mbps/UE observing registration and PDU retries. 

With 5 UE, 2 PDU session and 1 gNB observing no retries in registration and PDU session.

Please find the attached logs for 200 UEs, 4 PDU session, 5 UE/sec attach rate, 12 gNBs, HTTP traffic - 2mbps/UE.

[https://app.zenhub.com/files/170803235/98acb5f9-6b1e-46ac-9008-d10867278598/download](https://app.zenhub.com/files/170803235/98acb5f9-6b1e-46ac-9008-d10867278598/download)

[https://app.zenhub.com/files/170803235/a6d15a6e-7ecc-4866-a302-e34189bbbf30/download](https://app.zenhub.com/files/170803235/a6d15a6e-7ecc-4866-a302-e34189bbbf30/download)

[https://app.zenhub.com/files/170803235/d230ed74-45ec-4faa-a6b5-b28308dcbe85/download](https://app.zenhub.com/files/170803235/d230ed74-45ec-4faa-a6b5-b28308dcbe85/download)

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/a04f39a1-c3b6-48f7-9a0d-d45ba28c9d1a)

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/8bcb62a9-0f46-4d57-a2d2-bdc927455c91)

Expected Results : Registration accept - 200, PDU session Establishment accept - 800, Traffic - 2mbps/ UE.

**Comment by panyogesh** [comment]
All related PRs got merged can you please validate the same.
