### ISSUE TITLE
[CI] NMS docker image build failing on master branch

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#12106]
https://github.com/magma/magma/runs/5542475769?check_suite_focus=true#step:4:145

**Comment by ShubhamTatvamasi** [comment]
Build failing after the following PR merge.
https://github.com/magma/magma/pull/12069

**Comment by ShubhamTatvamasi** [comment]
Hi @lucasgonze, NMS docker builds are failing after your PR has been merged. Any idea how to fix this?

**Comment by ShubhamTatvamasi** [comment]
Check this our https://github.com/magma/magma/actions/runs/1982328700

**Comment by ShubhamTatvamasi** [comment]
There is code https://github.com/magma/magma/commit/ba9c553fb7392b5304a0def1ef4bbd047fad9d9a

**Comment by ShubhamTatvamasi** [comment]
Getting fresh error in building
https://github.com/magma/magma/runs/5543156029?check_suite_focus=true#step:4:146

**Comment by ShubhamTatvamasi** [comment]
```
error An unexpected error occurred: "https://registry.yarnpkg.com/string.prototype.trimstart/-/string.prototype.trimstart-1.0.3.tgz: Request failed \"502 Bad Gateway\"".
```

**Comment by lucasgonze** [comment]
Looking into it now.
