### ISSUE TITLE
[TVM Regression] No Response for TAU Request

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#12114]
**Tested magma Build**: 1.7.0-1646792286-35f8c481

Issue: No Response for TAU Request
Expectation:  TAU Accept

**AGW TA Config:**

<img width="410" alt="Screen Shot 2022-03-15 at 12 29 45 AM" src="https://user-images.githubusercontent.com/70725754/158327878-68881936-1d48-4c2e-a005-2273c98729c9.png">

**TAU TCs which has no TAU Accept initiated by AGW are listed below:**

02_Generic_TAU_with_Change_in_TA_on_Connected_Mode

[02_Generic_TAU_with_Change_in_TA_on_Connected_Mode_220309_132014-1.pcapng.zip](https://github.com/magma/magma/files/8251040/02_Generic_TAU_with_Change_in_TA_on_Connected_Mode_220309_132014-1.pcapng.zip)

<img width="1682" alt="Screen Shot 2022-03-15 at 12 25 03 AM" src="https://user-images.githubusercontent.com/70725754/158327180-6e5586c8-8636-45c7-959e-5959b6dec31e.png">

05_Periodic_TAU_with_change_in_TA_in_Idle_Mode

[05_Periodic_TAU_with_change_in_TA_in_Idle_Mode_220309_132145-1.pcapng.zip](https://github.com/magma/magma/files/8251042/05_Periodic_TAU_with_change_in_TA_in_Idle_Mode_220309_132145-1.pcapng.zip)

<img width="1682" alt="Screen Shot 2022-03-15 at 12 26 00 AM" src="https://user-images.githubusercontent.com/70725754/158327340-b6eb28b9-9d1f-4413-8308-0c582b7b9435.png">

08_TAU_for_connected_UEs_in_initialUE_Active_Flag

[08_TAU_for_connected_UEs_in_initialUE_Active_Flag_220309_132317-1.pcapng.zip](https://github.com/magma/magma/files/8251045/08_TAU_for_connected_UEs_in_initialUE_Active_Flag_220309_132317-1.pcapng.zip)

<img width="1543" alt="Screen Shot 2022-03-15 at 12 26 45 AM" src="https://user-images.githubusercontent.com/70725754/158327439-5c4e49e7-4659-409d-837e-2720392a89be.png">

09_TAU_for_connected_UEs_in_initialUE_Inactive_Flag

[09_TAU_for_connected_UEs_in_initialUE_Inactive_Flag_220309_132443-1.pcapng.zip](https://github.com/magma/magma/files/8251049/09_TAU_for_connected_UEs_in_initialUE_Inactive_Flag_220309_132443-1.pcapng.zip)

<img width="1543" alt="Screen Shot 2022-03-15 at 12 26 45 AM" src="https://user-images.githubusercontent.com/70725754/158327539-f2a0e9e0-9fc4-46e1-8cb9-b67e448b36c6.png">

**Comment by rsarwad** [comment]
Tracking area accept is not sent on v1.7. I imported the PR, https://github.com/magma/magma/pull/11795 on v1.7. With this change different issue is observed. 
on reception of Attach Request in initial ue message, mme gets the context based on GUTI and finds that UE is in connected mode and also has valid s1ap_id_key. So mme_app initiates UE context release but s1ap fails to find the ue_ref_p and message gets dropped. 
So I am suspecting cleanup is not happening correctly. 
On sctpd service restart, TAU test cases are working fine.
I am further analyzing the issue

**Comment by rsarwad** [comment]
The issue would be fixed from PRs, https://github.com/magma/magma/pull/11795 and https://github.com/magma/magma/pull/12275

**Comment by arun-magma** [comment]
Hi @ssanadhya : Like to know if this above PRs get merged as part of 1.7 rel ?

**Comment by ssanadhya** [comment]
> Hi @ssanadhya : Like to know if this above PRs get merged as part of 1.7 rel ?

@arun-magma , the above PRs will be part of release 1.7.1

**Comment by ssanadhya** [comment]
> > Hi @ssanadhya : Like to know if this above PRs get merged as part of 1.7 rel ?
> 
> @arun-magma , the above PRs will be part of release 1.7.1

@tmdzk, could you please update this issue once the above PRs have been backported to v1.7 branch.

**Comment by ssanadhya** [comment]
@arun-magma , @rsarwad , please note that the TSC discussed whether we should try to backport fixes to 1.7 (and create 1.7.1) or make them all part of 1.8, and the consensus was to make them all part of release 1.8. No backporting is needed. Closing this issue since fix is already in master.
