### ISSUE TITLE
Explore failing //lte/gateway/c/core/oai/test/amf:amf_encode_decode_test with --config=asan

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#12155]
The AMF test of `test_amf_encode_decode.cpp` fails with an ASAN issue.

## Reproduction

- If you have access to GitHub Codespaces (you should because you are a member of GH Magma)
- Head over to [GitHub Magma Master branch](https://github.com/magma/magma)
- Click on the Green colored `Code` drop down button
- Select the `Codespaces` toggle
- Select `New Codespace` and when asked select 16 core (why not!)
- This will spin up a GitHub codespace that contains my branch
- Once the codespace is up (vs code in browswer) in the terminal window type `bazel test //lte/gateway/c/core/oai/test/amf:amf_encode_decode_test --config=asan` and hit enter. This triggers a bazel build of all necessary components to run the amf_encode_decode_test, then runs the test

**Comment by themarwhal** [comment]
This is a dupe of https://github.com/magma/magma/issues/12163 and can be closed.
