### ISSUE TITLE
mme: //lte/gateway/c/core/oai/test/mme_app_task:mme_procedures_test is flaky

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#12166]
## Repro steps
Run `bazel test //lte/gateway/c/core/oai/test/mme_app_task:mme_procedures_test --runs_per_test=50 `

**Comment by themarwhal** [comment]
First, it would be good to identify exactly which of the 43 tests are flaky. This is also one of our longest tests, it would be good to break them up into separate files.

**Comment by themarwhal** [comment]
I'm hoping that https://github.com/magma/magma/issues/12182 will help us identify which ones are especially flaky and iterate from there.

**Comment by ssanadhya** [comment]
Running this locally, mme_procedures_test is randomly failing on `TestAttachIdleServiceReqDetach` due to a race condition. I am investigating a fix for that. cc: @LKreutzer @themarwhal
