### ISSUE TITLE
[AMF]: Decoding failure for extended UE Security Capabilities

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#12167]
When UE sends complete 8 octets of UE security capability the decoding fails in NAS5G decoder![Ue-Security-Capability-Extended.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/45118aba-553b-4a6b-a50f-f40c556615d9)[https://app.zenhub.com/files/170803235/1ec1f177-3846-4878-86b3-f8d00b5e2875/download](https://app.zenhub.com/files/170803235/1ec1f177-3846-4878-86b3-f8d00b5e2875/download)[https://app.zenhub.com/files/170803235/4639906a-1684-4b06-891b-2686257abdb4/download](https://app.zenhub.com/files/170803235/4639906a-1684-4b06-891b-2686257abdb4/download)

**Comment by sreedharkumartn** [comment]
Raised PR #12179
