### ISSUE TITLE
Bazelify lte/gateway/c/core/oai/test/s6a_task/s6a_recv_async_grpc_messages.cpp

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#12174]
Add `cc_test` for this unit test.

**Comment by themarwhal** [comment]
Is this a new test? @jheidbrink I wonder why I didn't find this by running the diff script.

**Comment by LKreutzer** [comment]
> Is this a new test? @jheidbrink I wonder why I didn't find this by running the diff script.

Seems like it was created in #8982 - ~~maybe the script did not pick it up because the name does not contain "test"?~~

Update: The script output in #12142 seems to contain the file.
