### ISSUE TITLE
Extend diagnostic information in NMS

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#1218]
Current Magma diagnostics information does not include low level LTE metrics. This limits troubleshooting abilities of connection issues. The eNodeB has much of this data.
Helpful additions would be:
1. List view of connected UEs with:
a.    ID (IMSI and IMEI, but RNTI could be used)
b.    DL CQI
c.    UL CQI
d.    DL MCS
e.    UL MCS
f.     DL RSRP
g.    DL RSRQ
h.    DL throughput
i.     UL throughput
1. In “Gateway” view of diagnostics, reporting of PRB resource usage on each connected eNodeB
a.    DL PRB % usage
b.    UL PRB % usage
1.    S1AP (and/or SCTP) call flow trace view
a.    Screen where S1AP NAS messages can be traced and viewed. This helps in troubleshooting attach and handover issues.

**Comment by 119Vik** [comment]
@ulaskozat @lionelgo  would be cool to get your feedback regarding this improvement

**Comment by andreilee** [comment]
UE & session info on our UI is an area in which we'll need to dedicate some time to improving. We've spent some time discussing possible MVPs. @ssanadhya can comment about the S1AP call flow trace. @rckclmbr 

Are there specific troubleshooting use cases that you have in mind here? It can help us get a clearer picture of what is ideal for an MVP.

**Comment by jpad-freedomfi** [comment]
Hi All, 
My main troubleshooting scenarios is diagnosing throughput and/or connection failure issues. The ability to see link quality per UE and histograms of link quality metrics provides a sort of "cell health" view into a deployment. That cover # 1 and # 2 above, then # 3 is more about easy access to S1 logs for attach/connection issues.

Currently for # 1 and # 2 we use the eNB webUI to view what we can, but it is not ideal to have to go direct to each eNB to see these metrics. 

For # 3, we use tcpdump on the AGW interface then open in Wireshark to view. This is again clunky multistep process and have you have to have SSH access to AGW. 

Does that help give a better view of the use case?

**Comment by ekowtaylor** [comment]
Stale
