### ISSUE TITLE
Revising Code Owner Voting Requirements

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#12191]
# Revising Code Owner Voting Requirements

## Problem

As we work on onboarding more code owners/maintainers for the Magma project, we need to revisit the voting guidelines for adding new code owners. The current [code owners](https://github.com/magma/magma/blob/master/CODEOWNERS) are split across the following GitHub teams :

1. Approvers-ci 
2. Approvers-orc8r
3. Approvers-orc8r-infra
4. Approvers-nms
5. Approvers-feg
6. Approvers-cwf
7. Approvers-openwrt
8. Approvers-agw
9. Approvers-agw-python
10. Approvers-agw-c
11. Approvers-agw-sessiond
12. Approvers-agw-mme
13. Approvers-agw-integtests
14. Approvers-agw-pipelined
15. Approvers-xwf
16. Approvers-cwf
17. Approvers-domain-proxy
18. Approvers-showtech
19. Approvers-bazel
20. Approvers-agw-containers
21. Approvers-docs

With the current guideline, a new nomination to add an existing contributor to, say `approvers-agw-mme` team, needs to get enough votes from code owners of all other teams. Not only does this prolong the voting process, it also creates undue burden on code owners who do not have enough context on the contributions in that part of the code base.

## Solution

In this context, @ulaskozat [suggested on Slack](https://magmacore.slack.com/archives/C01Q1T14YJ2/p1647368428003369) that we restrict voting for new members to the specific GitHub team(s) they intend to join. This will allow each existing code owner to confidently vote on the merit of the nomination, since they will have enough context on their contributions.

Specifically, 

1. Each new nomination to add contributor C to team T will require a majority vote from all existing members of team T. 
2. If a member of team T1 wants to become a member of team T2, they need to get majority votes from members of team T2 through a fresh nomination.

**Comment by ssanadhya** [comment]
As per the meeting on [March 21, 2022](https://wiki.magmacore.org/display/HOME/March+21%2C+2022+Meeting), the proposal is accepted with next steps to figure out the exact implementation path. @ssanadhya to work 
- with @wendallkaters to document the process for future nominations
- with existing code owners to prune the list of [approver teams,](https://github.com/orgs/magma/teams?query=approvers) if possible

**Comment by talkhasib** [comment]
Does it make sense to reduce the number of teams to manageable set (significantly less than 21 teams)

**Comment by ssanadhya** [comment]
> Does it make sense to reduce the number of teams to manageable set (significantly less than 21 teams)

Absolutely!

**Comment by ssanadhya** [comment]
## New code-owner voting process

Any nomination to add contributor C to approvers team T should be posted on #governance-codeowners public Slack channel, with the following template:

```
I would like to nominate _____ (Slack: ____ GitHub: ____) to be part of approvers-_____ to own magma/_____ . 
She/He has been contributing to <component name and highlights).
Here is a list of:
Committed PRs: 
Closed Issues:
Review History:
Other highlights:
```

From there, @wendallkaters  can start a vote on the Slack channel for existing members of team T with a week's notice. Each existing member of team T has the option to vote Yes or No (no option to Abstain here). If a nomination receives a majority "Yes" vote, they get added to the approvers' team T.

**Comment by ssanadhya** [comment]
Since we have tested the above process for several recent nominations, I have updated the new code owner voting process on [Community Structure and Governance Wiki](https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance). cc: @wendallkaters

**Comment by ssanadhya** [comment]
In an attempt to reduce the number of [approver teams](https://github.com/orgs/magma/teams?query=approvers), I propose to make the following changes:

1. Merge `approvers-showtech`, `approvers-agw-c` and `approvers-agw-python` into `approvers-agw`
2. Merge `approvers-openwrt` into `approvers-cwf`
3. Update the [CODEOWNERS](https://github.com/magma/magma/blob/master/CODEOWNERS) file accordingly

**Comment by ssanadhya** [comment]
Since PR #12475 is merged, deleted the deprecated teams from the [approvers team list](https://github.com/orgs/magma/teams?query=approvers)
