### ISSUE TITLE
Come up with a scalable solution for S3 cache population

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#12210]
We want to populate cache in S3 (or anywhere) so that they can be easily pulled in by devs and GitHub Codespaces

Some commands we want to cache

- bazel test //...
- bazel build //...
- bazel test //orc8r/gateway/c/... //lte/gateway/c/... --config=asan

**Comment by themarwhal** [comment]
@LKreutzer Also this too. if you already have a master task for cache related things, please close this out and point it to the other task :D

**Comment by LKreutzer** [comment]
> @LKreutzer Also this too. if you already have a master task for cache related things, please close this out and point it to the other task :D

Thanks for pointing this issue out to me! This should be covered by the work we are planning to do for https://github.com/magma/magma/issues/12458 - but I will keep it open for now. Currently the plan is that the s3 bazel-remote cache will be publicly read-only accessible, which could include the application in the codespaces and elsewhere in the future.

**Comment by LKreutzer** [comment]
These commands are already covered by the workflows and the remote cache that is currently set up.
