### ISSUE TITLE
[AMF]: Crash observed when DNN Length is incorrectly encoded by UE

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#12279]
Following are the steps :
1. DNN IE : DNN Content Length + DNN Contents
2. DNN Content Length = sizeof(unsigned char) + strlen("DNN Contents") 
    where sizeof(unsigned char) stores the length of DNN.
    If somehow this value is not encoded correctly by UE then memcpy will
    crash. Attaching the Packet snapshot with wrong and correct DNN. In any case crash should be avoided by putting length checks.

 ![Issue-With-DNN-Value.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/6b6a46ff-a033-4bda-9111-431dfae5143c)![TVM-Simulator-Working-DNN-Output-March-25.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/1eeab831-1be3-4169-b20f-5210c9a54f9f)

**Comment by panyogesh** [comment]
[https://app.zenhub.com/files/170803235/2ec1f089-265e-49aa-9123-7b30b81d7425/download](https://app.zenhub.com/files/170803235/2ec1f089-265e-49aa-9123-7b30b81d7425/download)

**Comment by sreedharkumartn** [comment]
Raised PR #12309
