### ISSUE TITLE
Make the magma code base reuse compliant

### ISSUE THREAD

**Issue by maxhbr** [magma/magma#12270]
# Make the magma code base reuse compliant

## Problem

Currently the files in the repository are not consistently equipped with a license header. And at the same time there is some copied third-party in the source tree. 

## Solution

The [reuse project](https://reuse.software/) defines a standard on how to add the license and copyright information in a lightweight way to the repository. This includes the following steps:

1. Adding machine and human readable statements to the file headers. These might look like:
    ```
    # SPDX-FileCopyrightText: The Magma Authors
    #
    # SPDX-License-Identifier: BSD-3-Clause
    ```
1. Add the license information for files not supporting headers via one of the alternative means, e.g. via `.license` files or `.reuse/dep5`.
1. Add all the relevant licenses to the `LICENSES/` folder
1. Require an CI check, that validates the conformance

There are also tools to support the above steps, e.g. by pulling the necessary licenses or by adding the header.

### Open Questions
- [ ] can we drop the existing license headers?

## Non-goals

This just affects code checked into the repository and is not relevant for other third party used as dependencies.

**Comment by lucasgonze** [comment]
https://github.com/hashicorp/copywrite would have been useful, but for now we don't seem to have anybody interested in doing the work.
