### ISSUE TITLE
Failed to start Magma eventd service

### ISSUE THREAD

**Issue by HanyHeikal** [magma/magma#1230]
### Your Environment

- **Version: Latest version
- **Affected Component: Access Gateway
- **Affected Subcomponent: AGW service
- **Deployment Environment:  local docker-compose (orc8r)

### Describe the Issue

MME is Not Connected

**To Reproduce**
 am trying to run magma software on my MacBook laptop,
I followed the installation instruction as shown in the following link:
https://facebookincubator.github.io/magma/docs/next/basics/quick_start_guide
**Expected behavior**

**Screenshots**
This is the error that keeps coming in the "/var/log/syslog"

Feb 19 01:33:23 magma-dev systemd[1]: Stopped Magma eventd service.
Feb 19 01:33:23 magma-dev systemd[1]: Starting Magma eventd service...
Feb 19 01:33:23 magma-dev eventd[6213]: Error resolving 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:23 magma-dev eventd[6213]: 19 Feb 01:33:23 ntpdate[6213]: Can't find host 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:23 magma-dev eventd[6213]: 19 Feb 01:33:23 ntpdate[6213]: no servers can be used, exiting
Feb 19 01:33:23 magma-dev systemd[1]: magma@eventd.service: Control process exited, code=exited status=1
Feb 19 01:33:23 magma-dev systemd[1]: Failed to start Magma eventd service.
Feb 19 01:33:23 magma-dev systemd[1]: magma@eventd.service: Unit entered failed state.
Feb 19 01:33:23 magma-dev systemd[1]: magma@eventd.service: Failed with result 'exit-code'.
Feb 19 01:33:28 magma-dev systemd[1]: magma@eventd.service: Service hold-off time over, scheduling restart.
Feb 19 01:33:28 magma-dev systemd[1]: Stopped Magma eventd service.
Feb 19 01:33:28 magma-dev systemd[1]: Starting Magma eventd service...
Feb 19 01:33:28 magma-dev eventd[6224]: Error resolving 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:28 magma-dev eventd[6224]: 19 Feb 01:33:28 ntpdate[6224]: Can't find host 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:28 magma-dev eventd[6224]: 19 Feb 01:33:28 ntpdate[6224]: no servers can be used, exiting
Feb 19 01:33:28 magma-dev systemd[1]: magma@eventd.service: Control process exited, code=exited status=1
Feb 19 01:33:28 magma-dev systemd[1]: Failed to start Magma eventd service.
Feb 19 01:33:28 magma-dev systemd[1]: magma@eventd.service: Unit entered failed state.
Feb 19 01:33:28 magma-dev systemd[1]: magma@eventd.service: Failed with result 'exit-code'.
Feb 19 01:33:31 magma-dev magmad[4601]: ERROR:root:GetServiceInfo Error for eventd! [StatusCode.DEADLINE_EXCEEDED] Deadline Exceeded
Feb 19 01:33:33 magma-dev systemd[1]: magma@eventd.service: Service hold-off time over, scheduling restart.
Feb 19 01:33:33 magma-dev systemd[1]: Stopped Magma eventd service.
Feb 19 01:33:33 magma-dev systemd[1]: Starting Magma eventd service...
Feb 19 01:33:34 magma-dev eventd[6231]: Error resolving 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:34 magma-dev eventd[6231]: 19 Feb 01:33:34 ntpdate[6231]: Can't find host 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:34 magma-dev eventd[6231]: 19 Feb 01:33:34 ntpdate[6231]: no servers can be used, exiting
Feb 19 01:33:34 magma-dev systemd[1]: magma@eventd.service: Control process exited, code=exited status=1
Feb 19 01:33:34 magma-dev systemd[1]: Failed to start Magma eventd service.
Feb 19 01:33:34 magma-dev systemd[1]: magma@eventd.service: Unit entered failed state.
Feb 19 01:33:34 magma-dev systemd[1]: magma@eventd.service: Failed with result 'exit-code'.
Feb 19 01:33:39 magma-dev systemd[1]: magma@eventd.service: Service hold-off time over, scheduling restart.
Feb 19 01:33:39 magma-dev systemd[1]: Stopped Magma eventd service.
Feb 19 01:33:39 magma-dev systemd[1]: Starting Magma eventd service...
Feb 19 01:33:39 magma-dev eventd[6236]: Error resolving 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:39 magma-dev eventd[6236]: 19 Feb 01:33:39 ntpdate[6236]: Can't find host 1.ntp.vip.facebook.com: Name or service not known (-2)
Feb 19 01:33:39 magma-dev eventd[6236]: 19 Feb 01:33:39 ntpdate[6236]: no servers can be used, exiting
Feb 19 01:33:39 magma-dev systemd[1]: magma@eventd.service: Control process exited, code=exited status=1
Feb 19 01:33:39 magma-dev systemd[1]: Failed to start Magma eventd service.
Feb 19 01:33:39 magma-dev systemd[1]: magma@eventd.service: Unit entered failed state.
Feb 19 01:33:39 magma-dev systemd[1]: magma@eventd.service: Failed with result 'exit-code'.

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by xjtian** [comment]
This is a bug @remo5000 will get to with the eventd service, but it shouldn't block MME in any way. Since this service is under active development and not integrated into the AGW yet, you can treat this as a benign yet annoying logspam.

**Comment by amarpad** [comment]
If the MME doesn't connect please upload a pcap so we know there is a SCTP handshake and an S1 message exchange at a minimum. As Jacky notes eventd is benign

**Comment by ardzoht** [comment]
Can you also share the output of `sudo journalctl -n 50 -u magma@mme`? I'm curious on the ongoing status of the service as we have systemd dependencies on other AGW services as well.

**Comment by HanyHeikal** [comment]
Thank you all for your response, this is definitely highly appreciated.
Please see all the requested information below:

vagrant@magma-dev:~$ sudo journalctl -n 50 -u magma@mme
-- No entries --

![virtualbox](https://user-images.githubusercontent.com/1537841/74998151-334dbb00-5415-11ea-99e0-a12742adf324.png)
![wireshark](https://user-images.githubusercontent.com/1537841/74998158-347ee800-5415-11ea-8dc0-0c9e9d7ffd2e.png)
![nms_agw_console](https://user-images.githubusercontent.com/1537841/74998159-35b01500-5415-11ea-8c23-ce6ee45e7b31.png)

[wireshark.pcapng.zip](https://github.com/facebookincubator/magma/files/4233953/wireshark.pcapng.zip)


> This is a bug @remo5000 will get to with the eventd service, but it shouldn't block MME in any way. Since this service is under active development and not integrated into the AGW yet, you can treat this as a benign yet annoying logspam.
