### ISSUE TITLE
Cannot change QoSProfile for a policy

### ISSUE THREAD

**Issue by abhinavbhagwat** [magma/magma#12307]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6.1
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator pod/service 
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

**To Reproduce**
1. On NMS UI, Make sure you have a few QoS Profiles defined under Traffic>Policies>Profiles
2. On NMS UI go to Traffic>Policies>Policies
3. Edit a existing policy and change the QoS Profile for it. Say earlier it was Policy1 now make it Policy2.
4. Click Save.
5. Open the same policy for edit again. You can see that it still points to Policy1 and not the updated Policy2.

**Expected behavior**
The policy change should be applied and new policy should be visible in the UI.

**Comment by sebathomas** [comment]
Just confirmed this bug on a local NMS on current master.

It's strange that the PUT policies call is successful but the subsequent GET still returns the old profile, and refreshing the site doesn't help.

**Comment by sebathomas** [comment]
Looking at the DB after trying out the request locally, it seems that the association to the new QoS profile is persisted in the DB, but the association to the old profile is not deleted.
