### ISSUE TITLE
Datapath: qos: move UP QoS class to OVS port

### ISSUE THREAD

**Issue by pshelar** [magma/magma#12318]
today pipelineD QoS configures UP traffic QoS policies on SGi interface, we could move it to dev 'gtp_br0' for NATed datapath. For Non-NAT no changes needed.
This would improve performance by dropping rate-limited packet early.

This task involves:

Make these changes in QoS lib in pipelineD
Run integ tests to validate AMBR is applied as expected.

**Comment by vikramgreddy** [comment]
@pshelar, For UP traffic on SGi interface, traffic on dev gtp_br0 will be ingress on the kernel.
A traffic classifier can be applied to the Egress. So, it would not be possible to move UP traffic QoS policies on SGi interface to dev gtp_br0.

**Comment by ssanadhya** [comment]
@pshelar @vikramgreddy , can we close this issue or are you exploring an alternate approach for this issue?

**Comment by pshelar** [comment]
right, lets close this.
