### ISSUE TITLE
Split MME service into MME and AMF services.

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#12324]
# Split MME into MME and AMF services

## Problem

Magma MME service currently hosts both 4G and 5G call flows, where sctp task running as part of the MME service routes 4G and 5G calls towards S1AP or NGAP tasks based on the PPID. In MME service, there are 2 threads for NGAP and AMF that are optionally run as part of the 5G configurations upon starting the MME service.

Although, this was the quickest path for including 5G SA support in Magma codebase, it bloats the MME service and it also leads to confusion in the community.

## Solution

- Spin off AMF/NGAP from MME service into its own service as a first class citizen.
- Control the start of the services as part of systemd or helm charts (non-containerized or containerized, respectively).
- Move sctp task from MME service to SCTPD service and route calls to/from MME or AMF service based on PPID at sctpd
- Change unix socket to tcp/ip socket for GRPC calls between sctpd and MME as well as sctpd and AMF services.

## Non-goals

Anything specifically excluded from the concept

**Comment by panyogesh** [comment]
There is one more change I would suggest if applicable, regarding the layout of ASN files.  Idea is to have all auto-generated files committed (no auto-generation) and layered in 3 directories :
1. common/ (common for both 4G and 5G)
 2. s1ap (Files with S1ap_*)
 3. ngap (Files with Ngap_*)
