### ISSUE TITLE
MME: unexpected restart of service

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#12321]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:1.7.0-1647281412-bc5fa02b
- **Affected Component:AGW
- **Affected Subcomponent:MME, Pipelined
- **Deployment Environment:Bare-metal (AGW)

### Describe the Issue

We are using an installation made from the Master because of some features we need and are not present on the current release 1.6.1 and a few days ago we had an issue, another operator failed and we detect that his clients were trying to connect to our network, and not sure, but it seems that our AGW collapse because of that, it restarted at least 3 times until we setup a restriction for the PLMN of the other operator  and that's when it stopped restarting.

**Expected behavior**
It should not fail if some other UE try to connect to AGW.

**Additional context**
Logs: 
https://drive.google.com/drive/folders/1Udt7gOsaaYEBmrSimfTSYO5pbYV9Sr_4

**Comment by javieraubert** [comment]
Update: we install a new version compiled from Master, the 1.8.0-1648772874-62caa3c3, and it has the same issue.

**Comment by hfvilca** [comment]
Version: 1.8.0-1648772874-62caa3c3

I have the same reboot problem, here the logs: 

https://drive.google.com/drive/folders/15WERAJmOmmfGDyDmqnwFtCxdGU4hUsee
