### ISSUE TITLE
Cannot build feg docker-compose because of docker-compose versions behavior conflict

### ISSUE THREAD

**Issue by malcolmmadsheep** [magma/magma#12356]
**Environment**

- docker-compose v1.25.0

When run `cd $MAGMA_ROOT/feg/gateway/docker && ./build.py -m` docker-compose fails with errors `&.depends_on contains an invalid type, it should be an array`.

It happens because [each service uses dependency on `tg-agent-bit`](https://github.com/magma/magma/blob/master/feg/gateway/docker/docker-compose.yml#L34-L37) which was valid behavior for docker-compose v2, but in v3 we can use only array of strings as a `depends_on` value.

As I understand we need to make sure that `td-agent-bit` service is healthy before run all other services. Probably, it can be fixed with some trick that are describe in [Control startup and shutdown order in Compose](https://docs.docker.com/compose/startup-order/) article.

**Solution**: upgrade to docker-compose v1.29.2

**Comment by uri200** [comment]
Note this dependency was introduced in the PR below by @119Vik. He will be able to provide more context

https://github.com/magma/magma/pull/6361

However, so far, magma support for docker-compose is at 1.29. So you should be using that version.

**Comment by malcolmmadsheep** [comment]
I upgraded to `docker-compose@1.29.2` and it works. I guess, we can close issue.

But I'm wondering if it works as we expect it to work. What if this option was added to back compatibility, but it takes only service key and do not really wait for service to be healthy?
