### ISSUE TITLE
Verify OAI-Jenkins job can pass with build feature `mme_oai`

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#12355]
The OAI jenkins job tests a flavor of MME that is built with FEATURE="mme_oai"

For code pointers, 
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+mme_oai&patternType=literal

We need ensure that we can 
1. build the MME binary with the feature (which essentially just sets the following variables: `-DS6A_OVER_GRPC=False -DEMBEDDED_SGW=False`)
2. successfully run OAI-Jenkins job on CI

**Comment by nstng** [comment]
See https://github.com/magma/magma/pull/12365 for one approach to make mme compile with Bazel using `-DS6A_OVER_GRPC=False -DEMBEDDED_SGW=False`.

**Comment by nstng** [comment]
See https://github.com/magma/magma/pull/12370 for cleanup that makes mme compile with Bazel and `-DS6A_OVER_GRPC=False -DEMBEDDED_SGW=False`. It should still be discussed if we want to build mme with Bazel using all source files (see #12365).

**Comment by nstng** [comment]
outdated - already implemented
