### ISSUE TITLE
MME: Shutdown request for association id

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#12378]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version: 1.8.0-1648772874-62caa3c3
- **Affected Component:AGW
- **Affected Subcomponent:MME
- **Deployment Environment:Bare-metal (AGW)

### Describe the Issue

Our enb send an alarma of S1 failure, we check logs and see this message at the time of the issue:

668620 Sat Apr 02 02:32:48 2022 7FB7E09EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :3654    SCTP disconnection request for association id 14, Reset Flag = 0. Connected UEs = 2714 Num elements = 18
668621 Sat Apr 02 02:32:48 2022 7FB7E09EB700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :3714    Marked enb s1 status to Shutdown, attached to assoc_id: 14

The S1 interfaces of our enb do not restore tu normal until we restart the sctpd service on AGW.

**To Reproduce**
Not sure how to reproduce.
[AGW2_3_02042022_1422_FAIL_MME.log](https://github.com/magma/magma/files/8403434/AGW2_3_02042022_1422_FAIL_MME.log)
[AGW2_3_02042022_1422_FAIL_syslog.1.log](https://github.com/magma/magma/files/8403435/AGW2_3_02042022_1422_FAIL_syslog.1.log)

**Additional context**
Logs

**Comment by edaspb** [comment]
The weird thing here is `Connected UEs = 2714 ` At that moment there were not more than 50 subscribers on the AGW.
