### ISSUE TITLE
Navigation Usability Fix - breadcrumbs

### ISSUE THREAD

**Issue by iirisgao** [magma/magma#12449]
## Problem

The NMS navigation isn't intuitive to help users find the information they need because:

- The order of navigation items doesn’t follow any particular logic.
- There's no easy entry point to go back up the hierarchy (ex Subscribers / this subscriber).
- With the menu-tab-subtab structure, the hierarchy is redundant for pages that don’t have multiple tabs.
- It doesn’t make sense to add a network to a network, that hierarchy isn’t logically correct.
- There's unnecessary information in the top bar (version info). Top bar uses up vertical space, but doesn’t add any context.
- The network switcher is difficult to discover and understand. 

See [screenshots](https://www.figma.com/file/ejhNLJ8Nwl6exgY7C9RiqD/?node-id=3%3A11) from the usability audit that capture the issues mentioned above.

### Navigation framework
There will be three levels of hierarchy in the navigation: primary, secondary, and tertiary navigation. The tertiary navigation is optional. It is used when a page has sub-sections. 
<img width="1440" alt="Navigation" src="https://user-images.githubusercontent.com/88680700/163069381-77e271f3-82ea-447e-ab30-e82597707c74.png">

### Network switcher
The Network switcher will be a global action on the top right corner. It is accessible on each page. It gives users the ability to:
- See the current network
- Open the dropdown menu and switch to another network
- Add a new network (available to super users)
- Manage networks
<img width="1440" alt="_ Network - Network Indiv - LP" src="https://user-images.githubusercontent.com/88680700/163069437-6135f9d6-1795-4af5-a15f-79e54b4b4852.png">
 

### Primary navigation

- By default, the nav menu is collapsed and shows icons only. 
- When hovering on the nav menu, it will expand to show all labels. The hover state of the menu appears on top of the page and doesn’t affect the main content. 
- Remove Traffic from the primary nav. Add three additional items: Policy, APN, and Data Plans. (They were previously under the Traffic page.)

<img width="1440" alt="Navigation_Default" src="https://user-images.githubusercontent.com/88680700/163069533-8bd410c3-8240-49ce-807d-38387fb9071e.png">
<img width="1440" alt="Navigation_Expanded" src="https://user-images.githubusercontent.com/88680700/163069547-c50515aa-96fa-4826-a0d4-a3957d58ab86.png">

### Breadcrumb
The breadcrumb shows the full path of the workflow. For example, on the Equipment page, the user clicks on the eNodeB tab, and then clicks on one of the eNodeB to view details. The breadcrumb looks like this: Equipment > eNodeB > eNodeB_Name

<img width="1440" alt="Navigation_Expanded" src="https://user-images.githubusercontent.com/88680700/163069599-fa818c97-e551-4fa5-a5c5-f6fc864a231d.png">

## Reference
[Figma](https://www.figma.com/file/ejhNLJ8Nwl6exgY7C9RiqD/Navigation-%5BUsability-Fix%5D?node-id=539%3A25652) (V3 is the latest version)

**Comment by iirisgao** [comment]
Email irisgao@fb.com for access to docs.

**Comment by Neudrino** [comment]
Two part implemented in #12537 an d#12541. The breadcrumbs are currently unimplemented.

**Comment by thmsschmitt** [comment]
We should try to use https://github.com/icd2k3/use-react-router-breadcrumbs for the breadcrumbs
