### ISSUE TITLE
[AMF]: Configuration validation on 1.7.1 

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#12442]
Basic AMF Configuration through orc8r validation on top of 1.7 using  PR : https://github.com/magma/magma/pull/12440/commits

**Comment by panyogesh** [comment]
Basic sanity done #12440. Order of commits of the 5G SA PR in 1.7 branch 

Order of commit for 5G PRs
1.  https://github.com/magma/magma/pull/12023
2.  https://github.com/magma/magma/pull/11121
3.  https://github.com/magma/magma/pull/11454
4.  https://github.com/magma/magma/pull/12215
5.  https://github.com/magma/magma/pull/12099
6.  https://github.com/magma/magma/pull/11995
7.  https://github.com/magma/magma/pull/12272
8.  https://github.com/magma/magma/pull/12020
9.  https://github.com/magma/magma/pull/12338
10. https://github.com/magma/magma/pull/12120
11. https://github.com/magma/magma/pull/12179
12. https://github.com/magma/magma/pull/12309
13. https://github.com/magma/magma/pull/12281
14. https://github.com/magma/magma/pull/12339

**Comment by sreedharkumartn** [comment]
Validated PR #12440 with Unit Test and basic registration, pdu session accept, pdu session release and deregistration in stateful and stateless mode with UERANSIM.
- Unit Test:
![image](https://user-images.githubusercontent.com/89978170/162943967-5e05def4-cfd0-444c-a063-358184127782.png)

- PCAP and mme log in Stateful mode.
[https://app.zenhub.com/files/170803235/ce8095d6-9357-4a25-9535-a7ef3f24a557/download](https://app.zenhub.com/files/170803235/ce8095d6-9357-4a25-9535-a7ef3f24a557/download)

- PCAP and mme logs in Stateless mode.
[https://app.zenhub.com/files/170803235/ef266907-2595-44b0-b521-0ea6d5eff5a7/download](https://app.zenhub.com/files/170803235/ef266907-2595-44b0-b521-0ea6d5eff5a7/download)

**Comment by Rajeshs23** [comment]
Tested pr #12442 with oaignb simulator and running as expected . Please find logs and pcap below.
[https://app.zenhub.com/files/170803235/1221dfb0-b3da-4ae3-8211-3935ebffb2f3/download](https://app.zenhub.com/files/170803235/1221dfb0-b3da-4ae3-8211-3935ebffb2f3/download)

**Comment by panyogesh** [comment]
1.  #12023 : fix(sessiond): Send grpc status code to AMF when duplicate session re…
2.  #11121 : fix(amf): Enhancement of logs during UE authentication failure
3.  #11454 : Re-Attempt Authentication during subscriberdb lock
4.  #12215 : fix(pipelined): PROXY_TAG_REG value is changed to reg12 so that overlaps are prevented
5.  #12099 : fix(amf): fix for test_amf_stateless in Bazel test
6.  #11995 : feat(amf): Added Implicit Deregistration Support
7.  #12272 : fix(amf): amf_stateless_test and amf_procedure_test in Bazel test 
8.  #12020 : fix(amf): Configured policy ambr and QFI related fix
9.  #12338 : fix(pipelined): pipelined_cli.py not working with debug qos option 
10. #12120 : fix(amf): handling sessiond pdu session failure response
11. #12179 : fix(amf): Decoding failure for extended UE Security Capabilities
12. #12309 : fix(amf): Crash observed when DNN Length is incorrectly encoded by UE
13. #12281 : feat(mme): SCTP Shutdown for NGAP
14. #12339 : chore(pipelined): blocking of local ipv6 addresses is supported

**Comment by panyogesh** [comment]
1.  #12023 : fix(sessiond): Send grpc status code to AMF when duplicate session re…
2.  #11121 : fix(amf): Enhancement of logs during UE authentication failure
3.  #11454 : Re-Attempt Authentication during subscriberdb lock
4.  #12215 : fix(pipelined): PROXY_TAG_REG value is changed to reg12 so that overlaps are prevented
5.  #12099 : fix(amf): fix for test_amf_stateless in Bazel test
6.  #11995 : feat(amf): Added Implicit Deregistration Support
7.  #12272 : fix(amf): amf_stateless_test and amf_procedure_test in Bazel test 
8.  #12020 : fix(amf): Configured policy ambr and QFI related fix
9.  #12338 : fix(pipelined): pipelined_cli.py not working with debug qos option 
10. #12120 : fix(amf): handling sessiond pdu session failure response
11. #12179 : fix(amf): Decoding failure for extended UE Security Capabilities
12. #12309 : fix(amf): Crash observed when DNN Length is incorrectly encoded by UE
13. #12281 : feat(mme): SCTP Shutdown for NGAP
14. #12339 : chore(pipelined): blocking of local ipv6 addresses is supported

**Comment by panyogesh** [comment]
Closed as 1.7.1 is not the primary release. All PRs are already part of master.
