### ISSUE TITLE
Usage Reporting: Observing Grafana metrics not being updated when Multiple PDU session test case is triggered.

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#12497]
- Version: 1.8.0-1650031149-22e7bef6 
- Affected Component: NMS

While performing Scale Test in Spirent with 1UEs, 4PDU, UDP ULDL 2.2mbps traffic, it is observed that for UEs with 1 PDU graph being reflected. But UEs with other 3 PDU, grafana metrics graph is not being updated [ Reflecting 0 MBPS - Data Usage IN/OUT and 0MBPS - Throughput IN/OUT]  

Expected behavior
For 1 UEs and all 4 PDU session Grafana metrics should reflect/update the graphs.

Please find the attached screenshot:
IMSI001019976545661 with internet1  ---> being updated
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/d1050d57-010e-4962-b166-c06f030429e8)

IMSI001019976545661 with internet2/internet3/internet4 ----> is not updating
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/9211187b-6f56-4941-8534-9a53e9cf56ea)

**Comment by anusha-konda** [comment]
Hi Apeksha
Can you share syslog of AGW to know if the stats for multiple sessions is reported to orc8r.
Please enable grpc_playload: true in the yaml files and share the syslog.

**Comment by apekshapk** [comment]
Hi,
Please find the attached logs and pcap
[https://app.zenhub.com/files/170803235/41884775-fad1-4c70-98fd-82baed9840f0/download](https://app.zenhub.com/files/170803235/41884775-fad1-4c70-98fd-82baed9840f0/download) 

[https://app.zenhub.com/files/170803235/46d81f09-193a-44ca-82eb-e2387c96ab6d/download](https://app.zenhub.com/files/170803235/46d81f09-193a-44ca-82eb-e2387c96ab6d/download)

**Comment by mehul-jindal-wavelabs** [comment]
We've established 2 PDU sessions w.r.t same U.E. and sent 50MB data through each session using trf server. We've observed the same being reflected correctly in graphana. Corresponding screenshots are attached herewith along with those of the commands used.
PDU session info:
![PDU sessions](https://user-images.githubusercontent.com/88073743/176628017-8d3b07d4-0020-453f-85da-f5ae10d8f324.png)
Usage before sending the traffic:
![before sending any data](https://user-images.githubusercontent.com/88073743/176629002-65904183-cc85-472f-9558-18d4ff2247c6.png)
Session 1, traffic command
![command for the data sent through first session](https://user-images.githubusercontent.com/88073743/176628228-8763f177-52b1-40a8-bd4f-88987526a8a8.png)
Usage after 50MB through session 1:
![after 50mb sent from 1st session](https://user-images.githubusercontent.com/88073743/176628469-371d90f1-c222-4b79-8ac2-e8b186f4d537.png)
Session 2, traffic command:
![command for data sent through second session](https://user-images.githubusercontent.com/88073743/176628522-708b72ee-acb9-4d1d-89de-371d9094c921.png)
Usage after 50MB through session 2:
![after 50mb sent through 2nd session](https://user-images.githubusercontent.com/88073743/176628578-6f4e61bb-8e4a-47b3-8074-eb6d69cb6abb.png)
Graphana:
![graphana-metrics](https://user-images.githubusercontent.com/88073743/176629752-5918e101-0452-424e-a429-0f77b5953bba.png)

**Comment by apekshapk** [comment]
Tested the scenario traffic scenario for with 1UE with 2 session, observing graph being reflected for both the PDU sessions. Attaching the Snapshot of the same. 
For IMSI001019976545660 with DNN - internet1
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/01c993b2-f990-428c-a2f4-7f3a3804bfd4)
For IMSI001019976545660 with DNN - internet2
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/2b34435f-a3ca-474f-acf2-fa103fa01398)

**NOTE: Closing the bug as the issue is resolved now.**
