### ISSUE TITLE
Towards a Bazel-built AGW

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#12519]
This issue tracks efforts and discussions around building AGW binaries and releases with Bazel.

Currently, we ship Ubuntu [packages](https://github.com/magma/magma/blob/33cd34820810ed71947aca9a6011182496c71324/lte/gateway/fabfile.py#L73) and an [installation script](https://github.com/magma/magma/blob/ac184db9e164bb38d7c3916e1b5fbc7a31738a13/lte/gateway/deploy/agw_install_ubuntu.sh) to install the AGW on a bare metal Ubuntu machine (There are also ongoing efforts of creating different release artifacts like [Docker containers](https://github.com/magma/magma/blob/69781968eb4a3d3afb23c2177c4fe6c46e4b4b43/lte/gateway/docker/readme.md) or [Snap packages](https://github.com/canonical/magma-access-gateway-snap)). The Ubuntu packages and the binaries they contain are currently built completely without Bazel.

Most of our binaries can already be built with Bazel. **The long-term goal is to create Ubuntu packages using only the bazel-built binaries**, and if feasible build some release artifacts (docker images, ...) with Bazel as well.

We therefore **need to include the bazel-built binaries in the LTE Integ test**. The first component will be MME: https://github.com/magma/magma/issues/12057. More components can follow after that.

We plan to duplicate the LTE Integ Test workflow, and in the copy migrate more and more components to Bazel. Until that migration is complete, releases won't contain any Bazel-built binaries. After the migration, we will work towards releases containing only the Bazel-built binaries. When that switch is complete, we can remove the Makefiles and the "old" LTE Integ Test workflow.

We found that one **pre-requisite for the LTE Integ Test with bazel-built binaries is the availability of a remote cache** that can be used by CI runners. The efforts towards a remote cache are tracked in https://github.com/magma/magma/issues/12458

**Comment by nstng** [comment]
already done in other issues - e.g., #13749. Docker builds are not yet bazelified, but this is actually under discussion in the community (#14313).
