### ISSUE TITLE
[AMF]: Multiple times GNB restart verification

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#12512]
Test scenario:

This was an overnight run where the gNB and UE processes were restarted 1000 times, and the test made sure that the UE registered, got an IP address, and was able to ping an external address. The test passed for 997 times, but failed three loops sequentially.

Failure analysis:

I captured a pcap for the entire run, and by reviewing my test logs (magma5g.log at 2022-04-13 19:55:06,439) I was able to identify the failures as attempts 943, 944, and 945. I exported the pcap (eth1.pcap) to a text file (eth1_1000_cycles.txt) and grepped on "InitialUEMessage, Registration request" and saved that (with line numbers from the original file) to eth1_1000_cycles_1.txt. Looking for line number 943 as the last passing cycle (my test started counting at 0, so it's 942+1) I saw that the last passing registration was line number 4178026 in the pcap text file. This corresponded to packet number 37039, which I found in Wireshark. At the end of the cycle, I saw that the gNB closed the SCTP connection with SHUTDOWN at packet 37068. On the next cycle the rebooted gNB tries to connect to the MME with NGSetupRequest, but the SCTP connection is closed down with ABORT. This happens three times in a row - thus the three failures from my test. It starts working again at packet 37097. The test failure occurred at 19:55:06, but the magma-5g-1 machine is running on GMT, so that corresponds to 23:55:06. I looked at the MME log and found that the MME restarted at 23:56:19. I grepped syslog.1 on "mme" (syslog_1_mme.txt) and found that the mme received a SIGINT or SIGTERM at 23:54:13. It looks like the cause was at 23:54:07 "sctpd_connection.cpp: accept error: Too many open files.".

**Comment by pratibhag1234** [comment]
We have restarted gNB and UE processes 1000 times and UE is able to get an ip address each time successfully.
Please refer to the attached mme log below.
### [https://app.zenhub.com/files/170803235/6c709e30-80b5-4343-b582-a22013248695/download](https://app.zenhub.com/files/170803235/6c709e30-80b5-4343-b582-a22013248695/download)
