### ISSUE TITLE
[Regression Issue]: AMF is processing the Registration Request even if the requested MNC and subscribed MNC are not matching

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#12536]
- Version: 1.8.0-1650484523-8f31585c
- Affected Component: Access Gateway

Subscribed IMSI MNC: 001 MCC: 01 MSIN: 9976545660
Processing with MNC: 001 MCC:019 MSIN: 976545660
Still it is processing with the Registration Request and sending OTH request

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/45d404a0-f8dd-4a29-a9a9-2d2b8c9b6e07)

Please find the attached pcap and logs for the same.

[https://app.zenhub.com/files/170803235/ede17b1e-0916-411d-8b8c-adcb15aca262/download](https://app.zenhub.com/files/170803235/ede17b1e-0916-411d-8b8c-adcb15aca262/download)

[https://app.zenhub.com/files/170803235/79598e96-6527-4f64-93d9-55e0d5da5cce/download](https://app.zenhub.com/files/170803235/79598e96-6527-4f64-93d9-55e0d5da5cce/download)

[https://app.zenhub.com/files/170803235/c3ace985-d8e3-4582-8883-aabe61afd289/download](https://app.zenhub.com/files/170803235/c3ace985-d8e3-4582-8883-aabe61afd289/download)

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/88bee53a-6778-4aff-9c4e-717337906e19)

**Comment by panyogesh** [comment]
![image](https://user-images.githubusercontent.com/69527565/164889763-af6a69a9-25a2-414c-968f-349f02fd171f.png)
[Service-Request-April-23.zip](https://github.com/magma/magma/files/8546660/Service-Request-April-23.zip)

**Comment by panyogesh** [comment]
Need to check the setup with additional logs
