### ISSUE TITLE
Bazel target visibility coding guidelines are decided

### ISSUE THREAD

**Issue by mpfirrmann** [magma/magma#12531]
# Coding guideline for visibility of Bazel targets

Bazel targets have a [visibility attribute](https://bazel.build/concepts/visibility). Per default a target's visibility is set to private and it is only accessible for targets within the same package. Possible values include (among others) a public visibility `//visibility:public` (accessible from all packages) or package specific visibility `//foo/bar:__pkg__` to grant targets in package `//foo/bar` access. The visibility can be set explicitly for a target or globally for the whole package.

Note: This proposal is only relevant for the developers currently migrating to Bazel and does not need the attendance of the TSC members.

## Problem

Visibility is currently used inconsistently throughout the Bazel migration effort.

## Solution

We propose the following coding guidelines that should be applied in a refactoring task. One important motivation for the proposed solution is based on encapsulation, i.e., keeping a clean architecture by restricting access to targets. For example, service libraries should only be accessed by the service itself. Proto- and util libraries can be accessed by any service (with certain restrictions if appropriate - e.g., the `all_python_proto` target should only be accessed by the `state` service).

### Protos BUILD.bazel Files
The global package visibility is set to public as compiled protos libraries need to be accessed from a lot of packages. The visibility of native proto libraries is set to private or is restricted to package visibility for other protos packages.

### Service BUILD.bazel Files
The global package visibility is set to private (i.e. default). The binaries should explicitly be set to private for readability reasons, even if this means redundancy. Libraries should explicitly be set to private or package visibility (e.g. for testing) when needed. The public visibility should be used only if necessary.

### Util Packages
In the `orc8r/configuration` and `orc8r/common` BUILD.bazel files the global package visibility is set to public.

**Comment by mpfirrmann** [comment]
Feedback appreciated :) 
@LKreutzer @jheidbrink @vktng @themarwhal @electronjoe

**Comment by jheidbrink** [comment]
Given that the simplest option would be to just use public visibility everywhere, I think we should motivate why we sometimes prefer private or package-specific visibility over public visibility (helps to maintain a clean architecture?).

**Comment by LKreutzer** [comment]
> Given that the simplest option would be to just use public visibility everywhere, I think we should motivate why we sometimes prefer private or package-specific visibility over public visibility (helps to maintain a clean architecture?).

A good example for a situation where a restrictive target visibility is clearly needed is in the [magma/lte/protos/oai/BUILD.bazel (see comment below):](https://github.com/magma/magma/blob/689cf2f3fd0b925821781138e526b65dddd6cde4/lte/protos/oai/BUILD.bazel#L137)
```
# This proto library is exclusively meant for the state service.
# Users can manually add proto libraries to state.yml.
# This means that all proto libraries need to be available
# in builds of the state service.
proto_library(
    name = "all_proto",
    srcs = glob(["*.proto"]),
    visibility = ["//visibility:private"],
    deps = ["@com_google_protobuf//:timestamp_proto"],
)

# See comment at :all_proto
python_proto_library(
    name = "all_python_proto",
    protos = [":all_proto"],
    visibility = ["//orc8r/gateway/python/magma/state:__pkg__"],
)
```
The target `all_python_proto` is needed in the state service due to special circumstances, because users can manually add proto libraries to state.yml. This target should not be used anywhere else and hence we should set the visibility to be package specific `visibility = ["//orc8r/gateway/python/magma/state:__pkg__"],`.

**Comment by nstng** [comment]
^ @LKreutzer, @jheidbrink feedback applied - feel free to edit :)

**Comment by nstng** [comment]
should be added to documentation
