### ISSUE TITLE
[AMF]: Issue in  setting AMF set ID, Region ID range  

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#12554]
Update from slack
================================
Hi Support, I'm having a lot of trouble trying to set my amf set id to 4 with the API interface.  is that not a valid number?
amf_set_idstring
example: 1
pattern: ^[0-3][A-Fa-f0-9]{0,2}$
should it be this:
AmfId string String identifying the AMF ID composed of AMF Region ID (8 bits), AMF Set ID (10 bits) and AMF Pointer (6 bits) as specified in subclause 2.10.1 of 3GPP TS 23.003 [7]. It is encoded as a string of 6 hexadecimal characters (i.e., 24 bits). Pattern: '^[A-Fa-f0-9]{6}$'
This seems to be the same with region id, I can't set it to "128" in the API, when I try to set it to "80" it just reads in as 80? (edited)

**Comment by panyogesh** [comment]
Reference : https://github.com/jdegre/5GC_APIs/blob/master/TS29571_CommonData.yaml

AmfSetId:  ^[0-3][A-Fa-f0-9]{0,2}$
The first digit should be 0-3, followed by 2 more letters (A-F,a-f,0-9)
Valid combinations : 0A1, 1B2, 3e9
Invalid comibation : 4A1, 5A2

AmfRegionId: '^[A-Fa-f0-9]{2}$'
It consists of only 2 characters
Valid combinations : Ae, F1, a9
Invalid combinations : 128, 345

**Comment by Radula76** [comment]
Some Testing: 
**API configuration:**
{
  "amf_default_sd": "ffffff",
  "amf_default_sst": 1,
  "amf_name": "rtcore.melb01.amf.5gc.mnc001.mcc001.3gppnetwork.org",
  "amf_pointer": "1",
  "amf_region_id": "80",
  "amf_set_id": "2"
}

Trace(initial context setup request):
GUAMI
    pLMNIdentity: 00f110
        Mobile Country Code (MCC): Unknown (1)
        Mobile Network Code (MNC): Unknown (01)
    aMFRegionID: 50 [bit length 8, 0101 0000 decimal value 80]
    aMFSetID: 0080 [bit length 10, 6 LSB pad bits, 0000 0000  10.. .... decimal value 2]
    aMFPointer: 04 [bit length 6, 2 LSB pad bits, 0000 01.. decimal value 1]

AllowedNSSAI: 1 item
    Item 0
        AllowedNSSAI-Item
            s-NSSAI
                sST: 01


Change 1.
**API configuration:**
{
    "amf_default_sd" : "AFAF",
    "amf_default_sst" : 2,
    "amf_name" : "rtcore.melb01.amf.5gc.mnc001.mcc001.3gppnetwork.org",
    "amf_pointer" : "1F",
    "amf_region_id" : "C1",
    "amf_set_id" : "2A1"
}

Trace(initial context setup request):
GUAMI
    pLMNIdentity: 00f110
        Mobile Country Code (MCC): Unknown (1)
        Mobile Network Code (MNC): Unknown (01)
    aMFRegionID: 00 [bit length 8, 0000 0000 decimal value 0]
    aMFSetID: 0080 [bit length 10, 6 LSB pad bits, 0000 0000  10.. .... decimal value 2]
    aMFPointer: 04 [bit length 6, 2 LSB pad bits, 0000 01.. decimal value 1]

AllowedNSSAI: 1 item
    Item 0
        AllowedNSSAI-Item
            s-NSSAI
                sST: 02
                sD: 00afaf

Change 2.
**API configuration:**
{
  "amf_default_sd": "AFAF",
  "amf_default_sst": 2,
  "amf_name": "rtcore.melb01.amf.5gc.mnc001.mcc001.3gppnetwork.org",
  "amf_pointer": "1",
  "amf_region_id": "2",
  "amf_set_id": "080"
}

Trace(initial context setup request):
GUAMI
    pLMNIdentity: 00f110
        Mobile Country Code (MCC): Unknown (1)
        Mobile Network Code (MNC): Unknown (01)
    aMFRegionID: 02 [bit length 8, 0000 0010 decimal value 2]
    aMFSetID: 1400 [bit length 10, 6 LSB pad bits, 0001 0100  00.. .... decimal value 80]
    aMFPointer: 04 [bit length 6, 2 LSB pad bits, 0000 01.. decimal value 1]

AllowedNSSAI-Item
    s-NSSAI
        sST: 02
        sD: 00afaf
