### ISSUE TITLE
[Backport][CI][GITHUB] Generate bot account for automatic backport. 

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#12552]
In order to be able to automatically backport PR through tags we need to create a bot account on github that has personnal access token with write access to release branches. 
In order to do that we need: 

1 - have a bot@magmacore.org 
2 - create a github account with it 
3 - generate a personal access token with write to release branches

**Comment by ShubhamTatvamasi** [comment]
This is already done.
https://magmacore.slack.com/archives/C01MDUQDFC3/p1652271417390339?thread_ts=1652262787.297849&cid=C01MDUQDFC3
