### ISSUE TITLE
Domain Proxy integration test job is flaky

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#12569]
### Describe the Issue

The [Domain Proxy (DP) integration test CI job](https://github.com/magma/magma/actions/workflows/dp-workflow.yml) is flaky. It does seemingly randomly fail on PR changes which have nothing to do with DP.
E.g. https://github.com/magma/magma/runs/6156533611?check_suite_focus=true

### Expected behavior

- The DP integration tests run stable.
  - This should be true for master.
  - This should be true for any PR run, not touching anything remotely related to DP. 
- The DP integration tests are only executed when this is sensible to do.
  - Sensible execution conditions should be set. E.g. a DP integration test is likely not necessary for changes on the DocuSaurus.

FYI @magma/approvers-domain-proxy

**Comment by xbend** [comment]
We are aware of the issue. 
https://app.zenhub.com/workspaces/magma--domain-proxy-development-6064cb9d84ca0600135548c9/issues/magma/domain-proxy/364

**Comment by xbend** [comment]
We will most likely increase the current sleep timer to 15sec in one of our next PRs as a temporary improvement (it should decrease/remove the flakiness), but we will work on a proper retry mechanism.

**Comment by sklgromek** [comment]
Hi @Neudrino, these are integration tests, so we want them to be run in case of changes to the magma components that may affect the operation of the domain-proxy. Though you are right, the documentation can be excluded here. Maybe you already have some list of excludes which is used in integration tests checks in other parts of magma, which we can also adopt?

**Comment by Neudrino** [comment]
Hi @sklgromek , yes, feel free to get inspired by the other integration tests [among the workflows in the repository](https://github.com/magma/magma/tree/master/.github/workflows). In general in the project, the [dorny path filters](https://github.com/dorny/paths-filter) are used.

**Comment by sklgromek** [comment]
Relevant path filters were added in #12700

**Comment by xbend** [comment]
@Neudrino 
We have made many changes to ensure Domain Proxy CI tests stability and reliability. All items in this issue description were addressed.

The Domain Proxy integration tests are now requested to be made a required CI job for PR merges in https://github.com/magma/magma/issues/12855

**Comment by Neudrino** [comment]
Thanks for your efforts, @xbend , @sklgromek ! Feel free to close the issue, if you see it resolved.

**Comment by xbend** [comment]
We have observed the CI runs for a while now for all PRs in Magma (after all the improvement PRs were merged) and we did not see any problems.
We consider this issue as resolved since the flaky behavior was consistent and no longer is.
