### ISSUE TITLE
[IPV6] PDU session type in the id-PDUSession type IE is not as per 3GPP standerds.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12577]
### Your Environment

- Version:
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- **Deployment Environment: bare-metal (AGW)- VM Based

 Describe the Issue
PDU Session type in PDU-IE is not matching with the value that is sent in Payload container and is not as per 3GPP standards.

**To Reproduce**
Execute any PDU session TC with a specific PDU-Session type.

**Expected behavior**

**Screenshots**

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/fb1f6c72-a197-4d65-ac52-0518dbe25045)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/e0631288-44c3-4870-9fc0-2a64eb53cf23)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9363eba3-3179-400f-8fd4-4b491f65bc75)

**Comment by panyogesh** [comment]
We are comparing NAS encoding schema with NGAP.  Both are different specifications.

**Comment by Rajeshs23** [comment]
![ngap_encodingdecoding.PNG](https://images.zenhubusercontent.com/615bcd72e819bdbfba821b84/7d9ecbf8-348e-418b-8c78-b319d3f24a93)[https://app.zenhub.com/files/170803235/e264f817-40a5-43df-a7d7-5e2fc2254d83/download](https://app.zenhub.com/files/170803235/e264f817-40a5-43df-a7d7-5e2fc2254d83/download)
