### ISSUE TITLE
orc8r-quick start error

### ISSUE THREAD

**Issue by jingc1413** [magma/magma#12598]
git version: v1.7
https://docs.magmacore.org/docs/basics/quick_start_guide

exec: 
git clone https://github.com/magma/magma
cd magma
git checkout v1.7
cd orc8r/cloud/docker
sudo -i
./run.py   
got error:  Step 14/24 : RUN echo "export GOCACHE_MODULES=\"$(for m in $MAGMA_MODULES ; do echo -n /gomod/src/magma/$m ; echo -n ' ' ; done)\"" >> /etc/profile.d/env.sh
 ---> Using cache
 ---> 43c49b65fa4f
Step 15/24 : COPY gomod /gomod
COPY failed: file not found in build context or excluded by .dockerignore: stat gomod: file does not exist
ERROR: Service 'test' failed to build : Build failed

**Comment by qoderwork** [comment]
sorry,  
I forgot to execute ./build.py --all  
it's ok
