### ISSUE TITLE
[Regression Issue]: While testing paging scenario, Observing Service Reject with cause conditional IE missing 

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#12628]
In Spirent, while performing paging scenario,  I'm observing that downlink traffic is not hitting the UPF. From Spirent side traffic is being sent, still paging scenario is not been triggered. 

Please find the attached logs and pcaps for the same

[https://app.zenhub.com/files/170803235/d7e8f6d3-02ba-4981-ad53-9a8749042b73/download](https://app.zenhub.com/files/170803235/d7e8f6d3-02ba-4981-ad53-9a8749042b73/download)

[https://app.zenhub.com/files/170803235/a389dbb7-5b82-4351-895b-1d956ef9c330/download](https://app.zenhub.com/files/170803235/a389dbb7-5b82-4351-895b-1d956ef9c330/download)[https://app.zenhub.com/files/170803235/b9ed2c54-294a-4fff-8abc-3c4b9b89feb1/download](https://app.zenhub.com/files/170803235/b9ed2c54-294a-4fff-8abc-3c4b9b89feb1/download)

**Comment by apekshapk** [comment]
We are observing paging notification, later service request is sent but service request is being rejected. It is observed that Uplink data status is optional as per 3GPP specifications, but magma is taking Uplink Data Status as mandatory parameter. 
![Paging_Error.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/da6e35d6-ff63-4ebb-9d14-dbc0078adb89)

Please find the attached logs and pcaps:

[https://app.zenhub.com/files/170803235/f175d483-12e1-4f38-b745-b006812aad9e/download](https://app.zenhub.com/files/170803235/f175d483-12e1-4f38-b745-b006812aad9e/download)

[https://app.zenhub.com/files/170803235/b7212bfd-ed80-4023-8aa9-9363089b49c9/download](https://app.zenhub.com/files/170803235/b7212bfd-ed80-4023-8aa9-9363089b49c9/download)

[https://app.zenhub.com/files/170803235/94792608-429e-4514-85b0-b973e9db2112/download](https://app.zenhub.com/files/170803235/94792608-429e-4514-85b0-b973e9db2112/download)

**Comment by moinuddin1980** [comment]
As per Table 8.2.16.1.1: SERVICE REQUEST message content in TS 24.501
Uplink data status IE is optional. Hence, service reject cannot be sent if it is missing. Thus need to be fixed. https://www.etsi.org/deliver/etsi_ts/124500_124599/124501/15.01.00_60/ts_124501v150100p.pdf
