### ISSUE TITLE
Check whether `github.com/pkg/errors` can be replaced with standard library functions

### ISSUE THREAD

**Issue by alexzurbonsen** [magma/magma#12632]
The module [`github.com/pkg/errors`](https://github.com/pkg/errors) is no longer maintained, see for example https://github.com/pkg/errors/issues/245.

It seems like it can be removed and replaced by standard lib functionality (mainly `errors.Errorf` --> `fmt.Errorf`), which includes all of the functionality, except for the stack traces, that are included in the error type from `pkg/errors`. See for example this comment https://github.com/microsoft/go-winio/pull/227#issuecomment-984390345.

We should probably check whether removal is sensible and if yes replace it.

## Progress:

this needs to be fixed in
- [x] ./orc8r : https://github.com/magma/magma/pull/12724
- [x] ./feg : https://github.com/magma/magma/pull/12726
- [x] ./cwf : https://github.com/magma/magma/pull/12725
- [x] ./src : https://github.com/magma/magma/pull/12729
- [x] ./dp : https://github.com/magma/magma/pull/12727
- [ ] ...

**Comment by MoritzThomasHuebner** [comment]
refactoring: Remove the use of "github.com/pkg/errors".

## Summary

These PRs remove the uses of [github.com/pkg/errors](github.com/pkg/errors) which [is no longer maintained](https://github.com/pkg/errors/issues/245). However, this change will remove stack traces in the output. 

- [ ] Replaces calls of the form `errors.Wrap(err, wrap)` with `fmt.Errorf(wrap + ": %w", err)` (or similar)
- [ ] Replaces calls of the form `errors.Wrapf(err, wrap, ...vars)` with `fmt.Errorf(wrap + ": %w", ...vars, err)`
- [ ] ...

I attached an example below of the change in output. I obtained this by modifying the source code so a test would fail.

Old output:
```
    eap_aka_test.go:48: 
        	Error Trace:	eap_aka_test.go:48
        	Error:      	Received unexpected error:
        	            	I caused this error deliberately.
        	            	Error validating EAP packet
        	            	magma/cwf/gateway/services/uesim/servicers.(*UESimServer).HandleEap
        	            		/home/bmoritz/Documents/magma/cwf/gateway/services/uesim/servicers/eap.go:36
        	            	magma/cwf/gateway/services/uesim/servicers_test.TestEapAkaIdentityRequest
        	            		/home/bmoritz/Documents/magma/cwf/gateway/services/uesim/servicers/eap_aka_test.go:47
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:1439
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1571
```

New output
```
    eap_aka_test.go:48: 
        	Error Trace:	eap_aka_test.go:48
        	Error:      	Received unexpected error:
        	            	Error validating EAP packet: I caused this error deliberately.
        	Test:       	TestEapAkaIdentityRequest
```
