### ISSUE TITLE
Cannot add users in the organization edit page of NMS

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#12640]
### Your Environment

- **Version:** master
- **Affected Component:** NMS
- **Deployment Environment:** local docker-compose (orc8r + NMS)

### Describe the Issue

![grafik](https://user-images.githubusercontent.com/13189449/166930295-f608c2a3-a720-43b7-bbba-f28c4f42f8f4.png)

The `Add Users` button does not allow to add users, but shows the same dialog as the `Edit` button.

### Expected behavior

The `Add Users` button should allow to add users.

**Comment by HannaFar** [comment]
This issue was fixed yesterday : https://github.com/magma/magma/pull/12651
