### ISSUE TITLE
Cleanup contribution related duplicated content - Community repo

### ISSUE THREAD

**Issue by ildikov** [magma/magma#12708]
### Your Environment

- **Affected Component:** Contributor Guide + community repo

### Describe the Issue

The community repo contains duplicated and in some cases out of date information regarding governance bodies and contribution workflows: https://github.com/magma/community

The repo needs to be cleaned up and have pointers that link to relevant content in the Contributor Guide and the governance repo instead:
* https://github.com/magma/magma/wiki/Contributor-Guide
* https://github.com/magma/Governance

**Comment by lucasgonze** [comment]
After deduplication this page in Docusaurus needs to be restructure or eliminated: https://docs.magmacore.org/docs/contributing/contribute_onboarding

**Comment by maxhbr** [comment]
In the TSC meeting on 2022-07-11 we agreed that less repos is better and we can go forward to clean it up and remove it if no content is left.

**Comment by Neudrino** [comment]
Hi @lucasgonze , I guess your comment above :arrow_up:  is rather something for https://github.com/magma/magma/issues/12707 as it is related to DocuSaurus and the Github Wiki but not the Community Repository.
Maybe it should be moved there, in order to not confuse people?

**Comment by lucasgonze** [comment]
Per the comment above, I have moved most of the items in [my comment 14 days ago](https://github.com/magma/magma/issues/12708#issuecomment-1178242351) into a comment in #12707. The following two items are relevant to this ticket, #12708:

- [ ] The link towards https://docs.magmacore.org/docs/contributing/contribute_onboarding in https://docs.magmacore.org/docs/basics/prerequisites should be changed to https://github.com/magma/magma/wiki

- [ ] We should consider removing the entire "Proposals" menu in the left nav in Docusaurus. Proposals are now in Github issues.

**Comment by Neudrino** [comment]
- Feel free to create a PR for the first item.
- The second item might need to be discussed in the TSC, because as far as I can see from [the proposal process](https://github.com/magma/magma/wiki/Adding-and-Tracking-Proposals) those items are supposed to be there.

**Comment by lucasgonze** [comment]
> Feel free to create a PR for the first item.

https://github.com/magma/magma/pull/13396

> discussed in the TSC

I'll add it to the agenda.

**Comment by ildikov** [comment]
The community repo is now archived, therefore this issue can be closed.
