### ISSUE TITLE
Add content to the Contributor Guide - Governance

### ISSUE THREAD

**Issue by ildikov** [magma/magma#12706]
### Your Environment

- **Affected Component:** Contributor Guide, Governance repo

### Describe the Issue

The Magma project now has a Contributor Guide that provides content to help new and established contributors to find and follow resources and processes to be able to contribute to the project.

The Governance bodies section of the guide is missing content: https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance#governance-bodies

This section of the guide should contain information about how the community is structured when it comes to leadership bodies, meaning a group of people who are responsible to guide the community, for instance the Technical Steering Committee (TSC).

The guide should contain pointers to any documentation that contains some more information, for instance the project and TSC charter: https://github.com/magma/Governance/blob/main/CHARTER.md

**Comment by ssanadhya** [comment]
@ildikov , note that we are tracking some governance topics on [Magma Confluence](https://wiki.magmacore.org/display/HOME/Technical+Steering+Committee+2022-2023) . Can you cross reference sections from there into GitHub Wiki?

**Comment by ildikov** [comment]
@ssanadhya We can hyperlink the Confluence pages from GitHub wiki and vice versa. Would that cover what you have in mind?

Also, is there a directive in terms of what information is stored on GitHub in the governance related repo(s) vs what's on Confluence, that we could document in the Contributor Guide?

**Comment by ssanadhya** [comment]
> @ssanadhya We can hyperlink the Confluence pages from GitHub wiki and vice versa. Would that cover what you have in mind?
> 
> Also, is there a directive in terms of what information is stored on GitHub in the governance related repo(s) vs what's on Confluence, that we could document in the Contributor Guide?

@ildikov , it will be best to split the governance document on the lines of what is aligned with the actual code, vs what is not. In that respect, the GitHub Wiki should only hold the content around code ownership. All other governance details, such as TSC, Outreach, DevOps, etc should be on Confluence, since we are also tracking meetings for these bodies there.

Further, we can get rid of the Magma technical leads section in https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance. The technical leadership is now spread across TSC and codeowners.

**Comment by ildikov** [comment]
@ssanadhya According to your comments I removed the 'technical leads section' and added references to Confluence and the Governance GitHub repo. Does that cover what you had in mind?

In addition, we also need to do some cleanup on GitHub. For instance, there is some duplicated and at the same time outdated information in the Community repo: https://github.com/magma/community/blob/main/Governance.md

**Comment by ssanadhya** [comment]
> @ssanadhya According to your comments I removed the 'technical leads section' and added references to Confluence and the Governance GitHub repo. Does that cover what you had in mind?
> 
> In addition, we also need to do some cleanup on GitHub. For instance, there is some duplicated and at the same time outdated information in the Community repo: https://github.com/magma/community/blob/main/Governance.md

@ildikov , the revised version of the page looks good to me. I think it will be best to deprecate the Community repository now that we have a Confluence page. What do you think @wendallkaters and @maxhbr ?

**Comment by ildikov** [comment]
As there's initial content about the project's governance in the Contributor Guide this issue can be closed. The Community repository related items are tracked elsewhere.
