### ISSUE TITLE
Add content to the Contributor Guide - Tracking and fixing bugs

### ISSUE THREAD

**Issue by ildikov** [magma/magma#12705]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Affected Component:** Contributor Guide

### Describe the Issue

The Magma project now has a Contributor Guide that provides content to help new and established contributors to find and follow resources and processes to be able to contribute to the project.

The Tracking and fixing bugs section of the guide is missing content: https://github.com/magma/magma/wiki/Report,-Track-and-Fix-Bugs

The content on this page is expected to contain information such as:
* Tool and place where bugs are reported and tracked
* Process to report a bug
  * Including any good practice that can guide people to write up an informative bug report
* Processes to handle bugs
  * The lifecycle of a bug report; ie: triaged, in progress, etc
  * Steps of fixing a bug; ie: assign it a person who is working on it, linking a bug report to PRs, targeting a bug report to a release
  * How to use tags

Related wiki page: https://github.com/magma/magma/wiki/Bug-Workstreams
* Background
  * Security and vulnerability management related issues usually go through a different workflow than regular bugs
  * The separate security area raised the question if there might be similar areas that deviate from the baseline workflow
* Next steps
  * Cover the vulnerability management workflow either in the 'Tracking and fixing bugs' chapter or add a link to the description of it

**Comment by Neudrino** [comment]
The page of "Bug workstreams" was a duplication of the page regarding [creating and cracking bugs](https://github.com/magma/magma/wiki/Report,-Track-and-Fix-Bugs). Thus this was consolidated and the respective missing content was added.
