### ISSUE TITLE
SUCI-Profiles configured through Swagger-API  are not getting updated into the subscriber-db .

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12750]
Your Environment

- Version: 1.8.0-1652770270-648289fb
- Affected Component:  Orchestrator, Access Gateway
- Affected Subcomponent: Orchestrator pod/service or AGW service
- Deployment Environment:  bare-metal (AGW)-VM based

### Describe the Issue
SUCI-Profiles configured through Swagger-API  are not getting updated into the subscriber-db .

**To Reproduce**
Step1: Using PUT API from Swagger-UI configure the suci-profile parameters as shown below .

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9a8859dc-59fe-4403-b846-efa2b3c78e5a)

Step2: Try to Fetch the SUCI-Profile info using Get command.
Step3 : Check the list of suci-profiles saved using the CLI in AGW.
Step4. We should get all the list of profiles saved .

**Expected behavior**
As profiles are not getting Posted to subscriberdb, AMF is failing to decrypt the imsi.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a1a62b3d-d6cb-499b-9324-b66c960facc8)

Get API output from swagger.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/dcf0532f-f99b-4bd7-9ec3-9825c958a6cc)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a0578d6d-853d-41a0-b05d-634984486289)

**Comment by panyogesh** [comment]
Closed as part of #12567
