### ISSUE TITLE
Does anyone have this running on stand alone or VMs rather than VAGRANT/VB . Are there any instructions?

### ISSUE THREAD

**Issue by pkapatsos-blinq** [magma/magma#1275]
I have to setup magma as a test as we are a eNB vendor with a CBRS system. Trying to build this outside of virtualized environments since we have real eNBs to test. Can anyone point me to this path?
We don't want to use desktops for this ,  plus all the issues relating to VB environments.
So looking for a way to build the AGW like it stated in the doc on a BAREMETAL machine however everything builds on a VB/Vagarant why?  Then the NMS , anything on it to build it local rather than AWS.
Sorry not an issue rather a ask on documentation for building standalone .

**Comment by edaspb** [comment]
Here you can find installation instructions:
https://facebookincubator.github.io/magma/docs/basics/introduction.html

Welcome to Discord channel https://discord.gg/WDBpebF

**Comment by pkapatsos-blinq** [comment]
HI I have those instructions already  everything it states or shows is running on vagrant or virtual box environments.
I’m trying to build standalone AGW running on the specs it states for BareMetal server however all the software still builds on vagrant why ?
Any way thanks for anything to get me on standalone setup.


Regards,
[BLINQ Logo Final_small]
Peter Kapatsos
LTE Solutions Engineer
T:  416 214-4204 x724
M:  647-269-9053 |  www.blinqnetworks.com
140 Renfrew Dr | Suite 200 | Markham | ON | L3R 6B3

**Comment by themarwhal** [comment]
Here is the documentation for baremetal AGW : https://facebookincubator.github.io/magma/docs/lte/setup_deb .
Here is the documentation for setting up the Orc8r/NMS on AWS: https://facebookincubator.github.io/magma/docs/orc8r/deploy_intro

**Comment by edaspb** [comment]
For bare metal installation you have to skip "Quick Start Guide", it is for quick tests only.
As far as I get you will need three elements, AGW, Orchestrator and NMS.
Agw can be installed as bare metal, but Orchestrator and NMS are Docker containers.

**Comment by xjtian** [comment]
If you start with a base Debian VM image, you can follow the baremetal installation guide (obviously skip the parts about installing Debian on baremetal hardware). The install script should work fine as long as it's a Debian Stretch VM.
