### ISSUE TITLE
Usability: wiki landing page is confusing to new contributors

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#12762]
### Your Environment (If applicable)

- **Affected Component:** onboarding documentation for new developers
- **Affected Subcomponent:** web site, Confluence, wiki

### Describe the problem

**Description**

A new developer looking to get started will have difficulty navigating available documentation. The information they need is hard to find. The information they get isn't entirely relevant.

- The "Getting Started" link should go to a page that does that
- magma.github.io should be merged into the wiki

**Additional context**

Following the standard trail of links:
1. at https://magmacore.org/ click "Join the open source community"
2. at https://magmacore.org/join-the-open-source-community/ scroll down to Developer Onboarding, click Get Started
3. at https://github.com/magma/magma/wiki/Contributing-Code there is no information on getting a build. Click "Opinionated set up of development environment for MacOS" in the sidebar. --> This link should point to the Contributor Guide itself as opposed to directly to the code section
4. at https://github.com/magma/magma/wiki/Opinionated-set-up-of-development-environment-for-MacOS scroll down below the fold to "Install Magma locally"
5. at https://github.com/magma/magma/wiki/Opinionated-set-up-of-development-environment-for-MacOS#install-magma-locally, click "Follow the [quick start guide](https://magma.github.io/magma/docs/next/basics/quick_start_guide) to get an AGW and Orc8r instance running on your dev machine"
6. at https://magma.github.io/magma/docs/next/basics/quick_start_guide you arrive at an entirely different starting point for developers. Here you can "Follow the deployment guides under Orchestrator and Access Gateway if you are installing Magma for a production deployment."

### Describe your idea

There are a few opportunities to improve the onboarding experience.

**Description**

- Clicking "Getting Started" in https://magmacore.org/join-the-open-source-community/ should lead to [Magma project overview](https://github.com/magma/magma/wiki/) instead of [Contributing Code](https://github.com/magma/magma/wiki/Contributing-Code)
- The information at magma.github.io needs to be merged into the wiki
- [Contributing Code](https://github.com/magma/magma/wiki/Contributing-Code) should be refactored. The CI information at the bottom doesn't belong here.

**Comment by platonenkoiurii** [comment]
Fully agree. sometimes information location is not very intuitive.
What about starting with some user stories to understand who and why comes to Magma site and github. Based on that information could be structured to satisfy the demand and lose such newcomers.

**Comment by lucasgonze** [comment]
Follow up tasks:

- talk to @platonenkoiurii to gather observations and input
- use #website-unification in slack to reset link in step 3 to point towards the Contributor Guide itself as opposed to directly to the code section

**Comment by lucasgonze** [comment]
Regarding "Talk to @platonenkoiurii to gather other observations and input.", he replied by email. Followups are to add to agenda for next meeting and to coordinate with him to gather additional details that may improve documentation.
