### ISSUE TITLE
chore: stale default assignees for new features

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#12763]
The default owners for new features are Tariq Al-Khasib and Aswin Alexander. I suspect those defaults are stale. 

1. Go to https://github.com/magma/magma/issues/new/choose to create a new issue
2. Select "Feedback form"
3. The assignees will default to aswin-alexander and talkhasib

The problem is that the assignees aren't active in Magma any more.

**Additional context**

magma/.github/ISSUE_TEMPLATE/feature_request.md

```
% cat feature_request.md 
---
name: "\U0001F680 Feedback form"
about: Describe a problem, suggest a new idea or functionality for the project
title: ''
labels: 'type: feature'
assignees: aswin-alexander, talkhasib

---
```

**Comment by Neudrino** [comment]
The following PR should be linked here for reference and restrictions: https://github.com/magma/magma/pull/12764.
