### ISSUE TITLE
Clean up MME_BENCHMARK

### ISSUE THREAD

**Issue by nstng** [magma/magma#12771]
MME_BENCHMARK is a new flag that also includes files via pre-processor mechanics.
* See https://github.com/magma/magma/pull/11633 for the introduction
* ~~Figure out if this flag is used in any CI builds~~
  * if not: ~~ask in slack if it can be removed and remove~~
  * ~~if yes: support the flag and by that bazelify missing files~~
* If this flag/build is supported, then also the following files should get bazelified
```
"./lte/gateway/c/core/oai/tasks/mme_app/experimental/mme_app_serialization.hpp"
"./lte/gateway/c/core/oai/tasks/mme_app/experimental/mme_app_serialization.cpp"
```
* Update bazel/scripts/check_c_cpp_bazel.sh

Update: See https://magmacore.slack.com/archives/C01B32Q9L76/p1662119897091189?thread_ts=1661851635.871369&cid=C01B32Q9L76
Can be removed. Make target also needs to be removed.

**Comment by LKreutzer** [comment]
See also https://magmacore.slack.com/archives/C01B32Q9L76/p1661851635871369
