### ISSUE TITLE
Behavioral deviation of periodic registration in TVM and ABot. 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12806]
Hi Moin/Yogesh,

Please let me know what should be the expected behavior when Periodic-Registration is triggered from UE.

Behavior in TVM:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/406a0c72-8b5e-41c4-829a-f1b64e2f8ceb)

Behavior in ABot :
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/45314eb2-d6fb-4b25-b5e9-c6e3afae81ad)

Please find the attached reference logs in detail.

Logs from TVM :
[https://app.zenhub.com/files/170803235/1f86024b-c1a3-4db8-af4d-5c3ac0655362/download](https://app.zenhub.com/files/170803235/1f86024b-c1a3-4db8-af4d-5c3ac0655362/download)

Logs from ABot :
[https://app.zenhub.com/files/170803235/a81fd389-6921-4f0c-b00d-967eeeeb6f43/download](https://app.zenhub.com/files/170803235/a81fd389-6921-4f0c-b00d-967eeeeb6f43/download)

**Comment by Sathyaj27** [comment]
Following are the observations :

From code :

1) if IMSI is known but mac-mismatching  authentication process will be triggered.
2) If registration ie is IMSI and if mac matched or Integrity type is not protected then authentication procedure will be triggered.


From about logs observed that mac is mismatching :
000700 Fri May 20 16:09:22 2022 7F470FEF0700 INFO  AMF-AP tasks/amf/nas5g_message.cpp     :0956    M5G_NAS_SECURITY_ALGORITHMS_128_5G_IA1 returned MAC 70.ed.ea.2f(803925360) for length 37, direction 0, count 2
**000701 Fri May 20 16:09:22 2022 7F470FEF0700 DEBUG AMF-AP tasks/amf/nas5g_message.cpp     :0163    msg->header.message_authentication_code = DF05AA96 != computed = 70EDEA2F**

This is the reason authentication procedure is triggered.



Thanks
Sathya
