### ISSUE TITLE
[AMF]: Support for 5GS network feature support

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#12811]
To support "5GS network feature support" IE in the Registration Accept message.

Some of the UEs are expeting Network Feature from core. Functionality is described in section "9.11.3.5 5GS network feature support" of 24.501

![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/8f28da6d-093a-4243-967b-6c3d064b6ac1)

**Comment by sreedharkumartn** [comment]
Please find the Private binary and the attached PCAP, for network feature support IE added newly in registration accept. Please find the private binary and pcap in below zip file.
https://drive.google.com/file/d/1T-1S2o6bAShPjtuhDEzNXlH_mOQOmfC6/view?usp=sharing

**Comment by sreedharkumartn** [comment]
Please find the Private binary, PCAP Snap shot for network feature support IE added newly in registration accept message with UERANSIM patch. 
https://drive.google.com/file/d/1K7AatZFBoagDu1k6tHHaBScVGbLeZgcI/view?usp=sharing
![image.png](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/abdf7bef-3c07-4b27-bb63-2a8af5de15cd)
