### ISSUE TITLE
[AUSF]Observance Trace Backes in Subscriber-db when registration request with invalid length of Keys 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12822]
Your Environment

Version: 1.8.0-1652928411-01faf444
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: bare-metal (AGW)-VM based

### Describe the Issue
[AUSF]Observance Trace Backes in Subscriber-db when registration request with invalid length of Keys .

Note : Observed the same issue when tried passing home-network-key identifier as invalid value say "256".

**To Reproduce**

1. Calculate public and private key from AGW and check for list of Keys.
2. Configure Public-Key and Private-Key in the Test Frame Work.
3. Trigger initial Registration and see that Deconceling is giving proper error instead of Trace Backs.

TraceBack ScreenShot:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/156e9bee-13e0-4341-b13f-d651c3271b07)

[https://app.zenhub.com/files/170803235/df40c26e-6e07-481d-b001-fe83cacde759/download](https://app.zenhub.com/files/170803235/df40c26e-6e07-481d-b001-fe83cacde759/download)

**Comment by panyogesh** [comment]
Fixed as part of #12567
