### ISSUE TITLE
[GenexCom]PDU-Session accept message coming with extra buffer causing failure of PDU-Session while interop with gnex-gnb 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12867]
### Your Environment

- Version: 1.8.0-1652928411-01faf444
- Affected Component: Access Gateway
- Affected Subcomponent:  AGW service
- Deployment Environment: bare-metal (AGW)-VM Based

### Describe the Issue
PDU-Session accept message coming with extra buffer causing failure of PDU-Session while interop with gnex-gnb . With other gnb simulators we are not seeing this issue.

**To Reproduce**
Trigger PDU-Session from Genexcom setup with Magma-Core.

**Expected behavior**
Buffer length has to be checked and parsed properly.

Note: Attached Pcaps and Logs are from ABot Simulator, where the buffer info is cross checked.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a4ab4175-6f60-4f90-b327-5857b63000d9)

**Additional context**
Logs from ABot-Setup:
[https://app.zenhub.com/files/170803235/81099555-31d9-486e-bac8-c9c2cb1057cc/download](https://app.zenhub.com/files/170803235/81099555-31d9-486e-bac8-c9c2cb1057cc/download)

Pcaps from GenexCom:
[https://app.zenhub.com/files/170803235/ebf9f47b-b0fc-461c-8f91-7b0f5498221e/download](https://app.zenhub.com/files/170803235/ebf9f47b-b0fc-461c-8f91-7b0f5498221e/download)

**Comment by ganeshg87** [comment]
update:
 - I have reproduced locally with UERANSIM, and I could see an extra buffer in ngap.pDUSessionResourceSetupRequestTransfer.
 - asn encode is building a complete buffer based on data structure from ngap.
