### ISSUE TITLE
Update go version in docs 1.7.0

### ISSUE THREAD

**Issue by geetikabatra** [magma/magma#12908]
Currently, the version of the docs 1.7.0 reflects go installation `1.13`. The latest one is 1.18. I think this should be updated in this as well as the suitable older version.
![image](https://user-images.githubusercontent.com/8664238/171808016-abcd35dc-0777-410e-ac55-0fccaf9f9da2.png)

**Comment by voisey** [comment]
> This is already updated for upcoming versions, see: https://magma.github.io/magma/docs/next/basics/prerequisites
> 
> As far as I know, Go 1.13 is still the correct version if you're working with release 1.7.

Yes, I believe this is the case too. The [upgrade to 1.18](https://github.com/magma/magma/pull/12151) was merged on 9/5/22 while [Magma 1.17](https://github.com/magma/magma/releases/tag/v1.7.0) was released on 3/3/22.
