### ISSUE TITLE
[Swagger-API] Configuring AMF set-ID, Region-ID and Pointer from swagger PUT command is failing.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12946]
Your Environment

- Orc8r Version: 1.7
- Affected Component: Orchestrator, Access Gateway
- Affected Subcomponent: Orchestrator pod/service or AGW service
- Deployment Environment: AWS (orc8r), bare-metal(AGW)-VM

### Describe the Issue
[Swagger-API] Configuring AMF set-ID, Region-ID and Pointer from swagger PUT command

**To Reproduce**
case 1 :  Set the below parameters from swagger API
            'https://api.magma.wavelabs.int/magma/v1/lte/abot- 
             network-238/gateways/abot-agw-238' 
               amf_region_id: 128
              amf_set_id: 4
              amf_pointer: 1

OutPut : Swagger PUT command is not getting executed when the region-id is set to 128.

case2: Set Region-id to different value say 80
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/f68d097f-e877-47a1-bee4-d788a8f3056c)

Observation : PUT-API is getting executed and values are getting reflected in the response.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/fb9ffc73-b95a-4e35-8072-fb1f1af28aa8)

Case 3 : Execute the GET-API and check that info configured from PUT is not getting configured from GET.

Observation : GET API is not having proper configured parameters.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6b3a3ef9-8be4-4bdf-86c6-1aeb5e7c2d28)

And finally the configured values are not getting reflected in AMF.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/e0fe1518-6a68-4432-a002-e6a5aeb99137)

**Comment by panyogesh** [comment]
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/259a5514-0aff-4489-b8bd-0139d4e17d8a)
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/6367916d-2675-4803-ad1e-16de61e6988d)
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/e12c0489-5d70-4cb4-97e9-551fcae9518d)
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/61fca23c-40a7-4d80-add4-a6517631b3cf)
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/eafb1c31-d0e1-424e-aa72-e5f4049ba970)

**Comment by panyogesh** [comment]
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/5eb4192d-c9d7-40a3-8baa-13aa7a8f5d5d)

**Comment by panyogesh** [comment]
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/78ae1fdc-6175-4f24-b2d0-793d71aa9abe)

**Comment by panyogesh** [comment]
![image.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/0e71e0cc-b375-4045-9e0c-e6bbb5b9e580)

**Comment by shivesh-wavelabs** [comment]
The regex of `amf_region_id` is `^[A-Fa-f0-9]{1,2}$,` so it only supports an alphanumeric value of length 2 characters.
