### ISSUE TITLE
CWF integ test flakyness is mitigated

### ISSUE THREAD

**Issue by nstng** [magma/magma#12977]
The CWF integ tests are currently very flaky:
https://github.com/magma/magma/actions/workflows/cwf-integ-test.yml?query=branch%3Amaster

Reasons of the last couple of runs:
* https://github.com/magma/magma/actions/runs/2490205734
  * TestGyAbortSessionRequest failed 4 times
* https://github.com/magma/magma/actions/runs/2490200084
  * cwag VM provisioning `Add Docker’s official GPG key` - `Temporary failure in name resolution`
  * Note: have noticed a couple of these in other jobs at the same time - can imo be ignored
* https://github.com/magma/magma/actions/runs/2487686056
  * TestGyAbortSessionRequest failed 4 times
* https://github.com/magma/magma/actions/runs/2486481999
  * cwag VM provisioning `Install packages to allow apt to use a repository over HTTPS` - `Failed to update apt cache: unknown reason`
* https://github.com/magma/magma/actions/runs/2486301233
  * TestGxReAuthQuotaRefill failed 4 times
* https://github.com/magma/magma/actions/runs/2476348872
  * vagrant cloud 429
* https://github.com/magma/magma/actions/runs/2476317955
  * vagrant cloud 429
* https://github.com/magma/magma/actions/runs/2476315519
  * vagrant cloud 429
* https://github.com/magma/magma/actions/runs/2476168188
  * TestGxMidSessionRuleRemovalWithCCA_U failed 4 times
  * TestGyAbortSessionRequest failed 4 times
  * TestOmnipresentRules failed 4 times
* https://github.com/magma/magma/actions/runs/2476135539
  * vagrant cloud 429
* https://github.com/magma/magma/actions/runs/2475562000
  * vagrant cloud 429
* https://github.com/magma/magma/actions/runs/2473353945
  * TestGyCreditExhaustionRedirect failed 4 times

**Observations**
* 26 Days ago the tests seem to be much more stable
* Starting with run 3375 the tests became red for a longer period
  * assumption: 3375 and 3376 were just flaky
  * 3377, 3378 and 3379 were the runs on the switch from fb to the magma artifactory - starting now the test were failing because of this until run 3473
  * Was in 3380 - 3472 something introduced that made the test more flaky - but was undiscovered because of the artifactory issues?

**Comment by voisey** [comment]
Closing via https://github.com/magma/magma/pull/13084, which fixes the majority of the failing tests. In the CI, the CWF integ tests are now green with the exception of one test, which is still flaky. It can be tracked in this new issue: https://github.com/magma/magma/issues/13180
