### ISSUE TITLE
Make NMS Github Actions pipeline a required check for pull request merges

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#12985]
## Problem

Many components have workflows, which are required to pass within the Github Actions Continuous Integration (CI), to be able to merge a pull request (PR). Examples are AGW and Orc8r.
In contrast the workflow available for NMS is not required for PRs. In the consequence the usual issues apply, including PRs breaking NMS or code (style) degradation.

## Solution

The (complete) **NMS workflow** should be a **required CI check** for every PR.

## Additional information

- The NMS workflow already exists and is quite stable:
  - https://github.com/magma/magma/actions/workflows/nms-workflow.yml
  - https://github.com/magma/magma/blob/master/.github/workflows/nms-workflow.yml
- The workflow includes linters and formatters.
- The workflow includes test execution.

**Comment by sebathomas** [comment]
This had to be reverted because it blocked other PRs that had no changes in NMS and skipped the nms-workflow.

**Comment by maxhbr** [comment]
@tmdzk : I removed the job from the list

**Comment by Neudrino** [comment]
The problem is described in https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs.
A workaround is not given there directly.

**Comment by Neudrino** [comment]
The problem was solved by @maxhbr , @thmsschmitt , @Neudrino .
The solution was, that not the complete workflow needed to be made required, but the single actions in it. Than it would show the desired behaviour.
