### ISSUE TITLE
[orc8r][onprem] Certifier pod keep crashing due to GoLang runtime error 

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#13000]
### Your Environment

- **Version:** v1.7
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Certifier service (consequently NGINX and whole orc8r)
- **Deployment Environment:** K8s cloud on baremetal using magma-galaxy (Ref: https://github.com/ShubhamTatvamasi/magma-galaxy)

### Describe the Issue

Starting from clean Ubuntu 20 server image on a server with 4 CPU 16G RAM 100 Disk flavor, I am trying to deploy orc8r on cloud using magma-galaxy method presented on below URL:
https://github.com/ShubhamTatvamasi/magma-galaxy

I have been able to deploy v1.6.1 succesfully using the helm charts (v1.6) and docker images prepared by magmacore on similar machine:
Helm: https://artifactory.magmacore.org:443/artifactory/helm/
Docker: https://registry.hub.docker.com/u/magmacore

v1.6.1: All pods are up and running with no exception:
orc8r-certifier-554bc9f9cf-pdcc5                 1/1     Running   0               24h

v1.7.0: Certifier pod keep crashing preventing the whole orc8r or NMS to work properly:

ubuntu@trial1-magmagalaxy:~$ kubectl get pods -norc8r
NAME                       READY  STATUS       RESTARTS     AGE
orc8r-certifier-79cc56875f-nbm8w         0/1   CrashLoopBackOff  161 (52s ago)  13h
orc8r-nginx-5f6f8fd4bb-tqjr7           0/1   CrashLoopBackOff  162 (60s ago)  13h
orc8r-prometheus-6546b6755b-gnjrh        0/1   Pending      0        13h
orc8r-user-grafana-79658fd6f4-rn29h       0/1   Pending      0        13h

ubuntu@trial1-magmagalaxy:~$ kubectl logs orc8r-certifier-79cc56875f-nbm8w -norc8r
I0615 13:33:47.038063    1 service_config.go:178] Successfully loaded ‘cwf::service_registry’ service configs from ‘/etc/magma/configs/cwf/service_registry.yml’
I0615 13:33:47.038278    1 service_config.go:178] Successfully loaded ‘dp::service_registry’ service configs from ‘/etc/magma/configs/dp/service_registry.yml’
I0615 13:33:47.038586    1 service_config.go:178] Successfully loaded ‘feg::service_registry’ service configs from ‘/etc/magma/configs/feg/service_registry.yml’
I0615 13:33:47.038891    1 service_config.go:178] Successfully loaded ‘lte::service_registry’ service configs from ‘/etc/magma/configs/lte/service_registry.yml’
I0615 13:33:47.039407    1 service_config.go:178] Successfully loaded ‘orc8r::service_registry’ service configs from ‘/etc/magma/configs/orc8r/service_registry.yml’
I0615 13:33:47.039689    1 service_config.go:120] Successfully loaded structured ‘orc8r::shared’ service configs from ‘/etc/magma/configs/orc8r/shared.yml’
I0615 13:33:47.039867    1 service_config.go:178] Successfully loaded ‘orc8r::certifier’ service configs from ‘/etc/magma/configs/orc8r/certifier.yml’
I0615 13:33:47.053001    1 main.go:89] ERROR: Failed to load VPN cert and key: Failed to load certificate (/var/opt/magma/certs/vpn_ca.crt) & key (/var/opt/magma/certs/vpn_ca.key): open /var/opt/magma/certs/vpn_ca.crt: no such file or directory
I0615 13:33:47.053157    1 service_config.go:120] Successfully loaded structured ‘orc8r::certifier’ service configs from ‘/etc/magma/configs/orc8r/certifier.yml’
I0615 13:33:47.053249    1 service_config.go:178] Successfully loaded ‘orc8r::metricsd’ service configs from ‘/etc/magma/configs/orc8r/metricsd.yml’
I0615 13:33:47.053302    1 service_config.go:189] Successfully loaded Override configs for service orc8r:metricsd from ‘/var/opt/magma/configs/orc8r/metricsd.yml’
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x8f7054]
goroutine 1 [running]:
[github.com/labstack/echo.(*Echo).Add(0x0](http://github.com/labstack/echo.(*Echo).Add(0x0), 0xf1b732, 0x3, 0xf25f5f, 0xe, 0xf63b08, 0x0, 0x0, 0x0, 0xc0000809c0)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:484 +0xb4
[github.com/labstack/echo.(*Echo).GET(0x0](http://github.com/labstack/echo.(*Echo).GET(0x0), 0xf25f5f, 0xe, 0xf63b08, 0x0, 0x0, 0x0, 0xe0b300)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:388 +0x89
magma/orc8r/cloud/go/obsidian.AttachHandlers(0x0, 0xc000563e30, 0x9, 0x9, 0x0, 0x0, 0x0)
	/src/magma/orc8r/cloud/go/obsidian/handler.go:174 +0x125
main.main()
	/src/magma/orc8r/cloud/go/services/certifier/certifier/main.go:117 +0x99e

**To Reproduce**
1. Install 0rc8r v1.7 on clean ubuntu 20 machine

**Expected behavior**
It is expected that all pods got created and run with no errors, if there is an exception or an error, it is expected to have a log report or error message that provide more info about fault.

**Screenshots**
NA

**Additional context**
Steps those done trying to troubleshoot this error:
1- Start all over again from scratch.
2- Make sure I am using the latest packages
3- Tear down k8s cluser and start it again
4- Delete the pod and let k8s automatically create new one

5- **Change the image of the pod manually to v1.6.1** and confirm if same error occur (kubect edit pod POD_NAME -n orc8r) and let k8s restart the pod and create new one with previous image.

Amazingly the last step worked out and pod was created succefully:
ubuntu@trial1-magmagalaxy:~$ **kubectl describe pod orc8r-certifier-79cc56875f-4hv25 -norc8r**
Name:         orc8r-certifier-79cc56875f-4hv25
Namespace:    orc8r
Priority:     0
Node:         10.1.12.134/10.1.12.134
Start Time:   Wed, 15 Jun 2022 14:11:38 +0000
Labels:       app.kubernetes.io/component=certifier
              app.kubernetes.io/instance=orc8r
              app.kubernetes.io/name=orc8r
              pod-template-hash=79cc56875f
Annotations:  cni.projectcalico.org/containerID: caa94795cf4e4114e97dfa6b082b0b0baa580835312179e5af981ac4ddbe3d2c
              cni.projectcalico.org/podIP: 10.42.0.105/32
              cni.projectcalico.org/podIPs: 10.42.0.105/32
Status:       Running
IP:           10.42.0.105
IPs:
  IP:           10.42.0.105
Controlled By:  ReplicaSet/orc8r-certifier-79cc56875f
Containers:
  certifier:
    Container ID:  docker://be594a929d2b640d5e8b04223b1fef5418e0f8b0e89c46560d2b0adda5d3b27c
    Image:         magmacore/controller:**1.6.1**
    Image ID:      docker-pullable://magmacore/controller@sha256:c760b5d42ec5c19898171f6f14cf741e717d7ad3c21c8b8b5b8841d81329bad8
    Port:          9086/TCP
    Host Port:     0/TCP

ubuntu@trial1-magmagalaxy:~$ kubectl get pods -norc8r
NAME                                             READY   STATUS             RESTARTS          AGE
**orc8r-certifier-79cc56875f-4hv25                 1/1     Running            6                 8m52s**

After which I have edited the image back to v1.7.0, k8s changed the metadata and updated the pod, however same error appeared again.

**Comment by MAAHamid** [comment]
@uri200 Hello Oriol, Could you help who might support with onprem orc8r installation?

**Comment by ShubhamTatvamasi** [comment]
Seems like you are using old Helm charts. You will have to use latest helm charts to get it working.
