### ISSUE TITLE
[Regression Issue]: With PDU type as IPV6, allocating IP Block in mobilityd, observing PDU Establishment Request retries

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13051]
PDU-Establishment is failing when ip-pool for IPV6 is not defined in gateway.mconfig and it is defined in mobilityd.yml file in headless mode.

Please find the attached logs and pcaps for the same:
[https://app.zenhub.com/files/170803235/67fd01a6-ad0d-4009-bd65-a06eca090c99/download](https://app.zenhub.com/files/170803235/67fd01a6-ad0d-4009-bd65-a06eca090c99/download)

[https://app.zenhub.com/files/170803235/186593f9-e600-4ec0-b655-9ca29dd74363/download](https://app.zenhub.com/files/170803235/186593f9-e600-4ec0-b655-9ca29dd74363/download)

[https://app.zenhub.com/files/170803235/83a0d675-613b-497c-8a55-d1e436fc1fcf/download](https://app.zenhub.com/files/170803235/83a0d675-613b-497c-8a55-d1e436fc1fcf/download)

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/d782e661-af28-4e3e-bc02-0b65fa7cb4b2)

**Comment by Rajeshs23** [comment]
As per the current design of mobilityD...this parameters are read only from gateway.mconfig "ipv6_block = _get_ip_block(mconfig.ipv6_block, "IPv6")" 
By default code is as follows the parameters are read only from gateway.mconfig. please find the pr and images attached below for reference.![mconfig.PNG](https://images.zenhubusercontent.com/615bcd72e819bdbfba821b84/3e34efe0-b189-4ff5-877f-5446ae911fb5)

**Comment by NeelimaKalpana** [comment]
Closing this issue as it is a config issue.
