### ISSUE TITLE
'nose' is replaced by 'pytest' for the python tests

### ISSUE THREAD

**Issue by mpfirrmann** [magma/magma#13095]
The `nose` package for testing is not maintained anymore and does not support the latest python versions anymore. This is a hard block for any changes in the VMs. Therefore it is replaced by `pytest`. The transition is done via three PRs:

1. Adapt the unittests #13052 
2. Adapt the integration tests #13060 
3. Cleanup / Housekeeping #13068 

`pytest` displays several deprecation warnings. The first ones are addressed in follow-up PRs

1. Fix the first warnings in the unit tests #13093
2. Fix all warnings in the integration tests #13094

The remaining warnings are mainly caused by two reasons: 

1. deprecated handling of asyncio's Event Loop (https://docs.python.org/3/library/asyncio-eventloop.html)
2. deprecated handling of asyncio's `@coroutine` decorator (https://docs.python.domainunion.de/3.8/library/asyncio-task.html#asyncio.coroutine)

Some warnings are caused by old versions of some used packages. 
For these to be fixed we need to upgrade ...

- ...`eventlet` from 0.30.2 (published 03/2021) to >=0.30.3 (05/2021); the latest is 0.33.1 (05/2022)
- ...`dnspython` from 1.16.0 (published 12/2018) to >= 2.0.0 (06/2020); the latest is 2.2.1 (03/2022)

The warning is not fixed (yet?) in the `pymemoize` packages since there were no code changes since 10/2018.

**Comment by voisey** [comment]
Since the replacement is now complete, I guess we can close this issue and perhaps create a new one for the remaining warnings pytest gives. Could you please do this if you think it sounds sensible @mpfirrmann?

**Comment by mpfirrmann** [comment]
I agree. The remaining tasks are python-related warnings and not connected to the testing package.
