### ISSUE TITLE
TAC value is different in Registration Accept message 

### ISSUE THREAD

**Issue by Chandrashrathore** [magma/magma#13141]
- **Version:**   1.7.0-1648152173-73e61141                  

As per the pcap log we have analysis that the we have configured different tac value in MME & gNB. When UE is sending Initial Registration request message with different tac value and we have received registration accept message from AMF with different TAC value.

![image.png](https://images.zenhubusercontent.com/61bad8f715f837be5855c509/d0ce06f7-e942-4350-bfaa-590d914a9b19)

![image.png](https://images.zenhubusercontent.com/61bad8f715f837be5855c509/58a07b03-1700-4352-b655-3f161f9b98b8)

[https://app.zenhub.com/files/170803235/09d9c7a5-d932-41b4-b223-bdd787c5cb91/download](https://app.zenhub.com/files/170803235/09d9c7a5-d932-41b4-b223-bdd787c5cb91/download)

**Comment by sreedharkumartn** [comment]
@Chandrashrathore, we found the root cause. We are working on the fix.

**Comment by sreedharkumartn** [comment]
Hai @Chandrashrathore, Please find the private binary with working PCAP with it.
https://drive.google.com/file/d/1T8RTb4iUg1IGH3LLOpHsj5ZTSwYuBjmh/view?usp=sharing
With this private binary, We are getting the same TAC value in registration accept which we are sending in the Initial UE message. Please find the PCAP Snap shots below.
![image.png](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/7eb85717-810f-4d72-a00c-d3cb2160ec8c)
![image.png](https://images.zenhubusercontent.com/61374a2e8f757482c1cb868c/9b5e3c89-10ac-492f-a7b5-6bfa5dee04d6)

**Comment by sreedharkumartn** [comment]
Raised the PR #13272 for fixing the TAC value.
