### ISSUE TITLE
[Qos]: After applying policy, only UL Qos policy is reflected in fast path whereas DL Qos policy can't be observed.

### ISSUE THREAD

**Issue by salman-momin07** [magma/magma#13149]
**Version:** 1.8.0-1656438709-ee69cd25
**Deployment Environment:** bare metal agw
**Tested with:** srsRAN simulator for 4G 

**Description:**
Tested the above mentioned version of AGW with srsRAN by applying Qos policy as 
"policy_1" and apn as "internet". It is observed that Qos policy is getting applied and is reflected in mmelog, syslog, pcap and the same can be seen by running the command "policydb_cli.py dump_data". However the same is not reflected in fast path only the UL Qos policy is there whereas DL Qos policy is not showing in fast path (so there is no output after executing this command: tc -d -s class show dev eth1 )

**Please find below screenshots for reference.**

**- Configured Qos policy in pcap.**
![image.png](https://images.zenhubusercontent.com/61378f5f6eed5f2fa7f4f46e/cbe74aa6-ee72-43b5-be99-88095a427c7d)

**- Output of "policydb_cli.py dump_data"**
![image.png](https://images.zenhubusercontent.com/61378f5f6eed5f2fa7f4f46e/a3a9e907-f209-4955-9486-f52607939157)

**- Output of table 12**
![image.png](https://images.zenhubusercontent.com/61378f5f6eed5f2fa7f4f46e/9742aa1e-cc46-443f-9e74-5090466bc355)

**- Output of tc command on eth0 interface**
![image.png](https://images.zenhubusercontent.com/61378f5f6eed5f2fa7f4f46e/0a1b3070-c720-4f8b-b8de-822543ef3c0d)

**To reproduce the issue please follow below steps:**
1) Configure APN, Qos policy and apply to a particular IMSI.
2) In the setup, attach the subscriber and start traffic testing.
3) Execute the below commands and check the parameters as highlighted in screenshots.
 --> policydb_cli.py dump_data
 --> tc -d -s class show dev eth0
 --> tc -d -s class show dev eth1
 --> sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0 
 --> sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=12
 --> sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=13

**Comment by prabinakpattnaik** [comment]
As per latest implementation of DL traffic QoS policies, Move pipelineD QoS DL traffic QoS policies from S1 interface to dev 'gtpu_sys_2152'. (#12373).

please find logs:
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.common:adding qos for imsi IMSI901700000000001 rule_num 2 direction 1 apn_ambr 100000000, QosInfo(gbr=0, mbr=9000000)
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.common:existing root rec: ambr_qos_handle_root 0
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.qos_tc_impl:add QoS: QosInfo(gbr=None, mbr=100000000)
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.id_manager:allocating idx 5
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.tc_pyroute2:Create HTB iface gtpu_sys_2152 qid 0x5 max_bw 100000000 rate 80Kbit
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.tc_pyroute2:Return: ({'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 276, 'pid': 58752, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'},)
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.qos_tc_impl:create done: if: gtpu_sys_2152 qid 5 err 0
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.qos_tc_impl:assigned qid: 5
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.common:Added root ambr qos mbr 100000000 direction 1 qos_handle 5
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.common:existing leaf rec: ambr_qos_handle_leaf 0
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.qos_tc_impl:add QoS: QosInfo(gbr=None, mbr=100000000)
Jun 30 16:30:53 magma-dev-focal pipelined[58752]: DEBUG:pipelined.qos.id_manager:allocating idx 6
