### ISSUE TITLE
[Enhancement] TRF Server VM should be migrated to Ubuntu 20.04

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#13203]
### Issue Description:
The TRF Server VM still contains Debian 9 OS. The OS version for TRF Server should be migrated to Ubuntu 20.04 to keep software versions updated and in sync with the Magma-Dev and Magma-Test VMs. The primary reason is that some of the traffic server code is being shared between Magma-Test and TRF Server VMs, and hence, upgradation of software packages or adapted coding style in one VM may not be applied in other and may lead to temporary failures.

One such recent examples of issue with python version requirement can be seen with PRs https://github.com/magma/magma/pull/12938 and https://github.com/magma/magma/pull/13202

**Comment by sebathomas** [comment]
I'm assigning myself. We're currently looking at several VM upgrades and would like to tackle this issue as well.

Hoping it will also fix #13245.
