### ISSUE TITLE
While adding SUCI Profile A and Profile B consecutively through Swagger API, restart of magma services is required to reflect the added keys in the AGW.

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13239]
- Version: 1.8.0-1657217245-cac083b0
- Deployment Environment: Bare-metal (AGW) - VM based 

With respect to addition of SUCI Profile A and Profile B through Swagger API:
Observation 1: 
Adding SUCI Profile A through Swagger API and then consecutively adding Profile B, it is noted that even after waiting for some time to fetch the information from SubscriberDB, still the Profile B is not getting reflecting at AGW.
Restart of services required to get the Profile B reflected.

Observation 2:
After restart of magma services, it is noted that Profile A is getting deleted and only the Profile B Keys are getting reflected.

Please find the attached logs for the same:
[https://app.zenhub.com/files/170803235/e01ab268-3304-4eff-bdff-2ca39c110317/download](https://app.zenhub.com/files/170803235/e01ab268-3304-4eff-bdff-2ca39c110317/download)

[https://app.zenhub.com/files/170803235/34071324-cfb4-4b1d-8895-92d98e014e1f/download](https://app.zenhub.com/files/170803235/34071324-cfb4-4b1d-8895-92d98e014e1f/download)

**Comment by NeelimaKalpana** [comment]
Validated and Closing .

Screenshot of Profiles Configure:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/ec694054-bd8f-4571-9163-522e7e9d79f6)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/e43c1e81-1700-4b58-8d5b-2480170ec3b0)


Logs :

[Uploading... SUCI_from_Swagger_sys.log]
