### ISSUE TITLE
Analysis of bazel vs. Make runtimes

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13246]
# Analysis of bazel vs. Make runtimes

### Setup:
In this analysis we compare running:
| Target/Build tool  | Make   |  Bazel  |
|---|---|---|
| MME  | `time make build_oai`  | `bazel build lte/gateway/c/core:agw_of`  |
|  All | `time make build`   | `bazel build ...`  |

We can distinguish four scenarios:

| Scenario | Cache exists  | Output files exist (i.e. for :x: do a `bazel clean` first) | Code changes since last build  |
|---|---|---|---|
| 0 |  :x: (Initial build)  |:x:   |  :x:   |
| 1 |  :heavy_check_mark:  |  :x:   |  :x:   |
| 2 |  :heavy_check_mark:   | :heavy_check_mark:  |   :x:  |
| 3 |  :heavy_check_mark:   | :heavy_check_mark:  | :heavy_check_mark:  |

:warning: Caveat: Scenario 0 is difficult to compare because bazel needs to download many things due to hermiticity, this results in much greater build times and is highly dependent on the internet connection. Most of this extra time is spent on fetching dependencies like grpc, protobuf etc. Moreover this step is mostly done during the provisioning of the magma-vm for Make (?). 

#### MME:
Results from running the command in a fresh magma-vm locally:
| Scenario/Tool:  | Make  | Bazel   |
|---|---|---|
| 0  | 80.384s  |  520.990s (:warning: see above) |
| 1 | -  |  15.872s |
| 2 | 7.464s  |  0.325s |
| 3 | 22.080s  |   7.250s |

#### All:
Results from running the command in a fresh magma-vm locally:
| Scenario/Tool:  | Make  | Bazel   |
|---|---|---|
| 0  | 523.541s  |  1174.337s (:warning: see above) |
| 1 | -  |  53.773s |
| 2 | 101.243s  |  70.925s* |
| 3 | 139.270s  |   127.925s |

\* In scenario 2 bazel fetches packages which prolongs the build time. This does not happen in scenario 1, which is thus faster.

## Comparing CI workflow jobs:
For some of the CI jobs that do not have a direct comparison with the other build tool a comparison time was added from a local VM run. The main overlap between the bazel and Make CI are right now the bazel and AGW workflows.

### Unit tests (Bazel & AGW workflows):
| Unit test targets/Tool  | Make   |  Bazel |
|---|---|---|
| All tests (incl. C/C++, Python, Go)  | -   | 242.857s (CI, without caching test results)  |
| MME tests |  1303s (CI) | 316.308s (VM, without cached test results)  |
|   |   | 25.249s (VM, with cached test results)
| SCTPD tests | 160s (CI) |  
| LIAGENT tests | 178s (CI) |  
| SESSION MAN. tests | 594s (CI) |  
| Python tests | 371s (CI) |  
| C/C++ non-MME unit tests with asan |   | 888.965s (CI)

### C/C++ unit test coverage (AGW workflow):
| Unit test targets/Tool | Make | Bazel |
| -- | -- | -- |
| MME tests | 2880.000s (CI) | 5.801s (VM, caching test results; 690.579s initial run) |
| All non-MME C/C++ tests |   | 142.000s (CI, caching test results) |
| All C/C++ tests |   | 69.981s (VM, caching test results) |

### All and packages:
 | Build target/Tool | Make | Bazel | 
 | -- | -- | -- | 
 | All * | 523.541s (VM) | 387.538s (CI) | 
 | magma-sctpd_1.8.0_amd64.deb |  - | 46.292s (CI, without using the build outputs, i.e. new build of the service) | 

\* See also analysis above for local comparisons.

## Conclusions:
- Due to the extensive caching bazel is generally faster in the **builds**. 
  - The exception to this is the very first build of any target on a fresh machine which needs to download the external dependencies like grpc, protobuf etc. Any of the following builds on any targets will not have this drawback. The upside of this is that the build is hermetic.
- **Test** and **coverage** executions are much faster with bazel. This is true even without caching test results, but can be further accelerated by adding this option.

**Comment by nstng** [comment]
analysis done - closed
