### ISSUE TITLE
[AGW] Write per subscriber APN specific data into subscriberDB store when MME receives Update Location Answer

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#13252]
- Function in S6a task which received ULA, where MME needs to write to Sqlite : [s6a_handle_update_location_ans](https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.cpp#L123)
- Reference: SubscriberDB interface with SQlite, to get configuration and schema
- C++ Sqlite interface https://www.sqlite.org/cintro.html
- Protos defining 
-- [APN configuration](https://github.com/magma/magma/blob/master/lte/protos/apn.proto#L42), which is part of [SubscriberData](https://github.com/magma/magma/blob/master/lte/protos/subscriberdb.proto#L139) message [sent from SubscriberDB to Mobilityd](https://github.com/magma/magma/blob/master/lte/gateway/python/magma/subscriberdb/rpc_servicer.py#L104) as part of [IP allocation ](https://github.com/magma/magma/blob/4844f8fbdd7035a236de46a7d839652d1ea461de/lte/gateway/python/magma/mobilityd/subscriberdb_client.py#L140)
-- [APN configuration](https://github.com/magma/magma/blob/master/feg/protos/s6a_proxy.proto#L187), which is sent as part of [ULA](https://github.com/magma/magma/blob/master/feg/protos/s6a_proxy.proto#L164)

**Comment by vroon2703** [comment]
Linking a pull request https://github.com/magma/magma/pull/13290 to this issue.

**Comment by sebathomas** [comment]
Possibly this was already done in #13470? That seems to be an updated version of the linked draft.

**Comment by lucasgonze** [comment]
> Possibly this was already done in #13470? That seems to be an updated version of the linked draft.

The descriptions ("This PR has the following new functions") are exactly the same.

**Comment by lucasgonze** [comment]
I think we should declare victory on this issue given that https://github.com/magma/magma/pull/13470 has been merged.

**Comment by sebathomas** [comment]
Yes, I agree. (I only saw that PR after reopening the issue.)
