### ISSUE TITLE
[AMF]: Handling of reject from Mobilityd when static-ip configuration is conflicting with IP-POOL Config

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#13258]
## Your Environment

Version:1.8.0-1657277947-b1829e92
Affected Component: Access Gateway
Affected Subcomponent: AMF

### Describe the Issue
Proper Rejection or notification has to be sent to UE when there is a static-IP configured for a subscriber is with in the subnet of IP_Pool Configured in Mobilityd

**To Reproduce**
1. Configure the Static-IP in the subnet of IP-Pool configured (in Mobilityd) while adding subscriber .
2. Trigger the 5G Registration and PDU-Establishment.
3. Check that AMF is responding with proper message, if there is any issue with the PDU Establishment.

**Expected behavior**
Proper response has to be sent to UE .

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/5ab6105c-5cf1-4af4-bf45-ee5ae0df87af)

Syslogs Observed:

![image.png](https://ima[https://app.zenhub.com/files/170803235/ec29bb0b-73db-4459-89b0-944a0575d6eb/download]

**Additional context**
Add any other context about the problem here (e.g. logs).
[https://app.zenhub.com/files/170803235/9e62666a-9197-445f-9ed3-b8375c4bb2c1/download](https://app.zenhub.com/files/170803235/9e62666a-9197-445f-9ed3-b8375c4bb2c1/download)

**Comment by Niteshwavelabs** [comment]
Hi Team 
The issue got resolve reject from Mobilityd when static-ip configuration is within IP-POOL Config

[https://app.zenhub.com/files/170803235/a1ca52ee-76e8-476d-a632-5c3732098e05/download](https://app.zenhub.com/files/170803235/a1ca52ee-76e8-476d-a632-5c3732098e05/download
)
