### ISSUE TITLE
Run integration tests against a Magma deployment build

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13263]
Subtasks:
- [x] Create the VM  (run via vagrant up magma-prod)
- [x] Make LTE integration tests run (run via make ...)
- [x] Run all LTE integration tests  (currently all tests that need downlink fail) (NB: not all pass, see #13551)
- [x] Documentation  (To be done in future work, see #13685, as it is not working completely at the current time)
- [x] Prepare internal review meeting

Currently, the LTE integration tests are executed against the Magma dev environment, and the release artifacts (i.e. debian packages) are created for each commit on master but not tested in the CI. It would be good to run integration tests against the deployed artifacts as well.

**Current state**
3 VM:
Magma dev
Magma test
Magma traffic server
Magma is build and installed on dev via `make`

**Target state**
3 VM:
Magma prod --> see Hint below for setup
Magma test (likely stays unchanged)
Magma traffic server (likely stays unchanged)
Magma is installed via apt packages from deb
Magma is not build

**Acceptance criteria**
- Vagrant up + Ansible as technology
- no fab
- A magma prod VM exists:
  - deb packages will be downloaded from Artifactory & installed
  - no builds are done
  - integration test are run against this machine
- Hint: magma test still needs a make execution
- There is a documentation in the getting started guide, which details the steps necessary to successfully execute the integration 

## Reference
https://github.com/mpfirrmann/magma/tree/magma_prod/init
https://confluence.tngtech.com/display/PFM/magma_prod+installation+and+LTE+integ_tests 
https://jira.tngtech.com/browse/FM-758

**Comment by ajahl** [comment]
All **precommit** tests run through.

**Comment by ajahl** [comment]
### Findings

Unlike precommit tests, running integ-tests and non-sanity tests need changes in the MME configuration. Therefore, `test_modify_mme_config_for_sanity.py` and `test_modify_config_for_non_sanity.py `are executed before the tests run and `test_restore_mme_config_after_sanity.py ` and `test_restore_config_after_non_sanity.py` restore the configuration afterwards.

**Problem:** In the Magma prod VM, MME does not load the modified configuration required by some tests.

**Reason:** Both Python scripts modify the configuration file mme.conf in `/home/vagrant/magma/lte/gateway/configs/templates/` but the MME service loads the `mme.conf` in `/etc/magma/templates/`. A symlink exists between both folders In the Magma dev VM but not in the Prod VM. 

**Solution:** Create a symlink or copy mme.conf after the modification and restart MME.

**Comment by ajahl** [comment]
During the test runs, I had the problem that MME took a long time when a test was restarted (1-2 min), so some tests had to be restarted. In general, the tests are very flaky in combination with the Prod VM.

**Comment by ajahl** [comment]
Tests that always failed so far:
1. Precommit Tests 

2. Extended Tests
		s1aptests/test_attach_detach_rar_tcp_he.py
		s1aptests/test_multi_enb_multi_ue_diff_plmn.py 
		s1aptests/test_s1_handover.py 
		s1aptests/test_attach_detach_rar_tcp_data.py 

3. Non-sanity Tests
		s1aptests/test_paging_with_mme_restart.py
		s1aptests/test_standalone_pdn_conn_req_with_apn_correction.py
		s1aptests/test_secondary_pdn_with_dedicated_bearer_multiple_services_restart.py 
		s1aptests/test_attach_esm_info_timerexpiration_max_retries.py
		s1aptests/test_paging_request.py
		s1aptests/test_multi_enb_paging_request.py 
		s1aptests/test_activate_deactivate_multiple_dedicated.py
		s1aptests/test_sctp_shutdown_while_mme_is_stopped.py
		s1aptests/test_3495_timer_for_dedicated_bearer_with_mme_restart.py
		s1aptests/test_attach_detach_with_corrupt_stateless_mme.py
		s1aptests/test_enb_partial_reset_multi_ue_with_mme_restart.py 
		s1aptests/test_no_auth_response_with_mme_restart.py
		s1aptests/test_no_attach_complete_with_mme_restart.py
		s1aptests/test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue.py
		s1aptests/test_restore_config_after_non_sanity.py

**Comment by ajahl** [comment]
Draft PR https://github.com/magma/magma/pull/13518
Provisioning Prod VM `host:~/magma/lte/gateway/$ vagrant magma_prod`
