### ISSUE TITLE
OVS Update.

### ISSUE THREAD

**Issue by Lkishor123** [magma/magma#13260]
Update the OVS by inserting new debian packages.

To create debian package, run the following script:

- `magma/third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh`

**Comment by Lkishor123** [comment]
![ping_test.png](https://images.zenhubusercontent.com/60e58be3aab41d3e7a7b2892/a5a67c59-dc60-47aa-b797-bb56cb9e6463)

![table_0.png](https://images.zenhubusercontent.com/60e58be3aab41d3e7a7b2892/49999026-4247-425c-9f3e-5ceb7d80a243)

**Comment by prabinakpattnaik** [comment]
[OVS-2.15.4.tgz](https://github.com/magma/magma/files/9084257/OVS-2.15.4.tgz)

**Comment by maxhbr** [comment]
https://github.com/magma/magma/pull/13171 was not yet updated to match deb files here, right?

**Comment by prabinakpattnaik** [comment]
@maxhbr , The 13 latest .deb files are present inside "OVS-2.15.4.tgz" as attached.

**Comment by maxhbr** [comment]
can you update the hashes and metadata in https://github.com/magma/magma/pull/13171 ?

**Comment by maxhbr** [comment]
The attached artifacts are named e.g. `libopenvswitch_2.15.4-8_amd64.deb`, which can be found in https://artifactory.magmacore.org/ui/repos/tree/General/debian%2Ffocal-1.7.0%2Flibopenvswitch_2.15.4-8_amd64.deb and thus do not satisfy the "globally uniquely named" requirement. If you build a release it should not reuse an old version. Every change should bump the version.

**Comment by maxhbr** [comment]
then this way of packaging does not meet the requirement towards traceability. If we fix and update OVS it should get a new version. Otherwise it will not be clear what is installed where and it is also unclear how updating is behaving. A package that was once published to the registry should be treated as immutable and should not be overwritten, but instead should get a new version.

**Comment by prabinakpattnaik** [comment]
As per latest changes for OVS build version, below is the complete deb packages.
[OVS-2.15.4.tar.gz](https://github.com/magma/magma/files/9118891/OVS-2.15.4.tar.gz)

**Comment by prabinakpattnaik** [comment]
![image](https://user-images.githubusercontent.com/69528542/179176434-b40aca20-a715-4c75-ab44-0e2df6d8be4f.png)
