### ISSUE TITLE
Clean up GitHub Actions workflow names

### ISSUE THREAD

**Issue by voisey** [magma/magma#13275]
Following on from https://github.com/magma/magma/pull/13197, I think the names of the workflows should be unified. In particular, looking at https://github.com/magma/magma/actions, some workflows have descriptive names, e.g. "Push Bazel Cache To S3", while some just use the name of the workflow file, e.g. "agw-build". This means that the "Workflows" section on the left of the Actions page has two ordered lists for the workflows, which can make finding a particular workflow harder than it should be, particularly for new users. I would suggest we use descriptive names for all of them.

See https://github.com/magma/magma/issues/13275#issuecomment-1182972207 for proposed naming conventions!

#### :warning: Beware of the following!
- Changing the workflow names might impact the required workflows for PRs.
- Mind CI dashboard need adoptions.
- Changing the workflow `name:` will preserve the run history, but only if you do not change the file name, i.e. leave the file names as is first.

Tasks
- [x] Change the names according to {component} {verb} [{addition}] (e.g. AGW build with bazel) so that component jobs are automatically grouped in alphabetic sorting. Before merging the pull request, discuss with Max to make sure required job names are changed in GitHub.
- [x] Document the naming scheme in the Wiki.
- [x] Prepare internal review.

**Comment by Neudrino** [comment]
This is a very good idea! :100: 
I would add that a **common naming scheme** should be defined, documented in the Contributers Guide, and applied in addition.

**Comment by LKreutzer** [comment]
I tested with a [dummy workflow ](https://github.com/LKreutzer/GH-actions-testing/actions/workflows/test_echo_2.yml) that a renaming of the workflow, i.e. changing the `name:` attribute, without renaming the file preserves the history in the actions tab on GitHub.
