### ISSUE TITLE
Upgrade material-ui

### ISSUE THREAD

**Issue by thmsschmitt** [magma/magma#13270]
Read through https://mui.com/material-ui/migration/migration-v4/ also have a look at the breaking changes link at the bottom of the document.

All other non material-ui core packages most likely have to updated as well:
* The date picker now lives under MUI X https://mui.com/x/react-date-pickers/date-picker/ 
* It looks like material-ui-dropzone might block the upgrade https://github.com/Yuvaleros/material-ui-dropzone/issues/341 we can probably use https://react-dropzone.js.org/ directly
* Material table has to be updated to the next branch https://github.com/material-table-core/core/issues/511#issuecomment-1189837387

### Subtasks

- [ ]  #13463

**Comment by voisey** [comment]
@thmsschmitt @Neudrino Can this be closed? It looks like it may have been closed via https://github.com/magma/magma/pull/13533.

**Comment by thmsschmitt** [comment]
Yes
