### ISSUE TITLE
TAC value issue in Registration accept and ICS issue when Context setup IE is not present

### ISSUE THREAD

**Issue by Sathyaj27** [magma/magma#13306]

**Comment by Sathyaj27** [comment]
[https://app.zenhub.com/files/170803235/e8903603-3fb3-4154-8f80-86c8f18d0455/download](https://app.zenhub.com/files/170803235/e8903603[https://app.zenhub.com/files/170803235/84cd5aef-0717-469f-9b55-22d6c792a907/download](https://app.zenhub.com/files/170803235/84cd5aef-0717-469f-9b55-22d6c792a907/download)-3fb3-4154-8f80-86c8f18d0455/download)

**Comment by panyogesh** [comment]
Closed as part of #13318
