### ISSUE TITLE
Observing Errors while performing session modification with multiple PDU multi session modification.

### ISSUE THREAD

**Issue by Niteshwavelabs** [magma/magma#13300]
- Version: 1.8.0-1657620996-00bf57fa
-Affected Component:  AGW
-Deployment Environment: bare-metal (AGW),VM-based 

 While performing session modification with multiple PDU it is observed that for 
second modification request is being sent through cli at AGW but observing errors wile processing it.
Please find the attached snapshots for the same

![MicrosoftTeams-image (30).png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/b501ccc6-7752-4566-9b47-f4e3cb43c546)

![MicrosoftTeams-image (29).png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/f9ca52d8-5428-4426-a9af-5f71e62a86a7)

**Comment by ajay-kashyap** [comment]
Hello all,
Current session modification feature we don't have support for multiple requests (QoS flows) to be sent, as mentioned in the use case document we are only supporting single Qos Flow  (ADD or DEL) in a session modification command.
