### ISSUE TITLE
Observing PDU retries if policies are attached with latest build.

### ISSUE THREAD

**Issue by Niteshwavelabs** [magma/magma#13310]
- Version :- 1.8.0-1657856247-0c10d58e
- Affected Component :- AGW
- Affected Subcomponent :- AGW
- Deployment Environment :- Baremetal - VM based

While performing SUCI Registration with multiple PDU with multiple Policies it is observed that PDU requests are retrying.

Please find the attached snapshot and the logs for the same.

![MicrosoftTeams-image (31).png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/3adea6ac-7916-4f99-b8f9-90921aad11d2)

![MicrosoftTeams-image (32).png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/dd66a2d2-cb5d-44f6-89a7-a2288f97f5d3)

![MicrosoftTeams-image (33).png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/bb41801f-8dea-49f7-be02-668d4d37e0b8)

[https://app.zenhub.com/files/170803235/66415981-5648-4290-af1b-b18e3914b8b1/download](https://app.zenhub.com/files/170803235/66415981-5648-4290-af1b-b18e3914b8b1/download)

**Comment by ganeshg87** [comment]
@Niteshwavelabs, please attach mme and sys logs along with pcap

**Comment by Niteshwavelabs** [comment]
Please find the attached logs for the same:

[22-07-15_08.00.47__RID-14__ts0_eth5_capture.zip]
(https://wavelabstechnologies-my.sharepoint.com/personal/apeksha_kulkarni_wavelabs_ai/Documents/Microsoft Teams Chat Files/22-07-15_08.00.47__RID-14__ts0_eth5_capture.zip)
[syslog_Policies_15.zip]
(https://wavelabstechnologies-my.sharepoint.com/personal/apeksha_kulkarni_wavelabs_ai/Documents/Microsoft Teams Chat Files/syslog_Policies_15.zip)
[mme_Policies_15.zip]
(https://wavelabstechnologies-my.sharepoint.com/personal/apeksha_kulkarni_wavelabs_ai/Documents/Microsoft Teams Chat Files/mme_Policies_15.zip)



[https://app.zenhub.com/files/170803235/75c4e75e-7687-40a8-9ee4-243bba2bf533/download](https://app.zenhub.com/files/170803235/75c4e75e-7687-40a8-9ee4-243bba2bf533/download)

[https://app.zenhub.com/files/170803235/756b640f-4ecf-4744-8319-b50699294ce0/download](https://app.zenhub.com/files/170803235/756b640f-4ecf-4744-8319-b50699294ce0/download)

[https://app.zenhub.com/files/170803235/1235ef74-d4e2-4f84-a641-25230ad75914/download](https://app.zenhub.com/files/170803235/1235ef74-d4e2-4f84-a641-25230ad75914/download)

**Comment by sreedharkumartn** [comment]
Raised PR #13390 to fix the printing of qos policies attached to IMSI in PDU Session Accept message, which will resolve the PDU retries happening.

**Comment by Niteshwavelabs** [comment]
Observing that AMBR value are not properly ported in PDU session .

[https://app.zenhub.com/files/170803235/191ff46d-a4e0-4c8f-8b86-9b8a73ff8fac/download](https://app.zenhub.com/files/170803235/191ff46d-a4e0-4c8f-8b86-9b8a73ff8fac/download)

[https://app.zenhub.com/files/170803235/b7bb84f4-a0ab-476b-8ee0-dc57b4629539/download](https://app.zenhub.com/files/170803235/b7bb84f4-a0ab-476b-8ee0-dc57b4629539/download)

[https://app.zenhub.com/files/170803235/7ff94c9f-c01c-41c0-8cae-06fc43533632/download](https://app.zenhub.com/files/170803235/7ff94c9f-c01c-41c0-8cae-06fc43533632/download)
