### ISSUE TITLE
[5G SA]: Integration with OSS/BSS systems 

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#13317]
Integration with OSS/BSS systems

**Comment by maxhbr** [comment]
hey @panyogesh, I think this ticket needs more content.

**Comment by panyogesh** [comment]
Idea of the ticket was to see if there are any Open Source OSS/BSS can be added on top of 5G Subscribers to see if billing data can be generated. Closing the ticket as there is no specific feedback on the same and is not pursued.
