### ISSUE TITLE
[DevOps] ARM documentation of docker containers

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#13328]

**Comment by jheidbrink** [comment]
On https://github.com/orgs/magma/projects/7/views/4 this ticket is shown as "in review". Where can I find the current state of the documentation?

**Comment by nstng** [comment]
@tmdzk what is the state of this issue?

**Comment by nstng** [comment]
Will close this for now in accordance with https://github.com/magma/magma/issues/12910
