### ISSUE TITLE
UE_initiated_Periodic_Registration_IdleMode TC is failing with latest Master Build.

### ISSUE THREAD

**Issue by Niteshwavelabs** [magma/magma#13340]
Version :- 1.8.0-1658210967-696e7931 
Affected Component :- AGW
Affected Subcomponent :- AGW
Deployment Environment :- Baremetal - VM based

It is observed that in UE_initiated_Periodic_Registration_IdleMode with magma build 1.8.0-1658210967-696e7931 TC is failing with error as Failed to respond to registration request. 
But same TC (UE_initiated_Periodic_Registration_IdleMode)  with Magma Build :- 1.8.0-1658162224-06349c5c it is working fine . 

Please find the logs and PCAP for Non-Working TC .

[https://app.zenhub.com/files/170803235/1bd8bb96-f566-4b55-8a64-41e6c3ebea85/download](https://app.zenhub.com/files/170803235/1bd8bb96-f566-4b55-8a64-41e6c3ebea85/download)

[https://app.zenhub.com/files/170803235/e697065f-5987-4eb9-81bd-d8423c76d883/download](https://app.zenhub.com/files/170803235/e697065f-5987-4eb9-81bd-d8423c76d883/download)

[https://app.zenhub.com/files/170803235/33f486c6-1e3b-4e64-b04c-9b35afc6bd30/download](https://app.zenhub.com/files/170803235/33f486c6-1e3b-4e64-b04c-9b35afc6bd30/download)

Please find the logs and PCAP for Working TC .

[https://app.zenhub.com/files/170803235/6096edab-e952-41a1-90a3-aa7ef855cfaf/download](https://app.zenhub.com/files/170803235/6096edab-e952-41a1-90a3-aa7ef855cfaf/download)

[https://app.zenhub.com/files/170803235/9e4e6c40-eea8-4f2a-8aaf-f4a9a7c9871b/download](https://app.zenhub.com/files/170803235/9e4e6c40-eea8-4f2a-8aaf-f4a9a7c9871b/download)

[https://app.zenhub.com/files/170803235/724e166a-767a-45c8-b5f0-6918369fe7c7/download](https://app.zenhub.com/files/170803235/724e166a-767a-45c8-b5f0-6918369fe7c7/download)

**Comment by NeelimaKalpana** [comment]
Please find the updated CV.

[https://app.zenhub.com/files/170803235/d36dc0a3-fc40-4321-93ff-44f664de2303/download](https://app.zenhub.com/files/170803235/d36dc0a3-fc40-4321-93ff-44f664de2303/download)

**Comment by NeelimaKalpana** [comment]
This issue got fixed in latest master, So marking it as closed.
