### ISSUE TITLE
customer_Issue_RegAcc_Retry_followedBY_Service_Request  TC is failing with latest Master Build.

### ISSUE THREAD

**Issue by Niteshwavelabs** [magma/magma#13342]
Version :- 1.8.0-1658236325-f73c3fc3 
Affected Component :- AGW
Affected Subcomponent :- AGW
Deployment Environment :- Baremetal - VM based

It is observed that in customer_Issue_RegAcc_Retry_followedBY_Service_Request with magma build 1.8.0-1658236325-f73c3fc3 TC is failing, Observed there is change in behavior as AMF is assigning different TMSI value for every retry of the Reg-accept message .
But same TC (customer_Issue_RegAcc_Retry_followedBY_Service_Request) with Magma Build :- 1.8.0-1658162224-06349c5c it is working fine. In pass case we observed that TMSI are same at every retry.

Please find the logs and PCAP for Non-Working TC .

[https://app.zenhub.com/files/170803235/6674d7a2-2756-4de6-8d79-5c1fa24fc4d1/download](https://app.zenhub.com/files/170803235/6674d7a2-2756-4de6-8d79-5c1fa24fc4d1/download)

[https://app.zenhub.com/files/170803235/c33f62aa-be15-4485-aca5-a9dcb9951237/download](https://app.zenhub.com/files/170803235/c33f62aa-be15-4485-aca5-a9dcb9951237/download)

[https://app.zenhub.com/files/170803235/30195940-8135-4733-ac70-ccaf38c2f92d/download](https://app.zenhub.com/files/170803235/30195940-8135-4733-ac70-ccaf38c2f92d/download)

Please find the logs and PCAP for Working TC .

[https://app.zenhub.com/files/170803235/14849f0b-3fda-4ad4-a503-c5e48f07d656/download](https://app.zenhub.com/files/170803235/14849f0b-3fda-4ad4-a503-c5e48f07d656/download)

[https://app.zenhub.com/files/170803235/974e0605-41ce-433b-92be-00011d2c87e3/download](https://app.zenhub.com/files/170803235/974e0605-41ce-433b-92be-00011d2c87e3/download)

[https://app.zenhub.com/files/170803235/86071c0e-8d74-47e1-af97-9346df0f7fb4/download](https://app.zenhub.com/files/170803235/86071c0e-8d74-47e1-af97-9346df0f7fb4/download)

**Comment by NeelimaKalpana** [comment]
Please find the updated logs.

[https://app.zenhub.com/files/170803235/6c3d4db3-ede6-485f-874d-41d015658a64/download](https://app.zenhub.com/files/170803235/6c3d4db3-ede6-485f-874d-41d015658a64/download)

**Comment by NeelimaKalpana** [comment]
Closing this bug as issue is not observed in latest master.
Here issue of assigning new TMSI on reg-accept retry got fixed
Validated Build: 1.8.0-1659442984-a5290e7d
Logs attached for the same.

[https://app.zenhub.com/files/170803235/096aadcf-308c-496e-9c8b-1737a9cd2fd2/download](https://app.zenhub.com/files/170803235/096aadcf-308c-496e-9c8b-1737a9cd2fd2/download)

[https://app.zenhub.com/files/170803235/b98dade2-dd53-4df9-a74a-61a1a93ffaa7/download](https://app.zenhub.com/files/170803235/b98dade2-dd53-4df9-a74a-61a1a93ffaa7/download)
