### ISSUE TITLE
Update bazel LTE integ test workflow

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13353]
Once the switchover to bazel happens the [bazel LTE integ test workflow](https://github.com/magma/magma/pull/13279) can be updated and modernized since it does not necessarily need to have the same environment as the Make LTE integ test workflow.

This includes addressing the comments of https://github.com/magma/magma/pull/13279, which affect the environment and in particular fixing the issue https://github.com/magma/magma/issues/13337 for the bazel workflow.

**Comment by LKreutzer** [comment]
To be done after bazel switch over, see https://github.com/magma/magma/issues/11283

**Comment by nstng** [comment]
outdated - closed
