### ISSUE TITLE
Pip dependencies are pinned for bazel

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13369]
To be discussed: is this even wanted/needed?
- There are a couple of pinned Python dependencies - an upgrade breaks the magma build/tests.
- New releases of pip dependencies can (and did) break CI.
- Bazel pip versions are stated in `requirements.in`, make versions in `setup.py`

Requirements:
- Main goal: do the same with Bazel as in `setup.py`s.
- Use the more restrictive pinning if there are conflicts in different `setup.py`s
- Create an issue where contradictions in `setup.py`s are documented.
- Think about the necessity of a CI job checking this. Create follow-up story if required.
- E.g. script that creates `requirements.in` from `setup.py`s and checks diff?

Notes:

- Take care of "_" and "-" differences - should be equivalent for pip

Extra story:

- Stretch goal, up for discussion: 
  - Pin all entries in `requirements.in` and `setup.py`s as `==`, `<=` or `<` (usage in this order is favorable).
  - Use `setup.py`s as basis:
    - Here often `>` and `>=` is used - change them to `==` current version
    - Report if pinning in different `setup.py`s diverges.

**Comment by LKreutzer** [comment]
Ping, are you doing this already on another ticket? @alexzurbonsen @sebathomas @wolfseb @MoritzThomasHuebner

**Comment by sebathomas** [comment]
There's ongoing work on Python dependencies in #13482 but the target was upgrading dependencies, not pinning them.

**Comment by wolfseb** [comment]
We did a lot of pinning of the dependencies in requirements.in as well, which you can find in the files changed section of #13482. We had to pin some dependencies because upgrades of some of the packages would break things.

**Comment by nstng** [comment]
out of date - closed for now
