### ISSUE TITLE
Current bazel remote cache hits are understood

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13362]
- This is an analysis task
- This task is time boxed: 2 days

Questions:
- What actions never have cache hits? 
  - Do such actions exist?
  - Why are those entries never cached?
  - If appropriate, create follow-up stories to make entries cache-able.
- What are the "internal" entries in builds? 
  - Is there something to cache/optimize here?
- Can the repository cache be used with bazel 5?

**Comment by LKreutzer** [comment]
Reuse of build step artifacts in test step with non-native config (i.e. asan or production) is low. 

Why is that? 
Is there an option that is blocking reuse?


https://github.com/magma/magma/issues/13653

**Comment by jheidbrink** [comment]
I just built the lte debian package with Bazel, then threw away /tmp but kept /var/cache/bazel_cache and .._repo, then built the debian package again. Result:
{code}
INFO: Elapsed time: 623.026s, Critical Path: 51.92s
INFO: 4841 processes: 684 disk cache hit, 160 internal, 3997 linux-sandbox.
INFO: Build completed successfully, 4841 total actions
{code}
The elapsed time was on a VM with 8 CPU cores and 12 GB Ram.

**Comment by jheidbrink** [comment]
Maybe the `--explain` flag is helpful for the analysis? https://bazel.build/reference/command-line-reference#flag--explain

**Comment by jheidbrink** [comment]
So far I couldn't reproduce the low cache hit ratio from https://github.com/magma/magma/issues/13362#issuecomment-1261913772

I completely removed all cache directives (including `--remote_download_...`) from `.bazelrc` and used the following line in zsh to build, clean local artifacs, and build again:
```
() { bazel build --remote_cache=$2 $1 && bazel clean --expunge && bazel build --remote_cache=$2  $1 } //lte/gateway/release:magma_deb_pkg   'http://localhost:9090'
```

The results:

```
  bazel-bin/lte/gateway/release/magma_1.8.0_amd64.deb
INFO: Elapsed time: 100.914s, Critical Path: 16.66s
INFO: 4841 processes: 4679 remote cache hit, 160 internal, 2 processwrapper-sandbox.
```

```
  bazel-bin/lte/gateway/release/magma-sctpd_1.8.0_amd64.deb
INFO: Elapsed time: 24.873s, Critical Path: 1.59s
INFO: 1878 processes: 1842 remote cache hit, 36 internal.
```

**Comment by jheidbrink** [comment]
Looking at the last Bazel Build & Test:

https://github.com/magma/magma/actions/runs/3335346711/jobs/5519231653 (config=asan, build only C targets)
```
INFO: Elapsed time: 51.031s, Critical Path: 1.92s
INFO: 5155 processes: 5152 remote cache hit, 1 internal, 2 local.
INFO: Build completed successfully, 5155 total actions
```

https://github.com/magma/magma/actions/runs/3335346711/jobs/5519231535, (no special flag, build everything)
```
 INFO: Elapsed time: 76.372s, Critical Path: 5.45s
INFO: 5881 processes: 5963 remote cache hit, 2 local, 8 processwrapper-sandbox.
INFO: Build completed successfully, 5881 total actions
```

https://github.com/magma/magma/actions/runs/3335346711/jobs/5519231746 (config=production, build only C targets)
```
 INFO: Elapsed time: 256.317s, Critical Path: 4.54s
INFO: 5155 processes: 5152 remote cache hit, 1 internal, 2 local.
INFO: Build completed successfully, 5155 total actions
```

**Comment by jheidbrink** [comment]
also related: #14311
