### ISSUE TITLE
Investigate bazel remote cache performance optimizations

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13360]
- Investigate the performance impact on CI runs of:
    - the flag [experimental_remote_cache_compression](https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_remote_cache_compression)
    - the flag [experimental_remote_cache_async](https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_remote_cache_async)
    - _grpcs_ vs. _https_ protocols
      - See also [comment by Zach Gray](https://github.com/magma/magma/issues/12458#issuecomment-1150243245)
      - only for read-only cache access as we didn't make basic auth over grpcs work yet when using an ALB
- See also notes/slides from the 2022 bazel eXchange conference

**Comment by LKreutzer** [comment]
![Image](https://user-images.githubusercontent.com/34488763/183074381-6e27f7ac-8975-4672-b73f-9ddbca72ebdf.png)

**Comment by nstng** [comment]
outdated - bazel remote caches are currently not used anymore
