### ISSUE TITLE
Prevent reuse of bazel caches across different environments

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13361]
See also https://github.com/magma/magma/issues/12458#issuecomment-1104112956

Bazel does not track tools outside of its workspace (like the system-installed C/C++ compiler etc.). It is thus not able to invalidate caches if these installed tools change. To avoid cache collisions we should use a unique cache key that reflects the versions of tools installed.

Suggestion for docker containers: Use the **image hash**. This has the disadvantage that it invalidates the caches even if an irrelevant detail of the image changes. The advantage is that this is simple and that the hash is guaranteed to change if a tool version changes.

VM and code spaces are out of scope here - separate stories will be created.

Ideas:
- Use the `sha-12345` tag of the docker image
    - How can this be fetched?
    - Is there a github action? 
    - Are we already using one in the image build jobs that can be reused? (see `docker/metadata-action@v3`)
- Alternative: calculate hash over dockerfile + docker build environment
- Why? To have similar mechanic for the vm (integ test workflow)

**Comment by nstng** [comment]
Outdated - we switched from remote caches to pre-build docker images with caches
