### ISSUE TITLE
Upgrade or replace moment.js

### ISSUE THREAD

**Issue by thmsschmitt** [magma/magma#13377]
Moment.js is no longer the library of choice as they admit on there own website https://momentjs.com/docs/#/-project-status/
Moment object are mutable and as such problematic to use as props or state in react.

Instead of upgrading we could also consider to switch to a different library. This requires more research and can also be done separately.

**Comment by Neudrino** [comment]
A very lightweight and quick near "drop-in-replacement" would be [Day.js](https://day.js.org/).

However, chart.js does not intrinsically work with Day.js, but needs [an adapter](https://www.npmjs.com/package/chartjs-adapter-dayjs-3). This adapter only works with chart.js v3 though.

I.e. The chart.js and moment upgrade might need to go in one bigger PR.

**Comment by Neudrino** [comment]
As day.js does not work together with chart.js well, now going for date-fns.
