### ISSUE TITLE
Fix IO exception error when using the bazel remote caches in the VM

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13383]
The following describes the initial issue. This did not happen anymore - reason might be that the base dev magma vm was updated.

But with new vm other issues popped up that are handled here. 

This is particularly relevant for the bazel LTE integ tests.

Context:
- Magma-vm (on MacOs GH runner or a fresh provision locally)
- Bazel remote cache configured
- Running a bazel build command (does not happen every time, but quite often)

Error: 

`"ConnectionError (HTTPConnectionPool(host='192.168.60.142', port=3333): Max retries exceeded with url"`

or 

```
ERROR: /home/vagrant/magma/lte/gateway/c/session_manager/BUILD.bazel:423:10: Linking lte/gateway/c/session_manager/sessiond failed: Exec failed due to IOException: 23 errors during bulk transfer:
com.google.devtools.build.lib.remote.http.DownloadTimeoutException: Download of '/magma-vm-lte-integ/cas/8eddd182fb4a6d14490fb767bff74074bf7b7b61b2525731503cc9f917cb3e56' timed out. Received 0 bytes.
com.google.devtools.build.lib.remote.http.DownloadTimeoutException: Download of '/magma-vm-lte-integ/cas/4c79871b35a7c5b27a17a335e75b4d9b26a0d9271bf64d96e2d33cc656564d9e' timed out. Received 442368 of 717800 bytes.
com.google.devtools.build.lib.remote.http.DownloadTimeoutException: Download of '/magma-vm-lte-integ/cas/7adc2a87d5773d1466dbbaf0d4e41604d4550c5732f2cb8b6aeefc24f88cae30' timed out. Received 442368 of 2213064 bytes.
com.google.devtools.build.lib.remote.http.DownloadTimeoutException: Download of '/magma-vm-lte-integ/cas/27d0e999eda3bb5f4c98a0a1f9fd706b2cdf56cc1bfd3efd76af562ab231324f' timed out. Received 33280 of 267000 bytes.
```

Definition of done:
- If IO exceptions occur they are not fatal to the build
- The services can be build with bazel with the remote cache in the bazel LTE integ test workflow
  - This may save up to 30min in the bazel LTE integ test workflow

May be helpful:

Similar `ConnectionError` issues with magma: 
https://magmacore.slack.com/archives/C0191LLL03S/p1628397576066200
https://magmacore.slack.com/archives/C019Z7Q4XJM/p1616875510061900
https://magmacore.slack.com/archives/C01AWMH0EJW/p1624353516028200
https://magmacore.slack.com/archives/C01AWMH0EJW/p1617020180046600
https://magmacore.slack.com/archives/C01M184QJGK/p1643375551700509
https://magmacore.slack.com/archives/C01AWMH0EJW/p1605378947173800
https://magmacore.slack.com/archives/C0191LLL03S/p1624342717279900
https://magmacore.slack.com/archives/C01AWMH0EJW/p1611212184000400

No real solution found:

- Rebuild VM
- Update to master
- Restart services

**Approaches**
* try to confirm that this is an issue with the magma VM -> create minimal setup (VM) and see if this still happens
  * try to narrow down the respective setup that causes this issue

timeboxed: 3 - if no results, then create follow-up issue

**Comment by jheidbrink** [comment]
Regarding the "create minimal setup" - I this when we were debugging slow LTE integration tests in the magma dev VM when building with Bazel. I created these files, maybe they are still helpful:

```
@ .github/workflows/bazel_build_in_vm.yml:4 @
name: bazel build in VM
on:
  workflow_dispatch:
jobs:
  bazel_build_in_vm:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          vagrant plugin install vagrant-vbguest vagrant-disksize
      - name: Bazel build
        run: |
          cd bazel/bazel_build_in_vm
          vagrant up
          vagrant ssh --command "cd magma && bazel/scripts/remote_cache_bazelrc_setup.sh vm ${{ secrets.BAZEL_REMOTE_PASSWORD }} && bazel build //..."
```

```
@ bazel/bazel_build_in_vm/Vagrantfile:4 @
Vagrant.configure("2") do |config|
  config.vm.synced_folder "../..", "/home/vagrant/magma"
  config.vm.define :bazelbuild, primary: true do |bazelbuild|
    config.vm.provider "virtualbox" do |vb|
      vb.memory=9000
      vb.cpus=3
    end
    config.vm.box = "ubuntu/focal64"
    config.vm.provision :shell, inline: "swapoff -a && fallocate -l 4G /swapfile && chmod 0600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' >> /etc/fstab && swapon -a"
    config.vm.provision :shell, inline: "echo vm.swappiness = 10 >> /etc/sysctl.conf && echo vm.vfs_cache_pressure = 50 >> /etc/sysctl.conf && sysctl -p"
    # Setup environment (copied from bazel-base-container Dockerfile):
    config.vm.provision :shell, path: "setup_bazel-base_environment.sh", env: {"MAGMA_ROOT" => "/home/vagrant/magma"}
    config.vm.provision :shell, inline: "if ! [ -x /usr/bin/bazel ]; then wget --progress=dot:giga https://github.com/bazelbuild/bazelisk/releases/download/v1.10.0/bazelisk-linux-amd64 && chmod +x bazelisk-linux-amd64 && cp bazelisk-linux-amd64 /usr/bin/b
azel && echo $PATH && cd /home/vagrant/magma && /usr/bin/bazel query //...; fi"
    config.vm.provision :shell, inline: "chown --recursive vagrant:vagrant /tmp/bazel"
  end
end
```

```
@ bazel/bazel_build_in_vm/setup_bazel-base_environment.sh:4 @
#!/usr/bin/env bash

set -euo pipefail


# This is copied from $MAGMA_ROOT/.devcontainer/bazel-base/Dockerfile and un-dockerfileized


echo "MAGMA_ROOT is $MAGMA_ROOT"

echo "Install general purpose packages" && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        apt-utils \
        bison \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        gcc \
        git \
        gnupg2 \
        g++ \
        iproute2 \
        iputils-ping \
        flex \
        libconfig-dev \
        libcurl4-openssl-dev \
        libczmq-dev \
        libgcrypt-dev \
        libgmp3-dev \
        libidn11-dev \
        libsctp1 \
        libsctp-dev \
        libssl-dev \
        libsystemd-dev \
        lld \
        net-tools \
        netbase \
        python3.8 \
        python-is-python3 \
        software-properties-common \
        systemd \
        unzip \
        uuid-dev \
        vim \
        wget \
        zip

apt-get install -y --no-install-recommends \
        libtool=2.4.6-14 && \
    echo "Install Folly dependencies" && \
    apt-get install -y --no-install-recommends \
        libgoogle-glog-dev \
        libgflags-dev \
        libboost-all-dev \
        libevent-dev \
        libdouble-conversion-dev \
        libboost-chrono-dev \
        libiberty-dev && \
    echo "Install libtins and connection tracker dependencies" && \
    apt-get install -y --no-install-recommends \
        libpcap-dev=1.9.1-3 \
        libmnl-dev=1.0.4-2

## Install Fmt (Folly Dep)
git clone https://github.com/fmtlib/fmt.git && \
    ( cd fmt && \
      mkdir _build && \
      cd _build && \
      cmake -DBUILD_SHARED_LIBS=ON -DFMT_TEST=0 .. && \
      make -j"$(nproc)" && \
      make install ) && \
    rm -rf fmt

# Facebook Folly C++ lib
# Note: "Because folly does not provide any ABI compatibility guarantees from
#        commit to commit, we generally recommend building folly as a static library."
# Here we checkout the hash for v2021.02.22.00 (arbitrary recent version)
git clone --depth 1 --branch v2021.02.15.00 https://github.com/facebook/folly && \
    ( cd folly && \
      mkdir _build && \
      cd _build && \
      cmake -DBUILD_SHARED_LIBS=ON .. && \
      make -j"$(nproc)" && \
      make install ) && \
    rm -rf folly

# setup magma artifactories and install magma dependencies
wget -qO - https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public | apt-key add - && \
    add-apt-repository 'deb https://artifactory.magmacore.org/artifactory/debian-test focal-ci main' && \
    add-apt-repository 'deb https://artifactory.magmacore.org/artifactory/debian-test focal-1.7.0 main' && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
        bcc-tools \
        liblfds710 \
        oai-asn1c \
        oai-gnutls \
        oai-nettle \
        oai-freediameter

# Update shared library configuration
ldconfig -v

ln -s "$MAGMA_ROOT"/bazel/bazelrcs/vm.bazelrc /etc/bazelrc
```

**Comment by LKreutzer** [comment]
- Filled the cache key: `magma-dev-vm`
  - Run: https://github.com/LKreutzer/magma/actions/runs/2832728919
  - Tests are failing (unclear what is going on)
  - Build was successful and cache is filled.

- Run with filled cache: https://github.com/LKreutzer/magma/actions/runs/2833218880
  - Using the cache can reduce the build time from ~40min to ~4min.
  - At least this build was successful and fully cached.
```
INFO: Elapsed time: 221.238s, Critical Path: 0.93s
INFO: 5038 processes: 4917 remote cache hit, 121 internal.
```
  - Cannot find any relevant errors in the logs.
  - Need more runs to confirm status.

**Comment by LKreutzer** [comment]
- In the run that filled the caches, the `ConnectionRefusedError: [Errno 111] Connection refused` errors are already occuring. Which means they occured without downloading from the cache.

**Comment by LKreutzer** [comment]
- It seems that the `runfiles` folder is not present -> magmad is not running -> tests are failing.

**Comment by LKreutzer** [comment]
- For testing: https://github.com/LKreutzer/magma/runs/7877895867?check_suite_focus=true
  - Remove remote download config with sed in the bazelrc
  - Use cache key `magma-dev-vm-debug`

**Comment by LKreutzer** [comment]
Possible solutions if the remote cache config is the issue:
- Modify config during LTE integ test bazel build
  - How to do this without writing in the `.bazelrc`?
- Modify the config in general 
  - Stop using remote cache configs `remote_download_toplevel` and `remote_download_minimal` 
  - Would increase cache costs
- Cherry-pick bazel 6 commit that might fix the issue?
  - Is this even possible? 
- Wait until bazel 6 to use the cache for the services(?)
- Run services directly with bazel
  - Probably not doable(?)
- Run `bazel run` on all services once at the beginning
  - Creates overhead and is an ugly hack

**Comment by LKreutzer** [comment]
Modify config during LTE integ test bazel build options:
- If possible: Use `--remote_download_minimal=no` or `--no_remote_download_minimal`
  - Might not be possible e.g. for the integ/sudo tests as they are run with a script that cannot pass on arguments. 
- Put the remote download config in the `cache.bazelrc` and sed in there.
  - Con: Removes information from the central `.bazelrc`.
  - Pro: The file is already a template.
- Sed into the `.bazelrc`.
  - Con: Not a good pattern.

**Comment by LKreutzer** [comment]
- Document cache configuration
- Proposal: Two configs:
  - Ro vs rw
  - Remote download flags vs none
  - Have option in config script to write the correct content in the `cache.bazelrc`

**Comment by LKreutzer** [comment]
This task requires https://github.com/magma/magma/issues/13651 to be merged.

**Comment by LKreutzer** [comment]
Test run with script modification from #13651: https://github.com/LKreutzer/magma/runs/7897314201?check_suite_focus=true
