### ISSUE TITLE
Run the integ tests with pytest

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13381]
## Run the integration tests (LTE, CWF and FEG) directly with pytest. 

Make is used simply as a wrapper for pytest, but may be replaced by a script in the future.

## Old description

Currently only the services are build by bazel in the bazel integ test workflow https://github.com/magma/magma/pull/13279, once the bazelification of the s1ap tests is completed the workflow should also use the bazel build tests.

This requires:
- https://github.com/magma/magma/pull/13344
- https://github.com/magma/magma/issues/13382
to be closed first.

Assumption:
* create new call in fab file and use it in ci
* make sure no make call is used on the magma_test vm - do not call bazel via fab, but use vagrant ssh (fab is too slow regarding logging) 
* try remote caches - if ioexceptions occur during testing, then document and do not use them for now
  * if this is not possible only to do in magma_test - create follow up issue for cache usage/separation
  * idea LK: move remote cache config after magma build -> so it only holds for magma_test. (workaround that is ok for now)

Check what files are published to firebase in make lte integ test workflow - if xml reports are needed, then mention this in #13526.

**Comment by vktng** [comment]
Initial draft test run:
https://github.com/vktng/magma/runs/7878825204?check_suite_focus=true

**Comment by vktng** [comment]
See: https://github.com/magma/magma/issues/13383#issuecomment-1217796772
The integ_test targets also have runfiles and same issue is expected here.

**Comment by vktng** [comment]
New issue created to add profile option: https://github.com/magma/magma/issues/13639

**Comment by vktng** [comment]
Test run 2: https://github.com/vktng/magma/runs/7880493470?check_suite_focus=true

- All test-result related steps deleted.
- Running all the tests.

**Comment by vktng** [comment]
Remote cache should be very important to have, because the Bazel build of the integ tests is slow (duration: TBD). The make build takes roughly 2 hours.

**Comment by vktng** [comment]
- [ ]  Create follow up story to publish test results
- [ ] Experiment with remote caching

**Comment by vktng** [comment]
Test run 3: https://github.com/vktng/magma/runs/7896253511?check_suite_focus=true
Using bash to execute the test.

**Comment by vktng** [comment]
Magma test VM should use a different cache key from Magma dev VM.

**Comment by vktng** [comment]
Test run 4: https://github.com/vktng/magma/actions/runs/2883367572
Using fabfile to execute local ssh commands.

**Comment by vktng** [comment]
Test run 4: https://github.com/vktng/magma/runs/7946930318?check_suite_focus=true
Using fabfile to execute local ssh commands.

**Comment by vktng** [comment]
Test run 6: https://github.com/vktng/magma/runs/7971056779?check_suite_focus=true
Executing all tests with local ssh.

**Comment by vktng** [comment]
Test run 7: https://github.com/vktng/magma/runs/7976115297?check_suite_focus=true
Executing ssh in the workflow yaml.

**Comment by vktng** [comment]
Test run 8: https://github.com/vktng/magma/runs/7976170702?check_suite_focus=true
Retrying vagrant ssh with test_attach_detach

**Comment by vktng** [comment]
Difference between fabric and vagrant ssh commands:

- Extra options for fabric: `-tt`
- Extra options for vagrant:
  - LogLevel=FATAL
  - Compression=yes
  - DSAAuthentication=yes
  - IdentitiesOnly=yes
  - ForwardAgent=yes

**Comment by vktng** [comment]
Test run 9: https://github.com/vktng/magma/runs/7976825715?check_suite_focus=true
Executing ssh in the yaml file with the arguments from the fabfile.

**Comment by vktng** [comment]
Test run 10: https://github.com/vktng/magma/runs/7991631877?check_suite_focus=true
Executing plain ssh in the workflow file with "fab args"
`ssh -i ~/.vagrant.d/insecure_private_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt vagrant@127.0.0.1 -p 2222 'cd \$MAGMA_ROOT;  sudo ethtool --offload eth1 rx off tx off; sudo ethtool --offload eth2 rx off tx off; export GATEWAY_IP=192.168.60.142; bazel/scripts/run_integ_tests.sh'`

**Comment by vktng** [comment]
Successfully reproduced locally with command:
`ssh vagrant@127.0.0.1 -p 2222 -o LogLevel=FATAL -o Compression=yes -o DSAAuthentication=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.vagrant.d/insecure_private_key -o ForwardAgent=yes 'cd $MAGMA_ROOT;  sudo ethtool --offload eth1 rx off tx off; sudo ethtool --offload eth2 rx off tx off; export GATEWAY_IP=192.168.60.142; bazel/scripts/run_integ_tests.sh //lte/gateway/python/integ_tests/s1aptests:test_attach_detach'`
`SInit(): Could not initialize the Logging streams`

**Comment by vktng** [comment]
| tool    | ssh config   | command                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | link                                                                  | status             | local/CI | error                                                                                                                                                                                                                                                                                                                                                             |
|---------|--------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------|--------------------|----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| fabric  |              | run(...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |                                                                       | (too slow)         | CI       |                                                                                                                                                                                                                                                                                                                                                                   |
| fabric  | fab args     | local ( 'ssh -i %s -o UserKnownHostsFile=/dev/null' ' -o StrictHostKeyChecking=no -tt %s -p %s ' ' \' cd $MAGMA_ROOT; ' ' sudo ethtool --offload eth1 rx off tx off; sudo ethtool --offload eth2 rx off tx off;' ' export GATEWAY_IP= %s ;' ' bazel/scripts/run_integ_tests.sh \' ' % (key, host, port, '192.168.60.142' ), )                                                                                                                                                     | https://github.com/vktng/magma/runs/7946930318?check_suite_focus=true | works              | CI       |                                                                                                                                                                                                                                                                                                                                                                   |
| vagrant | vagrant args | vagrant ssh -c 'cd ~/magma; bash -c "bazel/scripts/run_integ_tests.sh //lte/gateway/python/integ_tests/s1aptests:test_attach_detach"' magma_test                                                                                                                                                                                                                                                                                                                                  | https://github.com/vktng/magma/runs/7976170702?check_suite_focus=true |  ✖      | CI       | `SInit(): Could not initialize the Logging streams`                                                                                                                                                                                                                                                                                                               |
| vagrant | fab args     | vagrant ssh -c 'cd ~/magma; bash -c "bazel/scripts/run_integ_tests.sh //lte/gateway/python/integ_tests/s1aptests:test_attach_detach"' magma_test -- -tt -o LogLevel=INFO -o Compression=no -o IdentitiesOnly=no -o DSAAuthentication=no -o ForwardAgent=no                                                                                                                                                                                                                        | https://github.com/vktng/magma/runs/7976825715?check_suite_focus=true | ✖   | CI       | `SInit(): Could not initialize the Logging streams`                                                                                                                                                                                                                                                                                                               |
| ssh     | fab args     | ssh -i ~/.vagrant.d/insecure_private_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt vagrant@127.0.0.1 -p 2222 'cd \$MAGMA_ROOT;  sudo ethtool --offload eth1 rx off tx off; sudo ethtool --offload eth2 rx off tx off; export GATEWAY_IP=192.168.60.142; bazel/scripts/run_integ_tests.sh'                                                                                                                                                                   | https://github.com/vktng/magma/runs/7976825715?check_suite_focus=true |  ❓                |          |                                                                                                                                                                                                                                                                                                                                                                   |
| ssh     | vagrant args | ssh vagrant@127.0.0.1 -p 2222 -o LogLevel=FATAL -o Compression=yes -o DSAAuthentication=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.vagrant.d/insecure_private_key -o ForwardAgent=yes "cd \$MAGMA_ROOT; sudo ethtool --offload eth1 rx off tx off; sudo ethtool --offload eth2 rx off tx off; export GATEWAY_IP=192.168.60.142; bazel/scripts/run_integ_tests.sh  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach" | https://github.com/vktng/magma/runs/7976115297?check_suite_focus=true | ✖ | CI       | `ERROR: /home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/BUILD.bazel:71:12: Middleman _middlemen/lte_Sgateway_Spython_Sinteg_Utests_Ss1aptests_Stest_Uattach_Udetach-runfiles failed: missing input file 'external/s1ap_test_util/home/vagrant/s1ap-tester/bin/s1ap_types.py', owner: '@s1ap_test_util//:home/vagrant/s1ap-tester/bin/s1ap_types.py'` |
| ssh     | vagrant args | ssh vagrant@127.0.0.1 -p 2222 -o LogLevel=FATAL -o Compression=yes -o DSAAuthentication=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.vagrant.d/insecure_private_key -o ForwardAgent=yes 'cd $MAGMA_ROOT; sudo ethtool --offload eth1 rx off tx off; sudo ethtool --offload eth2 rx off tx off; export GATEWAY_IP=192.168.60.142; bazel/scripts/run_integ_tests.sh //lte/gateway/python/integ_tests/s1aptests:test_attach_detach'   |                                                                       | ✖      | local    | `SInit(): Could not initialize the Logging streams`                                                                                                                                                                                                                                                                                                               |
|         |              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                       |                    |          |                                                                                                                                                                                                                                                                                                                                                                   |
|         |              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                       |                    |          |                                                                                                                                                                                                                                                                                                                                                                   |

**Comment by vktng** [comment]
Test run 11: https://github.com/vktng/magma/runs/7995020331?check_suite_focus=true
Using vagrant-ssh with `-tt` and `shell: bash`.

**Comment by vktng** [comment]
Test run 12: https://github.com/vktng/magma/runs/7995699655?check_suite_focus=true
Using vagrant-ssh with `bash -i -c`.

**Comment by vktng** [comment]
`vagrant ssh -c 'cd ~/magma; bash -i -c "bazel/scripts/run_integ_tests.sh //lte/gateway/python/integ_tests/s1aptests:test_attach_detach"' magma_test -- -T`
`-T` turns off the interactive shell, with this the error `SInit(): Could not initialize the Logging streams` can be reproduced locally.

**Comment by vktng** [comment]
Test run 15: https://github.com/vktng/magma/runs/7996417183?check_suite_focus=true
Vagrant ssh with `-- -ttt`.

**Comment by vktng** [comment]
Test run 16: https://github.com/vktng/magma/runs/7997130758?check_suite_focus=true
Final (hopefully)!
All tests with `-- -ttt`.

**Comment by LKreutzer** [comment]
Test run:
https://github.com/LKreutzer/magma/runs/7997452812?check_suite_focus=true
For filling the caches with cache key `magma-test-vm`

**Comment by vktng** [comment]
These are provisioned with the `magma` role:
- config_stateless_agw.py
- config_iface_for_ipv6.py
- create_oai_certs.py
- generate_oai_config.py
- generate_dnsd_config.py

These are used in the service files:
- service_util.py
- config_stateless_agw.py
- generate_oai_config.py

**Comment by vktng** [comment]
Try this `vagrant ssh -c 'sudo sed -i "s@#precedence ::ffff:0:0/96  100@precedence ::ffff:0:0/96  100@" /etc/gai.conf;' magma` for:

- [ ] sudo tests
- [ ] integ tests

**Comment by LKreutzer** [comment]
- [ ] Remove all Make calls from the workflow

**Comment by vktng** [comment]
- [ ] Analyze profile data
- [ ] Limit Jobs
- [ ] Limit CPU
- [ ] Limit Memory

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8207617863?check_suite_focus=true
jobs=1
profile published
Bazel shutdown

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8207791146?check_suite_focus=true
limit_cpu=1
limit_memory=700

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8209164561?check_suite_focus=true
limit_cpu=HOST_CPU*.8

**Comment by vktng** [comment]
Local results for:
`time bazel/scripts/run_integ_tests.sh //lte/gateway/python/integ_tests/s1aptests:test_attach_detach //lte/gateway/python/integ_tests/s1aptests:test_attach_ul_udp_data //lte/gateway/python/integ_tests/s1aptests:test_no_attach_complete`

- 0m51.006s limit cpu=0,8
- 0m51.152s limit cpu=0,7
- 0m51.439s limit cpu=0,9
- 0m52.226s jobs=0,8
- 0m52.588s native
- 0m52.991s limit cpu=0,6
- 0m57.253s jobs=0,5
- 1m20.095s limit cpu=1 memory=700
- 1m31.647s config=limit_memory
- 1m48.517s bazel shutdown limit cpu=0,8
- 1m49.190s jobs=1 and bazel shutdown

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8225211367?check_suite_focus=true
`--local_cpu_resources=HOST_CPUS*.8`
All tests except sudo tests

**Comment by vktng** [comment]
- [ ] check if sudo tests can be faster too

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8225265349?check_suite_focus=true
`--jobs=HOST_CPUS*.8`
All tests except sudo tests

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8225945381?check_suite_focus=true
All tests
`--jobs=HOST_CPUS*.8`
Printing CPU and memory usage

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8225990859?check_suite_focus=true
All tests
`--local_cpu_resources=HOST_CPUS*.8`
Printing CPU and memory usage

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8226287253?check_suite_focus=true
With make bazel workflow
Printing CPU and memory usage

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8230479366?check_suite_focus=true
All tests
--local_cpu_resources=HOST_CPUS*.8
Printing CPU and memory usage
DEV_VM_CPU=2

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8246060294?check_suite_focus=true
Printing CPU and memory usage
MAGMA_DEV_MEMORY_MB=8192
MAGMA_DEV_MEMORY_MB=2048

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8246876978?check_suite_focus=true
Printing CPU and memory usage
Building everything first.

**Comment by vktng** [comment]
| jobs                | Bazel shutdown | RAM                         | CPU                                                                                     | workflow runtime | run_integ_test runtime | test_runtime | Note | link |
|---------------------|----------------|-----------------------------|-----------------------------------------------------------------------------------------|---------|----------|------------------------------------|------|-------|
| --jobs=1            | ✔              | native                      | native | 06:00:00  | 05:14:00  | cancelled |  | https://github.com/vktng/magma/runs/8207617863?check_suite_focus=true |
| native              | ✖              | --local_ram_resources=700Mb | --local_cpu_resources=HOST_CPUS*.8 | 02:25:00  | 01:37:00  | 01:28:00  | No extended or sudo tests | https://github.com/vktng/magma/runs/8207791146?check_suite_focus=true |
| native              | ✖              | native                      | --local_cpu_resources=HOST_CPUS*.8 | 02:15:00  | 01:28:00  | 01:20:00  | No extended or sudo tests | https://github.com/vktng/magma/runs/8209164561?check_suite_focus=true |
| native              | ✖              | native                      | --local_cpu_resources=HOST_CPUS*.8 | 03:57:00  | 03:05:00  | 02:52:00  | All tests except sudo tests | https://github.com/vktng/magma/runs/8225211367?check_suite_focus=true |
| --jobs=HOST_CPUS*.8 | ✖              | native                      | native | 03:56:00  | 03:07:00  | 03:56:00  | All tests except sudo tests | https://github.com/vktng/magma/runs/8225265349?check_suite_focus=true |
| --jobs=HOST_CPUS*.8 | ✖              | native                      | native | 04:23:00  | 03:03:00  | 02:53:00  | All tests, analysis failed for some | https://github.com/vktng/magma/runs/8225945381?check_suite_focus=true |
| native              | ✖              | native                      | --local_cpu_resources=HOST_CPUS*.8 | 04:44:00  | 03:18:00  | 03:06:00  | All tests | https://github.com/vktng/magma/runs/8225990859?check_suite_focus=true |
| native              | ✖              | native                      | native | 04:21:00  | 03:03:00  | 02:50:00  | With Make, not Bazel | https://github.com/vktng/magma/runs/8226287253?check_suite_focus=true |
| native              | ✖              | native                      | --local_cpu_resources=HOST_CPUS*.8, DEV_VM_CPU=2 | 04:23:00  | 02:56:00  | 02:47:00  | All tests | https://github.com/vktng/magma/runs/8230479366?check_suite_focus=true |
| native              | ✖              | native                      | --local_cpu_resources=HOST_CPUS*.8, MAGMA_DEV_MEMORY_MB=8192, MAGMA_TEST_MEMORY_MB=2048 | 04:17:00  | 02:55:00  | 02:48:00  | All tests | https://github.com/vktng/magma/runs/8247844700?check_suite_focus=true |
| native              | ✖              | native                      | MAGMA_DEV_MEMORY_MB=8192, MAGMA_TEST_MEMORY_MB=2048 | 04:25:00  | 03:04:00  | 02:52:00  | All tests | https://github.com/vktng/magma/runs/8265716953?check_suite_focus=true |
| native              | ✖              | native                      | native | 04:24:00  | 02:58:00  | 02:43:00  | All tests, building all tests first | https://github.com/vktng/magma/runs/8246876978?check_suite_focus=true |
| native              | ✖              | native                      | native | 03:55:00  | 02:46:00  | 02:34:00  | Currently broken master, with Make | https://github.com/magma/magma/runs/8256527110?check_suite_focus=true |

**Comment by vktng** [comment]
Testing branches:

- run_integ_test_job_with_bazel_limit_cpu_and_ram: Testing was mainly done here, force pushing removed changes previous runs. (Bazel args, build first, print cpu and memory)
- run_integ_test_job_with_bazel_build_all_first: Tests built together
- run_integ_test_job_with_bazel_limit_jons: Testing `--jobs`

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8277035370?check_suite_focus=true
Printing CPU and memory usage
Building everything first.
magma_test CPU = 2

**Comment by vktng** [comment]
https://github.com/vktng/magma/runs/8277069056?check_suite_focus=true
Printing CPU and memory usage
Building everything first.
magma_test CPU = 3

**Comment by LKreutzer** [comment]
https://github.com/LKreutzer/magma/runs/8306553844?check_suite_focus=true
magma_test CPU = 3

**Comment by LKreutzer** [comment]
https://github.com/LKreutzer/magma/actions/runs/3044597871/jobs/4905167516
magma_test CPU = 3 and magma_dev CPU 1

**Comment by LKreutzer** [comment]
https://github.com/LKreutzer/magma/actions/runs/3052348519/jobs/4921632893
magma test 2 cpus
magma dev 2 cpus

rebased on master

**Comment by LKreutzer** [comment]
https://github.com/LKreutzer/magma/actions/runs/3052436214/jobs/4921824354

 Run on PR after rebase

**Comment by vktng** [comment]
After rebase (sudo tests were split):
https://github.com/vktng/magma/actions/runs/3142927070/jobs/5107548377

1 test failed, no remote cache hits
4h47m for the workflow
3h58m for the test runtime

**Comment by vktng** [comment]
With remote caches, 3 failing tests:
https://github.com/vktng/magma/actions/runs/3142927070/jobs/5128937206
4h19m for the workflow
3h38m for the test runtime

**Comment by vktng** [comment]
With `--retry-on-failure` and build everything first:
https://github.com/vktng/magma/actions/runs/3157625019/jobs/5138721023
