### ISSUE TITLE
User confusion between the two wikis

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#13409]
### Your Environment

Github wiki: https://github.com/magma/magma
Linux Foundation wiki: http://wiki.magmacore.org/

### Describe the Issue

Because there are two wikis, one hosted by Github and one hosted by Linux Foundation, users are likely to be confused by where to find information and where to publish it. 

The purpose of each wiki should be clearly defined and communicated. 

* Github wiki ("Contributor Guide")
  * For all open-source development, regardless of organization
  * SDLC only, not TSC, business, or program management (apart from Issues)
* LF wiki ("Confluence")
  * For work funded through Linux Foundation 
  * All workstream types apart from software development

In defining the difference between the wikis, we may find documents that are redundant or that should migrate.

#### To Reproduce

1. For any given article, guess which wiki will contain it
2. Without prior experience viewing the article, you are likely to make wrong guesses

#### Expected behavior

Users should be able to consistently guess correctly at which wiki will contain which information.

#### Screenshots

LF wiki:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/111581/180806698-24f2b3f5-4a40-4001-aa57-a898e6d78c64.png">

Github wiki:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/111581/180806860-756f87c8-5ee6-4ba0-9f41-317f8f0e694a.png">

**Comment by Neudrino** [comment]
_My 2 cents:_
Visually both sites are rather different, such that seeing a page one can rather easily see, which tool it is in.
The confusion only arises because the string `wiki` was put into the Linux Foundation Confluence, such that both this string in their URL. A much more sensible choice would have been `confluence` for the Confluence.
If one could agree on the following naming, the problem would probably be resolved by itself:
- `Wiki` = Github Wiki = Contributor guide = the Github style page
- `Confluence` = the Linux foundation confluence = the Confluence Style violet page

**Comment by ildikov** [comment]
In this particular case I think we should focus on how these tools and resources are used:

* GitHub wiki tab:
The main artifact here is the Contributor Guide. This is rather static content that we will update when something changes or there's a new tool or process to describe. We are using this tool to store the Contributor Guide as it was the most compelling option to switch to; it is easy to update and it is close to the codebase and issue tracking interfaces that people use the most.

--> I would make sure that people see this as the source of information about how they can contribute and participate in the Magma community. We can clarify that on the landing page where people get when they click on "Wiki".

* Confluence:
The community is using Confluence as a more traditional and dynamic wiki tool, for instance we have meeting minutes, project team artifacts and other similar resources in it. It is expected that people will update the wiki pages more frequently based on how their teams and activities progress.

--> When we are pointing to the tool that the community is using as a wiki, we should point to Confluence and refer to it as 'Wiki".
