### ISSUE TITLE
 docs: eliminate Proposals in left nav in Docusaurus 

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#13411]
## Problem

The "Proposals" menu item in the left nav bar at [docs.magmacore.org](https://docs.magmacore.org) has gone stale. Each of the individual items in the menu should either be removed or is redundant.

1. The overview document [Magma Proposals](https://docs.magmacore.org/docs/proposals/p014_proposal_process) is redundant and is out of date. The correct information is in a different page, https://docs.magmacore.org/docs/contributing/contribute_proposals. 

2. The specific proposals listed in the nav should either be closed or they should be GitHub Issues using the type: proposal label. Otherwise this menu contradicts [Proposals Process](https://docs.magmacore.org/docs/contributing/contribute_proposals), which says "Proposals are tracked as GitHub Issues, using the type: proposal label." 

## Solution

If all the above items are removed, there will be nothing left in the menu. Therefore the menu as a whole should be removed.

## Non-Goals

Changes to any other items in the left nav or to the global nav on the top are out of scope.

## Context

For reference, this is a current screen shot:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/111581/180827926-c02161ab-0547-4aef-9d13-750a3de86906.png">

**Comment by Neudrino** [comment]
1. Regarding the Proposal workflow pages:
   1. The page https://docs.magmacore.org/docs/contributing/contribute_proposals was moved to the [Contributor Guide in Github Wiki](https://github.com/magma/magma/wiki/Adding-and-Tracking-Proposals) and should be cleaned up, i.e. removed. That page is probably a leftover of the bigger Migration of several pages to Github wiki which did not see any cleanup in the DocuSaurus.
      - Also see #9848 .
      - A contribution PR to clean this page up is welcome and does imho not need TSC attention.
   1. The page https://docs.magmacore.org/docs/proposals/p014_proposal_process is a design document similar to all other documents in this hierarchy and should imho not receive special treatment. Only the link in the yellow box at the top might be changed to point to the Contributor Guide on Github. Other than that the below applies.

1. Regarding the Proposals section, e.g. https://docs.magmacore.org/docs/proposals/p001_vpn_config_from_api
Those documents are design documents which are owned by the TSC. Design documents are different from proposals and can explicitly be [requested by the TSC during the proposal process](https://github.com/magma/magma/wiki/Adding-and-Tracking-Proposals#optional-needs-design-doc).
   - Thus I do see their relevance and they are not duplicated in my eyes.
   - A renaming of the section into "Design documents" might improve clarity.

**Comment by lucasgonze** [comment]
In the PR I will shortly submit I have:
- Renamed "Proposals" in the nav to "Design Documents"
- Updated the design doc for the proposals process per discussion above
- Removed https://docs.magmacore.org/docs/contributing/contribute_proposals from the sidebar

CC'ing @ildikov to keep her informed.

Note that my PR will also cover #13386.

**Comment by lucasgonze** [comment]
Fixed in https://github.com/magma/magma/pull/13547
