### ISSUE TITLE
[AMF]: MSIN in BCD format is not provided for encryption by spirent

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#13419]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

Version :- 1.8.0-1658821072-44f94ca1
Affected Component :- AGW
Affected Subcomponent :- AGW
Deployment Environment :- Baremetal - VM based

### Describe the Issue

Registration with SUCI profiles is failing as AMF is taking invalid MSIN , even after MSIN decrypted in subscriberdb  is fine

#### To Reproduce

1. Store proper SUCI Profiles in subscriber-db.
2. Try to trigger the SUCI registration with Profile-A from UE with proper MSIN encryption.
3. Check that MSIN is getting decrypted properly and AMF is triggering sub-procedures for the derived IMSI.
4. But AMF is getting an improper IMSI so Registration is getting rejected.

#### Expected behavior
Decryption of IMSI should work fine and registration should get success.

Note: SUCI registration is working fine in Spirent Setup.
IN Spirent Cyphertext length is 10 and 
In Abot Cyphertext length is 5.

#### Screenshots
decrypted MSIN in syslogs:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/dfd7adba-1009-4668-8e7d-fec2afe3d5d5)

With same Keys MSIN derived from script :
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/0c3d281c-3f58-4285-bc40-4a7cb3db6d12)

IMSI that AMF is getting and Processing Auth-Procedure:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/21d7d369-79e6-4751-906d-5bf54661ee5c)

#### Additional context

Please find attached logs for more info
[https://app.zenhub.com/files/170803235/45d8e2cf-36c1-478a-b24c-8e216840c4a5/download](https://app.zenhub.com/files/170803235/45d8e2cf-36c1-478a-b24c-8e216840c4a5/download)

**Comment by apekshapk** [comment]
For same MSIN, in spirent we are observing the deconcealing happening properly. 
Syslog: 
ubuntu@tes-team-agw-3:~$ sudo tail -f /var/log/syslog | grep subscriberdb
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:M5GDecryptMsinSUCIRegistration Request:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:GRPC message:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   magma.lte.M5GSUCIRegistrationRequest {
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "uePubkeyIdentifier": 1,
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "uePubkey": "L+BwSlVX7Q/Pe7TO312Cm8Osw7kXQouyxeLEHFYPfCE=",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "ueCiphertext": "B8qKtXt7KtfbLg==",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "ueEncryptedMac": "tsGEm8zqpUU="
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   }
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:Deconcealed **MSIN: b'0000000199'**
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:M5GDecryptMsinSUCIRegistration Response:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:GRPC message:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   magma.lte.M5GSUCIRegistrationAnswer {
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "ueMsinRecv": "MDAwMDAwMDE5OQ=="
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   }
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:M5GAuthenticationInformation Request:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:GRPC message:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   magma.lte.M5GAuthenticationInformationRequest {
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "userName": "001010000000199",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "servingNetworkName": "5G:mnc001.mcc001.3gppnetwork.org"
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   }
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:M5GAuthenticationInformation Response:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]: INFO:root:GRPC message:
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:   magma.lte.M5GAuthenticationInformationAnswer {
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "errorCode": "SUCCESS",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     "m5gauthVectors": [
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:       {
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:         "rand": "dSIEP+0ROrf5tzxAFG7Eiw==",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:         "xresStar": "dVzMMFPVc4bU/hny4UfNYQ==",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:         "autn": "w/o2+oiagADkQJpj0aYLOw==",
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:         "kseaf": "6upuRZCDYj2ah4UglSv3osl+uDHDvc1qL3VYdqWYiYw="
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:       }
Jul 27 08:03:33 tes-team-agw-3 subscriberdb[2276811]:     ]

**Comment by NeelimaKalpana** [comment]
This issue is merged in Master and validated .
Version : 1.8.0-1666201330-02bd3e60
Please find the attached validation logs.
[https://app.zenhub.com/files/170803235/e6a0af23-b798-47a8-a1f3-0897322e275b/download](https://app.zenhub.com/files/170803235/e6a0af23-b798-47a8-a1f3-0897322e275b/download)

**Comment by NeelimaKalpana** [comment]
This issue is merged in Master and validated .
Version : 1.8.0-1666201330-02bd3e60
Please find the attached validation logs.
[https://app.zenhub.com/files/170803235/e6a0af23-b798-47a8-a1f3-0897322e275b/download](https://app.zenhub.com/files/170803235/e6a0af23-b798-47a8-a1f3-0897322e275b/download)
