### ISSUE TITLE
Upgrade trafficgen VM to Ubuntu 20.04

### ISSUE THREAD

**Issue by crasu** [magma/magma#13424]
https://github.com/magma/magma/issues/13203

Description:
Also find out if the imports in the trafficgen Python code work correctly. Looking at the repository, its Python code is supposed to be in lte/gateway/deploy/roles/trfserver/files. The Ansible script only links one of these files in the VM. The other file is imported there with a non-relative path but has the same name as another file from the integration tests, which we reverted to keep it compatible with Python 3.5

**Comment by Neudrino** [comment]
This is a duplicate of https://github.com/magma/magma/issues/13203.
