### ISSUE TITLE
Migrate JFrog Artifactory from Magma to Linux Foundation

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13439]
## Prerequisits

- https://github.com/magma/magma/issues/13466
- https://github.com/magma/magma/issues/13449
- https://github.com/magma/magma/issues/13450

## Actions

- [ ] Check status of Linux Foundation (LF) Artifactory & Read Access
- [ ] Set LF token in Magma Github organisation
- [ ] Migrate one artifact upload workflow to LF Artifactory
- [ ] Use (the one) artifact from LF Artifactory in other CI jobs
- [ ] Roll-out the Artifactory switch to LF Artifactory for other artifacts

**Comment by Neudrino** [comment]
Might be related: https://github.com/magma/magma/issues?q=is%3Aopen+is%3Aissue+author%3Atmdzk+registry
- https://github.com/magma/magma/issues/13897
- https://github.com/magma/magma/issues/13898
- https://github.com/magma/magma/issues/13899
- https://github.com/magma/magma/issues/13900

**Comment by nstng** [comment]
duplicates #14495
