### ISSUE TITLE
Download links for rootca.perm and control_proxy.yml are broken

### ISSUE THREAD

**Issue by thmsschmitt** [magma/magma#13432]
The links should be removed and the text should be rephrased 

![Image](https://user-images.githubusercontent.com/102796295/181239811-fbd911a9-d068-4d29-971d-639c840d98e2.png)

**Comment by Neudrino** [comment]
`control_proxy.yml` documentation is described on https://docs.magmacore.org/docs/next/lte/deploy_install#post-install-check .
Zertificate configuration is described on https://docs.magmacore.org/docs/next/lte/deploy_config_agw .
