### ISSUE TITLE
Create CI to upload ONE deb artifact to JFrog Artifactory

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13449]
## Acceptance criteria

The artifact type should be `deb` and hence should the repository type be and **debian package repository**.

The CI job should
- have a manual trigger
- should not have an automatic trigger
- allow to configure the target repository
  - the default should be set to a testing, i.e. `*-test` repository

## To be clarified

- building the artifact:
  - we might want to have this separately, as building different artifacts is very different, but upload is always the same
- add build-number to version, so that every upload is unique
- test the uploaded artifact before uploading

**Comment by voisey** [comment]
@wolfseb @MoritzThomasHuebner Has this already been done? If so, could you please link the corresponding PR?

**Comment by MoritzThomasHuebner** [comment]
@voisey @Neudrino I think this should have been the linked PR:
https://github.com/magma/magma/pull/13431

Sorry, I haven't seen the notification until now.
