### ISSUE TITLE
Get s1ap-tester containerization merged

### ISSUE THREAD

**Issue by crasu** [magma/magma#13455]
## Context

The following pr containerizes the agw integ tests #11308. Before we merge this we want to bring the coding style. As this pr is pretty large it might be a good idea to split it up.

- [x] Try to build and run the s1ap container and trf container. It will likely fail without changes pointed out in the PR.
  - It's possible to run tests by starting the container inside the test vm (after installing docker). No other setup worked so far.
- [x] Start a branch from the existing PR and open a PR against the existing PR's branch. Fix all issues that have been pointed out in the PR's comments. Start from the comments at the bottom, the last comments from 21 July contain the relevant points.
  - https://github.com/sebathomas/magma/commit/4ae2b03847346f16757ae297b4120593f99f0d55
- [ ] Mount src into s1ap container
- [x] Run integration tests of each category: precommit, extended, nonsanity, traffic server. If any more fixes are necessary, do it in a PR against the existing PR again.
- [ ] Optional: Create a new CI workflow to build the container.
- [ ] Prepare internal review meeting

Hint: If you need CI, you may have to also open a PR against master.

## Acceptance criteria
- Understand how the architecture for the containerized agw works
    - How are service restarts are handled?
    - How are configuration restarts handled?
- Make the s1ap-container work in the dev vm
- Get the pr merged
- Update coding style issues
- Test each category of integration tests on your machine, but you don't have to get all tests green
  - precommit
  - extended
  - nonsanity
  - traffic server (you need to run the equivalent of `disable-tcp-checksumming` on the container)

**Comment by maxhbr** [comment]
relevant message in some random private chat: https://magmacore.slack.com/archives/C02HRAXJEBB/p1661175624268159?thread_ts=1655754232.877589&cid=C02HRAXJEBB

**Comment by sebathomas** [comment]
A merge of the PR is currently not planned.
