### ISSUE TITLE
Rollout CI to upload artifacts to JFrog Artifactory for all repository types

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13450]
## Story

Based on the previous work for `deb` files (#13449) we want to be able to upload any artifact (type) to the JFrog Artifactory for easy distribution.

## Prerequisits

- https://github.com/magma/magma/issues/13449

## Acceptance criteria

- Supported `Package Types` should be:
  - Debian (#13449)
  - Docker
  - Generic
- The CI job is 
  - modular and reusable.
  - callable from other pipelines.
  - configurable with respect to 
    - the repository type
    - the target repository
    - _possible other relevant configurations_
  - has sensible and save defaults, where possible. I.e. not by accident changing anything on production repositories.

## Additional information

- [Composite Actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) could be used to make the jobs modular and reusable.
- It might be checked if the [`choice` input](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs) can also be used with composite actions.

**Comment by nstng** [comment]
handled by #14495
