### ISSUE TITLE
[Regression Issue]: UE is not getting de-registered when we are making subscriber state to Inactive in NMS dashboard.

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13461]
- Version: 1.8.0-1658998712-78900dda
- Affected Component: Access Gateway, or NMS
- Deployment Environment: e.g. Bare-metal (AGW) - VM based.

While performing Registration with PDU and Traffic when UE is active and PDU is established and from NMS if for registered IMSI we turn configs to Inactive, it is expected to trigger Deregistration after AGW receiving Inactive configuration from Orc8r. But still the IMSI is not getting deregistered.

ACTIVE -- IMSI001019976545660
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/eae479e6-f568-4f81-9ba6-f7e991c491f5)

INACTIVE -- IMSI001019976545660 
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/720718c4-1bed-4e9f-9507-f5542ab5c7e8)

Please find the attached logs for the same:
[https://app.zenhub.com/files/170803235/b9265b46-8cc8-4d3c-a88f-091b2de2b309/download](https://app.zenhub.com/files/170803235/b9265b46-8cc8-4d3c-a88f-091b2de2b309/download)
[https://app.zenhub.com/files/170803235/cb063d5a-ed52-4533-b1a2-9392d0a44ba8/download](https://app.zenhub.com/files/170803235/cb063d5a-ed52-4533-b1a2-9392d0a44ba8/download)
[https://app.zenhub.com/files/170803235/a6e97268-8152-4d42-bfbb-ff4c746b0d37/download](https://app.zenhub.com/files/170803235/a6e97268-8152-4d42-bfbb-ff4c746b0d37/download)

**Comment by sebathomas** [comment]
I just tried to reproduce this and noticed that sometimes the subscriber root_digest doesn't get updated when you update individual subscribers. In that case, subscriberdb on the gateway won't update its copy of the information. That might have something to do with the bug.

Unfortunately, there doesn't seem to be much logging in subscriberdb so it's hard to tell. But from the logs in zenhub, I never see the root digests changing.

Could this be the cause or can you tell in your case that subscriberdb performs a sync and the deregistration is lost somewhere later?

**Comment by blueCARDSS** [comment]
Hi 

We badly need this feature to support!!! Is there any way that some one can fix it ?

@sebathomas @apekshapk

**Comment by sebathomas** [comment]
Can you confirm that the INACTIVE state doesn't propagate to the gateway, even after some time?

**Comment by blueCARDSS** [comment]
yes we did testing for different interval  . Example 15 min , 20 min ,30 min but still ue remain active in network .

**Comment by AtulSmahale** [comment]
Hi @sebathomas @apekshapk 

In the second test we connected the 1.8 Orc8r to the AGW (1.6.1 ver.) and Inactive the UE and it took 10 minutes to deactivate the UE. When the UE is activated from inactive, it takes 10 minutes for the UE to become active but the UE is not reconnecting automatically. When we manually attach the UE- then the UE gets connected to the system. please find below the attached logs file.
[New folder.zip](https://github.com/magma/magma/files/9645805/New.folder.zip)

**Comment by sebathomas** [comment]
I haven't looked at the new logs yet, but one thing I noticed is that the behavior is different for setting a subscriber to inactive vs. deleting a subscriber. Deletion triggers a detach, inactivity doesn't. I'm not sure if deleting the subscriber is an option for your use case, but it should result in a detach.

I don't know yet if this behavior used to be different before the changes of the subscriber sync code for v1.6, and if it would actually be correct to immediately detach inactive subscribers.

**Comment by sebathomas** [comment]
Looking at the code of old releases, I think the behavior was changed between v1.6 and v1.7 (probably when subscriberdb was adapted to use the digests for performance reasons). Back in v1.6, subscribers not in state ACTIVE got a detach request together with deleted subscribers, since v1.7 only deleted subscribers are detached.

**Comment by blueCARDSS** [comment]
@sebathomas how to achieve similar behaviour like 1.6 ...we are running network in production with approx 4k users  . We want to deploy 1.8 for better improvement how we can solve this challenge

**Comment by sebathomas** [comment]
I don't think there is anything you can do manually except delete the subscriber if that is an option.

I'm trying to come up with a patch to restore the old behavior.

**Comment by blueCARDSS** [comment]
@sebathomas yes patch will be very useful .Thank you for your support

**Comment by sebathomas** [comment]
@blueCARDSS Still working on a test and I will continue tomorrow, but I think the changes to client.py from #14024 can solve the issue.

**Comment by sebathomas** [comment]
With the changes of #14024, this issue should be fixed on master. It would be great if someone could test it with a more production-like setup.

Another question is if the fix should be backported to v1.7 and v1.8.

**Comment by blueCARDSS** [comment]
hi we are going to test .and will share with you outcome

**Comment by moinuddin1980** [comment]
> With the changes of #14024, this issue should be fixed on master. It would be great if someone could test it with a more production-like setup.
> 
> Another question is if the fix should be backported to v1.7 and v1.8.

HI @sebathomas 
We have tested the changes using the SRSRAN based 4G subscriber.
We see that when the subscriber is attached and we change the state from ACTIVE to INACTIVE in NMS, the subscriber gets deregistered in the AGW after  ~ 6 mins.
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/93516965/193257029-ebe4ecb9-0232-4550-b0b4-bb2ad8c97103.png)

BR,
Moin

**Comment by sebathomas** [comment]
Thank you! Looks like it's working now. :+1:

The delay is expected because it needs to run the periodic update first on the orc8r and then on the agw subscriberdb before triggering a deregistration.

**Comment by blueCARDSS** [comment]
@sebathomas hi morning ...is it possible to reduce sync time. We want to reduce it to 30 sec

**Comment by sebathomas** [comment]
@blueCARDSS 

The relevant configs to reduce the sync time are
* `syncInterval` in the gateway subscriberdb mconfig and
* `sleepIntervalSecs` in the orc8r subscriberdb_cache config.

**Comment by blueCARDSS** [comment]
@sebathomas hi we did changes syncInterval in the gateway subscriberdb mconfig and realise once AGW reboot again it went back to normal 300seconds 


sleepIntervalSecs in the orc8r subscriberdb_cache config. we dint mange to find path for this .

**Comment by sebathomas** [comment]
@blueCARDSS How did you change the mconfig? You need to update the value on the orc8r side, if you change it on the gateway it will be overridden by the orc8r config again in the next periodic sync. It's part of the gateway `cellular.epc` config and can be set in swagger. However, the minimum value is currently 60 seconds.

For the sleepIntervalSecs, do you have a subscriberdb_cache.yml? How did you deploy your orc8r?
