### ISSUE TITLE
[NMS] Subscriber edit page error after reload

### ISSUE THREAD

**Issue by HannaFar** [magma/magma#13506]
### Describe the Issue

Subscriber edit page error after reload.
We use paginated subscriber and we use the current page to show informations, this creates an error after a reload if the subscriber is not included in the first page

#### To Reproduce

1. Go to subscriber overview and go to page 2
2. Go to a subscriber edit config page
3. reload the page

#### Screenshots

https://user-images.githubusercontent.com/26038920/182860058-250ffdda-e8e6-4d94-b99e-28eea6cde88f.mov

**Comment by sebathomas** [comment]
Tasks
- [ ] Reproduce and fix the bug
  - The problem seems to be how the contexts of the subscriber data are handled on the subpage, i.e. that only the data for the first N subscribers is automatically loaded from the backend.
- [ ] Prepare internal review.
