### ISSUE TITLE
xml unit test reports are created and published

### ISSUE THREAD

**Issue by nstng** [magma/magma#13526]
* figure out how to create unit test XMLs using `bazel test ...`
  * might need to be split between py, go, c/c++
  * if needed create a concept to merge them to one XML file (at least for the different languages)
    * if merging of reports is necessary use `runtime_report.py` (see integration test script for usage)
* implement creating and publishing based on the findings above in CI workflows (`bazel.yml`)

**Comment by vktng** [comment]
In the LTE integ tests the following commands are executed:
```
- name: Publish results to Firebase
        if: always() && github.event.workflow_run.event == 'push'
        env:
          FIREBASE_SERVICE_CONFIG: ${{ secrets.FIREBASE_SERVICE_CONFIG }}
          REPORT_FILENAME: "lte_integ_test_${{ env.SHA }}.html"
        run: |
          npm install -g xunit-viewer
          [ -d "lte/gateway/test-results/" ] && { xunit-viewer -r lte/gateway/test-results/ -o "$REPORT_FILENAME"; }
          [ -f "$REPORT_FILENAME" ] && { python ci-scripts/firebase_upload_file.py -f "$REPORT_FILENAME" -o out_url.txt; }
          [ -f "out_url.txt" ] && { URL=$(cat out_url.txt); }
          python ci-scripts/firebase_publish_report.py -id ${{ env.SHA }} --verdict ${{ job.status }} --run_id ${{ github.run_id }} lte --url $URL
```
The` lte/gateway/test-results/` is the relevant folder.
