### ISSUE TITLE
Understand why the orc8r needs tenants

### ISSUE THREAD

**Issue by thmsschmitt** [magma/magma#13529]
Tasks:
- [x] Understand what tenants are used for in orc8r
- [x] Understand what organizations are used for in NMS
- [x] Document solution paths (to enable decision if they should be kept in sync (status quo) or if the information should live only in one of the components)
- [x] Prepare internal review meeting

Organization are managed through the NMS backend and are stored in the NMS database.
The orc8r has a tenants service that also stores the organizations.
The tenant service is only synced with the NMS when the 'Metrics' tab in NMS GUI is opened https://github.com/magma/magma/issues/11331
Tenants that are added directly though swagger are ignored by the NMS.   

Find out what tenants are needed for in the orc8r and if it would make sense to move the organization state to the orc8r.

**Comment by alexzurbonsen** [comment]
## What does the documentation say? 

The documentation suggests, that tenants and organizations might be the same concept, that got a frontend and a backend name.

From [nms/README.md](https://github.com/magma/magma/blob/master/nms/README.md)

> Multitenancy is supported in the Magma NMS. Each tenant is called an "organization".
> Each organization owns a subset of the networks provisioned on Orchestrator, and the special `host` organization administrates organizations in the system.

From https://docs.magmacore.org/docs/nms/nms_organizations

>  Tenants in the NMS are called "organizations".

Also note:

> Note that multitenacy is currently only supported through mechanisms living in the NMS, but not through the Orc8r API.

**Comment by alexzurbonsen** [comment]
### Tenants and Organizations: Sync

As described in #11331 there is a function `syncTenants` in NMS, that created and updates orc8r's tenants according to NMS' organizations (i.e. tenants are updated to equal organizations).

This function is only called in nms/server/grafana/handlers.ts

```
async function syncGrafana(req: Request, res: Response, next: NextFunction) {  
  const [tenantsRes, grafanaSyncRes] = await Promise.all([  
    syncTenants(),  
    syncGrafanaMeta(grafanaAdminClient, req),  
  ]);
  
  ...
```

**Comment by alexzurbonsen** [comment]
### Tenants in orc8r

There is a `tenants`service in orc8r. What is it used for? The documentation says 

> tenants provides CRUD interface for managing NMS tenants

### Go

Its grpc interface has the following callers in Go code (checked for the methods in `client_api.go`):

- `GetAllTenants`
	- no callers
- `CreateTenant`
	- obsidian handler
	- tests: bootstrapper, metricsd, obsidian
- `GetTenant`
	- obsidian handler (and a helper function for other handlers)
	- services: metricsd, certifier
- `SetTenant`
	- obsidian handler
- `DeleteTenant`
	- obsidian handler
- `GetControlProxy`
	- obsidian handler
- `GetControlProxyFromNetworkID`
	- service: bootstrapper
- `CreateOrUpdateControlProxy`
	- obsidian handler
	- tests: bootstrapper 

Except for `GetAllTenants` every method is called by an obisidian handler / endpoint.

Three other services use the tenants service (not counting tests):

**bootstrapper**

called in `Registration` grpc-service's endpoint
`Register` -->  `GetControlProxy` --> `GetControlProxyFromNetworkID` 

**certifier**

highest caller of `GetTenant` is a grpc endpoint of certifier: `GetPolicyDecision`

```go
[orc8r/cloud/go/services/certifier/servicers/protected/certifier.go]

// GetPolicyDecision makes a policy decision when a user attempts to access a resource.// For conflicting policy decisions from multiple tokens (e.g. one policy is ALLOW and the other DENY), the DENY effect  
// will take precedent.  
// For resources that do not have any policies addressing it, the policy decision defaults to DENY as well.  
func (srv *CertifierServer) GetPolicyDecision(ctx context.Context, getPDReq *certprotos.GetPolicyDecisionRequest) (*certprotos.GetPolicyDecisionResponse, error) {


// Networks are registered with tenants, hence any tenant scoped policies  
// have additional policies for their networks.
```

**metricsd**

various handlers in `orc8r/cloud/go/services/metricsd/prometheus/handlers/promo_handlers.go` call `GetTenant` via `tenantQueryRestrictorProvider`

### Python

There don't seem to be any callers in Python. grpc generates methods with the same name (see /home/vagrant/build/python/gen/orc8r/protos in the magma VM) that are not called in .py files.

**Comment by alexzurbonsen** [comment]
### Organizations in NMS

Organizations can be created and configured via host.localhost in NMS. In addition to the accessible networks one can also configure SSO options. Details about Organizations are stored in the "Organizations" table in the NMS' postgres database, see below for an example.

![Screenshot 2022-08-22 at 12 02 54](https://user-images.githubusercontent.com/82914459/185927846-b81337f0-c736-40a5-bc91-6aa13b9204d8.png)

As one can see in the picture the 8 rightmost columns, store sign-on details for that particular organization.

These details are not synced with orc8r's tenants table (see screenshot below). This table is the standard blobstore, where the value column holds a the values for tenant name and accessible networks.

<img width="901" alt="Screenshot 2022-08-22 at 15 05 12" src="https://user-images.githubusercontent.com/82914459/185928197-a82814b4-df34-4bdb-964d-059c84461ffb.png">

**Comment by alexzurbonsen** [comment]
### Synthesis

The tenant service needs information about tenants and their accessible networks for certificate related tasks in services like bootstrapper and certifier. It thus does not seem to be a sensible option to remove tenants from orc8r and store them in NMS only.
In turn, NMS needs the same information to provide functionality for organizations. Additionally it holds more specific information, that is the SSO options for each organization/tenant. These SSO options should not be kept in the orc8r because they concern the front-end only. 

Thus unification of data sources by removing orc8r's tenants or NMS' Organizations table, is not reasonable.   

Instead, to fix the bug we want to keep the data sources in sync in a more reliable way.

**Comment by alexzurbonsen** [comment]
### First sketch for a more reliable sync

Currently, tenants can be created via orc8r's swagger interface and via the GUI in the host in NMS. If created in the orc8r, the data is stored in the orc8r only. If created in the NMS, the data is stored in the NMS and only written to orc8r if the Grafana tab in NMS is opened.

To keep tenants and organizations in sync it would be nice if
1) in NMS
  a) the user sees an up-to-date list in host.localhost in NMS
  b) once an organization is created or updated, the data is written to orc8r automatically (need for to 2a)
2) in orc8r
  a) the user gets an up-to-date list if requested
  b) once a new tenant is created, the data gets pushed to NMS automatically (needed for 1a)

What happens in the case of conflict?
I.e. a tenant and an organization with the same name are created or updated simultaneaously in orc8r and NMS.
This sounds rather unlikely to me, but might anyways lead to some confusing behaviour. 
Implementing something like a lock between the two databases seems to be a bit of an overkill though.
The easiest solution might be to give one of the two precedence in the sync process.

What would be needed to implement such a solution?
1a) the calls that produce the table in https://host.localhost/host/organizations should trigger a sync step first.
1b) same for the create, update and delete functions on that page
2a) if NMS is started there should be a sync with orc8r, additional changes are captured by 1b
2b) if NMS is present, orc8r needs to talk to it and send modifications from post, put and delete calls to the Organizations table (guess there is no interface for this yet?)

The assumption here is, that an orc8r will already be there if an NMS is started and accessed.

**Comment by alexzurbonsen** [comment]
B) Sketch for deduplication: tenants in orc8r and corresponding SSO info in NMS

Alternatively, we could separate concerns cleaner and delete the `name` and `networkIDs` column from NMS' Organizations table. They encode the organization name and its accessible networks. This information is also stored in ocr8r's tenants table.

This requires:
in NMS
  1)
    a) all calls that do CRUD on data from Organization's table, need to interact with orc8r's tenants table to CRUD name and accessible networks
    b) the view of the organizations list in host.localhost should be up-to-date to ensure that users work with the latest status of orc8r
 
The assumption here is, that an orc8r will already be there if an NMS is started and accessed.

**Comment by alexzurbonsen** [comment]
Closing this one since all tasks within scope are done. Work continues in https://github.com/magma/magma/issues/11331
