### ISSUE TITLE
[AMF]: Session modification issues with policy clean up

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13536]
- Version:  1.8.0-1659649293-b6f20959
- Deployment Environment:** e.g. bare-metal (AGW)-VM based.

While testing session modification with ADD session policy, PDU Modification is getting triggered but if I'm deleting the session policy, policy is not getting deleted.

![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/da0ebdc6-f9be-4734-a472-9e0db62d783a)

Please find the attached logs below:
[https://app.zenhub.com/files/170803235/17895ae2-2a11-41b9-b5d1-7e399b1d0ba4/download](https://app.zenhub.com/files/170803235/17895ae2-2a11-41b9-b5d1-7e399b1d0ba4/download)
[https://app.zenhub.com/files/170803235/158c6cd6-3154-4b29-b27c-e6980ab76949/download](https://app.zenhub.com/files/170803235/158c6cd6-3154-4b29-b27c-e6980ab76949/download)
[https://app.zenhub.com/files/170803235/9ebee2cc-8574-43ba-a346-3a9de8c5f7bc/download](https://app.zenhub.com/files/170803235/9ebee2cc-8574-43ba-a346-3a9de8c5f7bc/download)

**Comment by NeelimaKalpana** [comment]
Latest Observation : 

In Positive Flow I am Observing that there is no error at CLI level.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/71506ddc-5599-414d-9960-017b9aa29cea)

Syslogs Capture where Sessiond is sendinga empty PolicyReAuthAnswer.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a69fad3f-447e-4a0a-9902-4fdc11014932)


Please find the latest logs:

[https://app.zenhub.com/files/170803235/70db134b-ddf2-4f6e-9fee-815153652438/download](https://app.zenhub.com/files/170803235/70db134b-ddf2-4f6e-9fee-815153652438/download)

**Comment by apekshapk** [comment]
Updated logs for session modification with Delete policy.
Please find the attached logs:
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/17e408e4-8e84-4d69-b9ef-8dc7c63cdded)
[https://app.zenhub.com/files/170803235/aa8c9cdd-2f94-4b8f-ae10-dfc7a5db9301/download](https://app.zenhub.com/files/170803235/aa8c9cdd-2f94-4b8f-ae10-dfc7a5db9301/download)
