### ISSUE TITLE
Every fork of magma tries to publish AMIs

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#13544]
Reported by @maxhbr:

> Every fork of magma tries to publish AMIs with a weekly job. Can we fix that so that it only runs on magma/magma? We shouldn't rely on them not having the credentials. There are secrets that get added to forks for testing and developing actions.

### Describe the Issue

Every fork of Magma inherits actions that try to publish AMIs. This doesn't cause a problem because they do not have the credentials to succeed at publishing. However, forks sometimes have secrets for testing and development purposes, so at some point the "try to publish" step is going to succeed accidentally.

#### To Reproduce

See [amis-workflow output](https://github.com/maxhbr/magma/runs/7709156206?check_suite_focus=true#step:11:36) in this fork.

#### Screenshots

<img width="943" alt="image" src="https://user-images.githubusercontent.com/111581/183486455-c735d691-cb8e-4538-b8e1-bbb8e4c1f19d.png">

#### Additional context

> fatal: [localhost]: FAILED! => {"boto3_version": "1.24.46", "botocore_version": "1.27.46", "changed": false, "error": {"code": "AuthFailure", "message": "AWS was not able to validate the provided access credentials"}, "msg": "error finding keypair: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: AWS was not able to validate the provided access credentials", "response_metadata": {"http_headers": {"cache-control": "no-cache, no-store", "content-type": "text/xml;charset=UTF-8", "date": "Sun, 07 Aug 2022 02:47:48 GMT", "server": "AmazonEC2", "strict-transport-security": "max-age=31536000; includeSubDomains", "transfer-encoding": "chunked", "vary": "accept-encoding", "x-amzn-requestid": "e23ad3bc-e496-48c8-ac58-8768af05ec19"}, "http_status_code": 401, "request_id": "e23ad3bc-e496-48c8-ac58-8768af05ec19", "retry_attempts": 0}}

**Comment by maxhbr** [comment]
@lucasgonze  and @ShubhamTatvamasi : is this done?

**Comment by ShubhamTatvamasi** [comment]
> @lucasgonze and @ShubhamTatvamasi : is this done?

Not yet, didn't get time to work on this. I think we should change the github action's trigger to `workflow_dispatch` so we can do it manually. This way, repo forks will not face this issue.

**Comment by lucasgonze** [comment]
Pushing AMIs is tied in with https://github.com/magma/magma/issues/13995

**Comment by lucasgonze** [comment]
To detect a fork, we can use [GITHUB_ACTION_REPOSITORY](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables). In a fork it would not be `magma/magma`.  

SO discussion of the necessary code: https://stackoverflow.com/questions/57903836/how-to-fail-a-job-in-github-actions

**Comment by nstng** [comment]
The workflow was removed in #14247 - I will close this for now. Please reopen if this issue is still needed.

**Comment by lucasgonze** [comment]
The many small reductions in scope are doing good things for security.
