### ISSUE TITLE
Pipelined Traceback are being observed when Single UE with PDU and traffic is triggered. 

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13548]
- Version: 1.8.0-1659984241-8f54687c
- Affected Component: Access Gateway
- Affected Subcomponent: Pipelined
- Deployment Environment: e.g. Bare-metal (AGW) - VM Based

While performing Single UE, Single PDU with traffic Test case on latest build observing pipelined Tracebacks for PDU session establishment of the session flows.

Traceback Observed:
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/3b4f9163-69e8-4568-b53d-b6edf77587ec)

Please find the attached logs:

[https://app.zenhub.com/files/170803235/aae66ee2-da59-4d35-8052-003435e70e73/download](https://app.zenhub.com/files/170803235/aae66ee2-da59-4d35-8052-003435e70e73/download)
[https://app.zenhub.com/files/170803235/8d038cbe-9ca3-4fef-84cd-048566738664/download](https://app.zenhub.com/files/170803235/8d038cbe-9ca3-4fef-84cd-048566738664/download)
[https://app.zenhub.com/files/170803235/28a7ca57-64ff-4a54-9c3c-260cce2a5dd8/download](https://app.zenhub.com/files/170803235/28a7ca57-64ff-4a54-9c3c-260cce2a5dd8/download)

**Comment by prabinakpattnaik** [comment]
Looks like RYU patch is missing for QFI. Please install agw again.

**Comment by NeelimaKalpana** [comment]
Please find the logs for qfi changes issue.

[https://app.zenhub.com/files/170803235/6d71ebe8-5434-4623-b6fc-8cb0c408e679/download](https://app.zenhub.com/files/170803235/6d71ebe8-5434-4623-b6fc-8cb0c408e679/download)

**Comment by panyogesh** [comment]
Using the latest python3-ryu changes the issue got resolved.  Closing the same based on 1.8 release.
