### ISSUE TITLE
Clean up dev VM and create another preburn image

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13566]
- Enable cleanup-ubuntu script in packer but make sure it doesn't remove too much. Check if this reduces the size of the box significantly. (Possible issues: Kernel headers, auto-completion?)
- After the clean-up work, publish a new preburn image.

Tasks:
- [ ] Adapt VMs and do the changes as described in the posts below
  - If more steps are moved to preburn, prepare both a new dev and a new test VM.
- [ ] Packer build
- [ ] AGW build
- [ ] Unit tests
- [ ] Sudo tests
- [ ] LTE integration tests
- [ ] Federated integration tests
- [ ] Prepare internal review meeting

**Comment by jheidbrink** [comment]
Simpler version of starting the traffic server: https://github.com/jheidbrink/magma/blob/8ae08254bd182db39118026844a2faaa67dae8c4/.github/workflows/lte-integ-test-with-bazel-built-binaries.yml#L161-L166

**Comment by sebathomas** [comment]
I think they have ansible 2.12 or 2.13 in the ppa depending on if you're on ubuntu 20.4 or 22.4?

**Comment by mpfirrmann** [comment]
During the packing process your local Ansible version doesn't matter. You need to install Ansible on the to-be-packed machine and apparently this version counts (even for the `full_provision` steps which are not executed).
Ubuntu 20.4's apt gives you 2.9.6 and the Ansible ppa gives you 5.10.0 (although I'm not really sure how the Ansible version numbering works, tbh)

**Comment by mpfirrmann** [comment]
Regerding pulling more steps into `preburn`: Since the Ansible roles are shared between `magma-dev` and `magma-test`, we would have to pack new images from both of them at once to get the most out of it.
