### ISSUE TITLE
Bazel Build & Test Job does not run when '.bazelrc' or 'WORKSPACE.bazel' files are modified

### ISSUE THREAD

**Issue by vktng** [magma/magma#13569]
The path_filter for the Bazel Build & Test Job is missing some crucial files:

1. `.bazelrc`
2. `envoy_controller` files

add them to the pathfilter

**Comment by LKreutzer** [comment]
1. I think the current `WORKSPACE.bazel` is actually covered since it has the right ending. It's just an issue if we ever get a `WORKSPACE` file as well.
2. The relevant folder for the `envoy_controller` in `feg` (+ others ?) should also be added to the path filter.
