### ISSUE TITLE
[Proposal] Make NMS e2e tests required

### ISSUE THREAD

**Issue by thmsschmitt** [magma/magma#13560]
### Problem

Without running e2e tests the NMS might end up in a broken state on master.

### Solution

Make the NMS e2e tests required.

**Comment by Neudrino** [comment]
Discussed and accepted in https://wiki.magmacore.org/display/HOME/August+15%2C+2022+Meeting.

**Comment by Neudrino** [comment]
The job was made required by @maxhbr on 2022-09-13.
