### ISSUE TITLE
gateway lost from orc8r when Network is deleted

### ISSUE THREAD

**Issue by reddydodda** [magma/magma#1357]
### Your Environment

- **Master:**
- **Affected Component:** NMS, Swagger
- **Deployment Environment:** Hosted K8S based orc8r and gateways

### Describe the Issue

Deleting a network should be a more secure way. currently, anyone can delete the network without even checking what all gateways running inside it. 

**To Reproduce**
1. Create a Network
2. Add gateways to the network
3.  try to delete the network ( both NMS and swagger )

**Expected behavior**
Network deletion should through error or popup warring to the user about active gateways running in it.

**Actual result**
Network deleted with gateway 

**Proposed **
1. when active gateways are inside Network, then show them to user before deleting
2. do not delete network when active gateways are there

**Comment by ekowtaylor** [comment]
Stale
