### ISSUE TITLE
Required Jobs for v1.* branches are outdated and not in sync with master

### ISSUE THREAD

**Issue by maxhbr** [magma/magma#13579]
There are currently the following jobs required:
![2022-08-11_10:50:38](https://user-images.githubusercontent.com/1187050/184098078-25ffa32c-a229-494e-b66b-7aff6d0d35aa.png)
This is out of sync and does not align with the current state of the project.

But changing this also potentially interferes with old PRs that do not yet have the necessary gh-actions files.

**Comment by Neudrino** [comment]
Should `master` and `v1.X` actually be covered by the same checks or are there differences needed?
In case it is the same, why not just extend the branch protection rules for master to the respective release branches?

**Comment by maxhbr** [comment]
I created a new rule that just applies to `v1.8` and overwrites `v1.*` for that. It is a plain copy of the current `master` rules
![2022-08-13_11:47:56](https://user-images.githubusercontent.com/1187050/184478573-1841badf-162f-4a7a-adc5-073518fc9e07.png)


This should mitigate the issue for now but is not a long term solution and for the next release we again have the same issue.
