### ISSUE TITLE
[AMF] : Multiple QoS Flow descriptors attached to Subscriberdb not working as expected

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13604]
- **Version:** 1.8.0-1660257461-1b734b83
- **Affected Component:** Access Gateway
- **Deployment Environment:** Bare-metal (AGW) - VM Based

While performing Test case with 1UE, 1PDU attaching 3 policies to UE, it is being observed that the QOS flow descriptions are not being updated in pcap as configured.

APN - AMBR Subscribed:
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/05d76aaa-b335-4a4d-9634-86ce71844fd9)

Profiles attached to 3 Policies:
 ![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/2e2cfc98-62df-4342-885a-b45955047849)

Subscribed IMSI:
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/d1edc724-54a6-42c4-b31f-5b3166e48efa)

PCAP Values:
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/7f11b9f8-0c81-4e29-9be7-ef51d6dea0cc)

Attaching the logs and pcap for the same:
[https://app.zenhub.com/files/170803235/f386cfea-d5ae-44df-a0cc-f8646d09700d/download](https://app.zenhub.com/files/170803235/f386cfea-d5ae-44df-a0cc-f8646d09700d/download)
[https://app.zenhub.com/files/170803235/31a4dad9-97e4-4e94-9cff-74888345880d/download](https://app.zenhub.com/files/170803235/31a4dad9-97e4-4e94-9cff-74888345880d/download)
[https://app.zenhub.com/files/170803235/b689d0a5-3338-483a-8bc6-d14220f6fa0e/download](https://app.zenhub.com/files/170803235/b689d0a5-3338-483a-8bc6-d14220f6fa0e/download)

**Comment by NeelimaKalpana** [comment]
Hi ,

Please find the attached logs with increased AMBR values.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/fd8a98cf-f456-48d9-8e42-869d0950e4f6)
[https://app.zenhub.com/files/170803235/a4c5c195-b2b4-4b01-8104-7d57ae4741b6/download](https://app.zenhub.com/files/170803235/a4c5c195-b2b4-4b01-8104-7d57ae4741b6/download)
