### ISSUE TITLE
Move or remove unused and confusing /src/ folder

### ISSUE THREAD

**Issue by maxhbr** [magma/magma#13614]
### Problem

We have the folder `/src/` that is the start for a refactoring of the source code structure, but it is not yet used or complete. All productive source code lives somewhere else. At the same time that folder contains READMEs with very broad statements that are not yet true, e.g. `"This is the home for all new Golang code for all magma deployment targets."`.

Despite not being used it has some negative impact, e.g.
* it needs to be touched, when e.g. go is upgraded or other conflicting changes happen
* it is confusing as it looks like an important entrypoint to source code.

### Solution

There are multiple possible solutions:
1. continue and finish this refactoring
1. move the folder to experimental, so that it at least is less confusing
1. drop that folder.

My personal preference would be to drop that folder.

### Non-goals

Everything else.

**Comment by nstng** [comment]
just some statistics ...
```
cloc ~/magma/src/
     120 text files.
     120 unique files.                                          
      39 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.25 s (318.9 files/s, 146872.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              73           4245           2499          30213
Markdown                         3             56              0            137
Protocol Buffers                 2             22             43             69
JSON                             3              1              0             26
-------------------------------------------------------------------------------
SUM:                            81           4324           2542          30445
-------------------------------------------------------------------------------
```

**Comment by maxhbr** [comment]
Hey @markjen and @mstre123,

I think you worked on this subfolder. What is your opinion? Would you keep it? Would you archive the code?

I think it was a good goal, but I see no progress and I am actually not sure which tickets correspond to that effort.
