### ISSUE TITLE
Python version issue observed while running checkin_cli.py script with containerized AGW

### ISSUE THREAD

**Issue by m-govind** [magma/magma#13645]
### 1.8 orc8r running in AWS cloud and containerized AGW running on Arm system

-  Version:1.8
- Affected Component: Orchestrator, Access Gateway
- Deployment Environment: AWS (orc8r), Containerized (AGW)

### 
After bringing up 1.8 orc8r in AWS and bringing up 1.8 containerized AGW image on Arm system, checkin_cli.py script fails with python version related error. Please check the attachment for error logs.

#### To Reproduce

1. Bring up 1.8 orc8r (or) use the existing 1.8 orc8r listed below:
https://arm.nms.galaxy.shubhamtatvamasi.com/
ID: admin
Pass: yfEr75fDXFzUzqVo7wh5
rootCA:
----------
-----BEGIN CERTIFICATE-----
MIIDYDCCAkigAwIBAgIUSlpb3Qq7r8C1LC+xVciOjseJGyQwDQYJKoZIhvcNAQEL
BQAwOjELMAkGA1UEBhMCVVMxKzApBgNVBAMMInJvb3RjYS5nYWxheHkuc2h1Ymhh
bXRhdHZhbWFzaS5jb20wHhcNMjIwODE1MTY0NjE3WhcNMzIwODEyMTY0NjE3WjA6
MQswCQYDVQQGEwJVUzErMCkGA1UEAwwicm9vdGNhLmdhbGF4eS5zaHViaGFtdGF0
dmFtYXNpLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMpOXgzc
Tx/UxmIRD0t4pwT4EoaRPIJf0iW1UIiSRDNRJSJWUIobpamBUaN6ZDc/VS3uQuPr
e7grMn3z7HjLfZadKLeeqIvkii9fNVYM1uQCoLZLLkMdIjFwDLp+mTQZgQr1WS85
jPIruPW0kqFOTb1HgeIsN7YhzydNvm25GMdvAkEi6UQkpqJjssfPhNoMdl1/21Uz
WZ9Z2kH/fi2Np+763JEyiPxC+PVMLtfFsqjNyh/3gd1Xt6T9vb0e/cy21tTj7evZ
xZ9N4uebMZelQoxE4LzR04UKcFLGqqlXwtOjiKFZ7OUDHziqS/c3lTa5lfV9UVrC
LhH+OxVgLr1RzBUCAwEAAaNeMFwwLQYDVR0RBCYwJIIicm9vdGNhLmdhbGF4eS5z
aHViaGFtdGF0dmFtYXNpLmNvbTAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBROq53S
jxPGmAWsZ48OlhIdimatwDANBgkqhkiG9w0BAQsFAAOCAQEACvAkSxs0BjgL25ge
D0Mgu8+N+46nKvkCuqqWbn2RDuvxcqEi4x/lX+pK46PzDMtT9/BqIWTbdkscRMUS
7PXdptcC2hPICKHuhX9YBDYWMlCz+NIsIO5uEJ/Qj6hlPtVJYYEnSkc0A/mK15Ow
3ncQZmeiboVhpEw8XWwR8cv97aYeAu+j7Ux6drUxHgITEO9nJeAJnIC/Rx1lYmpY
y2CI6LwVcgGOGdjGim+a2yUxXoHt24TxbJr+mXFNTo/bo7AYQCc+1hTnXPJLK1fy
+KPW/YMMTFyj1QwvWs5b89gW5OqOnbT5oo6u0gmhrZUkxeB2dw9XADHWbDtd45ko
ofXySg==
-----END CERTIFICATE-----
sudo mkdir -p /var/opt/magma/configs/
 sudo vim /var/opt/magma/configs/control_proxy.yml
cloud_address: [controller.galaxy.shubhamtatvamasi.com](http://controller.galaxy.shubhamtatvamasi.com/)
 cloud_port: 443
 bootstrap_address: [bootstrapper-controller.galaxy.shubhamtatvamasi.com](http://bootstrapper-controller.galaxy.shubhamtatvamasi.com/)
 bootstrap_port: 443
 fluentd_address: [fluentd.galaxy.shubhamtatvamasi.com](http://fluentd.galaxy.shubhamtatvamasi.com/)
 fluentd_port: 443
rootca_cert: /var/opt/magma/tmp/certs/rootCA.pem

2. Bring up 1.8 containerized AGW services in Arm system. You can try using x86 as well.

Follow the steps below to bring up containerized AGW services: https://github.com/magma/magma/blob/master/docs/readmes/lte/deploy_install_docker.md

Registry details for Arm AGW 1.8 image to be used in .env file:
DOCKER_REGISTRY=docker-test.artifactory.magmacore.org/
DOCKER_USERNAME=
DOCKER_PASSWORD=
IMAGE_VERSION=1.8.0

#### Expected behavior

root@ubuntu-server:/var/opt/magma/docker# docker exec magmad checkin_cli.py
1. -- Testing TCP connection to controller.mumbaimaster.failedwizard.dev:443 --
2. -- Testing Certificate --
4. -- Testing SSL --
5. -- Creating direct cloud checkin --
6. -- Creating proxy cloud checkin --

Success!

**Comment by m-govind** [comment]
![image (7)](https://user-images.githubusercontent.com/71405553/185217979-69e8419c-eb0e-4728-8016-f8272bcd0abe.png)

**Comment by nstng** [comment]
sentry-sdk got upgraded and has bumped its urllib3 dependency. but I still do not know why this causes dependency problems (because we are not pinning urllib3) :thinking_face:
https://github.com/getsentry/sentry-python/blob/b3bd629bc6163d371a45f64fcab37851746efdb7/setup.py#L42

**Comment by nstng** [comment]
not arm specific - can be reproduced on amd64
* `~/magma/lte/gateway$ vagrant up magma`
* `vagrant ssh magma`
* `~/magma/lte/gateway/docker$ docker-compose --file docker-compose.yaml --file docker-compose.override.yaml build`
* `~/magma/lte/gateway/docker$ docker-compose --file docker-compose.yaml --file docker-compose.override.yaml up magmad`
```
~$ docker exec magmad checkin_cli.py
Traceback (most recent call last):
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25.11 (/build/lib/python3.8/site-packages), Requirement.parse('urllib3>=1.26.11; python_version >= "3.6"'), {'sentry-sdk'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/bin/checkin_cli.py", line 4, in <module>
    __import__('pkg_resources').require('orc8r==0.0.0')
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/build/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3>=1.26.11; python_version >= "3.6"' distribution was not found and is required by sentry-sdk
```

**Comment by nstng** [comment]
@m-govind see #13652 for an approach to fix this.

If possible, you can ask the reporter of this bug to execute `docker exec magmad pip3 install sentry_sdk<1.9` and check if `docker exec magmad checkin_cli.py` then works as expected (I did this on my setup, but got follow-up runtime errors because my setup might not be sufficient).
