### ISSUE TITLE
docs: migrate Documentation Overview from Docusaurus to Contributor Guide

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#13662]
The Documentation Overview in Docusaurus (https://docs.magmacore.org/docs/docs/docs_overview) should move to the Contributor's Guide. Docusaurus is for users of Magma. The contributor's guide is for people working on Magma. The content of this page is for people working on Magma documentation. 

- [x] There is some content already in the Contributor's Guide. Content in docusaurus that is missing should be copied over from /magma/docs/readmes/docs/docs_overview.md 

- [x] The link to docs_overview in docusaurus should go away.  https://github.com/magma/magma/pull/14133

- [x] The new docs_overview page should be linked in the contributor's guide.

- [x] The old docs_overview.md file should be deleted from git. https://github.com/magma/magma/pull/14133

**Comment by lucasgonze** [comment]
@Neudrino

**Comment by voisey** [comment]
Thanks for the issue! I agree that this should be removed from the Docusaurus with any content that is not already [here](https://github.com/magma/magma/wiki/Contributing-Documentation) being migrated.

**Comment by lucasgonze** [comment]
I have reviewed the content of the two pages. All of the source page has been migrated over with the exception of this:

> [Docusaurus](https://docusaurus.io/)
> 
> Docusaurus is a framework for static site generation, focusing on documentation-based sites.
> 
> The [sidebars.json](https://v1.docusaurus.io/docs/en/navigation) and [siteConfig.js](https://v1.docusaurus.io/docs/en/site-config) are the main entrypoints for updating our documentation site. The former determines which README docs are displayed, and the latter sets site-wide config values.
> 
> There are two categories of documentation: "current" and "versioned". The current docs are stored under docs/readmes/. When cutting a specific release, we also capture a snapshot of the current docs and store them as versioned docs under docs/docusaurus/versioned_docs/. The sidebars are similarly versioned, with the versioned sidebars stored under docs/docusaurus/versioned_sidebars.

**Comment by voisey** [comment]
Sounds good to me. I can review your PR once it's open for review :slightly_smiling_face:
