### ISSUE TITLE
docs: migrate contributing pages in docusaurus to contributor guide

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#13661]
### Describe the Issue

The pages in Docusaurus under "Contribute > Contribute" (in the left nav) are duplicates of content in the Contributor's Guide. The options in that menu are:
```
          "contributing/contribute_onboarding",
          "contributing/contribute_workflow",
          "contributing/contribute_vscode",
          "contributing/contribute_conventions",
          "contributing/contribute_id_mappings",
          "contributing/contribute_ci_checks"
```

The simplest way to implement this is to have a page in docusaurus explaining what the contributor guide is and linking to it. The sidebar would go away except for this one page. The sub-pages above would only get linked in the github wiki. 

The pages in the sidebar would move to the wiki and be deleted from /magma/docs/readmes/contributing/

#### Screenshots

<img width="210" alt="image" src="https://user-images.githubusercontent.com/111581/185485999-be1ef3bb-1aa7-4982-8cd5-1941671301b6.png">

**Comment by lucasgonze** [comment]
Work will be in this branch: https://github.com/lucasgonze/magma/tree/docs-13661-migrate-contributing-pages

**Comment by lucasgonze** [comment]
When https://github.com/magma/magma/pull/14235 is merged, this can be closed.

**Comment by Neudrino** [comment]
> When #14235 is merged this ticket can be closed.

There is a Github functionallity for that, such that the comment is not necessary if correctly linked. See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.
