### ISSUE TITLE
Remove XWF radius from FeG

### ISSUE THREAD

**Issue by alexzurbonsen** [magma/magma#13671]
In https://github.com/magma/magma/pull/13545 the xwf gateway was removed and with https://github.com/magma/magma/issues/13546 most xwf functionality in the repo was removed. 

One last step remains, the removal of xwf radius in Feg and is tracked by this issue.

Note that this is related to #14184. Ideally, we could just remove the radius dependency.

**Comment by wolfseb** [comment]
This will be handled together with #14184 and can be closed.
