### ISSUE TITLE
Run integration tests against debian installation in CI

### ISSUE THREAD

**Issue by voisey** [magma/magma#13685]
Tasks:

- [x] Add a new GHA workflow that is triggered. It should be triggered on master after the build-all step is done. Plan: Copy the existing integ test job and modify it.
- [x] Investigate the stability issues. You can reproduce them by running the test suite on your machine and waiting until pipelined crashes. @nstng may know more details.
- [x] Optional: Look into how the debian packages are chosen. If we run after a merge to master, try to make sure it's using the results of the merge. In the current state, the process would always take the latest version of artifacts uploaded to the artifactory. Options:
  - Is there a way to get the version tag from the previous build-all run?
  - Another option: https://github.com/marketplace/actions/repository-dispatch
  - Add the commit hash to the uploaded version (this might cause other issues).
- [x] Add documentation to docusaurus.
- [x] Prepare internal review meeting.

Following on from #13263, we should create a version of the LTE integration test workflow that uses the debian installation as opposed to the make installation. Note that there are still some issues with the debian VM to be ironed out, see #13551.  Once working, the debian VM should be documented in the docusaurus with reference to running the integration tests.

* Add a new CI workflow to run the tests. It will not be required yet, and it will be an additional job, not replace the existing LTE integration tests. Run the workflow after build-all.
* Investigate stability issues and pipelined crashes. Try to improve stability.
* Optional: Look into how the debian packages are chosen. If we run after a merge to master, try to make sure it's using the results of the merge.

**Comment by ajahl** [comment]
Caching `magma-deb-box` exceeds the storage limit of the cache.
