### ISSUE TITLE
Fully test containerized AGW

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13684]
In #13659, a setup to run integration tests of the AGW container deployment was documented. Now this should be extended for more integration tests.

Acceptance criteria:
* [ ] Run all integration tests and try to get them green - document setup, results and possible issues
  * [x] precommit
    * [x] traffic server
  * [x] extended
  * [ ] nonsanity
* [x] Make s1ap_util.py docker aware
  * Look for systemd calls in s1ap_util.py and add a switch for the docker case.
* [x] Set init_system to docker in config for magmad running in the containerzed agw (does not seem to be aleady done (!))
  * Look into running the agw_install_docker.sh script - or set up another way to change the config. @jheidbrink might know more.
  * There is an `init_system` implemented in `magmad/service_manager.py` which sends the command to control docker container. The `docker start` commands are however executed within the magmad-container and throws a `FileNotFoundError: [Errno 2] No such file or directory: 'docker'`
* [x] Enabled magmad to control the hosts docker containers from within the vm (does not seem to be already done (!))
  * Check if this already works if you set the init_system correctly. The magmad container might need access to the docker socket so it can control docker containers outside it.
* [x] Figure out why the envoy controller is not dockerized
  * Probably because it's written in Go. Can it use the C++ container?
  * It might also be because of special dependencies of envoy proxy / controller on the OS side.
  * Relevant integration tests: 
    * s1aptests/test_attach_detach_with_he_policy.py
    * s1aptests/test_attach_detach_rar_tcp_he.py
  * Make sure the systemd envoy controller is not running when executing the tests. It should run as a container.
  *  :warning: From the `journalctl` output after the `docker-compose up`: `Error Loading feg::envoy_controller configs from '/etc/magma/feg/envoy_controller.yml': open /etc/magma/feg/envoy_controller.yml: no such file or directory` 

* [ ] Prepare internal review meeting.

**Comment by mpfirrmann** [comment]
Current state of the non-sanity tests (with no statistical significance): 18 out of 58 tests (incl. mandatory config changing tests) fail.
Of these 18 tests ...
- 12 fail with a "23 != 7" (UE_ATTACH_REJECT_IND != UE_AUTH_REQ_IND) assertion error
- 2 fail with a "7 != 52" (UE_AUTH_REQ_IND != UE_CTX_REL_IND) assertion error
- 4 fail with an unspecified assertion error

**Comment by mpfirrmann** [comment]
Closed the large ticket for follow-up tasks.
