### ISSUE TITLE
docker-compose build creates rootCA.pem directory instead of copying it as file

### ISSUE THREAD

**Issue by armin485** [magma/magma#13682]
### Your Environment

- Version: Magma version 1.7.0 and Ubuntu 20.04
- Affected Component: Access Gateway
- Affected Subcomponent: all AGW services cannot start
- Deployment Environment: docker container deployment of AGW

### Describe the Issue

After running agw_install_docker.sh on a fresh ubuntu and building successfully via docker-compose build command, docker cannot runn all the services within created docker images. After checking errors, it seems the reason is that it cannot find rootCA.pem file since it is copied by the builder script to create rooCA.pem directory instead of copying the file into certs directory.

#### To Reproduce

1. Run docker-compose build in directory: /opt/magma/lte/gateway/docker
2. Run docker-compose up in the same directory

#### Expected behavior

A bunch of errors like this happens:

ERROR: for pipelined  Cannot start service pipelined: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/magma/.cache/test_certs/rootCA.pem" to rootfs at "/var/opt/magma/certs/rootCA.pem": mount /opt/magma/.cache/test_certs/rootCA.pem:/var/opt/magma/certs/rootCA.pem (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by wolfseb** [comment]
The linked PR should fix this issue on master. If you want to keep using 1.7 there are two options: include the changes from that PR, or create the directory `/opt/magma/.cache/test_certs` and copy your `rootCA.pem` there.
