### ISSUE TITLE
[1.8] Release notes place holder

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#13683]

**Comment by maxhbr** [comment]
I think a limitation that might be missing is:

* Release testing and validation was (mostly) done on d00be5c4, instead of the commit that will be the release

**Comment by m-govind** [comment]
> I think a limitation that might be missing is:
> 
> * Release testing and validation was (mostly) done on [d00be5c](https://github.com/magma/magma/commit/d00be5c41db43f33c3c082d5b1b2bc7133043718), instead of the commit that will be the release

Please go ahead and add it.

**Comment by Hawkeyetech-Jess** [comment]
Tested 1.8 AGW docker image on HK-6050 (NXP Arm LS1043A based) on top of Ubuntu20.04/Linux5.4.3.
A workaround DKMS package from Jordan (jordan.vrtanoski@connectvg.com) is required to make the OVS working normally on 5.4.3 kernel.
Test case applied a srsRAN on simulated PC < -- > Containerized Magma AGW on HK6050
srsENB+srsUE attached is good and basic traffic validated with sanity check (iperf)

**Comment by jordanvrtanoski** [comment]
AGW Docker 1.8.0 tested on NexCom DTA1376 (based on NXP LS1046A 4-core Cortex-A72) with kernel 5.4.47 with LSDK image based on Ubuntu 20.04.
Ping test with srsRAN worked for 24h both on internal interfaces and to internet site. 
Load tests not performed, CPU utilisation stayed relatively low (below 30%), load average below 1

**Comment by jblakley** [comment]
Successfully brought up containerized 1.8.0 AGW on ARM64 Ampere server in Carnegie Mellon University Living Edge Lab. Successful means full deployment in a KVM VM on the server with successful checkin in to 1.8.0 Orc8r in remote AWS instance. Connection to eNodeB still to be done. Great support from @ShubhamTatvamasi  and @m-govind.

**Comment by ShubhamTatvamasi** [comment]
Limitations to be added as known issues.
No deployment code changes are made in orchestrator and Fed GW components as part of 1.8 Release.
As a result, official deployment will use 1.7 artifacts like helm charts and docker images of orc8r and Fed GW.
Note: Terraform version 1.0.11 must be used for orc8r deployment.
Following PRs will address the limitations specified above and will be addressed post 1.8 Release:
https://github.com/magma/magma/pull/13609 https://github.com/magma/magma/pull/13731

**Comment by m-govind** [comment]
> Limitations to be added as known issues. No deployment code changes are made in orchestrator and Fed GW components as part of 1.8 Release. As a result, official deployment will use 1.7 artifacts like helm charts and docker images of orc8r and Fed GW. Note: Terraform version 1.0.11 must be used for orc8r deployment. Following PRs will address the limitations specified above and will be addressed post 1.8 Release: #13609 #13731

@panyogesh Please share the Release testing details about which docker images and helm charts are used in your orc8r/Fed GW ?

**Comment by panyogesh** [comment]
> * SUCI Extensions: Support registration of UE/CPE with concealed identity (Subscription Concealed Identifier).

@m-govind : There were orc8r changes for 5G SA

**Comment by m-govind** [comment]
> > * SUCI Extensions: Support registration of UE/CPE with concealed identity (Subscription Concealed Identifier).
> 
> 
> 
> @m-govind : There were orc8r changes for 5G SA 
> 
> 

This feature have to go in 1.9 release if it is tested with your local orc8r docker images.

**Comment by m-govind** [comment]
> Tested 1.8 AGW docker image on HK-6050 (NXP Arm LS1043A based) on top of Ubuntu20.04/Linux5.4.3. A workaround DKMS package from Jordan ([jordan.vrtanoski@connectvg.com](mailto:jordan.vrtanoski@connectvg.com)) is required to make the OVS working normally on 5.4.3 kernel. Test case applied a srsRAN on simulated PC < -- > Containerized Magma AGW on HK6050 srsENB+srsUE attached is good and basic traffic validated with sanity check (iperf)

Referring the patch that supports 5.4.3 kernel - https://github.com/magma/magma/pull/13834/commits

**Comment by xiaoan-chen** [comment]
Tested 1.8.0 docker image on Sercomm BridgeColumn(NXP LS1046A, kernel 5.4.47-rt, LSDK 21.08, Ubuntu 20.04).
COTS UE (Google Pixel 5) attached on read radio (Sercomm Englewood, TDD LTE 20MHz, 2x2 DL-MIMO). Both iperf & speedtest results were good as expected (DL ~200Mbps, UL ~8Mbps). CPU loading is ~20% when idle and ~60% when full throughput test.
Thanks @m-govind @ShubhamTatvamasi for your support.

**Comment by NexcomScan** [comment]
> AGW Docker 1.8.0 tested on NexCom DTA1376 (based on NXP LS1046A 4-core Cortex-A72) with kernel 5.4.47 with LSDK image based on Ubuntu 20.04. Ping test with srsRAN worked for 24h both on internal interfaces and to internet site. Load tests not performed, CPU utilisation stayed relatively low (below 30%), load average below 1

Thanks @jordanvrtanoski @m-govind for the support to bring up the DTA1376 in line of Magma.

**Comment by nstng** [comment]
Current limitation/known bug: https://github.com/magma/magma/issues/13826 - mobility can not be cleanly restarted if there is no ipv6 interface defined. This should be triaged - I cannot judge the relevance of this issue.

**Comment by NeelimaKalpana** [comment]
Hi All,

We had done the testing of all 5G SA Features with the magma AGW and Orc8r versions as specified below.

Orc8r Version : v1.8
AGW Version : 1.8.0-1662727878-67ff69ff

Please find the attached logs for the reference.
[Magma  5G SA 1.8 Feature Release Logs.zip](https://github.com/magma/magma/files/9557456/Magma.5G.SA.1.8.Feature.Release.Logs.zip)

**Comment by NeelimaKalpana** [comment]
Hi All,

Please find the attached "Magma 5G SA 1.8 Validation Report".

[Magma_AGW_Release_V1.8-5G-SA _ Validation Report.pdf](https://github.com/magma/magma/files/9557476/Magma_AGW_Release_V1.8-5G-SA._.Validation.Report.pdf)

**Comment by panyogesh** [comment]
@NeelimaKalpana : Kindly upload the results in : [Results-Folder](https://drive.google.com/drive/folders/1JLbdi89Uy8XAIUxjk6XanB98Bb4sm-bN)  (as done for 1.7). You can make a folder for 5G and share the links in the links
@Sujay-Radtonics : Please upload the test logs in same folder : [Results-Folder](https://drive.google.com/drive/folders/1JLbdi89Uy8XAIUxjk6XanB98Bb4sm-bN). Please create a 4G folder and upload the results. 

We can use template of [1.7 report](https://github.com/magma/magma/releases/tag/v1.7.0) as a reference

**Comment by NeelimaKalpana** [comment]
Hi All,

We had done the testing of all 5G SA Features with the magma AGW and Orc8r versions as specified below.

Orc8r Version : v1.8
AGW Version : 1.8.0-1663094999-49ed2e69

Please find the attached logs for the reference.
[Magma  5G SA 1.8 Feature Release Logs.zip](https://github.com/magma/magma/files/9575462/Magma.5G.SA.1.8.Feature.Release.Logs.zip)

Please find the CI/CD logs from the artifacts: 
http://172.16.5.60/artifacts/14Sep2022-08:11:57.722893@magma-5G.zip

Thanks and Regards,
Neelima

**Comment by NeelimaKalpana** [comment]
Hi All,

Please find the attached "Magma 5G SA 1.8 Validation Report".

[Magma_AGW_Release_V1.8-5G-SA _ Validation Report.pdf](https://github.com/magma/magma/files/9575530/Magma_AGW_Release_V1.8-5G-SA._.Validation.Report.pdf)

**Comment by jordanvrtanoski** [comment]
NexCOM DT1376 with v1.8:
- Ping test passing on LTE
- Ping on 5G SA passed with workarounds. To pass the test a series of restarts of the containers with --force-recriate to update the configurations are required, followed by a reboot of the device. In addition, due to the defect #12846 the gNB should not populate the timeStamp field.

**Comment by m-govind** [comment]
> NexCOM DT1376 with v1.8:
> 
> * Ping test passing on LTE
> * Ping on 5G SA passed with workarounds. To pass the test a series of restarts of the containers with --force-recriate to update the configurations are required, followed by a reboot of the device. In addition, due to the defect [5G can't handle userLocationInformationNR timestamp field #12846](https://github.com/magma/magma/issues/12846) the gNB should not populate the timeStamp field.
> 
> 5G-SA Live Radio Test: Connect 5G performed live radio test of 5G-SA with a T1 radio and BEC 8230 CPE using r1.8 with additional fixes due to the known issue [#12846](https://github.com/magma/magma/issues/12846). After a workaround for the defect was applied, the CPE had attached successfully. Traffic flow was verified with ping to the gtp_br0 (192.168.128.1) and to Cloudfire (1.1.1.1).

Thanks for the 5G updates Jordan !!

**Comment by jordanvrtanoski** [comment]
MacMini Apple M1 with Parallels based VM:
- LTE test passed, UE attached successfully. Ping to internal gtp_br0 (192.168.128.1) and to Cloudfire (1.1.1.1) passed successfully
- 5G test passed with workaround (see NexCom DT1367). Ping to internal gtp_br0 (192.168.128.1) and Cloudfire (1.1.1.1) passed successfully

**Comment by m-govind** [comment]
> MacMini Apple M1 with Parallels based VM:
> 
> * LTE test passed, UE attached successfully. Ping to internal gtp_br0 (192.168.128.1) and to Cloudfire (1.1.1.1) passed successfully
> * 5G test passed with workaround (see NexCom DT1367). Ping to internal gtp_br0 (192.168.128.1) and Cloudfire (1.1.1.1) passed successfully

Thanks Jordan !!

**Comment by Hawkeyetech-Jess** [comment]
Installed AGW 1.8 on HK-6010 based on Linux kernel 5.4.47
Traffic test: AGW with Sercomm small cell (LTE CBRS, SCE4255W), all ping/iperf/speedtest passed.

**Comment by NexcomScan** [comment]
> NexCOM DT1376 with v1.8:
> 
> * Ping test passing on LTE
> * Ping on 5G SA passed with workarounds. To pass the test a series of restarts of the containers with --force-recriate to update the configurations are required, followed by a reboot of the device. In addition, due to the defect [5G can't handle userLocationInformationNR timestamp field #12846](https://github.com/magma/magma/issues/12846) the gNB should not populate the timeStamp field.
> 
> 5G-SA Live Radio Test: Connect 5G performed live radio test of 5G-SA with a T1 radio and BEC 8230 CPE using r1.8 on NexCOM DT1376. The 1.8 required additional fixes due to the known issue [#12846](https://github.com/magma/magma/issues/12846). After a workaround for the defect was applied, the CPE had attached successfully. Traffic flow was verified with ping to the gtp_br0 (192.168.128.1) and to Cloudfire (1.1.1.1). A laptop was connected to the CPE and used to verify a generic browsing traffic.

Thanks 

> > MacMini Apple M1 with Parallels based VM:
> > 
> > * LTE test passed, UE attached successfully. Ping to internal gtp_br0 (192.168.128.1) and to Cloudfire (1.1.1.1) passed successfully
> > * 5G test passed with workaround (see NexCom DT1367). Ping to internal gtp_br0 (192.168.128.1) and Cloudfire (1.1.1.1) passed successfully
> 
> Thanks Jordan !!

Thanks Jordan and Govin for the support

**Comment by nstng** [comment]
I assume this issue is not needed anymore, since the release already happened - if this issue is still used for something else, then please re-open.
