### ISSUE TITLE
CI support for dockerized agw attach dettach test

### ISSUE THREAD

**Issue by crasu** [magma/magma#13695]
### Background:

In [#13475](https://github.com/magma/magma/issues/13475) we analyzed what needs to be done to get the s1ap running with the dockerized agw. This story already enabled one s1ap test (attach/dettach). #13684 will enable more tests as well as improve the setup. This ticket will only enable the attach/dettach test

### Acceptance criteria:

- Add a ci job for running the s1ap attach/dettach against the dockerized agw

### Reference

- Follow up ticket [#14123](https://github.com/magma/magma/issues/14123)

**Comment by mpfirrmann** [comment]
I rebased and squashed the draft PR #13928 on my fork to be up to date.
https://github.com/mpfirrmann/magma/tree/dockerized_AGW_ci
