### ISSUE TITLE
Publish xml test results in LTE integ test bazel workflow

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13717]
Publish xml test results in LTE integ test bazel workflow
- Publish via action
  - publish sudo and integ tests results seperately
    - also publish the raw test xml files
  - use an appropriate action to do this - check if a newer version can be used if an establish action is used

Follow up to https://github.com/magma/magma/pull/13641

**Comment by vktng** [comment]
We are using [this](https://github.com/EnricoMi/publish-unit-test-result-action/tree/v2.0.0) action with version [v1.37](https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v1.37) to publish XML results. There is already a new release: [v2.0.0](https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v2.0.0). I have tried it out, but there is a bug, when if there are multiple workflows for the same commit, then the results will be printed to a random one. [Bug here](https://github.com/EnricoMi/publish-unit-test-result-action/issues/12). Workflow results can be seen [here](https://github.com/magma/magma/pull/13984#issuecomment-1255394973).
