### ISSUE TITLE
Metric collector error: failed to get metrics from service ha and subscriberdb_cache

### ISSUE THREAD

**Issue by vinny87ster** [magma/magma#13739]
### Your Environment

- **Version:** 1.8.0 (https://artifactory.magmacore.org/artifactory/orc8r-test/configuration-controller/1.8/)
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Metricsd
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

ha and subscriberdb_cache service doesn't have grpc-internal port defined in its k8 service file, as we see in the laster master code: 
https://github.com/magma/magma/blob/master/lte/cloud/helm/lte-orc8r/templates/ha.service.yaml,
Whereas metricsd pod tries to gather the metrics from all the pods using grpc-internal port, due to which we are getting could not find 'grpc-internal' port for 'ha' and 'subscriberdb_cache' service.

> E0816 14:21:09.671280       1 client_api.go:30] SERVICE303 service client initialization error: rpc error: code = Unknown desc = could not find 'grpc-internal' port for service 'subscriberdb_cache'
> E0816 14:24:09.678229       1 client_api.go:30] SERVICE303 service client initialization error: rpc error: code = Unknown desc = could not find 'grpc-internal' port for service 'ha'

Please note that as part of MR: https://github.com/magma/magma/pull/12941 , grpc-internal ports were added for analytics, bootstrapper, dispatcher, obsidian, orc8r_worker, and streamer services but grpc-internal ports are not added for ha and subscriberdb_cache service.

#### To Reproduce

1. Bring up the Orchestrator using helm chart.
2. Open the metricsd pod logs.
3. Search for _could not find 'grpc-internal'_  log.

#### Expected behavior

We should not see the error in metricsd pod stating _could not find 'grpc-internal'_
metricsd pod should be able to gather the metrics from ha and subscriberdb_cache pod.

**Comment by jingc1413** [comment]
i have the save problem
