### ISSUE TITLE
Observing no traffic flow when APN QFI is set to 7

### ISSUE THREAD

**Issue by apekshapk** [magma/magma#13732]
- **Version:** 1.8.0-1661371952-2b61b4bf 
- **Affected Component:** Access Gateway
- **Deployment Environment:**  Bare-metal (AGW) - VM based

While performing 1UE, 1PDU, UDP traffic with configuration of APN QFI as 7 it is being observed no traffic flow. It is being noticed that QOS Flow Identifier to 9 as hardcoded value.  

Configured QFI: 
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/3ab5e73e-347f-4782-b43c-c7c1e5958e57) 

Please find the snapshot for the observations in the syslogs:
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/8e2012cd-5783-403f-925b-6245dca2ddd9)

Please find the attached logs for the scenario tested:
[https://app.zenhub.com/files/170803235/76032b59-cac1-481e-8297-f35afa2fa7eb/download](https://app.zenhub.com/files/170803235/76032b59-cac1-481e-8297-f35afa2fa7eb/download)

**Comment by NeelimaKalpana** [comment]
Closing this ticket as the issue got fixed on latest master .
Please find the validation logs from below.

[https://app.zenhub.com/files/170803235/c626d439-72ab-464d-93f7-f6350867f4a8/download](https://app.zenhub.com/files/170803235/c626d439-72ab-464d-93f7-f6350867f4a8/download)
