### ISSUE TITLE
Clean up docusaurus footer

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13746]
### Describe the Issue

- The docusaurus has a footer which is largely outdated with links to events in 2019, old communication platforms (Discord), amongst others.
- Any navigation links are more accurately given in the top-bar.

![image](https://user-images.githubusercontent.com/13189449/186853510-362839c8-c267-48bb-b0aa-4d9a2fc527a3.png)

#### Suggested Resolution

- Remove anything from the bottom "navigation" but the license information.
  - Any meaningful navigation is in the topbar anyway.

**Comment by Demostenes777** [comment]
Hi, I have started working on this issue. What do I need to do to have this issue assigned? Thanks

**Comment by voisey** [comment]
> Hi, I have started working on this issue. What do I need to do to have this issue assigned? Thanks

In general, you can just assign yourself on the top right of this page :slightly_smiling_face:

**Comment by voisey** [comment]
Closed via https://github.com/magma/magma/pull/14515
