### ISSUE TITLE
[magma-installation]Seeing some openswitch installation issue while installing latest magma from 1.8 brach. 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#13762]
Initial Version details:  1.7.0-1648117787-73e61141

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/62691620-8270-4c95-9db5-9f573c9ff34e)

Then I tried to install latest version using below commands

List of magma packages available:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/f244d25b-a0d0-467b-b0e7-a26876c75eb3)

sudo apt update 
sudo apt-get install magma

Error observed:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/572acb48-0750-420b-a973-f2d9060a2004)

I am observing this issue while upgrading to 1.8 from 1.7 version.

Please help to resolve the issue.
 

Note: Issue is not observed in the AGWs which are already with 1.8 version.

**Comment by maxhbr** [comment]
looks like that `openvswitch-datapath-dkms_2.15.4-9-magma_all.deb` was overwritten by @m-govind with a package that in properties is listed as just supporting `arm64`:
![2022-08-29_09:52:05](https://user-images.githubusercontent.com/1187050/187152051-d23bfdd5-7f65-47cf-82df-35640b14fd97.png)

**Comment by maxhbr** [comment]
mentioned in the releasing channel: https://magmacore.slack.com/archives/C0301NRRL7K/p1661759840478899

**Comment by NeelimaKalpana** [comment]
Hi Max,

We are able to find the work around by pointing to the all available source list .

@maxhbr  , Kindly let us know when we will have fix for this issue.

**Comment by m-govind** [comment]
Hi, Following files are overwritten in JFrog "https://artifactory.magmacore.org/artifactory/debian-test/pool/focal-1.8.0/"
openvswitch-datapath-dkms_2.15.4-9-magma_all.deb
openvswitch-datapath-source_2.15.4-9-magma_all.deb
openvswitch-pki_2.15.4-9-magma_all.deb
openvswitch-test_2.15.4-9-magma_all.deb
python3-openvswitch_2.15.4-9-magma_all.deb

**Comment by m-govind** [comment]
Created a GH issue:
 https://github.com/magma/magma/issues/13771
