### ISSUE TITLE
OVS deb packages common for both Arm and x86 have to be tagged properly and uploaded in JFrog

### ISSUE THREAD

**Issue by m-govind** [magma/magma#13771]
Source/Duplicate: Zenhub: https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/13762

### Ubuntu 20.04

- Version:1.8
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment:  local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### 
 Following files are overwritten in JFrog yesterday after building on arm architecture and it broke the x86 tests. "https://artifactory.magmacore.org/artifactory/debian-test/pool/focal-1.8.0/".

openvswitch-datapath-dkms_2.15.4-9-magma_all.deb
openvswitch-datapath-source_2.15.4-9-magma_all.deb
openvswitch-pki_2.15.4-9-magma_all.deb
openvswitch-test_2.15.4-9-magma_all.deb
python3-openvswitch_2.15.4-9-magma_all.deb

#### Expected behavior
The common packages to arm and x86 have to be tagged and uploaded in JFrog to avoid the conflict.

**Comment by m-govind** [comment]
[jfrog_pkgs_common_x86_arm.zip](https://github.com/magma/magma/files/9444412/jfrog_pkgs_common_x86_arm.zip)

**Comment by m-govind** [comment]
I have attached the OVS all*.deb packages that were generated on arm64 architecture.

**Comment by nstng** [comment]
All packages here seem to be legitimate all packages (also `openvswitch-datapath-dkms` only has files in `/usr/src`). All packages had the property `deb.architecture` set to `arm64`. This was changed to `all`. With this `openvswitch-datapath-dkms` was installable in an amd64 system. For arm there were still problems that were tackled out of scope of this issue - see https://magmacore.slack.com/archives/C0301NRRL7K/p1661761174987709.

**Comment by nstng** [comment]
This was handled in #13790
