### ISSUE TITLE
[Magma-Installation] Observing python dependency issues while installing latest master . 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#13787]
Trying to upgrade magma to latest master and observing python dependency issues as specified below.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/d1e8216d-a757-4cd8-914f-bec81fb7b671)

Tried manually to install the required dependencies but still facing same error.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/5db69647-c2fb-4f1a-ab03-d84f171b8c70)

Looks like the required version of dependency has to be ported into magma artifacts.

This issue is observed so far in master. Need to check in 1.8 as well.

Please help to resolve the issue.

**Comment by panyogesh** [comment]
Some package updates are happening. Wait for a day, if issue not resolved please re-assign to to the DevOPs team

**Comment by sebathomas** [comment]
This might be related to the merge of #13482, we'll investigate.

**Comment by sebathomas** [comment]
All right, this was definitely broken by the PR. Some of the Python packages that are built and uploaded to artifactory do not fit the versions of dependencies written into the magma debian package. We're working on a fix.

The reason this happened is that the Python dependency upgrades require a lot of manual tests in order to check the production build, and not all tests were rerun after small changes in the PR and a rebase. We will have to be more careful in the future.

**Comment by sebathomas** [comment]
@NeelimaKalpana After merging #13799, the build on master is fixed and a new magma deb package was created:
https://artifactory.magmacore.org/ui/repos/tree/General/debian-test%2Fpool%2Ffocal-ci%2Fmagma_1.8.0-1662048011-e98445f9_amd64.deb

Can you test if the dependency issue still occurs with the new package?

**Comment by NeelimaKalpana** [comment]
@sebathomas 

I tried installing latest master version as specified above but now I am observing new dependencies .
The following packages have unmet dependencies:
 magma : Depends: python3-spyne (>= 2.13.16) but 2.13.15 is to be installed
         Depends: python3-spyne (>= 2.13.16) but 2.13.15 is to be installed
E: Unable to correct problems, you have held broken packages.

 ![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/43394843-6c11-487a-b07d-ab93f122dc9b)

**Comment by sebathomas** [comment]
Thanks for the quick response. Right, it's in the dependencies but not on artifactory. Will need to find out why pydep refuses to build that. Or maybe just pin it to 2.13.15 to make master green again...

**Comment by sebathomas** [comment]
The problem might be just the lockfile. Testing that in #13809.

**Comment by sebathomas** [comment]
@NeelimaKalpana Could you try again? I was able to install the latest build 1.8.0-1662112418-e2e032c0 with the fixed spyne version in the lockfile.

**Comment by sebathomas** [comment]
Closing this since the build and subsequent test jobs have been green again for a while and no further issues were reported.
