### ISSUE TITLE
Analysis: Is there an nice way of setting up C, C++, Python and Go formatters via Bazel?

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13785]
Is there an nice way of setting up C, C++, Python and Go formatters via Bazel?

Related to: https://github.com/magma/magma/issues/13591

* list all linters/formatters that are currently used with make
  * also mark if a make configured linter/formatter is not used in CI
* research what formatting/liniting tooling exists for bazel
* make suggestion what bazel tools can be used to replace the make tools
* discuss results with team and create follow up issues for the migration

Timeboxed: 2

**Comment by vktng** [comment]
Formatters:

- `make format_all`: also in CI, but without make, clang-format-11 in
  - `orc8r/gateway/c/`
  - `lte/gateway/c/`
  - `lte/gateway/python/`
- `lte/gateway/python/precommit.py`
  - `--lint -p PATH1 PATH2` run the flake8 linter by specifying paths
  - `--lint --diff` run the flake8 linter on all modified files in HEAD vs master (local only)
  - `--format -p PATH1 PATH2` run all available formatters by specifying paths (isort, autopep8, add-trailing-comma)
  - `--format --diff` run all available formatters on all modified files in HEAD vs master (local only)
- `mypy` with `tsuyoshicho/action-mypy@...` in reviewdog
- `make fmt` -> `go fmt` formatter, part of:
  - `make all`
  - `make`
  - `make precommit`
- `make -C ${{ env.MAGMA_ROOT }}/lte/gateway/python test_all` includes:
  - pylint
  - pycodestyle
- `make` in `lte/gateway/python/integ_tests/` includes:
  - pylint
  - pycodestyle

**Comment by vktng** [comment]
Solutions:

1. Create aliases for formatting (my suggestion)
2. Create wrapper rule
   - need to change all `cc_*ary` targets to wrapper
   - creates formatted files in `bazel-bin`
   - hacky way to modify source files*
   - not really Bazel like
   - can format without building the source files
3. Use Bazel aspects
   - can be attached to `cc_*ary` targets
   - creates formatted files in `bazel-bin`
   - hacky way to modify source files*
   - not really Bazel like
   - cannot format without building the source files

\* https://dev.to/bazel/bazel-can-write-to-the-source-folder-b9b
