### ISSUE TITLE
[arm] After migrating from focal-ci to focal-1.8.0 in magma artifactory, OVS installation fails

### ISSUE THREAD

**Issue by m-govind** [magma/magma#13790]
### Arm/aarch64

- Version:1.8
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment:  AWS arm instance - graviton2 (AGW) with 5.4.0-1017-aws kernel with 2 eth ports

### Describe the Issue
After running agw_install_docker.sh, OVS installation is not successful. Older version (2.13.*) of openvswitch-common is installed from ubuntu port and not from magma artifactory which has 2.15.4-9 version. apt installation is not happening from magma artifactory rather it is happening from ubuntu apt location.

Few observations that might have caused this issue:
---------------------------------------------------------
Comparing focal-ci and focal-1.8.0 deb packages for arm64, there are differences in properties. focal-ci has 9 properties whereas focal-1.8.0 has only 3/4 properties for some of the arm64 packages.

artifactory location to compare:

https://artifactory.magmacore.org/artifactory/debian-test/pool/focal-1.8.0/
https://artifactory.magmacore.org/artifactory/debian-test/pool/focal-ci/

Also,
Comparing focal-ci and focal-1.8.0 Packages file, there are differences and many deb packages are missing in focal-1.8.0:
https://artifactory.magmacore.org/artifactory/debian-test/dists/focal-ci/main/binary-arm64/Packages
https://artifactory.magmacore.org/artifactory/debian-test/dists/focal-1.8.0/main/binary-arm64/Packages

Note: OVS deb packages for arm64 are built on AWS graviton2 / 5.4.0-1017-aws kernel and uploaded in magma artifactory. Rest of the arm64 deb packages are moved from focal-ci to focal-1.8.0.

Logs:
------
apt list -a openvswitch-datapath-dkms
Listing... Done
openvswitch-datapath-dkms/focal-1.8.0,now 2.15.4-9-magma all

Except dkms all the OVS packages are pulled from ubuntu apt location and not from JFrog:

root@ip-172-31-19-78:/etc/apt/preferences.d# apt list -a openvswitch-common
Listing... Done
openvswitch-common/focal-updates,now 2.13.8-0ubuntu1 arm64 [installed]
openvswitch-common/focal-security 2.13.3-0ubuntu0.20.04.2 arm64
openvswitch-common/focal 2.13.0-0ubuntu1 arm64

root@ip-172-31-19-78:/etc/apt/preferences.d# apt list -a openvswitch-dbg
Listing... Done
openvswitch-dbg/focal-updates 2.13.8-0ubuntu1 arm64
openvswitch-dbg/focal-security 2.13.3-0ubuntu0.20.04.2 arm64
openvswitch-dbg/focal 2.13.0-0ubuntu1 arm64

root@ip-172-31-19-78:/etc/apt/preferences.d# apt list -a openvswitch-ipsec
Listing... Done
root@ip-172-31-19-78:/etc/apt/preferences.d# apt list -a openvswitch-switch
Listing... Done
openvswitch-switch/focal-updates,now 2.13.8-0ubuntu1 arm64 [installed]
openvswitch-switch/focal-security 2.13.3-0ubuntu0.20.04.2 arm64
openvswitch-switch/focal 2.13.0-0ubuntu1 arm64

root@ip-172-31-19-78:/etc/apt/preferences.d# apt list -a openvswitch-testcontroller
Listing... Done
openvswitch-testcontroller/focal-updates 2.13.8-0ubuntu1 arm64
openvswitch-testcontroller/focal-security 2.13.3-0ubuntu0.20.04.2 arm64
openvswitch-testcontroller/focal 2.13.0-0ubuntu1 arm64

root@ip-172-31-19-78:/etc/apt/preferences.d# apt list -a openvswitch-vtep
Listing... Done
openvswitch-vtep/focal-updates 2.13.8-0ubuntu1 arm64
openvswitch-vtep/focal-security 2.13.3-0ubuntu0.20.04.2 arm64
openvswitch-vtep/focal 2.13.0-0ubuntu1 arm64 (edited) 

#### To Reproduce

1. Follow the steps in https://github.com/magma/magma/blob/v1.8/docs/readmes/lte/deploy_install_docker.md
2. Stop after running bash agw_install_docker.sh
    Note: Apply the following change before ansible-playbook line and then run agw_install_docker.sh -
             sed -i 's/debian/debian-test/' /opt/magma/lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
sed -i 's/focal-1.7.0/focal-1.8.0/' /opt/magma/lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
sed -i 's/debian/debian-test/' /opt/magma/lte/gateway/deploy/roles/agw_docker/vars/all.yaml
sed -i 's/focal-1.7.0/focal-1.8.0/' /opt/magma/lte/gateway/deploy/roles/agw_docker/vars/all.yaml
3. Check the OVS version using foll. command and observe older version getting installed:
apt list -a openvswitch-common
Listing... Done
openvswitch-common/focal-updates,now 2.13.8-0ubuntu1 arm64 [installed]
openvswitch-common/focal-security 2.13.3-0ubuntu0.20.04.2 arm64
openvswitch-common/focal 2.13.0-0ubuntu1 arm64

#### Expected behavior

OVS deb packages must be installed from magma artifactory with version 2.15.4-9.

#### Additional context
Following issue could be related to improper OVS installation:
"modprobe vport-gtp" did not succeed. "lsmod | grep gtp" did not list vport-gtp modules after executing agw_install_docker.sh and rebooting the AWS instance.

**Comment by panyogesh** [comment]
[x86-ovs-install-logs-13790.txt](https://github.com/magma/magma/files/9460329/x86-ovs-install-logs-13790.txt)
For me its working fine

**Comment by panyogesh** [comment]
[upgade-docker-1.8.txt](https://github.com/magma/magma/files/9461149/upgade-docker-1.8.txt)

**Comment by maxhbr** [comment]
> [upgade-docker-1.8.txt](https://github.com/magma/magma/files/9461149/upgade-docker-1.8.txt)

can you share the definition of `destromagma` so that we can follow what is happening? It is installing 1.7.0 dependencies on the host, like ovs in version `2.15.4-8`. And I do not find the string `2.15.4-9-magma` in the log

**Comment by panyogesh** [comment]
[x86-ovs-install-logs-13790-v0.2.txt](https://github.com/magma/magma/files/9461911/x86-ovs-install-logs-13790-v0.2.txt)

You pointed correctly. It was infact picking up 2.15.4.-8. Modified the script : agw_install_docker.sh and added the below lines

_sed -i 's/debian/debian-test/' /opt/magma/lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
sed -i 's/focal-1.7.0/focal-1.8.0/' /opt/magma/lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
sed -i 's/debian/debian-test/' /opt/magma/lte/gateway/deploy/roles/agw_docker/vars/all.yaml
sed -i 's/focal-1.7.0/focal-1.8.0/' /opt/magma/lte/gateway/deploy/roles/agw_docker/vars/all.yaml_

**Comment by panyogesh** [comment]
[Vagrantfile.txt](https://github.com/magma/magma/files/9461928/Vagrantfile.txt)

**Comment by nstng** [comment]
### Used Environment for Issue
* manually created `t4g.large` instance with `ami-01c42f4eea2e93fa3` (and 20gb space).
* `git clone https://github.com/magma/magma.git`
* `sudo TEST_MODE=1 ~/magma/orc8r/cloud/docker/nginx/create_test_proxy_certs`
* `vim magma/lte/gateway/deploy/agw_install_docker.sh`
  * add [1] after git clone
* `sudo ./magma/lte/gateway/deploy/agw_install_docker.sh`
* restart (as ordered by install script)

### Analysis
After setup above, we see
```
apt list *openvswitch* | grep installed
libopenvswitch/focal-1.8.0,now 2.15.4-9-magma arm64 [installed]
openvswitch-common/focal-updates,now 2.13.8-0ubuntu1 arm64 [installed]
openvswitch-datapath-dkms/focal-1.8.0,now 2.15.4-9-magma all [installed]
openvswitch-datapath-source/focal-1.8.0,now 2.15.4-9-magma all [installed]
openvswitch-switch/focal-updates,now 2.13.8-0ubuntu1 arm64 [installed]
python3-openvswitch/focal-updates,now 2.13.8-0ubuntu1 all [installed,automatic]
```
This is, `openvswitch-common`, `openvswitch-switch` and `python3-openvswitch` are installed from the official ubuntu repos.
In the artifactory we see these packages with insufficient meta data.

Also `lsmod | grep gtp` is empty, i.e., openvswitch seems to be damaged.

### Proposed Solution
* delete affected packages from artifactory and re-upload them
* OKed in https://magmacore.slack.com/archives/C0301NRRL7K/p1661944804942379

### Audit Log for Changes to the Artifactory
* deleted packages manually after downloading them
* adding packages manually to `debian-test` with <package>:<distro>:<component>:<arch>
  * `openvswitch-common`:`focal-1.8.0`;`main`:`arm64`
  * `openvswitch-switch`:`focal-1.8.0`;`main`:`arm64`
  * `python3-openvswitch`:`focal-1.8.0`;`main`:`all`

### Verification
* after setup above we see
```
apt list *openvswitch* | grep installed
ubuntu@ip-172-31-12-234:~$ apt list *openvswitch* | grep install
libopenvswitch/focal-1.8.0,now 2.15.4-9-magma arm64 [installed]
openvswitch-common/focal-1.8.0,now 2.15.4-9-magma arm64 [installed]
openvswitch-datapath-dkms/focal-1.8.0,now 2.15.4-9-magma all [installed]
openvswitch-datapath-source/focal-1.8.0,now 2.15.4-9-magma all [installed]
openvswitch-switch/focal-1.8.0,now 2.15.4-9-magma arm64 [installed]
```
Note that `python3-openvswitch` is **not** installed. This seems to be a dependency of `openvswitch-switch` in the official ubuntu repos (see https://packages.ubuntu.com/focal/openvswitch-switch) but not of the magma version.
Also we see
```
lsmod | grep gtp
vport_gtp              16384  1
openvswitch           225280  9 vport_gtp
```


[1]
```
sed -i 's/debian/debian-test/' /opt/magma/lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
sed -i 's/focal-1.7.0/focal-1.8.0/' /opt/magma/lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
```

**Comment by m-govind** [comment]
This issue is resolved. I can successfully install OVS packages from focal-1.8.0 on fresh AWS arm instance (graviton2). srsRAN based traffic test passed.

**Comment by m-govind** [comment]
Reopening for @panyogesh to update his results on x86.
