### ISSUE TITLE
Regarding CI/CD testcase failure on latest 1.8 build : 1.8.0-1662060734-83622a9e

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#13812]
Hi ,

Failure test case : Invalid_DNN_ipv4_ipv6_dual_rejection
Failure Cause : The testcase failed due to rmq response issue in the test frame work. We are working to resolve it.

Latest logs on individual trigger of test case.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9de77940-3edc-4bf9-b3b6-4b928c96f3b5)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/da606ce6-7be4-4b0c-9b4d-07324d274909)
Please find the attached logs for reference.
[https://app.zenhub.com/files/170803235/11694026-98b6-47a0-83ea-e6db061f52a4/download](https://app.zenhub.com/files/170803235/11694026-98b6-47a0-83ea-e6db061f52a4/download)

**Comment by panyogesh** [comment]
After release closing release specific defects.
