### ISSUE TITLE
a switch over strategy is created

### ISSUE THREAD

**Issue by nstng** [magma/magma#13822]
create a detailed switch over strategy for bazel, e.g.,
* feature branch with rebase and merge strategy
* document all changes that need to be done here, i.e., breaking changes
  * sources are already documented needed changes in other issues
* goal: have a step by step plan for the actual switch over

**Comment by LKreutzer** [comment]
I suppose we can close this issue now?

**Comment by nstng** [comment]
is done in the regular planning process
