### ISSUE TITLE
magma documentation is parsed for make targets

### ISSUE THREAD

**Issue by nstng** [magma/magma#13821]
find all places in the current magma documentation (docusaurus, GHwiki, general .md files, code documentation) where make targets are used in the AGW ...
* sketch in task what needs to be done with bazel
* discuss with team foll-up issues if we have a gap
* create follow-up task with needed GHwiki changes
* create **draft** PR with docusaurus, .md and code documentation changes
  * create follow-up issue where the draft is linked for the actual switch over

**Comment by vktng** [comment]
Findings so far:

1) Search comments: #.*make (?!sure)

/workspaces/magma/.github/workflows/codeql-analysis.yml
	      #   make yml
	      #   make release

/workspaces/magma/bazel/scripts/check_c_cpp_bazel.sh
	  # TODO: GH12755 access via absolut path on the VM,
	  # this needs to be refactored when make is not used anymore

/workspaces/magma/bazel/scripts/check_py_bazel.sh
	  #  as of 2022.09.19 commented out in make

/workspaces/magma/docs/readmes/lte/dev_unit_testing.md
	[VM] make test_<service_directory_name> # Ex: make test_session_manager

/workspaces/magma/docs/readmes/lte/s1ap_tests.md
	a lot

/workspaces/magma/lte/gateway/docker/README.md
	cd $MAGMA_ROOT/lte/gateway && make run  # You can skip this if you have built the AGW with make before

2) Search docs and Docusaurus: make (?!sure)

/workspaces/magma/docs/readmes/lte/dev_notes.md
	make test_oai_runtime
	make test_oai

/workspaces/magma/docs/readmes/lte/dev_unit_testing.md
	a lot

/workspaces/magma/docs/readmes/lte/eventd.md
	    - (Python-only) Use `make build` under `lte/gateway` to generate swagger models into 

/workspaces/magma/docs/readmes/lte/setup.md
	AGW:~/magma/lte/gateway USER$ make run

/workspaces/magma/docs/readmes/orc8r/dev_testing.md
	cd ${MAGMA_ROOT}/orc8r/cloud/ && make tools  # install tools

3) agw|lte|orc8r \W+(?:\w+\W+){1,30}?make

--------

4) GithubWiki

/home/vkj/magma.wiki/Contributing-Code-with-VSCode.md
	- 7 GB RAM are required for `make test_oai` and `make build_oai` within `lte/gateway/`, while
	- 12 GB RAM are required from `make test_connection_manager` within `lte/gateway/`.
	To generate the compilation database with CMake, run `make build_oai` or the equivalent command for another target. 

/home/vkj/magma.wiki/Contributing-Documentation.md
	cd ${MAGMA_ROOT}/docs && make precommit
	cd ${MAGMA_ROOT}/docs && make precommit_fix
