### ISSUE TITLE
Make containerized AGW work without building the non-containerized AGW

### ISSUE THREAD

**Issue by wolfseb** [magma/magma#13837]
## Summary

Currently, the entire non-dockerized AGW needs to be built with `make run` before the containerized AGW is built. The goal of this story is to separate the build step of the dockerized and non-dockerized versions of the AGW.

## Acceptance criteria

* the containerized AGW can be build without executing `make run`
* find a way to execute python scripts without virtual env directly on the dev VM
* figure out how patched ovs version is currently installed and make sure ovs runs without calling `make run`
* make sure the envoy proxy is installed and running without calling `make run`

**Comment by sebathomas** [comment]
> find a way to execute python scripts without virtual env directly on the dev VM

Which Python scripts do you have in mind? Doesn't the dockerized AGW basically copy the virtualenv from the VM into the container?

**Comment by nstng** [comment]
@vktng is this already covered by an issue you recently worked on? I will close this for now - please link the issue.

**Comment by vktng** [comment]
> @vktng is this already covered by an issue you recently worked on? I will close this for now - please link the issue.

Here is the issue: https://github.com/magma/magma/issues/14391
