### ISSUE TITLE
Find a solution to build debian packages for modern Python libraries

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13847]
The current release tool pydep uses [fpm](https://fpm.readthedocs.io/en/v1.13.1/) to build debian packages, which cannot handle some dependency upgrades because newer versions use build tooling that it does not understand (see for example #13820).

Can this be solved by calling fpm with other options or upgrading it? Maybe other tooling exists to build debian packages? (See for example: https://askubuntu.com/a/508608)

Analyze all these issues and come up with a better way to package Python dependencies.

Hint: ryu...

(Note: If we fully switch to either Bazel or containerized Magma builds, we won't have this problem any more. For this reason, work on this issue is put on hold.)

**Comment by MoritzThomasHuebner** [comment]
- Look into fpm workarounds: 
  - https://github.com/jordansissel/fpm/issues/1873#issuecomment-1052033052
  - https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for
  - https://gist.github.com/adamghill/8a96311b5cf1790c72a0b825ffe4f6d2

**Comment by MoritzThomasHuebner** [comment]
Some more findings from researching this:

Options to get setup.py:
- shim "import setuptools; setuptools.setup()"
  -  Doesn't appear to work, fpm only packages the file itself, not the project
- https://github.com/orsinium-archive/poetry-setup -> Not maintained, appears to be incompatible
- https://github.com/dephell/dephell -> Not maintained
- Why can't we just use wheels?
  - Draft PR that uses `wheel2deb`: https://github.com/magma/magma/pull/13861
  - This method appears to be working on, e.g. `jsonschema==4.9.0`, which does not have a `setup.py`
