### ISSUE TITLE
Research: Improve the container agw build

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13856]
Steps:
* [x] Go through the containerized AGW code and Magma documentation and document current build process
* [x] Come up with ideas using Docker documentation (see below)
  * [ ] Reduce context size (compare with orc8r)
  * [ ] Improve build speed
  * [ ] Investigate Bazel container build. Discuss with @jheidbrink 
  * [ ] Do we really need a build container? Can we just do the build separately and then copy the output into the container?
  * [ ] Consider all three types of containers: Python, Go, C++
* [x] Discuss in a meeting
* [ ] Make a plan and create follow-up tickets
* [ ] Prepare internal review meeting

Preparation for #13836 and #13837.

* Understand which issues make the build slow, and which steps (C / Go compilation or Python env setup) are duplicated between `make run` and the different container builds.
* Come up with a plan to improve and accelerate the container build.

Hint:
When you analyze the docker files, consider
* https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
* https://docs.docker.com/develop/dev-best-practices/

**Comment by jheidbrink** [comment]
Given that we build our artifacts with Bazel, the Docker images will contain those images. The current approach is to have the Dockerfile contain a builder image, run Bazel inside that builder image, and later copy the built artifacts from the builder image to the final image.

Another approach would be to use Bazel not only to build our binaries, but also to build Docker images containing the binaries. This approach was investigated in #13549

Advantages of building Docker images with Bazel:
- Much faster builds as we can use the remote cache for the Bazel build
- Bazel's BUILD files are more nicely structured than Dockerfiles

Advantages of the current approach:
- Invocation of the build is simpler - just `docker-compose build`
- Dockerfiles are probably known to a wider audience than Bazel's BUILD files
