### ISSUE TITLE
Observing pipelined issue as there are some missing packages while installing.Observed in Master

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#13877]
All CI/CD test cases are failing because of pipelined crash which occurred because of missing oslo packages.

Here are logs capture from machine:

Sep  8 15:37:07 localhost systemd[1]: magma@enodebd.service: Failed with result 'exit-code'.
Sep  8 15:37:07 localhost pipelined[2822957]: Traceback (most recent call last):
Sep  8 15:37:07 localhost pipelined[2822957]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Sep  8 15:37:07 localhost pipelined[2822957]:     return _run_code(code, main_globals, None,
Sep  8 15:37:07 localhost pipelined[2822957]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Sep  8 15:37:07 localhost pipelined[2822957]:     exec(code, run_globals)
Sep  8 15:37:07 localhost pipelined[2822957]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/main.py", line 28, in <module>
Sep  8 15:37:07 localhost pipelined[2822957]:     from magma.pipelined.app import of_rest_server
Sep  8 15:37:07 localhost pipelined[2822957]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/app/of_rest_server.py", line 13, in <module>
Sep  8 15:37:07 localhost pipelined[2822957]:     from ryu import cfg
Sep  8 15:37:07 localhost pipelined[2822957]:   File "/usr/local/lib/python3.8/dist-packages/ryu/cfg.py", line 17, in <module>
Sep  8 15:37:07 localhost pipelined[2822957]:     import oslo_config.cfg
Sep  8 15:37:07 localhost pipelined[2822957]: ModuleNotFoundError: No module named 'oslo_config'
Sep  8 15:37:07 localhost systemd[1]: magma@pipelined.service: Main process exited, code=exited, status=1/FAILURE
Sep  8 15:37:08 localhost systemd[1]: magma@pipelined.service: Failed with result 'exit-code'.
Sep  8 15:37:08 localhost systemd-networkd[415]: envoy_cntr: Gained IPv6LL
Sep  8 15:37:08 localhost magmad[2751284]: ERROR:root:GetServiceInfo Error for enodebd! [StatusCode.UNAVAILABLE] failed to connect to all addresses

Recovery steps:
1048  pip3 list | grep oslo
 1049  sudo pip install oslo.config
 1050  sudo apt-get upgrade python-oslo.config
 1051  pip3 list | grep oslo
 1052  sudo pip install oslo.config
 1053  pidof mme
 1054  sudo apt-get upgrade python-oslo.config
 1055  pidof mme
 1056  sudo tail -f /var/log/syslog
 1057  sudo apt-get install python-oslo python-netaddr
 1058  sudo tail -f /var/log/syslog
 1059  sudo pip install Routes
 1060  pip install tinyrpc
 1061  sudo pip install tinyrpc==0.8
 1062  sudo pip install -r tools/pip-requires
 1063  sudo pip install -r ./tools/pip-requires
 1064  pidof mme
 1065  sudo tail -f /var/log/syslog
 1066  sudo webob
 1067  sudo pip install WebOb
 1068  sudo pip install WebOb==dev
 1069  sudo pip install WebOb==1.2
 1070  sudo service magma@* stop
 1071  sudo service magma@magmad start

**Comment by sebathomas** [comment]
I can't reproduce it with 1.8.0-1662716503-d6cea33a from today. Is it enough to install the magma debian package or do you need to do the manual recovery steps to reproduce the bug?

**Comment by NeelimaKalpana** [comment]
Hi Sebathomas,

Even I tried upgrade in one of the AGW . I did not encountered the issue. I will keep track of this issue and comment here if problem is observed again . 

I will keep this open for 3 days and close this ticket if issue is not notice.
Please let me know your opinion.

**Comment by sebathomas** [comment]
All right, let's wait and see if the problem happens again.
