### ISSUE TITLE
[AMF]: NGSetup failure with non-default Slice differentiator Values

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#13873]
When using non-default Slice differentiator value NGSetup requesets are failing.
Attaching the pcap [https://app.zenhub.com/files/170803235/04eaf560-17c9-403e-9e61-631d7e7c234b/download](https://app.zenhub.com/files/170803235/04eaf560-17c9-403e-9e61-631d7e7c234b/download)

**Comment by ganeshg87** [comment]
@panyogesh,

  we have tested locally,No issue identified NGSetup
[https://app.zenhub.com/files/170803235/58e39425-7b35-4017-9397-e52a7753a6ab/download](https://app.zenhub.com/files/170803235/58e39425-7b35-4017-9397-e52a7753a6ab/download)

**Comment by panyogesh** [comment]
Closing as the issue is not reproducible
