### ISSUE TITLE
[LTE Integ Flakiness] Router Advertisement issue

### ISSUE THREAD

**Issue by thinhnt1983** [magma/magma#13951]
### Description 
Some IPv6 test cases are failing for Assertion error with timeout when waiting for Router Advertisement
Observed in:
- RUN 4240: https://github.com/magma/magma/actions/runs/3063656475
- RUN 4232: https://github.com/magma/magma/actions/runs/3059652044
- RUN 4106 https://github.com/magma/magma/actions/runs/2915543298
- RUN 3910: https://github.com/magma/magma/actions/runs/2698151452 

### example: 
test_ipv6_paging_with_dedicated_bearer.py:77: 
AssertionError: Timeout (60 sec) occurred while waiting for response message

May related to https://github.com/magma/magma/pull/13020
@VinashakAnkitAman Please take a look at this issue. Thanks!
FYI: @nstng

**Comment by nstng** [comment]
Logs are outdated - and I have not seen this issue in the last couple of runs. Will close for now.
