### ISSUE TITLE
[LTE Integ Flakiness] LTE Integ tests were canceled due to timeout (360 minutes)

### ISSUE THREAD

**Issue by thinhnt1983** [magma/magma#13952]
### Description
 LTE Integ tests were canceled due to timeout (360 minutes)

- RUN 4289: https://github.com/magma/magma/actions/runs/3142207707/jobs/5105534701
- RUN 4242: https://github.com/magma/magma/actions/runs/3069323888
- RUN 4236:  https://github.com/magma/magma/actions/runs/3061866682
- RUN 3231: https://github.com/magma/magma/actions/runs/3059310760

@VinashakAnkitAman Please take a look at this issue. Thanks!
FYI: @nstng

**Comment by nstng** [comment]
Logs are outdated - the last one I can access has a timeout during running the sudo tests. These were separated from the integ tests some time ago - and are relatively stable in the last time. Will close this for now.
