### ISSUE TITLE
[LTE Integ Flakiness] AttributeError: 'NoneType' object has no attribute 'send_event_to_observers'

### ISSUE THREAD

**Issue by thinhnt1983** [magma/magma#13953]
### Description
RUN 4241: https://github.com/magma/magma/actions/runs/3068770372

 ERROR    ryu.lib.hub:hub.py:69 hub: uncaught exception: Traceback (most recent call last):
[vagrant@127.0.0.1:2222] out:   File "/home/vagrant/build/python/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
[vagrant@127.0.0.1:2222] out:     return func(*args, **kwargs)
[vagrant@127.0.0.1:2222] out:   File "/home/vagrant/build/python/lib/python3.8/site-packages/ryu/controller/controller.py", line 549, in datapath_connection_factory
[vagrant@127.0.0.1:2222] out:     with contextlib.closing(Datapath(socket, address)) as datapath:
[vagrant@127.0.0.1:2222] out:   File "/home/vagrant/build/python/lib/python3.8/site-packages/ryu/controller/controller.py", line 296, in __init__
[vagrant@127.0.0.1:2222] out:     self.set_state(HANDSHAKE_DISPATCHER)
[vagrant@127.0.0.1:2222] out:   File "/home/vagrant/build/python/lib/python3.8/site-packages/ryu/controller/controller.py", line 316, in set_state
[vagrant@127.0.0.1:2222] out:     self.ofp_brick.send_event_to_observers(ev, state)
[vagrant@127.0.0.1:2222] out: AttributeError: 'NoneType' object has no attribute 'send_event_to_observers'

@VinashakAnkitAman Please take a look at this issue. Thanks!
FYI: @nstng

**Comment by nstng** [comment]
logs are outdated and I have not seen this issue in the last couple of runs. Will close for now.
