### ISSUE TITLE
Make AGW service restarts aware of container status

### ISSUE THREAD

**Issue by wolfseb** [magma/magma#13965]
Currently, we already check for container status on the PR #13766. We are not aware whether this works for the non-containerized AGW and how stable this mechanism is for the containerized AGW.

## Acceptance criteria:

- [x] Get restart mechanism merged for the dockerized AGW
- [x] Check if the restart mechanism works for the non-containerized AGW
- [x] Make sure that integ tests work in github-actions
- [x] Prepare internal review

**Comment by mpfirrmann** [comment]
Current state: we differentiate between docker and `systemd` init system. For this, we need two parallel procedures to handle service restarts and waits for the services to run (again).
1. With docker we wait for the containers to become healthy. In the `systemd` case we wait a (empirically determined) certain amount of time (which is the current state on master).
2. Restarting all services is done via `docker-compose restart` / stopping all magma services with `sudo systemctl magma@* stop` and starting `magma@magmad`.
3. Individual services should be restarted via `restart_service(['list', 'of', 'services'], wait_time=wait_time)` to be handled correctly.

Several special cases have to be considered here:

- The container corresponding to the `mme` service is called `oai_mme`.
- The `sctpd` service does not have a `magma@` prefix. Nevertheless, it is started via the `magmad` service.
- The interdependencies between services is currently handled manually in the docker case.

In its current state, all pre-commit and extended S1AP integration tests pass using a containerized and a `systemd`-based AGW.
