### ISSUE TITLE
Make nonsanity tests against containerized AGW green

### ISSUE THREAD

**Issue by wolfseb** [magma/magma#13964]
Currently, about 5 of the nonsanity are still failing on our draft PR #13766.

## Acceptance criteria

- [x] How is the status of the systemd-based nonsanity tests on master?
- [x] Get the same tests green at least once with a containerized AGW
- [x] Get health container to start again (-> is disabled by initializing a `TestWrapper` object at the beginning of a tests)
- [x] Run all tests in a loop and create some statistics
- [x] Prepare internal review

**Comment by mpfirrmann** [comment]
"Never ran green" nonsanity tests on ...

... master:
- `test_3495_timer_for_dedicated_bearer_with_mme_restar`
- `test_sctp_shutdown_while_mme_is_stopped`

... containerized AGW:
- `test_attach_detach_with_corrupt_stateless_mme`
- `test_3495_timer_for_dedicated_bearer_with_mme_restart`
- `test_sctp_shutdown_while_mme_is_stopped`

... `systemd` based AGW on feature branch:
- `test_multi_enb_paging_request`
- `test_paging_request`
- `test_paging_with_mme_restart`
- `test_3495_timer_for_dedicated_bearer_with_mme_restart`
- `test_sctp_shutdown_while_mme_is_stopped`

**Comment by wolfseb** [comment]
The current state on master sees some nonsanity tests red (on systemd as well as Docker):
* test_3495_timer_for_dedicated_bearer_with_mme_restart
* test_sctp_shutdown_while_mme_is_stopped

These tests are red, when run repeatedly, at some point they all turn green and then stay green. It is unclear what causes this behavior.
* test_attach_esm_info_with_apn_correction
* test_no_attach_complete_with_mme_restart

This test was red but will receive a fix in #14183:
* test_no_esm_information_rsp_with_mme_restart

This test is flaky, and will be fixed in #14183:
* test_agw_offload_idle_active_ue
