### ISSUE TITLE
AGW issue，help please!

### ISSUE THREAD

**Issue by FrankZhaoX** [magma/magma#13962]
Hello,

Our COTX R&D team has now completed the following steps.
The gateway has been successfully added to orc8r (the image below shows that the gateway is only temporarily offline, the actual gateway is online).
![image](https://user-images.githubusercontent.com/93183389/191157607-356adf7b-fbc0-4c73-81a6-57e275f0e74b.png)

The small cell (SN 2202CW5001458) has also been added and the AGW has been successfully configured with a DHCP server configuration as follows ：
![image](https://user-images.githubusercontent.com/93183389/191157784-b0bb7136-3a98-41a5-b954-9015a69253a7.png)

By entering the AGW backend and checking the network configuration: eth1 port is configured with a static IP address of 10.0.2.1/24, and by checking the dnsmasq information and the arp information, we can see that the small cell has obtained an IP address of 10.0.2.246/24, and by checking the logs of enodebd, we can see that the enodebd service has been successfully started. Also in the iptables firewall you can see a nat conversion entry for the destination port 192.88.99.142:48080 to 10.0.2.1:48080, but the status of the small cell has been as follows.
![image](https://user-images.githubusercontent.com/93183389/191157814-ae2d477c-f5ce-4279-9c9f-2e04ba6efc29.png)

What is the reason for this? How can I continue debugging afterwards? Thank you!

**Comment by Radula76** [comment]
Hi, in the AGW equipment, EPC, that IP block is the DHCP/NAT for the subscribers, not for the eNB's.  please change that back to 192.168.128.0/24.
the enodeb daemon will be running a different DHCP for the eNB's.  your routing might be all messed up on the AGW, revert the config as above and restart.

**Comment by nstng** [comment]
Hi @FrankZhaoX, is your issue resolved by the answer provided from @Radula76? I will close the issue for now - feel free to reopen it if this is not resolved yet.
