### ISSUE TITLE
Assorted packer and dev-vm cleanups

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13969]
- [x] Remove old libvirt images and clean up names
- [x] Grep for stretch only stuff and remove it in vagrant and ansible
- [x] Investigate the error message that sometimes appears but doesn't seem to have an effect. If you cannot reproduce it any more after destroying and recreating the machine, ignore this task.
```
==> magma: Machine booted and ready!
==> magma: Checking for guest additions in VM...
==> magma: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl stop ifup@ovs-system.service;systemctl start ifup@ovs-system.service

Stdout from the command:



Stderr from the command:

A dependency job for ifup@ovs-system.service failed. See 'journalctl -xe' for details.
```

**Comment by mpfirrmann** [comment]
@LKreutzer @sebathomas
You may know this, as you were involved in the latest `magma-dev` VM preburn image: There is a `magma-focal-virtualbox-patch-upgrade-ovs-1.1.20210618.json` and `magma-focal-virtualbox.json`. Which one is to be removed and which one to keep / rename?

**Comment by mpfirrmann** [comment]
Grepping for `stretch` also gives me mentions in several other directories / files:

`.cache/go/pkg/mod/github.com/docker/docker@v1.13.1/ ...`
`.cache/go/pkg/mod/google.golang.org/genproto@v.0.0.0-202108223120-3a666f561d7aa/ ...`
`ci-scripts/registry/aptly/deploy_image.sh`
`experimental/cloudstrapper/playbooks/roles/magma-agw/vars/main.yaml`
`hil_testing/Magma_Ansible/project/roles/upgrade-prep/tasks/main.yaml`
`nms/app/components/JsonEditor.tsx`
`lte/gateway/release/upgrade_magma.sh`
`lte/gateway/release/pydep`
`lte/gateway/release/deb_dependencies.bzl`

I'm not quite sure what can be touched without breaking anything.

**Comment by mpfirrmann** [comment]
If I see this correctly, then @crasu fixed the VM error mentioned above some weeks ago in #13622.
> The reason the reload failing is that some magma network devices do not fully come up (e.g. do not get an ip even if set to auto). This triggers this systemd/vagrant issue:
> https://github.com/systemd/systemd/pull/4733
> https://github.com/fgrehm/vagrant-lxc/issues/481
The linked GitHub PR/issue features the error message described above.
