### ISSUE TITLE
(cloud): the role 'pkgrepo' was not found in magma/orc8r/cloud/roles

### ISSUE THREAD

**Issue by chrisburkegg** [magma/magma#14]
Environment (let me know if anything else is needed):

    OS X 10.14.2
    $ vagrant version
    Installed Version: 2.2.3
    Latest Version: 2.2.3
    $ ansible --version
    ansible 2.7.8

Same as #13

**To reproduce:**

1. clone the repository
2. follow instructions; in terminal window 2:
2. cd orc8r/cloud
3. vagrant up datastore (await completion)
3. vagrant up cloud

Output:

```
[ ... truncated vagrant output ...]
==> cloud: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.7.8).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    cloud: Running ansible-playbook...
 [WARNING]: Found both group and host with same name: magma-cloud-dev

ERROR! the role 'pkgrepo' was not found in /Users/christopherburke/magma/orc8r/cloud/deploy/roles:/Users/christopherburke/roles:/Users/christopherburke/magma/orc8r/cloud/deploy

The error appears to have been in '/Users/christopherburke/magma/orc8r/cloud/deploy/cloud.dev.yml': line 42, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - { role: apt_package_cache, when: ansible_user == 'vagrant'}
    - { role: pkgrepo, vars: { distribution: "xenial" } }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Note:

    $ ls deploy/roles
    apt_package_cache dev               golang            modules           pkg_repo          proxy
    aws_setup         disk_metrics      kafka             ocs               postgres          zookeeper
    controller        dynamodb          kafka_prod        osquery           prometheus

**Comment by xjtian** [comment]
Hi @krslynx, we set a roles path in `ansible.cfg` which should allow ansible to pick up the common roles like pkg_repo: https://github.com/facebookincubator/magma/blob/e309948fc53d273fd94289222efd7b856ca8a8a9/orc8r/cloud/ansible.cfg#L7

I'm unable to repro on a fresh clone of the repository on the same ansible version unfortunately.

Is it possible that you have environment variables which are overriding this? Specifically maybe an `ANSIBLE_ROLES_PATH`: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-roles-path

**Comment by chrisburkegg** [comment]
Good find, unsetting the environment variable fixed the issue for me. Thank you!
