### ISSUE TITLE
[AMF]Session AMBRs are not proper when there is a policy attached on Subscriber.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#14019]
Version: 1.8.0-1664274393-10f717f9
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: bare-metal (AGW)-VM Based

### Describe the Issue

[AMF]Session AMBRs are not proper when there is a policy attached on Subscriber.

#### To Reproduce

1. Add a subscriber with APN and Policy attached.
2. Trigger the PDU-Session from the UE.
3. Observe that PDU is success and traffic flow is working as expected. And the Session AMBR should be the APN AMBR configure in NMS.

#### Expected behavior

Expecting PDU should come up with all APN and Polices parameters  subscribed and Traffic flow should work.

#### Screenshots
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/160ba6be-30e5-4e88-bb4b-b70708059813)

![image.png](https://ima![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/503592d2-53f1-4e4d-b960-d5b81fc607b0)ges.zenhubusercontent.com/6139f1931bcb9da2af1bf651/00172275-57a2-4666-bbcc-5bdbe9f492fd)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1748bcde-8092-41dd-8d90-64eb3f4f9b17)

Session AMBRs in PDU-Accept Message:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/329f266e-9552-44ad-acd4-145c93e2143e)

Please find the attached logs for more details:
[https://app.zenhub.com/files/170803235/b45087c3-de1a-4960-ab80-feb934c33277/download](https://app.zenhub.com/files/170803235/b45087c3-de1a-4960-ab80-feb934c33277/download)

**Comment by nstng** [comment]
Already handled in #14098.
