### ISSUE TITLE
[Pipelined]Observing traffic DL traffic drop when there is a policy applied on a particular subscriber.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#14018]
Version: 1.8.0-1664274393-10f717f9
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: bare-metal (AGW)-VM Based

### Describe the Issue

[Pipelined]Observing traffic DL traffic drop when there is a policy applied on a particular subscriber.
Note : Tracebacks are observed in pipelined service.

#### To Reproduce

1. Add a subscriber with APN and Policy attached.
2. Trigger the PDU-Session from the UE.
3. Observe that PDU is success and traffic flow is working as expected.

#### Expected behavior

Expecting PDU should come up with all APN and Polices parameters  subscribed and Traffic flow should work.

#### Screenshots
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/160ba6be-30e5-4e88-bb4b-b70708059813)

![image.png](https://ima![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/503592d2-53f1-4e4d-b960-d5b81fc607b0)ges.zenhubusercontent.com/6139f1931bcb9da2af1bf651/00172275-57a2-4666-bbcc-5bdbe9f492fd)

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1748bcde-8092-41dd-8d90-64eb3f4f9b17)

Error Observed in syslogs:

![image.png](https://ima[https://app.zenhub.com/files/170803235/a23d1dd7-1912-4760-baa9-00b8ecf129a2/download](https://app.zenhub.com/files/170803235/a23d1dd7-1912-4760-baa9-00b8ecf129a2/download)ges.zenhubusercontent.com/6139f1931bcb9da2af1bf651/505766ac-4b5f-49dd-8ed4-2137fa4a9276)

**Comment by mehul-jindal-wavelabs** [comment]
Traffic is workig for a single subscriber as expected in my setup with latest code, will update the status of the issue in case of multiple subscribers shortly
![image](https://user-images.githubusercontent.com/88073743/201943587-cdb11bc6-7c27-46d0-8332-e9843a70de25.png)
![image](https://user-images.githubusercontent.com/88073743/201944358-f12fb53c-e681-4bcf-a1a3-90cfc1e8279e.png)

**Comment by prabinakpattnaik** [comment]
Please do configure in correct way and we have attached logs and correct scenario for how to verify the multiple policy configurations. This issue is not observed on master hence close this issue.
