### ISSUE TITLE
Make the Bazel local setup more comfortable

### ISSUE THREAD

**Issue by vktng** [magma/magma#14026]
Right now the setup for Bazel for local testing is not user/developer friendly:
```
vagrant up magma
vagrant ssh magma
---
# initial
# if wanted: cd ~/magma; bazel/scripts/remote_cache_bazelrc_setup.sh magma-dev-vm false
cd ~/magma; bazel build `bazel query "kind(.*_binary, //orc8r/... union //lte/... union //feg/...)"`;
cd ~/magma; bazel/scripts/link_scripts_for_bazel_integ_tests.sh;
sudo cp $MAGMA_ROOT/lte/gateway/deploy/roles/magma/files/systemd_bazel/* /etc/systemd/system/
sudo systemctl daemon-reload
magma-start
---
# rebuild change
cd ~/magma; bazel build <target>
magma-restart # (or only relevant service)
```
@nstng edit: removed precedence lines as this is now active on all relevant VMs per default
@nstng edit: removed dist upgrade as this is now removed from CI workflows

A script combined with a nice alias could be a good solution.

* remove dist-upgrade from all lte integ test workflows
  * do this in a separate PR
* precedence might get removed by #14057
* `cd ~/magma; bazel/scripts/link_scripts_for_bazel_integ_tests.sh;` is needed
* `sudo cp $MAGMA_ROOT/lte/gateway/deploy/roles/magma/files/systemd_bazel/* /etc/systemd/system/` is needed
  * see if this can be solved like for the scripts via linking (python services might be problematic) - if yes, include this in the script to link the scripts and remove the bazel systemd definitions
* summarize all steps in a convenience script that can be used to easily spin up a local integ test setup

**Comment by jheidbrink** [comment]
* I don't use the gai.conf modifications and it works fine
* why is the remote_cache_bazelrc_setup.sh needed? Didn't we explicitly design the caching so that the disk cache is used per default so that locally we don't need to change anything?
* for the scripts and systemd files: What I do is build the magma.deb with Bazel and then install it. But also, I don't run the Ansible provisioning, so the systemd files for the Make-based build are not present

**Comment by nstng** [comment]
@jheidbrink "I don't use the gai.conf modifications and it works fine" - this is only for performance reasons - see https://github.com/magma/magma/pull/14057
