### ISSUE TITLE
Try running integration tests with Sentry active

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14035]
There has not been much usage of [Sentry](https://github.com/magma/magma/wiki/Error-monitoring-and-triaging-workflow) within Magma since the lab was shut down after the v1.7 release. One possibility to get back error monitoring would be to connect the AGW services to Sentry while running integration tests.

Idea:
* [x] Set up an AGW with Sentry enabled for a test account, not the main Magma account.
* [x] Run the same integration tests that would also run in the CI (precommit + extended, not nonsanity).
* [x] Observe how many errors are reported in Sentry, and analyze the results (expected test errors vs. real bugs). If there are expected errors, think about changing the log level or excluding them from monitoring.
* [x] Depending on the results, think about enabling Sentry during integration tests in CI.
* [x] Prepare internal review meeting

**Comment by MoritzThomasHuebner** [comment]
Update: These are the errors triggered due to the tests.

![Image](https://user-images.githubusercontent.com/8889531/195042712-5df74aab-75b4-4188-a559-bcea29d7fdf2.png)

**Comment by alexzurbonsen** [comment]
With the changes from #14132 one can tag events in Sentry with integ test name. Used this for the analysis following below.

### test_attach_detach.py

Starting with a simple example.

#### Successful run

![grafik](https://user-images.githubusercontent.com/82914459/195314864-01edf80e-18e9-4311-9ab5-37fb360b3535.png)

#### Failed run, due to set up issues

![grafik](https://user-images.githubusercontent.com/82914459/195310171-8d9bed59-bfe8-4d01-9374-c092a5b2cff5.png)


Shows, that issues can easily accumulate if tests fail due to set up problems.

**Comment by alexzurbonsen** [comment]
### Precommit Tests

Running all precommit tests plus some idle time (ca. 1 h), in which the services are running without tests and other specific tasks. This was done to get a baseline of issues.

Great majority of tests passed. 

#### View of all issues that appeared

![Screenshot 2022-10-12 at 17 36 27](https://user-images.githubusercontent.com/82914459/195388580-4c445bcd-adca-4ed7-b0eb-23557f4cf4fd.png)

#### baseline issues

The top 6 issues in the list predominantly appeared during idle time (baseline). The `integ_test_name` distribution always shows roughly 65% of issues occurred during idle time. Probably that means that they are system noise.

![Screenshot 2022-10-12 at 17 35 46](https://user-images.githubusercontent.com/82914459/195388960-4b32f5eb-f0f6-44a8-ae78-4066719373d7.png)

#### integ test issues

Issue `unknown barrier xid 680361403` is by far the most frequent issue that occurs during test runs. It seems to appear in almost (or literally?) every test. Only once during idle time.

It is related to pipelined and ovs. But unclear to me currently whether this is a real error or something that is expected.

The following tests contributed more than 20 events.
![Screenshot 2022-10-12 at 17 53 25](https://user-images.githubusercontent.com/82914459/195390464-38d6a92e-ef34-414c-9d41-4be12b099a05.png)

**Comment by alexzurbonsen** [comment]
If we assume the top 6 errors to be system noise and exclude them (also done by changes in #14132), there are still some errors remaining.

Are they expected and should be excluded or not?

unknown barrier xid 680361403
- most frequent issue for me, but doesn't appear in Moritz' set up
- raised by a thrid party library: ryu's ofctl service (https://sourcegraph.com/github.com/faucetsdn/ryu/-/blob/ryu/app/ofctl/service.py?L189)
- unclear to me currently whether this is a real error or not
- could only be handled via exclude list

Unknown match field: priority
- another ryu error (https://sourcegraph.com/github.com/faucetsdn/ryu/-/blob/ryu/lib/ofctl_v1_4.py?L197)

unknown dpid 11014189103438
- unknown datapath id error
- could be raised in pipelined (lte/gateway/python/magma/pipelined/openflow/messages.py) or in ryu directly, not sure currently

unable to read speed from ...
- raised in pipelined (lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py L101)
- not visivle in Moritz' set up

**Comment by alexzurbonsen** [comment]
Sentry issues that should be turned into GH issues:

- [ ] unknown dpid 11014189103438
- [ ]
