### ISSUE TITLE
IDEs can navigate generated code without make

### ISSUE THREAD

**Issue by nstng** [magma/magma#14036]
Jan Heidbrink:
One thing to keep in mind for the Bazel switchover: I assume the Intellij over SSH solution still requires make to put things like compiled proto files to a place where intellij finds them. I think we shouldn't break things for Intellij users. That would mean we need to find a way to make Intellij aware of the Bazel-built proto files (similar probably for further things like Python dependencies).

* figure out how intellij is used - local repo vs vm repo vs docker
* figure out where intellij usage is documented
* figure out what bazel output needs to be added and what bazel build commands create them
  * proto, swagger, pip dependencies, ...
* what needs to be done for vscode/is already done?
* add documentation results to #14025

timeboxed 1p~=1day

**Comment by sebathomas** [comment]
For Python development in Intellij, you basically set the SDK path to sftp://vagrant@localhost:2222/home/vagrant/build/python/bin/python. If there is an equivalent path for the Bazel build, it might be enough to document that.

**Comment by jheidbrink** [comment]
A dedicated Bazel target might be needed. Maybe we can learn from how it's done for C.
