### ISSUE TITLE
Research: Reduce duplicate resources in GitHub action builds

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14045]
With the proposed CI changes, there are four integration test workflows
- Normal
- Bazel
- Debian
- Docker

They might be able to share resources.

Also, it seems unnecessary that all of them run on every merge.

**Comment by Neudrino** [comment]
- Closing as done with https://github.com/magma/magma/issues/14047. If something is not covered there, it should probably be added to get a consolidated overview of integration tests.
