### ISSUE TITLE
Prioritisation of LTE integ test workflows

### ISSUE THREAD

**Issue by voisey** [magma/magma#14047]
There are currently three workflows that run the LTE integration tests, the difference between them being the way magma is installed

- LTE integ test - development set-up with make
- LTE integ test bazel - development set-up with bazel
- LTE integ test magma-deb - production debian set-up

with a fourth on its way

- LTE integ test containerized agw - docker (https://github.com/magma/magma/pull/14023)

In addition, the debian and docker workflows could in theory also be built with bazel.

At present, only the first is in the [CI dashboard](https://magma-ci.web.app/). It should be decided which workflows we want to keep around, how often they should run (maybe for the development set-ups, running on every merge to master is too much), and which should be in the CI dashboard. I would propose aiming to have at least the debian and docker workflows in the CI dashboard.

Proposal for solution was presented in DevOps meeting, see: https://wiki.magmacore.org/display/HOME/2022-10-12+DevOps+Monthly

To dos from the above proposal:

- [x] #14159 
- [x] #14160
- [x] #14161
- [x] #14162
- [x] #14178
- [x] #14180

**Comment by nstng** [comment]
all sub-tasks are done -> closed
