### ISSUE TITLE
Try building the docker AGW containers with Bazel

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14049]
An alternative setup to build the AGW docker containers would be to use Bazel directly, instead of relying on custom Dockerfiles. As a first test, we want to try this approach with two of the containers (C++ and Python) and compare to the current way of building the containers.

- [x] Build example services with bazel and put them into a container (sessiond for C and mobilityd for python)
  - Measure the improvement in build time when changing something in the code until the container is up
- [x] Find efficient development workflow
  - bazel build cache in tmp folder → building on host more efficient
- [x] Run integ-tests that use mobilityd and sessionsd to test if new build flows work (basically any test with the traffic server should do)
  - test_attach_detach
  - test_attach_detach_[ul/dl]_[tcp/udp]
- [x] Summarize findings, evalutate bazel vs Dockerfile approach
- [x] Prepare internal review

**Comment by wolfseb** [comment]
## Summary

Containers were build with bazel for
* Python: enodebd, mobilityd
* C: sessiond (mme was tried as well, but has some minor issue left to solve regarding the entrypoint and startup command)

The integ tests against the dockerized AGW with the bazel-built containers enodebd, mobilityd, and sessiond run without issues:
* `test_attach_detach`
* `test_attach_[ul/dl]_[tcp/udp]_data`

## Comparison of build times

Build container                  |      Docker       |      Bazel (mobilityd / sessiond)
-|-|-
Python from scratch          |        258 s         |      15 s
Python after code change |          62 s         |        4 s
C from scratch                  |         840 s         |      15 s
C after code change         |         318 s         |       4 s

Note: The first build with Bazel includes downloads for general tools, which are cached for all subsequent builds, which adds roughly 30s to the first build after a fresh VM setup.

## Comparison of image size

Container     |   Docker     |    Bazel
-|-|-
Python           |   1.36 GB  |   ~200 MB per service
C                 |   1.28 GB     |  ~260 MB per service

Note: Bazel produces a lot of intermediate images which will be lying around, a lot of which might potentially be reusable, e.g. a separate base image with ca_certificates and the artifactory public key

**Comment by wolfseb** [comment]
@nstng Fyi: bazel vs Docker benchmarks

**Comment by wolfseb** [comment]
For an even better dev workflow, the bazel cache can be changed to, e.g., `/var/tmp/bazel` instead of `/tmp/bazel/`, to make it persistent (so it doesn't disappear after a vm reboot)
