### ISSUE TITLE
[LTE Integ Flakiness] Timeout occurred while waiting for response message

### ISSUE THREAD

**Issue by thinhnt1983** [magma/magma#14069]
## Description
AssertionError: Timeout (60 sec or 180 sec) occurred while waiting for response message

- It happens from time to time with most recent RUN 4300: https://github.com/magma/magma/actions/runs/3161998010 with scenario file test_3485_timer_for_default_bearer_with_mme_restart . It's related to ISSUE [14054](https://github.com/magma/magma/issues/14054) 

Happened in the past:
- RUN 4292 (https://github.com/magma/magma/actions/runs/3148778711) with scenario file 
test_ipv6_paging_with_dedicated_bearer.py and test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4329: https://github.com/magma/magma/actions/runs/3221315689 with scenario test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4291: https://github.com/magma/magma/actions/runs/3148198287 with scenario file test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4290: https://github.com/magma/magma/actions/runs/3142870045  with scenario file test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4288: https://github.com/magma/magma/actions/runs/3141952716 with scenario file test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4286: https://github.com/magma/magma/actions/runs/3137852300 with scenario file test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4335: https://github.com/magma/magma/runs/8832444576 with scenario file test_3485_timer_for_default_bearer_with_mme_restart.py
- RUN 4336: https://github.com/magma/magma/actions/runs/3229172130 with scenario file test_3485_timer_for_default_bearer_with_mme_restart.py 

@VinashakAnkitAman please take a look at this issue! Thanks!
FYI: @nstng

**Comment by nstng** [comment]
I have not seen this in the last time - it might have been fixed by various efforts to handle and mitigate integ test timeout issues. I will close this for now - if this is still a problem then a new issue with updated data should be created.
