### ISSUE TITLE
Remove unused files from AGW VM images

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#14080]
The AGW VM images contain some unused files that significantly increase the image size.

There are about 600 MB of `.deb` packages in `/home/vagrant/magma/.cache/apt/focal`. The reason probably is that we symlink `/var/cache/apt/archives` to `/home/vagrant/magma/.cache/apt/focal`. During normal VM usage, `/home/vagrant/magma` is a shared folder from the host system, and the symlink ensures that the apt cache can be reused between different VMs. However it seems that this symlink is already created during the VM build. And when the `magma` repository gets mounted at `/home/vagrant/magma`, these files become inaccessible, but still contribute to the VM image's size.

There is a `/var/tmp/libprotobuf-mutator` directory with a size of 1GB. This probably contains a lot of files only required for the build of libprotobuf-mutator and not for running it. In the devcontainer we remove this directory after we run `ninja install`, but in the VM we keep it. This should probably be removed.

**Comment by jheidbrink** [comment]
linking https://github.com/magma/magma/issues/13969 as this is also a cleanup task targeting the VMs.

**Comment by mpfirrmann** [comment]
Link #13566 as a todo when creating the next base image.

**Comment by jheidbrink** [comment]
The symlink for the apt cache is created in https://github.com/magma/magma/blob/f49152a0281ea922aaa699040026185820f2b4c8/orc8r/tools/ansible/roles/apt_cache/tasks/main.yml

**Comment by jheidbrink** [comment]
The first part is now done, but in the new image there still is 1GB `/var/tmp/libprotobuf-mutator`:

```
vagrant@magma-dev:~$ du -sh  /var/tmp/libprotobuf-mutator/
970M	/var/tmp/libprotobuf-mutator/
```

**Comment by nstng** [comment]
libprotobuf-mutator is removed in https://github.com/magma/magma/pull/14360 - for the VM a new preburn image is needed
