### ISSUE TITLE
pylint and pycodestyle should be moved to precommit.py

### ISSUE THREAD

**Issue by vktng** [magma/magma#14087]
`make integtests` includes running pylint and pycodestyle on Python files. The Python format check uses lte/gateway/python/precommit.py with isort, autopep8 and add-trailing-comma.

Why are there 2 different ways to format?
Could the ones from the make target be included in the `precommit.py`?

**Comment by MoritzThomasHuebner** [comment]
Note: I believe this is meant to say `make check` instead of `make integtests`
