### ISSUE TITLE
 [CWF Integ Flakiness] errors: /etc/magma/gateway.mconfig: no such file or directory and assertion greater than or equal

### ISSUE THREAD

**Issue by frmess** [magma/magma#14114]
### Description
In this issue we see two errors:
        - The file /etc/magma/gateway.mconfig: was not found
        -  Assertion "Value1" is not greater than or equal to "Value2"

### Runs
- RUN 4162: https://github.com/magma/magma/actions/runs/3218511914 with scenarios: 
     - gy_enforcement_test.go for tests:
                - TestGyCreditTransientErrorRestrict
- RUN 4240: https://github.com/magma/magma/actions/runs/3315070386 with scenarios: 
     - gy_enforcement_test.go for tests:
                - TestGyCreditExhaustionRestrict

**Comment by nstng** [comment]
Closed - see comment on #14113.
