### ISSUE TITLE
Track CWF Integ Flakiness

### ISSUE THREAD

**Issue by frmess** [magma/magma#14113]
To track the current status of all the issues related to CWF Integ Flakiness with **_To Be Completed_**: 

### Free to grab
- [ ] ISSUE 14114: https://github.com/magma/magma/issues/14114
- [ ] ISSUE 14119: https://github.com/magma/magma/issues/14119
- [ ] ISSUE 14120: https://github.com/magma/magma/issues/14120
- [ ] ISSUE 14257: https://github.com/magma/magma/issues/14257
- [ ] ISSUE 14258: https://github.com/magma/magma/issues/14258

### In progress

- [ ] 

### Done
- [ ]

**Comment by nstng** [comment]
CWF integration tests have been relatively stable in the lat couple of weeks https://github.com/magma/magma/actions/workflows/cwf-integ-test.yml (apart from an issue with the docker compose upgrade - but this was investigated and fixed). I will close this issue (and the sub-issues) for now. New one should be created if CI becomes flaky again.
@frmess feel free to reopen the issues if you disagree.
