### ISSUE TITLE
[CWF Integ Flakiness] Timeout error: timeout:60  

### ISSUE THREAD

**Issue by frmess** [magma/magma#14119]
### Description

Test is failing due to timeout(60) issue

### Runs

- RUN 4162: https://github.com/magma/magma/actions/runs/3218511914 with scenarios:
     - gy_enforcement_test.go for tests: 
                 - TestGyCreditValidityTime
- RUN 4240: https://github.com/magma/magma/actions/runs/3315070386 with scenarios:
     - gx_reauth_test.go for tests: 
                 - TestGxReAuthWithMidSessionPolicyRemoval
     - gx_reauth_test.go for tests:
                 - TestGxReAuthWithMidSessionPoliciesRemoval
                 - TestGxReAuthWithMidSessionPolicyInstall
                 - TestGxReAuthWithMidSessionPolicyInstallAndRemoval
                 - TestGxReAuthQuotaRefill
     - gy_enforcement_test.go for tests:
                 - TestGyCreditExhaustionWithCRRU
                 - TestGyCreditValidityTime
                 - TestGyCreditExhaustionWithoutCCRU
                 - TestGyCreditExhaustionRedirect
                 - TestGyAbortSessionRequest
                 - TestGyCreditExhaustionRestrict

**Comment by nstng** [comment]
Closed - see comment on #14113.
