### ISSUE TITLE
Fix Bazel build and test workflow for 1.8

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [magma/magma#14122]
### Describe the Issue
Running the Bazel build and test workflow with the current 1.8 release fails on the CI:
https://github.com/magma/magma/actions/runs/3224983943/jobs/5276741970

```
//lte/gateway/c/session_manager/test:cloud_reporter_test                TIMEOUT in 3 out of 3 in 60.0s
  Stats over 3 runs: max = 60.0s, min = 60.0s, avg = 60.0s, dev = 0.0s
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/session_manager/test/cloud_reporter_test/test.log
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/session_manager/test/cloud_reporter_test/test_attempts/attempt_1.log
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/session_manager/test/cloud_reporter_test/test_attempts/attempt_2.log
//lte/gateway/c/session_manager/test:sessiond_integ_test                TIMEOUT in 3 out of 3 in 60.0s
  Stats over 3 runs: max = 60.0s, min = 60.0s, avg = 60.0s, dev = 0.0s
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/session_manager/test/sessiond_integ_test/test.log
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/session_manager/test/sessiond_integ_test/test_attempts/attempt_1.log
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/session_manager/test/sessiond_integ_test/test_attempts/attempt_2.log

Executed 101 out of 191 tests: 189 tests pass and 2 fail locally.
```

#### To Reproduce

There are different ways to run this, you can use the Github CLI to trigger the Bazel Build and Test workflow to trigger a run on the 1.8 release. However, you need to make sure the path filters do not stop the workflow from running. See this PR for how to set up a workable branch:
https://github.com/magma/magma/pull/14108

#### Expected behavior

The workflow turns green.

#### Additional context

Follow up to https://github.com/magma/magma/issues/14078

**Comment by nstng** [comment]
Will be handled via https://github.com/magma/magma/pull/14108. Reason: https://github.com/magma/magma/pull/14108 and this PR are fixing required PR checks on the 1.8 branch. Only together they can be merged without force merges.
