### ISSUE TITLE
[LTE Integ Flakiness]  Bad File Descriptor

### ISSUE THREAD

**Issue by frmess** [magma/magma#14128]
## Description
OSError: Bad file descriptor

- RUN 4329 (https://github.com/magma/magma/actions/runs/3221315689) with scenario test_attach_detach_multiple_ip_blocks_mobilityd_restart.py

@VinashakAnkitAman please take a look at this issue! Thanks!
FYI: @nstng

**Comment by nstng** [comment]
I have not seen this issue in the last couple of runs. Will close for now.
