### ISSUE TITLE
[CWF Integ Flakiness] Timeout error: timeout:30

### ISSUE THREAD

**Issue by frmess** [magma/magma#14120]
### Description

Test is failing due to timeout(30) issue

### Runs
- RUN 4162: https://github.com/magma/magma/actions/runs/3218511914 with scenarios:
     -  auth_test.go for tests:
            -  TestAuthenticateMultipleAPsUplinkTraffic
- RUN 4240: https://github.com/magma/magma/actions/runs/3315070386 with scenarios:
     -  auth_test.go for tests:
            - TestAuthenticateUplinkTraffic
            - TestAuthenticateMultipleAPsUplinkTraffic
     - gx_enforcement_test.go for tests:
             - TestGxMidSessionRuleRemovalWithCCA_U

**Comment by nstng** [comment]
Closed - see comment on #14113.
