### ISSUE TITLE
CI support for dockerized agw fix tests that do not run out of the box on ci

### ISSUE THREAD

**Issue by crasu** [magma/magma#14124]
# Background

#14123 has added all the simple to integrate tests to ci. This ticket fixes all the hard cases/tests. 

# Acceptance

* Precommit and extended s1ap tests do work on ci
* Non sanity test are not included in this story

**Comment by Neudrino** [comment]
The following issues and pull requests might be overlapping:
- https://github.com/magma/magma/pull/13766
- https://github.com/magma/magma/issues/14124
- https://github.com/magma/magma/issues/14293
