### ISSUE TITLE
[LTE Integ Flakiness] Assertion Error

### ISSUE THREAD

**Issue by frmess** [magma/magma#14135]
### Description
Assertion comparing two numbers fails

### Scenarios
- RUN 4333 (https://github.com/magma/magma/actions/runs/3227519099) with scenario test_ipv4v6_paging_with_dedicated_bearer.py
- RUN 4404 (https://github.com/magma/magma/actions/runs/3315137520) with scenario test_services_are_running.py

**Comment by nstng** [comment]
I have not seen this issue in the last couple of runs. Will close for now.
