### ISSUE TITLE
Replace LTE make magma.deb workflow with Bazel version in CI dashboard

### ISSUE THREAD

**Issue by voisey** [magma/magma#14180]
:warning: This is part of the plan in https://github.com/magma/magma/issues/14047 but is not yet ready to be worked on.

When the switchover from make to Bazel happens, replace this [make workflow](https://github.com/magma/magma/blob/master/.github/workflows/lte-integ-test-magma-deb.yml) with the corresponding [Bazel workflow](https://github.com/magma/magma/blob/master/.github/workflows/lte-integ-test-bazel-magma-deb.yml) in the [CI dashboard](https://magma-ci.web.app/). Depends on https://github.com/magma/magma/issues/14159.

**Comment by jheidbrink** [comment]
Possibly depends on #14299
