### ISSUE TITLE
Removing code owners

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#14208]
The [Governance guidebook](https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance) only talks about adding code-owners. We also need a way to trim the code owner list as contributors move out of the project. This proposal is to add the following section to the guidebook.

**Removing code-owners**

- An existing code-owner can always choose to leave the `approvers-*` team by sending a request to @wendallkaters .

- Periodically, each `approvers-*` team can also review the code owner activity and initiate a vote to remove a member from the team. @wendallkaters can facilitate the voting, similar to the process for [becoming a code-owner](https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance). This should be done at least once every year.

**Comment by lucasgonze** [comment]
There should be a third bullet point for approvers-* teams that have no active members.

**Comment by maxhbr** [comment]
this was voted for and accepted on 2022-12-14

**Comment by Neudrino** [comment]
Implementation: https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance#removing-code-owners

Please verify and close if sufficient. @ssanadhya @wendallkaters @maxhbr
