### ISSUE TITLE
While testing registration reject PLMN mismatch TC notice after registration reject UE Context Release Command . 

### ISSUE THREAD

**Issue by Niteshwavelabs** [magma/magma#14213]
Your Environment

Version: 1.8.0-1666089907-0a0a7f55 
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: bare-metal (AGW)-VM Based

Describe the Issue: 
Performing Test Case PLMN mismatch  UE Context Release Command is sending after registration reject .

![image.png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/a49a343b-98bd-45d9-82ef-1daae9ff1573)

[https://app.zenhub.com/files/170803235/2d957bf3-947c-46cd-826d-141d3df27845/download](https://app.zenhub.com/files/170803235/2d957bf3-947c-46cd-826d-141d3df27845/download)

**Comment by Niteshwavelabs** [comment]
List of Test cases are failing in CICD because of this issue.
1.Verify_Service_Reject_for_SReq_MO_Data.
2.Reg_Reject_PLMNmismatch_cause_96

**Comment by ganeshg87** [comment]
Script changes are required. Scenario is not aligned with testcase

**Comment by Niteshwavelabs** [comment]
Yes, issue got resolved. I have attaching the PCAP for reference . 

![image.png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/145b3dcd-e6fc-4502-a721-a8af3f7a76e4)
