### ISSUE TITLE
Periodic registration is failing in security mode command as AMF is not sending proper UE security capability .

### ISSUE THREAD

**Issue by Niteshwavelabs** [magma/magma#14219]
Your Environment

Version: 1.8.0-1666111742-5dbb7ba2
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: bare-metal (AGW)-VM Based

Describe the Issue:
Performing Test Case Periodic_reg_with_0_sec_cap_Without_stmsi_PositiveFlow. in this Test case AMF is not sending proper UE security capabilities in security mode command request.

![image.png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/8cc99768-53c9-48a9-8f13-990a933067e2)

[https://app.zenhub.com/files/170803235/ccf49be9-46d8-442f-8a4c-069d68c45ae5/download](https://app.zenhub.com/files/170803235/ccf49be9-46d8-442f-8a4c-069d68c45ae5/download)

**Comment by Niteshwavelabs** [comment]
List of Test cases are failing in CICD because of this issue .
1. Periodic_reg_with_0_sec_cap
2. Periodic_reg_with_0_sec_cap_NO_STMSI
3. Periodic_reg_with_NO_STMSI 
4. Periodic_reg_with_0_sec_cap_Without_stmsi_PositiveFlow

**Comment by ganeshg87** [comment]
addressed theses and fixes are available in latest master.

**Comment by Niteshwavelabs** [comment]
yes we can close this ticket. I am adding here current working PCAP & logs.

![image.png](https://images.zenhubusercontent.com/618a22d32291cb62a63904cf/7f590170-fb10-4458-83fa-24f4f978c702)

http://172.16.5.60/abot/#/artifacts/61?path=magma-epc%2F28Oct2022-04:59:45.287011@magma-5G%2Fperiodic_reg_with_0_sec_cap_without_stmsi_positiveflow%2Fpacket-captures%2Fabot-packets%2FPeriodic_reg_with_0_sec_cap_Without_stmsi_PositiveFlow_28Oct2022-044123AM-UTC.pcap&fileName=Periodic_reg_with_0_sec_cap_Without_stmsi_PositiveFlow_28Oct2022-044123AM-UTC.pcap
