### ISSUE TITLE
Investigate state of `agw-docker-load-test.yml`

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#14228]
Ivestigate state of `agw-docker-load-test.yml`

If possible remove and clean up.

**Comment by LKreutzer** [comment]
> Possible duplicates:
> 
>     * [Investigate state of `agw-docker-load-test.yml` #14228](https://github.com/magma/magma/issues/14228)
> 
>     * [Create CI job for running the load tests #14318](https://github.com/magma/magma/issues/14318)

Keeping this open - it seems they are unrelated because the load tests are not executed anywhere - in fact the Make targets have been removed and this workflow is unchanged. The bazel script is not run in CI.

**Comment by mpfirrmann** [comment]
The last run was failing with an [authentication failure at AWS](https://github.com/magma/magma/actions/runs/3321374451/jobs/5488935250#step:8:34). The workflow uses `secrets.FB_AWS_ACCESS_KEY` and `secrets.FB_AWS_SECRET_ACCESS_KEY`. Are they still present / is the AGW account still open?
@maxhbr, do you know anything here?
