### ISSUE TITLE
[CWF Integ Flakiness] Timeout error: timeout

### ISSUE THREAD

**Issue by frmess** [magma/magma#14257]
### Description

Test is failing due to timeout issue or deadline exceeded

- RUN 4240: https://github.com/magma/magma/actions/runs/3315070386 with scenarios:
    - gx_enforcement_test.go for tests:
          - TestGxUsageReportEnforcement
          - TestGyCreditTransientErrorRestrict
          - TestGyWithTransientErrorCode

**Comment by nstng** [comment]
Closed - see comment on #14113.
