### ISSUE TITLE
Test Magma build and installation with the new Artifactory

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14272]
After the initial migration of packages is complete, we can test if all necessary packages are available in the new Artifactory.

* [x] Spin up a VM which is only based on the new Artifactory.
  * [x] Check if it is necessary to start from scratch with an Ubuntu base image and run the preburn steps. It's possible that the Artifactory is already used to create the base image - but maybe not. -> You need to run the preburn steps.
* [x] Try to build the magma services with `make run` and run some integration tests.
* [X] Try to start the dockerized AGW and make sure the containers run successfully.
* [x] Try to build a magma debian release.
* [x] Try to install a magma debian release from the CI.
  * [x] focal-ci in test
  * [x] focal-1.8.0 in prod
* [x] Try to install the orc8r from Artifactory helm charts in minikube.
* [x] Try FEG and CWAG setup.
  * [x] FEG helm
  * [ ] CWAG helm
  * [x] CWAG VM

In all cases, make sure to replace all links to the old Artifactory in the repo before starting a test.

Hint: To get a new base image, you can start vagrant of the magma-dev VM based on a plain Ubuntu image and run preburn and full-provision steps.

**Comment by jheidbrink** [comment]
I verified that building AGW docker images and running `agw_install_ubuntu.sh` both work using the LF artifactory. Code resides at https://github.com/jheidbrink/magma/commits/test_agwc_artifactory_switch. I didn't run an integration test but verified that the logs look good.
