### ISSUE TITLE
Format messages to CI Slack channel properly and sensibly

### ISSUE THREAD

**Issue by mpfirrmann** [magma/magma#14284]
The messages for i.e failing integration tests are formatted as:

`LTE integration test test failed on [${{ github.sha }}](${{github.event.repository.owner.html_url}}/magma/commit/${{ github.sha }}): ${{ steps.commit.outputs.title}}`

- While I assume, this is Markdown syntax for a link, that is not how [Slack formatting](https://api.slack.com/reference/surfaces/formatting#linking-urls) works
- The `steps.commit.outputs.title` is usually empty. Should this be the commit message? While this works i.e. for the `build-all` messages in Slack, we might be more successful using `github.event.head_commit.message`

**Comment by Neudrino** [comment]
I guess we can include this in https://github.com/magma/magma/issues/14283.
