### ISSUE TITLE
CI failing in Netlify 

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#14285]
### Your Environment

- **Version:** all
- **Affected Component:** all
- **Deployment Environment:** all

### Describe the Issue

Github Actions using Netlify are failing. 

#### To Reproduce

1. Make a change to documentation
2. Submit a PR
3. Review build log

#### Expected behavior

What should be happening is a clean build, since there is no error in the underlying PR.

#### Screenshots

<img width="636" alt="image (2)" src="https://user-images.githubusercontent.com/111581/198076484-48d0abc3-e500-4e99-a04a-f98cafb4ca4a.png">

<img width="552" alt="image (1)" src="https://user-images.githubusercontent.com/111581/198076509-eac99ab4-2893-4dbd-9b87-f363586b4178.png">

#### Additional context

For a log of one such failure see 
https://app.netlify.com/sites/competent-euler-513227/deploys/63518a3caae415000800ce62

This was discussed in Slack: https://magmacore.slack.com/archives/C01AWMH0EJW/p1666288811153539

**Comment by Neudrino** [comment]
Last successful run: https://app.netlify.com/sites/competent-euler-513227/deploys/634d1471f3bbee00098aabbf

**Comment by Neudrino** [comment]
Analysis of current state of DocuSaurus deployments and infrastructure was done. It was documented at https://github.com/magma/magma/wiki/Documentation-Infrastructure-for-DocuSaurus.

**Comment by Neudrino** [comment]
https://docs.magmacore.org/ now points to the DocuSaurus at https://magma.github.io/magma/ which is deployable and up to date. **Netlify** is no longer used by the project for DocuSaurus.
