### ISSUE TITLE
Flaky integration tests are identified and executed separetely

### ISSUE THREAD

**Issue by nstng** [magma/magma#14293]
In order to handle the currently (very) flaky behavior of the integration tests one approach could be to separate the usual flaky tests into a separate run and handle them then issue by issue.

### suggestions for requirements

* in the lte make debian workflow separate the flaky tests into a second workflow with the goal to fix the flaky tests and move them one by one over to the non-flaky workflow

**Comment by Neudrino** [comment]
The following issues and pull requests might be overlapping:
- https://github.com/magma/magma/pull/13766
- https://github.com/magma/magma/issues/14124
- https://github.com/magma/magma/issues/14293

**Comment by nstng** [comment]
It was decided to keep all tests in the workflow and fix them step by step - issue is outdated
