### ISSUE TITLE
the documentation is switched over - PART I

### ISSUE THREAD

**Issue by nstng** [magma/magma#14306]
#### requirements
* feel free to do this in small commits and do regular team discussions after the stand-up
* based on #14025 change as much documentation as possible to the bazel way
* if something is not yet possible with bazel, then discuss with team and create appropriate follow-up issues

TimeBoxed: max 3 person days until PARTI is merged and PART II is created

**Comment by jheidbrink** [comment]
Note that we also have documentation living in the Wiki
