### ISSUE TITLE
agw-workflow does not run parts that are already covered by bazel

### ISSUE THREAD

**Issue by nstng** [magma/magma#14300]
#### requirements
* [x] remove jobs that are already covered by bazel - check if they actually are completely covered
* [x] adapt path filter if appropriate
* [x] candidates:
  * [x] te-test
  * [x] li_agent_test
  * [x] mme_test
  * [x] session_manager_test
  * more?
* [x] remove make targets if they are not used anymore
* [x] if the remaining jobs in the workflow are not fitting to the name agw-workflow anymore, then create a follow-up issue to rename the workflow
* [x] check if removed jobs are required - coordinate with max to adapt this if necessary
* [x] adapt documentation where removed make targets are mentioned (or even the agw-workflow)
* [x] Should be seen as one issue but can be separated in multiple PRs, e.g., remove jobs, remove make targets, adapt documentation
* [x] Announce in Slack

**Comment by LKreutzer** [comment]
See https://stackoverflow.com/questions/48754619/what-are-cmake-build-type-debug-release-relwithdebinfo-and-minsizerel for relevant CMake build types

**Comment by LKreutzer** [comment]
The AGW Lint & Test workflow does:
```
make test_sctpd BUILD_TYPE=Debug
make test_sctpd BUILD_TYPE=RelWithDebInfo
make test_oai BUILD_TYPE=Debug
make test_oai BUILD_TYPE=RelWithDebInfo
make -C ${{ env.MAGMA_ROOT }}/lte/gateway/python test_all
make test_li_agent
make test_session_manager
```
all of which should be covered by the bazel workflow. Only the linters remain,

**Comment by LKreutzer** [comment]
Can remove

- lte-test
- li_agent_test
- mme_test
- session_manager_test

**Comment by LKreutzer** [comment]
That seems to imply that the devcontainer is not used in CI anymore?

**Comment by LKreutzer** [comment]
See also https://github.com/magma/magma/wiki/Bazel-vs.-Make-commands-dictionary

**Comment by LKreutzer** [comment]
Issue: How to deal with .github/workflows/unit-test-workflow.yml ?

**Comment by LKreutzer** [comment]
Difficult to update text on xml reports in docs/readmes/lte/dev_notes.md

**Comment by LKreutzer** [comment]
- [ ] #14320
- [ ] #14321
- [ ] #14322
