### ISSUE TITLE
Update python protobuf to latest 3.20 version

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14314]
Protobuf has released a new 3.20 patch to handle some security issues.
https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf

While this was already noticed by [dependabot](https://github.com/magma/magma/pull/14010), it's unfortunately a bit more difficult to merge this:
* Also update the dependencies within Bazel (requirements.in, requirements.txt).
* Make sure pydep uses the upgrade (look at the lockfile).
* Run debian integration tests.

Tasks:
* [x] Update protobuf dependency to latest 3.20.x version in setup.py, requirements.in, requirements.txt
* [x] Build a Magma debian release and make sure that pydep actually uses the new version.
* [x] Run debian integration tests.
* [x] Monitor the CI for build issues after merging.
* [x] Prepare internal review meeting.

**Comment by mpfirrmann** [comment]
I'm having trouble creating the `requirements.txt` (even without any changes to the protobuf version). What am I missing here?

```shell
$ pip-compile --allow-unsafe --generate-hashes --output-file=requirements.txt requirements.in
ERROR: Could not find a version that satisfies the requirement stevedore==4.0.0 (from oslo-config==8.8.0->-r requirements.in (line 45)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.7.1, 0.7.2, 0.8, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13, 0.14, 0.14.1, 0.15, 1.0.0.0a2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.18.0, 1.19.0, 1.19.1, 1.20.0, 1.20.1, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.27.0, 1.27.1, 1.28.0, 1.29.0, 1.30.0, 1.30.1, 1.31.0, 1.32.0, 2.0.0, 2.0.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.5.2)

```

**Comment by sebathomas** [comment]
It runs on my machine. Which pip-compile version did you install?

**Comment by mpfirrmann** [comment]
I deleted it and now it get`s recreated successfully from scratch :shrug:
