### ISSUE TITLE
loadtests vs make and bazel are executed and analyzed

### ISSUE THREAD

**Issue by nstng** [magma/magma#14416]
Idea:
* setup magma_deb with make and with bazel artifact - execute loadtests (with bazel)
* understand results - and maybe extend documentation (if helpful)
* compare results
* ask @LKreutzer for pointer to slack discussion during the 1.7 release load-testing
* create follow-up issues if there are issues found - like large performance differences

**Comment by vktng** [comment]
On bazel-built magma_deb running `bazel/scripts/run_load_tests.sh` gives error:
```
Running load test: loadtest_mobilityd allocate
Traceback (most recent call last):
  File "/home/vagrant/magma//bazel-bin/lte/gateway/python/load_tests/loadtest_mobilityd.runfiles/__main__/lte/gateway/python/load_tests/loadtest_mobilityd.py", line 220, in <module>
    main()
  File "/home/vagrant/magma//bazel-bin/lte/gateway/python/load_tests/loadtest_mobilityd.runfiles/__main__/lte/gateway/python/load_tests/loadtest_mobilityd.py", line 189, in main
    benchmark_grpc_request(
  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/load_tests/loadtest_mobilityd.runfiles/__main__/lte/gateway/python/load_tests/common.py", line 118, in benchmark_grpc_request
    subprocess.call(cmd_list)  # noqa: S603
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ghz'
```

**Comment by vktng** [comment]
Testing process for bazel:

1. Build the rpm on the magma VM with `bazel run //lte/gateway/release:release_build bazel run //lte/gateway/release:release_build`
2. Copy the rpm into `$MAGMA_ROOT`
3. `vagrant destroy magma_deb && vagrant up magma_deb`
4. `vagrant ssh magma_deb`
5. `cd $MAGMA_ROOT && bazel/scripts/run_load_tests.sh`

Testing process for make:

1. Build the rpm with `cd lte/gateway && fab release package:destroy_vm=True` (magma VM needs to be running)
2. Copy the rpm into `$MAGMA_ROOT`
3. `vagrant destroy magma_deb && vagrant up magma_deb`
4. `vagrant ssh magma_deb`
5. `cd $MAGMA_ROOT && bazel/scripts/run_load_tests.sh`

Dependencies:
The magma_deb VM is not ready to run the load_tests. `ghz` and `go` are missing for both cases and additionally you have install bazel for the make build too.

```
GHZ_REPO=https://github.com/bojand/ghz && \
cd /usr/local && \
GOLANG_VERSION="1.19.3" && \
GO_TARBALL="go${GOLANG_VERSION}.linux-amd64.tar.gz" && \
sudo curl https://linuxfoundation.jfrog.io/artifactory/magma-blob/${GO_TARBALL} --remote-name --location && \
sudo tar -xzf ${GO_TARBALL} && \
sudo ln -s /usr/local/go/bin/go /usr/local/bin/go && \
sudo rm ${GO_TARBALL} && \
cd $MAGMA_ROOT && \
git clone --depth 1 ${GHZ_REPO} && \
cd $MAGMA_ROOT/ghz && \
make build
```

```
cd /usr/sbin && \
sudo wget --progress=dot:giga https://github.com/bazelbuild/bazelisk/releases/download/v1.10.0/bazelisk-linux-amd64 && \
sudo chmod +x bazelisk-linux-amd64 && \
sudo ln -sf /usr/sbin/bazelisk-linux-amd64 /usr/sbin/bazel
```
