### ISSUE TITLE
MME crashes in handling Path Switch Request message during X2 Handover

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#1443]
### Your Environment

- **Version:** Local Development Setup
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Magma MME service
- **Deployment Environment:** Vagrant (AGW)

### Setup Details
The S1APTester (https://github.com/facebookexperimental/S1APTester) was used along with Magma EPC in Vagrant based setup to reproduce the issue.

### Describe the Issue

MME crashes for X2 Handover procedure during Path Switch Request message handling

**To Reproduce**
Run the test case test_x2_handover.py from S1APTester and see MME status after Path Switch Request message.

**Expected behavior**
The test case should pass and MME should not crash

**Additional context**
As per the analysis from backtrace, the crash is observed because of double free of memory. From code analysis it can be seen that during Path Switch Request message handling in S1ap, mme_ue_s1ap_id is removed  from the imsi_map->mme_ue_id_imsi_htbl two times leading to access of already freed pointer. Some of these changes have been added as part of feature enhancement with PR #1198

**Comment by ardzoht** [comment]
Hi @VinashakAnkitAman, thanks for creating this to track the crash, I have linked the PR that updates and fixes mme_ue_s1ap_id to IMSI behavior. Let's sync up to discuss this more in detail, thanks!
