### ISSUE TITLE
Add functionallity to retrieve remote gateway mac addresses

### ISSUE THREAD

**Issue by crasu** [magma/magma#14442]
# Summary

In #14355 we discovered that ebpf_manager needs the gateway ips to macs on the sgi interface. After changing to netifaces we can no longer retrieve remote macs via get_mac_address_from_ip4 as netifaces (afaik) does not send out arp pkts to retrieve those.

# Acceptance criteria

- [x] For IPv4, use the already existing code in pipelined to discover the address.
- [x] For IPv6, research if there is already an implementation of https://en.wikipedia.org/wiki/Neighbor_Discovery_Protocol in Python we could use.
- [x] Prepare internal review meeting.

# Discussion reference:
https://github.com/magma/magma/pull/14355#discussion_r1022619162

**Comment by wolfseb** [comment]
the function `get_gw_mac_address` in `gw_mac_address.py` does this already for IP4 addresses (at the moment it needs the egress interface name, which is `dhpc0` I believe), but not yet for IP6 addresses. Maybe that is a good starting point.
