### ISSUE TITLE
Virtual docker repos are configured for LF artifactory

### ISSUE THREAD

**Issue by nstng** [magma/magma#14497]
### State

* there is one virtual repo on the LF artifactory: https://linuxfoundation.jfrog.io/artifactory/magma-docker-test/ that covers
  * magma-docker-agw-prod
  * magma-docker-agw-test
  * magma-docker-cwag-prod
  * magma-docker-cwag-test
  * magma-docker-feg-prod
  * magma-docker-feg-test
  * magma-docker-orc8r-prod
  * magma-docker-orc8r-test 

### Expected State

* there are three virtual repos covering following repos - in brackets the magma core artifactory name for reference
  * magma-docker (docker)
    * magma-docker-agw-prod (agw-prod)
    * magma-docker-cwag-prod (cwf-prod)
    * magma-docker-feg-prod (feg-prod)
    * magma-docker-orc8r-prod (orc8r-prod)
  * magma-docker-ci (docker-ci) - **docker-ci is deprecated - not needed**
    * magma-docker-agw-ci (agw-ci)
      * this exists, but is empty
    * magma-docker-feg-ci (feg-ci)
      * this does not exist 
    * magma-docker-orc8r-ci (orc8r-ci)
      * this does not exist
    * magma-docker-cwag-ci (cwf-ci)
      * this does not exist
  * magma-docker-test (docker-test)
    * magma-docker-agw-test (agw-test)
    * magma-docker-cwag-test (cwf-test)
    * magma-docker-feg-test (feg-test)
    * magma-docker-orc8r-test (orc8r-test)

**Comment by fabiopalumbo** [comment]
Dear Team,

Created the `magma-docker-test` and `magma-docker`

We were requeste to only create prod and test repository, please review with @tmdzk also in the future create a ticket in support.linuxfoundation.org

If the ci repo are needed please advise.

**Comment by nstng** [comment]
done ny @fabiopalumbo
