### ISSUE TITLE
Create new VM base images

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14541]
Remove the workaround from #14514 and use the linuxfoundation artifactory directly in the preburn image.
- magma-dev
- magma-test

Also: use this issue to extend https://github.com/magma/magma/wiki/Creation,-Testing,-and-Publishing-of-Magma-VM-Base-Images with more details

**Comment by mpfirrmann** [comment]
This should also wait for #14415 to finish.

**Comment by mpfirrmann** [comment]
@jheidbrink, what would be best practice here? Don't we have to add certain 3rd party repos to install some packages?

**Comment by jheidbrink** [comment]
Also, for required 3rd party repos I see no use in removing them in the full provision step. So once we don't add any obsolete repositories in the preburn step, we shouldn't have to remove repositories in the full_provision step.
