### ISSUE TITLE
Create convenience alias targets in Bazel for services and other targets that are commonly used

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#14549]
See https://bazel.build/reference/be/general#alias

**Comment by jheidbrink** [comment]
It would be nice to have a single Bazel target that builds all AGW services

**Comment by vktng** [comment]
The potential solutions to build AGW with a simple command:

1. Bazel alias -> does not work, you can only alias 1 other target
2. Filegroup with the relevant targets -> hacky, has to be maintained.
3. --build_tag_filters -> uses tags that we already invested effort into, dynamic, no maintenance needed, but you will not remember it, has to be looked up

Option 3 was implemented, with additional bash aliases.
