### ISSUE TITLE
Memory leak when restoring UE contexts from database during MME restart

### ISSUE THREAD

**Issue by bhuvaneshne** [magma/magma#14542]
### Your Environment

- version 1.8.0
- AGW
- MME
- Bare-metal

### Describe the Issue

Below memory leaks are reported when restarting MME service.
![image](https://user-images.githubusercontent.com/97009526/203905943-131cb90f-8ab6-4aa2-9735-ebf1fa6707b7.png)

#### To Reproduce

1. Attach few UEs
2. Restart MME - UE contexts will be restored from database
3. Restart MME again after sometime - Just to get the reports of the leaks during "current run"

#### Expected behavior

Memory leaks should not be preset.

#### Additional context

This also restores context to a local variable instead of the proper destination - Which may result in the context not being fully restored during MME restart cases.

Need to investigate if https://github.com/magma/magma/issues/14205 is related.

PS: I also have fix for this. Will be raising a pull request soon.

**Comment by bhuvaneshne** [comment]
If the pull request gets approved, can this be ported back to 1.8?

**Comment by ajahl** [comment]
> If the pull request gets approved, can this be ported back to 1.8?

I think, it would be great if we could do that.
