### ISSUE TITLE
Try to download a prebuilt buildifier binary

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#14551]
Currently we build buildifier from source which takes a while and generates cache traffic (largely due to protobuf). Check if we can easily just download prebuilt binaries instead.

Might become obsolete with #13850

**Comment by LKreutzer** [comment]
Relevant page https://github.com/bazelbuild/buildtools/tree/master/buildifier

**Comment by LKreutzer** [comment]
- [ ] Handle clean up: remove integrated buildifier and all dependencies
