### ISSUE TITLE
Error on delete a Gateway Pool

### ISSUE THREAD

**Issue by paulocalaes** [magma/magma#14576]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Environment

- **Version: 1.8.0**
- **Affected Component:** Orchestrator and NMS
- **Deployment Environment:**  bare-metal 

### Describe the Issue

Trying to remove a Gateway Pool, return an errror: Request failed with status code 400. If check return from API is returning "{}".

#### To Reproduce

1. Go to 'nms/test/equipment/overview/pools'
2. Create a Gateway Pool 
3. Click to remove the Gateway Pool

#### Expected behavior

The expected behavior is to remove the gateway Pool

#### Screenshots

![image](https://user-images.githubusercontent.com/3208178/204588499-a78310fc-1250-4986-90ee-5a3793d3e69a.png)

**Comment by nstng** [comment]
Seems to work on current master. We will try to reproduce this on 1.8.

**Comment by nstng** [comment]
@paulocalaes it looks like the message `"Gateways %v still exist in pool %s. All gateways must first be removed from the pool before it can be deleted"` is not returned/displayed correctly.
We will have a look what might be the reason and either create a follow-up issue or fix it here.
