### ISSUE TITLE
Fixing Bufferbloat on these forms of wireless with cake middleboxes

### ISSUE THREAD

**Issue by dtaht** [magma/magma#14602]
### Problem

4G/5G benchmarks are perpetually showing 100s of ms of excess latency on uploads and downloads, even in good conditions. In poor conditions, 25seconds was measured recently on the linux kernel mailing list.

![rrul_-_bad_tx_aggr](https://user-images.githubusercontent.com/108682/205499465-c4d37f68-91d1-4aba-b930-b3c349853c90.png)

### Solution

Middlebox software like libreqos.io, preseem, and others, can now measure RTTs inband, and also apply flow queuing and AQM. Were some component in magma attempt to more closely match the buffering to the bandwidth, it would be a better world.  All libreqos's methods are open source so have at 'em!

Even better would be well controlled buffering and bandwidth at the handsets and e-node-bs (cake, fq_codel, etc), but it's possible to get to only +2ms with a middlebox alone...

![jack2](https://user-images.githubusercontent.com/108682/205499572-499c2e7a-902b-4233-91a2-ee25d6f617b5.png)

**Comment by dtaht** [comment]
Completed? Or did you give up, as I have?

**Comment by lucasgonze** [comment]
Sadly, not completed. Stale means an idea that never got done and has no reasonable expectation of getting done. By closing it when we recognize the reality and maybe help create energy to actually work on it in the future.
