### ISSUE TITLE
Artifactory certificate verification failed - During build

### ISSUE THREAD

**Issue by bhuvaneshne** [magma/magma#14604]
### Ubuntu 20.04 host + Virtualbox vagrant
- on tag v1.8.0
- AGW Build

### Describe the Issue

During build, the following errors are seen:

![image](https://user-images.githubusercontent.com/97009526/205560471-86b2e7e4-a69d-4bae-a220-bdc281de1443.png)

#### To Reproduce

Start build using fabric.

#### Expected behavior

Build should complete

#### Additional context

Build logs: attached.
[magmaBuildLogs.txt](https://github.com/magma/magma/files/10151030/magmaBuildLogs.txt)

**Comment by bhuvaneshne** [comment]
Could be related to this: https://github.com/magma/magma/issues/14495

**Comment by bhuvaneshne** [comment]
Closing this

**Comment by sebathomas** [comment]
Currently trying a backport of #14514, this might fix the issue.

**Comment by sebathomas** [comment]
@bhuvaneshne It should work again now on v1.8, please let us know if you still have issues.

**Comment by sebathomas** [comment]
@bhuvaneshne Are you sure you're on the latest version of the v1.8 branch? The step "Configuring the registry in sources.list.d" in your log is still trying to set the old artifactory, but on v1.8 it should use the new one:
https://github.com/magma/magma/blob/v1.8/orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml#L59

**Comment by bhuvaneshne** [comment]
Hi @sebathomas 
Confirming that the build succeeded on "v1.8"
Thank you!

**Comment by sebathomas** [comment]
Happy to hear that, thanks for confirming. :+1:
