### ISSUE TITLE
Vagrant AGW build failing in magma v1.8

### ISSUE THREAD

**Issue by sganiger1** [magma/magma#14603]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:**
v1.8
- **Affected Component:** Orchestrator, Access Gateway, or NMS
AGW(Access GateWay)
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
AGW build
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)
Vagrant build

### Describe the Issue

When a AGW build is triggered from vagrant VM with the command, "fab dev package", it is failing. Following is the snippet of the errors and failures from build logs. The "Error 1" is not consistent as it fails at different places in each build. Also note that it was working perfectly few days back.
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/87134057/205557377-f7f4f607-bb4c-44a3-9059-5214f31aae71.png">

#### To Reproduce
Triggering AGW build in vagrant VM with command, "fab dev package"

#### Expected behavior
No failure in builds.

#### Additional context

Add any other context about the problem here (e.g. logs).

**Comment by sebathomas** [comment]
This might be related to the artifactory switch, trying to backport some changes to v1.8 that might help.

**Comment by sebathomas** [comment]
@sganiger1  It should work again now on v1.8, please let us know if you still have issues.
