### ISSUE TITLE
Egress Tunnel Not Found

### ISSUE THREAD

**Issue by jao-tm** [magma/magma#14623]
### Your Environment

- **Version:** 1.8.0
- **Affected Component:** AGW
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** Bare-metal installation of AGW on Virtualbox VM, local Orc8r from magma-galaxy.  Tested with UERANSIM and OAI simulators.

### Describe the Issue

The UE does not have Internet access. The UE is given an IP address and the registration is successful, but ping (`ping 8.8.8.8 -I uesimtun0`) does not work. 

By following the Debugging steps (https://magma.github.io/magma/docs/howtos/troubleshooting/datapath_connectivity) I get to step number five. Using the `dp_probe_cli.py --imsi 99970 -d UL` command, the message `Egress Tunnel not Found` is returned and no packets are received using `gtp_br0 tcpdump -eni gtp_br0 host $UE_IP`. The UE is attached and appears when using `mobility_cli.py get_subscriber_table`, no errors appear at `ovs-vsctl show`, 

#### Expected behavior

The UE should have Internet access and the egress tunnel should be established.

#### Additional Information
`$ ovs-vsctl show
aefbf444-5f88-4c8d-b848-e49554329307
    Manager "ptcp:6640"
    Bridge uplink_br0
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port uplink_br0
            Interface uplink_br0
                type: internal
        Port dhcp0
            Interface dhcp0
                type: internal
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        fail_mode: secure
        Port proxy_port
            Interface proxy_port
        Port mtr0
            Interface mtr0
                type: internal
        Port gtp_br0
            Interface gtp_br0
                type: internal
        Port ipfix0
            Interface ipfix0
                type: internal
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port li_port
            Interface li_port
                type: internal
    ovs_version: "2.15.4"
`

**Comment by prabinakpattnaik** [comment]
If it is for 5G call setup then i assumed that the flag ```enable5gFeatures``` make as a true in gateway.mconfig under ```pipelined``` , ```sessiond``` , ```mme``` and ```subscriberd```.

Please check 2152 port is listening or not in AGW

**Comment by jao-tm** [comment]
The UERANSIM gNB connects to Magma, and the UERANSIM nr-ue attaches to the gNB and is assigned an IP address. The `enable5gFeatures` flag is true in parameters you mention.

nmap returns this:
PORT     STATE  SERVICE  VERSION
2152/tcp closed gtp-user

**Comment by prabinakpattnaik** [comment]
Please share the below output once PDU session established:
sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=12
sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=13

Capture the traffic in enodeb interface while doing ping.

**Comment by jao-tm** [comment]
Pcap shows that port 2152 is unreachable. Is this related to UERANSIM?


~# sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
 cookie=0x0, duration=17.679s, table=0, n_packets=0, n_bytes=0, priority=65503,tun_id=0x7fffffff,qfi=1,in_port=32768 actions=set_field:02:00:00:00:00:01->eth_src,set_field:ff:ff:ff:ff:ff:ff->eth_dst,set_field:0x1->reg9,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=LOCAL,nw_dst=192.168.128.12 actions=set_field:0x1->tun_id,set_field:10.40.90.10->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x1->qfi,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=mtr0,nw_dst=192.168.128.12 actions=set_field:0x1->tun_id,set_field:10.40.90.10->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x1->qfi,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=LOCAL,arp_tpa=192.168.128.12 actions=set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=mtr0,arp_tpa=192.168.128.12 actions=set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=7847.259s, table=0, n_packets=10, n_bytes=700, priority=10,in_port=ipfix0 actions=goto_table:201
 cookie=0x0, duration=7842.975s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=7842.975s, table=0, n_packets=10, n_bytes=700, priority=0,in_port="li_port" actions=resubmit(,202)
 cookie=0x0, duration=7842.975s, table=0, n_packets=32, n_bytes=2240, priority=0 actions=resubmit(,1)

# sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
 cookie=0x0, duration=17.679s, table=0, n_packets=0, n_bytes=0, priority=65503,tun_id=0x7fffffff,qfi=1,in_port=32768 actions=set_field:02:00:00:00:00:01->eth_src,set_field:ff:ff:ff:ff:ff:ff->eth_dst,set_field:0x1->reg9,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=LOCAL,nw_dst=192.168.128.12 actions=set_field:0x1->tun_id,set_field:10.40.90.10->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x1->qfi,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=mtr0,nw_dst=192.168.128.12 actions=set_field:0x1->tun_id,set_field:10.40.90.10->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x1->qfi,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=LOCAL,arp_tpa=192.168.128.12 actions=set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=17.656s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=mtr0,arp_tpa=192.168.128.12 actions=set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=7847.259s, table=0, n_packets=10, n_bytes=700, priority=10,in_port=ipfix0 actions=goto_table:201
 cookie=0x0, duration=7842.975s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=7842.975s, table=0, n_packets=10, n_bytes=700, priority=0,in_port="li_port" actions=resubmit(,202)
 cookie=0x0, duration=7842.975s, table=0, n_packets=32, n_bytes=2240, priority=0 actions=resubmit(,1)
root@agw-bm:~# sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=12
 cookie=0x1, duration=33.465s, table=12, n_packets=0, n_bytes=0, priority=65533,ip,reg1=0x1,metadata=0x1c69c719cab0d1,nw_src=192.168.128.12 actions=note:61.6c.6c.6f.77.6c.69.73.74.5f.73.69.64.2d.49.4d.53.49.39.39.39.37.30.30.34.30.30.30.30.32.35.38.36.2d.69.6e.74.65.72.6e.65.74.00.00.00.00,set_field:0x3->pkt_mark,set_field:0x1->reg2,set_field:0x1->reg4,set_field:0x7fffffff->reg11,resubmit(,13),resubmit(,20)
 cookie=0xfffffffffffffffe, duration=7857.667s, table=12, n_packets=19, n_bytes=1330, priority=0 actions=resubmit(,13),set_field:0->reg0,set_field:0->reg3

~# sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=13
 cookie=0x0, duration=59.992s, table=13, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x10,reg2=0x1,reg3=0,reg4=0x1,reg11=0x7fffffff,metadata=0x1c69c719cab0d1,nw_dst=192.168.128.12 actions=drop
 cookie=0x0, duration=59.992s, table=13, n_packets=0, n_bytes=0, priority=10,ip,reg1=0x1,reg2=0x1,reg3=0,reg4=0x1,reg11=0x7fffffff,metadata=0x1c69c719cab0d1,nw_src=192.168.128.12 actions=drop
 cookie=0x0, duration=59.989s, table=13, n_packets=0, n_bytes=0, priority=1,ip,reg1=0x10,reg2=0,reg4=0,reg11=0x7fffffff,metadata=0x1c69c719cab0d1,nw_dst=192.168.128.12 actions=drop
 cookie=0x0, duration=59.989s, table=13, n_packets=0, n_bytes=0, priority=1,ip,reg1=0x1,reg2=0,reg4=0,reg11=0x7fffffff,metadata=0x1c69c719
[egress-debug.zip](https://github.com/magma/magma/files/10218390/egress-debug.zip)
cab0d1,nw_src=192.168.128.12 actions=drop
 cookie=0xfffffffffffffffe, duration=7884.199s, table=13, n_packets=19, n_bytes=1330, priority=0 actions=drop

**Comment by prabinakpattnaik** [comment]
Looks like gtp0 port is not coming up as type ```gtpu``` in OVS setup.
Below part is missing:
```
        Port gtp0
            Interface gtp0
                type: gtpu
                options: {key=flow, remote_ip=flow}
```
Just verify the below content are present at ```/etc/network/interfaces.d/gtp``` 
# Add GTP vport to gtp_br0 as port 32768
allow-gtp_br0 gtp0
iface gtp0 inet manual
    ovs_bridge gtp_br0
    ovs_type OVSTunnel
    ovs_tunnel_type gtpu
    ovs_extra set interface ${IFACE} ofport_request=32768
    ovs_tunnel_options options:remote_ip=flow options:key=flow

Please restart the OVS or if AGW inside VM then please restart the VM.

**Comment by jao-tm** [comment]
The content are present at /etc/network/interfaces.d/gtp, and reboot doesn't help.

I've installed AGW on a second VM, and here port gtp0 is coming up as type gtpu in ovs-vsctl show. Port 2152 is then reachable, but same egress problem.

**Comment by prabinakpattnaik** [comment]
For second VM, need to change nat_interface in pipelined.yml file where default route is set for the interface.
For example, eth0 is default route interface then ping 8.8.8.8 -I eth0 should work in AGW then need to change in pipelined.yml file.

**Comment by jao-tm** [comment]
pipelined.yaml has nat_iface set to eth0. 

In AGW-host:
`# Interface to NAT traffic to
nat_iface: eth0

# Interface to eNodeB
enodeb_iface: eth1
`

`# ping 8.8.8.8 -I eth0
PING 8.8.8.8 (8.8.8.8) from 10.40.90.17 eth0: 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=53 time=15.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=53 time=14.8 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms`

**Comment by prabinakpattnaik** [comment]
So, please capture the traffic on eth0 and eth1 interfaces during sending the traffic.
At same time, take the output of below commands:
sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=12

**Comment by jao-tm** [comment]
```
sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
 cookie=0x0, duration=189.516s, table=0, n_packets=0, n_bytes=0, priority=65503,tun_id=0x80000001,qfi=1,in_port=gtp0 actions=set_field:02:00:00:00:00:01->eth_src,set_field:ff:ff:ff:ff:ff:ff->eth_dst,set_field:0x1->reg9,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=189.493s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=LOCAL,nw_dst=192.168.128.12 actions=set_field:0x1->tun_id,set_field:10.40.90.10->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x1->qfi,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=189.493s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=mtr0,nw_dst=192.168.128.12 actions=set_field:0x1->tun_id,set_field:10.40.90.10->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x1->qfi,set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=189.492s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=LOCAL,arp_tpa=192.168.128.12 actions=set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=189.492s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=mtr0,arp_tpa=192.168.128.12 actions=set_field:0x1c69c719cab0d1->metadata,resubmit(,1)
 cookie=0x0, duration=681.599s, table=0, n_packets=6, n_bytes=420, priority=10,in_port=ipfix0 actions=goto_table:201
 cookie=0x0, duration=681.438s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=681.438s, table=0, n_packets=6, n_bytes=420, priority=0,in_port="li_port" actions=resubmit(,202)
 cookie=0x0, duration=681.438s, table=0, n_packets=149, n_bytes=12264, priority=0 actions=resubmit(,1)
```
```
# sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=12
 cookie=0x1, duration=206.785s, table=12, n_packets=0, n_bytes=0, priority=65533,ip,reg1=0x1,metadata=0x1c69c719cab0d1,nw_src=192.168.128.12 actions=note:61.6c.6c.6f.77.6c.69.73.74.5f.73.69.64.2d.49.4d.53.49.39.39.39.37.30.30.34.30.30.30.30.32.35.38.36.2d.69.6e.74.65.72.6e.65.74.00.00.00.00,set_field:0x4->pkt_mark,set_field:0x1->reg2,set_field:0x1->reg4,set_field:0x80000001->reg11,resubmit(,13),resubmit(,20)
 cookie=0x1, duration=206.774s, table=12, n_packets=0, n_bytes=0, priority=65533,ip,reg1=0x10,metadata=0x1c69c719cab0d1,nw_dst=192.168.128.12 actions=note:61.6c.6c.6f.77.6c.69.73.74.5f.73.69.64.2d.49.4d.53.49.39.39.39.37.30.30.34.30.30.30.30.32.35.38.36.2d.69.6e.74.65.72.6e.65.74.00.00.00.00,set_field:0x2->pkt_mark,set_field:0x1->reg2,set_field:0x1->reg4,set_field:0x80000001->reg11,resubmit(,13),resubmit(,20)
 cookie=0xfffffffffffffffe, duration=696.616s, table=12, n_packets=160, n_bytes=13272, priority=0 actions=resubmit(,13),set_field:0->reg0,set_field:0->reg3
```

Filtered out SSH-traffic:
[eth0-eth1.zip](https://github.com/magma/magma/files/10225555/eth0-eth1.zip)

**Comment by prabinakpattnaik** [comment]
Could you please set the class_id value as 9 in APN configuration and restart the services.

**Comment by jao-tm** [comment]
That seemed to solve it.  Thank you!

**Comment by prabinakpattnaik** [comment]
Great...

**Comment by jao-tm** [comment]
Ping now works from UE, but `dp_probe_cli.py -i 999700400002586 -d UL` still returns "egress tunnel not found". What does this mean?

**Comment by prabinakpattnaik** [comment]
Please check whether IMSI value is correct or not.
tun_id and ue_ip parameters are mismatch with corresponding subscriber then getting that error.

In my setup, getting correct output like as below:
wavelabs@mars:~$ sudo dp_probe_cli.py -i 901700000000001 -d UL
IMSI: 901700000000001, IP: 192.168.131.182
UL stats: n_packets=2537303, n_bytes=3471030504
Running: sudo ovs-appctl ofproto/trace gtp_br0 tcp,in_port=3,tun_id=0x7fffffff,ip_dst=8.8.8.8,ip_src=192.168.131.182,tcp_src=3372,tcp_dst=80
Datapath Actions: drop
Uplink rules: allowlist_sid-IMSI901700000000001-internet

**Comment by jao-tm** [comment]
I can confirm that the IMSI value is correct, but `dp_probe_cli.py -i 999700400002586 -d UL` returns "egress tunnel not found". The command `dp_probe_cli.py -i 999700400002586 -d DL` returns 
```
IMSI: 999700000055808, IP: 192.168.190.37
Downlink rules: allowlist_sid-IMSI999700000055808-default
```
