### ISSUE TITLE
Proposal: cull four groups

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#14633]
### Problem

There are too many people with elevated security privileges. Over the history of the Magma project privileges have been granted but not taken away. As a result, there are a number of people no longer associated with Magma who still have access.

### Solution

We should remove the following groups:

- https://github.com/orgs/magma/teams/team-facebook (72 members)
- https://github.com/orgs/magma/teams/team-alten-calsoft-labs/ (12 members, 1 active on GitHub, none active in Magma)
- https://github.com/orgs/magma/teams/team-shoelacewireless (3 members, none active in Magma)
- https://github.com/orgs/magma/teams/magma-core-foundation (1 member, none active in Magma)

If it is possible to remove the permissions but keep the structure of these groups, that is better because it preserves information. If that is not possible, we should remove the groups at the org level.

### Non-goals

I don't propose to cull further in the short term. There are still too many people with write access, but the work to identify them has diminishing returns. Removing groups has the best ROI.

**Comment by maxhbr** [comment]
What does "remove" mean? Is that a "remove the group on magma org level" or "remove the permissions from the group, but keep the structure"?

**Comment by lucasgonze** [comment]
I hadn't considered the second option. I was thinking of this one:

> "remove the group on magma org level"

If it's possible to remove permissions but keep the structure, that would preserve information about past contributors that could be useful later.

**Comment by lucasgonze** [comment]
A counterargument to this proposal is that it is not complete enough. We should identify all dormant users.

**Comment by lucasgonze** [comment]
Verbal notice from @wendallkaters that this proposal has been approved.

**Comment by lucasgonze** [comment]
It is possible to remove permissions but keep structure, so I have changed the permissions for each of these groups from "write", "maintain" or "admin" to "read."
