### ISSUE TITLE
Bazel documentation is added to docusaurus as a separate overview page

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#14653]
Can be based on: https://github.com/magma/magma/issues/11917

Requirements:

- [x] Mention `.bazelrc` and explain the `--config`s.
- [x] Link to official bazel doc pages, e.g. for command line options.
- [x] Feature a section on `bazel help` as a generic way of finding help.
- [x] Where to find the bazel scripts and explain what they do.
- [x] Document some examples for useful bazel queries.
- [x] Testing documentation, what scripts to use, what test categories exist.
- [x] Troubleshooting documentation. 
- [x] Mention `bazel clean`.
- [x] How to add dependencies, for build files and external deps.

**Comment by LKreutzer** [comment]
- Set up basic structure
- Get feedback from team
- Fill in sections

**Comment by nstng** [comment]
TODO: add part about remote caches (how to re-activate). Here also possible security risk can be mentioned as to-be-solved (see below - closed for now as remote caches are currently disabled).
* https://github.com/magma/security/issues/108
* https://github.com/magma/security/issues/109

**Comment by LKreutzer** [comment]
Add section on visibility https://github.com/magma/magma/issues/12531#issuecomment-1365789917

**Comment by LKreutzer** [comment]
Deleted comment that contained private links to security repository. These links were added to the README file in the repository that they were concerned with.

**Comment by LKreutzer** [comment]
- [ ] Add section on remote caching and Docker bazel caches
