### ISSUE TITLE
Cannot import name 'arp'

### ISSUE THREAD

**Issue by mickymkumar** [magma/magma#14666]
Title: Failed import name 'arp' from 'dpkt'
Description: We unable to import 'arp' from dpkt
Version: 1.8.0-1670520973-20fc8649
Affected Component: Access Gateway
Screenshot:

![image.png](https://images.zenhubusercontent.com/61dfa6469da2e70f76e7e19f/ba0f4fcf-fe96-4970-b2c1-f76c10f32a13)

**Comment by micky-kumar** [comment]
update magma AGW

1) apt list --installed | grep magma (to check latest version)
2) sudo apt update
3) apt-cache madison magma (to update new version )
4) sudo apt-get install magma
5) sudo netstat | grep sctp
6) apt list --installed | grep magma

**Comment by micky-kumar** [comment]
update magma AGW

1) apt list --installed | grep magma (to check latest version)
2) sudo apt update
3) apt-cache madison magma (to update new version )
4) sudo apt-get install magma
5) sudo netstat | grep sctp
6) apt list --installed | grep magma
