### ISSUE TITLE
Redo #14454: replace deprecated GitHub action commands for `set-output`

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#14671]
- Redo https://github.com/magma/magma/pull/14454
  - Find and fix error that led to the build all workflow breaking.
  - See broken run https://github.com/magma/magma/actions/runs/3647099048
  - Fixed run after revert https://github.com/magma/magma/actions/runs/3649834411
- See also the revert PR https://github.com/magma/magma/pull/14657

Initial findings:
- In `.github/workflows/build_all.yml` in the `agw-build` failed in `Publish debian packages`.
- Only change here was
  - `echo "artifacts=$(echo $ARTIFACTS)" >> $GITHUB_OUTPUT` replaced by
  - `echo "artifacts=${ARTIFACTS}" >> $GITHUB_OUTPUT`
  - Difference might be the additional '\n' introduced by the `echo`(?).

**Comment by nstng** [comment]
The only part remaining from #14454 is changing `echo "artifacts=$(echo $ARTIFACTS)" >> $GITHUB_OUTPUT` to `echo "artifacts=${ARTIFACTS}" >> $GITHUB_OUTPUT`. I tested that this breaks the multiline value in `$ARTIFACTS`. I do not see another TODO here - the wrapped echo preserves the multiline value.
@LKreutzer if you see another action here, then please re-open the issue and provide a comment.
