### ISSUE TITLE
Add default values to "AGW Test LTE Integration With Make Containerized Build"

### ISSUE THREAD

**Issue by mpfirrmann** [magma/magma#14798]
For a [manual run of the test via "workflow_dispatch"](https://github.com/magma/magma/actions/workflows/lte-integ-test-containerized.yml) the user needs to enter the digest from the containers (agw_gateway_c, agw_gateway_python, and gateway_go) with which to run the test and the registry where to find them. These inputs are mandatory, however a default setting to the latest magma containers would be a great improvement in user experience.
At the moment one has to tediously get the information from the artifactory.

**Comment by nstng** [comment]
I only found a way to retrieve the digests when logged-in to the artifactory - this can be done by everybody, but needs special configuration if needed in fork CI. Small script to get the digests:
```
AUTH="X-JFrog-Art-Api:${1}"
ACCEPT="Accept: application/vnd.docker.distribution.manifest.v2+json"
TAG="latest"
ARTIFACTORY="http://linuxfoundation.jfrog.io/artifactory"

for image in agw_gateway_c agw_gateway_python gateway_go
do
  RES=$(curl --location --silent --head \
      "${ARTIFACTORY}/api/docker/magma-docker-test/v2/${image}/manifests/${TAG}" \
      -H "${AUTH}" -H "${ACCEPT}" \
    | grep -i docker-content-digest \
    | cut -d' ' -f2)
  echo $image: $RES
done

echo "linuxfoundation.jfrog.io/magma-docker-test"
```
An api token needs to be created on https://linuxfoundation.jfrog.io/ui/admin/artifactory/user_profile. Then call the script by
```
./agw_cont_digests.sh <API_TOKEN>
```
