### ISSUE TITLE
Chore: update groups to reflect transition

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#14800]
### Problem

As a result of the organizational transition in Jan 2023, a number of people who are no longer associated with the Magma project have excessive privileges. 

### Solution

Cull inactive members, e.g. Facebookers

- [x] https://github.com/orgs/magma/teams/repo-magma-maintain/members
- [x] https://github.com/orgs/magma/teams/repo-magma-website-write/members
- [x] https://github.com/orgs/magma/teams/repo-ci-infra-read/members
- [x] https://github.com/orgs/magma/teams/repo-ci-management-maintain/members
- [x] https://github.com/orgs/magma/teams/repo-domain-proxy-admin/members
- [x] https://github.com/orgs/magma/teams/repo-magma-admin/members

Change privileges from admin or write to read

- [x] Link: https://github.com/orgs/magma/teams/repo-augmented-networks
- [x] https://github.com/orgs/magma/teams/repo-teravm/repositories
- [x] https://github.com/orgs/magma/teams/repo-teravm-admin/repositories
- [x] https://github.com/orgs/magma/teams/team-freedomfi/repositories
- [x] https://github.com/orgs/magma/teams/team-radisys/repositories

Delete empty or otherwise broken groups

- [x] https://github.com/orgs/magma/teams/team-deutsche-telekom
- [x] https://github.com/orgs/magma/teams/repo-ci-testing

Investigate further

- [ ] Are there any active members from OIF? https://github.com/orgs/magma/teams/team-openinfrafoundation/repositories
- [ ] OSPOCO has write on Magma and Read on Security. I think these should both be Read, but my personal account should be Write on Security. 
- [ ] Are there inactive members from TNG who could be culled? https://github.com/orgs/magma/teams/team-tng/members
- [ ] Are there inactive members from Wavelabs who could be culled? https://github.com/orgs/magma/teams/team-wavelabs/members

**Comment by lucasgonze** [comment]
Most of the work to be done here is pretty clear, but not all. The following is a list of people who might want to ask to be re-added. (I am @ mentioning them so they can find this issue).

- @taaraora

**Comment by lucasgonze** [comment]
We should delete these teams, but I'm not seeing an admin feature to do that. Maybe I don't have the right privilege level. @wendallkaters, do you see a feature to delete the group?

- https://github.com/orgs/magma/teams/team-deutsche-telekom
- https://github.com/orgs/magma/teams/repo-ci-testing

**Comment by wendallkaters** [comment]
@lucasgonze - apologies for the delay on this. I have deleted those teams

**Comment by lucasgonze** [comment]
I culled all the remaining stale memberships.
