### ISSUE TITLE
Codeowner Groups are Simplified

### ISSUE THREAD

**Issue by nstng** [magma/magma#14822]
This issue tracks the implementation of a simplified codeowner structure based on the accepted proposal #14761.

#### Proposed Implementation

Create new codeowner groups and add users from respective legacy groups. Make needed code changes. Keep the legacy groups (maybe there is a function to mark them as deprecated - or at least some way to reflect this in the description of the groups). We should keep the legacy groups for some time in order to have a valid setup for older release branches.
Also `approvers-ci` should remain for now and is not deprecated. This group is used in CI as a guard for executing manual workflows to publish artifacts - the description of the group should reflect this.

##### Create new groups and add members

Create the groups on the first level and add users from the groups on the second level.

* @magma/approvers-infra
  * @magma/approvers-ci
  * @magma/approvers-agw-integtests
  * @magma/approvers-agw-containers
  * @magma/approvers-docs
  * @magma/approvers-bazel

* @magma/approvers-cloud
  * @magma/approvers-orc8r
  * @magma/approvers-nms
  * @magma/approvers-domain-proxy

* @magma/approvers-gw
  * @magma/approvers-feg
  * @magma/approvers-cwf
  * @magma/approvers-agw
  * @magma/approvers-agw-mme
  * @magma/approvers-agw-pipelined

- [x] new groups are created
- [x] members from legacy groups are added
- [x] legacy groups reflect their status (flag or group description) - see exception for `approvers-ci` above
- [x] slack channels reflect the new structure

##### Docs changes

- [x]  update places on https://github.com/magma/magma/wiki

##### Code changes

- [x] see PR  #14823 - should be merged after new groups are created

**Comment by nstng** [comment]
Hi @wendallkaters, I added you for the configuration of the new codeowner groups - are you the correct contact person?

**Comment by wendallkaters** [comment]
> Hi @wendallkaters, I added you for the configuration of the new codeowner groups - are you the correct contact person?

Yes, I am the correct person!

**Comment by wendallkaters** [comment]
I will work on this and have it completed by EOD on Wednesday, Jan 11

**Comment by wendallkaters** [comment]
@nstng - new groups have been created and I have added in the respective people to said groups. I am not sure if each of the groups have the correct permissions so you may need to double check that. At an upcoming TSC meeting, we should encourage the groups to go through the members list and vote to remove any inactive members bc as I was adding members, I believe there are quite a few that will need to be removed.

**Comment by nstng** [comment]
@wendallkaters 

> new groups have been created and I have added in the respective people to said groups.

Thank you, I will have a look.

> I am not sure if each of the groups have the correct permissions so you may need to double check that.

What permissions are you referring to? I do not see any permissions listed on the subpages of https://github.com/orgs/magma/teams/repo-magma-maintain/teams - do I have sufficient permissions to see such settings?

> At an upcoming TSC meeting, we should encourage the groups to go through the members list and vote to remove any inactive members bc as I was adding members, I believe there are quite a few that will need to be removed.

I agree - I will add Shrutis proposal https://github.com/magma/magma/issues/14208 to the agenda for presentation/discussion/voting.

**Comment by nstng** [comment]
@wendallkaters review of composition of groups lgtm - I noticed that you added yourself to the three new groups - was this intentionally? Imo, you would be selected for reviews by that.

**Comment by wendallkaters** [comment]
@nstng - that was unintentional. Github must have automatically added me when I created the groups. I will remove myself. Thank you for flagging!

**Comment by LKreutzer** [comment]
Changes to the Wiki page https://github.com/magma/magma/wiki/Contributing-Code/ lgtm!

As a side note: On this page there are individual devs named as owners for some checks, e.g. mergefreeze, Shellcheck by Reviewdog, etc. I think it would be great if we could find groups that could own these as the contacts might get outdated rather quickly and many of the devs named there are not at Magma anymore. Opinions?

**Comment by nstng** [comment]
> As a side note: On this page there are individual devs named as owners for some checks, e.g. mergefreeze, Shellcheck by Reviewdog, etc. I think it would be great if we could find groups that could own these as the contacts might get outdated rather quickly and many of the devs named there are not at Magma anymore. Opinions?

I see this covered by #14324.
