### ISSUE TITLE
AGW: MME is getting restarted as it is accessing the freed heap pointer in clean_stale_enb_state()

### ISSUE THREAD

**Issue by sganiger1** [magma/magma#14865]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:**
- magma v1.8
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- Access Gateway
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- MME
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)
- vmWare AGW

### Describe the Issue
MME is trying to access the heap pointer that is freed. The accessing MME function is clean_stale_enb_state() and the freeing function is s1ap_remove_ue(), which is called by accessing function, clean_stale_enb_state(). Following is the snip of the same.
**Accessing thread: T21**
<img width="1790" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/87134057/213432222-3fee12eb-c68e-4a7a-8338-1a0eacd1fb28.png">

**Code: While ++itr_map at line #434**
<img width="1011" alt="Pasted Graphic 8" src="https://user-images.githubusercontent.com/87134057/213432265-72b9f7b4-0d6f-493b-aba2-8054817f4f6e.png">

**FREEING Thread: Same as the accessing thread T21**
<img width="1790" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/87134057/213432456-977082bb-dce9-46eb-b0f5-13b7affac52b.png">

**Code: At line #465 of s1ap_remove_ue() the memory is freed**
<img width="1011" alt="Pasted Graphic 9" src="https://user-images.githubusercontent.com/87134057/213432543-c2d2fb72-4a95-44f6-9d6b-29cc26f91919.png">

#### Additional context

Add any other context about the problem here (e.g. logs).

**Comment by shashidhar-patil** [comment]
Hi @sganiger1, 
1. Does this issue still persist?
2. Can you please share the entire log files?
3. Can you also describe the scenario to reproduce this, if any?

Can you provide the following information, it'll help us to narrow down the issue.

**Comment by Sujay-Radtonics** [comment]
Hello @shashidhar-patil ,  We were hitting this issue when there were frequent power problems with customer. Now, they have not reported it.  However, I have mme and syslog from previous occurrences (2 times). I have attached here. 
[crash.zip](https://github.com/magma/magma/files/12928253/crash.zip)

Jun 14 11:29:59  in syslog.1 and MME.terdbn-vagw-01.root.log.INFO.20230612-102433.2209812
Jun 15 08:06:34 in syslog and MME.terdbn-vagw-01.root.log.INFO.20230614-113043.2401388

You should be able to hit the issue very consistently if you can create the scenario of stale_enb. (by hacking code probably).

**Comment by shashidhar-patil** [comment]
Hi, we created the stale_enb scenario and tested it with simulators. This issue doesn't persist on the latest magma master.

Attached logs and pcap: [14865.zip](https://github.com/magma/magma/files/13276320/14865.zip)

**Comment by sganiger1** [comment]
@shashidhar-patil 
We are not seeing this issue. You can check with @Sujay-Radtonics and take the appropriate next step.

**Comment by panyogesh** [comment]
@Sujay-Radtonics : We are planning to close the issue this week. Hope it should be  fine. If the issue persist we can create a new issue.

**Comment by panyogesh** [comment]
Closing the ticket assuming all is going well.
