### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by voisey** [magma/magma#14924]
See "Releasing" section of https://wiki.magmacore.org/display/HOME/Knowledge+to+Handover for an overview.

**Comment by nstng** [comment]
# Technical Release Process

:warning:  This documentation is loosely based on 1.8.0 release. After 1.8.0 the Magma artifactory was switched. This Included a more restrictive publishing of artifacts - only CI workflows can do this now. This is, some parts might need to be adapted or extended for the next releases or in general should be automated for future releases. Please update this documentation accordingly.

At some point the community decided that a release is planned. Usually the master needs to be brought in a release state, e.g., some features need to be finished, bugs need fixing, etc. Now the release can start.

The general idea is, to create release branch, publish all relevant artifacts to the artifactory test repositories, test the artifacts and eventually promote them to production repositories.

## Crate release branch

<details>
<summary>Open</summary>
test
</details>

## Create third party artifacts

<details>
<summary>Open</summary>
test
</details>

## PR on release branch vs back porting

<details>
<summary>Open</summary>
test
</details>

## Change endpoints

<details>
<summary>Open</summary>
test
</details>

## Verify artifacts

<details>
<summary>Open</summary>
test
</details>

## Testing

<details>
<summary>Open</summary>
test
</details>

## Release

<details>
<summary>Open</summary>
test
</details>

## Post steps

<details>
<summary>Open</summary>
test
</details>

## Hot fixes vs back porting

<details>
<summary>Open</summary>
test
</details>

**Comment by nstng** [comment]
published to https://github.com/magma/magma/wiki/Releases
