### ISSUE TITLE
Follow up tasks for `make check` and the precommit script

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [magma/magma#14932]
Following up on #14738 @nstng made some suggestions

- Use the latest tag for the `ghcr.io/magma/magma/python-precommit` github image in `precommit.py` (already done in [#14994](https://github.com/magma/magma/pull/14994))
- Investigate using `make check` in `.github/workflows/python-workflow.yml` in `Format and check for leftover changes` as there is a comment that claims that this step is identical to `make check`.

**Comment by mpfirrmann** [comment]
@wolfseb, is this covered by your current cleanup efforts?

**Comment by wolfseb** [comment]
* The first point is already implemented.
* The second point is probably not feasible without introducing more complexity, the commands differ in that the local `make check` is set to not fail no matter what the return code is. In the CI that is exactly what we don't want.
