### ISSUE TITLE
Handle docs that aren't displayed in the sidebar

### ISSUE THREAD

**Issue by voisey** [magma/magma#14958]
There are quite a few docs pages that exist in `docs/readmes/` but aren't included in `docs/docusaurus/sidebars.json` and so don't appear in [the documentation](https://magma.github.io/magma/docs/next/basics/introduction.html). We should go through these one by one, work out whether there's a reason each one isn't included (e.g. is the information covered elsewhere?), and either include the page in the sidebars or delete the file (with the exception of the proposals, which shouldn't be deleted). We could also include a check in the CI that all docs are included in the sidebars.

The docs that aren't displayed are:

- [x] cwf/deploy_intro.md https://github.com/magma/magma/pull/15018
- [x] cwf/deploy_install.md https://github.com/magma/magma/pull/15018
- [x] cwf/deploy_build.md https://github.com/magma/magma/pull/15018
- [x] cwf/healthchecker.md https://github.com/magma/magma/pull/15018
- [x] nms/deploy_setup.md https://github.com/magma/magma/pull/14964
- [x] feg/docker.md https://github.com/magma/magma/pull/15017
- [x] lte/readme_callflow.md https://github.com/magma/magma/pull/15108
- [x] lte/setup_baremetal.md https://github.com/magma/magma/pull/15102
- [x] lte/pipelined_tests.md https://github.com/magma/magma/pull/15078
- [x] lte/readme_agw.md https://github.com/magma/magma/pull/15078
- [x] lte/hil_tests.md https://github.com/magma/magma/pull/15107
- [x] lte/redirectd.md https://github.com/magma/magma/pull/15078
- [ ] proposals/p021_mme_migrate_to_c++.md
- [ ] proposals/p019_esim_mgmt_integration.md
- [ ] proposals/p006_subscriber_state_view.md
- [x] proposals/p004_fua-restrict-feature.md https://github.com/magma/magma/pull/14979
- [ ] proposals/p010_vendor_neutral_dp.md
- [ ] proposals/p011_intra_agw_mobility.md
- [ ] proposals/p008_mandatory_integration_tests_for_each_PR.md
- [ ] proposals/p008_inbound_roaming_with_subscriberdb.md
- [x] howtos/package.md https://github.com/magma/magma/pull/15097
- [ ] proposals/p024_magma_settlement_service.md
- [ ] proposals/p026_magma_inbound_roaming_extensions.md
- [ ] proposals/p022_enodebd_enhancements.md
- [ ] proposals/p025_magma_cdr_availability.md
- [ ] proposals/p012_resource-tagging.md
- [ ] proposals/qos_enforcement.md
- [ ] proposals/p023_magma_gtp_gateway.md
- [x] proposals/p016_nms_regression_testing.md https://github.com/magma/magma/pull/14979/files

**Comment by LKreutzer** [comment]
The ci job should go into the `.github/workflows/docs-workflow.yml` workflow.

**Comment by voisey** [comment]
Closing as it is unclear to me whether some of the design documents in the proposals folder are intentionally not included in the sidebar. A follow-up can be found in https://github.com/magma/magma/issues/15145.
