### ISSUE TITLE
using 3'ed party static library for build

### ISSUE THREAD

**Issue by 0x34d** [magma/magma#14982]
`Bazel` build system is detecting `static libraries`.

EDIT: The Thing is complete.

**Comment by 0x34d** [comment]
Is it really important to use `oai-nettle oai-gnutls oai-freediameter` for 

```
libfdcore.so.6
libfdproto.so.6
libgnutls.so.28
libnettle.so.4
libhogweed.so.2
```
why can't  I use default system libs?

**Comment by nstng** [comment]
Hi @0x34d, after a quick look into the code:
* `oai-freediameter` is patched
* `oai-nettle` uses a couple of config options - they might not be default.

See build scripts in `third_party/build/bin` for details.

Feel free to give more context, what you want to achieve. E.g., Why are static libraries problematic in you use case? Why would you prefer to use the default system libraries? What is the general goal you have in mind?

**Comment by 0x34d** [comment]
context: https://github.com/google/oss-fuzz/pull/9635#discussion_r1101551889

**Comment by 0x34d** [comment]
Long live bloat.
