### ISSUE TITLE
Add documentation about using new VM base images

### ISSUE THREAD

**Issue by voisey** [magma/magma#15008]
As part of the knowledge transfer work documented at https://wiki.magmacore.org/display/HOME/Knowledge+to+Handover, it would be good to add a brief explanation to the bottom of https://github.com/magma/magma/wiki/Creating,-Testing,-and-Publishing-Magma-VM-Base-Images about how to use newly created VM base images. That is, that one can destroy their local VMs and provision fresh ones by checking out master, as described [in Slack](https://magmacore.slack.com/archives/C018J8UMGMR/p1675071035259919).

**Comment by mpfirrmann** [comment]
Did you think about something like this?

## 8. Use new VM base images
After the changes in the Ansible files, Vagrantfiles, and box-caches and merge the commit to the local master branch, the virtual machines need to be built fresh from scratch. This means to destroy the VMs built with the old image and afterwards provision them again with `vagrant up`. By doing so, the new base images are downloaded and all updated Ansible roles will be applied to this image. This ensures an up-to-date system for development and testing.

```
HOST [magma/lte/gateway]$ vagrant destroy         # destroys all AGW VMs
HOST [magma/lte/gateway]$ vagrant up $VM_NAME     # build the VM with new base image
```

:warning: Destroying the VMs also removes any changes which are not part of the magma directory. If there is any important work on these machines, transfer it for example onto a local machine before destroying them.

**Comment by voisey** [comment]
Thanks @mpfirrmann, looks good! I've just integrated it with the docs at https://github.com/magma/magma/wiki/Creating,-Testing,-and-Publishing-Magma-VM-Base-Images#7-use-new-vm-base-images-locally. I made a couple of small changes including making this step 7 rather than 8 - you can see the diff here https://github.com/magma/magma/wiki/Creating,-Testing,-and-Publishing-Magma-VM-Base-Images/_compare/5f9a777d72476ba4abefd26d97e0615f60bec96d...ad1efae8657ee55d61317573920c18433ccb9603.
