### ISSUE TITLE
Consider merging magma/scripts and magma/dev_tools

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [magma/magma#15036]
In the magma root directory, there are two folders with a collection of scripts, magma/dev_tools and magma/scripts.

- Analyze the contents
- Consider merging these into a single folder
  - Decide which folder is preferable to keep. Likely dev_tools if it's descriptive of all the contents.
  - Make sure to adapt any external calls to these scripts.
- Communicate the change with the community

**Comment by lucasgonze** [comment]
This is stale, but I think it is a good candidate for @mickymkumar's folder refactoring project.

**Comment by lucasgonze** [comment]
Closing by TSC consensus 6/17/2024
