### ISSUE TITLE
Modify GitHub workflows to run on release branches

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#15031]
Currently most workflows also run on `push` triggers to `1.*` branches, however this is not true for all workflows.

- Workflows where this is missing should be modified to add this trigger.
- It needs to be checked that all `if:` conditions that check for the branch name `master` are updated as well.

**Comment by mpfirrmann** [comment]
Affected workflow files:

- [ ] `/workflows/bazel.yml`
- [ ] `/workflows/docker-builder-devcontainer.yml`
- [ ] `/workflows/docker-builder-python-precommit.yml`
- [ ] `/workflows/docs-workflow.yml`
- [ ] `/workflows/docusaurus-workflow.yml`
- [ ] `/workflows/sudo-python-tests.yml`
