### ISSUE TITLE
Add more detailed description to listed issues

### ISSUE THREAD

**Issue by wolfseb** [magma/magma#15047]
Several issues might be hard to understand due to a lack of detail in the description, a lack of a description of the goal, or just having an outdated description. Below is a collection of issues that would benefit from updating their description.

**Comment by mpfirrmann** [comment]
- [ ] #14359
- [ ] #12755
- [ ] #14318
- [ ] #13364
- [ ] #13915 
- [ ] #14624 
- [ ] #14396
- [ ] #3471
- [ ] #14933
