### ISSUE TITLE
Update GitHub-to-Slack mapping

### ISSUE THREAD

**Issue by voisey** [magma/magma#15071]
The table that maps GitHub IDs to email addresses and Slack names is outdated. As a follow-up to https://github.com/magma/magma/pull/15037, it should be updated or replaced by a more easily maintained solution. Note that the table is referenced in the [Code Review Process](https://github.com/magma/magma/wiki/Contributing-Code#code-review-process) section of the wiki.

**Comment by mpfirrmann** [comment]
See the table here: [GitHub-to-Slack mapping](https://github.com/magma/magma/wiki/Overview-of-the-Community-Structure-and-Governance#codeowners)
