### ISSUE TITLE
Fix broken links in `docs/`

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [magma/magma#15121]
Using a script I have identified the URLs below within the `docs/` directory which are unreachable or return status 404:

- [ ] Check if these URLs a genuinely unreachable and actually refer to resources on the internet
- [ ] If the link is in docs before v1.7, only fix if is very easy to do.
- [ ] If the link is in 1.7 or newer, figure out where it should be pointing and replace it.

You can use this script to check for URLs yourself: https://gist.github.com/MoritzThomasHuebner/442d977ef6c2b9ddf448e1eba44acd56
However, you will need double check the returned URLs manually since string formatting sometimes cuts out parts of URLs.

External:
http://app.kubernetes.io/component=alertmanager
http://app.kubernetes.io/component=alertmanager-configurer

http://automation.fbmagma.ninja/

https://black.readthedocs.io/en/stable/installation_and_usage.html

http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/sanity/hilsanitypass.svg

https://victoriametrics.github.io/Single-server-VictoriaMetrics#how-to-import-data-in-prometheus-exposition-format
https://victoriametrics.github.io/vmalert.html
https://victoriametrics.github.io/Single-server-VictoriaMetrics#how-to-scrape-prometheus-exporters-such-as-node-exporter
https://victoriametrics.github.io/Cluster-VictoriaMetrics
https://victoriametrics.github.io/CaseStudies.html

https://wemake-python-stylegui.de/en/latest/

https://thanos.io/storage.md/

Magma-related:
https://artifactory.magmacore.org/
https://artifactory.magmacore.org/artifactory/helm/
https://artifactory.magmacore.org/artifactory/helm-test/

https://docs.magmacore.org/docs/next/contributing/contribute_conventions

https://github.com/facebookincubator/magma/blob/master/docs/Magma_Specs_V1.1.pdf
https://github.com/facebookincubator/magma/blob/master/docs/Magma_Network_Management_System.pdf
https://github.com/fbcinternal/ens_magma/tree/master/spirent_automation
https://github.com/magma/ci-infra/blob/master/bazel/remote_caching/Readme.md
https://github.com/magma/magma/blob/master/.circleci/config.yml
https://github.com/magma/magma/blob/master/lte/gateway/c/oai/tasks/nas/emm/msg/AttachRequest.c
https://github.com/magma/magma/blob/master/orc8r/cloud/go/services/orchestrator/servicers/exporter_servicer.go

https://magma.github.io/magma/docs/orc8r/rds_upgrade#logs-and-validation
https:///magma.github.io/magma/docs/feg/deploy_intro
https://magma.github.io/magma/docs/next/orc8r/development/testing_tips
https:///magma.github.io/magma/docs/orc8r/architecture_overview

https://raw.githubusercontent.com/magma/magma/master/lte/gateway/deploy/agw_install.sh

**Comment by lucasgonze** [comment]
This is a good idea.
