### ISSUE TITLE
Report successful AGW build to `magma-ci.web.app`

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#15161]
- The `AGW` build entry on `https://magma-ci.web.app/` is empty. The Make job that provides this information was removed in https://github.com/magma/magma/pull/15144. 
![Screenshot from 2023-03-27 10-19-52](https://user-images.githubusercontent.com/34488763/227883235-e2352ba6-1348-4bd7-b2ee-2a4d3a5129e7.png)

- To provide this information the `Bazel package job` in the `bazel.yml` workflow needs to be updated to provide the relevant information.
  - https://github.com/magma/magma/pull/15144/files#diff-71a71e993dac5ebcaa1ad57402f04ee226b14121a8052e4f994706670fd65a1a can be used as a starting point on what information is needed. 

Related to:
- https://github.com/magma/magma/issues/15159
- https://github.com/magma/magma/pull/15158

**Comment by lucasgonze** [comment]
This is a blocker for https://github.com/magma/magma/pull/15172. When it is fixed, revisit that.

**Comment by lucasgonze** [comment]
See PR 15214

**Comment by maxhbr** [comment]
The solution seems to not work:

![2023-06-19_20-01-07](https://github.com/magma/magma/assets/1187050/34f6f02d-df5c-4810-87a0-bb13af0db78a)

**Comment by maxhbr** [comment]
see https://github.com/magma/magma/actions/runs/5313978394

**Comment by tapasmishra** [comment]
> The solution seems to not work:
> 
> ![2023-06-19_20-01-07](https://user-images.githubusercontent.com/1187050/246904301-34f6f02d-df5c-4810-87a0-bb13af0db78a.png)

As per the error; you just need to remove the branch reference. Rest of the solution should work as expected.

**Comment by maxhbr** [comment]
@tapasmishra this was already discussed in slack, done and merged yesterday. See https://github.com/magma/magma/pull/15219

**Comment by maxhbr** [comment]
Results are now posted to magma-ci again (these two rows are out of order, second row is current latest master)
![2023-06-20_11-40-45](https://github.com/magma/magma/assets/1187050/6e7e9c13-683a-4882-acd4-77ef9ece179b)

stuff is still failing and red, see: https://github.com/magma/magma/issues/15222
