### ISSUE TITLE
Magma 1.8, non-NAT multi-apn DHCP relay not working

### ISSUE THREAD

**Issue by Radula76** [magma/magma#15174]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- Magma 1.8
- AGW non-NAT, multi-APN, DHCP allocation
- Mobility, DHCP helper
- bare-metal (AGW)

### Describe the Issue

Customer has the DHCP server behind the next hop router(172.26.166.211).  Router is acting as a relay for the DHCP request.  We can see the DHCP offer (packet 3) come in with IP address:   172.26.160.69 (dhcp server, microsoft), but Next Server IP address marked as: 172.26.160.69.
the DHCP Request from the AGW (packet 4) is broadcast but next server IP is not set to 172.26.160.69.

We never receive the ACK from the DHCP server.

AGW N6 interface: 172.26.162.32

Or is it the DHCP server identifier not being used correctly?

#### To Reproduce

configure AGW with N6/SGi IP 172.26.162.32, next hop router 172.26.166.211, DHCP server  172.26.160.69.
next hop router DHCP relay to 172.26.160.69.
APN set to DHCP allocation, VLAN 1080

CPE connects and DHCP request is sent out, router relays to DHCP server, offer comes back.
AGW does broadcast but doesn't use 'next-server-ip address'

other possibility is the next hop router not putting in the 'relay' field?

#### Expected behavior

DHCP ack received and CPE retains IP address

#### Screenshots

PCAP trace attached

#### Additional context

PCAP trace attached
[DHCP_check5.zip](https://github.com/magma/magma/files/11153947/DHCP_check5.zip)

**Comment by Radula76** [comment]
possible fix:
  In the DHCP request message which client sends, there is a field DHCP server identifier.  This should be the DHCP server address whose IP client accepts. 
Magma is sending the next hop IP address in that field and not DHCP server. Due to this we do not see ack from server. 
It will work fine, if the next hop IP and the DHCP server is same. 

Fix:
/usr/local/lib/python3.8/dist-packages/magma/mobilityd/dhcp_client.py
Function _process_dhcp_pkt()
Line 276. Remove these 2 lines 
                if IP in packet:
                    dhcp_server_ip = packet[IP].src

and change it with
dhcp_server_ip = self._get_option(packet, "server_id")

We will look at more testing.

**Comment by javieraubert** [comment]
Hi @Radula76, have you try another DHCP server?, maybe is something with the Microsoft DHCP server config. I had try the same escenario, except that I used the ISC DHCP server, and it works fine.

**Comment by Radula76** [comment]
Thanks @javieraubert , the change we made has worked, the microsoft DHCP server is behind the first hop microtik router.  the AGW wasn't assigning the IP addresses correctly in the request packet.  the microtik is setup to relay the DHCP to the server.
