### ISSUE TITLE
AGW fails with Clearsigned file isn't valid, got 'NOSPLIT' error 

### ISSUE THREAD

**Issue by abh23** [magma/magma#15178]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6
- **Affected Component:**  Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** Vagrant (AGW)
- **OS:** Ubuntu 20.04(focal)

### Describe the Issue

Getting `Clearsigned file isn't valid` error at `Add apt-transport-https` step in `pkgrepo` ansible role. Full error below: 

```
fatal: [magma]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://facebookconnectivity.jfrog.io/artifactory/list/dev-focal/dists/focal/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?), E:The repository 'https://facebookconnectivity.jfrog.io/artifactory/list/dev-focal focal InRelease' is no longer signed."}
```

#### To Reproduce

1. Go to `lte/gateway/`
2. Run `vagrant up magma`
3. See error

#### Expected behavior

apt-transport-https should get installed without any errors.

**Comment by panyogesh** [comment]
This repo is not valid any more. Magma has moved on to new repository. Kindly try on the latest code based and if issue persists kindly file a new ticket.
Closing the ticket for now.
