### ISSUE TITLE
Bug: (FEG) mapping key "<<" already defined

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#15183]
### Your Environment

- **Affected Component:** FEG

### Describe the Issue

https://github.com/magma/magma/actions/runs/4702772703/jobs/8340442504 shows a CI error processing the yaml "<<" merge key. This appears to be an issue with upgrading docker-compose.

yaml: unmarshal errors:
  line 47: mapping key "<<" already defined at line 46
  line 52: mapping key "<<" already defined at line 51

#### To Reproduce

1. Submit any PR
2. Get a CI error on feg-build
3. Scroll down to details, e.g. at https://github.com/magma/magma/actions/runs/4702772703/jobs/8340442504

#### Expected behavior

The "<<" merge key in yaml should be accepted. 

#### Screenshots

Build error:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/111581/232911053-ac41d86d-0864-4001-85f3-130d85985183.png">

#### Additional context

Obligatory LMGTFY here:
https://github.com/docker/compose/issues/10407
```
Upon upgrading from Docker Compose version 2.16.0 to Docker Compose version 2.17.2 it seems like 2.17 and above dropped support for merging in yaml, ref: https://yaml.org/type/merge.html

yaml: unmarshal errors:
  line 155: mapping key "<<" already defined at line 154
  line 192: mapping key "<<" already defined at line 191

I seems to happen when to merge keys << exists in the same service. If only 1 exist there is not error.
```
In our own code the trigger is these two lines:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/111581/232912165-1415d63a-9dd9-43b5-9b19-483d0ee7b4eb.png">

Important: this yaml would have been legal until docker-compose was upgraded. The yaml is not the problem, though I guess we could work around the problem there.

**Comment by panyogesh** [comment]
Fixed as part of #15181
