### ISSUE TITLE
Traffic from UE not matching to correct table 0 rule, gets dropped

### ISSUE THREAD

**Issue by wesmwoo** [magma/magma#15185]
### Your Environment

- 'next'
- Access Gateway
- pipelined (I think? Issue with AGW datapath)
- Vagrant (AGW)

### Describe the Issue

I'm looking to figure out why UE traffic is not matching to the correct rule in table 0:
```
[6.] cookie=0x0, duration=1621.884s, table=0, n_packets=0, n_bytes=0, priority=10,tun_id=0x1,in_port="g_f7002a0a" actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1000108->NXM_NX_REG9[],load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1).
```
It looks like the traffic is not matching because the tun_id!=0x1 or the in_port!="g_f7002a0a". After running tshark on eth1 and checking the GTP packet TEID, I can see that it is set to 0x00000001, so the traffic must not have in_port = "g_f7002a0a". I can see the traffic at the gtpu_sys_2152 interface, but not the gtp_br0 interface using tshark.

Does anyone have guidance on how to check to see what port the traffic is entering gtp_br0 on, or how to find where g_f7002a0a is created/configured in the magma codebase?

#### To Reproduce

1. Set up AGW with physical eNB and UE, using "Quick Start" and "[Connecting physical eNB and UE to Gateway VM](https://magma.github.io/magma/docs/next/lte/dev_notes#on-the-magma_test-host-machine)"
2. Enter UE SIM into subscriberdb via subscriber_cli.py. I had to add in APN/AMBR information in as well to get the UE to attach
3. Run `sudo ovs-ofctl dump-flows gtp_br0 table=0` to list flows

#### Expected behavior

Expect to see the table 0 rule to be updating metadata, setting the correct metadata, etc. before resubmitting flow to table 1

#### Screenshots

Instead, I get the following result:

```
cookie=0x0, duration=6605.405s, table=0, n_packets=8, n_bytes=560, priority=10,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=6279.545s, table=0, n_packets=0, n_bytes=0, priority=10,tun_id=0x1,in_port="g_f7002a0a" actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1000008->NXM_NX_REG9[],load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=6279.545s, table=0, n_packets=0, n_bytes=0, priority=10,ip,in_port=LOCAL,nw_dst=192.168.128.12 actions=load:0x1000008->NXM_NX_TUN_ID[],load:0xa2a00f7->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x1->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=6279.545s, table=0, n_packets=0, n_bytes=0, priority=10,ip,in_port=mtr0,nw_dst=192.168.128.12 actions=load:0x1000008->NXM_NX_TUN_ID[],load:0xa2a00f7->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x1->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=6279.545s, table=0, n_packets=0, n_bytes=0, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.128.12 actions=load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=6279.545s, table=0, n_packets=0, n_bytes=0, priority=10,arp,in_port=mtr0,arp_tpa=192.168.128.12 actions=load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=6605.405s, table=0, n_packets=10157, n_bytes=642231, priority=0 actions=resubmit(,1)
```

The only rule being matched is the bottom, default rule, which resubmits the flow to table 1 without modification. This results in all packets being dropped.

#### Additional context
Result of `sudo ovs-vsctl show`:

```b0402d61-8d95-4466-b20c-35983b172040
    Manager "ptcp:6640"
    Bridge uplink_br0
        Port dhcp0
            Interface dhcp0
                type: internal
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port uplink_br0
            Interface uplink_br0
                type: internal
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        fail_mode: secure
        Port g_f7002a0a
            Interface g_f7002a0a
                type: gtpu
                options: {csum="false", key=flow, remote_ip="10.42.0.247"}
                bfd_status: {diagnostic="Neighbor Signaled Session Down", flap_count="0", forwarding="true", remote_diagnostic="No Diagnostic", remote_state=up, state=up}
        Port gtp0
            Interface gtp0
                type: gtpu
                options: {key=flow, remote_ip=flow}
        Port mtr0
            Interface mtr0
                type: internal
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port gtp_br0
            Interface gtp_br0
                type: internal
        Port li_port
            Interface li_port
                type: internal
        Port proxy_port
            Interface proxy_port
        Port ipfix0
            Interface ipfix0
                type: internal
    ovs_version: "2.15.4"
```

Result of `ethtool -i eth1`:

```
driver: e1000
version: 7.3.21-k8-NAPI
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:08.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
```

**Comment by prabinakpattnaik** [comment]
Please enable the debug logs in ovs using below steps:
```sudo su
sudo ovs-appctl vlog/set netdev dbg
sudo ovs-appctl vlog/set ofproto dbg
sudo ovs-appctl vlog/set vswitchd dbg
sudo ovs-appctl vlog/set dpif dbg
echo 'module openvswitch +p' > /sys/kernel/debug/dynamic_debug/control
exit
sudo dmesg -n 7
sudo dmesg -C```

After that send the few traffics then collect the logs using below command:
```sudo dmesg```

**Comment by wesmwoo** [comment]
Hi Prabina -- attached is my log output

It looks like there is a lot of repetition of this sequence:
```
[24946.512762] gtpu_sys_2152: inner pkt: ipv4
[24946.512766] gtpu_sys_2152: encap_recv sk=00000000d1d0a345 type 5
[24946.512775] gtpu_sys_2152: flags 30 type: ff
[24946.512784] gtpu_sys_2152: attaching metadata_dst to skb, gtp ver 1 hdrlen 16
[24946.512793] gtpu_sys_2152: forwarding packet from GGSN to uplink
``` 
and no other information...

[ovs_dmesg.log](https://github.com/magma/magma/files/11343883/ovs_dmesg.log)

**Comment by wesmwoo** [comment]
Hi @prabinakpattnaik -- after discussing with "jv connect 5G" on slack, I'm wondering if there is an issue with the vport_gtp kernel module attaching the correct metadata to packets at gtpu_sys_2152. Do you know how I can see the metadata attached to the packets, or look at the magma modifications to the vport_gtp module?

**Comment by prabinakpattnaik** [comment]
I am not sure about issue with metadata. As per OVS-kernel logs, seems OK. gtpu header is extracted and inner packet is showing as IPv4 packet.

Can you share output for below commands:
sudo ovs-appctl dpif/show

sudo ovs-appctl dpif/dump-dps

sudo ovs-appctl dpctl/dump-flows

sudo ovs-vsctl --columns=ofport,name --format=table list Interface

Could you try for disable the multi tunnel eNB
# Create separate tunnel interface for each eNodeB
ovs_multi_tunnel: true

Make it as false in spgw.yml and restart the services.

**Comment by wesmwoo** [comment]
Here are the outputs:
`sudo ovs appctl dpif/show`:
```system@ovs-system: hit:249 missed:60
  gtp_br0:
    g_f7002a0a 3/4: (gtpu: key=flow, remote_ip=10.42.0.247)
    gtp0 32768/4: (gtpu: key=flow, remote_ip=flow)
    gtp_br0 65534/3: (internal)
    ipfix0 15578/6: (internal)
    li_port 15579/8: (internal)
    mtr0 15577/5: (internal)
    patch-up 2/none: (patch: peer=patch-agw)
    proxy_port 1/7: (system)
  uplink_br0:
    dhcp0 3/2: (internal)
    patch-agw 2/none: (patch: peer=patch-up)
    uplink_br0 65534/1: (internal)
```

`sudo ovs-appctl dpif/dump-dps`:
```
system@gtp_br0
system@uplink_br0
```
`sudo ovs-appctl dpctl/dump-flows`:
```
recirc_id(0),tunnel(tun_id=0x1,src=192.168.60.1,dst=192.168.60.142,flags(-df+csum+key)),in_port(4),eth_type(0x0800),ipv4(dst=8.0.0.0/254.0.0.0,frag=no), packets:379, bytes:26687, used:0.012s, flags:S, actions:drop
```
`sudo ovs-vsctl --columns=ofport,name --format=table list Interface`:
```ofport name
------ ----------
2      patch-agw
65534  gtp_br0
32768  gtp0
15579  li_port
3      g_f7002a0a
1      proxy_port
65534  uplink_br0
15578  ipfix0
3      dhcp0
2      patch-up
15577  mtr0
```

**Comment by wesmwoo** [comment]
The multi tunnel eNB configuration change didn't affect anything

**Comment by wesmwoo** [comment]
If I'm understanding the output correctly, it looks like the flow is through port 4, but g_f7002a0a (the desired port) is port 3?

**Comment by wesmwoo** [comment]
Hi @prabinakpattnaik -- thanks again for all of your help so far! Do you have any insight on this most recent output?

**Comment by wesmwoo** [comment]
Updating in case anyone runs into this issue -- my problem was with my Virtualbox setup. I had to use a Bridged-only Adapter for eth1, which involved resetting the eth1 IP address to an IP address on the same subnet as my eNB.

**Comment by prabinakpattnaik** [comment]
The issue looks like in here only:
recirc_id(0),tunnel(tun_id=0x1,src=192.168.60.1,dst=192.168.60.142,flags(-df+csum+key)),in_port(4),eth_type(0x0800),ipv4(dst=8.0.0.0/254.0.0.0,frag=no), packets:379, bytes:26687, used:0.012s, flags:S, actions:drop

Could you please share the complete pcap file from Registration to traffic flows.

**Comment by wesmwoo** [comment]
Hi @prabinakpattnaik -- I've actually solved this problem and everything is working now! Thank you for all your help!
