### ISSUE TITLE
Acceptance Of Security Scorecard Task

### ISSUE THREAD

**Issue by bensternthal** [magma/magma#15199]
This issue tracks the voting of the TSC on the Acceptance Of Security Scorecard Task.

The project board that documents all sub-tasks and future follow-ups is here:
https://github.com/orgs/magma/projects/20/views/1

Messy tracking ticket that shows the actual scorecard run:
https://github.com/magma/security/issues/144

To vote please comment on this issue with either an Approve, Disapprove or Abstain.

**Comment by lucasgonze** [comment]
Is there a deadline for voting?

**Comment by bensternthal** [comment]
I would say 1 week, so end of day this Friday. We would need 4 approvals from the TSC for this to pass

**Comment by lucasgonze** [comment]
I abstain.

**Comment by jordanvrtanoski** [comment]
+1 from my side (Approve)

**Comment by panyogesh** [comment]
+1

**Comment by rdefosse** [comment]
+1

**Comment by maxhbr** [comment]
Approve

**Comment by bensternthal** [comment]
Based on my reading of the [TSC voting rules](https://github.com/magma/Governance/blob/main/CHARTER.md#3-tsc-voting), we need a majority (4 vote) in order to pass this resolution. Since we have 3 approvals and one abstain, I will extending the voting deadline to Wednesday next week to give @rdefosse and @pshelar a chance to vote.

**Comment by lucasgonze** [comment]
> Based on my reading of the [TSC voting rules](https://github.com/magma/Governance/blob/main/CHARTER.md#3-tsc-voting), we need a majority (4 vote) in order to pass this resolution. Since we have 3 approvals and one abstain, I will extending the voting deadline to Wednesday next week to give @rdefosse and @pshelar a chance to vote.

https://github.com/magma/magma/issues/15199#issuecomment-1562406880

**Comment by maxhbr** [comment]
yes, we have 
* 4 Approve
* 1 Abstain
and 2 have not voted

**Comment by maxhbr** [comment]
@bensternthal you might need to expand the "1 similar comment" part:
![2023-05-27_11-34-32](https://github.com/magma/magma/assets/1187050/a67b21a0-f8c7-4abd-bcf1-a53dca7b2ba2)

**Comment by bensternthal** [comment]
> @bensternthal you might need to expand the "1 similar comment" part: ![2023-05-27_11-34-32](https://user-images.githubusercontent.com/1187050/241376601-a67b21a0-f8c7-4abd-bcf1-a53dca7b2ba2.png)

You are correct, I don't know how but I missed seeing the 1 similar comment. Sorry about that! I will close this out and capture the results in google drive.
