### ISSUE TITLE
Unable to ping anything from a simulated UE (SRSRAN simulators)

### ISSUE THREAD

**Issue by Gmerold** [magma/magma#15196]
### Your Environment

- **Version:** 1.8
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** ?
- **Deployment Environment:** AWS (both Orc8r and AGW)

### Describe the Issue

While doing E2E tests including Magma 1.8 and SRSRAN simulators, I'm not able to ping anything (i.e. google.com) from the simulated UE unless, after connecting simulated eNB for the first time, I restart the AGW services. Once it's done and the UE is attached again, ping works just fine. It's also impossible to ping the EU from the AGW unless Magma is restarted.

#### To Reproduce

You may follow [this tutorial](https://canonical-charmed-magma.readthedocs-hosted.com/en/1.8/tutorial/01_getting_started/). You may ignore Juju context if you want. Bug is reproducible regardless of the way Magma has been deployed.

#### Expected behavior

Once the UE is successfully attached to the network, it should be able to reach the internet (i.e. google.com)

**Comment by jao-tm** [comment]
Do you have any logs and pcap trace for this? The mme.log and srsRAN logs, and pcap trace of S1 would be useful

**Comment by arunwave** [comment]
After testing with the SRSRAN simulator, I found that I could ping google.com without restarting the AGW services. Additionally, even after successfully connecting to the network, internet access was still available. I have attached logs and screenshots for your reference..
[Srsenb.zip](https://github.com/magma/magma/files/14717487/Srsenb.zip)
