### ISSUE TITLE
Orchestrator - ./build.py --all is not working

### ISSUE THREAD

**Issue by shriram1803-2** [magma/magma#15218]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator 

### Describe the Issue

rm@scvbox1:~/Desktop/magma/orc8r/cloud/docker$ ./build.py --all
Creating build context in '/tmp/magma_orc8r_build'...
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/gateway/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/api/v1/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/test/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/lib/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/lib/go/protos/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/lte/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/feg/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/feg/cloud/go/protos/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/cwf/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/dp/cloud/go/go.mod
Running 'docker compose --compatibility -f docker-compose.yml -f docker-compose.metrics.yml -f docker-compose.override.yml build --build-arg MAGMA_MODULES=orc8r lte feg cwf dp'...
[+] Building 0.0s (0/0)                                                         

Nothing is happening after this, I waited for hours. 
Has this happened to anyone else? If yes, please tell me how you resolved it??

Please note that I am doing the entire installation process inside a Ubuntu 22.04 VM (so that I could just erase the VM if anything goes wrong)

**Comment by panyogesh** [comment]
This is working fine on the latest repo. Kindly retest and raise a new ticket if issue persists. Closing the ticket.
