### ISSUE TITLE
AGW 1.6.1 services restarting 

### ISSUE THREAD

**Issue by AtulSmahale** [magma/magma#15280]
Your Environment

    Version: 1.6.1
    Affected Component: Access Gateway
    Affected Subcomponent: AGW MME, sessiond, mobilityd, pipelined
    Deployment Environment: e.g. bare-metal AGW, 

Describe the Issue

The MME service no longer starts, it stays in an endless crashloop together with mobilityd, pipelined, sessiond.

We have observed that the mme service keeps restarting with this error:

dishnet@dishnet:~$ sudo tail -f /var/log/mme.log
56843153 Wed Aug 02 20:50:22 2023 7EFFA3AF0700 ERROR MME-AP tasks/mme_app/mme_app_location.c:0432    IMSI is not present in the MME context for imsi 460000000010399
56843154 Wed Aug 02 20:50:22 2023 7EFFA3AF0700 WARNI MME-AP tasks/mme_app/mme_app_context.c :0332   [460000000013099]  No IMSI hashtable for this IMSI
56843155 Wed Aug 02 20:50:22 2023 7EFFA3AF0700 ERROR MME-AP tasks/mme_app/mme_app_location.c:0432    IMSI is not present in the MME context for imsi 460000000013099
56843156 Wed Aug 02 20:50:22 2023 7EFFA32EF700 ERROR SCTP   tasks/sctp/sctpd_downlink_client:0091    sctpdl.senddl error = Connect Failed
56843157 Wed Aug 02 20:50:22 2023 7EFFA32EF700 ERROR SCTP   tasks/sctp/sctpd_downlink_client:0198    assoc_id 913 stream 0 rc = -1
56843158 Wed Aug 02 20:50:22 2023 7EFFA02E9700 ERROR S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0107    ERROR: Failed to send connectionless S1AP message to eNB. mme_ue_s1ap_id =  0
56843159 Wed Aug 02 20:50:22 2023 7EFFA0AEA700 DEBUG SGW_S8 tasks/sgw_s8/sgw_s8_task.c      :0118    Finished cleaning up SGW_S8 task
56843160 Wed Aug 02 20:50:22 2023 7EFFA12EB700 INFO  GTPv1- lib/openflow/controller/Controll:0080    Stopped openflow controller
56843161 Wed Aug 02 20:50:26 2023 7EFFA32EF700 ERROR SCTP   tasks/sctp/sctpd_downlink_client:0091    sctpdl.senddl error = Connect Failed
56843162 Wed Aug 02 20:50:26 2023 7EFFA32EF700 ERROR SCTP   tasks/sctp/sctpd_downlink_client:0198    assoc_id 922 stream 0 rc = -1

To Reproduce

We don't know why this is started happening. We were having issues with user data plane (no traffic was being forwarded from UE to the Internet). At some point during troubleshooting we decided to:

    systemctl stop magma@*
    systemctl start magma@magmad

Then the mme service never came back up.
Expected behavior

the mme service should come up
Screenshots

Here's the output of health_cli.py:

![image](https://github.com/magma/magma/assets/66073724/d1397b6d-1a8c-4e4e-bdf1-1c5a0c080d63)

Add any other context about the problem here (e.g. logs).

**Comment by AtulSmahale** [comment]
[juba.zip](https://github.com/magma/magma/files/12243543/juba.zip)

**Comment by vinothinfinity** [comment]
From your logs,

```
Aug  2 21:10:10 dishnet systemd[1]: Started Magma OAI MME service.
Aug  2 21:10:10 dishnet mme[936280]: ==936280==Sanitizer CHECK failed: ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:53 ((!lsan_init_is_running)) != (0) (0, 0)
Aug  2 21:10:11 dishnet systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
Aug  2 21:10:11 dishnet smsd[932]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
```

You might want to check magma issue 15279.

**Comment by panyogesh** [comment]
For now we are planning to support 1.8 and ongoing release (master which will become 1.9)
