### ISSUE TITLE
Traffic is not flowing with policy 5GSA.

### ISSUE THREAD

**Issue by nareshwave** [magma/magma#15305]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

 Your Environment
   -**Version: 1.9.0-1694109294-30739e4a ** 
   - **Affected Component: AGW** 
   - **Affected Subcomponent: Pipelined** 
   - **Deployment Environment: Open stack VM (AGW)**

 

 Describe the Issue
   Installed version 1.9, to do some tests, my setup, Open stack VM AGW, and Policy config. in Orc8r. A configured policy 
   with flow and without flow, but traffic not flowing.   

 To Reproduce
    1.  Install V1.9
    2. Add the policy in NMS and attach the policy to UE.
    3. Execute the test case.
    4. Observe table0, table12.

 Expected behavior
    After adding the policy traffic flow, we can observe the output in Table 0 and Table 12.

 Screenshots
<img width="782" alt="Table 12" src="https://github.com/magma/magma/assets/92521398/c19ddf49-4d1f-4327-84e3-8e0352a53aa6">
<img width="764" alt="Table 0" src="https://github.com/magma/magma/assets/92521398/2a5f89b8-d819-4b23-aaf7-85ae214d0346">

 Additional context

 Please find the attached syslogs.
[sys987654321.log](https://github.com/magma/magma/files/12594968/sys987654321.log)

**Comment by akhilamoyila9** [comment]
The issue is resolved. Configuration issue in our setup. we tested the policies of UDP, TCP, and ICMP with permit and deny. All the scenarios are working, and traffic is flowing fine based on the scenario.

**Comment by nareshwave** [comment]
The issue is resolved. Configuration issue in our setup. we tested the policies of UDP, TCP, and ICMP with permit and deny. All the scenarios are working, and traffic is flowing fine.
