### ISSUE TITLE
CI Test Failing: build_dockerfile_bazel_cache_prod

### ISSUE THREAD

**Issue by shashidhar-patil** [magma/magma#15332]
### Your Environment

- **Version:** v1.9
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

Magma CI: build_dockerfile_bazel_cache_prod is failing. Bazel tests are failing due to memory leaks detected by Leak sanitizer.
![Screenshot from 2023-10-30 13-09-55](https://github.com/magma/magma/assets/89975652/2a20c5c5-1668-4c5d-923c-d2ffa31be0c8)

However, the memory leak seems to be in libsan library and not in the Magma codebase.
![Screenshot from 2023-10-30 13-10-35](https://github.com/magma/magma/assets/89975652/36540ecf-51d2-4506-9b92-bfc056730f3a)

#### Issue Analysis

- Leak Sanitizer Check is failing in the lsan lib init itself. 
- It is a gcc/sanitizer bug
- It is here to stay in gcc10 which is now end-of-support. This is a bug in liblsan version 10.5.0(This is the official supported version in ubuntu20.04,gcc10).
- We can find an in-depth explanation of this issue: https://github.com/magma/magma/issues/15279#issuecomment-1742247833 
- This bug is raised at Ubuntu forum as well: https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/2038386 

#### To Reproduce

1. [HOST] `git clone https://github.com/magma/magma.git`
2. [HOST] `cd magma/lte/gateway`
3. [HOST] `vagrant up magma`
4. [HOST] `vagrant ssh magma`
5. [VM] `cd magma/lte/gateway`
6. [VM] `apt list -i | grep liblsan`
    Fresh installation of magma gives older 10.3.0 version of lsan (in which the issue doesn't exist)
7. Run bazel test with leak sanitizer.
   [VM] `` bazel test --config=production --flaky_test_attempts=5 --test_tag_filters=-manual `bazel query "kind(cc_test, //...)"` ``
8. Now upgrade the liblsan0 package to 10.5.0 (The issue exists with this version)
    `sudo apt upgrade liblsan`
9. [VM] `` bazel test --config=production --flaky_test_attempts=5 --test_tag_filters=-manual `bazel query "kind(cc_test, //...)"` ``
   The issue is reproduced.
![Screenshot from 2023-10-30 13-10-35](https://github.com/magma/magma/assets/89975652/36540ecf-51d2-4506-9b92-bfc056730f3a)

#### Expected behavior

Successful execution of the Magma CI: build_dockerfile_bazel_cache_prod

#### Probable Fixes

1. Move to Ubuntu 22.04
    - Pro: This issue is fixed in gcc11+ through the reimplementation of dlsym allocator.
    - Con: This will need additional effort to test and stabilize Magma in Ubuntu 22.04.
2.  **Disable the Leak Sanitizer entirely from the Production build. (Preferred as it unblocks v1.9 PRs)**
    - Pro: Removing the --config=lsan --copt=O3 from profuction build fixes the issue.
    - Con: Some leaks may go unnoticed. However Address Sanitizer is running as part of CI, this should be able to catch most of the leaks.

**Comment by panyogesh** [comment]
It seems apt-install does not have the 10.3.0 version. It has only 10.5.0 version (sudo apt-get install -y liblsan0=10.5.0-1ubuntu1~20.04).
10.3.0 seems to be only in archives.  Forcing a downgrade to 10.3.0 locks our system in a state of broken dependencies [reference-link](https://askubuntu.com/questions/1484074/my-application-requires-liblsan0-10-3-0-but-it-was-removed-from-ubuntu-repos)

**Comment by lucasgonze** [comment]
For solution 1 "Move to Ubuntu 22.04", how much uncertainty does this create? How much new work is it?

**Comment by panyogesh** [comment]
> For solution 1 "Move to Ubuntu 22.04", how much uncertainty does this create? How much new work is it?

Based on our past exp.... Roughly 3 months 3-4 engg.

**Comment by lucasgonze** [comment]
> 3 months 3-4 eng

My guess is that we don't have that many hours available for an edge case like this. Do you agree, Yogesh?

**Comment by panyogesh** [comment]
> > 3 months 3-4 eng
> 
> My guess is that we don't have that many hours available for an edge case like this. Do you agree, Yogesh?

Yes

**Comment by panyogesh** [comment]
Meanwhile to unblock  we have raised the PR: https://github.com/magma/magma/pull/15334

**Comment by tapasmishra** [comment]
We can consider the issue to be fixed for now. Seems the changes in PR [#15334](https://github.com/magma/magma/pull/15334) are working and we are no more seeing the issue.
