### ISSUE TITLE
suci scenario: registration reject 

### ISSUE THREAD

**Issue by mickymkumar** [magma/magma#15331]
When we tried the suci scenario with spirent. We added the profileA via swagger it is reflected in  agw. but registration reject is happening due to illegeal ue cause value 3. 

**Can someone take look anf provide support?**

![image](https://github.com/magma/magma/assets/55264508/c7e1722b-2542-4c30-bbb6-fbc25b6c4831)
![image (1)](https://github.com/magma/magma/assets/55264508/e5d6d559-e1f2-4184-bf5a-9a83439d9481)
![image (2)](https://github.com/magma/magma/assets/55264508/c060530d-0464-43f5-b03b-d8e5f55d81d6)

[23-10-27_09.37.20__RID-187__ts0_eth6_capture.zip](https://github.com/magma/magma/files/13194197/23-10-27_09.37.20__RID-187__ts0_eth6_capture.zip)

**Comment by shashidhar-patil** [comment]
Hi @mickymkumar, 
Based on the log `get_decrypt_imsi_info fails with code 2, Message : Exception calling application: An X25519 private key is 32 bytes long`, the public and private keys added from swagger are incorrect.

 ![image](https://github.com/shashidhar-p/integration-magma/assets/42925091/1923cc77-8f82-4818-87de-4424713b7c73)

1. Format Private Key:
   
    - Private key(hex): ```48:d4:6f:5a:89:db:04:7b:f5:c1:ea:dc:5a:1c:bf:b2:06:79:22:80:af:9b:db:87:77:c9:09:0a:74:86:db:78```
   
    - Remove Colons and add "0x"(hex): ```0x48d46f5a89db047bf5c1eadc5a1cbfb206792280af9bdb8777c9090a7486db78```

    - Convert to private key to base64:
      ```
      SNRvWonbBHv1wercWhy/sgZ5IoCvm9uHd8kJCnSG23g=
      ```
      
2. Format Public Key:
   
    - Public key(hex): ```a1:1b:f9:0a:da:a0:3a:0c:df:57:9a:1d:86:33:e0:2f:43:d8:f5:3e:f8:e1:52:63:07:81:df:1f:0d:15:ef:0c```
   
    - Remove Colons and add "0x"(hex): ```0xa11bf90adaa03a0cdf579a1d8633e02f43d8f53ef8e152630781df1f0d15ef0c```

    - Convert to public key to base64:
      ```
      oRv5CtqgOgzfV5odhjPgL0PY9T744VJjB4HfHw0V7ww=
      ```

### Configure the suci profiles through swagger:
- **Network ID:** Check NMS to get the network id to which the AGW is connected.
- **home_network_private_key** : (generated in step 1)
      ```
      SNRvWonbBHv1wercWhy/sgZ5IoCvm9uHd8kJCnSG23g=
      ```
- **home_network_public_key** : (generated in step 2)
      ```
      oRv5CtqgOgzfV5odhjPgL0PY9T744VJjB4HfHw0V7ww=
      ```
- **home_network_public_key_identifier**: 22 (Any number between 0-255)
- **protection_scheme**: ProfileA (X25519 algo,this profile has been used as an example in this guide) **OR**
                         ProfileB (ECDH_SECP256R1 algo)
  
![image](https://github.com/shashidhar-p/integration-magma/assets/42925091/fe7bc90d-7bd6-4b11-85f9-80317cb73e40)


Here is a link for more detailed documentation: https://github.com/shashidhar-p/integration-magma/blob/main/suci_extension_magma/suci_spirent_test.md?plain=1
