### ISSUE TITLE
 replacing asn compiler with  latest compiler

### ISSUE THREAD

**Issue by ganeshg87** [magma/magma#15333]
### Problem

Existing Magma ASN Compiler Framework :

**ASN Repository Used:** https://gitlab.eurecom.fr/oai/asn1c.git
**Repository Forked From:** https://github.com/vlm/asn1c
**Last Activity on Repository:** March 24, 2017 (6 years ago)
**Cons:** 

- Additional patches are required to decode some of the S1AP and NGAP release ASN files.
- A couple of crashes were identified while decoding ngap and asn files.
- The repository was not maintained actively, it was stale for a long time

 **License:**  BSD-2-Clause license
 **Build from  :** magma/third_party/build/asn1c_build.sh

### Solution

**New ASN Compiler Options:**

A couple of open source and commercial options were screened and the one from an open source from Nokia seems to be a close fit. Following are the details of the same : 
Proposed Open-Source Software used in Compiler Development
**New ASN compilers:**  

1. https://github.com/nokia/asn1c.git 
2. https://github.com/mouse07410/asn1c

**Repository Forked From:** both nokia and mouse07410 from https://github.com/vlm/asn1c
**Last Activity on Repository:**

-    [vlm](https://github.com/vlm/asn1c) -  Apr 18, 2021(2 years ago)
-    [nokia](https://github.com/nokia/asn1c) - Sep 8, 2022 ( years ago)
-    [Mouse07410](https://github.com/mouse07410/asn1c)  - Oct 11, 2023 ( 2 Weeks ago).

**Pros:** 

- No additional patches requiried, it supports release 17 ngap & s1ap asn
- Open5gs also using same repo([mouse07410](https://github.com/mouse07410/asn1c)) 
- Originating branch same(vlm) for both nokia and mouse07410.

**License :**  BSD-2-Clause license

### Non-goals
 Please refer below path for comparing generated code from different compilers
 https://github.com/ganeshg87/utils/tree/main/asn/asn_compilers_gen_code

Anything specifically excluded from the concept

**Comment by lucasgonze** [comment]
Seems to be a dup of https://github.com/magma/magma/issues/15317

**Comment by panyogesh** [comment]
> Seems to be a dup of #15317

Yes. Will discuss with Ganesh and close it.
