### ISSUE TITLE
UE IP not getting NATed at the Gateway VM

### ISSUE THREAD

**Issue by User2707** [magma/magma#15378]
Vagrant VM

- Version: master
- Affected Component: Access Gateway
- Affected Subcomponent: AGW?
- Deployment Environment:Vagrant (AGW), Bare-metal (orc8r)

The UE IP doesnot get NATed when the packet goes out of the Vagrant VM.

![Screenshot from 2024-02-08 16-31-03](https://github.com/magma/magma/assets/148062117/459de0fe-e26d-46cc-8f44-220d04ac7360)

The outgoing packets should have been NATed while going out.

Any suggestions are welcome.
Thank You. :)

**Comment by javieraubert** [comment]
Hi, can you share your network and agw config from nms and your agw interface configs.

**Comment by User2707** [comment]
Hi @javieraubert,

Thanks for the reply and Sorry for the late reply.

I solved the issue by changing the nat_iface to eth0 in pipelined.yaml file.

Don't know if that is supposed to be the correct fix but it worked for me.

Thank you.

**Comment by User2707** [comment]
Hi @javieraubert,

Thanks for the reply and Sorry for the late reply.

I solved the issue by changing the nat_iface to eth0 in pipelined.yaml file.

Don't know if that is supposed to be the correct fix but it worked for me.

Thank you.
