### ISSUE TITLE
Fatal error: run() received nonzero return code 1 while executing!
Requested: cat /etc/snowflake
Executed: /bin/bash -l -c "cat /etc/snowflake"  | i face this problem when running fab -f dev_tools.py register_vm on magma/lte/gateway

### ISSUE THREAD

**Issue by thisisbaskara** [magma/magma#15386]
Fatal error: run() received nonzero return code 1 while executing!

Requested: cat /etc/snowflake
Executed: /bin/bash -l -c "cat /etc/snowflake"

============================================================================================= Standard output =============================================================================================

cat: /etc/snowflake: No such file or directory

===========================================================================================================================================================================================================

Aborting.
Disconnecting from vagrant@127.0.0.1:2222... done.

**Comment by mbilal92** [comment]
any fix for this?

**Comment by mbilal92** [comment]
fix is in this [PR](https://github.com/magma/magma/pull/15356)
you need to set `snowflake>=0.0.3` to `snowflake==0.0.3` in `bazel/external/requirements.in` and `orc8r/gateway/python/setup.py` and re-run the setup .
