### ISSUE TITLE
Proposal: Strengthening TMSI Generation

### ISSUE THREAD

**Issue by jorgevargasmor** [magma/magma#15399]
### **Problem**
The current method of generating Temporary Mobile Subscriber Identity (TMSI) values relies on a cryptographically insecure algorithm (rand() seeded to time(NULL)). This approach leads to predictable TMSI values, which compromises end user device privacy and security, allowing potential tracking of user associations by adversaries with over-the-air monitoring capabilities.

### **Solution**

To address this vulnerability and enhance user privacy and security, we propose replacing the existing TMSI generation method with a more robust and cryptographically secure approach. By utilizing the getrandom() function, which draws randomness from /dev/urandom, we ensure that the generated TMSI values are unpredictable and resistant to cryptographic attacks.

#include <sys/random.h>
// ...
static tmsi_t generate_random_TMSI() {
tmsi_t tmsi = (tmsi_t) 0;
if (getrandom((void*) &tmsi, sizeof(tmsi_t), 0) != sizeof(tmsi_t)) {
tmsi = (tmsi_t) rand(); // Fallback in case of fundamental system error
}
return tmsi;
}

This solution mitigates the risk of adversaries predicting TMSI values, thereby preserving the anonymity and confidentiality of user identities.

### **Non-goals**

- This proposal does not aim to address vulnerabilities unrelated to TMSI generation.
- It does not aim to introduce significant architectural changes or additional functionalities beyond enhancing TMSI generation security.

**Comment by lucasgonze** [comment]
See also https://github.com/magma/security/issues/183

**Comment by lucasgonze** [comment]
Closing this in favor of https://github.com/magma/magma/pull/15411
