### ISSUE TITLE
enodebd on AGW crashes when eNB config is updated and saved in orchestrator

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#1608]
### Your Environment

- **Version:1.0.1-1580860031-33a94e98**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** enodebd
- **Deployment Environment:** bare-metal (AGW)
- **eNodeB Model:** Baicells 436Q-CA
- **eNodeB Version:** BaiBS_QRTB_2.2.4

### Describe the Issue

eNB is not configurable via the NMS. When I go to eNodeB page, edit a setting and hit save button, there is no effect on eNB. Looking at syslog (attached) you can see each time I edit cfg and click save, the enodebd service gets a sigterm and restarts. 

**To Reproduce**
1. Go to eNodeB Devices page in orchestrator
2. Click on edit button for my eNB serial
3. Edit any field
4. Click save
5. Monitor syslog in AGW, about 10 seconds later see the following

`May  4 21:44:02 magma magmad[342]: INFO:root:Processing config update gw2
May  4 21:44:02 magma systemd[1]: Stopping Magma enodebd service...
May  4 21:44:02 magma enodebd[1415]: INFO:root:Stopping enodebd with reason SIGTERM...
May  4 21:44:02 magma systemd[1]: Stopped Magma enodebd service.
May  4 21:44:02 magma systemd[1]: Started Magma enodebd service.
May  4 21:44:04 magma enodebd[1625]: ERROR:root:Exception from _run: 'ERROR'
May  4 21:44:04 magma enodebd[1625]: INFO:root:Starting enodebd...
May  4 21:44:04 magma enodebd[1625]: INFO:root:Listening on address 127.0.0.1:60055
May  4 21:44:04 magma enodebd[1625]: INFO:root:Starting TR-069 server on 10.0.2.1:48080`

**Expected behavior**
Config changes in orchestrator should changes settings on eNB and not crash services. 

[syslog.txt](https://github.com/facebookincubator/magma/files/4578863/syslog.txt)

**Comment by andreilee** [comment]
Thanks for the detailed report, jpad.

When service configs are updated (specifically the gateway.mconfig), magmad will restart the corresponding services to consume the new config. This behavior is intended, and should not cause any issues with enodebd, as a new TR-069 session should be initiated as soon as the service is running again, and the eNB will be configured (if we support it).

To check if the config updates are getting propagated, we provide enodebd_cli.py as the first tool to check, though using tcpdump and wireshark can let you see specifically the TR-069 messages. Additionally, debug logs for enodebd are kept in enodebd.log, in the same directory where syslog is.

Let me know if this helps!

**Comment by andreilee** [comment]
Another thing to note is that we don't currently support that eNodeB version.
https://github.com/facebookincubator/magma/blob/master/lte/gateway/python/magma/enodebd/devices/device_utils.py#L47

**Comment by jpad-freedomfi** [comment]
Thanks Andrei. 

Here is what enodebd_cli gives me

`magma@magma:~/magma/lte/gateway/python/scripts$ enodebd_cli.py get_all_status
No status information to report.
Either there are no connected eNodeB devices, or no TR-069 messages have been received yet.`

Also, how do we add support for a new eNB model? Is there an onboarding process? 

Thanks for the help.

**Comment by jpad-freedomfi** [comment]
Also, do you have any plans to support NETCONF and/or SNMP?

**Comment by andreilee** [comment]
We have a short doc for adding support for a new eNB model:
https://facebookincubator.github.io/magma/docs/lte/tr069

Let us know if the doc is helpful or needs updates!

**Comment by andreilee** [comment]
Regarding NETCONF and SNMP: @talkhasib

**Comment by andreilee** [comment]
Closing this issue since from here it's not relevant to a wide audience anymore. For additional follow-up related to this, please reach out to us directly through email.

**Comment by andreilee** [comment]
Reopening to track as feature request for support of
eNodeB Model: Baicells 436Q-CA
eNodeB Version: BaiBS_QRTB_2.2.4

**Comment by xjtian** [comment]
Filed a new issue for the subtask
