### ISSUE TITLE
Magmalte (NMS) doesn't identify Organization from host

### ISSUE THREAD

**Issue by edaspb** [magma/magma#1611]
### Your Environment

- Version: Master
- Affected Component: NMS
- Affected Subcomponent: NMS Web Interface
- Deployment Environment: Third party k8s (orc8r)

Magmalte isn't able to get Organization name from header.

**To Reproduce**
1. Deploy Orchestrator and NMS from master branch
2. Try to login to NMS
3. In magamlte pod logs find "[fbcnms-auth/express.js] error: Error getting organizationInvalid organization!" message

Mysql query log on time of attempt:

"SELECT `id`, `name`, `tabs`, `csvCharset`, `customDomains`, `networkIDs`, `ssoSelectedType`, `ssoCert`, `ssoEntrypoint`, `ssoIssuer`, `ssoOidcClientID`, `ssoOidcClientSecret`, `ssoOidcConfigurationURL`, `createdAt`, `updatedAt` FROM `Organizations` AS `Organization` WHERE `Organization`.`name` = '**magmalte:8081**' LIMIT 1"

Expected behavior
Successful login to NMS

**Comment by xjtian** [comment]
How are you accessing the NMS? What's the address you're putting in your browser?

**Comment by edaspb** [comment]
The deployment I test is here: https://master.nms.yota.co.ni
Also available by https://nms.yota.co.ni

On magma_dev mail group there is another user describing the same (probably) problem
https://groups.google.com/forum/#!topic/magma-dev/amATNVv_Ixw

**Comment by edaspb** [comment]
It was incorrect /etc/nginx/conf.d/proxy_ssl.conf config.
The right one ust include
`proxy_set_header Host $http_host;`
I think somehow I had nms-nginx service from old magma version.
