### ISSUE TITLE
Fab error: vagrant AGW couldnt connect to Local orc8r

### ISSUE THREAD

**Issue by sothy** [magma/magma#1745]
### Your Environment

- **Version:** I used the lastest master branch to install development version of AGW and orchestrator.
- **Affected Component:** Orchestrator, Access Gateway, 

- **Deployment Environment:** local docker-compose (orc8r), and Vagrant (AGW)

### Describe the Issue

I'm following the document [here ](https://facebookincubator.github.io/magma/docs/basics/quick_start_guide). 

When I run the following command,
`HOST [magma/lte/gateway]$ fab -f dev_tools.py register_vm`
I'm getting the following error:
magma@magma:~/magma/lte/gateway$ fab -f dev_tools.py register_vm

```
Traceback (most recent call last):
  File "/home/magma/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/magma/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/magma/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/magma/magma/lte/gateway/dev_tools.py", line 26, in register_vm
    if not dev_utils.does_network_exist('test'):
  File "../../orc8r/tools/fab/dev_utils.py", line 138, in does_network_exist
    networks = cloud_get('/networks', admin_cert)
  File "../../orc8r/tools/fab/dev_utils.py", line 256, in cloud_get
    (resp.status_code, resp.text))
Exception: Received a 404 response: {"message":"Not Found"}

```
In my understanding, fab modules looks network configuration nginx network APIs (Data https://127.0.0.1:9443/magma/v1//networks). It is not there. Any idea to find a solution?

Thanks
Sothy

**Comment by ronit1495** [comment]
I am getting the exact same error.

**Comment by ulaskozat** [comment]
Could you try with the newest master? The fab script was adding an additional "/" and I think since earlier orc8r versions were suppressing additional "/", it was not creating an issue. There was a fix last week (landed on June 4th) that is on the master now...

**Comment by mimo123-code** [comment]
Hello i have run the fab command to connect to the local cloud it gives me the error TLS certificate failed. plzz help
