### ISSUE TITLE
Attach decode failure , MME does not send Attach Reject

### ISSUE THREAD

**Issue by anooptomar29** [magma/magma#176]
It is expected to send Attach Reject to UE when EPC can not decode any IE within Attach Request message. MME does not do it at present. Fix this issue. This results in partial reset from eNB.

Fix- Send Attach Reject when EPC can not decode any IE within Attach Request message.

**Comment by anooptomar29** [comment]
Essentially correct fix would be to send reject only when we are not able to decode mandatory IEs and/or those optional IEs which are mandatory for us from feature perspective..Otherwise we should add a generic logic that we skip the pointer by the length of the optinal IE and continue. However for the cases where in we dont recognize the IE itself ( new IE from later releases of the UE) then in that case we should send attach reject so that we don't cause partial reset.

**Comment by annepak88** [comment]
@ssanadhya - please assign to the right person on the team

**Comment by ssanadhya** [comment]
Fixed in commit 19cea9bd8b4277c86bb9aaf67299e12906df785d
