### ISSUE TITLE
Network deletion via NMS is not deleting network fully

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#1836]
### Your Environment

- **Version:** 1.1.0
- **Affected Component:** Orc8r
- **Affected Subcomponent:** NMS
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue
As a result of Network deletion it disapears from the network list but is still represented in the list of networks associated with the tenant  

**To Reproduce**
1. Go to https://mytenant.nms.example.com/admin/networks
2. Add new network "test_netwok_deletion" (Network added successfully)
3. Go to https://master.nms.example.com/master/organizations/detail/mytenant
4. Check list of networks associated with tenant
5. Go to https://mytenant.nms.example.com/admin/networks and delete "test_netwok_deletion" (Network deleted successfully)
6. Go to https://master.nms.example.com/master/organizations/detail/mytenant
7. Check list of networks associated with tenant - "test_netwok_deletion" is still in the list of networks, and it is not is the multi-select widget

**Expected behavior**
Network deleted successfully from the tenant admin page (passed)
Network deleted successfully from list of networks associated with at the Master Tenant view (failed)
Network deleted successfully from networks association multi-select widget with at the Master Tenant view (passed)

**Screenshots**
Before deletion:
<img width="1320" alt="Magma" src="https://user-images.githubusercontent.com/372029/85040330-5a34b780-b191-11ea-8d00-09ab26512128.png">
<img width="1153" alt="Magma_and_New_Issue_·_facebookincubator_magma" src="https://user-images.githubusercontent.com/372029/85040490-88b29280-b191-11ea-848f-f21b5b48ba19.png">
<img width="1067" alt="Magma" src="https://user-images.githubusercontent.com/372029/85040612-a8e25180-b191-11ea-8349-061bdb6e1423.png">

After deletion:
<img width="801" alt="Magma" src="https://user-images.githubusercontent.com/372029/85040802-daf3b380-b191-11ea-8bd4-2f90ac312f4b.png">
<img width="1036" alt="Magma_and_New_Issue_·_facebookincubator_magma" src="https://user-images.githubusercontent.com/372029/85040898-f52d9180-b191-11ea-9d44-daa52ec42788.png">
<img width="1122" alt="Magma" src="https://user-images.githubusercontent.com/372029/85041031-17bfaa80-b192-11ea-9799-513f22cf4d97.png">

**Comment by karthiksubraveti** [comment]
@119Vik Thanks for reporting this issue. I will take a look at this issue.

**Comment by xjtian** [comment]
The org to network mappings are stored on the NMS backend and it looks like we just didn't add a hook to the network deletion call to also delete the network from the NMS when it's deleted from the Orchestrator API

**Comment by karthiksubraveti** [comment]
Following fix should address this issue
https://github.com/facebookincubator/magma/commit/7e62f6a9319a824f3ee770321322a0cca76aaf9e
