### ISSUE TITLE
Exception starting orchestrator services in cloud VM

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#188]
```
vagrant@magma-cloud:~/magma/orc8r/cloud$ make run
Makefile:4: *** MAGMA_MODULE_NAMES is undefined.  Stop.
vagrant@magma-cloud:~/magma/orc8r/cloud$
```
Revision: 5b3daeca79fbb79d5ec6de9bdea7388a0900a282

Provisioning completed with no errors.
No luck with re-provisioning as documented.

**Comment by xjtian** [comment]
Hey @bmurithi, MAGMA_MODULE_NAMES is a deprecated env var - we now use MAGMA_MODULES, a space-separated list of the absolute paths of all magma modules on the system. If you update to latest trunk the VM should work after re-provisioning.
