### ISSUE TITLE
Ansible error

### ISSUE THREAD

**Issue by mubashertnss** [magma/magma#189]
i have successfully booted the CLOUD-VM and the MAGMA-VM but when i tried to provision it with command "vagrant provision cloud" it gives an error;
Error: 
fatal: [magma-cloud-dev]: FAILED! => {"changed": false, "cmd": "/home/vagrant/magma/orc8r/cloud/scripts/create_test_certs /home/vagrant/magma/.cache/test_certs", "msg": "[Errno 2] No such file or directory", "rc": 2}

i need help and please guide me what should i do?

**Comment by amarpad** [comment]
Can you ssh into the cloud VM and run the same script again?

**Comment by ajayvnl** [comment]
> i have successfully booted the CLOUD-VM and the MAGMA-VM but when i tried to provision it with command "vagrant provision cloud" it gives an error;
> Error:
> fatal: [magma-cloud-dev]: FAILED! => {"changed": false, "cmd": "/home/vagrant/magma/orc8r/cloud/scripts/create_test_certs /home/vagrant/magma/.cache/test_certs", "msg": "[Errno 2] No such file or directory", "rc": 2}
> 
> i need help and please guide me what should i do?

make sure the directory name is **magma** on your host machine. Not **megma-master**

**Comment by mcclochette** [comment]
Is there an update on that error ? I have the same error.
When I ssh into the magma-dev-cloud, the magma folder is empty.

**Comment by mcclochette** [comment]
What I did is clone the magma project into the magma-dev-cloud machine. 
I had to checkout to the release (0.3.70) that I was trying to install from.

**Comment by nikolakn** [comment]
I have run into this problem too, fixed by:
sudo rm -rf .cache
![image](https://user-images.githubusercontent.com/6031496/142399783-6c6ff382-852e-4c63-86d3-ad78b239db5f.png)
