### ISSUE TITLE
Doubt about MTU size / Jumbo Frame

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#1976]
Hello,

I'd like to know please if there is any limitation in any network function regarding the MTU size. I.e., am I able to configure Jumbo Frame, and will it work well?

**Comment by amarpad** [comment]
We do MSS clamping which is set in the ifaces file. The reason we do it is
that we found many UEs don't honor the MTU field. Other than that we don't
do anything special so jumbo frame should work

Thanks
Amar

**Comment by crbertoldo** [comment]
Thank you, @amarpad.

At eNodeB Huawei, it is possible to be configured:

![mtu](https://user-images.githubusercontent.com/6054708/87983708-2b22a600-caaf-11ea-82d7-ce3a78a73b9e.jpeg)

At UE, not sure. I think it depends on the model.

I ask that because it must be handled end-to-end, then knowing that the AGW does this way is really good.

**Comment by ekowtaylor** [comment]
Stale
