### ISSUE TITLE
Monitor number of bytes transferred by subscriber

### ISSUE THREAD

**Issue by eduardoefb** [magma/magma#2027]
Hi experts,  sorry if this is a duplicated or incorrect question.  Is there any possibility to monitor the number of bytes transferred for each subscriber on AGW or Orchestrator?

I tried to find in the documentation, but I couldn't find any similar feature.

Br.

**Comment by karthiksubraveti** [comment]
Yes. I believe this is available. @andreilee do you have more details here?

**Comment by eduardoefb** [comment]
> Yes. I believe this is available. @andreilee do you have more details here?

Thanks for your response.  It wold be very nice if it exists. While I'm still considering as not existing feature, I m implementing a simple [iptables script ](https://github.com/eduardoefb/submon)to do this and later export to sql (and also integrate with prometheus and grafana to create some chats).

**Comment by ekowtaylor** [comment]
Stale
