### ISSUE TITLE
sctp and sctpd modifications to support eNB and gNB sctp connections

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#2035]

**Comment by ulaskozat** [comment]
We need to support both eNB and gNB sctp termination in the converged core.

**Comment by sureshgorijavolu** [comment]
planned commit#1 
    Uplink data payload propagation from gNB via SCTPd and SCTP upto ZMQ
    SctpConnection_5G.Listen() -> SctpConnection_5G.HandleClientSock() -> SctpdEventHandler.HandleRecv() -> 
   SctpdUplinkClient.sendUl() -> gRPC call towards SCTP -> SctpdUplinkImpl.SendUl() -> sctp_itti_send_new_message_ind() 

Planned commit#2
   Pick Downlink data payload from ZMQ and sentd to gNB
   SCTP [handle_message() -> sctpd_send_dl() -> SctpdDownlinkClient.sendDl()] ->  gRPC call towards SCTPd -> 
   SctpdDownlinkImpl.SendDl() -> SctpConnection_5G.Send() -> sctp_sendmsg()

**Comment by ekowtaylor** [comment]
Stale
