### ISSUE TITLE
NGAP module development

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#2036]

**Comment by sureshgorijavolu** [comment]
Planned
commit#1 - UL functional flow 
Receive payload from ZMQ and process message for NGAP data indication
Pause ASN1 decode integration Until build issues are resolved on ASN1 autogenerated code.
Send hardcoded example decode UL message to ZMQ

Commit#2 - DL functional flow 
Receive payload from ZMQ and process message for NAS data indication
Pause ASN1 encode integration Until build issues are resolved on ASN1 autogenerated code.
Send hardcoded example encode DL msg to ZMQ

Commit#3 - NGAP header decode
5 mandatory fields of UE initial context set up message

Commit#4  - NGAP header encode
mandatory fields of DL Registration accept message

**Comment by ekowtaylor** [comment]
PR merged
