### ISSUE TITLE
5G NAS termination - Basic UE Registration/Deregistration Support

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#2038]
Skip optional steps in registration/deregistration process.

**Comment by sureshgorijavolu** [comment]
Planned
Commit#1 - for the UL NAS message
nas_message_header_decode()
nas_message_decode()
decode of the registration request message
decode of the registration type message
decode of the 5GMM capability message
decode of the UE status message


Commit#2 - DL NAS message
encode registration accept message
encode 5GS registration result message
encode PDU session status
encode registration complete message
encode SOR transparent container message

**Comment by ekowtaylor** [comment]
Stale
