### ISSUE TITLE
UPF Enforcement Application

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#2049]
- Permit/Deny UE flows
- Rate limiting

**Comment by panyogesh** [comment]
May-10
Some pieces of the enforcement code got re-written for 4G which can be made used in 5G. 
The original 5G patch now is modified to be at sync with 4G and have the stats (table-14) at session level.
Approach shared with Nick. Waiting for approval.

**Comment by panyogesh** [comment]
As the PRs are merged and tested on #8709 we can mark it for closure.
