### ISSUE TITLE
LTE Gateway make run is not working 

### ISSUE THREAD

**Issue by mubashertnss** [magma/magma#210]
Have anyone seen this error:

ubuntu@ip-10-0-0-107:~/magma/lte/gateway$ make run
sudo service magma@* stop
make -C /lte/gateway/python buildenv
make[1]: *** /lte/gateway/python: No such file or directory.  Stop.
Makefile:60: recipe for target 'build_python' failed
make: *** [build_python] Error 2

**Comment by mpgermano** [comment]
@mubashertnss I'm unable to reproduce on a fresh VM. Are you using the magma VM defined in the Vagrantfile located at `magma/lte/gateway`?

**Comment by mubashertnss** [comment]
I created ec2 machin, clone the directory and run "make run" @ magma/lte/gateway.

**Comment by xjtian** [comment]
@mubashertnss please follow the development quick start guide at https://facebookincubator.github.io/magma/docs/basics/quick_start_guide. There are specific requirements to build the code on the access gateway due to dependencies on certain kernel modules
