### ISSUE TITLE
[FEG] : Gy should be triggered for Omnipresent rules when they are configured with Rating group

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#2104]
### Your Environment

- **Version:**
- **Affected Component:**  Access Gateway, CWAG, Feg
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
Currently Feg does not trigger Gy for Omnipresent rules even if they are configured with a Rating Group. For some deployments which are running local policy  with OCS, this will be  a useful feature. 
**To Reproduce**
Configure Rating group for Omni present rules.
Trigger Auth flow 
GY-CCR is not sent with rating groups for  omnipresent rules. 

**Expected behavior**
If an omnipresent rule is configured with Rating  group, Feg should trigger a CCR for it over  Gy. 
**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ekowtaylor** [comment]
Stale
