### ISSUE TITLE
failed to build release version

### ISSUE THREAD

**Issue by jacqueline0124** [magma/magma#238]
when Running `fab dev package:git` under lte/gateway/ on the host to create a Magma
release, I encountered  error  and logs as follows:

[vagrant@127.0.0.1:2222] download: /tmp/packages.tar.gz <- /tmp/packages.tar.gz

Warning: Local file /tmp/packages.tar.gz already exists and is being overwritten.

Warning: Unable to load SSH config file '/root/.ssh/config'

Warning: Unable to load SSH config file '/root/.ssh/config'

[vagrant@127.0.0.1:2222] download: /tmp/packages.txt <- /tmp/packages.txt

Warning: Local file /tmp/packages.txt already exists and is being overwritten.

[localhost] local: aws s3 cp /tmp/packages.txt s3://magma-images/gateway/0.3.71-1556421385-6858deff.deplist
/bin/sh: 1: aws: not found

Fatal error: local() encountered an error (return code 127) while executing 'aws s3 cp /tmp/packages.txt s3://magma-images/gateway/0.3.71-1556421385-6858deff.deplist'

Aborting.

Warning: Unable to load SSH config file '/root/.ssh/config'

Warning: Unable to load SSH config file '/root/.ssh/config'

Warning: Unable to load SSH config file '/root/.ssh/config'

Disconnecting from vagrant@127.0.0.1:2222... done.

**Comment by xjtian** [comment]
fixed by referenced commit
