### ISSUE TITLE
[orc8r] Fix APN overview table to display actual fields

### ISSUE THREAD

**Issue by shanku9** [magma/magma#2416]
### Your Environment

- **Version:** Staging 
- **Affected Component:** Orchestrator UI
- **Deployment Environment:** e.g. AWS (orc8r)

### Describe the Issue

Add support to edit APN description and update the time added 

 JSON Config
```
"root":{2 items
"apn_configuration":{2 items
"ambr":{2 items
"max_bandwidth_dl":20000000
"max_bandwidth_ul":10000000
}
"qos_profile":{4 items
"class_id":9
"preemption_capability":true
"preemption_vulnerability":false
"priority_level":15
}
}
"apn_name":"oai.ipv4"
}
```

**To Reproduce**
1. Go to 'Traffic > APN'
2. Click on 'Edit Json'

**Expected behavior**
Edit APN field and correct time added 

**Screenshots**
<img width="1467" alt="orc8r_apn" src="https://user-images.githubusercontent.com/60643026/90819649-166f4300-e2e5-11ea-9292-37f9869c14ac.png">

**Comment by karthiksubraveti** [comment]
We need backend support to add these fields in the APN json

**Comment by shanku9** [comment]
Checking time should also be updated 
![Screen Shot 2020-08-28 at 1 07 58 PM](https://user-images.githubusercontent.com/60643026/91611211-9de53380-e92f-11ea-9089-833200cb291e.png)
