### ISSUE TITLE
Handle timers for registered UEs when stateless MME restarts

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#2475]
[Timer details document](https://docs.google.com/spreadsheets/d/1AUuwYfETPcswoVDNx53yyryLIFL3vjEagCEDhd_cu9I/edit#gid=1199317711)

**Comment by rsarwad** [comment]
When MME restarts, below are the timers handled for UEs in Registered mode
1. Paging response timer: On MME restart, MME re-transmits the Paging message
2. Initial Context Setup Response timer: On MME restart, MME moves the UE to Idle state and release S11 bearers
3. 3422_timer: The purpose of this timer is, for network initiated detach procedure, MME sends Detach Request and starts the timer to receive Detach Accept; 
   On MME restart, MME shall implicitly detach the UE and send UE context release request to eNB
4. 3485_timer: Purpose of this timer is, MME sends ACTIVATE DEDICATED EPS BEARER CONTEXT REQUEST to UE and waits for ACTIVATE DEDICATED EPS BEARER CONTEXT ACCEPT
   On MME restart, MME deletes the context locally allocated for the bearer, if it's intended for all bearers, MME deletes all  bearers and MME sends "Activation Bearer Reject" to SPGW
5. Timer_3495: Purpose of timer, MME sends DEACTIVATE EPS BEARER CONTEXT REQUEST and waits for  DEACTIVATE EPS BEARER CONTEXT ACCEPT
   On MME restart, MME shall deletes the context locally, send deactivation reject to SPGW

**Comment by rsarwad** [comment]
When MME restarts below are timers that are handled in EMM Registered mode:
1. Paging Response timer: On MME restart, MME shall send Paging message to eNB
2. Initial Context Setup Response timer: On MME restart, MME shall move the UE to Idle state and release s11 bearers
3. Timer_3422:  Purpose of the timer: MME sends Network Initiated Detach Request and waits for Detach Accept
   On MME restart, MME shall implicitly detach the UE and send UE context release request to eNB
4. Timer_3485: Purpose of the timer: MME sends ACTIVATE DEDICATED EPS BEARER CONTEXT REQUEST to UE and waits for ACTIVATE DEDICATED EPS BEARER CONTEXT ACCEPT
   On MME restart, MME deletes the context locally allocated for the bearer, if it's intended for all bearers, MME deletes all  bearers and MME sends "Activation Bearer Reject" to SPGW

**Comment by ssanadhya** [comment]
Paging response, ICS and T3422 are done. Closing this issue as we will use https://github.com/magma/magma/issues/3883 to track T3485 and T3495
