### ISSUE TITLE
Uninstall Magma

### ISSUE THREAD

**Issue by amintgan** [magma/magma#2535]
Hi, 
I have two instances of Magma running on two different bare metal servers.
I would like to uninstall magma on the old instance and still retains the OS.
Please what is the command to uninstall magma services. 

thanks

**Comment by ssanadhya** [comment]
@amintgan, the Magma package is installed via apt, so you can remove it with `apt-get –-purge remove magma` .

**Comment by amintgan** [comment]
Thanks
