### ISSUE TITLE
[CI/CD] Prepare deployment manifests based on KubeAdm for HA Kubernetes deployment with HAProxy as a LoadBalancer.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#2610]
Prepare deployment manifests based on KubeAdm for HA Kubernetes deployment with HAProxy as a LoadBalancer.

For bigger context for the issue see [Roadmap](https://docs.google.com/document/d/1cu4XGxfW7e0n84Fm82-Se_0DuKmTb2_3Qvk0vg6jVUs).

**Comment by mattymo** [comment]
Work is being covered in https://github.com/magma/magma/pull/2891
