### ISSUE TITLE
[CI/CD] Prepare deployment manifests for Multus CNI on top of Kubernetes.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#2614]
Prepare deployment manifests for Multus CNI on top of Kubernetes.

For the larger context for the issue see [Roadmap](https://docs.google.com/document/d/1cu4XGxfW7e0n84Fm82-Se_0DuKmTb2_3Qvk0vg6jVUs).

**Comment by mattymo** [comment]
Covered in https://github.com/magma/magma/pull/2891
