### ISSUE TITLE
[CI/CD] Prepare deployment manifests for HA PostgreSQL on top of Kubernetes.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#2615]
[CI/CD] Prepare deployment manifests for HA PostgreSQL on top of Kubernetes.

For the larger context for the issue see [Roadmap](https://docs.google.com/document/d/1cu4XGxfW7e0n84Fm82-Se_0DuKmTb2_3Qvk0vg6jVUs).

**Comment by mattymo** [comment]
https://github.com/helm/charts/tree/master/incubator/patroni

I've got experience using Patroni. It's active/passive HA, but it works pretty well.

**Comment by mattymo** [comment]
This is currently blocked because users cannot log into NMS due to a bug when deploying with PostgreSQL
