### ISSUE TITLE
NMS Event Logging

### ISSUE THREAD

**Issue by jaredmullane** [magma/magma#2629]
### Your Environment

- **Version:** latest
- **Affected Component:** NMS
- **Affected Subcomponent:** NMS UI
- **Deployment Environment:** AWS (orc8r)

New events don't show up until you manually refresh the page (should be auto-refresh)

**To Reproduce**
1. Go to NMS
2. Click on Events page
3. Review logs to see if they update as new traffic comes in

**Expected behavior**
New logs are expected to populate in real time or auto refresh 

**Screenshots**
![118653361_247345176427849_4172667113546300629_n](https://user-images.githubusercontent.com/61836831/92159562-77694180-ede2-11ea-8d53-dcb5dcc7edec.png)

**Comment by karthiksubraveti** [comment]
https://github.com/magma/magma/pull/2741 fixes this issue
