### ISSUE TITLE
[PLMN Filter] Add a configuration to specify which subscribers are allowed to authenticate with an operator HSS

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#2646]
**Background on Federated-FWA Subscriber Authentication**
An AGW service `MME` talks to the `s6a_proxy` service in FeG, which sends Authentication requests to an operator HSS.
**Proposal** 
Add a configuration in `s6a_proxy` to support filtering out subscribers that should not be authenticated with the HSS. We can do this in a similar way that `AAA` in CWAG does this. 
```  
eap_aka:
    type: object
    description: eap_aka configuration
    properties:
      timeout:
        $ref: '#/definitions/eap_aka_timeouts'
      plmn_ids:
        type: array
        items:
          type: string
          minLength: 5
          maxLength: 6
          pattern: '^(\d{5,6})$'
          example: '123456'
```
We will add a similar `plmn_ids` config in `s6a`
```
  plmn_ids:
    type: array
    items:
      type: string
      minLength: 5
      maxLength: 6
      pattern: '^(\d{5,6})$'
      example: '123456'
  s6a:
    type: object
    description: s6a configuration
    properties:
      server:
        $ref: '#/definitions/diameter_client_configs'
      plmn_ids: 
        $ref: '#/definitions/plmn_ids'
    x-go-custom-tag: 'magma_alt_name:"S6A"'
```
This will be streamed down via the Mconfig and be used in the Authentication handler in s6a.

**Caveats**
- This plan currently does not involve migrating what exists in `AAA` to be handled in `swx_proxy`, though we can consider doing this later on.
- This plan does not involve any NMS changes.

**Comment by ssanadhya** [comment]
In a federated fixed wireless access (FFWA) setup, the FFWA users and the operator mobile users can share the same eNodeB. In such a scenario, the Magma core should reject attach requests from the mobile users. The network setup is as shown below:


![FFWA users sharing RAN](https://user-images.githubusercontent.com/1519854/92634894-d10db800-f289-11ea-8e45-00ea1a2f5d5e.jpg)

**Comment by themarwhal** [comment]
Assigning from @ssanadhya -> @uri200 :D

**Comment by uri200** [comment]
PR added. Note i will do more testing once it is in staging.... I have the feeling it will need some more work

https://github.com/magma/magma/pull/2774
