### ISSUE TITLE
Add/Edit Policy dialog component

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#2763]
https://www.figma.com/file/hw8iheccicYs6tW7gsFsPK/Magma-Client-Facing-Final-Design?node-id=361%3A65937

edit policy figma link - 
https://www.figma.com/proto/aRJzvSa3J9nhD2n3yERd1s/Magma---Phase-2-(Updated-Styles)?node-id=319%3A28181&scaling=min-zoom

Lock rating group to the default unrated group maybe?
Don't include redirect tab because I'm not so sure this feature still works anymore

**Comment by karthiksubraveti** [comment]
https://www.figma.com/file/hw8iheccicYs6tW7gsFsPK/Magma-Client-Facing-Final-Design?node-id=361%3A65937

Lock rating group to the default unrated group maybe?
Don't include redirect tab because I'm not so sure this feature still works anymore

**Comment by koolzz** [comment]
With the ipv6 introduction probably we probably want to tweak the design a bit -> https://github.com/magma/magma/pull/2833
