### ISSUE TITLE
Add support for multiple PLMN ids  in MME/AGW

### ISSUE THREAD

**Issue by anooptomar29** [magma/magma#278]

**Comment by annepak88** [comment]
@ssanadhya  - please assign to the right person on the team

**Comment by andreilee** [comment]
This is currently supported.

**Comment by jpad-freedomfi** [comment]
@andreilee Above you said this is currently supported. Is there documentation on how to configure multiple PLMNs in MME? E.g. I want to accept S1AP Setup Request from eNBs with 315010 or 00101 (just example PLMNs).
