### ISSUE TITLE
TestGxAbortSessionRequest failure

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#2807]
https://app.circleci.com/pipelines/github/magma/magma/3438/workflows/46410f40-7e5e-48ca-908c-d0e130a550b7/jobs/35088

**Comment by uri200** [comment]
example of this issue can be seen at 

https://app.circleci.com/pipelines/github/magma/magma/5620/workflows/60bb1239-891a-4e32-94ac-a3fa8e156f80/jobs/57621/tests
