### ISSUE TITLE
S1 setup failing when MME restarts in Magma VM

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#283]
If you run test_attach_detach.py after restarting MME on devVM, it fails with:

```FAIL: Basic attach/detach test with a single UE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_detach.py", line 31, in test_attach_detach
    self._s1ap_wrapper.configUEDevice(num_ues)
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 188, in configUEDevice
    self.check_gw_health_after_ue_load()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 220, in check_gw_health_after_ue_load
    self.init_s1ap_tester()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 83, in init_s1ap_tester
    self._s1setup()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 123, in _s1setup
    res = self._issue_s1setup_req()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 117, in _issue_s1setup_req
    s1ap_types.tfwCmd.ENB_S1_SETUP_RESP.value)
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
root: INFO: Adding subscriber : IMSI001010000000001
root: INFO: Adding subscriber : IMSI001010000000002
root: INFO: Deleting subscriber : IMSI001010000000001
root: INFO: Deleting subscriber : IMSI001010000000002
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 2.023s

FAILED (failures=1)```

**Comment by chenhao5651** [comment]
I run test_attach_detach.py, it fails whith :
```
ERROR: Basic attach/detach test with a single UE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chenhao/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_detach.py", line 20, in setUp
    self._s1ap_wrapper = s1ap_wrapper.TestWrapper()
  File "/home/chenhao/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 61, in __init__
    self._sub_util.clean_up()
  File "/home/chenhao/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 286, in clean_up
    self._subscriber_client.clean_up()
  File "/home/chenhao/magma/lte/gateway/python/integ_tests/common/subscriber_db_client.py", line 168, in clean_up
    for sid in self.list_subscriber_sids():
  File "/home/chenhao/magma/lte/gateway/python/integ_tests/common/subscriber_db_client.py", line 163, in list_subscriber_sids
    sids = ['IMSI' + sid.id for sid in sids_pb]
TypeError: 'NoneType' object is not iterable
-------------------- >> begin captured logging << --------------------
root: INFO: Importing mconfig module orc8r.protos.mconfig.mconfigs_pb2
root: INFO: Importing mconfig module lte.protos.mconfig.mconfigs_pb2
root: INFO: Importing mconfig module feg.protos.mconfig.mconfigs_pb2
root: WARNING: Subscriberdb unavailable, retrying...
root: WARNING: Subscriberdb unavailable, retrying...
root: WARNING: Subscriberdb unavailable, retrying...
root: WARNING: Subscriberdb unavailable, retrying...
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```
It seems that can't contect to Subscriberdb,how can fix it?

**Comment by chenhao5651** [comment]
> If you run test_attach_detach.py after restarting MME on devVM, it fails with:
> 
> ```
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_detach.py", line 31, in test_attach_detach
>     self._s1ap_wrapper.configUEDevice(num_ues)
>   File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 188, in configUEDevice
>     self.check_gw_health_after_ue_load()
>   File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 220, in check_gw_health_after_ue_load
>     self.init_s1ap_tester()
>   File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 83, in init_s1ap_tester
>     self._s1setup()
>   File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 123, in _s1setup
>     res = self._issue_s1setup_req()
>   File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 117, in _issue_s1setup_req
>     s1ap_types.tfwCmd.ENB_S1_SETUP_RESP.value)
> AssertionError:
> -------------------- >> begin captured logging << --------------------
> root: ERROR: Could not load magmad yml config for mconfig modules
> root: INFO: Adding subscriber : IMSI001010000000001
> root: INFO: Adding subscriber : IMSI001010000000002
> root: INFO: Deleting subscriber : IMSI001010000000001
> root: INFO: Deleting subscriber : IMSI001010000000002
> --------------------- >> end captured logging << ---------------------
> 
> ----------------------------------------------------------------------
> Ran 1 test in 2.023s
> 
> FAILED (failures=1)```
> ```

I have the same problem, have you fixed it?

**Comment by ssanadhya** [comment]
Closing this issue as it does not happen on latest master
