### ISSUE TITLE
[ovs][bug] ovs rules are not created sometimes for few bearers after UE moves from idle to connected state

### ISSUE THREAD

**Issue by pruthvihebbani** [magma/magma#2852]
### Your Environment

Version: Local Development Setup
Affected Component: Access Gateway
Affected Subcomponent: Magma SPGW service
Deployment Environment: Vagrant (AGW)

### Describe the Issue
When a UE with multiple sessions and dedicated bearers transitions from idle to connected mode, sometimes OVS rules are not created for few bearers. This issue is random and mostly observed on multiple execution of the test case

**To Reproduce**
Execute the TCs in PR #2521 multiple times

**Expected behavior**
OVS rules should be created for all the pre-existing PDNs(sessions) and dedicated bearers when UE moves back from idle to connected state
MME log:
[test_attach_service_with_multi_pdns_and_bearers.txt](https://github.com/magma/magma/files/5391614/test_attach_service_with_multi_pdns_and_bearers.txt)

**Comment by pshelar** [comment]
@pruthvihebbani do you have MME logs for this bug.

**Comment by pruthvihebbani** [comment]
@pshelar @ulaskozat These TCs are stable on the latest master. Added them to sanity suite. Closing the issue

**Comment by pruthvihebbani** [comment]
@pshelar @ulaskozat These TCs are stable on the latest master. Added them to sanity suite. Closing the issue
