### ISSUE TITLE
[nms] Add support for update tier specification

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [magma/magma#2930]
### Your Environment

- **Version:** 1.2
- **Affected Component:** NMS
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

Add support to edit update tier for AGW. Currently, it is possible to specify it only via JSON Config.

**To Reproduce**
1. Go to 'Equipment'
2. Scroll down to 'Gateways'
3. Click on some gateway
4. Click on 'Config'

**Expected behavior**
There is a field with the current update tier and a way to edit it.

**Actual behavior**
Currently, it is possible to edit the update tier only via "Edit JSON"

**Comment by karthiksubraveti** [comment]
@berezovskyi-oleksandr Thanks for checking out the NMS. Let me know if you have any additional feedback here

I have added steps here, Can you check if this works. Can you post a screenshot or recording of the failure. 

https://magma.github.io/magma/docs/nms/nms_equipment#upgrading-an-existing-gateway

**Comment by berezovskyi-oleksandr** [comment]
@karthiksubraveti Thanks for your answer. It shows the way to update a version of the particular tier.

It seemd that I hadn't explain the issue correctly. The problem is that you can't change particular AGW's tier throught the UI. There was an option for this at NMS 1.1, but not available at NMS 1.2.

Currently there is only way to change the AGW Tier is to change it via JSON configuration editing.

**Comment by karthiksubraveti** [comment]
@berezovskyi-oleksandr does this work ?
![Screen Shot 2020-10-06 at 6 46 11 AM](https://user-images.githubusercontent.com/8224854/95209865-ad159780-079f-11eb-864e-32ac89a933ff.png)

If you go to "Upgrade view" of the gateways, You have an editable tier information. 
More screenshots on how to do it
![Screen Shot 2020-10-06 at 6 48 17 AM](https://user-images.githubusercontent.com/8224854/95210137-067dc680-07a0-11eb-8c93-f5d926eb6952.png)
![Screen Shot 2020-10-06 at 6 48 31 AM](https://user-images.githubusercontent.com/8224854/95210141-07aef380-07a0-11eb-9ce6-c928c36a7cf1.png)
![Screen Shot 2020-10-06 at 6 48 39 AM](https://user-images.githubusercontent.com/8224854/95210143-08478a00-07a0-11eb-976e-2848c970196e.png)

**Comment by karthiksubraveti** [comment]
Let me know if this is still missing the point. Thanks

**Comment by berezovskyi-oleksandr** [comment]
Yeah, I've now found that! Thanks!
