### ISSUE TITLE
[Magma] [Bug] Data test case fails if default UE IP subnet is changed

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#2965]
### Your Environment

- **Version:** Local Development Setup
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Magma MME/SPGW service
- **Deployment Environment:** Vagrant (AGW)

### Setup Details

The S1APTester ([https://github.com/facebookexperimental/S1APTester](https://github.com/facebookexperimental/S1APTester)) was used along with Magma EPC in Vagrant based setup to reproduce the issue.

### Describe the Issue

The s1ap_wrapper.py file contains UE IP subnet configuration with parameter "TEST_IP_BLOCK". When this configuration is modified, all the basic 3GPP procedure test cases pass perfectly fine, however, the data test cases get stuck and do not pass.

**To Reproduce**
1) Modify TEST_IP_BLOCK value in s1ap_wrapper.py file
2) Run any data test case

**Comment by VinashakAnkitAman** [comment]
Logs and packet capture attached here. Some additional prints will be present in ERROR mode for debugging purpose.

[data_test_failure_ue_subnet_change.zip](https://github.com/magma/magma/files/5850746/data_test_failure_ue_subnet_change.zip)

**Comment by ssanadhya** [comment]
@VinashakAnkitAman , can you confirm if this issue is still happening? If not, please close this issue.

**Comment by VinashakAnkitAman** [comment]
> @VinashakAnkitAman , can you confirm if this issue is still happening? If not, please close this issue.

Hi @ulaskozat The issue is still present. I am attaching here the logs and pcap file for the issues:
[issue_ue_ip_subnet.zip](https://github.com/magma/magma/files/6285820/issue_ue_ip_subnet.zip)

From the S1APTester_terminal_logs, it  can be seen that for first 2 executions with default UE IP subnet (TEST_IP_BLOCK = "192.168.128.0/24"), the test case is running fine. But for the 3rd execution, when UE IP subnet is changed to "192.168.128.0/20" in s1aptests/s1ap_wrapper.py, the test case fails to send and receive data. The UE IP assigned in 3rd execution is out of default subnet range (192.168.143.157)

The UE IP interface can be seen created in S1APTester VM:
```
eth2:UE1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.143.157  netmask 0.0.0.0  broadcast 0.0.0.0
        ether 08:00:27:cd:03:fa  txqueuelen 1000  (Ethernet)
```

Following is the OVS rules dump (sudo ovs-ofctl dump-flows gtp_br0 | grep "table=0")
```
 cookie=0x0, duration=52.128s, table=0, n_packets=6, n_bytes=360, idle_age=20, priority=10,tun_id=0x3,in_port=3 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x3->NXM_NX_REG9[],load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=52.128s, table=0, n_packets=0, n_bytes=0, idle_age=52, priority=10,ip,in_port=LOCAL,nw_dst=192.168.143.157 actions=load:0xa000128->NXM_NX_TUN_ID[],load:0xc0a83c8d->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x3->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=52.128s, table=0, n_packets=0, n_bytes=0, idle_age=52, priority=10,ip,in_port=15577,nw_dst=192.168.143.157 actions=load:0xa000128->NXM_NX_TUN_ID[],load:0xc0a83c8d->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x3->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=52.128s, table=0, n_packets=12, n_bytes=504, idle_age=18, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.143.157 actions=load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=52.128s, table=0, n_packets=0, n_bytes=0, idle_age=52, priority=10,arp,in_port=15577,arp_tpa=192.168.143.157 actions=load:0x7594587a00d->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=139.208s, table=0, n_packets=3, n_bytes=210, idle_age=12, priority=0,in_port=15578 actions=resubmit(,201)
 cookie=0x0, duration=139.208s, table=0, n_packets=69, n_bytes=5359, idle_age=13, priority=0 actions=resubmit(,1)
```

In the beginning I thought following route in TRF Server is creating problem:
```
default via 10.0.2.2 dev eth0
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
192.168.60.0/24 dev eth1 proto kernel scope link src 192.168.60.144
192.168.128.0/24 via 192.168.129.1 dev eth2
192.168.129.0/24 dev eth2 proto kernel scope link src 192.168.129.42
```

So I updated the route as per my UE IP subnet with following command:
```
sudo ip route flush via 192.168.129.1 && sudo ip route add 192.168.128.0/20 via 192.168.129.1 dev eth2
```
