### ISSUE TITLE
XWF CI pipeline broken. No arp requests seen on uplink_br0

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#2988]
Arp requests aren't seen on the uplink_br0. This is causing hourly xwfm jobs to fail. Current suspect is https://github.com/magma/magma/commit/fa8044eaf6b962e04afff03fc7af8627c82275ff

**Comment by karthiksubraveti** [comment]
@pshelar @koolzz @AyliD @aharonnovo

**Comment by karthiksubraveti** [comment]
https://app.circleci.com/pipelines/github/magma/magma/4298/workflows/c0060764-998e-45e2-a24b-afc03277d3fe/jobs/44321

**Comment by pshelar** [comment]
Can we revert the patch locally and retry the test?
