### ISSUE TITLE
IPv6 support (UE)

### ISSUE THREAD

**Issue by bbarritt** [magma/magma#2999]
- GTP IPv6 support (UE IPv6 + DL Flow Rule IPv6)
- Pipelined support and debug
- MME control plane changes
- IPv6 address allocation, configurations (pool, DNS, P-CSCF)
- sessiond and FEG support and debug
- eNB + S1 + SGI Ipv6
- VoLTE IMS integration with ipv6 and dual stack UEs
- IPv6 to Ipv4 natting

**Comment by adarshs-magma** [comment]
This will be required for migrating Magma network from lab to production environment. Facebook Data Centers require devices to be fully IPv6 compliant. IPv6 is currently supported for UE allocation but not SGi and will need to be added to the Magma roadmap for Q3 or risk having to alter timelines. IPv6 support on SGi and S1-U will need to be supported at some point. UE traffic should fully expect to be NAT64d.

**Comment by lpavao** [comment]
@jaredmullane : whats the required date for this from CBRS/FB deployment?

**Comment by jaredmullane** [comment]
@lpavao best estimated based on all the information we have now the target would be mid-October. However, there are some non-Magma dependencies both moving servers into more secure network locations and also timelines from internal penetration testing that could come into play. We should know better in the next two weeks.
