### ISSUE TITLE
[or8r] apn_resource management is broken

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [magma/magma#3009]
### Your Environment

- **Version:** 1.2
- **Affected Component:** Orchestrator, Access Gateway
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the Issue

I'm trying to setup Multi-APN IP Allocation according to the [docs](https://magma.github.io/magma/docs/howtos/config_agw_bridged#experimental-multi-apn-ip-allocation).

I've done the first step and added `enable_multi_apn_ip_allocation` option.

Then on the second step, I tried to create multiple `apn_resources`:
```
    "apn_resources": {
        "management": {
            "apn_name": "management",
            "gateway_ip": "192.168.9.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "management_apn_resource",
            "vlan_id": 12
        },
        "internet": {
            "apn_name": "internet",
            "gateway_ip": "192.168.10.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "internet_apn_resource",
            "vlan_id": 13
        }
    }
```
Once I update the gateway configuration with a new object with that `apn_resources`, I get an error:
 `{  "message": "an entity (apn_resource-internet_apn_resource) already exists"}`.
Once I swop these two entries, I get the opposite error with "management already exists".

Adding one `apn_resources` actually work and update succeed, but once I'm trying to get the gateway configuration, the `apn_resources` section is empty.

I skipped this step and moved forward to AGW Management Traffic and this step works great. 
Here is the drawing of what we want to achieve:
![image](https://user-images.githubusercontent.com/221562/94830151-f10d4300-0413-11eb-9e19-70664ca8befc.png)

**Comment by zer0tweets** [comment]
@pshelar would you please take a look ^^

**Comment by andreilee** [comment]
Can you try modifying the `"id"` field for each `"apn_resource"`? There's some other entity stored with a matching `"id"`, which is preventing the creation. The ID should be globally unique. It might have been from a separate gateway that was configured earlier with matching `apn_resource` IDs.

The version of `v1.2` I was testing with was pulled today

**Comment by berezovskyi-oleksandr** [comment]
I've modified `"id"` field for each `"apn_resource"` as you suggested by appending current date:
```
    "apn_resources": {
        "management": {
            "apn_name": "management",
            "gateway_ip": "192.168.9.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "management_apn_resource_10_05_2020",
            "vlan_id": 12
        },
        "internet": {
            "apn_name": "internet",
            "gateway_ip": "192.168.10.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "internet_apn_resource_10_05_2020",
            "vlan_id": 13
        }
    }
```

Here is the output from API:
![image](https://user-images.githubusercontent.com/221562/95077870-e3f69980-071c-11eb-9fc9-b3f5be9c86b8.png)

I'm 100% sure, that there was no `"apn_resource"` with such `"id"` before.

**Comment by andreilee** [comment]
Okay I managed to replicate the issue you're facing, and you should be able to mitigate it for now by adding the apn resources one at a time, first PUT with

```
"apn_resources": {
        "management": {
            "apn_name": "management",
            "gateway_ip": "192.168.9.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "management_apn_resource_10_05_2020",
            "vlan_id": 12
        }
}
```

and the second PUT with 
```
"apn_resources": {
        "management": {
            "apn_name": "management",
            "gateway_ip": "192.168.9.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "management_apn_resource_10_05_2020",
            "vlan_id": 12
        },
        "internet": {
            "apn_name": "internet",
            "gateway_ip": "192.168.10.1",
            "gateway_mac": "e0:63:da:22:47:21",
            "id": "internet_apn_resource_10_05_2020",
            "vlan_id": 13
        }
    }
```

Let me know if this works

We'll be putting in the proper patch soon

**Comment by jpad-freedomfi** [comment]
Hi Andrei, 

I tried the 2 PUT method you mentioned above, with unique strings for "id" value (added time to the end of date). 

First PUT gets 204, second PUT get 500, indicating that internet apn (the second to be added) already exists. 

Here is curl:
[curl_2nd_PUT.txt](https://github.com/magma/magma/files/5331349/curl_2nd_PUT.txt)

and reply
```
{
  "message": "an entity (apn_resource-internet_apn_resource_10_05_2020_2200) already exists"
}
```

I notice you mention you are using v1.2 pulled "today" which was 3 days ago. Our v1.2 is the tagged release from 9/24. Any chance you have later code in key areas for this issue? 

Also, when we do a GET for /lte/{network_id}/gateways/{gateway_id} we get empty set for apn_resources even after the 204 in first PUT. Does the same happen for you?

**Comment by andreilee** [comment]
At this point I'd recommend that you try again tomorrow after we finish merging in the patch for this reported issue and https://github.com/magma/magma/issues/3088

---

> Our v1.2 is the tagged release from 9/24. Any chance you have later code in key areas for this issue?

I don't see any key code changes since then for 1.2 - `https://github.com/magma/magma/commits/v1.2`

---

> Also, when we do a GET for /lte/{network_id}/gateways/{gateway_id} we get empty set for apn_resources even after the 204 in first PUT. Does the same happen for you?

After the first PUT and 204, the GET shows the apn_resource for me. I haven't been able to replicate this sub-issue you're seeing. Are you able to replicate that consistently? Tagging @hcgatewood for visibility
