### ISSUE TITLE
[orc8r] Can't get DHCP address with `sgi_management_iface_vlan` being set

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [magma/magma#3046]
### Your Environment

- **Version:** 1.2
- **Affected Component:** Orchestrator, Access Gateway
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the Issue

I'm following [the documentation](https://magma.github.io/magma/docs/howtos/config_agw_bridged#agw-management-traffic).

My aim is to get a management interface to get an IP via DHCP while it has VLAN on the port. So my configuration looks like:
```
    "epc": {
      "ip_block": "192.168.128.0/24",
      "nat_enabled": false,
      "sgi_management_iface_vlan": "2"
    }
``` 

According to pipelined logs, it sends "DHCPDISCOVER" and never gets "DHCPOFFER".
I've started wireshark at two interfaces: `eth0` (outgoing physical interface) and `uplink_br0`.

At the `eth0` port packet log everything seems OK. There are both "DHCPDISCOVER" and "DHCPOFFER" in place and wrapped into VLAN 2.
<details>
  <summary>Wireshark screenshots</summary>

![image](https://user-images.githubusercontent.com/221562/95105119-5e381580-073f-11eb-80dc-dc5ceaa65b22.png)
![image](https://user-images.githubusercontent.com/221562/95105147-65f7ba00-073f-11eb-96d4-7150e1f260ad.png)

</details>

At the `uplink_br0` port packet log still both "DHCPDISCOVER" and "DHCPOFFER" are in place, but "DHCPDISCOVER" is not wrapped into VLAN 2 (as it should be), but "DHCPOFFER" is received still wrapped into VLAN 2. I believe that this is the root cause, that `uplink_br0` can't get IP via DHCP.
<details>
  <summary>Wireshark screenshots</summary>

![image](https://user-images.githubusercontent.com/221562/95105410-cedf3200-073f-11eb-9300-7a6694922a65.png)
![image](https://user-images.githubusercontent.com/221562/95105427-d6064000-073f-11eb-8ab0-fe412e016e47.png)

</details>

I also gathered some info from OVS that could help:
<details>
  <summary>OVS configuration</summary>

```
magma@agw:~$ sudo ovs-vsctl show
a43cbd76-bf26-440d-b832-1c2a4093961d
    Bridge "uplink_br0"
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port vlan_pop_in
            Interface vlan_pop_in
        Port "eth0"
            Interface "eth0"
        Port "uplink_br0"
            tag: 2
            Interface "uplink_br0"
                type: internal
        Port "dhcp0"
            Interface "dhcp0"
                type: internal
        Port vlan_pop_out
            Interface vlan_pop_out
    Bridge "gtp_br0"
        Controller "tcp:127.0.0.1:6633"
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        fail_mode: secure
        Port "ipfix0"
            Interface "ipfix0"
                type: internal
        Port "gtp_br0"
            Interface "gtp_br0"
                type: internal
        Port "mtr0"
            Interface "mtr0"
                type: internal
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port "gtp0"
            Interface "gtp0"
                type: gtp
                options: {key=flow, remote_ip=flow}
    ovs_version: "2.8.9"
magma@agw:~$ sudo ovs-ofctl dump-flows uplink_br0
 cookie=0x0, duration=34.026s, table=0, n_packets=4, n_bytes=1384, priority=65535,udp,in_port=eth0,tp_dst=68 actions=output:dhcp0,output:"patch-agw",LOCAL
 cookie=0x0, duration=34.009s, table=0, n_packets=0, n_bytes=0, priority=100,ip,in_port="patch-agw" actions=mod_dl_src:da:6a:1c:f3:80:43,output:eth0
 cookie=0x0, duration=33.993s, table=0, n_packets=0, n_bytes=0, priority=100,ip,in_port=eth0,vlan_tci=0x0000/0x1000,dl_dst=da:6a:1c:f3:80:43 actions=output:"patch-agw"
 cookie=0x0, duration=33.980s, table=0, n_packets=0, n_bytes=0, priority=100,ip,in_port=eth0,vlan_tci=0x1000/0x1000,dl_dst=da:6a:1c:f3:80:43 actions=strip_vlan,output:"vlan_pop_in"
 cookie=0x0, duration=33.966s, table=0, n_packets=0, n_bytes=0, priority=100,ip,in_port="vlan_pop_out",dl_dst=da:6a:1c:f3:80:43 actions=output:"patch-agw"
 cookie=0x0, duration=33.954s, table=0, n_packets=4, n_bytes=1384, priority=100,in_port="vlan_pop_in" actions=drop
 cookie=0x0, duration=33.940s, table=0, n_packets=4, n_bytes=1384, priority=1,in_port="vlan_pop_out" actions=drop
 cookie=0x0, duration=33.926s, table=0, n_packets=22, n_bytes=2485, priority=0 actions=NORMAL
magma@agw:~$ sudo ovs-ofctl dump-flows gtp_br0
 cookie=0x0, duration=950.649s, table=0, n_packets=233, n_bytes=64378, priority=0 actions=resubmit(,1)
 cookie=0x0, duration=950.649s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,201)
```
  </details>

**Comment by pshelar** [comment]
@berezovskyi-oleksandr Can you try latest magma code from branch-1.2. also post dump flows from uplink_br0: `sudo ovs-ofctl dump-flows uplink_br0`

**Comment by berezovskyi-oleksandr** [comment]
@pshelar , I've updated AGW python stuff onto latest 1.2 and it works great now. Thanks
