### ISSUE TITLE
[orc8r] Can't handle more than 18 thousands subscribers.

### ISSUE THREAD

**Issue by edaspb** [magma/magma#3054]
### Your Environment

- Version:1.2.0
- Affected Component: Orchestrator
- Affected Subcomponent: Controller
- Deployment Environment: local docker-compose (orc8r)

### Describe the Issue

When I add more than 18k subscribers (approx) the error occurs:

1. With MariaDB as a database for controller:

`Error 1390: Prepared statement contains too many placeholders`
Looks like DB limitation

2. Using postgres:

`lte stderr | E1001 19:58:55.707561     105 handler.go:116] [ERROR /magma.orc8r.streamer.StreamProvider/GetUpdates]: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4265976 vs. 4194304)`

I believe it is due to grpc client configuration and can be tuned.

To Reproduce
1. Add about 18 thousands subscription
2. Check controller's pod logs

**Comment by hcgatewood** [comment]
We need to define the intended subscriber count per network we desire to support. That will determine how many of the below-listed steps we need to take.

Next steps for increasing the 18k cap, ordered by ease of implementation:

1. Increase max gRPC message size in orc8r
1. Mconfig builders should receive their entity graph pre-filtered to the desired types
1. Subscriber stream should only return subscriber info relevant to the particular requesting gateway

**Comment by edaspb** [comment]
What the cons of first the most strict and easy way - increase max gRPC message size?
The third one in my opinion contradicts to mobile conception. For example, s1-flex principals base on pseudo random AGW selection, where we don't know which AGW which subscriber will serve.
