### ISSUE TITLE
Inaccurate enodeb status

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#314]
enodeb_cli reports that there is no enodeb connected while the cell is actually connected and transmitting. There's SCTP traffic on the interface.

```magma: 0.3.71-1555979248-a98bf0c9```

```
$ enodebd_cli.py get_status
eNodeB connected: 0
eNodeB configured: 0
Opstate enabled: 0
RF TX on: 0
GPS connected: 0
PTP connected: 0
MME connected: 0
GPS Longitude: 0
GPS Latitude: 0
FSM State: Disconnected
```
![Selection_109](https://user-images.githubusercontent.com/6918709/58902506-e2255c00-870b-11e9-964f-0fe0322a37cf.png)

**Comment by bmurithi** [comment]
This is invalid - it appears to be resolved by correcting the management server configuration which appears to be resetting.

**Comment by andreilee** [comment]
What was the management server configured to? Service enodebd won't be able to detect eNB connection if the management server setting is incorrect.

**Comment by bmurithi** [comment]
It was configured to the correct value but appears to have reset to this.

baiomc.cloudapp.net:8080

Feels like an enodeb issue as far as I can tell. I've had reconfigure it
twice over the past month. Observing this unit going forward.

**Comment by andreilee** [comment]
Okay, I'll close this issue then, since we don't have reason to believe it's an enodebd problem.

**Comment by bmurithi** [comment]
@andreilee this is still recurring as at `0.3.78-1567853565-a69a32fa`

The management server settings are correct and the eNodeB is reporting periodically to the gateway.

```
 [18/Sep/2019:18:15:02 +0000] "POST /A20190918.1810%2B0000-1815%2B0000_48BF74.120200004917CNJ0012.xml HTTP/1.1" 200 0 "-" "-"
```

It feels like the case we are seeing here is that the eNodeB has already been configured and is on for an extended period of time while enodebd has lost state through reboot of the gateway or service restart.

![sshot_20190918_3](https://user-images.githubusercontent.com/6918709/65174892-75d02d80-da5a-11e9-9ac2-40f79ca8facb.png)

![enodeb_status](https://user-images.githubusercontent.com/6918709/65175110-e119ff80-da5a-11e9-89c6-4ccbcd1ed0e7.png)
