### ISSUE TITLE
CDR Support

### ISSUE THREAD

**Issue by bbarritt** [magma/magma#3155]

**Comment by themarwhal** [comment]
The goal is to complete this event log from SessionD on session terminations

session_terminated:
    type: object
    description: Used to track when a session was terminated
    properties:
      timestamp:
        type: string
        description: 'analogous to "Record Opening Time"'
      node_id:
        type: string
      duration:
        type: string
        description: 'termination timestamp - create timestamp'
      msisdn:
        type: string
      imsi:
        type: string
      imei:
        type: string
      charging_characteristic:
        type: string 
      user_location_info:
        type: string      
      session_id:
        type: string
        description: 'analogous to "Charging_ID"'
      Record Sequence Number:
        type: string
      cause_for_rec_closing:
        type: string
      apn:
        type: string
      ip_addr:
        type: string
      list_of_service_data:
        type: object
        description: 'Used to track traffic per rating_group'
        properties:
          rating_group:
            type: string
          data_volume_downlink:
            type: string
          data_volume_uplink:
            type: string
          service_condition_change:
            type: string
          time_of_first_usage:
            type: string
          time_of_last_usage:
            type: string

**Comment by themarwhal** [comment]
All necessary PRs are landed for now. Will test an re-open this issue if we notice any breakages.

**Comment by themarwhal** [comment]
Re-opening there are 2 remaining PRs for this feature.

**Comment by themarwhal** [comment]
😡 feature still not done since there is 2 remaining PRs

**Comment by ekowtaylor** [comment]
Please add estimates

**Comment by themarwhal** [comment]
Done!
