### ISSUE TITLE
Recover from corrupted state:

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#3159]
If a stateless service fails to start due to a bad Redis state, it will continue crash-looping. We need to capture this event and restart Sctpd service, so that all services are stopped, Redis state is cleared and then services are started.

Overview:
1. Enable health service on the AGW
2. Create health monitoring job that'll (will be stubbed into health service):
       Poll service systemd status every certain configurable interval
3. Define a threshold to identify cycle of service restart due to corrupted state or other reason
4. Trigger restart of sctpd service => which will take care of flushing redis (as of now it flushes everything, one improvement can be restricting to AGW state data)
5. Create alert for cycle of service restart to monitor and trace issue
6. Take a snapshot of the Redis data-store before clearing it, for post-mortem analysis.

**Comment by ardzoht** [comment]
For point 4), that is already tracked and in progress on https://github.com/magma/magma/pull/3165

**Comment by ekowtaylor** [comment]
Covered by https://github.com/magma/magma/pull/3460
