### ISSUE TITLE
clean up work from OAI project for CentOS 8 and integrate to main codebase (make build_oai)

### ISSUE THREAD

**Issue by sanazbazargan** [magma/magma#3197]
clean up work from OAI project for CentOS 8 and integrate to main codebase (make build_oai)
3) the following lte/gateway/Makefile targets
  - make build_python
  - make build_common
  - make build_sctpd
  - make build_session_manager

**Comment by pshelar** [comment]
We also need to build OVS, lets use OVS 2.14: https://github.com/magma/magma/tree/master/third_party/gtp_ovs/ovs-gtp-patches/2.14
