### ISSUE TITLE
Dynamically generate nginx ingress proxy configuration from Docker/Kubernetes API

### ISSUE THREAD

**Issue by xjtian** [magma/magma#3205]
We still build the nginx ingress configuration from the `service_registry.yml` files that each module provides. After we deploy the new Helm charts, we should instead pull the port mappings from Docker/k8s APIs (back the ingress config generation with service discovery).

Just a thought: since we're defining standard frontend ports for all the services in the mesh, I think we can actually probably just have a static configuration block in nginx instead.

**Comment by mpgermano** [comment]
Given that we've standardized on ports, we should be able to just use a static block in the config.
