### ISSUE TITLE
TestGyCreditExhaustionRedirect failure

### ISSUE THREAD

**Issue by uri200** [magma/magma#3211]

**Comment by talkhasib** [comment]
Reopening as this test seems to be flaky on CI
Check the following two recent runs
https://storage.googleapis.com/magma-ci.appspot.com/cwf_integ_test_d662c17650f53feab3edc89a782994144272a346.html
https://storage.googleapis.com/magma-ci.appspot.com/cwf_integ_test_ad5e806263b1caf213c39b95e85834b1879982cc.html
