### ISSUE TITLE
Add cAdvisor and node_exporter to carrier wifi gateways (feg/cwag)

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#3224]
### Your Environment

- **Version:** 1.3 and newer
- **Affected Component:** CWAG, FeG
- **Affected Subcomponent:** Metrics
- **Deployment Environment:** on-prem 

### Describe the Issue

node_exporter and cAdvisor need to be deployed and made part of the stock configuration so that gateways come up for the first time with these reporting. 

**To Reproduce**
NA

**Expected behavior**
Docker cAdvisor and node_exporter deployed via docker-compose

**Screenshots**
NA

**Additional context**
NA

**Comment by karthiksubraveti** [comment]
With cwf deprioritization, I don't think we can work on this issue for now. Closing it for now.
