### ISSUE TITLE
[lte][agw] MME crash during decoding Tracking Area Update Request

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#3235]
### Your Environment

- **Version:** v1.1 (potentially for v1.2 and v1.3)
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

MME is reported to crash on AGW v1.1 with the following syslog summary message about the crash:
`SUMMARY: AddressSanitizer: heap-buffer-overflow /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/msg/TrackingAreaUpdateRequest.c:79 in decode_tracking_area_update_request`

**To Reproduce**
There are no clear steps to reproduce the issue. The issue will be updated once this issue can be locally reproduced.

**Expected behavior**
No crash.

**Comment by attritionorg** [comment]
@ulaskozat If you can reproduce, can you include full ASAN output please?
