### ISSUE TITLE
Traffic forwarding errors in AGW Bridge Mode

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3242]
### Your Environment

- **Version:** v1.3 (AGW version 1.3.0-1602477016-723feee0)
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** pipelined, ovs-system
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)
- **Equipment** Baicells 436Q SW:2.3.6, Baicells Atom Cat 4 CPE SW: BaiCE_AP_2.1.4_NA

@pshelar and @berezovskyi-oleksandr FYI

### Describe the Issue

We are testing AGW Bridge Mode. We are trying to get to Multi-APN configuration. 

At this point, we have single APN configured (while in Multi-APN mode), with static IP on AGW mgmt interface with VLAN and DHCP for APN IP. See diagram. 

UE is able to attach and pass TCP data. Non-DNS UDP data inbound to UE fails with ICMP port unreachable. This seems to effect many apps, e.g. Apple Messages, FaceTime, Zoom, Speedtest all fail. Web pages and other TCP based traffic work. 

**To Reproduce**
1. Configure AGW for NAT disabled ([following guide here](https://magma.github.io/magma/docs/howtos/config_agw_bridged))
2. Add APN resource with a VLAN tag via NMS
3. Attach UE with single bridged APN 
4. start tcpdump on all interfaces of AGW ('_-i any_' flag)
4. Attempt to ping UE IP from PC northbound of AGW
5. Attempt to SNMP query system info on UE IP. 
6. Notice ICMP port unreachable reply from AGW, and notice inconsistent data path of ICMP packets. 

See attached pcap file of ICMP and SNMP query captured on "any" interface in AGW. 
https://drive.google.com/file/d/1-CqG5EadKhprNQUnk1ugV4WQOr3IiAzO/view?usp=sharing 

ICMP seq = 0 you see the request 7 times, seq = 1 only 5 times. Packet 6 appears to have VLAN tag 2 which should not be applied to APN internet traffic (should be VLAN 12 only). Then SNMP query it returned with ICMP port unreachable. 

**Expected behavior**
Expected behavior is clean data path for both TCP and UDP based traffic to UE IP when in bridged mode. 

**Screenshots**
See diagram of test setup. 
![AGW Bridge vs  NAT-Dual SGi UDP Test Net](https://user-images.githubusercontent.com/61293007/96088335-8253cf00-0e82-11eb-9bab-929f93ecd9a2.png)

**Additional context**
AGW JSON via orc8r shows:
```
"root":{
      "apn_resources":{
           "internet":{
              "apn_name":"internet"
              "id":"internet_resource12"
               "vlan_id":12
       }
}
"cellular":{
        "epc":{
            "ip_block":"192.168.128.0/24"
             "nat_enabled":false
             "sgi_management_iface_gw":"192.168.2.1"
             "sgi_management_iface_static_ip":"192.168.2.26/24"
             "sgi_management_iface_vlan":"2"
        }
      "ran":{
            "pci":260
            "transmit_enabled":true
        }
}
```
Also, API for VLAN tag for mgmt iface only accepts string vs. VLAN tag for APN resource configured via NMS is an integer.

Syslog attached. 
https://drive.google.com/file/d/1-Iu5NwZXQhzgJgtiF2Q4a7LWx46sHyFb/view?usp=sharing

**Comment by pshelar** [comment]
AGW datapath configures IP protocol level flows. so flows that handle TCP also handles UDP traffic.

Have you configured any policy rule for UDP protocol ?

**Comment by pshelar** [comment]
@jpad-freedomfi can you run tcpdump on eth0 (sgi interface) to trace UDP traffic `sudo tcpdump -eni eth0 udp`.
This way we can validate if traffic is egressing SGi interface or not.

**Comment by jpad-freedomfi** [comment]
@pshelar We found the problem. MSS clamping isn't working for a host plugged into a CPE UE. When we manually set the MTU for Macbook a.k.a. "Customer host" in diagram above, all data works fine. 

We'll update if we find a way to make this automatic.

**Comment by jpad-freedomfi** [comment]
See comment above for resolution here.
