### ISSUE TITLE
Mobility Restriction based on ECGI Area (+ dynamic rule)

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3264]

**Comment by themarwhal** [comment]
We want to track 2 things related to location based service restriction in this task:
1. ECGI should be sent to PCRF as part of CCR-I  (about 1 day)
    - The PCRF will use this information to decide whether the user is allowed or redirected. 
2. Gx based redirection should be tested. (about 1 day to confirm the feature is working)
    - This means a PolicyRule install by PCRF with redirection fields filled out should work.

**Comment by themarwhal** [comment]
Confirming 1 is done.

**Comment by ekowtaylor** [comment]
Any updates about 2?

**Comment by themarwhal** [comment]
Confirmed the Gx policy based redirection is working. 
Note: the feature only works to redirect away from HTTP websites not HTTPS. 
Policy I tested with:
```
{
  "flow_list": [],
  "id": "gx_redirect_rule",
  "priority": 1,
  "redirect": {
    "address_type": "URL",
    "server_address": "http://example.com/",
    "support": "ENABLED"
  },
  "tracking_type": "NO_TRACKING"
}
```

Once the policy was enabled, accessing any of neverssl.com apache.org redirected properly to example.com.
With Google.com / Youtube.com it just hangs.
