### ISSUE TITLE
Inbound roaming

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3277]
This is an umbrella issue to cover all activity adding Inbound Roaming support in Magma

**Comment by ssanadhya** [comment]
Roaming support allows mobile users from one operator network to access services while visiting areas outside their network coverage. In this document, we consider the use case when a subscriber of a network operator MNOH (home network) tries to access LTE services while visiting an area covered by operator MNOV (visiting network) who use Magma core.

Currently, the Magma Access Gateway (AGW) implements a merged SGW+PGW (SPGW) task without any support for inbound/outbound roaming. The goal of this document is to add S6a and S8 interface support in AGW and federate it with the core of MNOH for both control and user plane management.

Here we assume that the Magma MME will be federated to the MNOV core network (HSS) and is also federated with the MNOH (HSS and PGW).

The system architecture will be as shown below, where the orange boxes indicate the work in progress components.

![Inbound Roaming Architecture](https://user-images.githubusercontent.com/1519854/103509194-6b849f00-4e17-11eb-82c9-bb8469fcbe5c.jpg)

The following issues track the activity for individual components:

-- [Inbound Roaming] Add S8 proxy in FeGmagma #3595 
-- [Inbound Roaming]  Add Roaming Relay service in Orc8rmagma #3596 
-- [Inbound Roaming] TeraVM testbed setupmagma #3746  
-- [Inbound Roaming] Integration test setupmagma #3747 
-- [Inbound Roaming] Add S8 task in MME servicemagma #3748   
-- [Inbound Roaming] GTP-U support in OVS #3750

**Comment by uri200** [comment]
Design document can be found here


https://docs.google.com/document/d/11m6VF4Grg0yPjjhoXdxJ-kVhvxrbW6Lk0iIue3d-814/edit#heading=h.czv0vpn4mw66
