### ISSUE TITLE
Emergency Attach

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3278]
Impact: For voice services in Brazil and US is a regulatory requirement

**Comment by ulaskozat** [comment]
Emergency attach will likely to be moved out of v1.5 release.

**Comment by lpavao** [comment]
@lpavao following up with Aditya on impact so we can properly prioritize.

**Comment by ekowtaylor** [comment]
@lpavao there are still open dependencies for this epic https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/3278

**Comment by ekowtaylor** [comment]
Should we keep it in the icebox rather than close it?
