### ISSUE TITLE
Add AGW HA pool UI to FWA NMS

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#3320]
Once we've created the HAPair network entity for LTE networks with their associated CRUD routes in the API, we
need a UI to be able to create a new HA pair via the NMS for both LTE networks and Federated LTE networks

We will have to decide whether we should have a dedicated page for HA pairs, or instead create
a section for these on the page at nms/mpk_dogfooding/equipment/overview/gateway

When adding a pair, the NMS should prompt for:

pair ID as a string field
gatewayID1 dropdown box that lists all gateways in the network
gatewayID2 dropdown box that lists all gateways in the network

For displaying the status of the pair, we can refer to the mockup here:
https://www.figma.com/proto/aRJzvSa3J9nhD2n3yERd1s/Magma---Phase-2-(Updated-Styles)?node-id=1035%3A1754&scaling=min-zoom

**Comment by mpgermano** [comment]
Once we've created the HAPair network entity for LTE networks with their associated CRUD routes in the API, we
need a UI to be able to create a new HA pair via the NMS.

We will have to decide whether we should have a dedicated page for HA pairs, or instead create 
a section for these on the page at `nms/mpk_dogfooding/equipment/overview/gateway`

When adding a pair, the NMS should prompt for:
- pair ID as a string field
- gatewayID1 dropdown box that lists all gateways in the network
- gatewayID2 dropdown box that lists all gateways in the network

**Comment by ekowtaylor** [comment]
@HannaFar please link any PRs that you raise for this to this issue

**Comment by HannaFar** [comment]
> @HannaFar please link any PRs that you raise for this to this issue

@ekowtaylor I was working on the UI, I will open a PR next week 🙂

**Comment by ekowtaylor** [comment]
@HannaFar was this the PR you were referring to? https://github.com/magma/magma/pull/5639
