### ISSUE TITLE
Add MME group ID, MME code, and MME relative capacity to access gateway configuration in FWA NMS

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#3321]
We need the ability to set MME code, MME GID, and MME relative capacity for an access gateway
in the NMS. These fields are required for S1-flex behavior to function properly.

Once these fields are set in the orc8r, we should add the associated configuration
to the NMS. These will either be set via LTE AGW configs or in the HA pair configuration
depending on where they're defined in the orc8r.

**Comment by karthiksubraveti** [comment]
@HannaFar's changes address this issue. Closing this one.
