### ISSUE TITLE
Package Envoy binaries

### ISSUE THREAD

**Issue by pshelar** [magma/magma#3335]

**Comment by pshelar** [comment]
We need to deploy envoy 1.16.0 on AGW:
1. vagrant image.
2. Include it in prod deployment.

**Comment by koolzz** [comment]
@tmdzk unrelated but if you're generating a packer vm image can you aslo include these(I have a pr from a while back and I don't want to rerun packer https://github.com/magma/magma/pull/2318):
      - libpcap-dev
      - libtins-dev
      - libmnl-dev


And also for envoy we'll need golang

**Comment by pshelar** [comment]
Patch is handed.
