### ISSUE TITLE
pipelined crashing when in dual SGi configuration

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3341]
### Your Environment

- **Version:** 1.3.0-1602477016-723feee0
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** pipelined
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

Pipelined service is crashing and not recovering. 

We have setup using:
VLAN on AGW mgmt interface (VLAN 2)
VLAN on APN internet (VLAN 12)
VLAN on APN management (VLAN 13)
Subscriber setup with 2 APNs (above) and in Bridge mode so AGW performs DHCP for IP on each APN. 

After initial boot, system is ok and running, after about 15 minutes, pipelined appeared to crash, sys_gtp_2152 interface went away and returned with a different interface number, and journalctl logs showed repeated error/crash of pipelined. 

**To Reproduce**
Working on exact steps to reproduce. Don't have yet. 

**Expected behavior**
UE traffic should continue like after initial boot, pipelined should not crash and not recover. 

Attaching:

1. network drawing
![AGW Bridge Dual SGi Test Net (4)](https://user-images.githubusercontent.com/61293007/96655392-93756380-12fa-11eb-8055-e03a5c0f0828.png)
2. journalctl logs showing pipelined error
[journalctl -f output with pipelined error.txt](https://github.com/magma/magma/files/5412226/journalctl.-f.output.with.pipelined.error.txt)
3. ovs_ofctl output
[ovs-ofctl dump-flows gtp_br0.txt](https://github.com/magma/magma/files/5412227/ovs-ofctl.dump-flows.gtp_br0.txt)
4. ovs and ip interface output
[ovs and ip data.txt](https://github.com/magma/magma/files/5412228/ovs.and.ip.data.txt)

**Additional context**
Here is AGW json config from orc8r
```
"root": {
	"apn_resources": {
		"internet": {
			"apn_name": "internet"
			"id": "inet1212"
			"vlan_id": 12
		}
		"management": {
			"apn_name": "management"
			"id": "mgmt1313"
			"vlan_id": 13
		}
	}
	"cellular": {
		"epc": {
			"ip_block": "192.168.128.0/24"
			"nat_enabled": false "sgi_management_iface_vlan": "2"
		}
		"ran": {
			"pci": 260 "transmit_enabled": true
		}
	}
	"connected_enodeb_serials": [] 0 items "description": "nuc2"
	"device": {
		"hardware_id": "86f9c5fd-ad30-4150-b295-f1722a2a62a4"
		"key": {
			2 items "key": "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEaN3n0q1Cw919Jv2xzIqtMuLpm3nIT3wSFS0Nh7mM3hR76XKOLLGemVSgK6WfkB0s7mD+Fz+y3a5yB/et+yexyfWMwuly4LMIG9LIvJgcgUXEu7VRJGxm+TnIBuEIlQvE"
			"key_type": "SOFTWARE_ECDSA_SHA256"
		}
	}
	"id": "nuc2"
	"magmad": {
		"autoupgrade_enabled": true "autoupgrade_poll_interval": 60 "checkin_interval": 60 "checkin_timeout": 30 "dynamic_services": [2 items
			0: "eventd"
			1: "td-agent-bit"
		]
		"logging": {
			"aggregation": {
				"target_files_by_tag": {
					"mme": "var/log/mme.log"
				}
			}
			"log_level": "DEBUG"
		}
	}
	"name": "nuc2"
	"tier": "release_1_3"
}
```

**Comment by jpad-freedomfi** [comment]
Now working with patched mme file from troubleshooting https://github.com/magma/magma/issues/3380. 

I have a state currently where this happens repeatedly. UE attach can trigger the error, but not always. I have 3 core files from OVS crashes to attach. 
[Uploading 3pipelinedcoredumps.tar.zip…]()

**Comment by jpad-freedomfi** [comment]
apologies. Was using the unpatched uplink_bridge.py. Using the patched version from @pshelar things are working and stable.

**Comment by koolzz** [comment]
@pshelar can we close this then?

**Comment by jpad-freedomfi** [comment]
See update above, this fix has been merged a while back.
