### ISSUE TITLE
SPGW: Missing eNB IP address from UE attach event.

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3380]
### Your Environment

- **Version:** 1.3.0-1602477016-723feee0
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:**  bare-metal (AGW)

### Describe the Issue

Sometimes when UE adds 2nd APN (management) the OVS flows are not setup correctly and traffic cannot flow. The tunnel id and IP for next hop are all 0's. 

**To Reproduce**
1.  Configure AGW for NAT disabled mode via NMS.
2. Configure AGW for 2 APN resources using VLAN tags via NMS 
3. Boot UE, eNB, AGW and test both APNs Ping outbound APN1 (inet) and inbound APN2(mgmt)
4. Reboot either eNB, or AGW, or both, leave UE on trying to reconnect
5. wait for UE to reconnect, retest APN traffic passing. 
6. repeat and see that some boots both APNs work, some boots only APN1 inet works, mgmt OVS config is bad. 

**Expected behavior**
Expected behavior is that any boot sequence of UE, eNB, AGW, reliably results in both APNs being configured correctly in OVS. Also, successive attach of UE should have same results, OVS setup correctly. 

**Logs**
here is a zip with:
mme.log of working case
mme.log of not working case
ovs trace of working case
ovs trace of not working case
ovs dump flows table=0 for working case
ovs dump flows table=0 for not working case
[Dual APN Logs.zip](https://github.com/magma/magma/files/5420965/Dual.APN.Logs.zip)

Test Network Diagram
![AGW Bridge Dual SGi OVS Test Net](https://user-images.githubusercontent.com/61293007/96841481-17b60c80-1409-11eb-8db2-a8030c64bde9.png)
@pshelar

**Comment by ulaskozat** [comment]
@jpad-freedomfi Is this still an open issue?

**Comment by jpad-freedomfi** [comment]
No, I think it is resolved. Initial testing with 1.3.2 with dual SGi setup has been relatively smooth. APN resources disappeared and had to be re-added, but I think that is NMS issue. Once re-added they seem stable.

**Comment by ulaskozat** [comment]
Closing this issue then.
