### ISSUE TITLE
[NMS] IPv6 configuration for AGW

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3389]
## Summary

Currently we have IPv6 feature, but it can only be enabled through a combination of Orc8r API and editing `.yaml` files. We need to bridge this feature gap in the NMS.

API to configure the IPv6 pool is here: https://github.com/magma/magma/blob/a60bed8f43f72d7b9a2aa6ad5abfc3b02969d05c/lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml#L2086

Configuration guide (Meta only): [link](https://docs.google.com/document/d/1ZgowXtn24mHcJp-8QBiLtXahRlra6ADdobgTthGCOPM/edit)
IPv6 Design Doc (Meta only): [link](https://docs.google.com/document/d/1lRx7zmfs7YPVbz84Dm8nQ7mKKHHUYh2ryZJhRB9D7aM/edit#heading=h.c7qqiqtau83y)
Magma IP Allocation (Meta only): [link](https://docs.google.com/document/d/1M3pb5LJTFWii5_xJF4loWV6dcsjFfhI2NVj3uCkwgF4/edit#)

(Collapsed #3387 into this task)

## Changes

**Existing EPC config for AGW**
![Screen Shot 2022-02-11 at 3 10 39 PM](https://user-images.githubusercontent.com/804385/153682939-9f593f7d-42e7-4ac2-a355-76150a67c6d4.png)

Will need to add the following fields:
- `sgi_management_iface_ipv6_gw`
- `sgi_management_iface_ipv6_addr`

**Comment by ulaskozat** [comment]
test with json interface after orc8r support is landed.

**Comment by pshelar** [comment]
API to configure the IPv6 pool is here: https://github.com/magma/magma/blob/a60bed8f43f72d7b9a2aa6ad5abfc3b02969d05c/lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml#L2086

**Comment by andreilee** [comment]
@pshelar
1. I see there's an `ipv6_block` and `ip_block`. Would we want both to be configured, or only one of them?
2. For SGW management interface configurations in the swagger file, would both the IPv6 and IPv4 versions be configured, or only one of them?

**Comment by pshelar** [comment]
> 1. ipv6_block



> @pshelar
> 
> 1. I see there's an `ipv6_block` and `ip_block`. Would we want both to be configured, or only one of them?

ip_block is for IPv4, so ipv6_block is required if operator needs IPv6 UE address.

> 2. For SGW management interface configurations in the swagger file, would both the IPv6 and IPv4 versions be configured, or only one of them?

Operator can configure both or one of address family depending on need for dual or single stack management interface.
