### ISSUE TITLE
[AGW][Pipelined] Number of bytes not incrementing for UE in MME table despite traffic flowing successfully

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#3390]
### Your Environment

- **Version:** Git master branch
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Pipelined or MME
- **Deployment Environment:** bare-metal (AGW), but might show up on vagrant VM as well.

### Describe the Issue

**To Reproduce**
1. Generate package with `fab dev package:vcs=git`, which creates the magma package inside the local vagrant VM, under ~/magma-packages/magma_1.3_.*.deb
2. Install on bare-metal AGW with `sudo apt -f install magma_1.3_.*.deb`
3. Attach an eNB, UE and run data traffic through the web browser
4. On AGW, run `sudo pipelined_cli.py debug display_flows` to dump OVS flows

**Expected behavior**
The UE is assigned the IP address 192.168.128.223, so the MME table in OVS should show non-zero value for n_bytes in flows with nw_dst = 192.168.128.223. But as seen in attached ovs_dump_no_bytes.txt , that is not the case.

Also attaching pkt_trace_no_bytes.txt which runs the packet trace through OVS.

[ovs_dump_no_bytes.txt](https://github.com/magma/magma/files/5425244/ovs_dump_no_bytes.txt)
[pkt_trace_no_bytes.txt](https://github.com/magma/magma/files/5425245/pkt_trace_no_bytes.txt)

**Comment by ssanadhya** [comment]
I observed this issue in bare-metal AGW, but it should be reproducible on dev VM with any of the S1AP traffic tests.

**Comment by koolzz** [comment]
Can't seem to reproduce with s1

**Comment by ssanadhya** [comment]
> Can't seem to reproduce with s1
- On the latest master, I don't see the "MME" table at all in the pipelined display_flows
- You might have to change the test duration so that it runs long enough for you to query the OVS table.
