### ISSUE TITLE
[Integ tests] Enable stateless mode for all LTE and CWF integration tests

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3394]

**Comment by themarwhal** [comment]
SessionD has been running stateless for ~3 months on CWF Integration Test

**Comment by themarwhal** [comment]
Testing locally + on CircleCI by modifying `s1ap_wrapper.py`
```
    def __init__(
        self,
        stateless_mode=MagmadUtil.stateless_cmds.ENABLE,
        apn_correction=MagmadUtil.apn_correction_cmds.DISABLE,
    ):
```
There are some failures so compiling the list here: https://docs.google.com/spreadsheets/d/1Yav6PPah2v2rcf1frCdEFSY3Bxah_cny2Of55GHhDJ4/edit?usp=sharing

**Comment by themarwhal** [comment]
As for CWF Integration Tests, SessionD is already running stateless. 
I am working on enabling stateless PipelineD. Results are mixed on CircleCI: https://app.circleci.com/pipelines/github/magma/magma?branch=test-cwf-stateless-pipelined

I am trying to figure out which ones are real issues. Will update in the same document above.

**Comment by themarwhal** [comment]
CWF integration tests are now running all stateless.

**Comment by ssanadhya** [comment]
Completed with https://github.com/magma/magma/pull/4305
