### ISSUE TITLE
While running `test_attach_detach_with_mme_restart.py` syslog reports the following error on MME

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3395]
` [libprotobuf ERROR google/protobuf/wire_format_lite.cc:534] String field 'magma.lte.oai.EsmProcData.apn' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.`

**Comment by ssanadhya** [comment]
Fixed with https://github.com/magma/magma/pull/3168
