### ISSUE TITLE
[agw][stateless] Stress testing with S1ap tests

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3397]
- Reliability: Run each service restart test case multiple times
- Scalability: 
-- Increase number of UEs in existing stateless tests, i.e. restart MME after every attach
-- Attach multiple UEs, restart MME and then detach all UEs
-- Attach one UE, restart MME, attach another UE, restart MME, and so on, then start detaching UEs with MME restart after each detach

**Comment by VinashakAnkitAman** [comment]
Following scenarios have been tested in loop for a duration of around 12 hours:
1) test_attach_detach_with_mme_restart.py (Tested successfully with maximum 240 UEs)
        1-Attach
        2-MmeRestart + wait for 30 seconds
        3-Detach
        5-Repeat step 1, 2 and 3 in loop for all UEs
   
2) test_attach_mme_restart_detach_multi_ue.py (Tested successfully with maximum 240 UEs)
        1-Attach
        2-Repeat step 1 in loop for all UEs
        3-MmeRestart + wait for 30 seconds
        4-Detach
        5-Repeat step 4 in loop for all UEs

3) test_attach_loop_mme_restart_detach_and_mme_restart_loop_multi_ue.py (Tested successfully with maximum 32 UEs)
        1-Attach
        2-Repeat step 1 in loop for all UEs
        3-MmeRestart + wait for 30 seconds
        4-Detach
        5-MmeRestart + wait for 30 seconds
        6-Repeat step 4 and 5 in loop for all UEs

4) test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue.py (Tested successfully with maximum 32 UEs)
        1-Attach
        2-MmeRestart + wait for 30 seconds
        3-Repeat step 1 and 2 in loop for all UEs
        4-Detach
        5-MmeRestart + wait for 30 seconds
        6-Repeat step 4 and 5 in loop for all UEs

5) test_attach_ul_udp_data_with_mme_restart_multi_ue.py (Tested successfully with maximum 8 UEs --Failing right now for 32 UEs for Out Of Order packet issue)
        1-Attach
        2-Repeat step 1 in loop for all UEs
        3-Run uplink data for all the UEs
        4-MmeRestart + wait for 30 seconds
        5-Run uplink data for all the UEs
        6-Detach
        7-Repeat step 6 in loop for all UEs

6) test_attach_and_mme_restart_loop_ul_udp_data_detach_loop_multi_ue.py (Tested successfully with maximum 8 UEs --Failing right now for 32 UEs for Out Of Order packet issue)
        1-Attach
        2-MmeRestart + wait for 30 seconds
        3-Repeat step 1 and 2 in loop for all UEs
        4-Run uplink data for all the UEs
        5-Detach
        6-Repeat step 5 in loop for all UEs

7) test_attach_and_mme_restart_loop_ul_udp_data_detach_and_mme_restart_loop_multi_ue.py (Tested successfully with maximum 8 UEs --Failing right now for 32 UEs for Out Of Order packet issue)
        1-Attach
        2-MmeRestart + wait for 30 seconds
        3-Repeat step 1 and 2 in loop for all UEs
        4-Run uplink data for all the UEs
        5-Detach
        6-MmeRestart + wait for 25 seconds
        7-Repeat step 5 an 6 in loop for all UEs
