### ISSUE TITLE
AGW Containerization

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#3410]

**Comment by rmeleromira** [comment]
I have made a pull request to the magma repo with the basic docker-compose that will run mobilityd service, a Dockerfile for each AGW service, a build script that will run a build step to build dependencies and binaries, and put it all together.

Left to do is get the final build-magma.sh script working, and populate the docker-compose for the rest of the services and test.

https://github.com/magma/magma/pull/7007

**Comment by ekowtaylor** [comment]
@arunuke Thanks for the updates, this is great.

**Comment by lpavao** [comment]
Is this complete?
