### ISSUE TITLE
Add verbosity option when listing a network's subscribers

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#3421]
Current  `/lte/{network_id}/subscribers `returns the list of subscribers with very verbose state information per subscriber. Add support for a non-verbose option that returns just the list of subscribers in the network, e.g., `/lte/{network_id}/subscribers?verbose=false`.

**Comment by hcgatewood** [comment]
Previous PR: https://github.com/magma/magma/pull/8912/files
