### ISSUE TITLE
Improve the alerts table component in the dashboard

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#3473]

**Comment by karthiksubraveti** [comment]
![Screen Shot 2020-10-27 at 5.00.35 AM.png](https://images.zenhubusercontent.com/5f80914bb2a38126f381f77d/208d8af8-8009-4095-b7e9-b827b1e66652)

![Screen Shot 2020-10-27 at 5.00.47 AM.png](https://images.zenhubusercontent.com/5f80914bb2a38126f381f77d/2e5804f9-4236-4186-83a4-6a176e6e30dd)

Currently the alarm component shows better information than the alerts table shown in the dashboard. We can improve it with additional label information displayed in the alarm component.

**Comment by 119Vik** [comment]
RestartCWAGTests

**Comment by 119Vik** [comment]
RestartLTETests

**Comment by 119Vik** [comment]
@karthiksubraveti  sorry testing new pipelines :)
