### ISSUE TITLE
SCTPD and MME crashing every second generating coredumps

### ISSUE THREAD

**Issue by uri200** [magma/magma#3497]
SCTPD and MME are crashing constantly on teraVM. 
Restart the process fix them but after a while they loop crash

Attached you can find some of those coredumps (probably they have the same info), complete syslog and mme executable
[mme crashes.zip](https://github.com/magma/magma/files/5453711/mme.crashes.zip)

mme exec
https://www.dropbox.com/s/l9yx4443uzqxxrq/mme?dl=0

**Comment by ssanadhya** [comment]
The MME crash is happening due to the same issue as #3415 , which has been resolved. Pull Request https://github.com/magma/magma/pull/3659 fixes the Sctpd crash loop issue.
