### ISSUE TITLE
DNSD failing to start on attribute errors when generating runtime configuration from mconfig

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#352]
Generation of dnsd config fails at startup with an existing gateway config.

```
Jun 19 19:25:20 debiansb systemd[1]: magma@dnsd.service: Service hold-off time over, scheduling restart.
Jun 19 19:25:20 debiansb systemd[1]: Stopped Magma dnsd service.
Jun 19 19:25:20 debiansb systemd[1]: Starting Magma dnsd service...
Jun 19 19:25:22 debiansb dnsd[27198]: Traceback (most recent call last):
Jun 19 19:25:22 debiansb dnsd[27198]:   File "/usr/local/bin/generate_dnsd_config.py", line 86, in <module>
Jun 19 19:25:22 debiansb dnsd[27198]:     main()
Jun 19 19:25:22 debiansb dnsd[27198]:   File "/usr/local/bin/generate_dnsd_config.py", line 82, in main
Jun 19 19:25:22 debiansb dnsd[27198]:     CONFIG_OVERRIDE_DIR, get_context())
Jun 19 19:25:22 debiansb dnsd[27198]:   File "/usr/local/bin/generate_dnsd_config.py", line 72, in get_context
Jun 19 19:25:22 debiansb dnsd[27198]:     context['addresses'] = _get_addresses(cfg, mconfig)
Jun 19 19:25:22 debiansb dnsd[27198]:   File "/usr/local/bin/generate_dnsd_config.py", line 38, in _get_addresses
Jun 19 19:25:22 debiansb dnsd[27198]:     *record.a_record,
Jun 19 19:25:22 debiansb dnsd[27198]: AttributeError: 'dict' object has no attribute 'a_record'
Jun 19 19:25:22 debiansb systemd[1]: magma@dnsd.service: Control process exited, code=exited status=1
Jun 19 19:25:22 debiansb systemd[1]: Failed to start Magma dnsd service.
Jun 19 19:25:22 debiansb systemd[1]: magma@dnsd.service: Unit entered failed state.
Jun 19 19:25:22 debiansb systemd[1]: magma@dnsd.service: Failed with result 'exit-code'.

```

- `Dict has no attribute a_record`
- `Dict has no attribute aaa_record`
- `Dict has no attribute domain`

Tested with magma `0.3.73-1560304279-4309537e`

**Comment by xjtian** [comment]
can you paste the DNS configuration for the network from orchestrator/nms?

**Comment by bmurithi** [comment]
![screencap_20190620_006](https://user-images.githubusercontent.com/6918709/59861739-15155400-938a-11e9-94d7-72560b8e6e94.png)

The is different from the config found in gateway.mconfig which is correct as configured in the past.

**Comment by xjtian** [comment]
@bmurithi can you submit your fix as a PR?

**Comment by bmurithi** [comment]
@xjtian It looked like there was a change in how mconfig is parsed and perhaps the change didn't make it to `generate_dnsd_config.py` - I'm not certain my fix is even valid at all.

The corresponding mismatch in dns config in the orchestrator versus the pulled mconfig sounds like part of this issue.

**Comment by xjtian** [comment]
Yeah your intuition on the first part is correct. We load the mconfig as plain JSON instead of a protobuf message for the template functions now, which means fields which aren't included are no longer initialized with their zero value.

DNS mconfig bugfix is in the pipeline. I'm deploying the system migration which includes that fix to our staging stack today to let it soak. I'll let you know when we vet it on prod.
