### ISSUE TITLE
[NMS] Add checks in NMS to prevent gateway downgrades

### ISSUE THREAD

**Issue by pshelar** [magma/magma#3525]
### Your Environment

- **Version:** 1.2 or 1.3
- **Affected Component:** Access Gateway, or NMS
- **Affected Subcomponent:**  AGW service
- **Deployment Environment:** e.g. bare-metal (AGW)
### Describe the Issue

NMS downgrade does not work. it complains that the downgraded version is older than existing one :)

**To Reproduce**
1. Go to NMS console
2. Click on Upgrade and select older version. No error shown on UI
3. check syslog on AGW
4. See error:
Oct 29 15:26:42 multi_apn magmad[23865]: INFO:root:Service is currently on package version 1.3.0-1602721622-64eb10c5, ignoring upgrade to 0.0.0-0 because it is either equal or behind.

**Expected behavior**
NMS should support downgrade operation atleast to same major version. This would allow operator to revert back to working release in case any upgrade issue.

**Comment by mpgermano** [comment]
AFAIK, AGW downgrade is something we have never planned to support given that undoing an apt upgrade is not straightforward. Once the AGW is containerized then this will no longer be an issue.

**Comment by pshelar** [comment]
ok, given magma is not supporting downgrade, NMS shld not give this option.
@karthiksubraveti Can you take care of that.

**Comment by karthiksubraveti** [comment]
@mpgermano given that we might have users attempting to do this through API as well, I guess it might be better if we can actually validate this in orc8r and error out. wdyt ?
