### ISSUE TITLE
Pipelined (CWF) crashed after attempting to start scaled tests

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#3527]
### Your Environment

- **Version:** - 28f7f2e8 (~1.3)
- **Affected Component:** CWAG
- **Affected Subcomponent** Pipelined
- **Deployment Environment:** On-prem kube-virt based cwag.

### Describe the Issue

Pipelined started crashing with the following errors: 

https://gist.github.com/sudhikan/310cd6742bccc80c237606eb5581f5bc

We noticed that pipelined restarted minutes before the scaled test started (this is based on when the test started running and the last status report in the `docker ps` output. 

**To Reproduce**
Unable to say at this point. Leaving gateways as is for now. 

**Expected behavior**
Pipelined should not have crashed.

**Screenshots**
NA; error gist added above.

**Additional context**
NA

**Comment by koolzz** [comment]
Should be resolved by https://github.com/magma/magma/pull/3533

**Comment by ekowtaylor** [comment]
PR merged, closing issue.
