### ISSUE TITLE
[agw][mme] Memory leaks

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#3538]
Using this issue to track all memory leaks in MME, triggered by running:

`active_idle_sequencer_mode.py` with defaults (200 UEs) 5 iterations and restarting MME
`configurable_attach_detach.py` with defaults (200 UEs) 5 iterations and restarting MME

```
| Spirent 1.5.2                                  | Spirent 1.6                                    | Spirent master                                      |
|------------------------------------------------|------------------------------------------------|-----------------------------------------------------|
| s1ap_mme_handle_initial_context_setup_response | s1ap_mme_handle_initial_context_setup_response |                                                     |
| fluid_base::BaseOFConnection::OFReadBuffer     | fluid_base::BaseOFConnection::OFReadBuffer     | fluid_base::BaseOFConnection::OFReadBuffer          |
|  esm_recv_pdn_connectivity_request             |                                                |                                                     |
| nas_new_emm_procedures                         |                                                |                                                     |
| nas_new_attach_procedure                       |                                                |                                                     |
| emm_recv_attach_request                        |                                                |                                                     |
| emm_cn_cs_response_success                     |                                                |                                                     |
| emm_cn_ula_success                             |                                                |                                                     |
| decode_esm_message_container                   | decode_esm_message_container                   |                                                     |
| emm_tracking_area_update_accept                | emm_tracking_area_update_accept                |                                                     |
|                                                |                                                |                                                     |

```

Memory leaks on 1.5.2" **[P0]**
`s1ap_mme_handle_initial_context_setup_response` fixed by https://github.com/magma/magma/pull/8481/ (**backported**)
`fluid_base::BaseOFConnection::OFReadBuffer` fixed by https://github.com/magma/magma/pull/8495 (**backported**)
`emm_tracking_area_update_accept` fixed by https://github.com/magma/magma/pull/8029 (**backported**)
`decode_esm_message_container` fixed by https://github.com/magma/magma/pull/8594 (**backported**)
`esm_recv_pdn_connectivity_request` https://github.com/magma/magma/issues/8568 (**closed, not reproducible on latest v1.5**)
`nas_new_attach_procedure` https://github.com/magma/magma/issues/8570 (**closed, not reproducible on latest v1.5**)
`emm_recv_attach_request` https://github.com/magma/magma/issues/8574 (**closed, not reproducible on latest v1.5**)
`emm_cn_ula_success` https://github.com/magma/magma/issues/8571 (**closed, not reproducible on latest v1.5**)

Memory leaks on 1.6: **[P1]**
`s1ap_mme_handle_initial_context_setup_response` fixed by https://github.com/magma/magma/pull/8481/ (pending 1.6 backport)
`fluid_base::BaseOFConnection::OFReadBuffer` fixed by #8495 (pending 1.6 backport)
`emm_tracking_area_update_accept` fixed by https://github.com/magma/magma/pull/8029 (**backported**)
`decode_esm_message_container`  fixed by https://github.com/magma/magma/pull/8594 (**backported**)

Memory leaks on master: **[P1]**
`fluid_base::BaseOFConnection::OFReadBuffer` fixed by https://github.com/magma/magma/pull/8481/
`emm_tracking_area_update_accept` fixed by https://github.com/magma/magma/pull/8029
`decode_esm_message_container`  fixed by https://github.com/magma/magma/pull/8594

**Comment by rsarwad** [comment]
The memory leaks reported above looks very generic; either back-trace or scenario would be helpful;
Because memory leak might have reported while handling negative scenarios. Back-trace would help to identify the call flow.
wrt leak, decode_nas_message_container from code browsing it appears that, memory is not freed while sending SMS message to MSC/VLR. But doesn't have set-up to re-create the leak and validate the fix

**Comment by ssanadhya** [comment]
@rsarwad , modified the issue description to track all memory leaks. I found few while running `test_attach_detach_enb_rlf_initial_ue_msg.py`. Please take a look.

Jan 28 23:14:40 magma-dev mme[5627]: Direct leak of 560 byte(s) in 1 object(s) allocated from:
Jan 28 23:14:40 magma-dev mme[5627]:     #0 0x7f3cdf346ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
Jan 28 23:14:40 magma-dev mme[5627]:     #1 0x55b990694485 in esm_recv_pdn_connectivity_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c:192
Jan 28 23:14:40 magma-dev mme[5627]:     #2 0x55b990662189 in _esm_sap_recv /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c:623
Jan 28 23:14:40 magma-dev mme[5627]:     #3 0x55b9906611dc in esm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c:283
Jan 28 23:14:40 magma-dev mme[5627]:     #4 0x55b9905f353f in _emm_attach /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:1482
Jan 28 23:14:40 magma-dev mme[5627]:     #5 0x55b9905f2bbf in _emm_attach_success_security_cb /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:1290
Jan 28 23:14:40 magma-dev mme[5627]:     #6 0x55b990684b4a in EmmCommonProcedureInitiated /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/EmmCommonProcedureInitiated.c:113
Jan 28 23:14:40 magma-dev mme[5627]:     #7 0x55b99063f20d in emm_fsm_process /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_fsm.c:246
Jan 28 23:14:40 magma-dev mme[5627]:     #8 0x55b990691e51 in emm_reg_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_reg.c:87
Jan 28 23:14:40 magma-dev mme[5627]:     #9 0x55b990640aa1 in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:89
Jan 28 23:14:40 magma-dev mme[5627]:     #10 0x55b99062580a in emm_proc_security_mode_complete /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/SecurityModeControl.c:471
Jan 28 23:14:40 magma-dev mme[5627]:     #11 0x55b9906911b5 in emm_recv_security_mode_complete /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c:1055
Jan 28 23:14:40 magma-dev mme[5627]:     #12 0x55b9906794f0 in _emm_as_recv /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:428
Jan 28 23:14:40 magma-dev mme[5627]:     #13 0x55b99067b6f5 in _emm_as_data_ind /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:678
Jan 28 23:14:40 magma-dev mme[5627]:     #14 0x55b9906781f4 in emm_as_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:180
Jan 28 23:14:40 magma-dev mme[5627]:     #15 0x55b990640bdd in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:105
Jan 28 23:14:40 magma-dev mme[5627]:     #16 0x55b9905d8248 in nas_proc_ul_transfer_ind /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:326
Jan 28 23:14:40 magma-dev mme[5627]:     #17 0x55b9902af0f0 in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:98
Jan 28 23:14:40 magma-dev mme[5627]:     #18 0x7f3cdc6847bd in zloop_start (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x287bd)
Jan 28 23:14:40 magma-dev mme[5627]: Direct leak of 48 byte(s) in 1 object(s) allocated from:
Jan 28 23:14:40 magma-dev mme[5627]:     #0 0x7f3cdf346ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
Jan 28 23:14:40 magma-dev mme[5627]:     #1 0x7f3cdc6804c2 in zlist_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x244c2)
Jan 28 23:14:40 magma-dev mme[5627]: Indirect leak of 16 byte(s) in 1 object(s) allocated from:
Jan 28 23:14:40 magma-dev mme[5627]:     #0 0x7f3cdf346d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
Jan 28 23:14:40 magma-dev mme[5627]:     #1 0x55b9901e498a in bfromcstr /home/vagrant/magma/lte/gateway/c/oai/lib/bstr/bstrlib.c:216
Jan 28 23:14:40 magma-dev mme[5627]:     #2 0x55b990637f1d in _emm_cn_ula_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:330
Jan 28 23:14:40 magma-dev mme[5627]:     #3 0x55b99063dd63 in emm_cn_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:1150
Jan 28 23:14:40 magma-dev mme[5627]:     #4 0x55b990640c7e in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:113
Jan 28 23:14:40 magma-dev mme[5627]:     #5 0x55b9905d9a5c in nas_proc_ula_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:467
Jan 28 23:14:40 magma-dev mme[5627]:     #6 0x55b9902d58b8 in mme_app_handle_s6a_update_location_ans /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_location.c:346
Jan 28 23:14:40 magma-dev mme[5627]:     #7 0x55b9902af8dd in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:208
Jan 28 23:14:40 magma-dev mme[5627]:     #8 0x7f3cdc6847bd in zloop_start (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x287bd)
Jan 28 23:14:40 magma-dev mme[5627]: Indirect leak of 16 byte(s) in 1 object(s) allocated from:
Jan 28 23:14:40 magma-dev mme[5627]:     #0 0x7f3cdf346d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
Jan 28 23:14:40 magma-dev mme[5627]:     #1 0x55b9901e4a41 in bfromcstr /home/vagrant/magma/lte/gateway/c/oai/lib/bstr/bstrlib.c:219
Jan 28 23:14:40 magma-dev mme[5627]:     #2 0x55b990637f1d in _emm_cn_ula_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:330
Jan 28 23:14:40 magma-dev mme[5627]:     #3 0x55b99063dd63 in emm_cn_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:1150
Jan 28 23:14:40 magma-dev mme[5627]:     #4 0x55b990640c7e in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:113
Jan 28 23:14:40 magma-dev mme[5627]:     #5 0x55b9905d9a5c in nas_proc_ula_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:467
Jan 28 23:14:40 magma-dev mme[5627]:     #6 0x55b9902d58b8 in mme_app_handle_s6a_update_location_ans /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_location.c:346
Jan 28 23:14:40 magma-dev mme[5627]:     #7 0x55b9902af8dd in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:208
Jan 28 23:14:40 magma-dev mme[5627]:     #8 0x7f3cdc6847bd in zloop_start (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x287bd)

**Comment by ssanadhya** [comment]
@ardzoht @ulaskozat , assigning this to you. Feel free to re-assign/bootcamp these.

**Comment by ekowtaylor** [comment]
@ulaskozat please revise the story points to reflect the actual size of this effort

**Comment by ekowtaylor** [comment]
Marked as in progress

**Comment by ardzoht** [comment]
From  s1ap tester, most of the memory leaks mentioned here https://github.com/magma/magma/issues/3538#issuecomment-769462771 have been fixed, the only remaining to be fixed is the same as on https://github.com/magma/magma/issues/5086:

```
Feb 22 16:08:55 agw1 mme[26668]:     #0 0x7f56e2ff1cdf in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xdcdf)
Feb 22 16:08:55 agw1 mme[26668]:     #1 0x7f56e01b4783 in fluid_base::BaseOFConnection::OFReadBuffer::read_notify(unsigned short) fluid/base/BaseOFConnection.cc:84
Feb 22 16:08:55 agw1 mme[26668]:     #2 0x7f56e01b4783 in fluid_base::BaseOFConnection::LibEventBaseOFConnection::read_cb(bufferevent*, void*) fluid/base/BaseOFConnection.cc:353
````

**Comment by ekowtaylor** [comment]
See #8277

**Comment by ekowtaylor** [comment]
@ardzoht to link the description with latest tracker

**Comment by ardzoht** [comment]
@ekowtaylor I updated the summary with tracker https://docs.google.com/spreadsheets/d/18F4XsE6wXdNtMyMT0VipWPRf2oYzBw6a1_EFuhd4J54/edit#gid=6640006

**Comment by ulaskozat** [comment]
@ardzoht can you update the tasks in this epic (status and SWE days spent on them).
