### ISSUE TITLE
Gy Only Detach Issue

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3542]
### Your Environment

- **Version:**  v1.3 Stable
- **Affected Component:** FeG + AGW
- **Affected Subcomponent:** Session_proxy + Sessiond
- **Deployment Environment:** e.g. AWS (orc8r + FeG), bare-metal (AGW)

### Describe the Issue

We are testing Gy only connection from Federation Gateway to OCS. 

We are seeing a behavior where terminate is only sent for a session after a new session has been started. 

Based on the FB test plan attached, test case 13 and 18, it seems like a diameter termination should be send upon AGW knowledge that EU has left. It does not appear to do that. 

Here are logs in which:
UE attaches at 20:26:06
Data flows for ~5min
UE turns off and eNB sends UE ContextRelease to AGW indicating UE is gone. 
Session continues without termination 
(what we see is termination is only sent after initiation of new session upon next detach, don't have full captures, but can if needed). 

**To Reproduce**
1. Configure Gy only relay on federation gateway to external OCS
2. Attach UE
3. Observe session setup with CCR-I/CCA-I
4. Obaserve updates with usage noted CCR-U/CCA-U
5. observe in s1 trace that UE context release after silent detach (UE power off)
6. observe no Gy termination is sent to OCS

**Expected behavior**
When MME is aware that UE has detached, a Gy Termination should be triggered to OCS with accounting data. 

**Screenshots**
Here is network topology
[Magma + OCS FreedomFi Lab Topology.pdf](https://github.com/magma/magma/files/5466148/Magma.%2B.OCS.FreedomFi.Lab.Topology.pdf)

**Additional context**
Zip file with logs of:
Feg_gy pcap
sessiond logs with gRPC enabled
session_proxy logs with gRPC enabled (but feels like I didn't do it right)
docker_compose.yml to see what I did wrong with logging
agw s1 pcap
[FB Sessiond logs for detach.zip](https://github.com/magma/magma/files/5462716/FB.Sessiond.logs.for.detach.zip)
@joary @amarpad

**Comment by jpad-freedomfi** [comment]
Decided not to post the FB test plan. Please ping me if you need to see the referenced test cases.

**Comment by themarwhal** [comment]
From the SessionD logs attached, it looks like SessionD never receives the detach from MME. When MME sees a user detach it should trigger a GRPC call from MME to SessionD. 
(`rpc EndSession(LocalEndSessionRequest) returns (LocalEndSessionResponse) {}`)

**Comment by jpad-freedomfi** [comment]
Hi, 

Increased logging level on session_proxy and captured mme.log as well. 

Looks like however the containers are bouncing, so session_proxy log didn't live long enough to reach UEContextRelease time in S1 pcap. 

Either way, here is updated log set:
[FB Logs.zip](https://github.com/magma/magma/files/5466931/FB.Logs.zip)

**Comment by themarwhal** [comment]
Thanks this is looking much better. In SessionD now I am seeing the MME->SessionD terminate request:
```
Oct 30 11:09:22 agw sessiond[16045]:   magma.lte.LocalEndSessionRequest {
Oct 30 11:09:22 agw sessiond[16045]:       sid {
Oct 30 11:09:22 agw sessiond[16045]:         id: "IMSI315010999900109"
Oct 30 11:09:22 agw sessiond[16045]:       }
Oct 30 11:09:22 agw sessiond[16045]:       apn: "internet"
Oct 30 11:09:22 agw sessiond[16045]:   }
Oct 30 11:09:22 agw sessiond[16045]: I1030 11:09:22.112185 16045 LocalSessionManagerHandler.cpp:470] Received a termination request from Access for IMSI315010999900109 apn internet
Oct 30 11:09:22 agw sessiond[16045]: I1030 11:09:22.112212 16045 LocalEnforcer.cpp:375] Initiating session termination for IMSI315010999900109-270599
Oct 30 11:09:22 agw sessiond[16045]: I1030 11:09:22.112236 16045 PipelinedClient.cpp:270] Deactivating 1 static rules and 0 dynamic rules for subscriber IMSI315010999900109 IP 192.168.128.190
Oct 30 11:09:22 agw sessiond[16045]: I1030 11:09:22.112277 16045 GrpcMagmaUtils.cpp:38]
Oct 30 11:09:22 agw sessiond[16045]:   magma.lte.DeactivateFlowsRequest {
Oct 30 11:09:22 agw sessiond[16045]:       sid {
Oct 30 11:09:22 agw sessiond[16045]:         id: "IMSI315010999900109"
Oct 30 11:09:22 agw sessiond[16045]:       }
Oct 30 11:09:22 agw sessiond[16045]:       rule_ids: "metering_rule"
Oct 30 11:09:22 agw sessiond[16045]:       request_origin {
Oct 30 11:09:22 agw sessiond[16045]:       }
Oct 30 11:09:22 agw sessiond[16045]:       ip_addr: "192.168.128.190"
Oct 30 11:09:22 agw sessiond[16045]:   }
Oct 30 11:09:22 agw sessiond[16045]: I1030 11:09:22.112380 16045 SessionState.cpp:1046] Session IMSI315010999900109-270599 FSM state change from SESSION_ACTIVE to SESSION_RELEASED
```
and then ~3 seconds later I see
```
Oct 30 11:09:25 agw sessiond[16045]: I1030 11:09:25.580790 16045 SessionState.cpp:1046] Session IMSI315010999900109-270599 FSM state change from SESSION_RELEASED to SESSION_TERMINATED
Oct 30 11:09:25 agw sessiond[16045]: I1030 11:09:25.580837 16045 SessionCredit.cpp:416] ===> Data usage since last report is tx=0 rx=0
Oct 30 11:09:25 agw sessiond[16045]: I1030 11:09:25.580849 16045 SessionCredit.cpp:638] ===> Amount reporting for this report: tx=0 rx=0
Oct 30 11:09:25 agw sessiond[16045]: I1030 11:09:25.580857 16045 SessionCredit.cpp:640] ===> The total amount currently being reported: tx=0 rx=0
Oct 30 11:09:25 agw sessiond[16045]: I1030 11:09:25.580962 16045 GrpcMagmaUtils.cpp:38]
Oct 30 11:09:25 agw sessiond[16045]:   magma.lte.SessionTerminateRequest {
Oct 30 11:09:25 agw sessiond[16045]:       sid: "IMSI315010999900109"
Oct 30 11:09:25 agw sessiond[16045]:       session_id: "IMSI315010999900109-270599"
Oct 30 11:09:25 agw sessiond[16045]:       apn: "internet"
Oct 30 11:09:25 agw sessiond[16045]:       request_number: 1
Oct 30 11:09:25 agw sessiond[16045]:       credit_usages {
Oct 30 11:09:25 agw sessiond[16045]:         charging_key: 1
Oct 30 11:09:25 agw sessiond[16045]:         type: TERMINATED
Oct 30 11:09:25 agw sessiond[16045]:         requested_units {
Oct 30 11:09:25 agw sessiond[16045]:         }
Oct 30 11:09:25 agw sessiond[16045]:       }
Oct 30 11:09:25 agw sessiond[16045]:       ue_ipv4: "192.168.128.190"
Oct 30 11:09:25 agw sessiond[16045]:       spgw_ipv4: "10.0.2.1"
Oct 30 11:09:25 agw sessiond[16045]:       plmn_id: "315010"
Oct 30 11:09:25 agw sessiond[16045]:       imsi_plmn_id: "315010"
Oct 30 11:09:25 agw sessiond[16045]:       user_location: "\202\023\005\020\000\001\023\005\020\004\002V\326"
Oct 30 11:09:25 agw sessiond[16045]:       tgpp_ctx {
Oct 30 11:09:25 agw sessiond[16045]:         gx_dest_host: "gx-less.magma.com"
Oct 30 11:09:25 agw sessiond[16045]:         gy_dest_host: "gy00.inew-cs.com"
Oct 30 11:09:25 agw sessiond[16045]:       }
Oct 30 11:09:25 agw sessiond[16045]:   }
```
This delay is expected as SessionD will always wait for roughly 2-4 seconds to make sure all usage is reported from PipelineD. Only after this, we send a `magma.lte.SessionTerminateRequest` that gets converted to CCR-Terminate on the FeG. 
The only catch here is that during this time, we see a new session created. This should not cause problems however because the two sessions have separate sessionIDs.
I'm not seeing any DIAMETER messages on the FeG pcap though.

**Comment by jpad-freedomfi** [comment]
@themarwhal Thanks for looking. the diameter is on port 3869. 

Also, the UE has a funny behavior where when it boots, it attaches, then detaches (with actual detach message) then attaches again. When you power it off, it does a silent detach. So if you look at the flow, you want to follow the last session opened. 

that one does not have a terminate send after UEContextRelease is seen on S1AP.

**Comment by jpad-freedomfi** [comment]
So If you look at the S1AP pcap:

- UEContextRelease is seen at 12:12:00

Then look at sessionD logs:

- The only terminate is 3 minutes earlier (due to the attach -> detach -> attach behavior of the UE)

After the UEContextRelease from power off of UE (silent detach) there is not terminate in the SessionD log.

**Comment by themarwhal** [comment]
Ah I understand. Thanks! Let me look into how/if we handle silent detach differently from the regular detach.

**Comment by uri200** [comment]
@ulaskozat  and I were looking at the logs.

The detach you show on frame 41 is caused due to Radio link failure. For this kind of detaches we do not trigger a session termination. The reason is to avoid ping-pong situation where the UE goes back and forth out of coverage.

In case the UE does not do its periodic update, that signals that UE might be out of the service are for good and that is a trigger for session release.

Thanks @ulaskozat for the insight 

![image](https://user-images.githubusercontent.com/16157139/97770646-5aa36e80-1af2-11eb-917b-fd58131ecac3.png)

**Comment by jpad-freedomfi** [comment]
Ok, and the default for T3412 is 54 min right? So we should see Gy termination sent 54 min after last TAU if we power off UE?

**Comment by jpad-freedomfi** [comment]
Hi @ulaskozat and @themarwhal and @uri200 

I have performed a periodic TAU test to see if the termination is sent after 54 min and did not see that happen. Please attached MME log, Sessiond log, and Gy pcap. 

timeline I can see: in MME log
6:32 Attach
6:35 context release due to RLF (ue powered off)
7:33 Mobile reachability timer expired (assume this is T3412 timing out)

but in Gy and Sessiond logs you can see no termination message is sent. (or at least that I see)
[Uploading 11-2_perioidic_tau_test.zip…]()

**Comment by uri200** [comment]
Hi @jpad-freedomfi , the link points to the PR but i can't find the `Uploading 11-2_perioidic_tau_test.zip` file. Can you try to attach it again please?

**Comment by jpad-freedomfi** [comment]
@uri200 Ok, please try this. I renamed with no dashes or underscores. 
[files.zip](https://github.com/magma/magma/files/5477918/files.zip)

**Comment by uri200** [comment]
Thanks @jpad-freedomfi  It looks like the mme log is not on DEBUG mode so it is not showing much information.

Per sessiond log I can see that htere is no message being received when that happen.

Can you please repeate the experiment adding this to `etc/magma/mme.log`

```
log_level: DEBUG
```

**Comment by jpad-freedomfi** [comment]
hi @uri200 please see updated logs attached with MME in debug with grpc logging enabled. Logs looks much more verbose. 

[periodic_tau_session_term_test.zip](https://github.com/magma/magma/files/5533380/periodic_tau_session_term_test.zip)


Timeline of the test:
Attach at 12:14
Run a couple speed tests and data for ~4min
Silent detach at 12:18
Release UE context at 12:18
Expect periodic tau timer triggered termination at ~1:12pm
captures stopped at ~1:30

**Comment by ulaskozat** [comment]
@jpad-freedomfi , in mme logs, I don't see the expiration of reachability timer. Not sure if the second context release from the eNB side interferes with the timer or not.

**Comment by ulaskozat** [comment]
@jpad-freedomfi , my bad, it looks like I missed the line:
`004876 Thu Nov 12 12:16:24 2020 7FCB41DDE700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :3685    Expired- Mobile reachability timer for ue_id 0x00000001
`

If you look at [here](https://github.com/magma/magma/blob/0026edd68658e700bd2c32e89e6c3ccea787cd5b/lte/gateway/c/oai/tasks/mme_app/mme_app_location.c#L335) and [here](https://github.com/magma/magma/blob/0026edd68658e700bd2c32e89e6c3ccea787cd5b/lte/gateway/c/oai/tasks/mme_app/mme_app_location.c#L340) you will see that reachability timer is 58 minutes (as default) and after that timer expires, a timer for implicit detach is started (which again expires in 58 minutes). So with the default timer values, you need to wait for almost 2 hours for an actual detach to be triggered. To experiment with this, I suggest to modify the default value of T3412 in `/etc/magma/templates/mme.conf.template` to a smaller value so that you don't need to wait that long...

**Comment by ulaskozat** [comment]
This looks quite old. Closing it.
