### ISSUE TITLE
Gy only relay no CCR-U after Top Up RAR/RAA exchange

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3549]
### Your Environment

- **Version:** v1.3 Stable
- **Affected Component:** Federation Gateway, Access Gateway
- **Affected Subcomponent:** Session_proxy & Sessiond
- **Deployment Environment:** e.g. AWS (orc8r + FeG), bare-metal (AGW)

### Describe the Issue

When using external OCS, with Gy only relay, we see issue where after balance is exhausted, and top up is applied, after re-auth request / answer, magma does not perform update to get new quota to allow data flow to resume after top up. 

**To Reproduce**
1. Configure network for Gy only relay with external OCS
2. Configure a subscriber with zero balance
3. Attach the UE for that subscriber and observe FUI/FUA in the CCA-I
4. Apply a top up to the subscriber account in OCS
6. observe RAR/RAA are exchanged
7. observe in sessiond logs that "UPDATE NOT NEEDED" is logged and CCR-U for new quota is not sent to OCS <timestamp Oct 30 08:21:57>
8. observe data flow remains blocked after top up

**Expected behavior**
After the RAR/RAA exchange, and CCR-U should be sent to OCS with requested quota to allow data to flow after top up. 

**Additional context**
Attached are sessiond logs with gRPC logging enabled
FeG Gy pcap
AGW S1 pcap
[TopUP_noCCRU.zip](https://github.com/magma/magma/files/5466121/TopUP_noCCRU.zip)

Here is diagram of test network
[Magma + OCS FreedomFi Lab Topology.pdf](https://github.com/magma/magma/files/5466134/Magma.%2B.OCS.FreedomFi.Lab.Topology.pdf)

@joary @amarpad

**Comment by themarwhal** [comment]
This is probably due to the credit install failing as seen in SessionD log here:
```
Oct 30 08:20:57 agw sessiond[26743]: I1030 08:20:57.203830 26743 GrpcMagmaUtils.cpp:38]
Oct 30 08:20:57 agw sessiond[26743]:   magma.lte.CreateSessionResponse {
Oct 30 08:20:57 agw sessiond[26743]:       credits {
Oct 30 08:20:57 agw sessiond[26743]:         sid: "IMSI315010999900108"
Oct 30 08:20:57 agw sessiond[26743]:         charging_key: 1
Oct 30 08:20:57 agw sessiond[26743]:         credit {
Oct 30 08:20:57 agw sessiond[26743]:           validity_time: 900
Oct 30 08:20:57 agw sessiond[26743]:           is_final: true
Oct 30 08:20:57 agw sessiond[26743]:           final_action: REDIRECT
Oct 30 08:20:57 agw sessiond[26743]:           granted_units {
Oct 30 08:20:57 agw sessiond[26743]:             total {
Oct 30 08:20:57 agw sessiond[26743]:             }
Oct 30 08:20:57 agw sessiond[26743]:             tx {
Oct 30 08:20:57 agw sessiond[26743]:             }
Oct 30 08:20:57 agw sessiond[26743]:             rx {
Oct 30 08:20:57 agw sessiond[26743]:             }
Oct 30 08:20:57 agw sessiond[26743]:           }
Oct 30 08:20:57 agw sessiond[26743]:           redirect_server {
Oct 30 08:20:57 agw sessiond[26743]:             redirect_address_type: URL
Oct 30 08:20:57 agw sessiond[26743]:             redirect_server_address: "http://www.sersimple.com/PortalCautivo.php"
Oct 30 08:20:57 agw sessiond[26743]:           }
Oct 30 08:20:57 agw sessiond[26743]:         }
Oct 30 08:20:57 agw sessiond[26743]:         result_code: 4012
Oct 30 08:20:57 agw sessiond[26743]:         tgpp_ctx {
Oct 30 08:20:57 agw sessiond[26743]:           gy_dest_host: "gy00.inew-cs.com"
Oct 30 08:20:57 agw sessiond[26743]:         }
Oct 30 08:20:57 agw sessiond[26743]:       }
Oct 30 08:20:57 agw sessiond[26743]:       static_rules {
Oct 30 08:20:57 agw sessiond[26743]:         rule_id: "metering_rule"
Oct 30 08:20:57 agw sessiond[26743]:       }
Oct 30 08:20:57 agw sessiond[26743]:       session_id: "IMSI315010999900108-16726"
Oct 30 08:20:57 agw sessiond[26743]:       tgpp_ctx {
Oct 30 08:20:57 agw sessiond[26743]:         gx_dest_host: "gx-less.magma.com"
Oct 30 08:20:57 agw sessiond[26743]:         gy_dest_host: "gy00.inew-cs.com"
Oct 30 08:20:57 agw sessiond[26743]:       }
Oct 30 08:20:57 agw sessiond[26743]:   }
Oct 30 08:20:57 agw sessiond[26743]: I1030 08:20:57.203850 26743 LocalSessionManagerHandler.cpp:267] Processing a CreateSessionResponse for IMSI315010999900108-16726
Oct 30 08:20:57 agw sessiond[26743]: I1030 08:20:57.203866 26743 SessionState.cpp:1181] Credit init failed for imsi IMSI315010999900108 and charging key 1
Oct 30 08:20:57 agw sessiond[26743]: I1030 08:20:57.203883 26743 LocalEnforcer.cpp:754] Not activating Gy tracked metering_rule because credit w/ rating group 1 does not exist
Oct 30 08:20:57 agw sessiond[26743]: I1030 08:20:57.203902 26743 PipelinedClient.cpp:289] Activating 0 static rules and 0 dynamic rules for IMSI315010999900108 and ip 192.168.128.137
```
Since the result code is not 2001, the credit is never installed, no rules are installed. This is why the ReAuth does not do anything.

**Comment by uri200** [comment]
It looks like that subscirber doesn't have any quota on it. The CCA-I returns directly a 4012 messages, meaning quota limit is reached. Since quota limit is reach, sessiond decides to terminate the session

**Comment by themarwhal** [comment]
Hi @jpad-freedomfi 
As Oriol mentioned above, when we get a credit with result code 4012 (MSCC), we do not install the credit as it does not have credit. (This will also not install any policies with the RG). 
When a ReAuth is received, it applies the ReAuth to all credits that are installed in the session. In this case, no credit is installed, so nothing is done. 
What is the behavior you are expecting when PCEF receives a CCA-I with MSCC result code=4012?

**Comment by jpad-freedomfi** [comment]
Hi All, 

We retested this today. The Cyan changed the code replied in step 3 above to a 2001. However, we still see similar behavior.

Here is the observed flow:

1. start with zero balance
2. attach UE
3. get 2001 with FUI/FUA in CCA-I
4. wait for validity time to expire (2min)
5. observe no CCR-U to update quota after validity time expiry

Cyan was expecting the Gy credit session to be activated so that it could be updated later. 

Note log line 140 after the CCA-I is received:
`Nov 10 07:53:57 agw sessiond[12302]: I1110 07:53:57.416188 12302 LocalEnforcer.cpp:754] Not activating Gy tracked metering_rule because credit w/ rating group 1 does not exist`

In discussion with @joary today it sounds like we agree the credit rule should be activated even if no credit is received in CCA-I so that it can receive a top-up in the future. 

Logs attached:
FeG Gy pcap
S1 pcap
SessionD debug log with grpc
mme.log
[Cyan14.zip](https://github.com/magma/magma/files/5520933/Cyan14.zip)

**Comment by themarwhal** [comment]
Thanks for the new set of logs. If we receive a credit with 2001 it should work, but apparently it does not. Taking a look... 
Ok it looks like we reject credits that have all 0 grant: https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/SessionState.cpp#L1232

This does not seem to be the behavior I want. Let me investigate into why this logic is there before removing it. 
Thanks for your patience!

**Comment by themarwhal** [comment]
A fix to allow GSUs with all 0 credit was merged into master and 1.3 branch.

**Comment by jpad-freedomfi** [comment]
Hi @themarwhal, 

We tested 1.3 branch at commit de7c8e314fc2388da17f327adae838a919fda2e9. 

We see improved handling of attach with 0 balance or absent GSU in CCA-I. Now credits are installed with zero quota. 

This means when top up is performed, RAR/RAA occur, and quota is applied to existing rule. 

However, we see 3 issues still with Gy only relay setup
The UE can attach, rules are installed in sessiond with zero quota, when top up occurs, quota is updated and data is accessible by user. This looks great. 

We have 3 open issues: (I commented on GitHub Issue as well)

1. When Magma sees redirect, it appears validity timer is not being honored. So we don’t see CCR-U after timer expiry if redirect has occurred. 
1.1. This is true of attach with zero balance and immediate redirect and for attach with balance then exhaust and trigger redirect. (in files, Cyan73 is start with zero balance, Cyan74 is start with 1kB balance, both fail to send validity timer triggered update)
[validity_timer_after_redirect.zip](https://github.com/magma/magma/files/5585457/validity_timer_after_redirect.zip)

2. When we have 2 rating groups (rating group 1 and 100), and we attach with zero quota for RG 1, non-zero for RG100, when we perform top up, reauth occurs, then magma produces 2 CCR-Us, one separately for each RG and sends them back to back. (in Cyan75.pcap note reauth at 6:48:52, then 2 CCR-U at 6:48:53)
2.1 This causes Cyan to crash. They are fixing the crash, but
2.2 They have asked if Magma can send a single CCR-U with MSCC with both RGs instead of 2 separate messages.[double_ccr_u.zip](https://github.com/magma/magma/files/5585453/double_ccr_u.zip)
3. Potential issue with redirection with multiple RGs. This could also be Joey misconfiguration. We are not seeing traffic going to RG 100 which Cyan is zero-rating. I tried to use the policy rule with following JSON to capture traffic from www.play-hookey.com which for me resolves to 173.13.214.106. But no traffic is being accounted for that RG in SessionD logs, and perhaps related, when zero balance on RG1, this site get redirected as well, despite having quota.
3.1 Curious if you have example rules. The API example produces an error, so I’m unsure how to format 
3.2. Using API example I get "Invalid Argument: Can't mix old ipv4_src/ipv4_dst type with the new ip_src/ip_dst"

{
  "app_name": "NO_APP_NAME",
  "app_service_type": "NO_SERVICE_TYPE",
  "flow_list": [{
    "action": "PERMIT",
    "match": {
      "direction": "UPLINK",
      "ip_proto": "IPPROTO_IP",
      "ip_dst": {
        "address": "173.13.214.106/16",
        "version": "IPv4"
      }
    }
  }, {
    "action": "PERMIT",
    "match": {
      "direction": "DOWNLINK",
      "ip_proto": "IPPROTO_IP",
      "ip_src": {
        "address": "173.13.214.106/16",
        "version": "IPv4"
      }
    }
  }],
  "id": "captivo",
  "priority": 10,
  "rating_group": 100,
  "tracking_type": "ONLY_OCS"
}

**Comment by themarwhal** [comment]
Hi @jpad-freedomfi! Sorry about the delayed response, I was on break last week. Thank you for the detailed notes. I will first look into item 1 and get back to you, this seems like a bug on our end. 
With regards to 2, we currently generate a CCR for each rating group. Of course, it is possible to change this behavior but it is a medium sized item as I'll have to think through all the side effects if we do make the change. I wonder if it is the case with most OCSs that this behavior would cause the OCS to crash.
Let me get back to you on item 3 also later today.

**Comment by jpad-freedomfi** [comment]
Hi @themarwhal Any updates on items 1 and 3 from my comment above? 

Thanks.

**Comment by themarwhal** [comment]
Hi @jpad-freedomfi 
I think 1 will be improved by this PR: https://github.com/magma/magma/pull/3872

**Comment by themarwhal** [comment]
For redirection, is this via FUA-Redirect?

**Comment by jpad-freedomfi** [comment]
@themarwhal Yes, FUA-Redirect

**Comment by themarwhal** [comment]
@jpad-freedomfi Unfortunately, our implementation applies FUA-redirect rule to the entire session, not for the specific RG. I can work on a fix for this soon. 
Are you still having trouble configuring the PolicyRule via the API? The object you pasted seemed fine when I try to add it via the API.

**Comment by jpad-freedomfi** [comment]
@themarwhal ok. Let my discuss with @joary and see how that works for the customer w.r.t. FUA-redirect being entire session. 

Regarding the PolicyRule, it gets accepted via API, but I never see data being counted as used in that new RG even when I go to the website at the IP in the rule. So felt like I must have configured it wrong. Is there any documentation on how rules work in Magma? Like precedence if two rules match?

If we wanted to zero rate a website, or charge a different rate for it, do you have an example config for a public website? 

The example in the API if you try to apply it complains about the old and new style of IP. Can you clarify what that error is saying? 
exact text of error is:
`"message": "Invalid Argument: Can't mix old ipv4_src/ipv4_dst type with the new ip_src/ip_dst"`

Here is the body of the API call that produces that error (from API example):
```
{
  "app_name": "NO_APP_NAME",
  "app_service_type": "NO_SERVICE_TYPE",
  "assigned_subscribers": [
    "IMSI1234567890",
    "IMSI0987654321"
  ],
  "flow_list": [
    {
      "action": "PERMIT",
      "match": {
        "direction": "UPLINK",
        "ip_dst": {
          "address": "192.168.0.1/24",
          "version": "IPv4"
        },
        "ip_proto": "IPPROTO_IP",
        "ip_src": {
          "address": "192.168.0.1/24",
          "version": "IPv4"
        },
        "ipv4_dst": "0.0.0.0/0",
        "ipv4_src": "192.168.0.1/24",
        "tcp_dst": 0,
        "tcp_src": 0,
        "udp_dst": 0,
        "udp_src": 0
      }
    }
  ],
  "id": "All ICMP",
  "monitoring_key": "SGVsbG8gV29ybGQ=",
  "priority": 0,
  "qos_profile": "profile0",
  "rating_group": 20,
  "redirect": {
    "address_type": "IPv4",
    "server_address": "string",
    "support": "DISABLED"
  },
  "tracking_type": "ONLY_OCS"
}
```

**Comment by koolzz** [comment]
> @themarwhal ok. Let my discuss with @joary and see how that works for the customer w.r.t. FUA-redirect being entire session.
> 
> Regarding the PolicyRule, it gets accepted via API, but I never see data being counted as used in that new RG even when I go to the website at the IP in the rule. So felt like I must have configured it wrong. Is there any documentation on how rules work in Magma? Like precedence if two rules match?
> 
> If we wanted to zero rate a website, or charge a different rate for it, do you have an example config for a public website?
> 
> The example in the API if you try to apply it complains about the old and new style of IP. Can you clarify what that error is saying?
> exact text of error is:
> `"message": "Invalid Argument: Can't mix old ipv4_src/ipv4_dst type with the new ip_src/ip_dst"`
> 
> Here is the body of the API call that produces that error (from API example):
> 
> ```
> {
>   "app_name": "NO_APP_NAME",
>   "app_service_type": "NO_SERVICE_TYPE",
>   "assigned_subscribers": [
>     "IMSI1234567890",
>     "IMSI0987654321"
>   ],
>   "flow_list": [
>     {
>       "action": "PERMIT",
>       "match": {
>         "direction": "UPLINK",
>         "ip_dst": {
>           "address": "192.168.0.1/24",
>           "version": "IPv4"
>         },
>         "ip_proto": "IPPROTO_IP",
>         "ip_src": {
>           "address": "192.168.0.1/24",
>           "version": "IPv4"
>         },
>         "ipv4_dst": "0.0.0.0/0",
>         "ipv4_src": "192.168.0.1/24",
>         "tcp_dst": 0,
>         "tcp_src": 0,
>         "udp_dst": 0,
>         "udp_src": 0
>       }
>     }
>   ],
>   "id": "All ICMP",
>   "monitoring_key": "SGVsbG8gV29ybGQ=",
>   "priority": 0,
>   "qos_profile": "profile0",
>   "rating_group": 20,
>   "redirect": {
>     "address_type": "IPv4",
>     "server_address": "string",
>     "support": "DISABLED"
>   },
>   "tracking_type": "ONLY_OCS"
> }
> ```

Just remove the ipv4_src/ipv4_dst as you already define ip_src and ip_dst

**Comment by 119Vik** [comment]
@themarwhal  just to confirm, https://github.com/magma/magma/pull/3872 should fix issue on AGW side but not on FeGW side ?

**Comment by themarwhal** [comment]
@119Vik The PR is an AGW only change that will allow validity timer based update even when FUA is enabled.

**Comment by themarwhal** [comment]
@jpad-freedomfi Can I close this issue?
