### ISSUE TITLE
[CI/CD] Set up Artifactory for official Magma registry

### ISSUE THREAD

**Issue by ttx** [magma/magma#3588]
In order to provide an official public Magma registry for DEB, RPM, Helm, Docker binary artifacts, the Magma project would like to run an artifact repository server.

1- [x] Choose artifact repository software and operation mode - all
2- [x] Select cloud provider - all
3- [x] Specify needed resources - @mattymo @tmdzk @ttx
4- [x] Provide infrastructure resources (PostgreSQL server, Artifactory host, BLOB Storage) - @ttx
5- [x] Procure Artifactory Pro license - @ttx
6- [ ] Install and configure Artifactory - @mattymo

**Step 1 - Choose artifact repository software**
Several options were considered but the CI/CD team opted for JFrog Artifactory Pro software, self-hosted on cloud resources.

**Step 2 - Select cloud provider**
Given the nature of the service (a public repository), outbound bandwidth cost is a key concern, and can accidentally result in a lot of unpredictable cost. Cloud providers typically charge for outbound traffic from object storage and from host. OVHCloud provides [predictable cost](https://twitter.com/holgermu/status/1323285664981417985), with no additional charge for API calls or outbound bandwidth for compute hosts. However, they do charge for internal S3->EC2 traffic. To workaround that, we can attach up to 4Tb Block Storage instead of using Object Storage.

**Step 3 - Specify needed resources**
- Version of PostgreSQL: v9.6, v10, v11 or v12
- RAM/Storage for PostgreSQL database: 0.5Gb/8Gb, 1Gb/16Gb, 2Gb/32Gb, 4Gb/64Gb
- vCPU/RAM/Local Disk for Artifactory host: 2/7Gb/50Gb, 2/15Gb/50Gb, 4/15Gb/100Gb
- Required size of Artifact storage: ?

**Comment by mattymo** [comment]
@ttx Here are the resource requirements:
1 - PostgreSQL v11
2 - 4/64gb - a rather dated knowledgebase article from JFrog says "estimate 1gb of DB storage for every 100GB of artifacts". If we have 4TB of storage, we need 40gb of DB storage.
3 - Artifactory host can probably be 2/15/Gb/50Gb
4 - Artifact storage is going to be somewhere between 200GB and 4TB but that all depends on what we end up retaining. I plan to consume S3 Swift storage in OVH

**Comment by ttx** [comment]
OK, I'll set aside some time to set those resources up, hopefully this will be done before the end of the week.

**Comment by ttx** [comment]
Status update: Infrastructure resources are up (artifactory host, database, cloud account for object storage)

**Comment by ttx** [comment]
Status update:
- @mattymo has started deploying the instance, DNS entries were created under magmacore.org. This currently uses the 30-day trial license
- @ttx has started the process of procuring a permanent Artifactory license with jFrog.

**Comment by ttx** [comment]
Status update: License is now procured and provided.

**Comment by ttx** [comment]
@mattymo: any progress ?
