### ISSUE TITLE
Re-analyze the redis based pipelined state 

### ISSUE THREAD

**Issue by koolzz** [magma/magma#3632]
Currently the pipelined has a few in memory(optionally redis backed) dictionaries, such as policy rule name/version store, ipv6 prefix maps, as well as tunnel map.

We want to avoid maintaining pipelined state as almost everything can be reconstructed from session->pipelined setup call. We want restarts to be seamless:
 - all user traffic must be uninterrupted
 - things like RS->RA responses should be sent even if container just restarted
 - enforcement stats should be preserved

*As we're refactoring a lot of code with 5G changes I'm postponing this issue until all that code is landed*

**Comment by ssanadhya** [comment]
Adding this issue to the Stateless Access Gateway epic on ZenHub https://app.zenhub.com/workspaces/magma-5f6e766acfab7d26479e8771/issues/magma/magma/1205

**Comment by ekowtaylor** [comment]
@koolzz since this is pending the 5G MVC work, I'm removing it as a blocker for 1.5

**Comment by koolzz** [comment]
The main chunk of this will be done for 1.5 (this includes the high pri redis dicts, that are in the critical path). Some redis dicts will survive and will be addressed for 1.6

We'll just tag individual tasks with 1.5 (such as flat rate reporting)

**Comment by koolzz** [comment]
Closing this as I've looked over everything and broken it apart into multiple individual tasks
