### ISSUE TITLE
NMS Gateway Generic Command modal disappeared in 1.3

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3679]
### Your Environment

- **Version:** v1.3
- **Affected Component:**  NMS
- **Affected Subcomponent:** Gateway specific modal
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

In previous versions there was a NMS modal tab that enabled issuing "Generic Commands" to a specific gateway. (see image). The API still exists, but this tab/modal no longer exists in the NMS v1.3. 

We use this modal during installation and troubleshooting customer sites. 

**Screenshots**
Old View with "Command" tab in edit modal for specific gateway
![Screen Shot 2020-11-11 at 9 06 54 AM](https://user-images.githubusercontent.com/61293007/98835393-99dc9400-23fd-11eb-8b95-c20eb463c5a3.png)
![Screen Shot 2020-11-11 at 9 06 45 AM](https://user-images.githubusercontent.com/61293007/98835395-99dc9400-23fd-11eb-8d10-88398e9ce167.png)
New NMS gateway specific modal without "command" tab or equivalent replacement
![Screen Shot 2020-11-11 at 9 08 53 AM](https://user-images.githubusercontent.com/61293007/98835456-ac56cd80-23fd-11eb-9f5f-ba3e32b10609.png)

**Comment by jpad-freedomfi** [comment]
@MaksymDryha FYI, this is in backlog for us as well.

**Comment by karthiksubraveti** [comment]
@jpad-freedomfi  just curious, what specific command do you trigger off this modal ? We added a separate reboot button to the gateway page. Trying to understand the usecase better

**Comment by jpad-freedomfi** [comment]
@karthiksubraveti we have 2 main use cases right now.

1. Remote access. We have a reverse ssh service we trigger via "connect" and "disconnect" to trigger remote shell access. This may be deprecated after v1.4 openVPN solution, but until that is deployed and stable we use our reverse ssh solution REGULARLY in our early deployments. 
2. Port forwarding configuration. In many of our deployments, the operator needs to have webUI, SNMP, SSH access to the eNB connect behind the AGW. We have created a portforward service, that is configured via a generic command so that after eNB gets a DHCP lease from AGW, we can forward ports as needed from WAN IP (uplink_br0) of AGW. 
3. Disaster recovery. In certain scenarios, we have lost reverse SSH access, but maintained connection to orchestrator. In this scenario we have used Generic commands to issue bash commands to recover access. 

While I would love a future where we never need generic commands, the utility is too crucial at this stage to forgo.

**Comment by karthiksubraveti** [comment]
> @karthiksubraveti we have 2 main use cases right now.
> 
> 1. Remote access. We have a reverse ssh service we trigger via "connect" and "disconnect" to trigger remote shell access. This may be deprecated after v1.4 openVPN solution, but until that is deployed and stable we use our reverse ssh solution REGULARLY in our early deployments.
> 2. Port forwarding configuration. In many of our deployments, the operator needs to have webUI, SNMP, SSH access to the eNB connect behind the AGW. We have created a portforward service, that is configured via a generic command so that after eNB gets a DHCP lease from AGW, we can forward ports as needed from WAN IP (uplink_br0) of AGW.
> 3. Disaster recovery. In certain scenarios, we have lost reverse SSH access, but maintained connection to orchestrator. In this scenario we have used Generic commands to issue bash commands to recover access.
> 
> While I would love a future where we never need generic commands, the utility is too crucial at this stage to forgo.

Thanks for providing the context here.
