### ISSUE TITLE
Processing config update gw1 [json mconfig. get none type exception]

### ISSUE THREAD

**Issue by sarathbrp** [magma/magma#37]
Mar  6 23:57:57 magma-dev control_proxy[2761]: 2019-03-06T23:57:57.548Z [127.0.0.1 -> logger-controller.magma.test,8443] "POST /magma.orc8r.LoggingService/Log HTTP/2" 200 5bytes 0.016s
Mar  6 23:58:00 magma-dev control_proxy[2761]: 2019-03-06T23:58:00.175Z [127.0.0.1 -> metricsd-controller.magma.test,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.034s
Mar  6 23:58:00 magma-dev control_proxy[2761]: 2019-03-06T23:58:00.175Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 7bytes 0.014s
Mar  6 23:58:00 magma-dev policydb[2123]: INFO:root:Processing 0 policy updates (resync=True)
Mar  6 23:58:00 magma-dev control_proxy[2761]: 2019-03-06T23:58:00.175Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 7bytes 0.013s
Mar  6 23:58:00 magma-dev subscriberdb[2125]: INFO:root:Processing 0 subscriber updates (resync=True)
Mar  6 23:58:00 magma-dev enodebd[2160]: INFO:root:Checking mme connection
Mar  6 23:58:15 magma-dev enodebd[2160]: INFO:root:Checking mme connection
Mar  6 23:58:27 magma-dev control_proxy[2761]: 2019-03-06T23:58:27.549Z [127.0.0.1 -> logger-controller.magma.test,8443] "POST /magma.orc8r.LoggingService/Log HTTP/2" 200 5bytes 0.014s
Mar  6 23:58:27 magma-dev control_proxy[2761]: 2019-03-06T23:58:27.549Z [127.0.0.1 -> checkind-controller.magma.test,8443] "POST /magma.orc8r.Checkind/Checkin HTTP/2" 200 12bytes 0.021s
Mar  6 23:58:27 magma-dev magmad[2101]: INFO:root:Checkin Successful!
Mar  6 23:58:28 magma-dev magmad[2101]: INFO:root:[SyncRPC] Got heartBeat from cloud
Mar  6 23:58:29 magma-dev control_proxy[2761]: 2019-03-06T23:58:29.684Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 41bytes 0.032s
Mar  6 23:58:29 magma-dev magmad[2101]: INFO:root:Processing config update gw1
Mar  6 23:58:29 magma-dev magmad[2101]: ERROR:root:Invalid config! Magmad service config missing
Mar  6 23:58:29 magma-dev control_proxy[2761]: 2019-03-06T23:58:29.684Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 85bytes 0.005s
Mar  6 23:58:29 magma-dev magmad[2101]: INFO:root:Processing streamed config update d7eaeeed-e662-4310-9f01-ebebb95100a4
Mar  6 23:58:29 magma-dev magmad[2101]: ERROR:asyncio:Exception in callback StreamingMconfigCallback.process_update('mconfig_views', [key: "d7eaee...": \"0\"\n}"
Mar  6 23:58:29 magma-dev magmad[2101]: ], True)
Mar  6 23:58:29 magma-dev magmad[2101]: handle: <Handle StreamingMconfigCallback.process_update('mconfig_views', [key: "d7eaee...": \"0\"\n}"
Mar  6 23:58:29 magma-dev magmad[2101]: ], True)>
Mar  6 23:58:29 magma-dev magmad[2101]: Traceback (most recent call last):
Mar  6 23:58:29 magma-dev magmad[2101]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
Mar  6 23:58:29 magma-dev magmad[2101]:     self._callback(*self._args)
Mar  6 23:58:29 magma-dev magmad[2101]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/magmad/streaming_mconfig_callback.py", line 59, in process_update
Mar  6 23:58:29 magma-dev magmad[2101]:     allow_unknown_fields=self._allow_unknown_fields,
Mar  6 23:58:29 magma-dev magmad[2101]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/configuration/mconfig_managers.py", line 244, in deserialize_mconfig
Mar  6 23:58:29 magma-dev magmad[2101]:     cfgs_by_key_json = json_mconfig.get('configs_by_key', {})
Mar  6 23:58:29 magma-dev magmad[2101]: AttributeError: 'NoneType' object has no attribute 'get'
Mar  6 23:58:30 magma-dev enodebd[2160]: INFO:root:Checking mme connection

**Comment by rpraveen** [comment]
@sarathbrp which commit do you see the issue from? This should have been fixed by https://github.com/facebookincubator/magma/pull/6 which landed 2 days ago.

**Comment by sarathbrp** [comment]
Hi Praveen,
This issue is from yesterday code, not sure which commit I took.
Yesterday I ran git pull and ran the code with encountering this error.

I always ran git pull before the start of the day.
Thanks,
SP

**Comment by xjtian** [comment]
Hey @sarathbrp, this code path has been deleted since you opened the issue. In any case, it was benign (albeit an annoying logspam). If you git pull and `sudo service magma@* stop && sudo service magma@magmad restart) in your magma VM, you should no longer see this.

The actual config streaming codepath was unaffected - what you're looking for in the log is

```
Mar 6 23:58:29 magma-dev magmad[2101]: INFO:root:Processing config update gw1
```
