### ISSUE TITLE
NMS UI not auto refreshing status of gateways

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3708]
### Your Environment

- **Version:** v1.3
- **Affected Component:**  NMS
- **Affected Subcomponent:** page <tenant>/equipment/overview/gateway
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

The NMS page does not auto-refresh the status of Gateways. This causes "good/green" to switch to "bad/red" after ~5 min. If the user refreshes the browser page, the status refreshes and becomes correct again.  

**To Reproduce**
1. Go to <tenant>/equipment/overview/gateway in NMS
2. Note the checkin time / status for each gateway displayed
3. Let the page sit for 5min or more
4. See that status has changed to red/bad for any AGW that had been green and last checkin time is old
5. refresh the browser page, see that AGWs that were just "bad" are now "good" again. 

**Expected behavior**
The expected behavior is that page triggers browser pulls data periodically on its own to keep status accurate. 

I have tested with Chrome, Safari, and Firefox, so I don't think it is browser specific issue.

**Comment by jpad-freedomfi** [comment]
@MaksymDryha adding to our backlog as well.

**Comment by karthiksubraveti** [comment]
Yes. This is something we intend to fix it sometime. Currently the state is read and set in the context and we don't refresh it later on. This should be periodically refreshed. @MaksymDryha is this something you would be able to address ? I can provide you pointers to understand the underlying issue better.
