### ISSUE TITLE
Upgrade Orc8r failed due to missing rootCA.key

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#3713]
### Your Environment

- **Version:v1.1**
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator secrets manager
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

During upgrade from V1.1 to V1.2/V1.3 Installation scripts are requesting the rootCA.key
v1.1
https://github.com/magma/magma/blob/v1.1/orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf#L32

v1.2
https://github.com/magma/magma/blob/v1.2/orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf#L37

v1.3
https://github.com/magma/magma/blob/v1.3/orc8r/cloud/deploy/terraform/orc8r-helm-aws/scripts/create_orc8r_secrets.py#L23
https://github.com/magma/magma/blob/v1.3/orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf#L37

However some partners don't have the rootCA.key in their secrets manager , they lost it or deleted it, therefore installation is failing. 

**Steps to Reproduce**

Upgrade procedure to v1.2/v1.3, after "terraform apply" error of "Invalid Index" appeared

**Expected behavior**
Terraform apply shown any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/37117037/99009037-4cebe100-2515-11eb-91a0-1dacd19c8722.png)

**Additional context**
Will be great to add in prerequisites https://magma.github.io/magma/docs/orc8r/upgrade_1_2#prerequisites  which certificates are needed for the upgrade(new version), and standardize all needed certificates across different versions. (why do we need rootCA.key for some versions and some we don't)

**Comment by karthiksubraveti** [comment]
@wallyrb do we need more documentation here - https://docs.magmacore.org/docs/orc8r/dev_security#certificates or should we close this issue ?

**Comment by wallyrb** [comment]
yes we can close it. Thanks!
