### ISSUE TITLE
Upgrade Orc8r failed due to Postgres version was bumped to 9.6.18

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#3714]
### Your Environment

- **Version:v1.1**
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator database
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

During Upgrade from v1.1 to v1.3(or v1.2) was failing because the postgres version was unexpectedly upgraded to 9.6.18. The variables.tf contain a lower version(9.6.15)

**To Reproduce**

1. Installation of Orc8r v1.1
2. Follow upgrade guide https://magma.github.io/magma/docs/orc8r/upgrade_1_2
3. After terraform apply, error will appear https://magma.github.io/magma/docs/orc8r/upgrade_1_2#terraform-apply
4. Got the error  "Cannot upgrade Postgres from 9.6.18 to 9.6.15 status code: 400"

**Expected behavior**
terraform apply should work without issues

**Screenshots**
![image](https://user-images.githubusercontent.com/37117037/99011023-1e700500-2519-11eb-8894-e10e26ce65a9.png)

**Additional context**
To mitigate the issue, had to change the source to local repo and change the below line of the code to 9.6.18.
https://github.com/magma/magma/blob/v1.3/orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf#L209

**Comment by AyliD** [comment]
express-wifi's orc8r upgrade also affected on that on bump to version 20 on instance.

**Comment by karthiksubraveti** [comment]
When we run through our terraform based deployment, we might be turning up automatic minor upgrades
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#auto_minor_version_upgrade

That can cause us to potentially go out of sync here.
