### ISSUE TITLE
Dnsd errors when trying to connect gw to orchestrator

### ISSUE THREAD

**Issue by limitsg** [magma/magma#375]
I am bringing up a gateway and orchestrator on my Mac using the instructions 
https://facebookincubator.github.io/magma/docs/basics/quick_start_guide

So far, my gateway VM and orchestrator docker are up on their own, but they are unable to establish a connection upon doing a "fab register_vm"

git rev-parse HEAD
46c3196fb9d27eac70acb1cfa5a625093bba432f

Any ideas on what may be missing?

Logs from gw
==
Jun 21 06:52:05 packer-virtualbox-iso-1542061022 systemd[1]: Failed to start Magma dnsd service.

Jun 21 06:52:05 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Unit entered failed state.

Jun 21 06:52:05 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Failed with result 'exit-code'.

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Service hold-off time over, scheduling restart.

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: Stopped Magma dnsd service.

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: Starting Magma dnsd service...

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]: Traceback (most recent call last):

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:   File "/usr/local/bin/generate_dnsd_config.py", line 86, in <module>

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:     main()

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:   File "/usr/local/bin/generate_dnsd_config.py", line 82, in main

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:     CONFIG_OVERRIDE_DIR, get_context())

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:   File "/usr/local/bin/generate_dnsd_config.py", line 72, in get_context

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:     context['addresses'] = _get_addresses(cfg, mconfig)

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:   File "/usr/local/bin/generate_dnsd_config.py", line 35, in _get_addresses

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]:     for record in mconfig['records']:

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 dnsd[23980]: KeyError: 'records'

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Control process exited, code=exited status=1

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: Failed to start Magma dnsd service.

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Unit entered failed state.

Jun 21 06:52:11 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Failed with result 'exit-code'.

Jun 21 06:52:16 packer-virtualbox-iso-1542061022 systemd[1]: magma@dnsd.service: Service hold-off time over, scheduling restart.

Jun 21 06:52:16 packer-virtualbox-iso-1542061022 systemd[1]: Stopped Magma dnsd service.

Jun 21 06:52:16 packer-virtualbox-iso-1542061022 systemd[1]: Starting Magma dnsd service...

Jun 21 06:52:16 packer-virtualbox-iso-1542061022 magmad[22336]: ERROR:root:GetChallenge error! [StatusCode.NOT_FOUND] Failed to find gateway record: Network ID Lookup Error for hwId 0d6f7c62-f924-4686-b491-14fe6864360b: rpc error: code = NotFound desc = No record for query

Jun 21 06:52:16 packer-virtualbox-iso-1542061022 magmad[22336]: INFO:root:Retrying bootstrap in 30 seconds

**Comment by xjtian** [comment]
To bootstrap connection between the gateway VM and orchestrator cloud, you have to seed the system with some configs. I'll be giving the docs some love this week to update them with the proper procedure, but I'll outline them here first.

Basically, you need to create the following configs via the API (screenshots are from https://localhost:9443 which is where local orchestrator cloud runs):

1. Network DNS configs

![Screen Shot 2019-07-01 at 1 21 14 PM](https://user-images.githubusercontent.com/3249794/60464338-1e60b500-9c03-11e9-9dc2-6917f828d8ed.png)

```
{
  "enable_caching": false,
  "local_ttl": 0,
  "records": []
}
```

2. Network cellular configs (remove fdd_configs section from the default value, or paste the snippet below)

![Screen Shot 2019-07-01 at 1 19 28 PM](https://user-images.githubusercontent.com/3249794/60464258-de99cd80-9c02-11e9-8427-158009230701.png)

```
{
  "epc": {
    "cloud_subscriberdb_enabled": false,
    "default_rule_id": "default_rule_1",
    "lte_auth_amf": "gAA=",
    "lte_auth_op": "EREREREREREREREREREREQ==",
    "mcc": "001",
    "mnc": "01",
    "network_services": [
      "metering",
      "dpi",
      "policy_enforcement"
    ],
    "relay_enabled": false,
    "sub_profiles": {
      "additionalProp1": {
        "max_dl_bit_rate": 20000000,
        "max_ul_bit_rate": 100000000
      },
      "additionalProp2": {
        "max_dl_bit_rate": 20000000,
        "max_ul_bit_rate": 100000000
      },
      "additionalProp3": {
        "max_dl_bit_rate": 20000000,
        "max_ul_bit_rate": 100000000
      }
    },
    "tac": 1
  },
  "feg_network_id": "example_feg_network",
  "ran": {
    "bandwidth_mhz": 20,
    "earfcndl": 44590,
    "special_subframe_pattern": 7,
    "subframe_assignment": 2,
    "tdd_config": {
      "earfcndl": 44590,
      "special_subframe_pattern": 7,
      "subframe_assignment": 2
    }
  }
}
```

3. Gateway configs

![Screen Shot 2019-07-01 at 1 22 23 PM](https://user-images.githubusercontent.com/3249794/60464382-47814580-9c03-11e9-895f-8426e82291b9.png)

```
{
  "autoupgrade_enabled": true,
  "autoupgrade_poll_interval": 300,
  "checkin_interval": 60,
  "checkin_timeout": 10,
  "dynamic_services": [],
  "tier": "default"
}
```

4. Gateway cellular configs

![Screen Shot 2019-07-01 at 1 23 09 PM](https://user-images.githubusercontent.com/3249794/60464412-61bb2380-9c03-11e9-83a9-fa6fdb53577c.png)

```
{
  "attached_enodeb_serials": [],
  "epc": {
    "ip_block": "192.168.128.0/24",
    "nat_enabled": true
  },
  "non_eps_service": {
    "arfcn_2g": [
      0
    ],
    "csfb_mcc": "001",
    "csfb_mnc": "01",
    "csfb_rat": 0,
    "lac": 1,
    "non_eps_service_control": 0
  },
  "ran": {
    "pci": 260,
    "transmit_enabled": true
  }
}
```

The minimum set of configs required for connectivity between VM and cloud is network DNS configs and gateway configs. Without the cellular configs your LTE services on the gateway will crash loop (enodebd, mme, etc) but magmad will establish connectivity with the cloud.

**Comment by limitsg** [comment]
Thanks, will try this and update

**Comment by mcclochette** [comment]
Work for us on release 0.3.74!
