### ISSUE TITLE
Send PLMN Restriction message to the MS without use the FeG

### ISSUE THREAD

**Issue by juliogaraujo** [magma/magma#3811]
The reason why I'm asking is because I've been deployed few Magma here in Brazil for some ISPs and I can see a lot of MS Attach request from others MNO that does not belong to the PLMN and they are flooding the s6a statistics, so if I'm not making a mistake we might be able to tell to the MS that this PLMN is forbidden and then there will not be any other attach retry and we will have a clean system. Do you think this is possible?

**Comment by edaspb** [comment]
We see similar situation. IMSI filter for non-federated deployments would be very useful.

**Comment by ulaskozat** [comment]
@juliogaraujo and @edaspb  we are planning to deliver this feature by mid-Feb and backport to v1.4. The plan is to configure blocked PLMNs and if an IMSI has a PLMN field matching to the blocked PLMNs, then we will include AGW's PLMN in the restricted PLMN list while sending an attach reject to the UE. As long as UEs do not switch off/on, they should not attempt to connect again.

**Comment by ulaskozat** [comment]
This feature is landed on master and be part of release 1.5.
