### ISSUE TITLE
NMS upgrade takes dependencies to latest version, not upgrade specified version

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3814]
### Your Environment

- **Version:** e.g. 1.2.0-1600052642-416096082 to 1.3.0-1602477016-723feee0 for AGW
- **Affected Component:** Access Gateway 
- **Affected Subcomponent:** apt / upgrade
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

In the update process, when triggered via NMS or manually via apt, dependencies are updated to latest version, regardless of version specified in upgrade command. 

**To Reproduce**
1. Load an AGW with version stable release v1.2 (1.2.0-1600052642-416096082).
2. In NMS create an upgrade tier for stable release v1.3 (1.3.0-1602477016-723feee0)
3. After update, note that dependencies have been updated to latest, even if explicit match version exists (e.g. magma-sctpd 1.3.0-1602477016-723feee0 exits but latest version 1.3.1-1605904866-7933c828 is installed)
4. see that sctpd.service will be broken due to version mismatch

**Expected behavior**
Expected behavior is that when 1.3.0-1602477016-723feee0 is noted as the stable 1.3 release version, calling and upgrade to that version with full string will produce consistent results for all packages. 

**Additional context**
Attached are two versions of v1.3.0-1602477016-723feee0. 
One installed November 3rd
One installed November 24th
Note that 3 dependencies have changed between them. One of which for sure breaks AGW functionality.
Package Name | match/different
-- | --
python-openvswitch | match
python3-toml | different
python3-typed-ast | match
openvswitch-datapath-module-4.9.0-9-amd64 | match
python3-cffi | match
python3-astroid | match
python3-lazy-object-proxy | match
Magma | match
python3-jsonpointer | match
python3-netifaces | match
python3-wrapt | match
python3-cryptography | different
python3-itsdangerous | match
python3-click | match
magma-libfluid | match
python3-eventlet | match
python3-pylint | match
python3-yaml | match
magma-sctpd | different
openvswitch-switch | match
python3-mccabe | match
python3-redis-collections | match
python3-scapy | match
python3-redis | match
python3-pycares | match
libopenvswitch | match
python3-rfc3987 | match
openvswitch-common | match

[Nov 24 v1.3-1602477016-723feee0 stable release install versions.txt](https://github.com/magma/magma/files/5597779/Nov.24.v1.3-1602477016-723feee0.stable.release.install.versions.txt)
[Nov 3 v1.3-1602477016-723feee0 stable release install versions.txt](https://github.com/magma/magma/files/5597781/Nov.3.v1.3-1602477016-723feee0.stable.release.install.versions.txt)

**Comment by karthiksubraveti** [comment]
@jpad-freedomfi Just wanted to understand this problem better, Here you mentioned that "In the update process, when triggered via NMS or manually via apt, dependencies are updated to latest version, regardless of version specified in upgrade command.", Did you observe the right API with right tierID being pushed to the orc8r from NMS. Wanted to isolate here and confirm on whether it was a specific issue with upgrades triggered through NMS or if it was observed when upgrading manually as well. Thanks

**Comment by jpad-freedomfi** [comment]
@karthiksubraveti Yes, the upgrade flow in Magma seems ok. I created a tier for v1.3.0-1602477016-723feee0 and it applies that version of Magma package. But dependencies get upgraded to latest, even if there is a matching package to the specified version. 

AlexB will comment shortly with more specifics about how APT is handling this. 

BTW, this appears to happen for us with fresh build script as well as upgrade. Anything that uses APT to install/upgrade Magma will have the issue.

**Comment by berezovskyi-oleksandr** [comment]
The behavior of the apt-get command is consistent for install and update. 

So once you run 
```
apt-get install magma=1.3.0
```
 (versions are not exact because it doesn't matter here), `apt-get` will take a list of `magma=1.3.0` dependencies and will observe something like `magma-sctpd>=1.3.0`. 
Next `apt-get` will download the latest `magma-sctpd` version that applies to the rule `>=1.3.0` and `1.3.1` fits well. 
So it will install and download `magma=1.3.0` and `magma-sctpd=1.3.1`.

Update process is absolutely the same. 

I see several options here:
1) lock versions in package dependencies that for `magma=1.3.0` there will be dependency to `magma-sctpd=1.3.0` and same will be done for all the dependencies are being built;
2) expand the updating process to update not just magma to the desired version, but also versions of other packages;
3) make breaking changes management more consistent - increment first number in case of any as https://semver.org/ suggests.

**Comment by karthiksubraveti** [comment]
@tmdzk can we close this issue ?

**Comment by jpad-freedomfi** [comment]
@karthiksubraveti @tmdzk can you guys comment on what has change to resolve this? I don't see any commits linked to this issue.

**Comment by tmdzk** [comment]
Now when we release a version we create a new distribution called stretch-<VERSION> in our `packages.magma.etagecom.io` registry with the magma package and all its dependency. It allows us to avoid circling dependencies/conflicting packages. 
@jpad-freedomfi

**Comment by jpad-freedomfi** [comment]
Hi Tim, I think we have seen an example of this with 1.3.2 is that correct? 

If so, does that mean future version updates (e.g. 1.3.2 to 1.3.3) will require editing `/etc/apt/sources.list.d/packages_magma_etagcom_io.list` on each AGW we want to upgrade?

**Comment by tmdzk** [comment]
That's correct, I made a simple script for that https://github.com/magma/magma/blob/v1.3.2/lte/gateway/release/change_source.sh you just ./change_source.sh <VERSION> 

This is temporary until I come up with a better solution

**Comment by jpad-freedomfi** [comment]
Gotcha. It's that last comment I was curious about 😀

We'll be brainstorming ideas on how to fix longer term too.

**Comment by tmdzk** [comment]
I have a pretty good idea but I'm not 100% sure it works, apt is a mysterious beast sometimes :)

**Comment by tmdzk** [comment]
Closing this issue will create follow up task.
