### ISSUE TITLE
[TerraVM] RAA issues - test 14

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#3822]
### Your Environment

- **Version:** master
- **Affected Component:** FeG, SessionD

### Describe the Issue
Test case: 
- Attach UE with Gx Dynamic Rule for Specific IP flow with Precedence = 2
- 1st RAR with Deny the flow description and RAA - 2001 with higher Precedence = 1
- 2nd  RAR with Allow the flow description & Precedence = 1 which results with RAA - 3002 returned from Magma GW

Issues:
1. Sometimes, the RAA is never received on PCRF's end. Looks like FeG does not send back RAA due to some data inconsistency failures in SessionD.
2. Even when the first RAR/RAA exchange succeeds, the second RAR fails with 3002. Again, this seems to be a SessionD issue.

**Screenshots**
![rar-issue](https://user-images.githubusercontent.com/37634144/100633452-b7fa2d80-32f3-11eb-870a-6b62a431b5be.png)

**Comment by themarwhal** [comment]
[TC-14 RAR logs.zip](https://github.com/magma/magma/files/5617074/TC-14.RAR.logs.zip)

**Comment by uri200** [comment]
please create `state.yml` like below 


```
magma@AGW:/var/opt/magma/configs$ cat state.yml
sync_interval: 4
```

Note i did the changes on the agw i think it is setup 2. So maybe if you run the tests again it will work

**Comment by arun-magma** [comment]
After Sync Interval changes (from 60 to 4) I see RAR & RAA results are consistent with successful result code 2001 and Test cases are passing. Will Monitor the same in upcoming days regressions. Thanks!
![image](https://user-images.githubusercontent.com/70725754/106200150-65aa8100-616b-11eb-92b0-e6b53ae16073.png)
