### ISSUE TITLE
[CI/CD] Update code owners for CI purposes

### ISSUE THREAD

**Issue by mattymo** [magma/magma#3825]
In the interests of developing the CI/CD infrastructure of Magma project, the CI team members should have code ownership rights to certain files. This would benefit us avoids the long process of tracking down different code owners when making improvements or fixes. Below is a list of directories and files that the CI team should have code ownership for:

- circleci/
- ci-scripts/
- lte/gateway/Vagrantfile
- cwf/gateway/Vagrantfile
- orc8r/tools/packer/
- orc8r/cloud/deploy/bare-metal/

**Comment by mattymo** [comment]
@119Vik @tmdzk  Please take a look and comment with additions/deletions

**Comment by PARitter** [comment]
I think this makes a lot of sense and I would support it.
