### ISSUE TITLE
Build OVS for ARM platform.

### ISSUE THREAD

**Issue by pshelar** [magma/magma#3852]

**Comment by jordanvrtanoski** [comment]
Pull created to introduce support for the build of OVS on `ARM64` architecture. The following PRs are required:

#5352 [fix] Fixing the build for OVS build for multi architecture support
#5353 [fix] fixing the OVS makefile to support multi architecture (depending on #5352)

#5352 is preparing the build script to allow the multi architecture builds. #3532 is using the build environment to create the required packages.
