### ISSUE TITLE
grpc failure in sessiond to session_proxy UTF-8 error?

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3866]
### Your Environment

- **Version:**  1.3.0-1602477016-723feee0
- **Affected Component:** Access Gateway + FeG
- **Affected Subcomponent:** SessionD and Session_Proxy
- **Deployment Environment:** AWS (orc8r + FeG), bare-metal (AGW)
- **EPC Configuration:** HSS relay + Gx/Gy Relay both enabled

### Describe the Issue

We have a system with external OCS, HSS, PCRF. All signaling was working prior to update to v1.3 shown above when running v1.1. 

After update to v1.3 version above, we see a grpc message failure error when trying to attach a UE. I think it is related to empty string for UE IP, but not sure. We see User Location Request/Answer, then no external signaling on Gx as should be next in the flow. We see in sessiond logs the grpc error. 

**To Reproduce**
1. Configure lte_federated network
2. Configure for both relay booleans true (HSS relay + Gx_Gy_relay = true)
3. Attempt to attach a UE
4. See in sessiond log grpc error about invalid UTF-8 (I'm guessing a blank string where UE IP should be)

**Expected behavior**
The expected behavior is a flow through Gx and Gy signaling to complete the attach call flow. 

**Additional context**
Logs attached included:
- sessiond log with grpc logging and in debug level
- session_proxy log at normal level
- s1 pcap
- s6a, gy, gx pcap
[DishNet66.zip](https://github.com/magma/magma/files/5626979/DishNet66.zip)

s6a is diameter on port 3869, Gy/Gx is diameter on port 3868,

**Comment by themarwhal** [comment]
`CreateSessionRequest.ue_ipv4` is a field that existed in v1.1 but not in v1.3, so I suspect there is a version issue. Are all components (AGW/Orc8r/FeG) on the same version? 

v1.1: https://github.com/magma/magma/blob/v1.1/lte/protos/session_manager.proto#L413
v1.3: https://github.com/magma/magma/blob/v1.3/lte/protos/session_manager.proto#L490

Do you see any related logs on the orchestrator about the protobuf?

**Comment by jpad-freedomfi** [comment]
@119Vik csn you help check DishNet prod FeG for versions per above? I'll check the AGW side. 

@themarwhal this system was updated to v1.3 using magma update processes in docs. This may speak to the other update issue in #3814

**Comment by jpad-freedomfi** [comment]
@themarwhal Thank you Marie. You are right. Our FeG was still at v1.1 I thought it had been updated. 

After update to latest FeG 1.3 it is now working.
