### ISSUE TITLE
[NSA] Test 5G Non-Stand-Alone UE attachment

### ISSUE THREAD

**Issue by rdefosse** [magma/magma#3879]
### Your Environment

- **Version:**: Based on PR [2707](https://github.com/magma/magma/pull/2707)
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME service
- **Deployment Environment:** local docker-compose of MME and OAI components, and also OAI eNB/gNB and 5G-enabled smartphone

### Describe the Issue

This is not really an issue but for the community that is interested to follow this topic to see our progress

Our objective at `OpenAirInterface Software Alliance` is to replace our legacy MME with the Magma MME to repeat a 5G NSA UE attachment.

We are deploying:

- Redis Container
- Magma MME container that runs both the `sctpd` and the `mme` executables
  * S6A and S11 interfaces are enabled on this variant image.
  * Currently we are running under Ubuntu 18
- A Cassandra container is deployed to manage the HSS User database 
- OAI-HSS, OAI-SPGW-C, OAI-SPGW-U-Tiny containers
- OAI-eNB and OAI-gNB are running baremetal with real USRP SDR radio boards
- We are currently using a unlocked Oppo Reno 5G smartphone but we are transitioning to USB-powered modems.

For us the final goal is to run the MAGMA MME on our local `OpenShift` Cluster (`RHEL8`) and perform NSA UE attachment.

**Comment by rdefosse** [comment]
**Status (2020-12-03)**:

We are testing currently a LTE only attachment (with only the `LTE OAI enb`).

We had to patch the MAGMA MME to have a complete UE attachment. We believe our eNB is not fully 3GPP compliant. We need a patch on this side to remove the hack on MME

Then we will move to attach the UE in NSA mode. What we've seen, we might have to add a few element IDs that are not supported yet.

Raphael

**Comment by rdefosse** [comment]
**Status (2021-01-06):**

We were able to attach an Oppo Reno 5G as described in the 5G NSA mode and we were to do some traffic test in 5G (youtube).

We used as eNB/gNB the `2020.w51_2` tag on `https://gitlab.eurecom.fr/oai/openairinterface5g` repository.

@Vyas20 will prepare a Pull Request.

I've attached a PCAP capture on the MME container (all S1/S11/S6a interfaces). 

[nsa-trace-magma.zip](https://github.com/magma/magma/files/5777269/nsa-trace-magma.zip)

You will see that for the moment we have disabled the MME sending EMM-Information packet to the UE. We need to debug more why with this packet, the UE rejects the connection.

Regards
Raphael

**Comment by ssanadhya** [comment]
Thanks for sharing the pcap @rdefosse ! This is very informative. We do see:
- In Attach Request from UE, we see the "Dual connectivity with NR" flag set in NAS-PDU->UE Network Capability
- The first "Modify Bearer Request" in packet 39 indicates that bearer is setup with the eNB at 192.168.18.199
- The second "Modify Bearer Request" in packet 45 indicates that bearer is setup with the gNB at 192.168.18.198

**Comment by rdefosse** [comment]
**Status (2021-02-11)**

Following demo at MAGMA Dev conf (Feb 3)

See [video and tutorial](https://youtu.be/bnhguk6CfOk)
