### ISSUE TITLE
strech-test apt repo contains now any built version on any branch, not just master branch

### ISSUE THREAD

**Issue by uri200** [magma/magma#3954]
When we update teravm we use apt strech-test repo to get the latest version. This system has work so far, but now we see that strech-test repo is also being used for any branch that is being built. 

So if we build magma 1.1 branch this .deb will be labeled with a current label (for example `1.3.2-1607470122-c1dbe836`) but will contain a 1.1 version.  This will also be perceived as the latest version for our automation.

[below you have the initial description of the issue]

It looks like that the code we have on some of our debian packages is outdated. Per @koolzz we could see that the files included in that package can be more than a month old. 

To reproduce the issue do. 	

```
aptitude download magma
mkdir test
dpkg-deb  -R magma_1.3.2-1607409013-7695653e_amd64.deb test/
cd test
vim ./usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py
```
and compare that file with master https://github.com/magma/magma/blob/13c4b8063f552cbd4025ad9d8d3933337323dab4/lte/gateway/python/magma/pipelined/rpc_servicer.py
You will see the file doesnt match at all. You can choose other files to compre.

Not sure if this is happening with any other service

![image](https://user-images.githubusercontent.com/16157139/101533489-bf9c8080-394a-11eb-9e10-02c827a14639.png)

**Comment by tmdzk** [comment]
Where did you get that package from?

**Comment by tmdzk** [comment]
Okay I found it, this package is from `mme_testing` branch, which is based on the `v1.3` branch. It doesn't have the newest changes that are on master. I guess your setup is pointing to `stretch-test` which is our common distribution where we gather all built packages made by CI

**Comment by uri200** [comment]
Per what we discussed, it looks like `stretch-test` receives all the built versions , including those recently done on older branches. The naming does not give any indication of the real version, so it is impossible for us to know what is really the .deb packet for the latest version on master.

One solution mentioned could be to create a new repo which only includes non master builds. Or reverse, a new repo that only includes master packages

Also, an interim solution could be to label versions coming from master with a specific prefix so we can automate that and get the latest version

**Comment by tmdzk** [comment]
Fixed by having master pointing to version+1
