### ISSUE TITLE
Remove plugin from application and build process

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#3984]
Historically, Orchestrator has maintained modularity through the use of go plugins, with each module having a plugin to register a standard set of functionality to other services. In H2 of 2020, Magma's Orchestrator underwent a major architectural change to decompose the orc8r plugin interface used in all orc8r services into entirely RPC interfaces. The result of this work is that orc8r now runs as a service mesh, interfacing between services entirely through gRPC.

Now, legacy plugin code is lying around in the application (dead code) and in the build process (slowing down builds, slightly bloating container sizes). We want to entirely remove this code from our codebase. 

To start, read up on our process of working with git: https://www.internalfb.com/intern/wiki/MagmaGuide/Working_with_Git/
Then clone the magma repo (https://github.com/magma/magma) from github to get started. 

The plugin code that we want to remove exists at `magma/orc8r/cloud/go/plugin` and `magma/orc8r/cloud/go/pluginimpl`. Many calls to this library are scattered throughout the orc8r code. We'll need to remove all of these calls. 

A good starting point is this diff: https://github.com/xjtian/magma/commit/1bdf527916982065483d2f00e96c21e1079b5f72

Once all of the dead code is removed, we want to remove building the plugin entirely from our build process. Remove the `plugin` build target from the orc8r at `magma/orc8r/cloud/Makefile` as well as any reference to plugins in the Dockerfile at `magma/orc8r/cloud/docker/controller/Dockerfile`. To ensure this has been removed, we should no longer see the following during the build process:
```
...
make -C /src/magma/orc8r/cloud/go plugin
make[1]: Entering directory '/src/magma/orc8r/cloud/go'
go build -buildmode=plugin -o /orc8r.so .
make[1]: Leaving directory '/src/magma/orc8r/cloud/go'
make -C /src/magma/lte/cloud/go plugin
make[1]: Entering directory '/src/magma/lte/cloud/go'
go build -buildmode=plugin -o /lte.so .
make[1]: Leaving directory '/src/magma/lte/cloud/go'
make -C /src/magma/feg/cloud/go plugin
make[1]: Entering directory '/src/magma/feg/cloud/go'
go build -buildmode=plugin -o /feg.so .
make[1]: Leaving directory '/src/magma/feg/cloud/go'
make -C /src/magma/cwf/cloud/go plugin
make[1]: Entering directory '/src/magma/cwf/cloud/go'
go build -buildmode=plugin -o /cwf.so .
make[1]: Leaving directory '/src/magma/cwf/cloud/go'
make -C /src/magma/wifi/cloud/go plugin
make[1]: Entering directory '/src/magma/wifi/cloud/go'
go build -buildmode=plugin -o /wifi.so .
make[1]: Leaving directory '/src/magma/wifi/cloud/go'
make -C /src/magma/fbinternal/cloud/go plugin
make[1]: Entering directory '/src/magma/fbinternal/cloud/go'
go build -buildmode=plugin -o /fbinternal.so .
make[1]: Leaving directory '/src/magma/fbinternal/cloud/go'
make -C /src/magma/orc8r/cloud/go build
...
```
during the build process.

To test changes throughout: 
```
cd magma/orc8r/cloud/docker
./build.py -m
make build           # to build
make test             # to run all unit tests
make precommit # to run all targets needed before committing
```
Once everything is building inside the test container:
```
./build.py
docker-compose up -d
```

View the logs with `docker-compose logs -f controller` to ensure that there aren't any runtime errors.

**Comment by mpgermano** [comment]
Assigning to Scott for bootcamp L3 task.
