### ISSUE TITLE
Move to Minikube-first local development

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#3985]
### Rationale

Local Docker development is beginning to outweigh its benefits. The main reason for local Docker dev is to avoid the overhead of running Minikube locally. However,
- building application containers is already heavyweight, so initializing Minikube on top of building containers doesn't add much
- now that service mesh relies on k8s labels for some aspects of functionality, there is a non-trivial stream of PRs which work fine with Docker but break orc8r once they're deployed in staging
- testing changes locally with Minikube is rarely done since it's not the mainline for local dev
- lots of redundant code between dev and prod (Docker and k8s)

In light of this, we're proposing switching to Minikube-first for local development. We'll keep the Docker code around for a short while as a backup dev path for those who prefer it.

### Implementation notes

Orchestration options
- [(Overview 1)](https://www.bizety.com/2020/07/02/kubernetes-tools-helm-skaffold-tilt-draft-and-garden/) [(Overview 2)](https://www.cncf.io/webinars/container-native-development-tools-compared-draft-skaffold-and-tilt/)
- :star2: [Skaffold](https://github.com/GoogleContainerTools/skaffold) (see: [magma/domain-proxy](https://github.com/magma/domain-proxy) uses skaffold)
- [Tilt](https://github.com/tilt-dev/tilt)

K8s cluster
- [(Overview)](https://brennerm.github.io/posts/minikube-vs-kind-vs-k3s.html)
- :star2: [Minikube](https://github.com/kubernetes/minikube)
- [Kind](https://github.com/kubernetes-sigs/kind)
- [K3s](https://github.com/k3s-io/k3s)

Misc
- @mpgermano has indicated he's had some issues with AGW connectivity for local gateways trying to connect to Minikube orc8rs. Will need to investigate during as part of this task
- Since we're ~forcing Minikube on all cloud devs, we need to include well-detailed docs on how to use+dev with Minikube
- Help FB users guard against accidentally running commands against prod, e.g. via Chef script

**Comment by karthiksubraveti** [comment]
@Scott8440 Added this sometime back. https://github.com/magma/magma/pull/3247

**Comment by mgermano** [comment]
Hi, sorry, i think maybe you confused me with @mpgermano?

**Comment by Scott8440** [comment]
It would be nice to have a script to automate the spin up. Should make everything just as painless (ignoring the extra system requirements minikube takes up) as docker. Also since there are going to be a lot more helm/kubectl commands flying around we want to make sure thinks are pointed at minikube before anything dangerous happens.

**Comment by hcgatewood** [comment]
@Scott8440 agreed, goal is to make it as painless as possible.

For your second point -- any ideas on how to add some guards against accidentally blasting away prod deployments?

**Comment by Scott8440** [comment]
You might want to push some shell configurations to all team members via chef. Something like overriding `kubectl` to do `kubectx minikube; kubectl <command>`. Then add a separate command like `kubectlprod` that always prompts the user before they do something. Lots of options there. Also do the same for helm.
