### ISSUE TITLE
Add stress tests to identify subscriber streaming and metrics upload limits

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#4004]
We've been seeing more and more issues related to the load of gRPC messages causing functionality to fail. The easiest way to fix this would just be to increase the max message size in the short term for these functionalities by default. Given the expected load we're intending to support in the future, I think it would make sense if we have a local framework that we could run to diagnose the current limits of these functionalities.

In the short term, this should allow us to see at what point we expect to see issues and update the defaults to appropriate values. Longer term, we can continue to run these as we improve our capacities.

For streaming subscribers this can just a subscriber generator that adds subscribers and attempts to list them until it fails.
For metrics upload we can estimate some number of bytes of metrics per subscriber based on real deployments and then spam metric creation for an increasing number of the subscribers until the upload to orc8r fails.

**Comment by karthiksubraveti** [comment]
Closing this issue and tracking it with separate issues around subscriber streaming and metric scaling
