### ISSUE TITLE
Configure the new registry

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#4039]
The registry is up and running. We need to configure the different virtual and local repos in order to publish there. 

To be created:
- Helm 
- Blob
- Docker 
- Debian

**Comment by ekowtaylor** [comment]
@tmdzk I believe this is now done. Can it be closed?

**Comment by tmdzk** [comment]
We have to redo it, I'm on it. (we tested the registry and it was quickly down we had to redeploy and change the architecture)

**Comment by tmdzk** [comment]
- docker

feg-test (local)
feg-prod (local)
cwf-test (local)
cwf-prod (local)
orc8r-test (local) 
orc8r-prod (local)

docker (virtual/group) that contains all -prod above. 

- debian 

debian-prod (local)
debian-test (local)
debian (virtual/group) that contains debian-prod

- Helm 

helm-prod (local)
helm-test (local)
helm (virtual/group) that contains debian-prod


- Blob 
blob-prod
blob (virtual/group) that contains blob-prod

**Comment by ranj8work** [comment]
@tmdzk  All the repos on the new artifactory (https://artifactory.magmacore.org/ui) are rebuilt and available to public now:

![image](https://user-images.githubusercontent.com/77810379/113434863-baf35080-93af-11eb-96a1-a8daaeea2d7f.png)
