### ISSUE TITLE
integ test failure: test_attach_ul_udp_data_with_mme_restart.py

### ISSUE THREAD

**Issue by pshelar** [magma/magma#4045]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:**CICD

### Describe the Issue
https://app.circleci.com/pipelines/github/magma/magma/10874/workflows/d7022ebc-3357-48e9-912a-e73d357ab66b/jobs/94749

**Comment by pshelar** [comment]
https://circleci.com/api/v1.1/project/github/magma/magma/94786/output/110/0?file=true&allocation-id=5fd7b726a5c74b1908033617-0-build%2F5C979789

**Comment by ssanadhya** [comment]
Fixed on master
