### ISSUE TITLE
integ-test: failure: test_idle_mode_with_mme_restart.py

### ISSUE THREAD

**Issue by pshelar** [magma/magma#4046]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** MME
- **Deployment Environment:** CICD

### Describe the Issue

https://app.circleci.com/pipelines/github/magma/magma/10846/workflows/df8ca2ed-f78a-4558-a364-75bc00566d41/jobs/94662

**Comment by pshelar** [comment]
one more: 
https://circleci.com/api/v1.1/project/github/magma/magma/94588/output/110/0?file=true&allocation-id=5fd788e3c657ef736e59acb8-0-build%2F1EF8086C

**Comment by ssanadhya** [comment]
Fixed on master
