### ISSUE TITLE
Magma NSA support

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4072]
This issue tracks the activity related to:
**NSA support with MME + OAI CUPS SPGW + OAI HSS**

Add support for E-RAB Modification Response and Dual Connectivity with New Radio IEs

**NSA support in MME + Magma Subscriberdb + Embedded SPGW**
Ref: http://www.eventhelix.com/5G/non-standalone-access-en-dc/en-dc-secondary-node-addition-core-network-details.pdf

- Update Location Request/Answer: Add "NR as Secondary RAT", "Extended-Max-Requested-BW-UL" and "Extended-Max-Requested-BW-DL"
- Create Session Request/Response: Add "Extended APN-AMBR"
- Activate Default Bearer Request: Add "Extended UE-AMBR Downlink" and "Extended UE-AMBR Uplink"

**Comment by ssanadhya** [comment]
**NSA support in MME + Magma Core**
Ref: http://www.eventhelix.com/5G/non-standalone-access-en-dc/en-dc-secondary-node-addition-core-network-details.pdf

- Update Location Request/Answer: Add "NR as Secondary RAT", "Extended-Max-Requested-BW-UL" and "Extended-Max-Requested-BW-DL"
- Create Session Request/Response: Add "Extended APN-AMBR"
- Activate Default Bearer Request: Add "Extended UE-AMBR Downlink" and "Extended UE-AMBR Uplink"

**Comment by ssanadhya** [comment]
As seen in the packet capture shared in https://github.com/magma/magma/issues/3879#issuecomment-755244855:
- In Attach Request from UE, we see the "Dual connectivity with NR" flag set in NAS-PDU->UE Network Capability
- But in the Update Location Request, the "Dual-Registration-5G-Indicator" flag is not set under the ULR Flags.
@Vyas20 please add this flag as part of your PR and link to this issue.

**Comment by ssanadhya** [comment]
#4513 adds support for:
- Handling S1AP E-RAB Modification procedure
- Attach Request IEs:
--  "Dual Connectivity with New Radio" in NAS-PDU->UE Network Capability
-- "Dual Connectivity with New Radio" in NAS-PDU->MS Network Capability
-- "128-5G-IA" in NAS-PDU->UE Additional Security Capability
-- "128-5G-EA" in NAS-PDU->UE Additional Security Capability

**Comment by ssanadhya** [comment]
Pending work for NSA Option 3x in Magma pipeline:
1. Addition of NSA IEs in Update Location Request/Answer between MME and Subscriberdb #5672 
2. Addition of NSA IEs in Update Location Request/Answer between MME and Feg #5673 
3. Add NSA IE support in Create Session Request https://github.com/magma/magma/issues/5675
4. Add NSA IEs in session manager federated to operator core https://github.com/magma/magma/issues/5676
5. Programming path switch and testing with modify bearer #5809 
6. Lab setup for end to end NSA testing with Magma services #5810 
7. Add "Replayed UE Additional Security Capability" IE in Security Mode Command #5811 

NSA Option 3x in OAI pipeline:
1. Upgrade OAI-HSS to Release 15
2. Add "Dual-Registration-5G-Indicator" IE in Update Location Request over FreeDiameter
3. Add "NR as Secondary RAT" and "Extended AMBR" IEs in Update Location Answer over FreeDiameter

**Comment by ardzoht** [comment]
Closing issue since all sub-tasks have been completed.
