### ISSUE TITLE
[Conv-MME] Migrate to C++

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4074]
- Timer handling
- Hashtables
- Logging

**Comment by lionelgo** [comment]
- Timer handling
    Current implementation relies on posix timer_create(), the number of timers is limited by the RLIMIT_SIGPENDING resource limit, don't know this value actually.
    Actually there are problems with ITTI timers: a time-out occur, the ITTI time-out event is queued, the application may delete the timer before popping the ITTI  time-out event, pointers or IDs stored along the ITTI event may be obsolete and lead to segfaults if not carefully checked. 
  We could store the timer pointers or IDs in shared_ptr struct that should contain also timed-out, deleted flags.

    We can propose an implementation of an ordered collection of timers (sorted by time-out).
    We already have a C++-like implementation without timer posix timer_create(), that could be enhanced also regarding the issue described above, here: https://github.com/lionelgo/openair-spgwc/blob/develop/src/itti/itti.hpp

- Hashtables
  folly lockless hashtable seems fine if needed, else std hashtable ?
  First step: replace and remove lte/gateway/c/oai/lib/hashtable

- Logging
  Understood glog is the selected candidate.
