### ISSUE TITLE
Remove default in orc8r database storage

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#4086]
Currently we default to using an in memory db for the orc8r `storage.Database`. This can cause issues for an unaware user that is attempting to persist via a production db.

- Add a new `MustGetEnv` function in orc8r/lib/go/definitions/env.go
- Set SQL driver and DB source in orc8r/cloud/go/storage/storage.go with `MustGetEnv` instead of the "with default" getter

**Comment by hcgatewood** [comment]
Closed by #7484
