### ISSUE TITLE
Error: orc8rlib found in Chart.yaml but missing in charts/ directory

### ISSUE THREAD

**Issue by caprivm** [magma/magma#4125]
### Your Environment

- **Version:** Kubernetes 1.18.3, Helm 3.3.3, Kubespray v2.14.2
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator cloud deployment using Helm Charts
- **Deployment Environment:** Kubernetes cluster (using Kubespray).
- **Magma Branch:** master
### Describe the Issue

Following the documentation (https://magma.github.io/magma/docs/orc8r/deploy_build) for orc8r deployment, when execute `helm package MAGMA_ROOT/orc8r/cloud/helm/orc8r/` command, the output is `Error: found in Chart.yaml, but missing in charts/ directory: orc8rlib`. 

**Note:** I follow the steps without `git checkout a7580153` command because this branch is very old.

**To Reproduce**
1. Clone the Magma repository in master branch.
2. Execute `helm package <magma_folder>/orc8r/cloud/helm/orc8r/`.
3. See error: `Error: found in Chart.yaml, but missing in charts/ directory: orc8rlib`.

**Expected behavior**
An output with a .tar.gz folder with helm package for index and next to install.

**Additional context**
The steps are followed without `git checkout a7580153` because this branch is older (even before v1.2 branch).

**Comment by mpgermano** [comment]
This is issue is due to skipping the `git checkout a7580153`. For 1.3.2 we require a specific helm chart version (1.4.36) as later charts are undergoing a refactor for the 1.4 version. Despite being old, this is the correct way to proceed.
