### ISSUE TITLE
Convert controller to using orc8r_base image

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#4128]
The legacy `orc8r_controller` image and new `orc8r_base` are largely similar images, and the controller functionality can be achieved from the `orc8r_base` image. We also need to keep the controller service around for now since we're still using it for local docker-compose development.

For build/CI purposes, until we're fully Minikube-first for local dev (see #3985), we should convert the controller service to using the `orc8r_base` image, reducing build time and build memory/disk pressure.

**Comment by mpgermano** [comment]
No longer valid as controller and base image have been merged.
