### ISSUE TITLE
Unmanaged eNB with wrong IP Address show in NMS

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#4151]
### Your Environment

- **Version:** - 1.3.2 (AGW)
- **Affected Component:** NMS (staging)
- **Affected Subcomponent:** NMS
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

When an umanaged eNB is added to the nms with a specific IP address and saved, the NMS page shows an entirely different IP address upon coming to the equipment > eNB. However, when clicked on the eNB to edit, the correct IP address is shown on the config window.

**To Reproduce**
1. Add an unmanaged eNB to equipment section in the NMS.
2. Specify a TAC and IP address and save. Note that the IP address shown in the NMS is entirely different from what was entered in the dialog box when saving. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38921899/102839558-ac130000-43b5-11eb-8a6d-355901711af9.png)
![image](https://user-images.githubusercontent.com/38921899/102839570-b0d7b400-43b5-11eb-9dc9-0c7197fe4376.png)

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by karthiksubraveti** [comment]
@ardzoht  The former comes from the eNodeB state and the latter comes from the config. Do you know what might be going on here and why this might be out of sync ?

**Comment by ekowtaylor** [comment]
Stale

**Comment by sudhikan** [comment]
Are we sure this is stale @ekowtaylor? Perhaps backlog or starter task?

**Comment by ekowtaylor** [comment]
Happy to re-open for @ardzoht to take another look
