### ISSUE TITLE
Service Request Handling

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#4183]
### Your Environment

- **Version:** 1.3.2-1607014227-1462d960 (and also tested with 1.3.2-1608233049-8b3817ec)
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME and/or SCTPd
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

I have see Service Request not handled as expected. Based on @amarpad comment in Magma-Dev slack channel Service Request should be supported, that does not match with the two scenarios described here. 

Scenario 1: Baicells Nove 233 running 3.6.6 (latest FW) with a mix of UEs (all baicells but HW and FW versions varied). A couple UEs were flapping with Service Request -> Rejected by magma -> full attach -> 30s to 2min -> Service Request.... loop. Each time the SR is rejected, the subscribers loses IP connection while UE/Magma do full attach sequence.

Logs labeled "AP39"
[AP39_SR_issue.zip](https://github.com/magma/magma/files/5748419/AP39_SR_issue.zip)

Scenario 2: Accelleran radio, 4.2.6 FW, OnePlus 7T UE Android 11, UE attach, then push data, allow to go idle, you see SR being sent by eNB, magma doesn't reject, but no further signaling is seen. After a bit eNB tries again and gets no reply. This scenarios requires the some user intervention to toggle airplane mode to get connectivity again.

other logs apply to this scenario
[Archive.zip](https://github.com/magma/magma/files/5748418/Archive.zip)

**Expected behavior**
The expected behavior is for previously attached UE (for which magma should have context) SR should be completed successfully.

**Comment by jpad-freedomfi** [comment]
@amarpad and @ulaskozat ^^

**Comment by jpad-freedomfi** [comment]
Hi guys. I noted a line in the MME startup output noting that "Force reject SR = true". Curious if this is a setting in a config file? I have looked but don't see it yet. 

```
000244 Sat Jan  2 11:05:46 2021 7FBF2B97BC80 INFO  CONFIG tasks/mme_app/mme_config.c      :1409        NAS non standard features .:
000245 Sat Jan  2 11:05:46 2021 7FBF2B97BC80 INFO  CONFIG tasks/mme_app/mme_config.c      :1412          Force reject TAU ............: true
000246 Sat Jan  2 11:05:46 2021 7FBF2B97BC80 INFO  CONFIG tasks/mme_app/mme_config.c      :1415          Force reject SR .............: true
000247 Sat Jan  2 11:05:46 2021 7FBF2B97BC80 INFO  CONFIG tasks/mme_app/mme_config.c      :1418          Disable Esm information .....: false
000248 Sat Jan  2 11:05:46 2021 7FBF2B97BC80 INFO  CONFIG tasks/mme_app/mme_config.c      :1421          Enable APN Correction .......: false
000249 Sat Jan  2 11:05:46 2021 7FBF2B97BC80 INFO  CONFIG tasks/mme_app/mme_config.c      :1425          APN CORRECTION MAP LIST (IMSI_PREFIX | APN_OVERRIDE):
```

**Comment by ulaskozat** [comment]
@jpad-freedomfi, @pruthvihebbani is investigating the issue. For the rejected service request, UE service request includes an S-TMSI value set to all zeros and MME is not able to fetch a UE context with such an invalid S-TMSI value. We are not sure why the UE is sending such S-TMSI value. Would it be possible to run a test with only one of these UEs (so we can cross correlate service requests to previous attach accepts with confidence)?

**Comment by pruthvihebbani** [comment]
@jpad-freedomfi For the second scenario, after receiving service request MME is sending Initial context setup request message which can be seen in the pcap and the log included in Archive.zip. MME starts a 4sec timer after sending initial context setup req. But enb doesn't respond to this message. i.e it does not send initial context setup response message. Timer at MME expires and it sends UE context release command message which can be seen in the pcap. But enb does not respond to this as well. Can you check why enb is not responding to any of the messages?

**Comment by jpad-freedomfi** [comment]
The zero value S-TMSI was a SW bug on UE side. The no response to initial context setup response was fixed by eNB SW update.
