### ISSUE TITLE
[MME + Sctpd] Clean up the logic of restarting Sctpd when MME terminates

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4190]
Pull Request https://github.com/magma/magma/pull/2884 tried to consolidate the systemd unit files for stateless and stateful AGWs by:
- Removing the `PartOf` dependency between Sctpd and MME
- Adding an explicit SIGTERM from MME to Sctpd

For a stateful AGW, this logic does not capture the scenarios where the MME crashes and fails to send a SIGTERM to Sctpd. When MME comes back up and initiates the Sctpd service, it fails to bind with Sctp socket and goes into a crash loop.

**Comment by ssanadhya** [comment]
Stateful and Stateless AGW differ in how the MME and Sctpd services depend on each other. Specifically,
-- in a stateful AGW, the Sctpd service should always restart with MME service
-- in stateless AGW, the Sctpd service should not restart even if MME service restarts

There are multiple ways to approach this:
1. **Different systemd files for stateless and stateful AGW** : All Magma services are managed through systemd. If the  `PartOf=magma@mme.service` config is present in `sctpd.service` it will always restart with MME service. But this setting needs to be removed for stateless AGW. In order to support both stateful and stateless configs, we can include a default stateful `sctpd.service` in the Sctpd package and create a local override for stateless AGW. This requires:
-- Moving the default install location of `sctpd.service` from `/etc/systemd/system/` to `/usr/lib/systemd/system/` and adding the override in `/etc/systemd/system`.
-- Modify the stateless configuration scripts to create the systemd override file for Sctpd, in addition to the config override files for Mobilityd, MME, Sessiond and Pipelined.
**Pros**: This approach takes care of restarting stateful Sctpd every time MME terminates, even if it is an unexpected crash
**Cons**: While upgrading from older Magma versions to new one, this will create duplicate service files in `/etc/systemd/system` and `/usr/lib/systemd/system`, and since the unit file in `/etc/systemd/system` takes precedence, any new updates will not take effect unless the old files are manually cleared. This would not be an issue for new installs.

2. **Trigger Sctpd restart from MME service**: As the MME service is aware of whether it is stateless or stateful, it can trigger a restart of Sctpd service whenever it terminates. Currently, this logic is implemented by sending a SIGTERM to Sctpd whenever MME gracefully shuts down. This does not capture the cases where MME crashes unexpectedly. To make this effective:
-- Replace explicit SIGTERM signal with a GRPC based restart call from MME to Sctpd
-- Add logic to trigger the GRPC based restart call whenever MME exits due to failure codes, such as SEGV or other signals
**Pros**: Allows us to keep a single Systemd config in `sctpd.service` to support both stateful and stateless AGW
**Cons**: Takes away the Sctpd service management from systemd and mixes it with MME service implementation

3. **Systemd service file for MME conditionally restarts Sctpd**: The logic to restart Sctpd can be separated into a script, which can restart Sctpd right before MME starts in stateful mode. This script can be called using the `ExecStartPre` config in `magma@mme.service`
**Pros**: Allows us to keep a single Systemd config in `sctpd.service` to support both stateful and stateless AGW
**Cons**: Splits the Sctpd service management between `sctpd.service` and `magma@mme.service`
 
 
 If we can expect manual clean-up in all existing deployments , option 1 is the cleanest. Short of that, option 3 will be most effective. Option 2 just patches over what we have at the moment.

**Comment by amarpad** [comment]
One thought here:
If we are to model the EPC as a level and each service is aware of the "level" they are at, then if the current level of service is < new EPC level then we restart the service/dump state. If the current level is the same as the EPC level then it preserves state.

**Comment by uri200** [comment]
maybe this question has an obvious answer, but can't the mme use something like `system("service sctpd restart")`  
(if sudo is needed it may not work)

**Comment by ssanadhya** [comment]
> One thought here:
> If we are to model the EPC as a level and each service is aware of the "level" they are at, then if the current level of service is < new EPC level then we restart the service/dump state. If the current level is the same as the EPC level then it preserves state.

@amarpad  As per our discussion, this will require level awareness in all services and a global EPC state. I will create a separate document to track this goal of making AGW completely level triggered.

**Comment by ssanadhya** [comment]
> maybe this question has an obvious answer, but can't the mme use something like `system("service sctpd restart")`
> (if sudo is needed it may not work)

@uri200 , the goal is to separate the service restart logic from service implementation, hence the move to use a separate script (outside the Sctpd or MME implementation) to control when a service is stopped/started.
