### ISSUE TITLE
[AGW][MME] S1-setup failure

### ISSUE THREAD

**Issue by rsarwad** [magma/magma#4244]
### Describe the Issue
Configuring AGW to stateless and during the execution of sanity test suite, it gets stuck during execution of test_attach_detach_with_mme_restart.py TC.
On execution of next test case, s1ap tester always get S1-setup failure

**Comment by ssanadhya** [comment]
Can you try restarting Sctpd service after a test case gets stuck in stateless mode? You can use the following:
` $ sudo service sctpd restart`
