### ISSUE TITLE
Add a CircleCI job to test the freshly built magma.deb generated by CI 

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#4252]
### Context:

We will only talk about the .deb for the agw.

When a commit lands on master it will trigger the `agw` workflow ([example here](https://app.circleci.com/pipelines/github/magma/magma/12118/workflows/c5fcbe87-984f-409e-978e-ee86f08b0093)). If `lte-integ-test` ([example here](https://app.circleci.com/pipelines/github/magma/magma/12118/workflows/c5fcbe87-984f-409e-978e-ee86f08b0093/jobs/107228)) is successful it triggers `lte-agw-deploy` ([example here](https://app.circleci.com/pipelines/github/magma/magma/12109/workflows/1ff485ae-cd19-492e-853d-bd96f0d0960f/jobs/107206)) that will generate the magma.deb + magma_sctpd.deb + all its dependencies. 

### Problem:
We never automatically test the generated packages. The goal of that task is to add a new `job` or just a step to the `agw` workflow that will test the installation of that generated package. 

### How to solve it:
There are a couple of way to solve that.

1. Modify the lte-agw-deploy job to only build the packages, then you add a step that spins up a freshly built vagrant magma vm, and install the freshly built packages in it, if the install is successful you push it to the registry. 
note: Apt will give you hard time when you install local packages, cause it's not smart enough to look on filesystem for them. 

2. (recommended): Modify the lte-agw-deploy job to push to the [registry](http://packages.magma.etagecom.io/) as stretch-ci distribution, spin up a new vagrant, install magma, if successful promote from stretch-ci to stretch-test. 
Pro of that solution is that we can keep a copy of the "broken" packages in order to debug them. 

3.  /shrug maybe you have ideas :) 

Notes:

- Our release process is currently not perfect. 
The `lte-agw-deploy` ([example here](https://app.circleci.com/pipelines/github/magma/magma/12109/workflows/1ff485ae-cd19-492e-853d-bd96f0d0960f/jobs/107206)) job pushes to S3 then a conjob on [registry](http://packages.magma.etagecom.io/) run every hour to download and deploy those .deb to the registry. I'm currently working on fixing that. 

- We build magma and its dep by running this script [build-magma.sh](https://github.com/magma/magma/blob/master/lte/gateway/release/build-magma.sh) inside a Vagrant dev VM (Because it has all the build dependencies needed), we trigger it using fabfile (the command:  fab dev package:vcs=git)

**Comment by artblee** [comment]
so when a newly tagged build hits the repo the workflow is not deploying a fresh install of this for test then?

**Comment by artblee** [comment]
I think both 1 and 2 solutions mentioned above are very similar.

**Comment by artblee** [comment]
looking for a simple wrapper method to get around this:
"Apt will give you hard time when you install local packages, cause it's not smart enough to look on filesystem for them."

**Comment by artblee** [comment]
should we create a strech-ci install workflow for #2: (recommended): "Modify the lte-agw-deploy job to push to the registry as stretch-ci distribution, spin up a new vagrant, install magma, if successful promote from stretch-ci to stretch-test.
Pro of that solution is that we can keep a copy of the "broken" packages in order to debug them."?
