### ISSUE TITLE
Orc8r: Optimize AWS orchestrator infra for lite / trial deployments 

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#4270]
### Your Environment

- **Version:**
- Orchestrator, Access Gateway
- Deployment Environment:** e.g. AWS (orc8r)  on AWS

### Describe the Issue

Recently Baicells installed orc8r on AWS using the Orchestrator install guide on magmacore.io 
After successful install, we were looking  at the AWS costs for deploying as is in the documentation that we provide. 
The cost comes out to be USD 30 per day.
There should be an option to have a minimal orc8r setup for SI, OEM teams to experiment so that more folks can get hands on and collaborate. 
Optimizations here would mean that we provide more options / flavors of orc8r on AWS which would save on recurring costs. 
Attaching some screenshots of the billing. 
![15731610000364_ pic_hd](https://user-images.githubusercontent.com/48265190/103862107-6f574080-50f9-11eb-97dd-dc1572c12700.jpg)

![15471609999012_ pic_hd](https://user-images.githubusercontent.com/48265190/103862093-6bc3b980-50f9-11eb-8e47-7f1068711129.jpg)
![Uploading 15611610000023_.pic_hd.jpg…]
![15661610000152_ pic_hd](https://user-images.githubusercontent.com/48265190/103862099-6d8d7d00-50f9-11eb-96c4-40fa7d3b68e8.jpg)
![15711610000311_ pic_hd](https://user-images.githubusercontent.com/48265190/103862103-6ebeaa00-50f9-11eb-8251-58f08104ba12.jpg)
![15721610000337_ pic_hd](https://user-images.githubusercontent.com/48265190/103862106-6ebeaa00-50f9-11eb-8757-ce8b01939cd3.jpg)

![15461609998980_ pic_hd](https://user-images.githubusercontent.com/48265190/103862085-69615f80-50f9-11eb-800e-4018df6dd086.jpg)

**Comment by arunuke** [comment]
An internal prototype that makes changes to the instance types to reduce the current fixed costs by ~50%. I will post a PR shortly.

**Comment by jdesai61ilu** [comment]
Any updates? This will help a lot for me who wants to try magma

**Comment by arunuke** [comment]
@jdesai61ilu - This PR should land in Q3.
