### ISSUE TITLE
Can I use magma without deploy on AWS?

### ISSUE THREAD

**Issue by diorgesl** [magma/magma#4304]
I followed the quick start guide and I have magma running locally with orchestrator, agw (on vagrant) and nms.

I have a Baicells and a Mikrotik LTE here on my desk to test, but the agw running on vagrant cant communicate with the eNodeBs, I changed the Vagrantfile to bridge the interface eth1 on agw, and after that, the agw can see the eNodeB or other DHCP Client asking IP but (idk why) dont get any IP, btw, if I bridge the interface the NMS loss the connection to the agw.

Ah, instead of using a AGW running on vagrant, can I install an AGW in other VM and communicate with my local Cloud?

Can someone help me make this lab work as a Real environment?

Thank you.

**Comment by karthiksubraveti** [comment]
@diorgesl Have you looked at https://docs.magmacore.org/docs/lte/setup_deb, you can use this to setup LTE AGW on debian.
Let me know this works for you. Thanks

**Comment by diorgesl** [comment]
Hello, I did it, I installed the AGW on another VM, but I dont know how to connect to my local Orchestrator, I put them on same network, I run show_gateway_info.py to get the informations and I added the AGW to my Orchestrator and it wont become online.

Is there any step to do this?

Thank you.

**Comment by diorgesl** [comment]
@karthiksubraveti 

My local enviroment is running good now, I added my local eNodeBs, added some IMSI clients and everything is running good, also the CPE connected to eNodeB and the internet worked well.

But in this LAB, the AGW is running on Vagrant (Virtual Box) inside this machine where the Orchestrator is.

I tried now install the separeted AGW with the link you provided (I tried before too), but after following the steps I get these errors: 
This SSL error, I think is because of the SSL cert which is created automatically where we run the Orchestrator, also, I tried generate the SSL certs using the scripts, I created too the DNS in my provider, but no success.
>Jan 21 10:58:48 magma magmad[16406]: E0121 10:58:48.607380295   16420 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:10000095:SSL routines:OPENSSL_internal:ERROR_PARSING_EXTENSION.

This second error, I verified my machine running Orchestrator that the port 8443 inst running.
>Jan 21 10:58:44 magma control_proxy[16556]: 2021-01-21T10:58:44.002-04:00 [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 503 160bytes 0.000s

I`m really new in many of these technologies.

But, Thank you for your support.

**Comment by callumsnowden** [comment]
Hi @diorgesl I'm experiencing the same SSL error that you noted above - `Jan 21 10:58:48 magma magmad[16406]: E0121 10:58:48.607380295 16420 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:10000095:SSL routines:OPENSSL_internal:ERROR_PARSING_EXTENSION.`

Did you ever manage to resolve this? And if so what steps did you take to resolve it?
