### ISSUE TITLE
Static IP lookup fails cause subscriber DB is locked -> results in DHCP request

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#4321]
### Your Environment

- **Version:** 1.3.2-1607014227-1462d960
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Mobilityd / SPGW
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)
- **Deployment Details:** IP Allocation = DHCP broadcast, Multi-APN enabled, Static IPs enabled, All SIMs have static IPs. 

Network Diagram
[accessParks-Lion Country Framework-4.pdf](https://github.com/magma/magma/files/5793034/accessParks-Lion.Country.Framework-4.pdf)

### Describe the Issue

In AccessParks deployment, we had rogue DHCP server on the network for a short period. During a Service Request from a UE, the access to the subscriber DB was locked, so it appears mobilityd performed DHCP Discover to try and obtain and IP to allocat to UE during Service Request flow. The DHCP request was successful from rogue DHCP server, which caused pipelined to update the uplink_gw_MAC address to the MAC of the rogue DHCP server. All UE traffic stopped as this was not the MAC of the uplink_gw. 

**To Reproduce**
1. Configure network per deployment details above
2. Attach many UEs (>15) and leave UEs idle
3. Simultaneously trigger traffic on all UEs
4. Observe rapid service requests resulting in failed S6A messaging due to "subscriber db locked"
5. Observe that mobilityd/sgpw then sends DHCP discover for that UE to try and obtain IP from elsewhere

**Expected behavior**
I think subscriber DB should not be locking, should allow concurrent requests. 

If we can't fix DB locking, then return code for these two scenarios should be different and handled differently:

1. Query successful but IMSI has no static IP = trigger DHCP request
2. Query unsuccessful cause DB is locked, so no IP to return = trigger DB query retry

**Additional context**
Zip with logs includes:
full syslog
full mme.log
snippet of relatvant syslog and mme.log (follow IMSI ending in 22988)
[LCS_bad_def_gw_logs.zip](https://github.com/magma/magma/files/5793039/LCS_bad_def_gw_logs.zip)

**Comment by amarpad** [comment]
Good catch, I think our DB lock seems to be contending a fair bit, I have seen this happen in other places too. @sudhikan FYI

**Comment by karthiksubraveti** [comment]
@amarpad we had observed this on staging setup as well - https://github.com/magma/magma/issues/3631

**Comment by jpad-freedomfi** [comment]
@ulaskozat not sure this one has been addressed. This issue was created on 1.3, haven't see the issue on 1.5, but unsure if it got fixed or we just haven't see it yet.

**Comment by ulaskozat** [comment]
@pshelar could you comment on this? I vaguely remember that you resolved this issue?

**Comment by pshelar** [comment]
yes, IP allocation would fail if the subscriber DB is locked: https://github.com/magma/magma/pull/4511.
