### ISSUE TITLE
Mobilityd and/or pipelined hang if UEs attach with mixed static and DHCP ip allocation

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#4322]
### Your Environment

- **Version:** 1.3.2-1607014227-1462d960
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Mobilityd and pipelined
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)
- **Deployment Details:** IP Allocation = DHCP broadcast, Multi-APN enabled, Static IPs enabled, most SIMs have static IPs.

Network Diagram
[Static + DHCP AGW Hang Test Network.pdf](https://github.com/magma/magma/files/5793101/Static.%2B.DHCP.AGW.Hang.Test.Network.pdf)

### Describe the Issue

When network is configured for DHCP_Broadcast for IP allocation, Multi_APN, and static_ip support, and most but not all UEs have static IP assigned in subscriberDB, if first UE to join DOES have static IP assigned, and later an IMSI in DB that does not have static IP tries to attach, some mix of mobilityd and pipelined hang very hard. 

Regular systemctl stop magma@* does not work. you have to kill -9 services (one or both). Also initial systemctl stop command can cause all networking to stop on AGW making it unreachable until hard power cycle. 

**To Reproduce**
1. Configure network per diagram and notes
2. Attach the Static IP assigned UE first
3. Attach the DHCP IP UE second
4. Observed AGW entered failed state with mobilityd and/or pipelined hung
5. try to restart services and see that those services don't stop and can't restarted without kill -9

**Expected behavior**
If you reverse the order of step 2 and 3 above, you get a log error and everything proceeds without a big failure. but if you do the order as shown the AGW needs manual human intervention to get back to functional state.

Expected behavior is more like first scenario, throw error into log and keep running nominally. 

Also it is unclear to me at this time why the same subnet can't have some IPs DHCP and some static. uplink gateway is the same, why is this scenario precluded? 

**Additional context**
ZIP with logs contains:
pcap of s1 traffic
mme.log
syslog
journalctl -f output during steps to reproduce flow above
[Archive.zip](https://github.com/magma/magma/files/5793110/Archive.zip)

**Comment by pshelar** [comment]
@jpad-freedomfi Just to be clear, this issue only occurs when DHCP assigned IP address and static IPs are in same subnet, right ?

**Comment by jpad-freedomfi** [comment]
Yes, that is how it was tested.

**Comment by jpad-freedomfi** [comment]
@pshelar @amarpad just had another instance of this hang in AccessParks on 1.3.3

Retested on 1.4.0-1615912803-6bca6402 in my lab. 

Looks like my description was overly prescriptive. 

I can reproduce the hard hang with the following steps in 1.3.3 and 1.4:

1. Configure network for DHCP_broadcast IP allocation
2. enable static IP assignments
3. have no DHCP server in the subnet for static IPs
4. have first UE to connect have a properly configured HSS record with Static IP for APN
5. have second UE to connect have improperly configured HSS record without static IP for APN
6. observe Mobilityd hang very hard. 

difference here is, we don't have to have a DHCP server running in the same subnet, all we have to do is miss 1 IMSI when configuring static IPs, and the hang occurs. 

When AccessParks has 20-30 IMSIs, adding static IPs is a lot of clicking and easy to miss and imsi, or miss a save click and produce this hang. 

Claudio on our team is working on a static ip bulk configuration script  to help with human error in NMS method of configuration. 

AlexB will be looking into the mobilityd hang. 

but any insights will be helpful.

**Comment by pshelar** [comment]
The issue is mobilityD is single threaded. so when DHCP does not respond it is stuck retrying the DHCP allocation. this results in the hang you are seeing.

@jpad-freedomfi  easiest solution is to use set IP-POOL based allocation with no ip-pool CIDR set. This would result in instant IP allocation failure in case missing static IP.

**Comment by berezovskyi-oleksandr** [comment]
@pshelar what do you think about the idea to implement an IP allocator per APN to support the next scenario?
- APN 1: DHCP allocation with DHCP server;
- APN 2: Static IP without DHCP server.

**Comment by pshelar** [comment]
@berezovskyi-oleksandr we are working on APN restructuring task. This will take care of per APN ip allocations. @karthiksubraveti  is working on this design.

**Comment by jpad-freedomfi** [comment]
@pshelar and @ulaskozat did the planned APN rework get done? If not, should we leave this open?

**Comment by ulaskozat** [comment]
I think this was not concluded yet? @pshelar?

**Comment by pshelar** [comment]
I have a PR to handle it. I will validate it and post  the PR.

**Comment by pshelar** [comment]
Just to be clear, the APN restructuring work (as planned earlier) is delayed. and it will be done later this year. my current plan is going to handle this specific case.

**Comment by ekowtaylor** [comment]
@pshelar did the related PRs for this land yet?
