### ISSUE TITLE
[Stateless AGW][directoryd] Redis state left behind after detach

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4335]
Running `test_attach_detach.py` on master branch shows the following:

```
Redis state is [
 IMSI001010000000001:directory_record
IMSI001010000000002:directory_record
 ]
.
----------------------------------------------------------------------
Ran 1 test in 2.703s

OK
sleep 1
```

This indicates that the Redis keys were not cleared after the UEs detached.

**Comment by ardzoht** [comment]
Closing this, discussed offline and directoryd stale entries are left because these are soft entries that are removed by Orc8r state service, we added filtering on s1ap test to not display directoryd records.
