### ISSUE TITLE
Intra AGW Mobility

### ISSUE THREAD

**Issue by shaddi** [magma/magma#4348]
Impact: we have seen issues in the field are seeing issues with UEs and this is a required feature by multiple partners but we haven't been able to promote it yet. CBRS at FB also requesting this. This is S1 mobility, intra, within the same AGW, 2 enodes.

**Comment by lpavao** [comment]
7/15/21
- Impact: we have seen issues in the field are seeing issues with UEs and this is a required feature by multiple partners but we haven't been able to promote it yet. CBRS at FB also requesting this. This is S1 mobility, intra, within the same AGW, 2 enodes.
