### ISSUE TITLE
Unified Subscriber and Policy NMS View

### ISSUE THREAD

**Issue by andreilee** [magma/magma#4353]
## Unified Subscriber and Policies on NMS
Currently our policies and subscribers views are coupled to our networks. This tight coupling needs to be separated because policies and subscribers need to be replicated for multiple networks in federated network usage. Currently we can create policies and subscriber configuration locally for LTE networks and we can associate policies and subscribers with a federated network in case of (feg_lte) case.

**Impact**
Low impact at the moment. While the subscriber and policy management for federated LTE networks on Magma is not straightforward, without much explanation of how these need to be replicated across the federation network and LTE network, we don't have many examples of federated LTE Magma networks. It's also possible that organizations evaluating Magma as a solution are not inspired by the confusing workflow.

**Reach**
Fairly low reach - we're not finding federated lte networks to be very common currently.

**Confidence**
Medium confidence. We've received feedback about this workflow in the past, but getting more recent feedback is helpful.

**Eng Effort**
Likely fairly high, several weeks

Requirements
- create unified abstracted view on the way policies and subscribers are associated a network
- policy and subscriber profile creation must be independent of network
- Required for LTE and federated LTE

**Comment by jingtien** [comment]
@andreilee Can you add your notes to this issue?

**Impact**

**Reach**

**Confidence**

**Eng Effort**

**Comment by andreilee** [comment]
As of this comment, this is still not started, but would be helpful to various workflows.
