### ISSUE TITLE
[NMS] Unify DB for NMS/orc8r

### ISSUE THREAD

**Issue by andreilee** [magma/magma#4356]
Targeted for 1.5 release

To reduce operational expenses for those running on Magma, Postgres will be used for storage of both orc8r data and NMS-specific data. This requires a migration process for NMS data, as detailed in this proposal doc.

Design/Proposal Document:
> https://github.com/magma/magma/pull/4951

**Comment by karthiksubraveti** [comment]
Removing the Epic label here and folding this into Orc8r simplified deployments and Upgrade Epic
