### ISSUE TITLE
[NMS] Call tracing not working as expected

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#4367]
![Screen Shot 2021-01-13 at 6 09 30 AM](https://user-images.githubusercontent.com/8224854/104495638-de66e600-558c-11eb-81d2-76c523dbab48.png)
![Screen Shot 2021-01-13 at 6 10 25 AM](https://user-images.githubusercontent.com/8224854/104495648-e0c94000-558c-11eb-92fe-285992c06f23.png)

**Comment by andreilee** [comment]
Turns out the ctraced pod isn't actually running in our environment. Some deployment files were missing.
