### ISSUE TITLE
[Registry] Generate a GPG key in order to sign Release files

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#4378]
When you create a registry the release file will have to be signed. 
We need to generate a new private gpg key @ttx, can you take care of it?

**Comment by ttx** [comment]
I'm on it, just need an email alias created for this.

**Comment by ttx** [comment]
OK, private key generated for magma-artifacts@openinfra.dev and sent (encrypted) to @tmdzk 
Please reopen issue if there are any issues with it!
