### ISSUE TITLE
Orc8r Scaling

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#4411]
As part of the effort to achieve GA in 2021, we need a reliable way to reproduce and fix orchestrator issues that occur as deployments scale. Already, we have seen scaling issues with metrics upload and subscriber streaming due to gRPC message size exceeding the default max size.

This epic makes up two main issues:

- Create a scaling test framework to benchmark the system, reproduce issues, and test fixes. 
- Fix issues seen at scale. There are unknowns for what functionality will break. At a minimum this encompasses:
   - metrics upload
   - subscriber streaming

**Comment by jpad-freedomfi** [comment]
@mpgermano May want to add logs upload to the list. We just had orc8r ELK run out of memory, AGW logs stopped working in NMS. We currently have about 2GB of logs per day, default config appears to have no log rotation or cleanup configured. @119Vik has some config he can share that has resolved our issue. We now default to 2 weeks of logs.

**Comment by 119Vik** [comment]
@jpad-freedomfi we found reason for ELK issues - vanilla deployment has elastic search curator in the box, which should care about log rotation was misconfigured out of the box. We prepared PR https://github.com/magma/magma/pull/4449 with fix.
