### ISSUE TITLE
dhcp-range missing in dnsd config. 

### ISSUE THREAD

**Issue by hustundag** [magma/magma#4416]
### Your Environment

- Version:1.3.2
- Affected Component:Access Gateway,NMS
- Affected Subcomponent:AGW dnsd
- Deployment Environment:** AGW VM

### Describe the Issue

dhcp-range is missing ind dnsd.conf which breaks enodebs getting ip address. As workaround, I added dhcp-range manually. 

Note1: issue may be related to following feature. I see this issue at 1.3 onwards 
             [NMS] Add support to disable dhcp service at gateway level #2926. 
Note2:  I kept "DHCP Service" config in default( Turned on)   while provisioning NMS  

Note3: Orchestrator is still running 1.2- Not sure if it is related

Please see below. 

1) As workaround,  I added dhcp-range manually in the template below. with manual dhcp-range entry enodebs are able to get IP address. For testing, I commented out this manual entry 

admin@ecn1:/etc/magma/templates$ cat dnsd.conf.template 

#
interface={{ enodeb_interface }}
#dhcp-range=10.0.2.240,10.0.2.254,12h <===== Manually added and commented out to reproduce this issue 
{% if dhcp_server_enabled is sameas true %}
dhcp-range={{ dhcp_range.lower }},{{ dhcp_range.upper }},12h
{% endif %}
local-ttl={{ localTTL }}
{% if addresses is defined and addresses is iterable %}
{% for address in addresses -%}
{% if address.domain is defined and address.ip is defined %}
host-record={{ address.domain }},{{ address.ip }}
{% endif %}
{% endfor -%}
{% endif %}
interface={{ dns_iface_name }}
no-dhcp-interface={{ dns_iface_name }}
bind-dynamic
admin@ecn1:/etc/magma/templates$ 

2) Restarted dsnd service 

admin@ecn1:/etc/magma/templates$ sudo service magma@dnsd restart
admin@ecn1:/etc/magma/templates$ sudo service magma@dnsd status
● magma@dnsd.service - Magma dnsd service
   Loaded: loaded (/etc/systemd/system/magma@dnsd.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-01-16 12:51:16 PST; 16s ago
  Process: 29217 ExecStopPost=/usr/bin/env python3 /usr/local/bin/service_util.py dnsd (code=exited, status=0/SUCCESS)
  Process: 29221 ExecStartPre=/usr/bin/env python3 /usr/local/bin/generate_dnsd_config.py (code=exited, status=0/SUCCESS)
 Main PID: 29227 (dnsmasq)
    Tasks: 1 (limit: 4915)
   Memory: 692.0K (limit: 300.0M)
   CGroup: /system.slice/system-magma.slice/magma@dnsd.service
           └─29227 /usr/sbin/dnsmasq -k --conf-file=/var/opt/magma/tmp/dnsd.conf

Jan 16 12:51:16 ecn1 systemd[1]: Starting Magma dnsd service...
Jan 16 12:51:16 ecn1 systemd[1]: Started Magma dnsd service.
Jan 16 12:51:16 ecn1 dnsmasq[29227]: started, version 2.76 cachesize 150
Jan 16 12:51:16 ecn1 dnsmasq[29227]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Jan 16 12:51:16 ecn1 dnsmasq[29227]: reading /etc/resolv.conf
Jan 16 12:51:16 ecn1 dnsmasq[29227]: using nameserver 8.8.8.8#53
Jan 16 12:51:16 ecn1 dnsmasq[29227]: using nameserver 8.8.4.4#53
Jan 16 12:51:16 ecn1 dnsmasq[29227]: using nameserver 1.1.1.1#53
Jan 16 12:51:16 ecn1 dnsmasq[29227]: read /etc/hosts - 5 addresses
admin@ecn1:/etc/magma/templates$ 

3) As seen below only commented out dhcp-range entries there.  It is missing calculated dhcp-range 

admin@ecn1:/etc/magma/templates$ cat /var/opt/magma/tmp/dnsd.conf

#
interface=eth1
#dhcp-range=10.0.2.240,10.0.2.254,12h

local-ttl=

host-record=baiomc.cloudapp.net,192.88.99.142

host-record=baicells.chinacloudapp.cn,192.88.99.142

interface=gtp_br0
no-dhcp-interface=gtp_br0

bind-dynamic

admin@ecn1:/etc/magma/templates$

**Comment by karthiksubraveti** [comment]
@hustundag Thanks for creating this issue. The NMS change referenced above is for enabling magma gateways to support unmanaged eNodeBs. If your eNodeB is managed by magma, then leaving the default makes sense.

I will check further on why this config is missing in dnsd conf file and if something changed here.
