### ISSUE TITLE
eventd[8590]: ERROR:root:Connection to FluentBit failed

### ISSUE THREAD

**Issue by diorgesl** [magma/magma#4422]
Im getting this error with in AGW (vagrant), how to solve this?
Im trying/testing the magma without deploy it to AWS.

> Jan 18 23:12:51 magma-dev magmad[8350]: INFO:root:Checking for upgrade...
Jan 18 23:12:51 magma-dev magmad[8350]: INFO:root:Service is currently on package version 0.0.0, ignoring upgrade to 0.0.0-0 because it is either equal or behind.
Jan 18 23:12:51 magma-dev control_proxy[8338]: 2021-01-18T23:12:51.073Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 1972bytes 0.034s
Jan 18 23:12:51 magma-dev magmad[8350]: INFO:root:Processing config update ertel_agw
Jan 18 23:12:52 magma-dev eventd[8590]: ERROR:root:Connection to FluentBit failed: [Errno 111] Connection refused
Jan 18 23:12:52 magma-dev eventd[8590]: INFO:root:Fluentbit may not be configured correctly.
Jan 18 23:12:52 magma-dev eventd[8590]: ERROR:root:Connection to FluentBit failed: [Errno 111] Connection refused
Jan 18 23:12:52 magma-dev eventd[8590]: INFO:root:Fluentbit may not be configured correctly.

Thank you!

**Comment by themarwhal** [comment]
Is `td-agent-bit` enabled on your system? (Can check this with systemd: `sudo service magma@td-agent-bit status`)

For the service to be enabled by default, you can include `td-agent-bit` in gateway.mconfig like this:
```
    "magmad": {
      "@type": "type.googleapis.com/magma.mconfig.MagmaD",
      "logLevel": "INFO",
      "checkinInterval": 60,
      "checkinTimeout": 10,
      "autoupgradeEnabled": false,
      "autoupgradePollInterval": 300,
      "package_version": "0.0.0-0",
      "dynamic_services": [ "td-agent-bit"]
    },
``` 

To enable the service with orc8r's config streaming enabled, you can configure it in the orc8r API via the Gateway Magmad configs
```
"magmad": {
    "autoupgrade_enabled": true,
    "autoupgrade_poll_interval": 301,
    "checkin_interval": 60,
    "checkin_timeout": 20,
    "dynamic_services": [
      "redirectd",
      "eventd",
      "td-agent-bit"
    ],
    "logging": {
      "aggregation": {
        "target_files_by_tag": {
          "mme": "var/log/mme.log"
        }
      },
      "log_level": "DEBUG"
    }
  }
```

**Comment by themarwhal** [comment]
Hello @diorgesl!
Can I close this issue?

**Comment by diorgesl** [comment]
Hello, sorry, can close!

**Comment by Milind-Blaze** [comment]
Running 
```
sudo service magma@td-agent-bit status
```
on my host machine produces 

```
Unit magma@td-agent-bit.service could not be found.
```

I'm not sure what's going on. Can anyone offer some advice? Thanks!
