### ISSUE TITLE
Add support for Orc8r configuration to stream down restricted PLMNs

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#4428]

**Comment by ulaskozat** [comment]
@karthiksubraveti offloading @ardzoht from this task. Will you be able to handle this during this sprint?

**Comment by karthiksubraveti** [comment]
> @karthiksubraveti offloading @ardzoht from this task. Will you be able to handle this during this sprint?

I have to understand this further. Not sure if I can handle in this Sprint. Will update this issue soon.
