### ISSUE TITLE
NMS Showing incorrect Numbers of subscriber attached on AGW

### ISSUE THREAD

**Issue by jag-stack** [magma/magma#4433]
We have 10 AGW -> 20 eNB -> 10 CPE setup. 2 eNB per AGW.
Each CPE is connected to 1 AGW. CPE 2 is connected to AGW 2 and CPE 4 is connected to AGW 4 . But on NMS both CPE 2 and CPE4 are showing to be connected to AGW4.

Steps to reproduce the above scenario:-
1. Login to NMS. Navigate on "equipment" -> indoor_R1F4_AGW4 -> here the connected subscriber count is 2. 
2. Click on corresponding ID "indoorr1f4" -> under subscriber tab -> two subscriber with IMSI "001010000051011" and "001010000051013" are present.
3. Now ssh to AGW4(2620:10d:c0bf:1315::13, magma/magma)
4. Run "mobility_cli.py get_subscriber_table" on AGW4 -> it will display all the subs list. here it is showing only imsi " 001010000051013"

Attaching the Screen shot:-

<img width="723" alt="Screen Shot 2021-01-19 at 12 23 37 PM" src="https://user-images.githubusercontent.com/68403059/105091631-f63ede00-5a54-11eb-9f4a-dc45f3fdf696.png">
<img width="1414" alt="Screen Shot 2021-01-19 at 12 26 28 PM" src="https://user-images.githubusercontent.com/68403059/105091650-ffc84600-5a54-11eb-9a64-f0f1677d3135.png">
<img width="1771" alt="Screen Shot 2021-01-19 at 12 27 09 PM" src="https://user-images.githubusercontent.com/68403059/105091660-048cfa00-5a55-11eb-9c13-69d85db55df4.png">
<img width="672" alt="Screen Shot 2021-01-19 at 12 32 11 PM" src="https://user-images.githubusercontent.com/68403059/105091670-0a82db00-5a55-11eb-86ee-b5c0f2b16185.png">

**Comment by jpad-freedomfi** [comment]
Hi All, Are also seeing this issue. We will be looking into it. We can update here when we make progress.

**Comment by andreilee** [comment]
Any update, @jpad-freedomfi ?

**Comment by jpad-freedomfi** [comment]
@andreilee no. we thought it was fixed a while back. I can find the PR that was supposed to help. But I think the fundamental issue is that NMS gets data from Source A (directoryd I think if IMSI has location), mobilityd gets data from Source B (MME I think). They should both use the same source.
