### ISSUE TITLE
[Magma] [Issue] Sometimes the test case gets stuck before starting the test case commands

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#4475]
### Your Environment

- **Version:** Local Development Setup
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Magma MME/SPGW service
- **Deployment Environment:** Vagrant (AGW)

### Setup Details

The S1APTester ([https://github.com/facebookexperimental/S1APTester](https://github.com/facebookexperimental/S1APTester)) was used along with Magma EPC in Vagrant based setup to reproduce the issue.

### Describe the Issue

Sometimes while running a test script in S1APTester gets stuck in the beginning only without running any actual command from the test script. The issue was recently observed while running multi UE attach detach test case in loop for 240 UEs. The terminal remain stuck for long time with following output in terminal:

-----------------------------------
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_attach_detach_multi_ue.py"
Running test: s1aptests/test_attach_detach_multi_ue.py
sudo -E PATH=/home/vagrant/build/python/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests -x -s s1aptests/test_attach_detach_multi_ue.py || exit 1
-----------------------------------

Once the issue is observed, all next test case executions get stuck at the same place. For running any new test case after that we need to restart magma services in Magma dev VM (This service restart also sometimes takes 10-15 minutes).

**To Reproduce**
1) Modify s1aptests/test_attach_detach_multi_ue.py to run it for 240 UEs
2) Run the test case in loop

**Comment by VinashakAnkitAman** [comment]
Attaching the log and pcap files here:

[Issues.zip](https://github.com/magma/magma/files/5847350/Issues.zip)

**Comment by koolzz** [comment]
I see a whole bunch of qos error logs, I'm assuming this has been fixed as the issue is 21 days old.

@pshelar  tagging for context
