### ISSUE TITLE
Attach reject with wrong cause

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#449]
Test: EPS Attach procedure with IMSI unknown in HSS
Expected behaviour: Attach reject with cause # 2 (IMSI unknown in HSS)
Observed behaviour: Attach reject with cause # 17 (Network Failure)

Log and pcap attached

[mme_2_16.log](https://github.com/facebookincubator/magma/files/3418527/mme_2_16.log)
[dump_2_16.pcap.zip](https://github.com/facebookincubator/magma/files/3418530/dump_2_16.pcap.zip)

**Comment by rsarwad** [comment]
As per the mme logs, Authentication information response is received with diameter error code 5003. This error code corresponds to DIAMETER_AUTHORIZATION_REJECTED (5003)
As per the spec 29272, referring to table Table A.1: Mapping from S6a error code to NAS Cause Code values

If s6a response is received with error codes 5003, then NAS shall send the Attach reject with nas cause set to #15 "No suitable cells in tracking area", or
#17 "Network failure", or
#42 "Severe network failure"
(NOTE 1)

MME is receiving Authentication response with error code as 5003, MME does the mapping of S6a error code to nas emm cuase, MME sends Attach reject with emm cause as #17, network failure.

So we can say that MME behavior is correct

**Comment by houshangaziziaccelleran** [comment]
I am using a set of correct yaml files for my new open5gs (a set that works on my old open5gs).but i get:
S1AP/NAS-EPS	SACK (Ack=3, Arwnd=106496) , DownlinkNASTransport, Attach reject (No Suitable Cells In tracking area)
taci is 1 both on open5gs and enb side.
