### ISSUE TITLE
Magmad config for stateless mode

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#4497]
Design doc: https://fb.quip.com/Kmb3Aof3piWY

Convert AGW stateless mode config from a gateway-level per-service config boolean to a single orc8r-level config boolean.

This change will make AGW stateless mode
- cloud-driven
- single source of truth
- atomic, gateway-wise switchover rather than service-wise
- declarative config rather than procedural command
- support per-network default

**Comment by ssanadhya** [comment]
@ardzoht @hcgatewood , before we start implementation, let's agree on a better name. I know Stateless/Stateful has been confusing to a lot of folks. Let's try to use `persistent/nonpersistent` implying the state persists on a data store and can be recovered on restarts.

**Comment by hcgatewood** [comment]
> @ardzoht @hcgatewood , before we start implementation, let's agree on a better name. I know Stateless/Stateful has been confusing to a lot of folks. Let's try to use `persistent/nonpersistent` implying the state persists on a data store and can be recovered on restarts.

Honestly persistent/non-persistent is more confusing to me. Any chance there's an additional alternative under consideration?

**Comment by ssanadhya** [comment]
@hcgatewood , as per discussion with @ardzoht @ulaskozat , moving this to release 1.6 , cc: @ekowtaylor
