### ISSUE TITLE
Orc8r - Alerts not working for Access Parks  

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#4504]
FFI reported that Alerts are not working for Access parks Deployment. 
@119Vik

**Comment by sourabh-nanoti** [comment]
<img width="1592" alt="Screen Shot 2021-01-22 at 12 20 12 PM" src="https://user-images.githubusercontent.com/48265190/105446010-35b33780-5cac-11eb-9db1-d18533015b36.png">
I tried adding slack channel as receiver. It shows the error attached. 
@119Vik @jpad-freedomfi Can you please share controller ,nginx and prometheus pod logs here please ?

**Comment by sourabh-nanoti** [comment]
<img width="1668" alt="Screen Shot 2021-01-22 at 12 31 09 PM" src="https://user-images.githubusercontent.com/48265190/105446763-c3dbed80-5cad-11eb-9ba0-d3d5a7498e4f.png">

**Comment by sourabh-nanoti** [comment]
<img width="1576" alt="Screen Shot 2021-01-22 at 12 49 35 PM" src="https://user-images.githubusercontent.com/48265190/105448036-7614b480-5cb0-11eb-9cc0-de7063cdd616.png">
<img width="1560" alt="Screen Shot 2021-01-22 at 12 49 26 PM" src="https://user-images.githubusercontent.com/48265190/105448051-7a40d200-5cb0-11eb-976a-7612dab4b565.png">

I configured alers and they were fired and shown correctly on the NMS page but were catagorized in 'other' instead of 'critical' on the Dashboard page of the NMS. 
Also these alerts were not reported on the slack channel which was configured for.

**Comment by sourabh-nanoti** [comment]
In the api in staging, i dont see the notifications channel configured with the alert config- @karthiksubraveti Ideally we should also see the notification channel here correct?  
{
    "alert": "S6A Auth Failure",
    "expr": "increase(s6a_auth_failure{networkID=~\"baicells_china\"}[5m]) > 0",
    "for": "0s",
    "labels": {
      "networkID": "baicells_china",
      "severity": "minor"
    },
    "annotations": {
      "description": "Alerts when we have auth failures"
    }
  },
  {
    "alert": "Bootstrap Exception Alert",
    "expr": "increase(bootstrap_exception{networkID=~\"baicells_china\"}[5m]) > 0",
    "for": "0s",
    "labels": {
      "networkID": "baicells_china",
      "severity": "minor"
    },
    "annotations": {
      "description": "Alerts when we have exceptions during bootstrapping"
    }

**Comment by karthiksubraveti** [comment]
@Scott8440 We aren't able to configure alert receivers properly, Can you check what's going on here ? Is this the case of older version of alertmanager-configurer as well ?

**Comment by Scott8440** [comment]
yeah this is because they're using version 1.0.0 instead of 1.0.3. There will also need to be a slight modification to the written alertmanager.yml file to get it fixed. @sourabh-nanoti and I can work together to get that done.

**Comment by jpad-freedomfi** [comment]
@Scott8440 what element are you mentioning the version for? Those aren't version numbers for magma packages I'm familiar with.

**Comment by Scott8440** [comment]
the pod `alertmanager-configurer` is probably deployed with tag 1.0.0 but it needs to be 1.0.3. These are configurable in the helm values file under the metrics chart. You can also do the same to `prometheus-configurer` but the issue you're seeing is with the alertmanager pod

**Comment by sourabh-nanoti** [comment]
Hey @Scott8440 , @119Vik tried adding the changes regarding the alertmanager-configurer but also need addition change in the metricsd.yml that we did for other partner to get the alerts working. 
@karthiksubraveti

**Comment by 119Vik** [comment]
@Scott8440 thanks for the piece of advice - we successfully updated our deployment. We can create receiver and alert rules and see these changes in the corresponding files how ever I don't see any route in the alert manager config file besides "root route" which points to null_receiver. As a result - we see alerts displayer in the NMS according to alert rules created through the NMS earlier. But nothing delivered to the receiver, which is expected because of missing routing config.  We added missing routes manually to the config and alerts are delivered to the receiver.
List of the things which not work for us :
 - Alerts Rule to Receiver association is not saved when defined through the NMS
 - Routes can't be fetched or created trough the API using following APIs
    curl -X GET "/magma/v1/networks/<network>/prometheus/alert_receiver/route" -H "accept: application/json"
    returns   "message": "error reading alerting route: Not Found"
    curl -X POST "/magma/v1/networks//<network>/prometheus/alert_receiver/route" -H "accept: application/json"
    "message": "error updating alert route: error writing config: Not Found"**

**Comment by jpad-freedomfi** [comment]
Add one item to not working is deleting alert rules via nms

**Comment by sourabh-nanoti** [comment]
https://github.com/magma/magma/pull/4664 diff should fix the issue @119Vik @jpad-freedomfi 
I tested this on another deployment and got notifications on the slack channel for the alerts fired.

**Comment by 119Vik** [comment]
@sourabh-nanoti @Scott8440 thanks will check this today with our deployment
Also I left one comment for the PR

**Comment by 119Vik** [comment]
Thanks @sourabh-nanoti @Scott8440 I can confirm that changes done in the PR fixed our issue.
