### ISSUE TITLE
Upgrade 'magma_test' vm to ubuntu 20.04

### ISSUE THREAD

**Issue by pshelar** [magma/magma#4519]

**Comment by mpfirrmann** [comment]
## Larger tasks before upgrading
- [ ] The `stropts.h` c++ - library in the S1APTester repo is not supported by Ubuntu 20.04. This library seems not to do anything and can be dropped. The results of the integration tests with and without its imports are identical. 
- [ ] The vm artifacts must be uploaded to the hashicorp cloud
- [ ] Merge all other changes to VAGRANTFILE and ansible playbooks
