### ISSUE TITLE
[Orc8r] Add richer query support for subscriber APIs 

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#4538]
Currently NMS has two broad ways of querying for subscribers 
![Screen Shot 2021-01-26 at 5 41 18 AM](https://user-images.githubusercontent.com/8224854/105852935-f598d100-5f99-11eb-919a-fdf6319c8ffc.png)

From NMS perspective, we need support for the following
- Ability to paginate through all the subscribers 
- Ability to get the subscriber to gateway mapping instead of making this computation in the NMS

**Comment by hcgatewood** [comment]
@karthiksubraveti can you add a description to this issue -- I don't follow from the name what this issue aims to accomplish

**Comment by karthiksubraveti** [comment]
@hcgatewood let me know if this makes sense. Thanks

**Comment by hcgatewood** [comment]
> @hcgatewood let me know if this makes sense. Thanks

Perfect thanks @karthiksubraveti. I'll plan to get to this once I handle getting the opentracing work off the ground
