### ISSUE TITLE
Pass UE state from mme->pipelined 

### ISSUE THREAD

**Issue by koolzz** [magma/magma#4554]
Pass UE state over to pipelined classifier controller
The rpc call should contain this infromation
UpdateUEState:
- UE imsi
- ipv4/ipv6 
- uplink_tunnel/downlink_tunnel
- State
  - Active (normal browsing)
  - Idle (paging support/rules persist but tbl0 has specific logic)
  - Suspended (no paging, packets are dropped) from CSFS
  - Unregistered (all rules nuked)
- Apn 
- Vlan 
- DOWNLINK FLOW INFO

**Comment by koolzz** [comment]
For the move from GTP MME app to the pipelined classifier we need to take care of some UE paging state. 

https://docs.google.com/document/d/16v7QQbEZxTdo-JK6I_tyuO8QFECgwrLn9grwgWLFRn4/edit#

**Comment by prabinakpattnaik** [comment]
PR was merged into master branch.
