### ISSUE TITLE
Pass Vlan ID to pipelined from mme

### ISSUE THREAD

**Issue by koolzz** [magma/magma#4555]

**Comment by koolzz** [comment]
For the move from GTP MME app to the pipelined classifier.

Add VLAN ID arg to the ActivateFlowsRequest.

**Comment by uri200** [comment]
We need some info
- Where this vlan value will come from
- Is this value per session? 
- where this value will have to be sent (what protos)
- I this is just on creation, can this be added just as a field of Activate flows?
- Will this value be unique or many UEs can share

**Comment by koolzz** [comment]
@pshelar you have more context on this

**Comment by uri200** [comment]
Not sure if this issue is for the same feature we discussed on our last call. Since VLAN is not session related information, can this VLAN id tag be passed by the MME directly?

**Comment by koolzz** [comment]
@uri200  yeah we don't need it from sessiond for now, will be passed from mme
