### ISSUE TITLE
Add Classifier Circuit-Switched Fall-Back support

### ISSUE THREAD

**Issue by koolzz** [magma/magma#4559]

**Comment by koolzz** [comment]
Not quite sure what we need for this, @ulaskozat

**Comment by ulaskozat** [comment]
@koolzz we need to introduce a new session state called "suspended" in session state (cc @uri200 and @themarwhal). MME should make an rpc call "suspend_session" to sessiond,  sessiond then should activate a policy rule that will drop the packets for the UE. When session state is active again, MME should make an rpc call "activate" to sessiond, sessiond should then deactivate the policy rule that was dropping the packets for the UE.

**Comment by uri200** [comment]
Hi @ulaskozat per your description it looks like we are going to use a similar strategy as we did on Restriction/Redirection. In that case, we do not remove the rules from pieplined/ovs, but we just put a redirect/restrict rule on top of all the rulues. 

Can you confirm that there is no need to remove any rule from OVS during `suspended` mode?

**Comment by ulaskozat** [comment]
@uri200 yes, we just need to handle it in classifier app when UE flows are suspended or resumed. In the above description, rather than the session state, connected, idle, suspended are UE connection management states and registered, unregistered are UE mobility/access management states. So we do not need to add new session states.

**Comment by uri200** [comment]
Let me clarify the names just in case: suspended state is already being used for something else in sessiond.

We will use a new state called 'Idle'.

We will add a new grpc call on sessiond to go from 'active to idle' and 'idle to active'

Pipelined will need a similar call so the state can be propagated.

**Comment by ekowtaylor** [comment]
Iceboxed
