### ISSUE TITLE
NMS: After associating policy with a subscriber, NMS screen goes blank

### ISSUE THREAD

**Issue by pshelar** [magma/magma#4566]
### Your Environment

- **Version:** staging
- **Affected Component:** NMS
- **Affected Subcomponent:** Policy rule association.
- **Deployment Environment:** staging

### Describe the Issue

**To Reproduce**
1. Define a policy
2. Go to 'Subscribers' page, select subscriber
2. Click on: config
3. Click on: 'Traffic Policy" edit 
4. Activate any policy with subscriber, the screen goes blank.

**Expected behavior**
NMS should show subscriber config page.

**Additional context**
After refresh page, it shows subscriber page with activated policy.

**Comment by karthiksubraveti** [comment]
Hey @pshelar, can you attach the har files for this when possible. If you can reproduce this with developer console open, there is an option to download the debug output as a har file.

**Comment by pshelar** [comment]
[nms-stuck-activete-policy.har.txt](https://github.com/magma/magma/files/5869312/nms-stuck-activete-policy.har.txt)
