### ISSUE TITLE
[NMS] Alert URLs in slack aren't accessible

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#4573]
![foo](https://user-images.githubusercontent.com/8224854/105758406-11ea2e80-5f04-11eb-98bc-bd30394f5db3.png)
<img width="1680" alt="Screen Shot 2021-01-25 at 11 48 52 AM" src="https://user-images.githubusercontent.com/8224854/105758342-fe3ec800-5f03-11eb-998d-66ba29facdb3.png">

**Comment by ShubhamTatvamasi** [comment]
I think because these are pod's hostname.

**Comment by ssanadhya** [comment]
@ekowtaylor , this issue is from an older Slack workspace and an older orc8r deployment. Since the Meta Orc8rs have been decommissioned, closing this issue.
