### ISSUE TITLE
[orc8r][1.4] documentation updates needed

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#4579]
### Your Environment

- **Version:** 1.4
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Documentation (orc8r)
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

During the 1.3 ->1.4 orc8r upgrade, found the following things that can be added to the  documentation to make the upgrade process easier.

1. Explicitly mention to set the env variable `MAGMA_ROOT`. This was not necessary previously but for 1.4 it is required when packaging up the helm charts. 
2. In main.tf for `orc8r_deployment_type` we should explicitly specify "fwa" so the variable assignment is valid without modifications.
2. Add a note that terraform needs to be running 0.14.0 or higher. See Issue #4578 for why this is necessary.
3. Add a note stating that if this orc8r is not the only orc8r instance running on the aws account, then the role `AWSServiceRoleForAmazonElasticsearchService` may already exist. Operators can override creating this role again by setting `deploy_elasticsearch_service_linked_role` to `false` in my main.tf file under the `orc8r` module.

**Comment by hcgatewood** [comment]
Adding a PR to handle 1-3. Note that for 4 we explicitly indicate we only support one orc8r installation per account. Obviously we'd like that to change, but for now let's leave it at that
