### ISSUE TITLE
Move rule version generation to Sessiond

### ISSUE THREAD

**Issue by koolzz** [magma/magma#4599]

**Comment by koolzz** [comment]
Currently we manage rule version in pipelined. This creates unnecessary state as SessionD is already managing policy rules.

 - rule version should be passed during policy rule activation rpc call

**Comment by koolzz** [comment]
@pshelar @ulaskozat just wanted to check is wavelabs was planning to implement this or is this on our end? for 5g we're passing rule version to upf but is the generation work on us?

**Comment by ulaskozat** [comment]
version is generated at sessiond (5G side) and sent to pipelined. we need to do it for 4G as well.

**Comment by themarwhal** [comment]
This item is in progress with these merged: https://github.com/magma/magma/pull/5702, https://github.com/magma/magma/pull/5702, https://github.com/magma/magma/pull/5699
1-2 more PRs to go

**Comment by koolzz** [comment]
This has been merged closing
