### ISSUE TITLE
Attach Request NAS decode failure

### ISSUE THREAD

**Issue by sarathbrp** [magma/magma#46]
000278 Fri Mar  8 23:07:11 2019 7FE602729700 INFO  S1AP   /home/vagrant/magma/lte/gateway/:0085      Received S1AP INITIAL_UE_MESSAGE eNB_UE_S1AP_ID 0x000030
000279 Fri Mar  8 23:07:11 2019 7FE602729700 INFO  S1AP   /home/vagrant/magma/lte/gateway/:0109      New Initial UE message received with eNB UE S1AP ID: 0x000030
000280 Fri Mar  8 23:07:11 2019 7FE606FB6700 INFO  MME-AP /home/vagrant/magma/lte/gateway/:0636      INITIAL_UE_MESSAGE RCVD.mme_ue_s1ap_id = 1, enb_ue_s1ap_id = 48. Is S-TMSI Valid = 0
000281 Fri Mar  8 23:07:11 2019 7FE606FB6700 INFO  NAS-EM /home/vagrant/magma/lte/gateway/:0221               EMMAS-SAP - Received primitive EMMAS_ESTABLISH_REQ (205)
000282 Fri Mar  8 23:07:11 2019 7FE606FB6700 INFO  NAS-EM /home/vagrant/magma/lte/gateway/:0833                  EMMAS-SAP - Received AS connection establish request
000283 Fri Mar  8 23:07:11 2019 7FE606FB6700 INFO  NAS-EM /home/vagrant/magma/lte/gateway/:0844                  EMMAS-SAP - got context 0x62500049f828
000284 Fri Mar  8 23:07:11 2019 7FE606FB6700 WARNI NAS    /home/vagrant/magma/lte/gateway/:0041                           IEI is different than the one expected.(Got: 0x40, expecting: 0x1
000285 Fri Mar  8 23:07:11 2019 7FE606FB6700 ERROR NAS-EM /home/vagrant/magma/lte/gateway/:0281                        EMM-MSG   - Failed to decode L3 EMM message 0x41 (-2)
000286 Fri Mar  8 23:07:11 2019 7FE606FB6700 NOTIC NAS    /home/vagrant/magma/lte/gateway/:0873               Hit 3GPP TS 24_301R10_5_5_1_2_7_b__2 : Abnormal cases on the network side: Protocol error information element non-existent or not implemented
000287 Fri Mar  8 23:07:11 2019 7FE606FB6700 INFO  NAS-EM /home/vagrant/magma/lte/gateway/:0167                  EMMAS-SAP - Received Attach Request message
000288 Fri Mar  8 23:07:11 2019 7FE606FB6700 ERROR NAS-EM /home/vagrant/magma/lte/gateway/:0300            EMMAS-SAP - Failed to process primitive EMMAS_ESTABLISH_REQ (205)
000289 Fri Mar  8 23:07:16 2019 7FE602729700 INFO  S1AP   /home/vagrant/magma/lte/gateway/:0113      S1AP eNB RESET is received. Procedure code = 14
000290 Fri Mar  8 23:07:16 2019 7FE606FB6700 WARNI MME-AP /home/vagrant/magma/lte/gateway/:2401      UE Conetext Release Reqeust:Cause SCTP RESET/SHUTDOWN. UE state: IDLE. mme_ue_s1ap_id = 1, enb_ue_s1ap_id = 48 Action -- Handle the message
 000291 Fri Mar  8 23:07:16 2019 7FE606FB6700 ERROR MME-AP /home/vagrant/magma/lte/gateway/:2

409      ERROR: UE Context Release Request: UE state : IDLE. enb_ue_s1ap_ue_id 0x000030 mme_ue_s1ap_id 0x00000001 A
[nasdecodefailure.zip](https://github.com/facebookincubator/magma/files/2947786/nasdecodefailure.zip)
ction--- Ignore the message
tail: /var/log/mme.log: file truncated

It appears NAS is not happy with IE Supported Codec List (in Attach Request). Could you please confirm?

Thanks,
SP

**Comment by anooptomar29** [comment]
Fix for NAS EMM message decode failure is as follows : Modify c/oai/tasks/nas/emm/msg/AttachRequest.c" line # 272. Replace true by ATTACH_REQUEST_SUPPORTED_CODECS_IEI
Essentially replace true by ATTACH_REQUEST_SUPPORTED_CODECS_IEI while calling this function  (decoded_result = decode_supported_codec_list(
&attach_request->supportedcodecs,
*true*,
buffer + decoded,
len - decoded)) <= 0) {
This will solve decoding error of Attach request whenever UE sends optional IE "Supported Codec

**Comment by anooptomar29** [comment]
This issue is fixed. Please refer https://github.com/facebookincubator/magma/commit/c7c0da51724d39d2d0717ee812491b90a2ec5ad5. Can you please close this @sarathbrp .

**Comment by anooptomar29** [comment]
closing it.
