### ISSUE TITLE
Improve dependencies management

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#4634]
At the moment dependencies lists for packages are not strictly defined. This is good, cause it allows us to pick latest bug fixes for external packages during the next build. In the same time dependencies version definition is too broad so as a result of the new build we can use new major version which will unexpectedly break the system.
Let's review https://github.com/magma/magma/blob/master/orc8r/gateway/python/setup.py as an example :
Some dependencies (`setuptools==49.6.0` for example ) are strictly defined so will not be changes in the new build until list of requirements is explicitly updated. Rest of the dependencies are defined with lowest possible version but without highest, As an example `protobuf>=3.14.0` - this statement means that `protobuf 3.14.1` is good but `protobuf 8.0.0` is even better, which may not be true from software development point of view, cause `protobuf 8.0.0` has backward incompatible changes, new features, new bugs ...

Having such a broad requirements definitions means that our  CI and Artefacts building process are not repetitive and not stable by default. 

To make our process of building and distributing artefacts better / more stable we need to improve our dependencies management process. Best practice in this  case will be to define highest possible version allowed to install - `protobuf>=3.14.0, <4.0.0` **OR** `protobuf>=3.14.0, <3.15.0` - Highest limit is depends on the version management strategy selected by dependency owner. In some cases version definition may even have exclude statements for specific version known as buggy.

**Comment by 119Vik** [comment]
@amarpad, @ssanadhya, @ulaskozat    what's your opinion regarding problem explained above ?

**Comment by electronjoe** [comment]
I'm in strong agreement that the dependency story needs to be improved.  Pointing to this GH Issue on that front.
