### ISSUE TITLE
MME stale state for eNBs and UEs

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#4636]
MME got into a state where we have stale state on connected eNBs and UEs
014959 Thu Jan 28 16:44:55 2021 7F94E4EDF700 DEBUG MME-AP tasks/mme_app/mme_app_statistics:0028    ======================================= STATISTICS ============================================
tasks/mme_app/mme_app_statistics:0040    Connected eNBs |          2      |              0              |             0               |
tasks/mme_app/mme_app_statistics:0048    Attached UEs   |         23      |              0              |             0               |
tasks/mme_app/mme_app_statistics:0056    Connected UEs  |         65      |              0              |             0               |
tasks/mme_app/mme_app_statistics:0064    Default Bearers|         20      |              0              |             0               |
tasks/mme_app/mme_app_statistics:0072    S1-U Bearers   |          0      |              0              |             0               |
======================================= STATISTICS ============================================

When I try to run a new test, I get
asks/s1ap/s1ap_mme_handlers.c  :2177    SCTP disconnection request for association id 30, Reset Flag = 1. Connected UEs = 18
tasks/s1ap/s1ap_mme_handlers.c  :2224    Marked enb s1 status to Reset, attached to assoc_id: 30
tasks/s1ap/s1ap_mme_handlers.c  :0388    Ignoring s1setup from eNB in state S1AP_RESETING on assoc id 30

restarting MME does not help as it is configured for stateless operation

**Comment by ssanadhya** [comment]
Attaching some sample MME logs for this issue:

[mme_sctp_reset3.log.zip](https://github.com/magma/magma/files/5960633/mme_sctp_reset3.log.zip)
[mme_sctp_reset5.log.zip](https://github.com/magma/magma/files/5960639/mme_sctp_reset5.log.zip)

**Comment by ssanadhya** [comment]
Failure recovery provided by #4899 , as the root cause is not clear. If the Asserts mentioned in https://github.com/magma/magma/issues/4993  happen too frequently, we can re-open this.
