### ISSUE TITLE
Broken images for NMS Traffic Docusaurus [documentation]

### ISSUE THREAD

**Issue by jaredmullane** [magma/magma#4640]
### Your Environment

- Versions 1.3, 1.2
- https://magma.github.io/magma/docs/nms/nms_traffic

### Describe the Issue

The images for the NMS traffic section fail to load.

**To Reproduce**
1. Go to https://magma.github.io/magma/docs/nms/nms_traffic
2. View broken image links 

**Expected behavior**
Expected image links to be working on the page

**Screenshots**
![Screen Shot 2021-01-28 at 12 21 31 PM](https://user-images.githubusercontent.com/61836831/106194277-735c0880-6163-11eb-9a0c-505f665f9b59.png)

**Comment by karthiksubraveti** [comment]
@jaredmullane Yes. This has been fixed in master. I can check if we create versioned assets and fix it accordingly in older releases as well.
