### ISSUE TITLE
[orc8r][bare-metal] events elasticsearch error

### ISSUE THREAD

**Issue by diorgesl** [magma/magma#4694]
### Your Environment

- **Version:** 1.3.3
- **Affected Component:** Orc8r and NMS
- **Affected Subcomponent:** Orchestrator elasticsearch
- **Deployment Environment:** bare-metal (orc8r)

### Describe the Issue

Getting error 500 (Internal server error) when listing logs/events in NMS:
`curl -X GET "https://api.orc8r.domain.com/magma/v1/events/ertel" -H "accept: application/json"`
`{
  "message": "json: cannot unmarshal number into Go struct field SearchHits.hits.total of type elastic.TotalHits"
}`

**Additional context**
I think if update the pod to elasticsearch 7 would fix this problem, but I`m not that expert to do this.

**Comment by mpgermano** [comment]
In the terraform used for a cloud based orc8r, we use Elasticsearch version "7.1". Upgrading the ES to this version should fix the issue.
