### ISSUE TITLE
[DevOps][AGW] Core_pattern is set incorrectly on gateway dev VM

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4752]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Debugging tools
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

**To Reproduce**
1. Checkout master(say, commit https://github.com/magma/magma/commit/8bce47348c20c8c636baf9876e129baad51b182a) 
2. `cd /lte/gateway`
3. `vagrant destroy magma; vagrant up magma`
4. `vagrant ssh magma`
5. Check core_pattern system setting
```
vagrant@magma-dev:~/magma/lte/gateway$ cat /proc/sys/kernel/core_pattern
core
```

**Mitigation**
1. `vagrant reload magma`
2. `vagrant ssh magma`
3. Check core_pattern system setting
```
vagrant@magma-dev:~/magma/lte/gateway$ cat /proc/sys/kernel/core_pattern
```

**Expected behavior**
The core_pattern should be available the first time the box is provisioned.

**Comment by pshelar** [comment]
fixed in 1.4
