### ISSUE TITLE
[1.5] Inbound Roaming With SubscriberDB

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#4768]
## Overview
* The goal of this feature is to allow for inbound roaming via S8 while using Magma's local subscriberDB as the home HSS.

### Routing logic location
The routing configuration is the same PLMN based routing as the fully federated case. 
* Have the routing logic in S6a task in MME based on the PLMN based routing logic. Currently the S6a task supports sending auth requests to either Orc8r/FeG OR SubscriberDB. We’ll have to modify the task to handle a case where we switch between the two based on a config.
    * Upside: the routing config already needs to be there for the S8 switch
    * Downside: A slight change in the s6a task to allow for both SubscriberDB and Orc8r/FeG GRPC channels.
* We can stream down the routing logic to SubscriberDB and forward all roaming auth requests to the Orc8r/FeG. 
    * Downside: We will duplicate routing logic in SubscriberDB and Orc8r.
    * Upside: Only send Auth requests to Orc8r for UEs that need roaming.
* We can stream down a separate configuration to forward all subscribers that are not in the SubscriberDB database to Orc8r/FeG. 
    * Downside: We could end up with auth requests that leave the AGW for any UE that is not in SubscriberDB. However, with some PLMN based filtering on MME to block UEs, this could be manageable.
    * Downside: Cannot distinguish between auth failure and routing choices
    * Upside: Much simpler logic in SubscriberDB
 
 
### Routing config location. 
The PLMN based routing configuration will live on the Access (LTE)  network
It’ll be streamed down to MME as part of MConfig

## Upcoming items for me to work on
1. Design doc to discuss the points mentioned above (~1-2 days)
2. Call flow for the subscriberDB model (Will include in the doc) (~.5 day)
3. S6a task implementation + testing (~3-5 days)
4. Orc8r config implementation + testing ( ~2-5 days)

**Comment by emakeev** [comment]
I think, in the simplest form it could be just adding a single "Home PLMNID" config variable for AGW subscriberdb (or maybe a list of Home PLMNIDs).
Another option could be: lookup an attaching UE IMSI in the local subscriberdb; if found -> complete auth; if not -> forward to FeG (via Orc8r). This option may not even require a new additional configuration...

**Comment by themarwhal** [comment]
@emakeev I was thinking the second option, as it seems like the simplest approach. We just have to make sure the config is streamed down. 
In the home plmnsID case, it would look like:
1. UE sends an auth request to SubscriberDB
2. SubscriberDB looks up plmnID in the config and completes auth
3. Messages back MME

In the roaming case, it would look like:
1. UE sends an auth request to SubscriberDB
2. SubscriberDB looks up plmnID and forwards the auth to Orc8r
3. Orc8r forwards the auth request to FeG
4. SubscriberDB gets back a response from Orc8r/FeG
3. MME gets back a response from SubscriberDB

**Comment by emakeev** [comment]
@themarwhal, yes & it can probably be even simpler, without the home plmnID config (just enable/disable config switch):

1. UE sends an auth request to SubscriberDB
2. SubscriberDB looks up UE's IMSI using [SubscriberData RPC](https://github.com/magma/magma/blob/master/lte/protos/subscriberdb.proto#L233)
3. Depending on the result of the IMSI lookup:
    - If the subscriber with the IMSI found in step #2- subscriberdb messages back MME
    - If the IMSI is not found: 
      - SubscriberDB forwards the auth to Orc8r -> FeG
      - SubscriberDB gets back a response from Orc8r/FeG
      - MME gets back a response from SubscriberDB

**Comment by amarpad** [comment]
Yes I think the decision to fallback into the orc8r is a config time thing. I think it should be explicit.

**Comment by themarwhal** [comment]
Closing this task since the bigger EPIC covers the smaller tasks.
