### ISSUE TITLE
[AGW][MME] Memory profiling for MME

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4770]
- Profile MME memory usage from systemd and htop over a long time:
-- S1ap-tester
--- without any UE activity
--- with 32 UEs in continuous loops
--- with 128 UEs in continuous loops

- Remove stale state for stateless MME
-- Clean-up IMSI and GUTI hashtables

- Run Valgrind on MME with 
-- S1ap-tests
-- TeraVM
-- Spirent testbeds

**Comment by VinashakAnkitAman** [comment]
The memory usage trend with time and number of UEs is recorded in the document:
https://drive.google.com/file/d/1Fr774_MnVltIE2GZxVT3mjRhz7TzbEMa/view?usp=sharing

**Comment by VinashakAnkitAman** [comment]
The valgrind observations are recorded in the path:
https://drive.google.com/drive/folders/1z3lvhaCq2vvIQijJ0zJEXJw46h9rr36x?usp=sharing
