### ISSUE TITLE
eNodeB configuration exception - extra parameter

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#479]
Jul 27 08:27:46  enodebd[937]: ERROR:root:Failed to handle tr069 message
Jul 27 08:27:46  enodebd[937]: ERROR:root:Traceback (most recent call last):
Jul 27 08:27:46  enodebd[937]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_impl.py", line 87, in handle_tr069_message
Jul 27 08:27:46  enodebd[937]:     return self._get_tr069_msg()
Jul 27 08:27:46  enodebd[937]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_impl.py", line 153, in _get_tr069_msg
Jul 27 08:27:46  enodebd[937]:     msg_and_transition = self.state.get_msg()
Jul 27 08:27:46  enodebd[937]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_states.py", line 325, in get_msg
Jul 27 08:27:46  enodebd[937]:     if self.acs.data_model.is_parameter_present(name):
Jul 27 08:27:46  enodebd[937]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/data_models/data_model.py", line 51, in is_parameter_present
Jul 27 08:27:46  enodebd[937]:     raise KeyError('Parameter presence not yet marked in data model')
Jul 27 08:27:46  enodebd[937]: KeyError: 'Parameter presence not yet marked in data model'
Jul 27 08:27:46  enodebd[937]: ERROR:root:Device configuration: Param values: {
Jul 27 08:27:46  enodebd[937]:   "REM status": "1",
Jul 27 08:27:46  enodebd[937]:   "MME status": "1",
Jul 27 08:27:46  enodebd[937]:   "Serial number": "XXXXXXXXXXXXXXXXXXX",
Jul 27 08:27:46  enodebd[937]:   "GPS status": "1",
Jul 27 08:27:46  enodebd[937]:   "SW version": "BaiStation_V100R001C00B110SPC009",
Jul 27 08:27:46  enodebd[937]:   "Opstate": "true",
Jul 27 08:27:46  enodebd[937]:   "RF TX status": "true"
Jul 27 08:27:46  enodebd[937]: },
Jul 27 08:27:46  enodebd[937]:  Object values: {}
Jul 27 08:27:46  enodebd[937]: ERROR:root:Desired configuration: None

**Comment by andreilee** [comment]
Thanks for reporting this issue. I'll be following up on it.

**Comment by andreilee** [comment]
Do you have the model of the eNodeB you're using? As well as the software version.

**Comment by bmurithi** [comment]
@andreilee here you go

```
Product Type:BRU3510
Hardware Version:VER.D
Software Version:BaiBS_RTS_3.1.4
```
