### ISSUE TITLE
enodebd service does not recover from Error State - cell is active

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#480]
`enodebd` service fails to recover from this state.

![screencap_20190728_002](https://user-images.githubusercontent.com/6918709/62005986-67911f80-b143-11e9-8835-2961ab36a82b.png)

Remained in this state for *17 hours* - **The cell was actually active.**

- Rebooted the eNodeB
- `enodebd` still reported the error state
- Restarted `enodebd` service
- Cell state was then correctly reported

![screencap_20190728_003](https://user-images.githubusercontent.com/6918709/62006005-c48cd580-b143-11e9-8b83-7c614936ea2e.png)

# eNodeB model/software

```
Product Type:BRU3510
Hardware Version:VER.D
Software Version:BaiStation_V100R001C00B110SPC009
```

**Comment by bmurithi** [comment]
Same thing observed on a second eNodeB.

- `FSM State...............Error state - awaiting manual reboot`
- Rebooted the eNodeB from its management interface
- State remained as `FSM State...............Error state - awaiting manual reboot`
  - In this case, the RF/TX state was accurate
- Restarted `magma@enodedb`
- Correct state reported: `FSM State...............Completed provisioning eNB. Awaiting new Inform.`

# eNodeB model/software

```
Product Type:BRU3510
Hardware Version:VER.D
Software Version:BaiBS_RTS_3.1.4
```


# eNodeB model/software

```
```

**Comment by andreilee** [comment]
Do you have any syslog dumps from enodebd?

**Comment by bmurithi** [comment]
Just a bunch of these in the intervening period.

```
Jul 28 14:00:31 lte enodebd[14146]: INFO:aiohttp.access:192.168.150.251 - - [28/Jul/2019:11:00:31 +0000] "POST /A20190728.1055%2B0000-1100%2B0000_48BF74.<SERIAL>.xml HTTP/1.1" 200 0 "-" "-"
```

**Comment by andreilee** [comment]
This is definitely a bit of a usability issue on our end. `Error state - awaiting manual reboot` should indicate instead that enodebd service needs to be restarted, because some unexpected, and unrecoverable scenario has occurred.

Thanks for reporting this issue.

**Comment by andreilee** [comment]
Likely solved with https://github.com/facebookincubator/magma/pull/540

Error messaging changed with https://github.com/facebookincubator/magma/pull/542

Hopefully that should solve this issue, but it's hard to verify for certain in this case without good steps to reproduce it.

**Comment by bmurithi** [comment]
@andreilee noted - will test this internally.
