### ISSUE TITLE
[CI] LTE Integration Test on CircleCI failing at `sudo apt-get -y dist-upgrade` step

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#4809]
### Your Environment
- **Version:** master

### Describe the Issue
`sudo apt-get -y dist-upgrade` now requires a user input for `wireshark-common`. Leading the LTE Integration Test job to timeout since it is waiting for an input.

On CI: https://app.circleci.com/pipelines/github/magma/magma/14192/workflows/2a4ff017-4c83-4858-854d-369241b81370/jobs/128010

Locally on magma-dev VM:
![Screen Shot 2021-02-08 at 12 28 32 PM](https://user-images.githubusercontent.com/37634144/107264891-2c92cc00-6a09-11eb-97d9-17473efc750c.png)

**Comment by tmdzk** [comment]
Weird we disable the `DEBIAN_FRONTEND=noninteractive`, someone removed it?
