### ISSUE TITLE
[SessionD] GRPC server error: `sessiond server encountered error while processing request`

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#4811]
### Your Environment

- **Version:** 1.4
- **Affected Component:** AGW
- **Affected Subcomponent:** SessionD
- **Deployment Environment:** Test setup with load testing 

### Describe the Issue
Test scenario: Rapid 100 UE attach cycle
Starts to see these error logs 
<img width="1648" alt="Screen Shot 2021-02-08 at 1 40 46 PM" src="https://user-images.githubusercontent.com/37634144/107272423-489b6b00-6a13-11eb-8bc0-54bd6323f232.png">

**Comment by themarwhal** [comment]
(@uri200, @ulaskozat for visibility)

**Comment by uri200** [comment]
I think we have an issue overwhelming REDIS from Magma. And this is probably is not caused only by sessiond but by the combinations of all the systems. 

I used `s1aptests/test_attach_dl_ul_tcp_data_multi_ue.py` to generate multiple users go be idle on the system (just with a session)

Then I added some logging capabilities to sessiond to display deltas during `ReportRuleStats` call

As you can see below `read_all_sessions` takes 6 seconds to complete.  I can see that happen from time to time. But I also saw it on `check_usage_for_reporting` that is another function that calls redis to store values. 

All those delays do not happen all the time (maybe each 10 to 20s, which it is too much to me), but when they happen they not only delay themselves but other actions waiting on the queue. So those delays have long lasting consequences on the

```
Feb 10 01:36:15 magma-dev sessiond[10808]: I0210 01:36:15.556543 10974 LocalSessionManagerHandler.cpp:50] Aggregating 153 records
Feb 10 01:36:20 magma-dev sessiond[10808]: I0210 01:36:20.620278 10974 LocalSessionManagerHandler.cpp:50] Aggregating 153 records
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.990612 10808 LocalSessionManagerHandler.cpp:109] Succeeded in updating session after no reporting
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.991966 10808 LocalSessionManagerHandler.cpp:71] ---------------------------------------------------------
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.991988 10808 LocalSessionManagerHandler.cpp:72] ---DELTA ReportRules from receiving grps to start process 0.000720707
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.992420 10808 LocalSessionManagerHandler.cpp:74] ---DELTA ReportRules to read_all_sessions from redis 6.06852
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.992446 10808 LocalSessionManagerHandler.cpp:76] ---DELTA ReportRules to aggregate_records 0.0124525
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.992789 10808 LocalSessionManagerHandler.cpp:78] ---DELTA ReportRules to check_usage_for_reporting_ 0.353694
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.993681 10808 LocalSessionManagerHandler.cpp:80] ---DELTA ReportRules totaal 6.43467
Feb 10 01:36:21 magma-dev sessiond[10808]: I0210 01:36:21.993878 10808 LocalSessionManagerHandler.cpp:82] ---DELTA ReportRules totaal_client_side 6.43539
```
https://www.internalfb.com/phabricator/paste/view/P173862274

Note `totaal` is the total time took by the execution of the function.
Note `totaal_client_side` is the total execution of the function the client saw (which include the delay by the single thread queue on sessiond)


https://github.com/magma/magma/pull/4852

**Comment by uri200** [comment]
on my test, setting stateless `sessiond server encountered error while processing request` does not happen

**Comment by uri200** [comment]
Per what we could observe, this issue may have been produced because debug version was used instead of test version.

Once test version was used (through `fab test package:vcs=git`  command) the issue was not seen again
