### ISSUE TITLE
Slack: collapse MAI -> Magma workspace

### ISSUE THREAD

**Issue by bbarritt** [magma/magma#4813]

**Comment by bbarritt** [comment]
https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another

**Comment by ekowtaylor** [comment]
Folks can refer to this proposal doc: https://fb.quip.com/bo8bAi7spy1w

**Comment by ekowtaylor** [comment]
Updates
- The Magma Core workspace has been upgraded to the 'Plus' plan which removes the limitations of the free plan
- The MAI workspace is now operating in read-only mode and will remain in this mode until it is sunset (except for a few channels heavily used by bots to allow some time for a more graceful deprecation)
- Anyone needing access to the new workspace can join using this: https://join.slack.com/t/magmacore/shared_invite/zt-g76zkofr-g6~jYiS3KRzC9qhAISUC2A
