### ISSUE TITLE
Unable to change LTE config in NMS

### ISSUE THREAD

**Issue by alandrecm** [magma/magma#487]
In NMS, when you create a new Gateway record  it comes with the fields `CSFB MCC`, `CSFB MNC` and `LAC` with default value `1`. Later, when you try to change any information on tab `LTE` you are unable to save it. No error or information is shown to the user, but no action is taken. 

When you analyze with the browser console you see ```{"message":"Invalid config: validation failure list:\nvalidation failure list:\ncsfb_mcc in body should match '^(\\d{3})$'\ncsfb_mnc in body should match '^(\\d{2,3})$'"}```

The solution found was switch `NonEPS ServiceControl` to `SMS`, delete the value of the fields `CSFB MCC`, `CSFB MNC` and `LAC` and switching `NonEPS ServiceControl` back to `Off`

**Comment by fishlinghu** [comment]
@alandrecm I think it means MCC should be 3 numbers, and MNC should be 2 or 3 numbers. Can you try something like "001"? I agree that NMS should show explicitly about those restriction.

**Comment by alandrecm** [comment]
Hi @fishlinghu.

I'm sorry I wasn't clear enough. The problem is that `NonEPS ServiceControl` is set to `off` so these fields (`CSFB MCC`, `CSFB MNC` and `LAC`) are inactive and with default value `1`.  Either they shouldn't be validate or they shouldn't have an invalid default value.

**Comment by xjtian** [comment]
Resolved with 1a47e5cfed89bc4a1f94cb0961a8d60fa303eaac

**Comment by xjtian** [comment]
Closing issue since the commit made it into the v1.0.0-rc1 cut
