### ISSUE TITLE
Standardize Magma's Github label usage

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#4875]
Magma could use a thought out and documented plan around the use of Github labels (and their various use cases - e.g. in Zenhub, in processes around Proposals, etc). As I go to add Issues and tie them to epics I'm unsure how this is represented within Github - nor what labels I should be applying.  Further for some likely necessary open source processes, we lack appropriate labels. I do see a subset of these labels existing already.

There is tooling out in the wild to automate label standardization (see [git-labelmaker](https://github.com/himynameisdave/git-labelmaker) and some example templates for its use [here](https://github.com/jasonbellamy/git-label-packages/tree/master/packages)).

**Comment by ekowtaylor** [comment]
Shared a proposal on Github discussions: https://github.com/magma/magma/discussions/5370

**Comment by ekowtaylor** [comment]
Labels revised and standardized, will revisit every quarter to cleanup as needed
