### ISSUE TITLE
Formalize and document a process for Proposals at Magma

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#4888]
Now that Magma is transitioning to the Linux Foundation, it is increasingly important that we offer a clear public process and venue for Proposals, their discussion and outcome handling. Proposals can cover all sorts of aspects of Magma - including system design, feature or API design, processes for code submittal, repository changes, and more.

The process:

- Needs to be clearly documented
- Needs to leave a trace of historic Proposal outcomes (both accepted and rejected)
- Needs to be fair and offer equal opportunity for all parties to have their ideas heard
- Needs to have Magma points-of-contact who shepherd all Proposals through review
- Needs to be lightweight and timely in execution

Having surveyed the landscape of this problem space (Open source processes for Proposal handling) - I here propose that we adopt a variant of the [Golang community Proposal process](https://github.com/golang/proposal).

**Comment by electronjoe** [comment]
Following the Golang Proposal process - the details of this Proposal seem too vague and we would like more detail.

Specifically we would like to see at least the following in a follow-up design document within [docs/readmes/proposals/](https://github.com/magma/magma/tree/master/docs/readmes/proposals):

- A stepwise process for Proposals
- Clarity on how the public determines their Proposal shepherd at Magma
- Timeline expectations for Proposal steps
- A Proposal Template file, clarifying nominal proposal content topics (perhaps by class of Proposal)

**Comment by electronjoe** [comment]
Feedback so far has been out-of-band (not on this GH Issue) - which is itself a concerning trend for this new process proposal! I'll convey the topics voiced here so they are documented and allow access for all (the objective of this process).

## Design Document Authorship

**Comment:** The proposal has received some concern around the weight / difficulties of the proposed document authorship, commenting and editing. Specifically, concerns around use of Markdown and GitHub Pull Requests / GH Issues for commenting.  There is an argument being made that Google Docs or similar achieve more efficient commenting, revision, and initial authorship.

**Response:** If the attempt to formalize a public Proposal process is abandoned due to use friction, that's a fatal flaw. And team members have prior experience of this path - specifically with repository-based Design Document processes.  We should try to find a way to assess this early, and either change the mechanism of documentation or plan to do so if things are too high friction.

That said, I see strong rationale from the Golang team process here, including:

- Design Document revisions are clearly detected and understood in context
    - Not so at all with a Google Document or similar
    - One would need a lot of process around gDocs to try address this (track changes? accept changes? when?)
- Design Document comments are preserved with the state of the document at the comment time
    - Again, not so for a Google Document or similar
- Design Document Access Control is solved
    - GitHub Issue, PR processes have clear process for Access Control
    - Not so with a third party e.g. gDoc - who has edit, who has comment, how do we grant
- Design Documents stored directly in the repository are persistent
    - No loss of Google Drive access, no edit permissions challenges, no longer term loss of designs

## GH Issue Use vs GH Discussions

**Comment:** @tmdzk and @bbarritt expressed interest in exploring GH Discussions for the initial Proposal posting and discussion, instead of GH Issues.  I believe the argument was that GH Discussion allowed more free-flowing and complex discussion - e.g. threads and replies that are clearer.

**Response:** I think this should be evaluated. The key feature I would be looking to assure is that PR updates associated with the Design Doc on the Proposal are clearly tracked (automatically) by the GitHub infrastructure - to allow comments to clearly refer to a version of the Design Document.  This happens in GH Issues by default.  Can it be done in GH Discussions?

## Top Layer Process Feedback So Far

So far there is little dissent on the top level process (GH Issue or Discussion with tag for Proposals, escalation if necessary by asking for Design Doc addressing specific complexities, shepherd on Magma to ensure liveliness, finalization of decision).

**Comment by electronjoe** [comment]
## Design Document Authorship

So far, there has not been too much alarm over authoring Markdown documents. Some intend to author them in Quip and then export as Markdown - others seem OK with direct Markdown authorship.  **I am strongly leaning towards trying out the Markdown model first - as opposed to Google Docs support**.  Noting the extra friction possibly - for those who prefer GDocs.

As I worried above - we are already facing Google Doc Access Control problems at Magma. Maybe we will fix these / grow out of them but right now:

* FB Employees seem unable to share publicly any Google Doc
  * Due to FB policy enforcement that impacts even Magma Gdrive
  * To publicly share a doc they need to get a Magma Gdrive personal account tied to their personal Gmail
  * This intorduces a barrier for others to contribute Design Documents
  * This makes it more awkward for FB to shre documents with others
  * Support for commenting / suggesting changes is not yet tested for public access
    * But I suspect it may be another issue requiring per-user commenting permissions be added per design doc
  * **Generally: as I worried - access control is super problematic and will impact public use if we leave GitHub ecosystem for design docs**

## GH Issue Use vs GH Discussions

As I try to write up / edit the document to propose a process exclusively using GH Discussions and GH PR - I keep running into holes or clarity gaps.  Deviating from a well thought out and established process (e.g. ~Golang) means our proposal process has to be rebuilt / stress tested / worked on much more.  This is what I was looking to avoid.  Here are some examples of concerns I have raised in what-if ing a GH Discussion -> GH PR process that is one-way (additional concerns if we allow back and forth!):

* GH Discussions are not presently suited for management and monitoring of progress / status
  * Lack of labels makes them more challenging to employ
  * See the Proposal Review GH Issue [Labels](https://github.com/magma/magma/blob/master/docs/readmes/proposals/README.md#proposal-review) being proposed in draft
    * These make it really clear of the proposal state / easy to find proposals at various states
* Lightweight Proposals would ?end? by locking in GH Discussion -> No PR artifact
  * But GH Discussions are not easily searched by outcome or by proposal vs other Ideas
  * Small proposals may well get lost in Discussions
* At what point does discussion move from GH Discussion to GH PR?
  * After somebody locks discussion and points at a GH PR?
  * Then all discussion of the formal Design Doc would occur on GH PR
    * What happens if at this stage the Design Doc / Proposal is Rejected? Do we let the PR Rot? Do we commit it with a header saying: rejected?
* GH Discussions lack auto-referencing of PRs / Revisions and are not linear
  * I guess the GH Discussion would not be used once a PR is up (needs to be locked)

Again, the benefit of GH Discussions are:

* Low bar to contribute (people aren't intimidated over commenting on GH Issue)
* Good visibility (don't have to know to monitor GH Issues with a particular label)

I wonder if we could amend the Proposal Process draft (based on ~Golang) to prefix it with a ~:

> First, post a lightweight Idea concept to Magma/s GH Discussions - ensure the idea hasn't been proposed already, get early feedback on the wording of the proposal, and get visibility. Then once you feel ready - move the proposal text to a GH Issue as discussed below and drop a link to the GH Issue in your Magma GH Discussion, close the GH DIscussion.
```

**Comment by PARitter** [comment]
As described, the process states that "a discussion" leads to a proposal being "accepted", "rejected" or "ask for a design doc".

I don't think we should make this cumbersome and bureaucratic, but I think there needs to be a bit more detail here about WHO is required to make this decision and if there are any objective criteria they should apply.

**Comment by electronjoe** [comment]
On the Proposal GH Issue generation, the following feedback was supplied:

> Creating a GH issue for the actual Golang process throws a template that the author can fill in (no or less guesswork on level of detail). Might be good idea to do it for us.

**Comment by hcgatewood** [comment]
Closing as accepted!
