### ISSUE TITLE
Testing infrastructure for S1 mobility

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#4890]
Set up TeraVM and local dev test setup + documentation for S1 mobility

**Comment by shaddi** [comment]
- TM500 testbed set up @ FB. Test cases:
  - Test S1-Handover with 2 eNodeB and with Single Subscribers
  - Test S1-Handover with Multiple eNodeBs
  - Test S1-Handover with multi UE
  - Scale Test S1-Handover with 10 subscribers
  - (Negative Test Cases) - eNB rejects the HO
- Local test bed: 2x Baicells + UE configured
