### ISSUE TITLE
Error: Secrets Manager Secret "orc8r-secrets" not found

### ISSUE THREAD

**Issue by prudhviblinqnet** [magma/magma#4910]
I am using v1.3.3 used this tag git code to build and push images 
also using the same tag to use in terraform modules

i am using main.tf from this sample location and updated with my input variables
orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic

getting below error

_Error: Secrets Manager Secret "orc8r-secrets" not found

Error: Invalid count argument

  on .terraform/modules/orc8r-app/orc8r/cloud/deploy/terraform/orc8r-helm-aws/logging.tf line 101, in resource "helm_release" "elasticsearch_curator":
 101:   count = var.elasticsearch_endpoint == null ? 0 : 1

Error: Unable to find remote state

  on .terraform/modules/orc8r-app/orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf line 14, in data "terraform_remote_state" "current":
  14: data "terraform_remote_state" "current" {_

**Comment by karthiksubraveti** [comment]
Running with `-target=module.orc8r` fixed the issue
