### ISSUE TITLE
[CI][LTE] Integration test failure on nested libvirt

### ISSUE THREAD

**Issue by mattymo** [magma/magma#4911]
Magma git commit: 7268cba34a3a5de82b6dac24e0819d5c24a2060c

### Describe the Issue
Various s1aptests seem to be causing control_proxy to crash and not recover during integration tests:
s1aptests/test_attach_implicit_detach_timer_expiry.py (logs attached to issue)
s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py (logs in https://jenkins.magmacore.org/blue/organizations/jenkins/magma_integration_tests/detail/magma_integration_tests/2679/pipeline . Click "Artifacts" at the top to get magma syslog)

[lte integ failure.txt](https://github.com/magma/magma/files/5967898/lte.integ.failure.txt)
[syslog.txt](https://github.com/magma/magma/files/5967895/syslog.txt)

**Comment by koolzz** [comment]
@ardzoht  do you know if this is related to those failures you're fixing?

**Comment by ardzoht** [comment]
this failure looks unrelated to a s1ap test failure but more as a problem on the traffic server, is this happening constantly?
