### ISSUE TITLE
The machine with the name 'cloud' was not found configured for this Vagrant environment.

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#496]
When running this command following error is observed.
~/magma/orc8r/cloud$ vagrant up cloud datastore
The machine with the name 'cloud' was not found configured for
this Vagrant environment.

**Comment by xjtian** [comment]
We've been using docker for the orchestrator cloud for some time now. I would check the docs for the new dev setup for cloud: https://facebookincubator.github.io/magma/docs/basics/introduction.html
