### ISSUE TITLE
Add precheck and postcheck validation for Orc8r AWS deployment

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#4963]
Add precheck, postcheck and cleanup for orc8r AWS deployments.

**Comment by ShubhamTatvamasi** [comment]
I was thinking the same. I would also like to work on this as this will help me a lot at the time of deployment.

**Comment by karthiksubraveti** [comment]
> I was thinking the same. I would also like to work on this as this will help me a lot at the time of deployment.

That's great. Will flush out more details here and add smaller github issues and you can take on the issue if you are interested.
