### ISSUE TITLE
.env file is missing! Please add this file to the directory that you are running this command and re-try.

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#497]
When running this command sudo ./install_gateway.sh feg
.env file is missing! Please add this file to the directory that you are running this command and re-try.

**Comment by mpgermano** [comment]
Hi @shoaibbutt50. Are you attempting to setup a development environment or a production deployment. The install script is only needed for a production deployment. If attempting to setup a dev env, please follow: https://facebookincubator.github.io/magma/docs/feg/docker_setup

If attempting to setup a deployment, you'll need a .env, control_proxy.yml, and rootCA.pem, which should be specific to your deployment. If this is the case, I can provide more information on these three files.

**Comment by shoaibbutt50** [comment]
I am attempting a development environment. i solved the issue now i am facing another issue if you could help after running the sudo ./install_gateway.sh feg
Logging into docker registry at magmad_
Username: magma_dev
Password: 
Error response from daemon: Get https://magmad_/v2/: dial tcp: lookup magmad_: no such host
This error is observed.

**Comment by mpgermano** [comment]
Attempting to install using a deployment script for a dev environment will be harder than following the dev environment setup. I'd recommend following the link I provided above. It consists of only a few steps.

**Comment by shoaibbutt50** [comment]
Thanks for your support. Kindly share the guide link for production environment also.
