### ISSUE TITLE
Cloudstrapper AMI for AWS Marketplace

### ISSUE THREAD

**Issue by arunuke** [magma/magma#4987]

**Comment by arunuke** [comment]
As a user, I would like a pre-built image (in a Cloud Provider native form - ex: AMI for AWS) which has all dependencies and tools embedded in it to achieve a single-click/single-command deployment of Magma (referred to as Cloudstrapper - an instance that Bootstraps Magma in the Cloud)

As a user, I would require that the running instance of the Cloud to be from the free tier. For AWS, this requires the instance to use an eligible OS (Ubuntu 20.04 - standardizing with the rest of the stack) and an instance type from the free tier (t2.micro).

As a user, I would like the instance to clone the latest stable version of Magma when the instance type boots up by using a cloud-init script. This would ensure that the instance always has the desired binaries without having to replace the AMI itself on newer changes.

Design inputs:

- Deploy an upstream version of Ubuntu 20.04
- Configure the deployed version with the latest packages and tools required to deploy orchestrator and gateways
- Snapshot instance and save as AMI
- Customize AMI by adding a Cloud-init script that would pull the latest, stable Magma source code
- Publish AMI in Marketplace available across multiple regions

An implementation of this design is available from magma/expertimental/cloudstrapper from magma core's github repo.

Test Plan:

- Deploy t2.micro instance using Marketplace AMI
- From Magma sources (experimental or core directories), run the deployer for Orchestrator and validate Orchestrator readiness.
- Deploy in-region gateways and validate gateway connectivity.

**Comment by ekowtaylor** [comment]
@arunuke , I think this issue has gone stale. Can you please provide the latest updates here?

**Comment by arunuke** [comment]
Developer pipeline currently being built. On track for 1.6.

**Comment by vik2595** [comment]
What are the terraform settings that needs to be done before running orc8r.yaml playbook ?

**Comment by arunuke** [comment]
@vik2595 The main.tf file is built based on J2 templates at runtime. The values that need to be mandatorily specified are listed in Sec 4 of the Cloudstrapper README. the user has the option to skip the install tag and manually edit the main.tf file under <dirInventory>/<cluster name>/terraform directory as well if there are specific needs.

**Comment by arunuke** [comment]
Devops pipeline publishing images on Magma AWS accounts both internally and externally. v 1.5.X and 1.6.X available.
