### ISSUE TITLE
Cannot install FEG Gateway

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#499]
After executing the command 
vagrant@magma-feg-dev:~/magma/feg/gateway$ make run
Following error is observed
OSError: Command /home/vagrant/build/python/bin/python3.5 - setuptools pkg_resources pip wheel failed with error code 1
/home/vagrant/magma/orc8r/gateway/python/python.mk:23: recipe for target 'install_virtualenv' failed
make[1]: *** [install_virtualenv] Error 1
make[1]: Leaving directory '/home/vagrant/magma/orc8r/gateway/python'
Makefile:22: recipe for target 'buildenv' failed
make: *** [buildenv] Error 2

**Comment by mpgermano** [comment]
You should setup your dev environment using Docker (not Vagrant): https://facebookincubator.github.io/magma/docs/feg/docker_setup 

You can run these steps directly on your host machine. Vagrant is our legacy dev env and will be deprecated soon.

**Comment by shoaibbutt50** [comment]
Thanks for the support. Radius service is giving error
Creating radius        ... error

All other services are up
    Name                 Command             State               Ports          
--------------------------------------------------------------------------------
aaa_server      envdir                      Up                                  
                /var/opt/magma/envd ...                                         
control_proxy   /bin/bash -c ip -4 route    Up                                  
                l ...                                                           
csfb            envdir                      Up                                  
                /var/opt/magma/envd ...                                         
eap_aka         envdir                      Up                                  
                /var/opt/magma/envd ...                                         
feg_hello       envdir                      Up                                  
                /var/opt/magma/envd ...                                         
health          envdir                      Up                                  
                /var/opt/magma/envd ...                                         
hss             envdir                      Up                                  
                /var/opt/magma/envd ...                                         
magmad          /bin/bash -c ip -4 route    Up                                  
                l ...                                                           
radius          sh -c envsubst <            Exit 128                            
                radius.co ...                                                   
redis           /bin/bash -c                Up                                  
                /usr/local/bi ...                                               
s6a_proxy       envdir                      Up         0.0.0.0:3869->3868/tcp   
                /var/opt/magma/envd ...                                         
session_proxy   envdir                      Up         0.0.0.0:32771->3906/tcp, 
                /var/opt/magma/envd ...                0.0.0.0:32770->3907/tcp  
swx_proxy       envdir                      Up         0.0.0.0:3868->3868/tcp   
                /var/opt/magma/envd ...                                         
test            /bin/bash -c mkdir -p       Up                                  
                ../. ...

**Comment by shoaibbutt50** [comment]
After running this command /magma/orc8r/tools/docker$ sudo ./install_gateway.sh feg
Logging into docker registry at magmad_
Username:
From where to get the username and password
