### ISSUE TITLE
[MME] Implement property test to thoroughly validate state translation functions (struct<->proto)

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#4996]
Property tests are unit tests which generate random inputs, and then validate for each random trial that some property holds.  They can provide broad coverage and be low maintenance (because their properties rarely are impacted by changes). But they will not validate detailed behavior (normally) - that requires high effort targeted unit tests.

The MME has thousands of lines of newly added state transfer logic - from the migration to stateless MME (key state within the MME is converted from struct to protobuf format, stored in redis, and then fetched on startup).  There are no existing unit tests for this large block of new code - but a property test to validate that double-mutation (struct->proto->struct') and that struct == struct' would provide really strong test coverage of this type of code.

We should do that!

**Comment by electronjoe** [comment]
Note that we might be able to leverage Google's [Protobuf-fuzzer](https://blog.trailofbits.com/2016/05/18/protofuzz-a-protobuf-fuzzer/) library to generate random protobuf representations.  Then do proto->struct->proto and compare.

**Comment by electronjoe** [comment]
For property test frameworks and general discussion, see #5042.

**Comment by ekowtaylor** [comment]
@electronjoe since the associated PR has been merged can this be closed?

**Comment by electronjoe** [comment]
@ekowtaylor the PR was just a pre-requisite, there are still at least two, maybe as many as four PRs that will result from this effort. I've got a journal of tech debt issues which have slowed this effort - all of the issues I've run into are enumerated in my AGW Availability plan #6269 (and the tech debt has been deprioritized... but the many forms of tech debt result in ~10% efficiency on most tasks I attempt in MME).

**Comment by electronjoe** [comment]
A GH [Gist](https://gist.github.com/electronjoe/56d6d821b2120166859b4a0d8dcb4409) in which I enumerate the Technical debt issues (previously listed in #6269) which have substantially slowed my effort on this GH Issue this sprint.
