### ISSUE TITLE
[MME] LeakSanitizer triggering on bstring usage patterns #fuzz #llvm #bazel

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#4997]
## Setup

Discovery thanks to LLVM's [libFuzzer](https://llvm.org/docs/LibFuzzer.html).

This discovery comes from a personal branch of Magma [Master df06398](https://github.com/magma/magma/commit/df0639879a5be15746c41507c5a40573a1675bfc).  The branch was modified to support **clang 11.0 build** with **LLVM's lld linker** and build orchestration by **bazel build**.  The effort to support clang is a longer term one, and not the point of this Issue. I would note that so far - a GCC + American Fuzzy Lop fuzzing effort (See PR #4983 ) on this same code segment has not detected this leak (a leak that occurs 100% of function calls) - presumably LeakSanitizer is not enabled and should be - to be confirmed.

Fuzzing [decode_attach_accept()](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/tasks/nas/emm/msg/AttachAccept.c#L26) by use of **clang's built-in fuzzing engine - [libFuzzer](https://llvm.org/docs/LibFuzzer.html)** resulted in the following discovery of a LeakSantitizer hit.  Note that line numbers below align with Magma [Master df06398](https://github.com/magma/magma/commit/df0639879a5be15746c41507c5a40573a1675bfc).

## LLVM's libFuzzer + LeakSanitizer Finding

```text
INFO: Analyzed target //c/oai/tasks/nas/emm/msg:attach_accept_fuzz_test_run (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //c/oai/tasks/nas/emm/msg:attach_accept_fuzz_test_run up-to-date:
  bazel-bin/c/oai/tasks/nas/emm/msg/attach_accept_fuzz_test_run
INFO: Elapsed time: 0.105s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Launching c/oai/tasks/nas/emm/msg/attach_accept_fuzz_test_bin as a libFuzzer fuzz test...
Using test output root: /tmp/fuzzing
Writing new corpus elements at: /tmp/fuzzing/corpus
Writing new artifacts at: /tmp/fuzzing/artifacts
INFO: Seed: 1742680552
INFO: Loaded 1 modules   (11822 inline 8-bit counters): 11822 [0x60dc70, 0x610a9e),
INFO: Loaded 1 PC tables (11822 PCs): 11822 [0x610aa0,0x63ed80),
INFO:        2 files found in /tmp/fuzzing/corpus
INFO:        0 files found in c/oai/tasks/nas/emm/msg/attach_accept_fuzz_test_corpus
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 2 min: 9b max: 13b total: 22b rss: 35Mb
#3      INITED cov: 19 ft: 21 corp: 2/22b exec/s: 0 rss: 35Mb
        NEW_FUNC[1/4]: 0x403b20 in decode_esm_message_container /proc/self/cwd/c/oai/tasks/nas/ies/EsmMessageContainer.c:30
        NEW_FUNC[2/4]: 0x42b8d0 in decode_bstring /proc/self/cwd/c/oai/common/TLVDecoder.c:35

=================================================================
==27158==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x3c5e5d in malloc /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x50424c in blk2bstr /proc/self/cwd/c/oai/lib/bstr/bstrlib.c:314:17
    #2 0x42b9d2 in decode_bstring /proc/self/cwd/c/oai/common/TLVDecoder.c:41:13
    #3 0x403f1e in decode_esm_message_container /proc/self/cwd/c/oai/tasks/nas/ies/EsmMessageContainer.c:45:24
    #4 0x3f5fab in decode_attach_accept /proc/self/cwd/c/oai/tasks/nas/emm/msg/AttachAccept.c:58:25
    #5 0x3f5af8 in LLVMFuzzerTestOneInput /proc/self/cwd/c/oai/tasks/nas/emm/msg/AttachAcceptFuzzer.cpp:13:17
    #6 0x2ff3b1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:559:15
    #7 0x2feaf5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:471:3
    #8 0x300520 in fuzzer::Fuzzer::MutateAndTestOne() /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:702:19
    #9 0x300f95 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:838:5
    #10 0x2efd45 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:847:6
    #11 0x3185f2 in main /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #12 0x7fb5bc8192e0 in __libc_start_main /build/glibc-77giwP/glibc-2.24/csu/../csu/libc-start.c:291

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x3c5e5d in malloc /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5043c5 in blk2bstr /proc/self/cwd/c/oai/lib/bstr/bstrlib.c:323:30
    #2 0x42b9d2 in decode_bstring /proc/self/cwd/c/oai/common/TLVDecoder.c:41:13
    #3 0x403f1e in decode_esm_message_container /proc/self/cwd/c/oai/tasks/nas/ies/EsmMessageContainer.c:45:24
    #4 0x3f5fab in decode_attach_accept /proc/self/cwd/c/oai/tasks/nas/emm/msg/AttachAccept.c:58:25
    #5 0x3f5af8 in LLVMFuzzerTestOneInput /proc/self/cwd/c/oai/tasks/nas/emm/msg/AttachAcceptFuzzer.cpp:13:17
    #6 0x2ff3b1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:559:15
    #7 0x2feaf5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:471:3
    #8 0x300520 in fuzzer::Fuzzer::MutateAndTestOne() /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:702:19
    #9 0x300f95 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:838:5
    #10 0x2efd45 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:847:6
    #11 0x3185f2 in main /build/llvm-toolchain-11-11.1.0~++20210204123133+1fdec59bffc1/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #12 0x7fb5bc8192e0 in __libc_start_main /build/glibc-77giwP/glibc-2.24/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: 24 byte(s) leaked in 2 allocation(s).
INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

MS: 4 CopyPart-ChangeBinInt-ChangeBit-CrossOver-; base unit: ae42d8cae3e853ea5518ac46ce00b2d8181f979a
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xa,0x0,0x0,0x0,0x0,
\x00\x00\x00\x00\x00\x00\x00\x00\x0a\x00\x00\x00\x00
artifact_prefix='/tmp/fuzzing/artifacts/'; Test unit written to /tmp/fuzzing/artifacts/leak-8b6b45f88b7ba2710ae211b1e49888e058810cc1
Base64: AAAAAAAAAAAKAAAAAA==
vagrant@magma-dev:~/magma/lte/gateway$ %
```

## Source of the Indirect Leak

[Edit: see update in comment below]

The Indirect Leak is I believe a mistake in my top level fuzzer function. I'm still exploring this and it should be root caused.

## Source of the Direct Leak

Magma is using a forked copy of [bstrlib](https://github.com/websnarf/bstrlib).  Unfortunately the library lacks good examples, top level documentation or per function documentation with respect to memory management practices required for safe use.  But upon digging myself I see what is happening here, and [elsewhere](https://github.com/magma/magma/blob/4f87b3f4ebafd32b0a7772ec0be2566c2305cb4a/lte/gateway/c/oai/common/state_converter.cpp#L144) in the Magma MME codebase.

### bstrlib memory management

The objects we pass around most in the Magma MME, with respect to bstrlib - are **bstring** objects.

**bstring**s are actually pointers to bstrlib **tagbstring** structs [source](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/lib/bstr/bstrlib.h#L38-L39).  Critically, the various bstrlib bstring generators all dynamically allocate this struct - it must be memory-managed.

Additionally, Internal to bstrlib, these tagbstring [structs](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/lib/bstr/bstrlib.h#L206-L210) then have a pointer to a second dynamically allocated memory chunk to store the data.

So we have two dynamic allocations to manage / watch out for here.

The bstrlib offers [bdestroy](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/lib/bstr/bstrlib.h#L56-L57) as the public API to clean up a bstring.  The [function](https://github.com/magma/magma/blob/4f87b3f4ebafd32b0a7772ec0be2566c2305cb4a/lte/gateway/c/oai/lib/bstr/bstrlib.c#L1113-L1120) first attempts to free the internal data allocation (if non-null) and then frees the tagbstring struct.  I note that Magma MME makes [liberal use](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/magma/magma%24%404f87b3f+bdestroy&patternType=literal) of bdestroy(), as well as a Magma MME authored [bdestroy_wrapper](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/common/dynamic_memory_check.c#L53).

### This memory leak - caused in TLVDecoder.c:decode_bstring

In this specific detection, the fatal issue is observed in TLVDecoder.c:decode_bstring.  Specifically, [line 41](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/common/TLVDecoder.c#L41).  It's nuanced due to all the indirection and object-hiding combined with manual memory management.

Recall that blk2bstr is dynamically generating a new bstring object, which is a pointer to a tagbstring struct (dynamically allocated) which within it contains a pointer to a dynamically allocated data buffer.

Line 41 here is copy assigning the newly generated struct contents to bstr (bstring pointer, passed into decode_bstring as a return-value).  Presumably higher layer logic correctly calls bdestroy or bdestroy_wrapper on this newly copy-constructed bstring - hence we do not leak the inner data allocation.  But we are leaking the newly generated tagbstring struct! As it is never freed here, and is lost when we leave this branch of the if statement.

## Other bstrlib leaks in Magma MME Exist - Audit needed

We need to review the list of bstring references (e.g. [Here](https://sourcegraph.com/github.com/magma/magma@4f87b3f/-/blob/lte/gateway/c/oai/common/TLVDecoder.c#L34:5&tab=references) is a good starting point) - to audit for leaks elsewhere.  As an example, I spot a leak [in our state conversion logic](https://github.com/magma/magma/blob/4f87b3f4ebafd32b0a7772ec0be2566c2305cb4a/lte/gateway/c/oai/common/state_converter.cpp#L144).

**Comment by electronjoe** [comment]
## Source of the Indirect Leak ~ false alarm

The Indirect leak above is due to my fuzzing insertion point, which is too low in the call hierarchy to hit the cleanup of our emm_msg->attach_accept.esmmessagecontainer.  It would be nice to fuzz a higher insertion point, but functions higher in the call stack do have many parameters as input that may require specific shape. Worth exploring but not low hanging fruit.

I found the bdestroy(_wrapper) calls by use of [This](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/magma/magma%24%404f87b3f+:%5Bfunction%7Ebdestroy%28_wrapper%29%3F%5D%28:%5Bparam%5D%29+rule:%27where+match+:%5Bparam%5D+%7B+%7C+%22:%5B_%7Eesmmessagecontainer%5D%22+-%3E+true+%7C+%22:%5B_%5D%22+-%3E+false+%7D%27&patternType=structural) SourceGraph structural query.

- [Instance 1](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c#L381)
- [Instance 2](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c#L1467)
- [Instance 3](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c#L2125)

**Comment by electronjoe** [comment]
With the modification of my top level fuzing function to include bdestroy_wrapper of the allocated resources of the fuzz test, I find that the LeakSanitizer finding is removed [Gist of top level function](https://gist.github.com/electronjoe/3aff239f43680919c258a62a807cef02).  I do not yet understand why my logic above is incorrect - but it seems that copying the tagbstring struct [here](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/common/TLVDecoder.c#L41) is not inducing a leak of the pointed-to tagbstring struct.

The secondary finding upon audit of bstring use, however, still holds at this time: [this generation](https://github.com/magma/magma/blob/4f87b3f4ebafd32b0a7772ec0be2566c2305cb4a/lte/gateway/c/oai/common/state_converter.cpp#L144) of a bstring absolutely lacks a bdestroy / bdestroy_wrapped call to deallocate it. We should audit all bstring generation (or augment test coverage and run with LeakSanitizer enabled).

**Comment by ssanadhya** [comment]
@electronjoe , giving this back to you.
