### ISSUE TITLE
SCTP crashes while switching from master branch to v1.4 branch

### ISSUE THREAD

**Issue by rsarwad** [magma/magma#4998]
### Your Environment

- **Version:**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** sctpd service
- **Deployment Environment:**  Vagrant (AGW)

### Describe the Issue
After switching from master branch to v1.4 branch, sctpd crashes with below back trace
#0  0x0000557ada0637c4 in std::unique_ptr<std::thread, std::default_delete<std::thread> >::get (this=0x50)
    at /usr/include/c++/6/bits/unique_ptr.h:308
#1  0x0000557ada0635ca in std::unique_ptr<std::thread, std::default_delete<std::thread> >::operator bool (this=0x50)
    at /usr/include/c++/6/bits/unique_ptr.h:322
#2  0x0000557ada0634aa in std::operator!=<std::thread, std::default_delete<std::thread> >(std::unique_ptr<std::thread, std::default_delete<std::thread> > const&, decltype(nullptr)) (__x=<error reading variable: Cannot access memory at address 0x50>)
    at /usr/include/c++/6/bits/unique_ptr.h:674
#3  0x0000557ada060912 in magma::sctpd::SctpConnection::Send (this=0x0, assoc_id=13, stream=0,
    msg=" \021\000\027\000\000\002\000i\000\v\000\000\000\361\020\000\000\000\001\000\001\000W@\001\v")
    at /home/vagrant/magma/lte/gateway/c/sctpd/sctp_connection.cpp:78
#4  0x0000557ada03a03f in magma::sctpd::SctpdDownlinkImpl::SendDl (this=0x7ffeeca45400, context=0x7f4795083bc0, req=0x7f4795083a10,
    res=0x7f47950839a0) at /home/vagrant/magma/lte/gateway/c/sctpd/sctpd_downlink_impl.cpp:92
#5  0x0000557ada055c2b in std::__invoke_impl<grpc::Status, grpc::Status (magma::sctpd::SctpdDownlink::Service::* const&)(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), magma::sctpd::SctpdDownlink::Service*, grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*>(std::__invoke_memfun_deref, grpc::Status (magma::sctpd::SctpdDownlink::Service::* const&)(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), magma::sctpd::SctpdDownlink::Service*&&, grpc::ServerContext*&&, magma::sctpd::SendDlReq const*&&, magma::sctpd::SendDlRes*&&) (
    __f=@0x557ada6b0588: &virtual magma::sctpd::SctpdDownlink::Service::SendDl(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), __t=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb58b>,
    __args#0=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb597>,
    __args#1=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb6b3>,
    __args#2=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb6bf>) at /usr/include/c++/6/functional:227
#6  0x0000557ada0551b8 in std::__invoke<grpc::Status (magma::sctpd::SctpdDownlink::Service::* const&)(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), magma::sctpd::SctpdDownlink::Service*, grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*>(grpc::Status (magma::sctpd::SctpdDownlink::Service::* const&)(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), magma::sctpd::SctpdDownlink::Service*&&, grpc::ServerContext*&&, magma::sctpd::SendDlReq const*&&, magma::sctpd::SendDlRes*&&) (
    __fn=@0x557ada6b0588: &virtual magma::sctpd::SctpdDownlink::Service::SendDl(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), __args#0=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb58b>,
    __args#1=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb597>,
    __args#2=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb6b3>,
    __args#3=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb6bf>) at /usr/include/c++/6/functional:251
#7  0x0000557ada053bb4 in std::_Mem_fn_base<grpc::Status (magma::sctpd::SctpdDownlink::Service::*)(grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*), true>::operator()<magma::sctpd::SctpdDownlink::Service*, grpc::ServerContext*, magma::sctpd::SendDlReq const*, magma::sctpd::SendDlRes*>(magma::sctpd::SctpdDownlink::Service*&&, grpc::ServerContext*&&, magma::sctpd::SendDlReq const*&&, magma::sctpd::SendDlRes*&&) const (this=0x557ada6b0588,
    __args#0=<unknown type in /home/vagrant/build/c/sctpd/sctpd, CU 0x9d9cf, DIE 0xcb58b>
    
**To Reproduce**
Below are the steps to re-create the crash
1. Initially switch to master branch;
2. Build code and execute basic attach_detach test case, it works fine
3. Then switch to v1.4 branch 
4. Build the code and execute basic attach_detach test case, it leads to crash. But it works fine, if we execute "make run" and then run test case.

**Comment by ssanadhya** [comment]
@rsarwad, closing this issue as it is on a very old version. Please re-open if this recurs on master.
