### ISSUE TITLE
[AGW][S1ap tests] Integration tests with entries left in hashtable

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5005]
From the CircleCI run https://circleci.com/api/v1.1/project/github/magma/magma/132698/output/111/0?file=true&allocation-id=6026e100d83e952d4d5e0397-0-build%2F522E50F (Log file attached in [circleci_job_132698.txt](https://github.com/magma/magma/files/5998494/circleci_job_132698.txt)) two tests report non-zero values for `Entries left in hashtables (should be zero):`

- test_sctp_abort_after_identity_req.py
- test_sctp_shutdown_after_smc.py

These do not show up in the local run of `make integ_test`, so need to verify if latest CI builds are still reporting this issue.

**Comment by ssanadhya** [comment]
From https://circleci.com/api/v1.1/project/gh/magma/magma/134453/output/111/0?file=true&allocation-id=602c4793792b74309e189942-0-build%2F7E93C34E (log attached in [circleci_job_134453.txt](https://github.com/magma/magma/files/5998654/circleci_job_134453.txt)) seeing:

```
circleci_job_134453.txt:[magma@10.240.0.25] out: Running test: s1aptests/test_attach_no_initial_context_resp.py
circleci_job_134453.txt:[magma@10.240.0.25] out: Entries left in hashtables (should be zero): 1

circleci_job_134453.txt:[magma@10.240.0.25] out: Running test: s1aptests/test_attach_detach_enb_rlf_initial_ue_msg.py
circleci_job_134453.txt:[magma@10.240.0.25] out: Entries left in hashtables (should be zero): 3
```

**Comment by ssanadhya** [comment]
From https://circleci.com/api/v1.1/project/github/magma/magma/135590/output/111/0?file=true&allocation-id=602d58629a88cc4d6726ee26-0-build%2F3F1BA00E (log attached in [circleci_job_135590.txt](https://github.com/magma/magma/files/5998658/circleci_job_135590.txt) ) seeing:

```
circleci_job_135590.txt:[magma@10.240.0.5] out: Running test: s1aptests/test_attach_no_initial_context_resp.py
circleci_job_135590.txt:[magma@10.240.0.5] out: Entries left in hashtables (should be zero): 3
--
circleci_job_135590.txt:[magma@10.240.0.5] out: Running test: s1aptests/test_attach_detach_enb_rlf_initial_ue_msg.py
circleci_job_135590.txt:[magma@10.240.0.5] out: Entries left in hashtables (should be zero): 3
--
circleci_job_135590.txt:[magma@10.240.0.5] out: Running test: s1aptests/test_sctp_shutdown_after_auth_req.py
circleci_job_135590.txt:[magma@10.240.0.5] out: Entries left in hashtables (should be zero): 2
```

**Comment by ardzoht** [comment]
Closing this since latest CI runs (https://app.circleci.com/pipelines/github/magma/magma/17383/workflows/85a34f87-263e-44cb-8735-052a3ea0d932/jobs/164567/steps) don't report entries left on sctp integ tests
