### ISSUE TITLE
UE(ASUS) Unable to Attach 

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#5006]
### Your Environment
Version: 1.3.2-1607014227-1462d960
Affected Component: Access Gateway
Affected Subcomponent: mobilityd, MME
Deployment Environment: bare-metal (AGW)

### Describe the Issue

UE is not able to attach using specific handset (ASUS) while same SIM card can successfully attach with another equipment.

From PCAP Trace we observed the Attach got rejected by Magma MME while the same UE was able to attach using another equipment. Please refer below snapshots along with attach PCAP Trace.

**Successful  Attach**

![image](https://user-images.githubusercontent.com/77636702/108277306-d75c6600-713e-11eb-93d9-a9a1d2f2807a.png)

**Failed Case**

![image](https://user-images.githubusercontent.com/77636702/108277630-59e52580-713f-11eb-9c1e-fe28cfcb4fd0.png)

**PCAP Trace**

https://drive.google.com/file/d/1P2J9iLRcw_mDDb8W3Pa0Tc2UqHHpOKKw/view?usp=sharing

**MME LOGs**

![image](https://user-images.githubusercontent.com/77636702/108280337-a5013780-7143-11eb-946d-4df5e4e0307c.png)

**Expected behavior**
Attach should be accepted.

**Comment by ulaskozat** [comment]
I guess this is no longer an issue? I am closing it. Please reopen if not the case.
