### ISSUE TITLE
[CI] Re-enable code coverage for c/c++, integrate with CI / PR

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5043]
There was a time when it appears code coverage reporting was in place - as evident in the Makefiles of e.g. [lte/gateway](https://github.com/magma/magma/blob/v1.4/lte/gateway/Makefile#L195-L224) (thanks to @hcgatewood for what exists - which will make it easier to re-enable).

The key challenge today is that the AGW is not built on CircleCI machines, nor is it tested there (even unit tests, with exception of the Python tests).  Instead the job of build and test is pushed to remote machines using a [fab call](https://github.com/magma/magma/blob/v1.4/.circleci/config.yml#L285). So the challenge will be to update the fab call to collect coverage and then exfiltrate it to e.g. CodeCov.io (presently what we are migrating to).

**Comment by themarwhal** [comment]
If we run MME/SessionD unit tests independently from the LTE Integration test in the precommit stage, this might be easier to do. And we'll have the added benefit of doing these tests before the PRs are merged! 
We can probably extend this: https://sourcegraph.com/github.com/magma/magma/-/blob/lte/gateway/docker/mme/Dockerfile.ubuntu18.04
To also include dependencies for the SessionD tests.
