### ISSUE TITLE
[AGW] Automate process of crash stack trace reporting to DEV team

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5048]
Automation of stack traces from in-field AGW crashes has several major benefits:

- Ensure that valuable crash events are visible to developers
- Automated de-duplication of crash reports from the field
- Assist in prioritization of issues by frequency of occurrence

We should explore options such as e.g. [Sentry.io](https://sentry.io/for/native/).

Thanks to @bbarritt and @themarwhal for escalating this.

**Comment by themarwhal** [comment]
Looks like we may need to upgrade our gcc to try.

From https://github.com/getsentry/sentry-native
```
64bit Linux with GCC 9
64bit Linux with clang 9
32bit Linux with GCC 7 (cross compiled from 64bit host)
```

```
vagrant@magma-dev:~/magma/lte/gateway$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
While I try to figure out upgrading GCC6->GCC9, I'll try out the Python SDK in the meantime.

**Comment by themarwhal** [comment]
An issue tracking the GCC upgrade: https://github.com/magma/magma/issues/5102
