### ISSUE TITLE
[CI] Blacklist documentation PRs from executing full CI stack

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5049]
The argument goes that documentation changes (e.g. to magma/docs/) should not:

- Be blocked by long CI presubmit requirements with long execution time
- Be blocked by CI failures or flakes in functional systems
- Have misleading or confusing failures that (should) make the submitter pause or ask questions

I presume our CI (e.g. CircleCI) allow us to specify what sub-directories require what CI steps?

**Comment by electronjoe** [comment]
As an example, my [Proposal PR](https://github.com/magma/magma/pull/4907).

**Comment by nstng** [comment]
Closed under the assumption that this is outdated - in the GH CI pathfilters are used (introduced after this issue was created) in order to reduce unnecessary workflow runs.
