### ISSUE TITLE
[CI] Benchmark Github action: Machine environment Ubuntu 20.04 (Virtualized or not)

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#5072]

**Comment by tmdzk** [comment]
## Summary 

We have a couple of jobs that run inside a `machine` environment, the job start with docker installation and then builds some container and run them.
The goal of that task is to simply benchmark if Github Action can do that. 

Example of a job to migrate: 
[cwag-precommit](https://github.com/magma/magma/blob/master/.circleci/config.yml#L877)
Runner spec: ubuntu-1604:201903-01  - Ubuntu 16.04 machine 

## Ressources 
[Circle CI images ressource](https://circleci.com/docs/2.0/circleci-images/)

**Comment by bramwelt** [comment]
Here's an example of a Github Action that runs on an Ubuntu 20.04 machine. The job pulls down and runs docker's hello-world container: https://github.com/bramwelt/magma/runs/2098931469

Github Action jobs can also run on Ubuntu 18.04 and 16.04.
