### ISSUE TITLE
[CI] Benchmark Github action: Custom runner with nested virtualization (Virtualbox or libvirt)

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#5073]

**Comment by tmdzk** [comment]
## Summary 

Custom runner with nested virtualization (Virtualbox or libvirt)

### Background story
This task is a bit tricky because our current setup is a whole hack. We wrote that when CircleCI didn't have its custom runner 
So we have an hardware machine (Debian 9) under a VPN server. We start a CircleCi job with a machine node, install openVPN, get cert from CircleCI env key vault, run the openVPN service, connect a custom scheduling api that gives you a machine , then we use [fab](http://www.fabfile.org/) to run some remote commands from the CircleCI node to the machine. 
On the machine we run our vitualized environment using Vagrant with either libvirt or virtualbox and then trigger our integration test. 

Note: CircleCI machines nodes doesn't support nested virtualization

#### What we expect: 
I expect to be able to: 
- Connect a machine that has nested virt enable 
- Installa vagrant/virtualbox or libvirt
- clone code
- cd ${MAGMA_ROOT}/lte/gateway && vagrant up 

## Ressources 
[Circle CI images ressource](https://circleci.com/docs/2.0/circleci-images/)

**Comment by bramwelt** [comment]
Github's MacOSX machines support virtualization and come with vagrant + virtualbox [pre-installed](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md). I was able to get a [basic 'vagrant up' job](https://github.com/bramwelt/magma/runs/2081739164) working with the 'hashicorp/bionic64' box, but was unsuccessful in getting libvirt working.

It may be possible after specifying a different path to the libvirt socket in OSX (ex: /User/.cache/run/, vs /var/run/) and setting up libvirt networking manually (specific to vagrant) before bringing machines online.

Alternative to the OSX runners, as long as all the dependencies are installed and the machine is configured, Github Actions should have no issue running virtualization jobs on external hosts ("[self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)").
