### ISSUE TITLE
[CI] Benchmark Github action: Custom runner on VPN protected tools 

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#5074]

**Comment by tmdzk** [comment]
## Summary 

Custom runner that are VPN protected

### Background story
We have a bunch of tools in our lab that are under license or proprietary software. 
Those testing env are env where we run deep/long running test

#### What we expect: 
Be able to install an agent in our lab that pulls on Github Action x time and ask if there is a job for it. 
When a job is triggered through Github Action, the lab machine should be able to pull the information and start triggering the job. We would ideally like to be able to compare result to previous job. 

note: No proxy for outbound traffic, can reach 0.0.0.0 

Please contact @uri200 if you want to benchmark with a real example

**Comment by tykeal** [comment]
@tmdzk , 

This isn't something that LF Release Engineering is going to be able to do for you. We have a policy of only working on either fully open systems (no VPN required) or systems that we're actually managing. We won't touch a system that someone else administers, all we can do is give guidance in those cases and work with someone on the public side of any jobs that are built out.
