### ISSUE TITLE
[PipelineD] test_enforcement_stats_restart is flaky

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5087]
### Your Environment

- **Version:** master
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
Looks like this test is flaky?
https://app.circleci.com/pipelines/github/magma/magma/15220/workflows/7d9551cf-f2c2-48c1-b66d-4f1a646ab337/jobs/139349
https://app.circleci.com/pipelines/github/magma/magma/15199/workflows/f90ed84c-fbc4-4b40-b627-891255e5b179/jobs/139154
https://app.circleci.com/pipelines/github/magma/magma/15101/workflows/69e8e992-58d0-4647-836d-09280468fb67/jobs/138501
https://app.circleci.com/pipelines/github/magma/magma/15097/workflows/2f65dfb5-db3e-4811-8a0c-963dcbd6a808/jobs/138476
https://app.circleci.com/pipelines/github/magma/magma/15097/workflows/3c500742-bccd-481b-91ad-6df42d6124b4/jobs/138451

**Comment by koolzz** [comment]
Not sure if the datapath disconnect is the cause of this issue or the result, anyway I'll try to reproduce locally so fat I have never seen this localy though. @pshelar have you seen this locally? 
```
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 37792) discarded.
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: magma.pipelined.openflow.messages: WARNING: Error sending message, retrying again (attempt 0/3)
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 37792) discarded.
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: magma.pipelined.openflow.messages: WARNING: Error sending message, retrying again (attempt 1/3)
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 37792) discarded.
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: magma.pipelined.openflow.messages: WARNING: Error sending message, retrying again (attempt 2/3)
[magma@10.240.0.25] out: [vagrant@127.0.0.1:2222] out: root: ERROR: Send msg error! Type: MagmaDPDisconnectedError, Reason: 
```

**Comment by pshelar** [comment]
I have seen flakiness in this test, I did not capture entire log but there is assert failure:
```
======================================================================
FAIL: Adds 2 policies to subscriber, verifies that EnforcementStatsController
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py", line 419, in test_enforcement_stats_restart
    num_pkts_tx_match * len(packet1))
AssertionError: 8704 != 4352
```
