### ISSUE TITLE
Orchestrator creates cyclic dependencies between Security Groups

### ISSUE THREAD

**Issue by arunuke** [magma/magma#5150]
Problem:
Orchestrator creates a number of Security Groups that determine access privileges for various services. Two of the Security Groups, orc8r-eks_worker_sg and orc8r-eks_cluster_sg, have a cyclic dependency on each other. This causes any automatic security group deletion to fail since these two security groups are dependent on each other.

Workaround:
The workaround used today is to manually or automatically remove the dependencies. The preferred solution would be to not have any cyclic dependencies, but independently defined Security Groups that are added to create composite Security Groups.

Resolution:
Security Groups for all nodes in the cluster will continue to have a rule that allows worker pods to receive communication from the cluster control plane. In other words, orc8r-eks_worker_sg can be unchanged.

EKS Cluster security group will include a newly defined entry that allows worker pods to communicate with EKS API instead of the current circular dependency.

Notes:
Looking at orc8r-eks_worker_sg's snipped output, it includes another UserIdGroupPair.

```
cloudstrapper:~/magma-experimental/Sydney/terraform #aws ec2 describe-security-groups --group-ids sg-084a89fc85a9efd02

 {
              "Description": "Security group for all nodes in the cluster.",      
                    "FromPort": 1025,
                    "IpProtocol": "tcp",
                    "IpRanges": [],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "ToPort": 65535,
                    "UserIdGroupPairs": [
                        {
                            "Description": "Allow workers pods to receive communication from the cluster control plane.",
                            "GroupId": "sg-0bdd3a965cb5daf5b",
                            "UserId": "007606123670"
                        }
                    ]
                },
```

Exploring that UserIdGroupPair, the aforesaid Security Group is included as an UserIdGroupPair

```
cloudstrapper:~/magma-experimental/Sydney/terraform #aws ec2 describe-security-groups --group-ids sg-0bdd3a965cb5daf5b

 "UserIdGroupPairs": [
          "Description": "EKS cluster security group.",
                        {
                            "Description": "Allow pods to communicate with the EKS cluster API.",
                            "GroupId": "sg-084a89fc85a9efd02",
                            "UserId": "007606123670"
                        }
                    ]
```

**Comment by karthiksubraveti** [comment]
C
