### ISSUE TITLE
[AGW] Make magma run on baremetal Ubuntu 20.04

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#5159]

**Comment by jeremy-donson** [comment]
Should I set up agw on bare metal using debian first?

Debian first, or starting from scratch with local baremetal ubuntu?

Is this 100% local with the AGW hardware I was shipped?

**Comment by tmdzk** [comment]
Let's first make the install work on Ubuntu Vagrant VM and then we can talk about it.
