### ISSUE TITLE
[NMS][helm] Why are we using latest tag on nginx image for NMS Proxy?

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#5194]
Why are we using `latest` tag on `nginx` image for `nms-nginx-proxy` deployment, can't this lead to some incompatibility issues?
https://github.com/magma/magma/blob/v1.4/orc8r/cloud/helm/orc8r/charts/nms/values.yaml#L89

**Comment by karthiksubraveti** [comment]
@ShubhamTatvamasi  Let's move this github discussions.

**Comment by ShubhamTatvamasi** [comment]
https://github.com/magma/magma/discussions/5197
