### ISSUE TITLE
APN DL/UL AMBR incorrectly sent to UE during default bearer activation

### ISSUE THREAD

**Issue by eduardoefb** [magma/magma#5216]
### Your Environment

- **Version:**  AGW: 1.3.3-1612205679-45140093
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

**To Reproduce**
1. Create an APN with AMBR values, for example: 5Mbps UL/DL (or any other value different of 200Mbps / 8460 kbps) and change the UE test to have only this APN;
2. Establish a PDN context wit UE ;

**Expected behavior**
APN AMBR sent to UE must follow the same values as configured in APN

**Screenshots**
See attached files

**Additional context**

subscriber outpu in AGW:

```bash
root@agw01:/var/www/html/pcap# subscriber_cli.py get IMSI724170000000001
sid {
  id: "724170000000001"
}
lte {
  state: ACTIVE
  auth_key: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001"
  auth_opc: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001"
}
network_id {
  id: "samplenet"
}
state {
  lte_auth_next_seq: 1
}
sub_profile: "1M"
non_3gpp {
  apn_config {
    service_selection: "samplenet.net"
    qos_profile {
      class_id: 9
      priority_level: 15
      preemption_capability: true
    }
    ambr {
      max_bandwidth_ul: 5000000
      max_bandwidth_dl: 5000000
    }
  }
}


```

**Comment by eduardoefb** [comment]
[subscriber_test.pcap.zip](https://github.com/magma/magma/files/6056965/subscriber_test.pcap.zip)
tcpdump file with the messages.

**Comment by eduardoefb** [comment]
![apn_ambr_image](https://user-images.githubusercontent.com/19366248/109422648-2e71fe80-79bb-11eb-9d66-2bc57d5e3695.png)
APN AMBR,  unexpected behavior

**Comment by eduardoefb** [comment]
![default_ambr_image](https://user-images.githubusercontent.com/19366248/109422656-3f227480-79bb-11eb-9e67-1658d32e2c75.png)
UE AMBR (expected behavior)

**Comment by karthiksubraveti** [comment]
@andreilee  do you know what might be happening here
