### ISSUE TITLE
install_gateway.sh feg not copying all config files

### ISSUE THREAD

**Issue by uri200** [magma/magma#5229]
Per the comment here 

https://magmacore.slack.com/archives/G01N7ABCL6M/p1614029435002800?thread_ts=1613955524.002300&cid=G01N7ABCL6M

`install_gateway.sh feg` is failing to copy all the config files into `/etc/magma` folder

As a side note,  config files can be found at `/etc/magma`. Folder `/var/opt/magma/config` is were override configurations are dropped. Normally we place there `control_proxy.yml` so it is not modified when we install a new version (which overwrites `/etc/magma`). 
The content at /var/opt/magma/config` takes precedence over `/etc/magma`

**Comment by uri200** [comment]
this issue can be related with this too 
https://github.com/magma/magma/issues/4950

**Comment by jrmejiaa** [comment]
this issue is related to #5196

**Comment by artblee** [comment]
the mount 
            {
                "Type": "bind",
                "Source": "/var/opt/magma/configs",
                "Destination": "/etc/magma",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },

might need to be 
            {
                "Type": "bind",
                "Source": "/var/opt/magma/configs",
                "Destination": "/etc/magma/configs",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },

**Comment by uri200** [comment]
lets track this issue here #4950
