### ISSUE TITLE
Orc8r : Create one ELK record per user session which encapsulates session_start, update(future) and termination events

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#5245]
Currently AGW generates events 
session_start : when the user session starts 
session_terminate: when the user session terminates.

( In the future, there can also be an intermediate session_update event which will capture the interim information for the session )

As of now each event on AGW generates separate records in elastic search for the same session. One for session start and another for session termination.

With some config changes on the fluentbit and a minor code change, we can generate one record per user session. 
So one record in elk will have both start and terminate information and any further update information in the future.

The document id (__id) can be the user session id in ELK so that the same record is update for any further events for the same session.

**Comment by karthiksubraveti** [comment]
@sourabh-nanoti Trying to understand, why we want to change this ? Can't the client code deal with merging this information ?
