### ISSUE TITLE
[AGW] Possible router's arp table poisoning on multi apn scenario.

### ISSUE THREAD

**Issue by edaspb** [magma/magma#5263]
### Your Environment

- **Version: 1.3.3-1612205679-45140093
- **Affected Component: Access Gateway
- **Affected Subcomponent: Pipelined
- **Deployment Environment local docker-compose (orc8r), bare-metal (AGW)

### Describe the Issue

Multi apn scenario, dhcp forwarder (helper) on router's SVI interface.

SVI config, cisco router

interface Vlan1985
 description LTE_DATA
 ip dhcp relay information trusted
 ip address 10.231.1.1 255.255.255.0
 ip helper-address 10.202.7.162
end

Looks like on the moment of dhcp request arp table of the router can be poisoned with mac generated from IMSI.

Arp table after CPE attachment:
```
Router#sh ip arp vlan 1985
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.231.1.5              5   8ea0.e92f.6741  ARPA   Vlan1985
```
8ea0.e92f.6741 - gtp_br0 mac.
Traffic is passing thru, everything works good.

Waiting dchp renew and:

```
Router#sh ip arp vlan 1985
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.231.1.5              0   8aa2.fb40.5804  ARPA   Vlan1985
```
8aa2.fb40.5804 - Mac generated by mobilityd from IMSI
Traffic is not passing.

**To Reproduce**
1. Configure multi apn
2. Wait dhcp renew
3. check ip arp table

**Comment by pshelar** [comment]
@sudhikan Have you seen this issue ?

**Comment by sudhikan** [comment]
I have not seen this issue... but I tried to recreate this in the lab and still was not able to reproduce. I dropped the lease time to 10 minutes so renewal would be around the 5 minute mark. 

Here is the [continuous ping](https://gist.github.com/sudhikan/03081b28f258578238b67d3b060776e7) from my DHCP server towards the emulated client. Somewhere in there I do an arp lookup to make sure the mac address is that of the grp_br0 interface. I did this APR lookup after at least one renewal.

pcap with the renewals attached. I ran the experiment for 15 minutes so saw two renewals. 

MAC address shouldn't change right for the subscriber? 
[dhcp_renew_fwa_non_nat.pcapng.zip](https://github.com/magma/magma/files/6072255/dhcp_renew_fwa_non_nat.pcapng.zip)

**Comment by edaspb** [comment]
It can be router model or firmware specific.

**Comment by sudhikan** [comment]
@edaspb I am using a Nexus9K in my lab ... but even without that, going through pfsense I didn't see any issues.

**Comment by edaspb** [comment]
@sudhikan My theory is that my router uses mac/ip pairs from dhcp server respond and actualize ip arp table with that info. Why it does it that is the question. Router is old cisco 6513

**Comment by sudhikan** [comment]
Not sure I fully follow your topology... do you know what what mac address is (`8aa2.fb40.5804`)?

**Comment by edaspb** [comment]
@sudhikan yes, it is the mac generated from IMSI, It is not from any physical interface.
This mac is using for asking dhcp server which ip assign to CPE.
Dhcp server respond with ip 10.231.1.5 and looks like router substitute magma's mac with dhcp response frame destination mac.

**Comment by sudhikan** [comment]
@edaspb Understood ... In your testing, was the UE doing any traffic? In my environment, I did the DHCP renew while the UE was sending/receiving traffic?

**Comment by edaspb** [comment]
@sudhikan Yes, I did a tests: Regardless of traffic arp change happens. I also made a tests with cisco IOS 15 FW, the same behavior. I'm still looking for specific IOS feature which does this ip-arp change. I hope it can be disabled.

**Comment by sudhikan** [comment]
So I have a theory. 

In my lab the DHCP server and the upstream gateway are two different network elements. The DHCP server always sees the IMSI hash mac address per user but never sees any user traffic. 

The upstream switch on the other hand will not see the UE in the mac table until a downlink packet arrives or an Upink packet from the UE arrives at the switch. For the very first Downlink packet (assuming no entry in the mac table), the switch is forced to do an arp request and at that time gtp_br0 will respond accordingly. 

I maybe wrong here but one corner case is UE in idle mode, DHCP Renewal happens, ARP tables get updated, and downlink packet is coming without any uplink messaging from the UE causing mac table to be not correct. Ideally, this would force a downlink data notification and a paging action towards the UE I think ... but because the upstream switch doesn't know where the packet needs to go, that procedure isn't being triggered?  

do you think this could be the scenario that you are seeing?

**Comment by edaspb** [comment]
@sudhikan, I've tested today a scheme with two network elements, one for gateway and another one for DHCP/relay. It works as you sad. If one device serve as a relay and another as a data traffic forwarder everything run well. It can be a workaround an issue (if it is not my misconfiguration). 
Regarding dhcp and UE in idle mode it was my thought too. But I found out that even with CPE in active state with traffic alive arp poisoning happens on some routers. I've tested it with cisco 7600 and cisco 6500 with few IOS. I believe that is some sort of cisco specific protection mechanism on work.

**Comment by sudhikan** [comment]
Thanks for confirming!!

**Comment by edaspb** [comment]
Today I've made tests with cisco 4900 switch and it doesn't actualize arp table base on dhcp packets.

**Comment by pshelar** [comment]
document this.
