### ISSUE TITLE
[MME][Core] crash in _s6a_handle_authentication_info_ans

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#5287]
Might be related to recent changes for inbound roaming

====================core-1614755049-ITTI
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e88deff125 in send_msg_to_task (task_zmq_ctx_p=0x55e88e9dfea0 <s6a_task_zmq_ctx>, destination_task_id=TASK_MME_APP, message=0x60d00007f870)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/itti/intertask_interface.c:121
121	  AssertFatal(
[Current thread is 1 (Thread 0x7f471fdee700 (LWP 5980))]
#0  0x000055e88deff125 in send_msg_to_task (task_zmq_ctx_p=0x55e88e9dfea0 <s6a_task_zmq_ctx>, destination_task_id=TASK_MME_APP, message=0x60d00007f870)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/itti/intertask_interface.c:121
#1  0x000055e88dd9cfde in _s6a_handle_authentication_info_ans (imsi="001010000000089", imsi_length=15 '\017', status=..., response=...)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/s6a_proxy/s6a_client_api.cpp:104
#2  0x000055e88dd9d0b7 in <lambda(grpc::Status, magma::feg::AuthenticationInformationAnswer)>::operator()(grpc::Status, magma::feg::AuthenticationInformationAnswer) const (
    __closure=0x6040004d24d0, status=..., response=...) at /home/vagrant/magma/lte/gateway/c/oai/lib/s6a_proxy/s6a_client_api.cpp:119
#3  0x000055e88dd9de4b in std::_Function_handler<void(grpc::Status, magma::feg::AuthenticationInformationAnswer), s6a_authentication_info_req(const s6a_auth_info_req_t*)::<lambda(grpc::Status, magma::feg::AuthenticationInformationAnswer)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/vagrant/build/c/oai/oai_mme/mme, CU 0x1632e48, DIE 0x165d12a>, <unknown type in /home/vagrant/build/c/oai/oai_mme/mme, CU 0x1632e48, DIE 0x165d1b2>) (__functor=..., 
    __args#0=<unknown type in /home/vagrant/build/c/oai/oai_mme/mme, CU 0x1632e48, DIE 0x165d12a>, 
    __args#1=<unknown type in /home/vagrant/build/c/oai/oai_mme/mme, CU 0x1632e48, DIE 0x165d1b2>) at /usr/include/c++/6/functional:1731
#4  0x000055e88dda2c47 in std::function<void (grpc::Status, magma::feg::AuthenticationInformationAnswer)>::operator()(grpc::Status, magma::feg::AuthenticationInformationAnswer) const
    (this=0x61600022ec88, __args#0=..., __args#1=...) at /usr/include/c++/6/functional:2127
#5  0x000055e88dda2a06 in magma::AsyncLocalResponse<magma::feg::AuthenticationInformationAnswer>::handle_response (this=0x61600022ec80)
    at /home/vagrant/build/c/magma_common/async_grpc/GRPCReceiver.h:126
#6  0x000055e88de8ebde in magma::GRPCReceiver::rpc_response_loop (this=0x55e88e9d72c0 <magma::S6aClient::get_instance()::client_instance>)
    at /home/vagrant/magma/orc8r/gateway/c/common/async_grpc/GRPCReceiver.cpp:30
#7  0x000055e88dd9f645 in magma::S6aClient::<lambda()>::operator()(void) const (__closure=0x60200000f978) at /home/vagrant/magma/lte/gateway/c/oai/lib/s6a_proxy/S6aClient.cpp:113
#8  0x000055e88dda0396 in std::_Bind_simple<magma::S6aClient::S6aClient()::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (this=0x60200000f978) at /usr/include/c++/6/functional:1391
#9  0x000055e88dda0333 in std::_Bind_simple<magma::S6aClient::S6aClient()::<lambda()>()>::operator()(void) (this=0x60200000f978) at /usr/include/c++/6/functional:1380
#10 0x000055e88dda0312 in std::thread::_State_impl<std::_Bind_simple<magma::S6aClient::S6aClient()::<lambda()>()> >::_M_run(void) (this=0x60200000f970)
    at /usr/include/c++/6/thread:197
#11 0x00007f47383eae6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f473c5024a4 in start_thread (arg=0x7f471fdee700) at pthread_create.c:456
#13 0x00007f4737b5fd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by talkhasib** [comment]
Core is here
https://drive.google.com/drive/folders/1UYImcd-o1LF6YKI80T4FQNPiUAh1j6C1?ths=true

**Comment by ssanadhya** [comment]
@uri200 @talkhasib this looks similar to an older issue https://github.com/magma/magma/issues/4891, I have not looked into the older issue yet.

**Comment by uri200** [comment]
Added the core to public google drive so @pruthvihebbani can take a look

https://drive.google.com/drive/u/1/folders/1YVU3FUMInQFJJ-JSgcFnsihme_Ztu3n8?ths=true
