### ISSUE TITLE
Problem in S1AP-only test with 200 UEs

### ISSUE THREAD

**Issue by chenhao5651** [magma/magma#531]
I want to test magma with 200 simulative UEs，but the test frame can only support 32 UEs. I compiled the libtfw.so from  rashmi_oai_epc project. After replacing the libtfw.so, the  test frame seems igore the attach accept massage from agw. Did the magma project modfiy the rashmi_oai_epc code to adapt the agw?

**Comment by rsarwad** [comment]
Hi, 
rashmi_oai_epc was created 2 years back from https://github.com/Telecominfraproject/TelecomInfraSWStack and is not updated. So you can refer the latest code from master branch. 
I verified the 225 UEs on latest master code base of AGW and S1ap-simulator (TelecomInfraSWStack). It works fine.

**Comment by ssanadhya** [comment]
@chenhao5651, the test framework is not limited to 32 UEs. Can you try setting num_ues to 200 in test_attach_detach.py and re-running with `make integ_test TESTS=s1aptests/test_attach_detach.py` as described in https://facebookincubator.github.io/magma/docs/lte/s1ap_tests? 
You will also need to comment out the detach request in line 48, for all UEs to stay attached.

**Comment by chenhao5651** [comment]
> Hi,
> rashmi_oai_epc was created 2 years back from https://github.com/Telecominfraproject/TelecomInfraSWStack and is not updated. So you can refer the latest code from master branch.
> I verified the 225 UEs on latest master code base of AGW and S1ap-simulator (TelecomInfraSWStack). It works fine.

Thanks for repley. It dose work after I update the agw code. The test_attach_detach_multi_ue test case seems unstable. Sometimes ,it fails with no subscribers, like
"subscriberdb[1869]: WARNING:root:Subscriber not found: IMSI001010000000184"

**Comment by chenhao5651** [comment]
> Hi,
> rashmi_oai_epc was created 2 years back from https://github.com/Telecominfraproject/TelecomInfraSWStack and is not updated. So you can refer the latest code from master branch.
> I verified the 225 UEs on latest master code base of AGW and S1ap-simulator (TelecomInfraSWStack). It works fine.
