### ISSUE TITLE
[MME] Address Clang-Tidy clang-analyzer-unix.Malloc findings

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5333]
This GH Issue is to investigate the clang-analyzer-unix.Malloc findings from Clang-Tidy. Analysis was run on Magma @ [6c13c49](https://github.com/magma/magma/commit/9cc4be1e362e4cd0171be2bfcb47a054d6c13c49).

These are all of the shape `warning: Potential leak to memory pointed to by...`.

This is a result of #5302 execution of Clang-Tidy.

To keep track of the findings and status of each, here is a checklist which will tie to PRs:

- [ ] bstrlib.c:2465
- [ ] bstrlib.c:3161
- [ ] obj_hashtable.c:1018 [#5802]
- [ ] obj_hashtable.c:1053 [#5802]
- [ ] obj_hashtable_uint64.c:998 [#5801]
- [ ] mme_app_edns_emulation.c:63 [#5730]
- [ ] mme_app_state_manager.cpp:235
- [ ] s1ap_mme_handlers.c:1271

As these findings tend to be long (the static analyzer indicates the precise path through the codebase required for the leak) I will point at full logs and not quote them here.

Full logs from the above are available in [This](https://gist.github.com/electronjoe/987d20e3e730d0a22ce184644c70b449) Github Gist.

**Comment by anushadatar** [comment]
@electronjoe  Added two more quick PRs - let me know what you think! If they're on the right track, I'll investigate the rest and push similar updates if they are needed.
