### ISSUE TITLE
[MME] Address Clang-Tidy clang-analyzer-deadcode.DeadStores findings

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5364]
This GH Issue is to investigate the clang-analyzer-deadcode.DeadStores findings from Clang-Tidy. Analysis was run on Magma @ [6c13c49](https://github.com/magma/magma/commit/9cc4be1e362e4cd0171be2bfcb47a054d6c13c49).

These are all of the shape `warning: Value stored to 'cause_value' is never read`.

This is a result of #5302 execution of Clang-Tidy.

To keep track of the findings and status of each, here is a checklist which will tie to PRs:

- [ ] async_system.c:66 `rc`
- [ ] async_system.c:139 `rv`
- [ ] shared_ts_log.c:299 `rv`
- [ ] itti_free_defined_msg.c:76 `mme_app_est_cnf`
- [ ] log.c:88 `hash_rc`
- [ ] log.c:889 `rv`
- [ ] log.c:1117 `hash_rc`
- [ ] log.c:1138 `rv`
- [ ] log.c:1217 `hash_rc`
- [ ] log.c:1249 `hash_rc`
- [ ] utf8util.c:64 `ret`
- [ ] utf8util.c:159 `ofs`
- [ ] bstrlib.c:2541 `ret`
- [ ] bstrlib.c:2615 `ret`, `p` and `i`
- [ ] bstrlib.c:2616 `i`
- [ ] mme_app_bearer.c:273 `emm_context`
- [ ] mme_app_bearer.c:314 `rc`
- [ ] mme_app_bearer.c:364 `rc`
- [ ] mme_app_bearer.c:496 `rc`
- [ ] mme_app_context.c `h_rc`
- [ ] mme_app_context.c:556 `h_rc`
- [ ] mme_app_context.c:584 `h_rc`
- [ ] mme_app_context.c:605 `h_rc`
- [ ] mme_app_context.c:642 `h_rc`
- [ ] mme_app_itti_messaging.c:435 `uetimezone`
- [ ] mme_app_state_manager.cpp:102 `rc`
- [ ] nas_proc.c:655 `cs_location_updt_fail`
- [ ] AttachRequest.c:41 `decode_result`
- [ ] AttachRequest.c:47 `decode_result`
- [ ] Detach.c:410 `rc`
- [ ] Authentication.c:495 `rc`
- [ ] Authentication.c:609 `emm_cause`
- [ ] Authentication.c:702 `rc`
- [ ] Authentication.c:784 `rc`
- [ ] Authentication.c:1145 `rc`
- [ ] emm_data_ctx.c:726 `h_rc`
- [ ] Attach.c:373 `rc`
- [ ] Attach.c:376 `clear_emm_ctxt`
- [ ] Attach.c:643 `rc`
- [ ] TrackingAreaUpdate.c:211 `emm_context`
- [ ] EmmCommonProcedureInitiated.c:101 `rc`
- [ ] EmmCommonProcedureInitiated.c:152 `rc`
- [ ] EmmCommonProcedureInitiated.c:302 `rc`
- [ ] EmmCommonProcedureInitiated.c:316 `rc`
- [ ] EmmCommonProcedureInitiated.c:335 `rc`
- [ ] EmmDeregistered.c:135 `rc`
- [ ] EmmDeregistered.c:270 `rc`
- [ ] EmmDeregisteredInitiated.c:204 `rc`
- [ ] EmmDeregisteredInitiated.c:223 `rc`
- [ ] DedicatedEpsBearerContextActivation.c:430 `rc`
- [ ] EpsBearerContextDeactivation.c:423 `rc`
- [ ] s1ap_mme_encoder.c:117 `res`
- [ ] s1ap_mme_encoder.c:151 `res`
- [ ] s1ap_mme_handlers.c:1264 `cause_type`
- [ ] s1ap_mme_handlers.c:1265 `cause_value`
- [ ] s1ap_mme_handlers.c:1478 `ue_ref_p`
- [ ] s1ap_mme_handlers.c:1803 `cause_value`
- [ ] s1ap_mme_handlers.c:2850 `ue_ref_p`
- [ ] s1ap_mme_handlers.c:3111 `is_tai_found`
- [ ] s1ap_mme_handlers.c:3419 `ue_ref_p`

Full logs from the above are available in [This](https://gist.github.com/electronjoe/987d20e3e730d0a22ce184644c70b449) Github Gist.

**Comment by waqaraqeel** [comment]
Here is an updated checklist from analysis run on Magma @ [81025e8](https://github.com/magma/magma/commit/81025e8e10ad24a8831cde8e0e2d217e52024c8c)

- [ ] async_system.c:64 `rc`
- [ ] async_system.c:137 `rv`
- [ ] itti_free_defined_msg.c:76 `mme_app_est_cnf`
- [ ] shared_ts_log.c:297 `rv`
- [ ] log.c:896 `hash_rc`
- [ ] log.c:904 `rv`
- [ ] log.c:1132 `hash_rc`
- [ ] log.c:1153 `rv`
- [ ] log.c:1232 `hash_rc`
- [ ] log.c:1269 `hash_rc`
- [ ] bstrlib.c:2541 `ret`
- [ ] bstrlib.c:2615 `ret`
- [ ] bstrlib.c:2615 `p`
- [ ] bstrlib.c:2615 `i`
- [ ] bstrlib.c:2616 `i`
- [ ] utf8util.c:64 `ret`
- [ ] utf8util.c:159 `ofs`
- [ ] NwGtpv2cTrxn.c:149 `rc`
- [ ] NwGtpv2cTrxn.c:372 `rc`
- [ ] NwGtpv2cMsg.c:621 `pIeValue`
- [ ] gtpv2c_ie_formatter.c:935 `rc`
- [ ] gtpv2c_ie_formatter.c:942 `rc`
- [ ] gtpv2c_ie_formatter.c:1020 `rc`
- [ ] itti_free_defined_msg.c:76 `mme_app_est_cnf`
- [ ] mme_app_context.c:423 `h_rc`
- [ ] mme_app_context.c:453 `h_rc`
- [ ] mme_app_context.c:481 `h_rc`
- [ ] mme_app_context.c:502 `h_rc`
- [ ] mme_app_context.c:539 `h_rc`
- [ ] mme_app_bearer.c:295 `emm_context`
- [ ] mme_app_bearer.c:336 `rc`
- [ ] mme_app_bearer.c:386 `rc`
- [ ] mme_app_bearer.c:529 `rc`
- [ ] mme_app_bearer.c:3440 `e_rab_admitted_list`
- [ ] mme_app_itti_messaging.c:499 `uetimezone`
- [ ] nas_proc.c:657 `cs_location_updt_fail`
- [ ] AttachRequest.c:41 `decoded_result`
- [ ] AttachRequest.c:47 `decoded_result`
- [ ] Authentication.c:497 `rc`
- [ ] Authentication.c:615 `emm_cause`
- [ ] Authentication.c:708 `rc`
- [ ] Authentication.c:790 `rc`
- [ ] Authentication.c:1177 `rc`
- [ ] Detach.c:411 `rc`
- [ ] emm_data_ctx.c:726 `h_rc`
- [ ] Attach.c:377 `rc`
- [ ] Attach.c:380 `clear_emm_ctxt`
- [ ] Attach.c:658 `rc`
- [ ] TrackingAreaUpdate.c:210 `emm_context`
- [ ] EmmCommonProcedureInitiated.c:101 `rc`
- [ ] EmmCommonProcedureInitiated.c:152 `rc`
- [ ] EmmCommonProcedureInitiated.c:302 `rc`
- [ ] EmmCommonProcedureInitiated.c:316 `rc`
- [ ] EmmCommonProcedureInitiated.c:335 `rc`
- [ ] EmmDeregistered.c:135 `rc`
- [ ] EmmDeregistered.c:270 `rc`
- [ ] EmmDeregisteredInitiated.c:204 `rc`
- [ ] EmmDeregisteredInitiated.c:223 `rc`
- [ ] DedicatedEpsBearerContextActivation.c:440 `rc`
- [ ] EpsBearerContextDeactivation.c:433 `rc`
- [ ] M5GPDUSessionModificationRequest.cpp:58 `decoded`
- [ ] SmfMessage.cpp:143 `encode_result`
- [ ] s1ap_mme_encoder.c:118 `res`
- [ ] s1ap_mme_encoder.c:152 `res`
- [ ] s1ap_mme_handlers.c:1319 `cause_type`
- [ ] s1ap_mme_handlers.c:1320 `cause_value`
- [ ] s1ap_mme_handlers.c:1537 `ue_ref_p`
- [ ] s1ap_mme_handlers.c:2662 `cause`
- [ ] s1ap_mme_handlers.c:4308 `ue_ref_p`
- [ ] s1ap_mme_handlers.c:4569 `is_tai_found`
- [ ] s1ap_mme_handlers.c:5144 `ue_ref_p`
- [ ] NativeInteger_oer.c:19 `rval`
- [ ] INTEGER.c:1401 `pstart`
- [ ] oer_support.c:79 `sp`
- [ ] per_support.c:458 `bytes`
- [ ] ngap_amf_handlers.c:1177 `ue_ref_p`
- [ ] NativeInteger_oer.c:19 `rval`
- [ ] INTEGER.c:1401 `pstart`
- [ ] oer_support.c:79 `sp`
- [ ] per_support.c:458 `bytes`
- [ ] s6a_hss_reset.c:97 `result_code`
- [ ] s11_mme_bearer_manager.c:64 `rc`
- [ ] s11_mme_bearer_manager.c:211 `rc`
- [ ] s11_mme_bearer_manager.c:234 `rc`
- [ ] s11_mme_bearer_manager.c:307 `rc`
- [ ] s11_mme_bearer_manager.c:364 `rc`
- [ ] s11_mme_session_manager.c:73 `rc`
- [ ] s11_mme_session_manager.c:111 `rc`
- [ ] s11_mme_session_manager.c:306 `rc`
- [ ] s11_mme_session_manager.c:329 `rc`
- [ ] s11_ie_formatter.c:397 `rc`
- [ ] s11_ie_formatter.c:596 `rc`
- [ ] s11_ie_formatter.c:612 `rc`
- [ ] s11_ie_formatter.c:618 `rc`
- [ ] s11_ie_formatter.c:624 `rc`
- [ ] s11_ie_formatter.c:630 `rc`
- [ ] s11_ie_formatter.c:636 `rc`
- [ ] s11_ie_formatter.c:642 `rc`
- [ ] s11_ie_formatter.c:648 `rc`
- [ ] s11_ie_formatter.c:654 `rc`
- [ ] s11_ie_formatter.c:660 `rc`
- [ ] s11_ie_formatter.c:666 `rc`
- [ ] s11_ie_formatter.c:723 `rc`
- [ ] s11_ie_formatter.c:850 `rc`
- [ ] s11_ie_formatter.c:866 `rc`
- [ ] s11_ie_formatter.c:872 `rc`
- [ ] s11_ie_formatter.c:1059 `rc`
- [ ] s11_ie_formatter.c:1159 `rc`
- [ ] s11_ie_formatter.c:1287 `rc`
- [ ] s11_ie_formatter.c:1335 `rc`
- [ ] s11_ie_formatter.c:1653 `current`

Full logs are available [here](https://gist.github.com/waqaraqeel/217dc75015e307c7053daa145c922f5a)
