### ISSUE TITLE
How to update the .env file after pushing the images to my private docker registry.

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#537]
Error response from daemon: login attempt to https://id.docker.com/v2/ failed with status: 404 Not Found
After running the command sudo ./install_gateway.sh feg the above error is coming
after entering the docker hub username and password i have created my private docker
registry and pushed the image to my private Docker registry after that i have updated the .env file as well but how to change the https://id.docker.com/v2/ address or remove v2 and add the whole address of my registry so that installation can be successful.

**Comment by shoaibbutt50** [comment]
Error is different when in .env file magmad_ is replaced with my private registry name.
Logging into docker registry at shoaibfeg
Username: 
Password: 
Error response from daemon: Get https://shoaibfeg/v2/: dial tcp: lookup shoaibfeg: no such host

**Comment by shoaibbutt50** [comment]
Anyone here pls guide who has already successfully installed FEG gateway using docker.

**Comment by shoaibbutt50** [comment]
@mpgermano any update for the above mentioned issue.

**Comment by mpgermano** [comment]
Can you please paste your .env file that you are using to install with?

**Comment by shoaibbutt50** [comment]
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

COMPOSE_PROJECT_NAME=magmad
DOCKER_REGISTRY=shoaibfeg
IMAGE_VERSION=latest
BUILD_CONTEXT=../../../

ROOTCA_PATH=../../../.cache/test_certs/rootCA.pem
CONTROL_PROXY_PATH=../configs/control_proxy.yml
SNOWFLAKE_PATH=../../../.cache/orc8r/gateway/snowflake

CERTS_VOLUME=gwcerts
CONFIGS_VOLUME=gwconfigs

**Comment by shoaibbutt50** [comment]
This is the .env file i am using to install.

**Comment by shoaibbutt50** [comment]
The path of the file is /magma/orc8r/tools/docker

**Comment by mpgermano** [comment]
The docker daemon cannot connect to the registry at `https://shoaibfeg/v2/`. Please ensure you specify the full registry address, ending with a `/`

**Comment by shoaibbutt50** [comment]
i have also tried that the full registry address should be pasted here ?
DOCKER_REGISTRY=**shoaibfeg**

**Comment by shoaibbutt50** [comment]
Now this error is coming
**Logging into docker registry at https://cloud.docker.com/u/shoaibbutt50/repository/docker/shoaibbutt50/shoaibfeg/
Username: shoaibbutt50
Password: 
Error response from daemon: login attempt to https://cloud.docker.com/v2/ failed with status: 404 Not Found**

**Comment by shoaibbutt50** [comment]
How to remove the v2 from this address https://cloud.docker.com**/v2/**

**Comment by shoaibbutt50** [comment]
when i am running the command to resolve the address **wget https://cloud.docker.com/u/shoaibbutt50/repository/docker/shoaibbutt50/shoaibfeg/** it is resolved successfully
--2019-08-14 09:31:30--  https://cloud.docker.com/u/shoaibbutt50/repository/docker/shoaibbutt50/shoaibfeg/
Resolving cloud.docker.com (cloud.docker.com)... 34.234.47.50, 3.223.74.179, 3.225.142.245
Connecting to cloud.docker.com (cloud.docker.com)|34.234.47.50|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /sso/start?next=%2Fu%2Fshoaibbutt50%2Frepository%2Fdocker%2Fshoaibbutt50%2Fshoaibfeg%2F [following]
--2019-08-14 09:31:31--  https://cloud.docker.com/sso/start?next=%2Fu%2Fshoaibbutt50%2Frepository%2Fdocker%2Fshoaibbutt50%2Fshoaibfeg%2F
Reusing existing connection to cloud.docker.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://id.docker.com/id/oauth/authorize/?client_id=b1e4e661-9fec-4e9e-a611-b4b665c3eb03&next=%2Fu%2Fshoaibbutt50%2Frepository%2Fdocker%2Fshoaibbutt50%2Fshoaibfeg%2F&nonce=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ&redirect_uri=https%3A%2F%2Fcloud.docker.com%2Fsso%2Fcallback&response_type=code&scope=openid&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ [following]
--2019-08-14 09:31:31--  https://id.docker.com/id/oauth/authorize/?client_id=b1e4e661-9fec-4e9e-a611-b4b665c3eb03&next=%2Fu%2Fshoaibbutt50%2Frepository%2Fdocker%2Fshoaibbutt50%2Fshoaibfeg%2F&nonce=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ&redirect_uri=https%3A%2F%2Fcloud.docker.com%2Fsso%2Fcallback&response_type=code&scope=openid&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ
Resolving id.docker.com (id.docker.com)... 3.223.74.179, 34.234.47.50, 3.225.142.245
Connecting to id.docker.com (id.docker.com)|3.223.74.179|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /login/?next=%2Fid%2Foauth%2Fauthorize%2F%3Fclient_id%3Db1e4e661-9fec-4e9e-a611-b4b665c3eb03%26next%3D%252Fu%252Fshoaibbutt50%252Frepository%252Fdocker%252Fshoaibbutt50%252Fshoaibfeg%252F%26nonce%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ%26redirect_uri%3Dhttps%253A%252F%252Fcloud.docker.com%252Fsso%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%26state%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ [following]
--2019-08-14 09:31:32--  https://id.docker.com/login/?next=%2Fid%2Foauth%2Fauthorize%2F%3Fclient_id%3Db1e4e661-9fec-4e9e-a611-b4b665c3eb03%26next%3D%252Fu%252Fshoaibbutt50%252Frepository%252Fdocker%252Fshoaibbutt50%252Fshoaibfeg%252F%26nonce%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ%26redirect_uri%3Dhttps%253A%252F%252Fcloud.docker.com%252Fsso%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%26state%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiMWU0ZTY2MS05ZmVjLTRlOWUtYTYxMS1iNGI2NjVjM2ViMDMiLCJleHAiOjE1NjU3NjA5OTEsImlhdCI6MTU2NTc2MDY5MSwicmZwIjoiT0xBc25DN01oUTBqOTVZNDVZUDBXUT09IiwidGFyZ2V0X2xpbmtfdXJpIjoiL3Uvc2hvYWliYnV0dDUwL3JlcG9zaXRvcnkvZG9ja2VyL3Nob2FpYmJ1dHQ1MC9zaG9haWJmZWcvIn0.Q5x-KjU6C4aFx7LqgTypJMyc5OaH4fAcTUQgxiulEEQ
Reusing existing connection to id.docker.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 930 [text/html]
Saving to: ‘index.html’

index.html          100%[===================>]     930  --.-KB/s    in 0s      

2019-08-14 09:31:32 (117 MB/s) - ‘index.html’ saved [930/930]

**Comment by shoaibbutt50** [comment]
but this address is not resolved 
**wget https://cloud.docker.com/v2/** 
--2019-08-14 09:33:41--  https://cloud.docker.com/v2/
Resolving cloud.docker.com (cloud.docker.com)... 3.223.74.179, 34.234.47.50, 3.225.142.245
Connecting to cloud.docker.com (cloud.docker.com)|3.223.74.179|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-14 09:33:42 ERROR 404: Not Found.

**Comment by shoaibbutt50** [comment]
issue is resolved.

**Comment by shoaibbutt50** [comment]
Now this error is received 
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.s6a_proxy.ports contains an invalid type, it should be a number, or an object
services.session_proxy.ports contains an invalid type, it should be a number, or an object
services.session_proxy.ports contains an invalid type, it should be a number, or an object
services.swx_proxy.ports contains an invalid type, it should be a number, or an object
services.session_proxy.ports value [':/', ':/'] has non-unique elements

**Comment by shoaibbutt50** [comment]
@mpgermano how to fix this error now
