### ISSUE TITLE
[orc8r][helm] Refactor orc8r chart to use external-dns

### ISSUE THREAD

**Issue by mattymo** [magma/magma#5383]
### Describe the Issue

The current approach via terraform assumes precreated secrets. That isn't necessarily a bad thing, but it would be even better if these secrets could be generated by cert-manager, instead of shell scripts.

**Expected behavior**
A cloud-native approach should be possible so that helm install orc8r -f myvalues.yaml will cause cert-manager to create the necessary secrets for the certs that are needed for orc8r.

**Comment by mattymo** [comment]
@ShubhamTatvamasi  I can't assign you, but I'm tagging you here

**Comment by ShubhamTatvamasi** [comment]
> @ShubhamTatvamasi I can't assign you, but I'm tagging you here

Okay, Thanks @mattymo

**Comment by karthiksubraveti** [comment]
@mattymo This sounds like a good issue to take on. 
Adding @arunuke for visibility here. @ShubhamTatvamasi were you interested in working on this. I can assign you this issue if you are interested. LMK.

**Comment by ShubhamTatvamasi** [comment]
Yes, Please @karthiksubraveti. I would like to work on this.

**Comment by karthiksubraveti** [comment]
@mattymo The issue title seems to be different from the description, can you change it accordingly ? Thanks

**Comment by ShubhamTatvamasi** [comment]
@mattymo I have made this helm chart for generating secrets.
This is still a work in progress.
Can you please see if I am moving in the right direction?
https://github.com/ShubhamTatvamasi/magma-certs

**Comment by karthiksubraveti** [comment]
cc @hcgatewood

**Comment by hcgatewood** [comment]
Left some comments in Slack. Looks like we're making good progress. I think this will be a solid win for simplifying deploy+operate complexity

**Comment by ShubhamTatvamasi** [comment]
@mattymo I have a question.

Right now we have 3 issuers for signing certificates:
```
➜  magma-certs git:(master) kubectl get issuers
NAME                            READY   AGE
magma-certs-certifier-issuer    True    40s
magma-certs-root-issuer         True    40s
magma-certs-selfsigned-issuer   True    40s
```

And in total 6 certificates:
```
➜  magma-certs git:(master) kubectl get certificate
NAME                                     READY   SECRET                           AGE
magma-certs-admin-operator-certificate   True    magma-certs-admin-operator-tls   4m57s
magma-certs-certifier-certificate        True    magma-certs-certifier-tls        4m57s
magma-certs-controller-certificate       True    magma-certs-controller-tls       4m57s
magma-certs-fluentd-certificate          True    magma-certs-fluentd-tls          4m57s
magma-certs-nms-certificate              True    magma-certs-nms-tls              4m57s
magma-certs-root-certificate             True    magma-certs-root-tls             4m57s
```

And these 3 are self signed certificates:
- certifier-certificate
- fluentd-certificate
- root-certificate


As suggested by @hcgatewood I am trying to make issuers dynamic for signing certificates. Should I just set the issuers in `values.yaml` file for these certificates?
If someone wants to add their own issuer they can add it and update the `values.yaml`, is that fine?
- admin-operator-certificate
- controller-certificate
- nms-certificate


Source: https://github.com/ShubhamTatvamasi/magma-certs

**Comment by ShubhamTatvamasi** [comment]
@mattymo @hcgatewood I have created a **Draft Pull Request** https://github.com/magma/magma/pull/5584 based on your suggestions.
Please give your valuable feedback on this.

P.S. orc8r integration with **certs** helm chart is pending.

**Comment by ShubhamTatvamasi** [comment]
@mattymo @hcgatewood we can now close this issue as https://github.com/magma/magma/pull/5584 PR has been merged.

**Comment by electronjoe** [comment]
Thank you!

Edit: regarding closing issues - I believe if you link a PR to an issue it will auto close on merge (link it by use of right panel in GH PR UI).
