### ISSUE TITLE
[MME] Case statement accidental fall-through in ..context_release_command

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5388]
One of the Clang-Tidy Deadstores findings (#5364) pointed out that the following [case statement fall-through](https://github.com/magma/magma/blob/v1.4/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c#L1262-L1268) results in unused assignments:

```c
    case S1AP_INVALID_MME_UE_S1AP_ID: // rsarwad, 3 months ago: • As part of mme restart, added code to handle …
      cause_type  = S1ap_Cause_PR_radioNetwork;
      cause_value = S1ap_CauseRadioNetwork_unknown_mme_ue_s1ap_id;
    case S1AP_NAS_MME_OFFLOADING: // Ulas Kozat, 3 months ago: • [lte][agw] MME HA task and grpc service addit…
      cause_type  = S1ap_Cause_PR_radioNetwork;
      cause_value = S1ap_CauseRadioNetwork_load_balancing_tau_required;
      break; // rsarwad, 3 months ago: • As part of mme restart, added code to handle …
```

The `cause_type` appears identical in both cases so for S1AP_INVALID_MME_UE_S1AP_ID we are probably OK. But the cause_value is incorrect for S1AP_INVALID_MME_UE_S1AP_ID as it gets overwritten.

**Comment by ulaskozat** [comment]
@electronjoe these are correct. S1AP_NAS_MME_OFFLOADING is a special case where the cause_value here forces UE to reattach to another AGW in HA mode.

**Comment by ulaskozat** [comment]
yes, I got the comment now. there should be a break in the first case statement.

**Comment by electronjoe** [comment]
> yes, I got the comment now. there should be a break in the first case statement.

Sorry about the unclear GH Issue! Working on a PR now.
