### ISSUE TITLE
eNB datarate plots not showing valid data

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#5399]
### Your Environment

- **Version:** 1.3.2 NMS with 1.3.3-1614917907-371c6462 AGW
- **Affected Component:** Access Gateway and/or NMS
- **Affected Subcomponent:** Sessiond and NMS 
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the Issue

When using externally managed eNB, the data rate plot in the NMS does not appear to accurately reflect the data usage on an eNB. This is both in NMS and graphana plots

**To Reproduce**
1. Go to eNB specific view in NMS
2. Attach a single UE to the LTE network
3. Start and downlink iperf3 test, UDP, 5Mbps datarate, duration >>5 min to allow for averaging to converge
4. Observe the data is colored as uplink data
5. observe the y-axis is labeled mb/s and the value of the flat line portion is not equal to 5Mbps (shows 340340.418...)
6. Verify via Wireshark the data flow is actually 5Mbps

**Expected behavior**
NMS plot should be accurate on direction of flow and units / value should be correct.

Also, if it's being touched, we don't need significant digits to 11 decimal places. Maybe 1 or 2 would be closer to real precision. 

**Screenshots**
Included in ZIP:
Screenshot of NMS eNB data rate plot
Log of iperf run showing offered load by perf
Screenshot of wireshark sample showing approx 5.5Mbps
Screenshot of eNB webUI showing 5.44 Mbps
screenshot of graphana plots for the gateway of the tested eNB
[NMS eNB DataRate Plot Wrong.zip](https://github.com/magma/magma/files/6112268/NMS.eNB.DataRate.Plot.Wrong.zip)

**Comment by ymasmoudi** [comment]
This is fixed in 
https://github.com/magma/magma/pull/4440
https://github.com/magma/magma/pull/5003

**Comment by jpad-freedomfi** [comment]
Thank @ymasmoudi ! looks like that does fix the plots value and the inversion. I have tested in our lab. 

If you could back port to 1.3.3 that would be awesome. We can install across WiConnect sites.
