### ISSUE TITLE
[AGW] continuous DHCP requests from mobilityd after ip release procedure in multi apn mode

### ISSUE THREAD

**Issue by edaspb** [magma/magma#5413]
### Your Environment

- **Version: 1.3.3-1614917907-371c6462
- **Affected Component: Access Gateway
- **Affected Subcomponent: Mobilityd
- **Deployment Environment: local docker-compose (orc8r), bare-metal (AGW)

### Describe the Issue

Mobilityd keeps sending dhcp requests after ip release procedure. Long period of time (hours).
Tested with explicit and implicit detach. 
```
journalctl -fu magma@mobilityd
Mar 10 11:48:02 gw2-1 mobilityd[1980]: INFO:root:Allocated IPv4 10.231.1.13 for sid IMSI710700000000004 for apn internet
Mar 10 11:48:16 gw2-1 mobilityd[1980]: INFO:root:Released IPv4 10.231.1.13 for sid IMSI710700000000004
Mar 10 11:52:14 gw2-1 mobilityd[1980]: INFO:mobilityd.dhcp.sniff:Record DHCP for: v1985.8a_a2_fb_40_58_04 state: state: ACK      requested state: REQUEST  mac 8a:a2:fb:40:58:04 ip 10.231.1.13 subnet 10.231.1.0/24 DHCP: 10.231.1.4 router 10.231.1.1 lease time 2021-03-10 12:02:14.604179, renew 2021-03-10 11:57:14.604211 xid 5 vlan 1985
----
Mar 10 12:25:35 gw2-1 mobilityd[1980]: INFO:mobilityd.dhcp.sniff:Record DHCP for: v1985.8a_a2_fb_40_58_04 state: state: ACK      requested state: REQUEST  mac 8a:a2:fb:40:58:04 ip 10.231.1.13 subnet 10.231.1.0/24 DHCP: 10.231.1.4 router 10.231.1.1 lease time 2021-03-10 12:35:35.070448, renew 2021-03-10 12:30:35.070481 xid 5 vlan 1985
Mar 10 12:58:55 gw2-1 mobilityd[1980]: INFO:mobilityd.dhcp.sniff:Record DHCP for: v1985.8a_a2_fb_40_58_04 state: state: ACK      requested state: REQUEST  mac 8a:a2:fb:40:58:04 ip 10.231.1.13 subnet 10.231.1.0/24 DHCP: 10.231.1.4 router 10.231.1.1 lease time 2021-03-10 13:08:55.486283, renew 2021-03-10 13:03:55.486315 xid 5 vlan 1985
```

**To Reproduce**
1. Configure multi apn mode
2. attach/detach UE
3. See `journalctl -fu magma@mobilityd`

**Expected behavior**
Stop sending dhcp request after ip release.

**Comment by sourabh-nanoti** [comment]
The problem seems to be in marking the IP address as REAPED when the _recycle_timer is already running. Since the IP address is never marked as REAPED, it's never released.

**Comment by sourabh-nanoti** [comment]
By working through the code, it seems like this was an issue in 1.3.3 which was fixed by https://github.com/magma/magma/pull/3867 in the later releases. 
cc @pshelar
