### ISSUE TITLE
Export subscribers in .csv file

### ISSUE THREAD

**Issue by avast1268** [magma/magma#5458]
- Version: 1.3
- Affected Component:NMS

### Describe the Feature

**Is your feature request related to a known issue? Please describe.**
Requesting to return the button that has the option to export subscribers in a .csv file in the NMS interface as before the last updates it was possible to both import and export.

**Specify the applicable product use-cases**
Being able to download and work on Subscriber info.

**Describe the solution you'd like**
To be able to have the option of Export .CSV in subscriber level in NMS in addition to import.

**Desired timelines**
Next Release

**Comment by ekowtaylor** [comment]
@karthiksubraveti , @HannaFar is this now supported?

**Comment by karthiksubraveti** [comment]
Yes. We added this support in 1.5 and is mentioned in release notes

**Comment by ekowtaylor** [comment]
Thanks for confirming, will close this then.
