### ISSUE TITLE
[NMS] nms not updating when json is modifed

### ISSUE THREAD

**Issue by uri200** [magma/magma#5471]
### Your Environment

**To Reproduce**
Go to to staging, network  `mpk_dogfooding` network (link below), edit the network in JSON.

Then change
```
"feg_network_id":"mpk_tiplab_feg_wifi"
```
for
```
"feg_network_id":""
```

Save the file and check it is not updated with ""

**Expected behavior**
After that change we should see
```
"feg_network_id":""
```

https://magma-admin.nms-staging.magma.etagecom.io/nms/mpk_dogfooding/network/network

**Comment by uri200** [comment]
The problem is that that network had blank description. Through the API i can see an error message warning of that. But NMS does not return any evident message when that happens 

NMS should return the same message as API so we can understand what went wrong

**Comment by uri200** [comment]
Note this is happening in any element that fails. For example, when I try to update `lte_auth_op`, NMS was showing that changes were saved properly but they were never applied.


![image](https://user-images.githubusercontent.com/16157139/112026597-98318400-8af3-11eb-8a29-899dd77d3bbc.png)

**Comment by uri200** [comment]
the har shows an error, but the gui doesn't (see picture below how nms show network saved succesfully)


[magma-admin.nms-staging.magma.etagecom.io.har.zip](https://github.com/magma/magma/files/6246098/magma-admin.nms-staging.magma.etagecom.io.har.zip)


![image](https://user-images.githubusercontent.com/16157139/113345013-b31ba980-92e6-11eb-9f54-bb1d71fdec61.png)

**Comment by karthiksubraveti** [comment]
unable to reproduce this issue. Most likely issue between magmalte and orc8r
