### ISSUE TITLE
Additional fields in header enrichment

### ISSUE THREAD

**Issue by joary** [magma/magma#5516]
### Describe the Feature

**Is your feature request related to a known issue? Please describe.**
No

**Specify the applicable product use-cases**
This feature is originally from a Federated FWA use-case.

**Describe the solution you'd like**

Add options to include additional fields in the Header Enriched packets. Additional fields include: APN, RAT and ULI. [Existing HE proposal](https://docs.magmacore.org/docs/next/proposals/p007_header_enrichment) only includes MSISDM and IMSI.

**Describe alternatives you've considered**
No known alternatives.

**Additional context**
No other context

**Resources**
No additional resources

**Desired timelines**
H2 2021

**Comment by ekowtaylor** [comment]
@pshelar what are your thoughts about this feature request?

**Comment by pshelar** [comment]
sure, this feature can be targeted for 21Q3.
