### ISSUE TITLE
Traffic Split between S1-U and S1-C

### ISSUE THREAD

**Issue by joary** [magma/magma#5517]
### Describe the Feature

**Is your feature request related to a known issue? Please describe.**
No

**Specify the applicable product use-cases**
This feature is originally from a Federated FWA use-case.

**Describe the solution you'd like**

Split the S1 traffic into user-plane (S1-U) and control-plane (S1-C) traffic. Being able to use different interfaces or different V-LANs for each type of traffic. This allows network administrator to both monitor the control signalling and also apply different network configurations for user and control traffic.

**Describe alternatives you've considered**
No other alternatives were considered

**Additional context**

**Resources**
No additional resources

**Desired timelines**
No desired timeline, low priority.

**Comment by pshelar** [comment]
@joary AGW has configuration for S1-C interface in MME (s1ap_iface_name) and S1-U interface in SPGW (s1u_iface_name) yml file.
once you split the S1 interfaces, you can tag respective interfaces with VLAN you like.
