### ISSUE TITLE
[SessionD] Migrate unit tests to use protoc generate client mocks instead of a manually created server mock

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5531]
### Your Environment (If applicable)

- **Version:** master
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Feature
Currently in a few of SessionD's unit tests, we use a manually constructed GRPC server mocks. 
```
class MockCentralController final : public CentralSessionController::Service {
 public:
  MOCK_METHOD3(
      CreateSession, Status(
                         grpc::ServerContext*, const CreateSessionRequest*,
                         CreateSessionResponse*));

  MOCK_METHOD3(
      UpdateSession, Status(
                         grpc::ServerContext*, const UpdateSessionRequest*,
                         UpdateSessionResponse*));

  MOCK_METHOD3(
      TerminateSession,
      Status(
          grpc::ServerContext*, const SessionTerminateRequest*,
          SessionTerminateResponse*));
};
```
This can be cleaned up by using a protoc generated mock stubs. This will clean up the tests as we will no longer need to spin up a server for unit tests. 
We can modify the following lines in CMakeProtoMacro.txt to enable the mock generation.
`--grpc_out=generate_mock_code=true:${CMAKE_CURRENT_BINARY_DIR}`
`--grpc_out=generate_mock_code=true:${OUT_DIR}`

GRPC doc: https://grpc.github.io/grpc/cpp/md_doc_unit_testing.html

**Comment by ekowtaylor** [comment]
@themarwhal PR was merged, can this be closed now?

**Comment by themarwhal** [comment]
This is still open.

**Comment by ekowtaylor** [comment]
@themarwhal checking in again on the state of this issue

**Comment by themarwhal** [comment]
@ekowtaylor this should still be open.
