### ISSUE TITLE
AGW- SGI mgmt ip  or static IP not being set 

### ISSUE THREAD

**Issue by pkapatsos-blinq** [magma/magma#5535]
### Your Environment

- **Version:*Orc8r 1.4 and AGW 1.3.3-1614917907-371c6462
- **Affected Component: Access Gateway,
- **Affected Subcomponent: not certain , mobilityd/pipelined 
- **Deployment Environment:** e.g. AWS (orc8r),  bare-metal (AGW) and NAT VM AGW

### Describe the Issue
Trying to set the SGi as static or mgmt IP as described in https://docs.magmacore.org/docs/howtos/config_agw_bridged#agw-management-traffic .
the gateway.mconfig file showing the correct addresses but not being set on the OS.

**To Reproduce**
1. Go to aws orc8r under equipment, select AGW , then config  
2. Click on EPC 
3. Scroll down to SGi management interface IP address
4. Set ip address for SGI with subnet mask,  
**Expected behavior**
NAT mode , should set the eth0 IP to this new IP
NONAT mode should set uplink_br0 to this new IP

**Screenshots**
Setting for NONAT AGW, 
![image](https://user-images.githubusercontent.com/61711855/111356349-a9474480-865e-11eb-8576-dbab77fe199f.png)

Setting for NAT AGW
![image](https://user-images.githubusercontent.com/61711855/111356583-e3184b00-865e-11eb-8275-af41bb61a865.png)

**Additional context**
NO NAT 
View of gateway.mconfig showing the IP address being set ,
![image](https://user-images.githubusercontent.com/61711855/111357540-c892a180-865f-11eb-9a92-d3640ad2a207.png)

view of ip a , showing eth0 using dhcp address not what was set in NMS or gateway.mconfig file 
![image](https://user-images.githubusercontent.com/61711855/111357848-10b1c400-8660-11eb-9fe2-9e8443160e07.png)

After a reboot the new IP takes new ip but default gateway is removed, need to manually add it then stop and restart services to get AGW back to normal . 

![image](https://user-images.githubusercontent.com/61711855/111360240-e31a4a00-8662-11eb-89bc-a724f1f44e07.png)

NAT view of the same 
IP staying as dhcp on uplink_br0
![image](https://user-images.githubusercontent.com/61711855/111357067-56ba5800-865f-11eb-86cf-c3fb0dfc9dd1.png)
view that setting is in gateway.mconfig 
![image](https://user-images.githubusercontent.com/61711855/111358521-cf6de400-8660-11eb-8ea1-44d3875e64a4.png)

[sgI MGMT ISSUE.zip](https://github.com/magma/magma/files/6151338/sgI.MGMT.ISSUE.zip)
Attached are the gateway.mconfig files , what other logs can I share to help ?
I am not sure of the 100% of behavior when changing these settings as no mention in doc.  They  are network related and  if reboot  or networking services need to be restarted  , i see varied behaviors here .Like  the Default gateway adds a second route or when adding VLAN id this will make the AGW in-operable until you remove the gateway.mconfig and remove the setting from NMS to issue  anew file with out one.  So testing to verify as would be customer impacting . The focus on this issue is the static or management  SGi IPs and what could be stopping them from being set properly.

**Comment by pkapatsos-blinq** [comment]
Same issue under R.1.5.1 on Ubuntu
before setting mgmt IP
Showing the Uplink_Br0
![image](https://user-images.githubusercontent.com/61711855/123133278-92fb1280-d41d-11eb-83c4-35e20660ac24.png)
setting the IP in Orc8r
![image](https://user-images.githubusercontent.com/61711855/123133409-b45bfe80-d41d-11eb-871c-c8c9615fb476.png)
After push to AGW , IP removed 
![image](https://user-images.githubusercontent.com/61711855/123133569-e0777f80-d41d-11eb-813e-aa501a0cd475.png)

**Comment by pshelar** [comment]
@pkapatsos-blinq  here sgi network gateway IP address is also required. When both IPs are set, AGW would apply both configs.

**Comment by ekowtaylor** [comment]
@pkapatsos-blinq, @pshelar  what is the status of this issue?

**Comment by pkapatsos-blinq** [comment]
oops missed this and had to use this feture to correct uplink_BR0 ip  usign static IP on R1.6 AGW and r1.6orc8r NMS . now working so closing
