### ISSUE TITLE
[Orchestrator] Prometheus omits identical metrics

### ISSUE THREAD

**Issue by BioZrod** [magma/magma#5555]
### AWS Deployment

- Magma v1.4
- Affected Component: Orchestrator
- Affected Subcomponent: Prometheus-Grafana
- Deployment Environment: AWS (orc8r)

### Describe the Issue

When pushing events with the same exact Timestamp, Label, Labelname, etc. Where the only difference is the value. It pushes just one of the values with duplicate events and omitting the other ones:

![prometheus_identical1](https://user-images.githubusercontent.com/12672464/111431993-72a71380-86ca-11eb-9177-f9f3614f6e07.png)

![prometheus_identical](https://user-images.githubusercontent.com/12672464/111432410-feb93b00-86ca-11eb-8439-34511543dad0.png)

It is important to mention that we are bundling the metrics and pushing several of them at the same time.

**To Reproduce**

1.- Set up a gateway device to bootstrap to Orchestrator using GRPC.
2.- Collect some metrics and set all the required grpc values (label, labelName, etc) to the same value and just change the numeric value(untyped, gauge or counter).
3.- Collect this metric several times at the same exact time or send them in bundle with the same timestamp.

**Expected behavior**
Receive all the events with the set numeric value without duplicates or missing.

**Additional context**
- We are using https://github.com/magma/mma-android to push this metrics into the orchestrator.

**Comment by karthiksubraveti** [comment]
@BioZrod Why are we passing in timestamp as label again ? This should be automatically stamped as the metrics are being pushed into prometheus.

Also the behavior you are seeing sounds correct to me. Prometheus observes these as coming from same datasource and may be overwrites the value. If the metric about an entity is collected over different period of time, then we would see the variation over time.

**Comment by BioZrod** [comment]
Since the library we are using to push metrics runs on Android and IOS devices we were bundling metrics to push them together every x amount of time not use battery constantly. 

But either way if we push them bundled or if we push 2 metrics with the same timestamp (meaning they arrive with the same timestamp) and the label pair values are the same and the gauge, counter or untyped value is the only difference the issue is that it is duplicated or overwritten as you mentioned.

@karthiksubraveti if this is a expected behaviour I wonder if there is any way around it? Anyway I know the chances of this happening with the same timestamp is low especially if we push the metrics as they come but I was curious on why this was happening.

**Comment by karthiksubraveti** [comment]
Why are they have same metric name though ? Can you point me to the code where metric is being pushed ?

**Comment by BioZrod** [comment]
They have the same metric name as we are pushing cellular network information. Metric storing happens at `retrieveNetworkMetrics()` in the following link: [CellularNetworkMetrics](https://github.com/magma/mma-android/blob/master/OpenSchemaSDK/src/main/java/io/openschema/mma/metrics/CellularNetworkMetrics.java)

Metric push happens at `buildMetricsContainer()` in [MetricsWorker](https://github.com/magma/mma-android/blob/master/OpenSchemaSDK/src/main/java/io/openschema/mma/metrics/MetricsWorker.java)

We were planning on adding more network information metrics like pushing rssi value, so we tested pushing some .untyped data with different number value but the labels would be the same and we noticed that when they happened to have the same timestamp the issue mentioned above happened
