### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid because:

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#556]
For the installation of FeG after running the command sudo ./install_gateway.sh feg Below error is received. Kindly support to resolve this issue.
**ERROR: The Compose file './docker-compose.yml' is invalid because:
services.s6a_proxy.ports contains an invalid type, it should be a number, or an object
services.session_proxy.ports contains an invalid type, it should be a number, or an object
services.session_proxy.ports contains an invalid type, it should be a number, or an object
services.swx_proxy.ports contains an invalid type, it should be a number, or an object
services.session_proxy.ports value [':/', ':/'] has non-unique elements**

**Comment by shoaibbutt50** [comment]
Kindly support to tell which docker image this is looking for and which docker registry that I should use.

**Comment by mpgermano** [comment]
Your environment file likely is missing the necessary port mappings for the FeG services. Please see `magma/feg/gateway/docker/.env` and `magma/feg/gateway/docker/.prod_env` as examples.

**Comment by shoaibbutt50** [comment]
ok i will see magma/feg/gateway/docker/.env and magma/feg/gateway/docker/.prod_env as examples and update you.

**Comment by shahrahman-fb** [comment]
Hi, were you able to check this?

**Comment by shoaibbutt50** [comment]
@shahrahman-fb i am doing a fresh installation but now below error is coming.

/magma/orc8r/tools/docker$ sudo ./install_gateway.sh feg
[sudo] password for shoaib: 
Setting working directory as: .
Setting gateway type as: 'feg'
Cloning into 'magma'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 28186 (delta 4), reused 5 (delta 0), pack-reused 28172
Receiving objects: 100% (28186/28186), 26.22 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (17232/17232), done.
**error: pathspec 'latest' did not match any file(s) known to git.**

**Comment by mpgermano** [comment]
This issue should be fixed by https://github.com/facebookincubator/magma/commit/ed3198238696a4b7a800dca41494a076e3413ebd
