### ISSUE TITLE
AGW R1.4 new or upgrades, CPEs wont attach

### ISSUE THREAD

**Issue by pkapatsos-blinq** [magma/magma#5576]
### Your Environment - using Blinqnetworks FWi and Cat12/6 CPE devices 

- **Version:R1.4
- **Affected Component:** Access Gateway, 
- **Affected Subcomponent:**  AGW service - MME or SCTPD
- **Deployment Environment:** e.g. AWS (orc8r),bare-metal (AGW)

### Describe the Issue
Not certain as issue or bug may need feature for our equipment . However in R1.3.3 or prior this equipment works with magma.
After an upgrade to R1.4 , the CPEs will not attach. Rebuild a new AGW with R1.4 same exact errors.
Opening up this issue to attach logs and pcaps for support please.

**To Reproduce using only Blinqnetworks equipment.
1. Run the new build script for R1.4
2. Attach the or redirect eNB to this new MME ip 192.168.33.32
3. Verify S1 is up via GUI and mme.log
4. Attach or reboot CPEs 

**Expected behavior**
The CPEs to attach as in R1.3.3 or prior with full PDP context and a default bearers also S1 to have bi-directional S1AP flows.

**Screenshots**
Enb showing S1 up.. 
![image](https://user-images.githubusercontent.com/61711855/111543922-200d3c00-874a-11eb-8b69-0fbb1fa5c6cc.png)

CPE showing connecting
![image](https://user-images.githubusercontent.com/61711855/111544010-4206be80-874a-11eb-85c0-55e3f778fa05.png)

MME log , showing errors more in pcap and logs attached
![image](https://user-images.githubusercontent.com/61711855/111543665-c278ef80-8749-11eb-8e46-dae20394bffc.png)
![image](https://user-images.githubusercontent.com/61711855/111543679-c7d63a00-8749-11eb-8bbd-734c4a5fcfdb.png)
![image](https://user-images.githubusercontent.com/61711855/111543695-cf95de80-8749-11eb-8e04-7d618fcf1466.png)
![image](https://user-images.githubusercontent.com/61711855/111543723-d6bcec80-8749-11eb-89a8-ca377635deae.png)
![image](https://user-images.githubusercontent.com/61711855/111543749-dd4b6400-8749-11eb-9560-6a7ce9ab757b.png)
![image](https://user-images.githubusercontent.com/61711855/111543780-e76d6280-8749-11eb-96fa-febc3869f983.png)
![image](https://user-images.githubusercontent.com/61711855/111543797-ee947080-8749-11eb-91ff-f99834a1d572.png)

And repeats
Pcap for S1AP and only see traffic is one direction.
![image](https://user-images.githubusercontent.com/61711855/111544313-a6298280-874a-11eb-9217-6f230af61f6b.png)

**Additional context**
Show-tech support file attached plus PCAPs 
[report.AGW-Master-tst.2021-03-17T21_37_26Z.tgz.zip](https://github.com/magma/magma/files/6159925/report.AGW-Master-tst.2021-03-17T21_37_26Z.tgz.zip)
[Newbuildpcaps.zip](https://github.com/magma/magma/files/6159983/Newbuildpcaps.zip)

Please let me know what more we can provide to help get this resolved.

**Comment by sourabh-nanoti** [comment]
=======
000620 Wed Mar 17 15:12:23 2021 7F85513D9700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0865    Received Connection Establishment Confirm from MME_APP for ue_id = 2
000621 Wed Mar 17 15:12:23 2021 7F85513D9700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:1075   [999995432100458] Send S1AP_INITIAL_CONTEXT_SETUP_REQUEST message MME_UE_S1AP_ID = 0x00000002 eNB_UE_S1AP_ID = 0x000080
000622 Wed Mar 17 15:12:23 2021 7F8554BE0700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0535   [999995432100458] MME APP : Sent Initial context Setup Request and Started guard timer for UE id  2 timer_id :601000006c60
000623 Wed Mar 17 15:12:23 2021 7F85513D9700 WARNI S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2506    ERROR IND RCVD on Stream id 0, ignoring it
000624 Wed Mar 17 15:12:23 2021 7F85513D9700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :1068    UE CONTEXT RELEASE REQUEST with Cause_Type = Radio Network and Cause_Value = 21
000625 Wed Mar 17 15:12:23 2021 7F8554BE0700 ERROR MME-AP tasks/mme_app/mme_app_context.c :2175   [999995432100458] UE context release request received while UE is in Deregistered state Perform implicit detach for ue-id0x00000002
000626 Wed Mar 17 15:12:23 2021 7F8554BE0700 INFO  NAS-EM tasks/nas/emm/sap/emm_cn.c      :1138    EMMCN-SAP - Received primitive EMMCN_IMPLICIT_DETACH_UE (407)
========

It seems something goes a miss after MME sends Initial Context Setup Req to the CPE. CPE sends an error indication. Can we have the CPE side logs if possible? It seems that CPE is not liking the Initial Context Setup Req that MME is trying to send.

**Comment by sudhikan** [comment]
I merged two traces to get the full ul and dl messages in the same view.... checked the `attach accept` against v1.3 pcap... only thing that stood out to me was the criticality at the top of the `initialContextSetupRequest` along with the pre-emption capability for this bearer. It seems in 1.3 the pre-emption capability and vulnerability were set? Not sure if this has any impact? 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/38921899/111584520-31bb0780-877b-11eb-88bb-c22338a718e3.png">


[merged_14trace_14traceUEnot.pcap.zip](https://github.com/magma/magma/files/6161837/merged_14trace_14traceUEnot.pcap.zip)

**Comment by sourabh-nanoti** [comment]
<img width="674" alt="Screen Shot 2021-03-18 at 5 09 52 PM" src="https://user-images.githubusercontent.com/48265190/111600929-d20d3c80-880c-11eb-8533-fee3ddf0a598.png">
Looks like an ASN decoding issue for some IE at the CPE as the error indication indicates Protocol -> Transfer Syntax Error

**Comment by pkapatsos-blinq** [comment]
HI Thanks This is what we see as well so am checking with our CPE ENG to get logs. We cant give you pcaps from CPE directly as its own logging reviewing . Attached pcap from the enb showing it times out and detaching  just note a diff AGW same release same issues but you can see 2 way conv. I will get the same for the NAT AGW for ref.  
[agw140-fail-02.zip](https://github.com/magma/magma/files/6165224/agw140-fail-02.zip)

**Comment by pkapatsos-blinq** [comment]
Also attached from enb side and same AGW as other pcaps . We are looking into the ASN error from UE side as do see now its a S1AP message. 
[agw140NEW-fail-01.zip](https://github.com/magma/magma/files/6165385/agw140NEW-fail-01.zip)
 Of course still wondering what changes to the MME side for IE  UE side is there a list to reference as to review with our chipset vendor by chance.

**Comment by amarpad** [comment]
we upgraded s1ap to support release 15 for NSA support I believe. cc @ssanadhya

**Comment by pkapatsos-blinq** [comment]
HI there , we are seeing that you have changed S1AP messages there is criticality information set for individual IEs and/or IE groups,
Criticality instructs how nodes deal with the IE or IE group that is not understood.
In the bad one or R1.4 , you have it set to ignore  and  good R1.3 as reject ,  think not only our enb but other will have an issue if not corrected. 
 ![image](https://user-images.githubusercontent.com/61711855/111678483-b9922780-87f6-11eb-9759-bec943d11130.png)
![image](https://user-images.githubusercontent.com/61711855/111678532-c878da00-87f6-11eb-82d6-0e9db28cc08e.png)
This we feel is the issue breaking our sesssions, here is the specfication we are following, 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/61711855/111679009-40df9b00-87f7-11eb-8975-b6719373c15e.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61711855/111679013-40df9b00-87f7-11eb-9d9b-4f7fe39cd49a.png)

**Comment by ulaskozat** [comment]
@pkapatsos-blinq are you up for making a change in the source code, build and test? If it is the ICS criticality level that is the culprit then https://github.com/magma/magma/blob/0782704bdd7e0ae24af83360878fd2bf2a91c671/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c#L889 needs to be modified from `S1ap_Criticality_ignore` to `S1ap_Criticality_reject`.

**Comment by pkapatsos-blinq** [comment]
@ulaskozat no not yet  ,  we get the code via upgrade process or building baremetal AGW servers with scripts , As before can you update an provide me a new MME file . Please

**Comment by ulaskozat** [comment]
@pkapatsos-blinq I will provide an mme binary based on top of 1.4 release. thanks...

**Comment by amarpad** [comment]
Hi Peter given you are going to be supporting Magma in production, this might be a good time to try patching these things yourself (as it is in a friendly environment). Thanks for the detailed update.

**Comment by pkapatsos-blinq** [comment]
Thanks @ulaskozat
