### ISSUE TITLE
[swagger] Feg contains Federated LTE Networks on  HOME side bar 

### ISSUE THREAD

**Issue by uri200** [magma/magma#5582]
`FEG` entry on the new Home bar in swagger API contains `Federated LTE Networks`. I think that arrangement mixes concepts. 

So Either we organize by the Network type (federation and AGW)

```
/Feg
  - Federation Gateways
  - Federation Gateways

/lte
  - EnodeBs
  - LTE Gateway
  - LTE Network
  - Federated LTE Networks
  - APN
```

Or by type of deployment (Fixed and Federated)
```
/Feg (or federated wireless access or FFWA)
  - LTE Network
  - Federated LTE Networks
  - Federation Gateways
  - Federation Gateways

/lte (or fixed wireless access or FWA)
  - EnodeBs
  - LTE Gateway
  - LTE Network
  - Federated LTE Networks
  - APN
```

Or by the type of gateway (Fixed Access Gateway, Federated Access Gateway, Federation Gateway)
```
/Feg (or Federation Gateway)
  - Federation Gateways
  - Federation Gateways

/fed_lte (or Federated Access Gateway)
  - EnodeBs
  - LTE Network
  - Federated LTE Networks
  - APN 

/lte (ro Access Gateway)
  - EnodeBs
  - LTE Gateway
  - LTE Network
  - Federated LTE Networks
  - APN
```

To make it simple i would chose the first one, but i wanted to show all the options I think we may have

![image](https://user-images.githubusercontent.com/16157139/111557480-fb18c900-8749-11eb-9ed9-4337416e8238.png)

**Comment by hcgatewood** [comment]
@uri200 The sidebar logic is intentionally dumb here -- it lets you see the Swagger spec for a *particular Orc8r service*. It's intentionally not separated by logical function, but rather by implementational location*

*The idea being that the Swagger UI is meant to be a tool for power users, so exposing implementation details is actually preferred. Meanwhile, the NMS attempts to orient itself around more conceptual goals. That to say -- I don't think this is a change worth putting in the time for, and I definitely wouldn't categorize it as a bug

That said, if you want to reorganize things, feel free to move the relevant Swagger specs to the services you think would make more sense 🙂

**Comment by hcgatewood** [comment]
Closing since I don't think it's worth implementing
