### ISSUE TITLE
In quickstart procedure, error when run orc8r with ./run.py --metrics

### ISSUE THREAD

**Issue by pedroamfarias-cpqd** [magma/magma#5600]
### Quickstart environment -  (https://github.com/magma/magma/blob/v1.4.0/docs/readmes/basics/quick_start_guide.md)

- **Version:** v.1.4.0
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator pod/service
- **Deployment Environment:**  local docker-compose (orc8r)

### Describe the Issue

It's not possible to start orc8r with --metrics option. only ./run.py run with success

**To Reproduce**
Following the steps in quick start guide, at step "Terminal Tab 2: Start Orchestrator" with --metrics options, the following error was show:
```
(magma) [qui mar 18 15:42:12]:pedro@pedro-ThinkPad-E470:docker$ ./run.py --metrics
Running 'docker-compose up -d'...
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.override.yml  # DO NOT COMMIT THIS CHANGE'
```

**Expected behavior**
Run docker containers + metrics

**Workaround**
Looks like the run.py script is creating a comment "# DO NOT COMMIT THIS CHANGE" at same line of parameter "COMPOSE_FILE="
* file: magma/python/magma/orc8r/cloud/docker/.env
```
COMPOSE_FILE=docker-compose.yml:docker-compose.metrics.yml:docker-compose.override.yml  # DO NOT COMMIT THIS CHANGE

```

changing the run.py to add a "\n" in "'COMPOSE_FILE={}  {}\n'.format in this comment, the script run with success with --metrics
*file: magma/python/magma/orc8r/cloud/docker/run.py
```
        compose_line = 'COMPOSE_FILE={}  \n{}\n'.format(
            ':'.join(file_args),
            DO_NOT_COMMIT,
        )

```
and after that the .env file keep as it:
* file: magma/python/magma/orc8r/cloud/docker/.env
```
COMPOSE_FILE=docker-compose.yml:docker-compose.metrics.yml:docker-compose.override.yml 
# DO NOT COMMIT THIS CHANGE

```
After this change, the "run.py --metrics"  run with success

**Comment by karthiksubraveti** [comment]
Workaround looks good, can you submit a PR with the fix. We can merge this change

**Comment by pedroamfarias-cpqd** [comment]
Hi @karthiksubraveti ! Many thanks. I created the pull request (this is my first pull request. If I did something wrong let me know to fix it in time  =)

Brs,
Pedro Augusto.

**Comment by ekowtaylor** [comment]
PR merged
