### ISSUE TITLE
Expand Pipelined Stress test/gather test reports

### ISSUE THREAD

**Issue by koolzz** [magma/magma#5611]
Currently for 1.4 I've implemented the pipelined stress test to benchmark number of rpc reqs pipelined can handle.
f.e 
```
~/magma/lte/gateway/python/scripts$ pipelined_cli.py enforcement stress_test_grpc --attaches_per_sec=60 --test_iterations=5
```

It would be great for this would send traffic as well. 

This will help usTry reproducing pipelined specific issues such as the aioeventlet errors(`KeyError: '19 is not registered'`)

Could we try to add this to CI somehow @tmdzk, I assume this needs to be an integ test as it runs ovs.

**Comment by Neudrino** [comment]
As `aioeventlet` is causing issues here, linking #6368 as effort to get rid of it.
