### ISSUE TITLE
Widen range of magma 1.5 supported osx versions, from 10.? to 11.2.3 (BigSur) for AGW dev on Ubuntu20VM

### ISSUE THREAD

**Issue by jeremy-donson** [magma/magma#5621]
### Your Environment
This regards fully virtualized local dev setups on osx laptop only ( provisioner = vagrant, provider = vbox ).

- Facebook MacBookPro runs mac osx 10.15.7 ("Catalina").
- **Affected Component:** This regards agw only at present.
- **Affected Subcomponent:** AGW Service (local dev vms only)
- **Deployment Environment:** Vagrant (AGW)

### Describe the Feature
I am testing on OSX Catalina (10.15.7) to stand up Ubuntu20VM and then build magma binaries.
OSX Big Sur (11.2.3) is latest OSX operating system.  That needs to be tested asap.
We also need to determine earliest OSX version we can effectively support.

**Is your feature request related to a known issue? Please describe.**
Our overall goal is to support massive adoption and project contributions by streamlining support requests.

The biggest single point of procedural ambiguity with regard to osx regards python3.
_There are no instructions to install python3 on osx on magmacore.org._

**Specify the applicable product use-cases**
This is currently for agw local dev vm setups, as we migrate to ubuntuVM from debian VM.

**Describe the solution you'd like**
A local osx laptop-only demo with all magma components on ubuntu vms only.
The simpler the instructions are to stand up, build, install and run local virtualized magma components, the better.
Demos might be best supported with pre-built and tested binaries?

**Describe alternatives you've considered**
We could also support ubuntu local desktops.
This also allows us to consider putting local windows platform dev support on our roadmap?

**Additional context**
What public demos are we targeting for 1.5?

**Resources**
https://www.apple.com/macos/big-sur/

**Desired timelines**
This must be done by 1.5 release.

**Comment by mattymo** [comment]
@jeremy-donson  The blocker for Windows is that the vagrantfile uses built-in Ansible support to run playbooks on the VM. There is no Windows binary for Ansible. Vagrant support in general on Windows is quite spotty.

**Comment by jeremy-donson** [comment]
Understood and agreed, Matt.
Meanwhile:
- If (and only if) they can:
   - stand up an ubuntu20VM on Windows
   and
    - they will install ansible on that ubuntu20 vm
    
    Only then do I believe we MIGHT effectively support them from there.
