### ISSUE TITLE
[MME] Unused output parameter in `void SpgwStateConverter::proto_to_ue`

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5627]
### Your Environment

- **Version:** master

### Describe the Issue
On one of my [PR](https://github.com/magma/magma/pull/5509/files), I noticed the following error.
<img width="790" alt="Screen Shot 2021-03-19 at 12 28 19 PM" src="https://user-images.githubusercontent.com/37634144/111819658-9925a400-88ae-11eb-8035-19dd570e9354.png">

This seems suspicious as the function interface suggests the the protobuf struct will get converted into the mutable pointer parameter (`spgw_ue_context_t* ue_context_p`). 
The function is used here: https://sourcegraph.com/github.com/magma/magma/-/blob/lte/gateway/c/oai/tasks/sgw/spgw_state_manager.cpp#L127

If the function is behaving as intended, we should remove the unused parameter to be more clear. (And the function name since it's kind of an antipattern)

If the function is not behaving as intended, we should fix it. (obviously :D )

#thanks @electronjoe for enabling GCC warning annotation to give visibility to these kinds of things!

**Comment by ulaskozat** [comment]
It does not use ue_context_p indeed. This is not a bug though, should have a better label for these.

**Comment by themarwhal** [comment]
Didn't realize the issue came pre-assigned with a label. Removing it :) 
Oh I see an option to convert to a discussion.... let me try that.

**Comment by themarwhal** [comment]
Actually not sure if this is too specific for discussions. Leaving it as an issue.
