### ISSUE TITLE
Error setting up the NMS

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#563]
After running the command ./scripts/dev_setup.sh Yarn command failed error is received. Kindly support how to resolve this issue
/magma/nms/fbcnms-projects/magmalte$ ./scripts/dev_setup.sh
Starting magmalte_mysql_1 ... done
yarn run v1.17.3
$ node -r '@fbcnms/babel-register' scripts/setPassword.js admin@magma.test password1234
{ SequelizeDatabaseError: Table 'nms.Users' doesn't exist
    at Query.formatError (/usr/src/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.handler [as onResult] (/usr/src/node_modules/sequelize/lib/dialects/mysql/query.js:46:23)
    at Query.execute (/usr/src/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/usr/src/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/usr/src/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/usr/src/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/usr/src/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: Table 'nms.Users' doesn't exist
       at Packet.asError (/usr/src/node_modules/mysql2/lib/packets/packet.js:684:17)
       at Query.execute (/usr/src/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/usr/src/node_modules/mysql2/lib/connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/usr/src/node_modules/mysql2/lib/connection.js:72:12)
       at PacketParser.executeStart (/usr/src/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/usr/src/node_modules/mysql2/lib/connection.js:79:25)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     code: 'ER_NO_SUCH_TABLE',
     errno: 1146,
     sqlState: '42S02',
     sqlMessage: 'Table \'nms.Users\' doesn\'t exist',
     sql:
      'SELECT `id`, `email`, `organization`, `password`, `role`, `networkIDs`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`email` = \'admin@magma.test\' LIMIT 1;' },
  original:
   { Error: Table 'nms.Users' doesn't exist
       at Packet.asError (/usr/src/node_modules/mysql2/lib/packets/packet.js:684:17)
       at Query.execute (/usr/src/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/usr/src/node_modules/mysql2/lib/connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/usr/src/node_modules/mysql2/lib/connection.js:72:12)
       at PacketParser.executeStart (/usr/src/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/usr/src/node_modules/mysql2/lib/connection.js:79:25)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     code: 'ER_NO_SUCH_TABLE',
     errno: 1146,
     sqlState: '42S02',
     sqlMessage: 'Table \'nms.Users\' doesn\'t exist',
     sql:
      'SELECT `id`, `email`, `organization`, `password`, `role`, `networkIDs`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`email` = \'admin@magma.test\' LIMIT 1;' },
  sql:
   'SELECT `id`, `email`, `organization`, `password`, `role`, `networkIDs`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`email` = \'admin@magma.test\' LIMIT 1;' }
**error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

**Comment by shoaibbutt50** [comment]
Docker inspect output is listed below.
/magma/nms/fbcnms-projects/magmalte$ docker inspect --format "{{json .State.Health }}" magmalte_magmalte_1 | jq '.Log[].Output'
"Health check exceeded timeout (30s)"
"Health check exceeded timeout (30s)"
"Health check exceeded timeout (30s)"
"Health check exceeded timeout (30s)"
"Health check exceeded timeout (30s)"

/magma/nms/fbcnms-projects/magmalte$ docker-compose ps
       Name                 Command             State               Ports       
--------------------------------------------------------------------------------
magmalte_magmalte_1   docker-               Up (unhealthy)   0.0.0.0:8080->8080/
                      entrypoint.sh yarn                     tcp                
                      ...                                                       
magmalte_mysql_1      docker-               Up               3306/tcp, 33060/tcp
                      entrypoint.sh                                             
                      mysqld                                                    
magmalte_nginx-       nginx -g daemon       Up               0.0.0.0:443->443/tc
proxy_1               off;                                   p, 80/tcp

**Comment by rckclmbr** [comment]
@shoaibbutt50  can you give me the output of `docker-compose logs magmalte`?

**Comment by shoaibbutt50** [comment]
@rckclmbr i will give you the output of docker-compose logs magmalte

**Comment by shoaibbutt50** [comment]
Below are the logs of magmalte
[root@localhost magmalte]# docker-compose logs magmalte
Attaching to magmalte_magmalte_1
magmalte_1     | yarn run v1.17.3
magmalte_1     | $ nodemon scripts/server
magmalte_1     | [nodemon] 1.19.1
magmalte_1     | [nodemon] reading config ./nodemon.json
magmalte_1     | [nodemon] to restart at any time, enter `rs`
magmalte_1     | [nodemon] or send SIGHUP to 27 to restart
magmalte_1     | [nodemon] ignoring: /usr/src/fbcnms-packages/fbcnms-ui/**/*
magmalte_1     | [nodemon] watching: /usr/src/fbcnms-packages/**/* /usr/src/fbcnms-projects/magmalte/config/**/* /usr/src/fbcnms-projects/magmalte/scripts/**/* /usr/src/fbcnms-projects/magmalte/server/**/*
magmalte_1     | [nodemon] watching extensions: js,mjs,json
magmalte_1     | [nodemon] starting `node -r '@fbcnms/babel-register' scripts/server.js`
magmalte_1     | [nodemon] spawning
magmalte_1     | [nodemon] child pid: 39
magmalte_1     | [nodemon] watching 83 files
magmalte_1     | 2019-08-27T07:41:59.873Z [scripts/server.js] error: Access denied for user 'nms'@'%' to database 'nms'
magmalte_1     | Unhandled rejection SequelizeConnectionError: Access denied for user 'nms'@'%' to database 'nms'
magmalte_1     |     at Promise.tap.then.catch.err (/usr/src/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:19)
magmalte_1     | From previous event:
magmalte_1     |     at ConnectionManager.connect (/usr/src/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:120:13)
magmalte_1     |     at sequelize.runHooks.then (/usr/src/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:311:50)
magmalte_1     | From previous event:
magmalte_1     |     at ConnectionManager._connect (/usr/src/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:311:8)
magmalte_1     |     at ConnectionManager.getConnection (/usr/src/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:46)
magmalte_1     |     at Promise.try (/usr/src/node_modules/sequelize/lib/sequelize.js:631:36)
magmalte_1     | From previous event:
magmalte_1     |     at Promise.resolve.retry (/usr/src/node_modules/sequelize/lib/sequelize.js:619:53)
magmalte_1     |     at /usr/src/node_modules/retry-as-promised/index.js:70:21
magmalte_1     |     at new Promise (<anonymous>)
magmalte_1     |     at retryAsPromised (/usr/src/node_modules/retry-as-promised/index.js:60:10)
magmalte_1     |     at Promise.try (/usr/src/node_modules/sequelize/lib/sequelize.js:619:30)
magmalte_1     | From previous event:
magmalte_1     |     at Sequelize.query (/usr/src/node_modules/sequelize/lib/sequelize.js:576:23)
magmalte_1     |     at promise.then (/usr/src/node_modules/sequelize/lib/query-interface.js:236:46)
magmalte_1     | From previous event:
magmalte_1     |     at QueryInterface.createTable (/usr/src/node_modules/sequelize/lib/query-interface.js:236:20)
magmalte_1     |     at Promise.try.then.then (/usr/src/node_modules/sequelize/lib/model.js:1285:39)
magmalte_1     |     at runCallback (timers.js:705:18)
magmalte_1     |     at tryOnImmediate (timers.js:676:5)
magmalte_1     |     at processImmediate (timers.js:658:5)
magmalte_1     | From previous event:
magmalte_1     |     at Function.sync (/usr/src/node_modules/sequelize/lib/model.js:1285:8)
magmalte_1     |     at SequelizeStore.sync (/usr/src/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:58:30)
magmalte_1     |     at sync (/usr/src/fbcnms-packages/fbcnms-express-middleware/sessionMiddleware.js:22:24)
magmalte_1     |     at Object.sessionMiddleware (/usr/src/fbcnms-projects/magmalte/scripts/server.js:66:3)
magmalte_1     |     at Module._compile (internal/modules/cjs/loader.js:778:30)
magmalte_1     |     at Module._compile (/usr/src/node_modules/pirates/lib/index.js:99:24)
magmalte_1     |     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
magmalte_1     |     at Object.newLoader [as .js] (/usr/src/node_modules/pirates/lib/index.js:104:7)
magmalte_1     |     at Module.load (internal/modules/cjs/loader.js:653:32)
magmalte_1     |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
magmalte_1     |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
magmalte_1     |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
magmalte_1     |     at startup (internal/bootstrap/node.js:283:19)
magmalte_1     |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
magmalte_1     | webpack built fc3c113a29d25aa5b2c5 in 18467ms
magmalte_1     | 2019-08-27T07:42:17.887Z [fbcnms-express-middleware/webpackSmartMiddleware.js] info: Version: webpack 4.35.0
magmalte_1     | Time: 18467ms
magmalte_1     | Built at: 08/27/2019 7:42:17 AM
magmalte_1     |         Asset      Size  Chunks                    Chunk Names
magmalte_1     |      login.js  76.4 KiB   login  [emitted]         login
magmalte_1     |  login.js.map  67.6 KiB   login  [emitted]         login
magmalte_1     |       main.js   546 KiB    main  [emitted]  [big]  main
magmalte_1     |   main.js.map   504 KiB    main  [emitted]         main
magmalte_1     |     vendor.js   5.6 MiB  vendor  [emitted]  [big]  vendor
magmalte_1     | vendor.js.map  5.59 MiB  vendor  [emitted]         vendor
magmalte_1     | Entrypoint main [big] = vendor.js vendor.js.map main.js main.js.map
magmalte_1     | Entrypoint login [big] = vendor.js vendor.js.map login.js login.js.map
magmalte_1     | 2019-08-27T07:42:17.888Z [fbcnms-express-middleware/webpackSmartMiddleware.js] info: Compiled successfully.
[root@localhost magmalte]#

**Comment by shoaibbutt50** [comment]
@rckclmbr now the above mentioned issue is resolved when i reinstalled after removing everything. now when i entering the https://localhost 502 Bad Gateway is showing in the browser or when i am entering https://localhost:9443 This site can’t be reached localhost unexpectedly closed the connection. error is showing. also when i am doing wget in the terminal 
wget https://localhost:9443
--2019-08-28 12:22:06--  https://localhost:9443/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:9443... connected.
Unable to establish SSL connection.
