### ISSUE TITLE
NMS - Adding Unmanaged enodeB gives Errors

### ISSUE THREAD

**Issue by ahdabshafiq** [magma/magma#5633]
**Issue**
When filling out the eNodeB registration form for unmanaged enodeB, it doesn't proceed to next screen and "Notfound" is visible once we click next. However closing and opening the menu again allows to fill in the remaining data. 

**Software Version**
1.3

**Effected UI Component**
NMS - eNB

**Does any recent changes applied on network?**
No

**Impact**
Problem during configuration TAC to add new unmanaged enodeb 

![image](https://user-images.githubusercontent.com/41897810/111847884-9e750400-892b-11eb-86f6-f69918166519.png)

**Comment by karthiksubraveti** [comment]
Can you attach orc8r logs here ?

**Comment by karthiksubraveti** [comment]
Can you also try the same from swagger UI and add if it worked through API. Thanks.

**Comment by ahdabshafiq** [comment]
Yes, it works fine while configuring via API.

**Comment by thmsschmitt** [comment]
Cannot reproduce, looks like this has been fixed.
