### ISSUE TITLE
Associated EnodeB with a particular GW should not appear in the list of other GWs

### ISSUE THREAD

**Issue by ahdabshafiq** [magma/magma#5635]
**Software Version**
1.3

**Effected UI Component**
NMS - eNB

It has been noticed that same enodeB appears in multiple gateways even though if it is associated with only one of them. Ideally it should not appear in other GWs if it is already associated with a particular GW i.e when eNodeBs are registered in an AGW, they should not appear in the list of enodeB available to associate in other AGWs

**Specify the applicable product use-cases**
FWA

**Describe the solution you'd like**
Ideally enodeB should not appear in other GWs if it is already associated with a particular GW

**Comment by karthiksubraveti** [comment]
@ahdabshafiq  Can you provide screenshots to explain this better.

**Comment by ahdabshafiq** [comment]
@karthiksubraveti 

Example Scenario:
There are two GWs, and this enodeB "New Test 2" is already associated with GW1, but it still appears in dropdown menu of GW2.
Ideally if it is already associated with one GW, it shouldn't appear in the dropdown selector of second GW.

![image](https://user-images.githubusercontent.com/41897810/112029215-d01fe200-8b5a-11eb-92e7-7ec2084f1a44.png)

**Comment by karthiksubraveti** [comment]
@HannaFar @mpgermano Would we need this in Gateway HA support ?

**Comment by karthiksubraveti** [comment]
@ahdabshafiq We need eNodeB to be associated with both primary and secondary gateway in case they are going to be in the same pool. We can add additional checks in the future to ensure that we don't do it for gateways not a part of HA configuration. I will leave this issue open to address that.
