### ISSUE TITLE
Error in running the vagrant up command

### ISSUE THREAD

**Issue by mimo123-code** [magma/magma#5641]
### Your Environment

- **Version:**   Ubuntu 18.04
- **Affected Component:**  Access Gateway,
- **Affected Subcomponent:**AGW service
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

hello Everybody i am getting error while running the command "make run" during setting up access gateway .

OAI_FLAGS -DS6A_OVER_GRPC=True -DEMBEDDED_SGW=True -DENABLE_OPENFLOW=True -DSPGW_ENABLE_SESSIOND_AND_MOBILITYD=True
sudo service magma@* stop
make -C /lte/gateway/python buildenv
make[1]: *** /lte/gateway/python: No such file or directory. Stop.
Makefile:136: recipe for target 'build_python' failed
make: *** [build_python] Error 2

**Comment by edaspb** [comment]
I had this issue one time and it was related to Ansible version. I had to update Ansible, reprovision VM and issue disappeared.

**Comment by ekowtaylor** [comment]
Resolved with last comment
