### ISSUE TITLE
[Docs] Build and publish helm charts for magma 1.4

### ISSUE THREAD

**Issue by joary** [magma/magma#5665]
The documentation to publish the Helm charts is missing two pieces of information:

1. Ask the user to assure the github helm repository is new or empty. If repo already has content `package.sh` will fail. 

2. Make sure the GITHUB_REPO_URL also have the user and access_token in it, example:

```bash
export GITHUB_REPO=my-repo
export GITHUB_USERNAME=my-user
export GITHUB_ACCESS_TOKEN=my-token
export GITHUB_REPO_URL=https://$GITHUB_USERNAME:$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
```

Maybe a longer term solution for both is to try downloading first the helm repo. This would flag if the repo exists and is empty (or not), and would also flag if the username/password is valid (or not).

Please let me know if we should be moving this somewhere else.

**Comment by karthiksubraveti** [comment]
Why does the package.sh fail ? Can you dump the error logs here. ? We are just building the helm chart and doing a git add and a push. I don't see why it has to fail if something exists here. 

In medium term - 1.5+ @ranj8work is working on pushing this to centralized repo. We wouldn't mostly require this step going forward.

**Comment by joary** [comment]
Hi Karthik, it fails during the git push:

```
To https://github.com/joary/magma_helm_repo.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://<user>:<token>@github.com/joary/magma_helm_repo.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Just to give you a little more context, this repo was used to store the 1.3 helm chart, so it already have content in it.

If I understood it correctly, the package.sh will try to create a new repo content, add the remote and push it to master.
This will fail to push if the master already has some content (unless we force push it).

**Comment by ekowtaylor** [comment]
Stale
