### ISSUE TITLE
[mme + subscriberdb] Add 5G NSA IEs in Update Location Request/Answer

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5672]
Add the following **information elements** to the GRPC proto messages between MME and SubscriberDB:
1. [Update Location Request](https://github.com/magma/magma/blob/master/feg/protos/s6a_proxy.proto#L132) from MME to Subscriberdb: Dual-Registration-5G-Indicator 
2. [Update Location Answer](https://github.com/magma/magma/blob/master/feg/protos/s6a_proxy.proto#L146) from Subscriberdb to MME over GRPC: 
- NR as Secondary RAT
- Extend the [AggregateMaximumBitrate](https://github.com/magma/magma/blob/master/feg/protos/s6a_proxy.proto#L203) message to include an enum for specifying the units of maximum bitrate in `bps`(4G) or `kbps`(5G-NSA)

Add **logic in MME** to include the IE as part of ULR and process the IEs in ULA

Add **logic in SubscriberDB** to parse the `Dual-Registration-5G-Indicator` IE and respond with the correct values for `NR as Secondary RAT` and `AggregateMaximumBitrate` units

Ref: [LTE 5G Dual connectivity attach call flow](http://www.eventhelix.com/5G/non-standalone-access-en-dc/en-dc-secondary-node-addition-core-network-details.pdf)

**Comment by uri200** [comment]
Hey @ssanadhya I may be missing some context here, but is this feature trying to implement dual connectivity? 

If so, per the  [LTE 5G Dual connectivity attach call flow](http://www.eventhelix.com/5G/non-standalone-access-en-dc/en-dc-secondary-node-addition-core-network-details.pdf) doc I see that we need to send `Feature-List-ID-2 {NR as Secondary RAT}` on the ULA. 

![image](https://user-images.githubusercontent.com/16157139/113225944-cfb2d580-9243-11eb-9854-a6b6879feea3.png)

Table 7.3.10/2 at [3GPP TS 29.272](https://www.etsi.org/deliver/etsi_ts/129200_129299/129272/16.03.00_60/ts_129272v160300p.pdf)



while dual registration 5g indications says 

![image](https://user-images.githubusercontent.com/16157139/113226214-75fedb00-9244-11eb-9f88-045a272684f1.png)

**Comment by Vyas20** [comment]
Hey @uri200 
Yes, this feature is for Dual connectivity implementation.
You are correct about the Feature-List-ID-2 {NR as Secondary RAT} part. We have decided to add this feature in supported features in order to reduce the complexity because initially we only need one flag from the entire feature list.

**Comment by uri200** [comment]
Hi .@Vyas20  not sure if I understand it well so correct me if I am wrong: why we don't just add a flag ouside of supported feature message and label it with the actual AVP message name?

Note that we are free to design grpc message as we want. So it doesn't need to follow the same exact structure as the 3gpp message. However we should use the same fields.

Also note that maybe in the future we add more fields from feature Id list 2. So adding a message that contains only just a flag is not that bad idea. It will be easy extended if we add one more field of that list.

**Comment by Vyas20** [comment]
Hey @uri200 
I have added NR as secondary RAT feature like ULR flags are added in s6a_proxy.proto (as a bool and defined as "supported_features_feature_id_list_2_nr_as_secondary_rat").
