### ISSUE TITLE
[feg] Addition of 5G NSA IEs in Update Location Request/Answer between MME and Feg

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5673]
Extend the handling of 5G NSA IEs in ULA/ULR described in https://github.com/magma/magma/issues/5672 to S6a proxy in Feg

**Comment by uri200** [comment]
@ssanadhya  is this related to https://github.com/magma/magma/pull/5749?

**Comment by ssanadhya** [comment]
> @ssanadhya is this related to #5749?

@uri200, this issue is in addition to #5749, since that one only tracks MME <-> SubscriberDB communication

**Comment by uri200** [comment]
Yep , but in that PR there is a change on s6a_proxy.proto that I will need it for this request
thanks!

**Comment by uri200** [comment]
I also see on the diagram that there is a GX component. Do we need to implement that too? 
If so, that may require another issue for that part 


![image](https://user-images.githubusercontent.com/16157139/113223318-c292e800-923d-11eb-9236-73b3f0d32384.png)
