### ISSUE TITLE
[mme + sessiond] Add 5G NSA IE support in Create Session Request

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5675]
This issue is aimed to add support for 5G-NSA support in Magma MME and Sessiond (without any federated network)

1. Extend the [QosInformationRequest](https://github.com/magma/magma/blob/master/lte/protos/session_manager.proto#L510) to include units for AMBR, i.e. `bps` for 4G and `kbps` for 5G-NSA
2. Add logic at MME to include units in Create Session Request message, based on the IEs in Update Location Answer
3. Add logic at MME to include higher bitrates in Activate Default Bearer Request to UE with the **Extended UE-AMBR Downlink
and Uplink** IEs 
4. Add logic at Sessiond to parse the units field in the Create Session Request message

Ref: [LTE 5G Dual Connectivity Call Flow](http://www.eventhelix.com/5G/non-standalone-access-en-dc/en-dc-secondary-node-addition-core-network-details.pdf)

**Comment by ulaskozat** [comment]
@Vyas20 isn't this completed?

**Comment by Vyas20** [comment]
@ulaskozat Not yet, I am working on task 3 (Extended UE-AMBR Downlink
and Uplink IEs at the moment).

**Comment by ssanadhya** [comment]
Closing this issue since https://github.com/magma/magma/pull/7277 completes the Sessiond support for interpreting extended AMBR fields in Create Session Request.
Sessiond sends the higher bitrate in QoS info to Pipelined. The issue https://github.com/magma/magma/issues/7278 tracks addition needed on Pipelined to enforce the higher bitrates.
