### ISSUE TITLE
[MME][5G] clang detects memcpy overflows 

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5711]
# Summary

In surveying the ~3k clang warnings in building OAI today - I noticed two hits for `-Wfortify-source` as below.

```
/magma/lte/gateway/c/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp:322:3: warning: 'memcpy' will always overflow; destination buffer has size 1, but size argument is 2 [-Wfortify-source]
/magma/lte/gateway/c/oai/tasks/nas5g/src/ies/M5GEAPMessage.cpp:32:5: warning: 'memcpy' will always overflow; destination buffer has size 1, but size argument is 2 [-Wfortify-source]
```

Looking at these warnings, Clang has detected two instances where we memcpy two bytes onto a one-byte stack allocated value (writing off into the stack, presumably, though I suppose this depends upon any padding behavior of our stack).

Here is the finding snippet from [M5GSMobileIdentity.cpp:322](https://github.com/magma/magma/blob/f88aba474071a3b28073cce39b56dd888dafa79a/lte/gateway/c/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp#L322).
```c
  uint8_t ielen  = 0;
...
  IES_DECODE_U16(buffer, decoded, ielen);
```

**Comment by electronjoe** [comment]
Ping @chandra-77 , this bug appears still to exist.

**Comment by ulaskozat** [comment]
@electronjoe  PR #6302 should take of this.

**Comment by electronjoe** [comment]
Feel free to close this issue then - or I can. Up to you!
