### ISSUE TITLE
Swagger UI sidebar overlaps with Swagger endpoints

### ISSUE THREAD

**Issue by AndyLKhuu** [magma/magma#5721]
### Your Environment

- **Version:**
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Swagger UI
- **Deployment Environment:** Swagger UI (staging/local)

### Describe the Issue
Swagger UI currently has a sidebar which stylistically overlaps with the swagger-ui component. This overlap does not have any functional repercussions but should not be happening. 

**To Reproduce**
1. Go to 'https://localhost:9443/swagger/v1/ui/'
2. Inspect elements of page and notice that swaggerui overlaps with the sidebar

**Expected behavior**
No functional changes need to be made. Expected behavior is that both divs (sidebar and swagger-ui) do not overlap.

**Screenshots**
<img width="1792" alt="Screen Shot 2021-03-18 at 1 35 49 AM" src="https://user-images.githubusercontent.com/46101219/112377334-d7ea9e00-8ca2-11eb-8d77-853856f91708.png">
<img width="952" alt="Screen Shot 2021-03-18 at 1 38 39 AM" src="https://user-images.githubusercontent.com/46101219/112377340-db7e2500-8ca2-11eb-8807-24c961266b5f.png">

**Additional context**

**Comment by hcgatewood** [comment]
Resolved by https://github.com/magma/magma/pull/6113
