### ISSUE TITLE
Access gateway make failure

### ISSUE THREAD

**Issue by mimo123-code** [magma/magma#5782]
### Your Environment

- ubuntu 18.04 LTS
- **Affected Component:**  Access Gateway
- **Affected Subcomponent:** make test service
- **Deployment Environment:**   Vagrant (AGW)

### Describe the Issue
while running the make run command command for running the access gateway i am getting the following error :    touch /home/vagrant/build/python/sysdeps
touch: cannot touch '/home/vagrant/build/python/sysdeps': Permission denied
/home/vagrant/magma/orc8r/gateway/python/python.mk:47: recipe for target '/home/vagrant/build/python/sysdeps' failed (edited) 

**Screenshots**

![error](https://user-images.githubusercontent.com/69619527/112722891-e7cbe180-8f31-11eb-9a18-ffddf1668012.png)

**Comment by llewxam-kache** [comment]
After figuring out a previous issue with the MAGMA_ROOT system variable, I'm running into the same issue, was there a solution for this? 
```
vagrant@magma-dev:~/magma/lte/gateway$ export MAGMA_ROOT=/home/vagrant/magma
vagrant@magma-dev:~/magma/lte/gateway$ make run
OAI_FLAGS -DS6A_OVER_GRPC=True -DEMBEDDED_SGW=True -DENABLE_OPENFLOW=True -DSPGW_ENABLE_SESSIOND_AND_MOBILITYD=True
sudo service magma@* stop
make -C /home/vagrant/magma/lte/gateway/python buildenv
make[1]: Entering directory '/home/vagrant/magma/lte/gateway/python'
sudo apt-get -y install python3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dev is already the newest version (3.5.3-1).
E: Archives directory /var/cache/apt/archives/partial is missing. - Acquire (2: No such file or directory)
/home/vagrant/magma/orc8r/gateway/python/python.mk:47: recipe for target '/sysdeps' failed
make[1]: *** [/sysdeps] Error 100
make[1]: Leaving directory '/home/vagrant/magma/lte/gateway/python'
Makefile:146: recipe for target 'build_python' failed
make: *** [build_python] Error 2
```
