### ISSUE TITLE
Incorrect favicon in URLs/subdirectories

### ISSUE THREAD

**Issue by ghost** [magma/magma#5808]
### Your Environment

This docs-centric issue regards the public docs at magmacore.org.

### Describe the Issue

Certain URLs and/or subdirectories do not display the Magmacore favicon.

**To Reproduce**
1. Open a browser tab and navigate to  https://docs.magmacore.org/docs/basics/introduction.html
2. Open a second browser tab and navigate to https://www.magmacore.org/
3. View these tabs side-by-side.

**Expected behavior**
The Magmacore favicon should display for all URLs and/or subdirectories.

**Screenshots**
![wrong-favicon](https://user-images.githubusercontent.com/6627421/113017558-6b552080-9134-11eb-804f-48c08d74a556.png)

**Additional context**
Fixing the favicon for one URL or subdirectory may not resolve the issue sitewide. A stacked PR may be necessary to account for all instances.

**Comment by jaredmullane** [comment]
Good find @aabang. The fix should be altering the "favicon" field in the siteConfig.js file. I believe that should resolve it for all subpages. 
![Screen Shot 2021-03-30 at 9 23 17 AM](https://user-images.githubusercontent.com/61836831/113022790-d523f900-9139-11eb-8bc8-13eac0d01505.png)

**Comment by ekowtaylor** [comment]
PR merged
