### ISSUE TITLE
[NSA] Handling of ERAB Modification and testing modify bearer for secondary eNB/gNB 

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5809]
Testing for validating modified bearer (i.e., switch from the eNB to gNB).

**Comment by ulaskozat** [comment]
This is being tested with DS Tester using eNB secondary interface. Control Plane looks working, User Plane needs to be verified. @Vyas20 please attach the pcaps and mme log for CP test and also test the user plane.

**Comment by Vyas20** [comment]
[MAGMA-Dstester.zip](https://github.com/magma/magma/files/6464749/MAGMA-Dstester.zip)

Please find the MME logs and pcap traces for the control plane connection between MAGMA MME and dsTester
