### ISSUE TITLE
[CI] Improve visibility into test duration regressions

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5847]
## Symptom

@tmdzk noted that our AGW tests increased from ~2 hours to ~3 hours after a couple commits landed.

![Screen Shot 2021-03-31 at 8 33 10 AM](https://user-images.githubusercontent.com/3752618/113144863-bf770800-91fb-11eb-9b60-8b0a5e7faea1.png)

The regression occurred at or before [This PR](https://app.circleci.com/pipelines/gh/magma/magma/18031/workflows/f51526b5-0ebe-40d3-a0a9-ddbe49d4a996), and strictly after [This PR](https://app.circleci.com/pipelines/gh/magma/magma/18021/workflows/399f3d47-9432-4875-a1fb-1381cfcbdd38).  That leaves two candidate PRs.

## Cause

Looking at timing breakdowns for AGW tests on CircleCI, we see that the `integ_test` is excusively responsible for the +1 hour (each iteration of the test is +30 minutes, and we run the test twice).

### Before Regression

![Screen Shot 2021-03-31 at 8 36 11 AM](https://user-images.githubusercontent.com/3752618/113145216-2c8a9d80-91fc-11eb-9975-3e2d27e013dc.png)

### After Regression

![Screen Shot 2021-03-31 at 8 36 52 AM](https://user-images.githubusercontent.com/3752618/113145368-55ab2e00-91fc-11eb-9965-9f3eee7e755c.png)

Further, we can tell from the above that at least under GCC 9.3, the build_oai times did not change as `c-cpp-codecov` stage is unchanged.

### Lack of visibility

Unfortunately, when we open up `integ_test` logs to explore timing deltas, there are no timestamps.

### Python Unit Test Timestamps

Starting from the bottom of the stack, Python can emit one timestamp per unit test (though not per line of output). This may help, but only if the issue is within our tests (e.g. a timeout or slow stage in a test).  If the issue were instead e.g. fetch and build of our vagrant VM, that would not be discovered.

### Pipe all test outputs through Unix `ts`

```shell
command | ts '[%Y-%m-%d %H:%M:%S]'
```

This gives us nice granularity on per-output-line timing.  Perhaps it could be placed fairly high in our build / test scripts so that only one insertion is necessary? Downside: need to modify our vagrant VM (I've struggled with this). Downside: will have to add multiple places it appears... E.g. on many run lines of CircleCI config.

### Enable timestamps on all logs in CircleCI

This [appears to be a requested but unmet feature](https://discuss.circleci.com/t/timestamps-on-build-logs-repeat-request/37173) for CircleCI.  Notably, GitHub Action Logs all contain a prefix timestamp per log line and [Jenkins offers a plugin](https://plugins.jenkins.io/timestamper/).

**Comment by electronjoe** [comment]
Actually, these integ_test runs are all run remotely over SSH - there is some other script that determines the remote setup and execution. That is where we would presumably need to wrap `ts` timestamping?

**Comment by mattymo** [comment]
It's good to raise visibility on performance, but from the Magma Jenkins perspective, master from last night deployed in a normal amount of time: https://jenkins.magmacore.org/job/magma_integration_tests_regression/292/
The previous day's regression job did time out: https://jenkins.magmacore.org/job/magma_integration_tests_regression/291/

Jenkins has timestamps for all logs. You can compare there.

**Comment by electronjoe** [comment]
Was the first Link supposed to be a link to a `magma_integration_tests`, not a `magma_integration_tests_regression`? Poking around over in Jenkins land, I'm trying to assess which `magma_integration_tests` are operating on master, versus a pull request or some such.

**Comment by electronjoe** [comment]
Put another way - how do I determine which Jenkins builds align with the PR boundaries above?

**Comment by mattymo** [comment]
regression jobs are against master. magma_integration_tests builds are only against PRs
https://jenkins.magmacore.org/job/magma_integration_tests/

Since there is no auto-rebase (sometimes called auto-fast forward), there is no easy way to do a time based comparison except when comparing master to master. I could open a PR with based on master from 6 months ago and run CI.

**Comment by electronjoe** [comment]
The ultimate root cause on this was a merge of a new dependency for 5G - bringing the build targets for MME from ~1200 to ~1800.  I diagnosed this using `ts` wrapped on the vagrant builds manually in [This Gist](https://gist.github.com/electronjoe/b517e9b33994977c027f3bc69e88e80f).

Doesn't change the underlying ask that we enable faster root cause diagnosis through timestamp or other telemetry in CI.
