### ISSUE TITLE
[DevOps] [AGW] Verify sctpd package upgrade in stateless AGW

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5855]
As reported by @vaishaliCI : 

"
In teravm  Regression AGW (setup 2) (installed version : 1.5.0-1614817097-07f10f77) fails to responding with S1SetupResponse.

After upgrading sctpd package manually to 1.5.0-1614869512-4f8a5734, test cases were passing with successful s1 setup request. 

Related issue https://github.com/magma/magma/issues/5313 was resolved after manually  as per comments from @pshelar auto scptd upgrade missing from stateless feature.
"

**Comment by uri200** [comment]
Per what we discussed with @tmdzk it looks like sctpd version will not change if there are no changes on sctpd. So we can end up having different version number for agw and sctpd
