### ISSUE TITLE
[Proposal] CI metrics pipeline to track master branch behavior

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5872]
## Problem

There are a number of metrics that we would like to track across "releases" -> master branch builds.  This includes but is not limited to the following, *collected and tagged with the git hash of master which resulted in the metrics*.

- Performance Metrics
  - Select per-api [ghz](https://ghz.sh/) performance results (service requests/second)
  - Q: Arbitrary CI phase latency benchmarking?
- Code Health Metrics (e.g. agw c/cpp examples below)
  - [Count of Clang-Tidy findings by type](https://docs.google.com/spreadsheets/d/e/2PACX-1vRYjUoXzntoIQy-MH_0rI97yO4EQ0h-FFM67AqzIztax0cbnatRBmOs9teKOPcZUQ06qUAY9RN4qQfG/pubhtml#)
  - [Count of Clang warnings by type](https://docs.google.com/spreadsheets/d/e/2PACX-1vSB44kY5bt5Bgvdy9VPOgxrwQHgaa2lnTM_HbbGvw8OpDxs3iJg5fRWt7dOxGIWttTVGQD5Ggeltyqz/pubhtml#)
  - Count of GCC warnings by type
  - Count of `AssertFatal` by major code path
  - Count of `TODO` by major code path

Here is a screenshot of the presently-implemented Google Sheet / Google Survey approach to the problem.

![Screen Shot 2021-04-01 at 10 04 48 AM](https://user-images.githubusercontent.com/3752618/113306156-c7a17700-92d1-11eb-9e61-b1f0a47e1efb.png)

## Desirable Solution Properties

The following are desirable properties for a solution in this space.

- Devops overhead
  - Low overhead to set-up
  - Low overhead to maintain
- Security
  - Up for discussion
  - Restrict public from mutation of existing data
  - Public ability to insert may be acceptable
  - Public should be able to view results without any configuration required
- Repo differentiation
  - Mechanism to ensure that gh/magma/magma is only fork pushing telemetry
- Usage overhead (for those adding telemetry)
  - Simplicity of adding add new metrics
- Data and volume
  - Volume
    - Order 100 metrics, output once per CI build target
    - Order 30 builds per day
    - Metrics matter for at most 6 months
  - Metadata
    - Metrics labeled with master git hash
  - Types
    - float32, int32
    - Q: Distribution? For %iles? Or just post 99% etc as metrics...
- Outputs
  - Reasonably attractive graphs of metrics over time
    - Q: Is decimation required?
  - Public availability without access control issues
  - Q: It's unclear that any sophisticated telemetry processing language is needed
    - E.g. telemetry query languages of Prometheus etc
    - Certainly not for the high value case envisioned above
  - Q: Unclear whether raw data is necessary

### In-repo text file "database"

Could a CI action execute on any PR, mutating the PR or appending a PR automatically with the results of the telemetry being tracked? They could be stored to a CSV somewhere in the repo.  *This appears to be the only partial-solution that does rely on third party tools*.  Drawbacks are obvious and numerous, but this approach would remove yet another dependency by our CI.

### Google Sheet / Survey

This approach has been implemented to date, as it meets many of the above criteria at least partially and was very low friction to establish - getting telemetry ASAP was a priority.  For existing examples of this see:

- [Magma AGW c/c++ Clang-Tidy Telemetry (Responses)](https://docs.google.com/spreadsheets/d/e/2PACX-1vRYjUoXzntoIQy-MH_0rI97yO4EQ0h-FFM67AqzIztax0cbnatRBmOs9teKOPcZUQ06qUAY9RN4qQfG/pubhtml#)
- [Magma AGW c/c++ Clang Warning Telemetry (Responses)](https://docs.google.com/spreadsheets/d/e/2PACX-1vSB44kY5bt5Bgvdy9VPOgxrwQHgaa2lnTM_HbbGvw8OpDxs3iJg5fRWt7dOxGIWttTVGQD5Ggeltyqz/pubhtml#)

This is what the developer experience looks like, where the entry identifiers are available by perma-link generation of the Google Survey, per field.

```bash
	curl -L -v -G -Ss \
		--data-urlencode "entry.338748281=$(BRANCH)" \
		--data-urlencode "entry.1421502557=$(REVISION)" \
		--data-urlencode "entry.1687500610=OAI" \
		--data-urlencode "entry.1690779794=$(shell grep '\[android-cloexec' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1926965966=$(shell grep '\[bugprone-branch-clone\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.951746576=$(shell grep '\[bugprone-macro-parentheses\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.593794544=$(shell grep '\[bugprone-narrowing-conversions\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.607048444=$(shell grep '\[bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.2081825272=$(shell grep '\[bugprone-signed-char-misuse,cert-str34-c\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.268408734=$(shell grep '\[bugprone-sizeof-expression\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1339652996=$(shell grep '\[bugprone-suspicious-string-compare\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1446914229=$(shell grep '\[bugprone-too-small-loop-variable\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.718845718=$(shell grep '\[bugprone-undefined-memory-manipulation\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.851497596=$(shell grep '\[cert-' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1963803956=$(shell grep '\[clang-analyzer-core.CallAndMessage\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1218571043=$(shell grep '\[clang-analyzer-core.NullDereference\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1618711162=$(shell grep '\[clang-analyzer-core.uninitialized.Assign\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1062688275=$(shell grep '\[clang-analyzer-deadcode.DeadStores\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1790897376=$(shell grep '\[clang-analyzer-optin' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.1730273925=$(shell grep '\[clang-analyzer-security.insecureAPI.strcpy\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.806421502=$(shell grep '\[clang-analyzer-unix.Malloc\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.999694738=$(shell grep '\[clang-analyzer-unix.MallocSizeof\]' /tmp/clang-tidy-oai.findings | wc -l)" \
		--data-urlencode "entry.740240539=$(shell grep '\[misc-' /tmp/clang-tidy-oai.findings | wc -l)" \
		https://docs.google.com/forms/d/e/1FAIpQLSfHGqOmDhUMAWHSjA_w6NOGqglQBx2IaO1bXLo6zrOE95sRWQ/formResponse?usp=pp_url
```

### Event Database + GraphQL or Similar

@talkhasib has proposed this solution space, and it does appear to be a robust, formal solution. It does carry downsides in some criteria (at a minimum, `Devops overhead` and possibly `Usage overhead` of the preferred criteria above).  I'm unclear how safe a GraphQL front-end is to have on the public internet?  This approach should be evaluated.

### Classic Telemetry Services

To the best of my knowledge, classic telemetry services are not aimed at this use case - and suffer impedance mismatch.  This is because telemetry services such as e.g. *Prometheus* and similar - aim at the *monitoring* space in which the emitter identity is relative stable and has finite count.  While the problem space here the telemetry emitter is a one-shot at the end of a CI pipeline (or few-shot as the pipeline progresses) and the identifier of the emitter changes every CI build forever (git master hash).

**Comment by hcgatewood** [comment]
What would the file sizes be? I think chucking them directly into the repo would be preferable as an MVP, unless they're gonna get out of control

Could also put them into a separate repo in the Magma org, which is probably cleaner

**Comment by talkhasib** [comment]
If we end pushing the data to the repo, I agree with @hcgatewood on using a different repo than magma/magma
Instead of using a text file, can we load db files on demand by github actions and save the db files back to repo once done.

**Comment by electronjoe** [comment]
Interesting. I'll play with the GH Action repo checkout / database update / write concept.

**Comment by electronjoe** [comment]
> What would the file sizes be?

Hmmm, per WAG above - 100ish telemetry points stored as floats 30 times a day... So should be order 12KB / day but lets say you use god-awful encoding and so it's 50 KB a day. That 30 builds a day is probably high.  The 100 telemetry points may not be so high - but is approx in order.

If 50 KB a day we are looking at a git repo whose history grows 18 MB a year.

Probably can do some Git magic to squash the repo history every 12 months? Something along the lines of what Linus recommends [Here](https://gcc.gnu.org/legacy-ml/gcc/2007-12/msg00165.html) if possible in github...

```shell
git repack -a -d --depth=250 --window=250
```

Hmm, this is nuanced though - as we are talking about binary deltas if we use a formal database. Not sure how those deltas compress in git history?

**Comment by electronjoe** [comment]
Not advocating for this, but [MapBox has a library for storing json documents in a github branch](https://github.com/mapbox/hubdb) as a database! Hah.  Maybe there are other tools here - designed with the limitations of git in mind...

**Comment by hcgatewood** [comment]
Either way, looks like the separate GitHub repo approach has some nice affordances, I'm supportive of trying that direction first 🙂

**Comment by hcgatewood** [comment]
@electronjoe what's the status of this proposal?

**Comment by hcgatewood** [comment]
Closing as currently abandoned. cc @talkhasib for starting points based on current CI pipeline rework
