### ISSUE TITLE
NMS portal convert Auth Key and Auth OPc correctly

### ISSUE THREAD

**Issue by fishlinghu** [magma/magma#59]
The NMS portal converts Auth Key and Auth OPc directly from characters to bytes. However, users might put hex string as an input. Two hex characters together make a byte.

**Comment by xjtian** [comment]
The API expects LTE auth key and opc to be presented as base64-encoded bytes, not hex. The old frontend presented a hex input field and did the decoding and re-encoding in the application layer before sending the API request.

We will fix this interaction on the NMS (@rckclmbr) and add validation to these fields on the backend. In the meantime, you can pass the b64-encoded bytes directly to the NMS:

```
Python 3.7.2 (default, Feb 12 2019, 08:15:36)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import base64

In [2]: hex_key = '00000000000000000000000000000000'

In [3]: base64.b64encode(bytes.fromhex(hex_key)).decode('utf-8')
Out[3]: 'AAAAAAAAAAAAAAAAAAAAAA=='
```
