### ISSUE TITLE
[MME] Explore RelWithDebInfo compile flags for OAI builds

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5912]
### Your Environment

- **Version:** master 
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME

### Describe the Issue
In OAI's CmakeLists.txt, we seem to overwrite some default RelWithDebInfo compile flags with Debug flags.
```
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DDEBUG_IS_ON=1")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_DEBUG} -DDEBUG_IS_ON=1")
```

From looking the original commit that introduced this change (https://github.com/magma/magma/commit/7aea8951aa762eda52c67fabebad9680ebfe21db), it looks like this change was not done on purpose. 

One side effect of this change is that the default optimization value for RelWithDebInfo (-O2) is overwritten by the default value for Debug (-O1). 

It would be good to check if there could be other flags that are overwritten.

Finally, let's benchmark the MME performance between -O2 and -O1 and document explicitly which optimization level we want to be on and why.

**Comment by electronjoe** [comment]
Related: #5222
