### ISSUE TITLE
[NMS] Registered eNBs are greyed out when DHCP service is turned off.

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#5926]
### Your Environment

- **Version:** 1.4
- **Affected Component:** NMS
- **Affected Subcomponent:** Gateway registered eNB list
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

Currently unmanaged eNBs can only be associated with a gateway if the eNB DHCP service is also enabled. This causes un-wanted network behavior especially if there are multiple gateways running on the same LAN (e.g. one gateway with enb DHCP service turned on can address another gateway whose interface is set to `dhcp`). 

**To Reproduce**
1. NMS -> equipment -> enb -> add a new eNB
2. NMS -> equipment -> gateway -> configs -> edit config -> RAN configs
3. Note that eNB added in [1] cannot be associated with the gateway in [2] unless eNB DHCP service is turned on. 

**Expected behavior**
eNBs need to be associated with gateways without the DHCP service being turned on. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38921899/113639127-5513fc80-962d-11eb-8f3e-b09e38a9a6d6.png)
![image](https://user-images.githubusercontent.com/38921899/113639140-5a714700-962d-11eb-9fd5-a8e354106239.png)

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by karthiksubraveti** [comment]
Unmanaged eNodeBs can only be associated with a gateway when dhcp service is disabled.
