### ISSUE TITLE
[DevExp] Improve Intellisense / Clang-Tidy behavior for VS Code Remote Containers

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5955]
I merged a first-pass VS Code Remote Containers Support PR (#5710), but it is not yet as clean or capable as it could be.

While we can support building and running tests from the Docker Container it generates, e.g.

```
cd lte/gateway
make build_oai
make build_session_manager
make test_oai
make test_session_manager
etc
```

Some tooling built into the VS Code integrations are not yet always working.  E.g. the intellisense is not quite there, nor is the clang-tidy include paths.

I have tried two approaches. One is I now have our c/c++ build targets (e.g. specified in lte/gateway/Makefile) generating compile_commands.json. Generally within /build/ directory somewhere upon build.  You can point the configuration of VS code remote container (through the .devcontainer/ config) at this file - and that does work for e.g. Clang tidy and I think intellisense. But the downside is the user has to build that file to start the process (yuck). And it's limited to whatever target you generated a compile_commands.json for (yuck - we have lots of targets and no "build the world".. yet).

To address these shortcomings, I also tried hard-coding all the include paths (this is partially done in the above PR - see `.devcontainer/devcontainer.json` and the `clang-tidy.compilerArgs` settings) but I'm still missing some and the clang-tidy analysis tool is complaining about the lack of compile_commands.json.   Not ideal but it's nice NOT to have to build the compile_commands.json (also note that we may not presently have ONE compile_commands.json, I haven't experimented with a build-the-world build target to achieve this so today you may have only partial code base coverage from any one compile_commands.json).

**Comment by electronjoe** [comment]
Hoping @ShubhamTatvamasi can work on this - I've asked @bbarritt for help getting him in org so we can assign.

**Comment by ShubhamTatvamasi** [comment]
Sure, Thanks @electronjoe

**Comment by electronjoe** [comment]
There we go!
