### ISSUE TITLE
[NMS] Add e2e tests with Testim

### ISSUE THREAD

**Issue by andreilee** [magma/magma#5967]
## Summary
Configure e2e test flows through the Testim UI to ensure that key NMS functionality continues to work

- LTE network creation / update / deletion
- Federation network creation / update / deletion
- Gateway creation / update / deletion
- Policy configuration
- Subscriber configuration

**Comment by andreilee** [comment]
## Summary
Configure e2e test flows through the Testim UI to ensure that key NMS functionality continues to work

- LTE network creation / update / deletion
- Federation network creation / update / deletion
- Gateway creation / update / deletion
- Policy configuration
- Subscriber configuration

**Comment by ekowtaylor** [comment]
Phase 1 to be completed in sprint ending Sep 17. @andreilee to update
