### ISSUE TITLE
[NMS] Edit gateway YML configs on the NMS

### ISSUE THREAD

**Issue by andreilee** [magma/magma#5971]
## Summary

Add the ability to view and edit the gateway service YML configs on the NMS. This pane should be available in the NMS gateway configs, and similar to the `Troubleshoot Gateway` pane, which uses generic gateway commands to get the output of these yml config files. Depending on the type of gateway, and the version of gateway software that is being used, a different set of YML config files will be available to edit.

This feature limits the need of network operators to SSH into Magma gateways to reconfigure yml configs for gateway services.

**Comment by karthiksubraveti** [comment]
#closedby https://github.com/magma/magma/pull/6831
