### ISSUE TITLE
Downlink Throughput #s incorrect scale

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#5980]
### Your Environment

- **Version:** 1.4
- **Affected Component:** NMS
- **Affected Subcomponent:** Metrics (Downlink Throughput)
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue
We have a gateway that does HTTP downlink traffic every 30 minutes over the LTE network. It's a 10M file downloaded over 3 minutes, so the tput is definitely over 2Mbps. The tput shown on the gateway section shows the tput in the Kbps range...
![image](https://user-images.githubusercontent.com/38921899/113802811-35093980-9710-11eb-82cb-f0dce2a05328.png). Not sure if this is being read incorrectly or converted incorrectly? 

One additional thing to look at is the "subscriber" tab. Currently I do not see metrics populated for this particular network and UE (there is only one UE in this network). 

**To Reproduce**
1. Metrics -> Gateways -> Select Network and Gateway -> Go to Downlink and Uplink Tput

**Comment by karthiksubraveti** [comment]
We compute the rate over 5 minute window. That would be 10,000/300 =~ 33kbps sounds similar to the output observed above. Let me know if this sounds right.

**Comment by karthiksubraveti** [comment]
Discussed offline.
