### ISSUE TITLE
Datapath Probe Cli: add details when packet is dropped.

### ISSUE THREAD

**Issue by pshelar** [magma/magma#5987]
When user runs this script there are well known issues that prevent datapath connectivity.
1. UE is not attached.
2. UE flows are not programmed in table 0
3. there is ACL dropping packet
4. there is no enforcement rule allowing traffic.
5. unknown issue. packet is dropped in other OVS table.

The script can detect this and print such msg.

**Comment by amarpad** [comment]
I would add DNS is not reachable, (optionally take DNS as a command line param), SGi is messed up (vlan not getting pushed/set etc. on uplink_br).
