### ISSUE TITLE
NMS not showing the tabs

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#599]
[DockerComposelogs.TXT](https://github.com/facebookincubator/magma/files/3557091/DockerComposelogs.TXT)

I am able to log in into the Magma NMS but NMS tabs are not showing and docker compose logs are showing access denied for user. Kindly find the attached docker compose logs text file.
Please support how to resolve this issue.

```
mysql_1        | Version: '5.7.27'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
magmalte_1     | 2019-08-29T14:06:57.456Z [fbcnms-express-middleware/appMiddleware.js] info: ::ffff:127.0.0.1 - - [29/Aug/2019:14:06:57 +0000] "HEAD /user/login HTTP/1.1" 200 2 "-" "curl/7.64.0"
mysql_1        | 2019-08-29T13:59:48.513665Z 5 [Note] Access denied for user 'root'@'localhost' (using password: YES)
mysql_1        | 2019-08-29T14:00:18.895275Z 6 [Note] Access denied for user 'root'@'localhost' (using password: YES)
mysql_1        | 2019-08-29T14:00:45.963064Z 11 [Note] Aborted connection 11 to db: 'nms' user: 'nms' host: '172.24.0.3' (Got an error reading communication packets) 
```

**Comment by rckclmbr** [comment]
@shoaibbutt50 what's the full output of the logs from `magmalte`?  I don't think the error I need is there.

The "access denied" is a transient error (i'll make this less verbose).

**Comment by shoaibbutt50** [comment]
https://pastebin.com/RxdaYLNs

(moved to pastebin to reduce noise in issue)

**Comment by shoaibbutt50** [comment]
@rckclmbr The above is the logs of magmalte. Please check for the cause of the issue.

**Comment by rckclmbr** [comment]
@shoaibbutt50 your issue is here:

```
magmalte_1     | Error: connect EHOSTUNREACH 172.24.0.1:9443
magmalte_1     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

It's having trouble connecting to the controller.  You can simplify debugging this by testing with curl inside the magmalte container.  Run something like this:

```
docker-compose exec magmalte /bin/sh
curl -k --key $API_PRIVATE_KEY_FILENAME --cert $API_CERT_FILENAME https://$API_HOST/magma/networks
```

This will likely fail, but then you can get the controller running and further debug the reason why

**Comment by rckclmbr** [comment]
Closing due to no response, let me know if you continue to see issues
