### ISSUE TITLE
NMS doesn't reply to WEB login

### ISSUE THREAD

**Issue by JtpRtx** [magma/magma#602]
I have build release Magma 0.3.78 on a fresh Ubuntu 16.04 machine following instructions in the quick_start_guide. After starting the NMS with "docker-compose up -d" in directory "~/magma/nms/fbcnms-projects/magmalte", and after a while login from a web browser, there seems no reply from the WEB server. Inspecting the produced log from the magmalte docker container indicates that there is an error in /usr/src/fbcnms-packages/fbcnms-babel-register/polyfill.js  _Module not found: Error: Can't resolve 'core-js/modules/es.array.flat' in '/usr/src/fbcnms-packages/fbcnms-babel-register'_
(see also attached log information)
[Nms1.log](https://github.com/facebookincubator/magma/files/3567127/Nms1.log)

Am I missing something in my installation? Guidance is highly appreciated.

**Comment by rckclmbr** [comment]
@JtpRtx are you using docker-compose to start it?  If so, your node_modules might be out of date.  You can test it out by removing these lines:

https://github.com/facebookincubator/magma/blob/master/nms/fbcnms-projects/magmalte/docker-compose.yml#L31-L35

If it works (and you still want the volume mounts), you can run `yarn install` on the hosting server so the correct node dependencies will exist in the mounted volume.

**Comment by JtpRtx** [comment]
Yes, I am using docker-compose to start it. 
In the meantime I had cloned the project from git with newest file revisions. Now it seems to work.
Thanks for your support.
/jens
