### ISSUE TITLE
Required tests not running on PR

### ISSUE THREAD

**Issue by Scott8440** [magma/magma#6051]
### Your Environment

- **Version:** 1.3
- **Affected Component:** N/A
- **Affected Subcomponent:** N/A
- **Deployment Environment:** CircleCI

### Describe the Issue

PR #4664 is missing a required test (lte_test), but CI does not seem interested in trying to run it. My only thought is that this is because it's merging against brach 1.3.

**To Reproduce**
1. Go to #4664
2. Scroll down to checks
3. Look at ci/circleci:lte-test)

**Expected behavior**
All required tests run on PR

**Comment by hcgatewood** [comment]
I think you're right about targeting v1.3 branch. When I'm back in office next week I'll force-merge it to resolve

**Comment by themarwhal** [comment]
Force merged the PR. Will look into why this is an issue!
