### ISSUE TITLE
[NMS] can't edit policy due to missing subscriber

### ISSUE THREAD

**Issue by uri200** [magma/magma#6128]
When trying to edit a Policy on NMS we get `failed to create policy: one or more subscribers or QoS profiles do not exist`

This can be reproduced at `hcore_agw_inbound_network`
https://magma-admin.nms-staging.magma.etagecom.io/nms/hcore_agw_inbound_network/traffic/policy

HAR file
[subscriber_not_found_magma-admin.nms-staging.magma.etagecom.io.har.zip](https://github.com/magma/magma/files/6306985/subscriber_not_found_magma-admin.nms-staging.magma.etagecom.io.har.zip)

![image](https://user-images.githubusercontent.com/16157139/114627980-02f55b80-9c6b-11eb-8e52-34d29224d89b.png)

**Comment by karthiksubraveti** [comment]
@andreilee Can you take a look when possible. Thanks.

**Comment by karthiksubraveti** [comment]
@uri200 I suspect this is because of the non existent subscribers. Did you attempt to remove these subscribers from the policy prior to the deletion of the subscriber ?
```
          "postData": {
            "mimeType": "application/json",
            "text": "{\"assigned_subscribers\":[\"IMSI001001000000810\",\"IMSI001001000000811\",\"IMSI001002000000811\"],\"flow_list\":[{\"action\":\"PERMIT\",\"match\":{\"direction\":\"UPLINK\",\"ip_dst\":{\"address\":\"192.168.0.0/24\",\"version\":\"IPv4\"},\"ip_proto\":\"IPPROTO_IP\",\"ip_src\":{\"address\":\"192.168.0.0/24\",\"version\":\"IPv4\"}}},{\"action\":\"PERMIT\",\"match\":{\"direction\":\"DOWNLINK\",\"ip_proto\":\"IPPROTO_IP\"}}],\"header_enrichment_targets\":null,\"id\":\"pass_all_policy\",\"priority\":1,\"tracking_type\":\"NO_TRACKING\"}"
          }

```

**Comment by uri200** [comment]
Yep I did manually thought the API and it seemed it worked

But how did IMSI001002000000811 ended up there? That subscriber was never added to subscriberDb.

**Comment by karthiksubraveti** [comment]
No idea how it ended up there. This is a good reason on why we need a audit logging feature in NMS :-)

**Comment by karthiksubraveti** [comment]
I will close this bug that it works as expected.
