### ISSUE TITLE
CreateSessionUtil imports issue for pipelined_cli

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#6130]
Issue :
pipelined_cli.py : from magma.pipelined.tests.app.ng_set_session_msg import CreateSessionUtil
                                 ImportError: No module named 'magma.pipelined.tests'

Cause : For fab builds the tests directory is not present hence the CreateSessionUtil() is not present hence the error.

**Comment by ekowtaylor** [comment]
Stub, new more info to debug further
