### ISSUE TITLE
agw install script stuck in a loop

### ISSUE THREAD

**Issue by shanku9** [magma/magma#6137]
### Your Environment

- **Version:** 1.4
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service installer
- **Deployment Environment: bare-metal (AGW)

### Describe the Issue
Install script is stuck in loop 
root@debian:/home/magma# journalctl -fu agw_installation
-- Logs begin at Wed 2021-04-14 02:04:22 UTC. --
Apr 14 02:04:55 debian bash[937]: Please answer yes or no.
Apr 14 02:04:55 debian bash[937]: Please answer yes or no.
Apr 14 02:04:55 debian bash[937]: Please answer yes or no.
Apr 14 02:04:55 debian bash[937]: Please answer yes or no.
Apr 14 02:04:55 debian bash[937]: Please answer yes or no.
Apr 14 02:04:55 debian bash[937]: Please answer yes or no.

https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install.sh#L26-L33

**To Reproduce**
1. run agw_install.sh

**Expected behavior**
Installation should proceed without prompting /root/agw_install.sh https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install.sh#L5

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/
