### ISSUE TITLE
Magma AGW Ignored Attached Request - #T3410 timer 

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#6145]
**Version:**1.3.3-1614917907-371c6462
Affected Component: Access Gateway
Affected Subcomponent: Mobilityd
Deployment Environment: bare-metal (AGW)

### Describe the Issue

At one of Freedomfi site, we observed a scenario where Magma AGW kept on silently ignoring "Attach Requests" consistently unless the UE were restarted. From trace/logs it was found that some previous attach of same UE was not completed and Magma was expecting a response of some signaling messages from the UE which was never received (due to packet loss or abnormal signaling with the eNodeB) therefore Magma AGW as per 3GPP 24_301 ignored any new Attach request, which is as per the protocol. But the issue is that, Magma AGW never terminated previous attach procedure which resulted in issue lasting for approx 2 hours unless a Release Request received from the enodeB. Ideally, AGW should have terminated previous attach procedure if we had configured T3410 timer (starts when the Attach Request is received and stops when Attach Accept is sent). Since we dont have this timer configured on Magma AGW, the issue lasted for good 2 hours approximately.  

**To Reproduce**
To reproduce the issue, It is required to simulate a disconnection between UE and AGW during Common Procedure (May be by pulling out CPEs Battery) and try to attach again later. 

**Screenshots**
![image](https://user-images.githubusercontent.com/77636702/114792173-71aae580-9d4d-11eb-8f9d-89371e8d4643.png)

**logs**
089939 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0217    ATTACH REQ (ue_id = 0x00000209) (IMSI = 314030000022993) 
089940 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0234    EMM-PROC:  ATTACH - EPS attach type = EPS (0)
089941 Sun Apr 11 17:57:06 2021 7FCE32CDF700 NOTIC NAS-EM tasks/nas/emm/Attach.c          :0561    EMM-PROC  - Create EMM context ue_id = 0x00000209
089942 Sun Apr 11 17:57:06 2021 7FCE32CDF700 NOTIC NAS    tasks/nas/emm/Attach.c          :1089    Hit 3GPP TS 24_301R10_5_5_1_2_3__1 : EMM common procedure initiation during attach procedure
089943 Sun Apr 11 17:57:06 2021 7FCE32CDF700 ERROR MME-AP tasks/mme_app/mme_app_context.c :0618   [314030000022993] Error could not update this ue context 0x62100007bc00 enb_ue_s1ap_ue_id 0x000141 mme_ue_s1ap_id 0x00000209 mme_teid_s11 0x0 : HASH_TABLE_KEY_NOT_EXISTS
089944 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :1469    Sending Authentication Information Request message to S6A for ue_id =0x00000209
089945 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/nas_proc.c            :0367    Received Authentication Information Answer from S6A for ue_id =0x00000209
089946 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_cn.c      :1138    EMMCN-SAP - Received primitive EMM_CN_AUTHENTICATION_PARAM_RES (401)
089947 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0241    EMM-FSM   - Received event COMMON_PROC_ABORT (4) in state EMM-DEREGISTERED
089948 Sun Apr 11 17:57:06 2021 7FCE32CDF700 ERROR NAS-EM tasks/nas/emm/sap/EmmDeregistere:0123    EMM-FSM state EMM_DEREGISTERED - Primitive _EMMREG_COMMON_PROC_ABORT is not valid
089949 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :0167    ue_id=0x00000209 EMM-PROC  - Initiate Authentication KSI = 0
089950 Sun Apr 11 17:57:06 2021 7FCE32CDF700 WARNI NAS-EM tasks/nas/emm/LowerLayer.c      :0472    NO Valid Security Context Available
089951 Sun Apr 11 17:57:06 2021 7FCE32CDF700 NOTIC NAS    tasks/nas/emm/Authentication.c  :1238    Hit 3GPP TS 24_301R10_5_4_2_2 : Authentication initiation by the network
089952 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176    EMMAS-SAP - Received primitive EMMAS_SECURITY_REQ (201)
089953 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :1639    EMMAS-SAP - Send AS security request
089954 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :1347    EMMAS-SAP - Send Authentication Request message for ue_id = (521)
089955 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_context.c :1553   [314030000022993] UE STATE - CONNECTED.
089956 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0241    EMM-FSM   - Received event COMMON_PROC_REQ (1) in state EMM-DEREGISTERED
089957 Sun Apr 11 17:57:06 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0156    UE 0x00000209 EMM-FSM   - Status changed: EMM-DEREGISTERED ===> EMM-COMMON-PROCEDURE-INITIATED
089958 Sun Apr 11 17:57:06 2021 7FCE2F4D8700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0469   [314030000022993] Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x00000209 MME_UE_S1AP_ID = 0x00000209 eNB_UE_S1AP_ID = 0x000141
089959 Sun Apr 11 17:57:07 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2564    Sent paging message over sctp for IMSI 314030000022974
089960 Sun Apr 11 17:57:08 2021 7FCE2F4D8700 ERROR S1AP   tasks/s1ap/s1ap_mme_decoder.c   :0096    Error Indication is received. Ignoring it. Procedure code = 15
089961 Sun Apr 11 17:57:08 2021 7FCE2F4D8700 WARNI S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2044    ERROR IND RCVD on Stream id 0, ignoring it
089962 Sun Apr 11 17:57:11 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :3706    Expired- Paging timer for ue_id 0x00000202
089963 Sun Apr 11 17:57:11 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2564    Sent paging message over sctp for IMSI 314030000022974
089964 Sun Apr 11 17:57:12 2021 7FCE32CDF700 NOTIC NAS    tasks/nas/emm/Authentication.c  :1054    Hit 3GPP TS 24_301R10_5_4_2_7_b : Expiry of timer T3460
089965 Sun Apr 11 17:57:12 2021 7FCE32CDF700 WARNI NAS-EM tasks/nas/emm/Authentication.c  :1062    EMM-PROC  - T3460 timer expired, retransmission counter = 1
089966 Sun Apr 11 17:57:12 2021 7FCE32CDF700 WARNI NAS-EM tasks/nas/emm/LowerLayer.c      :0472    NO Valid Security Context Available
089967 Sun Apr 11 17:57:12 2021 7FCE32CDF700 NOTIC NAS    tasks/nas/emm/Authentication.c  :1238    Hit 3GPP TS 24_301R10_5_4_2_2 : Authentication initiation by the network
089968 Sun Apr 11 17:57:12 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176    EMMAS-SAP - Received primitive EMMAS_SECURITY_REQ (201)
089969 Sun Apr 11 17:57:12 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :1639    EMMAS-SAP - Send AS security request
089970 Sun Apr 11 17:57:12 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :1347    EMMAS-SAP - Send Authentication Request message for ue_id = (521)
089971 Sun Apr 11 17:57:12 2021 7FCE2F4D8700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0469   [314030000022993] Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x00000209 MME_UE_S1AP_ID = 0x00000209 eNB_UE_S1AP_ID = 0x000141
089972 Sun Apr 11 17:57:12 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2564    Sent paging message over sctp for IMSI 314030000022975
089973 Sun Apr 11 17:57:15 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :3706    Expired- Paging timer for ue_id 0x00000202
089974 Sun Apr 11 17:57:15 2021 7FCE32CDF700 ERROR MME-AP tasks/mme_app/mme_app_bearer.c  :2281   [314030000022974] Reached max re-transmission of Paging Ind for ue_id 0x00000202
089975 Sun Apr 11 17:57:16 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0095    Received S1AP INITIAL_UE_MESSAGE eNB_UE_S1AP_ID 0x000142
089976 Sun Apr 11 17:57:16 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0108    New Initial UE message received with eNB UE S1AP ID: 0x000142
089977 Sun Apr 11 17:57:16 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0175    Sending Initial UE Message to MME_APP, enb_ue_s1ap_id : 0x000142
089978 Sun Apr 11 17:57:16 2021 7FCE2F4D8700 ERROR S1AP   tasks/s1ap/s1ap_mme_decoder.c   :0096    Error Indication is received. Ignoring it. Procedure code = 15
089979 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0551    Received MME_APP_INITIAL_UE_MESSAGE from S1AP
089980 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0717   [0] INITIAL_UE_MESSAGE RCVD 
mme_ue_s1ap_id  = 522
enb_ue_s1ap_id  = 322
089981 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0724   [0] Sending NAS Establishment Indication to NAS for ue_id = (522)
089982 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176    EMMAS-SAP - Received primitive EMMAS_ESTABLISH_REQ (205)
089983 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0741    EMMAS-SAP - Received AS connection establish request
089984 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0801    EMMAS-SAP - Message Type = ATTACH_REQUEST(0x41) for (ue_id = 522)
089986 Sun Apr 11 17:57:16 2021 7FCE2F4D8700 WARNI S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2044    ERROR IND RCVD on Stream id 0, ignoring it
089985 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :0138    EMMAS-SAP - Received Attach Request message
089987 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0217    ATTACH REQ (ue_id = 0x0000020A) (IMSI = 314030000022993) 
089988 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0234    EMM-PROC:  ATTACH - EPS attach type = EPS (0)
089989 Sun Apr 11 17:57:16 2021 7FCE32CDF700 NOTIC NAS    tasks/nas/emm/Attach.c          :0473    Hit 3GPP TS 24_301R10_5_5_1_2_7_e__2 : Ignore the this duplicate ATTACH REQUEST message, continue with the previous attach procedure
089990 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_detach.c  :0126    Handle Detach Req at MME app for ue-id: 0x0000020A
089991 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_itti_messa:0089   [0] Sending UE Context Release Cmd to S1ap for (ue_id = 522)
UE Context Release Cause = (4)
089992 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_context.c :0120   [0] Deleted UE location from directoryd
089993 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  NAS-ES tasks/nas/esm/sap/esm_sap.c     :0142    ESM-SAP   - Received primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ (10)
089994 Sun Apr 11 17:57:16 2021 7FCE32CDF700 ERROR NAS-ES tasks/nas/esm/PdnConnectivity.c :0525    ESM-PROC  - PDN connection identifier is not valid
089995 Sun Apr 11 17:57:16 2021 7FCE32CDF700 ERROR NAS-ES tasks/nas/esm/sap/esm_sap.c     :0295    ESM-SAP   - Failed to process primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ (10)
089996 Sun Apr 11 17:57:16 2021 7FCE32CDF700 WARNI NAS-EM tasks/nas/emm/Attach.c          :0488    EMM-PROC  - Received duplicated Attach Request
089997 Sun Apr 11 17:57:16 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :3706    Expired- Paging timer for ue_id 0x000001EA
089998 Sun Apr 11 17:57:16 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2564    Sent paging message over sctp for IMSI 314030000022975
089999 Sun Apr 11 17:57:20 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :3706    Expired- Paging timer for ue_id 0x000001EA
090000 Sun Apr 11 17:57:20 2021 7FCE32CDF700 ERROR MME-AP tasks/mme_app/mme_app_bearer.c  :2281   [314030000022975] Reached max re-transmission of Paging Ind for ue_id 0x000001EA
090001 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0095    Received S1AP INITIAL_UE_MESSAGE eNB_UE_S1AP_ID 0x000143
090002 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0108    New Initial UE message received with eNB UE S1AP ID: 0x000143
090003 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0175    Sending Initial UE Message to MME_APP, enb_ue_s1ap_id : 0x000143
090004 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0551    Received MME_APP_INITIAL_UE_MESSAGE from S1AP
090005 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0717   [0] INITIAL_UE_MESSAGE RCVD 
mme_ue_s1ap_id  = 523
enb_ue_s1ap_id  = 323
090006 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0724   [0] Sending NAS Establishment Indication to NAS for ue_id = (523)
090007 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176    EMMAS-SAP - Received primitive EMMAS_ESTABLISH_REQ (205)
090008 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0741    EMMAS-SAP - Received AS connection establish request
090009 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0852    EMMAS-SAP - Message Type = TRACKING_AREA_UPDATE_REQUEST(0x48)for (ue_id = 523)
090010 Sun Apr 11 17:57:30 2021 7FCE32CDF700 WARNI NAS-EM tasks/nas/emm/TrackingAreaUpdate:0517    EMM-PROC- Sending Tracking Area Update Reject. ue_id=0x0000020B, cause=9)
090011 Sun Apr 11 17:57:30 2021 7FCE32CDF700 WARNI NAS-EM tasks/nas/emm/LowerLayer.c      :0472    NO Valid Security Context Available
090012 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176    EMMAS-SAP - Received primitive EMMAS_ESTABLISH_REJ (207)
090013 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :2161    EMMAS-SAP - Send AS connection establish reject
090014 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :1219    EMMAS-SAP - Send Tracking Area Update Reject message (cause=9)
090015 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_context.c :1553   [0] UE STATE - CONNECTED.
090016 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_itti_messa:0089   [0] Sending UE Context Release Cmd to S1ap for (ue_id = 523)
UE Context Release Cause = (1)
090017 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0469   [0] Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x0000020B MME_UE_S1AP_ID = 0x0000020B eNB_UE_S1AP_ID = 0x000143
090018 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_context.c :1952    Received UE context release complete message for ue_id: 0x0000020B
090019 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_context.c :0120   [0] Deleted UE location from directoryd
090020 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-ES tasks/nas/esm/sap/esm_sap.c     :0142    ESM-SAP   - Received primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ (10)
090021 Sun Apr 11 17:57:30 2021 7FCE32CDF700 ERROR NAS-ES tasks/nas/esm/PdnConnectivity.c :0525    ESM-PROC  - PDN connection identifier is not valid
090022 Sun Apr 11 17:57:30 2021 7FCE32CDF700 ERROR NAS-ES tasks/nas/esm/sap/esm_sap.c     :0295    ESM-SAP   - Failed to process primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ (10)
090023 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_handlers.c  :2564    Sent paging message over sctp for IMSI 314030000023043
090024 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0275    Received S1AP UPLINK_NAS_TRANSPORT message MME_UE_S1AP_ID 0x0000020B
090025 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 WARNI S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0283    Received S1AP UPLINK_NAS_TRANSPORT No UE is attached to this mme_ue_s1ap_id: 0x0000020B
090026 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0095    Received S1AP INITIAL_UE_MESSAGE eNB_UE_S1AP_ID 0x000144
090027 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0108    New Initial UE message received with eNB UE S1AP ID: 0x000144
090028 Sun Apr 11 17:57:30 2021 7FCE2F4D8700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0175    Sending Initial UE Message to MME_APP, enb_ue_s1ap_id : 0x000144
090029 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0551    Received MME_APP_INITIAL_UE_MESSAGE from S1AP
090030 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0717   [0] INITIAL_UE_MESSAGE RCVD 
mme_ue_s1ap_id  = 524
enb_ue_s1ap_id  = 324
090031 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  MME-AP tasks/mme_app/mme_app_bearer.c  :0724   [0] Sending NAS Establishment Indication to NAS for ue_id = (524)
090032 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176    EMMAS-SAP - Received primitive EMMAS_ESTABLISH_REQ (205)
090033 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0741    EMMAS-SAP - Received AS connection establish request
090034 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0801    EMMAS-SAP - Message Type = ATTACH_REQUEST(0x41) for (ue_id = 524)
090035 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :0138    EMMAS-SAP - Received Attach Request message
090036 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0217    ATTACH REQ (ue_id = 0x0000020C) (IMSI = 314030000022993) 
090037 Sun Apr 11 17:57:30 2021 7FCE32CDF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0234    EMM-PROC:  ATTACH - EPS attach type = EPS (0)
090038 Sun Apr 11 17:57:30 2021 7FCE32CDF700 NOTIC NAS    tasks/nas/emm/Attach.c          :0473    Hit 3GPP TS 24_301R10_5_5_1_2_7_e__2 : Ignore the this duplicate ATTACH REQUEST message, continue with the previous attach procedure

[Logs.zip](https://github.com/magma/magma/files/6314211/Logs.zip)

**Comment by shehzadalee** [comment]
@jpad-freedomfi

**Comment by ulaskozat** [comment]
@rsarwad and @pruthvihebbani could you take a look at this issue?

@shehzadalee isn't T3410 a UE side timer?

**Comment by shehzadalee** [comment]
Ah yes, its the timer in UE. Thats my bad. Then there is no issue. Magma AGW behaved as per 3GPP
