### ISSUE TITLE
Orchestrator Subscriber display limited to 1000

### ISSUE THREAD

**Issue by shanku9** [magma/magma#6147]
### Your Environment

- **Version:** Staging
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator pod
- **Deployment Environment:** e.g. AWS (orc8r)

### Describe the Issue
- Subscriber display limited to 1000
- Option to jump to last page is missing 

**To Reproduce**
1. Go to 'Staging' Network 'ak_ens'
2. Click on 'Subscriber'
3. Scroll down to 'last entry <1000>'
4. Try adding new sub 'ak_60508,IMSI001011234560508,8baf473f2f8fd09487cccbd7097c6862,8e27b6af0e692e750f32667a3b14605d,ACTIVE,default,oai.ipv4'

error saving IMSI001011234560508 : an entity (subscriber-IMSI001011234560508) already exists

**Expected behavior**
Verify all the subs from Orchestrator

**Screenshots**
![orc](https://user-images.githubusercontent.com/60643026/114794583-98fbb580-9d41-11eb-8d8b-47ce6cfec7a6.png)
![orc2](https://user-images.githubusercontent.com/60643026/114794589-9bf6a600-9d41-11eb-8a64-7adda21424d7.png)

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by karthiksubraveti** [comment]
This issue is fixed
