### ISSUE TITLE
Rename snowflake dependency

### ISSUE THREAD

**Issue by mrocklin** [magma/magma#6159]
Hi all, 

This project currently uses a utility package [snowflake](https://github.com/shaddi/snowflake) which conflicts a bit with a somewhat popular data warehousing system, [snowflake](https://www.snowflake.com/).  It might be good for the Python data science community to move the `snowflake` name on PyPI to the package of the larger project.  However doing this would affect downstream users of the current snowflake package, notably this project.  

Would people here be comfortable going through a renaming process of the current snowflake package?  This would require adjusting dependencies and requirements here. 

See also https://github.com/shaddi/snowflake/issues/4

Cheers,
-matt

**Comment by shaddi** [comment]
Thanks @mrocklin. I'll work on getting this dep updated once the upstream package is renamed.

**Comment by rogerpueyo** [comment]
OK, so the problem discussed in this issue eventually appeared as per #15352.
