### ISSUE TITLE
[orc8r][helm] Update secrets on orc8r, generated by cert-manager

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#6173]
With the new [certs](https://github.com/magma/magma/tree/master/orc8r/cloud/helm/orc8r/charts/certs) helm chart, we are getting auto-generated certificates from cert-manager.

Next, we have to mount these certificates on orc8r helm charts so all the pods can use these.

**Comment by ShubhamTatvamasi** [comment]
@hcgatewood could please assign me this issue, I would like to work on this.

**Comment by ShubhamTatvamasi** [comment]
@hcgatewood @mpgermano We have hardcoded the `controller.crt` and other keys on [nginx.conf.j2](https://github.com/magma/magma/blob/master/orc8r/cloud/docker/nginx/templates/nginx.conf.j2#L77) file. Can we move this to ConfigMap, or update the helm chart to pick the file location from `values.yaml`?

**Comment by mpgermano** [comment]
Is this necessary? Unless we plan on moving certs, I don't think this is needed. If anything, it'll need to be specified as an environment variable that is also added the to the `docker-compose.yml` to ensure that the dev environment doesn't break.

**Comment by ShubhamTatvamasi** [comment]
For now, I have updated the `nginx.conf.j2` file and picking the file location from the environment variable. Will let you know once things start working properly.

**Comment by ShubhamTatvamasi** [comment]
As we are moving from secrets -> certs helm chart. Do we still have to support the old secrets helm chart?
It would be easier if we just use the new certs helm chart with Orc8r.
