### ISSUE TITLE
[Proposal] migrate clang-format formatting to Google Style

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#6187]
## Proposal

That Magma adopts Google's clang-tidy configuration, dropping its present proprietary mix of Google-plus-customizations.

## Rationale

Magma presently uses `clang-format-7` to format our codebase, using a proprietary combination of formatting directives which is `Google inspired` but not totally compliant.

Moving clang forward with the recent `Ubuntu 20.04` images, which contains `clang-format-11` by default - has highlighted that our proprietary clang-format configuration is not totally stable across clang format revisions.

Additionally, there is growing interest in turning up e.g. `cpplint` - for C++ code base linting using the Google Style guide.  While we could disable the suite of analysis that implicates google formatting, it would be perhaps cleaner to simply use Google Style. See PR #6163.

**Comment by electronjoe** [comment]
@rdefosse for visibility and any input by OAI

**Comment by rdefosse** [comment]
@electronjoe

What are the differences that `clang-format-11` brings compared to `clang-format-7`?

Honestly I don't care about the tool. As long it does the job.

@lionelgo might have a better insight on this. They are planning to migrate most of the MME C code to C++.

Regards
Raphael

**Comment by lionelgo** [comment]
@rdefosse , @electronjoe I agree to keep/get things simple, so I agree.

**Comment by amarpad** [comment]
Lets also add the following to for the Cmake files
Tabs - 4 spaces, indentation 2 spaces, continued indentation 4 spaces, col limit 80 cols, just to keep it similar to the google standards.

**Comment by electronjoe** [comment]
This Proposal needs a migration strategy documented. Ordered as proposed below.

1. Ideally we would have a clang-format CI linter enabled which would block commits that reverted style during transition
1. Repo updates in one commit
    1. Remove the custom clang format configuration file (`/.clang-format`)
    1. Update all clang-format calls to specify Google style (builtin to clang-format)
    1. Apply Google style clang-format-7 repo-wide
1. Developer Environment
    1. Update dockerfile environments to clang-format-11
    1. Check for any formatting differences, apply if they exist (may well not)
    1. If clang-format version is consequential, update vagrant environments to clang-format-11
