### ISSUE TITLE
Unable to run vagrant on magma/lte/gateway 

### ISSUE THREAD

**Issue by arpitcoder** [magma/magma#6196]
### Your Environment

- **Version:**
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ShubhamTatvamasi** [comment]
Hi @arpitcoder, could you please start a [discussion](https://github.com/magma/magma/discussions) for this instead of an issue. This is not a bug on the platform.
