### ISSUE TITLE
Connect local gateway to local cloud

### ISSUE THREAD

**Issue by qinganrice** [magma/magma#6208]
Your Environment

- Version: Master
- Affected Component: Orchestrator, Access Gateway
- Affected Subcomponent: Connect local gateway to local cloud
- Deployment Environment: Ubuntu Vagrant (AGW)

### Describe the Issue

I followed the quick start guide but failed to connect local LTE gateway to local cloud. After I run "sudo tail -f /var/log/syslog", the following thing reported. I prepare to connect Magma with srsLTE eNB. Will fluent bit errors and this info (root:mme non_eps_service_config is not SMS_ORC8R, sleeping) affect it or I can ignore them? Thanks~

<img width="892" alt="Screen Shot 2021-04-18 at 7 43 38 PM" src="https://user-images.githubusercontent.com/82441879/115168836-d4ee9c00-a0ee-11eb-9e8e-8e857c1e3c74.png">

<img width="892" alt="Screen Shot 2021-04-18 at 7 43 38 PM" src="https://user-images.githubusercontent.com/82441879/115168859-eb94f300-a0ee-11eb-9520-b4c710efcbf0.png">

Apr 18 12:22:20 magma-dev kernel: [21061.845034] HTB: quantum of class 10001 is small. Consider r2q change.
Apr 18 12:22:20 magma-dev pipelined[24709]: INFO:pipelined.qos.common:final_qos_state -> {}
Apr 18 12:22:20 magma-dev pipelined[24709]: INFO:pipelined.qos.common:final_redis state -> <redis_collections.QosStore at QosManager {}>
Apr 18 12:22:20 magma-dev pipelined[24709]: INFO:ArpController:Setting local eth_dst to gtp_br0 for ip 10.1.0.1
Apr 18 12:22:20 magma-dev pipelined[24709]: INFO:ArpController:Setting default eth_dst to gtp_br0
Apr 18 12:22:20 magma-dev pipelined[24709]: INFO:InOutController:Nat is on
Apr 18 12:22:20 magma-dev pipelined[24709]: INFO:UplinkBridgeController:Delete all flows: ovs-ofctl del-flows uplink_br0
Apr 18 12:22:21 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:23 magma-dev eventd[24624]: 18 Apr 12:22:23 ntpdate[24624]: adjust time server 69.1.1.251 offset -0.088815 sec
Apr 18 12:22:23 magma-dev systemd[1]: Started Magma eventd service.
Apr 18 12:22:24 magma-dev eventd[25159]: INFO:root:Starting eventd...
Apr 18 12:22:24 magma-dev eventd[25159]: INFO:root:Listening on address 127.0.0.1:50075
Apr 18 12:22:25 magma-dev magmad[24505]: ERROR:root:GetServiceInfo Error for eventd! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Apr 18 12:22:26 magma-dev mme[24921]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:33] Override file not found for service redis
Apr 18 12:22:26 magma-dev sctpd[6331]: I0418 12:22:26.485667  6670 sctpd_downlink_impl.cpp:31] SctpdDownlinkImpl::Init starting
Apr 18 12:22:26 magma-dev sctpd[6331]: I0418 12:22:26.485690  6670 sctpd_downlink_impl.cpp:34] SctpdDownlinkImpl::Init reusing existing connection
Apr 18 12:22:26 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:30 magma-dev sessiond[24584]: I0418 12:22:30.343293 24742 LocalSessionManagerHandler.cpp:61] Pipelined has been restarted, attempting to sync flows, old epoch = 0, new epoch = 1618748539
Apr 18 12:22:30 magma-dev sessiond[24584]: I0418 12:22:30.344625 24584 LocalSessionManagerHandler.cpp:193] Sending a setup call to PipelineD with epoch: 1618748539
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:GYController:Received Setup request with epoch - 1618748539, current epoch  is - 1618748539
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:EnforcementController:Received Setup request with epoch - 1618748539, current epoch  is - 1618748539
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:EnforcementStatsController:Received Setup request with epoch - 1618748539, current epoch  is - 1618748539
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:EnforcementController:Initialized proxy_controller <magma.pipelined.app.he.HeaderEnrichmentController object at 0x7fc816f48160>
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:GYController:Initialized proxy_controller <magma.pipelined.app.he.HeaderEnrichmentController object at 0x7fc816f48160>
Apr 18 12:22:30 magma-dev pipelined[24709]: ERROR:EnforcementStatsController:1330 bytes total not reported.
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:EnforcementStatsController:Recovered enforcement stats
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:EnforcementStatsController:Initialized proxy_controller <magma.pipelined.app.he.HeaderEnrichmentController object at 0x7fc816f48160>
Apr 18 12:22:30 magma-dev pipelined[24709]: INFO:InOutController:Received Setup request with epoch - 1618748539, current epoch  is - 1618748539
Apr 18 12:22:31 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:37 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:42 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:47 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:52 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:22:55 magma-dev systemd[1]: Started Magma envoy service.
Apr 18 12:22:55 magma-dev envoy_controller[24674]: I0418 12:22:55.186382   24674 control_plane.go:89] OnStreamOpen 1 open for
Apr 18 12:22:55 magma-dev envoy_controller[24674]: I0418 12:22:55.186397   24674 control_plane.go:89] OnStreamOpen 2 open for type.googleapis.com/envoy.api.v2.Cluster
Apr 18 12:22:55 magma-dev envoy_controller[24674]: I0418 12:22:55.187710   24674 control_plane.go:98] OnStreamRequest
Apr 18 12:22:57 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:23:02 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:23:07 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:23:10 magma-dev envoy_controller[24674]: I0418 12:23:10.184180   24674 control_plane.go:89] OnStreamOpen 3 open for type.googleapis.com/envoy.api.v2.Listener
Apr 18 12:23:10 magma-dev envoy_controller[24674]: I0418 12:23:10.184547   24674 control_plane.go:98] OnStreamRequest
Apr 18 12:23:12 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:23:14 magma-dev control_proxy[24756]: 2021-04-18T12:23:14.270Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 1966bytes 0.010s
Apr 18 12:23:14 magma-dev magmad[24505]: INFO:root:Processing config update gw1
Apr 18 12:23:14 magma-dev eventd[25159]: ERROR:root:Connection to FluentBit failed: [Errno 111] Connection refused
Apr 18 12:23:14 magma-dev eventd[25159]: INFO:root:FluentBit (td-agent-bit) may not be enabled or configured correctly
Apr 18 12:23:14 magma-dev eventd[25159]: ERROR:root:Connection to FluentBit failed: [Errno 111] Connection refused
Apr 18 12:23:14 magma-dev eventd[25159]: INFO:root:FluentBit (td-agent-bit) may not be enabled or configured correctly
Apr 18 12:23:16 magma-dev control_proxy[24756]: 2021-04-18T12:23:16.778Z [127.0.0.1 -> state-controller.magma.test,8443] "POST /magma.orc8r.StateService/ReportStates HTTP/2" 200 5bytes 0.018s
Apr 18 12:23:16 magma-dev magmad[24505]: INFO:root:Checkin Successful! Successfully sent states to the cloud!
Apr 18 12:23:16 magma-dev magmad[24505]: INFO:root:[SyncRPC] Got heartBeat from cloud
Apr 18 12:23:17 magma-dev smsd[24544]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 18 12:23:17 magma-dev state[24595]: DEBUG:root:Check state
Apr 18 12:23:17 magma-dev state[24595]: DEBUG:root:Not re-syncing state. No local state found.
Apr 18 12:23:17 magma-dev state[24595]: DEBUG:root:Not replicating state. No state has changed!
Apr 18 12:23:17 magma-dev state[24595]: DEBUG:root:Not garbage collecting state. No state to delete!
Apr 18 12:23:17 magma-dev state[24595]: DEBUG:root:
Apr 18 12:23:17 magma-dev control_proxy[24756]: 2021-04-18T12:23:17.514Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 7bytes 0.004s
Apr 18 12:23:17 magma-dev policydb[24589]: INFO:root:Processing 0 SID -> apn -> policy updates
Apr 18 12:23:17 magma-dev control_proxy[24756]: 2021-04-18T12:23:17.514Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 7bytes 0.003s
Apr 18 12:23:17 magma-dev policydb[24589]: INFO:root:Processing 0 rating group updates
Apr 18 12:23:17 magma-dev control_proxy[24756]: 2021-04-18T12:23:17.514Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 7bytes 0.004s
Apr 18 12:23:17 magma-dev policydb[24589]: INFO:root:Processing 0 policy updates (resync=True)
Apr 18 12:23:18 magma-dev control_proxy[24756]: 2021-04-18T12:23:18.026Z [127.0.0.1 -> streamer-controller.magma.test,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 7bytes 0.006s

**Comment by Milind-Blaze** [comment]
Is there some clarity on this? Can the fluent bit errors and the (root:mme non_eps_service_config is not SMS_ORC8R, sleeping) message be safely ignored?
