### ISSUE TITLE
Toward Edge Cloud Gateways 

### ISSUE THREAD

**Issue by arunuke** [magma/magma#6248]
**Problem Statement - The Why**

Magma’s AGW services implement the control and data elements providing 3GPP interfaces and functions at the edge. AGW components are deployed as systemd services requiring specialized packaging based on the targeted host operating system. This limits the portability of the gateway across multiple architectures and platforms while simultaneously adding unique processes to the CI/CD tool chain targeted exclusively for the gateway.

The systemd driven processes also require a traditional, process-based lifecycle management which is markedly different from the Cloud components of Magma which are managed in a Cloud-native fashion. This difference is especially exacerbated in an on-prem Magma deployment where the Cloud services are managed using a different heuristics under a kubernetes cluster while the AGWs cannot extend the same benefits despite the availability of a cluster manager.

**Proposal - The What**
All AGW systemd services will be containerized to ensure higher levels of portability across multiple platforms. The containerized AGW services will be managed through a k8s controller. 
With AGWs running on a common Cloud platform at the Edge, they can be co-hosted with 5G applications such as AR/VR, Video Streaming and other low latency workloads to further enhance the local breakout use-case.

Three different containerized models are considered as part of the proposal. In the first iteration, titled “Containerization”, all services that are part of a single AGW bare-metal deployment are grouped together in pods to represent a single k8s service. This will provide portability for AGWs to run on any k8s environment and it will initially be available for Cloud HA instances. In the second iteration, titled “Disaggregation'', AGW services that are shared by multiple services can be spun out as a stand-alone service that can be used by multiple AGWs on the same host. In the third iteration, titled “Scaling”, individual processes that make up an AGW are grouped together based on their respective scaling profiles. This would allow the AGW to be scaled on specific vectors that need to be scaled instead of scaling it uniformly across all services.

Three different Edge Cloud Control Planes are considered as part of the proposal. In the simplest use-case (‘local’), every AGW node is configured to act as both kubernetes leader and follower nodes making up a fully localized failure domain. In an expanded use-case (‘local-distributed’), where there are more than three gateways in a cluster, the kubernetes Controller services can optionally be split across three nodes to expand the failure domain and manage additional new gateways added seamlessly. In this scenario, only the first three gateways would perform dual roles as leader and follower while any new gateway added would be added only as a follower node. In a split architecture (‘remote’) that could be considered for large AGW deployments, another on-prem kubernetes cluster can be used to manage all gateways. This could either be an on-prem deployment of Magma which inherently has a kubernetes control plane used to manage the Orchestrator or a distributed deployment that runs one or more kubernetes leader instances on low-powered, low-cost devices (ex: raspberry pi). Expanding on the hybrid cloud use-case, the cluster could be managed by a Cloud provider service as well.

**Comment by electrocucaracha** [comment]
In order to support lower-cost devices like raspberry pi, the container images need to be created with `linux/arm64` [buildx](https://www.docker.com/blog/multi-arch-images/) platform which may need changes in the AGW services' source code.

**Comment by amarpad** [comment]
Just to make sure if ever we realize our dream of running in an eNB we can still do it, i.e. we don't preclude that option due to our service control plane.
The way I see this is that there are enough edges out there that deploy the control plane which is k8s we need to play nicely there, but I haven't fully convinced myself that it is truly the way to do it for the site solution model where we run on an AGW hardware or even better on a board inside the eNB.
Containerization is of course a much better way of packaging things than our current apt dependency chains.

**Comment by arunuke** [comment]
@shaddi and @pshelar have brought this up a few times as well. As you rightly point out, two of the deployment models available (Cloud provider infrastructure and on-prem) have a requirement that there be a k8s controller accessible which indicates AGW containers will use the same control plane and we just "need to play nicely". The concern however is applicable to the scenario where Orc8r runs in the cloud and there is intermittent/undefined connectivity to the gateways.

One of the stated benefits behind containerization is the ability to go to a single type of artifact that can be used across embedded, physical, virtual and containerized form factors. In the 1.7 time frame, I have an action item to measure overhead of running a lightweight k8s controller on the gateway itself. Even in that case, the issue would impact scenarios where there are less than three radios/gateways at a site since for 3+, only three nodes need to run the clustered control plane.

k3s, a CNCF project now that provides a [light weight k8s control plane](https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/), has a single CPU/512 MB minimum requirement while microk8s has [similar](https://github.com/ubuntu/microk8s/issues/319) requirements too. I intend to start with using these numbers as baselines.
