### ISSUE TITLE
[NMS] v1.4. Adding LTE network under organization "Not Found"

### ISSUE THREAD

**Issue by ndacic** [magma/magma#6252]
### My Environment

- **Version 1.4**
- **Affected Component:** Orchestrator/NMS
- **Deployment Environment:** On premises, on Ubuntu 20.04, on minikube. Running WebUI with:
kubectl -n magma port-forward svc/nginx-proxy 8443:443

###Issue
Problem is with Magma's NMS's multitenancy functionality. 

![image](https://user-images.githubusercontent.com/82126098/115465508-040c2700-a22f-11eb-83d1-69c619b9de07.png)

I added new organization and logged into its NMS. 

![image](https://user-images.githubusercontent.com/82126098/115466085-db386180-a22f-11eb-9879-3b130d59aa5c.png)

In previous versions it was possible to add LTE network with several RAN/EPC config possibilities. 
All orc8r pods and services are running properly with no issues:
Under it I tried adding LTE network but I get error "Not found":

![image](https://user-images.githubusercontent.com/82126098/115465829-7846ca80-a22f-11eb-8414-524cd2a4ba41.png)

**To Reproduce**
1. Go to 'master organization', Under it crate new Organization. 
2. Allow access to all network for it. 
3. Create super user for that particular organization. 
4. Go to organization NMS page.
5. Try adding Lte network under it.

**Expected behavior**
It is expected that new network appears under created organization.

**Comment by karthiksubraveti** [comment]
In 1.4, we moved to service mesh architecture. This should work if lte chart is deployed. @ndacic can you check if this is installed. In the pod output, it doesn’t look like lte pods are running. Can you run that and check this again. For now I’ll go ahead and close this issue. Feel free to open it if this doesn’t work even after deploying it with lte chart

**Comment by ndacic** [comment]
@karthiksubraveti you were right mate 👍 Thanks a lot !!!
So for the rest of the magma newbies like myself. Go to  $MAGMA_ROOT/lte/cloud/helm/lte-orc8r/
Copy values.yaml file in the same directory name it like you wish 
Rename docker repo, image name and its tag like you did in a orc8r directory. you will need to change it for controller only here
After that run:
helm dep update
helm install orc8r --namespace magma . --values=<path-to-values-file> 

Helm should install 4-5 new pods on your minikube cluster. 

After that adding LTE network is easy through GUI.
