### ISSUE TITLE
[s1aptest] TestAttachDetachRarTcpDataWithHE is flaky / or broken

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#6254]
### Your Environment

- **Version:** master

### Describe the Issue
TestAttachDetachRarTcpDataWithHE seems to be flaky.
See here for the test insights: https://app.circleci.com/insights/github/magma/magma/workflows/agw/tests?reporting-window=last-90-days&branch=master

* 0% success rate
* failed in the last 7 runs out of 10
<img width="1371" alt="Screen Shot 2021-04-20 at 4 43 36 PM" src="https://user-images.githubusercontent.com/37634144/115467731-95f83d80-a1f7-11eb-9ab7-11e2a30b2b35.png">

**Comment by themarwhal** [comment]
Assigning it to @pshelar as he was the author of the test here: https://github.com/magma/magma/pull/4256

**Comment by themarwhal** [comment]
Disabled here : https://github.com/magma/magma/pull/6322

But not closing the issue obviously because its still broken

**Comment by themarwhal** [comment]
This was actually never resolved - reopening.

**Comment by pshelar** [comment]
@vikramgreddy can you have  a look at this.
