### ISSUE TITLE
agw_install_ubuntu.sh

### ISSUE THREAD

**Issue by shanku9** [magma/magma#6255]
Directory doesn't exists /etc/network/interfaces.d
Configs are not copied to eth0 or eth1

```
root@vagwu1:/home/magma# ls /etc/network
 if-pre-up.d  if-up.d  interfaces  
```
https://github.com/magma/magma/blob/861b04dbd7809a2ad9a244e4718dcc60de89d8fb/lte/gateway/deploy/agw_install_ubuntu.sh#L74

**Comment by pshelar** [comment]
fixes in 1.5
