### ISSUE TITLE
[Proposal] Tech debt week process documentation

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#6265]
Tech Debt Week is a rather complex operation - and we would benefit from a well documented and repeatable process for future use.

**Comment by electronjoe** [comment]
I've received feedback that an always-available Video Conference room is too heavy weight - and a more 1:1 on demand solution should be established.

**Comment by electronjoe** [comment]
I've received feedback that we should allow for the community to suggest Tech Debt Week tasks.

**Comment by hcgatewood** [comment]
@electronjoe what's the status of this proposal?
