### ISSUE TITLE
Toward AGW availability improvements

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#6267]
There have been repeated requests for a plan to address AGW Availability.  Though there have been some presentations within Magma giving thoughts - we lacked a public and thorough documentation of possible courses of action, and a staging of efforts.

A proposal seems a reasonable place to document this - and the proposal process seems a reasonable one for getting the plan vetted.

**Comment by hcgatewood** [comment]
Closed as accepted, with slightly altered title
