### ISSUE TITLE
[CI][PrecommitCheck] Add a sanity check to bring up all FeG, CWAG containers to see everything builds and doesn't crash

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#6284]
-> We do not check at the precommit stage that docker containers are healthy for FeG
-> We do not check at the precommit stage that docker containers are healthy for CWAG

We can do a simple check like this: https://sourcegraph.com/github.com/magma/magma/-/blob/cwf/gateway/fabfile.py#L344:5

**Comment by uri200** [comment]
Oh i think we opened the same issue.

I put some code here for FEG https://github.com/magma/magma/pull/6288

But we can't merge it until that issue is fixed
