### ISSUE TITLE
[lte][agw] AGW instability on scaling tests

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#6325]
### Your Environment

- **Version:** 1.5.0-1618544129-eb466962
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal (AGW), vm (AGW)

### Describe the Issue

Run spirent tests with 300 UEs, 10 UE/sec attach for > 4 hours. AGW ends up in a bad state with attach timeouts. 

After 11 iterations, we also start observing implicit detaches due to ICS request timeouts on MME side. The timers seem to expire early.

**Expected behavior**
no instability, no timeouts.

**Screenshots**
Spirent test dashboard capture:

![Screen Shot 2021-04-22 at 5 46 11 PM](https://user-images.githubusercontent.com/16007119/115801929-c2948c80-a392-11eb-87b4-11bf726671ce.png)

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ulaskozat** [comment]
LOGS and pcap: https://fburl.com/1dvkger3

**Comment by ulaskozat** [comment]
The following UEs states were left over after I stopped the test:
IMSI001011234560129:MME
IMSI001011234560039:MME

A quick inspection reveals that these UEs suffered from excessive message latency in-between threads where implicit detach, ICS request/response and attach accept messages are interleaved in a funny manner that leads a state where MME app thinks UE is registered, but the rest of the services have already released the resources for such UEs. Sequence of events roughly:

- MME gets session accept and starts ICS request process. ICS timer gets started.
- ICS timer expires but S1AP still have not sent out ICS request. MME starts implicit detach procedure and session gets deleted.
- ICS request is out but S1AP context is not yet released due to implicit detach procedure.
- S1AP receives Attach Accept and since S1AP context is still intact sends out the message to MME app. MME app accepts it and transitions the UE state to Registered.

**Comment by ulaskozat** [comment]
@talkhasib can you also add your observations related to MME here...

**Comment by ekowtaylor** [comment]
@ulaskozat @ardzoht I believe this issue has been resolved now. Can this be closed?
