### ISSUE TITLE
New Orc8r deployment on certain AWS region does not work

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#6326]
### Your Environment

- **Version:** 1.5 master
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator pod/service 
- **Deployment Environment:** e.g. AWS (orc8r)

### Describe the Issue

**To Reproduce**
- Follow instruction on orc8r deployment - https://docs.magmacore.org/docs/orc8r/deploy_intro on aws eu-west-3 region (paris)
- error received while doing terraform apply
```
Error: Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.m4.large, Engine=postgres, EngineVersion=9.6.15, LicenseModel=postgresql-license. For supported combinations of instance class and database engine version, see the documentation.
	status code: 400, request id: f56c501b-9eae-4aaa-8c07-1a29d62728fe

  on .terraform/modules/orc8r/orc8r/cloud/deploy/terraform/orc8r-aws/db.tf line 14, in resource "aws_db_instance" "default":
  14: resource "aws_db_instance" "default" {
```
while checking aws help we saw they don't support db.m4.large instance type on every region. We change (orc8r_db_instance_class) that param from terraform file, and it worked after that change.
however, we should give this details in faq or readme page so that users can make the required change from start.

**Expected behavior**
our readme/faq should cover option to change this param if they wish to deploy on certain aws region.

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by karthiksubraveti** [comment]
We do expose the instance class as a variable 
https://github.com/magma/magma/blob/master/orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf#L213

which a user can modify and it is specified in the README page as well
https://github.com/magma/magma/tree/master/orc8r/cloud/deploy/terraform/orc8r-aws

That being said it is pretty easy to fail here. I will add some prechecks around this in orcl and in documentation

**Comment by ShubhamTatvamasi** [comment]
@karthiksubraveti I can work on this, but I will be needing an AWS account for it.

**Comment by karthiksubraveti** [comment]
Hey @ShubhamTatvamasi, Can you create your personal AWS account for verifying this. Running `orcl install prechecks` shouldn't really consume any resources. It will mainly use the account credentials for running aws cli commands. 

One minor point is that you might have to add a default value in vars.yml for 
https://github.com/magma/magma/blob/master/orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
to contain same default as https://github.com/magma/magma/blob/master/orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf#L213
i.e make the following change in vars.yml
```
 orc8r_db_instance_class:
    Description: RDS instance Type for Orchestrator DB.
+  Default: "db.m4.large"
    Type: string
    Required: false
    ConfigApps:
      - tf
```
 


Based on the region we configure, we need to run 
https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-type-offerings.html
as a part of our db precheck and ensure that the variables 'orc8r_db_instance_class' specifies
a class available in this region. 
https://github.com/magma/magma/blob/master/orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/platform/tasks/rds.yml

**Comment by ShubhamTatvamasi** [comment]
Okay, let me look into this.

**Comment by karthiksubraveti** [comment]
@milapjoshi Have fixed the issue in this PR https://github.com/magma/magma/pull/7717/files

**Comment by nstng** [comment]
If I understand the conversation above correctly, then this is already solved - will close for now
