### ISSUE TITLE
[MME] Create  Redis table to store  ip, IMSI and type of subscriber

### ISSUE THREAD

**Issue by uri200** [magma/magma#6333]
Right now MME needs to call `get_subscriber_id_from_ipv4` that calls mobilityd http://github.com/magma/magma/blob/master/lte/gateway/c/oai/tasks/sgw/sgw_paging.c#L36-L36 
every time there is a paging request which creates a new GRPC call just to extract the IMSI

Also for inbound roaming users, this is not working because we don't store the IP, so we can't find them.

To be able to find those users we need a Redis table that stores the mapping of imsi, ipv4, ipv6 and type of subscriber (s11 or s8).  The key will be IP (either ipv4 or ipv6)

This table will be used to find out the IMSI of subscribers when paging is needed. 

Note that this table will may be updated (created entry and delete entry) by two different tasks, so maybe locks are required to avoid write access at the same time. To avoid having those locks lets try to implement the functions that are going to add/delete entries on that table in mme task. Reading from redis is not a problem and can be done by sp task and sp_s8 task

**Comment by rsarwad** [comment]
@uri200 Do we need type of subscriber as part of hash table. Once imsi is fetched from hash table, Paging request will be sent to mme and Paging Request has only imsi.

**Comment by uri200** [comment]
Yes the type of subscriber is needed so the api can decide where to send send the paging request, either sp or sp_s8. 

So the table will be a dictionary with a list of parameters.

```
{Ip: [imsi, type_subcriber]}
```

Type of subsciber should be stored at the same time we store imsi.

To avoid having to have locks:

MME task should be the one responsible to create that entry in the table when a new session is created.

MME should be responsible of deleting the entry once the subscriber is gone

For dual stack (ipv4 + ipv6) we will have to store two entries

**Comment by uri200** [comment]
Per our yesterday discussion we will implement the mapping table to find the IMSI based on the IP and forward the pagging request to the specific tast (either sp or sp_s8 tasks).

- Paging application on OAI will have to consult the table to know if this UE is sp (s11) or sp_s8 (s8) UE
- sp_s8 task will include a new function similar to sp spg_send_paging_request, but with its own logic




![image](https://user-images.githubusercontent.com/16157139/116133563-b60a7f80-a683-11eb-8283-ba2f334c3935.png)

**Comment by ekowtaylor** [comment]
Can this be closed now?

**Comment by rsarwad** [comment]
Once changes on PR, https://github.com/magma/magma/pull/7125 are merged to master; This issue can be closed.
