### ISSUE TITLE
Disk usage reporting on NMS off

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#634]
Disk usage reporting on NMS is off by one point.

![sshot_20190917_a](https://user-images.githubusercontent.com/6918709/65023084-d23c2b80-d93a-11e9-8f17-3c202dfe7c47.png)

**Comment by Scott8440** [comment]
Do you mean that the datapoint at 330% is wrong? If so, what data source are you using to discover the "correct" value? The NMS is querying prometheus which is storing the data.

**Comment by bmurithi** [comment]
Prometheus data queried via the API was correct

**Comment by Scott8440** [comment]
What was the query you ran on the api and was it the same query that the NMS is running? What values did it return that looked correct?

**Comment by bmurithi** [comment]
This is an invalid issue @Scott8440 

I read this off the aggregate metric tab on the NMS.
So perhaps this needs to be averaged out or nuked as an aggregate metric.
