### ISSUE TITLE
[s1aptest] test_attach_detach_with_he is failing on master

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#6344]
The test has been failing pretty consistently.
<img width="1365" alt="Screen Shot 2021-04-23 at 8 19 08 AM" src="https://user-images.githubusercontent.com/37634144/115877001-94ec2980-a40c-11eb-8daa-cc5202aa237d.png">

This combined with https://github.com/magma/magma/issues/6254 makes me wonder if HE has regressed.

**Comment by themarwhal** [comment]
@pshelar, I'm assigning this to you since I think you are the HE owner? (Please reassign if I'm wrong :) )

**Comment by pshelar** [comment]
same as issue https://github.com/magma/magma/issues/6439
