### ISSUE TITLE
[CI] Filter generated targets of lte/gateway/c from code coverage

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#6348]
## Summary

Today, code coverage includes some 10_000s of lines of auto-generated code, often from `asn1c` compiler. These targets could reasonably be omitted from our code coverage, yet are included today.

Additionally, today our test code itself is considered in our coverage statistics (not our objective).

## Approach

The path forward is not yet certain - there are probably a couple options that should be prototyped.

1. One option is to use `lcov` [filtering support](https://wiki.documentfoundation.org/Development/Lcov#Remove_.2F_filter_out_remaining_unwanted_stuff_from_tracefile)
    1. See Filtering out auto-generated code below
1. Another option is to pull in some public tool
    1. e.g. something like [lcov-filter](https://github.com/bahmutov/lcov-filter)
    1. But ideally more maintained / more stars / activity

### Filtering out auto-generated code

Code Coverage is executed today in CircleCI - by use of the `coverage` Makefile target in [/lte/gateway/Makefile](https://github.com/magma/magma/blob/2c05b1b20405a6f9c295ee811ddf1fab3b496b0f/lte/gateway/Makefile#L278-L285).  This target has dependencies on `base_coverage` (to determine what lines of code *should* be covered). And then the individual test coverage collection e.g. `coverage_oai`, `coverage_session_manager`, `coverage_sctpd`.

In order to filter out undesired coverage information, I believe `base_coverage` and maybe each of the `coverage_<target>` need to be amended with [lcov filtering](https://wiki.documentfoundation.org/Development/Lcov#Remove_.2F_filter_out_remaining_unwanted_stuff_from_tracefile).

### Filtering out test coverage

We should explore whether existing lcov filters make this easy enough (they may not) - and if not explore e.g. [lcov-filter](https://github.com/bahmutov/lcov-filter) or similar projects (admittedly, this project seems unmaintained and has ~no GH stars).

## Testing

Pushing a [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for the `magma/magma` repo will run the CircleCI jobs. Once the Coverage sub-job is complete, you can inspect the log files and you will find that the CodeCov shell script finalizes by emitting a URL to CodeCov analysis for this PR (**note this takes a couple hours to generate - our tests take a long time to build and run).  Opening that CodeCov log URL, you should observe coverage data and it should now omit the newly-filtered targets.

**Comment by themarwhal** [comment]
I removed test files from coverage here: https://github.com/magma/magma/pull/5719 :)

**Comment by electronjoe** [comment]
> I removed test files from coverage here: #5719 :)

Excellent! Looks like somebody can mimic your approach for filtering - to filter out compiler generated targets by path.

Thanks for dealing with the test coverage part of this!
