### ISSUE TITLE
MME ue_connected metric keeps growing

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#636]
> Magma Version: 0.3.78-1567853565-a69a32fa

`ue_connected` MME metric on access gateway keeps growing without reporting the actual number of connected UEs at point-in-time.

**Comment by bmurithi** [comment]
This has been tracked down to a UE connecting with the incorrect APN. 
After fixing the APN on the UE, and restarting `magma@mme` the correct ue_connected counts.

**Comment by ssanadhya** [comment]
Closing this issue as it was resolved by correct APN configuration.
