### ISSUE TITLE
X2 Handoff - UE ping/pong between sites ultimately causing ICS failures

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#6365]
### Your Environment

- **Version:** 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), 

### Describe the Issue
* UE Does a handoff from src_eNB (100.96.228.117) to target_enb (100.96.228.116). PathSwitchRequest is successfully acknowledged (timestamp  19:32:16 in MME log); eNB/MME S1AP IDs (2/35)
* UE transitions to old eNB and sends SR (6.3 seconds after PathSwitchAck; packet 177 in pcap) and uses S1AP IDs (2/49). Confirmed this by matching the mTMSI shown in SR with mme log.
* target_enb also sends ICS request using IDs (2/35) (Pkt 179). 
* MME releases context in target eNB 4 seconds later. 
* eNB resets S1AP IDs 2/49. 
* UE sends SR again (same mTMSI as above) in Pkt 196 using eNB_S1AP_ID 50.
* MME attempts to setup IC on src enb (100.96.228.117) using new S1AP IDs (2/50). 
* eNB sends ICS failure due to "encryption-and-or-integrity-protection-algorithms-not-supported"
* Context Release procedure commences; MME re-sends Context Release command in packet 205 for previously released context. S1AP IDs 2/49 were reset in packets 193 and 194. 

Comparing ICS Requests between packet 198 (failed one) and a good one (packet 12), it seems that `encryptionAlgorithms` and `integrityProtectionAlgorithms` are all set to `0`. This might be the issue? 

![image](https://user-images.githubusercontent.com/38921899/115930224-f11b7180-a43d-11eb-8842-ffb570fbb707.png)
![image](https://user-images.githubusercontent.com/38921899/115930230-f4aef880-a43d-11eb-8b13-9e6fee71215c.png)

**To Reproduce**
* Do back and forth ping-pongs between eNBs connected to the same AGW. 

**Expected behavior**
* ICS failure needs to be mitigated
* Context release commands for already acknowledged S1-AP Reset messages should be handled properly? not sure on the phrasing here but I think MME shouldn't be releasing this context after acknowledging reset request previously. 

[Archive.zip](https://github.com/magma/magma/files/6368074/Archive.zip)

PCAP and MME log attached.

**Comment by sudhikan** [comment]
Saw this issue when not doing an X2 handoff today... attaching logs and pcap here. 
[Archive 4.zip](https://github.com/magma/magma/files/6437070/Archive.4.zip)

**Comment by ekowtaylor** [comment]
@shaddi, have you made any progress on this issue?

**Comment by ulaskozat** [comment]
@sudhikan there is indeed a bug in AGW where path switch request seems to overwrite the security capabilities incorrectly. @rsarwad will raise a PR on this one. @rsarwad could you give an estimate on this one?
