### ISSUE TITLE
[Ubuntu][AGW] syslog seems to reset to blank periodically on ubuntu AGW

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#6366]
version: 1.5

Not sure on the exact replication steps, but I've found that occasionally /var/log/syslog is reset to a blank file. @ardzoht says journalctl seems to be working correctly. 

If I run `sudo service rsyslog restart` syslog starts to fill up again.

**Comment by themarwhal** [comment]
According to pravin it is a logrotate issue.
* After `service rsyslog restart` /var/log/syslog gets filled
* at some point syslog goes empty and all logs go to syslog.1

**Comment by talkhasib** [comment]
The issue will happen again on the next log rotate.
Maybe we should do this for a quick fix
In the /etc/logrotate.d/rsyslog file, replace 
invoke-rc.d rsyslog rotate > /dev/null
with
invoke-rc.d rsyslog restart > /dev/null

**Comment by pshelar** [comment]
> The issue will happen again on the next log rotate.
> Maybe we should do this for a quick fix
> In the /etc/logrotate.d/rsyslog file, replace
> invoke-rc.d rsyslog rotate > /dev/null
> with
> invoke-rc.d rsyslog restart > /dev/null

would the restart rotate the log? otherwise it would fill up disk space.

**Comment by talkhasib** [comment]
> > The issue will happen again on the next log rotate.
> > Maybe we should do this for a quick fix
> > In the /etc/logrotate.d/rsyslog file, replace
> > invoke-rc.d rsyslog rotate > /dev/null
> > with
> > invoke-rc.d rsyslog restart > /dev/null
> 
> would the restart rotate the log? otherwise it would fill up disk space.

This is done "postrotate"
The "invoke-rc.d rsyslog rotate" is supposed to force the release of old file descriptors, and to tell rsyslog that it must open the files again. Restart should achieve the same. Although I did not test this yet as part of the config file. I just tried the restart manually

**Comment by themarwhal** [comment]
@talkhasib / @pshelar this issue is good to close right?

**Comment by pshelar** [comment]
yes, fix is landed master.

**Comment by jingc1413** [comment]
i have the same pro
os: Ubuntu 20.04.5 LTS \n \l
agw: 1.8.0, last updated: 2022-09-13 18:49:59
rsyslog: rsyslogd  8.2001.0 (aka 2020.01)
![image](https://github.com/magma/magma/assets/13563637/a308cf50-62d9-4830-9352-4a9b510f2b59)
![image](https://github.com/magma/magma/assets/13563637/21bf239e-aec3-4cf2-91cc-143b0aa1d998)

Everything is normal when rsyslog is first started, and it will not be written to syslog for a period of time, jourctl -f is normal
