### ISSUE TITLE
[CI] ubuntu-1604:201903-01 image doesnt have .cache folder 

### ISSUE THREAD

**Issue by uri200** [magma/magma#6369]
When `feg-build:` is run by circle ci (see here http://github.com/magma/magma/blob/master/.circleci/config.yml#L696-L696 ) we need to have `magma/.cache/feg/snowflake` and `magma/.cache/certs/rootCA.pem`  with valid files. Otherwise the services crashloop. 

Right now we have to use a workaround to manually creating rootCA and snowflake to by creating them manually on circleci.yml file (see https://github.com/magma/magma/pull/6288)

But to avoid that manual patch, the image `ubuntu-1604:201903-01` should contain  the whole content of the `.cache` folder in order to be able to run it

**Comment by ekowtaylor** [comment]
PR merged
