### ISSUE TITLE
[AGW] Run unit tests, lab tests with ThreadSan turned on

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#6384]
## Summary

Now that we have achieved Clang Build capability (#4865), we can run our tests (unit, integration) and even lab environment with [Clang's Thread Sanitizer](https://clang.llvm.org/docs/ThreadSanitizer.html).  Though the team belief is that little to no concurrency is taking place in the c/c++ of the MME and partner binaries, this is hard to maintain with use of gRPC (new context per server receive) and concurrency has leaked in.

Thread sanitizer may not find much in our present unit tests, as it often takes a particular shaped unit test to stress concurrency.  But the use in e.g. lab testing, or integration tests perhaps - would likely root out any race conditions in our codebase.

**Comment by ekowtaylor** [comment]
@electronjoe what's the latest with these tests?

**Comment by electronjoe** [comment]
I have not worked this task this sprint.
