### ISSUE TITLE
Magma Orc8r 1.5 Documentation lists nmsdb changes for main.tf

### ISSUE THREAD

**Issue by arunuke** [magma/magma#6401]
### Your Environment

- **Version:** 
1.5 
- **Affected Component:** Orchestrator, Access Gateway, or NMS
Orc8r
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
Install Documentation
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)
NA
### Describe the Issue

The "Install Orchestrator/Initialize Terraform" section still lists nms_db_password as a required change to main.tf.

**To Reproduce**
https://docs.magmacore.org/docs/next/orc8r/deploy_install

**Expected behavior**
No references to nmsdb anymore.

**Comment by karthiksubraveti** [comment]
Andrei updated this in upgrade documentation
https://docs.magmacore.org/docs/orc8r/upgrade_1_5
