### ISSUE TITLE
[lte][agw] S1 handover does not complete successfully with real handset

### ISSUE THREAD

**Issue by shaddi** [magma/magma#6429]
### Your Environment

- **Version:** 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** Bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

During testing of S1 handover with a two physical eNBs and a UE, the UE fails to successfully complete the handover procedure, with no HandoverNotify message generated by the target eNB.

**To Reproduce**
1. Set up two eNBs such that handover can occur between them (i.e., configure neighbor tables, ensure both are connected to the same MME)
2. Attach a UE to the source eNB.
3. Trigger a handover to the target eNB (e.g., by reducing signal strength of the source eNB with attenuators)
3. Observe UE perform a reconnect to the target eNB, rather than a clean handover, and fail to receive a HandoverNotify at the MME from target eNB.

**Expected behavior**
Handover should complete successfully, and the target eNB should generate a HandoverNotify message towards the MME.

**Additional context**
We performed two sets of tests. The first used a Baicells Nova 227 (firmware: RTS 3.6.6) as both source and target eNB. The second used a Baicells Nova 227 as source eNB and Airspan AirVelocity 1500 (15.17.00.1049) as a target eNB. In both cases, we used a Pixel 3 as the UE. [Logs and packet traces are attached](https://github.com/magma/magma/files/6388337/handset_testing.zip), a description is below:

- Nova 227 > Nova 227.
  - handover_nova227_nova227_pixel3_20210426_2117_s1ap_rrc.pcapng: Contains RRC trace messages from both source eNB (192.168.60.249) and target eNB (192.168.60.245), along with S1AP messages.  
  - Nova 227 debug logs exported from target eNB.
  - Note that in this test, we receive an RRCConnectionReconfigurationComplete message in the RRC trace from the *target* eNB, indicating the UE reported it had successfully completed handover to the target eNB. 
- Nova 227 > AirVelocity 1500 
  - s1_handoff_airspan_target_1323.pcapng: Source eNB 10.0.2.10, Target eNB 10.0.2.20
  - RRC tracing was not available for this test.

**Comment by Lu-yun** [comment]
Hi, follow Wayne's arrangement,  i will track this issue here continuously. I see the captured log, target eNB doesn't receive the message 3 (RRC Reconfiguration Complete), there may be UP-link interfere in the environment?

**Comment by ekowtaylor** [comment]
@shaddi what's the latest with this issue?

**Comment by shaddi** [comment]
We're still trying to root cause, and still suspect a RAN issue as the main hypothesis (either bug or as Lu-yun suggested an RF environment issue).

I'm in the process of setting up a new local testbed with open source eNodeBs to get better visibility into what's actually happening.

**Comment by shaddi** [comment]
> I see the captured log, target eNB doesn't receive the message 3 (RRC Reconfiguration Complete), there may be UP-link interfere in the environment?

Thanks @Lu-yun. Are you referring to the log in `handover_nova227_nova227_pixel3_20210426_2117_s1ap_rrc.pcapng`? If so, we can see in packet no. 45 the RRC trace message from the *target* eNodeB (192.168.60.245) indicates it does receive the `RRCConnectionReconfigurationComplete` message from the UE during the handover procedure, but we never see a HandoverNotify message generated by the target eNB. Unless I'm missing something, this seems like it rules out an uplink interference issue in the environment?

**Comment by Lu-yun** [comment]
Sorry, I missed this problem. I will continue to track this problem again.

**Comment by Lu-yun** [comment]
Theoretically, once received the RRC Reconfiguration Complete(MSG3) , then trigger Handover Notify message transferred. In addition, I see appeared some radio cause in log(handover_nova227_nova227_pixel3_20210426_2117_s1ap_rrc.pcapng). 
![image](https://user-images.githubusercontent.com/84011775/121333276-3e4e9680-c94b-11eb-8d41-0c5ee3386bcd.png)
![Dingtalk_20210609175219](https://user-images.githubusercontent.com/84011775/121333420-6211dc80-c94b-11eb-9c84-7a221b2b897a.jpg)

**Comment by Lu-yun** [comment]
Hi shaddi, is there only one test environment? By the way, in previous captured packets, RRCReconfigurationComplete is only transferred by UE, but i have not see reception on the ENB side. It's my judgment.

**Comment by talkhasib** [comment]
https://github.com/magma/magma/pull/7985 fixes a security context issue. Now we see HandoverNotify from target eNB. See pcap attached to PR.

Few issues remain as noted on PR
- Context release is ending up at the wrong eNB
- MME needs to send the release command to the source eNB once it gets the handover notify
