### ISSUE TITLE
[AGW] OVS drops packets when MTU is 1400 or more

### ISSUE THREAD

**Issue by uri200** [magma/magma#6454]
~~Our current AGW config script doesn't modify MTU of the interfaces. For some systems that value is set to 1500 so that limits the size of the packets. Any packet bigger to the MTU size is being dropped.~~

~~In teravm we are experiencing that running `inbound_roaming_01b.ntl` (note this is not an issue limited to inbound roaming, but to the AGW interfaces)~~

~~To avoid dropping packets due to its size, AGW interfaces should be configured with bigest MTU possible. For that reason we suggest AGW install script to modify MTU value to it's max~~

OVS drops packets when MTU is close to 1500 

Test can be done at teravm using gxgy05_capacity and changing MTU to 1400

**Comment by pshelar** [comment]
interface MTU is determined by MTU of the network, so AGW can not unilaterally set higher MTU on S1 or SGi interface.

**Comment by uri200** [comment]
Hey @pshelar , then I am changing the name of the issue. We need to find a way for OVS not to fail with standard MTU of 1500
