### ISSUE TITLE
AGW 1.4 -  Pipelined "import error for aioeventlet "

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#6473]
AGW 1.4 
AGW installed using 
wget https://raw.githubusercontent.com/facebookincubator/magma/v1.4/lte/gateway/deploy/agw_install.sh
bash agw_install.sh 

Following crash occurs 
Apr 28 15:58:43 M-AGW-T pipelined[20480]: Traceback (most recent call last):
Apr 28 15:58:43 M-AGW-T pipelined[20480]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Apr 28 15:58:43 M-AGW-T pipelined[20480]:     "__main__", mod_spec)
Apr 28 15:58:43 M-AGW-T pipelined[20480]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Apr 28 15:58:43 M-AGW-T pipelined[20480]:     exec(code, run_globals)
Apr 28 15:58:43 M-AGW-T pipelined[20480]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 22, in <module>
Apr 28 15:58:43 M-AGW-T pipelined[20480]:     import aioeventlet
Apr 28 15:58:43 M-AGW-T pipelined[20480]: ImportError: No module named 'aioeventlet'

More Logs 

[R14Newbuild mme issue.zip](https://github.com/magma/magma/files/6397271/R14Newbuild.mme.issue.zip)

Manually installing aioeventlet and then restarting Magma services fixes the issue. 

@pshelar @ardzoht

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/tag/v1.5.3
