### ISSUE TITLE
SUCI based registration is followed by an Identity request from AMF. this needs to be fixed

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6480]

**Comment by sureshgorijavolu** [comment]
in SIT SUCI based registration is followed by an Identity request from AMF. AMF is expected to initiate Auth procedure.

**Comment by rjha72** [comment]
The issue has been analyzed, the identity request should not be sent for the SUCI based registration. This was fixed in a build given to SIT. The fix is not there on magma-5g branch, need to ensure that the fix is propagated to magma-5g branch

**Comment by sureshgorijavolu** [comment]
issue is no longer seen on magma-5g branch.
