### ISSUE TITLE
event handler for expiry of timer T3560 

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6485]

**Comment by Kaleem-Wavelabs** [comment]
Reproduced the scenario some minor changes to ueransim 
Done the code changes at AMF side to fix the missing functionality

**Comment by Kaleem-Wavelabs** [comment]
PR: https://github.com/magma/magma/pull/7708

**Comment by Kaleem-Wavelabs** [comment]
Shared the mme binary to TeraVM for verification of the change.
Addressed the review comments shared.
Will be amending the changes.
