### ISSUE TITLE
add Unit test support for registration procedure

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6505]

**Comment by sureshgorijavolu** [comment]
Unit tests to be written using gtest suite.

**Comment by panyogesh** [comment]
It will be an ongoing task. Each sprint specific number of ut cases will be added.

**Comment by panyogesh** [comment]
May-10
1. Added few testcases for NGAP. Draft PR raised (#6750).

**Comment by panyogesh** [comment]
May-12 : 
Raised a draft PR : #6750 for the same. It covers the following testcases - 
1. unsuccess_outcome_asn  (encode/decode stream format)
2. unsuccess_outcome_pdu (encode/decode pdu format)
3. initiate_ue_message (encode/decode)
4. pdusession_resource_setup_req (encode/decode)

With that some of the memory leaks are found and fixed the pdusession_resource_setup_req. Will re-base and raise a updated PR.

**Comment by ekowtaylor** [comment]
@sureshgorijavolu is this still in progress or can the issue be closed?
