### ISSUE TITLE
add integration test scenarios and validate them on DStester

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6506]

**Comment by sureshgorijavolu** [comment]
single UE  Registration with SUCI as mobile identity
single UE  Registration with GUTI as mobile identity
single UE  Registration with SUPI as mobile identity
UE deregistration
single UE registration and deregistration in a loop
single UE periodic registration update
verify Authentication failure support on AMF
Verify Authentication reject being sent from UE is correctly processed on AMF
Validate the behavior of AMF when UE does not send registration complete 
Attempt UE Registration for No initial context response
Attempt UE Registration for No Auth Response
Attempt UE Registration for  No security mode completion
Attempt UE registration After GPRS timer expiry
Attempt a duplicate registration for a given UE
Attempt registration for an invalid IMSI
Attempt registration for an IMSI that is not provisioned in subscriber db
Register and Deregister for no ue context release 
Register and DeRegister after ue context release
Registration for security mode reject
Register and DeRegister Multiple UEs
Register and DeRegister Multiples UEs in a   loop
Register and DeRegister  Multiple UEs concurrently

**Comment by Balaji-Jatla** [comment]
17 May 2021
I am working on **verify Authentication failure support on AMF** ---   In Ds Tester , subscriber group we can select the fixed vector values in that we can configure RAND, AUTN values, if we configure wrong values it will give authentication failure as output

**Comment by Balaji-Jatla** [comment]
17 May 2021
For **single UE registration and deregistration in a loop** loop is not working for single UE's. It's only working for Multiple UE's .

**Comment by Balaji-Jatla** [comment]
18 May 2021
Validate the behavior of AMF when UE does not send registration complete -- ?(How do we test this)

Verify Authentication reject being sent from UE is correctly processed on AMF -- (It is sent from AMF not UE, @rjha72 is looking to simulate this)

**Comment by Balaji-Jatla** [comment]
For failure scenario creation we need to know how to set the Individual IE values in Ds Tester for a Particular Message.
We need KT on how to create a new Test cases and populate IE's in DS Tester , we can identify the scenario and get DS test guys to help us create test cases.

**Comment by sureshgorijavolu** [comment]
this issue is broken down into multiple smaller issues and added to sprint backlog. they will be committed independently. So this issue is no longer required. closing the issue.
