### ISSUE TITLE
AGW: in-bound-roaming: broken on Non-NAT

### ISSUE THREAD

**Issue by pshelar** [magma/magma#6508]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

Setup AGW in Non-NAT, check syslog:
```
Apr 29 09:27:20 1vagw6 systemd[1]: Starting Magma OAI MME service...
Apr 29 09:27:20 1vagw6 smsd[17765]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Apr 29 09:27:20 1vagw6 mme[29866]: Traceback (most recent call last):
Apr 29 09:27:20 1vagw6 mme[29866]:   File "/usr/local/bin/generate_oai_config.py", line 273, in <module>
Apr 29 09:27:20 1vagw6 mme[29866]:     main()
Apr 29 09:27:20 1vagw6 mme[29866]:   File "/usr/local/bin/generate_oai_config.py", line 264, in main
Apr 29 09:27:20 1vagw6 mme[29866]:     context = _get_context()
Apr 29 09:27:20 1vagw6 mme[29866]:   File "/usr/local/bin/generate_oai_config.py", line 212, in _get_context
Apr 29 09:27:20 1vagw6 mme[29866]:     "sgw_s5s8_up_ip": _get_iface_ip("spgw", "sgw_s5s8_up_iface_name"),
Apr 29 09:27:20 1vagw6 mme[29866]:   File "/usr/local/bin/generate_oai_config.py", line 44, in _get_iface_ip
Apr 29 09:27:20 1vagw6 mme[29866]:     return get_ip_from_if_cidr(iface_name)
Apr 29 09:27:20 1vagw6 mme[29866]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/misc_utils.py", line 165, in get_ip_from_if_cidr
Apr 29 09:27:20 1vagw6 mme[29866]:     ip, netmask = get_if_ip_with_netmask(iface_name, preference)
Apr 29 09:27:20 1vagw6 mme[29866]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/misc_utils.py", line 65, in get_if_ip_with_netmask
Apr 29 09:27:20 1vagw6 mme[29866]:     raise ValueError('Error getting IPv4/6 address for %s' % interface)
Apr 29 09:27:20 1vagw6 mme[29866]: ValueError: Error getting IPv4/6 address for eth0
Apr 29 09:27:20 1vagw6 systemd[1]: magma@mme.service: Control process exited, code=exited status=1
Apr 29 09:27:20 1vagw6 systemd[1]: Failed to start Magma OAI MME service.
Apr 29 09:27:20 1vagw6 systemd[1]: magma@mme.service: Unit entered failed state.
Apr 29 09:27:20 1vagw6 systemd[1]: magma@mme.service: Failed with result 'exit-code'.
```

Egress interface should not be hardcoded in the config. As discussed we shld be using `ip route` cmd to find egress device.

**Comment by uri200** [comment]
Hey @pshelar thanks for finding that

Can you help us understand how to decide the proper way to decide the route in case of `Non-NAT` dynamically?

```
vagrant@magma-dev:~$ ip route
default via 10.0.2.2 dev eth0
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
10.1.0.0/24 dev mtr0 proto kernel scope link src 10.1.0.1
10.5.0.0/24 dev envoy_cntr proto kernel scope link src 10.5.0.2
127.0.0.0/24 dev ipfix0 proto kernel scope link src 127.0.0.10
192.168.60.0/24 dev eth1 proto kernel scope link src 192.168.60.142
192.168.128.0/24 dev gtp_br0 scope link
192.168.129.0/24 dev eth2 proto kernel scope link src 192.168.129.1
```


On FEG I had to solve the same issue and the way I did it is pinging the IP and checking the interface it was using. But there may be a better way for AGW

**Comment by pshelar** [comment]
we can use `ip route get $PGW_IP` command to get egress interface and then read IP address of the interface.

**Comment by uri200** [comment]
There is an issue here: to know the PGW u interface we need to create a session (pgw u comes on create session response)

But To create a session we need to include the SGW u interfaces.

So basically we need to know beforehand the IP we are going to be using to send the request to the PGW U.

**Comment by uri200** [comment]
As discuss internally and suggested by @pshelar , we can use the default route to find the IP we will be using to get the PGE user plane

That IP will be use as SGW user plane ip sent on the FTeid on `Create Session Request`

```
ip route show | grep default
```

**Comment by pshelar** [comment]
Due  to networking complexities it would be preferable to use specific interface name for NAT or NonNAT.
for NAT: eth0
for NonNAT: uplink_br0

**Comment by uri200** [comment]
Hey @pshelar, this linked PR is now merged. Is there any specific test on AGW to check non nated configuration? Does S1ap use non nated or nated?

**Comment by pshelar** [comment]
we dont have Non-Nat test yet. I will try it on bare metal setup.

**Comment by jpad-freedomfi** [comment]
@pshelar We just saw this issue. This is priority for us. We use Non-NAT in our bigger deployments. If you have patches I can test too.

**Comment by pshelar** [comment]
@jpad-freedomfi the fix is already merged to master and v1.5.

**Comment by jpad-freedomfi** [comment]
@ShubhamTatvamasi and @pshelar this is not just for inbound roaming/S8. This is true for any 1.4 or 1.5 AGW in non-NAT setup that uses uplink_br0 interface. 

in 1.4 the default route gets removed. 
in 1.5 you get the error logs posted above.

**Comment by pshelar** [comment]
@jpad-freedomfi this issue is not present on 1.4. there might be a different issue. can you post syslog from 1.4 when you see the error?

**Comment by jpad-freedomfi** [comment]
new issue for v1.4 https://github.com/magma/magma/issues/6888
