### ISSUE TITLE
[NMS] AGW Health in NMS is not accurate

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#6522]
- **Affected Component:**  NMS
- **Version:** 1.4

Health in NMS is not accurate(sometimes shows "Bad" but AGW is already checkin is OK)

![image](https://user-images.githubusercontent.com/37117037/116650471-06106d00-a936-11eb-9ba9-1c26bd47fdad.png)

**Comment by karthiksubraveti** [comment]
We rely on checkin_status for this value. Can you check if the page gets refreshed eventually and turns good or it stays bad all the time ?

**Comment by wallyrb** [comment]
> We rely on checkin_status for this value. Can you check if the page gets refreshed eventually and turns good or it stays bad all the time ?

@karthiksubraveti correct, page gets refreshed eventually to "good". (keep changing status)
