### ISSUE TITLE
[NMS] Show User State in NMS

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#6530]
### Your Environment (If applicable)

- **Version:**
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

As operations engineer, I want to be able to get the different states (EMM, ECM, ESM) , mobility(which eNB is connected) and session information of a user, so I have a better understanding  of user state and verify the correct subscription parameters has been assigned to the user

**Comment by ekowtaylor** [comment]
@wallyrb is this still high priority enough for a backlog grooming discussion?

**Comment by wallyrb** [comment]
Hey, @ekowtaylor, we can close this since user state it has been added into the NMS. Thanks a lot for following up.
