### ISSUE TITLE
Execute Unit tests in OAI

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6551]

**Comment by panyogesh** [comment]
Ganesh I to plan for the session.

**Comment by ganeshg87** [comment]
May 7:
 have executed all existing  UT cases. working on new UT cases for ##6788.

Thank you
Ganesh

**Comment by rjha72** [comment]
May 12
- Will be executing UT cases on oai code base today

**Comment by rjha72** [comment]
Have executed all existing OAI UT test cases.
