### ISSUE TITLE
execute session management UT scripts and learn data flows in sessiond and on N4 interface

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6552]

**Comment by rjha72** [comment]
Have run the UT test cases, attended the session on call flow between sessiond and pipelined

**Comment by GANESH-WAVELABS** [comment]
[12-May-2021 : Ganesh . I ] : for SMF all the UT cases are under "magma/lte/gateway/c/session_manager/test", 
"magma/lte/protos/pipelined.proto" contains the communication between SMF-UPF via N interface.

Executed the UT cases for SMF and gone through pipelined.proto file. So closing this Task
