### ISSUE TITLE
take a overview onto Proto files in sessiond(SMF) and pipelined(UPF)

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6553]

**Comment by GANESH-WAVELABS** [comment]
[12-May-2021 : Ganesh . I] : 
magma/lte/protos/session_manager.proto --> this proto file used b/w AMF-SMF communication as N11 interface.

magma/lte/protos/pipelined.proto --> this proto file used b/w SMF-UPF communication as N4 interface.

I have gone through the above files and understand the data structures used, so closing this Task.

**Comment by GANESH-WAVELABS** [comment]
Closing the task
