### ISSUE TITLE
magma package preparation, deployment on AGW node and run Integration tests using DStester

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6556]

**Comment by panyogesh** [comment]
Balaji to plan for the session.

**Comment by Balaji-Jatla** [comment]
@panyogesh yes Yogesh session will be delivered on Thursday.

**Comment by Balaji-Jatla** [comment]
Default Magma package is created , transferred to Integration Test AGW Node and Tried UE-Registration through DS-Tester and also captured Packets on DS tester interface and analyzed ds_log and mme.log .

**Comment by GANESH-WAVELABS** [comment]
[10-May-2021 : Ganesh . I ] : Not yet done. Will try it tomorrow

**Comment by rjha72** [comment]
May 12
- Need to run test cases on DStester, Plan to do it tomorrow

**Comment by ganeshg87** [comment]
May 12:
  - Not finished, will plan once #6788 fininshed

**Comment by rjha72** [comment]
May 13
- Execute existing registration test case in DsTester along with Roopa/Balaji
