### ISSUE TITLE
AGW stuck in weird state after upgrade to 1.5.0-1619628161-f023455f

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#6573]
### Your Environment

- **Version:** 1.5.0-1619628161-f023455f
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service mme, smsd, health

- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

**To Reproduce**
1. AGW was running on below magma software
     root@vagw-auto1:/home/magma# dpkg --list| grep magma
ii  magma                                     1.5.0-1616513315-56ff0559         amd64        Magma Access Gateway
ii  magma-cpp-redis                           4.3.1.2-2                         amd64        Redis C++ client library
ii  magma-libfluid                            0.1.0.6-1                         amd64        Libfluid Openflow Controller
ii  magma-sctpd                               1.5.0-1616513315-56ff0559         amd64        Magma SCTPD
2. i upgraded as per latest repo to below image version
    root@vagw-auto1:/home/magma# dpkg --list| grep magma
ii  magma                                     1.5.0-1619628161-f023455f         amd64        Magma Access Gateway
ii  magma-cpp-redis                           4.3.1.2-2                         amd64        Redis C++ client library
ii  magma-libfluid                            0.1.0.6-1                         amd64        Libfluid Openflow Controller
ii  magma-sctpd                               1.5.0-1619628161-f023455f         amd64        Magma SCTPD

3. after reboot GW did not start mme, health, smsd processes
● magma@smsd.service - Magma smsd service
   Loaded: loaded (/etc/systemd/system/magma@.service; disabled; vendor preset: enabled)
   Active: deactivating (stop-post) (Result: exit-code) since Fri 2021-04-30 10:40:23 PDT; 1s ago
  Process: 13082 ExecStart=/usr/bin/env python3 -m magma.smsd.main (code=exited, status=1/FAILURE)
 Main PID: 13082 (code=exited, status=1/FAILURE); Control PID: 13712 (python3)
    Tasks: 1 (limit: 4915)
   Memory: 14.0M (limit: 300.0M)
   CGroup: /system.slice/system-magma.slice/magma@smsd.service
           └─control
             └─13712 python3 /usr/local/bin/service_util.py smsd

Apr 30 10:40:23 vagw-auto1 smsd[13082]:   File "/usr/local/lib/python3.5/dist-packages/magma/smsd/main.py", line 54, in <module>
Apr 30 10:40:23 vagw-auto1 smsd[13082]:     main()
Apr 30 10:40:23 vagw-auto1 smsd[13082]:   File "/usr/local/lib/python3.5/dist-packages/magma/smsd/main.py", line 37, in main
Apr 30 10:40:23 vagw-auto1 smsd[13082]:     ServiceRegistry.LOCAL)
Apr 30 10:40:23 vagw-auto1 smsd[13082]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service_registry.py", line 156, in get_rpc_channel
Apr 30 10:40:23 vagw-auto1 smsd[13082]:     (ip, port) = ServiceRegistry.get_service_address(service)
Apr 30 10:40:23 vagw-auto1 smsd[13082]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service_registry.py", line 53, in get_service_address
Apr 30 10:40:23 vagw-auto1 smsd[13082]:     raise ValueError("Invalid service name: %s" % service)
Apr 30 10:40:23 vagw-auto1 smsd[13082]: ValueError: Invalid service name: sms_mme_service
Apr 30 10:40:23 vagw-auto1 systemd[1]: magma@smsd.service: Main process exited, code=exited, status=1/FAILURE

● magma@health.service - Magma health service
   Loaded: loaded (/etc/systemd/system/magma@.service; disabled; vendor preset: enabled)
   Active: deactivating (stop-post) (Result: exit-code) since Fri 2021-04-30 10:40:23 PDT; 1s ago
  Process: 13089 ExecStart=/usr/bin/env python3 -m magma.health.main (code=exited, status=1/FAILURE)
 Main PID: 13089 (code=exited, status=1/FAILURE); Control PID: 13720 (python3)
    Tasks: 1 (limit: 4915)
   Memory: 12.4M (limit: 300.0M)
   CGroup: /system.slice/system-magma.slice/magma@health.service
           └─control
             └─13720 python3 /usr/local/bin/service_util.py health

Apr 30 10:40:23 vagw-auto1 health[13089]:   File "/usr/local/lib/python3.5/dist-packages/magma/health/main.py", line 59, in <module>
Apr 30 10:40:23 vagw-auto1 health[13089]:     main()
Apr 30 10:40:23 vagw-auto1 health[13089]:   File "/usr/local/lib/python3.5/dist-packages/magma/health/main.py", line 52, in main
Apr 30 10:40:23 vagw-auto1 health[13089]:     service.run()
Apr 30 10:40:23 vagw-auto1 health[13089]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 236, in run
Apr 30 10:40:23 vagw-auto1 health[13089]:     (host, port) = ServiceRegistry.get_service_address(self._name)
Apr 30 10:40:23 vagw-auto1 health[13089]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service_registry.py", line 53, in get_service_address
Apr 30 10:40:23 vagw-auto1 health[13089]:     raise ValueError("Invalid service name: %s" % service)
Apr 30 10:40:23 vagw-auto1 health[13089]: ValueError: Invalid service name: health
Apr 30 10:40:23 vagw-auto1 systemd[1]: magma@health.service: Main process exited, code=exited, status=1/FAILURE

root@vagw-auto1:/var/core# systemctl status magma@mme.service
● magma@mme.service - Magma OAI MME service
   Loaded: loaded (/etc/systemd/system/magma@mme.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-04-30 10:46:16 PDT; 2s ago
  Process: 9746 ExecStopPost=/usr/bin/env python3 /usr/local/bin/service_util.py mme (code=exited, status=1/FAILURE)
  Process: 9670 ExecStartPre=/usr/bin/env python3 /usr/local/bin/config_stateless_agw.py reset_sctpd_for_stateful (code=killed, signal=TERM)
  Process: 9622 ExecStartPre=/usr/bin/env python3 /usr/local/bin/generate_oai_config.py (code=exited, status=0/SUCCESS)

Apr 30 10:46:16 vagw-auto1 mme[9746]:     update_stats(service_name)
Apr 30 10:46:16 vagw-auto1 mme[9746]:   File "/usr/local/bin/service_util.py", line 63, in update_stats
Apr 30 10:46:16 vagw-auto1 mme[9746]:     status = get_status()
Apr 30 10:46:16 vagw-auto1 mme[9746]:   File "/usr/local/bin/service_util.py", line 41, in get_status
Apr 30 10:46:16 vagw-auto1 mme[9746]:     ServiceExitStatus.ExitCode.Value(exit_code.upper())
Apr 30 10:46:16 vagw-auto1 mme[9746]: AttributeError: 'NoneType' object has no attribute 'upper'
Apr 30 10:46:16 vagw-auto1 systemd[1]: magma@mme.service: Control process exited, code=exited status=1
Apr 30 10:46:16 vagw-auto1 systemd[1]: Stopped Magma OAI MME service.
Apr 30 10:46:16 vagw-auto1 systemd[1]: magma@mme.service: Unit entered failed state.
Apr 30 10:46:16 vagw-auto1 systemd[1]: magma@mme.service: Failed with result 'exit-code'.

root@vagw-auto1:/var/core# magmad_cli.py check_stateless
AGW Mode: CORRUPT

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ardzoht** [comment]
@milapjoshi can you show more context in other services status? e.g is magmad running as well and healthy?

**Comment by milapjoshi** [comment]
@ardzoht sorry i have moved on from this state. would have to see if this happens again. will close and reopen if i see this again
