### ISSUE TITLE
rewrite SetUPFSessionConfig Periodic messages Handling in SMF

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6588]
1) Periodic messages about UPF session config
2) Read the SessionMap from global session store.
3) Search with session search criteria of IMSI and session_id and find respective sesion to operate
4) If No session found in SessionMap for IMSI with teid continue with other IMSI sessions.
5 If version mismatch then send the snapshot of session to UPF

**Comment by GANESH-WAVELABS** [comment]
[02-June-2021 : Ganesh . I ] : Identified and modified few files, will start UT cases and update here tomorrow

**Comment by GANESH-WAVELABS** [comment]
[08-June-2021 : Ganesh . I ]: Below PR has been created for this task : https://github.com/magma/magma/pull/7382

**Comment by GANESH-WAVELABS** [comment]
PR #7382 has been merged to magma master branch, hence closing this task.
