### ISSUE TITLE
Change all IMSI specific rules to default and remove all static rules related to imsi

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6590]

**Comment by GANESH-WAVELABS** [comment]
[11-June-2021 : Ganesh . I ] : This is duplicate task of #7215
Below PR has been raised for task #7215
https://github.com/magma/magma/pull/7254

**Comment by GANESH-WAVELABS** [comment]
PR #7254 has been merged on to magma master branch, hence closing this task.
