### ISSUE TITLE
Add IPv6 test cases for GTP-APP offload PRs

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6595]

**Comment by prabinakpattnaik** [comment]
Below are the test cases list for ipv6:
make integ_test TESTS=s1aptests/test_attach_detach_secondary_pdn_with_pcscf_address.py
make integ_test TESTS=s1aptests/test_attach_detach_with_ipv6_pcscf_and_dns_addr.py 
make integ_test TESTS=s1aptests/test_attach_detach_with_pcscf_address.py
make integ_test TESTS=s1aptests/test_attach_ipv4v6_pdn_type.py
make integ_test TESTS=s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
make integ_test TESTS=s1aptests/test_enb_partial_reset_con_dereg.py
make integ_test TESTS=s1aptests/test_ipv4v6_secondary_pdn.py                       
make integ_test TESTS=s1aptests/test_ipv4v6_secondary_pdn_multi_ue.py              
make integ_test TESTS=s1aptests/test_ipv4v6_secondary_pdn_rs_retransmit.py
make integ_test TESTS=s1aptests/test_ipv4v6_secondary_pdn_spgw_initiated_ded_bearer.py
make integ_test TESTS=s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer.py 
make integ_test TESTS=s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer_multi_ue.py 
make integ_test TESTS=s1aptests/test_ipv6_secondary_pdn_rs_retransmit.py 
make integ_test TESTS=s1aptests/test_ipv6_secondary_pdn_with_ded_bearer.py 
make integ_test TESTS=s1aptests/test_secondary_pdn_reject_unknown_pdn_type.py


These test cases will execute on master branch with #6947 fix.

**Comment by prabinakpattnaik** [comment]
Below IPv6 test cases are failing:
s1aptests/test_attach_detach_with_ipv6_pcscf_and_dns_addr.py
s1aptests/test_attach_ipv4v6_pdn_type.py
s1aptests/test_ipv4v6_secondary_pdn.py
s1aptests/test_ipv4v6_secondary_pdn_multi_ue.py
s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer.py
s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer_multi_ue.py
s1aptests/test_ipv6_secondary_pdn_with_ded_bearer.py
s1aptests/test_secondary_pdn_reject_unknown_pdn_type.py

**Comment by prabinakpattnaik** [comment]
Same test cases are failing in master branch as well.
We updated all ipv6 filing test cases.
