### ISSUE TITLE
save OVS Flow TEID to register in pipelined

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6596]

**Comment by prabinakpattnaik** [comment]
The PR (#6596) is raised on master branch.
Addressed the review comments as well.

**Comment by prabinakpattnaik** [comment]
PR is approved for merge into Master branch.

**Comment by prabinakpattnaik** [comment]
[13-05-2021]
This PR is merged on master branch.
Hence this task can be closed.
