### ISSUE TITLE
[Orc8r] Add test utilities to be used in cluster tests

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#6636]

**Comment by karthiksubraveti** [comment]
With inputs containing kubectl, api endpoints and certs. Need to add test utilities which can enable Orc8r tests to 
- invoke Orc8r APIs
- helper utilities to enable adding networks, gateways, subscribers etc. 
- upgrading or downgrading helm charts from test setup/teardown

**Comment by hcgatewood** [comment]
@karthiksubraveti the only difficult thing here is our Helm charts are actually a bit unwieldy. I think for now let's just have orcl install "latest" Helm charts and not mess with it.

Later we can add support for messing with Helm charts directly from tests, but I probably want to clean up our charts first

**Comment by hcgatewood** [comment]
@karthiksubraveti the only difficult thing here is our Helm charts are actually a bit unwieldy. I think for now let's just have orcl install "latest" Helm charts and not mess with it.

Later we can add support for messing with Helm charts directly from tests, but I probably want to clean up our charts first
