### ISSUE TITLE
AGW BE Overhaul

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#6663]
Design proposal:
https://docs.google.com/document/d/1TKY4z-fP1ljF_j5ebEHAjQeT3EsC_ndrP8NIVBvghOY/edit?ts=60ccb9a1#heading=h.kawewzdsw847

BE Roadmap for Current Product:
https://fb.quip.com/LMnnAUv10rz2

**Comment by ekowtaylor** [comment]
Sprint 1 exit criteria: Need to land execution plan

**Comment by ulaskozat** [comment]
Hey Ekow, I think the attached doc is not the ask of this issue. We are supposed to provide a roadmap of BE for H2, no?

**Comment by ekowtaylor** [comment]
Hi @ulaskozat , yes you are right. The attached document is only a proposal so a roadmap is indeed the required output of this sprint.

**Comment by ulaskozat** [comment]
https://fb.quip.com/LMnnAUv10rz2

**Comment by ekowtaylor** [comment]
@ulaskozat can we begin adding the dependencies as outlined in the doc to the epic for planning purposes?

**Comment by ulaskozat** [comment]
@ekowtaylor will finish adding them by Aug 6.
