### ISSUE TITLE
[Cloudstrapper] Create Cloudstrapper Dev pipeline on LF AWS account

### ISSUE THREAD

**Issue by arunuke** [magma/magma#6679]

**Comment by arunuke** [comment]
In Progress. PR under review - https://github.com/magma/magma/pull/6855

Cloudstrapper pipeline created on local AWS directory and will be replicated on LF AWS directory on PR review and merge.

**Comment by quentinDERORY** [comment]
Upon Merge of #6896 , we will replicate the circle ci job with the LF AWS credentials.

**Comment by quentinDERORY** [comment]
#6687 is the issue tracking the original ci pipeline for fb internal aws account

**Comment by quentinDERORY** [comment]
#6896  is ready to be merged with a circle ci job running in the release pipeline to publish amis to LF AWS account
