### ISSUE TITLE
[Cloudstrapper] Create Cloudstrapper Dev Pipeline on Magma AWS account for internal dogfooding

### ISSUE THREAD

**Issue by arunuke** [magma/magma#6687]

**Comment by artblee** [comment]
i have completed pipeline

**Comment by artblee** [comment]
https://app.circleci.com/pipelines/github/magma/magma/21422/workflows/93f1cfca-3792-4308-bf2e-f94fd56029fa

**Comment by artblee** [comment]
i have tested pipeline with new ec2 keys

**Comment by artblee** [comment]
https://app.circleci.com/pipelines/github/magma/magma/21878/workflows/2bf05e13-80ce-45eb-8d44-6feceaae8f85

**Comment by artblee** [comment]
i have tested pipeline with new aws api login
https://app.circleci.com/pipelines/github/magma/magma/21898/workflows/805f3ff0-2aac-4800-afee-50d3222c7c88

**Comment by artblee** [comment]
i have create PR to merge aws-dev into master

**Comment by artblee** [comment]
https://github.com/magma/magma/pull/6855

**Comment by quentinDERORY** [comment]
In Progress. PR under review - #6896 

Pipeline part of the release circle ci job which needs manual intervention to be triggered.
Deliverables of the pipeline:  Pushes the amis cloudstrapper-1.5 and cloudstrapper-1.5 in the us-west-1 region.
NB: The underlying AWS resources created during the AMI process are all deleted upon job completion

Still in progress:
- Improvements of cleaning playbook

**Comment by quentinDERORY** [comment]
#6896 PR ready to be merged with a weekly circle ci job running on master to publish amis.
It tags the amis with the latest tag from magma and suffix it with the circle ci job number.
The pipeline is running in us-east-1 now.
