### ISSUE TITLE
Fix state reindex race condition

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#6720]
### Bug

There's a race condition in the state reindexer: https://app.circleci.com/pipelines/github/magma/magma/21386/workflows/d0c26f76-117b-40fd-858e-e63b76a768b1/jobs/223527

My best guess is that this is due to `PopulateJobs` sometimes failing to complete =once, meaning the job queue doesn't get populated. In which case, the most straightforward solution is moving the `PopulateJobs` functionality (producer for the queue) out of state service and into a single-pod deployment. (Or, move the entire indexing functionality into its own service.)

Since this race condition is trivial in real deployments, and recoverable by bouncing a state service pod, we will deprioritize this fix until after GA.

### Resolution

Move the entirety of the reindexing functionality to its own singleton service: `reindex`. This singleton service will handle checking for, and enacting, the entirety of Orc8r's reindexing needs. Since this service will be a singleton, this removes the need for the [custom SQL job queue](https://github.com/magma/magma/blob/51843e3245e0b785a738d991f62657c2cac328b6/orc8r/cloud/go/services/state/indexer/reindex/queue.go#L54-L84)

**Comment by markjen** [comment]
if we want the `state` tier to be scalable, we may not want to make the `reindex` service a singleton
