### ISSUE TITLE
Enforcement support for converged UPF

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6721]

**Comment by prabinakpattnaik** [comment]
#2783 PR is updated with latest changes.
The original 5G patch now is modified to be at sync with 4G and have the stats (table-14) at session level.
Approach shared with Nick. Waiting for approval.

**Comment by prabinakpattnaik** [comment]
I have got review comments for this PR.
Will address all review comments soon.

**Comment by prabinakpattnaik** [comment]
Addressed all review comments.
Ready for merge.

**Comment by prabinakpattnaik** [comment]
The PR #2783 has been merged onto master.
