### ISSUE TITLE
on magma-5g branch Integrate 6752, 6336 and make sure UE Registration is successful

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6753]

**Comment by panyogesh** [comment]
May-10 :
1. #6752 and #6336 are giving merge conflicts. Had a discussion with ACL team and it seems #6336 is mainly targeted for SIT.
2. So for now the plan is to take in #6752 + #6437 + additional changes on top. #6336 needs to be taken little later.
3. Fixing some issues while packet processing in NGAP request which comes with additional fields (like 5GMM capability).

Need to discuss with team to take a final call.

**Comment by panyogesh** [comment]
May-12:
1. #6752 issue got merged. The Open Review comments on #6752 will be tracked in Issue #6860
2. #6336 is closed as it was having merge conflicts. A separate PR will be raised for the functionality commit
3. Issues like 5GMM capability handling etc is taken care. Will raise the PR shortly.

**Comment by panyogesh** [comment]
All the initial changes are done. Will share the code this week with Vinay for testing and based on results plan for a PR.
Working with Sanjay to get quick feedback on packet captures.

**Comment by sureshgorijavolu** [comment]
#6972 fixed this issue. code is merged onto magma-5g branch.
