### ISSUE TITLE
UE rejects Authentication procedure with 5G MM cause "NG KSI already in use"

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6788]

**Comment by sureshgorijavolu** [comment]
this issue is reproduced in SIT environment. steps to reproduce the issue
1. UE registers with AMF
2. Turn Airplane mode ON on UE
3. stop / start magma services
4. Turn Airplane mode OFF on UE

UE sends registration request to AMF
AMF sends Downlink Authentication Request
UE sends authentication failure with 5GMM cause #71 (Ng KSI already in Use)

24.501 section "5.4.1.2.4.5 Abnormal cases in the UE"
AMF is to select a new ngKSI and send the same EAP-request message to the UE.

**Comment by ganeshg87** [comment]
Update May-10 :
- AMF does not have code to handle  5GMM cause #71 "ngKSI already in use".
- Identified the placeholder for Issue fix. working on changes, and a Unit test plan for validation. 

Thank you
Ganesh

**Comment by ganeshg87** [comment]
Update May 12:

  -AMF Code changes in progress to handle AuthenticationFailure response(ngKSI is already in use) from UE.

**Comment by ganeshg87** [comment]
Update 24:
    code changes finished and validated using UT(UERANSIM).

**Comment by ganeshg87** [comment]
June 2 :
-------
-  resolved review comments provided by Ulas
-  I will resend PR for Review by today

**Comment by sureshgorijavolu** [comment]
fixed through PR# - https://github.com/magma/magma/pull/7195/
