### ISSUE TITLE
[orc8r][agw][nms] Refactor and enhance AGW upgrade process

### ISSUE THREAD

**Issue by mattymo** [magma/magma#6804]
Here is a high level overview of desired changes:

- [ ] AGW upgrades can switch the APT repo configuration "dist" field to match the desired magma package version to install
- [ ] AGW upgrades roll back if something goes wrong
- [ ] An Admin in NMS should have a panel that allows to configure available versions (instead of a buried API call)
- [ ] An operator can upgrade to any from a list of available magma versions for a given AGW (maintenance vs major upgrade)
- [ ] (not high priority) AGW upgrade process can invoke a 3rd party command, such as ansible, instead of apt-get install

This change is necessary because the magma repos switched from a single repo to split dists due to python dependency issues. This change had many benefits, but it broke the ability to perform upgrades remotely.

**Comment by mattymo** [comment]
@tmdzk @119Vik @jpad-freedomfi @berezovskyi-oleksandr @mpgermano @andreilee  Tagging because we discussed this.

**Comment by shaddi** [comment]
This seems like a great end-state to aim for. Is there a proposal for how to realize these changes yet?
