### ISSUE TITLE
[1.5] MME sends ICS request to the wrong enb after SR

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#6812]
### Your Environment

- **Version:** 1.5
- **Affected Component:** AGW
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

UE transitions from eNB_1 to eNB_2 (not gracefully), eNB_2 sends Initial UE message, Service Request. MME sends ICS request to eNB_1 instead. 

See packets 132 and 134 respectively and log line 002995 in the attached.

[Archive 5.zip](https://github.com/magma/magma/files/6437509/Archive.5.zip)

**Comment by shaddi** [comment]
Just to confirm, this was tested using a custom build derived from master, not the official 1.5 release, right?

**Comment by sudhikan** [comment]
Correct

**Comment by sudhikan** [comment]
@shaddi - found some more information on this today. So it seems that when the UE is in ECM_CONNECTED mode and if it ping-pongs between two sites, the ICS request goes to the wrong eNB (old eNB where the UE originally came from). Whereas if the UE is in ECM_IDLE mode, the ICS request goes to the correct eNB (the new eNB through which the UE sent the service request).

In the previous log file attached (Archive 5.zip), according to line `002841` the UE is in ECM_CONNECTED mode and the ICS request goes to the wrong eNB. 

Attaching new logs today. In `cbrs51.pcapng`, in packet `375` UE shows up at another eNB after having successfully attached at a different eNB. The ICS request subsequently in pkt 376 is sent to the wrong eNB. Log line `010396` corresponds to this ICS request being sent. However, in line `010374`, the UE is in ECM_CONNECTED mode.

On the flip side, looking at the interaction in packets `394` and `395`, the ICS request goes to the **correct** eNB. The corresponding log line is `010568`. Looking at line `010557` we see that the UE is in ECM_IDLE state. 

I sense there is a pattern here where the UE connection state impacts the routing of the ICS request, wdyt? 
[cbrs51.zip](https://github.com/magma/magma/files/6470425/cbrs51.zip)

**Comment by ekowtaylor** [comment]
Stale, newer release available https://github.com/magma/magma/releases/
