### ISSUE TITLE
 Registration complete message is not going along with ICS in Downlink message

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6825]
NGAP test on magma-5g branch found this issue. 
in SIT UE registration is passed.  it means functionality is available in local copy of code. Need to commit it onto magma-5g branch and unblock NGAP test.

**Comment by rjha72** [comment]
Reviewed logs from the NGAP tester. Initial context setup message is not going to gNB with the downlink registration accept message. Though the logs from SIT shows that this is being sent to the gNB. Need to see if the SIT fixes are present in the branch on which Vinay is doing this testing

**Comment by rjha72** [comment]
May 12
- Doing preliminary investigation by going through the existing code to see why ICS is not getting triggered in the DL when sending the Registration accept message

**Comment by panyogesh** [comment]
With inputs from ACL team (Sanjay) the ICS patch is integrated now. Will raise the review request shortly. The pcap is shared in slack channel.

**Comment by sureshgorijavolu** [comment]
code is merged onto magma-5g branch.
