### ISSUE TITLE
Backport the following into v1.4 (6363, 6335, 6291, 6258) 

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#6827]
These PRs all have merge conflicts when backporting, so please raise a PR against the v1.4 branch.
I'll remove the apply-1.4 tag from the PRs so that the scripts don't get stuck.

https://github.com/magma/magma/pull/6363
https://github.com/magma/magma/pull/6335
https://github.com/magma/magma/pull/6291
https://github.com/magma/magma/pull/6258

**Comment by themarwhal** [comment]
@koolzz should I close this? Not sure if it's still relevant.

**Comment by koolzz** [comment]
Yeah I don't think these would be critical for 1.4 lets close
