### ISSUE TITLE
[agw] Unable to install magma 1.3 in AGW 

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#6837]
### Your Environment

- **Version:1.3.3**
- **Affected Component:** AGW
- **Affected Subcomponent:** AGW Installation
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue
Unable to install AGW in 1.3. Getting the following error

"dpkg: error processing archive /tmp/apt-dpkg-install-LEdmMf/170-magma_1.3.3-1620326725-cba3f429_amd64.deb (--unpack):", " trying to overwrite '/usr/local/lib/python3.5/dist-packages/ryu/ofproto/nx_actions.py', which is also in package python3-ryu 4.30", "Selecting previously unselected package spawn-fcgi.", "Preparing to unpack .../171-spawn-fcgi_1.6.4-1+b1_amd64.deb ...", "Unpacking spawn-fcgi (1.6.4-1+b1) ...", "Errors were encountered while processing:", " /tmp/apt-dpkg-install-LEdmMf/170-magma_1.3.3-1620326725-cba3f429_amd64.deb"]}

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/tag/v1.5.3
