### ISSUE TITLE
Cloud Platform Golang Resolution

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#6857]
# Cloud Platform Golang Resolution

## Intro

As the Magma project grows, and its development is increasingly an open, collaborative endeavor, previously-implicit norms need to be examined and communicated with the community.

In this particular case, we discuss an implementation detail of the Magma cloud platform — using Golang as its lingua franca.

## Resolution

Note: the text of the resolution includes certain language denoting requirements — for full definitions, see [RFC 2119](https://tools.ietf.org/html/rfc2119).

> The Magma project affirms Golang as the principal, de facto language for its cloud platform.

> Core Orc8r services MUST be written in Go. The remainder of the cloud platform, including Orc8r extensions and any additional centralized management-plane services, SHOULD be written in Go. Proposals to author or introduce non-Go services to the cloud platform MUST receive TSC majority-vote approval.

### Preference for monoglotism

Magma does not aim to be a polyglot project.

The fact that Magma has emerged as a polyglot project is an artifact of its inception as a set of research- and community-oriented projects. These projects had different incentives and goals than the current Magma project. Where previous goals aligned toward rapid prototyping, codebase hack-ability, or operational simplicity, the current project aims to be a cloud-native, production-ready platform for building carrier-grade networks.

One of the key factors to consider in building cloud-native, production-ready systems is evolvability and maintainability. Keeping a project healthy across time, teams, and platforms incurs costs — developer time in design, implementation, and debugging, dev-ops time in testing, deploying, and monitoring, and management time in understanding, planning, and coordinating.

Keeping a *polyglot* project healthy multiplies these costs — *especially in the long term*. These increased costs, particularly the long-term costs, reduce a project’s evolvability (how effectively it can pivot to accommodate new use-cases) and maintainability (how effectively it can resolve latent issues). Evolvability and maintainability are reduced both in introducing the new language and in expanding its footprint.

For a more systematized approach, consider the classic presentation *[Choose Boring Technology](http://boringtechnology.club/)*. The author discusses the relationship between a problem-space and a technology-space. When evolving or maintaining a project, solving some particular, abstract problem confers a *benefit*. Actually implementing the solution, however, incurs a *cost*.

In a monoglot project, solving a problem once is sufficient — one unit of cost confers one unit of benefit. In a polyglot project, however, there is a non-trivial set of problems which must be solved *per-language* — ramping up new (and existing) contributors, upgrading versions and dependencies, building container images, deprecating old APIs (e.g. gRPC service definitions), writing a service/connection registry, or adding distributed tracing, to name a few.

![polyglot](https://user-images.githubusercontent.com/8029544/117761087-5f0cba80-b1ec-11eb-9329-f219e1e95883.png)

Consider the illustrative visualization above, where a development team has 3 units of work at their disposal. In the monoglot scenario, the team solves 3 problems for their 3 units of work. In the polyglot, they solve 1 problem 3 times. In this case, the monoglot scenario achieves 3x the impact.

For a related perspective, consider [Spotify’s “Golden Path”](https://engineering.atspotify.com/2020/08/17/how-we-use-golden-paths-to-solve-fragmentation-in-our-software-ecosystem/) approach. Developers collaborate to identify a set of key, “blessed” tools and patterns for developing at Spotify. Developers can then rally around the golden technologies with increased expertise, support, and cross-functional cooperation.

There are, of course, benefits to a polyglot approach — choosing the “best tool for the job” for any particular endeavor, allowing developers to program in high-comfort environments, increased experimentation, etc. However, the Magma project is focused on building a maintainable, production-ready platform, so evolvability and maintainability concerns take precedence.

### Choice of Golang

*Ecosystem.* Go is the de facto cloud-native language. In fact, of the 15 [CNCF graduated projects](https://www.cncf.io/projects/), 11 are written in Go. (The remaining 4 are a single project each of C++, Rust, Python, and Ruby.)

*Magma.* The Magma cloud platform is written entirely in Go, along with several additional components such as the federated gateway. Due to this, the current set of codeowners collectively contains a wealth of Golang expertise and competence, both generally and targeting the cloud platform specifically. Finally, the Magma project’s experience with Go as a language has been positive and productive.

*Golang.* Go is a simple language, and straightforward to pick up. For developers new to Go, perhaps 90% the knowledge needed to become productive in the Magma project is found in the [Effective Go](https://golang.org/doc/effective_go) documentation — with a manageable reading speed of 200 words per minute, absorbing Effective Go in-full takes 90 minutes. IDE support is stellar, and the wealth of reference code in the Magma project eases time-to-ramp.

## Adding non-Go services

As described in the resolution, the project does permit non-Go services on the cloud platform. Despite the increased effort to support a non-Go service, it may still be a beneficial trade-off in certain cases.

Since this cost-benefit calculation is necessarily evaluated on a case-by-case basis, gaining community approval to introduce a non-Go service must go through the [proposal process](https://github.com/magma/magma/blob/master/docs/readmes/proposals/p014_proposal_process.md) to communicate and discuss the cost-benefit trade-off. A majority vote of the TSC will then be required to pass the proposal.

## Conclusion

The Magma project as a whole desires to conform toward a monoglot pattern of development. For the Magma cloud platform in particular, the Magma project recognizes Go as both the de facto and desired language.

**Comment by ShubhamTatvamasi** [comment]
Awesome, Let's Go.
