### ISSUE TITLE
[Magma-5G] PR-6752 Related cleanups

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#6860]
[Cleanups-6752.txt](https://github.com/magma/magma/files/6458380/Cleanups-6752.txt)
Attaching the list of cleanups to be taken as part of #6752. As the PR is big, the changes needs to be taken separately.

**Comment by ganeshg87** [comment]
Resolved all cleanup as part of #7565 on master
Current PR was for magma-5G branch
