### ISSUE TITLE
Processing logic for ULA when NR as secondary RAT is present (subscriberdb and MME)

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#6862]

**Comment by ulaskozat** [comment]
There are two things to be addressed:
- nr_as_secondary_rat 
-- how does subscriberdb fill up this field based on the ULR message fields for 5G NR?
-- how does MME process this information and construct IEs in its response back to UE/RAN?
- check the APN AMBR rate and based on that fill up the extended AMBR fields.

**Comment by lionelgo** [comment]
Here are some information to be discussed:

* nr_as_secondary_rat
-- how does subscriberdb fill up this field based on the ULR message fields for 5G NR?

   If the subscription in HSS enable NR as Secondary RAT in E-UTRAN, and
   if ULR contains AVP Feature-List-ID-2/'NR as Secondary RAT' bit set
   the ULA answer
     Should Contain 
       AVP Subscription Data/Access-Restriction-Data/NR as Secondary RAT in E-UTRAN Not Allowed bit set to 0
       AVP Feature-List-ID-2/'NR as Secondary RAT' bit set
     Depending on the allocated UE APN-AMBR, and APN-AMBR of granted service(s), extented bitrates AVP may be used.
     
-- how does MME process this information and construct IEs in its response back to UE/RAN?
     Considering S11 and S1 interfaces:
     MME submit the APN AMBR in CSReq, it may be modified in CSResp by PCRF
     CSReq IEs 'UP Function Selection Indication Flags', 'Secondary RAT Usage Data Report' may optionally be considered to be included.
     Based on CSResp APN-AMBR if cause is request accepted, the MME should send this IE value as it is in ESM/Activate default EPS bearer context request/APN-AMBR or ESM/Activate default EPS bearer context request/'Extended APN aggregate maximum bit rate' if APN-AMBR has a value higher than 65280 Mbps.
     MME sends in InitialContextSetupRequest/UEAggregateMaximumBitrate a value that should be the lowest value between the UE-AMBR sent by HSS and the sum of APN-AMBR(s) for all PDNs.

**Comment by lionelgo** [comment]
![image.png](https://images.zenhubusercontent.com/5a326e8f8a75884b908b1f6d/0c24c229-bab8-469e-9e5e-8c91a52328d6)
