### ISSUE TITLE
[agw] Support pinning a version in the bare-metal AGW install script

### ISSUE THREAD

**Issue by adityawasudeo** [magma/magma#6876]
### Describe the Feature

OEM's who ship hardware units to customers prefer to standardize on a single AGW release for all the units they ship to customers to make it easier to support remotely. However, the AGW install script does not let you specify a commit version and just picks up the head of the branch. This sometimes introduces new problems and generally makes it hard to standardize on a well-tested release.

The AGW upgrade script has this functionality so one current workaround is to first install an older version, then upgrade to the specific frozen version

**Describe the solution you'd like**
Adding this functionality to the install script will simplify ops and support for OEMs

**Comment by mattymo** [comment]
@adityawasudeo What do you mean it's not possible to specify a commit version? Here's one of the latest install docs:
https://magma.github.io/magma/docs/lte/deploy_install_ubuntu

You can change the part of the url that says "master" to point to any specific commit you like.

**Comment by tmdzk** [comment]
I think @mattymo  solution is the way to go. Hardcoding the package is a bad practice as discussed internally, but pinning a commit version would be the way to go, It will just give you the latest stable minor of the pinned commit. 

Closing this. If you need more infos let's open a discussion and not an issue. 
cc @talkhasib

**Comment by adityawasudeo** [comment]
Thanks @tmdzk. Could you point me to instructions on how to pin a commit within the AGW install script? IIRC the script clones the version you specify and doesn't let you pin.
