### ISSUE TITLE
Identify Integration test cases for Registration and PDU session management procedures

### ISSUE THREAD

**Issue by rjha72** [magma/magma#6877]
Helping the IT team to come up with all the successful/negative scenarios for PDU session establishment/modification/release  procedures

**Comment by rjha72** [comment]
May 12
Identified test cases for PDU session establishment (all scenarios), 
Need to identify for modification and release as well

**Comment by rjha72** [comment]
May 24
- Identified Integration test cases for pdu establishment and release procedures
- updated the spreadsheet with new test cases.

**Comment by sureshgorijavolu** [comment]
test cases are updated here -> https://docs.google.com/spreadsheets/d/1myo5W0IHQZsp2PjWGgoYfsYZin2JVn0ka3Wk6ot1RTM/edit#gid=1929100818
