### ISSUE TITLE
[Orc8r] Add control plane SGW Teid to directoryd on AGW

### ISSUE THREAD

**Issue by uri200** [magma/magma#6886]
Since Create Bearer Request only has SGW control plane TEID, we need a way to find from FEG what AGW is serving an specific TEID.

For that reason we will add TEID to directoryd so FEG can do a query to find out AGW HwId.

Tasks to do are:
- Add a call to directoryd AGW api to add fields to the record
- Add new table on directoryd to match Teid to AGW_HwId
- Add Create Bearer Request to feg relay using TEID as a key to find serving AGW

**Comment by ekowtaylor** [comment]
Can this be closed now?
