### ISSUE TITLE
default route removed when non-NAT mode of AGW is used

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#6888]
### Your Environment

- **Version:** 1.5 orc8r, 1.4 AGW
- **Affected Component:**  Access Gateway
- **Affected Subcomponent:** routing table
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the Issue

When a 1.4 AGW is connected to a 1.5 orc8r and the IP Allocation is set to DHCP_Broadcast and NAT is disabled on the AGW, the AGW will DHCP and address but fails to add a default route so connectivity is lost. 

If I manually add the default a temporary default route, next time the gateway checks-in to orc8r the route get removed. 

**To Reproduce**
1. Add a 1.4 AGW to 1.5 orc8r
2. Change network IP allocation mode to DHCP_broadcast
3. Change AGW to NAT_Enable = false (toggle in NMS and save)
4. Start ping to AGW WAN IP and see that it stops responding after it updates configuration from orc8r checkin

**Expected behavior**
Default route should be managed in non-NAT mode

**Additional context**
syslog Snippet, in this snippet:

- Gateway was added and already lost default route
- I added default route manually using IP command (ip r add default via 10.200.82.1)
- Gateway was able to checkin to orc8r, got update configs, tried to apply, and route was removed
[non-nat_no_default_route_1.4agw_on_1.5orc8r.txt](https://github.com/magma/magma/files/6468207/non-nat_no_default_route_1.4agw_on_1.5orc8r.txt)

**Comment by pshelar** [comment]
AGW SGi interface configuration adds default IP route, does SGi get IP address using DHCP ?

**Comment by jpad-freedomfi** [comment]
Yes it does. I think you can see the dhclient get an IP in the syslog snippet I posted. IP is 10.200.82.214

**Comment by pshelar** [comment]
can you try '1.5.0-1619551902-44586193' release. we have added a check that does not change SGi IP routing in case it is up and running.

**Comment by jpad-freedomfi** [comment]
@pshelar is the mentioned release earlier or later than 1.5.0-1619628161-f023455f ?

Looks like from apt output it's older. Is that right? 

```
magma@FreedomFi-Gateway:~$ apt list magma -a
Listing... Done
magma/stretch-1.5.0,now 1.5.0-1619628161-f023455f amd64 [installed]
magma/stretch-1.5.0 1.5.0-1619551902-44586193 amd64
magma/stretch-1.5.0 1.5.0-1619534833-c724c405 amd64
magma/stretch-1.5.0 1.5.0-1619199218-d7b3087e amd64
magma/stretch-1.5.0 1.5.0-1619189278-2adf0235 amd64
```

**Comment by jpad-freedomfi** [comment]
@pshelar Just tried similar setup with 1.5.1-1622832859-484890af and again got a configuration where default route is not populated. 

Environment:
Orc8r is 1.5.0
AGW is 1.5.1-1622832859-484890af

We have:
Network IP Allocation = NAT
Gateway = NAT Enable
Gateway SGi IP = Static config via NMS

Result:
AGW SGi used to DHCP to get an address, and default route is not populated so IP connection is lost. 

Note when AGW was at 1.5.0 tagged release, we had default route, but static IP was still not applied to SGi. 

Log showing IP address not statically set on SGi per configuration in 1.5.0 (or possibly set then overwritten by dhclient)
[static_ip_not_applied_by_pipelined_15.txt](https://github.com/magma/magma/files/6619943/static_ip_not_applied_by_pipelined_15.txt)

Fresh log showing 1.5.1 coming up with A) same issue as above with static IP on SGi and no default route
console and syslog zipped together.
[static_ip_not_setup_on_SGI_and_no_default_route_1.5.1.zip](https://github.com/magma/magma/files/6619965/static_ip_not_setup_on_SGI_and_no_default_route_1.5.1.zip)

**Comment by pshelar** [comment]
It is trying to set the IP, next step is route update.
```
May 13 17:36:11 FreedomFi-Gateway pipelined[19867]: INFO:UplinkBridgeController:ip addr 10.200.82.101/24 already set for iface eth0
```
to get route addition related log we need to enable debug level logging.

**Comment by jpad-freedomfi** [comment]
here is updated syslog with DEBUG for pipelined
[syslog_static_ip_not_setup_on_SGI_and_no_default_route_1.5.1_DEBUG.txt.zip](https://github.com/magma/magma/files/6620079/syslog_static_ip_not_setup_on_SGI_and_no_default_route_1.5.1_DEBUG.txt.zip)

**Comment by pshelar** [comment]
This is artifactory issue, package python3-eventlet is swapped between debian and ubuntu.
@tmdzk is fixing it.

```
Jun  8 23:07:10 FreedomFi-Gateway systemd[1]: Started Magma pipelined service.
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]: Traceback (most recent call last):
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:     "__main__", mod_spec)
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:     exec(code, run_globals)
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 22, in <module>
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:     import aioeventlet
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 1, in <module>
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]:     import eventlet.hubs.hub
Jun  8 23:07:10 FreedomFi-Gateway pipelined[1383]: ImportError: No module named 'eventlet.hubs.hub'
Jun  8 23:07:10 FreedomFi-Gateway systemd[1]: magma@pipelined.service: Main process exited, code=exited, status=1/FAILURE
Jun  8 23:07:11 FreedomFi-Gateway systemd[1]: magma@pipelined.service: Unit entered failed state.
Jun  8 23:07:11 FreedomFi-Gateway systemd[1]: magma@pipelined.service: Failed with result 'exit-code'.
```

**Comment by jpad-freedomfi** [comment]
Thanks for looking at this guys. Any ETA for a fix in the repo? @tmdzk?

**Comment by tmdzk** [comment]
This is fixed. @jpad-freedomfi

**Comment by jpad-freedomfi** [comment]
@tmdzk how do I get the update? I don't see a new version after sudo apt-get update. So how do I pull the fixed version?

**Comment by jpad-freedomfi** [comment]
not sure this is fixed. https://github.com/magma/magma/issues/7487

**Comment by tmdzk** [comment]
```
sudo dpkg --purge --force-all python3-eventlet
sudo apt update
sudo apt install python3-eventlet
```

Unfortunately both versions have the same name. So you'll have to go though the script above
