### ISSUE TITLE
Execute integ_testcases enabling  pipelined_managed_tbl0

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#6947]
As part of #5217 and #5685 the GTP-APP can make use of RYU controller to configure ovs. Following are the tasks for this activity :
1. In app/classifier.py map the rpcs to the correct ovs-calls.
2. Run the integration test and see if Integration tests are passing.

**Comment by prabinakpattnaik** [comment]
PR raised on master branch for this issue:
https://github.com/magma/magma/pull/7001

**Comment by prabinakpattnaik** [comment]
The corresponding PR of this task has been merged into master.
Hence, close this task.
