### ISSUE TITLE
Handling of the Context present information in UE and populating in AMF

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#6949]
Following are the sequence of steps :
1. In the initialUEMessage parse the InitailUEContext ie if present.
2. If present set the ue_context_request_present to  true and pass this
    information to AMF
3. Based on this flag (if set to true) send the initieUEContext setup request.

Implement the steps in ngap and AMF.

**Comment by ganeshg87** [comment]
InitialUEMessage-IEs NGAP-PROTOCOL-IES ::= {
 { ID id-RAN-UE-NGAP-ID CRITICALITY reject TYPE RAN-UE-NGAP-ID PRESENCE mandatory }|
 { ID id-NAS-PDU CRITICALITY reject TYPE NAS-PDU PRESENCE mandatory }|
 { ID id-UserLocationInformation CRITICALITY reject TYPE UserLocationInformation PRESENCE mandatory }|
 { ID id-RRCEstablishmentCause CRITICALITY ignore TYPE RRCEstablishmentCause PRESENCE mandatory }|
 { ID id-FiveG-S-TMSI CRITICALITY reject TYPE FiveG-S-TMSI PRESENCE optional }|
 { ID id-AMFSetID CRITICALITY ignore TYPE AMFSetID PRESENCE optional }|
 { ID id-UEContextRequest CRITICALITY ignore TYPE UEContextRequest PRESENCE optional }|
 { ID id-AllowedNSSAI CRITICALITY reject TYPE AllowedNSSAI PRESENCE optional }

**Comment by ganeshg87** [comment]
June 2 :
-------
-  resolved review comments provided by Ulas
-  I will resend PR for Review by today

**Comment by sureshgorijavolu** [comment]
merged to magma-5g through PR# - https://github.com/magma/magma/pull/7195/
