### ISSUE TITLE
Timer Handling for TR3570

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#6951]
Handling of the timer TR3570 for registration procedure.

**Comment by Kaleem-Wavelabs** [comment]
26/5 Update: Required code analysis and test setup is done
Next Action item: Work onto complete the code changes and UT

**Comment by Kaleem-Wavelabs** [comment]
Shared the mme binary to TeraVM for verification of the change.
Addressed the review comments shared.
Will be amending the changes.
