### ISSUE TITLE
AGW: pipelined: pipelined-cli broken

### ISSUE THREAD

**Issue by pshelar** [magma/magma#6963]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** pipelined
- **Deployment Environment:**  bare-metal (AGW)

### Describe the Issue
pipelined cli throws error:
```
root@phy-u5:/home/magma/pravin# pipelined_cli.py
Traceback (most recent call last):
  File "/usr/local/bin/pipelined_cli.py", line 54, in <module>
    from scripts.helpers.ng_set_session_msg import CreateSessionUtil
ModuleNotFoundError: No module named 'scripts'
```

**Comment by prabinakpattnaik** [comment]
As part of #6191 , we have changed the place of ng_set_session_msg.py script from tests/app to python/scripts.
Bare metal build is not included the tests directory.
As suggested by Alex and Nick,  we could try is maybe define a scripts/helpers to put util related files on here.
But still "scripts" is not taking path in bare-metal build.  Better we will keep this file on same path (present directory).
Like:
from ng_set_session_msg import CreateSessionUtil

**Comment by prabinakpattnaik** [comment]
PR is raised for this issue.
https://github.com/magma/magma/pull/7031

**Comment by prabinakpattnaik** [comment]
The PR is merged into master branch.
