### ISSUE TITLE
Resolve UE registration Failure for EA0 and IA2 on magma-5g branch

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#7023]

**Comment by ganeshg87** [comment]
Update 24:
------------
 - Code changes finished and validated Registration with EA0 & IA2 using DSTester and UERANSIM.

**Comment by ganeshg87** [comment]
- Registration with EA0 & IA2 using UERANSIM. please find below the log file.
[https://app.zenhub.com/files/170803235/41b23834-119f-4edc-87e7-5fc129084db8/download](https://app.zenhub.com/files/170803235/41b23834-119f-4edc-87e7-5fc129084db8/download)

![image.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/23175a66-5b7a-4ee9-984a-d0facc3bf973)
