### ISSUE TITLE
/magma/orc8r/cloud/docker$ ./build.py --all  Produces FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'

### ISSUE THREAD

**Issue by ezechinwa** [magma/magma#7026]
### Ubuntu 20.04

- **Version:*Magma 1.4, python 3.8.3*
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator
- **Deployment Environment:** e.g. local docker-compose (orc8r), bare-metal (AGW),

### Describe the Issue
Running this command below 

/magma/orc8r/cloud/docker$ ./build.py --all

Creating build context in '/tmp/magma_orc8r_build'...
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/gateway/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/lib/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/lib/go/protos/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/lte/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/feg/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/feg/cloud/go/protos/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/cwf/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/wifi/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/fbinternal/cloud/go/go.mod
Running 'docker-compose -f docker-compose.yml -f docker-compose.metrics.yml -f docker-compose.override.yml build --build-arg MAGMA_MODULES=orc8r lte feg cwf wifi fbinternal'...
Traceback (most recent call last):
  File "./build.py", line 297, in <module>
    main()
  File "./build.py", line 89, in main
    _run(d_args)
  File "./build.py", line 124, in _run
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'

Link to the build.py file below
[https://codeshare.io/5wN8DJ](Build.py)

**Comment by ekowtaylor** [comment]
cc: @karthiksubraveti  for initial comments

**Comment by karthiksubraveti** [comment]
Please install =>  https://docs.magmacore.org/docs/basics/prerequisites#development-tools
