### ISSUE TITLE
[orc8r] Update RDS from 9.6 to 12 and inform current customers

### ISSUE THREAD

**Issue by arunuke** [magma/magma#7041]
### Your Environment (If applicable)

- **Version:**
1.7

- **Affected Component:** 
Orc8r

- **Affected Subcomponent:** 
Orc8r Database

- **Deployment Environment:** 
AWS Orc8r

### Describe the Feature

RDS is deprecating v9.6 and forcing an upgrade by Jan 2022 to v12.0. Since orc8rdb is a single instance, this becomes all the more important to formulate a plan for upgrade, intimate current customers of the plan and ensure newer customers do not have to do an upgrade.

**Describe the solution you'd like**
Upgrade to v12.0

**Describe alternatives you've considered**
None, since this is a forced update by AWS.

**Resources**
AWS RDS upgrade [info](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html).

**Desired timelines**
1.7

**Comment by ekowtaylor** [comment]
@arunuke, was this upgrade done already?
