### ISSUE TITLE
mme.conf not getting mapping mode settings from gateway.mconfig v1.5

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#7049]
### Your Environment

- **Version:** 1.5 release 1.5.0-1619628161-f023455f
- **Affected Component:** AGW/FeG S8 inbound roaming 
- **Affected Subcomponent:** MME
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the Issue

Configuration of the s6a mode mapping is not making it into MME process when configuring S8 inbound roaminig. Example gateway.mconfig is attached. I followed the setup guide here https://docs.magmacore.org/docs/howtos/inbound_roaming 

But when UE tries to attach to either local PLMN or roam PLMN both get rejected when s6a AIR fails. MME is saying it doesn't know how to route to FeG. 

After looking with @uri200 looks like the mme is not getting the mapping mode configuration from gateway.mconfig into /var/opt/magma/tmp/mme.conf. 

As a test, I made a "correct" looking file in /var/opt/magma/template/mme.conf.template to see if MME process would pick up the mapping. You can see the mapping in the startup log of the MME but still no difference in behavior.

**To Reproduce**
1. on bare metal AGW follow guide to setup inbound roaming
2. Configure local FeG_lte_network
3. Configure local feg_network (without FeG Gateway)
4. Configure roam feg_network (with FeG gateway)
5. Assign mode mappings per instructions
6. Try to attach a UE using either SIM from subscriberDB or roam HSS
7. See that MME fails AIR

**Expected behavior**
Expectation is that mapping propagates to mme configuration file and then is used by the process to route s6a appropriately

**Additional context**
log zip contains:
mme.log in debug mode
gateway.mconfig
pcaps of S1 and 

[Archive.zip](https://github.com/magma/magma/files/6525261/Archive.zip)

**Comment by uri200** [comment]
on swagger, lte_federated network, make sure the network has 

epc containing feg_netowrk_id
```
   "feg_network_id": "local_federated_network",
```


``` 
"federation": {
    "federated_modes_mapping": {
      "enabled": true,                 <---
      "mapping": [
        {
          "mode": "s8_subscriber",
          "plmn": "11111"
        },
        {
          "mode": "local_subscriber",
          "plmn": "22222"
        }
      ]
    },
    "feg_network_id": "terravm1_feg_network"
  },
 ```

**Comment by jpad-freedomfi** [comment]
this is resolved.
