### ISSUE TITLE
Proposal for better commit message

### ISSUE THREAD

**Issue by pshelar** [magma/magma#7105]
# Improve git commit messages
This proposal is about recommended git commit style.  Every project generally
has conventions for writing commit message subject line.  Rather than defining
out own convention, magma can make use of commit subject structure
according to conventionalcommits.org.

# tldr
Commit message can follow the template defined in magma github.
This document covers commit subject line structure and
validation APP.
```
<type>[optional scope]: <description>
```
for example:
```
fix(AGW): fix pyroute2 dependency
```

## Advantage of semantic commits.
1. This state intention of the commit msg in concise manner in PR title.
2. It can be used for automatically compiling change log for magma release
   documentation.
3. Analytics related to number of fixes vs feature commits in each release.
4. This would force developer to rethink when they mix different type of
   changes in same PR.

## type supported for magma project
Every commit would need to use `type` for each commit. Following would be the
type available for use.
```
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - proposal
```

## scope for magma code base.
After `type` commit subject should have `scope` of the change. `scope` is
optional  since it  can be automatically derived from the change. there is
already a bot to set component for every git PR.

```
  - orc8r
  - nms
  - feg
  - agw
  - mme
  - pipelined
  - sessiond
  - mobilityd
  - subscriberdb
  - policydb
```

For details on commit specification refer: https://www.conventionalcommits.org/en/v1.0.0/

## commit message body
magma github PR commit msg template covers required structure for commit message.

## Validation of commit mesages
semantic-pull-requests github app validates the commit subject according to
type and scopes defined for magma. This would be helpful while reviewing PR.
Configuration for this APP is in defined in `.github/semantic.yml`, As we add
more components to magma source code this file needs to be updated.

https://github.com/apps/semantic-pull-requests

**Comment by tykeal** [comment]
[pre-commit](https://pre-commit.com/) support for this is available from the [gitlint](https://jorisroovers.com/gitlint/) plugin as a community addition.

**Comment by amarpad** [comment]
Looks good to me,
Typo
> Rather than defining out own convention

**Comment by electrocucaracha** [comment]
The OpenStack community [defined](https://wiki.openstack.org/wiki/GitCommitMessages) some guidelines for their commit messages, maybe some of them can help to complement this proposal

**Comment by rdefosse** [comment]
@pshelar 

Pravin,

I am trying to apply the guidelines,

I mainly develop, fix or enhance on the CI scripts.

I would put `ci` as a scope because that is indeed my scope.

Raphael

**Comment by pshelar** [comment]
> The OpenStack community [defined](https://wiki.openstack.org/wiki/GitCommitMessages) some guidelines for their commit messages, maybe some of them can help to complement this proposal

Yes, there is plan to improve overall commit msg structure.

**Comment by pshelar** [comment]
> @pshelar
> 
> Pravin,
> 
> I am trying to apply the guidelines,
> 
> I mainly develop, fix or enhance on the CI scripts.
> 
> I would put `ci` as a scope because that is indeed my scope.
> 
> Raphael

sounds good. I would add CI as scope.

**Comment by electrocucaracha** [comment]
> > The OpenStack community [defined](https://wiki.openstack.org/wiki/GitCommitMessages) some guidelines for their commit messages, maybe some of them can help to complement this proposal
> 
> Yes, there is plan to improve overall commit msg structure.

This is another [resource](https://github.com/google/eng-practices/blob/master/review/developer/cl-descriptions.md) that can complement this proposal

**Comment by tykeal** [comment]
The Linux Foundation Release Engineering team has been maintaining the following "[Best Practices](https://docs.releng.linuxfoundation.org/en/latest/best-practices.html)" document related to changes and code review for some time.

I'll note that we link to a few different blog posts related to writing good commit messages. They go in depth as to the _why_ of doing so which is so often missed in other documents related to the subject.

In particular we've found that the 'seven rules of  a great Git commit message' from the Chris Beam article very useful. Those being:

1.  Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line  (I'll actually stress this one, the English language, and thus Git commit subjects, are easier to read if this held to!)
4. Do not end the subject line with a period
5. Use the imperative mood in the subject line
6. Wrap the body at 72 characters
7. Use the body to explain what and why vs. how

Item three is a contentious one to a lot of people, particular when all the documentation around Semantic Commits (aka Conventional Commits) shows a lowercase type. We've been enforcing with upper case and our subjects are significantly easier to read when doing something like

`git log --pretty=oneline --no-merges`

One of the other repositories used by an internal team is not presently enforcing these sorts of subject lines right now, though folks have started to use them and we've therefore got a mixture of Capitalized verses non-capitalized and it's a lot harder to read.
