### ISSUE TITLE
Error building orchestrator

### ISSUE THREAD

**Issue by pixelatedmirror** [magma/magma#713]
On a clean clone/build of orchestrator, I get the following output:
go: parsing ../../../feg/cloud/go/protos/go.mod: open /src/magma/feg/cloud/go/protos/go.mod: no such file or directory
go: error loading module requirements
/src/magma/orc8r/cloud/go/module.mk:42: recipe for target 'plugin' failed

Full log attached
[build.log](https://github.com/facebookincubator/magma/files/3713661/build.log)

**Comment by themarwhal** [comment]
Hi! We have a commit coming out soon to resolve this issue. In the mean time, please use the 1.0.0-alpha version. https://github.com/facebookincubator/magma/releases/tag/v1.0.0-alpha1.
