### ISSUE TITLE
S8 Inbound Roaming with s6a_proxy and s8_proxy not transferring MSISDN from ULA to CSR

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#7155]
### Your Environment

- **Version:** 1.5
- **Affected Component:** FeG and AGW
- **Affected Subcomponent:** s6a proxy and s8 proxy
- **Deployment Environment:** AWS (orc8r+feg),  bare-metal (AGW)

### Describe the Issue

When using S8 inbound roaming setup, and using roamed HSS for authentication, the MSISDN is not getting mapped correctly from Update Location Answer on s6a to the Create Session Request on S8. 

**To Reproduce**
1. Configure S8 inbound roaming with S8_subscriber using s6a for authentication
2. Follow the guide to setup (note the two tickets below to complete the setup)
3. Try to attach UE with roaming SIM while capturing UDP port 2123 and SCTP on FeG interfaces
4. See that MSISDN in ULA does not match the MSISDN sent in the SCR

**Expected behavior**
The MSISDN in ULA should be sent in SCR. 

**Additional context**
pcap of example where MSISDN in CSR does not match the one sent in ULA. 
[Magma_s6a_and_s8_create_session_request.pcapng.zip](https://github.com/magma/magma/files/6543521/Magma_s6a_and_s8_create_session_request.pcapng.zip)
<img width="1327" alt="Screen Shot 2021-05-25 at 8 46 54 PM" src="https://user-images.githubusercontent.com/61293007/119595221-74601800-bd9a-11eb-99de-278e2c969c8c.png">
<img width="1158" alt="Screen Shot 2021-05-25 at 8 47 17 PM" src="https://user-images.githubusercontent.com/61293007/119595227-75914500-bd9a-11eb-87e0-96517a863cf7.png">

Thanks to @uri200 and @sourabh-nanoti for getting me this far.

**Comment by uri200** [comment]
This has been fixed in master and 1.5 with this PR https://github.com/magma/magma/pull/7207


https://github.com/magma/magma/commits/v1.5

![image](https://user-images.githubusercontent.com/16157139/120367398-a8b96400-c2c5-11eb-8b78-a565c28dd865.png)
