### ISSUE TITLE
change gTEID from octet string to uint32 in AMF and NGAP

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#7174]

**Comment by Lkishor123** [comment]
gTEID was changed from octet string to uint32 using leftshift operator like following:

smf_ctx->gtp_tunnel_id.gnb_gtp_teid =
        (session_seup_resp.pduSessionResource_setup_list.item[0]
             .PDU_Session_Resource_Setup_Response_Transfer.tunnel.gTP_TEID[0]
         << 24) |
        (session_seup_resp.pduSessionResource_setup_list.item[0]
             .PDU_Session_Resource_Setup_Response_Transfer.tunnel.gTP_TEID[1]
         << 16) |
        (session_seup_resp.pduSessionResource_setup_list.item[0]
             .PDU_Session_Resource_Setup_Response_Transfer.tunnel.gTP_TEID[2]
         << 8) |
        (session_seup_resp.pduSessionResource_setup_list.item[0]
             .PDU_Session_Resource_Setup_Response_Transfer.tunnel.gTP_TEID[3]);
But upon recommendation from @panyogesh, I am considering use of DECODE_U32.

**Comment by Lkishor123** [comment]
PR raised: https://github.com/magma/magma/pull/8957, in ready for review state.

**Comment by Lkishor123** [comment]
PR merged.

**Comment by Lkishor123** [comment]
PR merged.
