### ISSUE TITLE
On-prem Magma. Failed connecting AGW and ORC8R (minicube)

### ISSUE THREAD

**Issue by ndacic** [magma/magma#7176]
ORC8R is on Ubuntu 20.04. 
AGW is on Debian

- **Version:1.4**
- **Affected Component:** Orchestrator, Access Gateway
- **Affected Subcomponent:** Communication b/w orchestrator pod/service and AGW 
- **Deployment Environment:** Both AGW and ORC8R are on ESXI VMs. Both are on-prem

### Describe the Issue
Finished installing AGW and ORC8R all seems ok and working, but I am stuck at last step :(
I am facing the issue with interconnecting them. 

In instructions for connecting AGW states:
![image](https://user-images.githubusercontent.com/82126098/119787981-0880cb00-bed2-11eb-9cb5-74a46cc678d2.png)

On ORC8R I have following k8s services: 
![image](https://user-images.githubusercontent.com/82126098/119788244-4251d180-bed2-11eb-8ef8-7bffd9b7e8de.png)

How do they map? To what k8s services should I instruct AGW to send info to?
My idea was to open ports on needed k8s services make them listen, then in AGW config instruct it to send info to those open interfaces.

Thanks in advance!

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/
