### ISSUE TITLE
Hardcoded address requirement on eNodeB interface

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#718]
Is there an underlying reason why enodebd would only enforce routing of TR069 traffic only when the eNodeB interface address is one of these:

    EXPECTED_IP4 = ('192.168.60.142', '10.0.2.1')

See: [enodeb_iptables_rules.py](https://github.com/facebookincubator/magma/blob/8634717a4e43f6189c29a9d51f17989d5ef04323/lte/gateway/python/magma/enodebd/enodebd_iptables_rules.py#L33)

It breaks eNodeB communication where the pre-exising network setup is different.

**Comment by xjtian** [comment]
IIRC when I reviewed this, I had this just log a warning and continue with provisioning - is this not what you're observing? I think if you look at https://github.com/facebookincubator/magma/blob/8634717a4e43f6189c29a9d51f17989d5ef04323/lte/gateway/python/magma/enodebd/enodebd_iptables_rules.py#L133 we should just log and move on regardless

**Comment by bmurithi** [comment]
Oh got it. Looking at it a little further, it looks like it is a result of
the "unexpected rules checks" further up in the module.

Had to reconfigure the eNodeB management IP to the configured on-gateway IP
to get enodebd reporting the actual state.

**Comment by xjtian** [comment]
Yeah this is a bit of a sanity check for configuration, nothing in that file should block workflows, just log warnings.

Instead of fiddling with management IP on the enodeB, you can also use the network DNS config API to hijack DNS resolution for your enodeB's default management hostname. We always hijack baiomc.cloudapp.net in dnsd for example

**Comment by bmurithi** [comment]
I'll take a second look at this. From what I recall, the NAT rule needs to
be explicitly set up even with DNS overrides.

Also, there are cases where the eNodeB resets the management IP to a
host:port combo with 8080.

**Comment by bmurithi** [comment]
There's definitely a codepath that results in the NAT rule not getting
installed.

There are other valid rules where NAT rules may already exist in the chain.

It feels like there should be a warning in this case as well and just set
up the rule.
