### ISSUE TITLE
[Proposal] Refactoring APN models and associated services on Orc8r and Gateways

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#7189]
### In Magma, APN configuration consists of two main entities.
* APN - network level entity which defines APN information and Qos characteristics.
* APN resource - gateway level entity which provides transport information for APN

### Currently two main issues exists in the way APNs are handled
* Poor abstraction - APN resource entity contains low level network information including vlan_id, gateway_ip, gateway_mac information. It is undesirable to directly associate the low level network information with an APN resource entity and abstracting these details into a separate transport entity is important for enabling the transport to evolve independent of APN resource mapping. For e.g: Immediate use case is for adding vxlan as a new transport mechanism for APN. In future, we could possibly extend this to other forms of transport including GRE tunnels, IP in IP etc.

* APN resource configuration is too tightly coupled with Subscriberdb data models. This makes any further changes to APN config hard and unnecessarily affects subscriber data models.

## Proposal
* Add new entity which encapsulates the data network information specific to each gateway and refactor "apn_resource" and rename "apn_resource" → "apn_gateway_config"
* Add APN DB servicer on the Orc8r to provide APN specific configs. This will include both network level and gateway level configs. 
* Add APN DB client on ConfigDB(rename subscriberDB -> ConfigDB) and periodically poll apn configs from Orc8r and store locally on sqlite db.
* Refactor mme and enhance pipelined code to get transport level configs from subscriberdb and directly program APN transport information through pipelined.

**Comment by jpad-freedomfi** [comment]
@karthiksubraveti not sure if I'm crossing topics, but we had discussed with @pshelar earlier it would be good to move IP allocation scheme to the APN level. Is that in scope of the this proposal and/or does anything being discussed here preclude that change later?

**Comment by karthiksubraveti** [comment]
> @karthiksubraveti not sure if I'm crossing topics, but we had discussed with @pshelar earlier it would be good to move IP allocation scheme to the APN level. Is that in scope of the this proposal and/or does anything being discussed here preclude that change later?

@jpad-freedomfi  This proposal moves the IP allocation scheme to APN level. This proposal infact moves it to per APN per gateway level. We are thinking of moving following attributes within gateway specific APN configuration. 
cc @pkapatsos-blinq  @pshelar 
```
enum EgressType {
  VLAN = 0;

  // Add other egress configurations including vxlan, gre
  // in the future
}

message VlanConfig {
    uint32 vlan_id = 4;
}

message APNTransportConfig {
    string gateway_ip = 1;
    string gateway_mac = 2;
    EgressType egress_type = 3;
    VlanConfig vlan_config = 4;
}

// Gateway specific APN configuration
message APNGatewayConfig {
    uint32 apn_id = 1;
    APNFilter apn_filter = 2;
    string dns_primary = 3;
    string dns_secondary = 4;
    enum IpAllocatorType {
          IP_POOL = 0;
          DHCP = 1;
    }
    IpAllocatorType ip_allocator_type = 5;
    string ip_block = 6;

    APNTransportConfig transport_config = 7;
}
```
