### ISSUE TITLE
[orc8r][helm][metrics] metrics-storeconfig pod fails to do apk update sometimes and crashes

### ISSUE THREAD

**Issue by mattymo** [magma/magma#7198]
### Your Environment

- **Version:** 1.5
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** orc8r-metrics-storeconfig
- **Deployment Environment:**  bare-metal

### Describe the Issue

```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 14 distinct packages available
cp: unrecognized option: n
BusyBox v1.32.1 () multi-call binary.
```

**To Reproduce**
1. Deploy orc8r helm chart

**Expected behavior**
orc8r-metrics-storeconfig deployment should point to an image with coreutils already installed (so it can run cp -n)

**Screenshots**

**Additional context**
This issue is only present in some countries where there seem to be regional blocks on accessing dl-cn.alpinelinux.org

**Comment by mattymo** [comment]
Possible solutions:
use a base ubuntu docker image (or any other distro because they always include coreutils)
use an alpine image with coreutils such as https://hub.docker.com/r/grrywlsn/alpine-coreutils-curl

**Comment by eduardoefb** [comment]
I m getting the same issue when try to use bare-metal-ansible installation:


root@compute1:/etc/orc8r/charts# kubectl -n magma logs -f orc8r-metrics-storeconfig-m8bxg
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
2 errors; 14 distinct packages available
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
cp: unrecognized option: n
BusyBox v1.32.1 () multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST

Copy SOURCE(s) to DEST

	-a	Same as -dpR
	-R,-r	Recurse
	-d,-P	Preserve symlinks (default if -R)
	-L	Follow all symlinks
	-H	Follow symlinks on command line
	-p	Preserve file attributes if possible
	-f	Overwrite
	-i	Prompt before overwrite
	-l,-s	Create (sym)links
	-T	Treat DEST as a normal file
	-u	Copy only newer files
cp: unrecognized option: n
BusyBox v1.32.1 () multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST
