### ISSUE TITLE
AGW Image Enrichment

### ISSUE THREAD

**Issue by arunuke** [magma/magma#7201]

**Comment by arunuke** [comment]
In any new build of AGW AMI, the newly generated AGWs should address the following (quite likely in ami-configure)

1. Delete the following

- gw_challenge.key in /var/opt/magma/certs
- remove /etc/snowflake

In any new customization of an AGW AMI, the AMI should allow for the following (quite likely in agw-configure)

1. Optionally, provide a way to add the following

- add a public key that is available in an AWS region to the authorized_keys of the AGW image. This is required for scenarios where AMIs have to be embedded in the image (ex: Snowflake and certain use-cases of Snowball)

In a new deployment, update /etc/hosts with the IP address of the new instance.

**Comment by quentinDERORY** [comment]
The key will be picked up from AWS KMS and only rsa keys are supported. EC2 keys is not possible as I cannot get public key from awscli.
