### ISSUE TITLE
Porting from magma-5G to magma(ngap,grpc, mme modules)

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#7222]

**Comment by ganeshg87** [comment]
Update 09:
------------
       - magma-5g branch code ported to magma and tested with UERANSIM
       - **directory structure got changed** in the master branch, I was not able to update the latest code to build the package for DSTester validation.
       - started merging code as per the new directory structure in master.
Old directory Structure:
![image.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/76277fa9-2150-4c19-adac-4873c3a4f619)

New directory structure:
![image.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/74f759bd-5b07-4ef6-bc7a-9e9576b26f9e)

**Comment by ganeshg87** [comment]
Update:
raised PR [WIP] https://github.com/magma/magma/pull/7565

**Comment by ganeshg87** [comment]
updated code review with latest P0 fixes done on magma-5G
code review request raised and review is progress
https://github.com/magma/magma/pull/7565

**Comment by ganeshg87** [comment]
- resolved review comments provided by Ulas and updated the PR
working on splitting PRs
 
PR3 - Changes only on the mme service side of the code + unit tests - finished and updated review.

 In Progress actions:
 PR1 -  New 5G authentication vector generation and rpc servicer + unit tests - Yogesh is working 
 PR2 -  N11 changes + session_manager.proto - building patch.

**Comment by ganeshg87** [comment]
Update:
--------
PR2 - N11 changes + session_manager.proto 
-resolved all review comments and working on test coverage. 
I am planning to finish today, the worst case will be finished by tomorrow.
https://github.com/magma/magma/pull/7786

PR3- Changes only on the mme service side of the code + unit tests
 - resolved all review comments and updated the review.
 - recently magma is completely moved to ubuntu-based VM. have tested on Debian.
    need to validate(basic registration & pdusession, dereg) on Ubuntu
https://github.com/magma/magma/pull/7565

PR1 - New 5G authentication vector generation and rpc servicer + unit tests - Yogesh is working

**Comment by ganeshg87** [comment]
Update:
- added the n11 unit test framework, started adding test cases.
- resolved linking issues with the help of Ganesh I and Yogesh.
- Tied structure mismatch resolved in amf code (session_manager.proto )

**Comment by ganeshg87** [comment]
Current Status: 
----------------
        Ulas review comments were resolved given in PR3 #7565, Current Testing in progress, a couple of issues during testing, Please find below
      
	 1. memory corruption issue was resolved(involved Yogesh & Kaleem).
![image_2021_07_06T15_51_34_094Z.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/a2f281e9-3418-4bdf-b253-606c0aad9205)

In Progress:	 
 - AMF is now not responding to PDUSession Request, analysis in progress 
 - need resolve Marie's review comments for PR2 #7786

**Comment by ganeshg87** [comment]
review in progress:
--------------------
https://github.com/magma/magma/pull/7565

**Comment by ganeshg87** [comment]
working one below activities on #7565
warning cleanup and log messages cleanup

**Comment by ganeshg87** [comment]
- rebased #7565 and resolved merge issues, validated with UERANSIM
- amf log cleanup activity in progress with another task #8266

**Comment by ganeshg87** [comment]
#7565 merged to master
