### ISSUE TITLE
Create a scenario file to verify when select the slice type which is not supported by AMF (SST value 2 or 3) using DStester

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#7239]

**Comment by Balaji-Jatla** [comment]
https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt

From the above Google drive link we can find the Scenario file.
File name - Unsupported_Slice.xml

**Comment by Balaji-Jatla** [comment]
Please find the Pcap from this Drive link for slice type https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
pcap name - Slice2-.pcap
