### ISSUE TITLE
[MME] 5G branch failing remote deploy in CI

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#7244]
## Summary

It has been noticed that on the magma-5G branch, `make build_oai` is [failing lte-agw-deploy](https://app.circleci.com/pipelines/github/magma/magma/23696/workflows/289a9563-ff21-4a43-ac3d-94c92cfb2064/jobs/251438).

**Comment by electronjoe** [comment]
## Early Findings

From `magma-5G` branch, I can successfully `make build_oai` within the following environments.

- Docker image built from `lte/gateway/dockerfile/mme/Dockerfile.ubunto20.04`
- Vagrant `magma` VM

I'm now attempting `fab test package:vcs=git` to see if I can reproduce the failure on my laptop.

**Comment by electronjoe** [comment]
Additionally, @themarwhal suggested that I try building with `make build_oai BUILD_TYPE=RelWithDebInfo` to see if this can generate the failure. And she notes that we should perhaps include this build environment in our presubmit CI as well.

I'll try `RelWithDebugInfo` now with my Docker environment as a starting point.

**Comment by ekowtaylor** [comment]
cc. @ulaskozat , @tmdzk

**Comment by electronjoe** [comment]
Marie was right, `make build_oai BUILD_TYPE=RelWithDebInfo` is resulting in drastically longer build times - though I think not uniformly across our compilation units. I've been watching e.g. `[1838/1972] Building C object tasks/nas/CMakeFiles/TASK_NAS.dir/esm/sap/esm_recv.o` for at least five minutes now... from within my Docker environment. Will wait out this long process and see if linking fails also.

[edit] Actually - that build has just totally deadlocked - perhaps a resource issue with my allocation to Docker (could it be that release builds require more than 12 Gigs of VM RAM...)

**Comment by electronjoe** [comment]
Ok, reproduced build failure from my local laptop's Magma repo, `lte/gateway/` sub-directory, by execution of `fab test package:vcs=git`.

**Comment by electronjoe** [comment]
I'm noticing that some of the failed linking is within `lte/gateway/c/oai/tasks/ngap/`:

```
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:204: undefined reference to `__asan_report_store4'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:204: undefined reference to `__asan_handle_no_return'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__ubsan_handle_type_mismatch'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__asan_report_load8'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__ubsan_handle_type_mismatch'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__asan_report_load8'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__ubsan_handle_type_mismatch'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__asan_report_load8'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__ubsan_handle_type_mismatch'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__ubsan_handle_type_mismatch'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__asan_report_load8'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__ubsan_handle_type_mismatch'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__asan_report_load4'
[vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c:207: undefined reference to `__asan
```

And I am also seeing the following Diff between `Master` and `magma-5G` branches for the associated CMakeLists:

```
➜  gateway git:(pr-mme-app-state-converter) ✗ diff ~/Documents/magma/lte/gateway/c/oai/tasks/ngap/CMakeLists.txt ~/Documents/vstest/magma/lte/gateway/c/oai/tasks/ngap/CMakeLists.txt
2a3
> set(CMAKE_BUILD_TYPE Debug)
```

Making me wonder if this is a critical change.

**Comment by themarwhal** [comment]
Seems like this issue is resolved? (after so many retries :D )
<img width="909" alt="Screen Shot 2021-06-02 at 7 03 22 AM" src="https://user-images.githubusercontent.com/37634144/120476917-c394e280-c370-11eb-9aa2-33b8d0cd5698.png">

**Comment by electronjoe** [comment]
Looks goodish! Calling it "fixed" for this particular issue (linking issues, build times).
