### ISSUE TITLE
Gateway CPU % incorrectly showing 100% on Amazon Outpost

### ISSUE THREAD

**Issue by sullivg2** [magma/magma#7250]
### Your Environment

-**Version:**  1.5
- **Affected Component:** NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** AWS (orc8r), Amazon Outpost (AGW)

### Describe the Issue

In the metrics tab our gateway CPU % is showing at 100% all the time, while our own monitoring of the underlying infra is showing pretty light CPU load. 

**To Reproduce**
1. Go to 'Metrics'
2. Click on 'Gateways'
3. Scroll down to 'Gateway CPU %'
4. See error: CPU % running at 100% all the time

**Expected behavior**
I expect to see an accurate reading of the CPU % for my AGW.

**Screenshots**

![Screenshot 2021-06-01 143252](https://user-images.githubusercontent.com/10464262/120366654-4c1a7100-c2e6-11eb-9ed1-d0f854d9e436.png)

Our monitoring tools:

<img width="1028" alt="Screen Shot 2021-06-01 at 10 13 04 AM" src="https://user-images.githubusercontent.com/10464262/120366403-ffcf3100-c2e5-11eb-92d7-2b80750c2e4f.png">

**Comment by milapjoshi** [comment]
Did some narrow down and found td-agent-bit.service was not running. we started that service manually.

However, that service is not enabled on reboot.  @tmdzk @arunuke FYI
