### ISSUE TITLE
[pipelined] Support for Extended bitrates for 5g

### ISSUE THREAD

**Issue by uri200** [magma/magma#7278]
In order to support extended bit rates for 5g (feature defined here https://github.com/magma/magma/issues/5676), we are introducing a flag on Qos to set units of the bitrates (either `bps` or `kbps`) 

Pipelined needs to check the value of units to apply the right value for Qos

Pipelined will receive a new field called `br_units` on `apn_ambr` (as you can see below). That field is the multiplier for the values. 

This new proto is defined in this pr https://github.com/magma/magma/pull/7277/files

```
Jun 02 11:47:49 agw sessiond[31976]:   magma.lte.ActivateFlowsRequest {
Jun 02 11:47:49 agw sessiond[31976]:       sid {
Jun 02 11:47:49 agw sessiond[31976]:         id: "IMSI999991234567810"
Jun 02 11:47:49 agw sessiond[31976]:       }
Jun 02 11:47:49 agw sessiond[31976]:       ip_addr: "172.17.138.133"
Jun 02 11:47:49 agw sessiond[31976]:       request_origin {
Jun 02 11:47:49 agw sessiond[31976]:       }
Jun 02 11:47:49 agw sessiond[31976]:       apn_ambr {
Jun 02 11:47:49 agw sessiond[31976]:         max_bandwidth_ul: 100000000
Jun 02 11:47:49 agw sessiond[31976]:         max_bandwidth_dl: 100000000
											 br_unit: 1				    	<---- kbps 
Jun 02 11:47:49 agw sessiond[31976]:       }
Jun 02 11:47:49 agw sessiond[31976]:       msisdn: "1234567810"
Jun 02 11:47:49 agw sessiond[31976]:       uplink_tunnel: 8
Jun 02 11:47:49 agw sessiond[31976]:       downlink_tunnel: 218103808
Jun 02 11:47:49 agw sessiond[31976]:       policies {
Jun 02 11:47:49 agw sessiond[31976]:         rule {

```

Note that the option of changing proto from uint32 to uint64 was discarded to avoid inconsistencies between versions and between systems (3gpp uses that flag too)

**Comment by pshelar** [comment]
@karthiksubraveti can you take care of protobuf changes in the APN refactoring ?

**Comment by ekowtaylor** [comment]
@pshelar, what is the priority and relevance of this?

**Comment by pshelar** [comment]
lets see if @panyogesh or @prabinakpattnaik can take care of this. cc: @ulaskozat

**Comment by panyogesh** [comment]
@pshelar : I have assigned the task to Prabina.

**Comment by ssanadhya** [comment]
@prabinakpattnaik , are you planning to work on this issue?

**Comment by prabinakpattnaik** [comment]
@ssanadhya , Yes. Code is ready for this issue. I will raise the PR coming week.
