### ISSUE TITLE
NGSetupRequest_Reject for unsupported slice types

### ISSUE THREAD

**Issue by Balaji-Jatla** [magma/magma#7298]
currently 5G MVC supports EMBB slice type
if any other slice type is asked for, AMF  is expected to send NGSetupRequest_Reject.

**Comment by rupa455wavelabs** [comment]
Currently 5G MVC supports EMBB slice type
if any other slice type is asked for, AMF is expected to return cause #69. but AMF is sending UEContextRelease to gNB.

**Comment by Balaji-Jatla** [comment]
https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
Pcap name -Slice-2.pcap



https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt
From the above Google drive link we can find the Scenario file.
File name - Unsupported_Slice.xml

**Comment by Lkishor123** [comment]
PR (https://github.com/magma/magma/pull/9048) fixes the issue.

**Comment by Lkishor123** [comment]
PR merged.
