### ISSUE TITLE
Receiving Malformed security mode command from AMF when tested with UE security capabilities as false

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#7325]

**Comment by Balaji-Jatla** [comment]
Tested the scenario file with EA0, IA0 security capabilities as false using dstester, In the pcap we see security mode reject due to malformed security mode command from AMF.

https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
Pcap name - 5GMM_cause#23_2.pcap

**Comment by rupa455wavelabs** [comment]
Expected behaviour: Registration Reject

If the REGISTRATION REQUEST message is received with invalid or unacceptable UE security capabilities 
(e.g. no 5GS encryption algorithms (all bits zero), no 5GS integrity algorithms (all bits zero), mandatory 5GS 
encryption algorithms not supported or mandatory 5GS integrity algorithms not supported, etc.), the AMF shall 
return a REGISTRATION REJECT message.

Actual behaviour:
Selected 5GS Encryption(EA0) & Integrity(IA0) algorithms as false and tested it in DStester, AMF returns Security Mode Reject due to Malformed security command. Needs to be fixed

https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt
Scenario file: Unsupported_Security_Capabilities.xml

**Comment by Chandhu-Wavelabs** [comment]
**ETSI TS 124 501 V16.5.1**
8.2.6.4 UE security capability
The UE shall include this IE, unless the UE performs a periodic registration updating procedure.

**UE should not send registration request message without the IE **UE SECURITY CAPABILITY** for initial registration request**.

**Comment by rupa455wavelabs** [comment]
Creating a magma-5G package with #8218 PR, Need to test it once package creation completes.

**Comment by rupa455wavelabs** [comment]
Tested the scenario with UE security capabilities as false in TVM setup, able to see registratoin reject with cause conditional IE error.

pcap: Registration_Reject
https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
