### ISSUE TITLE
On magma-5G authentication procedure is failing with protocol error #111

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#7326]
Issue is reproducible  the pcap and log files are attached.

**Comment by Balaji-Jatla** [comment]
https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
Pcap name - .Authentication procedure is failing with protocol error.pcap

**Comment by panyogesh** [comment]
Rupa : Can you please verify it in latest magma-5G or Master with #7565 and check if issue is getting reproduced.

**Comment by Kaleem-Wavelabs** [comment]
![20-Jul.jpg](https://images.zenhubusercontent.com/608bac58b7ba983c0fb15837/0038da23-99b5-4e73-8ed9-1054fa20850e)

Tested with 3 digit MCC and MNC, it is fine now with the latest code as per Roopa
We can process to close this task.
