### ISSUE TITLE
deprecate `relay_enabled` field in SessionD mconfig

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#7336]
## Goal for this issue
1. Get familiar with how mconfig.proto changes should be generated
2. Get familiar with how mconfig object is used in SessionD / C++

## Background about the `relay_enabled` field
`relay_enabled` was replaced by `gx_gy_relay_enabled` ~9 months ago, but we never marked the field as deprecated. 

## Steps needed
* Mark the field as deprecated: `bool relay_enabled = 2 [deprecated = true];`
* Run `./build.py --generate` in `$MAGMA_ROOT/orc8r/cloud/docker` to generate *.go changes. These files need to be committed.
* Run `./build.py --test` in `$MAGMA_ROOT/orc8r/cloud/docker` to run all orc8r tests
* Eliminate all references to the deprecated field in `lte/gateway/c/session_manager`. Then run `make test_session_manager` to make sure all tests pass. 

Bonus points if you do the same for `message MME {` (in a separate PR) :) It is the same steps, except you need to run `make test_oai`

**Comment by waqaraqeel** [comment]
Has the whole `message MME` structure been deprecated? What replaces it?
