### ISSUE TITLE
UT-failure: test_itti.cpp max latency

### ISSUE THREAD

**Issue by pshelar** [magma/magma#7337]
### Your Environment

- **Version:** master
- **Affected Component:** ] Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** CI

### Describe the Issue
https://app.circleci.com/pipelines/github/magma/magma/24839/workflows/a909a378-9f80-4cb7-b106-49b90cc96c47/jobs/263686
```
[magma@10.240.0.45] out: [vagrant@127.0.0.1:2222] out: /home/vagrant/magma/lte/gateway/c/oai/test/itti/test_itti.cpp:134: Failure
[magma@10.240.0.45] out: [vagrant@127.0.0.1:2222] out: Expected: (msg_latency) <= (1000), actual: 1725 vs 1000
```

**Comment by ulaskozat** [comment]
@pshelar this should be a rare occurrence. I can increase the check to 10000 microseconds to make it less flaky.

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/
