### ISSUE TITLE
Magma not deleting UE context after UE release command leading to asynchronous UE state between eNodeB and AGW

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#7348]
Your Environment
**Version:**1.3.3-1614917907-371c6462
Affected Component: Access Gateway
Affected Subcomponent: Mobilityd
Deployment Environment: bare-metal (AGW)

### Describe the Issue

Due to Radio Coverage Flap , UE Release Procedure takes place i.e. UE Release Request received from eNodeB with Cause 21 based on which UE Release command is sent by Magma and received UE Release complete. Yet the MME never removed the context of this UE instead added a paging flow. Later the same UE sent another GUTI based Attach Request (another UE ID)  which was accepted by Magma, but this new UE Id didnt update in MME. Later, Magma released old UE ID of this UE due to Expired Implicit Detach Timer, (since the UE is no more using this ue id, therefore no signaling happens with this UE and therefore timer expires) , Since the UE ID at Magma was never updated, Magma releases old UE ID due to Implicit Detach and sends UE Release Command for old UE ID to the eNodeB, while the eNodeB doesnt have this context any more since it already deleted during previous release procedure and maintains another (new) UE ID against this UE. This results in asynchronous state of UE between eNodeB and AGW.

**To Reproduce**
1. Enable DHCP IP assignment for UEs
2. Attach the UE
3. Simulate UE Release request with Cause 21.
4. Try another GUTI Based Attach.
5. check the logs

**Expected behavior**
Magma MME should have released the context during first UE Release procedure. and should have updated new UE ID for the new GUTI based Attached for this UE.

**Screenshots**

@15:46:35 UE Release Request was received from the eNodeB with Cause 21 against UE ID 6, IMSI 314030000015580 which followed the normal procedure until UE Release complete received. However magma added a paging flow for IP 10.1.39.174, the IP which was assigned by the DHCP Server.
![image](https://user-images.githubusercontent.com/77636702/120908376-48148900-c62f-11eb-87dd-3ae3130e2465.png)

@15:46:49 GUTI based Attached request received for same UE with UE ID 17, Magma successfully Attaches the UE.
![image](https://user-images.githubusercontent.com/77636702/120908428-c4a76780-c62f-11eb-8a28-a795a4daa303.png)

Re-allocation of IP 10.1.39.174 for sid IMSI314030000015580.internet without MME releasing can be clearly seen
![image](https://user-images.githubusercontent.com/77636702/120908459-2c5db280-c630-11eb-9147-7bd5cb8bdfe2.png)

@17:42:35 After the expiry of Implicit Detach Timer, Magma Released the context with UE ID 6 (Because no signaling would be observed against that ID Since the ID changed to 17 which was never updated by Magma)

![image](https://user-images.githubusercontent.com/77636702/120908495-89f1ff00-c630-11eb-997e-c04482a3ce5c.png)

Here Magma sent UE Release command against UE Id 6 which was never responded by the ENodeB since it had deleted this UE ID earlier and is now maintaining new UE ID i.e. 17.

As a result, the UE got released at MME while still remained connected at eNodeB.

**UE Status at eNodeB**

![image](https://user-images.githubusercontent.com/77636702/120908581-38963f80-c631-11eb-88f1-3bc1d8a778af.png)

**UE Status at AGW**

![image](https://user-images.githubusercontent.com/77636702/120908604-72674600-c631-11eb-8e3e-0149b50755d1.png)

**Additional context**
Logs Attached

[log.zip](https://github.com/magma/magma/files/6603429/log.zip)

**Comment by shehzadalee** [comment]
@jpad-freedomfi @ulaskozat @sourabh-nanoti

**Comment by ulaskozat** [comment]
Context release does not release the session. So paging rule should be indeed installed. What is unexpected is that when a new attach request comes in for an already attached UE, the UE should have been first implicitly detached and the new attach request should have been proceeded. But as far as I see, MME is logging that no GUTI is present. Can you attach the pcap? I want to see whether tmsi's are matching.

**Comment by ulaskozat** [comment]
In the log:
`012242 Fri Jun 04 15:46:49 2021 7F64BE893700 INFO  NAS-EM tasks/nas/emm/Attach.c :0222ATTACH REQ (ue_id = 0x00000017) (GUTI = 314.030|0001|01|00000000)`

M-tmsi from decoded IE is printed as `00000000`. This does not look like a legit m-tmsi value that could be potentially assigned by MME for 1.3.3  (which uses memory address of the UE context for the assignment).

**Comment by jpad-freedomfi** [comment]
@ulaskozat this mme should have that fix. We have a patched mme that includes https://github.com/magma/magma/pull/7109 

I just checked and it is the mme running on this AGW. 

```
magma@agw:~$ md5sum mme_13head_pr7109 
b2e6baa2228a28e59fa924c2ed6f0625  mme_13head_pr7109
magma@agw:~$ md5sum /usr/local/bin/mme 
b2e6baa2228a28e59fa924c2ed6f0625  /usr/local/bin/mme
magma@agw:~$ 
```

**Comment by ulaskozat** [comment]
@jpad-freedomfi  then it is a random assignment, still seeing all zeros is quite suspicious.

**Comment by shehzadalee** [comment]
Hi @ulaskozat What we have learned from other networks is that GUTI value 00000000 is being received by different UEs and in such a situation Magma sends Identity Request to retrieve the IMSI of the UE however once the IMSI is received. Below log is observed.

`012268 Fri Jun 04 15:46:49 2021 7F64BE893700 ERROR MME-AP tasks/mme_app/mme_app_context.c :0618[314030000015580]Error could not update this ue context 0x62100008e900 enb_ue_s1ap_ue_id 0x000027 mme_ue_s1ap_id 0x00000017 mme_teid_s11 0x0 : HASH_TABLE_KEY_NOT_EXISTS
`
Looks like Magma is unable to update the context of UE in such scenario which is weird. This seem to be quite frequent in many networks now. would appreciate your support here.

**Comment by shehzadalee** [comment]
Hi @ulaskozat Please find attached the PCAP and Logs as requested earlier for this case.
The GUTI in this PCAP is request 00000000 by the UE, but then MME sends Identity Requests messages requesting the IMSI and gets the attach procedure successful.
[0 GUTI.zip](https://github.com/magma/magma/files/6734008/0.GUTI.zip)

**Comment by ulaskozat** [comment]
@pruthvihebbani please provide your updates and estimated time to finish here.

**Comment by pruthvihebbani** [comment]
Issue: UE does GUTI attach with 0 M-TMSI, MME is not able to fetch the old context and perform implicit detach. Due to this the mobile reachability timer which was started during the previous attach does not get stopped. MME proceeds with the new attach without clearing the old context which leads to expiry of mobile reachability timer. 
Raised PR- https://github.com/magma/magma/pull/7916. This PR fixes the issue by performing identification procedure in case MME is not able to fetch context using GUTI. After receiving IMSI in identification response message, if context already exists for the user, MME triggers implicit detach and then proceeds with the new attach

**Comment by ulaskozat** [comment]
closing this issue as fix has been landed and tested (cc @amarpad)
