### ISSUE TITLE
Cannot run `./build.py --generate` in `orc8r/cloud/docker` in docker env on Linux host

### ISSUE THREAD

**Issue by waqaraqeel** [magma/magma#7369]
### Your Environment

- **Version:** latest master (Magma @ cc00897a)
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** `build.py`
- **Deployment Environment:** e.g. local docker-compose (orc8r)

### Describe the Issue

When running `./build.py --generate` or `./build.py -m` in `orc8r/cloud/docker`, the directories mounted in `/src/magma` are all empty. The `-v` switch for `docker-compose` does not seem to working on Linux hosts (verified on Ubuntu 20.04 bare metal and WSL2). It works on macOS host.

**To Reproduce**
1. Set up docker env on a Linux/WSL host. Instructions [here](https://github.com/magma/magma/tree/master/.devcontainer).
2. `cd $MAGMA_ROOT/orc8r/cloud/docker`
3. `./build.py -m`
4. `find /src/magma`: all directories are empty. `docker-compose -v` mounts have failed.

**Expected behavior**
`orc8r`, `lte` and other modules should be mounted in the `magma` directory.

**Comment by volkfield** [comment]
I am having the same issue did you ever find a resolution?

**Comment by waqaraqeel** [comment]
> I am having the same issue did you ever find a resolution?

I did not :( Could you please comment with your Linux kernel + docker version? Thanks!

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/
