### ISSUE TITLE
[orc8r] Swagger API not showing home endpoints on local dev setup

### ISSUE THREAD

**Issue by uri200** [magma/magma#7374]
On the local or8cr dev setup at `~/magma/orc8r/cloud/docker` , after doing 
```
./build.py -g
./run.py
```

and accessing to swagger API through https://127.0.0.1:9443/swagger/v1/ui/, the home page doesn't show endpoints. The page shows login all the time (as seen on the picture below)

The only way to access to endpoints is through the side bar.

![image](https://user-images.githubusercontent.com/16157139/121082474-01d83a80-c793-11eb-87e0-13c1d1122c9a.png)

**Comment by ardzoht** [comment]
I am facing the same issue while spinning up my local Orchestrator, accessing `lte` on menu I can see the endpoints successfully
