### ISSUE TITLE
NMS login unable -  Error: Invalid organization!

### ISSUE THREAD

**Issue by robinge330** [magma/magma#7391]
### Your Environment

- **Version:1.5
- **Affected Component:**  NMS
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** Openstack VM's for AGW and Orchestrator

### Describe the Issue
AGW was deployed on Openstack VM's using https://docs.magmacore.org/docs/lte/deploy_install_ubuntu
Orchestrator was deployed on Openstack VM's using bare-metal-ansible
 Metallb load balancer exists for the NMS
 On trying to login to NMS using the  loadblance IP 

root@compute1:~# kubectl -n magma get services
NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                    AGE
nginx-proxy                     LoadBalancer   10.233.62.182   10.53.213.93   443:32074/TCP                                              3d18h

kubectl -n magma logs -f nms-magmalte-f46488596-6wwqf

{"message":"::ffff:10.233.111.15 - - [08/Jun/2021:13:34:28 +0000] \"GET /nms/static/images/favicon.png HTTP/1.0\" - - \"https://10.53.213.93/user/login?to=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-06-08T13:34:28.861Z"}
{"message":"::ffff:10.233.111.15 - - [08/Jun/2021:13:35:08 +0000] \"GET /nms/static/images/favicon.png HTTP/1.0\" - - \"https://10.53.213.93/user/login?to=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-06-08T13:35:08.440Z"}
{"message":"::ffff:10.233.111.15 - - [08/Jun/2021:13:39:09 +0000] \"POST /user/login HTTP/1.0\" 302 114 \"https://10.53.213.93/user/login?to=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-06-08T13:39:09.139Z"}
{"level":"error","message":"Error getting organization Invalid organization!","stack":"Error: Invalid organization!\n    at getOrganization (/usr/src/node_modules/@fbcnms/express-middleware/organizationMiddleware.js:44:9)","label":"auth/express.js","timestamp":"2021-06-08T13:39:09.160Z"}
{"message":"::ffff:10.233.111.15 - - [08/Jun/2021:13:39:09 +0000] \"GET /user/login?invalid=true&to=%2F HTTP/1.0\" 200 - \**"https://10.53.213.93/user/login?to=%2F**\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-06-08T13:39:09.167Z"}
{"message":"::ffff:10.233.111.15 - - [08/Jun/2021:13:39:09 +0000] \"GET /nms/static/dist/vendor.d4f8252eb2e49a31d879.chunk.js HTTP/1.0\" 304 - \"https://10.53.213.93/user/login?invalid=true&to=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-06-08T13:39:09.232Z"}
{"message":"::ffff:10.233.111.15 - - [08/Jun/2021:13:39:09 +0000] \"GET /nms/static/dist/login.db1151080950de40be58.js HTTP/1.0\" 304 - \"https://10.53.213.93/user/login?invalid=true&to=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-06-08T13:39:09.240Z"}
**(node:27) **UnhandledPromiseRejectionWarning: Error: Invalid organization!
    at getOrganization (/usr/src/node_modules/@fbcnms/express-middleware/organizationMiddleware.js:44:9)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)****

i did got over https://github.com/magma/magma/issues/1611
verified the proxy_ssl.conf which has below entry ,

server {
  listen 443;
  ssl on;
  ssl_certificate /etc/nginx/conf.d/cert.pem;
  ssl_certificate_key /etc/nginx/conf.d/key.pem;
  location / {
     proxy_pass http://magmalte:8081;
     **proxy_set_header Host $http_host;**
  }
}

Kindly could you guide the issue resolution here so i can login in NMS successfully.

**To Reproduce**
deploy AGW and Orch on openstack VM's and connect to NMS.

**Expected behavior**
Successfully login to NMS

**Screenshots**
**Additional context**
logs in issue description

**Comment by robinge330** [comment]
Login as master.nms.<domain_name> done to resolve this and not with IP

**Comment by assyafii** [comment]
> Login as master.nms.<domain_name> done to resolve this and not with IP

Solved for me, Thanks
