### ISSUE TITLE
QoS control for inbound roaming bearers 

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#7415]
This feature request is about MME applying some QoS policy while forming bearers over s5/s8 for inbound roaming. The idea is to have Magma some control on the QoS for roaming subscribers.

**Comment by ulaskozat** [comment]
I am assuming the ask here is to overwrite QoS policies for the default and dedicated bearers fetched from PGW (non-Magma) to RAN as they are routed via Magma. So Magma will not perform any enforcement. cc   @sourabh-nanoti, @ekowtaylor, @uri200, @talkhasib.

Roughly the subtasks are:

- Design doc and proposal (5 SWE days)
- Reuse/extend current policy APIs and functional testing (3 SWE days)
- Extensions to policy streaming if needed and functional testing (2 SWE days)
- Updates to S8 task to fetch policies, correlate them with local policies,  and overwrite policies communicated via create session response and create bearer requests with unit tests. (5 SWE days)
- TeraVM test case development, testing, verification. (5 SWE days)

**Comment by uri200** [comment]
Before adding estimates I would like to better understand the feature and decide where we are going to place it.

Here we have 2 different places were we can do the overwrite: feg or agw. If we configure qos policy on the FEG, we will be able to set a global Qos per operator. MME will not need any change. No mapping will be required because the FEG is already mapped to one specific operator. This solution would be pretty quick and would not require much testing since it is pretty easy to add unit test at FEG.

But if we add this QOS overwrite profile at mme we will have to maintain a map on the configuration to match qos with PLMN. Also we will introduce some duplication (since mapping of PLMNs is already done by FEG configuration). Finally development and testing will take more due to the lack of unit test framework

**Comment by amarpad** [comment]
I have been thinking about this a bit given the other roaming conversations we are having, some of this is related to the access network particularly if we are federating across multiple AGWs. So does the FeG know which AGW the policy is going to? If not I would suggest we do this on the AGW side.

@themarwhal at some point we need to add some intelligence to the orc8r so we are not all passthrough. That is the right place I think ultimately as adding config state to the AGW without the orc8r knowing about it is kinda sub optimal

**Comment by ulaskozat** [comment]
@uri200 so will S8proxy fetch policies from Orc8r in the FEG case? We can add another week for scoping and design. Also add 1 more week to buffer for proper testing.

**Comment by uri200** [comment]
Sorry but I am kind of lost here. When you say `policies` what object are you referring to?  

On inbound roaming we do not deal with policies like when we do at sessiond. Magma acts as just as a sgw.

On Create Session Response we receive Qos. So the only parameters we can modify is MBR (and GBR which I think we do not support)

Per what I understand, this feature just tries to overwrite the QoS sent by the roam operator by a custom one to try to limit the performance on the RAN.

To me the complexity of this feature is to capture properly what parameters are needed on the decision algorithm to overwrite QoS, and how/where to store that mapping. 

Remember we did similar exercise for the federated_mapp we added at MME which determines based on PLMN, what user should be roam and what should be local. On that occasion we included field like APN or imsi range which are not yet implemented.  That mapping is stored on AGW swagger config


Just in case you were curious, this is the typical Create Session Response 

```
s8_proxy         | I0610 22:30:29.106562       1 logcodec.go:46] Sending: *protos.CreateSessionResponsePgw: {
s8_proxy         |      "pdn_type": "IPV4",
s8_proxy         |      "paa": {
s8_proxy         |              "ipv4_address": "192.168.126.7",
s8_proxy         |              "ipv6_address": "",
s8_proxy         |              "ipv6_prefix": 0
s8_proxy         |      },
s8_proxy         |      "apn_restriction": 0,
s8_proxy         |      "c_agw_teid": 1012873733,
s8_proxy         |      "c_pgw_fteid": {
s8_proxy         |              "ipv4_address": "172.16.1.2",
s8_proxy         |              "ipv6_address": "",
s8_proxy         |              "teid": 35
s8_proxy         |      },
s8_proxy         |      "bearer_context": {
s8_proxy         |              "id": 5,
s8_proxy         |              "user_plane_fteid": {
s8_proxy         |                      "ipv4_address": "172.16.20.150",
s8_proxy         |                      "ipv6_address": "",
s8_proxy         |                      "teid": 838860800
s8_proxy         |              },
s8_proxy         |              "qos": {
s8_proxy         |                      "pci": 0,
s8_proxy         |                      "priority_level": 9,
s8_proxy         |                      "preemption_capability": 0,
s8_proxy         |                      "preemption_vulnerability": 0,
s8_proxy         |                      "qci": 9,
s8_proxy         |                      "gbr": {
s8_proxy         |                              "br_ul": "0",
s8_proxy         |                              "br_dl": "0"
s8_proxy         |                      },
s8_proxy         |                      "mbr": {
s8_proxy         |                              "br_ul": "0",
s8_proxy         |                              "br_dl": "0"
s8_proxy         |                      }
s8_proxy         |              },
s8_proxy         |              "charging_id": 0,
s8_proxy         |            
s8_proxy         |      },
s8_proxy         |      "protocol_configuration_options": {
s8_proxy         |              "config_protocol": 0,
s8_proxy         |              "proto_or_container_id": [
s8_proxy         |                      {
s8_proxy         |                              "id": 13,
s8_proxy         |                              "contents": "CAgICA=="
s8_proxy         |                      },
s8_proxy         |                      {
s8_proxy         |                              "id": 12,
s8_proxy         |                              "contents": "CmQDCw=="
s8_proxy         |                      },
s8_proxy         |                      {
s8_proxy         |                              "id": 2,
s8_proxy         |                              "contents": null
s8_proxy         |                      }
s8_proxy         |              ]
s8_proxy         |      },
s8_proxy         |      "gtp_error": null
s8_proxy         | }
```
