### ISSUE TITLE
Multi-Sgi Support for AGW

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#7416]
This feature request is about having multiple (2) uplink interfaces from AGW towards internet.

**Comment by ekowtaylor** [comment]
@sourabh-nanoti kindly provide additional context or info as the ask here is not very clear. It could be interpreted in a couple of ways and we want to be sure the ask is clear.

**Comment by sourabh-nanoti** [comment]
The request was to have two uplink interfaces towards internet from AGW.
