### ISSUE TITLE
[FeGW] AVP 1009 ONLINE from PCRF not being parsed in Magma

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#7420]
### FeGW

- **Version:** 1.4
- **Affected Component:** Federation Gateway, NMS
- **Affected Subcomponent:** Session_proxy services in FeGW
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Feature
Magma needs to be able to parse the AVP code 1009 ONLINE in CCA-I send by PCRF. This is in order to trigger or avoid messages by Gy to OCS.

**Specify the applicable product use-cases**
FWA telecom provider

**Describe the solution you'd like**
Can be able to parse the AVP code 1009 ONLINE send by PCRF in the CCA-I. If this AVP value is ENABLED, can request to OCS to initiate session for the user. Otherwise, if this AVP value is disabled, no need to initiate session to OCS for user. It is highly recommended follow the 3GPP specification. 

**Resources**
Can see here traces and logs where Magma do not parse the AVP 1009. In this case, this AVP value is DISABLED, but still FEG try to initiate session with OCS and this cause an Attach Reject due to this user is not provisioned in the OCS. There is no need of OCS in this scenario. 
Gx TCP port = 5111
Gy TCP port = 5112
[logs_and_traces.zip](https://github.com/magma/magma/files/6620530/logs_and_traces.zip)

**Comment by uri200** [comment]
This is currently not implemented and may collide with some of current features.

In order to try to see how could this be implemented, can you help to interpret the standard per your knowledge?
Per the standard, it mentions if ONLINE is disabled, that means no GY session is stablished, does it mean that any RG group should be discarded by the PECF? Is that the behaviour expected?

![image](https://user-images.githubusercontent.com/16157139/121628142-88a84400-ca2d-11eb-9eaa-2c370a133c3f.png)

**Comment by emersonacuna** [comment]
That depends on the developer or vendor, I dont find any info related in 3GPP specification. But actually for this scenario (customer expectation), it is simpler. 
- PCRF will send ONLINE as DISABLED to users whose rules are configured in Magma to not track with OCS, some of these rules will track for quota with PCRF (this up how the rule is configured). 
- And PCRF will send ONLINE as ENABLED to users whose rules (at least some of them) are configured to track quota with OCS.

**Comment by uri200** [comment]
Right now our system is ONLINE = ENABLE all the time. The way we control this is using RG and Monitor Key. If Any of those are defined on the rule we set it up as Gx or Gy or both.

The way to do this is to configure a rule without RG for the subscribers that doesn't require OCS accounting

**Comment by uri200** [comment]
Also after reading some of the messages [here](https://magmacore.slack.com/archives/G01N7ABCL6M/p1623342408047200?thread_ts=1623277959.039800&cid=G01N7ABCL6M) note we support Gx Monitoring and Gy Credit (they have different behaviour and used for different stuff)

The credits given through Gx are Monitor credits per the standard and those are given to a specific monitoring key. But note monitoring is just that, monitoring. PCEF will just report traffic as long as it has credits is over, the user stops reporting but there is no action being taken. The action to be taken is up to PCRF. 

When using OCS those actions are predefine (for example terminate session, redirect, restrict)

To solve your issue, you can try to remove the charging key and use monitoring key. That will, per the code, disable any messaging to the OCS and only deal with PCRF
[gx_gy_combined_08_200505_211320-1-1.pcapng.zip]

Attached you have an example of Gx only monitoring and reporting
(https://github.com/magma/magma/files/6641615/gx_gy_combined_08_200505_211320-1-1.pcapng.zip)

![image](https://user-images.githubusercontent.com/16157139/121764249-6b3fac80-caf7-11eb-9642-d815fbbd4b42.png)

**Comment by angelahr450** [comment]
Question: Is Charging Key the same as RG?

**Comment by joary** [comment]
@uri200 , bringing more clarity to the discussion, this issue happens to a dynamic policy rule (that comes from PCRF).
This policy can not be easily changed without affecting existing users. 

In more details some users will have the AVP ONLINE = DISABLE to flag that even if the rating_group is specified the Gy charging (credit) should not be reported. @angelahr450 , @emersonacuna will correct me if I'm wrong.

A naive workaround proposal would be to check the AVP ONLINE on CCA's and drop the rating_group of that given policy if ONLINE = DISABLE, not sure if it is feasible though.

**Comment by emersonacuna** [comment]
Hello. Actually this issue is happening to static rules (configured in Magma). In our current test, PCRF sends two rules: one static and one dynamic. Both rules must be follow what ONLINE AVP indicates. 

These rules have configured RG because has been planned like that in the telecom provider. So we cannot remove RG for the configuration of these rules.

**Comment by emersonacuna** [comment]
hello @joary and @uri200 . I made a test with a rule with monitoring key and no RG configured. Still can see that FEG tries to initiate session with OCS, OCS replies with a CCA-I with 5030 RC (user unknown, the IMSI is not provisioned in the OCS)

**Comment by uri200** [comment]
Can you please share pcap? It would be good to have feg log with grpc messages enabled too.

Per our code, the only way for the FEG to send a Gy request is when Gx request has an RG on the rule definition sent by PCRF.

Also that could happen on static rules defined on orc8r. Do you have any local rule set up with an RG? or Omni rule? If so, those rules are injected on the Gx request and may be causing that.

**Comment by emersonacuna** [comment]
@uri200 ooh i see. Yes, actually the PCRF in the CCA-I sends a dynamic rule with RG inside it and our static rule is without RG. But this is a real scenario, even with dynamic rule with RG, the PCRF sends the ONLINE AVP as disabled, so we must not use Gy.

Here the trace i took yesterday. I gonna test again to capture the logs, but i am afraid cannot test with dynamic rule without RG, that implies a change in an external PCRF.

TCP port Gx = 5111
[trace2206_feg_03.zip](https://github.com/magma/magma/files/6702977/trace2206_feg_03.zip)
