### ISSUE TITLE
Magma SA-TeraVM | Authentication Sync Failure

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7437]
Issue:- Authentication Sync Failure
Possible cause:  Seq no mismatch

As discussed in Tshoot calls need to have permanent fix for AMF to add resync flows.

![image.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/be08b073-ffd2-437d-8e61-23fa8813c1a7)

**Comment by arun-magma** [comment]
cc: @ulaskozat

**Comment by ulaskozat** [comment]
closing the issue as this is resolved now.
