### ISSUE TITLE
`mme-clang-warnings` is incredibly flaky

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#7444]
Recently failed jobs:
* https://app.circleci.com/pipelines/github/magma/magma/25432/workflows/709993c5-aab3-44b3-8612-a521d4e7e474/jobs/269713
* https://app.circleci.com/pipelines/github/magma/magma/25436/workflows/c718a45d-f7d7-47c8-88af-f59dcfa4555c/jobs/269816
* https://app.circleci.com/pipelines/github/magma/magma/25351/workflows/12db3e51-f5ec-4b99-b1b5-01f1ff9457fe/jobs/269610
* https://app.circleci.com/pipelines/github/magma/magma/25351/workflows/29e9253c-1277-40a7-b506-14fdf3e55f45/jobs/269588
* https://app.circleci.com/pipelines/github/magma/magma/25351/workflows/97b6f832-befb-4dd4-b48f-ef60f287426a/jobs/269129

They all time out like this:
```
Copied /usr/local/share/asn1c/NativeEnumerated_oer.c	-> /build/c/core/oai/tasks/ngap/r16/NativeEnumerated_oer.c
Copied /usr/local/share/asn1c/constr_CHOICE_oer.c	-> /build/c/core/oai/tasks/ngap/r16/constr_CHOICE_oer.c
Copied /usr/local/share/asn1c/constr_SEQUENCE_oer.c	-> /build/c/core/oai/tasks/ngap/r16/constr_SEQUENCE_oer.c
Copied /usr/local/share/asn1c/constr_SET_OF_oer.c	-> /build/c/core/oai/tasks/ngap/r16/constr_SET_OF_oer.c
Generated /build/c/core/oai/tasks/ngap/r16/Makefile.am.libasncodec
Copied /usr/local/share/asn1c/converter-example.c	-> /build/c/core/oai/tasks/ngap/r16/converter-example.c implicit
Generated pdu_collection.c
Generated /build/c/core/oai/tasks/ngap/r16/converter-example.mk
Copied /usr/local/share/asn1c/converter-example.c	-> /build/c/core/oai/tasks/ngap/r16/converter-example.c implicit
Generated pdu_collection.c
Generated /build/c/core/oai/tasks/ngap/r16/Makefile.am.asn1convert
Generated Ngap_asn_constant.h
s8 Proto_srcs are /build/c/core/oai/tasks/sgw_s8/lte/protos/oai/spgw_state.pb.cc;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/sgw_state.pb.cc;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/common_types.pb.cc;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/std_3gpp_types.pb.cc
s8 Proto_includes are /build/c/core/oai/tasks/sgw_s8/lte/protos/oai/spgw_state.pb.h;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/sgw_state.pb.h;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/common_types.pb.h;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/std_3gpp_types.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /build/c/core/oai


Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by themarwhal** [comment]
I also see `c-cpp-codecov` failing similarly https://app.circleci.com/pipelines/github/magma/magma/25437/workflows/cfcea266-b659-40dd-8c83-dbbf0baf0f02/jobs/269844

```
s8 Proto_srcs are /build/c/core/oai/tasks/sgw_s8/lte/protos/oai/spgw_state.pb.cc;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/sgw_state.pb.cc;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/common_types.pb.cc;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/std_3gpp_types.pb.cc
s8 Proto_includes are /build/c/core/oai/tasks/sgw_s8/lte/protos/oai/spgw_state.pb.h;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/sgw_state.pb.h;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/common_types.pb.h;/build/c/core/oai/tasks/sgw_s8/lte/protos/oai/std_3gpp_types.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /build/c/core/oai
[13/16] Performing build step for 'MagmaCore'

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by electronjoe** [comment]
I personally observed this behavior on my laptop yesterday. My dockerfile build of `make test_oai` deadlocked at stage 13/16.  I would expect this is relate to the CMake revisions that migrated us to `/c/core` but cannot confirm.

I enlarged my Docker memory from 13 gigs to 16 gigs and observed success, but I'm not sure if this was simply a flake and I got lucky?

**Comment by electronjoe** [comment]
I may have been mis-interpreting the CMake output - is this stage `[13/16] Performing build step for 'MagmaCore'` suppressing all build output but internally building the ~1900 build targets?

If so, that could easily take 10 minutes and yield no output - do we need to enable more verbosity of this stage (if possible)? Is that all that's goin on here?

**Comment by electronjoe** [comment]
@amarpad has pointed out that in this stage work is being done by Ninja but no output is occurring from CMake. So this isn't broken but it is perhaps too long without any status outputs. Maybe we can add some sort of status output indicator for the build stage? Ideally.
