### ISSUE TITLE
[MME] No tests are run with `make test_oai` within Docker

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#7457]
## Summary

It appears that - perhaps correlated with the migration of some CMake config for the mme - our docker environment is no longer executing the oai tests (as of [noticed on master commit 7c37bdeaef9ea6a884796aec17ba56440b54fc57](https://github.com/magma/magma/commit/7c37bdeaef9ea6a884796aec17ba56440b54fc57)).

```
root@b41ea3bbf547:/magma/lte/gateway# make test_oai
...
[1993/1994] Linking CXX static library tasks/ha/libTASK_HA.a
[1994/1994] Linking CXX executable oai_mme/mme
[16/16] Completed 'MagmaCore'
cd  /build/c/core && ctest --output-on-failure
Test project /build/c/core
No tests were found!!!
```

This likely means we are not getting any test coverage within the CI Pipeline.

**Comment by electronjoe** [comment]
It appears to me that the tests are being built. Just not discovered and executed by e.g. ctest?

```
root@b41ea3bbf547:/magma/lte/gateway# ls /build/c/core/oai/test/
CMakeFiles  CTestTestfile.cmake  cmake_install.cmake  itti  mme_app_task  mobility_client  openflow  pipelined_client  spgw_task
```

**Comment by amarpad** [comment]
I can take this
