### ISSUE TITLE
[AGW] Get rid of MSISDN label for usage metrics.

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#7459]
Prometheus is pretty sensitive to high cardinality labels(https://www.robustperception.io/cardinality-is-key). 
We have similar labels, IMSI and MSISDN, which both run into 100s and 1000s of possible values. Ideally we should convert the usage metrics to events, if not possible, we should ensure sanity by having only a single high cardinality label. We cannot scale having both MSISDN and IMSI as label values for usage metrics.

**Comment by themarwhal** [comment]
@karthiksubraveti 
this is for both usage and dropped metrics right?
We currently have these 3 counters in sessiond
```
const char* UE_TRAFFIC_COUNTER_NAME = "ue_traffic"; // has imsi, session_id
const char* UE_DROPPED_COUNTER_NAME = "ue_dropped_usage"; // has imsi, apn, msisdn
const char* UE_USED_COUNTER_NAME    = "ue_reported_usage"; // has imsi, apn, msisdn
```

**Comment by karthiksubraveti** [comment]
> @karthiksubraveti 
> 
> this is for both usage and dropped metrics right?
> 
> We currently have these 3 counters in sessiond
> 
> ```
> 
> const char* UE_TRAFFIC_COUNTER_NAME = "ue_traffic"; // has imsi, session_id
> 
> const char* UE_DROPPED_COUNTER_NAME = "ue_dropped_usage"; // has imsi, apn, msisdn
> 
> const char* UE_USED_COUNTER_NAME    = "ue_reported_usage"; // has imsi, apn, msisdn
> 
> ```
> 
> 

Yes. This is for all the above mentioned metrics.
