### ISSUE TITLE
 GUTI based Registration is failing on magma-5G

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#7488]

**Comment by rupa455wavelabs** [comment]
Expected Behaviour: 

If the REGISTRATION ACCEPT message contained a 5G-GUTI, the UE shall return a REGISTRATION
COMPLETE message to the AMF to acknowledge the received 5G-GUTI, stop timer T3519 if running, and delete any
stored SUCI. The UE shall provide the 5G-GUTI to the lower layer of 3GPP access if the REGISTRATION ACCEPT
message is sent over the non-3GPP access, and the UE is in 5GMM-REGISTERED in both 3GPP access and non-3GPP
access in the same PLMN.

Actual Behaviour: 

AMF is sending Authentication failure for GUTI registration type, needs to fix.

Reference : 3GPP TS 24.501 version 15.6.0 Release 15, section - 8.2.7.2 5G-GUTI

**Comment by rupa455wavelabs** [comment]
scenario file: G0UTI_Registration.xml
pcap: GUTI_Registration.pcap

drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt

**Comment by ganeshg87** [comment]
All fixes present in #7565, this was raised on magma-5G branch.
