### ISSUE TITLE
[FeGW] TCP diameter Gx/Gy links failure

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#7496]
### Federated LTE Network 

- **Version:**
- **Affected Component:** Federation gateway
- **Affected Subcomponent:** Federation gateway, NMS
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG

### Describe the Issue
Diameter links Gx/Gy are configured with TCP port to a DRA. Randomly, these links are getting down from time to time. The way we get back the links is with a manual restart of services of dockers. The links does not drop off at the same time, there is no patron of time.

``` 
[36msession_proxy    |[0m E0603 02:46:04.104037       1 diameter_client.go:150] diameter error on 10.68.152.61:5112: read tcp 10.30.26.57:3871->10.68.152.61:5112: use of closed network connection
[36msession_proxy    |[0m E0603 11:52:27.999359       1 diameter_client.go:150] diameter error on 10.68.152.61:5111: read tcp 10.30.26.57:3870->10.68.152.61:5111: use of closed network connection
``` 

The S6a link is configured with SCTP port and never happens this issue.

**Expected behavior**
Links must estable all the time, otherwise will generate alarms in the DRA's side. 

**Additional context**
Attached the logs of session_proxy docker and the traces of Gx and Gy. Consider these info:
Gy (TCP port 5112) down time -> 02/06 21:46
Gx (TCP port 5111) down time -> 03/06 06:52
Each pcap file name ends with the interface name that got down within that capture

[GxGy_down.zip](https://github.com/magma/magma/files/6639810/GxGy_down.zip)

**Comment by emakeev** [comment]
It's not only affecting Gx/Gy TCP, the same logic is also used for s6a/swx & other diameter based protocols TCP or SCTP.
The connection recovers "on demand" & we currently do not track connection health.

**Comment by joary** [comment]
Is there a workaround that could be taken on this issue? 

From a naive perspective the diameter client could raise a signal for service restart when it detects the usage of closed network connection.

**Comment by ekowtaylor** [comment]
@uri200 , @themarwhal any thoughts and further insights about this issue?

**Comment by uri200** [comment]
Hey @ekowtaylor this is not a simple feature. It will require code changes on all our diameter clients and testing to see HA is not impacted (which I am not even sure if it is possible). This should be planned for 1.7 and try to backport it to 1.6 if ready earlier

**Comment by uri200** [comment]
@emersonacuna the issue may be coming from the vm where FEG is running. Per what I can see, this message is triggered when a socket is closed and feg tries to write on it. The reason for closing that socket is not known to the feg because there is nothing on the log that indicates an error.

Can you include the syslog when this issue happens?

Can you also include the version you are using (1.5? 1.5.1?) so I can try to build a custom binary please?

**Comment by uri200** [comment]
@emersonacuna  can you confirm that FEG is running at the ip `10..30.26.57`

**Comment by emersonacuna** [comment]
Hi @uri200 yes. IPs of FeG are these ones: FeG Active 10.30.26.55 / FeG Backup 10.30.26.57. All the info i sent you is for FeG Backup.

BTW, our current version is 1.4, but we are planning to upgrade 1.5.1.

**Comment by uri200** [comment]
@ekowtaylor this issue was closed. Waiting for the update to be installed at @emersonacuna setup to confirm
