### ISSUE TITLE
The APN Correction is not working with empty APN that math the prefix

### ISSUE THREAD

**Issue by jrmejiaa** [magma/magma#7497]
### Your Environment

- **Version:** 1.4
- **Affected Component:** AGW
- **Affected Subcomponent:** APN Correction - service pipelined
- **Deployment Environment:** e.g. AWS (VM Openstack), VM with docker (orc8r)

### Describe the Issue

CPEs are doing PDN Connectivity Request. Both of them should be able to use APN Correction without a problem, according to the documentation from Magma. However, when the second PDN Connectivity has an empty APN, the system would not make the correction of the APN successfully. The system would send strange unknown characters, as it can seen in the log of the `mme.log`. 

```bash
# First PDN Connectivity
INFO  NAS-ES tasks/nas/esm/sap/esm_recv.c    :0154    ESM-SAP   - Received PDN Connectivity Request message (ue_id= 0x00000040, pti=2, ebi=0)
INFO  NAS-ES tasks/nas/esm/sap/esm_recv.c    :0257    ESM-SAP   - APN CORRECTION (apn = bafi.amt.pe)
INFO  MME-AP tasks/mme_app/mme_app_apn_select:0170    Selected APN <bafi.amt.pe>, PDN Type <0> for UE 7167701200333980
# Second PDN Connectivity
INFO  NAS-ES tasks/nas/esm/sap/esm_recv.c    :0154    ESM-SAP   - Received PDN Connectivity Request message (ue_id= 0x00000040, pti=4, ebi=0)
INFO  NAS-ES tasks/nas/esm/sap/esm_recv.c    :0257    ESM-SAP   - APN CORRECTION (apn = �;���U)
ERROR NAS-ES tasks/nas/esm/sap/esm_recv.c    :0314    ESM-PROC  - Cannot select APN for ue id0x00000040
ERROR NAS-ES tasks/nas/esm/sap/esm_sap.c     :0637    ESM-SAP   - Sending PDN connectivity reject for ue_id = (64)
```

**To Reproduce**
1. Adapt your AGW to allow APN Correction according to the documentation [here](https://docs.magmacore.org/docs/lte/deploy_config_apn#apn-override-config-in-mme)
2. `sudo service magma@* stop && sudo service sctpd stop`
3. `sudo service magma@magmad restart`
4. Wait until all services are active again and the connection with the orchr8 is sucessfull `(POST 200)`
5. Use a UE that has the APN empty and test an attach to the AGW.

**Expected behavior**
The APN Correction should also work with empty APN who match with the prefix of the configuration: 

```bash
cat /etc/magma/mme.yml
....
enable_apn_correction: false
apn_correction_map_list:
        - imsi_prefix: "71677" # Match with the PLMN
          apn_override: "magma.ipv4"
```

**Logs:**
[APN_EMPTY.zip](https://github.com/magma/magma/files/6639757/APN_EMPTY.zip)

**Comment by ardzoht** [comment]
Hi @jrmejiaa thanks for filing this and sharing the pcap, can I ask you to share the full `/var/log/mme.log` output as well please?

**Comment by ardzoht** [comment]
Discussing with @ulaskozat, magma AGW does not support multiple sessions pointing to same APN, APN correction does not support this, may I ask what is the intended use case that you are testing? One potential fix you could use would be to add a separate entry with the UE prefix and APN to be overridden on the mapping, if this is not sufficient, we could look into adding this kind of support, but at the moment this feature is not intended to cover for this specific case.

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/
