### ISSUE TITLE
1.5.1 non-nat mode patch_up interface disappears

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#7508]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** Debian > 1.5.1-1622832859-484890af
- **Affected Component:**Access Gateway
- **Affected Subcomponent:** pipelined
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

After a reboot, and periodically during operation, patch-up interface dies causing pipelined to die. This happens after a reboot which causes WAN/SGi connection to not come up. Connection to AGW is lost. 

**To Reproduce**
1. Build AGW in 1.5.1 image above
2. Configure Non-NAT mode (network = DHCP_Broadcast, AGW = NAT disable)
3. Reboot or wait for changes to be applied
4. see connection lost, no IP on eth0 or uplink_br0

Logs attach
[patchup_iface_disappear.tar.gz](https://github.com/magma/magma/files/6641021/patchup_iface_disappear.tar.gz)

@pshelar @sudhikan @wallyrb

**Comment by pshelar** [comment]
Fixed and backported to 1.5
