### ISSUE TITLE
test_attach_mobile_reachability_timer_expiry.py Segfaults

### ISSUE THREAD

**Issue by toddingarfield** [magma/magma#7509]
### Environment
Local development environment as described in Magma Quick Start Guide.
macOS 11.4 x86_64, 2 GHz Quad-Core Intel Core i5, 16GB RAM
Docker Dekstop 3.3.3, Engine 20.10.6 Compose 1.29.1
Vagrant 2.2.16 / VirtualBox Version 6.1.22 r144080

- **Version:** 1.5.1
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** magma-test: python/integtest
- **Deployment Environment:**  local docker-compose (orc8r), Vagrant (AGW)

### Describe the Issue

When running all tests referenced on. S1AP Integration Tests the test_attach_mobile_reachability_timer_expiry.py segfaults.  Other tests prior to it are able to run.  

**To Reproduce**
1. Start 3 VMs documented in S1AP Integration Tests
2. Start orc8r in local cloud
3. Run all tests using vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test

**Expected behavior**
The test to complete

**Test log file**
Running test: s1aptests/test_attach_mobile_reachability_timer_expiry.py
timeout --foreground -k 930s 900s sudo -E PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests --with-xunit --xunit-file=/var/tmp/test_results/test_attach_mobile_reachability_timer_expiry.xml -x -s s1aptests/test_attach_mobile_reachability_timer_expiry.py || exit 1
Start time 20:55:09
tag: AUTH_TYPE tagVal: MILENAGE
************************* Enb tester config

**********************TPT open server******** 0

 Server Socket FD =[13]
************* Testing *Time elapsed(in usec): for timer expiry               :7173 usec
AGW is stateless
APN Correction configured
Health service is disabled
Using subscriber IMSI IMSI001010000000001
Using IMEI 3805468432113171
************************* UE device config for ue_id  1
************************* Configuring IP block
************************* Waiting for IP changes to propagate
************************* S1 setup
************************* UE App config
************************* Running End to End attach for UE id  1
ue id 1 found
PDN_TYPE: 1
IPv4 PDN_ADDRESS:192 168 128 12

*************NbUiNbuHdlUeRadioCapMsg: Send UE cap msg SUCCESS*********
************************* Sending UE context release request  for UE id  1
Deleting Ue Context from Traffic Handler
************************* Waiting for Mobile Reachability Timer to expire. Sleeping for 360 seconds..
*********** Slept for 5 seconds
*********** Slept for 10 seconds
*********** Slept for 15 seconds
*********** Slept for 20 seconds
*********** Slept for 25 seconds
*********** Slept for 30 seconds
*********** Slept for 35 seconds
*********** Slept for 40 seconds
*********** Slept for 45 seconds
*********** Slept for 50 seconds
*********** Slept for 55 seconds
*********** Slept for 60 seconds
*********** Slept for 65 seconds
*********** Slept for 70 seconds
*********** Slept for 75 seconds
*********** Slept for 80 seconds
*********** Slept for 85 seconds
*********** Slept for 90 seconds
*********** Slept for 95 seconds
*********** Slept for 100 seconds
*********** Slept for 105 seconds
*********** Slept for 110 seconds
*********** Slept for 115 seconds
*********** Slept for 120 seconds
*********** Slept for 125 seconds
*********** Slept for 130 seconds
Segmentation fault
Makefile:42: recipe for target 'integ_test' failed

**Additional context**
@VinashakAnkitAman 
From running the test a couple of times, it appears to fail consistently when running the orc8r local cloud.  
I found another person reporting a similar issue in Slack
https://magmacore.slack.com/archives/C01MDUQDFC3/p1622639493008000

**Comment by ulaskozat** [comment]
@toddingarfield , you should not connect orc8r when running s1ap integ tests. It will interfere with the configs the test set up pushes to AGW services.

**Comment by toddingarfield** [comment]
Thanks @ulaskozat, I will close the issue.
