### ISSUE TITLE
Registring AGW to Orchestrator on Ubuntu gives error MME failing with RECOVERY_MESSAGE

### ISSUE THREAD

**Issue by robinge330** [magma/magma#7546]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:1.5
- **Affected Component: Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service 
- **Deployment Environment:** Ubuntu
### Describe the Issue
after registration the AGW to orchestrator MME errors are seen and process does not comeup

root@fbf1-agw:~# checkin_cli.py
1. -- Testing TCP connection to controller.magma330.local:8443 --
2. -- Testing Certificate --
3. -- Testing SSL --
4. -- Creating direct cloud checkin --
5. -- Creating proxy cloud checkin --

Success!

root@fbf1-agw:~# agw_health_cli.py
Access Gateway health summary
Error: Service (mme) missing in mconfig

magma@mme.service - Magma OAI MME service
     Loaded: loaded (/etc/systemd/system/magma@mme.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2021-06-14 23:06:51 UTC; 410ms ago
    Process: 2660809 ExecStartPre=/usr/bin/env python3 /usr/local/bin/generate_oai_config.py (code=exited, status=1/FAILURE)
    Process: 2660821 ExecStopPost=/usr/bin/env python3 /usr/local/bin/service_util.py mme (code=exited, status=1/FAILURE)

less /var/log/mme.log

000283 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0578    - S5-S8:
000284 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0579        S5_S8 iface ..........: none
000285 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0582        S5_S8 ip  (read)......: 0.0.0.0
000286 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0585        S5_S8 MTU (read)......: 0
000287 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0588    - SGi:
000288 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0589        SGi iface ............: gtp_br0
000289 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0592        SGi MTU (read)........: 1500
000290 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0594        NAT ..................: true
000291 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0597        User TCP MSS clamping : true
000292 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0600        User IP masquerading  : false
000293 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0603    - PCEF support ...........: false (in development)
000294 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0651    - DNS Configuration:
000295 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0652        IPv4 Primary Address ..........: 8.8.8.8
000296 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0655        IPv4 Secondary Address ..........: 8.8.4.4
000297 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0658    - Helpers:
000298 Mon Jun 14 19:45:37 2021 7EFDA86A7BC0 INFO  SPGW-A tasks/sgw/pgw_config.c          :0659        Push PCO (DNS+MTU) ........: false
000299 Mon Jun 14 19:45:37 2021 7EFD9F3EF700 INFO  MME-AP tasks/mme_app/mme_app_main.c    :0456    Received RECOVERY_MESSAGE
000300 Mon Jun 14 19:45:37 2021 7EFD9CBEA700 DEBUG SGW_S8 tasks/sgw_s8/sgw_s8_task.c      :0103    Unkwnon message ID 11: RECOVERY_MESSAGE
000301 Mon Jun 14 19:45:37 2021 7EFD9C3E9700 ERROR S1AP   tasks/s1ap/s1ap_mme.c           :0320    Unknown message ID 11:RECOVERY_MESSAGE
000302 Mon Jun 14 20:31:49 2021 7EFD9CBEA700 DEBUG SGW_S8 tasks/sgw_s8/sgw_s8_task.c      :0117    Finished cleaning up SGW_S8 task
000303 Mon Jun 14 20:31:49 2021 7EFD9D3EB700 INFO  GTPv1- lib/openflow/controller/Controll:0080    Stopped openflow controller

root@fbf1-agw:/var/log# sudo journalctl -fu magma@mme
-- Logs begin at Fri 2021-06-04 21:09:52 UTC. --
Jun 14 22:57:31 fbf1-agw mme[2639741]:   File "/usr/local/bin/service_util.py", line 74, in <module>
Jun 14 22:57:31 fbf1-agw mme[2639741]:     update_stats(service_name)
Jun 14 22:57:31 fbf1-agw mme[2639741]:   File "/usr/local/bin/service_util.py", line 63, in update_stats
Jun 14 22:57:31 fbf1-agw mme[2639741]:     status = get_status()
Jun 14 22:57:31 fbf1-agw mme[2639741]:   File "/usr/local/bin/service_util.py", line 41, in get_status
Jun 14 22:57:31 fbf1-agw mme[2639741]:     ServiceExitStatus.ExitCode.Value(exit_code.upper())
Jun 14 22:57:31 fbf1-agw mme[2639741]: AttributeError: 'NoneType' object has no attribute 'upper'
Jun 14 22:57:31 fbf1-agw systemd[1]: magma@mme.service: Control process exited, code=exited, status=1/FAILURE
Jun 14 22:57:31 fbf1-agw systemd[1]: magma@mme.service: Failed with result 'exit-code'.
Jun 14 22:57:31 fbf1-agw systemd[1]: Failed to start Magma OAI MME service.
Jun 14 22:57:36 fbf1-agw systemd[1]: magma@mme.service: Scheduled restart job, restart counter is at 1128.
Jun 14 22:57:36 fbf1-agw systemd[1]: Stopped Magma OAI MME service.
Jun 14 22:57:37 fbf1-agw systemd[1]: Starting Magma OAI MME service...
Jun 14 22:57:37 fbf1-agw mme[2640016]: Traceback (most recent call last):
Jun 14 22:57:37 fbf1-agw mme[2640016]:   File "/usr/local/bin/generate_oai_config.py", line 273, in <module>
Jun 14 22:57:37 fbf1-agw mme[2640016]:     main()
Jun 14 22:57:37 fbf1-agw mme[2640016]:   File "/usr/local/bin/generate_oai_config.py", line 264, in main
Jun 14 22:57:37 fbf1-agw mme[2640016]:     context = _get_context()
Jun 14 22:57:37 fbf1-agw mme[2640016]:   File "/usr/local/bin/generate_oai_config.py", line 207, in _get_context
Jun 14 22:57:37 fbf1-agw mme[2640016]:     mme_service_config = load_service_mconfig("mme", MME())
Jun 14 22:57:37 fbf1-agw mme[2640016]:   File "/usr/local/lib/python3.8/dist-packages/magma/configuration/mconfig_managers.py", line 52, in load_service_mconfig
Jun 14 22:57:37 fbf1-agw mme[2640016]:     return get_mconfig_manager().load_service_mconfig(service, mconfig_struct)
Jun 14 22:57:37 fbf1-agw mme[2640016]:   File "/usr/local/lib/python3.8/dist-packages/magma/configuration/mconfig_managers.py", line 160, in load_service_mconfig
Jun 14 22:57:37 fbf1-agw mme[2640016]:     raise LoadConfigError(
Jun 14 22:57:37 fbf1-agw mme[2640016]: magma.configuration.exceptions.LoadConfigError: Service (mme) missing in mconfig
Jun 14 22:57:37 fbf1-agw systemd[1]: magma@mme.service: Control process exited, code=exited, status=1/FAILURE
Jun 14 22:57:38 fbf1-agw mme[2640023]: Traceback (most recent call last):
Jun 14 22:57:38 fbf1-agw mme[2640023]:   File "/usr/local/bin/service_util.py", line 74, in <module>
Jun 14 22:57:38 fbf1-agw mme[2640023]:     update_stats(service_name)
Jun 14 22:57:38 fbf1-agw mme[2640023]:   File "/usr/local/bin/service_util.py", line 63, in update_stats
Jun 14 22:57:38 fbf1-agw mme[2640023]:     status = get_status()
Jun 14 22:57:38 fbf1-agw mme[2640023]:   File "/usr/local/bin/service_util.py", line 41, in get_status
Jun 14 22:57:38 fbf1-agw mme[2640023]:     ServiceExitStatus.ExitCode.Value(exit_code.upper())
Jun 14 22:57:38 fbf1-agw mme[2640023]: AttributeError: 'NoneType' object has no attribute 'upper'
Jun 14 22:57:38 fbf1-agw systemd[1]: magma@mme.service: Control process exited, code=exited, status=1/FAILURE
Jun 14 22:57:38 fbf1-agw systemd[1]: magma@mme.service: Failed with result 'exit-code'.
Jun 14 22:57:38 fbf1-agw systemd[1]: Failed to start Magma OAI MME service.
Jun 14 22:57:43 fbf1-agw systemd[1]: magma@mme.service: Scheduled restart job, restart counter is at 1129.
Jun 14 22:57:43 fbf1-agw systemd[1]: Stopped Magma OAI MME service.

**To Reproduce**

**Expected behavior**
MME starting successfully

**Screenshots**

**Additional context**
logs in problem

**Comment by ulaskozat** [comment]
@robinge330 rather than github issues, it is better to create github discussion and share the context. The messages `000301 Mon Jun 14 19:45:37 2021 7EFD9C3E9700 ERROR S1AP tasks/s1ap/s1ap_mme.c :0320 Unknown message ID 11:RECOVERY_MESSAGE` are benign, it should not be at ERROR level but INFO level in this case. The reason why mme process is not starting is that gateway.mconfig file seems to be missing mme related configs. Can you paste the contents of `/var/opt/magma/configs/gateway.mconfig`?

**Comment by robinge330** [comment]
OK fine, i will close this and open a discussion item. I have re-install 1.5 and am trying to register the H/W through NMS instead of through the swagger which has this issue . Once done i open a discussion item and share the details.
