### ISSUE TITLE
[Orc8r] Certifier pod crashing due to certificate expiry alert changes

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#7548]
Certifier pod has been crashing due to recent changes. Need to investigate further.
```
ksubraveti@ksubraveti-mbp ~ % kubectl -n orc8r logs orc8r-certifier-7997d7b6d6-frj2f --previous
I0614 12:00:01.470225       1 service_config.go:169] Successfully loaded 'cwf::service_registry' service configs from '/etc/magma/configs/cwf/service_registry.yml'
I0614 12:00:01.470476       1 service_config.go:169] Successfully loaded 'fbinternal::service_registry' service configs from '/etc/magma/configs/fbinternal/service_registry.yml'
I0614 12:00:01.470704       1 service_config.go:169] Successfully loaded 'feg::service_registry' service configs from '/etc/magma/configs/feg/service_registry.yml'
I0614 12:00:01.471496       1 service_config.go:169] Successfully loaded 'lte::service_registry' service configs from '/etc/magma/configs/lte/service_registry.yml'
I0614 12:00:01.472226       1 service_config.go:169] Successfully loaded 'orc8r::service_registry' service configs from '/etc/magma/configs/orc8r/service_registry.yml'
I0614 12:00:01.472530       1 service_config.go:169] Successfully loaded 'wifi::service_registry' service configs from '/etc/magma/configs/wifi/service_registry.yml'
I0614 12:00:01.472986       1 service_config.go:111] Successfully loaded structured 'orc8r::shared' service configs from '/etc/magma/configs/orc8r/shared.yml'
I0614 12:00:01.473203       1 service_config.go:169] Successfully loaded 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0614 12:00:01.536785       1 service_config.go:111] Successfully loaded structured 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0614 12:00:01.537094       1 service_config.go:169] Successfully loaded 'orc8r::metricsd' service configs from '/etc/magma/configs/orc8r/metricsd.yml'
I0614 12:00:01.537551       1 service_config.go:180] Successfully loaded Override configs for service orc8r:metricsd from '/var/opt/magma/configs/orc8r/metricsd.yml'
E0614 18:00:00.001488       1 lifespan.go:53] Could not get lifespan for cert rootCA.pem: open /var/opt/magma/certs/rootCA.pem: no such file or directory
E0614 18:00:00.001517       1 lifespan.go:53] Could not get lifespan for cert admin_operator.pem: open /var/opt/magma/certs/admin_operator.pem: no such file or directory
2021/06/14 18:00:00 failed to decode PEM block containing public key
```

**Comment by hcgatewood** [comment]
@andreilee if relevant: let's not fatal on these sorts of "best effort" worker goroutines, just log an error

Relevant: "Logging" subsection under https://magma.github.io/magma/docs/next/contributing/contribute_conventions#go

**Comment by karthiksubraveti** [comment]
> @andreilee if relevant: let's not fatal on these sorts of "best effort" worker goroutines, just log an error
> 
> Relevant: "Logging" subsection under https://magma.github.io/magma/docs/next/contributing/contribute_conventions#go

@andreilee had added this based on my review comment. The main reason I had recommended adding fatal was to detect such issues. Otherwise we might not understand why for e.g. 
"failed to decode PEM block containing public key" Do we understand why we failed to decode this PEM block ?

**Comment by karthiksubraveti** [comment]
Also, I feel we can still leave it as fatal, Otherwise operator might end up with expired certs with no alert notification and the pod silently erroring.

**Comment by andreilee** [comment]
@hcgatewood @karthiksubraveti

I think the way forward here would be to have alerts that fire on missing metrics - keeps the whole thing running, but isn't silent

**Comment by hcgatewood** [comment]
I guess the question is: did this failure occur on (or near) startup, or did it occur after some time? If the former, I agree let's just fail fast. If the latter, error log is more graceful and gives an opportunity to fix

As far as missing metrics: I think we should at min definitely put out an error log. But I think a metric around "had an issue generating essential metrics" would also make sense. Sort of a "check the logs there's a problem with some of the metrics" type of warning

**Comment by andreilee** [comment]
This should be crashing every 3 hours or so judging by the default cron schedule for these analytics values

**Comment by karthiksubraveti** [comment]
> I guess the question is: did this failure occur on (or near) startup, or did it occur after some time? If the former, I agree let's just fail fast. If the latter, error log is more graceful and gives an opportunity to fix
> 
> As far as missing metrics: I think we should at min definitely put out an error log. But I think a metric around "had an issue generating essential metrics" would also make sense. Sort of a "check the logs there's a problem with some of the metrics" type of warning

I agree on this principle, but it depends on the context. IMO, If an invariant which the service is dependent on is broken even in a trivial usecase, we should assert. In this case, I understand perhaps the code should be more tolerant of admin_operator missing. Should we however be tolerant of missing rootCA.pem ? If rootCA.pem isn't needed by certifier, then I think we can simply error log it. I'm not too sure.
