### ISSUE TITLE
Magma SA-TeraVM | MNC has missing 3rd digit (only 2 digit found) in Registration Accept TAL

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7593]
Issue: - AMF generated "Registration Accept" TAL MNC value (2 digit) which is not matching to MNC (3 digit) received in TAI ( in ULI) Of "initial UE".

Tested AGW Build (CI based):  magma/stretch-5g,now 1.5.0-1623775933-314ce387

Snaps enclosed:

![image.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/5874a6e6-4d4d-4123-bba6-76c9e7623a74)

![image.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/679d788f-aeb4-43b1-851e-9f1317ee3caf)

**Comment by arun-magma** [comment]
cc: @ulaskozat

**Comment by Chandhu-Wavelabs** [comment]
![image.png](https://images.zenhubusercontent.com/60b72e6712fc8111b2ad4a05/8a96e1e3-044e-4384-a92a-7738de10c415)

![image.png](https://images.zenhubusercontent.com/60b72e6712fc8111b2ad4a05/a53d4d57-3b26-4ee5-a13f-e29cb669c6c9)

This issue is fixed in latest master code.
