### ISSUE TITLE
 Magma SA-TeraVM | Integrity Algorithm IA1 Support

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7594]
Feature Request: Integrity Algorithm TA1 Support
Currently AMF selects TA-2 as default requesting to add support for TA1 algorithm selection from AMF side.
cc: @ulaskozat 

Tested AGW Build (CI based): magma/stretch-5g,now 1.5.0-1623775933-314ce387

![image.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/b3eb252c-e08c-4b68-835a-d7491a9e7624)

**Comment by Chandhu-Wavelabs** [comment]
I believe TA1 is typo, TA1 used instead of IA1, if we need to add IA1 support, we already covered this issue in PR #7771, but PR raised against to magma-5g branch, need to shift the PR to master branch.

**Comment by Chandhu-Wavelabs** [comment]
We have covered this issue with algorithm selection logic in PR 8998
