### ISSUE TITLE
Magma needs a security policy / process to deal with security flaws

### ISSUE THREAD

**Issue by PARitter** [magma/magma#7608]
# Magma needs a Security Policy

From time to time Magma will be found to have security related issues where disclosure could put existing Magma deployments at risk.  While the Magma project is firmly committed to maintaining an open and transparent development process, we do require a more private process to handle security issues while fixes are developed to address them.

Currently the only way to report and track issues in Magma is through GitHub Issues.  For certain issues related to serious security flaws the project needs a mechanism to privately report issues and a process that ensures these issues are tracked, addressed at high priority, and ultimately disclosed when fixes are available to be applied.

I propose here the creation of a security policy for the Magma Core Foundation and implementation of the processes required to implement it.

## Best Practices

An informal survey of other Open Source projects, discussion with Linux Foundation Staff & Open Infra Foundation Staff, and review of [The CERT Guide to Coordinated Vulnerability Disclosure](https://resources.sei.cmu.edu/asset_files/SpecialReport/2017_003_001_503340.pdf) suggests that a good security policy have the following properties:

- A confidential reporting mechanism
- A group of project members committed to addressing security issues quickly and confidentially
- Inclusion of the person or entity that reported the issue in the resolution
- High priority (P0) assigned to developing and landing required code changes to close the issue
- A mechanism to track security issues that maintains their confidentiality while a fix is being developed
- Clear and transparent communication of the issue delivered coincidently with the patch to fix it

Examples of Open Source projects found during this survey with excellent security policies include [VS Code](https://github.com/microsoft/vscode/blob/main/SECURITY.md) and [Kata Containers](https://github.com/kata-containers/community/blob/master/VMT/VMT.md).

## Proposal

I propose that the Magma Foundation publish a security policy and creates the processes to implement that policy ASAP.  Github provides a well recognized mechanism to publish security policies through the creation of a SECURITY.md file at the top level.  I will be submitting a draft PR with a proposed security policy for discussion later this week.

The draft policy will be based on the practices found from other projects and advice from LF, OIF and Facebook.  It will strive to satisfy the properties listed above while remaining simple enough for Magma's limited development team to manage successfully.

This policy will require:

- Establishment of a secure e-mail forwarder at `security@magmacore.org`.
- Nomination of and commitment from a small group of Magma's codeowners to serve as a `vulnerability management team`
- Implementation of Github's "security advisory" feature to track issues confidentially and ultimately disclose them when a patch is available

**Comment by syotfs** [comment]
+1

**Comment by fungi** [comment]
After many years of doing vulnerability management for a number of community-maintained free/libre open source projects, I've found one nearly indispensable tool is a defect tracker which allows for reports to be filed and discussed privately, but which can then have those reports and their associated discussion made public at the time the vulnerability is disclosed. This sort of embargoed conversation is supported by quite a few popular defect trackers, and lends maximum transparency for your community into how you're handling and addressing vulnerability reports. While it's not necessary that the tracker you use for suspected security vulnerabilities be the same one you use for normal defect tracking in the project, it's generally better for your users if you have only one, so making a conscious decision early to standardize on a tracker with this feature helps a lot.
