### ISSUE TITLE
Magma SA-TeraVM | SUCI/IMSI based Registration fails when IMSI's MNC is sent as 3 DIGIT

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7619]
Issue:  Registartion fails with no response When using 3 DIGIT MNC in IMSI (SUCI) on Intial UE message.

Snap of Traces: 

![image.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/99aed3c7-c455-42a3-9d50-6f4d7822c320)

More details and full Logs are shared over slack channel (project-5g-teravm-sa-testing)

[https://app.zenhub.com/files/170803235/c5bc6671-1759-49ba-ab8e-3eabe02a9b03/download](https://app.zenhub.com/files/170803235/c5bc6671-1759-49ba-ab8e-3eabe02a9b03/download)

**Comment by arun-magma** [comment]
cc: @ulaskozat

**Comment by ganeshg87** [comment]
resolved the issue and raised PR for review 
https://github.com/magma/magma/pull/7666

**Comment by panyogesh** [comment]
#7676... Fix done by Ulas. Will confirm and close by June-22

**Comment by arun-magma** [comment]
This Issue can be closed as the MNC 3digit on IMSI (SUCI) as identity related registration is good now
