### ISSUE TITLE
Subscriber sessions info is too verbose in NMS GUI and doesn't auto-update when selected

### ISSUE THREAD

**Issue by hiawad** [magma/magma#7629]
### Explanation of the request
when we check "Subscriber Sessions" in NMS it shows there is active sessions for one subscriber while there is no enodeB in "good" status, neither selecting "autofresh" option nor manual reload will update the information.

Component
NMS

Version
v 1.5

- **Affected Component:** NMS
- **Affected Subcomponent:** NMS
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

Subscriber sessions show old information / active state with autorefresh defined.

**Comment by karthiksubraveti** [comment]
Is the associated gateway in healthy state ?

**Comment by wallyrb** [comment]
@karthiksubraveti  yes AGW is in healthy state

1. When users are active, status of "Current Usage", "State", "Active Duration" don't auto-refresh unless manually refresh the page.(even with auto-refresh option active)

2. When users are not longer active(not attached), the state of the user seems to remained with the previous value and doesn't update from there. Even after manually refreshing the page.
![image](https://user-images.githubusercontent.com/37117037/123905184-b1ce3d00-d926-11eb-8858-fcbd67036e1b.png)

**Comment by karthiksubraveti** [comment]
cc @themarwhal

**Comment by bbarritt** [comment]
@wallyrb also mentioned that the columns / information we're presenting is probably too verbose and we should think about what info we really want to display here

**Comment by jingtien** [comment]
Proposal to address UX issues in the subscriber sessions table can be found in the Figma below.  
- Wally and I discussed what info was extraneous and what info (EMM/ECM) was missing from the sessions table
- We validated that the EMM/ECM data is available with Ulas
- Still need to finalize some of the columns we removed and moved into the sub-table with Wally + Mose team, but the proposal is available

[Link to mocks/proposal](https://www.figma.com/file/3NjAxgY4ykdJ1e07OGlcn0/Subscribe-Sessions-Table-Data-Update?node-id=86%3A641)

**Comment by wallyrb** [comment]
Changing this issue to feature request to track EMM/ECM and columns added/removed.

The bug for state state of subscribers to be tracked on https://github.com/magma/magma/issues/8621
