### ISSUE TITLE
[CI] Hadolint is failing as GH Action

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#7634]
## Summary

@rdefosse pointed out that Hadolint is failing in GH Action CI. [example failure](https://github.com/magma/magma/pull/7329/checks?check_run_id=2849441812).

```
 Running hadolint with reviewdog 🐶 ...
  reviewdog: This is Pull-Request from forked repository.
  GitHub token doesn't have write permission of Review API, so reviewdog will
  report results via logging command [1] and create annotations similar to
  github-pr-check reporter as a fallback.
  fatal: ls-files -i must be used with either -o or -c
  [1]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
  parse error: Invalid numeric literal at line 1, column 7
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token 
Error: Process completed with exit code 1.
```

**Comment by electronjoe** [comment]
I filed an issue with the reviewdog hadolint folks to track - in case it's their side / GH Action environment breakge. Possibly a useful breadcrumb for others, depending upon how this resolves.

https://github.com/reviewdog/action-shellcheck/issues/21

**Comment by mgrachev** [comment]
@electronjoe 👋 
The problem was fixed in action-hadolint https://github.com/reviewdog/action-hadolint/issues/54

**Comment by electronjoe** [comment]
Thanks @MGAbdElKhalek ! High five.

**Comment by mgrachev** [comment]
Who is @MGAbdElKhalek? 😃
