### ISSUE TITLE
Magma SA-TeraVM | Consequent SUCI & GUTI Reg switch test fails with sessiond triggered Service restart

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7652]
Issue: - Consequent SUCI & GUTI Reg switch test fails with sessiond triggered Service restart

Pattern of test where this issue is observed:
SUCI Reg -> Reg Accept -> GUTI Reg -> Reg Accept ->PDU Est -> Traffic UL & DL -> PDU REL -> DEREG -> Repeat from start

back trace: 

[New LWP 327]
[New LWP 324]
[New LWP 328]

warning: Unexpected size of section `.reg-xstate/362' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGABRT, Aborted.

warning: Unexpected size of section `.reg-xstate/362' in core file.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f55ec7d7700 (LWP 362))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f55fec7742a in __GI_abort () at abort.c:89
#2  0x00007f55ff58e0ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f55ff58c066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f55ff58c0b1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f55ff58cb8f in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005606808caa7c in ngap_state_exit () at /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_state.cpp:51
#7  0x00005606808bd8e5 in ngap_amf_exit () at /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf.c:237
#8  0x00005606808bda3c in ngap_amf_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/ngap/ngap_amf.c:205
#9  0x00007f56029b84a4 in start_thread (arg=0x7f55ec7d7700) at pthread_create.c:456
#10 0x00007f55fed2bd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb)

Detailed logs enclosed[https://app.zenhub.com/files/170803235/1cfd668b-8a5e-4cd7-95c5-dbc9fc48d1d7/download](https://app.zenhub.com/files/170803235/1cfd668b-8a5e-4cd7-95c5-dbc9fc48d1d7/download)

**Comment by arun-magma** [comment]
cc: @ulaskozat

**Comment by panyogesh** [comment]
Closed with Fix ##7661. Tested on TerraVM setup as well on private binaries.
