### ISSUE TITLE
Magma SA-TeraVM | Repeated SUCI Registration fails

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7653]
Issue: Repeated SUCI Registration fails

Flow:

SUCI Reg -> Reg Accept -> PDU Est -> Traffic UL & DL -> PDU REL -> DEREG -> SUCI Reg -> Fails

Detailed logs and traces are provided over slack channel (project-5g-teravm-sa-testing)

![image.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/a5345182-e252-445e-bf12-6311102c755a)

**Comment by arun-magma** [comment]
cc: @ulaskozat

**Comment by panyogesh** [comment]
Fixed as part of #7661.

**Comment by arun-magma** [comment]
Repeated/Subsequent SUCI Registration is good, Higher no Loop & scale test issues are tracked in separate ticket.
