### ISSUE TITLE
Multi GNB support in NGAP.

### ISSUE THREAD

**Issue by Chandhu-Wavelabs** [magma/magma#7654]
Investigate the multi GNB support code in NGAP and start using the code.

**Comment by shanjanaWL** [comment]
I executed SA_01_02_03_04_Hyper_suci testcase with 100UE and 12 GNB. testcase passed. please find the pcap from below
[https://app.zenhub.com/files/170803235/15f6a0ed-28b9-432d-9400-b0531ded4dfc/download](https://app.zenhub.com/files/170803235/15f6a0ed-28b9-432d-9400-b0531ded4dfc/download)
