### ISSUE TITLE
Add support for TAU (0) - Normal Tracking Area Update

### ISSUE THREAD

**Issue by git-inet** [magma/magma#7658]
@ulaskozat @ekowtaylor 

- **Version v1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal (AGW)
- 
### Describe the Feature
Currently MME supports periodic TAU (3) but TAU (0) could happen when an UE moves into a new tracking area.
We have seen that some UE's request TAU (0) and then it gets rejected.

**Specify the applicable product use-cases**
Mobile UEs moving from one TA to another

**Desired timelines**
ASAP

**Comment by ekowtaylor** [comment]
@ulaskozat to review and provide initial assessment

**Comment by ekowtaylor** [comment]
@git-inet thanks for submitting this feature request. We would like for you to provide any additional info to help us better understand your environment, use-case etc to enable us prioritize this appropriately.

**Comment by ulaskozat** [comment]
@pruthvihebbani can you provide updates on your progress for this issue?

**Comment by sudhikan** [comment]
Hi @ulaskozat @pruthvihebbani 

```
864571 24.785195351  10.22.99.78 → 10.22.7.201  S1AP/NAS-EPS 146 UplinkNASTransport, Tracking area update request
868456 24.898713639  10.22.7.201 → 10.22.99.75  S1AP/NAS-EPS 106 DownlinkNASTransport, Tracking area update accept
874952 25.063601476  10.22.7.201 → 10.22.99.75  S1AP 86 UEContextReleaseCommand [NAS-cause=unspecified]
874957 25.063871192  10.22.99.75 → 10.22.7.201  S1AP 102 UEContextReleaseComplete
877561 25.127123986  10.22.99.75 → 10.22.7.201  S1AP/NAS-EPS 126 InitialUEMessage, Service request
```

taking a shot in the dark ... is this expected?

**Comment by ulaskozat** [comment]
Yes, after periodic TAU, context should be released.

**Comment by ssanadhya** [comment]
Resolved on latest master.
