### ISSUE TITLE
Move config items out of `network_epc_configs`

### ISSUE THREAD

**Issue by waqaraqeel** [magma/magma#7691]
The `network_epc_configs` model has become bloated with all sorts of network-wide configuration items thrown into it. Currently the list looks like this:

<table>
<tr>
	<td><b>Field
	<td><b>Type
	<td><b>For Service
<tr>
	<td>`mcc`
	<td>string
	<td>enodeb,mme
<tr>
	<td>`mnc`
	<td>string
	<td>enodeb,mme
<tr>
	<td>`tac`
	<td>number
	<td>enodeb,mme
<tr>
	<td>`lte_auth_op`
	<td>base64
	<td>subscriberdb
<tr>
	<td>`lte_auth_amf`
	<td>base64
	<td>subscriberdb
<tr>
	<td>`sub_profiles`
	<td>struct
	<td>subscriberdb
<tr>
	<td>`default_rule_id`
	<td>string
	<td>pipelined
<tr>
	<td>`hss_relay_enabled`
	<td>bool
	<td>subscriberdb,mme
<tr>
	<td>`gx_gy_relay_enabled`
	<td>bool
	<td>sessiond
<tr>
	<td>`subscriberdb_sync_interval`
	<td>number
	<td>subscriberdb
<tr>
	<td>`cloud_subscriberdb_enabled`
	<td>bool
	<td>mme
<tr>
	<td>`network_services`
	<td>array
	<td>pipelined
<tr>
	<td>`mobility`
	<td>struct
	<td>mobilityd
<tr>
	<td>`restricted_plmns`
	<td>array
	<td>mme
<tr>
	<td>`service_area_maps`
	<td>array
	<td>mme
<tr>
	<td>`restricted_imeis`
	<td>array
	<td>mme
</table>

It would be nice to clean up `network_epc_configs` and have configs that are used only by one service that is not `mme`, pulled into their own models and endpoints of the pattern `network_{service}_config` at `/lte/{network_id}/cellular/{service}_config`. Specifically:

- [ ] ~~Move `lte_auth_op`, `lte_auth_amf`, `sub_profiles` and `subscriberdb_sync_interval` to `network_subscriberdb_config`.~~
- [ ] ~~Move `default_rule_id` and `network_services` to `network_pipelined_config`.~~
- [ ] ~~Move `gx_gy_relay_enabled` to `network_sessiond_config`.~~
- [ ] ~~Move `mobility` to `network_mobilityd_config`.~~

**Comment by karthiksubraveti** [comment]
cc @ulaskozat @ardzoht

**Comment by ulaskozat** [comment]
I actually would not want to expose these at the services level. Our naming conventions for the services can change or be refactored. It is better to provide more abstract end points that deliver the intent of the configuration properly. For instance one outlier here is "network_services" for pipelined. The network services do not have to be EPC specific (and many are developed for Carrier WiFi use case). I would separate that one out as "datapath_services" (cc @pshelar).

**Comment by waqaraqeel** [comment]
After 1:1 discussion with @ulaskozat, it was decided that service-level separation of EPC configuration items was not a good idea. We want configuration endpoints to reflect abstract administrative domains, independent of Magma architecture-based services and modules. While `network_epc_configs` may seem bloated, it is still at a relatively manageable level. The effort and risk of refactoring may outweigh the benefit at this particular time. If one still wanted to refactor, the following could be done:

- Move `lte_auth_op` and `lte_auth_amf` to `/lte/{network_id}/auth`
- Move `hss_relay_enabled` and `gx_gy_relay_enabled` to `/lte/{network_id}/cellular/federation`
- Move `restricted_plmns`, `service_area_maps`, and `restricted_imeis` to `lte/{network_id}/restrictions`
- Move `network_services` to `/orc8r/{network_id}/datapath_services`

However, there are more pressing API refactoring opportunities outside of `epcConfigs`. For example, as we move towards 5G, it would be a good idea to take configuration items common between 4G and 5G outside of `/lte/` and place them in a new top-level path such as `/core/`. Another example would be that `/lte/{network_id}/cellular` is somewhat redundant since `lte` already indicates that it is `cellular`.

More discussion and consensus needed to move forward with API refactoring.

@karthiksubraveti.
