### ISSUE TITLE
1.5.1 NMS - Policy Rule creation / editing is buggy

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#7702]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** NMS 1.5.1, AGW head of 1.5 branch 6/21 build
- **Affected Component:** NMS
- **Affected Subcomponent:** Policy Rule Creation / Edit
- **Deployment Environment:** AWS (orc8r),  bare-metal (AGW)

### Describe the Issue

When creating or editing a policy, the NMS throws errors and/or shows wrong information:
1. when making a policy rule with a QoS profile, the NMS throws error "Failed to create policy, one or more subscriber or QoS profile do not exist" when it does exist. 
2. when rule is configured as network wide, the NMS toggle doesn't show the right status. 

**Expected behavior**
When a rule is created with a QoS profile it should find the QoS profile
When a rule is omni-present network wide = enable the NMS toggle should show that. 

**Screenshots**
<img width="956" alt="Screen Shot 2021-06-22 at 9 57 14 AM" src="https://user-images.githubusercontent.com/61293007/122961060-46420980-d341-11eb-9dcd-0e317eb4991a.png">

<img width="1166" alt="Screen_Shot_2021-06-22_at_9_59_40_AM" src="https://user-images.githubusercontent.com/61293007/122961091-4d691780-d341-11eb-915d-cead293330ec.png">

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by karthiksubraveti** [comment]
cc @andreilee @HannaFar, can you take a look at this issue. Thanks
