### ISSUE TITLE
Gy Relay not blocked data when quota exhausted and no reply from CCR-U

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#7733]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** v1.5 branch 6/20 package build AGW, 1.5.1. orc8r and FeG
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Sessiond and session_proxy
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

When UE is connected to network, and using Gy connection to OCS to meter/control data usage, when quota is exhausted, and CCR-U is sent to OCS, if OCS does not reply, magma system allosw UE to keep consuming data indefinitely. 

**To Reproduce**
1. Setup Gy relay in federate network
2. configure OCS to have small balance for subscriber (100MB)
3. Attach subscriber to network and allow CCR-I/CCA-I to be exchanged
4. Confirm data access and a couple CCR-U/CCA-U exchanges
5. insert FW rule to block CCA-U from OCS to FeG
6. observer that UE can now indefinitely consume data

**Expected behavior**
When CCR-U is sent for exhausted quota, after some minimal grace period data should be blocked until successful grant of new quota. 

**Additional context**
Logs
sessiond
session_proxy
gy pcap
s1 pcap
[Hughes_gy_new_sub_100MB_balance_no_cca_u_afte_quota_exhausted_data_keeps_flowing.zip](https://github.com/magma/magma/files/6703865/Hughes_gy_new_sub_100MB_balance_no_cca_u_afte_quota_exhausted_data_keeps_flowing.zip)

**Comment by themarwhal** [comment]
We don't have the concept of a grace period implemented currently. We allow user data until we receive a CCA-U. (cc @uri200)

**Comment by uri200** [comment]
That is correct @themarwhal. By design, the only one that can make the decision to stop a session is the PCRF. The PCEF will not terminate a session due to network issues with the core. The idea behind this is not to penalize the subscriber for an issue on operators core.

I was not able to find on 3gpp any clause related to that case. But if there is, please share so we can take a look.

**Comment by jpad-freedomfi** [comment]
interesting. Good points @uri200. Is a grace period a reasonable medium? Not an urgent feature request but a configurable grace period might be good. infinite non-charging seems generous :)

**Comment by uri200** [comment]
We could look into that but the problem that I see is we don't have the concept of block a specific credit/rule. We have some kind of suspended concept but it would stop the whole session until the core sends a RAR. Also, this may require to handle the case where multiple credits are installed and only one gets exhausted.

Earlier we used to have a grace period that would execute the final action (normally terminate) if credits were not replenished in the PCEF. However that was too dependent on the network and the user usage and it was causing trouble (disconnecting sessions too early).

**Comment by jpad-freedomfi** [comment]
gotcha. ok. thanks for the background. I'll close the ticket.
