### ISSUE TITLE
Add "about our team" page to Magma website

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#7754]
### Summary

Create a new, standalone page under the "Community" tab of https://www.magmacore.org/ that showcases the Magma team: TAC, TSC, governing board, outreach committee.

See this ["about our team" page from the Continuous Delivery Foundation](https://cd.foundation/about/governing-board/) as an example + template.

### Deliverables

- MVP: we want to publicize the Magma-TAC relationships
- Main deliverable: TAC, TSC, governing board, and outreach committee sections, following the Continuous Delivery Foundation template
- Stretch goal: dynamically generated list of Magma codeowners and/or contributors, at bottom of the page

### More context

Current TAC names
- Amar Padmanabhan (chair)
- Brian Barritt
- Bruce Davie
- Jennifer Rexford
- Martin Casado

Current TSC names
- Hunter Gatewood (chair)
- Marie Bremner
- Pravin Shelar
- Raphael Defosseux
- Scott Moeller

Additional info to grab per person
- Preferred email address
- Preferred "about me" external site(s), including any social media
- Preferred "about me" 1-2 sentence bio
- Preferred headshot

Communication channels
- TAC prefer communication via email, here’s the mailing list (I think): magma-tac@lists.magmacore.org
- TSC communicate via #governance-tsc-ama Slack channel

**Comment by iamweswilson** [comment]
In an effort to speed development time, would folks be interested in using [a template like this](https://openinfra.dev/about/staff/)? Looks like it has the elements to cover the request, but not the UI is not exactly aligned with the example you provided @hcgatewood

**Comment by hcgatewood** [comment]
Yes the delivered UI is less important, the included example is just for showing concept

The template you link looks reasonable, seems like a good starting spot

**Comment by iamweswilson** [comment]
Here's a [deploy preview](https://test-magma-tomas.netlify.app/committee/tac) to review. Kendall is working on gathering info needed for each member. Once that's put together, we will update these templates with that data and share again.

**Comment by iamweswilson** [comment]
These pages have been completed and merged to production: https://www.magmacore.org/committee/governing-board
