### ISSUE TITLE
[Proposal]  Make `Magma-OAI-Jenkins` precommit CI check a required check

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#7774]
This is a Repository change Proposal for Magma.

Authors: @themarwhal, @rdefosse

## Brief Context & scope

`Magma-OAI-Jenkins` is a precommit CI check that has been running for PRs for close to a year now. 

The test does the following:
1. Build an MME-only image for Ubuntu18 on the FEATURES=mme_oai variant
2. Build also a MME-only image for RHEL8 on the same FEATURES=mme_oai variant
3. Use the generated Ubuntu18 MME to deploy with the rest of OAI CN4G components on Ubuntu18 server and run a DsTester-based test-suite (especially a NSA-5G attach check)
4. Use the generated RHEL8 MME to deploy with the rest of OAI CN4G components on RHEL8 server and deploy also a OAI LTE eNB and an OAI LTE UE modems in RF simulator more to do a sanity check UE attachment 

It is very important to note here that passing magma's lte integration test suite **DOES NOT** guarantee that the OAI jenkins job will pass.

This test provides important insights on the health of MME and other MME related infrastructure, and we tend to revert any commits that end up breaking this test. (See https://github.com/magma/magma/pull/7687 for example, but there have been others in the past)

### Goals
* Prevent any PRs that break this test from being merge into master.

### Non-goals
* This is not related to the other jenkins jobs that run currently. (`Jenkins CWAG Libvirt`, `Jenkins `, `Jenkins LTE`)

## Proposal
* Make an announcement in #dev that this test will now be mandatory. (Note that it will not affect PRs that do not touch MME or protobufs used in MME) See `ci-scripts/check_pr_modified_files_for_oai_pipeline.py` for the exact set of files that will trigger the job.
* Wait 3 days for any objections
* Turn on the required check!

## Considerations before going ahead with this
1. The job must be triggered on all PRs for it to work as a required check. (GitHub will forever wait for the job to run. This may block unrelated PRs if it's not triggered at all)
2. Stability of the job. In the past @rdefosse has been pretty great at notifying breakages of tests in Slack/PRs, but this support will become more important if the check becomes required.
  a. What will happen if @rdefosse is on vacation and the job breaks?
  b. We may need to enhance log artifacts from the job so that it is easier for Magma engineers to identify issues

**Comment by electronjoe** [comment]
Tossing in my two cents, @rdefosse has built up a CI job that has been reliable and low flake rate.  From my experience, I back the proposal here.

**Comment by themarwhal** [comment]
proposal went through
