### ISSUE TITLE
Register AGW to a Federated LTE network failed due to ERROR_PARSING_EXTENSION error of openSSL

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#7832]
### Your Environment

- **Version:** v1.5.1
- **Affected Component:** Orchestrator, Access Gateway, NMS
- **Deployment Environment:** local docker-compose (orc8r), docker-compose (NMS), Vagrant (AGW)

### Describe the Issue

I am trying to register AGW to a federated LTE network. I have followed two methods:

A- Automated way using dev_tools.py script:

ws1@5G-WS1:~/magma/lte/gateway$ **fab -f dev_tools.py register_federated_vm**
Traceback (most recent call last):
  File "/home/ws1/.local/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/ws1/.local/lib/python3.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/ws1/.local/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/ws1/magma/lte/gateway/dev_tools.py", line 84, in register_federated_vm
    _register_agw(FEG_LTE_NETWORK_TYPE)
  File "/home/ws1/magma/lte/gateway/dev_tools.py", line 121, in _register_agw
    dev_utils.cloud_post(f'{network_type}/{network_id}/gateways', gw_payload)
  File "../../orc8r/tools/fab/dev_utils.py", line 291, in cloud_post
    (resp.status_code, resp.text))
**Exception: Received a 404 response: {"message":"Not Found"}**

- Checking the NGINX logs of the Orc8r we find a response with 404 already sent to the python script:   
nginx_1                    | {"nginx.time_local": "27/Jun/2021:18:56:22 +0000","nginx.remote_addr": "172.18.0.1","nginx.request": "POST /magma/v1/feg_lte/feg_lte_test/gateways HTTP/1.1","nginx.request_method": "POST","nginx.request_uri": "/magma/v1/feg_lte/feg_lte_test/gateways","nginx.status": 404,"nginx.body_bytes_sent": 24,"nginx.request_length": 1010,"nginx.request_time": 0.002,"nginx.server_name": "_","nginx.clientcert_port": 9070,"nginx.open_port": 9070,"nginx.client_serial": "FDC656119DE9BEDB8DD255042C85A19B","nginx.client_cn": "admin_operator"}

- Then we tried to add the gateway using the swagger API and it succeeded:   
nginx_1                    | {"nginx.time_local": "27/Jun/2021:19:03:20 +0000","nginx.remote_addr": "172.18.0.7","nginx.request": "POST /magma/v1/tenants HTTP/1.1","nginx.request_method": "POST","nginx.request_uri": "/magma/v1/tenants","nginx.status": 201,"nginx.body_bytes_sent": 0,"nginx.request_length": 249,"nginx.request_time": 0.005,"nginx.server_name": "_","nginx.clientcert_port": 9070,"nginx.open_port": 9070,"nginx.client_serial": "FDC656119DE9BEDB8DD255042C85A19B","nginx.client_cn": "admin_operator"}

- Checking the checkin_cli.py results:
(python) vagrant@magma-dev:~/magma/lte/gateway$ **checkin_cli.py **
/home/vagrant/magma/orc8r/gateway/python/magma/common/cert_utils.py:16: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography import x509
1. -- Testing TCP connection to controller.magma.test:9443 --
2. -- Testing Certificate -- > Error: [Errno 2] No such file or directory: '/var/opt/magma/certs/gateway.crt'

Suggestions:
- Regenerate session certs
    1. Delete gateway.key and gateway.crt in /var/opt/magma/certs
    2. Restart magmad (sudo service magma@magmad restart)
- Ensure gateway has been registered in the cloud, with correct
  hardware ID and key
    1. Run show_gateway_info.py.
    2. Go to cloud swagger
        - E.g. https://127.0.0.1:9443/swagger/v1/ui/
        - Query the list gateways endpoint
    3. POST to add a new gateway, filling JSON with corresponding
       values from step 1.

B- Manual way following all steps according to 
https://magma.github.io/magma/docs/lte/deploy_config_agw 
and https://github.com/magma/magma/blob/v1.5.0/docs/readmes/howtos/troubleshooting/agw_unable_to_checkin.md:

1-	Configuring control proxy info and copied the rootCA.pem file:
vagrant@magma-dev:~/magma/lte/gateway$ **sudo cat /var/opt/magma/configs/control_proxy.yml**
cloud_address: controller.magma.test
cloud_port: 9443
bootstrap_address: bootstrapper-controller.magma.test
bootstrap_port: 9443
fluentd_address: fluentd.magma.test
fluentd_port: 24224

**rootca_cert: /var/opt/magma/tmp/certs/rootCA.pem**

vagrant@magma-dev $ **telnet bootstrapper-controller.magma.test 9443**
Trying 10.0.2.2...
**Connected to bootstrapper-controller.magma.test.**
Escape character is '^]'.
^CConnection closed by foreign host.
vagrant@magma-dev $ **telnet controller.magma.test 9443**
Trying 10.0.2.2...
**Connected to controller.magma.test.**

vagrant@magma-dev $ sudo cat /var/opt/magma/tmp/certs/rootCA.pem
-----BEGIN CERTIFICATE-----
MIIDKjCCAhKgAwIBAgIJAIphOiwff2sDMA0GCSqGSIb3DQEBCwUAMCkxCzAJBgNV
BAYTAlVTMRowGAYDVQQDDBFyb290Y2EubWFnbWEudGVzdDAgFw0yMTA2MjQxMDM4
MTdaGA8zMDIwMTAyNTEwMzgxN1owKTELMAkGA1UEBhMCVVMxGjAYBgNVBAMMEXJv
b3RjYS5tYWdtYS50ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
ykW/Vsw+KxtM2joGliZl9T2JUorGFYST7ddyDNK89GAmENxxCf1+14jXtDvhmA1L
butjigAyutLSPLKhQJ37GN79vKLvOEcAjNh9lswf+bWIVhsNy4/KBgRAVGeSdrns
ukXnZA7/eRWOI31y2I+5QUa/VGfpMMqHBJBgKaA35sCM6vA2FulPs34UhHYFpPGm
FQvfRTgIL8HWj7vqsazFMlmbnkWh288Y1+YNVGwZNzeJY5KZwdQqR+HIadNClhrT
U5dDDDn8IKTQrHhatFwXmWEYLdHdTFdRV3KApwzd3ATibrdvZUCr/Fa/9+mXMJzX
PCynsSd7MriUWKP3ycA2wwIDAQABo1MwUTAdBgNVHQ4EFgQUyWClG76r4n620i7s
zWxC0qNN0TkwHwYDVR0jBBgwFoAUyWClG76r4n620i7szWxC0qNN0TkwDwYDVR0T
AQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAMfh438pZC9FUgGxIC8Z1B1L3
366cFZVxZSmMLntpSQYjy222D/lbmftIfA28O228sjYEked/sfkANvZMfNZZuMDW
DNe1Oxil0RuHTfxkQrgb53LqwFlXY3cCvAXKwsHnkgWRZ0cbPBCOy+EA9ATirTI8
3KEbDxZwfRXAxlsULxDMxG72VlqEhLsxxTrKWW1Tic1LCD6CYhdOPZRe3VaNxD2a
ymQSjsAcdYXkw5D8IRHs+e6KbYZ16vG0eLexwyjzcPrdKaRVpFPPvXtgnVfYMS3Q
JHSbHPQhAbyO0ZH977qAli36/VoEgtJFy1wnaWmgAmwRFHVfMHkh6yFaduaz0Q==
-----END CERTIFICATE-----

2-	Use Checkin_script.py to check what might stop checking process:
(python) vagrant@magma-dev:~/magma/lte/gateway$ checkin_cli.py
/home/vagrant/magma/orc8r/gateway/python/magma/common/cert_utils.py:16: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography import x509
1. -- Testing TCP connection to controller.magma.test:9443 --
2. -- Testing Certificate --
**Error: [Errno 2] No such file or directory: '/var/opt/magma/certs/gateway.crt'**

Suggestions:
- Regenerate session certs
    1. Delete gateway.key and gateway.crt in /var/opt/magma/certs
    2. Restart magmad (sudo service magma@magmad restart)
- Ensure gateway has been registered in the cloud, with correct
  hardware ID and key
    1. Run show_gateway_info.py.
    2. Go to cloud swagger
        - E.g. https://127.0.0.1:9443/swagger/v1/ui/
        - Query the list gateways endpoint
    3. POST to add a new gateway, filling JSON with corresponding
       values from step 1.

Restarting magmad service and monitoring the logs:
Jun 28 15:02:13 magma-dev systemd[1]: Stopped Magma magmad service.
Jun 28 15:02:37 magma-dev systemd[1]: Started Magma magmad service.
Jun 28 15:02:40 magma-dev magmad[457]: /home/vagrant/magma/orc8r/gateway/python/magma/common/cert_utils.py:16: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
Jun 28 15:02:40 magma-dev magmad[457]:   from cryptography import x509
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Starting magmad for UUID: b00ed81d-fbb1-41f5-89da-6a8dbd8cbc9d
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Starting collector...
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Streamer reconnect pause: 60
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Streamer timeout: 150
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Starting magmad...
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Listening on address 127.0.0.1:50052
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Cannot load a proper cert, start bootstrapping
Jun 28 15:02:40 magma-dev magmad[457]: INFO:root:Waiting before checking for updates for the first time...
**Jun 28 15:02:40 magma-dev magmad[457]: E0628 15:02:40.493773582     576 ssl_transport_security.cc:1468] Handshake failed with fatal error SSL_ERROR_SSL: error:10000095:SSL routines:OPENSSL_internal:ERROR_PARSING_EXTENSION.**

**Expected behavior**
It is expected that AGW checkin on Federated LTE network using either ways and no SSL errors occur.

**Comment by MAAHamid** [comment]
To solve this issue:

1- apply the command, get the error:
ws1@5G-WS1:~/magma/lte/gateway$ fab -f dev_tools.py register_federated_vm
Traceback (most recent call last):
  File "/home/ws1/.local/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/ws1/.local/lib/python3.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/ws1/.local/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/ws1/magma/lte/gateway/dev_tools.py", line 84, in register_federated_vm
    _register_agw(FEG_LTE_NETWORK_TYPE)
  File "/home/ws1/magma/lte/gateway/dev_tools.py", line 121, in _register_agw
    dev_utils.cloud_post(f'{network_type}/{network_id}/gateways', gw_payload)
  File "../../orc8r/tools/fab/dev_utils.py", line 291, in cloud_post
    (resp.status_code, resp.text))
**Exception: Received a 404 response: {"message":"Not Found"}**

Disconnecting from vagrant@127.0.0.1:2222... done.

2- Get the hardware ID and challenge key normally from the AGW using (show_gatewa_info.py).
3- Use the above info to add the AGW using the NMS (or the swagger).
4- Restart AGW services.
5- AGW will register normally.

**Comment by ardzoht** [comment]
Hey @MAAHamid, to confirm this issue was mitigated, did you validated the magmad logs? Did the issue do not appear anymore? Also, can you confirm that the `checkin_cli.py` is working as expected after your fix? Thanks!!

**Comment by MAAHamid** [comment]
@ardzoht checkin_cli.py show successful after all steps executed.
magmad logs showed sucessful checkin and sending update to cloud.
