### ISSUE TITLE
IPsec datapath support (design)

### ISSUE THREAD

**Issue by bbarritt** [magma/magma#7860]

**Comment by pshelar** [comment]
I am working on design for IPSec datapath

**Comment by ekowtaylor** [comment]
Will the design be completed by end of week?

**Comment by ekowtaylor** [comment]
@pshelar pending linkage of design doc

**Comment by pshelar** [comment]
https://docs.google.com/document/d/1e_A5KMu0mJKBLps73IHgP5gq5F8ydpw3jKS8FFEGD-U/edit#
