### ISSUE TITLE
TeraVM Regression | FUA Restrict Access rule blocks all traffic flow

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7896]
Title:  FUA Restrict Access rule blocks all traffic flow

Scenario: - 
- UE attach
- Magma sends GX-CCR and CCA with Dynamic and Static rules
- Session gets establish and traffic flow is good, Gy reporting is good based on dynamic rule based traffic flow.
- on Final quota OCS sends the Gy-CCA with Volume Grants and FUA = Restrict_access and Filter-id:  Restrict_Rule (Static Rule config in AGW with allow and deny flows)
- Static Rule: Restrict_Rule gets activated and all the traffic is blocked.

Note:- This is the static rule where  Deny And Allow flows are both configured on it.

**Issue:** restirct_rule has allow flows with UDP ports (17701 & 19701) on it, the flow matching to it should be passing through in SGi but its getting blocked in AGW

[TC-113_bugs.zip](https://github.com/magma/magma/files/6751031/TC-113_bugs.zip)

Enclosed logs:
- Sessiond
- Pipelined
- Session_proxy
- 3gpp pcap traces

Snap of Traffic block:

![image](https://user-images.githubusercontent.com/70725754/124194382-56fb2980-da7d-11eb-8f62-980675f42cd1.png)

Snap of Restirct_rule (flows):

![image](https://user-images.githubusercontent.com/70725754/124194671-db4dac80-da7d-11eb-89fa-04bebb2a11c1.png)

**Comment by koolzz** [comment]
@arun-magma any chance you have the flows for this? I didn't implement FUA = Restrict_access so I don't remember exactly what it installs. What are the steps to reproduce?

**Comment by uri200** [comment]
it looks like `ng40test gxgy13.ntl`


test does:
1- Attach UE, 
2- Gx CCR-Init returns just rule 1, 
3- Verify traffic cannot flow from UE, 
4- Send RAR from PCRF to PCEF with Charging-Rule-Install with modified rule 1, 
5- Verify RAA sent back, 6) Verify traffic can flow from UE,
7- detach and terminate


I can see the ReAuth coming to sessiond with a flow  sessiond sending the deactivate and activate flows
Then i can see pipelined doing a report with all 3 rules.
After that report, all the rules disappear



Jul 01 16:30:41 ubuntuAGW sessiond[2138498]: I0701 16:30:41.345463 2138498 GrpcMagmaUtils.cpp:58]
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:   magma.lte.DeactivateFlowsRequest {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       sid {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         id: "IMSI999991234567810"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       request_origin {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       ip_addr: "172.17.226.198"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       uplink_tunnel: 3
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       downlink_tunnel: 1174405120
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       policies {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         rule_id: "PCC110-QCI9-DYNAMIC"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         version: 2
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:   }```


 01 16:30:41 ubuntuAGW sessiond[2138498]: I0701 16:30:41.345585 2138498 GrpcMagmaUtils.cpp:58]
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:   magma.lte.ActivateFlowsRequest {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       sid {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         id: "IMSI999991234567810"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       ip_addr: "172.17.226.198"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       request_origin {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       apn_ambr {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         max_bandwidth_ul: 100000000
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         max_bandwidth_dl: 100000000
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       msisdn: "1234567810"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       uplink_tunnel: 3
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       downlink_tunnel: 1174405120
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       policies {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         rule {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           id: "PCC110-QCI9-DYNAMIC"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           priority: 1
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           flow_list {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             match {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               udp_src: 17109
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               ip_proto: IPPROTO_UDP
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               ip_src {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:                 address: "172.17.226.198"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           flow_list {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             match {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               udp_dst: 17109
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               ip_proto: IPPROTO_UDP
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               direction: DOWNLINK
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               ip_dst {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:                 address: "172.17.226.198"
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:               }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           qos {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             max_req_bw_ul: 16000
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             max_req_bw_dl: 12200
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:             qci: QCI_9
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           redirect {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:           tracking_type: NO_TRACKING
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:         version: 3
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:   }

```







```


Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:   magma.lte.PolicyReAuthAnswer {
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]:   }
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]: I0701 16:30:41.346316 2138498 SessionProxyResponderHandler.cpp:105] Sent RAA response for Gx ReAuth IMSI999991234567810-23023
Jul 01 16:30:41 ubuntuAGW sessiond[2138498]: I0701 16:30:41.382465 2138506 LocalEnforcer.cpp:1724] Pipelined add ue enf flow succeeded for IMSI999991234567810
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]: I0701 16:30:42.965327 2138546 GrpcMagmaUtils.cpp:58]
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:   magma.lte.RuleRecordTable {
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       records {
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         sid: "IMSI999991234567810"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         rule_id: "PCC110-QCI9-DYNAMIC"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         ue_ipv4: "172.17.226.198"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         rule_version: 1
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       records {
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         sid: "IMSI999991234567810"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         rule_id: "PCC110-QCI9-DYNAMIC"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         ue_ipv4: "172.17.226.198"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         rule_version: 3
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       records {
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         sid: "IMSI999991234567810"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         rule_id: "internal_default_drop_flow_rule"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         ue_ipv4: "172.17.226.198"
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:         dropped_tx: 6000
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:       epoch: 1625181777
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]:   }
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]: I0701 16:30:42.967743 2138498 LocalSessionManagerHandler.cpp:70] Aggregating 3 records
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]: I0701 16:30:42.967797 2138498 SessionState.cpp:493] Reported version higher than tracked one(2) for IMSI999991234567810-23023, rule_id: PCC110-QCI9-DYNAMIC, version: 3
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]: I0701 16:30:42.967819 2138498 LocalEnforcer.cpp:264] Received stats for 1 active sessions and 0 stale sessions
Jul 01 16:30:42 ubuntuAGW sessiond[2138498]: I0701 16:30:42.968384 2138498 LocalSessionManagerHandler.cpp:96] Succeeded in updating session after no reporting
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]: I0701 16:30:44.964928 2138546 GrpcMagmaUtils.cpp:58]
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:   magma.lte.RuleRecordTable {
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:       records {
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:         sid: "IMSI999991234567810"
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:         rule_id: "internal_default_drop_flow_rule"
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:         ue_ipv4: "172.17.226.198"
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:         dropped_tx: 8000
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:       epoch: 1625181777
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]:   }
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]: I0701 16:30:44.965396 2138498 LocalSessionManagerHandler.cpp:70] Aggregating 1 records
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]: I0701 16:30:44.965433 2138498 LocalEnforcer.cpp:264] Received stats for 1 active sessions and 0 stale sessions
Jul 01 16:30:44 ubuntuAGW sessiond[2138498]: I0701 16:30:44.967895 2138498 LocalSessionManagerHandler.cpp:96] Succeeded in updating session after no reporting
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]: I0701 16:30:46.966238 2138546 GrpcMagmaUtils.cpp:58]
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:   magma.lte.RuleRecordTable {
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:       records {
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:         sid: "IMSI999991234567810"
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:         rule_id: "internal_default_drop_flow_rule"
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:         ue_ipv4: "172.17.226.198"
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:         dropped_tx: 10000
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:       }
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:       epoch: 1625181777
Jul 01 16:30:46 ubuntuAGW sessiond[2138498]:   }

```

**Comment by arun-magma** [comment]
@koolzz : Here is the table-0 flow, let me know if any other logs needed from ovs
Sorry not sure why it strike out while i paste the logs here

```
magma@ubuntuAGW:~$ sudo ovs-ofctl dump-flows gtp_br0 | grep "table=0"
 cookie=0x0, duration=3284.823s, table=0, n_packets=6, n_bytes=420, idle_age=1326, priority=10,in_port=15578 actions=resubmit(,201)
 cookie=0x0, duration=18.831s, table=0, n_packets=13, n_bytes=13000, idle_age=1, priority=10,tun_id=0x7,in_port=3 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x7->NXM_NX_REG9[],load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=18.831s, table=0, n_packets=4, n_bytes=4056, idle_age=14, priority=10,ip,in_port=LOCAL,nw_dst=192.168.127.18 actions=load:0x2090000->NXM_NX_TUN_ID[],load:0xac100365->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x7->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=18.831s, table=0, n_packets=0, n_bytes=0, idle_age=18, priority=10,ip,in_port=15577,nw_dst=192.168.127.18 actions=load:0x2090000->NXM_NX_TUN_ID[],load:0xac100365->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x7->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=18.831s, table=0, n_packets=1, n_bytes=42, idle_age=17, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.127.18 actions=load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=18.831s, table=0, n_packets=0, n_bytes=0, idle_age=18, priority=10,arp,in_port=15577,arp_tpa=192.168.127.18 actions=load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
 cookie=0x0, duration=3284.823s, table=0, n_packets=11565, n_bytes=1018518, idle_age=15, priority=0 actions=resubmit(,1)
magma@ubuntuAGW:~$

```

**Comment by koolzz** [comment]
> @koolzz : Here is the table-0 flow, let me know if any other logs needed from ovs
> Sorry not sure why it strike out while i paste the logs here
> 
> ```
> magma@ubuntuAGW:~$ sudo ovs-ofctl dump-flows gtp_br0 | grep "table=0"
>  cookie=0x0, duration=3284.823s, table=0, n_packets=6, n_bytes=420, idle_age=1326, priority=10,in_port=15578 actions=resubmit(,201)
>  cookie=0x0, duration=18.831s, table=0, n_packets=13, n_bytes=13000, idle_age=1, priority=10,tun_id=0x7,in_port=3 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x7->NXM_NX_REG9[],load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
>  cookie=0x0, duration=18.831s, table=0, n_packets=4, n_bytes=4056, idle_age=14, priority=10,ip,in_port=LOCAL,nw_dst=192.168.127.18 actions=load:0x2090000->NXM_NX_TUN_ID[],load:0xac100365->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x7->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
>  cookie=0x0, duration=18.831s, table=0, n_packets=0, n_bytes=0, idle_age=18, priority=10,ip,in_port=15577,nw_dst=192.168.127.18 actions=load:0x2090000->NXM_NX_TUN_ID[],load:0xac100365->NXM_NX_TUN_IPV4_DST[],load:0x3->NXM_NX_REG8[],load:0x7->NXM_NX_REG9[],mod_dl_dst:ff:ff:ff:ff:ff:ff,load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
>  cookie=0x0, duration=18.831s, table=0, n_packets=1, n_bytes=42, idle_age=17, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.127.18 actions=load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
>  cookie=0x0, duration=18.831s, table=0, n_packets=0, n_bytes=0, idle_age=18, priority=10,arp,in_port=15577,arp_tpa=192.168.127.18 actions=load:0x1c6be4d284f411->OXM_OF_METADATA[],resubmit(,1)
>  cookie=0x0, duration=3284.823s, table=0, n_packets=11565, n_bytes=1018518, idle_age=15, priority=0 actions=resubmit(,1)
> magma@ubuntuAGW:~$
> ```

table0 are not sufficient sorry just dump the whole table

**Comment by uri200** [comment]
EDIT: removed this message. It looks like this issue happens on test gxgy113 not on gxgy13.

For the issue at gxgy13 i created this

#7902



Will do the analysis of 113 in this current issue

**Comment by uri200** [comment]
what is this spurieous retransmission

When i run the test i see it almost in all the traffic

![image](https://user-images.githubusercontent.com/16157139/124219112-7d868800-dab0-11eb-952b-dde8dbfb01be.png)

**Comment by uri200** [comment]
The problem is that right after receiving the last CCA-U which includes the restrict traffic, the traffic profile changes (check the ports on the pictures)

Since by then the credit is still not over (check second picture showing allowed 5500 and use 5000), restrict rule is never triggered.

So the solution is to keep sending the initial traffic (port 19141) to make sure the quota is flushed out and RESTRICT rule is applied. Then send the new traffic flow (port 17601)




![image](https://user-images.githubusercontent.com/16157139/124219651-7744db80-dab1-11eb-8148-952dd00067d7.png)



![image](https://user-images.githubusercontent.com/16157139/124219945-ddc9f980-dab1-11eb-93ad-c39784a16163.png)

**Comment by arun-magma** [comment]
[logs_ovs_sessiond_piped.zip](https://github.com/magma/magma/files/6752242/logs_ovs_sessiond_piped.zip)
@koolzz @uri200 : Enclosed OVS zip file has OVS gtp_br0 all table dump
