### ISSUE TITLE
TeraVM Regression | Attach Reject - Cause: Congestion

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7958]
Title:  Attach Reject - Cause: Congestion

Scenario:  32 UE attach for 3 loops

Issue: Some of the attaches are getting rejected with "congestion" as a cause

Script file name:  authentication_information_02

![image](https://user-images.githubusercontent.com/70725754/125004797-254f0900-e00f-11eb-8280-787a7d4be562.png)

cc: @vaishaliCI 

Enclosed Pcaps
[authentication_information_02_210708_135133-1.zip](https://github.com/magma/magma/files/6787861/authentication_information_02_210708_135133-1.zip)

**Comment by ulaskozat** [comment]
@arun-magma you can disable congestion control via the orc8r (set `congestion_control_enabled` to false) or do not attempt to send 32 attach requests at the same time in the script (are you allowed to pace them?).

**Comment by arun-magma** [comment]
Let's test & check by adding this congestion control flag in orc8r and go with 5 UE's Attach/sec.

**Comment by arun-magma** [comment]
After we modified the rate to 5 Attaches/sec the congestion errors were not found

**Comment by arun-magma** [comment]
[32-UE attach - Success.pcapng.zip](https://github.com/magma/magma/files/7050256/32-UE.attach.-.Success.pcapng.zip)

32 of 32 UEs have Successful Attach after changing rate to 5 attach/sec
<img width="1591" alt="Screen Shot 2021-08-25 at 2 54 56 PM" src="https://user-images.githubusercontent.com/70725754/130869818-908e2129-a968-4805-89e3-ef1fc90807f8.png">

**Comment by arun-magma** [comment]
Closing this issue based on above Test results
