### ISSUE TITLE
[AGW] Kernel Panic in new AGW Ubuntu

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#7978]
### Your Environment

- **Version:** v1.6
- **Version .deb packages:** `magma` and `magma-sctpd` in 1.7.0-1625779552-d6169104_amd64
- **Affected Component:**  Access Gateway Ubuntu
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** local docker-compose (orc8r), AGW Ubuntu in OpenStack, Federated LTE Network, FeGW and Federation Network

### Describe the Issue

We are getting the error message attached regarding memory for sessiond process, and this is happening when we start to generate a lot of traffic through AGW from the UE. We are currently using ubuntu 20.04 and AGW was installed using packages `magma` and `magma-sctpd` in 1.7.0-1625779552-d6169104_amd64

[dmesg_log.log](https://github.com/magma/magma/files/6793759/dmesg_log.log)

The VM is getting down and we can see in the consola an error related to `kernel panic`. 

```
WARNING: kernel relocated [298MB]: patching 115190 gdb minimal_symbol values
      KERNEL: /usr/lib/debug/boot/vmlinux-5.4.0-77-generic
    DUMPFILE: 202107091544/dump.202107091544  [PARTIAL DUMP]
        CPUS: 12
        DATE: Fri Jul  9 15:44:17 2021
      UPTIME: 05:31:48
LOAD AVERAGE: 0.37, 0.45, 0.61
       TASKS: 492
    NODENAME: agw-magma-active
     RELEASE: 5.4.0-77-generic
     VERSION: #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
     MACHINE: x86_64  (2299 Mhz)
      MEMORY: 16 GB
       PANIC: "kernel BUG at net/core/skbuff.c:2961!"
         PID: 0
     COMMAND: "swapper/11"
        TASK: ffff9d85adefdd00  (1 of 12)  [THREAD_INFO: ffff9d85adefdd00]
         CPU: 11
       STATE: TASK_RUNNING (PANIC)
crash> bt
PID: 0      TASK: ffff9d85adefdd00  CPU: 11  COMMAND: "swapper/11"
 #0 [ffffb93680310720] machine_kexec at ffffffff93a6b7b3
 #1 [ffffb93680310780] __crash_kexec at ffffffff93b49472
 #2 [ffffb93680310850] crash_kexec at ffffffff93b4a1f9
 #3 [ffffb93680310868] oops_end at ffffffff93a34499
 #4 [ffffb93680310890] die at ffffffff93a346c3
 #5 [ffffb936803108c0] do_trap at ffffffff93a30aa5
 #6 [ffffb93680310910] do_error_trap at ffffffff93a30ebc
 #7 [ffffb93680310958] do_invalid_op at ffffffff93a3135c
 #8 [ffffb93680310980] invalid_op at ffffffff94600d1e
    [exception RIP: skb_zerocopy+890]
    RIP: ffffffff942cf22a  RSP: ffffb93680310a38  RFLAGS: 00010246
    RAX: ffff9d83e3ba00d0  RBX: 0000000000000000  RCX: 0000000000000000
    RDX: 0000000000000010  RSI: ffff9d83cc04a700  RDI: ffff9d84aa81a900
    RBP: ffffb93680310a60   R8: 00000000000005fc   R9: ffff9d83e3ba00d4
    R10: 0000000000000000  R11: 0000000000000022  R12: ffff9d84aa81a900
    R13: ffff9d83cc04a700  R14: 00000000ffffff97  R15: 0000000000000010
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #9 [ffffb93680310a68] queue_userspace_packet at ffffffffc095172f [openvswitch]
#10 [ffffb93680310ad0] ovs_dp_upcall at ffffffffc095463d [openvswitch]
#11 [ffffb93680310ae8] ovs_dp_process_packet at ffffffffc0954785 [openvswitch]
#12 [ffffb93680310b60] ovs_vport_receive at ffffffffc0960517 [openvswitch]
#13 [ffffb93680310d58] netdev_port_receive at ffffffffc0960fb7 [openvswitch]
#14 [ffffb93680310d88] netdev_frame_hook at ffffffffc09610ab [openvswitch]
#15 [ffffb93680310d98] __netif_receive_skb_core at ffffffff942e5f64
#16 [ffffb93680310e40] __netif_receive_skb_one_core at ffffffff942e697f
#17 [ffffb93680310e70] __netif_receive_skb at ffffffff942e6a18
#18 [ffffb93680310e90] process_backlog at ffffffff942e6c69
#19 [ffffb93680310ec8] net_rx_action at ffffffff942e8682
#20 [ffffb93680310f40] __softirqentry_text_start at ffffffff948000e1
#21 [ffffb93680310fb8] irq_exit at ffffffff93a9fd8e
#22 [ffffb93680310fc8] do_IRQ at ffffffff94601e7a
--- <IRQ stack> ---
#23 [ffffb936800cbdc8] ret_from_intr at ffffffff94600a0f
    [exception RIP: native_safe_halt+14]
    RIP: ffffffff944df13e  RSP: ffffb936800cbe70  RFLAGS: 00000246
    RAX: ffffffff944ded50  RBX: 000000000000000b  RCX: 0000000000000001
    RDX: 0000000006356d66  RSI: ffffb936800cbe30  RDI: 0000479ba91e309f
    RBP: ffffb936800cbe90   R8: 0000000000000001   R9: 0000000000000001
    R10: 0000000000100000  R11: 0000000000000000  R12: 000000000000000b
    R13: ffff9d85adefdd00  R14: 0000000000000000  R15: 0000000000000000
    ORIG_RAX: ffffffffffffffdb  CS: 0010  SS: 0018
#24 [ffffb936800cbe70] default_idle at ffffffff944ded70
#25 [ffffb936800cbe98] arch_cpu_idle at ffffffff93a3bbd5
#26 [ffffb936800cbea8] default_idle_call at ffffffff944df2e3
#27 [ffffb936800cbeb8] do_idle at ffffffff93ad6e9b
#28 [ffffb936800cbf10] cpu_startup_entry at ffffffff93ad70a0
#29 [ffffb936800cbf28] start_secondary at ffffffff93a60997
#30 [ffffb936800cbf50] secondary_startup_64 at ffffffff93a000d4
crash>
``` 

**Expected behavior**
It is expected that we can performance tests of high throughtput in Magma without get any crash in the AGW or any other component.

**Comment by ekowtaylor** [comment]
cc. @sudhikan , @pshelar , @talkhasib

**Comment by sudhikan** [comment]
Is this v1.6 or v1.7?

**Comment by caprivm** [comment]
Hi @sudhikan, it is taken from the `master` branch. So, the commit that we take is d6169104 as suggest @uri200 to deploy the AGW using `.deb` files and without the memory problems caused by the `sessiond` service. The command that we use for this is:

```python
fab test package:vcs=git && fab copy_packages
```

**Comment by shanku9** [comment]
@caprivm  Can you try installing stable magma 1.6 release using this guide 
https://docs.magmacore.org/docs/lte/deploy_install#2-deploy-magma-on-the--agw_host

**Comment by caprivm** [comment]
Hi @shanku9 thanks for your response. We already tried it before using the script you mention. We did it in branch v1.6. In fact, it was in that release that the **Kernel Panic** problem arose. I do not know if now, in that same branch, an important change has been made on the performance of the AGW in Ubuntu?

**Comment by uri200** [comment]
@shanku9 , @caprivm , note the idea of building from master is to test some features that didn't make it to 1.6.

Once 1.7 is out the recommendation is to use the official release.

**Comment by caprivm** [comment]
Hi @uri200 thanks for the suggestion! However, we will continue to present the same problem while version 1.7 is available, so, while this is happening, what can we do to solve the error we reported in this issue?

**Comment by uri200** [comment]
@caprivm i will check with @pshelar  to see if this is the same issue they found this past week.

But could you share the log where this error was seen and the core dump it generated so we can have more context?

Was that error seen on sessiond logs? 

Can you also check memory consumption by sessiond while running this test (top or htop will be enough)

**Comment by caprivm** [comment]
@uri200 at the moment the information I have is what @emersonacuna put above to describe the issue. I do not know if it is useful for you to review. The logs and memory consumption you ask me for the `sessiond` would be generated on monday while we carry traffic through the AGW!

**Comment by angelahr450** [comment]
@uri200 after installing v1.6 and enabling the same amount of memory swap, we are not seeing the memory sessiond process error, however the VM keeps restarting every time it has traffic. These are the dump logs and it looks related to OVS:

```
WARNING: kernel relocated [606MB]: patching 115190 gdb minimal_symbol values

      KERNEL: /usr/lib/debug/boot/vmlinux-5.4.0-77-generic
    DUMPFILE: dump.202107110208  [PARTIAL DUMP]
        CPUS: 12
        DATE: Sun Jul 11 02:08:24 2021
      UPTIME: 06:24:37
LOAD AVERAGE: 0.57, 0.46, 0.45
       TASKS: 495
    NODENAME: agw-magma-active
     RELEASE: 5.4.0-77-generic
     VERSION: #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
     MACHINE: x86_64  (2299 Mhz)
      MEMORY: 16 GB
       PANIC: "kernel BUG at net/core/skbuff.c:2961!"
         PID: 0
     COMMAND: "swapper/2"
        TASK: ffff8c1aedea2e80  (1 of 12)  [THREAD_INFO: ffff8c1aedea2e80]
         CPU: 2
       STATE: TASK_RUNNING (PANIC)

crash> bt
PID: 0      TASK: ffff8c1aedea2e80  CPU: 2   COMMAND: "swapper/2"
 #0 [ffffa44d4013c720] machine_kexec at ffffffffa6e6b7b3
 #1 [ffffa44d4013c780] __crash_kexec at ffffffffa6f49472
 #2 [ffffa44d4013c850] crash_kexec at ffffffffa6f4a1f9
 #3 [ffffa44d4013c868] oops_end at ffffffffa6e34499
 #4 [ffffa44d4013c890] die at ffffffffa6e346c3
 #5 [ffffa44d4013c8c0] do_trap at ffffffffa6e30aa5
 #6 [ffffa44d4013c910] do_error_trap at ffffffffa6e30ebc
 #7 [ffffa44d4013c958] do_invalid_op at ffffffffa6e3135c
 #8 [ffffa44d4013c980] invalid_op at ffffffffa7a00d1e
    [exception RIP: skb_zerocopy+890]
    RIP: ffffffffa76cf22a  RSP: ffffa44d4013ca38  RFLAGS: 00010246
    RAX: ffff8c19ff7dc8d0  RBX: 0000000000000000  RCX: 0000000000000000
    RDX: 0000000000000010  RSI: ffff8c1ae76fd700  RDI: ffff8c1ae76fc100
    RBP: ffffa44d4013ca60   R8: 00000000000005fc   R9: ffff8c19ff7dc8d4
    R10: 0000000000000000  R11: 0000000000000022  R12: ffff8c1ae76fc100
    R13: ffff8c1ae76fd700  R14: 00000000ffffff97  R15: 0000000000000010
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #9 [ffffa44d4013ca68] queue_userspace_packet at ffffffffc06fe72f [openvswitch]
#10 [ffffa44d4013cad0] ovs_dp_upcall at ffffffffc070163d [openvswitch]
#11 [ffffa44d4013cae8] ovs_dp_process_packet at ffffffffc0701785 [openvswitch]
#12 [ffffa44d4013cb60] ovs_vport_receive at ffffffffc070d517 [openvswitch]
#13 [ffffa44d4013cd58] netdev_port_receive at ffffffffc070dfb7 [openvswitch]
#14 [ffffa44d4013cd88] netdev_frame_hook at ffffffffc070e0ab [openvswitch]
#15 [ffffa44d4013cd98] __netif_receive_skb_core at ffffffffa76e5f64
#16 [ffffa44d4013ce40] __netif_receive_skb_one_core at ffffffffa76e697f
#17 [ffffa44d4013ce70] __netif_receive_skb at ffffffffa76e6a18
#18 [ffffa44d4013ce90] process_backlog at ffffffffa76e6c69
#19 [ffffa44d4013cec8] net_rx_action at ffffffffa76e8682
#20 [ffffa44d4013cf40] __softirqentry_text_start at ffffffffa7c000e1
#21 [ffffa44d4013cfb8] irq_exit at ffffffffa6e9fd8e
#22 [ffffa44d4013cfc8] do_IRQ at ffffffffa7a01e7a
--- <IRQ stack> ---
#23 [ffffa44d40083dc8] ret_from_intr at ffffffffa7a00a0f
    [exception RIP: native_safe_halt+14]
    RIP: ffffffffa78df13e  RSP: ffffa44d40083e70  RFLAGS: 00000246
    RAX: ffffffffa78ded50  RBX: 0000000000000002  RCX: 0000000000000001
    RDX: 0000000006e12252  RSI: ffffa44d40083e30  RDI: 00005323730a6aa4
    RBP: ffffa44d40083e90   R8: 0000000000000001   R9: 0000000000000001
    R10: 0000000000100000  R11: 0000000000000000  R12: 0000000000000002
    R13: ffff8c1aedea2e80  R14: 0000000000000000  R15: 0000000000000000
    ORIG_RAX: ffffffffffffffd9  CS: 0010  SS: 0018
#24 [ffffa44d40083e70] default_idle at ffffffffa78ded70
#25 [ffffa44d40083e98] arch_cpu_idle at ffffffffa6e3bbd5
#26 [ffffa44d40083ea8] default_idle_call at ffffffffa78df2e3
#27 [ffffa44d40083eb8] do_idle at ffffffffa6ed6e9b
#28 [ffffa44d40083f10] cpu_startup_entry at ffffffffa6ed70a0
#29 [ffffa44d40083f28] start_secondary at ffffffffa6e60997
#30 [ffffa44d40083f50] secondary_startup_64 at ffffffffa6e000d4
```

```
crash> swap
SWAP_INFO_STRUCT    TYPE       SIZE       USED     PCT  PRI  FILENAME
ffff8c1aeace0800  PARTITION  16777212k     0k       0%   -2  /dev/vdb
```

PS during crash:
[ps_crash.txt](https://github.com/magma/magma/files/6800048/ps_crash.txt)

**Comment by uri200** [comment]
Hey @angelahr450 I think going from 1.7 to 1.6 may cause issues on OVS install. If you are moving backwards I would recommend a fresh install.

I would also recommend if you are using master (1.7) directly to build from the top of master. I think last week there were some fixes on datapath/OVS that may have fixed the crash you described first

@pshelar  can you please comment on that?

**Comment by pshelar** [comment]
yes, Ankur is trying to reproduce it in lab for debugging it faster.

**Comment by caprivm** [comment]
Hi @uri200 so to summarize, we are going to generate the `.deb` packages in the top master (1.7) and, in a fresh VM (with Ubuntu 20.04), we are going to install the AGW. Or do you suggest we do it with the `agw_install` script? what is the procedure you suggest?

**Comment by emersonacuna** [comment]
consider this OVS version
```
magma@agw-magma-active:~$ apt policy openvswitch-switch
openvswitch-switch:
  Installed: 2.14.3-3
  Candidate: 2.14.3-3
  Version table:
 *** 2.14.3-3 500
        500 https://artifactory.magmacore.org/artifactory/debian focal-1.5.1/main amd64 Packages
        100 /var/lib/dpkg/status
     2.13.3-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     2.13.1-0ubuntu0.20.04.4 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.13.0-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Comment by uri200** [comment]
Thanks for clarifying @caprivm  

Since this is related with datapath, I will let @pshelar comment on possible workarounds (if any), and on the status of the fix.

**Comment by pshelar** [comment]
@caprivm you should have '2.14.3-7' OVS installed. can you also show apt sources list:
`cat /etc/apt/sources.list.d/magma.list`

**Comment by uri200** [comment]
hey @pshelar  note they built their own .deb file out of master 1.7 

I think this was installed through `dpkg -i magma...deb`. Shouldn't that process take care of the OVS install

**Comment by emersonacuna** [comment]
hi @uri200 @pshelar, this issue is happening every time we start generate traffic from UE. It does not matter the throughput (we are using a Iperf server sometimes and we set different bandwidth, we tested until 4Mbps), almost always we are getting this kernel panic issue and the AGW restarts. Now we are just using 1 UE and 1 enodeB in a Federated LTE network (external HSS/PCRF/OCS).

**Comment by pshelar** [comment]
nope, OVS binaries are installed from the artifactory, since OVS does not change much.

**Comment by uri200** [comment]
> hi @uri200 @pshelar, this issue is happening every time we start generate traffic from UE. It does not matter the throughput (we are using a Iperf server sometimes and we set different bandwidth, we tested until 4Mbps), almost always we are getting this kernel panic issue and the AGW restarts. Now we are just using 1 UE and 1 enodeB in a Federated LTE network (external HSS/PCRF/OCS). 

Per what @pshelar  mentioned you should have 2.14.3-7 ovs installed. That can be the reason why you are getting kernel panics no matter what you send.

Per my understanding magma...deb package should contain the right version of ovs, but I may be wrong.

@caprivm can you provide the content of that apt source @pshelar mentioned please? (Maybe you don't even have that file)

**Comment by caprivm** [comment]
Hi @uri200 and @pshelar , this is the content of that file:
```
magma@agw-magma-active:~$ cat /etc/apt/sources.list.d/magma.list
deb https://artifactory.magmacore.org/artifactory/debian focal-1.5.1 main
```
So, as @emersonacuna mentioned before, if we run `apt policy openvswitch-switch` this is the output:
```
magma@agw-magma-active:~$ apt policy openvswitch-switch
openvswitch-switch:
  Installed: 2.14.3-3
  Candidate: 2.14.3-3
  Version table:
 *** 2.14.3-3 500
        500 https://artifactory.magmacore.org/artifactory/debian focal-1.5.1/main amd64 Packages
        100 /var/lib/dpkg/status
     2.13.3-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     2.13.1-0ubuntu0.20.04.4 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.13.0-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```
Is this OK?

**Comment by pshelar** [comment]
can you add 'deb https://artifactory.magmacore.org/artifactory/debian-prod focal-1.6.0 main' to the apt source file.
then run `ovs-kmod-upgrade.sh` to update OVS.

**Comment by caprivm** [comment]
Hi all, these are the steps to solve the issue. 

First we generate the `.deb` packages to update the AGW installation. The AGW installed before was in the `1.5.1` tag, while the `.deb` packages are in the `master` branch, specifically in the commit https://github.com/magma/magma/commit/d6169104d8436b8ca8ceaf32d7c2033fb687ed04. The packages were generated using the command:
```bash
fab test package:vcs=git && fab copy_packages
```

This procedure is suggested in this link: https://docs.magmacore.org/docs/lte/build_install_magma_pkg_in_agw unsing `test` instead `dev`. Then, we install the packages using:
```bash
sudo apt list --installed | grep magma
sudo apt-get remove --purge magma magma-sctpd  # <--- Remove the old versions of magma
sudo apt -f install $PATH_TO_PACKAGES/magma-sctpd_1.7.0-1625779552-d6169104_amd64.deb
sudo apt -f install $PATH_TO_PACKAGES/magma_1.7.0-1625779552-d6169104_amd64.deb
sudo apt list --installed | grep magma  # <--- Verify the new installed packages

# Output example:
# magma-cpp-redis/now 4.3.1.1-2 amd64 [installed,local]
# magma-libfluid/now 0.1.0.6-1 amd64 [installed,local]
# magma-libtacopie/now 3.2.0.1-1 amd64 [installed,local]
# magma-sctpd/now 1.7.0-1625779552-d6169104 amd64 [installed,upgradable to: 1.7.0-1626245089-37221e68]
# magma/now 1.7.0-1625779552-d6169104 amd64 [installed,upgradable to: 1.7.0-1626245089-37221e68]
```

We configure the `magmad.yml`, `mme.yml`, `pipelind.yml` and `spgw.yml` files based on need. In addition, we configure the network interfaces for the S1 and SGi networking. We ensured the function of the MME by validating that the content of the `/etc/magma/mme.yml` file had a content similar to that of: 

https://raw.githubusercontent.com/magma/magma/61fdbf1596f48517b300678e2bcaba8e0e2b72ec/lte/gateway/configs/mme.yml

You also need to have OVS version 2.14.3-9. If you have an old version of OVS you can upgrade by adding the following row to the file `/etc/apt/sources.list.d/magma.list`:
```bash
deb https://artifactory.magmacore.org/artifactory/debian-test focal-ci main
```

Next, upgrade the OVS version using:
```bash
sudo apt update
ovs-kmod-upgrade.sh
```
To validate the upgrade use:
```bash
apt policy openvswitch-datapath-dkms
# Output example:
# openvswitch-datapath-dkms:
#   Installed: 2.14.3-9
#   Candidate: 2.14.3-9
#   Version table:
#  *** 2.14.3-9 500
#         500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
#         100 /var/lib/dpkg/status
#      2.14.3-8 500
#         500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
#      2.14.3-7 500
#         500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
dmesg | grep vSwitch
# Output example:
# [15386.401576] openvswitch: Open vSwitch switching datapath 2.14.3: p1
```

The last thing that runs is:
```bash
sudo service magma@* stop
sudo service sctpd stop   # <--- Restart the S1 link
sudo service magma@magmad restart
```

And that is!

**Comment by uri200** [comment]
Thanks @caprivm for the detailed description!
