### ISSUE TITLE
[AGW] Explore Bazel build

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#8038]

**Comment by electronjoe** [comment]
Related

https://github.com/magma/magma/issues/4114
and
https://github.com/magma/magma/issues/8049

**Comment by electronjoe** [comment]
I created ZenHub epic for tracking sub-tasks: https://github.com/magma/magma/issues/8081

**Comment by tmdzk** [comment]
Leaving that one here just to log it in the DevOps Roadmap cc @electronjoe

**Comment by electronjoe** [comment]
Sounds good!
