### ISSUE TITLE
Show a version number on NMS or orc8r GUI 

### ISSUE THREAD

**Issue by pkapatsos-blinq** [magma/magma#8048]
Environment (If applicable) any magma orc8r/NMS version but views attached are from R1.6 and R.1.51 builds.

### Describe the Feature
Would like or need a version number showing on orc8r /NMS gui indicating what is running release version please. 
A view of dashboard no idea what version is running after we build other that we used a git tag. If there is even a command to run would be very helpful for us.
![image](https://user-images.githubusercontent.com/61711855/125801399-b3155141-4fde-4816-b9f8-5abfa3a54e01.png)

**Is your feature request related to a known issue? Please describe.**
When issues arise when building a new orc8  or upgrading we don't know which version is running once completed other than by a new item on the GUI if not were added we aren't sure .

**Additional context**
Can you see which version is which from the 2 screen shots attached ? 
![image](https://user-images.githubusercontent.com/61711855/125802253-3b9e23cb-a0ce-4750-8206-abe7067cc5da.png)
![image](https://user-images.githubusercontent.com/61711855/125802286-4def9829-95d8-4b58-b30f-45107d9205be.png)

**Desired timelines**
Next release please

**Comment by lpavao** [comment]
Impact: anytime they want to upgrade, downgrade or verify release they dont have a way to do this. Blinq requesting this - OEM partner. They upgrade every few releases. 
- AGW health status is higher pri than this

**Comment by ekowtaylor** [comment]
@andreilee story points required for this issue
