### ISSUE TITLE
Subscriber provisioning add feature for data plans GUI rather than using JSON manually to configure

### ISSUE THREAD

**Issue by pkapatsos-blinq** [magma/magma#8050]
### Your Environment orc8r/NMS GUI add on for data plans.

- **Version:** any 
- **Affected Component:** Orchestrator, NMS , subscriber tab

### Describe the Feature
Allow for configuration drop down of data plans via GUI
![image](https://user-images.githubusercontent.com/61711855/125805052-2f4a0c28-ac68-4676-83bb-f6d77725070a.png)

**Specify the applicable product use-cases**
Use case for FWA adding data plans on subscribers to push UE-MBR settings to eNBs. Can be done via JSON setup but when you have to add numerous plans can lead to misconfigurations or mistakes.

**Describe the solution you'd like**
Ability to have options to add to the drop down for data plans under subscribers.
![image](https://user-images.githubusercontent.com/61711855/125809199-8607457d-e003-4237-8f0d-4150880d7ca7.png)

**Desired timelines**
ASAP or next release.

**Comment by wallyrb** [comment]
Hey @pkapatsos-blinq thanks for sharing this, could you clarify why the current drop down you shared in the picture doesn't work?
Is the feature about adding an option to add data plan to multiple subscribers?

**Comment by pkapatsos-blinq** [comment]
@wallyrb Here is view when you create data plans via JSON showing under a subsciber as drop downs so not sure but how we build this via a NMS Gui .
![image](https://user-images.githubusercontent.com/61711855/125843819-c6210e8a-1da5-42f5-9746-70c844f3a59d.png)

Here is a view of the JSON  under network for a sub profile that make the drop down above appear 
![image](https://user-images.githubusercontent.com/61711855/125844309-67de6f89-5dfb-4d40-8196-98c42fd3a256.png)

**Comment by ekowtaylor** [comment]
@andreilee let's chat about story points

**Comment by aswin-alexander** [comment]
@sudhikan please share scripts
