### ISSUE TITLE
Not able to build  Orchestrator/Datastore

### ISSUE THREAD

**Issue by rbk1001** [magma/magma#809]
### Your Environment

- **Version:**
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:**Vagrant (AGW)

### Describe the Issue

Hi, I am new in Magma, I am trying to follow the installation guide "Magma_Deployment_Guide_Installing_Magma_V2.pdf" to build the env (vagrant on virtual box), but it is failed to build using "vagrant up cloud datastore", 

# vagrant up cloud datastore
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.

I found that there is no Vagrantfile file come with the source, what is the correct way to build it? for FeG and Gateway there is no such issue.

**Comment by xjtian** [comment]
We probably need to delete that PDF - if you're building a local development environment, follow https://facebookincubator.github.io/magma/docs/basics/quick_start_guide instead.

You can follow the deployment guides if you are deploying Orchestrator/magma.

**Comment by rbk1001** [comment]
have followed the quick start guide, however, the NMS UI is not functioned. kerep having 502 response. check on docker process on magmalte, it is running. any idea how to check further?

CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS                                                          NAMES
303d0dc86f74        nginx                                                 "nginx -g 'daemon of…"   34 minutes ago      Up 34 minutes               80/tcp, 0.0.0.0:443->443/tcp                                   magmalte_nginx-proxy_1
daf38063e459        magmalte_magmalte                                     "docker-entrypoint.s…"   34 minutes ago      Up 34 minutes (unhealthy)   0.0.0.0:8081->8081/tcp                                         magmalte_magmalte_1
b3b2044d41c6        mysql:5                                               "docker-entrypoint.s…"   34 minutes ago      Up 34 minutes (healthy)     3306/tcp, 33060/tcp                                            magmalte_mysql_1

**Comment by xjtian** [comment]
Open a new issue for the NMS 502's please. Include logs from the NMS container and the proxy and controller containers from the orc8r docker-compose.
