### ISSUE TITLE
Auto upgrade script for gateways fails by default

### ISSUE THREAD

**Issue by reddydodda** [magma/magma#812]
### Your Environment

- **Version: **V1.0.0
- **Affected Component:** Orchestrator, FeG Gateway
- **Affected Subcomponent:** Orchestrator proxy and FeG upgrade
- **Deployment Environment:** K8S (orc8r), Virtlet ( FeG )

### Describe the Issue

Add new upgrade tier and wait for orc8r to run upgrade task. 

** Expected:**

FeG gateway will be upgraded to the commit id mentioned in upgrade tier. 

** Actual: **
Upgrade failed as the squid proxy running on the orc8r-proxy container is using the wrong port number. default squid proxy is exposed to 3128 but 443 is used in upgrade script.

** Logs **
INFO:root:Checking for upgrade...
magmad           | INFO:root:There is work to be done:
magmad           |   current: v1.0.0-rc1
magmad           |   to_upgrade: 33a94e98
magmad           | Updating certificates in /etc/ssl/certs...
magmad           | 0 added, 0 removed; done.
magmad           | Running hooks in /etc/ca-certificates/update.d...
magmad           | done.
magmad           | Cloning into 'magma'...
magmad           | fatal: unable to access 'https://github.com/facebookincubator/magma.git/': Received HTTP code 502 from proxy after CONNECT
magmad           | ERROR:root:Upgrade loop failed! Error: Command failed: git -c http.proxy=https://bootstrapper-control-proxy.magma.svc.cluster.local:443 -C /tmp/magma_upgrade clone https://github.com/facebookincubator/magma.git
magmad           | ERROR:root:GetServiceInfo Error for s6a_proxy! [StatusCode.DEADLINE_EXCEEDED] Deadline Exceeded

**Note: **

by setting `allow_http_proxy: false` in control_proxy.yml has no effect of upgrade task.

**Comment by mpgermano** [comment]
The issue here isn't that the ports are wrong. The nghttpx reverse proxy forwards from 443 to 3128. The issue is likely the the Orchestrator proxy needs to have the following in it's helm values: `http_proxy_github_hostname: github.com`.

**Comment by reddydodda** [comment]
fixed with https://github.com/facebookincubator/magma/pull/833
