### ISSUE TITLE
Failed to connect AGW to Orc8r

### ISSUE THREAD

**Issue by zferfer** [magma/magma#8128]
Hi guys,

This is my first magma deployment, as I got ahead of an LTE project recently, so I'm having some issues in connecting the AGW with the Orc8r. Currently I am running a separate VM for the AGW with Ubuntu 20.04, after following the procedures to install the component I get the following message into magma@magmad service:

> jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service subscriberdb (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service mobilityd (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service mme (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service magmad (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service enodebd (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service pipelined (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service state (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:37 magma-agw magmad[6165]: ERROR:root:Metrics upload error for service sessiond (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:50 magma-agw magmad[6165]: ERROR:root:Checkin Error! Failed to report states. [StatusCode.UNAVAILABLE] Received http2 header with status: 502
jul 16 11:58:50 magma-agw magmad[6165]: INFO:root:StateReporting (Checkin) failure threshold met, remediating...
jul 16 11:58:51 magma-agw magmad[6165]: ERROR:root:Error making SSL connection: No such file or directory, [Errno 2] No such file or directory
jul 16 11:58:51 magma-agw magmad[6165]: ERROR:root:Bootstrapping due to invalid cert
jul 16 11:58:53 magma-agw magmad[6165]: ERROR:root:GetChallenge error! [StatusCode.UNAVAILABLE] failed to connect to all addresses
jul 16 11:58:53 magma-agw magmad[6165]: INFO:root:Retrying bootstrap in 30 seconds

I've checked Orc8r and it seems fine, also the gateway UUID and ChallengeKey are correctly set too.

Any help would be appreciated.

**Comment by wallyrb** [comment]
Hey @zferfer could you run the checkin_cli.py and verify the output?

Other suggested steps below to troubleshoot this further:

https://magma.github.io/magma/docs/howtos/troubleshooting/agw_unable_to_checkin

**Comment by zferfer** [comment]
Hi there, here's the output:

> root@magma-agw:/home/magma# checkin_cli.py
>1. -- Testing TCP connection to controller.lte.vocetelecom.vc:443 --
>2. -- Testing Certificate --
> Error: [Errno 2] No such file or directory: '/var/opt/magma/certs/gateway.crt'



I don't know where to create this cert. Also, didn't find any information about it in the docs.

**Comment by ardzoht** [comment]
Hey @zferfer, looks like there is something failing during the boostrap process, which is impeding your AGW to get a valid certificate from it. What I would suggest you to do would be:

1. If you can paste the output of the /var/opt/magma/configs/control_proxy.yml to check its configuration values 
2. Check the boostrapper logs on your Orc8r deployment and look for any errors related to the bootstrapping process (GetChallenge error would be something to look for)

Once we validate that then I can help you to debug the actual issue on the AGW, thanks!

**Comment by zferfer** [comment]
Hello @ardzoht, here is the control_proxy.yml output.
1.
![image](https://user-images.githubusercontent.com/87534532/126390758-ee18286a-9be1-4dd0-884a-defad9302d86.png)


As for 2. I was checking and didn't find out where it would be (guess it does need a pod with that name, right?)

![image](https://user-images.githubusercontent.com/87534532/126390444-f0988523-44bb-456b-9dfd-9bbc76dd90fb.png)



Will I have to reinstall or _terraforming_ should work?

I appreciate the patience :)

**Comment by MAAHamid** [comment]
@zferfer 
Faced same issue before with local deployment (orc8r built on docker), please refer to below issue with the steps I followed to solve it:
https://github.com/magma/magma/issues/7832

My case, apparently, there is something wrong in the fab automated script that register the agw to orc8r.

**Comment by ardzoht** [comment]
@MAAHamid thanks for your valuable input, it looks like the `fab register_vm` or `fab register_federated_vm` might be causing an issue while automating the connection between the VM and orc8r. @zferfer just to validate this, what were the steps you followed to register the VM? did you manually register the VM using Orc8r or did you use the `fab` command?

**Comment by ardzoht** [comment]
> Hello @ardzoht, here is the control_proxy.yml output.
> 1.
> ![image](https://user-images.githubusercontent.com/87534532/126390758-ee18286a-9be1-4dd0-884a-defad9302d86.png)
> 
> As for 2. I was checking and didn't find out where it would be (guess it does need a pod with that name, right?)
> 
> ![image](https://user-images.githubusercontent.com/87534532/126390444-f0988523-44bb-456b-9dfd-9bbc76dd90fb.png)
> 
> Will I have to reinstall or _terraforming_ should work?
> 
> I appreciate the patience :)

From the control_proxy output everything seems fine, the boostrapper logs should be part of the `controller` instance. Although I'm mostly interested on what did you use to register the VM, looks like @MAAHamid issue originated by using the `fab` automation commands, did you follow the same procedure as well? 

And thanks to you for your patience!

**Comment by zferfer** [comment]
Hello, it was manually registered using Orc8r. Also, my Orc8r is running on AWS.

**Comment by ardzoht** [comment]
@zferfer I would try the steps (starting from point 4) described on https://docs.magmacore.org/docs/howtos/troubleshooting/agw_unable_to_checkin#access-gateway-unable-to-check-in-to-orchestrator, to check the connection between AGW and Orchestrator
