### ISSUE TITLE
[CI] Vagrant up for magma dev VM fails on magma-5G branch 

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#8139]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** Magma 5G branch
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Development VM
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

lte-agw-deploy stage is failing due to failure in bringing up Magma VM on Circle CI (https://app.circleci.com/pipelines/github/magma/magma/28777/workflows/9c63e801-9ffb-4144-8d62-18a2ea525ba9/jobs/321816). Similar issue is reported for local dev environment.
```
[magma@10.240.0.45] out: TASK [pkgrepo : Add apt-transport-https] ***************************************
[magma@10.240.0.45] out: Thursday 15 July 2021  11:41:20 -0700 (0:00:00.494)       0:00:17.074 ********* 
[magma@10.240.0.45] out: fatal: [magma]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://dl.bintray.com/tetrate/getenvoy-deb stretch Release' does no longer have a Release file."}
[magma@10.240.0.45] out: 
[magma@10.240.0.45] out: PLAY RECAP *********************************************************************
[magma@10.240.0.45] out: magma                      : ok=6    changed=2    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
```

**To Reproduce**
Vagrant up on Magma-5G branch. 

**Expected behavior**
Vagrant up succeeds.

**Comment by ekowtaylor** [comment]
@ulaskozat, @tmdzk  to add story points

**Comment by ekowtaylor** [comment]
New VM image: https://app.vagrantup.com/magmacore/boxes/magma_dev/versions/1.1.20210716

**Comment by MAAHamid** [comment]
Same issue:
https://github.com/magma/magma/issues/7910

**Comment by ekowtaylor** [comment]
cc. @tmdzk

**Comment by ekowtaylor** [comment]
@tmdzk , @ulaskozat has this been resolved or its still pending?

**Comment by ulaskozat** [comment]
I am closing this as 5g branch will be deprecated soon.
