### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### ISSUE THREAD

**Issue by ezechinwa** [magma/magma#814]
vagrant up magma 

returns this error 

> An error occurred while downloading the remote file. The error
> message, if any, is reproduced below. Please fix this error and try
> again.
> 
> OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

![Screenshot 2019-11-05 at 4 28 26 PM](https://user-images.githubusercontent.com/17327631/68221202-5d57aa80-ffe9-11e9-9556-73cbe75edf24.png)

**Comment by xjtian** [comment]
Unable to repro, but take a look at some remediation options here: https://laracasts.com/discuss/channels/general-discussion/vagrant-openssl-ssl-read-ssl-error-syscall-errno-54

**Comment by ezechinwa** [comment]
Thanks xjtain, It was actually due to my internet connection.
