### ISSUE TITLE
Aggregate PR comment on check failure

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#8165]
Find a way to not have one comment per check failure. But instead have a comment that get updated with the list of failure

**Comment by quentinDERORY** [comment]
delete the comment when it finally succeds too.

**Comment by ranj8work** [comment]
The changes are made in the master branch of my forked repo and tested. The test PR is [here](https://github.com/ranj8work/magma/pull/4). The github workflow action logs dated 28-SEP-2021 are [here](https://github.com/ranj8work/magma/actions/workflows/comment-pr-on-check-failure.yml).
I will be raising the PR officially soon and share the link here too.

**Comment by ranj8work** [comment]
@quentinDERORY and @tmdzk - The [PR](https://github.com/magma/magma/pull/9322) that fixes this issue is raised and ready for your review. Please let me know if you have any questions.
