### ISSUE TITLE
Proposal for enodebd <-> Domain proxy communication for CBRS radios

### ISSUE THREAD

**Issue by amarpad** [magma/magma#8196]
Want to start a design discussion on integrating enodebd with a domain proxy. The main difference between existing enodeb provisioning to a SAS enabled one is that we don't have the full desired state of the enodeb at connect.

**Comment by xbend** [comment]
@amarpad

1. What will the integration of DP with orc8r look like? Separate service, part of other process, etc?

2. Given that DP will be part of orc8r, will DP API gateway need to be blended in somehow into orc8rs nginx or can DP have its own Gateway/proxy?

3. SAS can revoke grant at any time for a variety of reasons.
CBRS device is required to stop transmission within 60sec of such event.
DP has no way of assuring this behavior, for instance:
- eNB "Tx enabled": false, make not be effective immediately on the device
- AGW may loose internet connectivity and will never receive the DP state back to configure "Tx enabled": false
- etc...
We can configure the enodebd polling time (to, for example 10sec) but that still does not ensure that eNB will stop transmitting.
What should we do in such scenarios?

4. What should be the source of truth for DP regarding radios? On one hand, DP can simply get data from each AGW enodebd.
But it could also get this data from orc8r.
Example scenario:
Somebody removes an eNB from AGW via orc8r web ui. Should this event be notified to DP from the orc8r? or should it come from AGW enodebd. 

5. Also related. If eNB is deleted from magma, DP should stop sending heartbeats to SAS and deregister the device. How will the DP know that the eNB has been deleted? Should it get this information from enodebd or orc8r?

6. How does enodebd know that the eNB stopped radiating? What does "stop radiating" mean precisely?

7. You wrote "The knowledge of these radios being CBRS certified is obtained out of band. i.e. for practical purposes the onboarding of these radios are going to be similar to what we have today". Please elaborate on the current process and on how we will be able to determine whether a radio is a CBRS or not

8. Regarding API changes, do you mean the orc8r API?

9. "Swagger will introduce a new vendor name for CBRS certified radios".
What is a "new vendor name"? There is already BaiCells model support implemented. Do you mean "new radio type"?

10. What exactly is mconfig? From what we've seen in the code it seems to be something based off of mconfigs.proto, populated by the data from gateway.mconfig, but we may be totally wrong.

11. On an Inform request from eNB, do we always need to check in Redis if it's a new installation or a radio that was rebooted?

12. Why is the enodebd restart needed after configuration changes? I understand this is something we eventually want to optimize so first we need to know why exactly it needs restarting. To reload the config on the enodeb? Does the reboot not affect other eNBs connected to it?

13. "enodebd will remove the sas redis state associated with the radio and restart"
Is this something that needs implementing or is it already in place?

**Comment by amarpad** [comment]
> @amarpad
> 
> 1. What will the integration of DP with orc8r look like? Separate service, part of other process, etc?

It will be a separate microservice with a GPRC endpoint. control_proxy will need to be updated to register the service
> 2. Given that DP will be part of orc8r, will DP API gateway need to be blended in somehow into orc8rs nginx or can DP have its own Gateway/proxy?

@hcgatewood to chime in here as well. We should reuse the same orc8r nginx. The out of the box product for Magma orchestrator should include the Domain Proxy.
> 3. SAS can revoke grant at any time for a variety of reasons.
>    CBRS device is required to stop transmission within 60sec of such event.
>    DP has no way of assuring this behavior, for instance:

The poll interval for the enodebd will be ~30 seconds say. If the enodebd can't checkin to the orc8r for a period of time, then we should follow the same behavior as a CBSD when heartbeats fail to the SAS, when the CBSD is talking directly to SAS.
> 
> * eNB "Tx enabled": false, make not be effective immediately on the device
Why? Today if the ACS sets admin state to false it triggers an implicit reboot on the enodeb. Maybe I am not following this.
> * AGW may loose internet connectivity and will never receive the DP state back to configure "Tx enabled": false
> * etc...

There are two things here:
1 - If the enodebd cannot talk to the orchestrator we should implement the same behavior as the standards specify for heartbeats to the SAS failing and should itself turn off the radio.
2 - For jittery connections since the poll will retry, you will eventually receive the right state for the enodeb.

>   We can configure the enodebd polling time (to, for example 10sec) but that still does not ensure that eNB will stop transmitting.
>   What should we do in such scenarios?
> 

See above answer for heartbeats.
> 1. What should be the source of truth for DP regarding radios? On one hand, DP can simply get data from each AGW enodebd.
>    But it could also get this data from orc8r.
>    Example scenario:
>    Somebody removes an eNB from AGW via orc8r web ui. Should this event be notified to DP from the orc8r? or should it come from AGW enodebd.

There are two types of state, the runtime state of the endobe (its health, current gps location etc.) and config state. The runtime state will be reported by enodebd to the orc8r as part of the generic checkins or to the DP if it is part of the SAS related information (current SAS state whatever else we want to report). The configuration state e.g. access gws <-> enb mappings etc. the source of truth is always the orc8r. magma follows the desired state model here. @hcgatewood might be able to offer insights into how the domain proxy gets notified if a enodeb is unprovisioned from an AGW.

> 2. Also related. If eNB is deleted from magma, DP should stop sending heartbeats to SAS and deregister the device. How will the DP know that the eNB has been deleted? Should it get this information from enodebd or orc8r?

Same as above, orc8r is the source of truth.
> 3. How does enodebd know that the eNB stopped radiating? What does "stop radiating" mean precisely?

There will be a subsequent inform message from the radio that will contain the transmit and admin status of the enodeb. That will say false/down. Stop radiating means it will broadcast radio signal.
> 4. You wrote "The knowledge of these radios being CBRS certified is obtained out of band. i.e. for practical purposes the onboarding of these radios are going to be similar to what we have today". Please elaborate on the current process and on how we will be able to determine whether a radio is a CBRS or not

Try checking out the NMS, there is a drop down that lists the models, based on the models listed you can determine if the radio supports CBRS or not.
> 5. Regarding API changes, do you mean the orc8r API?

Both Swagger and GRPC interface to the domain proxy for enodebd to hit.
> 6. "Swagger will introduce a new vendor name for CBRS certified radios".
>    What is a "new vendor name"? There is already BaiCells model support implemented. Do you mean "new radio type"?

Yeah but you need to add a new line for the specific Baicells Nova or whatever model that supports CBRS no?
> 7. What exactly is mconfig? From what we've seen in the code it seems to be something based off of mconfigs.proto, populated by the data from gateway.mconfig, but we may be totally wrong.

Yes it is a config pushed from the orchestrator to the gateway. Not sure if there is better documentation on this. @ardzoht 
> 8. On an Inform request from eNB, do we always need to check in Redis if it's a new installation or a radio that was rebooted?

You can maintain an in-memory state cache of redis state thats what most services do today.
> 9. Why is the enodebd restart needed after configuration changes? I understand this is something we eventually want to optimize so first we need to know why exactly it needs restarting. To reload the config on the enodeb? Does the reboot not affect other eNBs connected to it?

enodebd today assumes that it knows what the enodeb config needs to be on startup. So if the config changes then we restart the endoedb service. Since endodeb does a getparam before sets it will not affect the enodeb configuration
> 10. "enodebd will remove the sas redis state associated with the radio and restart"
>     Is this something that needs implementing or is it already in place?

enodebd today doesn't talk to Redis, you will need to add support, look at mobilityd for an example.

**Comment by nobletrout** [comment]
hey guys, it's  little confusing for me an outsider. Is this proposal accepted? Is there active development going on to create a domain proxy for CBRS?

**Comment by xbend** [comment]
@nobletrout 
Hey,
The proposal was accepted. As you can see in the history of this issue it was labeled as accepted on 20 Sep 2021.
Domain Proxy for CBRS is already part of Magma and there is active development around it.

If you have any questions, I would redirect You to [Magma Community documentation](https://github.com/magma/community) and join us on Slack `#project-domain-proxy` channel.
