### ISSUE TITLE
[AGW] Skip format_* prerequisites on build_* targets

### ISSUE THREAD

**Issue by markjen** [magma/magma#8203]
# Skip format_* prerequisites on build_* targets

## Problem

Running `make build_oai` invokes `format_core` as a pre-req, which runs `clang-format` on all files in `lte/gateway/c/core`, which is slow and unnecessary.

In my dev environment, `make format_core` takes over a minute (without anything else running) and does not yield any code update:

```
vagrant@magma-dev-focal:~/magma/lte/gateway$ /usr/bin/time make format_core
OAI_FLAGS -DS6A_OVER_GRPC=True -DEMBEDDED_SGW=True -DENABLE_OPENFLOW=True -DSPGW_ENABLE_SESSIOND_AND_MOBILITYD=True
find /home/vagrant/magma/lte/gateway/c/core \( -iname "*.c" -o -iname "*.cpp" -o -iname "*.h" \) -exec \
clang-format --style=file -i {} \;
68.53user 18.73system 1:34.93elapsed 91%CPU (0avgtext+0avgdata 218964maxresident)k
0inputs+0outputs (0major+8284931minor)pagefaults 0swaps
```

## Solution

- Remove `format_core` prereq from `make_oai` and `format_common` prereq from `make_common`
- Add `precommit` target in lte/gateway/Makefile that runs format and fails if git is not clean
- Add ci check that runs `precommit`

## Non-goals

- None

**Comment by electronjoe** [comment]
Related #6187
