### ISSUE TITLE
Xwfm tests failing on master

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#8249]
close this once it is back to being healthy
https://circleci.com/gh/magma/magma/332934
https://circleci.com/gh/magma/magma/332928

flagging @aharonnovo since he is the owner

**Comment by themarwhal** [comment]
Assigning @koolzz as well as he is oncall this week.

**Comment by ulaskozat** [comment]
Coassigning to myself as I am the oncall this week. @aharonnovo what is the estimate time on closing this issue?

**Comment by themarwhal** [comment]
https://github.com/magma/magma/pull/8282 fixed the xwf test but broke CWAG build / tests so I had to revert it. Reopening the issue.

**Comment by ulaskozat** [comment]
This seems to be consistently failing today: https://app.circleci.com/insights/github/magma/magma/workflows/hourly_xwfm/overview?branch=master&reporting-window=last-24-hours @aharonnovo @quentinDERORY

**Comment by ulaskozat** [comment]
@aharonnovo are you looking into resolving this? Otherwise please advise on who the owner is.
