### ISSUE TITLE
agw: fix performance regression with GTP echo

### ISSUE THREAD

**Issue by pshelar** [magma/magma#8255]
On scale test we have observed performance regression when GTP echo is enabled. This likely OVS GTP implementation issue.

**Comment by ulaskozat** [comment]
what is the timeline on landing a fix on this?

**Comment by pshelar** [comment]
I am working on this, hopefully post fix this week.

**Comment by pshelar** [comment]
Posted PR: https://github.com/magma/magma/pull/8328
I am working on validation.

**Comment by pshelar** [comment]
PR landed.
