### ISSUE TITLE
[feg] vagrant up feg installed older version of docker-compose that caused building image process to fail

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#8286]
### Your Environment

- **Version:** 1.6
- **Affected Component:** FEG
- **Affected Subcomponent:** FEG
- **Deployment Environment:** local docker-compose (orc8r), Vagrant (AGW), Vagrant (FEG)

### Describe the Issue

We are testing FEG installation and registration to orc8r. Our environment as below:

Two VMs    ------ Vagrant magma AND Vagrant FEG ----- AGW (baremetal) \\ FEG (docker-compose)
Base server ---------------- Ubuntu 18.04 -------------- orc8r and NMS (docker-compose)

To install the FEG VM we have used Vagrant to bring up FEG machine:
1. To create and provision FEG VM:
[Base server] ~/magma/feg/gateway$ vagrant up feg

2. To access FEG VM:
[Base server] ~/magma/feg/gateway$ vagrant ssh feg

**To Reproduce**
1. SSH to FEG VM
[Base server] ~/magma/feg/gateway$ vagrant ssh feg

2. Navigate to docker folder of feg and build docker images:
vagrant@magma-feg-dev:~/magma/feg/gateway/docker$ docker-compose build --parallel
WARNING: The USE_GY_FOR_AUTH_ONLY variable is not set. Defaulting to a blank string.
WARNING: The GY_SUPPORTED_VENDOR_IDS variable is not set. Defaulting to a blank string.
WARNING: The GY_SERVICE_CONTEXT_ID variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.aaa_server.depends_on contains an invalid type, it should be an array
services.control_proxy.depends_on contains an invalid type, it should be an array
services.csfb.depends_on contains an invalid type, it should be an array
services.eap_aka.depends_on contains an invalid type, it should be an array
services.eap_sim.depends_on contains an invalid type, it should be an array
services.eventd.depends_on contains an invalid type, it should be an array
services.feg_hello.depends_on contains an invalid type, it should be an array
services.health.depends_on contains an invalid type, it should be an array
services.magmad.depends_on contains an invalid type, it should be an array
services.radiusd.depends_on contains an invalid type, it should be an array
services.redis.depends_on contains an invalid type, it should be an array
services.s6a_proxy.depends_on contains an invalid type, it should be an array
services.s8_proxy.depends_on contains an invalid type, it should be an array
services.session_proxy.depends_on contains an invalid type, it should be an array
services.swx_proxy.depends_on contains an invalid type, it should be an array

3. Check docker-compose version and compare it to the latest version:
vagrant@magma-feg-dev:~/magma/feg/gateway/docker$ docker-compose version
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

4. Download and install the latest version of docker-compose and build images again:
vagrant@magma-feg-dev:~/magma/feg/gateway/docker$ **docker-compose version**
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
vagrant@magma-feg-dev/magma/feg/gateway/docker$ **docker-compose build**
WARNING: The USE_GY_FOR_AUTH_ONLY variable is not set. Defaulting to a blank string.
WARNING: The GY_SUPPORTED_VENDOR_IDS variable is not set. Defaulting to a blank string.
WARNING: The GY_SERVICE_CONTEXT_ID variable is not set. Defaulting to a blank string.
td-agent-bit uses an image, skipping
eventd uses an image, skipping
eap_aka uses an image, skipping
feg_hello uses an image, skipping
swx_proxy uses an image, skipping
session_proxy uses an image, skipping
eap_sim uses an image, skipping
aaa_server uses an image, skipping
health uses an image, skipping
control_proxy uses an image, skipping
radiusd uses an image, skipping
s6a_proxy uses an image, skipping
s8_proxy uses an image, skipping
redis uses an image, skipping
hss uses an image, skipping
**Building csfb**

**Expected behavior**
It is expected that provisioning of the FEG machine install latest and consistent version of components that help with later steps.

**Comment by ekowtaylor** [comment]
cc. @ulaskozat , @tmdzk
