### ISSUE TITLE
[agw] Openflow controller lost connection to switch

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#8312]
### Your Environment

- **Version:** v1.6 / master 
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** virtual access gateway with 64G mem and 16vCPU. Cores 7-15 associated with S1/SGi in pipelined.

### Describe the Issue
Ran a spirent test with 1800 subs, 36 eNBs, 10UE/sec attach rate, 350K per UE. 

After about 5-6 minutes into the test, mme log shows 

'''
148065 Tue Jul 27 18:23:22 2021 7F677E3EC700 ERROR GTPv1- lib/openflow/controller/Openflow:0091    Openflow controller lost connection to switch
148066 Tue Jul 27 18:23:24 2021 7F677EBED700 INFO  GTPv1- lib/openflow/controller/Openflow:0071    Openflow controller connected to switch
148067 Tue Jul 27 18:23:24 2021 7F677EBED700 INFO  GTPv1- lib/openflow/controller/Openflow:0076    Send signal that Controller is connected to switch to all waiting threads
'''

![image](https://user-images.githubusercontent.com/38921899/127248808-9e46865a-d244-4c59-b16c-4629bfa736ae.png)
Any subscriber already attached continues to stay connected, however no new subs can be onboarded. Attach requests are timing out after getting the connection loss error to switch.

openvswitch-switch hasn't restarted throughout the test.

```
● openvswitch-switch.service - LSB: Open vSwitch switch
     Loaded: loaded (/etc/init.d/openvswitch-switch; generated)
     Active: active (running) since Tue 2021-07-27 17:45:45 PDT; 42min ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 21 (limit: 77196)
     Memory: 173.6M
     CGroup: /system.slice/openvswitch-switch.service
             ├─942569 ovsdb-server: monitoring pid 942570 (healthy)
             ├─942570 ovsdb-server /etc/openvswitch/conf.db -vconsole:emer -vsyslog:err -vfile:info --remote=punix:/var/run/openvswitch/db.sock --private-key=db:Open_vSwitch,SSL,private_k>
             ├─942589 ovs-vswitchd: monitoring pid 942590 (healthy)
             └─942590 ovs-vswitchd unix:/var/run/openvswitch/db.sock -vconsole:emer -vsyslog:err -vfile:info --mlockall --no-chdir --log-file=/var/log/openvswitch/ovs-vswitchd.log --pidfi>

Jul 27 17:45:44 vagw-uu9 ovs-vsctl[942757]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 mtr0 -- set Interface mtr0 type=internal -- set interface >
Jul 27 17:45:44 vagw-uu9 ovs-vsctl[942816]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 ipfix0 -- set Interface ipfix0 type=internal -- set interf>
Jul 27 17:45:45 vagw-uu9 ovs-vsctl[942875]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 patch-up -- set Interface patch-up type=patch options:peer>
Jul 27 17:45:45 vagw-uu9 ovs-vsctl[942924]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 proxy_port --
Jul 27 17:45:45 vagw-uu9 ovs-vsctl[942972]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 li_port -- set Interface li_port type=internal -- set inte>
Jul 27 17:45:45 vagw-uu9 openvswitch-switch[943010]: net.ipv4.ip_forward = 1
Jul 27 17:45:45 vagw-uu9 ovs-vsctl[943059]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-br uplink_br0 --
Jul 27 17:45:45 vagw-uu9 ovs-vsctl[943102]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port uplink_br0 dhcp0 -- set Interface dhcp0 type=internal -- set inter>
Jul 27 17:45:45 vagw-uu9 ovs-vsctl[943160]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port uplink_br0 patch-agw -- set Interface patch-agw type=patch options>
Jul 27 17:45:45 vagw-uu9 systemd[1]: Started LSB: Open vSwitch switch.
```

[mme_vagwu9.log.zip](https://github.com/magma/magma/files/6889666/mme_vagwu9.log.zip)

**Comment by pshelar** [comment]
@koolzz Can you have a look at this one. It looks like MME controller is dropping connection to OVS.

**Comment by koolzz** [comment]
> @koolzz Can you have a look at this one. It looks like MME controller is dropping connection to OVS.

I think this will fix it https://github.com/magma/magma/pull/7741/files#diff-b45e66ca9bf03856b9c65446abed494113be7bd5824751c560f32846e4dabbccR18

Whenever controller losses connection its usually ovs restart and with that PR landed the mme will also get restarted (I'll try to get that erged shortly, it got lost as it wasn't reviewed)

**Comment by sudhikan** [comment]
hey @koolzz - still seeing the same thing .

I tested on 1.7.0-1629228553-c8e34da6... it seems the PR referenced above was back ported to v1.7 branch but after the ovs connection is lost, no additional subscribers can be onboarded. 
![image](https://user-images.githubusercontent.com/38921899/129976738-e960418f-1144-43e3-8ec3-998903aa42aa.png)

Test Case was 2K subs, 32 eNBs, 5UEs/sec attach rate, with 350K per UE. 
VM is a 16 core VM with cores 7-15 reserved for S1 and SGi.

**Comment by koolzz** [comment]
> hey @koolzz - still seeing the same thing .
> 
> I tested on 1.7.0-1629228553-c8e34da6... it seems the PR referenced above was back ported to v1.7 branch but after the ovs connection is lost, no additional subscribers can be onboarded.
> ![image](https://user-images.githubusercontent.com/38921899/129976738-e960418f-1144-43e3-8ec3-998903aa42aa.png)
> 
> Test Case was 2K subs, 32 eNBs, 5UEs/sec attach rate, with 350K per UE.
> VM is a 16 core VM with cores 7-15 reserved for S1 and SGi.

hmm thats odd, I'll try to reproduce, for this did you just restart openvswitch service mid run?
