### ISSUE TITLE
QOS errors on Pipelined

### ISSUE THREAD

**Issue by veshkemburu** [magma/magma#8317]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 
- **Affected Component:** Access Gateway(phy_agw1)
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** AGW

### Describe the Issue

Looking at pipelined logs, I've noticed qos errors in the form of the following:
`Jul 28 16:06:33 phy-agw1 pipelined[3139383]: ERROR:pipelined.qos.tc_pyroute2:del-filter error : 2
Jul 28 16:06:33 phy-agw1 pipelined[3139383]: ERROR:pipelined.qos.tc_pyroute2:del-htb  error error : 2
Jul 28 16:06:33 phy-agw1 pipelined[3139383]: ERROR:pipelined.qos.qos_tc_impl:error deleting class 4209, not releasing idx`

**To Reproduce**
1. Transfer over latest sessiond binary to AGW(phy_agw1) and update to latest magma version.
2. Ssh into spirient VM and run test script
3. View pipelined logs in phy_agw1

**Expected behavior**

**Screenshots**
<img width="1791" alt="Screen Shot 2021-07-28 at 12 09 09 PM" src="https://user-images.githubusercontent.com/84861766/127357794-9e94c8fa-e690-433a-8b0e-a2c100f80cb1.png">

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ekowtaylor** [comment]
What version was this issue observed?
