### ISSUE TITLE
bettereng: update cpp_redis version

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#8321]
The current cpp_redis version we use is from nov 2017, it would be good upgrade this so we include any potential bug fixes. For example, debug level logging for the version we are currently on is broken and is only fixed in a later version.

One other perk of the more recent releases is that it comes with a Bazel build file. This means we can no longer maintain our own build file for the repository.

**Comment by wolfseb** [comment]
The cpp_redis version 4.3.1 is still the newest version on `github.com/cpp-redis/cpp_redis`. An update is thus not possible. The only alternative would be to switch to a different redis library that is maintained more frequently.

**Comment by wolfseb** [comment]
Follow-up: see #14789
