### ISSUE TITLE
Attach Reject as Create Session Response Fails/Timeout | Sessiond running out of memory in a couple of minutes

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#8322]
**Version:**1.5.167-1625830115-2f993e3b9
Affected Component: Access Gateway
Affected Subcomponent: Mobilityd
Deployment Environment: bare-metal (AGW)

### Describe the Issue

We observed some UEs were rejected by Magma with Cause 19 ESM Failures as Create Session Response failed after 10 seconds of the request due to timer expiry. In MME logs we can see S11 Create Session Request sent/Received, while in System logs after the ULA is successful and MME allocates UE an IP, no Create Session Request Received neither a new session is established.

**Expected behavior**
Sessiond should receive Create Session Request and established a new session

**Screenshots**
![image](https://user-images.githubusercontent.com/77636702/127390277-d3037857-b826-4304-a0d1-d347622a1bb6.png)

![image](https://user-images.githubusercontent.com/77636702/127397372-b7e12f2a-7600-4071-8ecd-2f1c5a40868b.png)
![image](https://user-images.githubusercontent.com/77636702/127397542-feb54a1a-77c8-41cd-b63e-de3c0084788f.png)

**Additional context**
[Logs.zip](https://github.com/magma/magma/files/6896545/Logs.zip)

**Comment by shehzadalee** [comment]
@amarpad @jpad-freedomfi

**Comment by shehzadalee** [comment]
We observed this issue on another unit as well which was recently upgraded to 1.5.167. Apparently it is due to Sessiond memory being exhausted as evident from below snapshot.
![image](https://user-images.githubusercontent.com/77636702/127430095-91e1fb49-7c1a-44c7-821d-8d4777f54c98.png)

Moreover, it seems to consume memory very rapidly, like 290M in 14 minutes after service restart.

**Comment by jpad-freedomfi** [comment]
@wallyrb and @sudhikan  wanna bring this one to your attention. looks like sessiond has memory issue. Should the service go to 100% of allowed mem usage and just sit there? I have new 1.5 build in our lab, 1 UE, UE-inactivity timer = 4sec, sessiond reaches default limit of 300MB in 1 hr. 

this is in vanilla NAT mode(lab test), as well as non-NAT mode (production)

Can we get some help looking into this?

**Comment by jpad-freedomfi** [comment]
also, here is picture of service restart metric table. Not all 1.5 sites are having issue, but looks like 2 sights in particular are seeing sessiond and pipelined restarts. But lets start with sessiond as it clearly consumes mem and has trouble garbage collecting it seems. 
<img width="1344" alt="Screen Shot 2021-08-05 at 4 11 55 PM" src="https://user-images.githubusercontent.com/61293007/128428163-dafdbf7f-6950-482c-9946-e76b80c2cacb.png">

**Comment by ulaskozat** [comment]
isn't swap enabled here?

**Comment by ulaskozat** [comment]
Are you enabling ASAN on this build? cc @themarwhal

**Comment by jpad-freedomfi** [comment]
This is a build off 1.5.2 or very similar head of 1.5 branch. To my knowledge we didn't enable anything special. 

We can enable ASAN in a new image.

**Comment by jpad-freedomfi** [comment]
And yes swap is enabled

**Comment by themarwhal** [comment]
We've seen that when the executable is built with ASAN we see memory issues in SessionD. Can you run `nm -an /usr/local/bin/sessiond | grep asan` to see if this particular binary has ASAN enabled or not?

**Comment by jpad-freedomfi** [comment]
@themarwhal and @ulaskozat does that mean it's on? 
```
magma@FreedomFi-Gateway:~$ nm -an /usr/local/bin/sessiond | grep asan
                 U __asan_after_dynamic_init
                 U __asan_before_dynamic_init
                 U __asan_handle_no_return
                 U __asan_init
                 U __asan_register_globals
                 U __asan_report_load1
                 U __asan_report_load16
                 U __asan_report_load4
                 U __asan_report_load8
                 U __asan_report_load_n
                 U __asan_report_store1
                 U __asan_report_store16
                 U __asan_report_store4
                 U __asan_report_store8
                 U __asan_report_store_n
                 U __asan_stack_free_5
                 U __asan_stack_free_6
                 U __asan_stack_free_7
                 U __asan_stack_malloc_1
                 U __asan_stack_malloc_2
                 U __asan_stack_malloc_3
                 U __asan_stack_malloc_4
                 U __asan_stack_malloc_5
                 U __asan_stack_malloc_6
                 U __asan_stack_malloc_7
                 U __asan_unregister_globals
                 U __asan_version_mismatch_check_v6
0000000000000000 a asan_preinit.cc
00000000032f6b30 d __local_asan_preinit
0000000003fa5878 B __asan_option_detect_stack_use_after_return
```

**Comment by jpad-freedomfi** [comment]
is ASAN toggle global? Should we be disabling in other services as well?

**Comment by jpad-freedomfi** [comment]
Guidance for how @mattymo can disable requested. Not sure we know where to set that.

**Comment by themarwhal** [comment]
Yes so it looks liks ASAN is enabled. How was this built? 
You should be able to build (no ASAN) by running
```
cd $MAGMA_ROOT/lte/gateway
fab test package:vcs=git
```

**Comment by ulaskozat** [comment]
Thanks @themarwhal for confirming that the build has ASAN enabled. @jpad-freedomfi when fab command used for packaging if `test` is used it actually provides a release build and when `dev` is used it is a development build. Since the term is confusing and documentation was lagging, @themarwhal raised two PRs #8527 and #8529.

**Comment by jpad-freedomfi** [comment]
Awesome! Thanks for the help!

@mattymo does that get you what you need to do a new build for us without ASAN?

**Comment by ulaskozat** [comment]
@jpad-freedomfi let's close the issue as soon as you verify that release build fixes the issue.

**Comment by mattymo** [comment]
@themarwhal And how about building without ASAN support?

**Comment by jpad-freedomfi** [comment]
@themarwhal can you share more about how to disable if we build with vagrant? @mattymo can you describe how we build?

**Comment by themarwhal** [comment]
I've upgraded the doc recently to add more information on the build process:https://docs.magmacore.org/docs/lte/build_install_magma_pkg_in_agw

`fab test package:vcs=git` -> No ASAN, production package
`fab dev package:vcs=git` -> Development, debug level package with ASAN enabled

**Comment by ulaskozat** [comment]
@shehzadalee @jpad-freedomfi I am closing this. Please reopen if the issue is still there.
