### ISSUE TITLE
Deployment Guide or installation step

### ISSUE THREAD

**Issue by rbk1001** [magma/magma#834]
Hi,

the link "https://facebookincubator.github.io/magma/docs/basics/quick_start_guide" described the step to deploy a development environment, is there any information on how to setup for a environment for real traffics testing?

**Comment by xjtian** [comment]
https://facebookincubator.github.io/magma/docs/orc8r/deploy_intro

https://facebookincubator.github.io/magma/docs/lte/setup_deb
