### ISSUE TITLE
[AMF: Unit Test] Creating ue_context infrastructure

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#8347]
This is a place holder PR for unit testing infrastructure.
There are some pre-requisite structure to be filled before calling the functions. This PR is about filling the ue_context structure to be used.

**Comment by panyogesh** [comment]
1. Write the test_fixtures for common code 
For instance in setup :
  a. Create amf_create_new_ue_context()
In tear Down
   b. Clean up the variables.

**Comment by Krishnavamsi-wavelabs** [comment]
I raised PR #9121 for this issue. PR got merged.
