### ISSUE TITLE
AMF Configuration optimization

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#8353]
As part of AMF Configuration optimization, amf will pull the configuration from mme if its generic. Only if the parameter is specific to AMF it will parse it.

Idea is to re-use the mme parsing code to possible extent

**Comment by ganeshg87** [comment]
- add supported slice types configurable on amf

**Comment by ganeshg87** [comment]
duplicate Zenhub ticket https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/8332
