### ISSUE TITLE
Remove old northbound listSubscribers handler

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#8359]
## Prerequisites 

- [ ] Go through the prerequisites section in the magma doc to install all dependencies: https://docs.magmacore.org/docs/next/basics/prerequisites
- [ ] Try building / running the Orc8r by following: https://docs.magmacore.org/docs/next/basics/quick_start_guide#terminal-tab-2-build-orchestrator
- [ ] Try building / running the NMS: https://docs.magmacore.org/docs/next/basics/quick_start_guide#using-the-nms-ui

## Action

Old handler: https://github.com/magma/magma/blob/50c1b7f34342c63f861baa56275b45bfb41b45c0/lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go#L136-L149

New handler: https://github.com/magma/magma/blob/50c1b7f34342c63f861baa56275b45bfb41b45c0/lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go#L189-L213

We don't use the old handler anymore, so can remove it in favor of the new handler

## Validation Steps
1. Run all Orc8r unit tests: https://docs.magmacore.org/docs/next/orc8r/dev_testing
2. Regenerate Magma <-> NMS API Bindings.js: https://docs.magmacore.org/docs/next/orc8r/dev_testing#pre-build-code-generation
3. Bring up the NMS locally to check everything compiles

## Followup task
https://github.com/magma/magma/issues/8662

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by christinewang5** [comment]
working on this task for bootcamp!
