### ISSUE TITLE
app: state: Increase default state sync interval, make interval Orc8r-controlled

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#8384]

**Comment by uri200** [comment]
Hey @hcgatewood, in fact we need to reduce the synch interval in order to have real time responses on federated scenarios

In teravm we had to reduce it to 4s to be able to execute RARs right after attaching (that is something that happens on the field too). We will probably have to use a very low value for some of our production deployments.

State sync will probably have to be redesigned so the information is ready to be consumed by or8cr as soon as it exist on AGW.

**Comment by hcgatewood** [comment]
> Hey @hcgatewood, in fact we need to reduce the synch interval in order to have real time responses on federated scenarios
> 
> In teravm we had to reduce it to 4s to be able to execute RARs right after attaching (that is something that happens on the field too). We will probably have to use a very low value for some of our production deployments.
> 
> State sync will probably have to be redesigned so the information is ready to be consumed by or8cr as soon as it exist on AGW.

Hey @uri200 thanks for the context

The state service is meant to be a way to preserve AGW state across AGW failures etc. We also provide some state indexing functionality for non-time-sensitive indexing needs

Use-cases that expect time-sensitive state reporting (e.g. less than 60s, and definitely for those less than 10s) are effectively treating the state service as a message bus, rather than a state replicator. So I agree that the state service is not a good fit for this use-case. Instead, the immediate solution feels like those use-cases should be making event-triggered unary grpc requests to Orc8r

Lmk your thoughts on this. Happy to learn more about the need and work toward an effective solution

**Comment by uri200** [comment]
We may build some kidn of ID dispatcher on orc8r for AGW (to avoid collisions #8313). Maybe we can widen the scope and include some of the field updated by state id.

**Comment by uri200** [comment]
> We may build some kidn of ID dispatcher on orc8r for AGW (to avoid collisions #8313). Maybe we can widen the scope and include some of the field updated by state id.

unfortunately this is not valid anymore. If we want to Federated case working on request initiated from the core, we need to reduce the frequency until we find a better solution (recommended now is 4s)
