### ISSUE TITLE
agw: Individual task TASK_MME_APP being terminated

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#8425]
### Your Environment

- **Version:** 1.5.2-1624485681-ae972900
- **Affected Component:** Access Gateway
- **Affected Subcomponent:**  mme service
- **Deployment Environment:**Virtual AGW(VMWARE)

### Describe the Issue

TASK_MME_APP is being terminated unexpectably, other tasks don't terminate, making mme unresponsive. It can be observe, later mme service is exited.

```
Aug  1 03:23:18 mme[3747752]: TASK_MME_APP terminated
Aug  1 08:20:28 systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
```

**Expected behavior**
TASK_MME_APP should terminate, and if terminates, other tasks should terminate as well.

Internal task: T97082675

**Comment by ulaskozat** [comment]
Closing the issue as the fixes have landed to prevent individual thread exits (and safeguards if some does).
