### ISSUE TITLE
Extension to subscriber configuration, unit tests to verify API compatibility with Orchestrator.

### ISSUE THREAD

**Issue by pmishra-wavelabs** [magma/magma#8438]
1) **defaultSingleNssais -> array(Snssai)** 
Snssai  => sst,sd
sd => nil
sst =>
Unsigned integer, within the range 0 to 255,  
representing the Slice/Service Type. It indicates the  
expected Network Slice behaviour in terms of  
features and services.  
Values 0 to 127 correspond to the standardized SST  
range. Values 128 to 255 correspond to the  
Operator-specific range. See clause 28.4.2 of  
3GPP TS 23.003 [7].  
Standardized values are defined in clause 5.15.2.2  
of 3GPP TS 23.501 [8] 

2) **coreNetworkTypeRestrictions -> array(CoreNetworkType)** 

Enumeration value 
"5GC" 
"EPC"

**Comment by anusha-konda** [comment]
Duplicate of #8787, hence closing the issue.
