### ISSUE TITLE
[agw][BE] S1AP gRPC servicer state access violation

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8450]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

- Currently, enodebd sends out a `GetENBState` gRPC request for obtaining the current eNB state from s1ap task, this is a periodic call that is done every minute through the service303's `get_operational_states` function.
- This results in a crash due to the gRPC call done by enodebd comes before `s1ap_state` getting read and populated from redis, there is an assertion done by the StateManager that expects the state to be not null. 

**Proposed changes**

> To fix the resulting crash due to the `AssertFatal` on the S1APStateManager, `GetENBState` can be modified to be a push (or streaming) model. 
> This gRPC call will be initiated by the MME and should only be done after all S1AP task state in the service is populated.
> This will also allow to maintain the `get_s1ap_state` retrieved call for now, to ensure state sync and ownership of the task's state. 

- Current service definition:
```
service S1apService {
    // Returns state of the S1 connected eNBs
    rpc GetENBState (magma.orc8r.Void) returns (EnbStateResult) {}
}
```

- Updated service definition (with streaming):
```
service S1apService {
    // Pushes a stream of S1 connected eNBs map
    rpc ListEnbState (magma.orc8r.Void) returns (stream EnbStateResult) {}
}
```

- `enodebd/s1ap_service.py` gRPC client updates will be needed to reflect consuming of the `EnbStateResult` stream.

**Comment by ulaskozat** [comment]
@ardzoht we do have the same issue for HA service.
