### ISSUE TITLE
techdebt: upgrade protobuf and migrate C++ protobuf library usage of `status.error_message()` to `status.message()`

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#8457]
The protobuf team has deprecated the `error_messasge` method sometime between the latest release ( https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3) and release 3.15.0 (https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0)

Our dev VM uses protobuf version 3.6.1 (From Jul 31, 2018)

We currently have 55 instances of C++ code that uses this method: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+.error_message%28%29&patternType=literal

We should upgrade protobuf and migrate to the new method as we're unable to upgrade a few other dependencies that depend on protobuf.

This can be easily done once/if we migrate to bazel.

**Comment by themarwhal** [comment]
Comment

**Comment by nstng** [comment]
Looks like its only `lte/gateway/c/session_manager/OperationalStatesHandler.cpp`. In similar cases `status.ToString()` is used. As Bazel already uses a protobuf version > 3.6.1 it might be OK to make this change - because bazel 5 needs `rules_proto_grpc >= 4.1.1` which ships with protobuf 3.19.1.
