### ISSUE TITLE
Protobuf compiler installation step in magma VM provisioning fails

### ISSUE THREAD

**Issue by ezechinwa** [magma/magma#846]
I get this error when running 
`MAGMA-VM [/home/vagrant/magma/lte/gateway]$ make run`

cannot create directory '/magma_common': Permission denied 

Here is an image of the error response 
![Screenshot 2019-11-12 at 5 35 28 PM](https://user-images.githubusercontent.com/17327631/68691318-d4ee8200-0573-11ea-8ccb-ff759344ac38.png)

**Comment by ardzoht** [comment]
Can you check if the `vagrant up magma` step ran successfully? As the `make run` step will be dependent whether the VM was provisioned successfully, we need to check if that passed without errors first

**Comment by ezechinwa** [comment]
Provisioning the VM fails with the following errors below;
![Screenshot 2019-11-12 at 6 07 01 PM](https://user-images.githubusercontent.com/17327631/68693383-7f1bd900-0577-11ea-9fb0-58048f902fb0.png)
![Screenshot 2019-11-12 at 6 06 23 PM](https://user-images.githubusercontent.com/17327631/68693391-8216c980-0577-11ea-8eb4-ac3346c0c4fd.png)
![Screenshot 2019-11-12 at 6 06 08 PM](https://user-images.githubusercontent.com/17327631/68693402-8642e700-0577-11ea-9c3c-814fccc3fdc9.png)

**Comment by ardzoht** [comment]
Ok, we can try two things here, first, replacing the ansible version installed by pip3, and installing it with `brew install ansible`, in case homebrew isn't available, the second thing to do would be to remove the `match` condition on line 73 on `magma/orc8r/tools/ansible/roles/gateway_dev/tasks/main.yml` (as a temporary fix). I will dig more into why this is happening, but to unblock you these 2 options will help.

**Comment by ezechinwa** [comment]
Hi, 
I have tried the solution you recommended, now getting this error when running
 ` make run`

![Screenshot 2019-11-13 at 11 04 29 AM](https://user-images.githubusercontent.com/17327631/68753534-812c7900-0605-11ea-81a9-99e58c1eb2c0.png)

**Comment by ardzoht** [comment]
Ok I found the issue, can you try this? Replacing line 73 on the same file (magma/orc8r/tools/ansible/roles/gateway_dev/tasks/main.yml), and change the `match("^libprotoc 3.")` to `regex_search("^libprotoc 3.")`. I tried on my vm with a fresh VM provisioning and worked, if it does let me know and I'll push an update to fix this.

**Comment by ezechinwa** [comment]
It worked thanks a lot

**Comment by ardzoht** [comment]
Closing this, fixed by https://github.com/facebookincubator/magma/pull/861.
