### ISSUE TITLE
Subscriber Events Monitoring in NMS

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#8466]
### Your Environment (If applicable)

- **Affected Component:** AGW, Orchestrator, NMS

### Describe the problem

**Description**
In order to troubleshoot user specific issues we need to collect control plane logs(ie. attach request, create session request, etc) from several services(mme, sessiond, pipelined, etc). For this, we need to connect to AGW and then collect logs from several files that keep rotating(mme logs, syslogs, etc). And some logs are not properly tagged with IMSI. Therefore, it takes long time and becomes confusing to troubleshoot user specific issues.

Troubleshoot user specific issues is part of daily operations in monitoring Magma. 

**Desired timelines**
2021 H2

### Describe your solution
**Description**
NMS should have an option under Call tracing to visualize the control plane flows. For example, using an IMSI and time range to filter control plane logs for all services involved in the session. All necessary logs(including errors) should be able to collect with one single query. 

**Additional context**
Visualization of internal tracing can follow below call flow
https://github.com/magma/magma/blob/master/docs/readmes/lte/Attach_call_flow_in_Magma.jpg

### Impact Evaluation

**Impact**
High, fills in missing information which allows users to resolve issues faster

**Reach**
Medium, need confirmation on how often the Call Tracing feature is used

**Confidence**
Medium, yes this info is missing and they need it 

**Eng Effort**
tbd

### High priority events

- attach_request
- attach_accept
- attach_complete
- attach_reject
- security_mode_command
- security_mode_complete
- authentication_information_request
- authentication_information_response
- update_location_request
- update_location_answer
- initial_context_setup_request
- initial_context_setup_response
- esm_request
- esm_response
- paging
- service_request: 
- service_reject: 
- ue_context_release_request
- ue_context_release_command
- ue_context_release_complete
- tracking_area_update_request
- tracking_area_update_success
- tracking_area_update_reject
- create_session_request
- create_session_response
- modify_bearer_request
- modify_bearer_response
- ue_state_change

### Event Details
Event information may differ by each event, but in general events should have:

- imsi or GUTI if imsi not available
- mme id
- enodeb id
- enodeb IP
- cause (For non success events)
- APN (if have it)

**Comment by krramasw** [comment]
My comments

1) My understanding is that td-agent-bit service forwards event logging to an external server. 

From the doc

 Enables log aggregation and event logging where it takes input from syslog and the events service and forwards the output to the Orchestrator. It is received on the Orchestrator by Fluentd then stored in Elasticsearch.


2) Also, show tech-support collects other information (config etc) and I think it needs to be visible in NMS.

**Comment by krramasw** [comment]
Also please look at the proposal https://magma.github.io/magma/docs/next/proposals/p018_control_network_metrics
Seems to me that p018_control_network_metrics feature has some overlap with you what you articulated

**Comment by wallyrb** [comment]
> My comments
> 
> 1. My understanding is that td-agent-bit service forwards event logging to an external server.
> 
> From the doc
> 
> Enables log aggregation and event logging where it takes input from syslog and the events service and forwards the output to the Orchestrator. It is received on the Orchestrator by Fluentd then stored in Elasticsearch.
> 
> 1. Also, show tech-support collects other information (config etc) and I think it needs to be visible in NMS.

thanks @krramasw ! yeah there are already some tools to collect the control plane logs from users. However, I notice not all logs have IMSI label, or UE ID label. So will be great to improve the logging to improve observability. 

And just to remark, the problem here is that using logs to analyze user control issues is not straightforward. Since we need to do a lot of text manipulation in the logs to filter one single user. And also we don't have one single log file, we have several and these keep rotating. I am preparing a python script to do all this, but  I think the end goal is to move this to NMS. Like  Call tracing to visualize the control plane flows for a specific user.(similar to the picture attached in this issue)

**Comment by jingtien** [comment]
- [Wally] First draft of high priority events including details, attach to this task.
- [Wally] Write up impact on reliability, add to this task.
- Move this task to Product Backlog

Design
- Exploration
- Create documentation for troubleshooting suggestions based on Alerts troubleshooting template

**Comment by wallyrb** [comment]
### High priority events

- attach_request
- attach_accept
- attach_complete
- attach_reject
- security_mode_command
- security_mode_complete
- authentication_information_request
- authentication_information_response
- update_location_request
- update_location_answer
- initial_context_setup_request
- initial_context_setup_response
- esm_request
- esm_response
- paging
- service_request: 
- service_reject: 
- ue_context_release_request
- ue_context_release_command
- ue_context_release_complete
- tracking_area_update_request
- tracking_area_update_success
- tracking_area_update_reject
- create_session_request
- create_session_response
- modify_bearer_request
- modify_bearer_response
- ue_state_change

### Event Details
Event information may differ by each event, but in general events should have:

- imsi or GUTI if imsi not available
- mme id
- enodeb id
- enodeb IP
- cause (For non success events)
- APN (if have it)

### Impact
Reduce MTTR (Mean time to repair) by having proper filtering of events and having this tool accessible directly through NMS

cc: @jingtien @andreilee @iirisgao

**Comment by andreilee** [comment]
@wallyrb overall, this looks really feasible.

Some small details - we can't trivially report which IMSI is connected to which eNodeB at the moment. We do know which gateway each IMSI is connected to, though. Could you link which events `paging`, `service_request`, and `service_reject` are referring to? Those terms are not easily google-able.

**Comment by wallyrb** [comment]
thanks @andreilee ! I think eNB can hold and we can add it in future.

Below the information requested

- service_request, service reject
context:  https://www.netmanias.com/en/post/techdocs/6134/emm-lte/emm-procedure-4-service-request
Code in Github where is log this: https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c#L898

- paging
Context: Some information about paging can be found in same above document. Paging flow is triggered when user is in idle mode and there is a downlink data to the user.
Code in Github where is log this: https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c#L4620

Note: I added one more event which I missed when copied this "ue_state_change": Used to track changes of UE EMM and ECM state changes. (ie. IDLE to Connected, Registered to Unregistered). I believe AGW already log these states and push to Orc8r.

**Comment by jingtien** [comment]
Based on our walk through with Wally, I'm changing and documenting our prioritization on this issue.

**Impact**
High, fills in missing information which allows users to resolve issues faster

**Reach**
Medium, need confirmation on how often the Call Tracing feature is used

**Confidence**
Medium, yes this info is missing and they need it 

**Eng Effort**
tbd

**Comment by jingtien** [comment]
Next steps
- Spreadsheet of events with status, feasibility
- For each event, we need data available, discuss which data is valuable for the user with Wally/team
- Andrei to see if other team members have bandwidth
- Andrei to select and work on event
- Design to do deep dive on understanding call tracing and adding new events

**Comment by aswin-alexander** [comment]
Triage update: @talkhasib to dig into the process/ownership on how we add new alerts/events
