### ISSUE TITLE
Feature Request - Telrad BreezeCompact 1000 eNodeB NETCONF/YANG Model Support

### ISSUE THREAD

**Issue by GrandArcher** [magma/magma#8485]
### Describe the Feature

**Is your feature request related to a known issue? Please describe.**
I currently have 10 Telrad BreezeCompact 1000 eNodeBs that do not support TR-069 for configuration but rather NETCONF with a YANG Data Model. The model is proprietary and thus no way currently to use autoconf. I dont think its possible to maintain FCC compliance if we don't use their EPC and Management Software as it was filed with the FCC that way being that they run a CBRS domain proxy inside of BreezeView with their EPC. Also I do not know if VPLS/Bridge mode would be supported as well as this is configured through the YANG Data Model. Also it would be nice if MagmaCore could act as the CBRS Domain Proxy in order to maintain CBRS compliance with this equipment as interfaces on the eNodeBs would need to be disabled through NETCONF if the spectrum grant was not approved or revoked.
 
**Specify the applicable product use-cases**
We currently use the product for FWA but would enjoy having mobility as well. VPLS/Bridge Mode has been helpful in our deployment of FWA.

**Describe the solution you'd like**
I would like to see MagmaCore add NETCONF/YANG support as well as support for Telrad eNodeBs. I would like to see MagmaCore offer a CBRS Domain Proxy solution as well.

**Comment by krishnanken** [comment]
Is it possible to share netconf/yang details for this device? It will give us what kind of actions/tasks that can be performed on the device.  

enodebd service in AGW performs several tasks using a state machine and all operations are through TZ-069 now.
