### ISSUE TITLE
UE gets Incorrect local time

### ISSUE THREAD

**Issue by saurabhm3hra** [magma/magma#8488]
UE gets incorrect Local time information in the "EMM Information" message.

### Your Environment

- **Version:**  1.5.2
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW

### Describe the Issue
In the "EMM Information" message there is a 'Time Zone and Time - Universal Time and Local Time Zone' IE in which the Time = UTC time and Timezone is the local timezone.
AGW sends the Time as "Local Time" instead of UTC time alongwith the timezone information. Hence the UE gets incorrect time.

**To Reproduce**
EMM Information Message
![image](https://user-images.githubusercontent.com/26427970/128289808-70e9072f-720a-43b1-a5dc-09c88340f73a.png)

Time print from AGW:
![image](https://user-images.githubusercontent.com/26427970/128289837-a8f72351-23f9-463c-8017-7f72ca86d51b.png)

**Comment by saurabhm3hra** [comment]
https://github.com/magma/magma/blob/22a587e6d73d4d8076d21a91297845116fb845ea/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_send.c#L1620

Should it be changed from getting localtime to UTC time?

**Comment by wallyrb** [comment]
> https://github.com/magma/magma/blob/22a587e6d73d4d8076d21a91297845116fb845ea/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_send.c#L1620
> 
> Should it be changed from getting localtime to UTC time?

@ardzoht I believe this was fixed on 1.4 through the Rel15 upgrade. Context: T87538014
Do you know if there were some kind of regression?

**Comment by ardzoht** [comment]
@saurabhm3hra @wallyrb  This should have been fixed on v1.5 (Rel15 changes), no significant change has been going through those handlers. Having said that if the issue is still reproducible, indeed looking at the `emm_send` function looks like we should use different time retrieval for that. We can try using `gmtime` to fix this.
