### ISSUE TITLE
TASK_SGW_S8 unit test coverage

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#8502]

**Comment by ulaskozat** [comment]
@uri200 @rsarwad could you provide an update on where we are on adding unit tests for the code introduced during inbound roaming? Let's start with the libraries (e.g., ip map, state manager, etc.) in this sprint.

**Comment by uri200** [comment]
Hey @ulaskozat  we are going to start using this PR as an example 

https://github.com/magma/magma/pull/8209/files

Note we were prioritizing this issue reported by entel and create bearer request

https://github.com/magma/magma/issues/5449
https://github.com/magma/magma/issues/8609

We will re-prioritize and  include some unit test in this sprint

**Comment by ulaskozat** [comment]
@uri200 can you update the progress on this one?

**Comment by ulaskozat** [comment]
https://github.com/magma/magma/pull/8972

**Comment by uri200** [comment]
Hey @ulaskozat  we are focused on releasing Create Bearer Request this week.

 Next week we will go on with this PR and other PRs to fix issues on S6a_proxy when doing CancelLocation

**Comment by uri200** [comment]
https://github.com/magma/magma/pull/8972

**Comment by uri200** [comment]
We are already adding unit test to our PR on MME now

https://github.com/magma/magma/pull/8972
https://github.com/magma/magma/pull/9112
