### ISSUE TITLE
Auto label pull request based on paths

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#8531]
In Github actions create new pipeline to autolabel PRs.

- Use the association defined in the CODEOWNERS file(https://github.com/magma/magma/blob/master/CODEOWNERS to label the PR.

- Use the existing component label.

Wins:
Actually useful to filter by component: * labels
Unlock per-approver-teams github notifications (right now they don’t really work, but with labels they would)

**Comment by quentinDERORY** [comment]
will deprecate this job once done: https://github.com/magma/magma/blob/master/ci-scripts/JenkinsFile-autolabel-pull-request
https://jenkins.magmacore.org/job/autolabel_pull_request/

**Comment by ranj8work** [comment]
@tmdzk and @quentinDERORY 
I have made the changes on my forked repo and tested the component label getting applied automatically on pull requests. Based on the data seen in the event payload of pull request, we decided to write a workflow one for each component. I will raise a pull request once I have those changed ready in the base repo.

**Comment by ranj8work** [comment]
@tmdzk and @quentinDERORY 
I have tested scenarios with PR having changes in multiple components as well (ex: ci, agw)
The original PR which has the actual code changes in the workflow is [here](https://github.com/ranj8work/magma/pull/8).
The test PR raised to test this change is [here](https://github.com/ranj8work/magma/pull/9)
I pasted some screenshots below for test evidence:

- Below test case covers changes made in ci and agw components
![image](https://user-images.githubusercontent.com/77810379/129295403-7f3db76a-f892-4bc8-8e23-7c7c6f8e2f4e.png)

- Below test case covers changes made in ci and orc8r components. I removed the ci label manually before making the changes in the test branch. And I saw it automatically applied the ci and orc8r labels as expected. This is awesome ! :) 
![image](https://user-images.githubusercontent.com/77810379/129296349-b334a875-0509-4e48-9292-d67ee6fdbf7f.png)

**Comment by ranj8work** [comment]
Hi @quentinDERORY and @tmdzk 
After the changes are merged to the master, I can see the workflow is getting executed successfully and trying to apply the labels right:

[autolabel-pullrequests workflow action](https://github.com/magma/magma/actions/workflows/autolabel-pullrequests.yml)
[autolabel-pullrequests workflow action log](https://pipelines.actions.githubusercontent.com/qcF6GNXDClZL8OiFNquoGwIQGZUgvDVDNaKC8bHLwzb9p4DaYq/_apis/pipelines/1/runs/71354/signedlogcontent/3?urlExpires=2021-08-24T13%3A41%3A33.9173332Z&urlSigningMethod=HMACV1&urlSignature=DhZGpqAn62QJQ2YXskHYlO9fbCgbW1WVaqA1H%2FJVqOA%3D)
