### ISSUE TITLE
[feg] Magma doesn't follow diameter RFC causing AIR\AIA to fail of cause (AVP_NOT_ALLOWED) from HSS

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#8536]
### Your Environment

- **Version:** 1.6
- **Affected Component:** FEG
- **Affected Subcomponent:** s6a_proxy
- **Deployment Environment:** local docker-compose (orc8r), Vagrant (AGW), Vagrant (FEG)

### Describe the Issue

We are testing FEG connectivity with HSS during attachment procedures. Our environment as below:
- Base server ---------------- Ubuntu 18.04 -------------- contains orc8r and NMS (based on docker-compose)
- AGW VM    ------ magma gateway based on Vagrant (vagrant up magma) and magma services installed on baremetal
- FEG VM      ------ feg gateway based on vagrant (vagrant up feg) and services are running based on docker-compose
- HSS simulator --- HSS simulator installed on the same VM which contains FEG services dockers

After connecting all nodes and make sure basic messages exchanged properly, attach of physical phone was rejected.

**To Reproduce**
1. Start orc8 services (**_SUCCESS_**)
2. Start NMS services, and make the necessary configurations of Networks\APNs\RAN..... (**_SUCCESS_**)
3. Start AGW services and make sure checkin was successful (**_SUCCESS_**)
4. Start FEG services and make sure checkin was successful (**_SUCCESS_**)
5. Start HSS simulator and configure it to connect to FEG, make sure both of them are connected and exchanging watchdog messages (**_SUCCESS_**)
![image](https://user-images.githubusercontent.com/34710611/128635448-8e9fe056-5fcf-49e7-ac09-99b3e9480852.png)

Sample of DWR:
![image](https://user-images.githubusercontent.com/34710611/128635496-efc6e53a-f8a7-4b82-b6c4-5f1cce7ea42f.png)

Sample of DWA:
![image](https://user-images.githubusercontent.com/34710611/128635507-80cc470d-3d5d-4384-b610-db5e3301a5d4.png)

6. Start eNodeB based on USRB and OAI eNB (**_SUCCESS_**)
7. Make sure eNB sent S1 setup request (**_SUCCESS_**)

![image](https://user-images.githubusercontent.com/34710611/128635587-12ba8a11-c3c9-4f99-b0ab-b66371386c60.png)

S1AP-PDU:
![image](https://user-images.githubusercontent.com/34710611/128635623-7a486a8d-c3ed-4ee8-928e-837120d9a5f5.png)

Succesful outcome:
![image](https://user-images.githubusercontent.com/34710611/128635639-bcbac91a-3dd7-4472-bb55-5a0c2331bd6b.png)

8. Have physical phone with customized SIM card to attach to the network (**_FAIL_**)

![image](https://user-images.githubusercontent.com/34710611/128635668-9b8b2869-83b1-46bb-859e-d088a0fb21d8.png)

9. Check AIR\AIA between FEG and HSS:

![image](https://user-images.githubusercontent.com/34710611/128635567-7867de07-e693-4c3a-9ec7-54eb3048fd09.png)

AIR:
![image](https://user-images.githubusercontent.com/34710611/128635699-7e335d52-c88b-477c-a9c7-ea3b925cbacd.png)

AIA:
![image](https://user-images.githubusercontent.com/34710611/128635731-07d8892a-6f9f-4755-baa9-33aa7fdfeb0a.png)

10. Checking diameter error meaning and standard AIR structure, it was found that AIR shouldn't contain "Origin-State-Id AVP" (AVP Code 278) according to 3GPP TS 129 272 V15.4.0
https://www.etsi.org/deliver/etsi_ts/129200_129299/129272/16.06.00_60/ts_129272v160600p.pdf

![image](https://user-images.githubusercontent.com/34710611/128636047-8dbbb75d-3611-4076-b728-fd2404be402d.png)

**Expected behavior**
FEG should support latest RFCs

**Comment by MAAHamid** [comment]
Hello Alex, @ardzoht, can you help to validate if this is an actual bug or not (or assign someone who could). It is a blocking issue to the use case we are doing now.
Is there any workaround or an HSS which ignores this AVP that I can use?

**Comment by ardzoht** [comment]
@uri200 can you take a look at this?

**Comment by MAAHamid** [comment]
Hello @uri200 is there any preliminary feedback?

**Comment by uri200** [comment]
Thanks for reporting @MAAHamid. 

I attached a PR removing that AVP. Not sure why was there initially.

This should apply to master, 1.6 and 1.5

**Comment by MAAHamid** [comment]
Thanks @uri200 I will test 1.6 and let you know
