### ISSUE TITLE
gateway key/crt not renew reliably, orc8r connection fails/checkins fail

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#8537]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.3 - 1.6
- **Affected Component:** Orchestrator & Access Gateway
- **Affected Subcomponent:** Magmad
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

We have seen now across 1.3 - 1.6 images failures renewing gateway.key and gateway.crt. When the happens, AGW is unable to recover on its own, and loses ability to perform checkins and connection to orc8r. 

**To Reproduce**
TBD, can be triggered by temporary WAN connection loss around time of cert renewal, but not 100% that is only cause. 

**Expected behavior**
When gateway.key and gateway.crt expire, AGW needs to keep trying to renew, after a period, it should delete them proactively and restart bootstrapping on its own. 

**Screenshots**
Example state AGW ends up stuck in

```
root@FreedomFi-Gateway:/var/opt/magma/certs# ls -la
total 24
drwxr-xr-x 2 root  root  4096 Aug  6 03:11 .
drwxr-xr-x 5 root  root  4096 Aug  6 03:10 ..
-rw-r--r-- 1 root  root   875 Aug  2 22:30 gateway.crt
-rw-r--r-- 1 root  root   227 Aug  2 22:30 gateway.key
-rw-r--r-- 1 root  root     0 Aug  8 13:13 gateway.key.tmp
-rw-r--r-- 1 root  root   288 Aug  2 22:21 gw_challenge.key
-rw-r--r-- 1 magma magma 1058 Aug  2 22:28 rootCA.pem
root@FreedomFi-Gateway:/var/opt/magma/certs# ls -la
total 24
drwxr-xr-x 2 root  root  4096 Aug  6 03:11 .
drwxr-xr-x 5 root  root  4096 Aug  6 03:10 ..
-rw-r--r-- 1 root  root   875 Aug  2 22:30 gateway.crt
-rw-r--r-- 1 root  root   227 Aug  2 22:30 gateway.key
-rw-r--r-- 1 root  root     0 Aug  8 14:13 gateway.key.tmp
-rw-r--r-- 1 root  root   288 Aug  2 22:21 gw_challenge.key
-rw-r--r-- 1 magma magma 1058 Aug  2 22:28 rootCA.pem
root@FreedomFi-Gateway:/var/opt/magma/certs#
root@FreedomFi-Gateway:/var/opt/magma/certs# cat gateway.crt | openssl x509 -noout -enddate
notAfter=Aug  6 22:30:16 2021 GMT
root@FreedomFi-Gateway:/var/opt/magma/certs# date
Sun Aug  8 14:28:36 UTC 2021
root@FreedomFi-Gateway:/var/opt/magma/certs#
```

and error from magmad

```
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: INFO:root:[SyncRPC] Waiting for requests
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: ERROR:root:[SyncRPC] Failing to forward request, err: failed to connect to all addresses
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: ERROR:root:[SyncRPC] gRPC error: failed to connect to all addresses, reconnecting to cloud.
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: INFO:root:[SyncRPC] Opening stream to cloud
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: INFO:root:[SyncRPC] Waiting for requests
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: ERROR:root:[SyncRPC] Failing to forward request, err: failed to connect to all addresses
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: ERROR:root:[SyncRPC] gRPC error: failed to connect to all addresses, reconnecting to cloud.
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: INFO:root:[SyncRPC] Opening stream to cloud
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: INFO:root:[SyncRPC] Waiting for requests
Aug 08 14:10:44 FreedomFi-Gateway magmad[489]: ERROR:root:[SyncRPC] Failing to forward request, err: failed to connect to all addresses
```

**Comment by hcgatewood** [comment]
Feature work tracked in #8369

**Comment by hcgatewood** [comment]
@ardzoht do you have time to take this on this sprint?

**Comment by crbertoldo** [comment]
Complementary to the @jpad-freedomfi's magmad logs, please see below a `Received RST_STREAM with error code 0` just after restarting magmad service _without_ purposely deleting both gateway.crt and gateway.key.

```
Aug 19 12:50:13 FreedomFi-Gateway magmad[27079]: INFO:root:Stopping magmad with reason SIGTERM...
Aug 19 12:50:14 FreedomFi-Gateway systemd[1]: Stopped Magma magmad service.
Aug 19 12:50:14 FreedomFi-Gateway systemd[1]: Started Magma magmad service.
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: /usr/local/lib/python3.5/dist-packages/magma/common/cert_utils.py:16: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]:  from cryptography import x509
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: INFO:root:Starting magmad for UUID: 500677a1-dfdf-4ccf-bfff-3ecd2dc2b571
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: ERROR:root:Magmad mconfig error: service eventd is not a registered dynamic service
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: INFO:root:Starting collector...
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: INFO:root:Streamer reconnect pause: 60
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: INFO:root:Streamer timeout: 150
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: INFO:root:Starting magmad...
Aug 19 12:50:17 FreedomFi-Gateway magmad[27649]: INFO:root:Listening on address 127.0.0.1:50052
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: INFO:root:[SyncRPC] Opening stream to cloud
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: INFO:root:Waiting before checking for updates for the first time...
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: ERROR:root:Error! Streaming from the cloud failed! [StatusCode.UNKNOWN] Stream removed
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: INFO:root:[SyncRPC] Waiting for requests
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: ERROR:root:[SyncRPC] Failing to forward request, err: Received RST_STREAM with error code 0
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: ERROR:root:[SyncRPC] gRPC error: Received RST_STREAM with error code 0, reconnecting to cloud.
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: INFO:root:[SyncRPC] Opening stream to cloud
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: INFO:root:[SyncRPC] Waiting for requests
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: ERROR:root:[SyncRPC] Failing to forward request, err: Received http2 header with status: 503
Aug 19 12:50:18 FreedomFi-Gateway magmad[27649]: ERROR:root:[SyncRPC] gRPC error: Received http2 header with status: 503, reconnecting to cloud.
```

**Comment by wallyrb** [comment]
Impact:
Loose the ability to monitor/control the AGW. At that point we have to have hands in the room to fix it. Those are they kind of fixes that get very expensive in cost and customer perception.

**Comment by hcgatewood** [comment]
@jpad-freedomfi can you send logs for the AGW's bootstrapper service when this happens. Trying to understand the root cause. Doesn't have to be logs from exactly when it fails -- just logs from an AGW that has entered this unhealthy state 

My reading of the bootstrapper service so far is that it should still eventually recover. So the logs will help me determine why this isn't the case

**Comment by crbertoldo** [comment]
@hcgatewood this issue can be related to the wrong date/time in the AGW. For a unit that had NTP ports blocked upstream, it had been happening frequently. I can reproduce that, but please let me know if it makes sense.

**Comment by hcgatewood** [comment]
@crbertoldo yes this is a known issue. I'll bundle the fix into https://github.com/magma/magma/issues/8369

**Comment by hcgatewood** [comment]
Closing with https://github.com/magma/magma/issues/8369. @crbertoldo I also bundled the fix for bad NTP as well

**Comment by crbertoldo** [comment]
Thanks a lot @hcgatewood

**Comment by hcgatewood** [comment]
Hey @crbertoldo, after some discussion with the other codeowners, we've decided to revert the NTP-related part of that PR, with the idea the proper time is an expected prerequisite for proper AGW functionality

If you still desire this functionality, can you add a bit more context on the use-case. If there's a strong need + agreement with other codeowners, I'm happy to add the NTP-related part back in as a non-default AGW config 🙂

**Comment by crbertoldo** [comment]
Hi @hcgatewood actually I agree that the proper time is an expected prerequisite for proper AGW functionality, so let's keep it closed with this conclusion. The goal was to really know if it could be the root cause. Thanks a lot.
