### ISSUE TITLE
[NMS] Add bulk subscriber management workflows

### ISSUE THREAD

**Issue by jingtien** [magma/magma#8547]
### Goals
Streamline the managing subscriber workflow for the following:
- Bulk add subscribers
- Bulk update subscribers
- Bulk delete subscribers

### Resource links
[1-pager](https://fb.quip.com/Js3uAnLkiA8T)
[Latest design](https://www.figma.com/file/eCFQciASKwI6ydKsTXTafw/?node-id=127%3A35040) 
Design is ready for implementation. 

### Status
Ready for implementation

**Comment by jingtien** [comment]
**Possible starter task for Iris**
Usability issues around subscriber bulk editing workflow
- [1-pager](https://fb.quip.com/Js3uAnLkiA8T) for usability issues and suggested UX improvement
- Need to review issues with Hanna
- [Screenshots](https://www.figma.com/file/QhPXa8Xc8TbnPxD1mv3zNH/subscribers?node-id=0%3A1) provided by Hanna

**Comment by ekowtaylor** [comment]
@andreilee , @HannaFar please add story points https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/8547
