### ISSUE TITLE
[NMS] eSIM Integration

### ISSUE THREAD

**Issue by andreilee** [magma/magma#8552]
## Problem

SIM platform integration is both a commonly requested integration capability, and also necessary feature.

The use case that will be focused on here is providing LTE access on a Magma network, and allowing subscribers to have access when leaving the Magma network. One way to provide this is outbound roaming, and another way to provide this is with integration with a programmable SIM platform, such as Teal Systems. Teal provides programmable SIMs that can provide connectivity globally (or just locally if specified), and have the home network be specified as the Magma network.

Another use for this is for CBRS `<to be filled in when details are acquired>`

#### NMS UI Changes
Subscribers management will have the addition of a SIM management page. Here, API keys can be uploaded to provide Magma with API access on the SIM management platform of choice (Teal as provided example). After uploading API keys, NMS users should be able to manage users that have Magma-only managed SIM cards, or 3rd-party managed SIM cards.

#### API Changes
API changes will be required to allow upload a csv file (or similar file appropriate for bulk upload) with Auth OPC/Key data to be correlated with UICCs of the platform. As well, API related to subscriber management should change to reflect the possibility of 3rd-party managed SIM cards, and of updating API keys for interacting with these 3rd-party platforms.

#### Orc8r Changes
- New Orc8r Service uicc for SIM management
  - Orc8r-only service, in LTE directory
  - optional service
- Orc8r Subscriberdb Changes
  - subscribers are split to have SIM entries
  - subscribers can either have associated SIM EIDs from a separate managed system, or be Magma managed
  - orc8r subscriberdb should still stream the same updates to AGW

## Impact Evaluation

**Impact**
Very high impact. Network operators would like a plug and play SIM management solution to integrate directly with Magma. This can also address the need for outbound roaming.

**Reach**
Fairly high reach. Many operators using Magma would like to have a SIM management solution integration.

**Confidence**
Relatively high confidence. We've received consistent feedback and questions about SIM management integration, and also for support of outbound roaming, which this helps address or mitigate.

**Eng Effort**
Medium engineering effort on the NMS front. The workflows for this should be relatively self-contained. Likely 2-3 weeks.

**Comment by jingtien** [comment]
@andreilee Can you add your notes to this issue?

**Impact**

**Reach**

**Confidence**

**Eng Effort**
