### ISSUE TITLE
[Skipped] v1.7 release request (Sprint 1)

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#8557]

**Comment by ekowtaylor** [comment]
Timeboxed to  end of first sprint 2

**Comment by ekowtaylor** [comment]
@pshelar link dependent PRs here

**Comment by pshelar** [comment]
https://github.com/magma/magma/pull/8525
https://github.com/magma/magma/pull/8530

**Comment by ekowtaylor** [comment]
Skipping this release cycle
