### ISSUE TITLE
[FeG] add service identifier to terminate request to

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#8575]
### Your Environment

- **Version:** 1.6
- **Affected Component:** FeGs
- **Affected Subcomponent:** FeG containers services
- **Deployment Environment:**  local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue

The CCR-T from FeG to OCS is not including the service-identifier AVP inside the MSCC AVP. OCS is answering 5031 DIAMETER RATING FAILED. In CCR-I and CCR-U, this AVP Service-Identifier it is included, only is missing in the CCR-T.

**Expected behavior**
In order to expect a 2001 as result code inside the MSCC in the CCA-T, the CCR-T needs to include the service-identifier AVP along with Rating Group.

**Screenshots**
No Service-Identifier AVP inside MSCC in the CCR-T
![image](https://user-images.githubusercontent.com/79710920/128789443-7c5d555c-4262-427c-901f-8f7ed75775f2.png)

Below attached the AGW syslog, FeG session proxy log and trace FeG-DRA:
[Github_issue.zip](https://github.com/magma/magma/files/6958074/Github_issue.zip)

**Comment by uri200** [comment]
#8564 should fix this. That change has been backported to 1.5 and 1.6

**Comment by joary** [comment]
@emersonacuna , I propose you apply the change directly in your FeG code and rebuild/redeploy the FeG container-images.

This will be faster than re-deploying everything on master.
