### ISSUE TITLE
mme process crash with 600UE and 400mbps throughput over 2 hours

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#8581]
this is identified as a part of HIL automated performance testing

we have observed mme/pipelined process crashed during the test run

### Your Environment

- **Version:** >> 1.7.0-1628560576-0f98f5fe
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** mme
- **Deployment Environment:** e.g. bare-metal (AGW)

### Describe the Issue

get 600 UE (NAT based) UEs attached.
send traffic over 500K
session holding time = 30 min
run test over 2 hours.

it is observed the mme process is crashed with this backtrace

```
Aug 10 06:58:41 phy-u4 mme[42275]: Cleaning up SPGW configsLeakSanitizer:DEADLYSIGNAL
Aug 10 06:58:41 phy-u4 mme[42275]: ==42275==ERROR: LeakSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7fca19c95fc4 bp 0x7ffe8c16ce00 sp 0x7ffe8c16cdc8 T0)
Aug 10 06:58:41 phy-u4 mme[42275]: ==42275==The signal is caused by a READ memory access.
Aug 10 06:58:41 phy-u4 mme[42275]: ==42275==Hint: address points to the zero page.
Aug 10 06:58:41 phy-u4 mme[42275]:     #0 0x7fca19c95fc4 in __GI___pthread_mutex_lock ../nptl/pthread_mutex_lock.c:67
Aug 10 06:58:41 phy-u4 mme[42275]:     #1 0x55f845a68b3f in hashtable_ts_get_keys /home/vagrant/magma/lte/gateway/c/core/oai/lib/hashtable/hashtable.c:467
Aug 10 06:58:41 phy-u4 mme[42275]:     #2 0x55f845a6d80b in magma::lte::free_s1ap_state(s1ap_state_s*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp:106
Aug 10 06:58:41 phy-u4 mme[42275]:     #3 0x55f845a6db2f in magma::lte::S1apStateManager::free_state() /home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp:137
Aug 10 06:58:41 phy-u4 mme[42275]:     #4 0x55f845a6d449 in magma::lte::S1apStateManager::~S1apStateManager() /home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp:39
Aug 10 06:58:41 phy-u4 mme[42275]:     #5 0x7fca1899ba26  (/lib/x86_64-linux-gnu/libc.so.6+0x49a26)
Aug 10 06:58:41 phy-u4 mme[42275]:     #6 0x7fca1899bbdf in exit (/lib/x86_64-linux-gnu/libc.so.6+0x49bdf)
Aug 10 06:58:41 phy-u4 mme[42275]:     #7 0x7fca189790b9 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b9)
Aug 10 06:58:41 phy-u4 mme[42275]:     #8 0x55f845a5558d in _start (/usr/local/bin/mme+0x20b58d)
Aug 10 06:58:41 phy-u4 mme[42275]: LeakSanitizer can not provide additional info.
Aug 10 06:58:41 phy-u4 mme[42275]: SUMMARY: LeakSanitizer: SEGV ../nptl/pthread_mutex_lock.c:67 in __GI___pthread_mutex_lock
Aug 10 06:58:41 phy-u4 mme[42275]: ==42275==ABORTING
Aug 10 06:58:41 phy-u4 systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
```

to get detailed log you can find f rom this page: http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/performance/test_result_1.7.0-1628560576-0f98f5fe_2021-08-10%2003:12:13.html

metrics grafana page for test run : - https://grafana.spirent.fbmagma.ninja/d/9PzxTuPMz/spirent-landslide-results?orgId=3&var-agw=phy-u4&var-run_id=570&from=1628598268381&to=1628605881706

**Comment by milapjoshi** [comment]
@pshelar @ulaskozat FYI

**Comment by ardzoht** [comment]
From the logs it looks like pipelined is crashing and thus MME exits because of this, can you help me confirm this @pshelar ?
The memory leak itself on MME is being tracked on https://github.com/magma/magma/issues/3538 already, I think we should update the issue title as this is a pipelined originating issue

**Comment by pshelar** [comment]
> From the logs it looks like pipelined is crashing and thus MME exits because of this, can you help me confirm this @pshelar ?
> The memory leak itself on MME is being tracked on #3538 already, I think we should update the issue title as this is a pipelined originating issue

I see MME log as "The signal is caused by a READ memory access." Is this related to memory leak?
