### ISSUE TITLE
[NMS][Docs] Better docs for initial organization and default user on initial k8s setup

### ISSUE THREAD

**Issue by andreilee** [magma/magma#8590]
## Description

Users are reporting trouble with initial organization setup when using the NMS for the first time. It's unclear from the NMS that an organization is not setup, and that it needs to be setup through a shell script. It's also unclear how users are specific to an organization, and what role organizations play within Magma and the NMS

**Comment by ekowtaylor** [comment]
@andreilee to split up as discussed

**Comment by ekowtaylor** [comment]
PR #8750, #9079
