### ISSUE TITLE
[FeG] Insert-Subscriber-Data Request AVP Diameter in S6a

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#8606]
### Your Environment

- **Version:** 1.6
- **Affected Component:** Fed Gateway
- **Affected Subcomponent:** Fed Gateway
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue
Currently when FeG receives a diameter Command Code: 319 3GPP-Insert-Subscriber-Data, the SCTP link is shutdown by the FeG. 

![image](https://user-images.githubusercontent.com/79710920/129110528-cf257492-d4ff-4130-94e6-3e9514e358e6.png)

It is highly recommended that FeG can support this kind of diameter messages for FWA scenarios.

**Expected behavior**
Magma must be able to parse and produce the changes of features/provisioning contains in the ISDR message from the HSS.

**Additional context**
* Releases to follow are not defined, but it is recommended stable specifications (like Release 13) and be compatible with old but popular release (f.i. R 9)
[Doc 3GPP.zip](https://github.com/magma/magma/files/6971745/Doc.3GPP.zip)

* Attached trace to see an example of the message (frame # 450)
[trace1008_fegentel_04.zip](https://github.com/magma/magma/files/6971737/trace1008_fegentel_04.zip)

**Comment by uri200** [comment]
This is not supported because there is currently no use case for Magma
Can you provide a use case for this to evaluate the importance of this message?
