### ISSUE TITLE
[FeG] Cancel Location Answer with a Result Code 3002 UNABLE TO DELIVER

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#8609]
### Your Environment

- **Version:** 1.6 
- **Affected Component:**  Fed Gateway
- **Affected Subcomponent:** Fed Gateway
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue
FeG receives a Command Code: 317 3GPP-Cancel-Location from HSS. FeG answers with a result code 3002 DIAMETER_UNABLE_TO_DELIVER in frame # 703
![image](https://user-images.githubusercontent.com/79710920/129115645-3e1dd302-8d55-4171-bf2f-7ea0d776fa62.png)

Logs of the s6a_proxy shows this failure:
```
[36ms6a_proxy        |[0m I0810 20:36:20.814825       1 service_config.go:169] Successfully loaded '::control_proxy' service configs from '/etc/magma/control_proxy.yml'
[36ms6a_proxy        |[0m I0810 20:36:20.815072       1 service_config.go:180] Successfully loaded Override configs for service :control_proxy from '/var/opt/magma/configs/control_proxy.yml'
[36ms6a_proxy        |[0m I0810 20:36:20.815116       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.851575       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 3
[36ms6a_proxy        |[0m I0810 20:36:20.851659       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.874176       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 2
[36ms6a_proxy        |[0m I0810 20:36:20.874305       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.911323       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 1
[36ms6a_proxy        |[0m I0810 20:36:20.911393       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.932022       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 0
```
In syslog of the AGW cannot see any related log to this failure.

**Expected behavior**
FeG must be able to parse and answer correctly a Cancel Location Request from HSS.

**Additional context**
* Attached trace, see frame # 703 
[trace1008_fegentel_02.zip](https://github.com/magma/magma/files/6971879/trace1008_fegentel_02.zip)
* Attached the s6a_proxy logs in FeG, can see logs from line # 160 to 203 
[s6a_proxy.zip](https://github.com/magma/magma/files/6971883/s6a_proxy.zip)
* Attached syslog of AGW. Cannot find any related failure log about this issue. The time window when the message came should be between 20:34 - 20:36
[syslog.zip](https://github.com/magma/magma/files/6971885/syslog.zip)

**Comment by uri200** [comment]
this is tracked here https://github.com/magma/magma/issues/6884
