### ISSUE TITLE
[FeG] AVP 437 Requested-Service-Unit inside MSCC must be empty

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#8612]
### Your Environment

- **Version:** 1.6 
- **Affected Component:** Fed Gateway
- **Affected Subcomponent:** Fed Gateway
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue
AVP Code: 437 Requested-Service-Unit

FeG sends inside the MSCC, the AVP Code: 437 Requested-Service-Unit along with RG and SI AVP in CCR-I and CCR-U. RSU indicates in every CCR-U a decreasing quota respect to the previous one. For a better behavior of slice quota management, Magma must be able to send empty this AVP as others SPGW do. 

**Current behavior**:
In CCR-I and CCR-U, inside the AVP MSCC, it sent the AVP 437 RSU with a configurable quantity of requested quota to OCS by Gy:
![image](https://user-images.githubusercontent.com/79710920/129117505-2fcc45bd-11d3-464c-a08b-172c9bf2fdef.png)

In each CCR-U, the RSU is decreasing the requested quota respect to the previous one:
![image](https://user-images.githubusercontent.com/79710920/129117728-05ff1f36-6de3-4ca9-979b-5e152c47064f.png)

**Expected behavior**:
In order to let the Quota Manager (OCS) the one who decides how much should be the quota slice, this AVP RSU must be sent empty in CCR-I and CCR-U. 
![image](https://user-images.githubusercontent.com/79710920/129117875-4a689990-dcce-4eba-9814-c640bfc7e2c6.png)

AVP RSU must be sent but should be empty. This is in order to not cause any kind of slice quota loop and let the OCS send the proper quantity of octects.

**Additional context**
Attached a trace with the current Magma FeG bahavior (Gy TCP port 5112 and Gx TCP port 5111).
[trace1108_fegbk_01.zip](https://github.com/magma/magma/files/6971959/trace1108_fegbk_01.zip)

**Comment by uri200** [comment]
Sessiond defines the target value. In case of the pcap, sessiond target is to have 100mb grant.
 
Once the subscriber has used up 80% of the quota (around 80mb), it will trigger the update request. Then sessiond will ask for more quota, but not for a whole 100mb more, but it will take into consideration it still have around 20% left of the previous quota. So in case of the first request it asks for just 80mb more. That is why every time you see it requesting for less quota (because it still have quota left from previous grant)


Can you please do the same test but sending even more data? You should see eventually the value to stabilize. 


![image](https://user-images.githubusercontent.com/16157139/129282472-5290db19-edb9-43f3-850d-843f77c72572.png)

**Comment by uri200** [comment]
note I have done a change on sessiond.yml file to set this to 10Mb instead of 200kb (that was the default value)

here -> https://github.com/magma/magma/issues/8670

**Comment by emersonacuna** [comment]
Hi @uri200 sorry for the delayed response. Yes, as you said, we can changed the RSU in the sessiond.yml. But actually, the problem is that the expected behavior from the customer (commercial OCS Ericsson) is that RSU is sent empty. This is a normal behavior in commercial FWA and mobile massive users. 

We did a workaround with @joary  commenting line # 393, 394 & 395 here: https://github.com/magma/magma/blob/9c0a20ca99fdcff07c3128953daf623298440a36/feg/gateway/services/session_proxy/credit_control/gy/gy_client.go#L393

**Comment by uri200** [comment]
We can create a flag on FEG to disable that AVP, but I haven't found anything on 3gpp that says that has to be not sent.

**Comment by emersonacuna** [comment]
Yes, would be very helpful a flag in FeG to handle this RSU AVP (if send it as empty or with the amount of bits configured in the sessiond.yml). Note that our request is not send this AVP, but send it as empty. 
![image](https://user-images.githubusercontent.com/79710920/130100270-61a48980-d8e4-4fc0-bc18-ba14c574129b.png)

**Comment by uri200** [comment]
that PR adds the capability to disable that AVP
