### ISSUE TITLE
Outdated NMS UI information in Quick Start Guide

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#862]
### Your Environment

- **Version:** 1.0.0
- **Affected Component:** NMS
- **Affected Subcomponent:** documentation
- **Deployment Environment:** local

### Describe the Issue

The quickstart documentation includes outdate directives related to using the NMS UI.

**To Reproduce**
1. Go to [quick start guide > using the NMS UI](https://facebookincubator.github.io/magma/docs/basics/quick_start_guide#using-the-nms-ui)
1. See outdated directives

**Expected behavior**
Expected directives to produce a working NMS UI setup--instead, the mentioned directories/files were not present.

**Screenshots**
![Screen Shot 2019-11-13 at 3 30 10 PM](https://user-images.githubusercontent.com/8029544/68813539-feb6b000-062a-11ea-9967-668233f32f43.png)

**Additional context**
n/a

**Comment by xjtian** [comment]
RC here is the difference between FB-internal working setup and opensource
