### ISSUE TITLE
bettereng: Converge on a proto directory layout

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#8625]
We currently have proto files all over the repo without a single pattern.

Many of the proto files live in a flat directory in `<module>/proto`, but there are some proto files that live under corresponding services as well. (See `feg/gateway/services/aaa/protos/`, for example).

The inconsistency is not breaking anything, but is a little awkward. Would be good to come up with a plan so that all new proto files live in the correct place while we migrate the rest.

**Comment by LKreutzer** [comment]
Currently not needed
