### ISSUE TITLE
malformed packet(Authentication request ) during scale test

### ISSUE THREAD

**Issue by ganeshg87** [magma/magma#8633]
Executed the 100 UEs SUCI Reg (without PDU) scale test on the Ubuntu package and observed that re-run of the test is fails. First, run the test case is PASS, but the 2nd run is failing.

**Comment by ganeshg87** [comment]
Initial Analysis: 
----------------
 - issue was triggered AMF-UE-NGAP-ID value with 256
![image.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/b63cbf7d-bb14-4c74-ba7e-077c07f331d8)

- I have debugged registration flow there was no issue on amf & ngap. 
      - able to reproduce the issue with UERANSIM
      -  tried using UT, but encoding & decoding success for AMF-UE-NGAP-ID value with 256

 suspecting there is some issue with asn encoder, need to debug furthur
![image.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/f591f607-2494-4aad-9ee0-f11fa7e8859a)

**Comment by Lkishor123** [comment]
Related to Zenhub Task (Changes for making UE Identifier to 64 bits #8759).

**Comment by Lkishor123** [comment]
PR merged.
