### ISSUE TITLE
[Doc] Usage > NMS > Network: Include how to configure the "default subscriber profile"

### ISSUE THREAD

**Issue by joary** [magma/magma#8646]
# [Doc] Usage > NMS > Network: Include how to configure the "default subscriber profile"

## Problem

Commonly partner is not aware of the default subscriber policy of a network (policy applied when there's no other policy for a subscriber). Partner expects the subscriber to have unlimited BW since subscriber configuration starts without a profile limit. 

Magma documentation does not describe how to configure the default subscriber profile in NMS. Whithout NMS configuration AGW will enforce the values  in [subscriberdb.yml](https://github.com/magma/magma/blob/c0148b227885e0a8fdabc7ce44249c3754625a18/lte/gateway/configs/subscriberdb.yml#L42), which causes confusion with partners.

## Solution

Include in the [Network configuration page](https://docs.magmacore.org/docs/nms/network). A brief explanation on the default subscriber policy and how to configure it:

Currently it is possible to do it editing directly the network JSON configuration and including `sub_profiles.default` as in the example below: 

![image](https://user-images.githubusercontent.com/1166157/129602028-51cc5a8b-31d0-4504-bdb8-e6d6b75f42d0.png)

## Non-goals

Anything specifically excluded from the concept

**Comment by hcgatewood** [comment]
This is a feature request, rather than a proposal, so fixing the metadata and assigning @ekowtaylor
