### ISSUE TITLE
fix(mme): Incorrect S-NSSAI sST value set

### ISSUE THREAD

**Issue by Lkishor123** [magma/magma#8654]
Incorrect S-NSSAI sST value set, causing Slice not support error.
Encoded sST value change should be 0x1 but it is 0x11 right now,

**Comment by ganeshg87** [comment]
analysis:
---------
amf is setting S-NSSAI value to 1 correctly, but I see there were "Unaligned OctetString" causing failure
![image_2021_08_17T15_08_34_940Z.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/5f13b8e7-742a-4e16-bd22-3a6c0dc2b978)

**Comment by Lkishor123** [comment]
In lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers., we are hard coding (char* from_buf = "0x11");

**Comment by Lkishor123** [comment]
PR Raised: https://github.com/magma/magma/pull/8674
