### ISSUE TITLE
[agw] S1AP UE contexts are not recovered on redis after UE goes IDLE

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8657]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:**  MME
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

- S1AP UE context is created on Initial UE message, and it's generated on redis once IMSI is available on S1AP task (`Downlink NAS Transport` msg is sent)
- S1AP UE context on redis is deleted whenever local entry on S1AP task is deleted (`UE detach`, `Error IND sent by eNB`, `UE inactivity`)
- e.g. If UE goes to IDLE mode, and comes active again, the context is lost on redis as it's only generated on `Downlink NAS Transport` msg, and not on `Service Request` for Idle mode)

**To Reproduce**
- Run `lte/gateway/python/integ_tests/s1aptests/test_idle_mode_with_mme_restart.py` on S1AP integ tests

**Expected behavior**
- S1AP UE context should have an entry on redis after UE comes back to active from idle mode.

**Comment by ulaskozat** [comment]
@ardzoht are we closing this in this sprint?

**Comment by ardzoht** [comment]
Yes, I have a fix ready, I will put a PR today and should be closed for tomorrow.

**Comment by ulaskozat** [comment]
cc @ekowtaylor
