### ISSUE TITLE
[AGW] UE attach reject due to (Missing or unknown APN)

### ISSUE THREAD

**Issue by MAAHamid** [magma/magma#8660]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** mme
- **Deployment Environment:** local docker-compose (orc8r/NMS), Vagrant (AGW) baremetal, Vagrant (FEG) docker

### Describe the Issue

We are testing Federated LTE network connectivity with external HSS. Our environment as below:
- Base server ---------------- Ubuntu 18.04 -------------- contains orc8r and NMS (based on docker-compose)
- AGW VM    ------ magma gateway based on Vagrant (vagrant up magma) and magma services installed on baremetal
- FEG VM      ------ feg gateway based on vagrant (vagrant up feg) and services are running based on docker-compose
- HSS simulator --- HSS simulator installed on the same VM which contains FEG service dockers

After connecting all nodes and make sure basic messages exchanged properly, attach of physical phone was rejected.

**To Reproduce**
1. Make the necessary configurations of Networks\APNs\RAN..... (**_SUCCESS_**)
`curl -X GET "https://127.0.0.1:9443/magma/v1/lte/feg_lte_test/apns" -H  "accept: application/json"`
```
{
  "oai.ipv4": {
    "apn_configuration": {
      "ambr": {
        "max_bandwidth_dl": 1000000,
        "max_bandwidth_ul": 1000000
      },
      "qos_profile": {
        "class_id": 9,
        "preemption_capability": true,
        "preemption_vulnerability": true,
        "priority_level": 15
      }
    },
    "apn_name": "oai.ipv4"
  }
}
```
2. Start AGW services and make sure checkin was successful (**_SUCCESS_**)
3. Start FEG\HSS services and make diameter links are up and exchanging watchdog (**_SUCCESS_**)
4. Start eNodeB based on USRB and OAI eNB (**_SUCCESS_**)
5. Make the necessary config in HSS and UE of APN profiles (oai.ipv4)
5. Have physical UE with customized SIM card to attach to the network (**_FAIL_**) with cause (Missing or unknown APN)
6. Check S1AP messages between UE\eNodeB and AGW:
![image](https://user-images.githubusercontent.com/34710611/129765383-bc6149c2-4ce3-45ea-b84f-b967e617d28f.png)

7. Validate if UE requested for encrypted ESM information transfer:
![image](https://user-images.githubusercontent.com/34710611/129765771-2e39384e-33bf-4823-8ef7-9708a71b82e9.png)
![image](https://user-images.githubusercontent.com/34710611/129765843-d5ddc880-7264-4c57-85f8-c53e83bdac4c.png)

8. Check authentication and security completed:
![image](https://user-images.githubusercontent.com/34710611/129765970-088ccbd3-1872-4e82-8e75-7340a8489434.png)

9. ESM information transfer: 
![image](https://user-images.githubusercontent.com/34710611/129766040-8f4779f2-925b-4918-a68b-9bf7e5113471.png)
![image](https://user-images.githubusercontent.com/34710611/129766188-093e93dc-355f-4c67-9665-5b4fcda5910e.png)

10. Check location update answer message and subscriber data:
![image](https://user-images.githubusercontent.com/34710611/129766367-9ddd38a8-47d6-40e2-b5fa-74105cc7d4c4.png)
![image](https://user-images.githubusercontent.com/34710611/129766535-ebe5231f-f217-4073-8f20-70a7ad372bcb.png)
![image](https://user-images.githubusercontent.com/34710611/129766656-96b1edc6-ade8-42e1-87e0-5560b92571a3.png)
![image](https://user-images.githubusercontent.com/34710611/129766815-c02ab925-b2b9-4056-97d3-a980e62df601.png)

11. Check mme.log:
[208930000000009] PLMN is not configured. Selecting default mode: SPGW_SUBSCRIBER 
 **Received S6A Update Location Answer from S6A**
      Received S6a-Update Location Answer Success for ue_id = 15
            EMMCN-SAP - Received primitive EMM_CN_ULA_SUCCESS (403)
               **No suitable APN found ue_id=15)**
                     EMM-PROC  - EMM attach procedure not accepted by the network 
                           EMMAS-SAP - Received primitive EMMAS_ESTABLISH_REJ (207)
                              EMMAS-SAP - Send AS connection establish reject
                              EMMAS-SAP - Send Attach Reject message (cause=19)
[mme.log](https://github.com/magma/magma/files/7001677/mme.log)

**Expected behavior**
Attach should be accepted by MME since APN is properly configured in all parties.

**Comment by MAAHamid** [comment]
Hello @uri200 I have seen an old fixes related to APN configuration, not sure if this issue related to them or not.
Also I noticed that if the procedures doesn't have ESM information request (in the cases of OAI simulation UE), APN was accepted and this issue doesn't occur.

**Comment by uri200** [comment]
Hello, can you include session_proxy logs when you do an attach from feg using debug mode and grpc enabled please?

To do so, yo to docker-compose.yml in feg and add `-v=9` and 'MAGMA_PRINT_GRPC_PAYLOAD: 1`


```
  session_proxy:
    <<: *goservice
    environment:
      USE_GY_FOR_AUTH_ONLY: ${USE_GY_FOR_AUTH_ONLY}
      GY_SUPPORTED_VENDOR_IDS: ${GY_SUPPORTED_VENDOR_IDS}
      GY_SERVICE_CONTEXT_ID: ${GY_SERVICE_CONTEXT_ID}
      MAGMA_PRINT_GRPC_PAYLOAD: 1
    container_name: session_proxy
    command: envdir /var/opt/magma/envdir /var/opt/magma/bin/session_proxy -logtostderr=true -v=9
```

**Comment by uri200** [comment]
by the way, is the apn set with proper utf8 format on HSS? (if set)

![image](https://user-images.githubusercontent.com/16157139/129800742-be607893-0901-4047-a9b5-1bf3495e2a99.png)


In our test bed it shows proper on wireshark 


![image](https://user-images.githubusercontent.com/16157139/129802290-f11b9447-6ad0-4519-b0d9-c89f8a4073b9.png)

**Comment by MAAHamid** [comment]
Hello @uri200 I have seen an old fixes related to APN configuration, not sure if this issue related to them or not.
Also I noticed that if the procedures doesn't have ESM information request (in the cases of OAI simulation UE), APN was accepted and this issue doesn't occur.

> 
> 
> Hello, can you include session_proxy logs when you do an attach from feg using debug mode and grpc enabled please?
> 
> To do so, yo to docker-compose.yml in feg and add `-v=9` and 'MAGMA_PRINT_GRPC_PAYLOAD: 1`
> 
> ```
>   session_proxy:
>     <<: *goservice
>     environment:
>       USE_GY_FOR_AUTH_ONLY: ${USE_GY_FOR_AUTH_ONLY}
>       GY_SUPPORTED_VENDOR_IDS: ${GY_SUPPORTED_VENDOR_IDS}
>       GY_SERVICE_CONTEXT_ID: ${GY_SERVICE_CONTEXT_ID}
>       MAGMA_PRINT_GRPC_PAYLOAD: 1
>     container_name: session_proxy
>     command: envdir /var/opt/magma/envdir /var/opt/magma/bin/session_proxy -logtostderr=true -v=9
> ```

Ok, let me try this.
Should i retrieve logs using (docker-compose logs session-proxy) or copy log file from inside the docker? or any other mean

**Comment by MAAHamid** [comment]
> 
> 
> by the way, is the apn set with proper utf8 format on HSS? (if set)
> 
> ![image](https://user-images.githubusercontent.com/16157139/129800742-be607893-0901-4047-a9b5-1bf3495e2a99.png)
> 
> In our test bed it shows proper on wireshark
> 
> ![image](https://user-images.githubusercontent.com/16157139/129802290-f11b9447-6ad0-4519-b0d9-c89f8a4073b9.png)

On HSS, subscription data configured properly, I thought the display of extra characters a bad representation of wireshark, but I will need to troubleshoot it more, or maybe replace our HSS simulator. What HSS software you use in lab?

**Comment by uri200** [comment]
this capture is from a commercial HSS and I don't see weird chars.
Also i checked your string on UTF8 and it should not display those back slashed characters. Is it possible HSS simulator has different formats to send on that AVP?

![image](https://user-images.githubusercontent.com/16157139/129940894-c446598a-db59-4131-8b32-8114bae637b1.png)

**Comment by MAAHamid** [comment]
> 
> 
> this capture is from a commercial HSS and I don't see weird chars.
> Also i checked your string on UTF8 and it should not display those back slashed characters. Is it possible HSS simulator has different formats to send on that AVP?
> 
> ![image](https://user-images.githubusercontent.com/16157139/129940894-c446598a-db59-4131-8b32-8114bae637b1.png)

I agree, that is weird, I have been stuck with OAI-HSS as they have changed lots of things recently and I can't deploy it, give me sometime and I will report back some updates.
thanks for the help so far.

**Comment by MAAHamid** [comment]
@uri200 thanks a lot, it was HSS problem, using OAI_HSS make it done. UE now can Attach/connect and access internet via magma core.
