### ISSUE TITLE
Include eNB_name in s1_setup metric

### ISSUE THREAD

**Issue by joary** [magma/magma#8661]
### Your Environment (If applicable)

- **Version:** 1.5.0
- **Affected Component:** AGW Metrics
- **Affected Subcomponent:** MME, Fluentd, Grafana
- **Deployment Environment:** all

### Describe the problem

**Description**
In the scenario of an AGW with more than one eNB connected.

The `s1_setup` with type `failure` do not include the an identification from which eNB the failure come from.

Customers need to manually debug every eNB in AGW in order to rootCause the failure. 

**Additional context**
Example of failures:

![image](https://user-images.githubusercontent.com/1166157/129771645-21ca0f21-7689-43c6-9719-1364c80bbec8.png)

### Describe your idea(optional)

**Description**
Include the eNB_name (or any other eNB identification information) in the s1_setup failure event.

**Comment by aswin-alexander** [comment]
Adding to product backlog per offline request from Joary

**Comment by ekowtaylor** [comment]
@andreilee please add story points

**Comment by andreilee** [comment]
@joary Is this for events, metrics, or both? And also, would we like to include the eNB serial (or what is being referred to by the 'name')?

**Comment by ardzoht** [comment]
@andreilee eNB name from MME is different from the serial (since we use S1AP to retrieve these values), i think with including the name and eNB id should be sufficient (@joary can you help me confirming if these are sufficient?)

**Comment by ekowtaylor** [comment]
@andreilee , can this be closed?
