### ISSUE TITLE
[agw] Remove subscriberdb StreamerCallback usage

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8662]
Since #6008, subscriberdb moved to `SubscriberDBCloudClient` class to fetch the subscriberdb data from Orchestrator, and `SubscriberDBStreamerCallback` was deprecated.

There are multiple references to the deprecated class (mainly on unit tests) that can be removed as this class it's not used anymore.

Unit tests reference: `lte/gateway/python/magma/subscriberdb/tests/streamer_callback_tests.py`

**Comment by lucasege** [comment]
@ardzoht I can take this task
