### ISSUE TITLE
[v1.7][NMS] Orc8r/NMS version numbers is not showing up properly.

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#8678]
### Your Environment

- **Version:** v1.7 (public images).
- **Affected Component:** Orchestrator or NMS
- **Affected Subcomponent:** Version #s on NMS
- **Deployment Environment:**  AWS (orc8r)

### Describe the Issue

v1.7 included a way to show the version number for the orc8r on the NMS. Upgrading to the charts on NMS, it seems that the values are not being parsed properly. 

**To Reproduce**
1. Go to the ENS orc8r and login and note the following version information.
![image](https://user-images.githubusercontent.com/38921899/129978195-41195afe-6dd1-4866-bdac-130b718b15cd.png)
2. the get version info is triggering a 500 server error 
![image](https://user-images.githubusercontent.com/38921899/129978370-35b3f36f-7746-45b6-9701-046b6c7aee11.png)

**Expected behavior**
Show the correct orc8r container tag as the version number.

**Screenshots**
See above.

**Additional context**

**Comment by sudhikan** [comment]
Hey @andreilee I think I have a lead on this. 

The environment variables are not getting set properly. 

I edited the `orc8r-orchestrator` deployment manually in one of my deployments and set `VERSION_TAG` and `HELM_VERSION_TAG` and the API call comes back successfully. 

The env vars are not making it into the orc8r-orchestrator pod. I was playing around with this a bit... i'll try to raise a PR to this if I can figure out what needs to get plumbed where. At a cursory glance, it seems like the helm template for `orcchestrator-deployment` doesn't have the placeholder for the env variables... but I am not 100% sure on that yet. 

For the NMS version, I see the API endpoint going to `https://<tenant>.domain.com/version`. Is this correct?

**Comment by ShubhamTatvamasi** [comment]
When we are setting the variable on this helm chart it's still not working?
https://github.com/magma/magma/blob/master/orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl#L58

**Comment by sudhikan** [comment]
@ShubhamTatvamasi yea the problem is while it's set in the values file, it doesn't actually correspond to anything on the helm template files. 

So I've been tinkering around with modifying `orclib/templates/_container.yaml` similar to all other env variables. What I am not understanding is why two additional env vars are not populating in the deployment spec.

**Comment by ShubhamTatvamasi** [comment]
Just add the following in the `_container.yaml`, it will solve the issue.
```
  - name: HELM_VERSION_TAG
    value: {{ .Chart.Version }}
  - name: VERSION_TAG
    value: {{ .Values.controller.image.tag }}
```

**Comment by sudhikan** [comment]
yep! that's what I was modifying :-) 

arghh keep forgetting that we have a separate helm repo. Never thought twice about why those changes weren't reflecting in the deployment. Thanks @ShubhamTatvamasi for the second pair of eyes :-)
