### ISSUE TITLE
TeraVM Regression | Include Service Identifier as part of MSCC in Gy CCR

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#8683]
"Service Identifier” (SID) along with "Rating group”(RG) on Gy CCR under grouped AVP MSCC (multi service credit control) combination is significant, commercial OCS configs generally expects both these values,  generally these SID and RG AVPs are part of a PCC rule (Static or Dynamic) and Gy-CCR_I must have these AVPs under MSCC inorder for OCS to provided right Volume Grants, SID AVP outside of MSCC in Gy CCR message is no more valid for any charging activities hence 3Gpp striked out.

I see in our Gx rules SID+RG is included in rule but on Gy CCR only RG is going in MSCC which need to be changed to include both RG and SID in MSCC. TeraVM OCS function should consider/check both RG+SID values to provide the Volume grants.

GY-CCR , Has only RG, missing to cascade & send SID received in PCC rule on Gx. Need to include RG & SID under MSCC Volume Request, will open GH issue for this.

<img width="925" alt="Screen Shot 2021-08-18 at 10 43 28 PM" src="https://user-images.githubusercontent.com/70725754/130015748-0fd11e98-f358-44ef-b591-b98b076058fb.png">

Gx Dynamic PCC rule has both Rating Group and Service Identifier. Which looks good.

<img width="825" alt="Screen Shot 2021-08-18 at 10 42 51 PM" src="https://user-images.githubusercontent.com/70725754/130015801-60a125b6-dbec-49f6-a6ab-54b54a98f3bc.png">

PCAP enclosed

[gx_gy_combined_02_210804_062054-1.pcapng.zip](https://github.com/magma/magma/files/7012087/gx_gy_combined_02_210804_062054-1.pcapng.zip)

**Comment by uri200** [comment]
this is completed here 
https://github.com/magma/magma/pull/8659
