### ISSUE TITLE
proposal of subscriberDB ext - UI pages 

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#8686]
Study and Proposal for SubscriberDB Ext functionality support in 5G.

**Comment by Abhishek-R15** [comment]
https://docs.google.com/document/d/1V7wK5OxVxv9fmDiF1_6IbCXr5hnyLDT0/edit

**Comment by Abhishek-R15** [comment]
Internal Review is completed.

**Comment by anusha-konda** [comment]
Raised proposal 8904 for review. All the NMS changes are part of PR9165. To work on proposal/code comments related to NMS, 8787 zenhub task will be used for tracking.
