### ISSUE TITLE
magma V1.0.0 fail to install AGW with the reason “ magma : Depends: python3-psutil (>= 5.6.3) but it is not going to be installed”

### ISSUE THREAD

**Issue by chenhao5651** [magma/magma#869]
### Your Environment
Debian 9.8
Linux version 4.9.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.168-1 (2019-04-12)
- **Version:** magma 1.0.0
- **Affected Component:*AGW* Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:*AGW* Orchestrator pod/service or AGW service
- **Deployment Environment:*bare-metal* e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
I Refer to the https://facebookincubator.github.io/magma/docs/lte/setup_deb and install AGW（orc8r is not installed），it fails with ：
TASK [ovs_deploy : Installing magma.] 
fatal: [10.0.2.1]: FAILED! => {"cache_update_time": 1573720532, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'magma'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n magma : Depends: python3-psutil (>= 5.6.3) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " magma : Depends: python3-psutil (>= 5.6.3) but it is not going to be installed"]}

When I use apt-get install python3-psutil ，the version is python3-psutil (5.2.2)，and it does not meet the magma request.
When I use pip3 install psutil ,the version is psutil 5.6.5 ,and it dose not work,so How can I install the python3-psutil?

 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ardzoht** [comment]
Hey, we recently fixed the installation of magma package, can you give this a shot again and let me know if it works? Thanks!

**Comment by chenhao5651** [comment]
> Hey, we recently fixed the installation of magma package, can you give this a shot again and let me know if it works? Thanks!

It works! Thank you very much.
