### ISSUE TITLE
Orc8r Code changes (SubDB Extensions) - Updation to Swagger API doc, callback functions, subscriberDB service.

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#8691]
This task points to Orc8r code changes.
Updation to Swagger API doc, 
Updation of API callback functions(create, get, update) to make new attr as part of config entities.
Verification of swagger UI. 
Updation of DB field changes if any.
Addition of Unittestcases

**Comment by Abhishek-R15** [comment]
Draft PR has been submitted
https://github.com/magma/magma/pull/9161

**Comment by Abhishek-R15** [comment]
Comments are addressed and requested for re-review.

**Comment by Abhishek-R15** [comment]
Merged on 29th-Oct
