### ISSUE TITLE
bogus sync failure log entry in MME when any auth_proc fails

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#8696]
### Your Environment

- **Version:** mast back to at least 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

MME authentication procedure has a misleading error log entry anytime the authentication procedure fails. I results in mme log show sync failure even when sync failure is not cause code for authentication procedure fail. 

see line
https://github.com/magma/magma/blob/6138a36495e5985a33cafb3ed9335ea894b7c6ce/lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c#L631 

this log entry is called anytime that auth_proc if is entered before the switch/case checks which cause code it is. 

perhaps wrong reference?

**Comment by lionelgo** [comment]
The R10_5_4_2_4__3_BRIEF is not a good brief of R10_5_4_2_4__3 in magma/lte/gateway/c/core/oai/include/3gpp_requirements_24.301.h, should be modified.
