### ISSUE TITLE
Make cwag workflow required for PR merge on master

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#8699]
GHA does not manage well required checks on jobs that does not trigger.
Plan:

- Skip cwag tests if files does not match the path filter.
- Remove the existing path filters on the gha workflow
- Mark the cwag jobs to be required for PRs in github

**Comment by ranj8work** [comment]
@quentinDERORY and @tmdzk 
I made the changes and the [PR](https://github.com/magma/magma/pull/9062) is raised.

**Comment by quentinDERORY** [comment]
Done for github actions pipeline:
- cwag
- feg
- cloud
- agw
- cwf
And marked cwag gha as required on PR to master
