### ISSUE TITLE
User APN-AMBR different from PCRF instructs in the CCA-I

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#8700]
### Your Environment

- **Version:** 1.6
- **Affected Component:** Fed Gateway
- **Affected Subcomponent:** Fed Gateway
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue

* Magma receives ULA with AMBR (inside AVP Subscription Data - AVP APN-Configuration-Profile) for both Max-Requested-BW UL and DL: 10Mb
![image](https://user-images.githubusercontent.com/79710920/130117107-86c1dad2-0473-47ef-a231-6abcf8aeff31.png)

* In the CCR-I to PCRF from FeG, the value of AVP APN-Aggregate-Max-Bitrate for both DL and UL is 10Mb/s
![image](https://user-images.githubusercontent.com/79710920/130117408-58ac7bad-8752-492d-bc0b-c9ffbde8df4f.png)

*  From PCRF in the CCR-A, FeG receives AVPs APN-Aggregate-Max-Bitrate (inside AVP QoS-Information) for UL and DL with 12Mb and 24Mb, respectively
![image](https://user-images.githubusercontent.com/79710920/130117444-6685ffb6-a6f5-4b6b-8512-8ff6747c4320.png)

* Then, we do a speedtest and the results never go beyond 10Mb/s for both UL and DL
![photo2](https://user-images.githubusercontent.com/79710920/130119176-767688d3-4317-4fff-a7d6-933503c8acdb.PNG)

**Expected behavior**
The expected speed results must be 12Mb/s for UL and 24Mb/s for DL as the PCRF instructed. Magma is not setting up the APN-AMBR that PCRF instructs in the CCA-I, it is only considering the provisioned AMBR in the HSS

**Additional context**
I am attaching the FeG trace (S6a SCTP port 5002, Gx TCP port 5111), sessiond and syslog AGW logs
[2. QoS.zip](https://github.com/magma/magma/files/7016734/2.QoS.zip)

**Comment by uri200** [comment]
Per sessiond logs we keep AMBR received from ULA by design

```
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:           qos_info {
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:             apn_ambr_dl: 10000000
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:             apn_ambr_ul: 10000000
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:             priority_level: 1
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:             preemption_capability: 1
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:             preemption_vulnerability: 1
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:             qos_class_id: 9
Aug 18 16:30:21 agw-magma-backup sessiond[2596684]:           }

```

http://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/LocalEnforcer.cpp#L1802-L1802
