### ISSUE TITLE
[NMS] Remove extra configuration options that are not relevant anymore.

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#8705]
### Your Environment (If applicable)

- **Version:** 1.4 and newer.
- **Affected Component:**  NMS
- **Affected Subcomponent:** NMS `master` organization.
- **Deployment Environment:** AWS (orc8r)

### Describe the problem

**Description**
* First time configuration for the NMS requires users to create a new organization and add a user to it. However, in the process of doing this, the user is presented with `tabs` that are not relevant to the Magma project anymore. Furthermore, the `fb-test` org has accessible tabs that can't be unchecked and selected only to add the `nms` tab. This requires the user to potentially delete the org and recreate it. 
* `Features` tab has many features that are not relevant to the project.
* Metrics tab is not populating with meaningful output. See a 5xx, 4xx, 3xx error code respectively. 

**Additional context**
Add any other context or screenshots about the problem here. You can also provide links to relevant resources.

### Describe your idea(optional)

**Description**
* Remove tabs `Inventory`, `Work Orders`, `Automation`, `Hub` from the drop down. Default all organizations to the `NMS` tab and remove drop down.
* Remove `fb-test` as a valid first organization and make `magma-test` as the first default organization. 
* Rename `master` to `main` or `admin`. 
* Remove features (in `features` tab ) not related to the `NMS` tab. 
* Add support for API metrics (or deprecate with an splash message that this is WIP). 

**Additional context**
Add any other context or screenshots about your solution.

**Desired timelines**
Share any information about timeline expectations.

**Comment by andreilee** [comment]
To be completed as part of NMS 'Host Portal Onboarding' project, by @HannaFar
