### ISSUE TITLE
Magma- SA TeraVM | AGW sends unknown "Transport layer Addr" in PDU session setup Request 

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#8708]
AGW sends unknown "Transport layer Addr (49.48.46.50)" in PDU session setup Request , This address is not the eth1 or any interface IP of AGW, Need to investigate the source of this IP selection.

Here is the snap of the traces

<img width="1729" alt="Screen Shot 2021-08-20 at 5 27 06 PM" src="https://user-images.githubusercontent.com/70725754/130305051-54defc38-13fe-40ff-871a-d102d5d74c76.png">

Enclosed the pcap

[SA_01_02_03_04_Hyper_Suci_210818_050204-1.pcapng.zip](https://github.com/magma/magma/files/7024577/SA_01_02_03_04_Hyper_Suci_210818_050204-1.pcapng.zip)

**Comment by ulaskozat** [comment]
@panyogesh can you check this with @prabinakpattnaik ?

**Comment by panyogesh** [comment]
> @panyogesh can you check this with @prabinakpattnaik ?

@ulaskozat : #8583 should resolve the issue. Can we review the same.

**Comment by ulaskozat** [comment]
@panyogesh thanks. also pinged @uri200 for approval.
