### ISSUE TITLE
[bug] Failed to send Modify Bearer Request for SPGW-C IP for a second APN.

### ISSUE THREAD

**Issue by CaioWalker** [magma/magma#8725]
### My Environment

- **Docker Version:** 20.10.7, build f0df350
- **Compose Version:** 1.29.2, build 5becea4c
- **openair-epc-fed version:** `afeb9d22770864fed00242544702e22258db637a` (tag: 2021.w23)
- **oai-hss version:** (tag: 2021.w29)
- **oai-spgwc:** (tag: 2021.w29)
- **oai-spgwu-tiny:** (tag: 2021.w29)
- **Magma version:** `37a50f0714561a18ab31f9db1236896615a5ad7d`
- **Deployment Environment:** Intel(R) Xeon(R) Gold 5215 , hyperthreading disabled, bare-metal
- **Kernel:** 4.15.0-118-lowlatency
- **Core and RAN at same machine**
- **Affected Component: Access Gateway (MME)**

### Describe the Issue

After the device performs the IMS APN request, the network starts the activate defalult EPC bearer process and obtains a positive response from the device, however the MME ends up breaking, returning an critical error indicating timeout in the S11 interface communication. The observed timeout may be due to the peer_ip information incorrectly persisted in the MME (0.0.0.0), which even receiving the IP referring to SPGW-C (192.168.61.132) assembles the S11 modify bearer req and tries to send to the wrong IP (0.0.0.0).

**To Reproduce**

1. git clone [open-air-repo](https://github.com/OPENAIRINTERFACE/openair-epc-fed.git)
2. Add the elements of the environment to the APN IMS (HSS, SPGW-C).
3. docker-compose up -d db_init
4. docker-compose up -d oai_spgwu
5. Start enb
6. Disable the device's airplane mode with default APNs and ims configured.

**Expected behavior**
After receiving the Create Session Response message from SPGW-C, Magma MME should send the Modify Bearer Request message to the SPGW-C IP (192.168.61.132) and receive the Modify Bearer Response message from SPGW-C.

**Additional context**

Here you can find the MME and SPGWC execution logs and pcaps
[logs.pcaps.zip](https://github.com/magma/magma/files/7034610/logs.pcaps.zip)

**Comment by lionelgo** [comment]
Looking at pcap may be you face the same issues as us, your UE seems not happy with EMM_INFO.
You may try also to increase T3402 (12 or 24 for example)

**Comment by hygorjardim** [comment]
Thanks for your reply @lionelgo, I believe I am also facing the same problem.

I'm not very familiar with "T3402" but as far as I understand I should adjust from the UE side, correct?

**Comment by hygorjardim** [comment]
I found the configuration file that modifies these times, thanks!

**Comment by CaioWalker** [comment]
Hi, thanks for the reply.

When trying to increment T3402 to 12 or 24 we got the same results as we can see in the [logs.pcaps.zip](https://github.com/magma/magma/files/7042999/logs.pcaps.zip) logs.

The problem can be seen at the end of the MME log as follows:

```
1502    RECEIVED GTPV2c  response message of type 33, length 116 and seqNum 803.
1526    Not removing the initial request transaction for message type 33, seqNo 803 (altough remove flag set). 
0132    Created message 0x627000003800!
1209    Received IE 2 with instance 0 of length 2 in msg-type 33!
1209    Received IE 87 with instance 0 of length 9 in msg-type 33!
1209    Received IE 79 with instance 0 of length 5 in msg-type 33!
1209    Received IE 72 with instance 0 of length 8 in msg-type 33!
1287    Unexpected IE 72 with instance 0 of length 8 received in msg 33!
1209    Received IE 78 with instance 0 of length 32 in msg-type 33!
1209    Received IE 93 with instance 0 of length 24 in msg-type 33!
0213    Received IE 2 of length 2!
0120    	- Cause value 16
0213    Received IE 87 of length 9!
0200    	- F-TEID type 11
0205    	- TEID/GRE    00000001
0218    	- IPv4 addr   192.168.61.132
0213    Received IE 79 of length 5!
0246    	- PAA type  1
0279    	- IPv4 addr 12.0.0.2
0213    Received IE 72 of length 8!
0388    	- AMBR UL 10000000
0389    	- AMBR DL 10000000
0213    Received IE 78 of length 32!
0213    Received IE 93 of length 24!
0345    	- EBI 6
0120    	- Cause value 16
0200    	- F-TEID type 1
0205    	- TEID/GRE    00000002
0218    	- IPv4 addr   192.168.61.133
0142    Purging message 0x627000003800!
0147    Message pool 0x627000003800! Next element (nil) !
1573    Removing the initial request transaction for message type 33, seqNo 803 in conclusion (not late response). 
2441    Stopping active timer 0x6010000060f0 for info 0x0x60700001a9b0!
2453    Stopped active timer 0x6010000060f0 for info 0x0x60700001a9b0!
0142    Purging message 0x627000000000!
0147    Message pool 0x627000000000! Next element 0x627000003800 !
0429    Purging  transaction 0x60c00004bfc0 with seqNum 2051. (before) Head (nil), Next (nil). 
0436    After purging  transaction 0x60c00004bfc0, Head 0x60c00004bfc0, Next (nil)
0094    Inside get_state with read_from_db 0
0084    MME APP ZMQ latency
1078   [208920100001108] Received S11_CREATE_SESSION_RESPONSE from S+P-GW for ue id 1 with MME S11 teid = 1, cause = 16
                                        .
                                        .
                                        .

 0142    ESM-SAP   - Received primitive ESM_UNITDATA_IND (20)
0345    ESM-SAP   - Decoding ESM Message 
0748    ESM-SAP   - Received Activate Default EPS Bearer Context Accept message (ue_id=1, pti=0, ebi=6)
0269    ESM-PROC  - Default EPS bearer context activation accepted by the UE (ue_id=1, ebi=6)
0393    ESM-FSM   - Stop retransmission timer 105621835762032 1
0536    ESM-FSM   - Status of EPS bearer context 6 changed
4529   [208920100001108] Sending S11 modify bearer req message to SPGW task for ue_id 1
0823    ESM-PROC  - Sending Modify bearer req ue_id=1ebi (6), enb_fteid_s1u.teid 8403d588
0456    ESM-SAP   - ESM Message type = ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT(0xc2)(ESM Cause = -1) for (ue_id = 1)
0092    Created message 0x627000000000!
2064    Received initial request from ulp
0255    Created not trx without seqNum as transaction 0x60c00004bfc0. Head (nil), Next (nil)
0269    Created transaction 0x60c00004bfc0
0777    peer IP information 0.0.0.0
2327    Started timer 0x601000006120 for info 0x0x60700001a9b0!
0487    Unknown address type
0129    Assertion (task_zmq_ctx_p->push_socks[destination_task_id]) failed! Sending to task without push socket. id
```
Observing the MME pcap with the GTPv2 filter, we identified that it does not send the modify bearer req to SPGW-C, even though the bearer of the second APN was successfully created.

![Screenshot from 2021-08-24 22-43-02](https://user-images.githubusercontent.com/19229977/130712541-760b43ba-b963-499c-a0d4-4e466cfd4230.png)

I believe that there is a problem with the persistence of the SPGW-C address that corresponds to the second APN after receiving the positive answer for the bearer creation, because the peer IP information points to 0.0.0.0 during the modify bearer req.

Would you have any direction for solving this problem @lionelgo?

Any comments will be greatly appreciated.

**Comment by lionelgo** [comment]
> Thanks for your reply @lionelgo, I believe I am also facing the same problem.
> 
> I'm not very familiar with "T3402" but as far as I understand I should adjust from the UE side, correct?

yes

**Comment by lionelgo** [comment]
> Would you have any direction for solving this problem @lionelgo?
> 
> Any comments will be greatly appreciated.

I have the same problem on my side with our own tests, I investigate on this:
The problem comes from the SPGW IP address not filled in the second PDN context, so that in send_modify_bearer_req() called by esm_recv_activate_default_eps_bearer_context_accept(), we use pdn_context_p->s_gw_address_s11_s4.address that is zero.
This peer IP address should/could be filled during Create Session Request.

**Comment by lionelgo** [comment]
Get it working now.
You can find fixes in this branch: https://github.com/lionelgo/magma/tree/fix-s11-multi-pdn-mbr-peer-spgw-ip
just rebased with master.

**Comment by lionelgo** [comment]
I will make a PR when successfully tested with magma s1aptester

**Comment by hygorjardim** [comment]
Thanks @lionelgo, I will test and post the results as soon as possible.

**Comment by hygorjardim** [comment]
@lionelgo now will any APN name other than "oai.ipv4" be suffixed with (apn_name)+mnc(code).mcc(code).gprs? For example, `internet` generates an `internet.mnc092.mcc208.gprs` FQDN.

**Comment by lionelgo** [comment]
I imagine this is because oai.ipv4 has a dot, internet has no dot. I have to check.

**Comment by CaioWalker** [comment]
Hi @lionelgo, thanks for the reply.

Apparently the change in the code made it possible for the MME to send the Modify bearer req to the corresponding SPGW-C as we can see in [logs.pcaps.zip](https://github.com/magma/magma/files/7067734/logs.pcaps.zip).

In order to perform the tests, we placed the address ranges of both APNs within the same address range configured in the SPGW-U (APN1 12.1.1.2 - 12.1.1.126 and APN2 12.1.1.129 - 12.1.1.254), since it points that only one address range is allowed in your conf file.

```
PDN_NETWORK_LIST = (
{NETWORK_IPV4 = "12.1.1.0/24";} # 1 ITEM SUPPORTED ONLY
);
```

Is this way of using the address ranges correct?

Any comments will be greatly appreciated.

**Comment by lionelgo** [comment]
Just an update, it passes all s1aptester integ_tests

**Comment by lionelgo** [comment]
> Hi @lionelgo, thanks for the reply.
> 
> Apparently the change in the code made it possible for the MME to send the Modify bearer req to the corresponding SPGW-C as we can see in [logs.pcaps.zip](https://github.com/magma/magma/files/7067734/logs.pcaps.zip).
> 
> In order to perform the tests, we placed the address ranges of both APNs within the same address range configured in the SPGW-U (APN1 12.1.1.2 - 12.1.1.126 and APN2 12.1.1.129 - 12.1.1.254), since it points that only one address range is allowed in your conf file.
> 
> ```
> PDN_NETWORK_LIST = (
> {NETWORK_IPV4 = "12.1.1.0/24";} # 1 ITEM SUPPORTED ONLY
> );
> ```
> 
> Is this way of using the address ranges correct?
> 
> Any comments will be greatly appreciated.

I nether did that, I use 2 spgwu, each for one APN, but what you propose should work.

**Comment by hygorjardim** [comment]
> Get it working now.
> You can find fixes in this branch: https://github.com/lionelgo/magma/tree/fix-s11-multi-pdn-mbr-peer-spgw-ip
> just rebased with master.

Thanks again @lionelgo, as @CaioWalker said we were successful using the branch you mentioned.


> > Is this way of using the address ranges correct?
> > Any comments will be greatly appreciated.
> 
> I nether did that, I use 2 spgwu, each for one APN, but what you propose should work.

This possibility went unnoticed, in this case I should just indicate the FDQN of the second spgwu in the CUPS section of spgw_c.json?

Something similar to this.

``` json
    "cups" : {
        "association_retry_period_ms" : 15000,
        "association_heartbeat_period_ms" : 2000,
        "feature_overload_control" : false,
        "feature_load_control" : false,
        "up_nodes_selection" : [
            { "mcc" : "208", "mnc" : "92", "tac" : 1, "apn_ni" : "oai.ipv4", "pdn_idx" : 0, "id" : "gw1.spgw.node.epc.mnc92.mcc208.openairinterface.org" },
            { "mcc" : "208", "mnc" : "92", "tac" : 1, "apn_ni" : "ims.mnc092.mcc208.gprs", "pdn_idx" : 1, "id" : "gw2.spgw.node.epc.mnc92.mcc208.openairinterface.org" }
        ]
    },
```

Once again, thanks for your attention.

**Comment by hygorjardim** [comment]
I'll add the pull request here just so we can follow up.

- https://github.com/magma/magma/pull/8864

**Comment by ekowtaylor** [comment]
PR merged
