### ISSUE TITLE
PTI Mismatch 5G Attach

### ISSUE THREAD

**Issue by shanku9** [magma/magma#8742]
PTI Mismatch observed in 5G NAS PDU ![Screen Shot 2021-08-24 at 12.12.49 PM.png](https://images.zenhubusercontent.com/5f86188e2de2a44cd6987ea4/5a8ea29e-3a54-4d2b-8411-3d349f9563be)

**Comment by shanku9** [comment]
Downlink > 1
Uplink > 78![Screen Shot 2021-08-24 at 12.24.11 PM.png](https://images.zenhubusercontent.com/5f86188e2de2a44cd6987ea4/b3e3e081-86c6-4f54-89f3-c36e173112a4)

**Comment by VinayKumar1591** [comment]
fixed in latest build
