### ISSUE TITLE
[FEG] Host-IP-Address AVP in CER is hardcoded to 127.0.0.1

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#8752]
According to Diameter RFC https://datatracker.ietf.org/doc/html/rfc6733 
the AVP Host-IP-Address in CER should be set to the IP address which will be used to send diameter messages. As of now its  hardcoded to localhost ip  address 127.0.0.1.
During a recent interop with a 3rdParty PCRF, this  caused an issue as the PCRF was expecting the IP address of the transport endpoint sending CER. 

After we changed the Host-IP-Address AVP to contain valid IP address, the  CER-CEA exchange was successful. (Please see screenshots
<img width="1666" alt="Screen Shot 2021-08-25 at 10 27 00 AM" src="https://user-images.githubusercontent.com/48265190/130716471-78a86a62-45d2-47c1-b1b9-528918931c92.png">
) 

### Your Environment

AGW-Feg. Orc8r in AWS. 
Operator PCRF from Huawei.  
<img width="548" alt="Screen Shot 2021-08-23 at 3 55 53 PM" src="https://user-images.githubusercontent.com/48265190/130716075-41c790a3-1804-4ac0-86f4-124dd4094b2e.png">

**Comment by MAAHamid** [comment]
Faced same issue while integrating with OCS

**Comment by uri200** [comment]
this parameter is configured here:  adding the IP aaddressof your client to the locall_address on your diameter server configuration


![image](https://user-images.githubusercontent.com/16157139/150453926-de89c389-fd1a-4a89-9d38-82449aac8c2c.png)

From https://github.com/magma/magma/issues/10001


![image](https://user-images.githubusercontent.com/16157139/150454099-78ae49d0-8faf-4c77-8de3-3ddb6e38a847.png)

**Comment by uri200** [comment]
Hey @sourabh-nanoti  This Pr https://github.com/magma/magma/pull/11252 may fix the issue
