### ISSUE TITLE
Magma SA-TeraVM | Inclusion of DNS IP addresses on Extended PCO in DL 5G-NAS 

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#8757]
Inclusion of DNS IP addresses on Protocol Configuration in 5G-NAS 

<img width="1733" alt="Screen Shot 2021-08-24 at 9 37 03 PM" src="https://user-images.githubusercontent.com/70725754/130727336-7cfd40a5-8fb8-4484-95f0-21cdada48c40.png">

Currently UE on PDU Session Establishment message requesting "DNS Addresses" in 5G NAS I.E "PPP-IP Control Protocol Code: Configuration Request" but AMF not returning the "DNS Addresses" with "Configuration Ack", infact the entire "PPP-IP Control Protocol" I.E list is missing / not implemented yet in AMF on PDU Session establish Accept.

**Comment by ekowtaylor** [comment]
This looks a lot like this other issue: https://github.com/magma/magma/issues/8782. Should they be consolidated?

**Comment by panyogesh** [comment]
#8782 is closed.
Review request for this feature is tracked as part of #8849.

**Comment by panyogesh** [comment]
Code committed as part of #8849 and was tested on SIT. Closing the task.
