### ISSUE TITLE
Changes for making UE Identifier to 64 bits

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#8759]
Changing the ueid from 32 bits to 40 bits as per the spec. Data structure for holding the identifier needs to be made to 64 bits. This will also require unit and function testing with Simulators.

**Comment by Lkishor123** [comment]
PR raised: https://github.com/magma/magma/pull/8796

**Comment by Lkishor123** [comment]
TeraVM testing in progress.

**Comment by Lkishor123** [comment]
PR merged.
