### ISSUE TITLE
[NMS] Collect AGW CLI tools into NMS

### ISSUE THREAD

**Issue by andreilee** [magma/magma#8762]
### Background
The Magma AGW has a number of CLI tools that are critical for monitoring, setup, and debug. To access these tools and use them reliably, requires both SSH access to the AGW, often requires explicit knowledge of these tools, and even some usage info that is available mainly to the developers of these tools.

This represents a large usability gap, as users are not able to use the tools that we have built.

### Task
- Allow NMS access to all AGW CLI tools
- Provide an easy user interface for all these CLI tools
- Provide good feature discoverability of these CLI tools

**Comment by jingtien** [comment]
Merging this task with [#8465](https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/8465)
