### ISSUE TITLE
Fix non-exhaustive HTTP error reporting

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#8763]
Current HTTP (obsidian) errors are reported via the HttpError type. This is an idiosyncratic solution, which also doesn't capture all the possible errors. Instead, we should use middleware to capture and report 100% of the HTTP errors

Deliverables

1. Remove HttpError from the codebase. Instead, either use echo.HTTPError directly, or use/create a convenience function to convert grpc errors to echo.HTTPError
2. Add http middleware to log/report metrics on http codes -- logging decision should follow the existing logic in HttpError type

**Comment by lucasege** [comment]
I can take this issue if it's still available. The deliverables seem simple, it's just a question of how to package them in an idiomatic fashion.

Will post some notes on a solution tomorrow unless I'm directed to another issue.

**Comment by lucasege** [comment]
Looked into this, it actually would appear that #9767 resolved this issue already.

Please let me know @hcgatewood if that is not the case, otherwise I would suggest closing this issue

**Comment by hcgatewood** [comment]
Hey @lucasege correct it is resolved, thanks for the catch 🙂 

Another great starter task, if you're interested, is https://github.com/magma/magma/issues/8748

Happy to chat about it if desired!
