### ISSUE TITLE
[Orc8r] Incorrect authorisation of the client with resource specific cert.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#8764]
### Your Environment

- **Version:** 1.5 , 1.6
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** FEG / FEG LTE
- **Deployment Environment:** AWS 

### Describe the Issue

As per the documentation  of ```/var/opt/magma/bin/accessc add-existing``` we can  register client certificate for specific set of resources, for example :
```/var/opt/magma/bin/accessc add-existing -n some_lte:RW -n some_feg:RW  -n some_feg_lte:RW -cert some_cert.pem some_operator```
When we try to use newly registered cert we will have
FOR LTE:
```
curl -X GET \
    -H "accept: application/json" \
    --cacert rootCA.pem \
    --key ./some_cert.key.pem \
    --cert ./some_cert.pem  \
    /magma/v1/lte/some_lte/gateways"
 HTTP 200
 { ...some data...}  

curl -X GET \
    -H "accept: application/json" \
    --cacert rootCA.pem \
    --key ./some_cert.key.pem \
    --cert ./some_cert.pem  \
    /magma/v1/lte/some_OTHER_lte/gateways"
 HTTP 403
{"message":"access denied (rpc error: code = PermissionDenied desc = Unsatisfied permissions, need: b00000001, got: b00000000 for Id_Network_some_OTHER_lte)"} 
```

FOR FEG_LTE:
```
curl -X GET \
    -H "accept: application/json" \
    --cacert rootCA.pem \
    --key ./some_cert.key.pem \
    --cert ./some_cert.pem  \
    /magma/v1/feg_lte/some_feg_lte/federation"
 HTTP 403
{"message":"access denied (rpc error: code = PermissionDenied desc = Unsatisfied permissions, need: b00000001, got: b00000000 for Id_Wildcard_Network)"}
```

FOR FEG:
```
curl -X GET \
    -H "accept: application/json" \
    --cacert rootCA.pem \
    --key ./some_cert.key.pem \
    --cert ./some_cert.pem  \
    /magma/v1/feg/some_feg/federation"
 HTTP 403
{"message":"access denied (rpc error: code = PermissionDenied desc = Unsatisfied permissions, need: b00000001, got: b00000000 for Id_Wildcard_Network)"}
```

As we can see LTE resources are trying to do permissions check based on network name, which works correctly,  while FEG and FEG_LTE  sub resources are doing "Id_Wildcard_Network" check - which leads to failed authorisation.

**Comment by 119Vik** [comment]
'/events/' api group does not do authorisation correctly it responds  with 
```{"message":"access denied (rpc error: code = PermissionDenied desc = Unsatisfied permissions, need: b00000001, got: b00000000 for Id_Wildcard_Network)"}``` as a result of requests to ```/events/<network_id>```

**Comment by hcgatewood** [comment]
Fine-grained network access has been broken for ~2 years. We only support using an admin operator for REST API certs

Closing since this bug is actually a feature request (we'll have to go through and redesign how this works). If desired, please recreate the issue as a feature request, then sync with @ekowtaylor to determine priority within the backlog
