### ISSUE TITLE
FeG Scale Testing with Multiple AGWs

### ISSUE THREAD

**Issue by ekowtaylor** [magma/magma#8773]
In review of the SyncRPC SEV with FreedomFI, it was noted by Ulas that we presently lack testing which stress tests FEG <-> Multiple AGW, in an architecture that mimics frequent use cases by new larger customer deployments for FEG.

Ulas asked Oriol if he might explore and document a plan for such tests.

**Comment by uri200** [comment]
This requieres a test that includes AGW-Or8c-FEG. Right now the only place where we can test that is on labs (TerraVM basically)

So I suggest first the creation of a test that we can run in our mac and on CI that involves AGW-Or8c-FEG. 

Then we can think on how to use multiple AGWs on there
