### ISSUE TITLE
Orc8r Code changes (SubDB Extensions) - Subscriberdb Proto changes, and respective callback functions.

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#8783]
Orc8r Code changes (SubDB Extensions)
Updation to Subscriberdb Proto changes.
Updation to callback functions to serialize and deserialize data.
Addition of Unittestcases

**Comment by Abhishek-R15** [comment]
Draft PR has been raised.
https://github.com/magma/magma/pull/9161

**Comment by anusha-konda** [comment]
Update Subscriberdb.proto and also subscriberdb service function which loads the entries from cfg_entities table to subscriberdb_cache table. Raised PR for all orc8r changes #PR9161.
