### ISSUE TITLE
Orc8r Code changes (SubDB Extensions) - Southbound changes - Verify if AGW is able to read the newly added attributes

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#8784]

**Comment by rupa455wavelabs** [comment]
added the code changes in subscriber_cli.py script, need to test it

**Comment by anusha-konda** [comment]
Verified the changes by configuring NetworkType restriction from NMS, and the same is fetched using subscriber_cli.py. Also added new subscriber using updated subscriber_cli.py with core network restrictions. Changes are part of PR9161.
