### ISSUE TITLE
Finalization of Proposal - Listing API changes, Proto changes, Attr descriptions

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#8791]

**Comment by anusha-konda** [comment]
Proposal doc, https://docs.google.com/document/d/1V7wK5OxVxv9fmDiF1_6IbCXr5hnyLDT0/edit.
Raised a github proposal, https://github.com/magma/magma/issues/8904

**Comment by hcgatewood** [comment]
Hi @anusha-konda! I'm gonna close this issue, if that's alright with you, in favor of https://github.com/magma/magma/issues/8904
