### ISSUE TITLE
[AGW] Header Enrichment on Policy Rule not work on HTTP

### ISSUE THREAD

**Issue by lulloaX** [magma/magma#8802]
### Your Environment
- **Version:** 1.6
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue
After configuring a HE Rule Policy by following the documentation considerations shown below:
- Enabled HE by API` /LTE/{Network-id}/{Gateway-id}/`
![image](https://user-images.githubusercontent.com/28659806/131011148-96f1dd9a-b14f-4ada-9af1-f012a74e7c15.png)

- HE Rule `R_PCC_TDE_BAFI_FREE_HE_01` configured as follow:
```
{
  "app_name": "NO_APP_NAME",
  "app_service_type": "NO_SERVICE_TYPE",
  "flow_list": [
    {
      "action": "PERMIT",
      "match": {
        "direction": "UPLINK",
        "ip_dst": {
          "address": "0.0.0.0/0",
          "version": "IPv4"
        },
        "ip_proto": "IPPROTO_IP",
        "ip_src": {
          "address": "0.0.0.0/0",
          "version": "IPv4"
        },
        "tcp_dst": 80
      }
    },
    {
      "action": "PERMIT",
      "match": {
        "direction": "DOWNLINK",
        "ip_dst": {
          "address": "0.0.0.0/0",
          "version": "IPv4"
        },
        "ip_proto": "IPPROTO_IP",
        "ip_src": {
          "address": "0.0.0.0/0",
          "version": "IPv4"
        }
      }
    }
  ],
  "header_enrichment_targets": [
    "autoatencion.entel.pe/*",
    "autoatencionuat.entel.pe/*",
    "www.entel.pe/*",
    "entel.pe/*",
    "casaideal.com.pe/*",
    "roble.pntic.mec.es/*"
  ],
  "id": "R_PCC_TDE_BAFI_FREE_HE_01",
  "priority": 5,
  "rating_group": 200,
  "redirect": {
    "address_type": "IPv4",
    "server_address": "",
    "support": "DISABLED"
  },
  "service_identifier": 200,
  "tracking_type": "ONLY_OCS"
}
```

But SGi Trace for HTTP session does not show any message that include IMSI and MSISDN from UE. .pcap file attached, please filter it using `ip.addr==212.128.121.30`

**Expected behavior**
During HTTP comunication AGW should add messages that include UE IMSI and MSISDN.

**Additional context**
-  Sessiond logs
[sessiond_log_HE.zip](https://github.com/magma/magma/files/7061735/sessiond_log_HE.zip)

- SGi .pcap file can download [here](https://everisgroup-my.sharepoint.com/:u:/g/personal/lulloaba_everis_com/EfK2H9IC-qhKsJSoJQwvjtQB3RPx0Y0APt5K4Z1M-VS3qg?e=J9jncU)

**Comment by sudhikan** [comment]
The header enrichment configuration that I have working in the lab (on 1.6) has tracking type set to `NO_TRACKING`. Change that and check? Below is the output from `state_cli.py parse policydb:rules` pertaining to header enrichment. Further, I don't see a specific IP endpoint identified in the flows ... below I reference ipv4_dst: 10.22.3.240 as *.fbmamga.ninja will resolve to that IP addr. 

```
header_enrich_wo_cipher
id: "header_enrich_wo_cipher"
priority: 1
flow_list {
  match {
    ipv4_dst: "10.22.3.240"
    tcp_dst: 80
    ip_proto: IPPROTO_TCP
    ip_dst {
      address: "10.22.3.240"
    }
  }
}
tracking_type: NO_TRACKING
he {
  urls: "*.fbmagma.ninja"
}

...

header_enrich_wo_chiper
id: "header_enrich_wo_chiper"
priority: 1
flow_list {
  match {
    ipv4_dst: "10.22.3.240"
    tcp_dst: 80
    ip_proto: IPPROTO_TCP
    ip_dst {
      address: "10.22.3.240"
    }
  }
}
tracking_type: NO_TRACKING
he {
  urls: "*.fbmagma.ninja"
}

```

cc: @joary

**Comment by lulloaX** [comment]
@sudhikan @joary dears, we just tested it again using a modified rule according the feedback you gave us, but it didn´t work. Please let us know if there are some other configs we have to check in order to solve this issue.

- Rule `R_PCC_TDE_BAFI_FREE_HE_01` modified:
```
{
  "app_name": "NO_APP_NAME",
  "app_service_type": "NO_SERVICE_TYPE",
  "flow_list": [
    {
      "action": "PERMIT",
      "match": {
        "direction": "UPLINK",
        "ip_dst": {
          "address": "212.128.121.30",
          "version": "IPv4"
        },
        "ip_proto": "IPPROTO_TCP",
        "ip_src": {
          "version": "IPv4"
        },
        "tcp_dst": 80
      }
    }
  ],
  "header_enrichment_targets": [
    "autoatencion.entel.pe/*",
    "autoatencionuat.entel.pe/*",
    "www.entel.pe/*",
    "entel.pe/*",
    "casaideal.com.pe/*",
    "roble.pntic.mec.es/*",
    "212.128.121.30"
  ],
  "id": "R_PCC_TDE_BAFI_FREE_HE_01",
  "priority": 1,
  "rating_group": 200,
  "redirect": {
    "address_type": "IPv4",
    "server_address": "",
    "support": "DISABLED"
  },
  "service_identifier": 200,
  "tracking_type": "NO_TRACKING"
}
```
- SGi trace pcap file:
[trace0811_SGi_AGW_HE_03.zip](https://github.com/magma/magma/files/7500877/trace0811_SGi_AGW_HE_03.zip)


Thanks in advance!

**Comment by sudhikan** [comment]
Hey @LuisUlloaB  - can you show what you get for `cat /var/log/syslog | grep -i he_enabled` ? 

Also, is this a nat or non-nat setup (I see `nat-enabled` false in your gateway.mcconfig above... please confirm) ? I just ran into a scenario (#10338) where he_enabled wouldn't come back to `true` after a few restarts. Could the two be related?
