### ISSUE TITLE
[AGW][vN] Pick Dependency Injection pattern

### ISSUE THREAD

**Issue by markjen** [magma/magma#8825]

**Comment by markjen** [comment]
I had taken a look at https://github.com/google/wire, but found it to be of minimal value (at least at the current state of our codebase). It codegens basic wiring (passing provider func outputs to other provider inputs and handling errs), but does so at the cost of requiring folks to learn the wire tool and has some unnatural construction, e.g.:

```
//+build wireinject

func NewThing(inputs) Thing {
  panic(wire.Build(deps, ...))
}
```

@hcgatewood took a look at https://pkg.go.dev/go.uber.org/dig and https://pkg.go.dev/go.uber.org/fx but has concerns around requiring learning this framework and reflection magic.

Our last two options are: manual DI or context (https://pkg.go.dev/context#WithValue). 

We'll continue with manual DI for now and revisit if the dependency graph starts to get difficult to manage.

**Comment by hcgatewood** [comment]
From offline: my light input is we should go with manual DI for now, then as soon as it gets mildly painful switch to fx.

Upon a second look, fx seems to solve a lot of problems we could run into. The main downside is it is a bit too magic for a new codebase, so I personally default to manual until we hit explicit pain points
