### ISSUE TITLE
[AGW][vN] src/go/metrics

### ISSUE THREAD

**Issue by markjen** [magma/magma#8843]
- abstraction of metrics data model and collector for use across new golang code
  - potentially use models defined in orc8r/protos/metricsd.proto
  - define `type Collector interface` that will be injected into code, i.e. src/go/service/... implementations
  - helper funcs make it easy for code to create PushedMetric models into a Collector
  - goal is to make sure src/go/metrics does not import github.com/prometheus/...
- implementation that integrates with metricsd
  - maybe have a Collector implementation that periodically pushes to MetricsController.Push? (not sure on the details here yet)

**Comment by ekowtaylor** [comment]
PR: #9412
