### ISSUE TITLE
(orc8r) Non-Superuser is not  able to see Grafana charts in NMS

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#8847]
Non Super users are not able to see Grafana charts on the metrics page.
They are still shown the older display of the statistics. 
@karthiksubraveti

**Comment by paulocalaes** [comment]
Hi guys I created a pull request to solve this issue on: https://github.com/magma/magma/pull/14079

**Comment by nstng** [comment]
already tackled in #14079
