### ISSUE TITLE
pipelined: unit test cleanup

### ISSUE THREAD

**Issue by pshelar** [magma/magma#8880]
investigate all skipped unit test in CI.
create plan to fix it or remote tests that are no longer relevant.

**Comment by ekowtaylor** [comment]
@koolzz please add story points https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/8880

**Comment by ekowtaylor** [comment]
@pshelar and @koolzz to discuss further
