### ISSUE TITLE
Unsafe delete_wrapper

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#8894]

**Comment by ulaskozat** [comment]
![Screen Shot 2021-08-30 at 12.17.02 PM.png](https://images.zenhubusercontent.com/5f7f35c3f500626f8f4b65f1/7375f9c2-18f9-4113-882d-a64252460b15)

**Comment by shashidhar-patil** [comment]
Casting the pointers into void* and then calling delete on them may cause defects as the delete operator  will not call the destructor for the object of type "Example_type" pointed to by 'example_ptr'. This will lead to undefined behavior and is unsafe.

The following sample program mimics the scenario.
[https://app.zenhub.com/files/170803235/ced8fc88-3a5a-477f-9862-2eba081457c9/download](https://app.zenhub.com/files/170803235/ced8fc88-3a5a-477f-9862-2eba081457c9/download)

![delete_wrapper_demo_output.PNG](https://images.zenhubusercontent.com/613855e61bcb9d0f761befab/93c3c7be-513d-40bf-9db0-34d635410f76)

References:
1) https://wiki.sei.cmu.edu/confluence/display/cplusplus/EXP57-CPP.+Do+not+cast+or+delete+pointers+to+incomplete+classes#:~:text=If%20the%20object%20being%20deleted,an%20object%20of%20incomplete%20type.

2) https://pvs-studio.com/en/docs/warnings/v772/

**Comment by shashidhar-patil** [comment]
**Update** : Code changes have been made. Testing in progress.

**Comment by shashidhar-patil** [comment]
**Update:** During testing discovered some issues which require changes in existing code. Working on it.
