### ISSUE TITLE
Magma 5G SA - TeraVM | Error on "PDU_sess_reource_setup_response" from gNB is not handled by AGW

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#8905]
@ulaskozat @VinayKumar1591 @panyogesh: As discussed over call kindly look into this Error handling issue.

gNB sends "PDU_sess_reource_setup_response" message which has "message not compatible with receiver state" error, this error is currently not handled by AGW, ignoring that AGW sends "PDU Session Est Accept".

Below Snap has snap of error & subsequent AGW flow 

<img width="1728" alt="Screen Shot 2021-08-30 at 9 20 41 PM" src="https://user-images.githubusercontent.com/70725754/131441526-d2cc0b48-cdc5-4fc2-90f6-4484453137ac.png">

Enclosed pcap of it.
[SA_07a_Verify__PDU_session_establishment__after_Service_Request___Signaling___Service_Accept_210827_165739-1.pcapng.zip](https://github.com/magma/magma/files/7081189/SA_07a_Verify__PDU_session_establishment__after_Service_Request___Signaling___Service_Accept_210827_165739-1.pcapng.zip)

**Comment by ganeshg87** [comment]
![image.png](https://images.zenhubusercontent.com/6088efcb01ad17d8df423104/077a66d9-2bd5-4a6e-b85a-a5eadd68c68c)

- handling "message not compatible with receiver state" is implementation-dependent.
   this case Initial message with Service Request invalid behaviour from UE.

- @VinayKumar1591 added fix to reject service Request. 

- holding this issue as less priority

**Comment by ganeshg87** [comment]
The primary issue was resolved as part of #8939
https://github.com/magma/magma/pull/8939
