### ISSUE TITLE
Magma 5G SA | Reboot machine after OVS package upgrade from CI Build.

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#8914]
@Ulas Kozat @Yogesh Pandey: Upgraded one of the old version AGW machine & i see in latest AGW build install process OVS pkg old version uninstall (2.14.3) & install new OVS pkg(2.15.2)  is part of it. Only reboot need to be added after this.

[Upgrade logs]

vport-vxlan.ko:
Preparing to unpack .../4-openvswitch-datapath-dkms_2.15.2-1_all.deb ...
-------- Uninstall Beginning --------
Module: openvswitch
Version: 2.14.3
Kernel: 5.4.0-42-generic (x86_64)
-------------------------------------
Status: Before uninstall, this module version was ACTIVE on this kernel. 
.....................
------------- Skipped intermediate logs --------
-------------
- Uninstallation
  - Deleting from: /lib/modules/5.4.0-42-generic/updates/dkms/
 - Original module
  - No original module was found for this module on this kernel.
  - Use the dkms install command to reinstall any previous module version.
depmod................
DKMS: uninstall completed.
------------------------------
Deleting module version: 2.14.3
completely from the DKMS tree.
------------------------------
Done.
Unpacking openvswitch-datapath-dkms (2.15.2-1) over (2.14.3-13) ...
Preparing to unpack .../5-magma_1.7.0-1630402452-10986616_amd64.deb ...
Unpacking magma (1.7.0-1630402452-10986616) over (1.7.0-1628639188-c855b96b) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-t229k3/3-python3-ryu_4.34_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
magma@TVM3-SIT:*~*$ ovs-vswitchd --version
ovs-vswitchd (Open vSwitch) 2.15.2
magma@TVM3-SIT:*~*$

**Comment by pshelar** [comment]
@arun-magma use `ovs-kmod-upgrade.sh` script to upgrade OVS. this handles reloading ovs kmod.

**Comment by pshelar** [comment]
We should installing 2.15 OVS packages in VM and package it to avoid upgrading it to avoid overhead in CI build.

**Comment by panyogesh** [comment]
@pshelar : I guess there are no more actions shall I mark the ticket for closure.

**Comment by panyogesh** [comment]
Closing the ticket.
