### ISSUE TITLE
Fix for CPPLint warnings raised for PRs

### ISSUE THREAD

**Issue by Kaleem-Wavelabs** [magma/magma#8915]

**Comment by Kaleem-Wavelabs** [comment]
Need to cleanup the below warnings/notes whichever is applicable:

/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c:813:15: warning: type defaults to ‘int’ in declaration of ‘i’ [-Wimplicit-int]
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c:829:11: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c:851:7: warning: implicit declaration of function ‘ngap_fill_pdu_session_resource_setup_request_transfer’ [-Wimplicit-function-declaration]
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c:865:38: warning: ‘return’ with a value, in function returning void [-Wreturn-type]
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_itti_messaging.c:52:10: warning: implicit declaration of function ‘ngap_send_msg_to_task’; did you mean ‘send_msg_to_task’? [-Wimplicit-function-declaration]
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_itti_messaging.c:61:17: warning: passing argument 6 of ‘log_message’ makes pointer from integer without a cast [-Wint-conversion]
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/Registration.cpp:1096:17: warning: deleting ‘void*’ is undefined [-Wdelete-incomplete]

/home/vagrant/magma/lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:36:31: note: (near initialization for \lquote upf_openflow_ops.add_tunnel\rquote )\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:37:31: note: (near initialization for \lquote upf_openflow_ops.del_tunnel\rquote )\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:38:31: note: (near initialization for \lquote upf_openflow_ops.discard_data_on_tunnel\rquote )\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:39:31: note: (near initialization for \lquote upf_openflow_ops.forward_data_on_tunnel\rquote )\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:40:31: note: (near initialization for \lquote upf_openflow_ops.add_paging_rule\rquote )\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c:41:31: note: (near initialization for \lquote upf_openflow_ops.delete_paging_rule\rquote )\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/common/log.h:513:12: note: in definition of macro \lquote OAILOG_FUNC_RETURN\rquote\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c:561:6: note: declared here\cf1\highlight2 
/home/vagrant/magma/lte/gateway/c/core/oai/common/log.h:478:64: note: in definition of macro \lquote OAILOG_DEBUG\rquote\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/common/log.h:355:47: note: expected \lquote const char *\rquote  but argument is of type \lquote imsi64_t\rquote  \{aka \lquote long unsigned int\rquote\}\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/common/log.h:438:63: note: in definition of macro \lquote OAILOG_INFO\rquote\cf1\highlight2\f0 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:637:38: note: format string is defined here\cf1\highlight2 
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp:370:39: note: \lquote snprintf\rquote  output between 33 and 49 bytes into a destination of size 31\cf1\highlight2\f0

**Comment by panyogesh** [comment]
Couple of warnings have been fixed especially wrt NGAP and AMF. As the main intent of the PR is to close 5G specific warnings, "tasks/gtpv1-u" warnings will be taken separately
