### ISSUE TITLE
Error response from daemon: Get https://REGISTRY/v2/: Service Unavailable

### ISSUE THREAD

**Issue by ezechinwa** [magma/magma#892]
We need to push the images to our registry 

export MAGMA_TAG=v1.0.0
for image in proxy controller prometheus-cache config-manager grafana
do
    ../../../orc8r/tools/docker/publish.sh -r REGISTRY -i ${image} -v ${MAGMA_TAG}
done

![Screenshot 2019-11-18 at 7 40 47 PM](https://user-images.githubusercontent.com/17327631/69080726-cbb25900-0a3c-11ea-9908-a74d660df95b.png)

**Comment by ardzoht** [comment]
This is most likely a proxy issue, what I'd recommend is to check your proxy settings and configure it as it seems Docker can't connect to registry, once you do that restart docker daemon and give it a shot.

**Comment by xjtian** [comment]
You are supposed to replace "REGISTRY" in that shell command with the URL of the docker registry that you're pushing to (e.g. docker hub/jfrog).
