### ISSUE TITLE
[agw] Experiment w/ Golang for main gateway functionality

### ISSUE THREAD

**Issue by markjen** [magma/magma#8927]
# Experiment w/ Golang for main gateway functionality

## Problem

1. Our current lte/gateway codebase suffers from stability, performance, and maintenance issues.
  i. `lte/gateway/c` code is a c/c++ mix, much of it having poor testability. This has resulted in a dearth of tests; efforts to add tests lead to requiring major refactoring.
  ii. `lte/gateway/python` has significant portions without type-hinting/checking and has performance issues.
2. Developer tooling support in the `lte` codebase is poor. Builds are slow and not hermetic (see #8338), and IDEs/debuggers do not work reliably.
3. Onboarding developers into the `lte` codebase is slow and error-prone.
4. Rate of regression in the `lte` codebase is high, even for developers experienced in the codebase. 
5. Mobility across the codebase (e.g. between `orc8r`, `feg`, and `lte`) is high friction.

Combined, these issues are an impediment to Magma ecosystem growth, a continuous drag on productivity, and a major contributing factor to ongoing issues in deployments.

However, we also have significant unknowns with using a different programming language and toolchain for `lte` services. This expirement aims to answer the following:

1. Will Golang (or other alternatives) be able to achieve the functional and performance requirements?
2. Will the developer experience actually improve? Or will we trade one set of issues for another?
3. Will improvements to developer experience increase velocity, decrease issues, and promote mobility across the codebase?

## Solution

Experiment with reimplementing `lte` components in Golang, starting with the S1AP task in MME and Pipelined.GetStats. Experimental code will not be used in any release until we achieve exit criteria; if the experiment is a success, another proposal will be submitted to decide future development direction, using results from this experiment as an input.

Goals of this experiment are:

1. Experiment should pass S1APTest when integrated with existing services on a magma vargrant VM.
2. New implementation should achieve the same performance metrics as our published v1.6 benchmark.
3. Test code coverage should be >= 75%. Execution of tests to achieve this coverage should be < 15 minutes.
4. Improved developer experience:
  i. Decreased onboarding time / dev environment setup time
  ii. All IDE / dev tools working for all developers
  iii. Decreased time to first PR
  iv. Code is buildable / unit tests are runnable in the developers' native environment w/ IDE integration

## Non-goals

1. Interruption of any existing workstreams, e.g. 5G

**Comment by hcgatewood** [comment]
@markjen are you desiring a specific vote on this from the TSC, or is this more for communication purposes?

**Comment by hcgatewood** [comment]
Accepted as notice of codeowner-led experiment in the Magma codebase
