### ISSUE TITLE
SUCI based loop test is failing on TVM set up.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#8934]
Tested with SUCI based loop test, 3 iterations with multi UE(2 UE's). Testcase failed. Please find the pcaps and logs below..
https://app.zenhub.com/files/170803235/ca864425-20c6-4a53-862d-bf8831578d42/download

**Comment by panyogesh** [comment]
1. SUCI based loop tests
2. 3 Iterations with multiple UE (2 UEs)

**Comment by shanjanaWL** [comment]
I tested with suci based loop test, 3 iterations with multi UE(2 UE's). Testcase failed. Please find the pcaps and logs below.. 
[https://app.zenhub.com/files/170803235/ca864425-20c6-4a53-862d-bf8831578d42/download](https://app.zenhub.com/files/170803235/ca864425-20c6-4a53-862d-bf8831578d42/download)
