### ISSUE TITLE
NgsetupstopRetry - Slice Not Support

### ISSUE THREAD

**Issue by lsguima** [magma/magma#8945]
### Your Environment (If applicable)

- **Version:**
- Installed: 1.7.0-1630547252-c8871d11
Ubuntu Server 20.04 LTS

- **Affected Component:** Access Gateway, Gnb - NOKIA AEQP Massive MIMO 64TX 64RX

### Describe the problem

**Description**
We installed the AGW with success and when we tried to connect the gnb nokia with AGW we are receiving this error on gnb: Slice not support.
On agw we are checking this error:

000342 Thu Sep 02 11:59:04 2021 7F100B4E7700 INFO  NGAP   tasks/ngap/ngap_amf.c           :0087    Received msg from :[TASK_SCTP] id:[114] name:[SCTP_CLOSE_ASSOCIATION]
000343 Thu Sep 02 11:59:04 2021 7F100B4E7700 ERROR NGAP   tasks/ngap/ngap_amf.c           :0182    Unknown message ID 114:SCTP_CLOSE_ASSOCIATION
000344 Thu Sep 02 12:02:07 2021 7F100B4E7700 INFO  NGAP   tasks/ngap/ngap_amf.c           :0087    Received msg from :[TASK_SCTP] id:[113] name:[SCTP_NEW_ASSOCIATION]
000345 Thu Sep 02 12:04:37 2021 7F100B4E7700 INFO  NGAP   tasks/ngap/ngap_amf.c           :0087    Received msg from :[TASK_SCTP] id:[111] name:[SCTP_DATA_IND]
000346 Thu Sep 02 12:04:37 2021 7F100B4E7700 WARNI UTIL   common/log.c                    :1082    Calling finish on a NULL message
000347 Thu Sep 02 12:04:37 2021 7F100B4E7700 INFO  NGAP   tasks/ngap/ngap_amf.c           :0377    Sending msg to :[TASK_SCTP] id: [110]-[SCTP_DATA_REQ]
000348 Thu Sep 02 12:04:37 2021 7F100B4E7700 INFO  NGAP   tasks/ngap/ngap_amf.c           :0087    Received msg from :[TASK_SCTP] id:[111] name:[SCTP_DATA_IND]
000349 Thu Sep 02 12:04:37 2021 7F100B4E7700 ERROR NGAP   tasks/ngap/ngap_amf_decoder.c   :0044    Failed to decode PDU
000350 Thu Sep 02 12:04:37 2021 7F100B4E7700 ERROR NGAP   tasks/ngap/ngap_amf.c           :0105    Failed to decode new buffer

**Additional context**
We collected some logs: Syslog / mme / pcap

http://transfer.sh/H1X6K8/syslog-magma5gsa-Sep02.zip
http://transfer.sh/pE9dfb/mme_logs.zip
http://transfer.sh/gzwHpS/gnb5g_test_trace.zip

![gnb_error](https://user-images.githubusercontent.com/83219702/131890650-c67369f8-70f4-4887-8f72-47ee32212ae8.jpeg)

**Comment by panyogesh** [comment]
In the attached pcaps it seems ngap packets are not present (we can see only tcp packets). Also the error mentioned "Failed to decode PDU" seems to be coming from ASN decoder. So their might be some mismatch in the ASN formats.
Can you please provide the following information :
1. The pcaps with ngap (or tcpdump with filter SCTP)
2. The 3GPP spec version being used in the NGAP on the RAN side.

Thanks.

**Comment by lsguima** [comment]
Hi...I attached the pcap with SCTP filter. We only see HeartBeat. 
http://transfer.sh/fa37f4/gnb_sctp_interface_trace.pcap

**Comment by lsguima** [comment]
I collected a trace during the gnb restart. I'm trying to analyzi the pcap - DATA message ..I think that this log we can have more information to check.

http://transfer.sh/iieLMW/gnbreset_sctp_interface_trace.pcap

**Comment by lsguima** [comment]
Hi Team,

We are checking the log and we can detected that Gnb is sending the information of n_SSAI : SD - d143a5 on NGSetupRequest to AGW and AGW only send the n_SSAi - SST: 01 on NGSetupResponse. After this we received a Error Indicantion from gnb with Cause Slice not supported.  Is it possible to configure the sSD on agw?


![gnb_agw_NGSetupRequest](https://user-images.githubusercontent.com/83219702/132080878-ddfa87a2-929c-4fc3-8ec9-b5b5c9ca08cb.png)
![agw_gnb_NGSetupResponse](https://user-images.githubusercontent.com/83219702/132080883-6c46e524-8c66-4a6a-b8ac-a70f758d5ed2.png)
![gnb_agw_errorindication](https://user-images.githubusercontent.com/83219702/132080886-21a1436d-3a60-41b1-8a2d-1d7d2766e167.png)

**Comment by panyogesh** [comment]
Tracked as part of commit : #9048

**Comment by panyogesh** [comment]
An additional PR  #9243  was merged. This will make AMF parameters configurable from /var/opt/magma/conf/mme.yml part.
