### ISSUE TITLE
NMS Subscribers Config table not being sorted by the sorting button

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#8951]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:**  NMS
- **Affected Subcomponent:** NMS UI
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

The sorting function/button (in red on the image below) is not working for the Subscribers Config table. When clicked, nothing happens.

![Captura de Tela 2021-09-03 às 09 36 00](https://user-images.githubusercontent.com/6054708/132006827-e72a3b4c-b6e7-4bed-8f04-1b9e5c06d916.png)

Tested with Firefox Developer Edition 92.0b9 and Chrome 92.0.4515.159.

**To Reproduce**
1. Go to NMS UI > Network Management > Subscribers > Config
2. Click on the right side of any column header (Name, IMSI, Service, Current Usage, Daily Average, or Last Reported Time)
3. The up arrow button should sort the rows accordingly
4. See the issue: rows are not sorted.

**Expected behavior**

The subscriber rows should be sorted accordingly, by alphabetical order, timestamp, data amount, etc.

**Comment by thmsschmitt** [comment]
The subscribers are fetched paginated therefore the sorting has to be done in the orchestrator and is just not implemented at the moment. As quick "fix" we are disabling the sorting on the table for now.
