### ISSUE TITLE
mme_app_handle_detach_t3422_expiry Fatal Error: SIGSEGV /SEGV_MAPERR

### ISSUE THREAD

**Issue by aswin-alexander** [magma/magma#8983]
[10 instances](https://sentry.io/organizations/lf-9c/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&id=10126&name=1.7&query=release%3A1.7%2A+title%3Amme_app_handle_detach_t3422_expiry&sort=-timestamp&statsPeriod=90d&user=1496893&yAxis=count%28%29) of this on sentry from Sept 5:

**Comment by aswin-alexander** [comment]
Log ([mme.log](https://sentry.io/api/0/projects/lf-9c/lab-agws-native/events/83cc70b612e14eee4b6d92f8f04c47ec/attachments/1796357759/?download=1)) shows:

000343 Sun Sep 05 16:38:11 2021 7F5F525EE700 WARNI NAS-EM tasks/nas/emm/Detach.c          :0135    EMM-PROC: T3422 timer expired,**retransmission counter = 5** for ue id 12444

From detach.c, we see that we attempt to [access detach type](https://github.com/magma/magma/blob/ccf6b1c5e13f1919e82adf37b2880efe42d25906/lte/gateway/c/core/oai/tasks/nas/emm/Detach.c#L151) even though we [cleared data](https://github.com/magma/magma/blob/ccf6b1c5e13f1919e82adf37b2880efe42d25906/lte/gateway/c/core/oai/tasks/nas/emm/Detach.c#L148)

**Comment by aswin-alexander** [comment]
Looks like we had [MME restart](https://github.com/magma/magma/blob/ccf6b1c5e13f1919e82adf37b2880efe42d25906/lte/gateway/c/core/oai/lib/itti/intertask_messages_def.h#L65)

000331 Sun Sep 05 16:38:11 2021 7F5F525EE700 INFO  MME-AP tasks/mme_app/mme_app_main.c    :0490    Received RECOVERY_MESSAGE

**Comment by aswin-alexander** [comment]
Side note, should sgw_s8 [handle recovery](https://github.com/magma/magma/blob/ccf6b1c5e13f1919e82adf37b2880efe42d25906/lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c#L105)?


000330 Sun Sep 05 16:38:11 2021 7F5F4FDE9700 DEBUG SGW_S8 tasks/sgw_s8/sgw_s8_task.c      :0104    Unknown message ID 11: RECOVERY_MESSAGE

**Comment by aswin-alexander** [comment]
It may be worth reviewing the other warnings that were [flagged](https://gist.github.com/electronjoe/987d20e3e730d0a22ce184644c70b449)

cc @electronjoe

**Comment by ulaskozat** [comment]
@aswin-alexander recovery message is a broadcast message. the tasks who do not need a recovery do not implement it.

**Comment by ulaskozat** [comment]
@ardzoht, can you put this into your tracker? @aswin-alexander thanks for catching the invalid data access.

**Comment by ardzoht** [comment]
Added this to the BE tracker https://docs.google.com/spreadsheets/d/18F4XsE6wXdNtMyMT0VipWPRf2oYzBw6a1_EFuhd4J54

**Comment by ardzoht** [comment]
Closing since fix has landed with according s1ap test
