### ISSUE TITLE
NGAP module warning cleanup

### ISSUE THREAD

**Issue by ganeshg87** [magma/magma#8984]
- build manga and capture all warnings from ngap

**Comment by shashidhar-patil** [comment]
Collected ngap warnings.
Dated: 13/09/2021
[https://app.zenhub.com/files/170803235/030a067a-4d86-49c9-9957-eb91adce6365/download](https://app.zenhub.com/files/170803235/030a067a-4d86-49c9-9957-eb91adce6365/download)

**Comment by shashidhar-patil** [comment]
PR #9160 got merged on master, so issue closed.
