### ISSUE TITLE
AMF module warning cleanup

### ISSUE THREAD

**Issue by ganeshg87** [magma/magma#8985]
build magma and capture all warnings of  amf module

**Comment by sreedharkumartn** [comment]
Collected AMF warnings.
Date : 13-09-2021
[https://app.zenhub.com/files/170803235/c66395a4-480b-41f3-9ade-8f2e773d92d0/download](https://app.zenhub.com/files/170803235/c66395a4-480b-41f3-9ade-8f2e773d92d0/download)

**Comment by sreedharkumartn** [comment]
I raised PR #9238 for this issue. PR got merged.
