### ISSUE TITLE
TC011_SANITY_data_600UE_500k_500sec failure

### ISSUE THREAD

**Issue by aswin-alexander** [magma/magma#8997]
Magma build 1.7.0-1631085115-ccf6b1c5
[ENS Dash](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/sanity/test_result_1.7.0-1631085115-ccf6b1c5_2021-09-08%2001:10:02.html)
[Logs](https://ens-spirent-test-summary.com.s3.amazonaws.com/logs/2021-09-08%2001:10:02_sanity_magma.log)

**Comment by aswin-alexander** [comment]
@electronjoe are we tracking log spam?

seeing a LOT of

Sep 08 01:12:54 hil-1 state[117854]: DEBUG:root:
Sep 08 01:12:54 hil-1 state[117854]: DEBUG:root:Check state
Sep 08 01:12:54 hil-1 state[117854]: DEBUG:root:Not re-syncing state. No local state found.

**Comment by aswin-alexander** [comment]
@ulaskozat looks like the issue we were looking at [before](https://app.circleci.com/pipelines/github/magma/magma/31996/workflows/6169fe7f-10af-4d4e-91a6-e851c78e113d/jobs/370799/tests)



Sep 08 01:11:18 hil-1 systemd[1]: Stopping Magma state service...
Sep 08 01:11:18 hil-1 systemd[1]: Stopping Magma OAI MME service...
Sep 08 01:11:18 hil-1 mme[3543]: Received SIGINT or SIGTERM
Sep 08 01:11:18 hil-1 mme[3543]: TASK_S1AP terminated
Sep 08 01:11:18 hil-1 mme[3543]: TASK_SERVICE303 terminated
Sep 08 01:11:18 hil-1 mme[3543]: TASK_SERVICE303_SERVER terminated
<snip>
Sep 08 01:13:34 hil-1 systemd[1]: Stopped Magma OAI MME service.
Sep 08 01:13:34 hil-1 systemd[1]: Stopping Magma pipelined service...
Sep 08 01:13:34 hil-1 systemd[1]: Stopping Magma session manager service...
Sep 08 01:13:34 hil-1 pipelined[118208]: INFO:root:Stopping pipelined with reason SIGTERM...

**Comment by electronjoe** [comment]
> @electronjoe are we tracking log spam?

We should absolutely be monitoring for log spam. I'm surprised we are emitting debug log level from this python binary.

orc8r/gateway/python/magma/state/state_replicator.py
