### ISSUE TITLE
magma 1.0.1,AGW can't connect to local cloud

### ISSUE THREAD

**Issue by chenhao5651** [magma/magma#900]
### Your Environment
AGW host and Orchestrator host , Orchestrator and agw are installed in two debian mechine successfully.
- **Version:1.0.0
- **Affected Component:**  NMS
- **Affected Subcomponent:Orchestrator and AGW service
- **Deployment Environment:, local docker-compose (orc8r), bare-metal (AGW),

### Describe the Issue
I follow the [https://facebookincubator.github.io/magma/docs/lte/config_agw](url) to config AGW, after adding the AGW Hardware ID and Challenge Key in the NMS, AGW can't register to my local orc8r. When I hit "Reboot Gateway" ,it appears
"Reboot failed: gateway magmad client initialization error: rpc error: code = Unknown desc = Error getting location record: No record for query"

Then I followed the [https://facebookincubator.github.io/magma/docs/basics/quick_start_guide](url) to register AGW by implementing fab -f dev_tools.py register_vm.
I changed the  PORTAL_URL = 'https://127.0.0.1:9443/magma/v1/' to 
PORTAL_URL = 'https://192.168.4.94:9443/magma/v1/' , the address 192.168.4.94 is the orc8r communication port,it fails with 
```
root@magma:/home/magma/magma/lte/gateway# fab -f dev_tools.py register_vm
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/usr/local/lib/python3.5/dist-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/magma/magma/lte/gateway/dev_tools.py", line 48, in register_vm
    dev_utils.create_tier_if_not_exists('test', 'default')
  File "../../orc8r/tools/fab/dev_utils.py", line 159, in create_tier_if_not_exists
    tiers = cloud_get('networks/{network_id}/tiers', admin_cert=admin_cert)
  File "../../orc8r/tools/fab/dev_utils.py", line 254, in cloud_get
    (resp.status_code, resp.text))
```

Exception: Received a 500 response: {"message":"Not found"}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ezechinwa** [comment]
Is the port 9443 allowed for traffic flow?

**Comment by chenhao5651** [comment]
> Is the port 9443 allowed for traffic flow?

port 9443 works well
`tcp6       0      0 :::9443                 :::*                    LISTEN      5740/docker-proxy`

If I deployed  orc8r and AGW at one linux machine，orc8r and  AGWS work well. If I deployed  orc8r and AGW at diffrent linux machine, AGW can not register to orc8r .
