### ISSUE TITLE
Magma SA Regression | TeraVM | Downlink GTP packets are not flowing

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9012]
Scenario: 
1, NAT AGW
2, UE Register, Establish PDU Session, sends UL traffic over GTP and Egress on N6 is good.
3, Ingress Pkts received in N6 and we couldn't find any downlink GTP pkts flowing. 

Test setup: Magma SA daily Regression on TeraVM setup.
Ubuntu Master build id: magma | 1.7.0-1631085115-ccf6b1c5

[Snap of UE Reg, PDU & traffic flow, GTP DL pkts are not flowing]

<img width="1553" alt="Screen Shot 2021-09-08 at 7 38 45 PM" src="https://user-images.githubusercontent.com/70725754/132613279-7b0d0f25-b762-4fdd-a70b-ec166a2bac22.png">

Enclosed the Pcap

[SA_01_02_03_04_Hyper_Suci_210908_165152-1.pcapng.zip](https://github.com/magma/magma/files/7132949/SA_01_02_03_04_Hyper_Suci_210908_165152-1.pcapng.zip)

**Comment by panyogesh** [comment]
@arun-magma : In the latest code base the issue seems to be not reproducing. Attaching the snapshot. In case if issue is coming once again in regression on Sep-15 will check on the setup.

<img width="960" alt="Test-Logs-9012-Sep-15" src="https://user-images.githubusercontent.com/69527565/133316677-3c35219d-192c-4cdd-997f-c140343e92ff.png">
[Ovs-Outgoing-Table-Dump.txt](https://github.com/magma/magma/files/7164422/Ovs-Outgoing-Table-Dump.txt)

**Comment by panyogesh** [comment]
[Ovs-Outgoing-Table-Dump.txt](https://github.com/magma/magma/files/7164430/Ovs-Outgoing-Table-Dump.txt)

**Comment by panyogesh** [comment]
Snapshot of : pipelined.yml
----------------------------------------
enforcement:
  poll_interval: 2
  default_drop_flow_name: 'internal_default_drop_flow_rule'
  periodic_stats_reporting: false                         <<<< Add the line or make sure that value is set to false.

**Comment by GANESH-WAVELABS** [comment]
[22-Oct-2021 : Ganesh . I] : below PR has been created for this task:https://github.com/magma/magma/pull/9843

**Comment by GANESH-WAVELABS** [comment]
Below testcases are failing in daily regression which runs on 141 server.
TC2 - SA_TC2_UE_Initiated_PDU_Session_Establishment_with_traffic_test
TC9 - SA_TC9_AMF_Initiated_Paging

But these testcases are passing on 140 server when we execute manually.
While debugging we observed that flag "periodic_stats_reporting" is not configured properly in default configuration file /etc/magma/pipelined.yml. This flag is mentioned as individual parameter, but it should be nested flag under "enforcement" as shown in the attached image.

Could you please set the "periodic_stats_reporting" flag as mentioned in attached image. Also it should be updated in overridden configuration file "/var/opt/magma/configs/pipelined.yml".
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/da227a71-a68e-4c2a-9400-c3ec41264d91)

**Comment by GANESH-WAVELABS** [comment]
verified on TerraVM regression setup, periodic_stats flags was not set as expected. raised zenhub task #10002 to make it correct on teravm setup, So closing this issue.
