### ISSUE TITLE
GTP Echo issue

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#9025]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:1.5.2
- **Affected Component:Acces Gateway
- **Affected Subcomponent:AGW service
- **Deployment Environment:bare-metal (AGW)

### Describe the Issue

ENodeB send an GTP echo request, but no response from AGW and seems that the ENodeB puts the path as failed because of no response. So the UE needs to reconnect (airplane mode on-off) to regain services.

**Expected behavior**
Should receive an echo response.

**Screenshots**
![image](https://user-images.githubusercontent.com/90400693/132705798-c13945f1-fd88-4971-95d1-ab902ec48c28.png)

![image](https://user-images.githubusercontent.com/90400693/132708709-948fe38d-4bea-4cec-81c6-3abe09a21b5f.png)

**Comment by pshelar** [comment]
can you update ovs to 2.14.3-13 using `ovs-kmod-upgrade.sh` ?

**Comment by javieraubert** [comment]
Hi, lets keep track of the issue here https://github.com/magma/magma/issues/9049
