### ISSUE TITLE
XWFM test has been failing on master

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#9026]
It looks to be failing for the past ~3-5 days. 

One failure from 3 days ago: https://app.circleci.com/pipelines/github/magma/magma/32152/workflows/1bf904c4-2e57-4b05-94c8-6917b40fb7c1/jobs/372106 (Sept 6th 2021)

**Comment by ulaskozat** [comment]
@aharonnovo if you are the owner for the tests, can you take a look at it. These tests are consistently failing for quite some time now.

**Comment by themarwhal** [comment]
disabled unit tests
