### ISSUE TITLE
Create/Update Organization error

### ISSUE THREAD

**Issue by HannaFar** [magma/magma#9031]
### Describe the Issue

Error when creating/updating an organization

**To Reproduce**
1. Go to the nms master portal
3. Click Add Organization

**Additional context**
<img width="453" alt="Capture d’écran 2021-09-09 à 19 32 45" src="https://user-images.githubusercontent.com/26038920/132734468-ab561927-a94f-4c4e-a933-c34ad8398fb5.png">

**Comment by ekowtaylor** [comment]
Has this issue been resolved yet?
