### ISSUE TITLE
[test] federated integ test including all gateways (AGW, orc8r and FEG)

### ISSUE THREAD

**Issue by uri200** [magma/magma#9039]
Currently we do not have a way to run a complete Magma setup (AGW + orc8r + feg) on our dev environments. That prevents us to experiment with our code and even test before landing. 

In order to allow developers to run a complete setup, we purpose the creation of a similar setup to lte_integ test but which include all 3 gateways.

This setup must me easy to build and to run. We have to provide a way to wipe all the changes so we can switch between federated integ_test and lte integ_test.

The setup should use:
- AGW running on magma vm
- FEG running on local host or on magma VM 
- Orc8r running on local host
- s1ap running from magma_test
- HSS running as part of the FEG
- Traffic server running from magma_trfserver

The steps to develop this feature will be:
- Develop/Improve fab files to configure network and local gateways in orc8r, making sure we can add and remove the configuration easily
- Modify AGW and FEG configuration on orc8r to support federated case. gateway.mconfig files must be proerly generated by orc8r and stream down to the gateways
- Run FEG either on magma vagrant vm or on local vm. We need to reconfigure feg so it can run simultaneously with AGW and Orc8r
- Modify `build.py`, `run.py` on orc8r and `dev_tools.py`, `fabfile.py` on to support new commands to automate the build and run of the federated case
- Create a new repository for the `federated_integ_test` which includes a new `fabfile.py` to automate the whole setup and any specific configuration files from the setup.
- Add some specific test to s1apTester

**Comment by hcgatewood** [comment]
I support the push for improved testing! However I don't view this as a proposal -- you're the TL for this, so I think a better fit is creating a zenhub epic directly. Proposal => you need TSC approval, and I don't immediately see where this needs TSC approval 🙂 i.e. I think just go for it!

**Comment by uri200** [comment]
Hey @hcgatewood  this issue has lots of context and we don't have the time to move it now

Is there any place where this can be switch into a plain issue?

**Comment by uri200** [comment]
I answer myself: I think removing `type proposal` is enough. So i will keep using this issue
