### ISSUE TITLE
Problem while trying to access organization and adding a new network in existing organization. 

### ISSUE THREAD

**Issue by RadhaKrishna0018** [magma/magma#9051]
Hi All,
I had deployed orc8r locally using this documentation https://github.com/magma/magma/tree/master/orc8r/cloud/deploy/bare-metal-ansible 
So, when I added an organization in master.nms.mydomain.org and also add A record for the organization in AWS as we are hosting the domain in route53 as shown below

<img width="502" alt="aws" src="https://user-images.githubusercontent.com/81242291/132865441-6d5e00af-5012-4c59-8116-b0bcedca629e.PNG">

I have added the new organisation as “test” so when I tried to access it I am able to open the frontend page 
 
<img width="952" alt="2" src="https://user-images.githubusercontent.com/81242291/132872394-c2c03850-585a-4365-ac9a-563d043f7c99.PNG">

But after I enter my credentials, I keep getting this even after I cleared all the cookies and I also tried in incognito but still getting the same thing.
<img width="699" alt="3" src="https://user-images.githubusercontent.com/81242291/132872423-70c24714-689d-4173-a6f0-66af32793f51.PNG">
 

So, I tried logging into magma-test organisation by adding a user and it allowed me to login successfully but when I try to add a new network I got this 
 
<img width="802" alt="4" src="https://user-images.githubusercontent.com/81242291/132872467-d46e5df7-8e4b-4d38-b6f3-75d816f58c5a.PNG">

Here is what the logs looks like for nms-nginx-proxy pod
 
<img width="949" alt="1" src="https://user-images.githubusercontent.com/81242291/132872495-a3a8f223-a442-49aa-82fc-b3c7a4553867.PNG">

Seems to me like a SSL certificate error. Any idea how to resolve this would be helpful. Thanks

**Comment by wallyrb** [comment]
Hey @RadhaKrishna0018  thanks for reporting this. Could you confirm which version did you install, so I can try to reproduce ?

**Comment by RadhaKrishna0018** [comment]
Hi @wallyrb I have installed v1.6.

**Comment by wallyrb** [comment]
thanks @RadhaKrishna0018 will look into it

**Comment by joary** [comment]
@RadhaKrishna0018 , I was checking this bare-metal-ansible deployment this is just supposed to work until magma 1.4. It will not work in latest deployments.

Please let-me know if this feature is required for any production deployment, so we can invest resources to fix the script.
