### ISSUE TITLE
ExecStartPre for sctpd.service is throwing exception due to unavailable Redis service

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#9054]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** - 1.7.0-1631237431-a9e49a48
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service - sctpd
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue
We have observed service restarts with HIL sanity failure. Multiple services indicate connection issues to Redis and systemd restarts services. During sctpd restart,  Redis clean up done before the actual scptd service start `ExecStartPre=/usr/bin/env python3 /usr/local/bin/config_stateless_agw.py sctpd_pre
` throws exception. Rather than exception stack we should instead print a clean exit statement. 

http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/sanity/test_result_1.7.0-1631237431-a9e49a48_2021-09-10%2001:10:03.html

while debugging we observed sctpd crash with below backtrace
```
Sep 10 01:13:21 hil-1 magmad[769]: INFO:root:[SyncRPC] Waiting for requests
Sep 10 01:13:21 hil-1 magmad[769]: ERROR:root:[SyncRPC] Failing to forward request, err: failed to connect to all addresses
Sep 10 01:13:21 hil-1 magmad[769]: ERROR:root:[SyncRPC] gRPC error: failed to connect to all addresses, reconnecting to cloud.
Sep 10 01:13:22 hil-1 sctpd[1740]: Traceback (most recent call last):
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/connection.py", line 539, in connect
Sep 10 01:13:22 hil-1 sctpd[1740]:     sock = self._connect()
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/connection.py", line 596, in _connect
Sep 10 01:13:22 hil-1 sctpd[1740]:     raise err
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/connection.py", line 584, in _connect
Sep 10 01:13:22 hil-1 sctpd[1740]:     sock.connect(socket_address)
Sep 10 01:13:22 hil-1 sctpd[1740]: ConnectionRefusedError: [Errno 111] Connection refused
Sep 10 01:13:22 hil-1 sctpd[1740]: During handling of the above exception, another exception occurred:
Sep 10 01:13:22 hil-1 sctpd[1740]: Traceback (most recent call last):
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/local/bin/config_stateless_agw.py", line 262, in <module>
Sep 10 01:13:22 hil-1 sctpd[1740]:     main()
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/local/bin/config_stateless_agw.py", line 258, in main
Sep 10 01:13:22 hil-1 sctpd[1740]:     func()
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/local/bin/config_stateless_agw.py", line 204, in sctpd_pre_start
Sep 10 01:13:22 hil-1 sctpd[1740]:     clear_redis_state()
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/local/bin/config_stateless_agw.py", line 105, in clear_redis_state
Sep 10 01:13:22 hil-1 sctpd[1740]:     for key in redis_client.scan_iter(key_regex):
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/client.py", line 1835, in scan_iter
Sep 10 01:13:22 hil-1 sctpd[1740]:     cursor, data = self.scan(cursor=cursor, match=match, count=count)
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/client.py", line 1822, in scan
Sep 10 01:13:22 hil-1 sctpd[1740]:     return self.execute_command('SCAN', *pieces)
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/client.py", line 836, in execute_command
Sep 10 01:13:22 hil-1 sctpd[1740]:     conn = self.connection or pool.get_connection(command_name, **options)
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/connection.py", line 1073, in get_connection
Sep 10 01:13:22 hil-1 sctpd[1740]:     connection.connect()
Sep 10 01:13:22 hil-1 sctpd[1740]:   File "/usr/lib/python3/dist-packages/redis/connection.py", line 544, in connect
Sep 10 01:13:22 hil-1 sctpd[1740]:     raise ConnectionError(self._error_message(e))
Sep 10 01:13:22 hil-1 sctpd[1740]: redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6380. Connection refused.
Sep 10 01:13:22 hil-1 systemd[1]: sctpd.service: Control process exited, code=exited, status=1/FAILURE
Sep 10 01:13:22 hil-1 redis[1992]: 1992:C 10 Sep 2021 01:13:22.406 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Sep 10 01:13:22 hil-1 redis[1992]: 1992:C 10 Sep 2021 01:13:22.410 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1992, just started
Sep 10 01:13:22 hil-1 redis[1992]: 1992:C 10 Sep 2021 01:13:22.410 # Configuration loaded
```

**To Reproduce**
Run HIL sanity suite again

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).
logs are attached on s3 link

**Comment by ekowtaylor** [comment]
@ulaskozat, @pshelar could use a check on this

**Comment by ulaskozat** [comment]
@milapjoshi can you point me to the specific syslog file for this issue?

**Comment by ulaskozat** [comment]
This is actually not an sctpd crash. Systemd runs `/usr/bin/env python3 /usr/local/bin/config_stateless_agw.py sctpd_pre` before starting the sctpd service. Since redis is not up, that step is failing.

**Comment by ulaskozat** [comment]
It is not worth handling this exception as systemd will attempt to restart sctpd service again (which is the case also in the logs) and start it.

**Comment by ulaskozat** [comment]
Looks like the real culprit is here:
```
Sep 10 01:11:35 hil-1 redis[240127]: Could not connect to Redis at 127.0.0.1:6379: Connection refused
Sep 10 01:11:35 hil-1 systemd[1]: magma@redis.service: Control process exited, code=exited, status=1/FAILURE
```

**Comment by markjen** [comment]
> It is not worth handling this exception as systemd will attempt to restart sctpd service again (which is the case also in the logs) and start it.

when we encounter this, do we want systemd to auto-restart? In which case, should we have `config_stateless_agw.py sctpd_pre` catch this exception, log an info/warning, and exit(1) cleanly?

**Comment by ulaskozat** [comment]
> > It is not worth handling this exception as systemd will attempt to restart sctpd service again (which is the case also in the logs) and start it.
> 
> when we encounter this, do we want systemd to auto-restart? In which case, should we have `config_stateless_agw.py sctpd_pre` catch this exception, log an info/warning, and exit(1) cleanly?

Yes, we should be catching the exception and exiting cleanly. My comment was intended for retrying in the config_stateless_agw.py. This I think should be under the purview of systemd. One other things is to check/reconsider our dependency graphs for ExecStartPre.
