### ISSUE TITLE
Migrate MCF Artifacts to LF hosted Confluence

### ISSUE THREAD

**Issue by aswin-alexander** [magma/magma#9066]
Currently, MCF artifacts are not 

1. easily discoverable
2. aggregated
3. easy to navigate

For example, TSC captures minutes [here](https://docs.google.com/document/d/1JmAmXluZBtzFlDKd-s4a-3NhsIPs4ifQD9mjwCJaMRc/edit), and videos [here](https://www.youtube.com/playlist?list=PLQ88zlc9KWGdcl_w38Sd1GqzhFLDNveE8) which are discoverable via the [calendar](https://calendar.google.com/calendar/event?eid=c3NsY201bGl0MTYzMnNxcDdqcWgydGY4djRfMjAyMTA5MjBUMTkwMDAwWiBjX2diaXUxdDdhNjdpa2ExdGgyc21sZGVoMTlzQGc&ctz=GMT-07:00) but not on the [website](https://www.magmacore.org/committee/tsc) 

This proposal is to align MCF with other LF efforts (eg: [ORAN](https://wiki.o-ran-sc.org/display/TOC), [ONAP](https://wiki.onap.org/pages/viewpage.action?pageId=4719160)) by using [LF hosted confluence](https://www.linuxfoundation.org/projects/support-programs/)

**Comment by aswin-alexander** [comment]
10/4 TSC [update](https://docs.google.com/document/d/1JmAmXluZBtzFlDKd-s4a-3NhsIPs4ifQD9mjwCJaMRc/edit#)

Notes:

- Jessica W (LF) to provide a walk through next week of ONAP
- Kendall (LF) confirmed the MCF package covers this hosting service
- The [outreach committee ](https://wiki.magmacore.org/display/MOC/Magma+Outreach+Committee+Home)already uses it
  

Next steps:

1. Wait for feedback/ input from the community (comments welcome here)
2. Evaluate the walk through by LF at the next TSC
3. Make a decision at the next TSC based on the above 2

**Comment by hcgatewood** [comment]
After some discussion, here's what we're proposing

---

Needs

1. User-facing documentation, which goes through a code review
2. Contributor-facing documentation, wiki-style
3. Collaboration hub (artifacts, meeting/training recordings, meeting minutes + action items, etc — all separated by working group)

Solution

1. Docusaurus (docs.magmacore.org) still seems like the right move
2. GitHub wiki seems like a solid choice — can attach contributor docs directly the the relevant repo (default to magma/magma), and is wiki-style
3. Confluence seems like a great choice here to fill in the gaps left by the other 2

We can start with this^ approach, then if Confluence goes well, we can *consider* moving all GitHub wiki items to confluence, but as an optional post-step

**Comment by PARitter** [comment]
Question: do we want to start using GitHub Wiki when we have a tentative plan to move those items to Confluence "if it goes well"?  If we presume success - assume Confluence Wiki features are good and use it for item (2).  Then we still have GitHub Wiki as a fallback if Confluence is deemed not good enough.

This approach gets us to the end state more quickly, without requiring an extra step through GitHub Wiki, and still leaves the same fallback position as your proposed step.

**Comment by hcgatewood** [comment]
It's a good point. The rationale is it feels like there's not a lot of love for confluence within the dev bench, and devops has already begun a migration to GH wiki

The inclusion of GH wiki seems like where people are naturally gravitating, so I think it could be worthwhile to let that play out and see where it lands us.

Thoughts @PARitter?

**Comment by PARitter** [comment]
I can work with that.

**Comment by hcgatewood** [comment]
Accepted. @ildikov to coordinate migrating contributor docs to GitHub Wiki, @aswin-alexander to coordinate migrating other artifacts to Confluence

**Comment by Neudrino** [comment]
For reference: The Linux Foundation Magma Confluence can be found at https://wiki.magmacore.org/spacedirectory/view.action.
