### ISSUE TITLE
[AMF] : TC-17 Issue in T3592 expiry and Retransmission of PDU SESSION RELEASE COMMAND message

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9075]
TC-17 Issue in T3592 expiry and Retransmission of PDU SESSION RELEASE COMMAND message  
PDUSessionResourceReleaseCommand retry messages are transmitting on NGAP after the release response. Retry messages go on DL NAS Transport as already release response came from gNB..

**Comment by Kaleem-Wavelabs** [comment]
@shanjanaWL can you please attach pcap and log file as it is not present in shared drive
