### ISSUE TITLE
[AMF] : DNN provided in PDU Session Establishment not being used

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9076]
PR Summary:
DNN from subscriberdb being matched with the one requested by UE.
 1. `apn_config_profile` fetched from subscriberdb using `s6a_update_location_ans_t` wrapper.
 2. `apn_config_profile` from subscriberdb will be matched against the one sent by UE. If a match is present, it will be saved in amf_context `apn_config_profile` wrapper otherwise default `apn_config_profile` will be stored in amf_context.
 3. Finally this apn_config will be sent to smf using `smf_ctx->apn`.

**Comment by panyogesh** [comment]
Assigned to Laawanya Kishore.

**Comment by Lkishor123** [comment]
PR raised: (https://github.com/magma/magma/pull/9645).

**Comment by Lkishor123** [comment]
Registration Process and PDU Session Establishment successful.
![DNN.png](https://images.zenhubusercontent.com/60e58be3aab41d3e7a7b2892/ae65cf88-4943-4cfc-9126-3bdc0c44a434)

**Comment by Lkishor123** [comment]
PR merged.
