### ISSUE TITLE
Events-Based call tracing design exploration

### ISSUE THREAD

**Issue by andreilee** [magma/magma#9134]
## Problem
When network operators troubleshoot issues in a network, they need to understand which section of the network is problematic. Using logs to analyze subscriber issues is not straightforward. We need to connect to AGW and collect logs from several files that keep rotating (mme logs, syslogs, etc). Then we need to do a lot of text manipulation in the logs to filter for one single subscriber. 

In the MVP, we’ve built the basic traffic capture for troubleshooting purposes. Users could initiate a call trace from the NMS to capture files and obtain specific information about the network. This is supported by the TShark tool. Users can view/download the captures on Wireshark when the captures are available.

The MVP has some limitations:
- It only collects the traffic between the AGW and eNodeB, and doesn’t collect information about what’s going on within the AGW.
- Filtering functionality for a specific subscriber or historical trace is missing.
- The viewing of the traffic captures is only available on a third-party tool.
- It is hard to see all the issues across multiple gateways in a single view, because call tracing across multiple gateways simultaneously is inconvenient. Users have to start packet capture for every single gateway. 

## Design Proposal

- Keep the current call trace workflow and rename it as Packet Capture.
- Add a new workflow called Call Trace. In this new workflow, use events to describe subscriber state changes. 
- Reuse the events table for call trace. Support filtering for historical data and specific subscribers.
- Rename the page title as “Troubleshooting”. The 2 tabs under it are Packet Capture and Call Trace. 

## Reference

[One-pager](https://docs.google.com/document/d/1XxLzUtwGzY0hRsngNU69ecMBPym1lWHKTThnrVJBIOo/edit?usp=sharing)
[Figma](https://www.figma.com/file/W5CSgNZ8hqdmuYvwSpZ6rH/Event-based-Call-Tracing?node-id=448%3A4821)

For questions or access to docs, email irisgao@fb.com

**Comment by Neudrino** [comment]
Might be overlapping with a possible idea on Jaeger tracing. See also https://github.com/magma/magma/issues/10492.
