### ISSUE TITLE
[AGW] LTE C++ Migration

### ISSUE THREAD

**Issue by lionelgo** [magma/magma#9136]
# C++ Migration

## Problem

Initially and historically, the development of MME magma was done only in C.

Many third party libraries and features that were integrated and or developed around the MME core are written in C++.
The integration of third party C++ libraries necessary to support the evolution of the MME is each time not straightforward due to the significant remaining C code.

## Solution

A migration of an identified part of the C code in C++ is proposed to facilitate the maintenance and the integration of third party libraries.

See PR #9118

**Comment by Neudrino** [comment]
Super-seeded by https://github.com/magma/magma/issues/11199.
