### ISSUE TITLE
markdown lint job failing

### ISSUE THREAD

**Issue by markjen** [magma/magma#9140]
docs-workflow markdown-lint job is failing on main (from .github/workflows/docs-workflow.yml)

Example: https://github.com/magma/magma/runs/3604837835

Looks like this may not have been running previously on the paths its now checking.

Fix would be to either update markdown files to address lint issues or update the lint check to ignore paths we don't want to check.

This action has been failing for a few weeks now, see:

[all runs](https://github.com/magma/magma/actions/workflows/docs-workflow.yml)
[last success](https://github.com/magma/magma/actions/workflows/docs-workflow.yml?query=is%3Asuccess)

**Comment by ekowtaylor** [comment]
PR merged
