### ISSUE TITLE
Implement asynchronous server for handling s8 messages

### ISSUE THREAD

**Issue by rsarwad** [magma/magma#9157]
- Design changes
Implement asynchronous server for handling s8 messages. Similar to handling HSS initiated messages

**Comment by hcgatewood** [comment]
Hi @rsarwad, thanks for opening this. I would view this more as a feature request. When you have an idea like this, feel free to float it at the biweekly eng meetings or just open a feature request directly.

I'll go ahead and close this for now -- feel free to reopen it if/when you are ready with proposed architecture etc that better fit the proposal type

**Comment by uri200** [comment]
Hey @hcgatewood  we will add more context to this PR.

Reopening
