### ISSUE TITLE
NMS Alerts by Email

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#9162]
### Your Environment (If applicable)

- **Version:** 1.5
- **Affected Component:** Orchestrator, NMS
- **Affected Subcomponent:** NMS Alerts
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the problem

**Description**
It seems that NMS Alerts by email cannot work since the SMTP server credentials are not asked by the UI (please see the screenshot below). At the current version, there is no API route for setting Alerts as well.

**Additional context**
In order to reproduce, go to NMS > Alerts > Receivers  > Add new. Under "Add Notification", choose "Email" and click on the '+' button on the right side of it. Only "From", "Send To" and "Host" are asked.

![Captura de Tela 2021-09-17 às 12 29 54](https://user-images.githubusercontent.com/6054708/133812291-d507ee57-43f5-48d7-bcd9-c683f4ab1497.png)

### Describe your idea

If it works, please share any resource (link, how-tos) for configuring it, since it could not be found over the official docs or other issues over here. Else, please let us know about the plans for it.

**Comment by ekowtaylor** [comment]
@andreilee , would love your initial review of this request

**Comment by ekowtaylor** [comment]
/remind me to follow up with @andreilee in 2 days

**Comment by ekowtaylor** [comment]
Hey @andreilee I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by crbertoldo** [comment]
Hi @andreilee @ekowtaylor, please, any feedback on it?
