### ISSUE TITLE
[HIL-Failure]-TC011_SANITY_data_600UE_500k_500sec

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9169]
### Your Environment

- **Version:** 1.7.0-1631759351-95e75e99
- **Affected Component:** AGW
- **Affected Subcomponent:** MME
- **Deployment Environment:** AWS (orc8r), BM (AGW)

### Describe the Issue

`TC011_SANITY_data_600UE_500k_500sec` runs with 600UEs with a peak expected tput of 300Mbps over 500 seconds. During the nightly execution, there were 9 service rejects that caused the TC to fail. 

Upon first inspection, the team re-ran the TC and noticed that this issue was reproducible. 

#### Symptoms
* UE attached and an attach accept was sent from the MME.
* Sessiond logs show deadline exceeded as shown below.
`Sep 17 09:37:01 hil-1 sessiond[3412]: I0917 09:37:01.258742  3443 LocalEnforcer.cpp:1932] Could not activate rules for IMSI001011234560535, rpc failed: Deadline Exceeded, terminating session...`
* Pipelined logs show activate flows timedout.
`Sep 17 09:37:02 hil-1 pipelined[3499]: ERROR:root:ActivateFlows request processing timed out`
* Subsequently a network initiated detach is sent to the user. 
* However, during this time we noticed that the UE did a service request when the detach was in progress and the MME rejected it as there was no context for this UE. 

#### Issues noted

1. Potentially minor - Sessiond error is what is causing the downstream issues. Identifying the root cause of this is critical for minimizing network initiated detaches. 
2. The UE should not be doing a service request especially after a network initiated detach as the UE is not in ECM-IDLE but de-registered. The UE should be sending an Initial UE Message followed by Attach Request. This is subsequently seen in the logs but after the service reject is sent to the UE. 

#### Theories
*  Pipelined/Sessiond - TBD 
* SR - The team thinks that because the idle timer was set to 0 seconds and due to this the UE thought it was in ECM Idle mode. This was causing the device to send an SR instead of an Attach Request. 

#### Action
* SR - changed idle timer on TC to 4 seconds. We haven't seen the same signature show up yet (i.e. sessiond logs showing deadline exceeded followed by network initiated detach). 

**Screenshots**
![image](https://user-images.githubusercontent.com/38921899/133841535-20da26ee-390c-470b-986b-9ba4c95f8499.png)
[syslog_tc011.zip](https://github.com/magma/magma/files/7188044/syslog_tc011.zip)
[mme_tc011.log.zip](https://github.com/magma/magma/files/7188165/mme_tc011.log.zip)

**Comment by sudhikan** [comment]
Closing until we can repro this after SR timer change.

cc: @milapjoshi

**Comment by sudhikan** [comment]
cc: @milapjoshi

**Comment by milapjoshi** [comment]
detailed log http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/sanity/test_result_1.7.0-1631759351-95e75e99_2021-09-17%2001:10:02.html

**Comment by crbertoldo** [comment]
@sudhikan, it seems we are facing this issue in a real/lab environment. There's no UE service request when the detach is in progress, but we see both sessions and pipelined errors. Please, do you have any suggestions to test?
@joary @jpad-freedomfi

**Comment by jpad-freedomfi** [comment]
@crbertoldo Do we know how to change the SR timer like they did?  What is our current value?

**Comment by crbertoldo** [comment]
@jpad-freedomfi it seems a UE timer (please correct if I'm wrong). I edited my comment because this timer may be related to the UE service request when the detach is in progress, which is not our case.

**Comment by crbertoldo** [comment]
@sudhikan, our issue was clearly related to low BW (<60 bps) assigned to the bad rule's QoS profile, so don't worry. @joary got it. I will open a new issue. Thanks!
