### ISSUE TITLE
5G-SA | TeraVM | "SD" IE is not populated in NSSAI of UE Session (Ngap & NAS) procedures

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9214]
Issue: "SD" IE is missing on Allowed NSSAI in NgAP and NAS layer UE Procedures includes "Registration_complete" , PDU_Session_Resources_Setup etc.

Expectation:  As SD values are configured in NgAP Setup Response , Expect all the NSSAI group IE has SST and SD values in all of the UE session related procedures initiated by AGW.

Tested build : - magma/focal-ci,now 1.7.0-1632067445-bb4e83cb
As this is the new feature inclusion in earlier build behavior is not required to be taken in account.

Logs enclosed: mmelog, Syslog, Ngap Setup pcap and UE Registration pcaps
[Nssai-SD missing.zip](https://github.com/magma/magma/files/7199642/Nssai-SD.missing.zip)

<img width="1584" alt="Screen Shot 2021-09-20 at 6 39 56 PM" src="https://user-images.githubusercontent.com/70725754/134099257-c6e40d18-5dae-4fb7-8c7f-dc643084f57f.png">

Where as in NgAP Setup Response AGW sends SD value along with SST on NSSAI

<img width="1229" alt="Screen Shot 2021-09-20 at 6 52 05 PM" src="https://user-images.githubusercontent.com/70725754/134100144-5fc9c3c0-d99b-4d38-a576-6cc331e01301.png">

**Comment by panyogesh** [comment]
Close. This will be taken as part of slicing feature as the changes are needed from subscriberdb as well.
