### ISSUE TITLE
[FeG] Validity Time inconsistency after RAR from OCS

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#9299]
### Your Environment

- **Version:** 1.6
- **Affected Component:** Orchestrator, Access Gateway, FEG
- **Affected Subcomponent:** FeG
- **Deployment Environment:** Federated LTE Network (AGW, k8s orchestrator, docker FeG)

### Describe the Issue

User has been provisioned with 3 different services (Rating Group : Service ID): 200:200, 201:201 , 201:375
OCS sends in CCA-I a granted quota and validity time for each: 
a) For 201:375, validity time = 48600 (13.5h)
b) For 201:201, validity time = 48600 (13.5h)
c) For 200:200, validity time = 52200 (14.5h)
![image](https://user-images.githubusercontent.com/79710920/134937474-08ba20db-3dd1-46f2-8a9d-b57a9c58d550.png)

Before any validity time meets, OCS sends a RAR (routine procedure) and the FeG sends CCR-U reporting the used quota and the OCS answer with the same validity time. But after we wait that all services meet the validity time according to their last CCA-U timestamp due to RAR -forced reauthorization-, we see that one service RG:SI MSCC (201:375 with validity time = 13.5h) is not doing it, this is meeting the time according to the CCA-Initial timestamp. 
![image](https://user-images.githubusercontent.com/79710920/134941427-bf076729-2790-4df9-afbb-71bca0e555c1.png)

The remaining two services do meet with the validity time according to their last CCA-U due to RAR.
This problem happens always but not with the same RG:SI. For instance, the next day the issue was with the 200:200
![image](https://user-images.githubusercontent.com/79710920/134942738-528dc7ea-be9e-4fef-9ddd-fd5cf65938e1.png)

Let me know if you need extra info. 

**Additional context**
This the trace of FeG. Consider Gy as TCP port 5112, Gx TCP 5111 and IMSI 716770120257790
[fegActive_2409_validityTime.zip](https://github.com/magma/magma/files/7237724/fegActive_2409_validityTime.zip)

**Comment by uri200** [comment]
Hey @emersonacuna , sorry but I may have lost some parts: the issue you are seeing is the validity time is updated for two of RG properly, but the other one (`201:375`) is not updated and finishes too early?

**Comment by emersonacuna** [comment]
hi @uri200 the issue is one service (RG:SI) is not meeting the validity timer considering that last CCR-U triggered by RAR. The rest two of them do meet. 

The issued service is considering the validity timer from the CCA-I or the previous CCA-U before the RAR. The issued service is not always the same.

**Comment by uri200** [comment]
I may not be that familiarized with Validity time field: when we receive the RAR, is the validity time of the 3 RG updated?  When one of the RG hit the validity time, is the traffic supposed to be terminated, or is the PCEF supposed to send a CCRU?

Also, on this specific pcap, is the issue with `201:375` RG?
