### ISSUE TITLE
[Subscriberdb] : Support for core network type while configuring subscribers

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9341]
As part of #9165, new parameter has been added to inform whether Subscriber is allowed to have 4G, 5G or both kind of access. 

SubscriberDB changes are needed support the same. 
If AMF authenticates a User, the core-network type information is also checked to see if Subscriber is allowed for 5G services or not.

**Comment by rupa455wavelabs** [comment]
9775 PR merged into master.
