### ISSUE TITLE
SCTP close association testing.

### ISSUE THREAD

**Issue by Chandhu-Wavelabs** [magma/magma#9345]
Need to prepare script for stopping(to trigger sctp shutdown) and starting the gNB.

Scenario : 

Precondition:

Have 5 UEs to be registered and established session (they are in connected state)
Have 5 UEs to be registered, established session and moved to idle mode.
Action: Trigger sctp shutdown

Post conditions:

Observe that all UEs transition into idle mode in the logs, NGAP receives the context releases
Table-0 rules have the correct rules installed
Action: Bring up gNB and have UEs send service request
Post condition:

Observe that all UEs are switched from idle to connected state in the logs
Observe that Table 0 has the right rules installed.

**Comment by arun-magma** [comment]
SA_TC_58 TC added for this requirement to check SCTP Shutdown

![Screen Shot 2021-10-12 at 9.23.48 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/3a867900-247d-4181-acf6-511b7b56ea17)[https://app.zenhub.com/files/170803235/4532319d-811d-4142-b4f1-f82202d615c1/download](https://app.zenhub.com/files/170803235/4532319d-811d-4142-b4f1-f82202d615c1/download)

**Comment by arun-magma** [comment]
[Uploading... SA_TC59_SCTP_Connection_Shutdown_Verify_N2_N1_State_in_AGW_211025_095224-1.pcapng.zip]

1, After 5UEs + 5UEs in Attach Conn & idle mode Triggered Shutdown and Ngap Setups success  
2, No “Service Accept”
3, Crash Found after the Service Request.
4, Following to that observed a SCTP Aborts
5, Here is Core dump generated during the test

**Comment by arun-magma** [comment]
Type “apropos word” to search for commands related to “word”...
Reading symbols from /usr/local/bin/mme...
[New LWP 890674]
[New LWP 890654]
[New LWP 890658]
[New LWP 890659]
[New LWP 890661]
[New LWP 890662]
[New LWP 890663]
[New LWP 890664]
[New LWP 890665]
[New LWP 890666]
[New LWP 890667]
[New LWP 890668]
[New LWP 890669]
[New LWP 890670]
[New LWP 890671]
[New LWP 890672]
[New LWP 890673]
[New LWP 890675]
[New LWP 890676]
[New LWP 890681]
[New LWP 890682]
[New LWP 890691]
[New LWP 890692]
[New LWP 890693]
[New LWP 890694]
[New LWP 890700]
[New LWP 890701]
[New LWP 890702]
[New LWP 890745]
[New LWP 890746]
[New LWP 890747]
[New LWP 890760]
[New LWP 890802]
[New LWP 1058514]
[New LWP 1058596]
warning: Unexpected size of section `.reg-xstate/890674' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library “/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--c
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co’.
Program terminated with signal SIGSEGV, Segmentation fault.
warning: Unexpected size of section `.reg-xstate/890674' in core file.
#0 0x00005603df9d7ec2 in magma5g::amf_as_establish_cnf (msg=0x7fe503bc1408, as_msg=0x7fe503bc11e8) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:1375
1375	/home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7fe503bf0700 (LWP 890674))]
(gdb)

**Comment by arun-magma** [comment]
Snapshot shows No "Service Accept"
![Screen Shot 2021-10-25 at 3.32.54 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/62e763ea-bd7b-4153-af2b-b3b293da8360)

**Comment by arun-magma** [comment]
@Chandhu-Wavelabs : Hope this PR is merged ? , let me know plz, if possible provide the PR#
