### ISSUE TITLE
agw performance issue

### ISSUE THREAD

**Issue by pshelar** [magma/magma#9348]
### Your Environment

- **Version:** 1.6
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** datapath
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

downlink performance is very low.

**Comment by pshelar** [comment]
Can you post output of apt source file: `cat /etc/apt/sources.list.d/magma.list`

**Comment by armindoantunes** [comment]
> cat /etc/apt/sources.list.d/magma.list

cat /etc/apt/sources.list.d/magma.list
deb https://artifactory.magmacore.org/artifactory/debian focal-1.6.0 main

**Comment by pshelar** [comment]
Thanks @armindoantunes , I have updated the 1.6.0  repo, can you try running `ovs-kmod-upgrade.sh` script and restart all service.

**Comment by armindoantunes** [comment]
> Thanks @armindoantunes , I have updated the 1.6.0 repo, can you try running `ovs-kmod-upgrade.sh` script and restart all service.

I did run the script, it did the upgrade but I got the same results - less than 1Mbps

Didn't took logs from 1st run, this is the output for the 2nd run:
```magma@magma:~$ sudo ovs-kmod-upgrade.sh
This upgrade would result in datapath level downtime for few minutes!
Do you want to proceed with upgrade ?(y/n)y
Hit:1 http://pt.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://pt.archive.ubuntu.com/ubuntu focal-updates InRelease               
Hit:3 http://pt.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                          
Hit:4 http://pt.archive.ubuntu.com/ubuntu focal-security InRelease                                                                           
Hit:5 https://artifactory.magmacore.org/artifactory/debian focal-1.6.0 InRelease                                                             
Hit:6 https://download.docker.com/linux/ubuntu focal InRelease                                     
Reading package lists... Done                                                
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenvswitch is already the newest version (2.15.2-5).
openvswitch-common is already the newest version (2.15.2-5).
openvswitch-datapath-dkms is already the newest version (2.15.2-5).
openvswitch-switch is already the newest version (2.15.2-5).
python3-openvswitch is already the newest version (2.15.2-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 * Detected internal interfaces: 
 * Exiting ovsdb-server (5069)
 * Starting ovsdb-server
 * Configuring Open vSwitch system IDs
 * Exiting ovs-vswitchd (5133)
 * Saving interface configuration
 * Removing vport_gtp module
 * Removing openvswitch module
 * Inserting openvswitch module
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers
 * Restoring interface configuration
 * Finding processes on dead interfaces
RTNETLINK answers: File exists
net.ipv4.ip_forward = 1
update successful
To cleanup control plane state run: config_stateless_agw.py flushall_redis
```

Let me know If you need some extra debugging from my side.

**Comment by pshelar** [comment]
@armindoantunes can you run `config_stateless_agw.py flushall_redis` to restart services and perform the traffic test.

**Comment by brajagopal-h9** [comment]
After upgrade &reboot, gtp0 is not coming up. Please see the logs

root@ip-10-0-4-246:/home/ubuntu# ovs-vsctl show
2b7d10e7-2896-407c-8219-da62f968fd3f
    Manager "ptcp:6640"
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        fail_mode: secure
        Port ipfix0
            Interface ipfix0
                type: internal
        Port li_port
            Interface li_port
                type: internal
        Port proxy_port
            Interface proxy_port
        Port gtp_br0
            Interface gtp_br0
                type: internal
        Port mtr0
            Interface mtr0
                type: internal
        Port gtp0
            Interface gtp0
                type: gtpu
                options: {key=flow, remote_ip=flow}
                error: "could not add network device gtp0 to ofproto (Address family not supported by protocol)"
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
    Bridge uplink_br0
        Port uplink_br0
            Interface uplink_br0
                type: internal
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port dhcp0
            Interface dhcp0
                type: internal
    ovs_version: "2.15.2"


root@ip-10-0-4-246:/home/ubuntu# ovs-vswitchd log
2021-09-30T06:23:35Z|00001|ovs_numa|INFO|Discovered 4 CPU cores on NUMA node 0
2021-09-30T06:23:35Z|00002|ovs_numa|INFO|Discovered 1 NUMA nodes and 4 CPU cores
2021-09-30T06:23:35Z|00003|reconnect|INFO|log: connecting...
2021-09-30T06:23:35Z|00004|reconnect|INFO|log: connection attempt failed (Address family not supported by protocol)
2021-09-30T06:23:36Z|00005|reconnect|INFO|log: connecting...
2021-09-30T06:23:36Z|00006|reconnect|INFO|log: connection attempt failed (Address family not supported by protocol)
2021-09-30T06:23:36Z|00007|reconnect|INFO|log: waiting 2 seconds before reconnect
2021-09-30T06:23:38Z|00008|reconnect|INFO|log: connecting...
2021-09-30T06:23:38Z|00009|reconnect|INFO|log: connection attempt failed (Address family not supported by protocol)
2021-09-30T06:23:38Z|00010|reconnect|INFO|log: waiting 4 seconds before reconnect


● openvswitch-switch.service - LSB: Open vSwitch switch
     Loaded: loaded (/etc/init.d/openvswitch-switch; generated)
     Active: active (running) since Thu 2021-09-30 06:22:27 UTC; 2min 4s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 5277 ExecStart=/etc/init.d/openvswitch-switch start (code=exited, status=0/SUCCESS)
      Tasks: 9 (limit: 18973)
     Memory: 46.1M
     CGroup: /system.slice/openvswitch-switch.service
             ├─5330 ovsdb-server: monitoring pid 5331 (healthy)
             ├─5331 ovsdb-server /etc/openvswitch/conf.db -vconsole:emer -vsyslog:err -vfile:info --remote=punix:/var/run/openvswitch/db.sock --private-key=db:Open_vSwitch,SSL,private_key --certificate=d>
             ├─5350 ovs-vswitchd: monitoring pid 5351 (healthy)
             └─5351 ovs-vswitchd unix:/var/run/openvswitch/db.sock -vconsole:emer -vsyslog:err -vfile:info --mlockall --no-chdir --log-file=/var/log/openvswitch/ovs-vswitchd.log --pidfile=/var/run/openvs>

Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5507]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 mtr0 -- set Interface mtr0 type=internal -- set interface mtr0 ofport_r>
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5577]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 ipfix0 -- set Interface ipfix0 type=internal -- set interface ipfix0 of>
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5646]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 patch-up -- set Interface patch-up type=patch options:peer=patch-agw -->
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5703]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 proxy_port --
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5760]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port gtp_br0 li_port -- set Interface li_port type=internal -- set interface li_port>
Sep 30 06:22:27 ip-10-0-4-246 openvswitch-switch[5809]: net.ipv4.ip_forward = 1
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5866]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-br uplink_br0 --
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5911]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port uplink_br0 dhcp0 -- set Interface dhcp0 type=internal -- set interface dhcp0 of>
Sep 30 06:22:27 ip-10-0-4-246 ovs-vsctl[5979]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --timeout=5 -- --may-exist add-port uplink_br0 patch-agw -- set Interface patch-agw type=patch options:peer=patch-u>
Sep 30 06:22:27 ip-10-0-4-246 systemd[1]: Started LSB: Open vSwitch switch.

**Comment by anevrekarh9** [comment]
After running `"ovs-kmod-upgrade.sh" & "config_stateless_agw.py flushall_redis"` and before reboot, gtp0 is up. But this did not help solve the performance issue.

```
2b7d10e7-2896-407c-8219-da62f968fd3f
    Manager "ptcp:6640"
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        fail_mode: secure
        Port g_2303000a
            Interface g_2303000a
                type: gtpu
                options: {key=flow, remote_ip="10.0.3.35"}
        Port gtp0
            Interface gtp0
                type: gtpu
                options: {key=flow, remote_ip=flow}
        Port proxy_port
            Interface proxy_port
        Port li_port
            Interface li_port
                type: internal
        Port ipfix0
            Interface ipfix0
                type: internal
        Port mtr0
            Interface mtr0
                type: internal
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port gtp_br0
            Interface gtp_br0
                type: internal
    Bridge uplink_br0
        Port uplink_br0
            Interface uplink_br0
                type: internal
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port dhcp0
            Interface dhcp0
                type: internal
    ovs_version: "2.15.2"
```

After reboot, gtp0 is down.

```
2b7d10e7-2896-407c-8219-da62f968fd3f
    Manager "ptcp:6640"
    Bridge uplink_br0
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port dhcp0
            Interface dhcp0
                type: internal
        Port uplink_br0
            Interface uplink_br0
                type: internal
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        fail_mode: secure
        Port proxy_port
            Interface proxy_port
        Port gtp_br0
            Interface gtp_br0
                type: internal
        Port li_port
            Interface li_port
                type: internal
        Port ipfix0
            Interface ipfix0
                type: internal
        Port mtr0
            Interface mtr0
                type: internal
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port gtp0
            Interface gtp0
                type: gtpu
                options: {key=flow, remote_ip=flow}
                error: "could not add network device gtp0 to ofproto (Address family not supported by protocol)"
    ovs_version: "2.15.2"
```

**Comment by armindoantunes** [comment]
Now have about 15.4 Mbps download and 10.4 Mbps upload with a usrp b200.
I think I know what my problem was:
the apn bandwidth was limited to 1Mbps:
max_bandwidth_ul: 1000000
max_bandwidth_dl: 1000000
@anevrekarh9 try running `subscriber_cli.py get IMSIxxxxxxx `to confirm your values

**Comment by pshelar** [comment]
@armindoantunes what is limiting the bandwidth to 15 mbps. I am getting 65 mbps bandwidth in lab setup.

**Comment by pshelar** [comment]
FYI, when you see following issue:
```
Port gtp0
            Interface gtp0
                type: gtpu
                options: {key=flow, remote_ip=flow}
                error: "could not add network device gtp0 to ofproto (Address family not supported by protocol)"
    ovs_version: "2.15.2"
```
you can fix it by `ifdown gtp_br0; ifup gtp_br0`

**Comment by armindoantunes** [comment]
> @armindoantunes what is limiting the bandwidth to 15 mbps. I am getting 65 mbps bandwidth in lab setup.

I'm using a usrp b200 (via usb) not sure if that's the reason.

**Comment by brajagopal-h9** [comment]
that did not help
root@ip-10-0-4-246:/home/magma# ifdown gtp_br0; ifup gtp_br0
RTNETLINK answers: File exists
ovs-vsctl: Error detected while setting up 'gtp0': could not add network device gtp0 to ofproto (Address family not supported by protocol).  See ovs-vswitchd log for details.
ovs-vsctl: The default log directory is "/var/log/openvswitch".


root@ip-10-0-4-246:/home/magma# tail -20 /var/log/openvswitch/ovs-vswitchd.log
2021-10-01T11:29:01.272Z|00106|bridge|INFO|bridge gtp_br0: deleted interface ipfix0 on port 15578
2021-10-01T11:29:01.334Z|00107|bridge|INFO|bridge gtp_br0: deleted interface patch-up on port 2
2021-10-01T11:29:01.366Z|00108|bridge|INFO|bridge gtp_br0: deleted interface proxy_port on port 1
2021-10-01T11:29:01.402Z|00109|bridge|INFO|bridge gtp_br0: deleted interface li_port on port 15579
2021-10-01T11:29:01.433Z|00110|bridge|INFO|bridge gtp_br0: deleted interface gtp_br0 on port 65534
2021-10-01T11:29:11.224Z|00111|bridge|INFO|bridge gtp_br0: added interface gtp_br0 on port 65534
2021-10-01T11:29:11.224Z|00112|bridge|INFO|bridge gtp_br0: using datapath ID 0000da7eb53ad94d
2021-10-01T11:29:11.224Z|00113|connmgr|INFO|gtp_br0: added service controller "punix:/var/run/openvswitch/gtp_br0.mgmt"
2021-10-01T11:29:11.261Z|00114|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.300Z|00115|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.303Z|00116|bridge|INFO|bridge gtp_br0: added interface mtr0 on port 15577
2021-10-01T11:29:11.307Z|00117|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.312Z|00118|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.347Z|00119|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.349Z|00120|bridge|INFO|bridge gtp_br0: added interface ipfix0 on port 15578
2021-10-01T11:29:11.354Z|00121|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.357Z|00122|dpif|WARN|system@ovs-system: failed to add gtp0 as port: Address family not supported by protocol
2021-10-01T11:29:11.395Z|00123|bridge|INFO|bridge gtp_br0: added interface patch-up on port 2
2021-10-01T11:29:11.434Z|00124|bridge|INFO|bridge gtp_br0: added interface proxy_port on port 1
2021-10-01T11:29:11.474Z|00125|bridge|INFO|bridge gtp_br0: added interface li_port on port 15579

**Comment by sergemaskalik** [comment]
Is it possible to disable APN AMBR and the token bucket rate limiter while this is being worked out as a workaround? Can we add a feature to Orc8r to disable for now?

**Comment by ulaskozat** [comment]
disabling APN AMBR is not an option. Please root cause the issue rather than trying to hack a workaround.

**Comment by pshelar** [comment]
@sergemaskalik lets connect on slack, its taking too long  to debug on github.

**Comment by pshelar** [comment]
After running `ovs-kmod-upgrade.sh` performance improved.
