### ISSUE TITLE
Openvswitch ko module upgrade script should be part of magma upgrade procedure 

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#9356]
- **Version:** any
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW openvswitch
- **Deployment Environment:** e.g. bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

`ovs-kmod-upgrade.sh` this script make sure magma AGW is using correct openvswitch kernel module. However it seems this need to be run manually first time to get correct cornel version on syste.

this cause uncertainty on curring system as KO module upgrade is manual.

proposal is to make this script run as part of upgrade procedure. so that each system is on predicted system version automatically.
 

before upgrade
`root@hil-1:~# modinfo openvswitch
filename:       /lib/modules/5.4.0-88-generic/kernel/net/openvswitch/openvswitch.ko
alias:          net-pf-16-proto-16-family-ovs_ct_limit
alias:          net-pf-16-proto-16-family-ovs_meter
alias:          net-pf-16-proto-16-family-ovs_packet
alias:          net-pf-16-proto-16-family-ovs_flow
alias:          net-pf-16-proto-16-family-ovs_vport
alias:          net-pf-16-proto-16-family-ovs_datapath
`

after upgrade

`filename:       /lib/modules/5.4.0-88-generic/updates/dkms/openvswitch.ko
alias:          net-pf-16-proto-16-family-ovs_ct_limit
alias:          net-pf-16-proto-16-family-ovs_meter
alias:          net-pf-16-proto-16-family-ovs_packet
alias:          net-pf-16-proto-16-family-ovs_flow
alias:          net-pf-16-proto-16-family-ovs_vport
alias:          net-pf-16-proto-16-family-ovs_datapath
version:        2.15.2
license:        GPL
description:    Open vSwitch switching datapath
srcversion:     9A76C00DE246AED7891AF3E
depends:        nf_conntrack,nf_nat,udp_tunnel,libcrc32c,nf_defrag_ipv6
retpoline:      Y
name:           openvswitch
vermagic:       5.4.0-88-generic SMP mod_unload modversions
sig_id:         PKCS#7
signer:         magma-agw Secure Boot Module Signature key
sig_key:        77:E4:30:0A:A9:1F:6E:9D:87:3F:16:54:C2:87:41:9F:A4:BA:CB:C4
sig_hashalgo:   sha512
`

**Comment by pshelar** [comment]
@milapjoshi can you point me to the upgrade script.
