### ISSUE TITLE
magma V1.0.0 test case fails with MAC Failure

### ISSUE THREAD

**Issue by chenhao5651** [magma/magma#936]
### Your Environment

- **Version:V1.0.0
- **Affected Component: Access Gateway
- **Affected Subcomponent:test case
- **Deployment Environment:**   bare-metal (AGW), test host

### Describe the Issue
My AGW works well with eNode,then I want to test magma V1.0.0 with it's own test cases,
run the test_attach_detach.py test case ,it fails with MAC Failure:
`Entering _nas_message_get_mac()` 
    `NAS_SECURITY_ALGORITHMS_EIA2 dir UPLINK count.seq_num 0 count 0`
   `Byte length: 11, Zero bits: 0:`
    `m: (11 bytes) 00 00 00 00 00 00 00 00 00 07 5e`
    `Key: (16 bytes) ff 00 e9 0e c0 a7 54 61 24 ee 27 1f 65 11 35 3c`
    `Message: (3 bytes) 00 07 5e`
    `Out: (16 bytes) c5 bb e7 02 17 eb b1 f4 85 7e b2 68 76 8b 96 e4`
    `NAS_SECURITY_ALGORITHMS_EIA2 returned MAC c5.bb.e7.2(48741317) for length 3 direction 0, count 0`
 `Leaving _nas_message_get_mac() (rc=3317425922)`
`MAC Failure MSG:92CAFFDA(2462777306) <> INT ALGO:C5BBE702(3317425922) Type of security context 2`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ssanadhya** [comment]
@chenhao5651, this is unexpected behavior! The test is working fine in my local setup. Did you restart all magma services after installing V1.0.0?

**Comment by chenhao5651** [comment]
> @chenhao5651, this is unexpected behavior! The test is working fine in my local setup. Did you restart all magma services after installing V1.0.0?

I did not restart magma host and test host.How the test case generates MAC? Dose it relate to ueAppCfg.txt or  ueCfg.txt?

**Comment by chenhao5651** [comment]
> @chenhao5651, this is unexpected behavior! The test is working fine in my local setup. Did you restart all magma services after installing V1.0.0?
AGW sent security mode command message with IE ‘IMEISV’，but test case sent security mode complete message without IMEISV ，so AGW failed with MAC Failure

**Comment by ssanadhya** [comment]
Can you share the MME log and packet capture for this test run?
