### ISSUE TITLE
error: error executing jsonpath "{.items[0].metadata.name}"

### ISSUE THREAD

**Issue by ezechinwa** [magma/magma#937]
![Screenshot 2019-11-23 at 3 18 57 PM](https://user-images.githubusercontent.com/17327631/69480759-90cc6e80-0e0a-11ea-9b59-dd34f656383a.png)

After running
` export CNTLR_POD=$(kubectl get pod -l app.kubernetes.io/component=controller -o jsonpath='{.items[0].metadata.name}')`

I get the error above.

**Comment by xjtian** [comment]
Unable to repro on our v1.0 testing stack - the helm chart properly tags the controller pod and kubectl returns a controller pod's name as expected. Something is wrong with your installation, but there's not nearly enough context here to properly diagnose the issue.

Please re-open with more context, following the bug report template
