### ISSUE TITLE
FWA 4G 1.6 | Service identifier AVP is Missing in Gy MSCC Requests from Magma

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9370]
Issues : Service identifier AVP is Missing in Gy MSCC Requests from Magma
Scenario: 
1, UE Attach in federated mode and in Gx Receives the single Dynamic Rule.
2, Gx Dynamic rules consists of Service Identifier and Rating group.
3, [issue #1] on Gy MSCC only Rating Group value is cascaded from Gx missing Service identifier.
4, [issue #2] There is no Usage reporting Gy CCR-U going after continuous Traffic flow matching to the rule for these cases, need to Debug that as well.

Expectation: Include Rating group and Service identifier in Gy MSCC Requests as it comes from Gx Dynamic Rules.

Note:
This issue is observed in 1.6 production release, in later 1.7 release SI + RG both are included by default on Gy MSCC Requests.

Tested Build: 1.6.0-1625592603-1f26ba81
TeraVm test Scenarios:
gx_gy_combined_05_capacity
gx_gy_combined_05

[Snaps]
Gx Dynamic rule: (SI+RG)

<img width="1582" alt="Screen Shot 2021-09-29 at 11 19 01 PM" src="https://user-images.githubusercontent.com/70725754/135398118-380280fc-3d00-44e4-a407-2bf35b95a0e9.png">

Gy MSCC Request ( only RG, Missing "SI")

<img width="1582" alt="Screen Shot 2021-09-29 at 11 19 33 PM" src="https://user-images.githubusercontent.com/70725754/135398194-cbcb7bcd-0876-4662-8c00-9e5dfca8090b.png">

[Enclosed traces]
[gx_gy_combined_06_210929_062436-1.pcapng.zip](https://github.com/magma/magma/files/7257151/gx_gy_combined_06_210929_062436-1.pcapng.zip)
[gx_gy_combined_05_capacity_210929_062242-1.pcapng.zip](https://github.com/magma/magma/files/7257152/gx_gy_combined_05_capacity_210929_062242-1.pcapng.zip)

**Comment by uri200** [comment]
This had never been implemented, so was considered a new feature.

This feature was already added to master on Aug 17 after @arun-magma  raised the issue below. 

This feature was never part of any requirement for 1.6.

https://github.com/magma/magma/issues/8683
