### ISSUE TITLE
AGW ERROR (ModuleNotFoundError: No module named 'magma.sctpd')

### ISSUE THREAD

**Issue by durihub-africa** [magma/magma#9387]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:**1.6 and ubuntu 20.04
- **Affected Component:**  Access Gateway
- **Affected Subcomponent:** AGW 
- **Deployment Environment:** e.g. bare-metal (AGW)

### Describe the Issue

**To Reproduce**
1. Go to 'Install AGW 1.6'
2. Click on 'Checkin AGW to OCR8'
3. Scroll down to 'journalctl -fu .'
-- Logs begin at Mon 2021-08-23 01:49:09 CAT. --
Sep 30 21:25:10 andromeda systemd[1]: Started Magma sctpd service.
Sep 30 21:25:10 andromeda sctpd[15346]: /usr/bin/python3: Error while finding module specification for 'magma.sctpd.main' (ModuleNotFoundError: No module named 'magma.sctpd')
Sep 30 21:25:10 andromeda systemd[1]: magma@sctpd.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 21:25:10 andromeda systemd[1]: magma@sctpd.service: Failed with result 'exit-code'.
Sep 30 21:25:15 andromeda systemd[1]: magma@sctpd.service: Scheduled restart job, restart counter is at 57.
Sep 30 21:25:15 andromeda systemd[1]: Stopped Magma sctpd service.

**Expected behavior**
sctpd service running 

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by maxthetor** [comment]
resolved?
I have the same problem in 1.8
