### ISSUE TITLE
MySQl connection Timeout

### ISSUE THREAD

**Issue by phirmware** [magma/magma#939]
Hi Guys,

I have been able to follow all the steps in the documentation for deploying the ochestrator on aws,
but i am having an issue with one of the pods,

```
kubectl exec -it -n magma \
  $(kubectl get pod -l app.kubernetes.io/component=magmalte -o jsonpath='{.items[0].metadata.name}') -- \
  yarn setAdminPassword <admin user email> <admin user password>
```
When i run the function above, I get a Timeout error from mysql
![yo](https://user-images.githubusercontent.com/32414323/69564897-23f4d800-0fb4-11ea-8da5-c5637846cae3.png)

Then when i check the pods with
`kubectl -n magma get pods`
I noticed the nms-magmalte pod failing the liveness probe 
![Screenshot 2019-11-25 at 6 29 27 PM](https://user-images.githubusercontent.com/32414323/69564943-3d961f80-0fb4-11ea-9b04-7df17ee22752.png)

What should I do?

**Comment by phirmware** [comment]
There is no response!
I have done the deployment again.
Everything works fine until this point.

When I run 
`kubectl -n magma desribe pod nms-magmalte-xxxxx`, 
I get this
![yoyo](https://user-images.githubusercontent.com/32414323/69754537-69e9a180-1156-11ea-92ba-3d913971d8ac.png)

For some reason , connection to port 8081 is not working.

**Comment by themarwhal** [comment]
So the magmalte pod is crash looping before you run the `kubectl exec...` command, is that correct? Were you able to get any logs from the container to see why it failed? `kubectl logs nms-magmalte-xxxxx`

**Comment by phirmware** [comment]
Thanks a lot for the response @themarwhal
I took a good look at it and i figured out the problem.
I used the wrong `RDS MYSQL HOST ` on the vals.yml file.
Everything works fine now.
Thank you!
