### ISSUE TITLE
Cronologically unordered SMSes triggered by the Magma API

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#9392]
### Your Environment

- **Version:** 1.5
- **Affected Component:** Orchestrator or Access Gateway
- **Affected Subcomponent:** Orchestrator pod/service or AGW service (not sure which)
- **Deployment Environment:** e.g. AWS (orc8r),  bare-metal (AGW)

Note: this setup is part of a federated network, with a Gy interface towards SigScale OCS, but I think it's not an issue.

### Describe the Issue

SMSes are triggered through the Magma API. Some SMSs are immediately delivered as we can see on the phone UI, by tracing S1, and by the "Delivered" status through the same API. Therefore, other ones cannot be delivered immediately due to a reason that we don't know (any clue is welcome here) - paging is being delivered and everything looks fine by the way.  Not delivering immediately is not an issue. These ones receive the status of "Waiting".  The issue: it seems to be a LIFO rule for those SMSes triggered and immediately delivered vs. the waiting ones, and a FIFO rule for those waiting. 

**To Reproduce**
1. Create a cron job to POST SMSs by the Magma API every 'n' second with its triggering timestamp as content (see the screenshot below)
2. Check if the SMS PK is successfully returned for each API call - a log file with a timestamp, and it, is helpful
3. When the job is running, trace S1 looking for any inconsistency (not found - what doesn't mean it doesn't exist)
4. Both by the phone UI and querying the SMS delivery status by the API and the SMS PK, see the issue (unordered messages that break our use case)

**Expected behavior**

The SMSes on the screenshot below were triggered sequentially by a 1 min loop cronjob. The expected behavior was not receiving them immediately, but was having them ordered chronologically. I.e., for example, the SMS from 22:37 should be queued after those waiting (from 22:32, 22:33, 22:34, 24:35, and 22:36).

**Screenshots**

![Captura de Tela 2021-09-30 às 19 42 37](https://user-images.githubusercontent.com/6054708/135541721-3f31df5a-8d1e-4e78-8de6-1637b27b4d4e.png)

**Additional context**

- Please find attached the S1 pcap, syslog, and MME log 
[unordered_sms_issue_agw_logs_and_trace.zip](https://github.com/magma/magma/files/7263032/unordered_sms_issue_agw_logs_and_trace.zip)
- IMSI under test is 90212012345678
- smsd seems to check-in for SMS every 5 seconds: ok

**Comment by crbertoldo** [comment]
@shehzadalee @jpad-freedomfi

**Comment by jpad-freedomfi** [comment]
@hcgatewood and @wallyrb this effects two customers pushing for commercial deployment.

**Comment by ekowtaylor** [comment]
@wallyrb  to provide additional comments

**Comment by wallyrb** [comment]
Hey @jpad-freedomfi we discussed this with the team,  unfortunately, we don't have bandwidth to triage and fix this in the next sprint. We are planning to investigate this further, but at the moment we can't provide an ETA for the resolution of this.

Meanwhile, if you have the bandwidth, will appreciate you can help us to investigate this further. Let me know if you have any questions. (cc: Aditya @adityawasudeo )
