### ISSUE TITLE
Pipelined Restarts for Unknown Reason in 1.5

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#9417]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

Pipelined gets restarted every some time with unknown reason in 1,5 also affecting the service as AGW deactivated the bearers.

**To Reproduce**
Not sure

**Expected behavior**
The service should run smooth.

**Screenshots**

Oct  3 21:26:25 agw pipelined[15451]: Traceback (most recent call last):
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Oct  3 21:26:25 agw pipelined[15451]:     "__main__", mod_spec)
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Oct  3 21:26:25 agw pipelined[15451]:     exec(code, run_globals)
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 202, in <module>
Oct  3 21:26:25 agw pipelined[15451]:     main()
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 186, in main
Oct  3 21:26:25 agw pipelined[15451]:     service.run()
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 243, in run
Oct  3 21:26:25 agw pipelined[15451]:     self._loop.run_forever()
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 253, in run_forever
Oct  3 21:26:25 agw pipelined[15451]:     super(EventLoop, self).run_forever()
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
Oct  3 21:26:25 agw pipelined[15451]:     self._run_once()
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 1388, in _run_once
Oct  3 21:26:25 agw pipelined[15451]:     event_list = self._selector.select(timeout)
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 167, in select
Oct  3 21:26:25 agw pipelined[15451]:     events = self._read_events()
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 162, in _read_events
Oct  3 21:26:25 agw pipelined[15451]:     key = self.get_key(fd)
Oct  3 21:26:25 agw pipelined[15451]:   File "/usr/lib/python3.5/selectors.py", line 191, in get_key
Oct  3 21:26:25 agw pipelined[15451]:     raise KeyError("{!r} is not registered".format(fileobj)) from Non
[logs.zip](https://github.com/magma/magma/files/7274832/logs.zip)
e

**Comment by shehzadalee** [comment]
@ulaskozat @amarpad @jpad-freedomfi

**Comment by ulaskozat** [comment]
@koolzz could you check what the issue might be and whether it is already fixed on the master?

**Comment by koolzz** [comment]
> @koolzz could you check what the issue might be and whether it is already fixed on the master?

Yeah this depends on the patched aioeventlet lib https://github.com/magma/magma/pull/6404/files. 

I think we also needed to build the lib and I'm not quite sure which release we did that for @pshelar  any idea?
