### ISSUE TITLE
Session Event functionality support for 5G in sessiond.

### ISSUE THREAD

**Issue by prabinakpattnaik** [magma/magma#9421]

**Comment by ekowtaylor** [comment]
@prabinakpattnaik please provide some more details for this new feature

**Comment by prabinakpattnaik** [comment]
We will capture the all sessiond events in cloud service (Orc8r/NMS deskboard).
Below Session Events are sent to the eventd service for logging:
session_creation
session_create_failure
session_updates
session_update_failure
session_terminate

**Comment by prabinakpattnaik** [comment]
The PR (#10239) has been merged into master branch. The PR (#10239) was part of this task. Hence will close this task.
