### ISSUE TITLE
Update to FEG_RELAY, to redirect the sessiond request to N7_PROXY based on RATTYpe

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#9424]
Required update to Orc8r FEG Relay module, to redirect the request to FEG Sessiond Proxy and FEG N7 Proxy based on the RATType in CommonSessionContext of Create/Update/Terminate session requests.

**Comment by Abhishek-R15** [comment]
Orc8r patch has been submitted for integration test.

**Comment by Abhishek-R15** [comment]
Draft PR has been raised
https://github.com/magma/magma/pull/10254
