### ISSUE TITLE
[AGW][1.6] States are not clearing post scale tests

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9430]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6.0-1625592603-1f26ba81
- **Affected Component:** AGW
- **Affected Subcomponent:** States
- **Deployment Environment:** AWS (orc8r) bare-metal (AGW)

### Describe the Issue

For 1.6.1 to be released,  the team benchmarked 1.6.0 again (these same validations did not exist when 1.6.0 was released back in July). 

In this latest, we are noticing that `MME, SPGW, S1AP, table0, table12, table13, and mobilityd` states are not getting cleared upon UEs detaching from the network. Currently there is a strict check for making sure that we achieve 0,0,0,3,2,2,0 output for these `state_cli`, `ovs-ofctl`, and `mobility_cli.py` outputs respectively. 

NAT -
  * SANITY - Pass
  * FEATURE - [Fail](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/feature/test_result_1.6.0-1625592603-1f26ba81_2021-10-01%2015:00:30.html)
  
Non-NAT - 
  * SANITY - [Fail](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/sanity/test_result_1.6.0-1625592603-1f26ba81_2021-09-30%2011:58:37.html)
  * FEATURE - [Fail](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/feature/test_result_1.6.0-1625592603-1f26ba81_2021-10-01%2014:59:03.html)

Magma logs are in the above logs. They are for the entire run of the test suite. (click on the top left hand corner of the screen to download the magma logs). 

**Expected behavior**
NAT Scenario in 1.6.0 and in 1.7.0 passes consistently. non-NAT 1.7 however also [fails](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/sanity/test_result_1.7.0-1632182938-0073ffd9_2021-10-01%2016:58:57.html). 

1.7 Feature was [passing](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/feature/test_result_1.7.0-1632278348-9baf09db_2021-09-22%2001:00:03.html) till 9/22 but since then we have regressed and mostly in the states section. [Failures](http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/feature/test_result_1.7.0-1632966807-9c186ea2_2021-10-03%2001:00:02.html) on 10/3

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by sudhikan** [comment]
cc: @milapjoshi @markjen @pshelar @aswin-alexander

**Comment by pshelar** [comment]
@sudhikan can you show was is state of `state_cli, ovs-ofctl, and mobility_cli.py` services at end of the run?

**Comment by sudhikan** [comment]
@pshelar @ulaskozat @aswin-alexander - 

Update on non-NAT: 

* We identified an issue on the DHCP server where `dhcpd` sends a ping request towards an assigned IP and if it doesn't get a response back, it will assign the IP address. It is plausible that because of this setting we were assigning duplicate IP addresses causing us to have issues when assigning IPs. 

We debugged this by testing on `1.7` with the multi APN setup using just DHCP ip alloc and noticed that life was good. Comparing the DHCP server instances between the multi-apn setup and the setup used for this validation, we noticed that `ping` check was the only thing differentiating the two instances. Removing the ping check, we were able to get TC005_SANITY to pass consistently. 

![image](https://user-images.githubusercontent.com/38921899/135918745-57a9c143-6bcb-4c1a-89e3-cb7b7ebaed58.png)

Keeping the issue open for potential issues on the NAT side. Upgrading to latest 1.6.1 to re-test and report back here.

**Comment by pshelar** [comment]
@sudhikan the ping response for UE IP is not guaranteed, so AGW can not support such option.

**Comment by sudhikan** [comment]
@pshelar agreed.

**Comment by pshelar** [comment]
@sudhikan can we close this issue?

**Comment by sudhikan** [comment]
Will reopen if necessary; but for now this seems to be resolved on v1.6.1
