### ISSUE TITLE
[NMS][QOS Policies] Tracking type is incorrect in table vs in the policy

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9442]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6.1 (orc8r 1.7)
- **Affected Component:** Access Gateway, and NMS
- **Affected Subcomponent:** policydb and sessiond
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

* NMS -> Policies -> Policy -> Tracking: Shows that the tracking type is set to `OCS_Only` however in the table it shows `NO_TRACKING`. 
 
![image](https://user-images.githubusercontent.com/38921899/135939139-4142e7bd-48e8-4738-afd9-a60d203ab27f.png)
![image](https://user-images.githubusercontent.com/38921899/135939154-bab568df-3b91-454d-8a44-f4929dba257b.png)

* Policydb on AGW shows that the policies are indeed set to `NO_TRACKING`. This value does not change. 

```
root@u-160-161-nonnat:/home/magma# state_cli.py parse policydb:rules | grep -i tracking
tracking_type: NO_TRACKING
tracking_type: NO_TRACKING
root@u-160-161-nonnat:/home/magma# state_cli.py parse policydb:rules | grep -i tracking
...
All UDP 1
id: "All UDP 1"
priority: 1
flow_list {
  match {
    ip_proto: IPPROTO_UDP
    direction: DOWNLINK
  }
}
flow_list {
  match {
    ip_proto: IPPROTO_UDP
  }
}
qos {
  max_req_bw_ul: 500000
  max_req_bw_dl: 500000
  qci: QCI_9
}

All HTTP 1
id: "All HTTP 1"
priority: 1
flow_list {
  match {
    ip_proto: IPPROTO_TCP
  }
}
flow_list {
  match {
    ip_proto: IPPROTO_TCP
    direction: DOWNLINK
  }
}
qos {
  max_req_bw_ul: 500000
  max_req_bw_dl: 500000
  qci: QCI_9
}
```

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by sudhikan** [comment]
@themarwhal thoughts on this? 

cc: @milapjoshi

**Comment by themarwhal** [comment]
@HannaFar / @andreilee any guesses as to why off the top of head?
