### ISSUE TITLE
[HIL] logs consolidation for mme and syslog

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#9464]
### Your Environment (If applicable)

- **Version:1.6.x or master
- **Affected Component:** AGW
- **Affected Subcomponent:** mme, GRPC, sctpd

### Describe the problem
1) As of now mme logs are going in its separate file at /var/log/mme.log and all other magma process goes in syslog. this separation create difficulty while debugging problem.
==> Proposal is to send mme.log in syslog

2) As of now mme logs is putting lot of output for INFO level. with scale or prod this may cause issue. 
==> proposal is to limit mme log for INFO level

3) As of now sctpd debug level is hardcoded to 'DEBUG' level in code. 
==> proposal is to have this log level configurable for sctpd so that correct level can be set for prod and scale testing

4) GRPC logs, if possible, can also go in syslog. this would allow debug inter-process timeout and their corresponding failure handling.

**Comment by ekowtaylor** [comment]
@milapjoshi do you want this tabled for discussion at the  next backlog grooming session?

**Comment by ekowtaylor** [comment]
@ulaskozat will discuss with @ssanadhya about next steps
