### ISSUE TITLE
GitHub Actions does not include as many tests as CircleCi did 

### ISSUE THREAD

**Issue by uri200** [magma/magma#9480]
CircleCI was running cwag integ test every time we merge code from AGW or FEG into master. GitHub action is not running. 

Cwag integ test is specially critical for any changes in sessiond or session_proxuy

**Comment by quentinDERORY** [comment]
The cwag integ test is still running on circle ci.
We did not yet migrate it to github actions.
For the trigger It's still on every PR merge on master: https://app.circleci.com/pipelines/github/magma/magma?branch=master (you can see it under cwag)

**Comment by uri200** [comment]
Thanks! Now I see it. I thought it was migrated completely

![image](https://user-images.githubusercontent.com/16157139/136262291-ee795cc6-1dce-43af-8a0c-1b1e55ec10a2.png)
