### ISSUE TITLE
Save labels not assigned by autolabel PR before resetting them

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#9512]
In the Autolabel PR job, we are wiping every labels on every run.
This wipes ou the labels that people put and the sizing label too.

To address that, we should save all non component  labels, find the new component labels and then reassign the new component labels and the ones that were not assign by this job.

**Comment by quentinDERORY** [comment]
Make sure to not call the set API if there are no changes in label. It will permit to not overload the gha UI

**Comment by ranj8work** [comment]
- First retrieve the labels on the PR
```
github.issues.listLabelsOnIssue({
  owner,
  repo,
  issue_number,
});

```
- Get the non-component labels (ex: size, type, product etc..)
- Update the labels with the component ones and the non-component's using github.issues.setLabels()

**Comment by quentinDERORY** [comment]
Sounds good but just add one step: If the new set of labels is the same as the old one, do nothing at the end

**Comment by ranj8work** [comment]
Thanks @quentinDERORY will do like we discussed. We will have the component labels controlled and applied by the workflow logic we have today and also ensure the NON-component labels (ex: size, type, product etc..) applied manually are retained on the PR.

**Comment by ranj8work** [comment]
I fixed the issue and tested it in a test [PR](https://github.com/ranj8work/magma/pull/2) of my forked repo. The last action [log](https://github.com/ranj8work/magma/actions/runs/1400835508) shows the execution and you can see it ensured the non-component labels (bug, documentation) are not removed now.
I will raise official PR early next week once after my current PRs in the pipeline are merged to the base.
Please reach out to me if you have any questions.
