### ISSUE TITLE
(pipelined) Scalable test with pipelined_cli.py script to test multiple sessions creation/deletion for 4G and 5G

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9525]
(pipelined) Scalable test with pipelined_cli.py script to test multiple sessions creation/deletion for 4G and 5G

**Comment by Balaji-Jatla** [comment]
Scalable test with pipelined_cli.py script to test multiple sessions creation/deletion is done for 4G. Actual attach rate = 20 UEs per sec and Actual detach rate = 47 UEs per sec. Please find the below text file for reference. 
[https://app.zenhub.com/files/170803235/01a85d9d-40f7-40c0-8839-7575d679683e/download](https://app.zenhub.com/files/170803235/01a85d9d-40f7-40c0-8839-7575d679683e/download)

**Comment by Balaji-Jatla** [comment]
Tested the 4G script with 5000 iterations the Actual attach rate = 46 UEs per sec and Actual detach rate = 46 UEs per sec.

And also tested the 5G script with 5000 Iterations Actual attach rate = 46 UEs per sec and Actual detach rate = 48 UEs per sec , please find the below log files for reference.

(https://app.zenhub.com/files/170803235/11cd83cb-3b2a-4236-985c-a57fde205879/download)

(https://app.zenhub.com/files/170803235/e232b044-99aa-4ef7-9027-74caecebc16b/download)

**Comment by prabinakpattnaik** [comment]
Attached 4g and 5g scalability logs. Hence  will close this task.
