### ISSUE TITLE
AUSF Support - Orc8r changes(Swagger, obsidian handlers) to handle suciProfiles configured per network.

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#9544]
Updated create/update network REST APIs to handle SuciProfiles.
Update obsidian handlers to parse the payload and add in DB.
Add unit testcases for the changes.

**Comment by Abhishek-R15** [comment]
PR is submitted for review
https://github.com/magma/magma/pull/10209

**Comment by Abhishek-R15** [comment]
PR has been approved by Hunter, waiting for PR #10382 to merge.
