### ISSUE TITLE
[Feg] [1.6] : Sessionproxy goes silent preventing new subscribers from getting attached to AGW

### ISSUE THREAD

**Issue by sourabh-nanoti** [magma/magma#9564]
In one of the production deployments, i observed that post certain duration, the session proxy is not able to send out  any requests towards PCRF. I also tried taking a pcap and nothing is sent out on the wire. 
PCRF is not TCP connection and not even a SYN is attempted. 

Please see the log attached. 

[session_proxy_logs_7Oct_Night.log](https://github.com/magma/magma/files/7305182/session_proxy_logs_7Oct_Night.log)
Line # 10940 is where the last CCA is received 
[session_proxy_logs_7Oct.log](https://github.com/magma/magma/files/7305183/session_proxy_logs_7Oct.log)
Line #18391 is where the last CCA is received. 

Restart of the session proxy container fixes the issue and i can see traffic on the wire again.

**Comment by sourabh-nanoti** [comment]
cc @uri200

**Comment by ulaskozat** [comment]
cc @ekowtaylor and @aswin-alexander

**Comment by sourabh-nanoti** [comment]
I upgraded the  Feg to  the latest master dated 8thOct and i have not observed the issue since past 3 days. 
The last feg was from master branch dated 24th Aug where i was seeing the issue within 12 hrs. 
I will monitor this a few more days and then close if everything ok.

**Comment by blueCARDSS** [comment]
@sourabh-nanoti which oCS do you use for production!

**Comment by uri200** [comment]
Note we did some changes to recover connection on diameter client when we fixed this issue https://github.com/magma/magma/issues/7496 (see associated PR)

Also, you can check FEG version using ` docker-compose exec magmad show_gateway_info.py`
```
magma@magma-fedgw:/var/opt/magma/docker$ docker-compose exec magmad show_gateway_info.py

Hardware ID
-----------
b5d0cf72-56a6-4433-a00e-86ae5c445770

Challenge key
-------------
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEDwaahIb5pd9bmLUHopNGzwabGSXXuDA9DigD9lMphtT3PsK0w1gukSC0WAOVhF6McwchRyiLtt537R3hxHICqVYACe1hx/v6JD+0oqPAKYDoIQSTIwzflZB5eitMKatA

Build info
-------------
 Commit Branch: master
 Commit Tag:
 Commit Hash: 00227f6
 Commit Date: 2021-10-29 10:26:01 -0700

```
