### ISSUE TITLE
[AGW] Pipelined service constantly restarting

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#9570]
### Your Environment

- **Version:**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Orchestrator, AGW, FeG
- **Deployment Environment:** cluster (orc8r), AGW Ubuntu in OpenStack, Federated LTE Network, FeGW and Federation Network

### Describe the Issue
we did an upgrade to fix the "echo response" issue but after we try to restart services, the pipelined service is restarting repeatly. The changes in the AGW was following this issue and comming [here](https://github.com/magma/magma/issues/9049). This is the version of Magma and OVS. Also, some pipelined logs are attached.

```
magma@agw-magma-backup:~/packages_AGW_20211006$ dpkg --list | grep magma
ii  magma                                1.7.0-1633384771-d0b4cdcc             amd64        Magma Access Gateway
ii  magma-cpp-redis                      4.3.1.1-2                             amd64        Redis C++ client library
ii  magma-libfluid                       0.1.0.7-1                             amd64        Libfluid Openflow Controller
ii  magma-libtacopie                     3.2.0.1-1                             amd64        TacoPie C++ library
ii  magma-sctpd                          1.7.0-1633384771-d0b4cdcc             amd64        Magma SCTPD

magma@agw-magma-backup:~$ dpkg --list | grep openvs
ii  libopenvswitch:amd64                 2.14.3-13                             amd64        Open vSwitch common components
ii  openvswitch-common                   2.14.3-13                             amd64        Open vSwitch common components
ii  openvswitch-datapath-dkms            2.14.3-13                             all          Open vSwitch datapath module source - DKMS version
ii  openvswitch-switch                   2.14.3-13                             amd64        Open vSwitch switch implementations
ii  python3-openvswitch                  2.14.3-13                             all          Python bindings for Open vSwitch
```

Here the logs of pipelined service: 
[pipelined.log](https://github.com/magma/magma/files/7306735/pipelined.log)

Can help to take a look at this, please? We think maybe is a issue related some missing python packages.

**Comment by pshelar** [comment]
This issue is not reproducible.
