### ISSUE TITLE
[Proposal]Magma release cadence 

### ISSUE THREAD

**Issue by shanku9** [magma/magma#9577]
# Establishing a formal cutoff day to include all code changes before magma release validation

## Problem
During a new magma release, the following benchmarking is done:
- Sanity, Performance, Availability 
- Baremetal Installs 
- Upgrade/Downgrade 
- Soak tests 

Last minute changes have negatively affected to our ability to assess the readiness of releases and impacted our ability to do long duration testing

## Solution

Establish a clear cutoff day for each new release before kicking off testing.
Last Wednesday of every sprint can be setup as the code freeze for testing to begin. This gives more time to validate the build thoroughly and identify potential bugs that are induced over a longer period of time

**Comment by aswin-alexander** [comment]
TODO @ekowtaylor, @jaredmullane and I will get back with the updated release process mid next week

**Comment by hcgatewood** [comment]
Fully in favor of this proposal! That said, I think it fits best within a general, top-down description of how we should do releases given our current constraints -- that way we know what the cutoff day should be, etc

Will leave to @aswin-alexander for next steps on this proposal!

**Comment by lucasgonze** [comment]
Stale
