### ISSUE TITLE
Sentry Fatal Error: SIGSEGV /SEGV_MAPERR 

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#9586]
Sentry has received this event with phy-u6 AGW running  1.6.1-1633382405-5d6fa069

https://sentry.io/organizations/lf-9c/issues/2698712047/?project=5754002&referrer=slack

- **Version:**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

we would probabally need help to understand if this is due to eventd crashing due to python module or new issue.

**Comment by aswin-alexander** [comment]
cc @ulaskozat
