### ISSUE TITLE
Merging of FEG and AGW images

### ISSUE THREAD

**Issue by rmeleromira** [magma/magma#9589]
# Merging of FEG and AGW images

## Problem

Currently the images for FEG and are built separately and live as two different images.

## Solution

Create a single build for gateway_c and gateway_python images that can be shared in containerized environments.

**Comment by hcgatewood** [comment]
Is this proposal to fully share 1 image between the 2 gateways, or share a base image between the 2 and the final images are still separate? My assumption is the latter, but lmk

My understanding is that the shared code between FeG and AGW is the orc8r/gateway code (ref: https://magma.github.io/magma/docs/next/orc8r/architecture_modularity#modules). And specifically, that's all Python code. Let me know if those descriptions are inaccurate

With that as context, I do think, conceptually, it would be a nice win to provide a Magma gateway Python base image. Lmk your thoughts!

**Comment by hcgatewood** [comment]
@arunuke let's plan to have you present this proposal at the Nov 1 TSC meeting

http://bit.ly/MagmaPublicCalendar

**Comment by hcgatewood** [comment]
Closing in favor of https://github.com/magma/magma/issues/10498
