### ISSUE TITLE
mme crash due to UE context Release Complete received in Incorrect S1AP UE state in MME

### ISSUE THREAD

**Issue by sarathbrp** [magma/magma#96]
mme crash in this scenario,

1. Attach
2. goes to Idle mode (for user inactivity) or transport resource unavailable.
3. UE triggers Initial UE message with Service Request, MME responds with Initial Context Setup Resoponse.
4. enodeb triggers S1Ap error indication with unknown-mme-ue-s1ap-id
and here mme crashes.

Please find the wireshark logs. 

Thanks,
SP

**Comment by sarathbrp** [comment]
[mme_crash_issue_96.zip](https://github.com/facebookincubator/magma/files/2984938/mme_crash_issue_96.zip)

**Comment by sarathbrp** [comment]
[mme_crash_logs.zip](https://github.com/facebookincubator/magma/files/2985369/mme_crash_logs.zip)

**Comment by anooptomar29** [comment]
I have looked at the pcap and logs. Logs are misleading. Essentially MME is not crashing due to error indication. It is crashing due to reception of UE Context release complete is received in incorrect state.

**Comment by anooptomar29** [comment]
Can we please update the title of issue ? cc @sarathbrp

**Comment by sarathbrp** [comment]
Can we add some check for wrong UE state, so that it won't crash MME.

**Comment by ssanadhya** [comment]
Below is BT for the crash with the DevAssert highlighted

********************************************************************************
(gdb) c
Continuing.
[New Thread 0x7fe1d3afb700 (LWP 18575)]
[New Thread 0x7fe1d32c6700 (LWP 18576)]

Thread 18 "ITTI 7" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fe1d7c6f700 (LWP 18370)]
0x00005577149de648 in s1ap_mme_handle_ue_context_release_complete (assoc_id=45, stream=2, message=0x7fe1d7c6e9e0)
   at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:1415
1415      **DevAssert(ue_ref_p->s1_ue_state == S1AP_UE_WAITING_CRR);**
(gdb) bt
#0  0x00005577149de648 in s1ap_mme_handle_ue_context_release_complete (assoc_id=45, stream=2, message=0x7fe1d7c6e9e0)
   at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:1415
#1  0x00005577149d65c5 in s1ap_mme_handle_message (assoc_id=45, stream=2, message=0x7fe1d7c6e9e0)
   at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:240
#2  0x00005577149cddac in s1ap_mme_thread (args=0x0) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:156
#3  0x00007fe1ea78a494 in start_thread (arg=0x7fe1d7c6f700) at pthread_create.c:333
#4  0x00007fe1e74ffacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb)

**Comment by ssanadhya** [comment]
Resolved with commit a3e81fcce65cfefe778234e897feede41e696fa7
