### ISSUE TITLE
Inability to use some browsers and app on magma 1.5

### ISSUE THREAD

**Issue by obensouda** [magma/magma#9600]
We recently deploy magma 1.5 and are using airspan airhamony 4000 enodeb. We find that in some cases the suggested MTU value of 1400 is not honored by the UE. The UE defaults to 1500. In such cases we are unable to browse as segmented packets are not sent to the enodeb by magma.

We found that traffic works normally when we force the MTU on the laptop to 1372 or raise the MTU between the enodeb and agw to 1600 or higher. We have been advised by airspan that it is better to keep the MTU at 1500. We would appreciate any tips. We think that magma is not able to handle segmented packets when the UE uses an MTU that is higher than the suggested MTU value . Our guess is that there is an interface within magma that is dropping these packets.

**Comment by pshelar** [comment]
@obensouda  are you using NATed datapath?

are you seeing packet drop for UDP or TCP?

**Comment by obensouda** [comment]
hi @pshelar currently we see the behavior on udp and tcp. We are able receive the fragmented udp packets from internet to AGW but the first fragmented packet never leaves AGW to enodeb. 

We wondering if the issue might be that the WAN ip has an MTU of 1500 and magma is not able to fragment packets to fit into suggested MTU 1400.?

**Comment by pshelar** [comment]
ok, Thanks for the info.
Can you increase MTU of S1 link? on AGW S1 interface and eNB interface to 1600 ?

**Comment by obensouda** [comment]
yes we tried that and it worked. However Airspan said that they do not recommend changing MTU on the eNB as they have not tested this configuration. So we looking to see if there is another solution or if this is a know issue with expected fix.

**Comment by pshelar** [comment]
That is recommended solution. 
AGW datapath does not fully support PMTU discovery, so we depend on right MTU on S1 AP link.
For TCP AGW does set MSS clamping, so you should not see any issue for TCP sessions.

**Comment by obensouda** [comment]
@pshelar thank you for this. We do see similar issues for TCP sessions. Infact that is what got us looking for solution. Do we have to enable MSS clamping on upstream router?

**Comment by pshelar** [comment]
MSS clamping is already done on AGW. Can you redue MTU on SGi (eth0) interface to 1400?

**Comment by obensouda** [comment]
Quick update on this ticket in case anyone else runs into the issue. Reducing SGi interface to 1400 did not help. We found that some UE were not able to reassemble tcp packets received causing packet loss.

The only solution that worked for us was to finally change MTU on enodeb to 1600 and AGW S1 interface to 1600 to allow ue to use 1500 mtu.
