### ISSUE TITLE
Contributor Guide Improvements

### ISSUE THREAD

**Issue by ildikov** [magma/magma#9601]
# Contributor Guide Improvements

## Problem

The Magma community has put together an initial documentation to help new contributors to maintain and enhance the Magma codebase and related documentation. To further improve the contribution process and help new contributors to come on board this proposal suggests to refactor and extend the current documentation to form a Contributor Guide that is applicable to more types of contributions than just code.

Areas to improve in the current docs:
* The current documentation mainly covers the code development workflow and the architecture of the Magma components
* The guidelines to add or improve documentation is hidden under the code contribution conventions and is very hard to find
* The detailed proposal process is hidden under the 'Proposals' section in the documentation while it should be part of the contributor guidelines to make it easier to find and follow
* Currently there is no clear documentation that provides an overview of the contribution process in general
* The documentation doesn't outline the required accounts that are needed to be set up in order to be able to contribute
* Currently it is unclear what tools the community is using to maintain and enhance the project's code base and artifacts

## Solution

This issue is proposing to refactor the existing contributor documentation to make it easier to follow and find information in.

As an addition, the current documentation should be extended to form a Contributor Guide to hold all information in one place that a contributor needs in order to be able to participate in the project and help the community to achieve its mission and goals.

Suggested sections to cover in the new Contributor Guide:
1. Introduction
2. Overview of the Magma governance and community structure
3. Communication tools and processes
4. Overview of the contribution workflow
5. Tools overview (if not covered in the previous sections)
6. Accounts setup
7. Tracking and fixing bugs
8. Adding and tracking proposals
9. Contributing code
  9.1 Overview of programming languages
  9.2 Development environment
  9.3 Coding guidelines
  9.4 Testing your code locally
  9.5 Testing your code upstream (CI/CD, GitHub Checks)
10. Contributing documentation

## Next steps outline
AP for Ildiko to fill this out

## Non-goals

- Add a link to the Deployment Guide from the Intro and Development Env sections, BUT this guide will not cover the deployment guide improvements

## Next Steps

- Create an umbrella task that covers the restructuring of the Contributor Guide to what we agreed on in this issue
- Create tasks to cover the sections in the new guide to allow multiple people to participate in contributing to and shaping the document
- The umbrella task should contain pointers to the sub-tasks to make sure that we have good visibility into what is in progress and what still needs to be covered

## Contributors

- @ildikov to create the umbrella task to capture the new document structure and tasks

**Comment by dcheline** [comment]
This looks great!   Perhaps we should also have a download link (or page) where one can download AGW or or8r sw including the binaries that have been pre-created.

**Comment by hcgatewood** [comment]
This looks awesome! Thanks @ildikov for all your hard work 🙂 

What are your thoughts on immediate next steps? In my mind, I'm thinking a DRI to begin drafting these pages -- do you have anyone in mind?

**Comment by ildikov** [comment]
Hi Hunter,

Thank you for the nice feedback.

Can you please help me out with what ‘DRI’ stands for here? :)

When we discussed the topic on the last Magma Contributor Experience and Onboarding call we agreed to start fleshing out the details in a proposal, aka a GH issue that I created since, and create a plan that has well-defined tasks for people to pick up. In that sense, if we can agree on the placement of the document and the high level structure then we can have people signing up to write chapters or sections of it, depending on where their expertise are. We all preferred this route to ensure that anyone, who is interested in improving the guide, can contribute and help out with writing it.

We will review the issue on the next call tomorrow (October 14, at 8:30am Pacific) where I hope that people will have feedback to the currently outlined table of contents.

Placement can be a challenge, I think we need to make sure that the document is visible and easy to find. So I assume it should either be a top level segment in the Docusaurus or maybe a standalone document. It is also a question we would need some feedback on.

Once the above two items are settled I will document that in the GH issue and from there we can move ahead with implementation. I will also check tomorrow if we have some volunteers to pick up some of the parts.

What do you think?

Thanks,
Ildikó

**Comment by electronjoe** [comment]
@ildikov Designated Responsible Individual (DRI) - a term used in FB frequently.

@hcgatewood I believe @ildikov has proposed that upon agreeing to the some document set / layout (per above) - we would open up contribution to individual documents to the community / solicit volunteers vis-a-vis the semi-weekly `Magma Contributor Experience and Onboarding` [Meetings](https://calendar.google.com/calendar/embed?src=c_gbiu1t7a67ika1th2smldeh19s%40group.calendar.google.com&ctz=America%2FChicago). Am I summarizing correctly? Edit: yes indeed, this is in Ildiko's reply directly above - my bad. `Once the above two items are settled I will document that in the GH issue and from there we can move ahead with implementation. I will also check tomorrow if we have some volunteers to pick up some of the parts.`

**Comment by ildikov** [comment]
Re DRI: Got it. :) I think it would be better to avoid introducing new acronyms especially if they are Facebook specific for inclusivity. Since Magma is a telco-focused project I think we have enough to keep track of already...

As I opened this PR I envisioned that also entails to "volunteer" to be the cat herder, which I still intend to do/continue. But other than that my intention is to involve the community as much as we can both in terms of weighing in on the proposal as well as picking up tasks.

@electronjoe I think we're on the same page, thanks for the summary!

**Comment by hcgatewood** [comment]
Okay awesome. So then in terms of concrete next steps, I'm envisioning:

- Create GitHub tasks for each of these, under a top-level task
- @ildikov will shepherd the top-level task, with the idea that community members will progressively take on each sub-task

As far as where to locate this: my thought was it should go under the "Contribute" section of the docusaurus (as a complete reworking of that section), but we should add links to it in a number of places -- on the docs landing page, on the magmacore website, in the slack, etc

Let me know your thoughts @ildikov @electronjoe!

**Comment by ildikov** [comment]
@hcgatewood Yes, that looks like an accurate outline of steps. Let's wait with activation till the contributor meeting tomorrow morning to ensure that we collect all input and feedback. After that we can put the tasks up and people can comment on those and take on what they want to work on. Does that sound good to you?

**Comment by electronjoe** [comment]
Minor feedback!

1. It appears your ordered list accidentally reverted to bullets for a few points in the chain?
1. I wonder if `Adding and tracking new feature proposals` should become `Adding and tracking proposals` or some such, as features are only one type of proposal?

**Comment by sebathomas** [comment]
As someone going through the contributor documentation right now, I think the restructuring looks like a great idea.

One point that seemed a bit strange to me in the Onboarding section is that there's a lot of details about how to set up an IDE for developing in Go but nothing about any of the other languages of the project.

**Comment by ildikov** [comment]
@electronjoe Thanks for catching those issues. I had some indentation challenges in the editor, I fixed it manually now. I expect the actual document might end up being an evolution of the proposal by the time it is done so I wasn't really sweating on that one. Fixed the proposal bullet point too, great point!

@sebathomas Very good point, I think it would be great to highlight what programming languages the project is using. Should we add a dedicated section to programming languages under "Contributing Code"?

**Comment by sebathomas** [comment]
@ildikov Yes, a dedicated section with an overview would be awesome.

**Comment by ildikov** [comment]
@sebathomas Sounds good, I added a section to cover it.

**Comment by hcgatewood** [comment]
Accepted! I am closing the issue to denote it no longer needs a TSC vote, but please feel free to continue using the issue for coordination until the corresponding Issues are created 🙂
