### ISSUE TITLE
Add SPGW state conversion unit testing

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#9603]
SPGW state converter (https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp) needs code coverage by adding unit testing. These are well-contained functions that don't have any dependency to mock/include.

For reference and an example of a state converter unit test, please refer to: https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp

**Comment by ulaskozat** [comment]
@Vyas20 reassigning this to @hcgatewood
