### ISSUE TITLE
[AMF]: Changing the hashtable implementations for UE mgmt in amf to maps

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9610]
The requirement is to change the UE data structures from existing hashtable implementation to cmaps. Reason for the movement is cmaps are in built libraries and faster as compared to hashtables.

As part of it following tables needs to be checked :
   imsi_amf_ue_id_htbl
   tun11_ue_context_htbl
   gnb_ue_ngap_id_ue_context_htbl
   guti_ue_context_htbl

It the code changes are big this task can be further subdivided into smaller tasks.

Reference can be taken from : mme_app_ip_imsi.cpp

**Comment by ganeshg87** [comment]
this issue was resolved as part of #9780
