### ISSUE TITLE
(pipelined): throughput testing of GTP traffic 

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9639]
(pipelined): throughput testing of GTP traffic

**Comment by prabinakpattnaik** [comment]
We have verified the throughput testing of User plane for TCP/UDP traffic using Iperf3.
We have documented the setup details and logs for iperf3 output.

**Comment by prabinakpattnaik** [comment]
https://docs.google.com/document/d/1tm3zsAiSK2gJ6aOwPPigS10UvfmwUlot71uist39ygw/edit
