### ISSUE TITLE
Scale test- AGW is not stable when 200UEs are tried at the rate  of 10 attaches / Sec

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#9655]
### Your Environment

Version:1.7.0-1633728278-844ee0bb
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: Vagrant (AGW)

**To Reproduce**
1. In TVM-GUI go to testcase SA_01_02_03_04_Hyper_Suci.
2. Change the rate to 10(That means triggering 10 UE request/attaches per second) .
3. Trigger the test case with 100 UE attaches.(For 100 UE's test case is passing)
4. Trigger the test case for 200 UE attaches.

 ** Error Noticed **
For 200 UE attaches ,observed some fluctuations in serving request.
When trying multiple times noticed different behaviors. Also noticed that Reg- Request and PDU_Session_Request are getting retried.
Please find the Screen shots attached for your perusal.

**Expected behavior**
All 200 UE attaches should get served.

Note : With same testcase and environment, when tried up to 600 UE attaches with 1 UE/Sec all sessions are coming up.

[https://app.zenhub.com/files/170803235/6bdf8947-912f-4df6-ade7-3c909e2c8dea/download](https://app.zenhub.com/files/170803235/6bdf8947-912f-4df6-ade7-3c909e2c8dea/download)

**Comment by Kaleem-Wavelabs** [comment]
@rupa455wavelabs Please attach the test results collected till now and process. Thanks.

**Comment by Kaleem-Wavelabs** [comment]
Please validate this TC with latest build and process the ticket accordingly

**Comment by panyogesh** [comment]
Closing the issue as its old and for now target is 5 UEs/sec. If there is any issue will raise a new PR.
