### ISSUE TITLE
[HIL] TC010 sanity failed on non-nat setup with core

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#9662]
TC010 - 600UE attached at 3ue/sec and run traffic @500kbps / UE for 3mins.
this test resulted in coredump on 1.6.1 non-nat sanity run.

### Your Environment

- **Version:**1.6.1-1634100297-71f9bccc
- **Affected Component:** Access Gateway mme
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** physical AGW

### Describe the Issue

during the automated sanity test run below core is observed

`Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  get_nas_common_procedure (ctxt=ctxt@entry=0x6210000531c0, proc_type=proc_type@entry=EMM_COMM_PROC_IDENT) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c:73
73	/home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c: No such file or directory.
[Current thread is 1 (Thread 0x7ff3b25f0700 (LWP 205335))]
(gdb) bt
#0  get_nas_common_procedure (ctxt=ctxt@entry=0x6210000531c0, proc_type=proc_type@entry=EMM_COMM_PROC_IDENT) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c:73
#1  0x000055abdc1ac0ce in get_nas_common_procedure_identification (ctxt=ctxt@entry=0x6210000531c0) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c:163
#2  0x000055abdc1c29a3 in identification_t3470_handler (args=0x6210000531c0, imsi64=0x7ff3b25e1988) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/emm/Identification.c:399
#3  0x000055abdc1b5644 in mme_app_nas_timer_handle_signal_expiry (timer_id=105621835869920, cb=0x6020000771e0, imsi64=imsi64@entry=0x7ff3b25e1988)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c:114
#4  0x000055abdbe724e0 in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:275
#5  0x00007ff3bf4355c7 in zloop_start () from /lib/x86_64-linux-gnu/libczmq.so.4
#6  0x000055abdbe729f2 in mme_app_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:532
#7  0x00007ff3c0029609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ff3bee07293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`

core file - http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/cores/core-1634108740-TASK_MME_APP-205312-1.6.1-1634100297-71f9bccc.tgz

logs: - http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/performance/test_result_1.6.1-1633382405-5d6fa069_2021-10-11%2013:24:01.html

**Comment by ssanadhya** [comment]
@milapjoshi , closing this issue since the PR was merged.
