### ISSUE TITLE
Initial context setup request (MME <-> eNB) TEID ipv6 adv

### ISSUE THREAD

**Issue by koolzz** [magma/magma#9687]
We need to add support for ipv6 for this

![244876834_476955763369139_4563719796028722554_n](https://user-images.githubusercontent.com/11281728/137386962-8019b650-81f9-4a0b-9efb-9847ea565221.png)

**Comment by ssanadhya** [comment]
@koolzz , can this be closed?

**Comment by koolzz** [comment]
Oh yeah I’ve implemented it
