### ISSUE TITLE
[NMS][Service Request Failures]

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9701]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.7(ish)
- **Affected Component:** NMS
- **Affected Subcomponent:** Grafana dash
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

Looking at a campus network, according to Grafana, even though there aren't any service request failures, but it seems to peg on the graph anyway. 

Grafana > Networks > Service Requests (Rate) and Service Requests (1h increase) 

It seems that the failures are tracking the total attempts and the successes are half of the failures/attempts. Seems like an error in calculation. 

![image](https://user-images.githubusercontent.com/38921899/137517095-46475db1-e74d-454e-8340-77ceaecd78f7.png)
![image](https://user-images.githubusercontent.com/38921899/137517118-cb4301ba-6604-4ec6-ba85-210cd4ded771.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by aswin-alexander** [comment]
Triage update: Needs further debug at the source. cc @talkhasib
