### ISSUE TITLE
[NMS][FR] File Feedback from UI

### ISSUE THREAD

**Issue by aswin-alexander** [magma/magma#9706]
Please add a file feedback button on the NMS UI that would

- Grab all the required logs 
- Grab screenshot
- Provides dialog box for user to provide description
- Showing PII disclaimer 
- Files a github issue

**Comment by aswin-alexander** [comment]
Triage update: Need a design doc. @electronjoe or @markjen need help please
Need deeper analysis of PII/ privacy for production use cases.

**Comment by electronjoe** [comment]
Do we have more background on the motivation here, and what is proposed?  I'm not clear yet whether this is a "this UI thing is confusing, please change it" type of feedback. Or "this AGW has stale data as seen in this UI and that shell terminal" type of feedback, etc.

**Comment by aswin-alexander** [comment]
Motivation is to

1. Make it easy for users to report issues with the NMS
2. Reduce the back and forth between SWE team and reporter asking for logs/repro attempts
3. Getting a better signal on UX/ workflow challenges

To the scenarios presented, yes to both.
