### ISSUE TITLE
bazel: Generate ASN1C with bazel

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#9710]
So a few things here:

1. This repository (https://gitlab.eurecom.fr/oai/asn1c) hasn't been updated in 4 years. And it hasn't been actively updated since 2013 it seems. Not sure how much this asn1c has diverged from the original asn1c repo: https://github.com/vlm/asn1c
<img width="1288" alt="Screen Shot 2021-10-15 at 6 40 10 PM" src="https://user-images.githubusercontent.com/37634144/137561669-3b5abe72-a7a6-4474-b439-73d9cc335f54.png">

2. Either way, instead of generating the executable inside the Dockerfile, do this with Bazel.

**Comment by Neudrino** [comment]
Maybe overlapping with:
- #11114 
- #11115 
- #11116

**Comment by nstng** [comment]
Close for now as not in scope - can be reopened when it becomes relevant again.
