### ISSUE TITLE
[AMF]: Fixing memory leaks in AMF procedures

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9721]
![Existing-Data-Structure-OCT-19.drawio.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/2d53d4a5-30f6-48fa-a280-81269bdcde9e)![Existing-Place-Holder.drawio.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/dab03072-da4e-449c-96ac-5b0e42b3d941)![Relation-Between-Procedures.drawio.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/4a914d27-0b03-4c44-8565-00b5e21b902b)

Following are the main points observed while integrating AMF procedures with unit testing infrastructure :-

1. When integrating with Unit Test Framework it shows memory leak in couple of places in amf procedures.
2. Additional memory allocation in list infrastructure.
3. Some of memory allocations can be optimized using smart pointers.
4. Fxing allocations which are done using "new ()" operator where as           
 free'ing these variables are done using free() function.
5. Code optimization possible using class based approach (struct treating as class)
6. Removal of the delete_wrapper function as the smart_pointers will do the cleanups.
7. amf_delete_child_procedures () can be simplified as only under registration_procedure all other common pocedure will have same base_proc hence no searching.   

Attaching screenshots of existing struct based procedures 

New Proposal :
  1. Re-visit all existing procedures.
  2. Used shared_ptr whenever possible.
  3. Moving to class based approach (struct behaving as class).

**Comment by panyogesh** [comment]
![New-Class-Based-Procedure-v0.1.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/c3fdaf9a-556e-4576-88bd-55d121046949)

**Comment by panyogesh** [comment]
[https://app.zenhub.com/files/170803235/0d91fdd3-2033-4497-812c-85acdc5907e2/download](https://app.zenhub.com/files/170803235/0d91fdd3-2033-4497-812c-85acdc5907e2/download)

**Comment by ulaskozat** [comment]
@ssanadhya, @ardzoht comment on this please.

**Comment by panyogesh** [comment]
![Relation-Between-Procedures.drawio.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/58462205-9d85-4826-897c-f0197d2b1dc2)

**Comment by ssanadhya** [comment]
@panyogesh, two comments:
1. Why do we need `shared_ptr` here? Wouldn't unique_ptr suffice, since each procedure is only owned by a single UE context?
2. Can we leverage proto messages to define these structures? Those can be easily translated to C++ objects or, in future, to GoLang

**Comment by ardzoht** [comment]
+1 on defining protobuf Messages, this way we extend interoperability between local and saved state and also we can get accessors / setters to each of one of the parameters included on the structures.

**Comment by ssanadhya** [comment]
@panyogesh , note that each of the EMM procedures also have their specific timeout and failure handling functions, which are stored in the C structs as function pointers. There is no equivalent for these in protobuf.
