### ISSUE TITLE
[AMF-SIT]: NGSetupFailure getting generated with Slice Descriptor 0xd143a5

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9722]
Following are the details we got from customer :
  MCC : 724
  MNC : 77
  Slice Type : 01
  Slice Descriptor : d143a5

With the above setting the customer is not able to get the NGSetupResponse (insted NGSetupFailure is received).

Attaching file with details ![Issue-gnb-sdtest0xd143a5.png](https://images.zenhubusercontent.com/60897609f8251d0d2333851b/0f0f514e-63ac-459e-af30-5243f8ddd2e5)

enable5g_features: true
enable_converged_core: true
default_slice_service_type: "1"
default_slice_differentiator: "0xd143a5"

**Comment by NeelimaKalpana** [comment]
With the configurations specified in the Ticket , NGAP connection is successful and PDU-session is also UP.

Following are the specified configurations:
MCC : 724
MNC : 77
Slice Type : 01
Slice Descriptor : d143a5

Please find the attachment for respective logs and pcaps .

[https://app.zenhub.com/files/170803235/7f8b3221-27e3-471d-bcb7-a88373592b3f/download](https://app.zenhub.com/files/170803235/7f8b3221-27e3-471d-bcb7-a88373592b3f/download)
