### ISSUE TITLE
bazel: Add repository dependencies for ZMQ / CZMQ

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#9728]
We currently use `libczmq-dev` in the magma-dev VM.

We will have to manually build https://github.com/zeromq/czmq or just use apt

For an example of an existing custom build of a depndency, see [bazel/external/libtins.BUILD](https://github.com/magma/magma/blob/master/bazel/external/libtins.BUILD)
For an example of an existing wrapper library for a system dependency, see [bazel/external/system_libraries.BUILD](https://github.com/magma/magma/blob/master/bazel/external/system_libraries.BUILD)

## Exit Criteria
1. Have the library built manually (like libfluid) or create a wrapper around the dependency (like folly)
2. For custom BUILD files, it is recommended to build and run a small test to make sure everything is linking properly

**Comment by LKreutzer** [comment]
Currently not needed
