### ISSUE TITLE
[MME bazelification] Remove cyclic dependency between Logging, ITTI and Assertions

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#9732]
@themarwhal noticed the following cyclic dependency across MME libraries and common utils

![mme-dependency-cycle-2](https://user-images.githubusercontent.com/1519854/137773141-33a4dac1-6f07-492c-a50b-bbd557eb109f.png)

**Comment by lionelgo** [comment]
From Marie Bremner:
This dependency cycle is giving me a particularly hard time. I can't seem to figure out how the current CMake config deals with this either  Does anyone have context on why most of itti files are in the lib/itti directory? But I still see some itti prefixed files in common as well (itti_free_defined_msg). This was making me wonder if all itti files used to be under common at some point.
But maybe an easier approach would be to have assertions.h not depend on log.h . Would love any thoughts on this! Thanks

**Comment by lionelgo** [comment]
We can get rid of OAILOG_XYZ in assertions.h and use print functions.  We break one dependency.

**Comment by lionelgo** [comment]
OAI logging is an ITTI task, the only interest for that is that it handles the ITTI TERMINATE_MESSAGE. This dependency can be removed also.

**Comment by themarwhal** [comment]
What is the difference between doing an OAILOG and fprintf? I see that the `_Assert_` macro logs to both `OAI_CRITICAL` and `fprintf`.
https://sourcegraph.com/github.com/magma/magma/-/blob/lte/gateway/c/core/oai/common/assertions.h?L68

@lionelgo

**Comment by lionelgo** [comment]
OAILOG in the early developments could be redirected to stdout, a local file, or a socket.

**Comment by themarwhal** [comment]
Ok, thanks for the information! 
If this sounds reasonable with @ulaskozat / @ardzoht  / @ssanadhya as well, I can remove OAI_XX_LOG etc from assertions.h

**Comment by themarwhal** [comment]
I've added a draft PR of what this change would look like.

**Comment by ssanadhya** [comment]
> Ok, thanks for the information! If this sounds reasonable with @ulaskozat / @ardzoht / @ssanadhya as well, I can remove OAI_XX_LOG etc from assertions.h

@themarwhal , please go ahead and remove the OAILOG_* calls from assertions.h . In its current form the OAILOG prints the Assertion message to `/var/log/mme.log`, while fprintf dumps it in syslog. We can do without the message in mme.log.

**Comment by ssanadhya** [comment]
@themarwhal @lionelgo re-opening this issue so:
1. we can also track the dependency between ITTI and Log
2. @lionelgo can also comment on the OAILOG_* removal change in assertions.h. I think it is okay to redirect Assertion logs (such as Seg Fault instances) to syslog instead of mme.log. What do you think?
