### ISSUE TITLE
NMS subscribers' search/filter with inconsistent return for 'Name' and 'Actions'

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#9733]
### Your Environment

- **Version:** 1.6
- **Affected Component:** NMS
- **Affected Subcomponent:** Subscribers module
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

Wrong subscriber's name after searching/filtering it through the NMS subscribers page, and 'Actions' links not opening/redirecting properly to the corresponding pages. 

**To Reproduce**
1. Go to 'NMS>Subscribers>Config>Search...'
2. Input an IMSI to search/filter the target subscriber (see screenshots below as an example)
3. See the incorrect name: it shows the IMSI again and not the name
4. Try to 'View' or 'Edit' the subscriber through the 'Actions' column

**Expected behavior**
The subscriber's name should be shown as is, and the 'Actions' links should open/redirect properly to the corresponding pages.

**Screenshots**

Take the highlighted subscriber as an example in order to search/filter it:

![Captura de Tela 2021-10-18 às 13 52 58](https://user-images.githubusercontent.com/6054708/137775344-b1e4eeea-a076-43ae-aa5f-dc11d32c40f5.png)

The subscriber's name is shown incorrectly. Also, if the subscriber page (https://<tenant>.nms.freedomfi.com/nms/<network>/subscribers/overview/config/<imsi>/overview) has never been visited, click on any 'Action' item ('View', 'Edit' etc.) still filters, redirects to a blank page (maybe related to the React states).

![Captura de Tela 2021-10-18 às 13 55 54](https://user-images.githubusercontent.com/6054708/137775356-50ed312e-5259-4db5-9622-5ffa97cae7ee.png)

**Comment by Neudrino** [comment]
Maybe correlated to subscriber table data bug: https://github.com/magma/magma/issues/8951.
