### ISSUE TITLE
[AGW][IPFIX]Connectiond service doens't start after host reboot

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9745]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6.1
- **Affected Component:** AGW
- **Affected Subcomponent:** `connectiond`
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

`connectiond` service is deployed for IPFIX records. On more than a few occasions, the service has been in the "stopped" state. I was able to confirm this that the service doesn't come up after a host reboot. 

The service has been added to: 
magmad.yml -> magma_service -> connectiond
magmad.yml -> services_to_restart -> connectiond

**To Reproduce**
1. Reboot AGW which has connectiond running
2. post reboot check `sudo service magma@connectiond status`. It will be in stopped state.

**Expected behavior**
Connectiond service to persist post reboots. 

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by koolzz** [comment]
Should be mitigated by https://github.com/magma/magma/pull/9857, just ned to include connectiond in services to restart. Still checking why service receives sigterm shortly after reboot
