### ISSUE TITLE
IMEI handling - format issues of User-Equipment-Info-Value

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#9758]
### Your Environment

- **Version:**1.5
- **Affected Component:** AGW/FEG
- **Affected Subcomponent:** AGW/FEG
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

At one of our site the requirement is to use IMEI to be parsed at OCS for specific service. However the format of IMEI sent in CCR-I doesnt seem to be a standard one and for that reason seems difficult to be parsed at peer end.

**Expected behavior**
The IMEI format should follow standard format.

**Screenshots**
Magma AGW:
![image](https://user-images.githubusercontent.com/77636702/137941604-093601c3-70fc-4b86-bb34-daa76cdb974b.png)

Nokia GGSN:
![image](https://user-images.githubusercontent.com/77636702/137941694-985df533-627b-4a9a-9ca9-a8815dbd3951.png)

**Additional context**
Traces Attached
[PCAPs.zip](https://github.com/magma/magma/files/7374979/PCAPs.zip)

**Comment by shehzadalee** [comment]
Hi @talkhasib 
Could you please help us with this issue?

Thanks

**Comment by talkhasib** [comment]
@uri200 might wana look at this

**Comment by uri200** [comment]
Thanks @sanazbazargan  for including the pcaps. That helps us to debug the issue and compare with other vendors. 

I am looking into this. Maybe the IMEI format magma AGW is sending is not proper. Will update soon

(create session request sent by mme to sessiomd)
![image](https://user-images.githubusercontent.com/16157139/138944019-c660dccd-b3a1-49f6-8e34-4abe9d5d1bf4.png)

**Comment by uri200** [comment]
Hey @sanazbazargan on your Magma PCAP, can you confirm which should be the proper decoded value of the IMEI. Is this the correct IMEI `04000904010705030307070600000000`

Note we do not send IMEISV


![image](https://user-images.githubusercontent.com/16157139/138947915-13cd5af6-fdc3-4df2-8feb-db60f41b2e46.png)

7.1.17 User-Equipment-Info AVP
https://www.etsi.org/deliver/etsi_ts/132200_132299/132299/15.03.00_60/ts_132299v150300p.pdf

6.2 Composition of IMEI and IMEISV 
https://www.etsi.org/deliver/etsi_ts/123000_123099/123003/16.03.00_60/ts_123003v160300p.pdf

**Comment by uri200** [comment]
Some more info. 

- This is the value comming on S!AP message
```
3571490400677300
```
![image](https://user-images.githubusercontent.com/16157139/139190683-a7188c85-a67d-482e-8d63-c7390bd6c53f.png)


- This is the value mme sends to sessiond 
```
Oct 27 21:54:14 ubuntuAGW sessiond[3071932]:       rat_specific_context {
Oct 27 21:54:14 ubuntuAGW sessiond[3071932]:         lte_context {
Oct 27 21:54:14 ubuntuAGW sessiond[3071932]:           spgw_ipv4: "172.16.10.101"
Oct 27 21:54:14 ubuntuAGW sessiond[3071932]:           imei: "\004\000\t\004\001\007\005\003\003\007\007\006\000\000\000\000"
Oct 27 21:54:14 ubuntuAGW sessiond[3071932]:           plmn_id: "00101"
```

- This is the value session_proxy receives at feg
```
session_proxy    |      "rat_specific_context": {
session_proxy    |              "lte_context": {
session_proxy    |                      "spgw_ipv4": "172.16.10.101",
session_proxy    |                      "imei": "\u0004\u0000\t\u0004\u0001\u0007\u0005\u0003\u0003\u0007\u0007\u0006\u0000\u0000\u0000\u0000",
session_proxy    |                      "plmn_id": "00101",
session_proxy    |                      "imsi_plmn_id": "99999",
```

- This is the Useer-Equipement-Info-Value AVP
```
04000904010705030307070600000000
```

![image](https://user-images.githubusercontent.com/16157139/139190840-6b468b32-800c-4993-a722-b2cd1caf696a.png)

**Comment by uri200** [comment]
Hey @shehzadalee  this issue should be fixed with this pr https://github.com/magma/magma/pull/9947
