### ISSUE TITLE
Service restart after changed the use_stateless to False

### ISSUE THREAD

**Issue by lsguima** [magma/magma#9774]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version: 1.7.0-1633009790-60b96438
- **Affected Component: Access Gateway
- **Affected Subcomponent: AGW service
- **Deployment Environment: AGW Virtual Machine

### Describe the Issue

We are testing the AGW with a gnb Nokia and after changed the configuration from use_stateless to False, the AGW services are restarting / MME failed.

magma@magma:~$ cat /etc/magma/mme.yml 
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

log_level: INFO
s11_iface_name: "eth1"  # 'mme_s11_ip' will be filled automatically
remote_sgw_ip: "192.168.60.153" # IP Address of the remote IP for S11
s1ap_iface_name: "eth1"  # 's1_ip' will be filled automatically
realm: "magma.com"
conf_dir: "/var/opt/magma/tmp"
cert_dir: "/usr/local/etc/oai"
hss_ip: "192.168.60.153"
hss_hostname: "hss"
use_stateless: false
use_ha: false
enable_gtpu_private_ip_correction: false
enable_apn_correction: false
apn_correction_map_list:
        - imsi_prefix: "00101"
          apn_override: "magma.ipv4"

s1ap_zmq_th_us: 2000000  # delay threshold used for dropping initial UE message
mme_app_zmq_congest_th_us: 100000  # delay threshold used for rejecting attach requests
mme_app_zmq_auth_th_us: 200000  # delay threshold used for dropping Authentication Complete
mme_app_zmq_ident_th_us: 400000  # delay threshold used for dropping Identification Complete
mme_app_zmq_smc_th_us: 1000000  # delay threshold used for dropping SMC Complete
accept_combined_attach_tau_wo_csfb: true

enable5g_features: true
enable_converged_core: true
default_slice_service_type: "1"
default_slice_differentiator: "0xd143a5"

+------------------------------------------------------------+
|                        Magma status                        |
|                 1.7.0-1633009790-60b96438                  |
+------------------------------------------------------------+
| Subscribers connected: 0                                   |
+------------------------------------------------------------+
|       control_proxy: active                                  |
|                 ctraced: active                                  |
|             directoryd: active                                  |
|                     dnsd: active                                  |
|               enodebd: active                                  |
| envoy_controller: inactive                                 |
|                  eventd: active                                  |
|                   health: active                                  |
|               magmad: active                                  |
|                      mme: failed                                  |
|            mobilityd: inactive                                  |
|               pipelined: failed                                  |
|               policydb: active                                  |
|                     redis: active                                  |
|           sessiond: inactive                                  |
|                   smsd: active                                  |
|                     state: active                                  |
|      subscriberdb: active                                  |
+------------------------------------------------------------+

**Comment by ardzoht** [comment]
What is the status of MME service? Can you run `sudo systemctl status magma@mme` and `sudo journalctl -n 100 -fu magma@mme` and post the output, current description doesn't lead to much insight.

**Comment by lsguima** [comment]
Hi...Mme failed status after changed the use_stateless to false and send the commands sudo service magma@* stop and sudo service magma@magmad restart. Maybe loss configuration after restart.
[log_mme.txt](https://github.com/magma/magma/files/7377923/log_mme.txt)

**Comment by NeelimaKalpana** [comment]
Hi ,
Please find logs and pcaps with stateless enable and disable.

[Config_Stateless_9774 (2).zip](https://github.com/magma/magma/files/7381512/Config_Stateless_9774.2.zip)

**Comment by joary** [comment]
During a troubleshooting call this issue was solved by upgrading magma into the latest version: `1.7.0-1634668331-66d9b7be` and applying the following changes to the AGW:

1. Disabled stateless with: `sudo python3.8 magmad_cli.py config_stateless disable`
2. Add the following to the config files at `/var/opt/magma/configs`
- sessiond.yml    :=> enable5g_features: true
- mme.yml         :=>
  - enable5g_features: true;
  - default_slice_service_type: “1”
  - default_slice_differentiator: “0xd143a5"
- subscriberdb.yml :=> 
  - enable5g_features: True
- pipelined.yml   :=>
  - enable5g_features: True;
  - upf_node_identifier: 192.168.200.1

**Comment by lsguima** [comment]
Ok...The problem solved .
