### ISSUE TITLE
[AMF]: Re-aligning configuration read with the amf section in gatway.mconfig 

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9783]
As part of PR #9756 a new AMF section is added in gateway.mconfig for amf specific configuration. 
AMF configuration read section needs to re-align with the changes to reflect the configuration :

Older :
  --------------
   mme {
     "amfName": "AMF_1",
      "amfRegionId": "1",
      "amfSetId": "1",
      "amfPointer": "0",
  }

newer
  --------------
amf {
      "amfName": "AMF_1",
      "amfRegionId": "1",
      "amfSetId": "1",
      "amfPointer": "0",
}

**Comment by panyogesh** [comment]
[https://app.zenhub.com/files/170803235/09018e71-efb4-4117-b4d6-4afb0628a14c/download](https://app.zenhub.com/files/170803235/09018e71-efb4-4117-b4d6-4afb0628a14c/download)

**Comment by panyogesh** [comment]
Tentative changes in generate_oai file (https://app.zenhub.com/files/170803235/09018e71-efb4-4117-b4d6-4afb0628a14c/download). Need to check if mme.conf.template can be broken into two parts one for MME one for AMF. Or we can have something like amf.conf.template (like : spgw.conf.template)

**Comment by RahulKalsangra** [comment]
Changes and the issue observed. Have shared with orc8r team for further discussion.
