### ISSUE TITLE
Scale test: Idle mode support testcase is going to loop when more than 300 UEs tried at the rate of 10 attaches/sec

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#9784]
#Environment
Version:1.7.0-1634668331-66d9b7be
Affected Component:  Access Gateway
Affected Subcomponent:  AGW service
Deployment Environment: Vagrant (AGW)

#Describe the Issue
Scale test: Idle mode support testcase is going to loop when more than 300 UEs tried at the rate of 10 attaches/sec

**To Reproduce**
1 .In TVM-GUI go to testcase SA_TC7_UE_Idle_Mode_Support_Service_requist_proce
2. Change the rate to 10(That means triggering 10 UE request/attaches per second) .
3. Trigger the test case with 100,200,300UE  attaches.(For 100 UE's test case is passing)
4. Trigger the test case for More than 300 UE attaches.
 Error Noticed:
For 300 UEs testcase is working. But when we trigger more than 300 testcases, testcase going to loop and result is inconclusive.

**Expected behavior**
More than 300 UEs  should be served.

Note : With same testcase and environment, when tried up to 600 UE attaches with 1 UE/Sec all sessions are coming up.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60ff6822051e9582447f32aa/6b242b54-02db-47b7-9c3c-1660ad64b200)
please find the logs and pcaps below:
[https://app.zenhub.com/files/170803235/3bc8b7e1-8a7e-4321-a9e2-7cf5bf5c321a/download](https://app.zenhub.com/files/170803235/3bc8b7e1-8a7e-4321-a9e2-7cf5bf5c321a/download)
[https://app.zenhub.com/files/170803235/121e1b74-96bb-406e-9953-3a9b0955a4e5/download](https://app.zenhub.com/files/170803235/121e1b74-96bb-406e-9953-3a9b0955a4e5/download)

**Comment by panyogesh** [comment]
For now lets target 5 UE attaches/sec for 1.7. We will re-visit this for later release and open a new issue if problem is repeated.
