### ISSUE TITLE
NGSetupNoResp Alarm on GNB Nokia

### ISSUE THREAD

**Issue by lsguima** [magma/magma#9792]
- **Version: 1.7.0-1634668331-66d9b7be
- **Affected Component:Access Gateway, Gnb Nokia
- **Affected Subcomponent:AGW service - traffic
- **Deployment Environment: (AGW Virtual machine)

### Describe the Issue

Alarm of Base Station Connectivity Problem : NGSetupNoResp on GNB Nokia. In pcap file we received the information "protocol: transfer-syntax-error (0)".

![alarm_gnb](https://user-images.githubusercontent.com/83219702/138144873-e9b81f70-3e7f-4101-997e-498fa4f86632.png)
[test01-gNB.zip](https://github.com/magma/magma/files/7383284/test01-gNB.zip)

**Comment by joary** [comment]
Including here as well the test show-tech tool capture made during after the event:  https://transfer.sh/nINb6J/report.magma.2021-10-20T14:15:14Z.zip

cc @panyogesh

**Comment by joary** [comment]
It was tested Open5GS with UERANSIM(gnb and Ue simulator)  and then tested magma AMF also with UERANSIM.

In both the experiments we were able to bring up the PDU session. We're suspecting may be one of the value is not going well with GNB. There are 2 values of interest here
  1. amf_name : Default is set to "AMF_1"
  2. amf_pointer : Defaults to "0".
Can we change the Values of these variables. Here are the suggestions
   amf_name: "AMF1"
   amf_pointer: "1"
   
Both can be changed by having these parameters in /var/opt/magma/configs/mme.yml.

@lsguima , can we re-test with the values above?

**Comment by ekowtaylor** [comment]
cc @aswin-alexander

**Comment by joary** [comment]
@lsguima , Was this issue solved? can we close it?
