### ISSUE TITLE
[NMS][Alerts][v1.6.1] - High Mem Alert does not fire

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9799]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** v1.6
- **Affected Component:** NMS
- **Affected Subcomponent:** Alerts
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

High mem alert does not fire. Mem usage went up to over 90% today on the CBRS AGWs and there was no alert in the alert window. 

Based on the graph attached below, alert for high mem usage should have fired between 10/19 21:15 and 10/20 3:15. 

![image](https://user-images.githubusercontent.com/38921899/138186564-062c7ad5-ba6d-4659-8065-22c0ce15de82.png)

**Comment by aswin-alexander** [comment]
Triage update: This is high value.
cc @talkhasib

**Comment by sudhikan** [comment]
Okay tested with @andreilee using `stress-ng` and it seems we are triggering the alert. The issue is that from the moment the condition clears, the alert auto clears. 

Separate issue is to keep this alert for vis so the operator is able to take remedial actions for the future. 

Alert literally clears within seconds of the condition coming back to normal.

**Comment by aswin-alexander** [comment]
should this have showed up as a greyed out (or resolved) alert?
surely an operator would want to know something fired and then got cleared?

**Comment by sudhikan** [comment]
Totally yes. But that probably won't get resolved for current release.

**Comment by andreilee** [comment]
@aswin-alexander For sure, that would be ideal. With how Prometheus alerts works day, keeping a proper history of alerts that have fired isn't trivial, and can't be done through configuration. What can be done, but will also take a bit of time, is increasing the amount of time that it takes for alerts to clear.

**Comment by aswin-alexander** [comment]
Fully agree we don't need it for the current release.
Perhaps a forked/tweaked issue for our backlog 
wdyt @ekowtaylor ?
Sounds like we need a UXR task as a blocker?
What are the product requirements? @lpavao
