### ISSUE TITLE
[TeraVM 5G SA Regression] Downlink_NAS_Auth Request is not triggered by AGW - Error Sub_db Locked

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9809]
Scenario: 

1, UE SUCI based Reg is Successful and M-TMSI  Allocated.
2, [Issue] UE sends the GUTI based Reg and after Identity Req & Response there is no DL_Authentication_Request being triggered.
3, After 15 sec UE Retries GUTI Reg and its Successful.

Pcap and Logs Enclosed

[https://app.zenhub.com/files/170803235/90ae6588-5f3f-4a45-a1e9-c88b6db3561b/download](https://app.zenhub.com/files/170803235/90ae6588-5f3f-4a45-a1e9-c88b6db3561b/download)

MME jounalctl Logs
**Error:  Sub_db Database Table is locked**

![Screen Shot 2021-10-20 at 11.04.03 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/1f785ac2-b906-43ee-bd46-3963466b9fb1)

[ Pcap:  Please look for Time stamp  12:03:27 ]
![Screen Shot 2021-10-20 at 10.54.26 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/8c76b89e-db52-461e-b2e9-943365ede73c)

**Comment by ganeshg87** [comment]
Update:
   - Issue could not be reproducible in TeraVM setup
   - I don't find enough information to debug based on Syslog.
   - Please refer to the below PR, as per @ulaskozat  comment, DB lock cannot be avoided as we have multiple writers/readers to subscriber tables. 
 https://github.com/magma/magma/issues/6937
   - test case should have some time interval subsequent GUTI registration
cc: @arun-magma, @panyogesh 
Please share the below information if the same issue occurs
          mme log  and    syslog

**Comment by ganeshg87** [comment]
@arun-magma ,

Please find the task update

**Comment by arun-magma** [comment]
Currently this issue is not found, Are we concluding during Sub_db lock we can expect chances of Auth flow/any sub_db issues ?
