### ISSUE TITLE
Dependency cycle(?) witthin common_types, log, and itti

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#9817]
Another dependency cycle detected.

1. `common/log` depends on `lib/itti/intertask_interface`
2. `lib/itti/intertask_interface.h` needs `imsi64_t` to be defined. This is not explicitly defined in any of the files that it depends on (maybe there is an implicit dependency somewhere), but I see that it's defined in `common/common_types.h` (https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/common/common_types.h#L118). This makes `lib/itti/intertask_interface.h` dependent on `common/common_types.h` .
3. `common/common_types.h` declares a few helper functions that are defined in `common/common_types.c`
4. `common/common_types.c` depends on `common/log.h`

This is a light dependency cycle and there are probably a few ways to fix this
1. move the type definition of imsi64_t to some other file
2. `common/common_types.c` seems to implement some functions defined in `common/common_types.h`. We can split `common/common_types.h` into 2 files, one with only type definitions and one with helper function declarations. This way we avoid step 3/4 in the above section.

I don't like option 1 as basic types as `imsi64_t` would make sense to stay in a file called `common_types.h`. I would prefer option 2 as it separates pure type definitions that are used by many files from a few helper functions that are used by a few files.

![mme-dependency-cycle-imsi64-2](https://user-images.githubusercontent.com/37634144/138291949-12ffcb70-abd4-4636-a22f-0d5623da84ba.png)

**Comment by themarwhal** [comment]
Well, maybe I can just get around it by creating a library that consists of common_types.c only, but it might still be nice to split them into two files.

**Comment by ardzoht** [comment]
For option 2, would moving the helper functions to `conversions.h/.c` be sufficient? Since the helper functions seem to be anyways related with converting and deconverting structs that might be a better place to declare them and implement and breaks the cyclic dependency?

**Comment by themarwhal** [comment]
> For option 2, would moving the helper functions to `conversions.h/.c` be sufficient? Since the helper functions seem to be anyways related with converting and deconverting structs that might be a better place to declare them and implement and breaks the cyclic dependency?

@ardzoht yes that would work! as long as the types are separate from the functions, it should be good. Thanks for the pointer! :)
