### ISSUE TITLE
Building NMS Image - incorrect path (documentation)

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#982]
### Your Environment

- **Version:** v1
- **Affected Component:**  NMS
- **Affected Subcomponent:** building docker containers
- **Deployment Environment:** local docker-compose (orc8r)

### Describe the Issue
path to docker-compose file is incorrect on the documentation. Currently it points to magma/nms/fbcnms-projects/magmalte 

based on searching around this has moved to 
magma/symphony/app/fbcnms-projects/magmalte

**To Reproduce**
NA

**Expected behavior**
Update documentation

**Screenshots**
NA

**Additional context**
NA

**Comment by xjtian** [comment]
We made the path change on master but not the v1.0 branch - the documentation for master reflects the change (https://facebookincubator.github.io/magma/docs/next/orc8r/deploy_build)
