### ISSUE TITLE
1.5/1.6 NMS Policy Rule Creation With QoS Profile Fails partially

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#9820]
### Your Environment

- **Version:** 1.6
- **Affected Component:** Orchestrator, FeG, and NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** AWS (orc8r + FeG), bare-metal (AGW)

### Describe the Issue

When using a feg_lte with a feg_network, and creating a policy that includes a QoS profile, via the NMS, the policy fails to fully create and throws an error. This is due to policy rule in Feg network not allowing QoS profile element, where as the policy rule API in FeG_LTE network does. 

**To Reproduce**
1. Create a feg_lte network
2. Create a feg network
3. link the two
4. in Feg_lte network, create a rating group
5. in Feg_lte network, create a QoS Profile
6. in feg_lte network, create a policy rule and select the rating group and qos policy created above
7. press save
8. see 404 error (1.6) or "failed to create policy: one or more subscribers or QoS profiles do not exist" (1.5) error

**Expected behavior**
NMS should remove QoS profile when making the API call to FeG network to create the rule without it. 

This was point 1) in issue https://github.com/magma/magma/issues/7702

**Comment by jpad-freedomfi** [comment]
BTW, temp workaround for anyone else having this issue, create policy without QoS profile. Save everything. Go back and edit the rule to add QoS profile. you will see error, but feg_lte network rule will have been updated.

**Comment by andreilee** [comment]
Additional thread for reference: https://magmacore.slack.com/archives/C0191LLL03S/p1638889745340200

**Comment by jpad-freedomfi** [comment]
@Neudrino FYI this is still very much present in NMS. Please keep ticket open.
