### ISSUE TITLE
SUCI Registration TeraVM captured pcap file

### ISSUE THREAD

**Issue by Kaleem-Wavelabs** [magma/magma#9834]
Hi Arun,
Can you please share one pcap file for suci based registration TC.

Thanks and Regards,
Kaleem

**Comment by arun-magma** [comment]
Hi @Kaleem-Wavelabs @panyogesh : As discussed please find enclosed the pcaps
[https://app.zenhub.com/files/170803235/cf5bcae7-7dd7-4868-a759-0d134b407cc2/download](https://app.zenhub.com/files/170803235/cf5bcae7-7dd7-4868-a759-0d134b407cc2/download)

**Comment by arun-magma** [comment]
Pcap Enclosed, Closing this issue
