### ISSUE TITLE
MME better eng: Run IWYU on MME

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#9839]
## Repro steps (tested inside the devcontainer)
1. run make build_oai
2. while 1 is running install IWYU - https://include-what-you-use.org (checkout clang 11)
3. run `iwyu_tool.py -p /workspaces/magma/build/c/core/oai/compile_commands.json  /workspaces/magma/lte/gateway/c/core/oai` where -p points to the generated compile_commands.json from step 1. (`/workspaces/magma/build/c/core/oai/compile_commands.json`)
4. I filtered the output by running the following regex (`(?=The full include-list for \/workspaces\/magma\/lte)((.|\n)*?)(?=---)`

## IWYU result filtered as of Oct 22
[filtered-iwyu-output.txt](https://github.com/magma/magma/files/7398005/filtered-iwyu-output.txt)

**Comment by electronjoe** [comment]
Related: #4868

**Comment by electronjoe** [comment]
Just a note that iwyu is already installed in our devcontainer (from my prior work here) so I think step 2 isn't necessary if you specify that environment?
