### ISSUE TITLE
[pipelined]: User Plane Scalability benchmarking 

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9851]
[pipelined]: User Plane Scalability benchmarking

**Comment by pratibhag1234** [comment]
Topology

![image.png](https://images.zenhubusercontent.com/615bd90ec862be7dece5262e/0a1f4d73-caf3-4c2e-a308-9ab8fab619f2)

Following are the logs below:

![MicrosoftTeams-image (6).png](https://images.zenhubusercontent.com/615bd90ec862be7dece5262e/bfaae16c-8bbc-4080-b030-cc5b3dac8088)

![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/615bd90ec862be7dece5262e/addeddad-2d39-4713-81a6-9e01b5b2fcfb)

![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/615bd90ec862be7dece5262e/344a8cc9-09a3-401d-9008-d9c45e64a279)

![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/615bd90ec862be7dece5262e/71a8736a-7c2c-4778-b7ba-080ab6c50521)

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/615bd90ec862be7dece5262e/f24a0a87-7185-448a-9820-30668998c123)
