### ISSUE TITLE
[AGW]:[Testing]:Magma 5G- Scale testing.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#9854]
1.Performing Scale testing up to 600 UE's , with 1UE/Sec and 10UE's/Sec. Try to increment number of UE's step by step till reaching 600 UE's.
2. Monitoring the CPU and Memory usage when testing for 600 UE's.

Note: Please find the attachment for the Test scenarios and results.

https://wavelabstechnologies-my.sharepoint.com/:x:/g/personal/neelima_kalpana_wavelabs_ai/ESIYWnphsJdBlDa4QwUOWW8BJJ7bwwN6QYrS41mTzsxUKA?e=esWY31

**Comment by Kaleem-Wavelabs** [comment]
@rupa455wavelabs Can you please check the validity of this TC to process. Thanks.

**Comment by rupa455wavelabs** [comment]
sure kaleem, I will update you.

**Comment by rupa455wavelabs** [comment]
Need to test in TVM with latest magma build and update it.

**Comment by NeelimaKalpana** [comment]
@Apeksha , Please test this in Spirent setup and close it if issue is not Observed
