### ISSUE TITLE
[AMF]: amf is crashing while sending ContextSetupRequest for the ServiceRequest received from UE.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#9862]
[https://app.zenhub.com/files/170803235/5d0c2b71-b1cb-403c-9b41-f113e1c7167b/download](https://app.zenhub.com/files/170803235/5d0c2b71-b1cb-403c-9b41-f113e1c7167b/download)- 

Version:magma/focal-ci,now 1.7.0-1635105260-8be0ef7e
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: AWS (orc8r),

### Describe the Issue
[AMF]: amf is crashing while sending ContextSetupRequest for the ServiceRequest received from UE.

**To Reproduce**
1. Make sure the services are up and NGAP and SCTP conncetion is UP.
2. Try to execute the test case "SA_TC4c_DeRegistration_cause_as_Switchoff_after_idle_to_Active_mode"
3. Check for the pcaps.
4. Error: AMF is not sending the InitialContextSetupRequest message after receiving ServiceRequest from UE. 

**Expected behavior**
AMF should send the InitialContextSetupRequest for the ServiceRequest Received from UE .

**Additional context**
syslog:
magma@TVM3-SA:~$ sudo tail -f /var/log/syslog | grep mme
Oct 25 04:53:05 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:10 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:15 TVM3-SA magmad[734638]: ERROR:root:GetServiceInfo Error for mme! [StatusCode.DEADLINE_EXCEEDED] Deadline Exceeded
Oct 25 04:53:15 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:20 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:26 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:26 TVM3-SA mme[890513]: sigwait: Interrupted system call
Oct 25 04:53:26 TVM3-SA mme[890513]: Caught signal SIGPIPE 13
Oct 25 04:53:26 TVM3-SA mme[890513]: Connection error: Broken pipe
Oct 25 04:53:29 TVM3-SA kernel: [2862381.752176] TASK_AMF_APP[893102]: segfault at b0 ip 0000556a96b39ec2 sp 00007f8989f9e0a0 error 4 in mme[556a9692c000+85d000]
Oct 25 04:53:40 TVM3-SA magmad[734638]: ERROR:root:GetOperationalStates Error for mme! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:53:40 TVM3-SA magmad[734638]: ERROR:root:GetServiceInfo Error for mme! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:53:40 TVM3-SA systemd[1]: magma@mme.service: Main process exited, code=killed, status=11/SEGV
Oct 25 04:53:40 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:40 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:40 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:43 TVM3-SA systemd[1]: magma@mme.service: Failed with result 'signal'.
Oct 25 04:53:45 TVM3-SA magmad[734638]: ERROR:root:GetServiceInfo Error for mme! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:53:45 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:48 TVM3-SA systemd[1]: magma@mme.service: Scheduled restart job, restart counter is at 4.
Oct 25 04:53:51 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:55 TVM3-SA magmad[734638]: ERROR:root:GetServiceInfo Error for mme! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:53:56 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:53:59 TVM3-SA magmad[734638]: ERROR:root:Metrics upload error for service mme (chunk 0)! [StatusCode.UNAVAILABLE] Received http2 header with status: 502
Oct 25 04:54:01 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:54:01 TVM3-SA magmad[734638]: WARNING:root:Collect mme Error! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:54:06 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:54:06 TVM3-SA magmad[734638]: ERROR:root:GetServiceInfo Error for mme! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:54:11 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:54:16 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:54:16 TVM3-SA magmad[734638]: ERROR:root:GetServiceInfo Error for mme! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Oct 25 04:54:21 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: enable_nat
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: congestion_control_enabled
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: default_slice_service_type
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: default_slice_differentiator
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: amf_name
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: amf_region_id
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: amf_set_id
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for mme, key not found: amf_pointer
Oct 25 04:54:24 TVM3-SA mme[927942]: ERROR:root:Error retrieving config for spgw, key not found: ovs_internal_sampling_fwd_tbl
Oct 25 04:54:24 TVM3-SA mme[927942]: WARNING:root:Service (spgw) missing in mconfig
Oct 25 04:54:26 TVM3-SA smsd[734811]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.

**Comment by NeelimaKalpana** [comment]
[https://app.zenhub.com/files/170803235/0b710784-9806-41d8-b7e5-eb5b28b9b426/download](https://app.zenhub.com/files/170803235/0b710784-9806-41d8-b7e5-eb5b28b9b426/download)

**Comment by NeelimaKalpana** [comment]
bt analysis for crash :

#0  0x0000559e0ec30ade in magma5g::amf_as_establish_cnf (msg=0x7fded32cbef8, as_msg=0x7fded32cbcd8)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:1375
#1  0x0000559e0ec2da06 in magma5g::amf_as_send_ng (msg=0x7fded32cbe78)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:257
#2  0x0000559e0ec2ccf1 in magma5g::amf_as_send (msg=0x7fded32cbe78)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:91
#3  0x0000559e0ec06bbf in magma5g::amf_sap_send (msg=0x7fded32cbe40)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_sap.cpp:58
#4  0x0000559e0ec0dc83 in magma5g::amf_handle_service_request (ue_id=319, msg=0x7fded32dc110, decode_status=...)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp:127
#5  0x0000559e0ec2d3f0 in magma5g::amf_as_establish_req (msg=0x7fded32ec2e8, amf_cause=0x7fded32ec19c)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:183
#6  0x0000559e0ec2ccce in magma5g::amf_as_send (msg=0x7fded32ec268)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:86
#7  0x0000559e0ec06bbf in magma5g::amf_sap_send (msg=0x7fded32ec230)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_sap.cpp:58
#8  0x0000559e0ec07172 in magma5g::nas_proc_establish_ind (ue_id=319, is_mm_ctx_new=true, originating_tai=...,
    ecgi=..., as_cause=M5G_MO_SIGNALLING, s_tmsi=..., msg=0x60200011abf0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp:61
#9  0x0000559e0ebf6914 in magma5g::amf_app_handle_initial_ue_message (amf_app_desc_p=0x606000037580,
    initial_pP=0x60e00008ac60) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:519
#10 0x0000559e0ebe0837 in magma5g::handle_message (loop=0x60b000030030, reader=0x60600004c0a0, arg=0x0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp:70
#11 0x00007fdee461d5c7 in zloop_start () from /lib/x86_64-linux-gnu/libczmq.so.4
#12 0x0000559e0ebe0d1b in magma5g::amf_app_thread (args=0x0)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp:171
#13 0x00007fdee51b4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007fdee34e1293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) p state
$1 = magma5g::REGISTERED_IDLE
(gdb) p registration_proc
$2 = (magma5g::nas_amf_registration_proc_t *) 0x0
(gdb)

**Comment by panyogesh** [comment]
Closing the PR as not seen in latest builds.
