### ISSUE TITLE
Requesting for Qos testcase list automated in 4G/5G.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#9875]
Please give the list of all testcases and test scripts that are available for Qos-Feature in TeraVM.

**Comment by arun-magma** [comment]
Hi Shanjana, We reviewed QOS test cases need, At the moment evaluation of AMBR enforcement & check throught Throttling is the need , for this test case we can make use of below TeraVM Throughput scripts, manual Mode of execution is currently feasible as S-AMBR & live UP Throughput cross validation is not feasible in TeraVM Veridct calculations.

[Throughput scripts]
SA_TC51_Scale_mbps_udp
SA_TC52_Scale_mbps_tcp

**Comment by NeelimaKalpana** [comment]
Hi Arun, Thank you for the inputs.

**Comment by NeelimaKalpana** [comment]
Hi Arun & Ankur,

For Qos feature support in 5G can we add testcases for static Qos configuration .

**Comment by arun-magma** [comment]
I believe we can test only with static QOS config (Default AMBR) from orc8r policy db & hence above comments are for static, I assume dynamic is not possible until Magma supports full fledged PCF support, let us know if you have diff logics for static & dynamic ?
