### ISSUE TITLE
bazel: Bazelify Python

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#9878]
## Objectives

Mamga is interested in migrating all languages towards Bazel build and test infrastructure (See #8338 and #11293). For python, the objective is to not only build and test as driven by Bazel, but also to migrate to some more self contained Python packaging. Bazel offers different options, e.g. [Python binaries](https://github.com/bazelbuild/rules_python). The goal is to remove environmental dependencies from Python execution, so that the Bazel built artifact is more self-contained. It remains questionable if self-sufficiency is totally achievable, due to usage of system dependencies (e.g. kernel modules for Berkeley Package Filter (BPF)). Regardless, wrapping all python language dependencies per target into one build artifact would be progress and the broader Bazel migration holds benefits across languages.

## Python services

- [x] #11413 
- [x] #11484
- [x] #11723
- [x] #11301
- [x] #11724
- [x] #11725
- [x] #11284
- [x] #9881
- [x] #11657
- [x] #11726
- [x] #11727
- [x] #11356
- [x] #11302
- [x] #11728
- [x]  #11729
- [x] #11505

## Other migration efforts

- [x] #12295
- [x] #12287
- [x] bazel: Bazelify Python tests (integration, load, ...)
- [x] bazel: Generate Bazel files for Python with Gazelle - not feasible with current gazelle python support
- [x] bazel: Collect and check licenses of external dependencies - out of scope for now
- [x] bazel: Migrate linter tests (pylint_tests.py) - make approach maybe not compatible with Bazel philosophy - bazel is not suited for doing this (all sources need to be dependencies of linter targets)
- [x] #11614

## Environment

See [Magma's experimental bazel documentation](https://github.com/magma/magma/tree/master/experimental/bazel-base).

This effort can be prototyped in the devcontainer.  Final PR testing will need to occur in additional environments (e.g. Magma VMs).  You can enter the devcontainer environment by either:

- Opening a GH Code Space on your Magma fork
- Opening a GitPod development environment on your Magma fork
- Locally installing VS Code + the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) plugin
  - Open the Magma repo directory with VS Code and hit `F1`, search for `Remote-Containers: Rebuild Container`
  - This will build / load the repo in the devcontainer locally

Example workflow:

- Modify some BUILD.bazel files in various python directories

```bash
bazel build //lte/gateway/python/magma/mobilityd:main
./bazel-bin/lte/gateway/python/magma/mobilityd/main
```

You can explore the bazel output directory structure e.g.

```
ls /workspaces/magma/./bazel-bin/lte/gateway/python/magma/mobilityd/main.runfiles/__main__/lte/protos/
```

Notes regarding the python interpreter for bazel: https://github.com/magma/magma/issues/11346

## Bazel Formatting

From the devcontainer: `bazel run //:buildifier`

## Early prototyping Findings

See my (@electronjoe ) incomplete PR #9900 - which demonstrates substantial progress towards Bazel success (but the methods applied were not exhaustively completed).
Prototype includes:

- Pip usage by Bazel
- Import path fixups of various python
- Protobuf and grpc imports / proto compilation for python / use in BUILD.bazel files

The early prototype has a successor in PR #10341, which demonstrates a working example for the mobilityd build.

**Comment by Neudrino** [comment]
> The details and value add of PAR generation is yet to be proven

:x: **PAR** has several issues and did not withstand a evaluation. 
The following issues were found:
* The package seems to be unmaintained with the [last commit in 2019](https://github.com/google/subpar/commits/master).
* A python interpreter cannot be bundled ([google/subpar#131](https://github.com/google/subpar/issues/131)).
* The package has issues with Ubuntu >= 20.04 ([google/subpar#133](https://github.com/google/subpar/issues/133)).

For a more elaborate explanation also see https://github.com/magma/magma/pull/10341#discussion_r757551452.

For packaging docker files might be considered as an alternative, as it is much easier to provide hermetic environments with them. Especially https://github.com/magma/magma/issues/10498 would build a very convenient basis for it. Some more details can be found in https://github.com/magma/magma/pull/10341#discussion_r758300587.

However, mind, that I still think the docker migration of the product components is a distinct topic and should not be mixed with Bazel topic!

**Comment by nstng** [comment]
@electronjoe 
Couple points/questions to the list of services above:
* nitpicking enodeb -> enodebd
* from the orc8r services only magmad is listed - by design?
	* missing are ctraced, eventd, directoryd, state
* kernsnoopd - first glance: I do not see any usage (call of main or import in other modules)
* maybe off-topic, but out of curiosity
  * not all modules seem to be called in systemd service files - what is the pattern here?
  * monitord has a systemd service template in the repo but the service is not in the vm-setup
  
Are you fine with me editing your initial comment for tracking the migration progress or would you prefer a separate issue?

**Comment by nstng** [comment]
all sub-tasks done
