### ISSUE TITLE
TeraVM scripts readiness for SUCI Registration testing

### ISSUE THREAD

**Issue by Kaleem-Wavelabs** [magma/magma#9880]

**Comment by arun-magma** [comment]
Two test cases added for SUCI encryptions
SA_TC1x_UE_Registration___SUCI_Encryption_with_Profile_A
SA_TC1y_UE_Registration___SUCI_Encryption_with_Profile_B

**Comment by arun-magma** [comment]
Scrpts are ready to use, closing it for now, incase any info needed please reopen with the Question.
