### ISSUE TITLE
5G SA Regression |. TC4c Fails as no response for service Request

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9905]
Scenario: 

1, SUCI Registration Sucessful
2, UE goes to idle Mode
3, UE sends Service Request
4, [Issue] AGW not responding Service Accept & Core Dump observed (Enclosed).
5, Subsequently found a crash (SCTP broken with Aborts)

Tested build: (Failing for last 4 days)
1.7.0-1635176801-701d9996

TeraVM TC ID:
SA_TC4c_DeRegistration_cause_as_Switchoff_after_idle_to_Active_mode

Snap of pcap

![Screen Shot 2021-10-26 at 2.03.55 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/6adb4296-b3e9-49f6-bc95-421ee1010f89)

Core Dump snap
![Screen Shot 2021-10-26 at 8.33.13 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/e64c62a9-189a-4d52-9399-e1638ecb4585)

[https://app.zenhub.com/files/170803235/8c088f24-cc21-43cf-87d3-3927b3fc3364/download](https://app.zenhub.com/files/170803235/8c088f24-cc21-43cf-87d3-3927b3fc3364/download)

[https://app.zenhub.com/files/170803235/0b5b0977-b084-422b-82aa-aef8a8a94fe4/download](https://app.zenhub.com/files/170803235/0b5b0977-b084-422b-82aa-aef8a8a94fe4/download)

**Comment by panyogesh** [comment]
Fixed as part of #9956. Passed on build : 1.7.0-1635443057-66fc3fce (Oct-28)
