### ISSUE TITLE
Problem during attach - CPE with GNB Nokia - Magma 1.7

### ISSUE THREAD

**Issue by lsguima** [magma/magma#9939]
- **Version:1.7.0-1634668331-66d9b7be
- **Affected Component: Access Gateway
- **Affected Subcomponent: AGW service
- **Deployment Environment: VM (AGW)

### Describe the problem

**Description**
We tried to connect one CPE with the GNB Nokia - AGW, but the attach process failure.We collected the trace during the tentative.
Test number: IMSI724770000000810 / APN: internet

**Additional context**
![image](https://user-images.githubusercontent.com/83219702/139175781-214a8069-07c9-46df-9b25-8ce8e5c21a0c.png)
[mme.log](https://github.com/magma/magma/files/7430593/mme.log)
[attach_fail_logs.zip](https://github.com/magma/magma/files/7430605/attach_fail_logs.zip)

**Desired timelines**
Share any information about timeline expectations.

**Comment by panyogesh** [comment]
Review request raised : #9979
