### ISSUE TITLE
[AMF]: Executing the failed, in-scope testcases of P0, P1 and P2 on TVM setup

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9940]
Attaching the list of cases. Kindly check the same. [https://app.zenhub.com/files/170803235/ab6dd2d8-5add-4800-a720-ff07b99dcd32/download](https://app.zenhub.com/files/170803235/ab6dd2d8-5add-4800-a720-ff07b99dcd32/download)

Kindly execute the cases and mark their status on latest build of OCT-28

**Comment by shanjanaWL** [comment]
I have executed all p0 and p1 testcases which is shared by Yogesh. All p0 and p1 testcases are passing except TC7e and TC7f. There is no crash generated. Please find the failure testcases logs and pcaps below
[SA_TC7f_Verify_Service_Reject_when_wrong_TMSI_is_used_in_Service_Request_211028_014226-1.zip](https://github.com/magma/magma/files/7433095/SA_TC7f_Verify_Service_Reject_when_wrong_TMSI_is_used_in_Service_Request_211028_014226-1.zip)
[sys_oct28_TC7f.zip](https://github.com/magma/magma/files/7433097/sys_oct28_TC7f.zip)
![image](https://user-images.githubusercontent.com/86910517/139235567-b86dd9a2-0845-4dab-9596-01a340e7d1ae.png)
