### ISSUE TITLE
[lte][agw] Make sctpd service logging level configurable

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#9943]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** sctpd
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

- Currently, sctpd service logging level is set and hardcoded to DEBUG level.
- We should add support to make this level configurable, from service config file. (Create `magma/lte/gateway/configs/sctpd.yml` and make the sctpd service read from it)

References:
- https://github.com/magma/magma/blob/master/lte/gateway/c/sctpd/src/sctpd.cpp#L82

**Comment by themarwhal** [comment]
Done with https://github.com/magma/magma/pull/10904
