### ISSUE TITLE
Requesting for N7 interface support for PCF testcase list automated in 5G.

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9952]
Requesting for N7 interface support for PCF testcase list automated in 5G.

Proposal document link : https://docs.google.com/document/d/18umXHz4OBNh2XhNqEfa6G3ObBJ1nC2M1aMWtZS-jkGE/edit#heading=h.e21fdx6mrmgn

Code will be available in master by 08-November-2021.Target date for end-to -end testing is 15-November-2021

**Comment by arun-magma** [comment]
Inclusion of PCF N7 interface in progress, Can we get the ETA for feg readiness to integrate the REST HTTPv2 integration and testing ?

**Comment by GANESH-WAVELABS** [comment]
@arun-magma 
we are trying to make FEG ready for this N7 interface by 15-Nov-2021.

**Comment by arun-magma** [comment]
Its a 2 step process , please let us know when feg is ready we can start the integration efforts & design the default policy and reauth trigger policy needs.

PCF Integ
Step-1
N7 only for now (N15 for subscription flow ?)
Rest HTTPv2 (8080) interworking data to be provided
Default Policy info need to be planned

Step-2
Network initiated Sess modify

**Comment by arun-magma** [comment]
May I know ETA for code readiness ?

**Comment by arun-magma** [comment]
PCF function is available in TeraVM to integrate, Once the feg service is ready we can have working session to complete N7 integration efforts, let us know, thanks!
