### ISSUE TITLE
Requesting for PCF/network initiated session modification testcase list automated in 5G.

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9957]
Requesting for PCF/network initiated session modification testcase list automated in 5G.

Proposal document link : https://docs.google.com/document/d/18umXHz4OBNh2XhNqEfa6G3ObBJ1nC2M1aMWtZS-jkGE/edit#heading=h.e21fdx6mrmgn

Code will be available in master by 08-November-2021.Target date for end-to -end testing is 15-November-2021

**Comment by arun-magma** [comment]
Dependency on below ZH issue i.e PCF Integration and baseline test
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/9952

**Comment by NeelimaKalpana** [comment]
Scenarios to be automated for PCF and Network Initiated Session Modification. 

Scenario1 : Static Policy creation from orc8 without PCF.
Step1: Try to create a static policy from orc8 .
Step2: Apply the policy on the Subscriber.
Step3: Trigger the PDU-Session.Check the 5G policy is taken from local PolicyDB.
Step4: Try to modify the Policy info from the orc8.
Expectation: Check that PDU-Session shouldnot get updated.
Step5: Try to delete the static policy and add new policy from the orc8.
Expectation: Check that PDU-Session shouldnot get updated.
Step6: Try to remove the policy associted with session when session is UP.
Expectation: Check that PDU-Session shouldnot get impacted.
Step Trigger PDU-Release and De-Registration.

Scenario2 : Static Policy creation from orc8 with PCF.
Step1: Try to create a static policy from orc8 .
Step2: Apply the policy on the Subscriber.
Step3: Trigger the PDU-Session.Check the 5G policy is taken from local PolicyDB.
Step4: Try to modify the Policy info from the orc8.
Expectation: Check that LocalSession manager will send the update to SessionD via policydb to Update the policies 
             associated with PDU Session.Check that PDU session should get updated with new policy.
Step5: Try to delete the static policy and add new policy from the orc8.
Expectation: Check that PDU session should get updated with new policy.
Step6: Try to remove the policy associted with session when session is UP.
Expectation: Check that  PDU session is getting UPdated with 

Scenario3 : Dynamic Policy with PCF.
Step1: Trigger the PDU-Session .
Step2: Check that AMF is sending SessionCotext to PCF via FEG.
Step3: PCF is Responding back with the proposed policy info for a given subscriber via FEG==>orc8==>Sessiond
Step4: Check that PDU-Session is coming up as per the Policies proposed by PCF.
Ste5: Check that PDU-Session update is triggered from sessiond for any change in the policy(update of Qos-profile info)
Expectation: PDU-Session should get updated accordingly and the same thing should me notified to AMF by SMF.
Step5:Trigger the PDU-Session termination from SMF
Expectation: PCF should Terminate the session as per Request.

Scenario4 : Dynamic Policy with PCF.
Step1: Trigger the PDU-Session .
Step2: Check that AMF is sending SessionCotext to PCF via FEG.
Step3: PCF is Responding back with the proposed policy info for a given subscriber via FEG==>orc8==>Sessiond
Step4: Check that PDU-Session is coming up as per the Policies proposed by PCF.
Ste5: Check that PDU-Session update is triggered from PCF using PolicyReAuth message.
Expectation: PDU-Session should get updated accordingly, sessiond should propagate the rules to policydb
             and the same thing should me notified to AMF setSMSessionCotext message and send a policyReAuthResponce to PCF.
Step5:Trigger the PDU-Session termination from PCF
Expectation: PDU-Session should get Terminated.

Scenario5 : Dynamic Policy without PCF.
Step1: Try to configure the Policies from orc8 and attach the policy to subscriber.
Step2: Check that PDU-Session is coming up with the configured policy.
Step3: Try to modify the policy info and check that policy is getting updated in the sessiond and 
       Sessiond has to propagate the updated policies to policydb and pipelindb
Step4: Check that PDU-Session is geting modified with the new policyInfo.
Expectation: PDU-Session should get updated accordingly, sessiond should propagate the rules to policydb
             and the same thing should me notified to AMF setSMSessionCotext message and send a policyReAuthResponce to PCF.
Step5:Trigger the PDU-Session termination.
Expectation: PDU-Session should get Terminated.

**Comment by GANESH-WAVELABS** [comment]
> Scenario2 : Static Policy creation from orc8 with PCF.

The description is not clear. It should mention that the static policy is applied from the PCF as a response to the Npcf_SMPolicyCreate request. Similarly there deletion of a static policy can be performed using a Npcf_SmPolicyUpdateNotification message from the PCF.

> Scenario5 : Dynamic Policy without PCF.

Dynamic policies without PCF - this is not supported currently

> Ste5: Check that PDU-Session update is triggered from PCF using PolicyReAuth message.

There is no  PolicyReAuth message in N7 interface. This will be a Npcf_SMPolicyUpdateNotification message from PCF.

More scenarios that can be added
 - Can add a scenario with both static and dynamic policy rules
 - A scenario to trigger usage monitoring and see if the usage monitoring data is reported to PCF periodically
 - A scenario to set/change revalidation time, so that a Policy Update is trigger to PCF after the expiry of revalidation time
 - A scenario to terminate session from PCF.
