### ISSUE TITLE
Requesting for dynamic policy changes without PCF testcase list automated in 5G.

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9958]
Requesting for dynamic policy changes without PCF testcase list automated in 5G.

Proposal document link : https://docs.google.com/document/d/18umXHz4OBNh2XhNqEfa6G3ObBJ1nC2M1aMWtZS-jkGE/edit#heading=h.e21fdx6mrmgn

Code will be available in master by 08-November-2021.Target date for end-to -end testing is 15-November-2021

**Comment by arun-magma** [comment]
kindly let us know how would be the initial Static policy mapping and the changes intended to trigger a internal Re_Auth to get the Sess_modifcations ? , Will the configs get pulled from existing policy config in orc8r or how do we config it for initial phase of testing ?

**Comment by arun-magma** [comment]
There are test cases AMF initiated Session Modification (TC-10) and Termination (TC-11) , Can we get a idea if AMF /SMF Initiated  would be triggered from PCF or through Internal (orc8r) method, provide a clarity of it to keep above two test cases in active state if it can be clubbed i would remove it saying duplicate, Thanks
