### ISSUE TITLE
Design proposal for IPv6 PDU session support for UE

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#9959]
Design proposal for IPv6 PDU session support for UE

**Comment by GANESH-WAVELABS** [comment]
design doc can be found in the google doc : https://docs.google.com/document/d/1yE862ImntChYpkLSDoSwXVB0yvtYCfl3wbP42VRH3w8/edit#

**Comment by hcgatewood** [comment]
Hi @GANESH-WAVELABS, thanks for opening this design doc. I'm going to remove the `proposal` label if that works for you, as it's a mostly single-component design that can go directly to the relevant tech lead (@pshelar)

Let me know if you'd like me to take a look though!

**Comment by GANESH-WAVELABS** [comment]
> Hi @GANESH-WAVELABS, thanks for opening this design doc. I'm going to remove the `proposal` label if that works for you, as it's a mostly single-component design that can go directly to the relevant tech lead (@pshelar)
> 
> Let me know if you'd like me to take a look though!

Hi @hcgatewood Please go ahead and remove the flag "proposal".

**Comment by GANESH-WAVELABS** [comment]
[07-Dec-2021 : Ganesh . I ] :  sessiond PR (#10539), pipelined PR (#10346) has been merged into master, so proposal is closing as it got approved via code chagnes.
