### ISSUE TITLE
[AMF]: Set of operations to enable 5g flags in master

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9962]
1.
Disable the stateless feature :
    cd magma/orc8r/gateway/python/scripts/
    magtivate
   magmad_cli.py config_stateless disable

2.
Right now by default 5G feature flags are disabled. Enable via orc8r or put the following flags in /var/opt/magma/configs/

sessiond.yml    :=> enable5g_features: true
 mme.yml         :=> enable5g_features: true
 subscriberdb.yml :=> enable5g_features: True
 pipelined.yml   :=> enable5g_features: True

3.
If for any specific case we need to disable the flag please update one of the yml files in " /var/opt/magma/configs/"

4. 
After changing of yml files magma service restart is required.

**Comment by GANESH-WAVELABS** [comment]
Need to set the `periodic_stats_reporting` flag  to `false` and it should be nested flag under `enforcement` as shown in the attached image. It should not be an individual flag. Also it should be updated in overridden configuration file `/var/opt/magma/configs/pipelined.yml`.
![image](https://user-images.githubusercontent.com/70899516/139700198-7f6dcef2-dbbf-4c40-97e4-9085d67ebcb6.png)
