### ISSUE TITLE
Scale test: paging testcase is going to loop with more than 200UEs(1UE/sec)

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#9971]
### Your Environment
Version:1.7.0-1635476162-d07bb9da
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment:  Vagrant (AGW)

### Describe the Issue
Scale test: paging testcase is going to loop more than 200UEs tried with rate of 1 UE/sec

To Reproduce:
1. In TVM-GUI go to testcase SA_TC9_AMF_Initiated_Paging.
2. Execute testcase by increasing the number of UEs step by step(100,200,....)

Error Noticed:
 For 200UEs testcase is working. But when we trigger more than 200 UEs, testcase going to loop and result is inconclusive.
Expected behavior:
More than 200 UEs should be served upto 600UEs.

please find the logs and pcaps below:

[https://app.zenhub.com/files/170803235/6d663e1f-dd9a-4000-aa23-42d95e3cdf97/download](https://app.zenhub.com/files/170803235/6d663e1f-dd9a-4000-aa23-42d95e3cdf97/download)
[https://app.zenhub.com/files/170803235/a070f5ef-a2d4-4c71-aa02-7c5835a1893a/download](https://app.zenhub.com/files/170803235/a070f5ef-a2d4-4c71-aa02-7c5835a1893a/download)
![image.png](https://images.zenhubusercontent.com/60ff6822051e9582447f32aa/39887ecc-4a18-4be9-a549-6f70d1611b21)

**Comment by rupa455wavelabs** [comment]
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment]
Hi @all, I re-tested the paging scenario(200UE, 1ue/s) with latest magma build, Test is passing without any issues.

When I triggered the same scenario with 5 ue/s attach rate I am observing a slight drop in ul/dl traffic, Please check the below logs for the same.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/6ca230b4-9357-4323-aae7-6ba67d037d97)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/92232ee0-92f6-4100-8d37-b428db5e9a7f)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/1098ffd2-b208-497f-a7f6-5421619ec304)

**Comment by rupa455wavelabs** [comment]
[https://app.zenhub.com/files/170803235/16ae0755-7a64-4c81-9401-80f5fc65990a/download](https://app.zenhub.com/files/170803235/16ae0755-7a64-4c81-9401-80f5fc65990a/download)
