### ISSUE TITLE
[Subscriberdb]: Proto Changes in subscriberdb to support configuration of suci profiles

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#9996]
This is part of the Main Task #9779. As part of this activity following tasks needs to be done :
1. Adding a CLI which can help User to get Private and Public Key
2. Have a CLI which can be used to create the profile in SubscriberDB
3. Define a Proto File for above mentioned point.
4. Write the pull based approach to periodically fetch the profile from orc8r.
5. Unit testing for all cases.

**Comment by rupa455wavelabs** [comment]
https://github.com/magma/magma/pull/10512 PR got merged. Closing the issue
